#!/usr/bin/env python3
"""Written one-line takeaways for Acts.

Each states what the verse turns on. Narrative verses carrying no standalone
point — itinerary notes, name lists, bare connectives, the lead-in half of a
quotation — are left out deliberately; the drawer hides the card rather than
showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"All that Jesus began both to do and teach\" — the Gospel was the beginning, and this book is the continuing.",
    '1:2': "The commandments are given through the Holy Ghost. The Spirit is already at work before Pentecost arrives.",
    '1:3': "\"Many infallible proofs.\" Luke stakes the whole account on evidence rather than on impression.",
    '1:4': "The first thing the church is commanded to do is nothing: wait for the promise of the Father.",
    '1:5': "Water baptism is set beside Spirit baptism, and what John pointed toward is now days away.",
    '1:6': "The last question before Pentecost is still the old one about Israel's borders and Israel's throne.",
    '1:7': "\"It is not for you to know the times.\" Curiosity about the calendar is answered with a flat refusal.",
    '1:8': "Witness, not restoration, is the assignment — and the geography in this verse is the outline of the book.",
    '1:9': "A cloud receives him. The ascension is told as a departure to somewhere, not a vanishing.",
    '1:11': "\"Why stand ye gazing up into heaven?\" The church is turned from the sky back toward the work.",
    '1:14': "One accord in prayer, with the women and with Mary named among them rather than around the edges.",
    '1:15': "About a hundred and twenty. Luke gives the number small so the later ones cannot be explained by momentum.",
    '1:16': "Peter reads Judas as scripture already spoken. Even the betrayal fell inside the word, not outside it.",
    '1:17': "\"He was numbered with us.\" Proximity to Jesus and a share in the ministry saved no one by themselves.",
    '1:18': "Luke records the field and the bowels without a word of moral commentary. The facts are left standing.",
    '1:20': "The Psalms supply the warrant: an office outlives the man who abandons it.",
    '1:21': "The qualification is having been there — companied with them the whole time, not merely convinced of it.",
    '1:22': "\"A witness with us of his resurrection.\" The apostolic job description is testimony to one event.",
    '1:24': "\"Thou, Lord, which knowest the hearts.\" They narrowed it to two; they did not claim to do the choosing.",
    '1:25': "\"That he might go to his own place\" — Luke's restraint about Judas is more terrible than a verdict.",
    '1:26': "The lot falls on Matthias, and after the Spirit comes the church never casts lots again.",

    # ---- Chapter 2 ----
    '2:1': "They are together in one place because they obeyed the command to wait. The Spirit comes to people already gathered.",
    '2:2': "The sound comes from heaven and fills the house. Nothing in this is worked up from below.",
    '2:3': "The fire divides and sits on each of them. The gift is corporate and individual in the same moment.",
    '2:4': "They speak \"as the Spirit gave them utterance.\" Even the words are received rather than produced.",
    '2:5': "Devout Jews from every nation under heaven are already in the city. The audience was assembled before the sign.",
    '2:6': "Every man hears in his own language. The miracle lands in the hearing as much as in the speaking.",
    '2:7': "\"Are not all these which speak Galilaeans?\" The obscurity of the speakers is part of the evidence.",
    '2:11': "The content of the tongues is \"the wonderful works of God\" — not private ecstasy but public praise.",
    '2:12': "\"What meaneth this?\" A sign can raise the question; only preaching can answer it.",
    '2:13': "Mockery remains a live option in front of the very same evidence.",
    '2:14': "Peter, who denied Christ to a servant girl, now stands up and takes the questioning of a city.",
    '2:15': "The rebuttal is mundane — it is nine in the morning. Peter does not defend the miracle, he dates it.",
    '2:16': "\"This is that.\" Peter explains the unprecedented by the long-written, not the other way round.",
    '2:17': "\"Upon all flesh\" — sons and daughters, young and old. What had been given to a few prophets is now poured out.",
    '2:18': "Servants and handmaidens prophesy. The lowest rank in the household is named explicitly in the promise.",
    '2:19': "Joel's blood and fire and smoke are quoted as begun, not postponed. The last days start at Pentecost.",
    '2:21': "\"Whosoever shall call on the name of the Lord shall be saved\" — the door is opened before the indictment is made.",
    '2:22': "Jesus is presented as one God approved among them, \"as ye yourselves also know.\" No new information is offered.",
    '2:23': "God's determinate counsel and their wicked hands stand in one sentence, and Peter does not resolve the tension.",
    '2:24': "\"Not possible that he should be holden of it.\" Death had taken hold of the one man it had no claim on.",
    '2:25': "David's words are treated as spoken about someone else. The Psalter is read as testimony, not autobiography.",
    '2:27': "\"Thou wilt not leave my soul in hell.\" The hope in the psalm outruns anything David could claim for himself.",
    '2:29': "David's tomb is the argument. It is still there, so the psalm must be about someone whose tomb is not.",
    '2:30': "The oath sworn to David is read as a promise of resurrection, not merely of dynastic succession.",
    '2:32': "\"Whereof we all are witnesses.\" The claim is made in the city where it could most easily have been disproved.",
    '2:33': "Pentecost is offered as proof of the ascension: what the crowd sees and hears was poured out from the throne.",
    '2:34': "David never ascended, so the psalm about sitting at God's right hand needs another occupant.",
    '2:36': "\"Both Lord and Christ\" and \"whom ye have crucified\" — God's verdict and their crime named in one breath.",
    '2:37': "\"Pricked in their heart.\" The law lands first, and the question about what to do comes only after it.",
    '2:38': "Repent and be baptized — and the gift of the Spirit follows the promise rather than any performance.",
    '2:39': "\"To all that are afar off.\" The promise already reaches past the room, to their children and beyond them.",
    '2:40': "\"Save yourselves from this untoward generation.\" Peter treats the crowd's own world as the thing to be escaped.",
    '2:41': "Three thousand baptized the same day. There is no probation, no waiting period, no proving of sincerity.",
    '2:42': "Doctrine, fellowship, breaking of bread, prayers. The church's shape is described before it has any structure.",
    '2:43': "Fear came upon every soul. The first mood of the new community is not enthusiasm but awe.",
    '2:44': "All things common — reported as something that happened, never issued as a rule for anyone else.",
    '2:45': "They parted goods \"as every man had need.\" The measure is need, not equal shares.",
    '2:46': "Temple and house, daily. They did not have to choose between the public liturgy and the kitchen table.",
    '2:47': "\"The Lord added to the church.\" Growth is credited to him, not to their method or their zeal.",

    # ---- Chapter 3 ----
    '3:1': "Peter and John go up at the hour of prayer. The new thing does not begin by despising the old hours.",
    '3:2': "He was laid daily at the gate called Beautiful. The loveliest door in Jerusalem had a beggar outside it.",
    '3:4': "\"Look on us.\" Before anything is given, the man is looked at and made to look back.",
    '3:5': "He expects to receive something. His expectation is not wrong, only far too small.",
    '3:6': "\"Silver and gold have I none.\" What the church could not give turns out not to have been the point.",
    '3:7': "Peter takes him by the hand and lifts. The strength arrives while he is already being raised.",
    '3:8': "Walking and leaping and praising God, he goes into the temple he had spent his life sitting outside of.",
    '3:10': "They knew it was the same man. Recognition is what makes the thing impossible to explain away.",
    '3:11': "The crowd runs to the two men holding the healed man, which is precisely the problem Peter is about to fix.",
    '3:12': "\"As though by our own power or holiness.\" The sermon's first move is to refuse the credit being offered.",
    '3:13': "The God of Abraham glorified Jesus — the one they delivered up while Pilate was determined to release him.",
    '3:14': "They asked for a murderer in place of the Holy One. Peter will not let the exchange be forgotten.",
    '3:15': "\"Killed the Prince of life.\" The phrase is built to be impossible, and that is the whole charge.",
    '3:16': "The man is made strong by the name through faith — and even the faith is \"by him.\" Nothing is left to supply.",
    '3:17': "\"Through ignorance ye did it.\" Peter opens a way back without withdrawing a word of the accusation.",
    '3:18': "What they did in ignorance God had already announced by every prophet. Their crime did not derail anything.",
    '3:19': "Repent, and be converted, that sins may be blotted out. The blotting is done to them, not by them.",
    '3:21': "Heaven must receive him until the restitution of all things. The absence has a stated end.",
    '3:22': "Moses pointed past himself to a prophet who must be heard in all things. The greatest lawgiver expected a successor.",
    '3:23': "The warning attached to the promise: refusing that prophet cuts a soul off from the people.",
    '3:24': "Samuel onward, all of them spoke of these days. Peter claims the whole prophetic line, not a proof text.",
    '3:25': "\"In thy seed shall all the kindreds of the earth be blessed.\" The Gentile mission is quoted from Genesis before it begins.",
    '3:26': "\"Unto you first.\" Israel has priority, and the blessing offered is being turned from iniquity, not spared trouble.",
}

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:1': "The arrest comes while they are still speaking. The sermon is interrupted, not answered.",
    '4:2': "What grieves the Sadducees is resurrection preached at all. The doctrine offended before the man did.",
    '4:3': "They are held overnight because it was late. Persecution begins with something as ordinary as the hour.",
    '4:4': "The word had already done its work. Arresting the preachers did nothing to the five thousand who believed.",
    '4:7': "\"By what power, or by what name?\" The council cannot deny the healing, so it interrogates the source.",
    '4:8': "Peter is filled with the Holy Ghost at the moment of examination, which is exactly what Jesus had promised.",
    '4:9': "Peter names the charge for what it is: they are on trial for a good deed done to a helpless man.",
    '4:10': "\"Whom ye crucified, whom God raised\" — the whole gospel is put to the men who signed the order.",
    '4:11': "The builders' rejected stone becomes the corner. The men who threw it out are addressed as the builders.",
    '4:12': "\"None other name under heaven\" — the exclusivity is stated to the authorities, not whispered among friends.",
    '4:13': "Unlearned and ignorant men, and the council can only account for them by saying they had been with Jesus.",
    '4:14': "The healed man standing there leaves nothing to say. A restored body is an argument that cannot be cross-examined.",
    '4:16': "\"We cannot deny it.\" They concede the miracle in private and still plan to suppress it in public.",
    '4:17': "The concern is containment, not truth. The question is never whether it happened but how far it will spread.",
    '4:18': "The ban is total: not to speak at all nor teach in that name. The name itself is what they cannot tolerate.",
    '4:19': "\"Judge ye\" — Peter hands the council the question of whether God or the council outranks the other.",
    '4:20': "\"We cannot but speak.\" Not defiance chosen but testimony that will not stay down.",
    '4:21': "They release them for fear of the people. The crowd's praise of God is the only restraint on the court.",
    '4:22': "Above forty years old. Luke gives the age because the lameness was too long-standing to be staged.",
    '4:23': "Released, they go straight back to their own company. Nobody in this book faces the council alone for long.",
    '4:24': "The prayer opens with the Creator, not the crisis. They set the threat inside a much larger frame.",
    '4:25': "They pray the second Psalm. The raging of the heathen was written down long before it reached their door.",
    '4:27': "Herod, Pilate, Gentiles and Israel gathered together — the whole world's authorities on one side, briefly united.",
    '4:28': "The conspiracy accomplished what God's hand had determined. Luke will not let evil be the sovereign actor.",
    '4:29': "They do not pray for the threats to stop. They pray to keep speaking through them.",
    '4:30': "The request is that God stretch out his hand; the healing is asked for as his work, not licensed as theirs.",
    '4:31': "The place is shaken and they are filled again. The Spirit is not a one-time endowment to be conserved.",
    '4:32': "One heart and one soul, and nobody calls what he owns his own. The sharing follows the unity rather than producing it.",
    '4:33': "Great power in witness and great grace upon them all, reported in the same breath.",
    '4:34': "\"Neither was there any among them that lacked.\" The measure of the arrangement is that no one went short.",
    '4:35': "Laid at the apostles' feet, distributed according to need. Ownership is surrendered before it is redistributed.",
    '4:36': "Barnabas is introduced as son of consolation, and Luke lets the nickname stand as a character reference.",
    '4:37': "Barnabas sells a field and lays down the money. The same act Ananias will imitate, without the lie.",

    # ---- Chapter 5 ----
    '5:1': "\"But a certain man\" — the word turns, and the first sin recorded inside the church is about money and reputation.",
    '5:2': "Keeping back part was never the crime. Bringing part while implying all was.",
    '5:3': "Peter names Satan at work in a heart that was performing generosity in public.",
    '5:4': "\"Was it not thine own?\" The giving was voluntary throughout. The lie was the only thing required of him.",
    '5:5': "He lied to men and died before God. The distinction Peter drew turns out not to be rhetorical.",
    '5:6': "The young men wrap him and carry him out. The church buries its own dead without ceremony or explanation.",
    '5:8': "Peter gives Sapphira the chance to tell the truth, and she answers with the agreed figure.",
    '5:9': "\"Ye have agreed together to tempt the Spirit.\" What they thought was a private arrangement was a test of God.",
    '5:10': "She is buried beside her husband. The story ends with a household intact in everything but life.",
    '5:11': "Great fear came upon the church. The first thing the community learns about the Spirit is that he is not safe.",
    '5:12': "Signs and wonders and one accord together in Solomon's porch. The church stays public, in the temple's own colonnade.",
    '5:13': "No one dares join them, and the people magnify them anyway. Admiration and distance can coexist for a long time.",
    '5:14': "Believers are added notwithstanding the fear — multitudes, and Luke names the women as well as the men.",
    '5:15': "They lay the sick where Peter's shadow might fall. Luke reports the hope without endorsing the theory behind it.",
    '5:16': "People come in from the surrounding cities. The movement is already outgrowing the city it started in.",
    '5:17': "Indignation is the high priest's motive, and Luke says so plainly. The opposition is not principled.",
    '5:18': "The common prison, not a private cell. They are treated as ordinary criminals.",
    '5:19': "The angel opens the doors at night. Deliverance here is not from suffering but for the sake of the next sermon.",
    '5:20': "\"All the words of this life.\" They are freed from prison and sent straight back to the place they were arrested.",
    '5:21': "They teach at daybreak while the council is still assembling to try them. The mission does not wait for the verdict.",
    '5:23': "The doors shut, the keepers standing, and no one inside. The report is exact and completely useless.",
    '5:24': "\"They doubted whereunto this would grow.\" The authorities sense they are managing something that cannot be managed.",
    '5:26': "They are fetched without violence because the officers fear the crowd. Power is calculating, not courageous.",
    '5:28': "\"Ye have filled Jerusalem with your doctrine\" — an accusation that reads as a progress report.",
    '5:29': "\"We ought to obey God rather than men.\" The principle is stated where it costs something to state it.",
    '5:30': "\"Whom ye slew and hanged on a tree.\" Peter uses the language of the curse in Deuteronomy on purpose.",
    '5:31': "Repentance itself is listed among the gifts Christ gives. Even the turning is not the sinner's contribution.",
    '5:32': "Two witnesses are named: the apostles and the Holy Ghost. The testimony was never only human.",
    '5:33': "Cut to the heart, they take counsel to kill. The same words that pricked hearts at Pentecost now produce murder.",
    '5:34': "Gamaliel clears the room before he speaks. Even the moderate voice is careful about who hears it.",
    '5:36': "Theudas is the first precedent: a movement that ended when its leader did.",
    '5:37': "Judas of Galilee is the second. Gamaliel's whole case rests on how such things usually finish.",
    '5:38': "\"If this counsel be of men, it will come to nought.\" Prudent advice, and it saves the apostles' lives.",
    '5:39': "\"Lest haply ye be found even to fight against God.\" Gamaliel names the danger and still declines to decide.",
    '5:40': "They agree with Gamaliel and beat the men anyway. Moderation stopped the execution, not the flogging.",
    '5:41': "They rejoice at being counted worthy of shame. The shame is not endured but received as an honour.",
    '5:42': "Daily, in the temple and in every house, they never stopped. The ban changed nothing about what they did.",

    # ---- Chapter 6 ----
    '6:1': "Growth produces the first internal complaint, and it runs along an ethnic line: Greek-speaking widows overlooked.",
    '6:2': "\"It is not reason that we should leave the word of God.\" The apostles refuse a good task to keep the first one.",
    '6:3': "Men full of the Holy Ghost and wisdom are chosen to hand out food. Waiting on tables is not treated as the lesser work.",
    '6:4': "Prayer and the ministry of the word are named as one office, and it requires the whole of a man.",
    '6:5': "Every one of the seven bears a Greek name. The aggrieved group is handed the administration of the remedy.",
    '6:6': "Prayer, then hands laid on. The congregation chooses and the apostles ordain, and both steps are kept.",
    '6:7': "\"The word of God increased\" — the count rises after a conflict was settled, and even priests come in.",
    '6:8': "Stephen was appointed to serve tables and is found doing wonders. The office did not limit the man.",
    '6:9': "The dispute starts in a synagogue of Diaspora Jews, among men who had come home to Jerusalem to be faithful.",
    '6:10': "They could not resist the wisdom by which he spoke, so they stopped arguing and started arranging.",
    '6:11': "\"They suborned men.\" When argument fails, witnesses are bought. Luke tells you the testimony was paid for.",
    '6:13': "The charge is words against the holy place and the law — the same charge brought against Jesus.",
    '6:14': "\"Shall change the customs which Moses delivered.\" The accusation is a distortion, and it is not entirely wrong.",
    '6:15': "His face is like an angel's while the false witnesses speak. The court sees the glory and proceeds anyway.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:1': "\"Are these things so?\" The high priest asks one short question and gets the longest speech in the book.",
    '7:2': "Stephen begins with God appearing to Abraham in Mesopotamia — outside the land, before there was any holy place.",
    '7:3': "The call is to leave. Israel's history starts with a man told to lose his address.",
    '7:4': "God moved him again after his father died. The promise advances by relocations, not by settlement.",
    '7:5': "Abraham owned not so much as a footstep of the land, and was promised all of it. He died holding only the word.",
    '7:6': "Four hundred years of bondage are announced in advance. The delay was in the promise from the start.",
    '7:7': "\"And serve me in this place.\" Even the exodus is aimed at worship rather than at territory.",
    '7:8': "The covenant of circumcision is given to a childless man, and the sign precedes the son it depends on.",
    '7:9': "The patriarchs sold their brother out of envy — \"but God was with him.\" Stephen's pattern is already forming.",
    '7:10': "The man they sold becomes the one who feeds them. God's deliverer works from inside a foreign court.",
    '7:12': "Israel's survival depended on grain from Egypt. The family was kept alive by the place it would later be enslaved in.",
    '7:13': "\"At the second time Joseph was made known.\" Recognition of the rejected brother comes late, and only on his terms.",
    '7:15': "Jacob and the fathers died in Egypt. The patriarchs never saw the promise they are famous for believing.",
    '7:16': "They are buried in a plot bought with money. The only land they held was a grave.",
    '7:17': "The people multiply exactly when the promise draws near, and that growth is what brings the persecution.",
    '7:18': "\"Another king which knew not Joseph.\" Gratitude has a short memory in every generation of power.",
    '7:19': "Infants cast out to die. Stephen puts Pharaoh's policy in the record without softening the word.",
    '7:20': "Moses is born into the massacre. The deliverer arrives at the point of maximum danger, not of safety.",
    '7:21': "Cast out by his own people's enemy and taken up by that enemy's daughter. God uses Pharaoh's household to save Israel.",
    '7:22': "Learned in all the wisdom of the Egyptians. Moses' training was entirely foreign and entirely useful.",
    '7:23': "At forty it came into his heart to visit his brethren. The impulse was right and the timing was his own.",
    '7:24': "He avenged the oppressed by killing a man. Stephen reports the deed plainly, neither excusing nor condemning.",
    '7:25': "\"He supposed his brethren would have understood… but they understood not.\" The rescuer is misread by the rescued.",
    '7:26': "\"Sirs, ye are brethren; why do ye wrong one to another?\" He tries mediation and it goes worse than the killing.",
    '7:27': "\"Who made thee a ruler and a judge over us?\" The question Stephen will turn on the council in a moment.",
    '7:29': "Moses flees and becomes a stranger in Madian. Forty years of nothing follow the first attempt to help.",
    '7:30': "After forty years, in a wilderness, in a bush. God appears where no one would have thought to look for him.",
    '7:32': "The God of Abraham, Isaac and Jacob speaks in Sinai, far from the temple the council is defending.",
    '7:33': "Holy ground is wherever God is speaking. The sandals come off in the desert, not in Jerusalem.",
    '7:34': "\"I have seen, I have seen… and am come down to deliver.\" The doubling is God insisting he has not missed it.",
    '7:35': "\"This Moses whom they refused… the same did God send.\" The rejected one is the sent one, and Stephen means the parallel.",
    '7:36': "Wonders in Egypt, at the sea, and forty years in the wilderness. The deliverance was long, not a single night.",
    '7:37': "Moses himself announced a prophet like him who must be heard. The law's own author pointed away from himself.",
    '7:38': "\"The lively oracles\" were received to be given away. Stephen honours the law he is accused of blaspheming.",
    '7:39': "\"Our fathers would not obey, but thrust him from them.\" The rejection is habitual, not a single lapse.",
    '7:40': "\"We wot not what is become of him.\" The calf is made because the mediator was out of sight too long.",
    '7:41': "They rejoiced in the works of their own hands. Idolatry is admiring your own product and calling it God.",
    '7:42': "\"God turned, and gave them up.\" The judgment is being handed over to what you already wanted.",
    '7:43': "Moloch and Remphan were carried through the wilderness alongside the tabernacle. Both were in the camp the whole time.",
    '7:44': "The tabernacle was built to a pattern God showed. Even the tent was not Israel's own idea.",
    '7:45': "The tent came into the land with Joshua and stayed a tent for centuries. God was in no hurry for a building.",
    '7:46': "David only desired to find a dwelling. The favoured king wanted to build and was not the one who did.",
    '7:47': "\"But Solomon built him an house.\" One flat sentence, and Stephen's \"but\" carries the weight of the charge.",
    '7:48': "\"The most High dwelleth not in temples made with hands.\" The accused answers the temple charge by conceding it.",
    '7:49': "\"What house will ye build me?\" Isaiah asked the question long before Stephen was accused of asking it.",
    '7:50': "\"Hath not my hand made all these things?\" The builder cannot house the one who made the materials.",
    '7:51': "\"Ye do always resist the Holy Ghost.\" The history turns into an indictment; his hearers are the latest chapter.",
    '7:52': "Their fathers killed the prophets who foretold the Just One; they killed the Just One himself. The line is continuous.",
    '7:53': "They received the law by angels and did not keep it. The temple charge is returned with interest.",
    '7:54': "Cut to the heart and gnashing with their teeth. The same wound that produced three thousand converts produces rage here.",
    '7:55': "He sees Jesus standing at the right hand — the seated Lord is on his feet for the first martyr.",
    '7:56': "\"The Son of man standing.\" Stephen uses the title Jesus used at his own trial, and is condemned for the same words.",
    '7:57': "They stop their ears and run on him with one accord. The verdict is shouted down rather than argued.",
    '7:58': "The witnesses lay their coats at the feet of a young man named Saul. Luke plants him in the scene without comment.",
    '7:59': "\"Lord Jesus, receive my spirit\" — a prayer to Jesus, in the words Jesus prayed to the Father.",
    '7:60': "He asks that the sin not be laid to their charge, and one of those men is standing right there.",

    # ---- Chapter 8 ----
    '8:1': "Saul consenting, the church scattered, the apostles staying. The persecution does the work of the great commission.",
    '8:2': "Devout men bury Stephen and make great lamentation. Grief over a martyr is not treated as a failure of faith.",
    '8:3': "Saul entered every house and hauled off men and women. Luke will not let his later story erase this one.",
    '8:4': "\"They that were scattered abroad went every where preaching.\" The refugees, not the apostles, carried it out.",
    '8:5': "Philip goes to Samaria — the old enemy, the half-breed neighbour — and preaches Christ there.",
    '8:6': "The Samaritans give heed with one accord. The wall that stood for centuries comes down in a single verse.",
    '8:7': "The unclean spirits come out crying. The powers that held that city had no more standing than in Judaea.",
    '8:8': "\"There was great joy in that city.\" Luke marks the gospel's arrival in a place by what it leaves behind.",
    '8:9': "Simon had bewitched the city, giving out that he himself was some great one. Religion and self-promotion were already partners.",
    '8:10': "\"This man is the great power of God\" — said from the least to the greatest. Everyone had believed him.",
    '8:11': "They regarded him because of long time. Habit, not evidence, held that city to its magician.",
    '8:12': "They believed the preaching and were baptized, men and women alike. Samaritans enter the church on identical terms.",
    '8:13': "Simon believed and was baptized, and what held him was the miracles. Luke leaves the ambiguity standing.",
    '8:14': "Jerusalem sends Peter and John to Samaria — the same John who once wanted fire called down on such a village.",
    '8:16': "They had been baptized and the Spirit had not fallen. God withholds until the apostles are present to see it.",
    '8:17': "Hands laid on, the Spirit received. The Samaritan church is joined to the Jerusalem church before either can go separate ways.",
    '8:18': "Simon sees a transaction where God gave a gift, and offers money for the franchise.",
    '8:19': "\"Give me also this power.\" What he wants is not the Spirit but the ability to dispense him.",
    '8:20': "\"Thy money perish with thee.\" Peter's severity is aimed at the idea that the gift of God has a price.",
    '8:21': "\"Thy heart is not right in the sight of God.\" Baptism did not settle the question of the man's heart.",
    '8:22': "\"If perhaps the thought of thine heart may be forgiven thee.\" Peter offers repentance without offering certainty.",
    '8:23': "\"The gall of bitterness, and the bond of iniquity\" — a man bound by what he thought he was buying.",
    '8:24': "Simon asks for prayer that the consequences be averted, not that the heart be changed. He fears the penalty only.",
    '8:25': "On the way back they preach in many Samaritan villages. The detour becomes a circuit.",
    '8:26': "Philip is pulled out of a city-wide revival and sent to a desert road. The Spirit's arithmetic is not about numbers.",
    '8:27': "An Ethiopian eunuch, a foreigner and a man the law barred from the assembly, is returning from worship.",
    '8:28': "He is reading Isaiah in a chariot. The Spirit's timing depends on a man's ordinary habit of reading.",
    '8:29': "\"Go near, and join thyself to this chariot.\" The instruction is small and specific, and the whole of Africa turns on it.",
    '8:30': "\"Understandest thou what thou readest?\" The text alone was not enough, and the eunuch knew it.",
    '8:31': "\"How can I, except some man should guide me?\" Scripture is given to be read, and read with help.",
    '8:32': "He was reading the suffering servant, silent before the shearer. The passage had found him before Philip did.",
    '8:33': "\"Who shall declare his generation?\" A man who could have no descendants is reading about one who had none.",
    '8:34': "\"Of whom speaketh the prophet this?\" The honest question, and the one the whole chapter hangs on.",
    '8:35': "\"Began at the same scripture, and preached unto him Jesus.\" Philip starts where the man already was.",
    '8:36': "\"What doth hinder me to be baptized?\" Deuteronomy hindered him. The eunuch asks anyway, and the answer is nothing.",
    '8:37': "Confession precedes baptism here, and the confession is one sentence long.",
    '8:38': "The chariot of a court official stops at a roadside pool. Rank has no bearing on how a man is received.",
    '8:39': "Philip is taken away and the eunuch goes on rejoicing — without a teacher, a congregation, or a follow-up visit.",
    '8:40': "Philip surfaces at Azotus and preaches all the way to Caesarea, where the next boundary will fall.",
})

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:1': "\"Yet breathing out threatenings and slaughter.\" Luke describes Saul as a man exhaling violence.",
    '9:2': "He wanted letters — the persecution was legal, documented, and carried out through proper channels.",
    '9:3': "The light comes suddenly, on the road, with nothing sought and nothing prepared for.",
    '9:4': "\"Why persecutest thou me?\" Jesus counts what is done to the church as done to himself.",
    '9:5': "\"Who art thou, Lord?\" He calls him Lord before he knows who it is, and the answer undoes his whole life.",
    '9:6': "He is not told what to do, only to go and wait for instructions. Even his conversion leaves him dependent.",
    '9:7': "His companions stand speechless. Something undeniable happened to them and it converted nobody.",
    '9:8': "The man who came to take prisoners is led into Damascus by the hand.",
    '9:9': "Three days blind, without food or drink. Nothing is said about what he thought, and the silence is the point.",
    '9:10': "\"Behold, I am here, Lord.\" An unknown disciple answers, and the whole Gentile mission turns on his obedience.",
    '9:11': "\"Behold, he prayeth.\" The proof offered to Ananias is not Saul's record but that he is praying.",
    '9:12': "Saul has been shown Ananias coming. Both ends of the meeting were arranged before either man moved.",
    '9:13': "Ananias argues with God, citing the evidence. His fear is entirely reasonable and entirely beside the point.",
    '9:14': "\"Authority from the chief priests to bind all that call on thy name.\" Ananias knows he is on the list.",
    '9:15': "\"He is a chosen vessel unto me.\" The choosing happened while Saul was still on his way to make arrests.",
    '9:16': "The commission comes with suffering attached, announced in advance and as part of the call.",
    '9:17': "\"Brother Saul.\" Ananias gives him the family word before anything else is said or proved.",
    '9:18': "Scales fall and he is baptized at once. The persecutor is received without a probationary period.",
    '9:19': "He eats, and then stays with the disciples he came to arrest. The first thing he receives from them is food.",
    '9:20': "\"Straightway he preached.\" The content is the Son of God, and the venue is the synagogue he carried letters to.",
    '9:21': "The whole city is amazed. His old reputation is the strongest thing his preaching has going for it.",
    '9:22': "He confounds them by proving from scripture what he had been killing people for believing.",
    '9:23': "The counsel to kill him comes from the men he once worked for. He has changed sides, not temperature.",
    '9:25': "The great apostle leaves his first mission field in a basket, lowered over a wall at night.",
    '9:26': "The Jerusalem disciples are afraid of him and do not believe he is one of them. The suspicion is understandable.",
    '9:27': "Barnabas takes him and vouches for him. The church needed one man willing to risk being wrong about Saul.",
    '9:29': "He disputes with the Grecians, Stephen's old opponents, and they try to kill him as they killed Stephen.",
    '9:30': "The brethren get him out of the city. Sometimes the church's care for a preacher is to remove him.",
    '9:31': "Rest, edification, the fear of the Lord and the comfort of the Spirit — and multiplication in the quiet.",
    '9:33': "Aeneas had kept his bed eight years. Luke records the length so the cure cannot be mistaken for a remission.",
    '9:34': "\"Jesus Christ maketh thee whole.\" Peter is careful to name who is doing it, then tells him to make his bed.",
    '9:35': "Two towns turn to the Lord because of one bedridden man. The scale of the effect is out of proportion to the sign.",
    '9:36': "Tabitha is introduced by her good works and almsdeeds. Luke's obituary for her is a list of what she did.",
    '9:37': "They wash her and lay her in an upper chamber. The care given the dead body is reported without apology.",
    '9:39': "The widows stand weeping and hold up the coats she made. Grief here is specific, and it has garments in its hands.",
    '9:40': "\"Tabitha, arise\" — two words, in Peter's own language, echoing what he had watched Jesus do in a similar room.",
    '9:41': "He presents her alive to the saints and the widows. The gift is given back to the community she served.",
    '9:43': "Peter lodges with a tanner, in a trade that kept a man ritually unclean. The next chapter starts from that house.",

    # ---- Chapter 10 ----
    '10:1': "A centurion of the Italian band — an officer of the occupying army is about to become the church's test case.",
    '10:2': "Devout, God-fearing, generous, praying. Cornelius has everything but the one thing Peter has to bring him.",
    '10:3': "The angel comes at the ninth hour, the hour of the temple sacrifice, to a Roman soldier in Caesarea.",
    '10:4': "\"Thy prayers and thine alms are come up for a memorial.\" God had been keeping account of a Gentile's devotion.",
    '10:5': "The angel does not preach. He sends for a man who will. God routes the gospel through people on purpose.",
    '10:6': "\"He shall tell thee what thou oughtest to do.\" The angel gives an address and stops short of the message.",
    '10:7': "Cornelius sends two servants and a devout soldier. Even his household has been shaped by his faith.",
    '10:9': "Peter goes up to pray at noon while the men are already at the gate. The vision is timed to the minute.",
    '10:10': "He is hungry, and the vision arrives through his hunger. God uses the appetite already in the room.",
    '10:11': "Heaven opened, and what comes down is a sheet of food. The revelation is about the dinner table.",
    '10:12': "All manner of beasts and creeping things — everything the law had spent centuries teaching him to refuse.",
    '10:13': "\"Rise, Peter; kill, and eat.\" The command is direct, and it contradicts a lifetime of obedience.",
    '10:14': "\"Not so, Lord.\" The two words do not belong together, and Peter says them anyway.",
    '10:15': "\"What God hath cleansed, that call not thou common.\" Cleanness is a verdict God issues, not a quality men detect.",
    '10:16': "Three times, then taken up. Peter needed the repetition, and later he will need to be able to report it.",
    '10:17': "Peter doubts what it means while the answer is standing at the gate. The interpretation walks up to the house.",
    '10:19': "The Spirit speaks while he is still puzzling. Understanding arrives after obedience begins, not before.",
    '10:20': "\"Go with them, doubting nothing: for I have sent them.\" The scruple is overruled by the sender's authority.",
    '10:22': "The messengers' credentials are Cornelius's character and an angel's word. Peter is given every reason but the law.",
    '10:23': "He lodges Gentiles overnight before he ever enters a Gentile house. The barrier falls in stages.",
    '10:24': "Cornelius had gathered his kinsmen and friends. He expected the message to be worth more than one man's hearing.",
    '10:25': "Cornelius falls at Peter's feet. The Roman officer worships the fisherman, and both instincts are wrong.",
    '10:26': "\"Stand up; I myself also am a man.\" The refusal of worship is immediate and without embarrassment.",
    '10:28': "\"God hath shewed me that I should not call any man common or unclean.\" The sheet was never about food.",
    '10:29': "\"I ask therefore for what intent ye have sent for me?\" Peter has obeyed without yet knowing the reason.",
    '10:30': "Cornelius tells it back, fasting and hour and all. Luke repeats the whole story because the church would need it.",
    '10:31': "\"Thy prayer is heard.\" The Gentile's prayers were heard before the Gentile mission was thought of.",
    '10:33': "\"We are all here present before God, to hear all things that are commanded thee.\" No preacher ever had a better audience.",
    '10:34': "\"God is no respecter of persons.\" Peter is not announcing a doctrine but admitting what he has just learned.",
    '10:35': "\"In every nation he that feareth him… is accepted with him.\" Nation ceases to be a category God sorts by.",
    '10:36': "\"He is Lord of all\" — the parenthesis is the whole argument for why Peter is standing in that room.",
    '10:37': "\"Ye know\" — even in Caesarea the story of Jesus had already travelled. Peter starts from public knowledge.",
    '10:38': "\"Went about doing good, and healing all that were oppressed.\" The summary of Jesus' life fits in one clause.",
    '10:39': "\"Whom they slew and hanged on a tree.\" The crucifixion is told to Gentiles in the language of the curse.",
    '10:40': "God raised him and shewed him openly. The resurrection is presented as something God did, not as a discovery.",
    '10:41': "\"Not to all the people, but unto witnesses chosen before.\" The risen Christ did not put himself on public display.",
    '10:42': "They are commanded to preach him as Judge of the living and the dead. Even to a friendly house the warning comes.",
    '10:43': "\"Whosoever believeth in him shall receive remission of sins.\" The sermon ends on the word that opens the door.",
    '10:44': "The Spirit falls while Peter is still speaking. The sermon is interrupted by God agreeing with it.",
    '10:45': "The circumcised believers are astonished. The people most prepared for this are the ones most surprised by it.",
    '10:46': "They hear tongues and magnifying of God — the same evidence as Pentecost, given so nobody could argue.",
    '10:47': "\"Can any man forbid water?\" The Spirit came first, and baptism can only acknowledge what God has already done.",
    '10:48': "He commands their baptism and stays several days. Eating with them was the harder half of the obedience.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "The news travels ahead of Peter: the Gentiles have received the word. Judaea hears it as a report, not a triumph.",
    '11:2': "\"They that were of the circumcision contended with him.\" The first church controversy is fought inside the church.",
    '11:3': "The charge is not that he preached but that he ate. Table fellowship, not doctrine, is where the wall really stood.",
    '11:4': "Peter does not pull rank. He rehearses the matter in order, and lets the sequence of events make the case.",
    '11:5': "He begins with \"I was praying.\" His defence rests on something that happened to him, not something he decided.",
    '11:8': "\"Nothing common or unclean hath at any time entered into my mouth.\" He reminds them he was as scrupulous as they are.",
    '11:12': "\"These six brethren accompanied me.\" Peter had brought witnesses, having guessed what the questions would be.",
    '11:14': "\"Words, whereby thou and all thy house shall be saved.\" Even an angel's visit left the household needing words.",
    '11:15': "\"As I began to speak\" — God did not wait for the sermon to finish, and Peter builds his whole argument on the timing.",
    '11:16': "Peter recalls a promise of Jesus that he only now understands. Memory catches up with events after the fact.",
    '11:17': "\"What was I, that I could withstand God?\" The decisive argument is that the objection came too late.",
    '11:18': "They held their peace and glorified God. A church argument ends with the losing side worshipping.",
    '11:19': "The scattered preached \"to none but unto the Jews only.\" The boundary survived the persecution intact.",
    '11:20': "Unnamed men from Cyprus and Cyrene preach to Greeks at Antioch. The decisive step is taken by nobody famous.",
    '11:21': "\"The hand of the Lord was with them.\" Luke credits the breakthrough to God rather than to a strategy.",
    '11:22': "Jerusalem sends Barnabas to look at Antioch. The mother church inspects what it did not start.",
    '11:23': "\"He had seen the grace of God, was glad.\" He looked for grace rather than for conformity, and found it.",
    '11:24': "\"He was a good man\" — Luke's plainest commendation, and it is offered as the reason the church grew.",
    '11:25': "Barnabas goes to Tarsus to find Saul. Someone had to remember the man the church had quietly shelved.",
    '11:26': "A whole year of teaching, and the name Christian is coined by outsiders in a Gentile city.",
    '11:28': "Agabus foretells a famine, and Luke notes it came to pass. Prophecy here is practical, not decorative.",
    '11:29': "\"Every man according to his ability\" — the relief is proportioned to means, and decided before it is collected.",
    '11:30': "The Gentile church sends money back to Jerusalem. The gospel went out from there, and the aid comes back to it.",

    # ---- Chapter 12 ----
    '12:1': "Herod stretches out his hands against the church. The state takes over where the temple authorities left off.",
    '12:2': "James is killed with the sword, in half a verse. One apostle dies and Luke gives it no more room than that.",
    '12:3': "\"Because he saw it pleased the Jews.\" The second arrest is made for popularity, which is motive enough.",
    '12:4': "Four squads of four to guard one fisherman. The precaution says what Herod had heard about escaped prisoners.",
    '12:5': "\"But prayer was made without ceasing.\" The church's only available action is set against the whole apparatus.",
    '12:6': "The night before execution, Peter is asleep between two soldiers. The detail is Luke's whole comment on his state of mind.",
    '12:7': "The angel has to strike him on the side to wake him. Deliverance arrives and finds the man unconscious.",
    '12:8': "\"Gird thyself, and bind on thy sandals.\" The miracle includes instructions about getting dressed properly.",
    '12:9': "He thought he saw a vision. The rescue is too unlikely for the man being rescued to credit it.",
    '12:10': "The iron gate opens of its own accord, and then the angel leaves him in the street to manage on his own.",
    '12:11': "\"Now I know of a surety.\" Certainty arrives only after he is standing outside in the cold.",
    '12:12': "He goes to a house where many are praying — for him, as it turns out, though they will not believe it.",
    '12:13': "A servant girl named Rhoda answers the door. Luke bothers to record her name in the middle of a jailbreak.",
    '12:14': "For gladness she leaves him outside. The joy is real and the door stays shut, which is very close to the point.",
    '12:15': "\"Thou art mad.\" The praying church calls the answer to its prayers an impossibility.",
    '12:16': "Peter keeps knocking while they argue. The comedy is that the miracle has to wait on the meeting.",
    '12:17': "He tells them to report to James, and goes elsewhere. The leader of the church slips out of the story quietly.",
    '12:18': "\"No small stir among the soldiers.\" Luke's understatement covers men who know what the penalty will be.",
    '12:19': "The keepers are executed. Peter's deliverance cost other men their lives, and Luke does not look away from it.",
    '12:20': "Tyre and Sidon flatter a chamberlain because their food supply depends on Herod. Politics runs on the grain trade.",
    '12:21': "Royal apparel, a throne, an oration. Everything is arranged for the moment that is about to destroy him.",
    '12:22': "\"It is the voice of a god, and not of a man.\" Flattery from men whose motive was already stated.",
    '12:23': "\"Because he gave not God the glory\" — the charge is not the shout but the silence that accepted it.",
    '12:24': "\"But the word of God grew and multiplied.\" The king is dead and the sentence about the word follows immediately.",
    '12:25': "They take John Mark with them. A quiet note that will matter a great deal two chapters later.",

    # ---- Chapter 13 ----
    '13:1': "Prophets and teachers at Antioch: an African, a Cyrenian, a man raised with Herod, and Saul. The list is the church's shape.",
    '13:2': "\"Separate me Barnabas and Saul.\" The mission is launched by the Spirit interrupting a service already in progress.",
    '13:3': "Fasting, prayer, hands laid on, sent away. The church ratifies the call rather than originating it.",
    '13:4': "\"Being sent forth by the Holy Ghost\" — Luke names the real sender, then records the boat they took.",
    '13:5': "They begin in the synagogues. The mission to the nations starts each time among Israel first.",
    '13:6': "A Jewish false prophet attached to a Roman governor. Opposition comes from inside the household of faith.",
    '13:7': "Sergius Paulus, a prudent man, sends for the word himself. Curiosity in high places is treated as an opening.",
    '13:8': "Elymas works to turn the governor from the faith. The counterfeit's whole business is keeping a patron.",
    '13:9': "\"Saul, who also is called Paul.\" From here he carries the Roman name, and Luke never uses the other again.",
    '13:10': "\"Thou child of the devil, thou enemy of all righteousness.\" Paul's first recorded words are a denunciation.",
    '13:11': "Blindness for a season, and a man groping for a hand to lead him — exactly what happened to Paul on his own road.",
    '13:12': "The deputy believes, astonished at the doctrine. What convinced him was the teaching, with the sign clearing the way.",
    '13:13': "John departed from them and returned to Jerusalem. Luke gives no reason, and the omission will cost a partnership.",
    '13:15': "The synagogue invites a word of exhortation. Paul's greatest opportunities keep arriving as ordinary hospitality.",
    '13:16': "\"Men of Israel, and ye that fear God.\" Two audiences are addressed from the first sentence, and both are kept.",
    '13:17': "God chose the fathers and exalted the people while they were strangers in Egypt. Israel was made great as aliens.",
    '13:18': "\"About the time of forty years suffered he their manners.\" The history includes God's patience as a fact about him.",
    '13:20': "Judges for four hundred and fifty years. Paul lets the long stretch of muddle stand in his summary.",
    '13:21': "\"They desired a king: and God gave unto them Saul.\" The first Saul is named by a man who bore that name.",
    '13:22': "\"A man after mine own heart, which shall fulfil all my will\" — said of David, whose record is what it is.",
    '13:23': "\"Of this man's seed hath God… raised unto Israel a Saviour.\" The whole history was leading to one name.",
    '13:25': "John refused the role offered him: \"I am not he.\" The greatest prophet's work was to decline promotion.",
    '13:26': "\"To you is the word of this salvation sent.\" The synagogue is told the message is addressed to them personally.",
    '13:27': "They fulfilled the prophets by condemning him — reading the words every sabbath and enacting them without knowing.",
    '13:28': "They found no cause of death and asked for the execution anyway. Paul states it without adjectives.",
    '13:29': "\"When they had fulfilled all that was written.\" Even the burial is inside what had been foretold.",
    '13:30': "\"But God raised him from the dead.\" Three words in the Greek, and the hinge of every sermon in this book.",
    '13:31': "The witnesses were seen by many for many days, and they are still alive and speaking to the people.",
    '13:33': "The second psalm is applied to the resurrection: the begetting announced there is the raising up of the Son.",
    '13:34': "\"The sure mercies of David\" — a promise of permanence, which requires a king who does not stay dead.",
    '13:36': "\"David… fell on sleep, and saw corruption.\" His service ended and his body did what bodies do.",
    '13:37': "\"But he, whom God raised again, saw no corruption.\" The contrast carries the whole argument from the psalms.",
    '13:38': "\"Through this man is preached unto you the forgiveness of sins.\" The offer is announced, not negotiated.",
    '13:39': "Justified from all things the law could not justify from. Paul's great theme is stated here first, in a synagogue.",
    '13:40': "The sermon ends with a warning. The same word that offers forgiveness can be despised, and often is.",
    '13:41': "\"Ye shall in no wise believe, though a man declare it unto you.\" Habakkuk's warning about hearing and refusing.",
    '13:42': "The Gentiles ask for the same words next sabbath. The overflow congregation asks for a repeat, not a variation.",
    '13:43': "\"Continue in the grace of God\" — the follow-up instruction to converts is to stay where they already stand.",
    '13:44': "Almost the whole city gathers. A synagogue invitation has turned into a public meeting of Antioch.",
    '13:45': "\"Filled with envy.\" Luke names the motive for the opposition, and it is the size of the crowd.",
    '13:46': "\"Ye put it from you, and judge yourselves unworthy.\" The refusal is theirs; the turning to the Gentiles follows it.",
    '13:47': "The commission is quoted from Isaiah's servant songs and applied to themselves: a light to the Gentiles.",
    '13:48': "\"As many as were ordained to eternal life believed.\" Luke puts the election behind the believing, not after it.",
    '13:50': "The persecution is organised through devout women and chief men. Respectability is the instrument of the expulsion.",
    '13:51': "They shake off the dust, which Jesus prescribed, and go on to the next town. The gesture ends nothing but their stay.",
    '13:52': "The disciples left behind in that city are filled with joy and the Holy Ghost, with their teachers expelled.",
})

TAKEAWAYS.update({
    # ---- Chapter 14 ----
    '14:1': "\"So spake, that a great multitude… believed.\" Luke credits the manner of the speaking, not only its content.",
    '14:2': "The opposition works by poisoning minds in advance. Its weapon is the mood of a city, not an argument.",
    '14:3': "They stayed a long time because of the opposition, not in spite of it. Danger did not shorten the visit.",
    '14:4': "The city is divided. The gospel does not arrive and leave a place as it found it.",
    '14:5': "Gentiles, Jews and rulers combine against them. Old enemies find agreement in what they both want to stop.",
    '14:6': "They flee rather than face the stoning. Fleeing is treated as an ordinary and legitimate move.",
    '14:8': "A cripple from his mother's womb, sitting and listening. Luke stages Lystra like Jerusalem's Beautiful gate.",
    '14:9': "Paul perceived he had faith to be healed. The man had heard preaching before anything happened to his feet.",
    '14:10': "\"Stand upright on thy feet.\" A command issued to legs that had never once obeyed such a thing.",
    '14:11': "The crowd interprets the miracle through its own mythology. A sign is read by whatever story a people already has.",
    '14:12': "Barnabas is Jupiter and Paul is Mercury, because Paul talked more. Reputation is assigned on very thin evidence.",
    '14:13': "Oxen and garlands at the gates. Their sincerity is complete, and it is aimed at exactly the wrong object.",
    '14:14': "They rend their clothes and run into the crowd. Being worshipped is treated as an emergency.",
    '14:15': "\"We also are men of like passions with you.\" The first thing preached to pagans is that the preachers are ordinary.",
    '14:16': "\"Suffered all nations to walk in their own ways.\" God's patience with the nations is named as part of the history.",
    '14:17': "Rain and fruitful seasons are called witness. God left his signature on the weather in places that never heard Moses.",
    '14:18': "They \"scarce restrained\" the people. Stopping a sacrifice in their honour took more effort than healing the man.",
    '14:19': "The same crowd that wanted to sacrifice to him helps stone him. Adulation and violence come from one appetite.",
    '14:20': "He rises, walks back into the city that stoned him, and leaves the next morning. Luke reports it without comment.",
    '14:21': "They go back through the very towns that threw them out. Founding churches meant returning to dangerous places.",
    '14:22': "\"We must through much tribulation enter into the kingdom.\" Their pastoral encouragement is a warning.",
    '14:23': "Elders ordained in every church, with prayer and fasting, then left to God. They hand the congregations over and go.",
    '14:26': "They return to the church that commended them to grace, and report at the end of the work they were sent for.",
    '14:27': "\"He had opened the door of faith unto the Gentiles.\" The door is God's to open; they only walked through it.",

    # ---- Chapter 15 ----
    '15:1': "\"Except ye be circumcised… ye cannot be saved.\" The dispute is not about custom but about what saves.",
    '15:2': "\"No small dissension.\" Luke does not pretend the apostolic church settled things without a fight.",
    '15:3': "On the way to the trial they tell the story of Gentile conversions, and it causes great joy in every town.",
    '15:4': "They report \"all things that God had done.\" Their defence is a narrative of God's actions, not a position paper.",
    '15:5': "Believing Pharisees make the case. The objection comes from the devout, not from opponents of the faith.",
    '15:7': "Peter dates the decision: God made the choice long ago, at Cornelius's house, and it was God's choice.",
    '15:8': "\"God, which knoweth the hearts, bare them witness.\" The evidence is what God did, not what the Gentiles achieved.",
    '15:9': "\"Purifying their hearts by faith\" — and no difference put between us and them. The ground is level or it is nothing.",
    '15:10': "\"A yoke… which neither our fathers nor we were able to bear.\" Peter concedes that the law defeated Israel too.",
    '15:11': "\"We shall be saved, even as they.\" The Jews are saved the way the Gentiles are, not the other way round.",
    '15:12': "The multitude falls silent to hear what God had wrought. The turning point in the debate is a report of facts.",
    '15:13': "James answers last, and he is the one the strict party would have expected to side with them.",
    '15:14': "\"To take out of them a people for his name.\" The Gentiles are not added to Israel but gathered as God's own.",
    '15:16': "Amos is read as fulfilled now: the fallen tabernacle of David rebuilt is the church receiving the nations.",
    '15:17': "\"That the residue of men might seek after the Lord.\" The prophets had the Gentiles in view all along.",
    '15:18': "\"Known unto God are all his works from the beginning.\" The surprise was only ever on the church's side.",
    '15:19': "\"That we trouble not them.\" The ruling is framed as removing a burden rather than imposing a settlement.",
    '15:20': "The four items are about idol-tables and sexual practice — how Gentiles can eat with Jews, not how they are saved.",
    '15:21': "Moses is preached in every city. The restraint asked of Gentiles is consideration for neighbours who hear him weekly.",
    '15:22': "The whole church joins the apostles and elders in sending. The decision is made and owned publicly.",
    '15:23': "The letter is addressed to brethren of the Gentiles. The word brethren does the work the whole council was about.",
    '15:24': "\"To whom we gave no such commandment.\" Jerusalem disowns the men who had used its name.",
    '15:26': "\"Men that have hazarded their lives for the name\" — Paul and Barnabas are commended, not merely permitted.",
    '15:27': "Judas and Silas will say the same things by mouth. A letter is sent with people who can be questioned.",
    '15:28': "\"It seemed good to the Holy Ghost, and to us.\" A church decision claims the Spirit without claiming a vision.",
    '15:29': "\"From which if ye keep yourselves, ye shall do well.\" No threat attached, and no promise of salvation either.",
    '15:31': "They rejoiced for the consolation. What relieved them was not permission but the removal of a fear.",
    '15:32': "Judas and Silas exhort with many words. The letter was short; the pastoral work of delivering it was not.",
    '15:36': "\"Let us… see how they do.\" The second journey begins as a pastoral visit, not as an expansion.",
    '15:37': "Barnabas determines to take Mark. The son of consolation is consistent to the end about second chances.",
    '15:38': "Paul thought not good to take a man who had left the work. His judgment is about reliability, and it is not petty.",
    '15:39': "\"The contention was so sharp.\" Two good men part company, and Luke assigns blame to neither.",
    '15:40': "Paul chooses Silas and is commended to grace. The quarrel produces two mission teams instead of one.",
    '15:41': "He goes through Syria and Cilicia confirming churches. The split does not slow the work by a single town.",

    # ---- Chapter 16 ----
    '16:1': "Timothy: a believing Jewish mother, a Greek father. The next generation of leadership is already mixed.",
    '16:2': "He was well reported of by the brethren in two towns. The recommendation comes from the churches, not from Paul.",
    '16:3': "Paul circumcises the man he just refused to require circumcision of. Principle held; the concession was freely made.",
    '16:4': "They carry the Jerusalem decrees as they go. The council's work travels with the mission rather than staying filed.",
    '16:5': "Established in the faith and increased in number. Luke joins the two as though they normally go together.",
    '16:6': "\"Forbidden of the Holy Ghost to preach the word in Asia.\" Guidance here is a closed door, not an open one.",
    '16:7': "\"The Spirit suffered them not.\" Twice refused, with no reason given and no alternative yet offered.",
    '16:9': "\"Come over into Macedonia, and help us.\" The call into Europe is a request for help, not an offer of opportunity.",
    '16:10': "\"We endeavoured to go\" — Luke slips into the first person, and joins the story he has been telling.",
    '16:12': "Philippi, a Roman colony. The gospel enters Europe in a town proud of being a small piece of Rome.",
    '16:13': "No synagogue, so they look for a riverside prayer meeting and speak to the women who gathered there.",
    '16:14': "\"Whose heart the Lord opened.\" Lydia listened because God opened her, and Luke puts the opening first.",
    '16:15': "\"If ye have judged me to be faithful… come into my house.\" Her first act as a believer is to insist on hospitality.",
    '16:16': "A slave girl whose spirit brings her masters much gain. Exploitation and the occult are running the same business.",
    '16:17': "What she cries is perfectly true. Paul still silences it, because true words from that source help nothing.",
    '16:18': "\"Being grieved\" — after many days. The exorcism is done out of weariness with her, not as a display.",
    '16:19': "\"When her masters saw that the hope of their gains was gone.\" The charge follows the money, exactly.",
    '16:20': "\"These men, being Jews, do exceedingly trouble our city.\" The complaint is racial because the real one is financial.",
    '16:21': "\"Not lawful for us to receive… being Romans.\" Civic identity is the respectable cover for a lost income.",
    '16:22': "The magistrates beat them without a hearing. Roman order collapses into mob procedure when a crowd is loud enough.",
    '16:23': "Many stripes, then prison, with the jailer charged to keep them safely. The precautions pile up in Luke's telling.",
    '16:24': "The inner prison and the stocks. Every additional security will be undone in a single sentence.",
    '16:25': "Midnight, backs bleeding, and they sing. Luke adds that the other prisoners were listening.",
    '16:26': "The earthquake opens every door and looses every prisoner's bands, not only the two men who were praying.",
    '16:27': "The jailer reaches for his sword. A Roman knows what the penalty for lost prisoners is.",
    '16:28': "\"We are all here.\" The miracle they use is staying put, and it saves the one man they came to Philippi for.",
    '16:29': "He springs in trembling and falls at their feet — a jailer prostrate before the men he had put in the stocks.",
    '16:30': "\"What must I do to be saved?\" An hour ago he was about to kill himself; the question has changed its object.",
    '16:31': "\"Believe on the Lord Jesus Christ.\" The whole answer is one verb, and the doing he asked about is not his.",
    '16:32': "They speak the word to him and to all in his house. The promise to the household still comes by preaching to them.",
    '16:33': "He washes their stripes and is washed himself the same hour. The care runs both directions before the night ends.",
    '16:34': "He sets food before them and rejoices. The gospel reaches Philippi's jail and ends at a table.",
    '16:35': "In the morning the magistrates want it all to go away quietly. Injustice prefers to be tidied rather than admitted.",
    '16:37': "\"They have beaten us openly uncondemned, being Romans.\" Paul uses his citizenship after the beating, not before it.",
    '16:38': "The magistrates are afraid. The men with the power spend the last scene of this story frightened.",
    '16:39': "They beseech them and ask them to leave. The public apology is extracted for the young church's sake.",
    '16:40': "They go to Lydia's house, comfort the brethren, and only then depart. The congregation is left standing.",
})
