#!/usr/bin/env python3
"""Written one-line takeaways for Colossians."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"By the will of God\" — the apostleship is credentialed from outside himself, not by anything Colosse could check.",
    '1:2': "He writes to a church he has never visited and calls them saints before he has seen a thing they have done.",
    '1:4': "Faith in Christ and love to all the saints arrive together. Neither is reported without the other.",
    '1:5': "The hope is \"laid up\" elsewhere and already theirs, which is why it can be the root of the love rather than its reward.",
    '1:6': "The same gospel is bearing fruit worldwide and in them. Nothing local was added to make it work at Colosse.",
    '1:7': "They learned it from Epaphras, not from Paul. The gospel arrives secondhand and loses nothing.",
    '1:8': "The only report Paul has of them is of their love. That is what a messenger thought worth carrying.",
    '1:9': "The prayer is for knowledge of God's will, not for relief from circumstances.",
    '1:10': "Walking worthy is unpacked as fruitfulness and growing knowledge — not as avoiding failure.",
    '1:11': "All that might and glorious power is spent on patience. The strength asked for is stamina, not force.",
    '1:12': "\"Hath made us meet\" — fitness for the inheritance is something done to them, past tense, before any qualifying.",
    '1:13': "Deliverance and transfer both happened. No one is left between kingdoms, negotiating.",
    '1:14': "Redemption is defined immediately and narrowly: forgiveness of sins. Nothing else is offered as the content.",
    '1:15': "The invisible God has an image, and \"firstborn\" here is rank over creation, not membership in it.",
    '1:16': "Thrones, dominions, principalities, powers — the very hierarchy the false teachers admired was made by him, and for him.",
    '1:17': "\"By him all things consist.\" Creation is not merely started by Christ but held together moment by moment.",
    '1:18': "Head of the church and firstborn from the dead: the same preeminence in the new creation as in the old.",
    '1:19': "The fulness dwells in him because it pleased the Father. Christ's sufficiency is the Father's decision.",
    '1:20': "Peace was made through blood, which means reconciliation cost something rather than being declared.",
    '1:21': "The alienation was \"in your mind by wicked works\" — enmity is located in thought as much as behaviour.",
    '1:22': "Presented holy and unblameable in his sight, not in their own. The verdict is rendered where it counts.",
    '1:23': "Continuing is not how the reconciliation is earned but how it shows; the grounding and settling were already given.",
    '1:24': "Not the atonement's remainder: what is \"behind\" is the suffering his body still meets in the world.",
    '1:25': "A minister is a steward of a message he did not compose. The dispensation was given to him for them.",
    '1:26': "The mystery was hidden, not undiscovered. It waited on revelation rather than on cleverness.",
    '1:27': "\"Christ in you, the hope of glory\" — the secret withheld from ages turns out to be Gentiles included.",
    '1:28': "\"Every man\" three times in one verse. The warning and teaching are as wide as the preaching.",
    '1:29': "He labours and strives, but according to a working that works in him. Effort and gift are not rivals here.",

    # ---- Chapter 2 ----
    '2:1': "He agonises over congregations that have never seen his face. Pastoral concern is not limited to acquaintance.",
    '2:2': "Assurance is described as riches. Certainty about Christ is treated as wealth, not as a temperament.",
    '2:3': "All the treasures are hidden in Christ, which means the advanced knowledge on offer elsewhere is not advanced.",
    '2:4': "\"Enticing words\" — the danger is named as persuasiveness, not as obvious error.",
    '2:5': "He praises their order and steadfastness in the same breath as warning them. Commendation is not a softening tactic.",
    '2:6': "The way forward is the way in: they received Christ by faith, and they walk the same way.",
    '2:7': "Rooted, built, established — and the growth is \"as ye have been taught,\" not beyond it.",
    '2:8': "Philosophy is not condemned as such; being carried off as plunder by it is.",
    '2:9': "\"Bodily.\" The fulness of God is not diffused through intermediaries but housed in one man.",
    '2:10': "\"Ye are complete in him.\" Whatever the new teaching promised to add, the addition would be to a full cup.",
    '2:11': "A circumcision made without hands: the mark they were being pressed to take has already been given invisibly.",
    '2:12': "Buried and risen in baptism, and the faith rests on \"the operation of God,\" not on the strength of the believing.",
    '2:13': "Dead men are quickened before they are improved, and the forgiveness is of \"all trespasses.\"",
    '2:14': "The record against us was not shredded quietly. It was nailed up in public on the cross.",
    '2:15': "The powers were disarmed at the very moment he looked most defeated. The cross is described as a triumphal procession.",
    '2:16': "Food, festival, sabbath — he does not defend their choices, he denies anyone the right to judge them.",
    '2:17': "\"The body is of Christ.\" Shadows are not falsehoods; they are simply what stops mattering once the thing arrives.",
    '2:18': "\"Vainly puffed up by his fleshly mind\" — the humility on display is itself the pride.",
    '2:19': "Growth comes from the Head through the body's own joints. A spirituality that bypasses the church starves.",
    '2:20': "Having died with Christ to the world's rudiments, submitting to them again is treated as a category error.",
    '2:21': "\"Touch not; taste not; handle not\" — the slogans are quoted flatly, without argument, because quoting them is the argument.",
    '2:22': "The rules govern things that perish in the using. A regime built on the temporary cannot be ultimate.",
    '2:23': "Severity toward the body looks like wisdom and does nothing about the appetite it was meant to curb.",

    # ---- Chapter 3 ----
    '3:1': "The command to seek follows from having been raised. Ethics begins in the indicative, not the imperative.",
    '3:2': "Affection is something set, deliberately, rather than something felt and then followed.",
    '3:3': "\"Your life is hid with Christ in God.\" Assurance is placed somewhere the believer cannot inspect it or lose it.",
    '3:4': "The hidden life will be made public when he is. Their appearing waits on his.",
    '3:5': "Covetousness is called idolatry outright, which puts a respectable sin in the same list as fornication.",
    '3:6': "The wrath is named without hedging, and it is directed at the things, and at those who keep living in them.",
    '3:7': "\"Ye also walked some time.\" The list is not about other people; it is their own biography.",
    '3:8': "The second list is all sins of temper and speech, and it is given the same weight as the first.",
    '3:9': "Lying is forbidden on the ground of what has already happened: the old man is off, so the old habits are inconsistent.",
    '3:10': "The new man is renewed \"after the image of him that created him\" — restoration, not novelty.",
    '3:11': "Scythian, the byword for barbarism, is included. No category of person survives as a category here.",
    '3:12': "\"Elect of God, holy and beloved\" is the standing; the virtues are put on over it, not to acquire it.",
    '3:13': "The measure of forgiveness is \"even as Christ forgave you\" — the pattern precedes and outsizes the demand.",
    '3:14': "Charity is what holds the other virtues together; without it the list is a set of unconnected efforts.",
    '3:15': "Peace is to \"rule\" — to act as umpire — in hearts that belong to one body, so the ruling is not a private mood.",
    '3:16': "The word dwelling richly shows up as singing. Doctrine ends in congregational music, not in private mastery.",
    '3:17': "Word and deed alike are done in his name, which leaves no zone of life that is merely neutral.",
    '3:18': "\"As it is fit in the Lord\" — the qualification is there, and it sets a limit on what can be asked.",
    '3:19': "The command to husbands includes a specific prohibition: bitterness, the quiet form of harshness.",
    '3:20': "The motive given to children is not household peace but what pleases the Lord.",
    '3:21': "Fathers can provoke children into discouragement, and Paul treats that outcome as the father's doing.",
    '3:22': "\"Not with eyeservice, as menpleasers\" — work done only when watched is named for what it is.",
    '3:23': "Ordinary labour is done \"as to the Lord,\" which makes the slave's work and the apostle's the same kind of thing.",
    '3:24': "A slave, who could inherit nothing, is told of an inheritance and called a servant of Christ instead.",
    '3:25': "\"No respect of persons\" is said to slaves, then masters are addressed next. The same court hears both.",

    # ---- Chapter 4 ----
    '4:1': "Masters are told they have a Master. The chain of command does not stop at the top of the household.",
    '4:2': "Watchfulness and thanksgiving are attached to persistence in prayer, as though prayer could be done asleep.",
    '4:3': "The prisoner asks for an open door for the word, not for an open door out.",
    '4:4': "Even the apostle asks for help to say it clearly. Clarity is treated as something granted.",
    '4:5': "\"Them that are without\" are to be met with wisdom and time well bought, not with argument.",
    '4:6': "Speech seasoned with salt is speech worth tasting, and the aim is to answer each man, not all men alike.",
    '4:9': "Onesimus, the runaway slave, is introduced as \"a faithful and beloved brother, who is one of you.\"",
    '4:10': "Mark, who once walked out on Paul, is here recommended in advance: \"if he come unto you, receive him.\"",
    '4:11': "\"These only are my fellowworkers.\" Paul counts the Jewish believers still with him, and the number is small.",
    '4:12': "Epaphras labours in prayer the way others labour in travel — and the thing he asks for them is maturity.",
    '4:16': "The letters were meant to circulate. Nothing in them was written for one congregation's private use.",
    '4:17': "A word to one man, sent through the whole church, so that the congregation hears the charge he was given.",
    '4:18': "\"Remember my bonds.\" The last thing in his own handwriting is not instruction but a request not to be forgotten.",
}
