#!/usr/bin/env python3
"""Written one-line takeaways for 2 Corinthians.

Each states what the verse turns on. Greetings, travel notes and bare
connectives are left out deliberately; the drawer hides the card rather
than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Addressed past Corinth to all Achaia. A letter about a private quarrel is written to be read widely.",
    '1:3': "Father of mercies, God of all comfort — the titles a man picks when he is writing out of trouble.",
    '1:4': "Comfort is given in order to be handed on. It is not allowed to stop with the person comforted.",
    '1:5': "Sufferings and consolation are measured against each other, and the scale is said to match.",
    '1:6': "Even his affliction is entered on their account. Nothing that happens to him is only his.",
    '1:7': "Partakers of the sufferings and of the consolation. The two are not offered as alternatives.",
    '1:8': "\"We despaired even of life.\" An apostle puts despair in writing and attaches no lesson to it.",
    '1:9': "The sentence of death had a purpose: to end any remaining trust in himself.",
    '1:10': "Delivered, doth deliver, will deliver. Three tenses, and the middle one is the hardest to hold.",
    '1:11': "Their praying is written into the machinery, so that the thanks afterwards belongs to many.",
    '1:12': "His one boast is a clear conscience, and even that he credits to grace rather than to character.",
    '1:13': "\"We write none other things than what ye read.\" No second meaning waiting behind the letter.",
    '1:14': "The relationship is dated forward. What they are to each other is settled in the day of the Lord.",
    '1:15': "The whole breach began with a changed travel plan and a visit that never happened.",
    '1:17': "The charge is that he is unreliable, and he takes it seriously enough to answer it for two chapters.",
    '1:18': "He stakes the truthfulness of God on whether his own word to them was yes and no.",
    '1:19': "The argument moves from Paul's reliability to Christ's, because the first was never the real question.",
    '1:20': "Every promise God ever made is kept in one place, and the Amen is said there too.",
    '1:21': "Establishing and anointing are both God's verbs, and they are in the present tense.",
    '1:22': "The Spirit is called an earnest — a down payment, which commits the payer to the rest of the sum.",
    '1:23': "The absence they held against him is explained as mercy: he stayed away in order to spare them.",
    '1:24': "\"Not dominion over your faith.\" An apostle declining the authority he is being accused of misusing.",

    # ---- Chapter 2 ----
    '2:1': "He decides against a second painful visit, and the pain he is weighing is theirs.",
    '2:2': "The only people who could cheer him up are the ones he has just made sorry.",
    '2:3': "He wrote rather than came. The severe letter was the gentler of the two options open to him.",
    '2:4': "\"With many tears.\" He tells them what the harsh letter actually was: love, written badly on purpose.",
    '2:5': "\"He hath not grieved me, but in part.\" He refuses to cast himself as the injured party.",
    '2:6': "The punishment is called sufficient, which means discipline in this church is given an ending.",
    '2:7': "The danger has changed sides: the man is now at risk of being swallowed up by too much sorrow.",
    '2:8': "Love is to be confirmed — ratified publicly, in the same assembly that voted the punishment.",
    '2:9': "He admits the letter had a second purpose: it was a test of whether they would obey at all.",
    '2:10': "He follows their forgiveness rather than leading it, and does it in the presence of Christ.",
    '2:11': "The advantage Satan is looking for is a congregation that will not let a man back in.",
    '2:13': "A door opened by the Lord at Troas, and he walked away from it because Titus had not come.",
    '2:14': "The triumph is a Roman procession, and the apostles are walking in it as the captives.",
    '2:15': "The same fragrance rises whether men are saved or perish. The gospel does not change to suit its result.",
    '2:16': "\"Who is sufficient for these things?\" The question is left standing, and the chapter ends on it.",
    '2:17': "The word for corrupting the word is a wine-seller's word. His rivals are accused of watering it.",

    # ---- Chapter 3 ----
    '3:1': "Letters of commendation were the ordinary credential, and he declines to produce one.",
    '3:2': "\"Ye are our epistle.\" The congregation is the reference letter, and it is being read by everyone.",
    '3:3': "Written with the Spirit on hearts of flesh. Jeremiah and Ezekiel are pressed into a defence of a ministry.",
    '3:4': "Whatever confidence he has is held through Christ and directed toward God, not toward his record.",
    '3:5': "Not sufficient even to think anything as of ourselves. The disclaimer reaches down to the thoughts.",
    '3:6': "\"The letter killeth, but the spirit giveth life.\" Law and gospel distinguished in six words.",
    '3:7': "He grants the old covenant its glory first, and calls the ministry of death glorious without irony.",
    '3:8': "The argument is from greater to greater. Nothing is won here by making the first covenant small.",
    '3:9': "Condemnation and righteousness are both named ministries. The law was doing a real job, not a failed one.",
    '3:10': "The earlier glory is eclipsed rather than denied — outshone by something standing next to it.",
    '3:11': "The difference between them is not brightness but duration: one is passing, the other remains.",
    '3:12': "The hope produces bluntness. Plain speech is presented as a consequence of confidence, not of temperament.",
    '3:13': "The veil is read as hiding a fading glory — a reason Exodus itself never gives for it.",
    '3:14': "The veil has moved from a face to a reading. It now lies over a text rather than over a man.",
    '3:15': "And then it moves again, from the page to the heart, where no amount of reading can reach it.",
    '3:16': "The veil is not studied away. It is removed in the turning, and by someone other than the reader.",
    '3:17': "Liberty is located in a presence rather than in a permission. Where the Spirit is, it is already there.",
    '3:18': "\"Are changed\" is passive, and the means is looking. Nobody in this sentence transforms himself.",

    # ---- Chapter 4 ----
    '4:1': "\"As we have received mercy, we faint not.\" The stamina is traced to mercy, not to resolve.",
    '4:2': "Handling the word of God deceitfully was evidently a live option, or there would be nothing to renounce.",
    '4:3': "If the gospel is hidden, he will not locate the fault in the message or in his own delivery.",
    '4:4': "Unbelief is described as a blinding done to a man, which makes it worse than a bad decision.",
    '4:5': "\"We preach not ourselves\" — and the rest of the sentence makes him their servant, for Jesus' sake.",
    '4:6': "The light of Genesis shines into a heart, and what it shows is a face.",
    '4:7': "The cheapness of the pot is not an embarrassment to the plan. It is the plan.",
    '4:8': "Each concession is made fully before it is qualified. He is troubled, and he is perplexed, and he says so.",
    '4:9': "Persecuted but not forsaken. The denial is never that it happened, only that it finished him.",
    '4:10': "The body carries the dying of Jesus around so that the living of Jesus has somewhere to show.",
    '4:12': "\"Death worketh in us, but life in you.\" The cost lands on one side and the benefit on the other.",
    '4:13': "\"I believed, and therefore have I spoken.\" Speaking is the consequence of faith, which is why he cannot stop.",
    '4:14': "The resurrection he expects is a corporate one: raised, and presented together with them.",
    '4:15': "The chain runs grace, thanksgiving, glory — and the thanksgiving is other people's, not his.",
    '4:16': "Outward man perishing and inward man renewed, both asserted as present facts, neither cancelling the other.",
    '4:17': "\"Light affliction, which is but for a moment\" — written by the man who despaired of his life in chapter one.",
    '4:18': "Looking at what cannot be seen is what makes the weighing possible. Without it the affliction is just heavy.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "A tent against a building. He is writing about his own body wearing out, and he knows it.",
    '5:2': "The groaning is a kind of desiring. It is not complaint but appetite for something not yet given.",
    '5:4': "\"Not for that we would be unclothed, but clothed upon.\" He wants more body, not escape from it.",
    '5:5': "God manufactured the longing itself, and then handed over the Spirit as the receipt for it.",
    '5:6': "At home in the body means absent from the Lord. The present arrangement is named as a real cost.",
    '5:7': "Faith is set against sight, which means it is a way of walking rather than a quality of feeling.",
    '5:8': "He would rather be away from the body, and he states the preference without insulting the body.",
    '5:9': "Present or absent, the aim does not move. The circumstances change and the labour does not.",
    '5:10': "What is assessed is \"the things done in his body,\" which is why the whole chapter argues about bodies.",
    '5:11': "\"The terror of the Lord\" is given as the reason he persuades men, not as something he preaches to them.",
    '5:12': "He is not defending himself. He is arming them with an answer for the people who glory in appearance.",
    '5:13': "Beside himself or sober, both are accounted for, and neither one is apologized for.",
    '5:14': "Constraineth, not inspires. The love of Christ presses in from the sides rather than lifting from above.",
    '5:15': "The purpose of the death is stated as a change of address: living no longer to oneself.",
    '5:16': "Even Christ is no longer known after the flesh. The outward measure is retired, and he starts with himself.",
    '5:17': "A new creature is announced, not felt. The old things passing away is a report before it is an experience.",
    '5:18': "Reconciliation is first something done and then something handed over as a job to do.",
    '5:19': "\"Not imputing their trespasses unto them.\" The mechanism is accounting: the charges are not entered.",
    '5:20': "Ambassadors begging. And the plea to be reconciled is addressed to a church, not to outsiders.",
    '5:21': "He was made sin who knew none, so that we might be made righteousness. Neither side earned its half.",

    # ---- Chapter 6 ----
    '6:1': "Grace can be received and still come to nothing. That possibility is what the appeal rests on.",
    '6:2': "An old oracle is turned into an emergency. The accepted time is dragged forward into the word now.",
    '6:3': "The care taken is not for his reputation but so that nobody can blame the ministry itself.",
    '6:4': "Patience heads the list of credentials, and everything after it is a hardship rather than an achievement.",
    '6:5': "Stripes, prisons, sleeplessness, hunger. The résumé is largely a list of things done to him.",
    '6:6': "Halfway through the list it turns from what he endured to what he is: pureness, kindness, love unfeigned.",
    '6:7': "Armour on the right hand and on the left, which covers the attack and the retreat at once.",
    '6:8': "\"As deceivers, and yet true.\" He picks up his critics' word for him and sets it down beside the truth.",
    '6:9': "Unknown and well known, dying and alive, chastened and not killed. Both halves are reported as facts.",
    '6:10': "Poor yet making many rich, having nothing and possessing all things. The ledger refuses to balance.",
    '6:11': "\"Our heart is enlarged.\" He describes the openness he is offering before asking for anything back.",
    '6:12': "The narrowness is on their side, and he says so plainly instead of pretending the distance is mutual.",
    '6:13': "The only thing he asks in return for everything in the list is that they widen toward him.",
    '6:14': "A farming image about mismatched animals pulling one plough, applied to alliances that cannot pull together.",
    '6:16': "The quotation he lands on is about God dwelling and walking among them, not about keeping clear of others.",
    '6:17': "\"Come out... and I will receive you.\" The separation is not the goal; being received is.",
    '6:18': "The line of quotations ends in a family — Father, sons and daughters — rather than in a boundary.",

    # ---- Chapter 7 ----
    '7:1': "The promises come first and the cleansing follows from them. The order is doing the work.",
    '7:2': "Three denials in a row, which tells you there were three accusations in circulation.",
    '7:3': "He breaks off his own defence to make sure it is not heard as an accusation against them.",
    '7:4': "The joy is located in the tribulation rather than after it. He does not wait for the trouble to end.",
    '7:5': "\"Without were fightings, within were fears.\" He names the inward fear as readily as the outward fight.",
    '7:6': "God comforts the cast down, and here the comfort arrives as a colleague walking through the door.",
    '7:7': "The consolation travels along a chain: they comforted Titus, and Titus brought it to Paul.",
    '7:8': "\"I do not repent, though I did repent.\" He admits he had regretted sending the letter at all.",
    '7:9': "His gladness is not that they were hurt but that the hurt moved them somewhere.",
    '7:10': "Two sorrows that look identical from outside. One works repentance and the other works death.",
    '7:11': "Seven things their sorrow produced, ending with revenge. Real repentance is not described as calm.",
    '7:12': "The severe letter was written for neither the offender nor the victim, but so his care would become visible.",
    '7:14': "He had staked his own credibility on them to Titus, and says he is relieved the boast held up.",
    '7:15': "Titus remembers being received with fear and trembling. They treated the messenger better than the letter.",
    '7:16': "\"I have confidence in you in all things\" — an interesting note to end on, one verse before asking for money.",

    # ---- Chapter 8 ----
    '8:1': "The collection is introduced as grace bestowed on the givers, not as generosity produced by them.",
    '8:2': "Deep poverty abounding into riches of liberality. The arithmetic is wrong and he leaves it standing.",
    '8:3': "Beyond their power, and of themselves. No pressure was applied, which is why he can tell the story.",
    '8:4': "They had to beg for permission to give. The appeal in Macedonia ran in the opposite direction.",
    '8:5': "\"First gave their own selves to the Lord.\" The money went where the person had already gone.",
    '8:6': "The collection is called a grace, and Titus is sent to finish it rather than to organize it.",
    '8:7': "Giving is set in the list beside faith, utterance and knowledge, as one more thing to abound in.",
    '8:8': "\"Not by commandment.\" He declines to make it an order, which leaves it a test of something else.",
    '8:9': "The incarnation is put to work in a fundraising letter, and summarized in one sentence about money.",
    '8:10': "Advice rather than instruction, and the reminder that this was their own idea a year ago.",
    '8:11': "Readiness to will and performance are held apart. The enthusiasm was real and the money was not sent.",
    '8:12': "Accepted according to what a man has. The measure is proportion, which makes small gifts uncountable.",
    '8:13': "He explicitly rules out impoverishing one church to relieve another.",
    '8:14': "The flow is expected to reverse someday. Today's donor is written into the plan as tomorrow's recipient.",
    '8:15': "The manna text: gathering much and gathering little came out the same by the end of the day.",
    '8:16': "Even a colleague's enthusiasm is credited upward. God put the care into Titus, so God gets the thanks.",
    '8:17': "Titus went of his own accord. The exhortation was accepted, and then overtaken by willingness.",
    '8:19': "The churches elected the man who carries the money. The appointment was not Paul's to make.",
    '8:20': "The procedure exists because someone will suspect him, and he treats that suspicion as reasonable.",
    '8:21': "Honest in the sight of the Lord is not enough. It has to be visible to men as well.",
    '8:24': "The proof asked for is of love, and it is to be shown before the churches rather than privately.",
})

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:1': "\"Superfluous for me to write to you\" — and then he writes another fifteen verses about it.",
    '9:2': "He has already boasted about Achaia to the Macedonians, which puts his own credit on the line.",
    '9:3': "The brethren go ahead so the boast does not collapse. The anxiety is practical and he admits it.",
    '9:4': "\"We (that we say not, ye) should be ashamed.\" The correction mid-sentence says exactly what he means.",
    '9:5': "Collected beforehand so that it arrives as bounty rather than as something squeezed out on the day.",
    '9:6': "Sowing and reaping, and he never specifies the harvest. The image is left agricultural, not transactional.",
    '9:7': "Not grudgingly, not of necessity. The manner of the giving is weighed more carefully than the amount.",
    '9:8': "Sufficiency in all things is given so that it can be spent on every good work, not banked.",
    '9:9': "The quotation defines a lasting righteousness as dispersing abroad. Permanence looks like letting go.",
    '9:10': "God supplies the seed before the sowing. Even the capacity to give was handed to the giver.",
    '9:12': "The collection does two jobs at once: it fills an empty stomach and it raises thanksgiving to God.",
    '9:13': "Gentile money reaching Jerusalem will make Jerusalem glorify God. The gift is aimed at a gulf.",
    '9:14': "What comes back is longing and prayer. The donors gain the affection of people they never met.",
    '9:15': "Two chapters of careful accounting end on the one gift that cannot be priced or described.",

    # ---- Chapter 10 ----
    '10:1': "\"In presence am base among you, but being absent am bold.\" He quotes the accusation in his own voice.",
    '10:2': "He is pleading to be spared the need to use the authority he is accused of not really having.",
    '10:3': "Walking in the flesh is conceded. Warring after the flesh is the thing denied.",
    '10:4': "Siege language: strongholds pulled down. The battlefield being described is made of arguments.",
    '10:5': "Every thought brought into captivity. What is taken prisoner here is reasoning, not behaviour.",
    '10:6': "He will deal with the disobedient only after the obedient are settled. The loyal are not made to wait.",
    '10:7': "\"Do ye look on things after the outward appearance?\" The whole quarrel is about how a man looks.",
    '10:8': "The authority is for building up and not for pulling down, and he sets that limit on himself.",
    '10:10': "He prints his critics' review word for word: weak presence, contemptible speech. He does not soften it.",
    '10:11': "The only answer he offers to the charge is that the letters and the man will turn out to match.",
    '10:12': "Measuring themselves by themselves is a closed circle. It cannot return a disappointing result.",
    '10:13': "The measure is one God distributed. His territory was assigned to him rather than taken.",
    '10:14': "The claim is simply that he got there first, with the gospel, before any of the rivals arrived.",
    '10:15': "Boasting in other men's labours is what he refuses. Corinth is somebody else's work to the newcomers.",
    '10:16': "His ambition points at the regions beyond, not at a congregation another man has already prepared.",
    '10:17': "He quotes his own first letter back at the problem, because the problem has not changed.",
    '10:18': "The approval that counts is not self-issued, which disposes of the entire credential contest.",

    # ---- Chapter 11 ----
    '11:1': "He labels the speech folly before he makes it, and asks to be endured rather than admired.",
    '11:2': "The jealousy is called godly, and the picture is a father handing a bride over at the door.",
    '11:3': "The danger named is not immorality but sophistication — losing the simplicity that is in Christ.",
    '11:4': "\"Ye might well bear with him.\" They put up with rivals more patiently than with the man who founded them.",
    '11:5': "\"The very chiefest apostles\" is almost certainly their phrase, handed back with the edge left on.",
    '11:6': "He concedes the criticism of his speaking outright and contests only what the speaking carried.",
    '11:7': "Preaching to them without charge has been turned into a charge against him.",
    '11:8': "\"I robbed other churches.\" He chooses a criminal word for what other people call support.",
    '11:9': "Costing them nothing is a settled policy, not an accident of one visit, and he says he will keep it.",
    '11:10': "Of everything in dispute, this is the one point he announces he will never concede.",
    '11:11': "He states the reading they have put on his refusal, and answers it with two words: God knoweth.",
    '11:12': "The refusal of money is also tactical. It denies his rivals the one comparison they could win.",
    '11:13': "False apostles are described as transforming themselves, which means the disguise is deliberate work.",
    '11:14': "Satan appears as an angel of light. The best deception does not look dark; it looks better than you.",
    '11:15': "His ministers come as ministers of righteousness. The counterfeit imitates virtue, not vice.",
    '11:16': "He keeps apologizing for what he is about to say, which is itself part of what he is saying.",
    '11:17': "\"I speak it not after the Lord.\" He marks the boasting as unlike Christ even while he does it.",
    '11:18': "He enters a competition he despises, on its own terms, in order to wreck it from inside.",
    '11:19': "\"Ye suffer fools gladly, seeing ye yourselves are wise.\" The sharpest line he ever wrote to them.",
    '11:20': "Bondage, devouring, a slap in the face — and they call it leadership and put up with it.",
    '11:21': "He takes up the charge of weakness ironically here, and will be holding it in earnest ten verses later.",
    '11:22': "Hebrew, Israelite, seed of Abraham. He matches the credentials item for item and gains nothing by it.",
    '11:23': "\"I am more\" — and the evidence produced is labours, stripes, prisons and brushes with death.",
    '11:24': "Five floggings, thirty-nine strokes each. He knows the count, which means he counted them.",
    '11:25': "Rods, stoning, three shipwrecks, a day adrift at sea. Almost none of this appears in Acts.",
    '11:26': "Eight kinds of peril, and the list ends with false brethren. The worst danger was inside.",
    '11:27': "Cold and nakedness close the list. The indignities are recorded alongside the heroics.",
    '11:28': "The daily pressure of caring about churches is ranked above the beatings, and it comes last for emphasis.",
    '11:29': "\"Who is offended, and I burn not?\" Sympathy is described as something that happens in the body.",
    '11:30': "The rule of the whole speech, stated once it is nearly over: the boasting will be about weakness.",
    '11:31': "He swears he is not lying, which tells you he expects not to be believed.",
    '11:33': "The climax of the boast is a middle-aged man lowered out of a window in a laundry basket.",

    # ---- Chapter 12 ----
    '12:1': "He calls the boasting useless and proceeds anyway, which is how the entire fool's speech works.",
    '12:2': "\"I knew a man in Christ.\" The third person is a device for not quite claiming the experience.",
    '12:4': "The greatest revelation he ever had produced nothing he is permitted to pass on.",
    '12:5': "He splits himself in two: that man can be boasted of, this man can only be boasted of in weakness.",
    '12:6': "He would rather be underestimated than let anyone think of him above what they can actually see.",
    '12:7': "\"There was given\" — a passive verb, and the giver is not Satan, whose messenger merely does the work.",
    '12:8': "Three prayers, the same request, like another man in a garden who also asked three times.",
    '12:9': "The prayer is refused and answered in the same sentence. What he asked to lose is what carries the power.",
    '12:10': "\"When I am weak, then am I strong.\" The letter has been walking toward this line since chapter one.",
    '12:11': "The boasting was compelled. He says the commendation should have come from them and never did.",
    '12:12': "The signs of an apostle are listed, and patience is put in front of the signs and wonders.",
    '12:13': "\"Forgive me this wrong.\" The wrong he asks pardon for is that he never took their money.",
    '12:14': "\"I seek not yours, but you.\" Parents save for children, and he puts himself on the parents' side.",
    '12:15': "Loving more and being loved less is stated as a rate of exchange he has accepted, not as a complaint.",
    '12:16': "He quotes the rumour directly: that the collection was the clever way he was taking their money after all.",
    '12:17': "He invites the audit. Name the man I sent who made a profit out of you.",
    '12:18': "Titus is produced as evidence. The defence rests on the conduct of the people he sent, not his own word.",
    '12:19': "After four chapters of defending himself, he denies that any of it was a defence.",
    '12:20': "The list of what he dreads finding — debates, envyings, whisperings — is the first letter's list again.",
    '12:21': "What he fears is his own humbling. Their unrepentance is described as something that would happen to him.",

    # ---- Chapter 13 ----
    '13:1': "The law's rule about witnesses is brought into a pastoral visit. The third trip will be a hearing.",
    '13:2': "\"I will not spare\" — a sentence written by the man they described as weak when present.",
    '13:3': "They asked for proof that Christ speaks in him. He points out what that proof would cost them.",
    '13:4': "Crucified through weakness and living by power. The pattern is Christ's first and his only afterwards.",
    '13:5': "The examination is turned around. The people auditing his apostleship are told to audit themselves.",
    '13:6': "He hopes the test they run on themselves will incidentally settle the question about him.",
    '13:7': "He would rather they do right and he look discredited than be vindicated by their failure.",
    '13:8': "\"We can do nothing against the truth.\" A limit on his authority that he places there himself.",
    '13:9': "Glad to be weak so long as they are strong. The whole ministry compressed into one clause.",
    '13:10': "The sharpness goes into the letter so that it does not have to come out in the room.",
    '13:11': "Four short imperatives and then a promise, and the promise is not conditional on the imperatives.",
    '13:14': "The fullest benediction Paul ever wrote is addressed to the congregation that gave him the most trouble.",
})
