#!/usr/bin/env python3
"""Written one-line takeaways for 1 Corinthians.

Each states what the verse turns on. Greetings, name lists and bare
connectives are left out deliberately; the drawer hides the card rather
than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"Through the will of God\" — the office rests on God's decision, not on Paul's suitability for it.",
    '1:2': "Called saints before a word of correction. Their holiness is a standing, not a report card.",
    '1:4': "He gives thanks for a church he is about to spend sixteen chapters correcting.",
    '1:5': "The gifts that became the trouble in this church are named first as gifts.",
    '1:6': "The testimony was confirmed in them, not by them. They are the evidence, not the authors.",
    '1:7': "A church behind in no gift is still a church waiting. Gifts are not the arrival.",
    '1:8': "The one who confirms them to the end is the one who will judge them at it.",
    '1:9': "\"God is faithful.\" The whole guarantee of the previous verse rests on someone else's character.",
    '1:10': "Unity is asked for at the level of speech first, because that is where the split shows.",
    '1:11': "Paul names his informants. The complaint is not allowed to circulate as rumour.",
    '1:12': "Four slogans, and the last is the worst: Christ himself turned into a party badge.",
    '1:13': "\"Was Paul crucified for you?\" The test of any name you take is whether it was on a cross.",
    '1:14': "He is relieved, not proud, about how few people he can be said to have collected.",
    '1:15': "Ministry conducted so as to leave no personal following behind it.",
    '1:16': "He cannot remember who else he baptized. The tally was never his to keep.",
    '1:17': "Polished speech can empty the cross of effect while still naming it.",
    '1:18': "The same sentence is foolishness and power. Hearers are sorted by what it does in them.",
    '1:19': "God's opposition to the wisdom of the wise is announced in advance, not stumbled into.",
    '1:20': "\"Where is the wise?\" The credentials that count everywhere else do not transfer here.",
    '1:21': "Wisdom had its chance at God and missed. Preaching is God's deliberate second method.",
    '1:22': "Sign and wisdom are two ways of asking God to arrive on the terms already set for him.",
    '1:23': "Christ crucified offends both audiences, and is preached to both without adjustment.",
    '1:24': "To the called, the very thing that scandalized becomes the power and the wisdom.",
    '1:25': "God at his supposed weakest still outmatches men at their best. The comparison is a concession.",
    '1:26': "Look around at who is actually in the room — that congregation is evidence about God's choosing.",
    '1:27': "The weak were chosen to confound the mighty. This is strategy, not a shortage of better material.",
    '1:28': "\"Things which are not, to bring to nought things that are.\" God recruits nobodies against the establishment.",
    '1:29': "The purpose of the whole arrangement is stated plainly: the silencing of human boasting.",
    '1:30': "Wisdom, righteousness, sanctification, redemption — four things, all of them arriving as a person.",
    '1:31': "Boasting is not abolished but relocated. The mouth stays open; the subject changes.",

    # ---- Chapter 2 ----
    '2:1': "He came without excellency of speech on purpose. The weaker delivery was a decision.",
    '2:2': "\"I determined not to know any thing\" — a deliberate narrowing, not the limit of his learning.",
    '2:3': "\"In weakness, and in fear, and in much trembling.\" He puts his own nerves into the record.",
    '2:4': "Demonstration of the Spirit, not enticing words: the persuading was never his to manage.",
    '2:5': "A faith that was argued into a man can be argued back out of him again.",
    '2:6': "There is wisdom here after all. It belongs to an age that the princes of this one are leaving.",
    '2:7': "Hidden wisdom \"ordained before the world.\" The mystery was planned, not improvised at the cross.",
    '2:8': "Had they known, they would not have crucified him. The ignorance is what damns rather than excuses.",
    '2:9': "What God prepared was beyond guessing. The quotation is about unavailability, not about scenery.",
    '2:10': "The verse turns on \"but\": what no eye saw has now been told out loud.",
    '2:11': "Only a man's own spirit knows the man. God is knowable only from inside God.",
    '2:12': "The Spirit's first work here is recognition — seeing what was already freely given.",
    '2:13': "Even the words are taught. The wrapping of the message is not left to human taste.",
    '2:14': "The natural man's problem is capacity, not information. More evidence would not help him.",
    '2:15': "\"Judged of no man\" — the line Corinth would most enjoy is set down exactly where it stings them.",
    '2:16': "An unanswerable question is answered by a gift: we have the mind of Christ, not access to it.",

    # ---- Chapter 3 ----
    '3:1': "A church rich in utterance and knowledge is addressed as infants. Gifting is not maturity.",
    '3:2': "\"Neither yet now are ye able.\" Years have passed and the diet has not changed.",
    '3:3': "Envy and strife, not scandal, are produced as the proof of carnality.",
    '3:4': "Preferring one preacher to another is classed as walking the way anyone walks.",
    '3:5': "\"Who then is Paul?\" The question about rank gets answered with a job description.",
    '3:6': "Planting and watering are visible; the increase is not. The indispensable worker is the invisible one.",
    '3:7': "In the accounting of growth the workers are set at zero, and Paul writes himself in first.",
    '3:8': "One work, separate wages. Labour is shared without anyone's part being absorbed.",
    '3:9': "\"Labourers together with God\" — the field belongs to him, and so does the building crew.",
    '3:10': "The warning falls on how a man builds, never on whether the foundation will hold.",
    '3:11': "The one item in the whole project not open to improvement is the part already laid.",
    '3:12': "Gold and stubble go up on the same foundation. Bad work is still built on Christ.",
    '3:13': "Fire is brought in to assess the work. The day declares it; no one declares it early.",
    '3:14': "Reward is for what survives, which means no one knows the total yet.",
    '3:15': "A man's life work burns and the man is saved. Losing everything built is not losing him.",
    '3:16': "\"Ye are the temple\" is plural. The sanctuary in view is a congregation, not a soul.",
    '3:17': "The people tearing the church into parties are told what they are actually damaging.",
    '3:18': "Becoming a fool is prescribed as the route to wisdom, and there is no other route offered.",
    '3:19': "The clever are caught in their own craftiness. Cleverness supplies the trap it falls into.",
    '3:21': "\"All things are yours.\" The parties were dividing up what each of them already owned entire.",
    '3:22': "The list of their possessions includes death. Nothing is left over to be afraid of.",
    '3:23': "The chain ends in belonging, not in owning: theirs, Christ's, God's.",

    # ---- Chapter 4 ----
    '4:1': "Steward is the key word. What he handles at the table is somebody else's property.",
    '4:2': "The one thing required of a steward is faithfulness, which is not the same as success.",
    '4:3': "He declines the congregation's verdict, and in the same breath declines his own.",
    '4:4': "\"I know nothing by myself; yet am I not hereby justified.\" A clear conscience is not an acquittal.",
    '4:5': "Every verdict waits for the one who reads hidden counsels — and it ends in praise, not exposure.",
    '4:6': "The figure was a device for keeping the real names out of a dispute about names.",
    '4:7': "\"What hast thou that thou didst not receive?\" Boasting is a gift misfiled as an achievement.",
    '4:8': "\"Ye have reigned as kings without us.\" They have taken the throne while the apostles are still dying.",
    '4:9': "The apostles come last in the procession, in the place kept for men condemned to die.",
    '4:10': "Fools and wise, weak and strong, despised and honourable: the contrast is set out to be felt.",
    '4:11': "Hunger, thirst, nakedness, no fixed address. Apostolic life described with the dignity removed.",
    '4:12': "Working with his own hands sits in the list of credentials, beside blessing those who curse him.",
    '4:13': "\"The filth of the world... the offscouring of all things.\" He picks the ugliest words for himself.",
    '4:14': "He stops and says what the irony was for. Shaming was available; he refuses it.",
    '4:15': "Instructors can be counted in the thousands. Fathers cannot, because begetting is not teaching.",
    '4:16': "After a paragraph of hunger and contempt, this is the life he invites them to copy.",
    '4:18': "Arrogance grows quickly in the space left by an absent leader who may not return.",
    '4:19': "He proposes to test the talkers by power rather than by their speech, on their own ground.",
    '4:20': "The criterion is stated flat, in a letter to people who valued eloquence above everything.",
    '4:21': "Rod or meekness — he hands the choice back to them and leaves it there.",
}
