#!/usr/bin/env python3
"""Written one-line takeaways for 1 Corinthians.

Each states what the verse turns on. Greetings, name lists and bare
connectives are left out deliberately; the drawer hides the card rather
than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"Through the will of God\" — the office rests on God's decision, not on Paul's suitability for it.",
    '1:2': "Called saints before a word of correction. Their holiness is a standing, not a report card.",
    '1:4': "He gives thanks for a church he is about to spend sixteen chapters correcting.",
    '1:5': "The gifts that became the trouble in this church are named first as gifts.",
    '1:6': "The testimony was confirmed in them, not by them. They are the evidence, not the authors.",
    '1:7': "A church behind in no gift is still a church waiting. Gifts are not the arrival.",
    '1:8': "The one who confirms them to the end is the one who will judge them at it.",
    '1:9': "\"God is faithful.\" The whole guarantee of the previous verse rests on someone else's character.",
    '1:10': "Unity is asked for at the level of speech first, because that is where the split shows.",
    '1:11': "Paul names his informants. The complaint is not allowed to circulate as rumour.",
    '1:12': "Four slogans, and the last is the worst: Christ himself turned into a party badge.",
    '1:13': "\"Was Paul crucified for you?\" The test of any name you take is whether it was on a cross.",
    '1:14': "He is relieved, not proud, about how few people he can be said to have collected.",
    '1:15': "Ministry conducted so as to leave no personal following behind it.",
    '1:16': "He cannot remember who else he baptized. The tally was never his to keep.",
    '1:17': "Polished speech can empty the cross of effect while still naming it.",
    '1:18': "The same sentence is foolishness and power. Hearers are sorted by what it does in them.",
    '1:19': "God's opposition to the wisdom of the wise is announced in advance, not stumbled into.",
    '1:20': "\"Where is the wise?\" The credentials that count everywhere else do not transfer here.",
    '1:21': "Wisdom had its chance at God and missed. Preaching is God's deliberate second method.",
    '1:22': "Sign and wisdom are two ways of asking God to arrive on the terms already set for him.",
    '1:23': "Christ crucified offends both audiences, and is preached to both without adjustment.",
    '1:24': "To the called, the very thing that scandalized becomes the power and the wisdom.",
    '1:25': "God at his supposed weakest still outmatches men at their best. The comparison is a concession.",
    '1:26': "Look around at who is actually in the room — that congregation is evidence about God's choosing.",
    '1:27': "The weak were chosen to confound the mighty. This is strategy, not a shortage of better material.",
    '1:28': "\"Things which are not, to bring to nought things that are.\" God recruits nobodies against the establishment.",
    '1:29': "The purpose of the whole arrangement is stated plainly: the silencing of human boasting.",
    '1:30': "Wisdom, righteousness, sanctification, redemption — four things, all of them arriving as a person.",
    '1:31': "Boasting is not abolished but relocated. The mouth stays open; the subject changes.",

    # ---- Chapter 2 ----
    '2:1': "He came without excellency of speech on purpose. The weaker delivery was a decision.",
    '2:2': "\"I determined not to know any thing\" — a deliberate narrowing, not the limit of his learning.",
    '2:3': "\"In weakness, and in fear, and in much trembling.\" He puts his own nerves into the record.",
    '2:4': "Demonstration of the Spirit, not enticing words: the persuading was never his to manage.",
    '2:5': "A faith that was argued into a man can be argued back out of him again.",
    '2:6': "There is wisdom here after all. It belongs to an age that the princes of this one are leaving.",
    '2:7': "Hidden wisdom \"ordained before the world.\" The mystery was planned, not improvised at the cross.",
    '2:8': "Had they known, they would not have crucified him. The ignorance is what damns rather than excuses.",
    '2:9': "What God prepared was beyond guessing. The quotation is about unavailability, not about scenery.",
    '2:10': "The verse turns on \"but\": what no eye saw has now been told out loud.",
    '2:11': "Only a man's own spirit knows the man. God is knowable only from inside God.",
    '2:12': "The Spirit's first work here is recognition — seeing what was already freely given.",
    '2:13': "Even the words are taught. The wrapping of the message is not left to human taste.",
    '2:14': "The natural man's problem is capacity, not information. More evidence would not help him.",
    '2:15': "\"Judged of no man\" — the line Corinth would most enjoy is set down exactly where it stings them.",
    '2:16': "An unanswerable question is answered by a gift: we have the mind of Christ, not access to it.",

    # ---- Chapter 3 ----
    '3:1': "A church rich in utterance and knowledge is addressed as infants. Gifting is not maturity.",
    '3:2': "\"Neither yet now are ye able.\" Years have passed and the diet has not changed.",
    '3:3': "Envy and strife, not scandal, are produced as the proof of carnality.",
    '3:4': "Preferring one preacher to another is classed as walking the way anyone walks.",
    '3:5': "\"Who then is Paul?\" The question about rank gets answered with a job description.",
    '3:6': "Planting and watering are visible; the increase is not. The indispensable worker is the invisible one.",
    '3:7': "In the accounting of growth the workers are set at zero, and Paul writes himself in first.",
    '3:8': "One work, separate wages. Labour is shared without anyone's part being absorbed.",
    '3:9': "\"Labourers together with God\" — the field belongs to him, and so does the building crew.",
    '3:10': "The warning falls on how a man builds, never on whether the foundation will hold.",
    '3:11': "The one item in the whole project not open to improvement is the part already laid.",
    '3:12': "Gold and stubble go up on the same foundation. Bad work is still built on Christ.",
    '3:13': "Fire is brought in to assess the work. The day declares it; no one declares it early.",
    '3:14': "Reward is for what survives, which means no one knows the total yet.",
    '3:15': "A man's life work burns and the man is saved. Losing everything built is not losing him.",
    '3:16': "\"Ye are the temple\" is plural. The sanctuary in view is a congregation, not a soul.",
    '3:17': "The people tearing the church into parties are told what they are actually damaging.",
    '3:18': "Becoming a fool is prescribed as the route to wisdom, and there is no other route offered.",
    '3:19': "The clever are caught in their own craftiness. Cleverness supplies the trap it falls into.",
    '3:21': "\"All things are yours.\" The parties were dividing up what each of them already owned entire.",
    '3:22': "The list of their possessions includes death. Nothing is left over to be afraid of.",
    '3:23': "The chain ends in belonging, not in owning: theirs, Christ's, God's.",

    # ---- Chapter 4 ----
    '4:1': "Steward is the key word. What he handles at the table is somebody else's property.",
    '4:2': "The one thing required of a steward is faithfulness, which is not the same as success.",
    '4:3': "He declines the congregation's verdict, and in the same breath declines his own.",
    '4:4': "\"I know nothing by myself; yet am I not hereby justified.\" A clear conscience is not an acquittal.",
    '4:5': "Every verdict waits for the one who reads hidden counsels — and it ends in praise, not exposure.",
    '4:6': "The figure was a device for keeping the real names out of a dispute about names.",
    '4:7': "\"What hast thou that thou didst not receive?\" Boasting is a gift misfiled as an achievement.",
    '4:8': "\"Ye have reigned as kings without us.\" They have taken the throne while the apostles are still dying.",
    '4:9': "The apostles come last in the procession, in the place kept for men condemned to die.",
    '4:10': "Fools and wise, weak and strong, despised and honourable: the contrast is set out to be felt.",
    '4:11': "Hunger, thirst, nakedness, no fixed address. Apostolic life described with the dignity removed.",
    '4:12': "Working with his own hands sits in the list of credentials, beside blessing those who curse him.",
    '4:13': "\"The filth of the world... the offscouring of all things.\" He picks the ugliest words for himself.",
    '4:14': "He stops and says what the irony was for. Shaming was available; he refuses it.",
    '4:15': "Instructors can be counted in the thousands. Fathers cannot, because begetting is not teaching.",
    '4:16': "After a paragraph of hunger and contempt, this is the life he invites them to copy.",
    '4:18': "Arrogance grows quickly in the space left by an absent leader who may not return.",
    '4:19': "He proposes to test the talkers by power rather than by their speech, on their own ground.",
    '4:20': "The criterion is stated flat, in a letter to people who valued eloquence above everything.",
    '4:21': "Rod or meekness — he hands the choice back to them and leaves it there.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "A sin \"not so much as named among the Gentiles.\" The church has outdone the pagan city it sits in.",
    '5:2': "What appals him is not the deed but the mood around it — puffed up where they should be mourning.",
    '5:3': "Absent in body and unwilling to treat absence as an excuse for having no verdict.",
    '5:4': "The sentence is carried out by an assembled congregation, not by a letter arriving in the post.",
    '5:5': "The harshest sentence in the letter is passed with the man's final salvation as its stated aim.",
    '5:6': "The question is not how bad one man is but how fast a lump changes once leaven is in it.",
    '5:7': "\"Purge out... as ye are unleavened.\" They are told to become what they have already been made.",
    '5:8': "Malice and wickedness are set on the same shelf as the sin that opened the chapter.",
    '5:9': "An earlier letter had already said this, and they had read it in the most convenient way.",
    '5:10': "Withdrawal from immoral outsiders would mean leaving the world. That was never the instruction.",
    '5:11': "The list runs from fornicator to railer. The tongue sins sit in it without being softened.",
    '5:12': "The church's judging is aimed inward at its own, which is the exact reverse of the instinct.",
    '5:13': "Those outside are left to God. The single decision entrusted to the congregation is this one.",

    # ---- Chapter 6 ----
    '6:1': "\"Dare any of you\" — the scandal is the venue, before anything is said about the dispute itself.",
    '6:2': "A people who will judge the world are asking outsiders to settle a quarrel about money.",
    '6:3': "Judging angels is thrown in to make the present lawsuit look as small as it is.",
    '6:4': "Even the least regarded member of the congregation is treated as a better bench than the court.",
    '6:5': "A church famous for its wisdom cannot produce one man able to arbitrate between two brothers.",
    '6:6': "Brother against brother, and unbelievers watching. The audience is part of the injury.",
    '6:7': "Going to law is already the defeat. \"Why do ye not rather take wrong?\" assumes losing is survivable.",
    '6:8': "The plaintiffs turn out to be defrauders themselves, and the wronged parties are their own brethren.",
    '6:9': "\"Be not deceived\" is addressed to people confident the list could not possibly include them.",
    '6:11': "\"Such were some of you.\" Washed, sanctified, justified — every verb is something done to them.",
    '6:12': "Their slogan is quoted back and then fenced: a freedom that ends in bondage has stopped being one.",
    '6:13': "Food and stomach are both temporary. The argument fails the moment it is applied to the body.",
    '6:14': "The body's resurrection is made the reason for what is done with the body now.",
    '6:15': "The union already in place is what makes the other union unthinkable, not a rule against it.",
    '6:16': "Genesis on one flesh is quoted about a prostitute — applied where nobody wanted it applied.",
    '6:17': "\"One spirit\" is set parallel to \"one body.\" Both unions are real; that is the whole problem.",
    '6:18': "The one instruction here is simply to leave. No argument is offered for standing your ground.",
    '6:19': "Temple language, used of the congregation in chapter three, is now brought down to one body.",
    '6:20': "\"Bought with a price.\" Ownership has changed hands, and the body is where the new owner is honoured.",

    # ---- Chapter 7 ----
    '7:1': "He is answering their letter, and the opening line may be their slogan rather than his.",
    '7:2': "Marriage is named as the ordinary provision, not as the concession for those who could not manage.",
    '7:3': "\"Due benevolence\" — what is rendered here is owed, which makes withholding it a default, not a discipline.",
    '7:4': "The wife has authority over the husband's body. The symmetry is stated without qualification.",
    '7:5': "The exception is fenced on every side: by consent, for a time, and ending in coming together again.",
    '7:6': "\"By permission, and not of commandment.\" He marks which of his own words are binding.",
    '7:7': "Celibacy and marriage are both filed under gift. Neither is the achievement of the person holding it.",
    '7:8': "He commends his own condition to the unmarried without once turning it into a requirement.",
    '7:9': "\"Better to marry than to burn\" is an unromantic reason for marriage, and he lets it stand.",
    '7:10': "\"Not I, but the Lord.\" He distinguishes the dominical word from his own judgment in public.",
    '7:11': "If she departs, both roads lead back: unmarried or reconciled. The door is deliberately left ajar.",
    '7:12': "\"Speak I, not the Lord.\" Cases Jesus never addressed still get a pastoral answer rather than silence.",
    '7:14': "In a mixed house the holiness travels outward. Contamination is not assumed to run the other way.",
    '7:15': "If the unbeliever leaves, the believer is not to hold the marriage shut by force. Peace outranks the tie.",
    '7:16': "The saving of a spouse is uncertain, which undercuts both staying at any cost and leaving in despair.",
    '7:17': "The rule is to walk where God has already put you, and he says he teaches it in every church.",
    '7:18': "Neither circumcision nor its reversal is required by conversion. Nobody has to change bodies to belong.",
    '7:19': "The mark whole parties fought over is set at nothing, twice, in a single sentence.",
    '7:20': "The station a man was standing in when God called him is the place the calling now lives.",
    '7:21': "A slave is told not to fret and, in the next clause, to take freedom if it comes. Both at once.",
    '7:22': "The statuses cross over: the slave is the Lord's freeman and the free man is Christ's servant.",
    '7:23': "The price already paid makes any further human ownership of a Christian a presumption.",
    '7:24': "\"Therein abide with God.\" It is the company, not the position, that makes the position holy.",
    '7:25': "No commandment to cite, so he gives judgment as a man who obtained mercy — authority received, not earned.",
    '7:26': "\"The present distress.\" He dates his advice to a circumstance rather than issuing it for all time.",
    '7:27': "Bound or loosed, the counsel is the same, which makes it counsel against restlessness.",
    '7:28': "After a long preference for the single life: \"thou hast not sinned,\" said twice, to settle it.",
    '7:29': "\"The time is short.\" The as-though-not is about grip loosening, not about duties dropped.",
    '7:30': "Weeping and rejoicing are both held at arm's length. Even the good is not to be clutched.",
    '7:31': "The reason the grip loosens is out in the world, which is passing, and not inside the believer.",
    '7:32': "The case for singleness turns on undivided attention, never on the body being purer.",
    '7:33': "Caring how to please a wife is not named as a fault. It is a real claim, and it takes room.",
    '7:35': "\"Not that I may cast a snare upon you.\" He refuses to let his own preference harden into a rule.",
    '7:36': "The anxious man is told again that marrying is no sin, in case the argument had frightened him.",
    '7:37': "Standing steadfast counts only where there is no necessity pressing and no compulsion at work.",
    '7:38': "The comparison is well and better, not right and wrong, and the whole chapter hangs on that.",
    '7:39': "A widow is free to marry whom she will. The one boundary given is \"only in the Lord.\"",
    '7:40': "He ends with \"after my judgment\" and a mild claim to the Spirit, rather than with a decree.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "Knowledge and love both do something to a church. Only one of the two leaves a building behind.",
    '8:2': "Thinking you have the matter settled is produced as the evidence that you have not.",
    '8:3': "The sentence swerves. It does not end in knowing God but in being known by him.",
    '8:4': "He concedes the strong party's point outright: the idol is nothing, and their theology is correct.",
    '8:6': "One God and one Lord — the confession of Israel opened up wide enough to take in Jesus Christ.",
    '8:7': "The argument has been won and the people have not caught up. Conscience lags behind doctrine.",
    '8:8': "Neither eating nor abstaining moves a man an inch toward God. The whole quarrel is over nothing.",
    '8:9': "The liberty is genuine, which is exactly why it is able to put something in a brother's path.",
    '8:10': "The weak man is not argued into it. He is emboldened by watching someone he respects.",
    '8:11': "\"For whom Christ died.\" The price paid for the weak brother decides a question about dinner.",
    '8:12': "Wounding a conscience does not stop at the conscience. The injury is passed straight up to Christ.",
    '8:13': "The man who insisted the meat was lawful offers to give up meat for good. Rights are for spending.",

    # ---- Chapter 9 ----
    '9:1': "Four questions establishing how free he is, asked before he describes what he does with it.",
    '9:2': "The proof of his apostleship is the very congregation now examining it.",
    '9:4': "He begins with the smallest right imaginable — eating and drinking at the church's expense.",
    '9:5': "Other apostles travel with their wives, Peter among them. Paul is listing what he declined.",
    '9:6': "He and Barnabas are the exception who work for a living, and he notices that they are.",
    '9:7': "Soldier, vinedresser, shepherd. Ordinary life already assumes a worker eats from the work.",
    '9:9': "\"Doth God take care for oxen?\" A law about an animal is read as a law about paying people.",
    '9:10': "The plowman works in hope of a share. Hope of return is written into the labour itself.",
    '9:11': "Spiritual things sown, material things reaped: the exchange is lopsided in the church's favour.",
    '9:12': "The right was real and he did not use it, because using it might have cost the gospel a hearing.",
    '9:13': "Temple servants living from the temple is not an abuse. It is how altars have always worked.",
    '9:14': "The Lord ordained that preachers live of the gospel — stated plainly, one verse before he refuses it.",
    '9:15': "He would rather die than lose this one boast, and the boast is that he costs them nothing.",
    '9:16': "\"Necessity is laid upon me.\" He cannot boast of preaching because he never chose to preach.",
    '9:18': "His wages are the absence of wages. The reward asked for is the right to charge nothing.",
    '9:19': "Free from all men, and he spends the freedom on becoming everyone's servant.",
    '9:20': "As a Jew to Jews. He bends on everything that was never the gospel in the first place.",
    '9:21': "\"Not without law to God, but under the law to Christ.\" The flexibility has a floor under it.",
    '9:22': "All things to all men, and the aim is only to save some. Total method, modest expectation.",
    '9:23': "He preaches so as to share in the gospel himself. The preacher is not standing outside it.",
    '9:24': "The runners are not racing each other. The image is of effort, borrowed from a city that loved games.",
    '9:25': "Athletes give up more than this for a wreath that dies. The comparison is meant to embarrass.",
    '9:26': "Running with a destination, fighting something that is actually there — aimlessness is the fault named.",
    '9:27': "\"Lest I myself should be a castaway.\" The apostle writes no exemption for the apostle.",

    # ---- Chapter 10 ----
    '10:1': "\"All our fathers.\" A largely Gentile church is handed Israel's ancestors without apology.",
    '10:2': "Baptized unto Moses in cloud and sea. Sacramental language is pushed backwards into the Exodus.",
    '10:4': "They drank from a Rock, and the Rock was Christ. He was present in the story before he entered it.",
    '10:5': "Five times \"all,\" and then the collapse: with most of them God was not well pleased.",
    '10:6': "The wilderness is held up as a mirror rather than as history. These things happened as examples.",
    '10:7': "\"The people sat down to eat and drink, and rose up to play.\" Idolatry that looked like a good party.",
    '10:8': "The number of the dead is given. He is not willing to let the cost stay abstract.",
    '10:9': "Christ is the one tempted in the wilderness. The old story is not somebody else's religion.",
    '10:10': "Murmuring is put in the same list as idolatry and fornication, with the same ending.",
    '10:11': "\"Written for our admonition.\" Old texts were composed with a reader like this one in view.",
    '10:12': "The warning is aimed precisely at the man who is sure he is standing. Confidence is the danger.",
    '10:13': "The promise is not that you are strong enough but that God is faithful, and that doors exist.",
    '10:14': "After all the theology about idols being nothing, the instruction is simply to walk away from them.",
    '10:15': "\"Judge ye what I say.\" He hands the argument over to be weighed rather than obeyed on authority.",
    '10:16': "Cup and bread are named communion in the blood and body. Participation, not remembrance only.",
    '10:17': "One loaf makes one body. The unity of the church is argued from the shape of a meal.",
    '10:18': "Israel's sacrifices are brought in as a third case: eating at an altar makes you a partner in it.",
    '10:20': "The idol is nothing and there are demons behind it. Both stay true in the same paragraph.",
    '10:21': "\"Ye cannot\" is said twice. It reads less like a prohibition than like a statement of fact.",
    '10:22': "The argument ends in a question about provoking jealousy, which nobody wants answered.",
    '10:23': "Their slogan is quoted a second time, and the new limit is not danger to self but building others.",
    '10:24': "\"Let no man seek his own.\" One line, and it is the rule sitting underneath the entire dispute.",
    '10:25': "Buy from the market and ask nothing. The freedom is handed back in the most practical terms.",
    '10:26': "\"The earth is the Lord's.\" The ground of eating anything is that the meat was never the idol's.",
    '10:27': "Dinner at an unbeliever's table, no scruples required and no interrogation of the host.",
    '10:28': "The meat has not changed; the company has. Someone said it aloud, and that alone is enough.",
    '10:29': "The conscience being protected is not the eater's own. Nobody is being asked to feel guilty.",
    '10:30': "He surrenders the use of his liberty while flatly refusing to surrender the liberty itself.",
    '10:31': "Eating and drinking — the smallest things in the letter — are placed under the glory of God.",
    '10:33': "He offers himself as the pattern, and the point of the pattern is other people being saved.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "Imitation with a limit written into it. He is a model only as far as he is following someone else.",
    '11:2': "He praises them for keeping what he delivered, four verses before he stops praising them entirely.",
    '11:3': "God is called the head of Christ in the same breath. Whatever head means here, it cannot mean worth.",
    '11:4': "Men are addressed first and corrected first. The instruction about covering cuts in both directions.",
    '11:5': "The women in view are praying and prophesying aloud. The argument takes their speaking for granted.",
    '11:6': "He pushes the logic to its ugly conclusion — then be shorn — to make the alternative obvious.",
    '11:7': "Image and glory are not distributed evenly here, and he makes no attempt to smooth the asymmetry.",
    '11:8': "The argument reaches back to the order of Genesis rather than to the manners of Corinth.",
    '11:10': "\"Power on her head because of the angels\" — the strangest clause in the letter, and it says power.",
    '11:11': "\"Nevertheless\" stops his own argument mid-stride: in the Lord, neither stands without the other.",
    '11:12': "Every man since the first has come by a woman, and the whole arrangement terminates in God.",
    '11:13': "\"Judge in yourselves.\" He puts the question to their own sense instead of closing it by command.",
    '11:14': "An appeal to nature that is plainly an appeal to custom, and the letter will admit as much shortly.",
    '11:16': "\"We have no such custom.\" After fifteen verses he calls it custom and declines to fight over it.",
    '11:17': "A church gathering can leave people worse than it found them. That possibility is stated flatly.",
    '11:18': "\"I partly believe it.\" He acts on the report without pretending to know how much of it is true.",
    '11:19': "Even the factions are put to work: they show up who among them is actually approved.",
    '11:20': "They are holding a meal and it is not the Lord's supper. The name has come off the thing.",
    '11:21': "One hungry and one drunk at the same table. The social divide is visible in who has food.",
    '11:22': "The sin at the table is contempt — shaming those who have nothing, in the church of God.",
    '11:23': "The oldest account of the supper we possess, and he marks it as received before delivered.",
    '11:24': "\"Broken for you.\" The gift arrives before the instruction, and the instruction only points back to it.",
    '11:25': "The cup is called the new testament in his blood. It does not stand for the covenant; it is it.",
    '11:26': "The meal preaches a death, and it is given an expiry date: till he come.",
    '11:27': "Unworthy eating makes a man guilty of the body and blood — which presumes they are really there.",
    '11:28': "Examination ends with \"so let him eat.\" The self-searching sends a man to the table, not away.",
    '11:29': "Given what this chapter is about, the body not discerned may well be the brother going hungry.",
    '11:30': "Weakness, sickness and death in the congregation are traced back to how they eat together.",
    '11:31': "Self-judgment is offered as the way to forestall judgment, which makes it a mercy rather than a burden.",
    '11:32': "Chastening is placed on the side of rescue: it happens so that condemnation will not.",
    '11:33': "The whole remedy for the scandal comes down to one instruction — wait for each other.",
    '11:34': "Hunger is real and is not what the supper is for. He sends it home and keeps the table free.",

    # ---- Chapter 12 ----
    '12:1': "A new question from their letter, and the first thing he supplies is not enthusiasm but a test.",
    '12:2': "They had ecstatic experience as pagans too. Being carried away proves nothing about the Spirit.",
    '12:3': "The test is a confession, not a phenomenon: no one says Jesus is Lord but by the Holy Ghost.",
    '12:4': "Diversity is the first word and the same Spirit is the second. Neither is allowed to cancel the other.",
    '12:6': "Gifts, administrations, operations — three words for variety, and one God working all of it.",
    '12:7': "The manifestation is given to a man for everyone else's profit. It was never private property.",
    '12:8': "Wisdom and knowledge, the two things Corinth prized most, head the list — as gifts, not attainments.",
    '12:10': "Tongues comes last in a list written for a church that had put it first.",
    '12:11': "\"As he will.\" The Spirit distributes, which shuts down envy at one end and pride at the other.",
    '12:12': "The sentence ends \"so also is Christ,\" where the expected word was church.",
    '12:13': "Jew or Greek, slave or free, one baptism. The levelling comes before any of the differentiating.",
    '12:14': "The body is not one member but many. Uniformity is the thing being argued against, not disorder.",
    '12:15': "The foot excludes itself. Nobody put it out, and its saying so does not make it true.",
    '12:16': "The ear repeats the foot's mistake, which is how Paul shows it is a pattern and not an accident.",
    '12:17': "A body that was all eye would not be a better body. It would be a mutilation.",
    '12:18': "\"As it hath pleased him.\" Placement in the body is God's arrangement, not merit and not preference.",
    '12:21': "The second temptation is the opposite of the first: the strong announcing they need no one.",
    '12:22': "The members that look feeble are called necessary — not tolerated, not included, necessary.",
    '12:23': "The church is told to overcompensate on purpose, putting more honour where there is less.",
    '12:24': "God tempered the body so the lacking part got the extra honour. The compensation is designed in.",
    '12:25': "The whole anatomy lesson exists to answer one thing: a split in a congregation.",
    '12:26': "Suffering together is described as something bodies do, not as something members are told to do.",
    '12:27': "Body of Christ and members in particular, in one line. Neither the corporate nor the individual survives alone.",
    '12:28': "A ranked list, in the middle of a chapter against ranking, and tongues is at the bottom of it.",
    '12:29': "\"Are all apostles?\" Every question expects no, and the no is meant to come as a relief.",
    '12:30': "The gift this church wanted everyone to have is the one he asks about last, expecting the same answer.",
    '12:31': "Wanting the better gifts is not the error. The correction comes as a better way, not a ban.",

    # ---- Chapter 13 ----
    '13:1': "The prized gift, taken to its furthest extent, is reduced to noise from temple instruments.",
    '13:2': "Not I have less, but \"I am nothing.\" The subtraction takes the man, not the achievement.",
    '13:3': "Even goods given away and a body burned are audited, and can come back showing no profit.",
    '13:4': "Envy, vaunting, being puffed up — the list of what love is not is a list of this church's faults.",
    '13:5': "\"Seeketh not her own\" is the sentence that settles the whole quarrel over meat and rights.",
    '13:6': "Love takes no pleasure in wrongdoing, which is what the congregation had been doing in chapter five.",
    '13:7': "Bears, believes, hopes, endures. All four verbs describe staying rather than feeling.",
    '13:8': "Prophecy, tongues and knowledge are given expiry dates. The chapter is about obsolescence.",
    '13:9': "\"We know in part\" is said to people whose entire quarrel was conducted in the name of knowledge.",
    '13:10': "The partial is not discarded for being false. It is done away by the arrival of something whole.",
    '13:11': "Childish things are not wicked things. The gifts are being called young, not wrong.",
    '13:12': "The verse does not end in seeing God but in being known by him, which is where chapter eight ended too.",
    '13:13': "Love is greatest because it is the one of the three still standing when sight and possession arrive.",
})
