#!/usr/bin/env python3
"""Written one-line takeaways for Galatians.

Each states what the verse turns on. Verses carrying no standalone point —
bare connectives, travel notes, greeting lists — are left out deliberately;
the drawer hides the card rather than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"Not of men, neither by man\" — the defence of his apostleship starts before the greeting is finished.",
    '1:4': "Deliverance, not improvement. Christ gave himself to get us out of this present evil world, and it was the Father's will.",
    '1:5': "A doxology in the opening sentence, before Paul has said one angry word.",
    '1:6': "They are removed not from a doctrine but from a person — \"him that called you\" — and it happened fast.",
    '1:7': "\"Which is not another\" — there is no second gospel available, only the first one with the life taken out.",
    '1:8': "An angel from heaven is placed under the curse. No messenger's credentials can outrank the message.",
    '1:9': "He says it a second time, which turns an outburst into a settled judgment.",
    '1:10': "Pleasing men and serving Christ are set as alternatives, and the curse he has just pronounced is his evidence.",
    '1:11': "A gospel invented by men would have been kinder to men. Paul's point is that this one was not invented.",
    '1:12': "Neither received nor taught — the two ordinary ways of acquiring anything are both ruled out.",
    '1:13': "He tells the story of persecuting the church without softening the verb: he wasted it.",
    '1:14': "He was not a failing Pharisee looking for relief. He was outrunning his contemporaries when he was stopped.",
    '1:15': "\"Separated me from my mother's womb\" — the call is dated before the persecuting, which leaves merit nothing to do.",
    '1:16': "\"I conferred not with flesh and blood\" — the revelation needed no committee to certify it.",
    '1:17': "Arabia, not Jerusalem. The itinerary is part of the argument about where his gospel came from.",
    '1:18': "Three years, then a fortnight with Peter. The dates are given because their brevity is the point.",
    '1:19': "One other apostle seen, and Paul names him. The account is offered as checkable.",
    '1:20': "An oath in the middle of an autobiography tells you the facts were being disputed.",
    '1:22': "The Judaean churches did not know him by sight, which disposes of any claim that he was their delegate.",
    '1:23': "They knew him only as a report: the persecutor now preaches the faith he was destroying.",
    '1:24': "\"They glorified God in me\" — the praise travelled straight past Paul, and he tells it that way.",

    # ---- Chapter 2 ----
    '2:1': "Fourteen more years before the next visit. Paul measures his independence in decades.",
    '2:2': "He went up by revelation rather than summons, and still wanted to know he had not run in vain.",
    '2:3': "Titus is the test case, and what settles it is that nothing was done to him.",
    '2:4': "\"To spy out our liberty\" — the freedom was substantial enough to be worth infiltrating.",
    '2:5': "\"No, not for an hour.\" The reason given is not Paul's dignity but the Galatians' gospel.",
    '2:6': "Twice he notes the reputation of the men in conference, and twice sets it aside: they added nothing to him.",
    '2:7': "One gospel, two assignments. What was divided at Jerusalem was the field, not the message.",
    '2:9': "The right hand of fellowship was given because they perceived the grace given to him, not his qualifications.",
    '2:10': "One request came out of the whole conference, and it was to remember the poor.",
    '2:11': "\"I withstood him to the face\" — the rebuke of the senior apostle is put in writing, with the name attached.",
    '2:12': "It was not doctrine that moved Peter but fear, and it showed itself at the dinner table.",
    '2:13': "Even Barnabas was carried away. Paul records the one name that would have cost him most to write.",
    '2:14': "The charge is inconsistency: a Jew living like a Gentile whose withdrawal forced Gentiles to live like Jews.",
    '2:16': "Three times in one sentence: not by works of the law, but by faith. Paul will not risk being heard once.",
    '2:17': "If seeking justification in Christ exposes us as sinners, the fault lies in what was exposed, not in Christ.",
    '2:18': "Rebuilding what he had torn down is what would make him a transgressor. Going back is the offence.",
    '2:19': "\"Through the law am dead to the law\" — the law itself did the killing, which was its proper work.",
    '2:20': "\"Yet not I, but Christ\" — and the life is still lived in the flesh, by faith, not above it.",
    '2:21': "If righteousness could come any other way, the cross was a waste. Paul lets that stand as his conclusion.",

    # ---- Chapter 3 ----
    '3:1': "\"Who hath bewitched you\" — turning from grace is treated as something done to them, not merely thought by them.",
    '3:2': "One question is expected to settle the whole dispute, and it asks about their own experience.",
    '3:3': "Beginning in the Spirit and finishing in the flesh is the standing temptation, and Paul calls it foolishness.",
    '3:4': "\"If it be yet in vain\" — he checks his own severity mid-sentence and leaves the door standing open.",
    '3:5': "Present tense: the Spirit is still being supplied, and still by hearing rather than by doing.",
    '3:6': "Abraham is brought in as the precedent because the other side had claimed him first.",
    '3:7': "Children of Abraham are identified by faith, which quietly rewrites everybody's genealogy.",
    '3:8': "Scripture is said to have preached the gospel to Abraham. The good news is older than the law.",
    '3:10': "The curse attaches to the law-keeping itself, because the terms read all things, continually, without a gap.",
    '3:11': "\"The just shall live by faith\" is quoted as already evident, not as something Paul is introducing.",
    '3:12': "\"The law is not of faith\" — the two run on different principles and cannot be blended into one.",
    '3:13': "\"Made a curse for us\" — the exchange is complete, and the proof text is about a body on a tree.",
    '3:14': "The blessing was always meant to travel outward, and the promise being received is the Spirit himself.",
    '3:15': "Even a human contract cannot be amended once confirmed. The argument runs from the smaller case upward.",
    '3:16': "The whole argument turns on a singular noun. Paul reads the promise as pointing to one person.",
    '3:17': "Four hundred and thirty years later — the law arrives too late to alter a covenant already ratified.",
    '3:18': "Inheritance goes with promise, not with law. A gift cannot be half earned and stay a gift.",
    '3:19': "\"Added because of transgressions\" — the law is given a reason and an expiry in the same breath.",
    '3:20': "A mediator implies two parties. The promise had only one, which is why it cannot fail from our side.",
    '3:21': "Paul refuses to set the law against the promise. Its fault is inability, not opposition.",
    '3:22': "Scripture shut everyone up under sin so that what follows could be given rather than awarded.",
    '3:23': "Kept and shut up — the law's custody is described as confinement with a release date, not as the sentence itself.",
    '3:24': "The schoolmaster's task was to deliver a child somewhere, and the destination named is Christ.",
    '3:25': "The tutor is not discredited when he is dismissed. He is finished.",
    '3:26': "Sonship by faith is stated as present and complete. There is no further initiation on offer.",
    '3:27': "Baptism is described as putting on Christ, so that what is seen is him and not the wearer.",
    '3:28': "The three great divisions are not dissolved as facts; they are abolished as grounds of standing.",
    '3:29': "Belonging to Christ is what makes a man Abraham's seed. The descent runs through him, not around him.",
}

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:1': "An heir who is still a child lives exactly like a servant, though everything already belongs to him.",
    '4:3': "\"The elements of the world\" — the religious past is described as a minority, not as a golden age.",
    '4:4': "\"Made of a woman, made under the law\" — the Son comes in under the very thing he arrives to redeem people from.",
    '4:5': "Redemption and adoption in one sentence: bought out of one standing and placed into another.",
    '4:6': "The Spirit is sent because they are sons, not in order to make them sons. The order is the comfort.",
    '4:7': "\"No more a servant, but a son\" — and the inheritance named is God himself, not a benefit from him.",
    '4:8': "Their former bondage was to things that were no gods at all, which is Paul's measure of what they are drifting back into.",
    '4:9': "He corrects himself mid-phrase: not that they knew God, but that they are known of him.",
    '4:10': "Days, months, times and years. The return to law shows up first in a calendar.",
    '4:11': "\"Lest I have bestowed upon you labour in vain\" — the fear is for his own work, and he says it aloud.",
    '4:12': "\"Ye have not injured me at all\" clears away the suspicion that he is writing out of personal grievance.",
    '4:13': "The gospel first reached them through a sick man, and the weakness is left in the account.",
    '4:14': "They welcomed a man they might reasonably have despised, and Paul reminds them of their own better instinct.",
    '4:15': "The blessedness is spoken of in the past tense. He asks where it went rather than announcing that it is gone.",
    '4:16': "\"Am I therefore become your enemy, because I tell you the truth?\" — the standing price of saying it plainly.",
    '4:17': "The rivals' technique is exclusion: shut people out so that they will work to be let back in.",
    '4:19': "He takes the mother's part, and what he is in labour for is Christ formed in them, not agreement with himself.",
    '4:20': "\"I stand in doubt of you\" — an apostle admitting he does not know what to make of a church.",
    '4:21': "Those who want to be under the law are asked whether they have actually listened to it.",
    '4:23': "One son came the natural way and one by promise. The difference is the manner of the birth, not the merit of anyone in it.",
    '4:24': "Two covenants, and the one given at Sinai is said to bear its children into bondage.",
    '4:25': "Agar answers to the Jerusalem of Paul's own day. The religious centre is placed on the slave side of the line.",
    '4:26': "\"Jerusalem which is above is free\" — the mother of believers is a city none of them has seen.",
    '4:27': "The barren woman is told to rejoice before any child appears. The promise runs well ahead of the evidence.",
    '4:28': "\"As Isaac was\" — believers are placed in the line of the impossible birth rather than the arranged one.",
    '4:29': "The son born after the flesh persecuting the other is described as the standing pattern, then and now.",
    '4:30': "The quotation is harsh and Paul uses it unedited: the two principles cannot share one inheritance.",

    # ---- Chapter 5 ----
    '5:1': "Liberty is something to stand in, and the danger named is entanglement rather than assault.",
    '5:2': "If circumcision is taken as necessary, Christ profits nothing. No partial arrangement is on offer.",
    '5:3': "Accepting one requirement is accepting all of them. The law does not come in portions.",
    '5:4': "\"Fallen from grace\" is said of people trying to be justified by law, not of people sinning badly.",
    '5:5': "Righteousness is waited for through the Spirit rather than produced and inspected in the meantime.",
    '5:6': "\"Faith which worketh by love\" — denying that works justify does not leave faith with nothing to do.",
    '5:7': "\"Ye did run well\" — the good beginning is granted before he asks who got in the way.",
    '5:8': "The persuasion did not come from the one who called them. That is how a true voice is told from a plausible one.",
    '5:9': "A little leaven is enough. Small additions to the gospel are not small.",
    '5:10': "Confidence in them and judgment on the troubler in one breath. The deceived and the deceiver are not treated alike.",
    '5:11': "His own persecution is the proof: nobody troubles a preacher who leaves the offence of the cross out.",
    '5:12': "The bitterest line in the letter, and Paul lets it stand rather than tidying his anger away.",
    '5:13': "Liberty can be used as an occasion. The safeguard offered is not law but serving one another in love.",
    '5:14': "The whole law fulfilled in one word — the same law he has spent five chapters refusing as a way to be justified.",
    '5:15': "Biting and devouring ends with both parties consumed. No winner is described.",
    '5:16': "The promise is not that the desire disappears but that walking in the Spirit does not fulfil it.",
    '5:17': "\"Ye cannot do the things that ye would\" — the conflict is described as the normal condition, not a failure in it.",
    '5:18': "Led by the Spirit and under the law are alternatives. The Spirit does not produce a better legalist.",
    '5:21': "Envying and revelling are listed beside murder, and the warning is said to be a repeat of earlier preaching.",
    '5:22': "Fruit, not works, and the noun is singular. One crop with many features, grown rather than manufactured.",
    '5:23': "\"Against such there is no law\" — the law has nothing to say to what the Spirit produces.",
    '5:24': "The crucifying of the flesh is spoken of as something already done by those who are Christ's.",
    '5:25': "Living in the Spirit is assumed; walking in him is what is urged. The second does not earn the first.",
    '5:26': "Vainglory is the root, and its two branches are provoking those beneath you and envying those above.",

    # ---- Chapter 6 ----
    '6:1': "The one restoring is told to watch himself in the same sentence that tells him to restore.",
    '6:2': "\"The law of Christ\" is fulfilled by carrying weight. It is the only law this letter commends.",
    '6:3': "The danger named is self-deception, and the mechanism is thinking oneself to be something.",
    '6:4': "Proving one's own work removes the comparison. Rejoicing \"in himself alone\" means with no rival in view.",
    '6:5': "Three verses after bearing one another's burdens, each man bears his own. Both stand, and neither cancels the other.",
    '6:6': "Supporting the teacher is stated as a plain obligation rather than as generosity.",
    '6:7': "\"God is not mocked\" — the law of harvest applies inside the church as much as outside it.",
    '6:8': "Two soils, two crops. What is sown to the flesh does not fail to grow; it grows corruption.",
    '6:9': "The harvest is certain and the season is not ours to set, which is exactly what makes weariness likely.",
    '6:10': "Good to all men, and first to the household of faith. The priority is stated without narrowing the circle.",
    '6:11': "He takes the pen from the scribe for the ending, and the size of the letters is itself the emphasis.",
    '6:12': "Their motive is named as self-protection — a fair show in the flesh, to dodge persecution for the cross.",
    '6:13': "They do not keep the law themselves. What they want is something to boast about in another man's body.",
    '6:14': "The only permitted boast is an instrument of execution, and it has ended the world's claim on him and his on it.",
    '6:15': "The letter closes the question by dismissing both sides of it: what counts is a new creature.",
    '6:16': "Peace and mercy are pronounced on those walking by this rule, and \"the Israel of God\" is named among them.",
    '6:17': "His credentials at the end are scars rather than arguments.",
    '6:18': "The letter that opened with an anathema closes with grace, and grace is given the last word.",
})
