#!/usr/bin/env python3
"""Written one-line takeaways for James.

Each states what the verse turns on. Verses carrying no standalone point
are left out deliberately; the drawer hides the card rather than showing
filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"James, a servant\" — the Lord's own brother claims no closer title than that.",
    '1:2': "\"Count it all joy\" — joy is reckoned here, a judgement about the trial rather than a feeling in it.",
    '1:3': "Patience is not native to anyone. It is what the trying of faith produces, and little else does.",
    '1:4': "\"Let patience have her perfect work.\" The standing temptation is to cut the process short.",
    '1:5': "God gives wisdom liberally and \"upbraideth not\" — no lecture attached about why you lacked it.",
    '1:6': "Wavering is not faith gone weak but two minds at once, moved by whatever wind is blowing.",
    '1:7': "A blunt sentence: that man receives nothing. The asking was never really aimed anywhere.",
    '1:8': "Double mindedness does not stay in the prayer. It destabilises \"all his ways.\"",
    '1:9': "The brother of low degree rejoices in being exalted — present tense, before anything has changed.",
    '1:10': "The rich man's ground for rejoicing is being made low. Wealth never reads itself that way.",
    '1:11': "The burning sun does not consult the flower. Wealth fades \"in his ways\" — mid-plan, mid-career.",
    '1:12': "The crown is promised to them that love him, not awarded to them that endured impressively.",
    '1:13': "The line is drawn early: no one may trace his own wanting back to the God who made him.",
    '1:14': "Drawn away of his own lust. The bait was already inside the man before anything was offered.",
    '1:15': "Lust conceives, sin is born, death follows. Nothing in that sequence happens suddenly.",
    '1:17': "Every good gift comes down from a Father with no shadow of turning — no moods, no off days.",
    '1:18': "\"Of his own will begat he us.\" The new birth is traced to God's decision, never to ours.",
    '1:19': "Swift to hear, slow to speak, slow to wrath. The order is itself the whole instruction.",
    '1:20': "Man's wrath never produces God's righteousness, however righteous the anger feels at the time.",
    '1:21': "The word is engrafted and received with meekness; it saves, and the hearer did not grow it.",
    '1:22': "Hearers only are not merely unproductive. They are \"deceiving your own selves.\"",
    '1:23': "The mirror shows a man his natural face — the one he was born with and did not choose.",
    '1:24': "He beholdeth himself and goeth his way. The failure is not in the looking but in the walking off.",
    '1:25': "\"The perfect law of liberty\" — law and freedom in one phrase, and the blessing is in the deed.",
    '1:26': "An unbridled tongue is enough by itself to make a man's religion vain, whatever else is kept.",
    '1:27': "Pure religion is named as orphans, widows, and staying unspotted. Both halves, or neither.",

    # ---- Chapter 2 ----
    '2:1': "Faith in \"the Lord of glory\" and respect of persons cannot be held at the same time.",
    '2:3': "\"Sit thou here\" and \"Stand thou there.\" Partiality is acted out in seating, not in speeches.",
    '2:4': "Judges of evil thoughts: the sin is not the preference but the verdict it quietly passes.",
    '2:5': "God chose the poor, rich in faith. The room's ranking runs exactly opposite to his choosing.",
    '2:6': "\"Ye have despised the poor\" — while flattering the class that drags you before the courts.",
    '2:7': "Honouring the rich here means honouring men who blaspheme the name you are called by.",
    '2:8': "The royal law is loving your neighbour, and the neighbour includes the badly dressed one.",
    '2:9': "Respect of persons is not bad manners. The law convicts it, and the word used is sin.",
    '2:10': "One point broken makes a man guilty of all. The law is not a score to be totalled up.",
    '2:11': "The same One spoke both commands, so keeping one buys no licence to break the other.",
    '2:12': "Judgement by the law of liberty still comes. Freedom does not cancel the reckoning.",
    '2:13': "\"Mercy rejoiceth against judgment.\" Mercy does not plead with judgement; it outranks it.",
    '2:14': "\"Can faith save him?\" The question is about a faith that is only said, not about faith itself.",
    '2:16': "\"Be ye warmed and filled\" — a blessing that costs the speaker nothing and does nothing.",
    '2:17': "Faith without works is dead \"being alone.\" Not weak faith; James says it is a corpse.",
    '2:18': "\"Shew me thy faith without thy works\" — the challenge is that it cannot be shown at all.",
    '2:19': "The devils hold orthodox doctrine and tremble at it. Assent is not the same thing as trust.",
    '2:20': "\"O vain man\" — the argument is with someone who wants a faith that costs him nothing.",
    '2:21': "Abraham is called justified by works, and the work named is the one done at God's word.",
    '2:22': "Faith wrought with his works. The works did not replace the faith; they brought it to completion.",
    '2:23': "Imputed for righteousness first, called the Friend of God after. The reckoning came before the name.",
    '2:24': "\"Not by faith only.\" James will not soften the sentence, and it is left standing as he wrote it.",
    '2:25': "Rahab, a harlot and a foreigner, is the second witness — chosen for the scandal of it.",
    '2:26': "Body and spirit: the figure makes works the sign that life is present, not the cause of it.",

    # ---- Chapter 3 ----
    '3:1': "Teachers receive the greater condemnation. The warning is aimed at those who want the role.",
    '3:2': "\"In many things we offend all.\" James counts himself in before he says anything else.",
    '3:3': "The bit is small and goes in the mouth, and the whole animal turns with what is put there.",
    '3:4': "Great ships, fierce winds, a very small helm. Size is not what decides direction.",
    '3:5': "A little fire, a great matter. The damage is out of all proportion to the size of the member.",
    '3:6': "\"Set on fire of hell.\" The source of the words is traced further back than the speaker.",
    '3:8': "No man can tame the tongue. No technique is offered; James says the thing cannot be done.",
    '3:9': "Blessing God and cursing men made in his likeness — the same breath aimed in both directions.",
    '3:10': "\"These things ought not so to be.\" No remedy follows, only the contradiction named aloud.",
    '3:11': "A fountain cannot run sweet and bitter. Nature turns out to be more consistent than we are.",
    '3:12': "Figs from a vine, olives from a fig tree: what comes out tells you what the tree already is.",
    '3:13': "Wisdom is shown by a good conversation \"with meekness\" — not by the ability to win an argument.",
    '3:14': "Bitter envying in the heart makes the boast a lie against the truth, however true the words.",
    '3:15': "Wisdom not from above is traced down three steps in one breath: earthly, sensual, devilish.",
    '3:16': "Where envying and strife are, confusion follows, and every evil work finds room to work.",
    '3:17': "Pure first, then peaceable. The order keeps peaceableness from turning into appeasement.",
    '3:18': "Righteousness is a crop, sown in peace by the people who make it. Harvest language for slow work.",

    # ---- Chapter 4 ----
    '4:1': "Wars among you come of lusts \"in your members.\" The front line runs inside the combatants.",
    '4:2': "\"Ye have not, because ye ask not.\" The whole scramble was for what could have been requested.",
    '4:3': "A prayer can be refused because the request was aimed squarely at the petitioner's pleasure.",
    '4:4': "Friendship with the world is not a lesser loyalty. James calls it adultery and enmity.",
    '4:5': "The spirit in us lusteth to envy. Scripture says so, and James expects that to be believed.",
    '4:6': "\"But he giveth more grace.\" Four words turn the chapter, and they answer envy with gift.",
    '4:7': "Submission comes first. Resistance to the devil follows from it, never the other way round.",
    '4:8': "Draw nigh and he draws nigh, and the cleansing is commanded to sinners, not to the qualified.",
    '4:9': "Laughter turned to mourning. The call is to grief, and no apology is made for it.",
    '4:10': "Humble yourselves, and the lifting is his to do. Nobody arranges his own exaltation here.",
    '4:11': "Speaking evil of a brother puts a man over the law rather than under it.",
    '4:12': "\"Who art thou that judgest another?\" There is one lawgiver, and the seat is already occupied.",
    '4:13': "The plan is detailed — city, year, trade, gain. Everything is settled except whether you will be there.",
    '4:14': "\"What is your life? It is even a vapour.\" Asked of people in the middle of confident planning.",
    '4:15': "\"If the Lord will\" is not a pious addition. It is a true description of every plan ever made.",
    '4:16': "Boasting about tomorrow is called evil here, not called optimistic.",
    '4:17': "Sin is defined by what a man who knew better simply left undone.",

    # ---- Chapter 5 ----
    '5:1': "\"Weep and howl\" — the rich are addressed not with an invitation but with what is coming.",
    '5:3': "The rust itself is the witness. What was hoarded ends up testifying against the hoarder.",
    '5:4': "The withheld wages cry out, and the cry reaches the Lord of sabaoth — the Lord of armies.",
    '5:5': "Hearts nourished \"as in a day of slaughter.\" Pleasure described as fattening for the kill.",
    '5:6': "\"He doth not resist you.\" The just man's silence is the last thing recorded of him.",
    '5:7': "The husbandman cannot hurry rain. Patience is what is left when the outcome is not yours.",
    '5:8': "\"Stablish your hearts.\" Patience needs the heart propped up, not just the calendar endured.",
    '5:9': "Grudging among brethren is judged, and the judge is already standing at the door.",
    '5:10': "The prophets are the worked example, and what they model is affliction, not success.",
    '5:11': "Job is called patient, and \"the end of the Lord\" is named as pity and tender mercy.",
    '5:12': "Oaths are set aside because a plain yes ought to be enough from a man who fears God.",
    '5:13': "Afflicted, pray; merry, sing. Both moods are turned toward God rather than away from him.",
    '5:14': "The sick man calls for the elders. The asking is his, and the church comes to where he is.",
    '5:15': "\"The prayer of faith shall save the sick,\" and forgiveness is named in the same breath.",
    '5:16': "Confession here is mutual, one to another, long before it is anything formal.",
    '5:17': "\"Subject to like passions as we are.\" Elias is introduced by what he shared with us.",
    '5:19': "Erring from the truth is assumed possible \"among you,\" and somebody has to go after him.",
    '5:20': "Saving a soul from death and hiding a multitude of sins — an errand given to an ordinary brother.",
}
