#!/usr/bin/env python3
"""Written one-line takeaways for 1 John.

Each states what the verse turns on. Verses carrying no standalone point
are left out deliberately; the drawer hides the card rather than showing
filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Heard, seen, looked upon, handled. The eternal Word is introduced through four physical senses.",
    '1:3': "What was seen is declared so that others may share the fellowship. Witness exists to widen the circle.",
    '1:4': "\"That your joy may be full\" — the letter's stated aim is joy, before a single test is applied.",
    '1:5': "God is light, and in him is no darkness at all. The \"at all\" is what the rest of the letter rests on.",
    '1:6': "Claiming fellowship while walking in darkness is not an inconsistency but a lie.",
    '1:7': "Walking in the light does not mean having nothing to cleanse. The blood is at work in the light.",
    '1:8': "The man with no sin to confess has only deceived himself; nobody else was fooled.",
    '1:9': "Forgiveness is called faithful and just, not generous. God is keeping a promise, not bending a rule.",
    '1:10': "Denying that we have sinned contradicts God's own testimony and makes him the liar.",

    # ---- Chapter 2 ----
    '2:1': "Written that ye sin not — and the next clause plans for what happens when you do.",
    '2:2': "\"Not for ours only, but also for the sins of the whole world.\" The propitiation is not rationed.",
    '2:3': "Keeping his commandments is the evidence that we know him, never the means of getting to know him.",
    '2:4': "The claim and the life are weighed against each other, and the claim is the part called a lie.",
    '2:5': "The love of God is perfected in the one who keeps his word — his love completed, not ours proved.",
    '2:6': "Abiding in him carries an obligation to walk as he walked. The claim commits you to the pattern.",
    '2:7': "No new commandment, but the old one they had from the beginning. Nothing here is an innovation.",
    '2:8': "The same commandment is called new, because the darkness is passing and the light already shines.",
    '2:9': "Hating a brother locates a man in darkness \"even until now,\" whatever he says about the light.",
    '2:10': "Love removes the occasion of stumbling — in him, so his brother is not the one who trips.",
    '2:11': "The hater walks not knowing where he goes. Darkness blinds before it misleads.",
    '2:12': "Sins forgiven \"for his name's sake\" — the reason given is his name, not their progress.",
    '2:13': "Fathers, young men, little children: each group is addressed by what it already has, not what it lacks.",
    '2:15': "Loving the world and the love of the Father are named as occupying the same space.",
    '2:16': "Lust of the flesh, lust of the eyes, pride of life — the world is inventoried as three appetites.",
    '2:17': "The world is passing away while it is being desired. The doer of God's will outlasts what he gave up.",
    '2:18': "Many antichrists already, and their presence is what tells John the hour is late.",
    '2:19': "\"They went out from us, but they were not of us.\" The departure revealed something already true.",
    '2:20': "The unction is from the Holy One and belongs to all of them. No inner circle is left holding it.",
    '2:21': "John writes because they know the truth, not because they do not. Reminder, not initiation.",
    '2:22': "The lie is specific: denying that Jesus is the Christ, which also lets go of the Father.",
    '2:23': "There is no keeping the Father while releasing the Son. They are not separable holdings.",
    '2:24': "Continuing in the Son turns on what abides in you from the beginning, not on what is added later.",
    '2:25': "The promise is stated in two words: eternal life. Nothing is attached about what earns it.",
    '2:27': "The anointing teaches, so no teacher can claim they cannot manage without him.",
    '2:28': "Abiding now is what makes confidence at his appearing possible then.",
    '2:29': "Doing righteousness is the sign of being born of him. Birth comes first and the doing follows.",

    # ---- Chapter 3 ----
    '3:1': "\"What manner of love\" — sonship is bestowed, and the world's failure to recognise it is expected.",
    '3:2': "Now sons, and what we shall be is not yet shown. The transformation comes from seeing him as he is.",
    '3:3': "The hope purifies the man who holds it, and the standard named is his purity rather than an average.",
    '3:4': "Sin is defined flatly as the transgression of the law — no softer word is offered.",
    '3:5': "He was manifested to take away sins, and in him is no sin. Both halves are needed for the first to work.",
    '3:6': "The one who abides does not go on sinning. John speaks of a settled direction, not a perfect record.",
    '3:7': "\"Let no man deceive you\" — someone was teaching that righteousness could be claimed without doing any.",
    '3:8': "The Son was manifested to destroy the works of the devil, so sin is treated as enemy occupation.",
    '3:9': "\"His seed remaineth in him.\" The impossibility is traced to what God put there, not to willpower.",
    '3:10': "The children of God are made manifest by two things together: righteousness and loving a brother.",
    '3:11': "The message from the beginning was that we love one another. Nothing newer has replaced it.",
    '3:12': "Cain killed because his own works were evil and his brother's righteous. Envy of the good turns murderous.",
    '3:13': "\"Marvel not\" — being hated by the world is unsurprising, and surprise would be the mistake.",
    '3:14': "Loving the brethren is how we know we have passed from death to life, not how we make the passage.",
    '3:15': "Hatred is classed with murder, which means the hidden version is already the real thing.",
    '3:16': "Love is defined by his laying down his life, and then that definition is handed to us as a duty.",
    '3:17': "Shut bowels of compassion toward a brother in need raise a question about whether love is there at all.",
    '3:18': "Love in deed and in truth, not in word and tongue. The contrast assumes words are the easy part.",
    '3:20': "\"God is greater than our heart\" — the self-accusing conscience is not the highest court.",
    '3:21': "Confidence toward God is described as what an uncondemning heart makes possible, not as a mood.",
    '3:22': "Asking and receiving are tied to keeping his commandments, which is the life of someone already his.",
    '3:23': "One commandment with two halves: believe on the Son, and love one another. Faith and love, undivided.",
    '3:24': "We know he abides in us by the Spirit he gave. The evidence is a gift, not an achievement.",

    # ---- Chapter 4 ----
    '4:1': "Believe not every spirit, but try them. Sincerity of the speaker is not admitted as evidence.",
    '4:2': "The test is confessing Jesus Christ come in the flesh. Doctrine about the body decides the spirit.",
    '4:3': "The spirit of antichrist is already in the world, so the danger is present tense, not predicted.",
    '4:4': "\"Greater is he that is in you\" — the overcoming is credited to the One indwelling, not to their resolve.",
    '4:5': "The world hears its own. Popularity is explained here as a family resemblance.",
    '4:6': "Who listens to the apostles sorts the spirit of truth from the spirit of error. A blunt criterion.",
    '4:7': "Love one another, for love is of God. The command comes with its source attached.",
    '4:8': "\"God is love\" is stated as the reason the loveless do not know him, not as a definition of niceness.",
    '4:9': "Love was manifested by the Son being sent — an event, not a disposition we are asked to detect.",
    '4:10': "\"Not that we loved God, but that he loved us.\" The direction of the love is the whole point.",
    '4:11': "\"If God so loved us\" — the obligation to love each other is derived from what was done to us.",
    '4:12': "No man has seen God, and his love is perfected among people loving each other. That is where he is visible.",
    '4:14': "The apostles testify that the Father sent the Son as Saviour of the world — a wider claim than the sect's.",
    '4:15': "Confession of the Son and God dwelling in him are joined without any further condition inserted.",
    '4:16': "\"We have known and believed the love that God hath to us.\" Love is believed before it is produced.",
    '4:17': "Boldness in the day of judgment comes from love made perfect, not from a record made clean.",
    '4:18': "Fear has torment, and perfect love casts it out. The fear was never the mark of taking God seriously.",
    '4:19': "\"Because he first loved us.\" Every love in this letter is a reply.",
    '4:20': "The brother you have seen is the test case for the God you have not.",
    '4:21': "The commandment binds the two loves together so neither can be offered as a substitute.",

    # ---- Chapter 5 ----
    '5:1': "Believing that Jesus is the Christ is the mark of being born of God — the birth is not felt, it is believed.",
    '5:2': "The test is run in both directions: love of God shows in love of his children, and the reverse.",
    '5:3': "\"His commandments are not grievous\" — said to people who know exactly how demanding they are.",
    '5:4': "The victory that overcomes the world is named as our faith, which holds on to someone else's victory.",
    '5:5': "The overcomer is not described by strength but by what he believes about the Son of God.",
    '5:6': "Water and blood, not water only. John insists on the death as well as the baptism.",
    '5:7': "Father, Word and Holy Ghost bearing record, and these three are one. The witness is God's own.",
    '5:9': "If the witness of men is received daily, the greater witness of God is the one being refused.",
    '5:10': "The believer has the witness in himself; unbelief is described as calling God a liar.",
    '5:11': "\"This life is in his Son.\" Eternal life is not a substance given but a person to be had.",
    '5:12': "He that hath the Son hath life. The sentence leaves no third category standing.",
    '5:13': "\"That ye may know that ye have eternal life\" — assurance is the reason the letter exists.",
    '5:14': "Confidence in prayer is tied to asking according to his will, which is a limit and a guarantee at once.",
    '5:16': "Prayer for a sinning brother is expected, and the one exception is left undefined rather than explained.",
    '5:18': "The born of God are kept, and \"that wicked one toucheth him not.\" The keeping is not self-generated.",
    '5:19': "We are of God, and the whole world lieth in wickedness. John allows no comfortable middle ground.",
    '5:20': "\"This is the true God, and eternal life\" — the letter's last doctrine is that the Son is the true God.",
    '5:21': "It ends with idols, abruptly. Anything held in the place of the true God is one.",
}
