#!/usr/bin/env python3
"""Written one-line takeaways for Mark.

Each states what the verse turns on. Narrative verses that carry no
standalone point — bare connectives, travel notes, the lead-in half of a
quotation — are left out deliberately; the drawer hides the card rather
than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"The beginning of the gospel\" — Mark calls the whole book a beginning. It is still running.",
    '1:2': "No genealogy, no nativity. Mark opens with the prophets, because the story started long before Nazareth.",
    '1:3': "A voice in the wilderness, not in the temple. God's preparation begins outside the approved places.",
    '1:4': "Baptism of repentance for the remission of sins — the forgiveness is what repentance is for.",
    '1:5': "They came confessing. Confession was the only thing anybody brought down to the Jordan.",
    '1:6': "Camel's hair and locusts. The last prophet looks like Elijah and like nothing the city would respect.",
    '1:7': "John measures himself against Christ and lands beneath the slave who unties the sandals.",
    '1:8': "Water was the whole of John's reach. What comes after is not more of the same but a different act.",
    '1:9': "He comes from Nazareth to be baptized among sinners, having nothing of his own to confess.",
    '1:10': "The heavens are torn open — the same violent word Mark will use of the veil at the end.",
    '1:11': "\"Thou art my beloved Son.\" The Father's pleasure is declared before a single work is done.",
    '1:12': "The Spirit drives him out. The wilderness is not a lapse from the Father's pleasure but the next step in it.",
    '1:13': "Forty days, wild beasts, angels. Mark gives no dialogue, only that he was there and was kept.",
    '1:14': "The preaching starts after John is arrested. The gospel goes forward over the wreckage of its forerunner.",
    '1:15': "\"The time is fulfilled\" comes first; repent and believe follow from it. The gift precedes the demand.",
    '1:16': "He calls them mid-net. The summons finds working men in the middle of an ordinary shift.",
    '1:17': "\"I will make you to become.\" What they turn into is his doing, not their qualification.",
    '1:18': "Straightway they forsook their nets. Mark records no deliberation, only the leaving.",
    '1:19': "James and John were mending, not casting. He calls men in the middle of repair work too.",
    '1:20': "They left Zebedee with the hired servants. Mark notes who was left behind; the leaving cost somebody.",
    '1:22': "The scribes quoted authorities; he spoke as one. The room could hear the difference.",
    '1:23': "The unclean spirit is found inside the synagogue. Evil is comfortable in religious places.",
    '1:24': "\"I know thee who thou art.\" The demon's Christology is exact and does him no good whatever.",
    '1:25': "He silences the demon before he expels it. Christ refuses to be advertised by that witness.",
    '1:26': "The exit is violent. Deliverance is not always gentle in the going.",
    '1:27': "They call it new doctrine, having just watched an exorcism. Word and power are one thing here.",
    '1:30': "\"Anon they tell him of her.\" The whole of their intercession is that they mentioned her.",
    '1:31': "He lifted her up and the fever left; then she served. Strength goes back into ordinary work.",
    '1:32': "They waited for sunset and the sabbath's end before carrying the sick. Scruple governed their mercy.",
    '1:33': "All the city at the door. Mark's crowds are always larger than his believers.",
    '1:34': "He suffered not the devils to speak, because they knew him. He will not have his name told by them.",
    '1:35': "A great while before day, a solitary place, and there prayed. The one who needed nothing prayed first.",
    '1:37': "\"All men seek for thee\" is offered as a reason to stay. He hears it as a reason to move on.",
    '1:38': "\"Therefore came I forth.\" It is the preaching, not the healing, that he names as his errand.",
    '1:40': "\"If thou wilt, thou canst.\" The leper never doubts the power; it is the willingness he cannot assume.",
    '1:41': "Moved with compassion, he touched him. The touch was needless for the cure and needed by the man.",
    '1:44': "Sent to the priest with Moses' offering. The cleansing is certified by the law it came from outside.",
    '1:45': "The healed man's disobedience shuts Jesus out of the towns. Gratitude obstructs when it will not obey.",

    # ---- Chapter 2 ----
    '2:2': "No room, not so much as about the door — and what he did with that crowd was preach the word.",
    '2:3': "Borne of four. The man contributes nothing whatever to his own arrival.",
    '2:4': "They dug through somebody else's roof. Faith here is inconvenient, destructive, and commended.",
    '2:5': "\"When Jesus saw their faith\" — the friends' faith, and he names the sin before the palsy.",
    '2:6': "The objection is raised in the heart, where it can be neither answered nor withdrawn.",
    '2:7': "\"Who can forgive sins but God only?\" The theology is exactly right and the conclusion exactly wrong.",
    '2:8': "He answers the argument they never said out loud. The hidden objection is not hidden.",
    '2:9': "The easier thing to say is the one nobody can check. He does the visible work to prove the invisible.",
    '2:10': "\"That ye may know.\" The healing is evidence, staged for the doubters rather than for the patient.",
    '2:11': "The bed that carried him in, he now carries out. The proof walks home under its own load.",
    '2:12': "\"We never saw it on this fashion.\" They marvel at the walking and say nothing at all about the pardon.",
    '2:14': "Levi is called at the customs table, in the middle of the trade everyone despised him for.",
    '2:15': "\"For there were many.\" Mark notes that the sinners at that table were not a handful but a crowd.",
    '2:16': "The complaint goes to the disciples, not to him. Objections about Christ are raised to somebody else.",
    '2:17': "\"I came not to call the righteous.\" The only people shut out are those who have no need of him.",
    '2:18': "The question compares his disciples unfavourably with two rival parties at once.",
    '2:19': "Fasting at a wedding would be a lie about what is happening. His presence changes what is fitting.",
    '2:20': "\"The bridegroom shall be taken away.\" The first shadow of the cross falls in an answer about fasting.",
    '2:21': "New cloth on an old garment makes the tear worse. What he brings will not serve as a patch.",
    '2:22': "New wine bursts old bottles. The trouble is not that the old is worthless but that it cannot hold this.",
    '2:24': "They never ask whether the men were hungry. The rule is consulted; the men are not.",
    '2:25': "\"Have ye never read?\" He answers the experts out of the book they are standing on.",
    '2:26': "David ate what was not lawful and is not condemned. Need is read within the law, not against it.",
    '2:27': "The sabbath was made for man. The order in which the gift was given settles the whole argument.",
    '2:28': "\"Lord also of the sabbath.\" He is not relaxing the commandment; he is claiming to own it.",

    # ---- Chapter 3 ----
    '3:2': "They watched, hoping he would heal, so that they could accuse him. Mercy had become evidence.",
    '3:3': "\"Stand forth.\" He sets the man in the middle, where the healing cannot be quietly argued away.",
    '3:4': "Do good or do evil, save life or kill. They hold their peace while planning his death.",
    '3:5': "Anger and grief at once. Mark alone records Jesus angry, and hardness of heart is what provokes it.",
    '3:6': "Pharisees and Herodians, enemies to each other, agree on killing him. Opposition makes strange allies.",
    '3:8': "They came because of what they had heard he did. Report of power draws better crowds than preaching.",
    '3:9': "A boat kept ready against the crush. The press of need was a danger he made provision against.",
    '3:10': "They pressed upon him to touch him. The crowd wanted contact; nobody is recorded asking for teaching.",
    '3:11': "The unclean spirits confess him Son of God — the right title, from the wrong mouths, first.",
    '3:12': "He charges them not to make him known. The secret is kept hardest from those most eager to publish it.",
    '3:13': "\"Calleth unto him whom he would.\" The choosing is entirely on his side of the transaction.",
    '3:14': "With him first, then sent. Being with him comes before the work in the job description.",
    '3:15': "The power they will use is delegated, not native. It was his before it was ever theirs.",
    '3:16': "Simon he surnamed Peter. The new name is given long before the man grows into it.",
    '3:17': "Sons of thunder. He names the temperament he has chosen rather than pretending it is not there.",
    '3:19': "\"Judas Iscariot, which also betrayed him.\" He was chosen with the rest, and Mark says so.",
    '3:20': "They could not so much as eat bread. Mark measures the pressure on him by the meals that were missed.",
    '3:21': "His own friends went out to lay hold on him. The first people who tried to stop him were his own.",
    '3:22': "They cannot deny the exorcisms, so they reassign the source. Undeniable good is credited to the devil.",
    '3:23': "\"How can Satan cast out Satan?\" He meets the slander by testing whether it can even stand up.",
    '3:24': "A divided kingdom cannot stand. He grants their premise and lets it dismantle their charge.",
    '3:26': "If Satan were divided he would already be finished. The accusation would be good news if it were true.",
    '3:27': "The strong man must be bound before the house is spoiled. The exorcisms are a burglary already under way.",
    '3:28': "\"All sins shall be forgiven unto the sons of men.\" The widest amnesty in scripture opens the sentence.",
    '3:29': "The one unforgivable sin is named inside that amnesty, and it is calling the Spirit's work devilish.",
    '3:30': "\"Because they said, He hath an unclean spirit.\" Mark names the sin, which is a mercy to the anxious.",
    '3:31': "His mother and brethren stand without and send in for him. The family is outside the circle, literally.",
    '3:33': "\"Who is my mother, or my brethren?\" Not a denial of them so much as a redrawing of the line.",
    '3:34': "He looked round on those sitting there and called them family. Kinship reassigned by where you sit.",
    '3:35': "Whoever does the will of God is brother, sister, mother. The tie that counts is not blood.",
}

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:3': "\"Behold, there went out a sower to sow.\" The parable starts with the one thing nobody in it controls.",
    '4:4': "Some fell by the way side and the birds took it. Loss is written into the method from the first line.",
    '4:5': "It sprang up immediately because it had no depth. Fast growth is here a symptom, not a sign.",
    '4:6': "No root, so the sun finished it. The heat did not create the problem; it revealed it.",
    '4:7': "The thorns did not attack the seed. They simply grew alongside it and crowded it out.",
    '4:8': "Thirty, sixty, a hundred. The yields differ wildly and all three count as good ground.",
    '4:9': "\"He that hath ears to hear, let him hear.\" The parable is left standing with no explanation attached.",
    '4:10': "They wait until he is alone to admit they did not follow it. Even the twelve ask their questions privately.",
    '4:11': "\"Unto you it is given.\" Understanding is spoken of as a gift handed over, not an achievement reached.",
    '4:12': "The hardest sentence in Mark: the parables also conceal. Hearing can be a judgment as well as an offer.",
    '4:13': "\"Know ye not this parable?\" The insiders who were given the mystery still have to have it spelled out.",
    '4:14': "\"The sower soweth the word.\" The whole drama turns on what happens to a word that was preached.",
    '4:15': "Satan comes immediately and takes the word away. The first threat is not hostility but forgetting.",
    '4:16': "Received with gladness, straight away. Delight at the message proves nothing yet about where it landed.",
    '4:17': "Affliction for the word's sake is what offends them. The gospel itself is the pressure that sorts this soil.",
    '4:18': "These hear the word too. All four soils hear; only the ground differs.",
    '4:19': "Cares, riches, and the lust of other things. Nothing evil is named here — only rival goods that crowd.",
    '4:20': "Hear, receive, bear fruit. The good ground does nothing to make itself good; it simply holds the seed.",
    '4:21': "A candle is not lit to be hidden. The secrecy of the kingdom is temporary by design.",
    '4:22': "Nothing is kept secret except that it should come abroad. The hiding is in service of the disclosure.",
    '4:24': "\"Take heed what ye hear.\" Attention is treated as a moral act with consequences attached.",
    '4:25': "To him that hath shall be given. Hearing either grows into more or drains away what was there.",
    '4:27': "He sleeps and rises and knows not how the seed grows. Growth happens on nobody's watch.",
    '4:28': "The earth bringeth forth fruit of herself. Blade, ear, full corn — none of it hurried by the farmer.",
    '4:29': "The sickle goes in when the fruit is ready. The one thing the man does is reap what he did not make.",
    '4:31': "Less than all seeds. The kingdom is introduced at the size where it can easily be overlooked.",
    '4:32': "The birds lodge under its shade. What began too small to notice ends up sheltering others.",
    '4:33': "\"As they were able to hear it.\" He fits the teaching to the hearers rather than to the subject.",
    '4:34': "In public, parables; alone, the explanation. The twelve get more, and still understand very little.",
    '4:35': "\"Let us pass over unto the other side.\" The storm comes while they are doing exactly what he told them.",
    '4:36': "\"Even as he was\" — no preparation, no provisioning. Mark keeps how plain the departure was.",
    '4:37': "The ship was now full. Mark does not soften the danger to make the miracle larger.",
    '4:38': "\"Carest thou not?\" The accusation under most panic is not that he cannot but that he will not.",
    '4:39': "He rebukes the wind as he rebuked the demon. The same authority, applied to weather.",
    '4:40': "\"How is it that ye have no faith?\" He treats their terror as a failure of trust, not of nerve.",
    '4:41': "They feared exceedingly after the calm. The stilled sea frightened them more than the storm had.",

    # ---- Chapter 5 ----
    '5:2': "He lands on Gentile ground and the welcoming party is a man out of the tombs.",
    '5:3': "No man could bind him. Every human remedy had already been tried and had failed.",
    '5:4': "Chains plucked asunder, fetters broken. Restraint had only proved how far past restraint he was.",
    '5:5': "Crying and cutting himself with stones. What possessed him turned him against his own body.",
    '5:6': "He ran and worshipped him. The approach is the man's; the words that follow are not.",
    '5:7': "\"I adjure thee by God.\" The demon tries to work the formula of exorcism on Christ himself.",
    '5:9': "\"My name is Legion: for we are many.\" The man has lost even the ability to say who he is.",
    '5:10': "They beg not to be sent out of the country. Even a devil's request is a petition he grants or refuses.",
    '5:12': "The devils must ask permission to enter pigs. Their power is real and entirely on a leash.",
    '5:13': "Two thousand swine drowned to free one man. Mark lets the cost stand without comment.",
    '5:14': "The herdsmen ran and told it. The news that travelled fastest was the loss, not the deliverance.",
    '5:15': "Sitting, clothed, and in his right mind — and they were afraid. Restoration frightened them.",
    '5:17': "They pray him to depart. He is asked to leave a district he has just emptied of a legion.",
    '5:18': "The healed man asks to come along. The only person in the country who wants him is the one delivered.",
    '5:19': "The request to follow is refused, and ordinary life is handed back as the assignment.",
    '5:20': "He publishes it in Decapolis. The secrecy Jesus enforces in Galilee is not imposed on Gentile ground.",
    '5:22': "A ruler of the synagogue falls at his feet. The official class is not uniformly against him.",
    '5:23': "\"Come and lay thy hands on her.\" Jairus asks for presence and touch, and specifies the method.",
    '5:25': "Twelve years of bleeding, the same span as the girl's whole life. Mark sets the two cases side by side.",
    '5:26': "She had spent all she had and was nothing bettered. Medicine had taken her money and left her worse.",
    '5:27': "She came behind him in the press. Everything about her approach is calculated to avoid being seen.",
    '5:28': "\"If I may touch but his clothes.\" Her theology is half superstition and brings her to the right person.",
    '5:29': "She felt in her body that she was healed. The cure was not announced to her; she discovered it.",
    '5:30': "Virtue had gone out of him. The healing cost him something, even when he was not asked.",
    '5:31': "The disciples find the question absurd. Crowds touch him constantly; faith touches him differently.",
    '5:32': "He looks round to see her. He will not let the healing stay anonymous.",
    '5:33': "Fearing and trembling, she told him all the truth. The confession she dreaded is what he waited for.",
    '5:34': "\"Daughter.\" He gives her a name in the family before he sends her away in peace.",
    '5:35': "\"Why troublest thou the Master any further?\" Death is assumed to be the end of what Jesus is good for.",
    '5:36': "\"Be not afraid, only believe.\" Spoken to a man who has just been told his daughter is dead.",
    '5:38': "He walks into the tumult of professional mourning. The grief in that house was already an industry.",
    '5:39': "\"Not dead, but sleepeth.\" He renames death in front of people who know better, and is right.",
    '5:40': "They laughed him to scorn. The mourners switched to mockery in a single sentence.",
    '5:41': "\"Talitha cumi.\" Mark keeps the Aramaic — somebody remembered the actual sound of the words.",
    '5:42': "She arose and walked. The raising is reported in half a line; the astonishment takes longer.",
    '5:43': "He commands that she be given something to eat. Resurrection, and then supper.",

    # ---- Chapter 6 ----
    '6:2': "They are astonished at the wisdom and hostile to the man. Admiration and offence in the same breath.",
    '6:3': "\"Is not this the carpenter?\" Familiarity with his trade is the reason given for not receiving him.",
    '6:4': "A prophet is without honour in his own house. Nearness makes it harder to believe, not easier.",
    '6:5': "\"He could there do no mighty work.\" Mark writes the sentence plainly and leaves it uncomfortable.",
    '6:6': "He marvelled at their unbelief. The only other thing Mark says astonished him was a Gentile's faith.",
    '6:7': "Sent by two and two, with power given them. Nobody is sent alone and nobody goes on his own authority.",
    '6:8': "No bread, no money, no bag. The orders guarantee they will be dependent on somebody before nightfall.",
    '6:10': "Stay in the first house that takes you. They are forbidden to trade up to better lodging.",
    '6:11': "Shake off the dust. They are given a way to leave rejection behind rather than carry it.",
    '6:12': "The twelve preach repentance — the same message John and Jesus both began with.",
    '6:13': "They anointed with oil and healed. Ordinary means are used alongside delegated power.",
    '6:14': "Herod's guilty conscience supplies the explanation: John risen. Fear invents its own theology.",
    '6:16': "\"It is John, whom I beheaded.\" He names his own crime in the act of identifying Jesus.",
    '6:17': "John's trouble began with a domestic arrangement he had criticised in public.",
    '6:18': "\"It is not lawful for thee.\" John applied the law to the king as if the king were a man.",
    '6:19': "Herodias would have killed him but she could not. The grudge waited, fully formed, for its opportunity.",
    '6:20': "Herod feared John, heard him gladly, and killed him anyway. Enjoying the preaching is not repentance.",
    '6:21': "\"A convenient day.\" Mark marks the birthday as the opportunity that the waiting hatred had wanted.",
    '6:22': "A rash promise made to impress the men at the table. The murder begins as vanity in company.",
    '6:23': "He swore to half his kingdom. The oath was extravagant precisely because he assumed it was safe.",
    '6:24': "\"What shall I ask?\" The girl has no request of her own; her mother has had one ready for months.",
    '6:25': "\"By and by in a charger.\" The daughter adds the platter and the haste; the cruelty becomes her own.",
    '6:26': "Exceeding sorry, and he did it for his oath and his guests. Reputation outweighed conscience.",
    '6:27': "The execution is done offstage, in a prison, at a word. No trial, no charge, no reason given.",
    '6:29': "His disciples came and took up his corpse. The forerunner's story ends with a burial and no rescue.",
    '6:31': "Rest is commanded, not permitted, and the reason given is that they had not had time to eat.",
    '6:33': "The crowd outran the boat. The attempt to withdraw failed before it had properly begun.",
    '6:34': "Sheep not having a shepherd — and what he does about it is teach them. Compassion issues in doctrine.",
    '6:36': "\"That they may buy themselves bread.\" The plan assumes every man must provide for himself.",
    '6:37': "\"Give ye them to eat.\" He hands the impossible job back before he does anything about it.",
    '6:38': "\"How many loaves have ye? go and see.\" He makes them count what little they have before he uses it.",
    '6:39': "Sat down by companies on the green grass. Mark remembers the grass; somebody was there.",
    '6:41': "He gave the loaves to the disciples to distribute. The bread passed through their hands.",
    '6:42': "They did all eat, and were filled. Not a taste apiece — a meal.",
    '6:43': "Twelve baskets over, one for each of the men who said it could not be done.",
    '6:44': "Five thousand men. Mark gives the number and nothing about anyone believing because of it.",
    '6:45': "He constrained them into the ship. They are sent into the night by him, and the wind is against them.",
    '6:46': "He departed into a mountain to pray. The prayer he was seeking at dawn he finally gets after dark.",
    '6:48': "\"Would have passed by them\" — the language of God passing before Moses, used of a man on the water.",
    '6:49': "They supposed it had been a spirit. The sight of him coming to help was the most frightening thing yet.",
    '6:50': "\"It is I; be not afraid.\" The name given at the bush, spoken in the middle of the lake.",
    '6:51': "The wind ceased when he got in. Mark reports their amazement, not their worship.",
    '6:52': "They considered not the miracle of the loaves. A fed man can forget by the next crossing.",
    '6:55': "They carried the sick in beds to wherever they heard he was. A country moving its invalids.",
    '6:56': "They asked to touch the border of his garment. One woman's desperate idea had become the method.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:1': "A delegation comes down from Jerusalem. The scrutiny is now official and has travelled to find him.",
    '7:2': "They saw unwashen hands and found fault. The charge is hygiene raised to the level of holiness.",
    '7:3': "Mark stops to explain the custom, because his readers are Gentiles who would not know it.",
    '7:5': "The charge concerns the tradition of the elders, not the law of God. The substitution is already made.",
    '7:6': "Lips near, heart far. Hypocrisy here is not pretence but a real distance under real worship.",
    '7:7': "\"Teaching for doctrines the commandments of men.\" Worship can be sincere and still be in vain.",
    '7:8': "Laying aside the commandment to hold the tradition. One had to be dropped to make room for the other.",
    '7:9': "\"Full well ye reject the commandment of God.\" The irony is that they are skilful at it.",
    '7:10': "He sets Moses against them. The defence of tradition is answered from the text it claims to guard.",
    '7:11': "Corban made a vow out of what a man owed his parents. Piety became the instrument of neglect.",
    '7:13': "Tradition made the word of God of none effect. It did not deny the commandment; it disabled it.",
    '7:14': "He calls the whole crowd to hear what was said to the scribes. The ruling is made public deliberately.",
    '7:15': "Defilement runs outward, not inward. The whole machinery of clean and unclean is turned around.",
    '7:18': "\"Are ye so without understanding also?\" The disciples are lumped in with the ones who missed it.",
    '7:19': "Mark's aside: thus he purged all meats. A dietary code is set aside in a subordinate clause.",
    '7:21': "The list begins with evil thoughts, before any act. The heart is named as the source, not the victim.",
    '7:22': "Covetousness and pride listed with murder and theft. The respectable sins are not graded lower.",
    '7:23': "\"All these evil things come from within.\" No washing reaches the place the trouble starts.",
    '7:24': "He went to Gentile territory to be hidden, and could not be hid. Even withdrawal fails.",
    '7:25': "A mother with a possessed daughter falls at his feet. She has no standing and comes anyway.",
    '7:26': "A Greek, a Syrophenician. Mark names her foreignness twice before she opens her mouth.",
    '7:27': "\"Let the children first be filled.\" The hardest thing Jesus says to anyone who asks him for help.",
    '7:28': "\"The dogs under the table eat of the children's crumbs.\" She takes the place and claims the table.",
    '7:29': "\"For this saying.\" The one time Jesus grants a request on the strength of an argument.",
    '7:30': "She found it done when she got home. The healing happened at a distance, with no touch and no sign.",
    '7:32': "They ask him to put his hand on the man. The request specifies a method, as Jairus' did.",
    '7:33': "Aside from the multitude, fingers and spittle. The cure is private, physical and undignified.",
    '7:34': "He sighed. The healing costs him something before the word is spoken.",
    '7:35': "\"He spake plain.\" The tongue is loosed as well as the ears, though only the ears were mentioned.",
    '7:36': "The more he charged them, the more they published it. Obedience fails first at the order to be quiet.",
    '7:37': "\"He hath done all things well\" — the language of Genesis, said of a man by a Gentile crowd.",

    # ---- Chapter 8 ----
    '8:2': "\"I have compassion on the multitude.\" The feeding starts as pity, not as a demonstration.",
    '8:4': "\"From whence can a man satisfy these men?\" They ask it having already watched him feed five thousand.",
    '8:5': "\"How many loaves have ye?\" The same question as before, and they answer it as though it were new.",
    '8:6': "He gave thanks, brake, and gave to the disciples. The pattern is fixed long before the upper room.",
    '8:8': "They did eat and were filled, with seven baskets left. A second miracle, in Gentile country this time.",
    '8:11': "They want a sign from the man who has just fed four thousand. A sign was never what they lacked.",
    '8:12': "He sighed deeply and refused. No sign will be given, because no sign would settle it.",
    '8:14': "One loaf in the boat, and they call it no bread. Sitting with the bread of life, counting stock.",
    '8:15': "The leaven of the Pharisees and of Herod — religion and power, both working quietly through the lump.",
    '8:16': "They hear a warning about leaven and conclude he is scolding them about catering.",
    '8:17': "\"Have ye your heart yet hardened?\" The word used of his enemies is now used of the twelve.",
    '8:18': "Eyes that do not see, ears that do not hear. The judgment of chapter four lands on the insiders.",
    '8:19': "He makes them recite the number of baskets. Memory is treated as the cure for anxiety.",
    '8:21': "\"How is it that ye do not understand?\" The question is left hanging without an answer.",
    '8:23': "He leads the blind man out of the town by the hand before doing anything else.",
    '8:24': "\"I see men as trees, walking.\" The only healing in the gospels that works by halves.",
    '8:25': "A second touch, and he saw clearly. The half-cure sits right beside Peter's half-seeing confession.",
    '8:26': "Sent home and told not to go into the town. The cure is given and the publicity refused.",
    '8:27': "\"Whom do men say that I am?\" He asks about the rumours first, on the road, away from crowds.",
    '8:28': "Every answer names a prophet. Public opinion is respectful and entirely short of the mark.",
    '8:29': "\"Thou art the Christ.\" Peter gets it exactly right and is about to show he has understood nothing.",
    '8:30': "He charges them to tell no man. The confession is correct and still not safe to broadcast.",
    '8:31': "\"The Son of man must suffer.\" The must is the point: the cross is not an accident but the appointment.",
    '8:32': "He spake it openly, and Peter rebuked him. The man who just confessed him tries to correct him.",
    '8:33': "\"Get thee behind me, Satan.\" The temptation to skip the cross comes through a friend who means well.",
    '8:34': "Deny himself, take up his cross, follow. The cross is the disciple's road before it is his own.",
    '8:35': "Whoever will save his life shall lose it. Self-preservation is the surest way to lose what is preserved.",
    '8:36': "Gain the world, lose the soul. The exchange rate is stated and there is no version where it works.",
    '8:37': "\"What shall a man give in exchange for his soul?\" Asked because there is nothing to name.",
    '8:38': "Shame now, shame then. What is at stake in embarrassment about Christ is larger than it feels.",

    # ---- Chapter 9 ----
    '9:1': "Some standing here will see the kingdom come with power — and the next scene is the mountain.",
    '9:2': "A high mountain, three men, and he was transfigured. The glory was always there; now it is visible.",
    '9:3': "Whiter than any fuller on earth could make it. Mark reaches for laundry to describe the light.",
    '9:4': "Moses and Elias, the law and the prophets, standing there talking with him.",
    '9:5': "Peter proposes three tabernacles, putting Jesus on a level with the other two.",
    '9:6': "\"He wist not what to say; for they were sore afraid.\" Mark explains the suggestion by naming the fear.",
    '9:7': "\"This is my beloved Son: hear him.\" The correction to Peter's proposal is a command to listen.",
    '9:8': "They saw no man save Jesus only. Moses and Elias withdraw and leave him standing alone.",
    '9:9': "Tell no man till the Son of man is risen. The secret has an expiry date, and it is Easter.",
    '9:10': "They argued about what rising from the dead could mean. They had no category to put it in.",
    '9:11': "They ask about Elias, having just seen him. The theological question survives the experience intact.",
    '9:12': "Restoration comes first and the cross comes anyway. The one does not cancel the other.",
    '9:13': "\"They have done unto him whatsoever they listed.\" John's fate is read as the pattern for his own.",
    '9:14': "He comes down from the glory into an argument his disciples are losing.",
    '9:17': "\"I have brought unto thee my son.\" The father brings the boy to Jesus because the disciples failed.",
    '9:18': "\"And they could not.\" The failure of the twelve is stated plainly, by the man they let down.",
    '9:19': "\"How long shall I suffer you?\" His exasperation falls on the generation, disciples included.",
    '9:20': "The spirit tears the boy the moment it sees Jesus. Nearness to Christ makes the conflict worse first.",
    '9:22': "\"If thou canst do any thing.\" Years of failure have worn the father's request down to a conditional.",
    '9:23': "Jesus hands the if back. The question was never whether he could.",
    '9:24': "\"Lord, I believe; help thou mine unbelief.\" The only honest prayer about faith, and it is answered.",
    '9:25': "He acts when the crowd comes running — quickly, to avoid the spectacle rather than to stage it.",
    '9:26': "The boy was left as one dead. Deliverance looked exactly like defeat for a moment.",
    '9:27': "He took him by the hand and lifted him up, and he arose. The words Mark will use again at the tomb.",
    '9:28': "\"Why could not we cast him out?\" They ask privately, which is where failure usually gets discussed.",
    '9:29': "\"This kind\" — some things do not yield to method or experience, only to prayer.",
    '9:31': "The second passion prediction is given privately. Teaching the twelve has become the priority.",
    '9:32': "They understood not, and were afraid to ask. Fear of the answer kept them ignorant.",
    '9:33': "He asks what they were disputing about on the road. He had let them argue the whole way.",
    '9:34': "The subject was which of them was greatest, argued behind the back of the man going to die.",
    '9:35': "\"Last of all, and servant of all.\" He does not forbid the ambition; he redirects where it must go.",
    '9:36': "He takes a child in his arms as the illustration. The lowest-status person present is the visual aid.",
    '9:37': "Receive the child, receive him; receive him, receive the Father. The chain runs all the way up.",
    '9:38': "\"He followeth not us.\" The objection is about the group's authority, and John states it twice.",
    '9:39': "\"Forbid him not.\" The work done in his name is not policed by the twelve.",
    '9:40': "He that is not against us is on our part. The line is drawn further out than the disciples wanted.",
    '9:41': "A cup of water is enough to count. The smallest service done to Christ's people is not lost.",
    '9:42': "A millstone, for offending one little one. The severity is reserved for harming the least.",
    '9:43': "\"Cut it off.\" Hyperbole with a serious edge: nothing is worth keeping that costs you life.",
    '9:47': "Better one-eyed in the kingdom than whole outside it. The arithmetic of loss is entirely reversed.",
    '9:48': "Isaiah's last verse, quoted three times. Mark will not let the warning be heard once and dropped.",
    '9:49': "\"Every one shall be salted with fire.\" Purging is spoken of as normal, not exceptional.",
    '9:50': "Salt that has lost its saltness cannot be re-salted. The warning ends in a call to be at peace.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:2': "The question about divorce is asked to trap him, not to settle a case. Marriage is being used as bait.",
    '10:3': "\"What did Moses command you?\" He sends them back to the text before he answers.",
    '10:4': "Moses suffered a bill of divorcement. They cite a permission and call it a command.",
    '10:5': "\"For the hardness of your heart he wrote you this precept.\" The law here regulates a wound it did not cause.",
    '10:6': "He goes behind Moses to creation. The argument is settled by what was true before the concession.",
    '10:7': "A man leaves father and mother. The new household outranks the one he came from.",
    '10:8': "\"No more twain, but one flesh.\" The union is described as a fact accomplished, not a goal to reach.",
    '10:9': "What God hath joined together. The joining is God's act; only the sundering is attributed to man.",
    '10:11': "\"Adultery against her.\" A wife is named as someone who can be wronged, which the law scarcely allowed.",
    '10:12': "He states the case of a woman divorcing her husband, which Jewish law did not contemplate.",
    '10:13': "The disciples rebuked the people bringing children. They are guarding his time from the people he wants.",
    '10:14': "\"He was much displeased.\" Mark keeps the flash of anger, aimed at his own men for blocking access.",
    '10:15': "Receive the kingdom as a little child — that is, as someone with nothing to bring and no claim to press.",
    '10:16': "He took them in his arms and blessed them. No lesson is drawn from the children; they are simply blessed.",
    '10:17': "He comes running and kneeling, and asks what he must do. The question already has the wrong verb in it.",
    '10:18': "\"Why callest thou me good?\" He refuses the compliment until the man has thought about what he is saying.",
    '10:19': "He quotes the second table only — the commandments about neighbours, where the man feels safe.",
    '10:20': "\"All these have I observed from my youth.\" Said without hesitation, and Jesus does not contradict it.",
    '10:21': "\"Beholding him loved him.\" The hardest word Jesus speaks to anyone is spoken in love, not exasperation.",
    '10:22': "He went away grieved, for he had great possessions. The one man in the gospels who is called and declines.",
    '10:23': "The difficulty of riches is stated as a general rule, not as one hard case.",
    '10:24': "The disciples are astonished, because wealth was read as a sign of God's favour. He repeats it anyway.",
    '10:25': "A camel through a needle's eye. The image is not difficulty but impossibility, which is the point.",
    '10:26': "\"Who then can be saved?\" They have finally understood, and it has left them with no one qualified.",
    '10:27': "\"With men it is impossible, but not with God.\" Salvation is moved out of the column of achievement.",
    '10:28': "\"Lo, we have left all.\" Peter turns the rich man's failure into a claim on his own account.",
    '10:29': "The list of what is left names houses and family. Following costs actual people, not abstractions.",
    '10:30': "A hundredfold now — and persecutions listed in the same inventory as the houses and lands.",
    '10:31': "Many first shall be last. The sentence lands on men who have just been calculating their position.",
    '10:32': "Jesus went before them and they were afraid. Mark notices that following him had become frightening.",
    '10:33': "Delivered to the priests and then to the Gentiles. He names each hand the betrayal will pass through.",
    '10:34': "Mock, scourge, spit, kill, rise. The detail is exact, and they still hear none of it.",
    '10:35': "\"Whatsoever we shall desire.\" A blank cheque, requested from a man on his way to be killed.",
    '10:36': "\"What would ye that I should do for you?\" He makes them say it out loud rather than refusing in advance.",
    '10:37': "Right hand and left, in his glory. They ask for the places that will be occupied by two thieves.",
    '10:38': "\"Ye know not what ye ask.\" The cup and the baptism are the cross, and they volunteer for it blindly.",
    '10:39': "\"We can.\" They will in fact drink it — the confidence is misplaced but the promise is not withdrawn.",
    '10:40': "\"Not mine to give.\" Even the Son does not distribute those seats; they are prepared by another.",
    '10:41': "The ten are displeased — not at the ambition but at being beaten to it.",
    '10:42': "The Gentile pattern is lordship exercised downward. He describes it accurately before forbidding it.",
    '10:43': "\"So shall it not be among you.\" Greatness is not abolished in the church; its direction is reversed.",
    '10:45': "\"A ransom for many.\" The one verse in Mark that says plainly what the death is for.",
    '10:46': "Blind Bartimaeus, sitting by the highway begging. Mark gives the beggar a name, which he rarely does.",
    '10:47': "\"Thou son of David.\" The messianic title is shouted in public by a blind man at the roadside.",
    '10:48': "The crowd tells him to be quiet and he shouts louder. Faith here is indecorous and will not be managed.",
    '10:49': "\"He calleth thee.\" The same crowd that silenced him now hurries him forward.",
    '10:50': "He cast away his garment — a beggar's cloak was his working capital, and he left it in the road.",
    '10:51': "\"What wilt thou that I should do unto thee?\" The identical question James and John were asked.",
    '10:52': "\"Thy faith hath made thee whole\" — and he followed him in the way, which leads to Jerusalem.",

    # ---- Chapter 11 ----
    '11:2': "A colt whereon never man sat. The detail marks it as fit for sacred use, not merely convenient.",
    '11:3': "\"The Lord hath need of him.\" The only thing Jesus is recorded as needing is a borrowed animal.",
    '11:7': "They cast their garments on the colt. The coronation is improvised out of what people had on.",
    '11:8': "Garments and branches in the road. The welcome is genuine and will not survive the week.",
    '11:9': "\"Hosanna\" means save now. The crowd is asking for rescue and has a particular kind in mind.",
    '11:10': "They shout for the kingdom of David. Right about the King, wrong about the throne.",
    '11:11': "He looked round upon all things and left. The entry ends with an inspection and no speech.",
    '11:13': "Leaves and no figs, and it was not the season. The tree was advertising fruit it did not have.",
    '11:14': "\"And his disciples heard it.\" Mark notes the audience, because the tree is a sermon about the temple.",
    '11:15': "He overthrew the tables. The cleansing is framed by the cursed tree on either side of it.",
    '11:16': "He stopped the temple being used as a shortcut. Even the traffic through it was a kind of contempt.",
    '11:17': "\"A house of prayer for all nations.\" The trade was set up in the one court where Gentiles could pray.",
    '11:18': "They feared him because the people were astonished at his doctrine. The teaching alarmed them.",
    '11:20': "Dried up from the roots. The judgment was complete underground before anything showed above.",
    '11:21': "Peter remembers the curse and reports the withering. He sees a wonder where a warning was intended.",
    '11:22': "\"Have faith in God.\" The answer to a withered tree is not an explanation but a direction to look.",
    '11:23': "The mountain cast into the sea. Said in sight of the temple mount, which is about to be left desolate.",
    '11:24': "Believe that ye receive them. Prayer is described as trusting a giver, not as operating a mechanism.",
    '11:25': "Forgive when you stand praying. The unforgiven grudge is named as the obstacle standing in the room.",
    '11:26': "Refusing forgiveness and expecting it are not compatible positions. The warning is blunt.",
    '11:28': "\"By what authority?\" Having failed to deny the acts, they attack his credentials.",
    '11:29': "He answers a question with a question — not evasion, but a test of whether they will judge honestly.",
    '11:30': "John's baptism, heaven or men. The whole case turns on whether they will say what they actually think.",
    '11:31': "They reason about which answer costs least. Truth is not among the factors they weigh.",
    '11:32': "They feared the people. Their theology is being decided by a crowd estimate.",
    '11:33': "\"We cannot tell.\" The official custodians of the truth plead ignorance to stay safe.",

    # ---- Chapter 12 ----
    '12:1': "Hedge, winefat, tower. The tenants were handed a vineyard somebody else had finished building.",
    '12:2': "He sent at the season for his own fruit. The claim is modest and entirely just.",
    '12:3': "They beat the first servant and sent him away empty. The rebellion begins as robbery, not as argument.",
    '12:4': "The second is wounded in the head and shamefully handled. Each refusal escalates.",
    '12:5': "\"Beating some, and killing some.\" The prophets are summarised in half a sentence of casual violence.",
    '12:6': "\"Having yet therefore one son.\" The owner's patience is the strangest thing in the parable.",
    '12:7': "\"This is the heir.\" They kill him precisely because they recognise him, not because they mistake him.",
    '12:8': "Cast out of the vineyard, then killed. Jesus tells them where he will die before they decide it.",
    '12:9': "The vineyard given to others. The warning that the tenancy can change hands is what they will not hear.",
    '12:10': "The rejected stone becomes the head of the corner. The rejection is not reversed; it is used.",
    '12:12': "They knew the parable was against them and went away to plot. Understanding did not help them.",
    '12:14': "The flattery is entirely accurate. They describe him rightly in the act of trying to destroy him.",
    '12:15': "\"Why tempt ye me? bring me a penny.\" He makes them produce the coin they are carrying.",
    '12:16': "Caesar's image, on a coin in their own hands. The trap is sprung by an inventory of their pockets.",
    '12:17': "The coin bears Caesar's image; the man bears God's. That settles which of the two claims is total.",
    '12:18': "The Sadducees deny the resurrection and then ask a question about it. The case is a joke with a doctrine inside.",
    '12:23': "\"Whose wife shall she be?\" A woman used as a puzzle piece by men arguing about a doctrine they reject.",
    '12:24': "\"Ye know not the scriptures, neither the power of God.\" Two errors, and the second is the larger.",
    '12:25': "The resurrection is not this life extended but this life transfigured.",
    '12:26': "\"I am the God of Abraham.\" The whole argument for resurrection rests on the tense of a verb.",
    '12:27': "God of the living, not the dead. Covenant with God is a bond death is not permitted to end.",
    '12:28': "A scribe asks a real question, because he liked the answers. Not every expert in Mark is an enemy.",
    '12:29': "He begins with the Shema. The first commandment starts with who God is, not with what to do.",
    '12:30': "Heart, soul, mind, strength. The demand is total, which is why it can only ever be received as law.",
    '12:31': "Love of neighbour is not a lesser commandment but the same love turned outward.",
    '12:32': "The scribe repeats the answer back in his own words. He was listening, not scoring a point.",
    '12:33': "More than all burnt offerings. A temple scribe says it, standing in the temple.",
    '12:34': "\"Not far from the kingdom.\" A generous verdict that is still, carefully, not an entry.",
    '12:35': "He raises the question himself this time. The teaching moves from defence to attack.",
    '12:36': "David calls him Lord. The messiah is David's descendant and David's superior at once.",
    '12:37': "\"The common people heard him gladly.\" The crowds enjoy the argument; the enjoyment is not yet faith.",
    '12:38': "Long clothing and salutations. The warning is about religion worn where it can be seen.",
    '12:39': "Chief seats and uppermost rooms. The sin named is the seating chart, which sounds petty and is not.",
    '12:40': "Devouring widows' houses behind long prayers. The prayers are the cover, not a separate fault.",
    '12:41': "He sat and watched how people gave. The giving was public enough to be watched.",
    '12:42': "Two mites, which make a farthing. Mark converts it so his Roman readers feel how little it was.",
    '12:43': "\"Cast more in than all they.\" The accounting is done by what is left, not by what is given.",
    '12:44': "She gave all her living — and he lets her do it, in a temple he has just said is under judgment.",
})

TAKEAWAYS.update({
    # ---- Chapter 13 ----
    '13:1': "A disciple admires the stonework. His men's last word about the temple is a note on the masonry.",
    '13:2': "Not one stone upon another. The building they were proud of is given a demolition date.",
    '13:4': "\"When shall these things be?\" They ask for a timetable, and the answer they get is about endurance.",
    '13:5': "\"Take heed lest any man deceive you.\" The first word about the end is a warning about being fooled.",
    '13:6': "Many shall come in my name. The danger is not opposition but impersonation.",
    '13:7': "Wars and rumours, and yet \"the end shall not be yet.\" Catastrophe is not the same as conclusion.",
    '13:8': "\"The beginnings of sorrows\" — birth pangs. The trouble is productive, not merely destructive.",
    '13:9': "Councils, beatings, rulers. The suffering he predicts for them is institutional and legal.",
    '13:10': "The gospel must first be published among all nations. The delay has a purpose written into it.",
    '13:11': "Take no thought beforehand. The promise is not that they will be clever but that they will not be alone.",
    '13:12': "Brother betraying brother. The persecution will come through families, not only through strangers.",
    '13:13': "Endurance to the end is the evidence of salvation, not the achievement that earns it.",
    '13:14': "\"Let him that readeth understand\" — Mark speaks past the scene to a reader in real danger.",
    '13:15': "Do not go down for your things. The flight is urgent enough that possessions are written off.",
    '13:17': "Woe to them with child. He names who will suffer most, which prophecy rarely stops to do.",
    '13:18': "\"Pray ye that your flight be not in the winter.\" Prayer about the weather, inside an apocalypse.",
    '13:19': "Affliction such as there has never been. Mark does not soften the scale of what is coming.",
    '13:20': "The days are shortened for the elect's sake. Mercy is the reason the worst is cut short.",
    '13:21': "\"Lo, here is Christ\" — the temptation in disaster is to accept any rescuer who is offered.",
    '13:22': "False Christs with real signs. Wonders are no proof; they are precisely the bait.",
    '13:23': "\"I have foretold you all things.\" The defence against deception is having been told beforehand.",
    '13:24': "Sun darkened, moon dark. The language is the prophets' way of saying a world order is ending.",
    '13:26': "The Son of man coming in the clouds — Daniel's figure, which he has been quietly claiming all along.",
    '13:27': "The angels gather the elect from the four winds. The end is a collection, not merely a conflagration.",
    '13:28': "The fig tree again. He uses the tree he cursed as a lesson in reading the season.",
    '13:29': "\"Even at the doors.\" The signs tell you nearness, which is not the same as a date.",
    '13:30': "\"This generation shall not pass.\" The hardest verse to date, and Mark leaves it unexplained.",
    '13:31': "Heaven and earth will go; his words will not. The most permanent thing named is a sentence he spoke.",
    '13:32': "\"Neither the Son, but the Father.\" He says plainly that he does not know, and nobody has softened it.",
    '13:33': "Watch and pray, for ye know not when. Ignorance of the hour is the reason for watching, not an excuse.",
    '13:34': "\"To every man his work.\" Waiting is not idleness; the household has jobs while the master is away.",
    '13:35': "Even, midnight, cockcrowing, morning — the four watches, three of them named in the passion.",
    '13:36': "\"Lest coming suddenly he find you sleeping.\" The next chapter has them asleep in the garden.",
    '13:37': "\"What I say unto you I say unto all.\" The discourse is handed past the four to the reader.",

    # ---- Chapter 14 ----
    '14:1': "They sought to take him by craft. The authorities need secrecy, which is what Judas will sell them.",
    '14:2': "\"Not on the feast day.\" Their plan was to wait, and it is the one detail that does not survive.",
    '14:3': "She brake the box. Nothing is held back for later; the vessel is destroyed along with the contents.",
    '14:4': "\"Why was this waste?\" The objection is economic and sounds entirely reasonable.",
    '14:5': "Three hundred pence, nearly a year's wages, and they murmured against her. The arithmetic was correct.",
    '14:6': "\"She hath wrought a good work on me.\" He calls it good work, which is the language of vocation.",
    '14:7': "\"Me ye have not always.\" The poor remain a standing duty; this occasion does not.",
    '14:8': "\"She hath done what she could.\" The whole commendation is that she did what was in her hand to do.",
    '14:9': "Her act travels with the gospel wherever it is preached. Mark keeps the promise as he writes it.",
    '14:10': "\"One of the twelve.\" Mark repeats the credential every time and never explains the motive.",
    '14:11': "They were glad and promised money. The price is offered after the offer, not before it.",
    '14:13': "A man carrying a pitcher of water was an unusual sight, since that was women's work — so, a signal.",
    '14:15': "A large upper room, furnished and prepared. Somebody had made ready before anyone was sent.",
    '14:18': "\"One of you which eateth with me.\" The betrayal is placed at the table, in the middle of hospitality.",
    '14:19': "\"Is it I?\" Each man doubts himself rather than his neighbour. They knew what they were capable of.",
    '14:20': "One dipping with him in the dish. He identifies the traitor by the intimacy of the gesture.",
    '14:21': "It is written, and still woe to that man. Scripture fulfilled does not turn the betrayer into a victim.",
    '14:22': "\"Take, eat: this is my body.\" He says it holding bread, at a table, and lets the sentence stand.",
    '14:23': "\"And they all drank of it\" — including the man who would betray him and the man who would deny him.",
    '14:24': "\"Shed for many.\" The blood is spoken of as poured out before a drop of it has been spilled.",
    '14:25': "He looks past the cross to a table in the kingdom. The last supper is described as an interrupted meal.",
    '14:26': "They sang a hymn and went out. The walk to Gethsemane begins with the passover psalms.",
    '14:27': "\"I will smite the shepherd.\" The scattering is foretold as God's own doing, not merely their failure.",
    '14:28': "The reunion in Galilee is promised before the desertion has even happened.",
    '14:29': "Peter's confidence rests on a comparison: whatever the others do, he will not.",
    '14:30': "Before the cock crow twice. Jesus knows the count, which makes the warning impossible to misremember.",
    '14:31': "\"Likewise also said they all.\" Every one of them promised it, so the failure is not Peter's alone.",
    '14:32': "\"Sit ye here, while I shall pray.\" He does not want to be alone and does not ask them to come further.",
    '14:33': "Sore amazed and very heavy. Mark uses the strongest words he has for the dread on him.",
    '14:34': "\"My soul is exceeding sorrowful unto death.\" He tells them how bad it is instead of hiding it.",
    '14:35': "He fell on the ground and prayed the hour might pass. The praying is not composed.",
    '14:36': "\"Abba, Father.\" The most intimate address in scripture, used in the request that is refused.",
    '14:37': "\"Simon, sleepest thou?\" He uses the old name, not Peter, at the moment the rock is not holding.",
    '14:38': "\"The spirit truly is ready, but the flesh is weak.\" Diagnosis rather than accusation, and it is exact.",
    '14:39': "He prayed the same words again. Repetition is not unbelief; it is what real urgency sounds like.",
    '14:40': "\"Neither wist they what to answer him.\" There is nothing to say, so Mark records the silence.",
    '14:41': "\"Sleep on now.\" He stops asking. The watching he wanted is no longer needed, and he says so.",
    '14:42': "\"Rise up, let us go.\" He goes to meet the arrest rather than waiting to be found.",
    '14:43': "Swords and staves, sent by priests and scribes. The religious authorities arrive armed.",
    '14:44': "The agreed sign was a kiss. Betrayal chose the gesture of affection because it was most reliable.",
    '14:45': "\"Master, master\" — and kissed him. Judas uses the title of a disciple while handing him over.",
    '14:47': "Someone draws a sword and takes off an ear. The one act of resistance is useless and off target.",
    '14:48': "\"As against a thief.\" He points out that the force assembled tells you what they think of themselves.",
    '14:49': "\"I was daily with you in the temple.\" They had every chance in daylight and needed the dark.",
    '14:50': "\"They all forsook him, and fled.\" Five words, no excuses offered, written by Peter's companion.",
    '14:51': "A young man following in a linen cloth. Mark keeps a detail that serves no purpose in the plot.",
    '14:52': "He fled naked, leaving the cloth. The last disciple in the garden loses even his clothes getting away.",
    '14:54': "He warmed himself at the enemy's fire. The denial begins as proximity, not as cowardice.",
    '14:55': "They sought witness to put him to death, and found none. The verdict was fixed before the evidence.",
    '14:56': "Their witness agreed not together. Even the perjury was incompetent.",
    '14:58': "The false witness is a garbled version of something true. Distortion works best on real material.",
    '14:60': "\"Answerest thou nothing?\" The silence unsettles the court more than a defence would have.",
    '14:61': "Silence under slander, speech under oath. He answers only when asked directly if he is the Christ.",
    '14:62': "\"I am.\" The messianic secret ends here, under oath, at the moment the answer guarantees his death.",
    '14:63': "The high priest rent his clothes — the prescribed response to blasphemy, and the end of the inquiry.",
    '14:64': "They all condemned him. Mark records no dissent and no abstention in the room.",
    '14:65': "\"Prophesy\" — said to a man who had just told them exactly what would happen to him.",
    '14:66': "The interrogation that breaks Peter is conducted by a servant girl, not by the court.",
    '14:67': "\"Thou also wast with Jesus of Nazareth.\" The charge is only that he had been in the company.",
    '14:68': "\"I know not what thou sayest.\" The first denial is a pretence of not understanding the question.",
    '14:70': "His accent gave him away. He could deny the words but not where he was from.",
    '14:71': "The denials escalate into cursing. A lie needs more lies to hold it up.",
    '14:72': "The cock crew, and he wept. Mark gives the collapse and leaves the restoration to the last chapter.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:1': "They bound him and handed him to Pilate. The religious court needed the state to do the killing.",
    '15:2': "\"Art thou the King of the Jews?\" The charge has quietly changed from blasphemy to sedition.",
    '15:3': "They accused him of many things and he answered nothing. The silence is the loudest thing in the trial.",
    '15:4': "Pilate coaches him toward a defence. Even the judge wants him to say something in his own favour.",
    '15:5': "Pilate marvelled. A governor used to men pleading for their lives had not seen this before.",
    '15:7': "Barabbas had actually done what Jesus was charged with. The guilty insurrectionist goes free instead.",
    '15:9': "Pilate calls him King of the Jews to the crowd, half taunt and half attempt at release.",
    '15:10': "Pilate knew it was envy. The motive was plain to the man who gave way to it anyway.",
    '15:11': "The chief priests moved the people. The crowd that chooses Barabbas has been worked on.",
    '15:13': "\"Crucify him.\" The same city that shouted Hosanna five days earlier.",
    '15:14': "\"Why, what evil hath he done?\" The question is never answered, and the sentence is passed anyway.",
    '15:15': "Pilate, willing to content the people. A man condemned to death to settle a public relations problem.",
    '15:16': "They call the whole band together. The mockery is organised entertainment for a garrison.",
    '15:17': "Purple and a crown of thorns. The soldiers stage a coronation as a joke and get it exactly right.",
    '15:18': "\"Hail, King of the Jews.\" The truest words spoken that morning are spoken in sarcasm.",
    '15:19': "They bowed their knees and worshipped him in mockery. The posture will be required of them eventually.",
    '15:21': "Simon is compelled to carry the cross. Mark names his sons, because the church in Rome knew them.",
    '15:23': "Wine mingled with myrrh, and he received it not. He refuses the one thing offered to dull it.",
    '15:24': "The crucifying is a subordinate clause; the gambling over his clothes gets the verb.",
    '15:25': "\"It was the third hour.\" Mark keeps the clock running through the whole afternoon.",
    '15:26': "The charge nailed above him reads THE KING OF THE JEWS. The accusation is a true confession.",
    '15:27': "Two thieves, one on his right and one on his left. The seats James and John asked for are occupied.",
    '15:29': "They throw his own words about the temple back at him, three days before they are proved true.",
    '15:30': "\"Save thyself, and come down.\" The temptation of the wilderness, repeated by passers-by at the end.",
    '15:31': "\"He saved others; himself he cannot save.\" Meant as a sneer, and it is the atonement exactly.",
    '15:32': "They want the sign first. The sign they ask for would have undone the salvation.",
    '15:33': "Darkness from the sixth hour to the ninth. The sun goes out at noon, and Mark offers no explanation.",
    '15:34': "\"Eloi, Eloi, lama sabachthani?\" The only words from the cross Mark records, and he keeps the Aramaic.",
    '15:35': "They mishear it as a call for Elias. Even the cry of dereliction is misunderstood by the bystanders.",
    '15:36': "The vinegar is offered so the show can run longer. Mercy and cruelty in the same gesture.",
    '15:37': "He cried with a loud voice and gave up the ghost. A dying man should not have had that breath left.",
    '15:38': "The veil rent from the top to the bottom — torn from God's side, and the way in is open.",
    '15:39': "The first human being in Mark to confess him Son of God is the Roman who watched him die.",
    '15:40': "The women were looking on afar off. When the men had gone, they were the ones still there.",
    '15:41': "They had followed and ministered to him in Galilee. Mark mentions their long service only at the grave.",
    '15:43': "Joseph went in boldly and asked for the body. A council member breaks ranks after the verdict, not before.",
    '15:44': "Pilate checked with the centurion. The death is confirmed by the men who carried it out.",
    '15:46': "Linen, a rock tomb, a stone rolled to the door. Mark is careful about exactly where the body went.",
    '15:47': "The women beheld where he was laid. The witnesses to the burial are the same ones who return on Sunday.",

    # ---- Chapter 16 ----
    '16:1': "They bought spices to anoint a body. Everything they do assumes the story ended on Friday.",
    '16:2': "Very early, at the rising of the sun. They come at the first hour the law allowed them to travel.",
    '16:3': "\"Who shall roll us away the stone?\" They set out on an errand they had no way of completing.",
    '16:4': "The stone was rolled away, \"for it was very great.\" Mark explains the size after the problem is gone.",
    '16:5': "A young man in white, sitting. The tomb's occupant is at rest, which is not how graves are found.",
    '16:6': "\"He is risen; he is not here: behold the place.\" The evidence offered is an empty shelf.",
    '16:7': "\"Tell his disciples and Peter.\" He is named separately, so he cannot think himself excluded.",
    '16:8': "They said nothing to any man, for they were afraid. Mark ends on fear and an unfinished errand.",
    '16:9': "The first witness is the woman out of whom he had cast seven devils.",
    '16:11': "They believed not. The resurrection is disbelieved first by the people closest to him.",
    '16:12': "He appeared in another form. Even the risen Christ is not immediately recognised by his own.",
    '16:14': "He upbraided them for unbelief and then sent them anyway. The commission is given to men just rebuked.",
    '16:15': "\"Preach the gospel to every creature.\" What was kept secret all through the book is now to be shouted.",
    '16:16': "Believing and baptism are named together. The promise is attached to something done to you.",
    '16:17': "The signs follow them that believe. They follow; they are not what faith is built on.",
    '16:19': "Received up, and sat down on the right hand of God. The sitting means the work is finished.",
    '16:20': "\"The Lord working with them.\" The one they preach is the one doing the work in the preaching.",
})
