#!/usr/bin/env python3
"""Written one-line takeaways for Matthew.

Each states what the verse turns on. Narrative verses that carry no
standalone point — genealogy links, bare connectives, the lead-in half of a
quotation — are left out deliberately; the drawer hides the card rather than
showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Matthew opens by tying Jesus to David and to Abraham: the throne and the promise both land here.",
    '1:2': "The line runs through Judah rather than the firstborn. God's choosing has never followed human precedence.",
    '1:3': "Tamar's name in a royal genealogy is deliberate. Matthew will not tidy up the family Christ was born into.",
    '1:5': "Rahab and Ruth, a Canaanite and a Moabite, stand in Messiah's line. The Gentiles were never an afterthought.",
    '1:6': "\"Her that had been the wife of Urias\" — David's worst hour is left in the record rather than edited out.",
    '1:11': "The genealogy runs straight through the exile. The promise was not cancelled by catastrophe.",
    '1:12': "The line continues on the far side of Babylon. God kept a thread through the wreckage.",
    '1:16': "The pattern breaks: not \"Joseph begat\" but \"of whom was born.\" The line reaches Jesus and stops being ordinary.",
    '1:17': "Matthew counts the generations to show a shape, not to pad. History was going somewhere.",
    '1:18': "The conception is of the Holy Ghost. Whatever Jesus is, he is not the next link in a human chain.",
    '1:19': "Joseph looks for the least damaging way to do right. Righteousness is not automatically the harshest option available.",
    '1:20': "Joseph is addressed as \"son of David\" at the moment he is asked to adopt the Son of God.",
    '1:21': "The name is the mission: he will save his people from their sins, not from their circumstances.",
    '1:22': "Matthew's refrain begins here. What happens to Jesus is what God had already said would happen.",
    '1:23': "Emmanuel. The point of the incarnation is not a message delivered but God present.",
    '1:24': "Joseph obeys before anything has been explained or confirmed to him.",
    '1:25': "Joseph names the child, which is how an adoption was made. The legal line to David runs through his obedience.",

    # ---- Chapter 2 ----
    '2:1': "Foreigners arrive looking for the King of the Jews while Jerusalem has not noticed he is born.",
    '2:2': "They travelled on a light in the sky and a text they half understood, and they came to worship.",
    '2:3': "A rival king troubles Herod, and the city is troubled with him. Power fears what it cannot absorb.",
    '2:4': "Herod consults the experts about a birth he already intends to end.",
    '2:5': "The scribes could give the address and never made the journey. Knowing where Christ is is not the same as going.",
    '2:6': "Bethlehem is called \"not the least,\" because God's choosing reverses the scale men measure by.",
    '2:7': "Herod's diligence is entirely in the service of murder. Zeal proves nothing on its own.",
    '2:8': "\"That I may come and worship him also.\" The language of devotion is available even to the man planning a massacre.",
    '2:9': "The star that first set them going goes before them all the way to the end.",
    '2:10': "They rejoice at the sign. The joy is not yet at the child, but it will be.",
    '2:11': "They find a child in a house and fall down. Worship is given to what looks least like a king.",
    '2:12': "Having met Christ they go home another way. Nobody leaves that house by the road he came in on.",
    '2:13': "God protects his Son by flight rather than by intervention. Rescue is not always deliverance from.",
    '2:14': "Joseph moves at night, on the strength of a dream, into a foreign country.",
    '2:15': "Israel's whole history is replayed in one child: out of Egypt God calls his son.",
    '2:16': "Herod's fury falls on children who could not have threatened him. This is what frightened power does.",
    '2:18': "Matthew quotes Rachel's weeping and leaves it unresolved. The gospel arrives into real grief without explaining it away.",
    '2:19': "The threat dies before the child does. Herods are temporary.",
    '2:20': "\"They are dead which sought the young child's life.\" The sentence outlives the men who passed it.",
    '2:21': "Joseph obeys the second dream as readily as he obeyed the first.",
    '2:22': "Guidance here is caution plus a warning, not certainty. Joseph is afraid and led at the same time.",
    '2:23': "Nazareth, a place of no reputation, is where the Messiah is from. The scandal is part of the fulfilment.",

    # ---- Chapter 3 ----
    '3:1': "The word of God comes in the wilderness rather than the temple. God's next move rarely starts where the institutions are.",
    '3:2': "Repentance is commanded because the kingdom is near, not in order to bring it near.",
    '3:3': "John's whole identity is a voice. A forerunner exists to point away from himself.",
    '3:4': "John's clothing and diet deliberately recall Elijah. The dress is itself a sermon.",
    '3:5': "The crowds go out to the wilderness. The emptiness is where they finally hear it.",
    '3:6': "Baptism here comes with confession. Nobody is washed who has not first admitted the dirt.",
    '3:7': "John calls the religious leadership vipers. Position is no protection from the wrath to come.",
    '3:8': "Fruit is the evidence of repentance, never its substitute and never its cause.",
    '3:9': "Descent from Abraham saves nobody. God can raise children from stones and has no need of your pedigree.",
    '3:10': "The axe is already at the root. John's warning concerns imminence, not possibility.",
    '3:11': "John's baptism points past itself to one who baptizes with the Spirit. The sign was never the substance.",
    '3:12': "The same harvest that gathers wheat burns chaff. Judgement is the other face of salvation.",
    '3:13': "Jesus comes to a baptism meant for sinners, having none of his own to confess.",
    '3:14': "John sees the absurdity at once: the one who ought to be baptizing is asking to be baptized.",
    '3:15': "Jesus takes his place among sinners from the very start. \"All righteousness\" is fulfilled by standing where we stand.",
    '3:16': "The heavens open over a man standing in a river with the guilty.",
    '3:17': "The Father's pleasure is declared before a single miracle or sermon. Sonship is not earned by output.",

    # ---- Chapter 4 ----
    '4:1': "The Spirit leads him out to be tempted. The wilderness is not a detour from God's will but the route of it.",
    '4:2': "Forty days recall Israel's forty years. Where the nation failed, the Son is tested in earnest.",
    '4:3': "\"If thou be the Son of God\" — the attack aims straight at the word just spoken from heaven.",
    '4:4': "Jesus answers hunger with Scripture rather than with power. The Word is enough to stand on.",
    '4:5': "The devil can work the temple as easily as the wilderness. No location is safe ground.",
    '4:6': "Satan quotes Scripture accurately and uses it to urge presumption. A text can be weaponised.",
    '4:7': "Scripture is answered with Scripture. The defence is not cleverness but knowing what else is written.",
    '4:8': "The kingdoms are offered whole, with no cross attached. That is always the offer.",
    '4:9': "Everything Satan offers costs worship, and the price is never the first thing named.",
    '4:10': "Worship belongs to God alone. The answer to a bidding war is a command, not a negotiation.",
    '4:11': "The devil leaves and angels come. The relief arrives after the obedience, not before it.",
    '4:12': "Jesus' public work begins as John's ends. The kingdom advances through the removal of its servants.",
    '4:13': "He settles in Capernaum — off-centre, on the road, where the traffic is.",
    '4:16': "Light springs up on people who were sitting in darkness. Not seeking it; sitting in it.",
    '4:17': "Jesus preaches John's message as his own. Repentance is not a preliminary the gospel outgrows.",
    '4:18': "He calls working men in the middle of their work.",
    '4:19': "The call is \"follow me.\" The usefulness follows the following.",
    '4:20': "They left the nets straightway. Obedience that waits for a better moment is a different thing.",
    '4:21': "James and John are called while mending, not while idle. God interrupts maintenance as readily as crisis.",
    '4:22': "They left the ship and their father. The cost is stated plainly and not softened.",
    '4:23': "Teaching, preaching and healing go together. The kingdom comes to the whole person.",
    '4:24': "The list of afflictions is long and specific, and he healed them. Nobody is a category to him.",
    '4:25': "The crowds come from everywhere, drawn by relief. Multitudes are not yet disciples.",
}

TAKEAWAYS.update({
    # ---- Chapter 5: the Sermon begins ----
    '5:1': "He goes up a mountain and sits down to teach. Matthew means you to have Sinai in mind.",
    '5:3': "The kingdom's first citizens are the spiritually bankrupt. Blessedness starts with having nothing to bring.",
    '5:4': "Mourning is called blessed because God has undertaken to comfort it, not because grief is good in itself.",
    '5:5': "The meek inherit; they do not seize. The earth changes hands by gift rather than by conquest.",
    '5:6': "Hunger for righteousness is itself the qualification. The appetite is not the achievement.",
    '5:7': "Mercy given and mercy received are bound together — though not as payment for each other.",
    '5:8': "Purity is located in the heart, where nobody can inspect it but God.",
    '5:9': "Peacemakers are called children of God because they are doing the family work.",
    '5:10': "Persecution for righteousness' sake carries the same promise as poverty of spirit: the kingdom itself.",
    '5:11': "The blessing turns personal here — \"blessed are ye\" — and the cause given is \"for my sake.\"",
    '5:12': "Being treated as the prophets were is evidence that you are standing where they stood.",
    '5:13': "Salt exists to be tasted in something else. Christians are not preserved for their own sake.",
    '5:14': "A city on a hill has no strategy for hiding. Visibility is a condition, not a decision.",
    '5:15': "Nobody lights a lamp in order to cover it. Concealment defeats the purpose of the gift.",
    '5:16': "The works are seen and the Father gets the glory. Visibility is not self-display when the credit goes elsewhere.",
    '5:17': "Christ came to fulfil the law, not to abolish it. Grace does not dispose of God's demand; it satisfies it.",
    '5:18': "Not a stroke of the law passes away. What is finished is our use of it to justify ourselves.",
    '5:19': "Teaching and doing are joined. What a teacher lives is part of what he teaches.",
    '5:20': "A righteousness exceeding the Pharisees' is required — which rules out getting there by doing more than they did.",
    '5:21': "\"Ye have heard... but I say unto you.\" Jesus speaks with an authority that outranks the tradition.",
    '5:22': "The commandment reaches contempt, not only killing. The law goes further in than we had hoped.",
    '5:23': "Worship is interrupted for reconciliation. God would rather have the brother than the gift.",
    '5:24': "\"First be reconciled.\" The order is not negotiable, and the move is yours even when the grievance is theirs.",
    '5:25': "Settle quickly. Unresolved conflict compounds while you delay.",
    '5:26': "The debt is paid to the last coin. Jesus does not soften what justice costs.",
    '5:28': "Adultery is committed in the heart before the body. The law judges the desire, not only the deed.",
    '5:29': "The language is deliberately violent. Jesus assumes sin is worth losing something over.",
    '5:30': "Repeated for the hand: whatever cutting off costs, it costs less than keeping.",
    '5:32': "Jesus treats marriage as a bond that persists, and divorce as something done to the other person.",
    '5:34': "Oaths are forbidden because every one of them drags God in as collateral.",
    '5:35': "Everything men swear by already belongs to God. There is no neutral thing left to pledge.",
    '5:36': "You cannot guarantee a single hair, which is exactly why your oath guarantees nothing.",
    '5:37': "\"Yea, yea; Nay, nay.\" A person whose word holds needs no oath to shore it up.",
    '5:39': "Not resisting evil breaks the chain instead of extending it. The turned cheek is refusal, not passivity.",
    '5:40': "Give more than was taken. This is not fairness; it is the end of scorekeeping.",
    '5:41': "The second mile is the one nobody can compel. Freedom shows up in what is given past the demand.",
    '5:42': "Giving is commanded with no means test attached to it.",
    '5:43': "\"Hate thine enemy\" appears nowhere in the law. Jesus is correcting an addition, not the Scripture.",
    '5:44': "Love for enemies is commanded as specific acts — bless, do good, pray — not as a feeling to be summoned.",
    '5:45': "God's sun rises on the evil and the good. Loving enemies is family resemblance, not heroism.",
    '5:46': "Loving those who love you is common ground with anybody. It proves nothing about grace.",
    '5:47': "Greeting only your own is the ordinary human minimum, not the kingdom's.",
    '5:48': "The standard is the Father's own completeness, which is why this sermon drives you to mercy rather than to confidence.",

    # ---- Chapter 6: religion done before God ----
    '6:1': "The same act done to be seen loses its reward. Motive decides what a deed is worth.",
    '6:2': "\"They have their reward.\" The applause was the payment, and it has been collected in full.",
    '6:3': "Giving so secret the giver barely tracks it. Generosity is meant to be forgetful.",
    '6:4': "The Father sees in secret, and that is the only audience which finally matters.",
    '6:5': "Prayer performed for an audience gets exactly the audience it played to.",
    '6:6': "The shut door is a mercy. It removes the temptation to be impressive.",
    '6:7': "God is not persuaded by volume. Prayer is not a technique that works by repetition.",
    '6:8': "Your Father knows before you ask, so prayer is not informing God but coming to him.",
    '6:9': "Prayer begins with \"Our Father,\" and with God's name before our needs.",
    '6:10': "\"Thy kingdom come\" asks for God's rule — a larger request than anything we would have thought to want.",
    '6:11': "Daily bread: enough for today, asked for today. A prayer against hoarding as much as against want.",
    '6:12': "Forgiveness asked and forgiveness given are set side by side in a single petition.",
    '6:13': "The prayer ends asking for protection, not achievement. We are kept; we are not self-sustaining.",
    '6:14': "Forgiving others does not earn forgiveness, but an unforgiving heart shows it has not received any.",
    '6:15': "The warning is blunt, and nothing later in the sermon softens it.",
    '6:16': "Even fasting can be staged. Any discipline at all can be turned into a performance.",
    '6:17': "Wash, and look ordinary. Hide the discipline rather than advertising it.",
    '6:18': "The reward comes from the Father who sees in secret, and it is better than being noticed.",
    '6:19': "Earthly treasure is described by what happens to it — moth, rust, theft. It is not wicked, it is perishable.",
    '6:20': "Treasure in heaven is simply treasure kept where it cannot be lost.",
    '6:21': "The heart follows the treasure, not the other way round. Where the money goes, affection follows.",
    '6:22': "A single eye — undivided attention — floods the whole person with light.",
    '6:23': "Light gone dark is the worst case, because you no longer know that you cannot see.",
    '6:24': "Not \"should not\" but cannot. Divided service is not difficult; it is impossible.",
    '6:25': "Anxiety is forbidden on the ground that life is more than the things which sustain it.",
    '6:26': "The birds are fed without storing anything. The argument runs from lesser to greater: you matter more.",
    '6:27': "Worry adds nothing to anything. It is expenditure with no return.",
    '6:28': "Lilies neither toil nor spin, and they are dressed better than Solomon was.",
    '6:29': "Solomon's wardrobe loses to a wildflower. God's ordinary generosity outstrips our best display.",
    '6:30': "Grass burned tomorrow is clothed today. \"O ye of little faith\" is a diagnosis, not a scolding.",
    '6:31': "The anxious questions are quoted back to you so that you can hear how they sound.",
    '6:32': "Your Father knows what you need — which is precisely what the anxious heart has forgotten.",
    '6:33': "Seek first the kingdom and the rest is added. The cure for anxiety is a reordered priority, not a stronger will.",
    '6:34': "Today's trouble is enough. Tomorrow's is not yours to carry yet.",

    # ---- Chapter 7: the Sermon ends ----
    '7:1': "The prohibition is against setting yourself up as judge, not against discernment.",
    '7:2': "The measure you use is the measure used on you. Judgement turns out to be self-administered.",
    '7:3': "The comedy is the point: a beam and a speck, and the beam is the one in your own eye.",
    '7:4': "Offering to fix someone while blind yourself is not help.",
    '7:5': "The beam comes out first, and then you do see clearly to help. Removing the speck is still the goal.",
    '7:6': "Holy things are not to be forced on those who will only trample them. Discernment is the other half of verse 1.",
    '7:7': "Ask, seek, knock — three verbs, all of them assuming God intends to answer.",
    '7:8': "\"Every one that asketh receiveth.\" The promise carries no qualifying clause about worthiness.",
    '7:9': "No father hands his child a stone. The argument runs from ordinary fatherhood upward.",
    '7:10': "Nor a serpent for a fish. God does not answer a request with cruelty.",
    '7:11': "\"If ye then, being evil\" — even bad fathers give good gifts. How much more your Father.",
    '7:12': "Do to others what you would want done. Jesus calls this the sum of the law and the prophets.",
    '7:13': "The wide gate is wide because it asks nothing. A crowd is no evidence of where a road goes.",
    '7:14': "The narrow way is found, not stumbled into. Few find it, and Jesus says so plainly.",
    '7:15': "False prophets come in sheep's clothing, which is to say they will not look false.",
    '7:16': "Fruit, not claims, is the test. What a teaching produces tells you what it is.",
    '7:17': "What a tree is determines what it yields. Behaviour reveals a nature rather than creating one.",
    '7:18': "The impossibility runs both ways, which is why the test is reliable.",
    '7:19': "Fruitlessness by itself is grounds for the fire. Nothing further is required against the tree.",
    '7:20': "The test is repeated for emphasis: by their fruits, not by their words.",
    '7:21': "Saying \"Lord, Lord\" is not the entrance. Doing the Father's will is.",
    '7:22': "Prophecy, exorcism and mighty works are all claimed here — and none of them settles the question.",
    '7:23': "\"I never knew you.\" The issue is not performance but acquaintance.",
    '7:24': "The wise man is the one who hears and does. Both halves are required.",
    '7:25': "Rain, flood and wind hit both houses. The storm is not a test of whether God is pleased with you.",
    '7:26': "The foolish man heard too. Hearing without doing is the specific thing named.",
    '7:27': "\"Great was the fall of it.\" What was built on hearing alone comes down all at once.",
    '7:28': "The crowds are astonished at his teaching, not first of all at his miracles.",
    '7:29': "He taught with authority rather than by citing authorities, and the difference was audible.",
}) 

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:2': "\"If thou wilt\" — the leper doubts the willingness, never the power. That is often where faith actually falters.",
    '8:3': "He touched the untouchable. The uncleanness did not travel to Christ; the cleansing travelled to the leper.",
    '8:4': "Jesus sends him to the priest. The healing is to be certified by the very system that had excluded him.",
    '8:5': "A Roman officer comes asking. The occupying power arrives as a petitioner.",
    '8:6': "He comes for a servant, not for himself. The request costs him something and gains him nothing.",
    '8:8': "\"Speak the word only.\" He asks for less than was offered, because he believes the word is enough.",
    '8:9': "A man under authority recognises authority. He reads Jesus' command as being of the same kind, and higher.",
    '8:10': "Jesus marvels — and the faith that astonishes him is a Gentile's.",
    '8:11': "Outsiders will sit down with Abraham. The table is fuller than the insiders expected.",
    '8:12': "\"The children of the kingdom\" can be the ones cast out. Proximity is not possession.",
    '8:13': "The servant is healed at a distance, at the moment the word is spoken.",
    '8:14': "He heals in a private house, with no crowd and nothing to gain by it.",
    '8:15': "She rose and served them. The first use of restored strength is ordinary work.",
    '8:16': "He cast out the spirits with his word. Authority needs no ritual to make it work.",
    '8:17': "The healings are read as Isaiah's Servant bearing our sicknesses. They cost him something.",
    '8:19': "The scribe volunteers \"whithersoever.\" Jesus answers by telling him what that means.",
    '8:20': "The Son of man has nowhere to lay his head. Following him is not a route to security.",
    '8:21': "\"Suffer me first.\" The word that ruins discipleship is usually not no, but first.",
    '8:22': "The reply is deliberately severe. Jesus will not let even a good delay become the real answer.",
    '8:24': "The storm is real and he is asleep in it. His peace is not ignorance of the danger.",
    '8:25': "\"Lord, save us: we perish.\" A poor prayer, prayed in panic, and it is answered.",
    '8:26': "He rebukes the fear before he rebukes the sea. The storm was the smaller problem.",
    '8:27': "\"What manner of man is this?\" The miracle raises a question about him, not merely about the weather.",
    '8:28': "The demoniacs live among tombs, cut off from everyone. Evil isolates before it destroys.",
    '8:29': "The demons know exactly who he is. Right doctrine about Christ is not the same as being his.",
    '8:31': "Even the demons must ask permission. Their power is real and entirely on a leash.",
    '8:32': "One word — \"Go\" — and it is done. No struggle is recorded.",
    '8:34': "The city asks him to leave. Deliverance that costs the local economy is not always welcome.",

    # ---- Chapter 9 ----
    '9:2': "He forgives before he heals. The paralysis was not the man's deepest problem, and Jesus says so first.",
    '9:3': "The scribes are right that only God forgives sins. They draw every conclusion but the correct one.",
    '9:4': "He answers thoughts they never spoke aloud.",
    '9:5': "Easier to say, harder to prove — so he does the provable thing to establish the unprovable one.",
    '9:6': "The healing exists to demonstrate the authority to forgive. The miracle is the lesser act.",
    '9:8': "The crowd glorifies God for power given to men. They see more than the scribes did.",
    '9:9': "A tax collector at his booth, called in the middle of a despised trade, and he rose and followed.",
    '9:10': "Jesus eats with publicans and sinners. The meal is the offence, because a shared table meant acceptance.",
    '9:11': "The Pharisees ask the disciples rather than Jesus. Objections often travel sideways.",
    '9:12': "The sick need the physician. Whoever thinks himself whole has ruled himself out of the consultation.",
    '9:13': "\"I will have mercy, and not sacrifice.\" Jesus sends the experts back to learn their own book.",
    '9:14': "John's disciples ask about fasting. Sincere religious people are puzzled by the freedom of Jesus' friends.",
    '9:15': "You do not fast at a wedding. The presence of the bridegroom changes what the moment calls for.",
    '9:16': "New cloth on an old garment tears worse. What Jesus brings will not be fitted into the old frame.",
    '9:17': "New wine needs new skins. The gospel is not a patch on an existing religion.",
    '9:18': "A synagogue ruler kneels and asks. Desperation crosses lines that respectability had drawn.",
    '9:20': "Twelve years of bleeding meant twelve years of being unclean. She reaches for the hem rather than the man.",
    '9:21': "\"If I may but touch.\" Her theology is imperfect and her faith is real.",
    '9:22': "He turns and calls her Daughter. She wanted to leave unnoticed; he insists on the relationship.",
    '9:24': "\"Not dead, but sleepeth\" — and they laughed. Christ's view of death is comic to those who have measured it.",
    '9:25': "He took her by the hand. A dead body made him unclean by law; here the touch runs the other way.",
    '9:27': "\"Thou son of David\" — blind men see the messianic title the sighted keep missing.",
    '9:28': "\"Believe ye that I am able?\" He asks for the confession before he gives the sight.",
    '9:29': "\"According to your faith\" — not as a measure of merit but as the empty hand that receives.",
    '9:30': "He charges them to keep quiet. He is not building a following on spectacle.",
    '9:32': "They bring him a man who cannot speak for himself. Somebody else carried the request.",
    '9:33': "\"It was never so seen in Israel.\" The crowd concludes that something unprecedented is happening.",
    '9:34': "The same evidence produces worship in one group and slander in another.",
    '9:35': "Teaching, preaching, healing — the same threefold work, now taken through every village.",
    '9:36': "The compassion is aroused by sheep without a shepherd. What moves him is their leaderlessness.",
    '9:37': "The shortage is not in the harvest but in the labourers.",
    '9:38': "The first response commanded is prayer — and those who pray it tend to become the answer.",

    # ---- Chapter 10 ----
    '10:1': "He gives them his own authority before he gives them their instructions.",
    '10:2': "The list begins with Peter, who will deny him. These are the men, named and known.",
    '10:4': "\"Judas Iscariot, who also betrayed him.\" The traitor is in the list from the start, and Jesus chose him.",
    '10:5': "The first mission is limited to Israel. God's purposes unfold in an order, not all at once.",
    '10:6': "\"The lost sheep of the house of Israel\" — the shepherdless crowd of 9:36 now has men sent to it.",
    '10:7': "The message is the one John preached and Jesus preached. Nothing new is asked of them.",
    '10:8': "\"Freely ye have received, freely give.\" What was never bought cannot rightly be sold.",
    '10:9': "They travel without funds, which leaves them dependent on the people they are sent to.",
    '10:10': "\"The workman is worthy of his meat.\" Dependence is not degradation; it is how the gospel travels.",
    '10:11': "Stay where you first lodge. No upgrading to better hospitality once the town has seen you.",
    '10:13': "Peace offered can return unreceived. The messenger is not responsible for the reception.",
    '10:14': "Shake off the dust and move on. Rejection is to be left behind rather than argued with indefinitely.",
    '10:15': "Sodom fares better than a town that heard and refused. Light received raises the stakes.",
    '10:16': "Sheep among wolves, wise as serpents, harmless as doves — no promise of safety, and no licence for cunning.",
    '10:17': "\"Beware of men.\" Jesus tells them the cost in advance rather than after they have signed on.",
    '10:18': "Being dragged before governors is reframed as testimony. The trial becomes the pulpit.",
    '10:19': "Take no thought for what to say. The anxiety is forbidden, not the preparation.",
    '10:20': "\"It is not ye that speak, but the Spirit.\" The words will be given when they are needed, not before.",
    '10:21': "Families will divide over him. Jesus does not pretend the cost will stay outside the home.",
    '10:22': "Hated of all men, and he that endures to the end shall be saved. Endurance, not intensity, is the mark.",
    '10:23': "Flight is permitted. Courage does not require standing still when moving on serves the mission.",
    '10:24': "The disciple is not above his master. Expect the treatment he received.",
    '10:25': "They called the master Beelzebub. The household should not be surprised by the same slander.",
    '10:26': "Nothing stays covered. Present misrepresentation is temporary, and that is the ground for not fearing.",
    '10:27': "What is heard in private is to be preached on the housetops. The gospel has no confidential tier.",
    '10:28': "Fear the one who holds the soul. Rightly placed fear is what dissolves every other kind.",
    '10:29': "Not one sparrow falls without your Father. The verse does not promise no falling.",
    '10:30': "The hairs of your head are numbered — an absurd level of attention, which is the point.",
    '10:31': "\"Ye are of more value than many sparrows.\" The comparison is meant to be almost insulting in its ease.",
    '10:32': "Confessing Christ before men is met by his confessing us before the Father.",
    '10:33': "The reverse is stated with equal plainness, and Peter will need the rest of the story.",
    '10:34': "Not peace but a sword. The division is a consequence of his coming, not its purpose defeated.",
    '10:35': "The division runs through households. Christ will not be added quietly to an existing arrangement.",
    '10:37': "Loving family more than him disqualifies. He claims the place no one else may claim.",
    '10:38': "The cross is taken up, not merely accepted. A man carrying one was already on his way to die.",
    '10:39': "Grasping life loses it; losing it for his sake finds it. The economy is inverted at every point.",
    '10:40': "Receiving the messenger is receiving Christ, and receiving Christ is receiving the Father.",
    '10:41': "A reward for receiving a prophet, given to someone who never prophesied.",
    '10:42': "A cup of cold water is not overlooked. The smallest kindness done in his name is counted.",

    # ---- Chapter 11 ----
    '11:2': "John, in prison, sends to ask. Doubt reaches the greatest of the prophets, and he takes it to Jesus.",
    '11:3': "\"Art thou he?\" The question is honest, and Jesus never rebukes him for asking it.",
    '11:4': "The answer is evidence rather than reassurance. Go and tell him what you hear and see.",
    '11:5': "The list ends with the poor having the gospel preached to them — the climax, not the afterthought.",
    '11:6': "\"Blessed is he whosoever shall not be offended in me.\" Jesus knows he is not what was expected.",
    '11:7': "\"A reed shaken with the wind?\" Jesus defends John publicly at the moment John is wavering privately.",
    '11:8': "Soft clothing belongs in kings' houses. John's life was itself a verdict on the court that jailed him.",
    '11:9': "More than a prophet: the one prophets had pointed toward now has someone pointing at him.",
    '11:11': "None greater than John — and the least in the kingdom is greater. Position in Christ outranks personal stature.",
    '11:12': "The kingdom suffers violence. It advances against resistance, not on a smooth road.",
    '11:14': "\"If ye will receive it.\" Even a plain identification has to be received; evidence does not compel faith.",
    '11:15': "\"He that hath ears to hear\" — the trouble was never the volume.",
    '11:16': "Children in the marketplace who will not play either game. The generation objects to whatever is offered.",
    '11:18': "John fasted and was called demon-possessed.",
    '11:19': "Jesus ate and was called a glutton. Any stick will do when the refusal is already decided.",
    '11:20': "The upbraiding falls on the cities that saw most. Privilege of exposure carries weight.",
    '11:21': "Tyre and Sidon would have repented. Jesus states plainly that some who never heard would have responded better.",
    '11:23': "Capernaum, his own base, is warned most sharply. Nearness to Christ is the greater danger when unrepented.",
    '11:25': "Hidden from the wise, revealed to babes — and Jesus thanks the Father for it.",
    '11:26': "\"So it seemed good in thy sight.\" Election is met here with gratitude rather than with argument.",
    '11:27': "No one knows the Father except through the Son's revealing. Access runs through a person.",
    '11:28': "The invitation is to the labouring and heavy laden, and what is offered is rest — not a better technique.",
    '11:29': "A yoke is still a yoke; but this master is meek and lowly, and the rest is found in him rather than after him.",
    '11:30': "Easy and light — not because less is asked, but because he is pulling.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:1': "Hungry men picking grain on the sabbath. The controversy starts with something entirely ordinary.",
    '12:2': "The Pharisees are watching the disciples rather than listening to the teacher.",
    '12:3': "\"Have ye not read?\" Jesus answers the experts from the text they claim to guard.",
    '12:4': "David ate the shewbread. Scripture itself records mercy overriding ritual when need was real.",
    '12:5': "The priests work on the sabbath and are blameless. The law was never as simple as the accusers claimed.",
    '12:6': "\"One greater than the temple.\" The claim is larger than the sabbath argument it settles.",
    '12:7': "Mercy, not sacrifice — quoted again, because they still had not learned it.",
    '12:8': "The Son of man is Lord of the sabbath. He does not abolish the day; he claims it.",
    '12:10': "They ask a legal question in order to build a case. The withered hand is incidental to them.",
    '12:11': "They would rescue a sheep without hesitating. The argument is from their own instincts.",
    '12:12': "\"It is lawful to do well on the sabbath days.\" Doing good never needed a permit.",
    '12:13': "He heals with a word, giving them nothing to charge him with — and they charge him anyway.",
    '12:14': "They leave a healing and go to plot a killing. On the sabbath.",
    '12:15': "He withdraws rather than confronts. There is a time to avoid the fight.",
    '12:18': "Matthew reads the whole ministry through Isaiah's Servant: chosen, beloved, Spirit-anointed.",
    '12:19': "He will not strive or cry aloud. The Messiah's method is quieter than anyone expected.",
    '12:20': "A bruised reed he will not break. Christ's gentleness with the barely-holding-on is prophesied, not incidental.",
    '12:21': "The Gentiles will trust in his name. It was always going that far.",
    '12:22': "Blind and dumb and possessed — and he healed him. Matthew records the compounding need without comment.",
    '12:23': "The crowd starts asking the right question. The leaders move to shut it down.",
    '12:24': "Unable to deny the work, they attack its source. Undeniable evidence gets reinterpreted, not accepted.",
    '12:25': "A divided kingdom falls. Jesus answers the slander with plain logic.",
    '12:27': "\"By whom do your children cast them out?\" The charge condemns their own people too.",
    '12:28': "If the Spirit is casting out devils, the kingdom has arrived — which is the thing they are refusing.",
    '12:29': "The strong man must be bound before his house is spoiled. Every exorcism is evidence of a binding already done.",
    '12:30': "There is no neutral position with respect to Christ. Not gathering is scattering.",
    '12:31': "Every sin is forgivable except the settled refusal that calls the Spirit's work demonic.",
    '12:32': "The unforgivable sin is not a slip of the tongue but the hardened attribution of God's work to Satan.",
    '12:33': "Make the tree good and the fruit follows. You cannot fix the fruit while the tree is what it is.",
    '12:34': "\"Out of the abundance of the heart the mouth speaketh.\" Speech is overflow, not decoration.",
    '12:35': "A man brings out of his treasure what is in it. Words reveal stock rather than create it.",
    '12:36': "Idle words are accounted for. What we say carelessly may reveal most accurately.",
    '12:37': "Justified or condemned by your words, because they report what the heart holds.",
    '12:38': "After all the signs, they ask for a sign. The demand is a way of not deciding.",
    '12:39': "Only the sign of Jonah — which is to say, a death and a rising, not a spectacle.",
    '12:40': "Jesus predicts his burial and resurrection in the middle of an argument about signs.",
    '12:41': "Nineveh repented at far less. Greater light refused is a heavier account.",
    '12:42': "The queen of the south crossed the world to hear wisdom. A greater than Solomon was at hand and ignored.",
    '12:43': "An empty house is not a safe house. Reformation without occupation leaves room.",
    '12:45': "The last state worse than the first. Moral tidying that stops short of Christ is dangerous, not neutral.",
    '12:46': "His own family stands outside asking for him.",
    '12:48': "\"Who is my mother?\" The question is not a rejection but a redefinition about to be made.",
    '12:50': "Whoever does the Father's will is family. The nearest relation to Christ is obedience, not blood.",

    # ---- Chapter 13 ----
    '13:3': "He teaches in parables — stories that reveal to the willing and conceal from the settled.",
    '13:4': "The sower scatters where birds wait. Some of the word will be taken before it lands.",
    '13:5': "Quick growth on shallow soil. Immediate enthusiasm is not evidence of depth.",
    '13:6': "No root, so the sun that should have grown it killed it.",
    '13:7': "Thorns do not attack the seed; they simply grow too, and crowd it out.",
    '13:8': "Good ground yields thirty, sixty, a hundredfold. The harvest is wildly out of proportion to the sowing.",
    '13:9': "\"Who hath ears to hear, let him hear.\" The parable does its own sorting.",
    '13:10': "Even the disciples have to ask why he teaches this way.",
    '13:11': "The mysteries are given, not deduced. Understanding is a gift before it is an achievement.",
    '13:12': "To him that hath shall be given. Response to light is met with more; refusal loses what it had.",
    '13:13': "Seeing they see not. The problem is never the clarity of the word.",
    '13:15': "A heart waxed gross, ears dull, eyes deliberately closed. The closing is theirs.",
    '13:16': "\"Blessed are your eyes, for they see.\" Sight is counted a blessing, which means it was given.",
    '13:17': "Prophets longed to see what the disciples are watching casually.",
    '13:19': "The word is snatched from the one who does not understand it. Comprehension is a battleground.",
    '13:20': "Received with joy — and joy alone proves nothing about what will last.",
    '13:21': "Tribulation exposes rootlessness. The trouble does not cause the fall; it reveals it.",
    '13:22': "Care and riches both choke. Anxiety and comfort kill the word by the same method.",
    '13:23': "The good ground hears and understands and bears fruit. All three, in that order.",
    '13:25': "The enemy sows while men sleep. Opposition works quietly and at night.",
    '13:26': "The tares only show when the fruit does. Time reveals what planting concealed.",
    '13:28': "\"Wilt thou that we go and gather them up?\" The servants' instinct is to purge immediately.",
    '13:29': "Uprooting tares would uproot wheat. Zeal for purity damages what it means to protect.",
    '13:30': "\"Let both grow together until the harvest.\" A mixed field is not a failed field, and the sorting is not ours.",
    '13:31': "The smallest seed. The kingdom's beginnings look negligible on purpose.",
    '13:32': "It becomes a tree that birds lodge in. Small beginnings are not small endings.",
    '13:33': "Leaven works hidden and throughout. The kingdom spreads by permeation rather than display.",
    '13:35': "Parables utter what was kept secret from the foundation of the world.",
    '13:37': "The sower is the Son of man. He is not only the teller of the parable but a figure inside it.",
    '13:38': "\"The field is the world\" — not the church. The mixture Jesus describes is wider than a congregation.",
    '13:39': "The harvest is the end of the age and the reapers are angels. The sorting is scheduled and staffed.",
    '13:41': "What is gathered out is \"all things that offend\" — the removal is of what spoils, for the sake of what remains.",
    '13:43': "\"Then shall the righteous shine forth as the sun.\" The end of the parable is glory, not only judgement.",
    '13:44': "He sells all he has for joy. The cost is real and the joy makes it no sacrifice at all.",
    '13:45': "The merchant was already looking. Some are found while searching and some while not.",
    '13:46': "One pearl worth everything else. Christ is not added to a portfolio; he replaces it.",
    '13:47': "The net gathers of every kind. The visible church is mixed by design until the shore.",
    '13:48': "The sorting happens on the beach, not in the water.",
    '13:50': "Matthew will not let the parables end in comfort alone. The furnace is named twice in one chapter.",
    '13:51': "\"Have ye understood?\" They say yes, and the rest of the gospel will test the answer.",
    '13:52': "The instructed scribe brings out things new and old. The gospel does not discard the Scriptures it fulfils.",
    '13:54': "His own town is astonished — and astonishment turns to offence.",
    '13:55': "\"Is not this the carpenter's son?\" Familiarity supplies the objection.",
    '13:57': "A prophet is without honour at home. Nearness can blind more thoroughly than distance.",
    '13:58': "Unbelief is named as the cause, and the withholding sits on their side of the room, not his.",

    # ---- Chapter 14 ----
    '14:2': "Herod's guilty conscience supplies the explanation. Murder is not so easily forgotten.",
    '14:3': "John was imprisoned for telling a king the truth about his marriage.",
    '14:4': "\"It is not lawful for thee.\" John applies the law to the man who could kill him for it.",
    '14:5': "Herod feared the crowd more than he feared God. That is the whole of his character.",
    '14:8': "The girl asks what her mother told her to ask. Evil is passed down as well as committed.",
    '14:9': "\"The king was sorry: nevertheless.\" He kills a prophet rather than lose face at a dinner.",
    '14:10': "The greatest born of women dies offstage, at a party, for a promise made while drunk on applause.",
    '14:12': "John's disciples bury him and go and tell Jesus. Grief is carried to the right place.",
    '14:13': "He withdraws to be alone and the crowd follows on foot. The retreat is interrupted.",
    '14:14': "Grieving, he is moved with compassion and heals them. His sorrow did not make him unavailable.",
    '14:15': "The disciples' solution is to send people away. It is the reasonable answer.",
    '14:16': "\"Give ye them to eat.\" He hands the impossible task back to them.",
    '14:17': "Five loaves and two fishes — stated as an objection, and it becomes the material.",
    '14:18': "\"Bring them hither to me.\" The inadequate supply has to be handed over before it multiplies.",
    '14:19': "He blessed, brake, and gave to the disciples, who gave to the crowd. The feeding passes through their hands.",
    '14:20': "Twelve baskets left. God's provision does not run to the edge and stop.",
    '14:21': "Five thousand men besides women and children. Matthew lets the number speak.",
    '14:22': "He constrained them to get into the ship — the storm ahead is not an accident of scheduling.",
    '14:23': "After feeding thousands he goes up alone to pray. The crowd did not replace the Father.",
    '14:25': "He comes in the fourth watch — the darkest part, and the last. Late is not absent.",
    '14:26': "They are more frightened by Christ approaching than by the storm.",
    '14:27': "\"It is I; be not afraid.\" The cure for the fear is his own name.",
    '14:28': "\"If it be thou, bid me come.\" Peter asks for a command, not an adventure.",
    '14:29': "\"Come.\" One word, and a man walks on water.",
    '14:30': "He looked at the wind. Sinking begins where attention shifts.",
    '14:31': "\"Immediately Jesus stretched forth his hand.\" The rebuke comes after the rescue, not instead of it.",
    '14:33': "The men in the boat worship and confess him Son of God — the first such confession in the gospel.",
    '14:36': "They ask only to touch the hem, and as many as touched were made whole.",

    # ---- Chapter 15 ----
    '15:2': "The charge is breaking tradition, not breaking the law. The two had quietly merged.",
    '15:3': "He answers a question about tradition with a question about the commandment of God.",
    '15:5': "\"It is a gift\" — a pious formula used to avoid supporting one's parents.",
    '15:6': "Tradition had made the commandment of none effect. Religion can be the instrument of disobedience.",
    '15:8': "Lips near, heart far. Isaiah's diagnosis is quoted as still current.",
    '15:9': "Worship is called vain when the doctrines taught are human commandments.",
    '15:11': "Defilement travels outward, not inward. The whole purity system is turned around in a sentence.",
    '15:12': "The disciples report that the Pharisees were offended, as though that settled something.",
    '15:13': "Every plant the Father has not planted will be rooted up. Not everything religious is from God.",
    '15:14': "\"Let them alone.\" Some opposition is to be left rather than answered.",
    '15:16': "\"Are ye also yet without understanding?\" The disciples are as slow as the crowd.",
    '15:18': "What comes out proceeds from the heart. The mouth is a window, not the source.",
    '15:19': "The list runs from thoughts to murders. Evil deeds begin where nobody can see them.",
    '15:20': "Unwashed hands defile nobody. The real contamination was never on the outside.",
    '15:22': "A Canaanite woman uses a Jewish title — \"son of David\" — and asks for mercy.",
    '15:23': "He answered her not a word, and the disciples want her removed. The silence is the hardest part of the story.",
    '15:24': "\"I am not sent but unto the lost sheep of Israel.\" The order of the mission is stated, not her exclusion.",
    '15:25': "\"Lord, help me.\" Three words, after the silence and the refusal.",
    '15:26': "The word Jesus uses is confronting, and he lets her answer it rather than softening it himself.",
    '15:27': "\"Truth, Lord: yet the dogs eat of the crumbs.\" She accepts the place and still claims the table.",
    '15:28': "\"Great is thy faith.\" The two people whose faith he calls great in Matthew are both Gentiles.",
    '15:30': "They cast the sick down at his feet, and he healed them. No screening, no sequence.",
    '15:31': "They glorified the God of Israel — Gentile crowds, praising Israel's God.",
    '15:32': "\"I have compassion on the multitude.\" The feeding begins with what he feels, not what they ask.",
    '15:33': "The disciples ask where bread could come from, having watched him feed five thousand.",
    '15:37': "Seven baskets over. The second feeding is not a repetition but a second proof for slow learners.",
})

TAKEAWAYS.update({
    # ---- Chapter 16 ----
    '16:1': "Pharisees and Sadducees, who agreed on almost nothing, unite against Jesus.",
    '16:3': "They can read the sky and not the times. Skill in one kind of discernment is no guarantee of another.",
    '16:4': "Again only the sign of Jonah — and this time he simply leaves them.",
    '16:6': "\"Beware of the leaven.\" False teaching works like yeast: small, quiet, and through the whole lump.",
    '16:7': "They think he is talking about lunch. The disciples' literalism is almost comic.",
    '16:8': "\"O ye of little faith\" — spoken over an anxiety about bread by men who had watched two feedings.",
    '16:9': "\"Do ye not yet remember?\" Forgetting what God has already done is the root of present anxiety.",
    '16:12': "They finally understand it was about doctrine. Some lessons land only after the third attempt.",
    '16:13': "\"Whom do men say that I am?\" He asks for the public verdict before he asks for theirs.",
    '16:14': "Every popular answer is a compliment, and every one of them is wrong.",
    '16:15': "\"But whom say ye that I am?\" The question every reader of the gospel eventually stands in front of.",
    '16:16': "\"Thou art the Christ, the Son of the living God.\" The confession the whole book has been driving toward.",
    '16:17': "Flesh and blood did not reveal it. Peter's insight is a gift, which is why it is called blessed.",
    '16:18': "The church is built by Christ, on what Peter confessed, and the gates of hell will not hold against it.",
    '16:19': "The keys open and shut by the preaching of that confession. What the church binds, heaven honours.",
    '16:20': "He forbids them to publicise it. The title would be misunderstood until the cross explained it.",
    '16:21': "\"From that time forth.\" The confession is immediately followed by the first passion prediction.",
    '16:22': "Peter, moments after his great confession, rebukes Christ. Insight is not the same as maturity.",
    '16:23': "\"Get thee behind me, Satan.\" A well-meant attempt to spare Jesus the cross is the enemy's voice.",
    '16:24': "Deny himself, take up his cross, follow. The order is fixed and the first step is not enthusiasm.",
    '16:25': "Saving your life loses it. The instinct for self-preservation is the thing most needing to die.",
    '16:26': "The whole world against one soul — and the trade is still a loss.",
    '16:27': "He will come in glory and reward every man. The cross is not the end of the sentence.",

    # ---- Chapter 17 ----
    '17:1': "Three witnesses, up a mountain, six days after the cross was first mentioned.",
    '17:2': "His face shone as the sun. For a moment the veil is lifted on what was always there.",
    '17:3': "Moses and Elijah — the law and the prophets — in conversation with him, not instructing him.",
    '17:4': "Peter offers to build three shelters, putting Christ on a level with Moses and Elijah.",
    '17:5': "The cloud interrupts Peter mid-sentence. \"Hear ye him\" — not the three of them, him.",
    '17:6': "The glory terrifies them. Seeing God is never described in Scripture as comfortable.",
    '17:7': "The touch comes before the words. He reaches the terrified men first and tells them not to fear second.",
    '17:8': "\"They saw no man, save Jesus only.\" That is the point the mountain was making.",
    '17:9': "Silence until the resurrection. The glory cannot be told rightly before the cross.",
    '17:12': "Elijah has come and they did not know him. Expected figures arrive unrecognised.",
    '17:15': "A father describes his son's suffering in detail — fire and water, over and over.",
    '17:16': "\"They could not cure him.\" The disciples' failure is stated plainly and not excused.",
    '17:17': "The exasperation is real. Jesus is not endlessly patient in the way sentiment imagines.",
    '17:18': "One rebuke and the child was cured from that very hour.",
    '17:19': "\"Why could not we?\" They ask privately, which is the right place for that question.",
    '17:20': "Faith like a mustard seed moves mountains. The issue is not the quantity but whether it is real.",
    '17:21': "Some things yield only to prayer and fasting. Not every failure is a lack of technique.",
    '17:22': "The second passion prediction. He keeps telling them, and they keep not hearing it.",
    '17:23': "\"They were exceeding sorry\" — they caught the killing and missed the rising.",
    '17:25': "Kings do not tax their own children. Jesus draws out Peter's answer rather than stating his own.",
    '17:26': "\"Then are the children free.\" A claim about his sonship hidden inside a question about tax.",
    '17:27': "He pays anyway, to avoid needless offence. Freedom is exercised by surrendering it.",

    # ---- Chapter 18 ----
    '18:1': "\"Who is the greatest?\" The question is asked out loud, by grown men, to Jesus.",
    '18:2': "He answers by putting a child in the middle of them.",
    '18:3': "Conversion is required, not improvement — and the model is a child's smallness, not innocence.",
    '18:4': "Humbling yourself is the path to greatness, which means greatness is not what they were competing for.",
    '18:5': "Receiving one such child is receiving Christ. The lowest-status person carries his presence.",
    '18:6': "A millstone is preferable to causing a little one to stumble. Jesus' severity here is about protecting the weak.",
    '18:7': "Offences will come, and that does not excuse the one through whom they come.",
    '18:8': "Better maimed and alive. The amputation language returns, now about what damages others too.",
    '18:10': "Do not despise one of these little ones — their angels behold the Father's face.",
    '18:11': "\"The Son of man is come to save that which was lost.\" The whole chapter sits under this sentence.",
    '18:12': "Ninety-nine are left to go after one. The arithmetic is wrong by every measure but love's.",
    '18:13': "He rejoices more over the one found. Recovery brings a joy that steadiness does not.",
    '18:14': "It is not the Father's will that one should perish. The shepherd's search reflects the Father's heart.",
    '18:15': "Go to him alone first. The smallest audience that can fix it is the right one.",
    '18:16': "Only then one or two more. Each step widens reluctantly, not eagerly.",
    '18:17': "The church is the last resort, not the first. And even exclusion aims at recovery.",
    '18:18': "Binding and loosing is given to the church, not just to Peter. Discipline is Christ's authority, exercised carefully.",
    '18:19': "Agreement in prayer is set in the context of restoring a brother, not of getting what we want.",
    '18:20': "\"There am I in the midst of them.\" Two or three are enough for Christ to be present.",
    '18:21': "Peter offers seven times, and thinks he is being generous.",
    '18:22': "Seventy times seven means stop counting. A tally is already a failure to forgive.",
    '18:24': "Ten thousand talents — an unpayable, almost comic sum. That is the debt being illustrated.",
    '18:26': "\"Have patience with me, and I will pay thee all.\" He asks for time, not mercy, and still has no idea.",
    '18:27': "The lord forgave the debt. He asked for patience and was given release.",
    '18:28': "A hundred pence, and he takes him by the throat. The contrast is the whole parable.",
    '18:29': "The fellowservant uses the very words that had just worked for him.",
    '18:30': "\"He would not.\" Two words carry the entire weight of the story.",
    '18:32': "\"I forgave thee all that debt.\" The wickedness named is not the original debt but the unforgiveness after it.",
    '18:33': "\"Even as I had pity on thee\" — the measure of forgiveness owed is the forgiveness received.",
    '18:35': "\"From your hearts.\" Forgiveness that stops at the mouth is not what is meant.",

    # ---- Chapter 19 ----
    '19:3': "The question is a trap, and it is about grounds for divorce rather than the nature of marriage.",
    '19:4': "He goes back past Moses to the creation. The argument starts at the beginning, not the concession.",
    '19:5': "Leaving, cleaving, one flesh — the three words that define what marriage is.",
    '19:6': "\"What therefore God hath joined together\" — the joining is God's act, not merely the couple's.",
    '19:7': "They cite Moses as a command. Jesus will call it a permission.",
    '19:8': "\"Because of the hardness of your hearts.\" Some laws regulate sin rather than approving it.",
    '19:9': "Jesus narrows what they wanted broadened. He treats marriage more seriously than his questioners did.",
    '19:10': "The disciples conclude it would be better not to marry. They have understood the weight of it.",
    '19:11': "\"Save they to whom it is given.\" Singleness is spoken of as a gift, not a deficiency.",
    '19:12': "Some remain unmarried for the kingdom's sake. A life without marriage can be a whole life.",
    '19:13': "The disciples rebuke those bringing children, having just been taught with a child in their midst.",
    '19:14': "\"Suffer little children, and forbid them not.\" Access to Christ is not for the qualified.",
    '19:16': "\"What good thing shall I do?\" The question assumes eternal life is an achievement.",
    '19:17': "\"There is none good but one.\" Jesus starts by dismantling the word the man used casually.",
    '19:18': "He lists commandments about neighbours, and leaves out the ones about God.",
    '19:20': "\"All these things have I kept.\" He believes it, and still knows something is missing.",
    '19:21': "\"Go and sell... and come and follow me.\" The command exposes the god he actually had.",
    '19:22': "He went away sorrowful. The one person in the gospels who refuses a direct call from Christ.",
    '19:23': "Wealth is named as a hindrance, not a blessing to be envied.",
    '19:24': "A camel through a needle's eye. Jesus chooses an image of plain impossibility.",
    '19:25': "\"Who then can be saved?\" The disciples take the point further than we usually let it go.",
    '19:26': "\"With men this is impossible; but with God all things are possible.\" Salvation is God's work or it does not happen.",
    '19:27': "\"What shall we have therefore?\" Peter has left everything and is still calculating.",
    '19:28': "The answer is generous rather than rebuking. Jesus does not shame the question.",
    '19:29': "A hundredfold and eternal life. Nothing surrendered for his name is lost.",
    '19:30': "\"Many that are first shall be last.\" The reversal is stated flatly, straight after a promise of reward.",
})

TAKEAWAYS.update({
    # ---- Chapter 20 ----
    '20:2': "A penny a day, agreed in advance. The first workers got exactly the contract they wanted.",
    '20:6': "\"Why stand ye here all the day idle?\" — \"Because no man hath hired us.\" They were available all along.",
    '20:8': "Paid beginning from the last. The order of payment is designed so the first will see.",
    '20:9': "A full day's wage for one hour's work. Grace is indefensible by any accounting.",
    '20:12': "\"Thou hast made them equal unto us.\" The grievance is not injustice but equality.",
    '20:13': "\"Friend, I do thee no wrong.\" Nobody received less than justice; some received more.",
    '20:15': "\"Is thine eye evil, because I am good?\" Generosity to another is resented as though it were theft.",
    '20:16': "The last first and the first last. In the kingdom, seniority earns nothing.",
    '20:18': "The third passion prediction, now with the details filled in.",
    '20:19': "Mocked, scourged, crucified — and the third day raised. He knows the whole sequence in advance.",
    '20:20': "A mother asks for thrones, immediately after he has described his own execution.",
    '20:21': "Right hand and left — the places that will be occupied by two thieves.",
    '20:22': "\"Ye know not what ye ask.\" The cup they volunteer for is Gethsemane's.",
    '20:23': "They will drink the cup. The suffering is granted; the status is not his to hand out.",
    '20:24': "The ten are indignant — not because the request was wrong, but because they did not make it first.",
    '20:25': "Gentile rulers exercise dominion. Jesus names the ordinary shape of power in order to forbid it.",
    '20:26': "\"It shall not be so among you.\" Greatness is redefined rather than discouraged.",
    '20:28': "He came to serve and to give his life a ransom. The pattern for leadership is his death.",
    '20:30': "Blind men call him son of David. They see the title the crowd cannot.",
    '20:31': "The crowd tries to silence them and they cry louder. Persistence in prayer looks like this.",
    '20:32': "\"What will ye that I shall do unto you?\" He asks them to name it, though he knows.",
    '20:34': "He touched their eyes, and they followed him. Sight given is spent on discipleship.",

    # ---- Chapter 21 ----
    '21:2': "He arranges his own entry in detail. Nothing about this week happens to him accidentally.",
    '21:3': "\"The Lord hath need of them.\" The one who owns everything asks to borrow a donkey.",
    '21:5': "\"Meek, and sitting upon an ass.\" The king arrives in the manner the prophets described, not as expected.",
    '21:8': "Garments and branches on the road — a royal welcome offered by people about to change their minds.",
    '21:9': "\"Hosanna\" means save now. The crowd is right about the words and wrong about the timing.",
    '21:10': "\"Who is this?\" The city asks the question the whole gospel answers.",
    '21:11': "\"The prophet of Nazareth\" — true, and far less than the crowd had just been shouting.",
    '21:12': "He clears the temple. The first act of the King in his city is against its religion.",
    '21:13': "A house of prayer made a den of thieves. Commerce had displaced the one thing the court was for.",
    '21:14': "The blind and lame come to him in the cleared temple. Removing the tables made room for them.",
    '21:15': "Children shouting hosanna displeases the chief priests. Praise from the wrong mouths is offensive.",
    '21:16': "\"Out of the mouth of babes.\" He answers the objection with Scripture and keeps the children.",
    '21:19': "A tree in full leaf with no fruit. The sign is aimed at a religion advertising what it does not have.",
    '21:21': "Faith without doubt moves mountains. Said in Jerusalem, in the shadow of the temple mount.",
    '21:22': "\"All things, whatsoever ye shall ask in prayer, believing.\" The promise is left deliberately wide.",
    '21:23': "\"By what authority?\" They cannot deny what he did, so they question his right to do it.",
    '21:25': "He asks about John's baptism, and their reasoning is entirely about consequences.",
    '21:26': "\"We fear the people.\" Their theology is decided by the crowd.",
    '21:27': "\"We cannot tell\" is a lie, and Jesus declines to answer men who will not say what they think.",
    '21:29': "The son who refused, then went. What was finally done outweighs what was first said.",
    '21:30': "\"I go, sir: and went not.\" Agreement costs nothing and proves nothing.",
    '21:31': "Publicans and harlots enter first — said to the religious leadership, to their faces.",
    '21:32': "They saw others repent and were not moved. Evidence changed nothing because the will was set.",
    '21:33': "The vineyard is fully equipped. The tenants were given everything and owed only fruit.",
    '21:35': "The servants are beaten, killed, stoned. The parable is Israel's history of prophets.",
    '21:37': "\"They will reverence my son.\" The owner's last move is to send the one he loves.",
    '21:38': "\"This is the heir; come, let us kill him.\" They recognise him exactly, and that is why they kill him.",
    '21:41': "They pronounce their own sentence without realising it.",
    '21:42': "The rejected stone becomes the head of the corner. The builders' judgement is overturned by God's.",
    '21:43': "The kingdom is given to a nation bringing forth fruit. Stewardship can be transferred.",
    '21:45': "\"They perceived that he spake of them.\" They understood perfectly and repented of nothing.",
    '21:46': "They feared the multitude — again. Fear of people is the only restraint operating on them.",

    # ---- Chapter 22 ----
    '22:2': "A wedding for the king's son. The kingdom is pictured as a celebration, and refusing it is the offence.",
    '22:3': "\"They would not come.\" The invitation is free and it is declined.",
    '22:5': "A farm and a business. What keeps people from the feast is not wickedness but ordinary preoccupation.",
    '22:6': "The remnant killed the servants. Indifference and violence sit side by side in the same refusal.",
    '22:9': "\"Go ye therefore into the highways.\" The refusal of the invited opens the door to everyone else.",
    '22:10': "\"Both bad and good\" are gathered in. Nobody at that table was there on merit.",
    '22:11': "One man without a wedding garment. Coming in on grace does not mean coming in on your own terms.",
    '22:12': "\"He was speechless.\" There was no defence, because the garment had been provided.",
    '22:14': "Many called, few chosen. Matthew ends the parable without softening it.",
    '22:15': "They take counsel to entangle him in his talk. The questions that follow are traps, not enquiries.",
    '22:16': "The flattery is accurate. Everything they say about him is true, and they do not believe a word of it.",
    '22:17': "The tribute question is designed so either answer destroys him.",
    '22:18': "\"Why tempt ye me, ye hypocrites?\" He names the motive before he answers the question.",
    '22:20': "\"Whose is this image?\" He makes them produce the coin and answer their own question.",
    '22:21': "Render to Caesar and to God. The coin bears Caesar's image; you bear God's.",
    '22:22': "They marvelled and left. The trap closes on nothing.",
    '22:23': "The Sadducees, who deny the resurrection, ask a question about the resurrection.",
    '22:28': "The riddle is designed to make resurrection look absurd.",
    '22:29': "\"Ye do err, not knowing the scriptures, nor the power of God.\" Both halves of the ignorance are named.",
    '22:30': "Resurrection life is not a continuation of this one. They assumed it would be, and built the trap on that.",
    '22:32': "\"God is not the God of the dead, but of the living.\" The argument rests on a present-tense verb.",
    '22:36': "\"Which is the great commandment?\" Asked as a test, and answered as though it were sincere.",
    '22:37': "Heart, soul and mind. The first commandment claims the whole person, not a portion.",
    '22:39': "The second is like it. Love of God that leaves the neighbour untouched has misunderstood the first.",
    '22:40': "On these two hang all the law and the prophets. Everything else is commentary on love.",
    '22:42': "\"What think ye of Christ?\" Now he asks the questions.",
    '22:44': "David calls his own descendant Lord. The Messiah is more than a son of David.",
    '22:46': "Nobody dared ask him anything more. The questioning ends because the questioners have run out.",

    # ---- Chapter 23 ----
    '23:2': "They sit in Moses' seat — a real authority, which is why what follows is so serious.",
    '23:3': "Do what they say, not what they do. Jesus separates the office from the man holding it.",
    '23:4': "Heavy burdens laid on others and not lifted with a finger. Religion as weight rather than rest.",
    '23:5': "Everything done to be seen. The phylacteries and borders are enlarged for an audience.",
    '23:6': "Best seats and public greetings. The appetite is not for God but for position.",
    '23:8': "\"All ye are brethren.\" Titles that put distance between Christians are forbidden.",
    '23:9': "One Father, in heaven. No human authority may occupy the place that belongs to God.",
    '23:11': "\"He that is greatest among you shall be your servant.\" The same reversal, stated again.",
    '23:12': "Self-exaltation ends in abasement. The way up and the way down are not where we assume.",
    '23:13': "They shut the kingdom and do not enter it themselves. The worst charge is obstruction.",
    '23:14': "Devouring widows' houses under cover of long prayers. Piety used as a cover for predation.",
    '23:15': "Enormous effort spent making converts worse. Zeal without truth is not neutral.",
    '23:16': "\"Blind guides\" — a system of oaths built to let people say things they do not mean.",
    '23:17': "The temple sanctifies the gold, not the reverse. They had inverted what mattered.",
    '23:23': "Tithing herbs while omitting judgement, mercy and faith. Precision in the small can hide neglect of the large.",
    '23:24': "Straining at a gnat and swallowing a camel. The image is meant to be ridiculous.",
    '23:25': "The outside of the cup clean, the inside full of extortion. Appearance managed, substance untouched.",
    '23:26': "\"Cleanse first that which is within.\" The order is not optional.",
    '23:27': "Whited sepulchres, beautiful outside and full of bones. The harshest image in the gospels.",
    '23:28': "Outwardly righteous, inwardly full of hypocrisy. The gap between the two is the definition of it.",
    '23:29': "They build the tombs of the prophets their fathers killed. Honouring dead prophets is safe.",
    '23:30': "\"We would not have been partakers.\" They are saying this in the week they kill the Son.",
    '23:31': "Their own words witness against them.",
    '23:33': "\"How can ye escape the damnation of hell?\" Jesus asks it as a real question.",
    '23:34': "He will keep sending prophets, knowing what will be done to them.",
    '23:37': "\"How often would I have gathered thy children.\" The woes end in grief, not satisfaction.",
    '23:38': "\"Your house is left unto you desolate.\" Judgement is described as God's departure.",
    '23:39': "Even here the last word is a \"till.\" The door is closed and not nailed shut.",
})

TAKEAWAYS.update({
    # ---- Chapter 24 ----
    '24:1': "The disciples point out the buildings. They are admiring what is about to be levelled.",
    '24:2': "Not one stone left on another. Said of the most impressive religious structure they knew.",
    '24:3': "They ask three questions at once, and the answer that follows is not a timetable.",
    '24:4': "The first word about the future is a warning against deception, not a date.",
    '24:5': "Many will come in his name. The danger named first is counterfeits, not catastrophes.",
    '24:6': "Wars and rumours of wars — \"see that ye be not troubled.\" Headlines are not the signal.",
    '24:8': "\"The beginning of sorrows.\" Birth pangs, not the end: the worst is not the last word.",
    '24:9': "Persecution is predicted plainly, so that when it comes it will not look like abandonment.",
    '24:10': "Betrayal will come from inside. Many shall be offended and betray one another.",
    '24:12': "Love waxing cold is listed among the signs. Coldness is as serious as catastrophe.",
    '24:13': "\"He that shall endure unto the end, the same shall be saved.\" Endurance, not intensity.",
    '24:14': "The gospel preached in all the world, and then the end. Mission is what the interval is for.",
    '24:20': "\"Pray ye that your flight be not in the winter.\" Even in apocalypse, he thinks about their comfort.",
    '24:22': "The days are shortened for the elect's sake. God limits the suffering of his own.",
    '24:23': "\"Believe it not.\" Claims about a hidden Christ are to be refused on principle.",
    '24:24': "False signs and wonders. Miracles by themselves authenticate nothing.",
    '24:25': "\"I have told you before.\" Forewarning is itself a mercy.",
    '24:27': "Like lightning east to west. His coming will need no announcement and no insider information.",
    '24:30': "All the tribes of the earth shall mourn. The return is public, visible and unmistakable.",
    '24:31': "The angels gather his elect from the four winds. Nobody is overlooked in the gathering.",
    '24:32': "The fig tree tells you the season, not the date. Signs indicate nearness, never the hour.",
    '24:35': "Heaven and earth pass away; his words do not. The most durable thing in the universe is what he said.",
    '24:36': "Not the angels, not the Son — only the Father. Every date-setter is contradicted in one verse.",
    '24:37': "As in the days of Noah: eating, drinking, marrying. The problem was not wickedness but obliviousness.",
    '24:39': "\"And knew not until the flood came.\" They were not warned insufficiently; they were not listening.",
    '24:40': "Two in a field, one taken. The division runs between people who looked identical.",
    '24:42': "\"Watch therefore.\" Not knowing the hour is the reason for readiness, not an excuse for delay.",
    '24:44': "\"In such an hour as ye think not.\" Readiness cannot be scheduled for the last minute.",
    '24:45': "The faithful servant is defined by feeding the household in due season. Faithfulness is ordinary work.",
    '24:46': "The blessing falls on being found working, not on having guessed the hour correctly.",
    '24:48': "\"My lord delayeth his coming.\" The wicked servant's theology is what licenses his behaviour.",
    '24:49': "Delay is used as permission to abuse fellow servants. How we treat others reveals what we expect.",
    '24:51': "\"His portion with the hypocrites.\" The servant who assumed a long delay is judged with the pretenders.",

    # ---- Chapter 25 ----
    '25:2': "Five wise and five foolish, and nothing outwardly distinguished them until the delay.",
    '25:3': "The foolish took lamps but no oil. They were equipped for the appearance of readiness only.",
    '25:5': "All ten slumbered. Sleeping is not the failure; the parable does not blame it.",
    '25:6': "The cry comes at midnight, at the least convenient hour.",
    '25:8': "\"Give us of your oil.\" Some things cannot be borrowed at the last moment.",
    '25:9': "The wise are not being unkind. There are preparations nobody can make on your behalf.",
    '25:10': "\"And the door was shut.\" The parable's most frightening sentence is its quietest.",
    '25:12': "\"I know you not.\" As in chapter 7, the issue is acquaintance rather than performance.",
    '25:13': "\"Watch therefore\" — the point is not oil, lamps or timing, but being ready for a person.",
    '25:15': "Talents given according to ability. Nobody is handed more than they can handle.",
    '25:18': "The one-talent servant hid it. Doing nothing is presented as a decision, not a neutral state.",
    '25:21': "\"Well done, good and faithful servant\" — said identically to the five and the two. The return differed; the verdict did not.",
    '25:23': "The same commendation, word for word. God does not grade on the size of the gift.",
    '25:24': "\"I knew thee that thou art an hard man.\" His view of the master is what shaped his inaction.",
    '25:25': "\"I was afraid.\" Fear of the master produced a life with nothing to show.",
    '25:27': "Even the bank would have done. The failure was not poor returns but no attempt.",
    '25:29': "To him that hath shall be given. What is used grows; what is buried is lost.",
    '25:30': "\"The unprofitable servant\" is judged for what he did not do. Omission is enough.",
    '25:31': "The Son of man on the throne of his glory, with all the angels. The parables end in a courtroom.",
    '25:32': "All nations gathered, and a shepherd separating. The division is as simple as sorting a flock.",
    '25:34': "\"Inherit the kingdom prepared for you from the foundation of the world.\" An inheritance, prepared long before.",
    '25:35': "Food, drink, welcome. The evidence cited at the judgement is entirely ordinary and physical.",
    '25:36': "Clothing, sickness, prison. None of it is religious activity, and all of it costs something.",
    '25:37': "\"Lord, when saw we thee?\" The righteous do not recognise their own good works.",
    '25:40': "\"Unto one of the least of these my brethren, ye have done it unto me.\" Christ identifies himself with the overlooked.",
    '25:41': "The fire was prepared for the devil and his angels, not for people. Nobody was made for it.",
    '25:44': "The condemned also ask when they saw him. Both groups missed him; only one group served him anyway.",
    '25:45': "\"Ye did it not to me.\" The charge is entirely about what was left undone.",
    '25:46': "Everlasting punishment and life eternal are set in the same sentence, with the same word.",
})

TAKEAWAYS.update({
    # ---- Chapter 26 ----
    '26:2': "He names the day and the method. Nothing that follows catches him off guard.",
    '26:4': "They consult how to take him by subtilty. The plot needs darkness because the case is empty.",
    '26:5': "\"Not on the feast day\" — their timetable, which God overrules. He dies at Passover.",
    '26:6': "In the house of Simon the leper. Even in the last week, the company he keeps is the same.",
    '26:7': "She breaks something costly over his head, and Matthew does not tell us her name.",
    '26:8': "\"To what purpose is this waste?\" Extravagance toward Christ always looks like waste to somebody.",
    '26:10': "\"She hath wrought a good work upon me.\" He defends her against his own disciples.",
    '26:11': "\"Me ye have not always.\" Not a dismissal of the poor but a statement about this particular week.",
    '26:12': "She anointed him for his burial. She understood what was coming better than the twelve did.",
    '26:13': "Wherever the gospel is preached, her act is told. He gives her a memorial in the story itself.",
    '26:14': "\"Then one of the twelve.\" Matthew places the betrayal immediately after the extravagance.",
    '26:15': "Thirty pieces of silver — the price of a slave. He sold him cheap.",
    '26:16': "\"He sought opportunity.\" Betrayal was not a moment of madness but a plan he worked at.",
    '26:18': "\"My time is at hand.\" Even the room is arranged in advance.",
    '26:21': "\"One of you shall betray me.\" He says it at the table, while eating with him.",
    '26:22': "\"Lord, is it I?\" Every one of them asks. None is confident of himself.",
    '26:24': "Predestined and culpable at once. Matthew holds both without resolving the tension.",
    '26:25': "Judas asks the same question as the rest, and gets a different answer.",
    '26:26': "\"Take, eat; this is my body.\" On the night he is betrayed, he gives himself to them.",
    '26:27': "\"Drink ye all of it.\" Judas is at the table; the invitation is not narrowed.",
    '26:28': "Blood of the new testament, shed for many for the remission of sins. The supper interprets the cross before it happens.",
    '26:29': "He looks past the cross to a table in his Father's kingdom. The supper points forward, not only back.",
    '26:30': "They sang a hymn on the way to Gethsemane.",
    '26:31': "He predicts their failure and quotes Scripture for it. Their desertion does not surprise him either.",
    '26:32': "\"But after I am risen again, I will go before you.\" The restoration is promised before the denial happens.",
    '26:33': "\"Though all men shall be offended... yet will I never.\" Peter's confidence is in himself.",
    '26:34': "Before the cock crows, three times. The prediction is specific enough to be unmistakable.",
    '26:35': "\"Likewise also said all the disciples.\" Peter is not uniquely overconfident; he is only the loudest.",
    '26:37': "He began to be sorrowful and very heavy. Matthew does not hide what this cost him.",
    '26:38': "\"My soul is exceeding sorrowful, even unto death.\" He asks his friends to stay near.",
    '26:39': "\"Nevertheless not as I will, but as thou wilt.\" The prayer asks honestly and submits completely.",
    '26:40': "\"Could ye not watch with me one hour?\" The disappointment is personal.",
    '26:41': "\"The spirit indeed is willing, but the flesh is weak.\" A diagnosis offered with sympathy, not contempt.",
    '26:42': "The second prayer drops the \"if it be possible.\" He has his answer and accepts it.",
    '26:44': "He prayed the third time, saying the same words. Repeating a prayer is not unbelief.",
    '26:45': "\"Sleep on now.\" The time for their help has passed, and he faces it alone.",
    '26:46': "\"Rise, let us be going.\" He walks toward the betrayer rather than away.",
    '26:48': "The agreed sign is a kiss. Betrayal borrows the language of affection.",
    '26:49': "\"Hail, master; and kissed him.\" The betrayal is delivered in the form of affection, using its warmest sign.",
    '26:50': "\"Friend, wherefore art thou come?\" He calls Judas friend at the moment of the arrest.",
    '26:52': "\"Put up again thy sword.\" The kingdom will not be defended by the world's instruments.",
    '26:53': "Twelve legions of angels were available. He is not overpowered; he declines rescue.",
    '26:54': "\"How then shall the scriptures be fulfilled?\" The restraint is obedience, not weakness.",
    '26:55': "\"I sat daily with you teaching in the temple.\" The swords are an admission that they had no case.",
    '26:56': "\"Then all the disciples forsook him, and fled.\" Exactly as he had said an hour before.",
    '26:58': "Peter followed afar off — close enough to be recognised, far enough to be safe.",
    '26:59': "The council sought false witness. The verdict was fixed before the evidence was gathered.",
    '26:60': "Even the false witnesses could not agree. The trial fails by its own standards.",
    '26:63': "\"But Jesus held his peace.\" The silence before his accusers is its own answer.",
    '26:64': "Put under oath, he answers — and claims the throne. The one sentence he offers is the one they kill him for.",
    '26:65': "The high priest tears his robes and declares no more witnesses are needed. The confession was the evidence they wanted.",
    '26:67': "They spat in his face. Matthew records it in four words and moves on.",
    '26:68': "\"Prophesy unto us\" — they mock him as a prophet while his prophecy about Peter is coming true outside.",
    '26:69': "A servant girl is enough to start it. The denial does not require a threat.",
    '26:70': "\"I know not what thou sayest.\" The first denial is evasion rather than outright lie.",
    '26:72': "\"He denied with an oath.\" The second is worse, and swearing has entered it.",
    '26:74': "Cursing and swearing, and then the cock crew. The third denial is the furthest from the man who drew a sword.",
    '26:75': "\"He went out, and wept bitterly.\" The tears are why this story ends differently from Judas'.",
})

TAKEAWAYS.update({
    # ---- Chapter 27 ----
    '27:2': "They deliver him to Pilate. The religious court needed the state to do what it wanted done.",
    '27:3': "Judas repented — the wrong kind. Remorse without faith runs to despair rather than to Christ.",
    '27:4': "\"I have betrayed the innocent blood.\" The betrayer testifies to Jesus' innocence, and nobody cares.",
    '27:5': "He cast down the silver and hanged himself. Peter wept; Judas went out alone.",
    '27:6': "They will not put blood money in the treasury, having just paid it to kill a man. Scruple without conscience.",
    '27:11': "\"Art thou the King of the Jews?\" Pilate asks the true question without believing it.",
    '27:12': "He answered nothing. Silence before false accusation is its own kind of strength.",
    '27:14': "\"The governor marvelled greatly.\" Pilate has never seen a prisoner behave like this.",
    '27:17': "Barabbas or Jesus. A guilty man goes free and an innocent man takes his place, in literal fact.",
    '27:18': "\"He knew that for envy they had delivered him.\" Pilate understood the case perfectly.",
    '27:19': "Even Pilate's wife warns him. He is given every opportunity to do right.",
    '27:20': "The crowd is persuaded. The same voices that sang hosanna are now managed by the priests.",
    '27:22': "\"What shall I do then with Jesus?\" Pilate's question is the one nobody escapes.",
    '27:23': "\"Why, what evil hath he done?\" The judge cannot name a crime, and sentences him anyway.",
    '27:24': "Washing his hands changes nothing. Pilate performs innocence while signing the order.",
    '27:25': "\"His blood be on us.\" They say it as a curse; it is the only thing that could save them.",
    '27:26': "Barabbas released, Jesus scourged. Matthew tells the substitution in half a sentence.",
    '27:28': "A scarlet robe, to dress him as the king they think he is pretending to be.",
    '27:29': "A crown of thorns and a reed for a sceptre. Every item of the mockery is accidentally true.",
    '27:30': "They spat on him and struck him with the reed they had given him as a sceptre.",
    '27:32': "Simon of Cyrene is compelled to carry the cross — a stranger, pressed into the story.",
    '27:34': "He refused the drugged wine. He would meet it with his mind clear.",
    '27:35': "\"And they crucified him\" — three words. Matthew does not describe what every reader had seen.",
    '27:37': "The charge nailed above his head is the truth: THIS IS JESUS THE KING OF THE JEWS.",
    '27:38': "Two thieves, one on either side. The places James and John had asked for.",
    '27:40': "\"If thou be the Son of God, come down.\" The wilderness temptation returns at the last hour.",
    '27:42': "\"He saved others; himself he cannot save.\" A taunt that states the gospel exactly.",
    '27:43': "They quote Psalm 22 at him without recognising which psalm they are in.",
    '27:44': "Even the thieves revile him. At this point nobody on earth is on his side.",
    '27:45': "Darkness from the sixth hour to the ninth. Creation itself registers what is happening.",
    '27:46': "\"My God, my God, why hast thou forsaken me?\" The one loss he had never known, suffered here in our place.",
    '27:47': "They misunderstand even his dying words.",
    '27:50': "He \"yielded up the ghost.\" The life is not taken from him; it is given.",
    '27:51': "The veil torn from the top down — torn by God, from his side, and the way in is open.",
    '27:52': "Graves opened. The death that looked like the end has already begun undoing death.",
    '27:54': "\"Truly this was the Son of God\" — the first full confession after the cross comes from a Roman soldier.",
    '27:55': "The women were there, watching. They had followed from Galilee and they did not leave.",
    '27:57': "A rich man from Arimathaea, a disciple, comes forward when the twelve have scattered.",
    '27:58': "He went to Pilate and begged the body. It cost him his safety and his standing to ask.",
    '27:60': "He laid him in his own new tomb — a grave bought for himself, given away.",
    '27:61': "Mary Magdalene and the other Mary sat over against the sepulchre. They stayed to the end.",
    '27:63': "His enemies remembered the resurrection promise when his friends had forgotten it.",
    '27:64': "They seal the tomb to prevent a fraud, and so provide the guard that makes fraud impossible.",
    '27:66': "\"Made the sepulchre sure, sealing the stone, and setting a watch.\" Every precaution, against God.",

    # ---- Chapter 28 ----
    '28:1': "The women come first, to a grave, expecting nothing but a body.",
    '28:2': "The stone is rolled away so they can see in, not so he can get out.",
    '28:4': "The guards became as dead men. The only people who fell down at the tomb were the ones sent to secure it.",
    '28:5': "\"Fear not ye: for I know that ye seek Jesus, which was crucified.\" The angel knows who they came for.",
    '28:6': "\"He is risen, as he said.\" The resurrection is presented as a promise kept, not a surprise.",
    '28:7': "\"Go quickly, and tell.\" The first commission of the risen Christ is given to women.",
    '28:8': "\"With fear and great joy.\" Both at once, which is what actually happens when God acts.",
    '28:9': "Jesus meets them on the road. They held him by the feet — it is a body, not a vision.",
    '28:10': "\"Go tell my brethren.\" After they abandoned him, he calls them brothers.",
    '28:11': "The guards report to the priests rather than to Pilate. Both sides know what happened.",
    '28:13': "The bribe buys a story that refutes itself: sleeping witnesses to a theft they slept through.",
    '28:15': "Money and a cover story, against the resurrection. It is the best the opposition could manage.",
    '28:16': "The eleven. Matthew counts them honestly; one is missing and everyone knows why.",
    '28:17': "\"They worshipped him: but some doubted.\" The commission is given to a mixed and wavering group.",
    '28:18': "\"All power is given unto me in heaven and in earth.\" The command rests on his authority, not ours.",
    '28:19': "Go, disciple, baptize, teach — one commission with the Triune name at its centre.",
    '28:20': "\"Lo, I am with you alway.\" The gospel that opened with Emmanuel closes with the same promise kept.",
})
