#!/usr/bin/env python3
"""Written one-line takeaways for Obadiah.

Generated by scripts/merge_takeaway_parts.py from
scripts/takeaways/parts/obadiah_*.py — edit those, not this file.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The shortest book in the Old Testament opens with a war rumour already moving among the nations.",
    '1:2': "Smallness is not Edom's misfortune but God's doing, announced before a single charge is laid.",
    '1:3': "A fortress in the rock breeds a question nobody outside was asking: who shall bring me down?",
    '1:4': "Height is the one defence this oracle treats as no defence whatever, nest among the stars included.",
    '1:5': "Thieves leave something and grapegatherers leave some grapes. This stripping is measured against robbers.",
    '1:6': "Esau's hidden things are searched out. A people who trusted a hiding place lose the hiding place first.",
    '1:7': "Confederates walk him to the border and bread-eaters lay a wound under him. Edom is paid in its own coin.",
    '1:8': "Edom was famous for its wise men, and the wisdom is the first thing taken out of it.",
    '1:10': "\"Thy brother Jacob.\" The word the whole oracle turns on is finally spoken, and it is a family word.",
    '1:11': "Standing on the other side counts as joining in. Neutrality toward a brother is not on offer here.",
    '1:12': "Looking, rejoicing, speaking proudly. The charges begin with the things that leave no marks.",
    '1:13': "\"In the day of their calamity,\" three times in one verse. The timing is what makes each act worse.",
    '1:14': "The last charge is the worst: standing at the crossway to catch his brother's people as they escape.",
    '1:15': "The sentence is the deed handed back. Edom is judged by exactly the measure it used on Jacob.",
    '1:16': "They drank on the holy mountain in celebration. The cup comes round again, and it is not wine.",
    '1:17': "The book turns here: deliverance on mount Zion, and the house of Jacob given back what was its own.",
    '1:18': "Jacob and Joseph are the fire and Esau the stubble. The brothers are still set against each other at the end.",
    '1:21': "The last word is not Edom's ruin but whose the kingdom is, and the book will not close on the brother.",
}
