#!/usr/bin/env python3
"""Written one-line takeaways for 1 Peter.

Each states what the verse turns on. Verses carrying no standalone point
are left out deliberately; the drawer hides the card rather than showing
filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"Strangers scattered\" — the readers' address is their displacement, and Peter writes to that.",
    '1:2': "Foreknowledge, sanctification, sprinkled blood: the whole Trinity is named before a single command.",
    '1:3': "The hope is called lively because a resurrection stands behind it, not because it feels strong.",
    '1:4': "An inheritance reserved in heaven is the one thing exiles cannot be dispossessed of.",
    '1:5': "Kept by the power of God through faith. The keeping is his; the faith is how it reaches us.",
    '1:6': "\"For a season, if need be\" — the heaviness is real, and it is also measured and temporary.",
    '1:7': "Gold perishes even when it survives the fire. Tried faith is being kept for a day still coming.",
    '1:8': "Whom having not seen, ye love. Peter had seen him, and does not treat that as the advantage.",
    '1:10': "The prophets searched their own words for what they meant. Grace was aimed past them.",
    '1:11': "The Spirit of Christ in the prophets testified sufferings first, and the glory that should follow.",
    '1:12': "They ministered to us, not to themselves, and angels lean in at what these exiles were told.",
    '1:13': "Gird up the loins of the mind: hope is given work to do, and the work is thinking clearly.",
    '1:14': "The former lusts belonged to ignorance. What is known now makes the old shape unwearable.",
    '1:15': "Holiness is measured by the One who called, not by comparison with the neighbours.",
    '1:16': "\"Be ye holy; for I am holy.\" The reason given is God's character, never the benefit to us.",
    '1:17': "A Father who judges without respect of persons is still a Father. Fear and sonship stand together.",
    '1:18': "Silver and gold are called corruptible in a letter written to people who had very little of either.",
    '1:19': "The price was the blood of a lamb without blemish. Redemption is priced, and the price is named.",
    '1:20': "Foreordained before the foundation of the world, manifest \"for you.\" Eternity aimed at these readers.",
    '1:21': "Faith and hope are placed in God, and it is the resurrection that put them there.",
    '1:22': "Souls purified in obeying the truth — and the purpose named is unfeigned love of the brethren.",
    '1:23': "Born again of incorruptible seed. The new life carries the durability of the word that made it.",
    '1:24': "All flesh is grass, and the glory of man is the flower on it. Both are given the same forecast.",
    '1:25': "The enduring word is not distant: \"this is the word which by the gospel is preached unto you.\"",

    # ---- Chapter 2 ----
    '2:1': "Malice, guile, hypocrisy, envy, evil speaking — the list is all of it damage done by speech.",
    '2:2': "Newborn babes desire milk without being persuaded to. The appetite is the evidence of life.",
    '2:3': "\"If so be ye have tasted.\" The argument rests on something already experienced, not argued.",
    '2:4': "A living stone, disallowed of men and chosen of God. Both verdicts are on record at once.",
    '2:5': "Lively stones built into a house: the material is people, and each one is also a priest.",
    '2:6': "The cornerstone was laid by God in Sion, so believing on him cannot end in confusion.",
    '2:7': "The same stone: precious to believers, and to the disobedient the head of the corner anyway.",
    '2:8': "A rock of offence to those who stumble at the word. Peter lets the hard clause stand unexplained.",
    '2:9': "Chosen, royal, holy, peculiar — four titles from Sinai handed to scattered nobodies in Asia Minor.",
    '2:10': "\"Not a people\" became the people of God. The identity was received, never assembled.",
    '2:11': "Strangers and pilgrims: fleshly lusts are resisted as a foreign claim, not as a native duty.",
    '2:12': "Good works seen by hostile neighbours may end in their glorifying God, not in your vindication.",
    '2:13': "Submission is \"for the Lord's sake\" — the reason is never that the ordinance deserves it.",
    '2:14': "Governors are described by their function, punishing evil and praising good, not by their virtue.",
    '2:15': "Well doing silences ignorance. Peter expects the answer to slander to be a life, not a reply.",
    '2:16': "Free, and servants of God. Liberty used as a cloak for malice is the one misuse named.",
    '2:17': "Four short commands, and honour is given to all men before the king gets any of it.",
    '2:18': "\"Not only to the good and gentle, but also to the froward.\" The hard case is stated, not avoided.",
    '2:19': "What makes suffering thankworthy is conscience toward God, and the grief is called wrongful.",
    '2:20': "Patience under deserved punishment earns nothing. The text distinguishes the two kinds of suffering.",
    '2:21': "\"Hereunto were ye called.\" Suffering is not the interruption of the calling but part of it.",
    '2:22': "Who did no sin. The one person with grounds to protest is the one who did not.",
    '2:23': "Reviled, he reviled not again — because he handed the case to him that judgeth righteously.",
    '2:24': "He bare our sins in his own body. The example of verse 21 turns out to be a substitution.",
    '2:25': "Sheep going astray, now returned. The straying was ours; the returning is credited to the Shepherd.",

    # ---- Chapter 3 ----
    '3:1': "A husband who will not hear the word may still be won \"without the word\" — by a life he watches.",
    '3:3': "Plaited hair and gold are not condemned so much as demoted. The adorning is placed elsewhere.",
    '3:4': "\"The hidden man of the heart\" is called incorruptible and of great price in God's sight, not in the room's.",
    '3:5': "The holy women of old are cited as trusting God. Their submission is traced back to that trust.",
    '3:6': "\"Not afraid with any amazement\" — daughters of Sara are marked by the absence of terror.",
    '3:7': "Husbands are told to dwell according to knowledge, and a failure here obstructs their prayers.",
    '3:8': "One mind, compassion, brotherly love, pity, courtesy — the list ends with plain good manners.",
    '3:9': "Blessing instead of railing, \"knowing that ye are thereunto called\" to inherit a blessing yourself.",
    '3:10': "Loving life begins with the tongue. The first move toward good days is what is not said.",
    '3:12': "The Lord's eyes on the righteous and his ears open — attention described as the actual protection.",
    '3:13': "A fair question in ordinary times, which verse 14 immediately allows may not be the times you are in.",
    '3:14': "\"Be not afraid of their terror.\" The command is not to share the fear their threats are made of.",
    '3:15': "Sanctify Christ in the heart first; the answer to the questioner comes second, with meekness and fear.",
    '3:16': "A good conscience is what makes slander fall apart. The defence is built long before the accusation.",
    '3:17': "Better to suffer for well doing — and \"if the will of God be so\" places even that inside his will.",
    '3:18': "\"The just for the unjust, that he might bring us to God.\" The whole exchange stated in one line.",
    '3:19': "Preached to the spirits in prison. Peter drops the claim in and does not explain it.",
    '3:20': "Eight souls saved, and the long waiting of God is what the years of ark-building actually were.",
    '3:21': "Baptism saves as \"the answer of a good conscience,\" not as a washing of the body.",
    '3:22': "Angels, authorities and powers made subject to him — written to people with no power at all.",

    # ---- Chapter 4 ----
    '4:1': "Arm yourselves with the same mind. The weapon issued is a settled intention about suffering.",
    '4:3': "\"The time past may suffice.\" Enough of that life has been lived; none of it needs repeating.",
    '4:4': "They think it strange and speak evil of you. Withdrawal from the party is read as an accusation.",
    '4:5': "The mockers will give account. The judgement is theirs to face, which is why it is not yours to deliver.",
    '4:6': "The gospel reached the dead so that the verdict of men in the flesh would not be the final one.",
    '4:7': "\"The end of all things is at hand\" produces sobriety and prayer, not excitement.",
    '4:8': "Charity covers a multitude of sins — it does not deny them, and it does not publish them.",
    '4:9': "Hospitality without grudging. The grudge is assumed, and the command reaches past it.",
    '4:10': "Every man has received a gift, and every gift is held in stewardship for someone else.",
    '4:11': "Speaking as the oracles of God and serving by the ability God gives both end in God glorified.",
    '4:12': "The fiery trial is not strange. Expecting exemption is what makes suffering feel like betrayal.",
    '4:13': "Partakers of Christ's sufferings now, glad at the revealing of his glory then. The order is fixed.",
    '4:14': "Reproached for the name, and the spirit of glory rests on you. The shame and the glory coincide.",
    '4:15': "Peter names the suffering that deserves no comfort, and a busybody is on the list with thieves.",
    '4:16': "Suffering \"as a Christian\" is met with glorifying God, and the name itself is not to be a shame.",
    '4:17': "Judgement begins at the house of God. The church is the first address, not the exempt one.",
    '4:18': "\"The righteous scarcely saved\" — salvation is narrow even for those inside it, and still salvation.",
    '4:19': "Souls committed to a faithful Creator, and the committing is done \"in well doing,\" not in waiting.",

    # ---- Chapter 5 ----
    '5:1': "Peter exhorts elders as a fellow elder and a witness — no appeal to rank among them.",
    '5:2': "Feed the flock \"of God,\" not by constraint and not for lucre. The flock belongs to someone else.",
    '5:3': "Not lords over God's heritage but ensamples. Oversight is exercised by being watched, not by ruling.",
    '5:4': "The chief Shepherd appears and hands out a crown that does not fade — unlike every other one.",
    '5:5': "Humility is clothing to put on, and the proud are told plainly whom they are being resisted by.",
    '5:6': "Under the mighty hand of God, and the lifting is left to his timing: \"in due time.\"",
    '5:7': "Care is cast on him for a reason stated as fact: he careth for you.",
    '5:8': "A roaring lion seeking whom he may devour. Sobriety and vigilance are the whole defence offered.",
    '5:9': "Resist stedfast in the faith, knowing others bear the same. Suffering is not evidence of singularity.",
    '5:10': "Perfect, stablish, strengthen, settle — four verbs, all of them God's, and all after the suffering.",
    '5:11': "Glory and dominion for ever, written by a man expecting to die under someone else's dominion.",
    '5:12': "Peter calls the whole letter \"the true grace of God wherein ye stand\" — grace, not advice.",
}
