#!/usr/bin/env python3
"""Written one-line takeaways for Philippians."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"Servants\" — Paul claims no apostolic rank here, and the bishops and deacons are greeted after the saints, not above them.",
    '1:2': "Grace first, then peace. The order never reverses, because the second is what the first produces.",
    '1:3': "Remembrance itself is the occasion for thanks. These people are a gift he keeps receiving.",
    '1:4': "Prayer here is not a duty discharged but a place where joy happens.",
    '1:5': "\"Fellowship in the gospel\" means partnership in the work, not warm feeling about it.",
    '1:6': "The good work is God's from the first day to the last. Their part was never the thing holding it together.",
    '1:7': "Prison has not put Paul on one side and them on the other: they are partakers of the same grace.",
    '1:8': "He calls God as witness to an affection he cannot prove — the longing is real enough to need a witness.",
    '1:9': "Love is asked to grow in knowledge and judgment. Sentiment left untrained is not what he is praying for.",
    '1:10': "Approving the excellent is a skill of discernment, not a burst of zeal; it takes the trained love of verse 9.",
    '1:11': "The fruits of righteousness are \"by Jesus Christ\" — even the harvest is not self-grown.",
    '1:12': "He reads his own imprisonment as gospel logistics. The thing that stopped him did not stop the word.",
    '1:13': "The palace guard learned the reason for his chains. A prison became a pulpit by the mere fact of the charge.",
    '1:14': "His bonds made others bolder, not quieter. Courage spread from the man who had lost the most.",
    '1:15': "Some preach Christ from envy. Paul names the motive without pretending it is anything better.",
    '1:16': "Rivals preached hoping to deepen his misery. The gospel can be used as a weapon against a fellow preacher.",
    '1:17': "The others preached from love, understanding what his imprisonment actually was — a defence, not a defeat.",
    '1:18': "\"Whether in pretence, or in truth, Christ is preached.\" His own vindication matters less to him than the message getting out.",
    '1:19': "Their prayer and the Spirit's supply are named in one breath, as though they were one provision.",
    '1:20': "The hope is not survival but that Christ be magnified either way. Life and death are both listed as acceptable outcomes.",
    '1:21': "\"To live is Christ, and to die is gain.\" Death is not the loss of the thing he lives for but arrival at it.",
    '1:22': "He cannot choose. A man with nothing to fear on either side has no obvious preference.",
    '1:23': "\"To depart, and to be with Christ; which is far better.\" He says plainly that death would be the better deal.",
    '1:24': "He stays because they need him. Usefulness to others outranks his own far better option.",
    '1:25': "The confidence is not about his trial's verdict but about what God still intends to do through him.",
    '1:26': "Their rejoicing, not his comfort, is the stated reason for his release.",
    '1:27': "\"Let your conversation be as it becometh the gospel\" — the word means the whole public life of a citizen, not talk.",
    '1:28': "Their composure under threat is itself a sign, legible to both sides but read in opposite directions.",
    '1:29': "Suffering is \"given\" alongside believing. Both are listed as grants, not as misfortunes.",
    '1:30': "They are not watching his conflict from safety; they are in the same one.",

    # ---- Chapter 2 ----
    '2:1': "Four conditions, all already true. The \"if\" is not doubt but the ground being laid before the request lands.",
    '2:2': "Paul's joy is not yet full, and what would fill it is their agreement with each other.",
    '2:3': "\"Lowliness of mind\" is not low self-estimate but a refusal to rank oneself first in the room.",
    '2:4': "Not that a man ignore his own things, but that he also look at another's. Attention is the asked-for currency.",
    '2:5': "The argument for humility is about to become a matter of who Christ is, not a technique for getting along.",
    '2:6': "Equality with God was not something he had to grasp at, because it was already his.",
    '2:7': "\"Made himself of no reputation.\" The emptying was his own act, not something done to him.",
    '2:8': "The descent has a floor: obedience to death, and then the particular death that carried a curse.",
    '2:9': "The exaltation is God's response to the obedience, not a reward negotiated in advance.",
    '2:10': "Every knee, including things under the earth. Nothing is left outside the range of that name.",
    '2:11': "The universal confession ends in the Father's glory, so the Son's honour takes nothing from him.",
    '2:12': "\"Work out your own salvation\" — work out, not work for. What is already given is what gets worked out.",
    '2:13': "God works the willing as well as the doing. Even the wanting to obey is traced back to him.",
    '2:14': "Murmuring is listed as a thing to stop, not a mood to excuse. Grumbling is treated as conduct.",
    '2:15': "The crooked nation is not the problem to be fled; it is the darkness that makes lights visible.",
    '2:16': "Paul's labour could in principle have been in vain, and he says so. He is not above the risk.",
    '2:17': "He casts his own death as the drink offering poured over their sacrifice — a minor part of their service.",
    '2:19': "Sending Timothy is for Paul's comfort as much as theirs. The prisoner admits he needs news.",
    '2:20': "\"No man likeminded\" — Paul, surrounded by helpers, still knows what it is to be short of one.",
    '2:21': "\"All seek their own.\" A flat verdict on his own circle, written without softening.",
    '2:22': "Timothy served \"as a son with the father,\" and the proof was known to them before Paul had to argue it.",
    '2:25': "Five titles for Epaphroditus, and the last two are what he was to the Philippians, not to Paul.",
    '2:26': "He was distressed not that he was ill but that they had heard he was ill.",
    '2:27': "\"Lest I should have sorrow upon sorrow.\" Paul names his own grief as part of why God spared the man.",
    '2:28': "He sends him back to end their anxiety, and says openly that it will lighten his own.",
    '2:29': "Receive him gladly — said because a man sent home early could easily be read as a man who failed.",
    '2:30': "He nearly died supplying what they could not deliver in person. Their gift is credited through his risk.",

    # ---- Chapter 3 ----
    '3:1': "Repetition is called safe. Paul does not assume that what has been said once has been learned.",
    '3:2': "\"Beware of dogs\" — the slur usually aimed at Gentiles is turned on those demanding Gentile circumcision.",
    '3:3': "The mark of the covenant people is worship in the Spirit and no confidence in the flesh at all.",
    '3:4': "Before dismissing the credentials, he establishes he could out-argue anyone who has them.",
    '3:5': "Birth, tribe, lineage, party — everything on the list was either inherited or earned, and all of it is about to be priced.",
    '3:6': "\"Touching the righteousness which is in the law, blameless.\" By that measure he passed, and the measure is what he abandons.",
    '3:7': "The ledger is rewritten, not adjusted: what stood in the gain column is moved to loss.",
    '3:8': "\"Dung.\" Not merely outweighed by Christ but actively disposed of, because keeping it would be a rival.",
    '3:9': "Two righteousnesses are set against each other: his own, and one received by faith from God.",
    '3:10': "Knowing the resurrection power and the fellowship of his sufferings are one petition, not two.",
    '3:11': "\"If by any means\" — the confidence of verse 9 does not produce swagger about what is still ahead.",
    '3:12': "He is apprehended before he apprehends. The pursuit is a response to having been caught.",
    '3:13': "\"This one thing I do.\" The forgetting is deliberate, and it includes the record he just listed.",
    '3:14': "The prize belongs to a calling from above, so the race is run toward a gift rather than for a wage.",
    '3:15': "Where they still disagree, Paul leaves the correcting to God rather than forcing the point.",
    '3:17': "He offers himself as a pattern, then immediately widens it to others who walk the same way.",
    '3:18': "He weeps while naming them enemies. The verdict is not delivered with satisfaction.",
    '3:19': "\"Whose God is their belly\" — the appetite in charge is the god, whatever the confession says.",
    '3:20': "Citizenship is elsewhere, which is why a Roman colony town needed telling where its real papers were filed.",
    '3:21': "The same power that subdues all things is what will be spent on changing a body. Nothing is held back for larger work.",

    # ---- Chapter 4 ----
    '4:1': "He calls them his joy and crown before asking anything, and the request is only that they stay where they are.",
    '4:2': "Two women are named in a letter meant to be read aloud. The quarrel was public enough to need a public word.",
    '4:3': "The remedy is not arbitration but help: someone is asked to come alongside them both.",
    '4:4': "\"Rejoice in the Lord alway\" — written in chains, which is the only reason the command can be taken seriously.",
    '4:5': "Moderation is grounded not in temperament but in a fact: \"The Lord is at hand.\"",
    '4:6': "Anxiety is not answered by resolve but by relocation — the thing worried over gets told to God instead.",
    '4:7': "The peace guards the heart; it does not explain itself to the mind. It passes understanding rather than satisfying it.",
    '4:8': "The list is not distinctively Christian vocabulary. Whatever is true and lovely is fair ground for attention.",
    '4:9': "What they learned, received, heard and saw in him is one thing, taught four ways. Doctrine came with a life attached.",
    '4:10': "He credits them with care they could not act on, and refuses to read the silence as neglect.",
    '4:11': "Contentment is \"learned,\" which means he had not always had it.",
    '4:12': "Abounding is listed as something needing instruction too. Plenty is as hard a school as hunger.",
    '4:13': "\"I can do all things\" is said about being full and being hungry, not about achievement.",
    '4:15': "They gave when no one else did. Paul remembers who was there at the beginning and says so by name.",
    '4:17': "He wants the gift for their sake, not his. The fruit is credited to their account, not to his relief.",
    '4:18': "Money sent to a prisoner is described as sacrifice and sweet smell. Ordinary support is named worship.",
    '4:19': "The promise follows a church that gave out of their own want. Supply is pledged to people already emptying their hands.",
    '4:20': "The doxology lands where the letter began: the glory is God's, not the givers'.",
    '4:22': "\"They that are of Caesar's household.\" The gospel reached inside the house of the man holding him.",
}
