#!/usr/bin/env python3
"""Written one-line takeaways for Revelation.

Each states what the verse turns on. Long stretches of vision description
-- trumpet and bowl mechanics, measurements, tribe and cargo lists -- are
left out where a single verse carries no standalone point.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The revelation is of Jesus Christ and was given to him. Even here he receives before he discloses.",
    '1:2': "John's part is to bear record of what he saw. He is a witness before he is anything else.",
    '1:3': "The blessing falls on the reader, the hearers, and those who keep it. Three parties, one book.",
    '1:4': "\"Him which is, and which was, and which is to come.\" The grammar is broken open to hold the name.",
    '1:5': "Faithful witness, firstborn of the dead, prince of the kings -- and then \"washed us in his own blood.\"",
    '1:6': "Made kings and priests. The titles are handed to people writing from underneath an empire.",
    '1:7': "\"They also which pierced him\" will see him. The ones who did it are counted among the seers.",
    '1:8': "Alpha and Omega. He claims the first letter and the last, and everything spelled out between.",
    '1:9': "Brother, companion in tribulation, and in the kingdom. The kingdom and the tribulation share an address.",
    '1:10': "The voice came from behind him. He had to turn round before he could see what was speaking.",
    '1:12': "He turned to see a voice and saw lampstands. The speaker was located among the churches.",
    '1:13': "\"In the midst of the seven candlesticks\" -- before a word of praise or rebuke, he is standing among them.",
    '1:14': "White hair and eyes of flame. Daniel's Ancient of Days is used to describe him without apology.",
    '1:15': "Feet of burning brass, a voice like many waters. Nothing in the description is meant to soothe.",
    '1:16': "The sword comes out of his mouth. The weapon in this book is always speech.",
    '1:17': "He fell as dead, and the hand that terrified him is laid on him with \"Fear not.\"",
    '1:18': "\"I am he that liveth, and was dead.\" The keys of death are held by someone who used that door.",
    '1:19': "Seen, are, and shall be hereafter. All three tenses are commissioned as one book.",
    '1:20': "The mystery is explained outright: stars are angels, candlesticks are churches. Not every symbol stays dark.",

    # ---- Chapter 2 ----
    '2:1': "He holds the stars and walks among the lampstands. Every letter opens with who is speaking.",
    '2:2': "\"I know thy works\" -- and the works are good: labour, patience, false apostles tried and refused.",
    '2:3': "They bore it and did not faint. The endurance is granted in full before the complaint arrives.",
    '2:4': "\"Thou hast left thy first love.\" Everything correct was in place, and the one missing thing undid it.",
    '2:5': "Remember, repent, do the first works. The way forward is described entirely as going back.",
    '2:6': "Even the sharpest letter finds something to commend, and it turns out to be a hatred they share.",
    '2:7': "The tree of life, guarded since Eden, is offered as food to the one who overcomes.",
    '2:8': "To the church facing death he introduces himself as the one who was dead and is alive.",
    '2:9': "\"But thou art rich.\" The parenthesis contradicts the poverty in the same breath.",
    '2:10': "Ten days of tribulation, and no offer of escape from it. Faithful unto death means through it.",
    '2:11': "The overcomer is not promised exemption from the first death, only from the second.",
    '2:12': "To the church living at Satan's seat he comes carrying a sword, and the sword is his word.",
    '2:13': "He knows the address, names the martyr, and does not move them out of the city.",
    '2:14': "Balaam could not curse Israel, so he taught them to compromise. The method still works from inside.",
    '2:16': "\"I will fight against them with the sword of my mouth.\" The threat falls on the teachers, not the church.",
    '2:17': "Hidden manna, a white stone, a name no one else knows. The reward is private and unshareable.",
    '2:18': "Eyes of flame and feet of brass are the self-description given to the church that tolerated a teacher.",
    '2:19': "Their last works exceed the first, which is the opposite of Ephesus -- and still not the end of the matter.",
    '2:20': "The charge is not holding Jezebel's doctrine but suffering it. Tolerance is counted here as a work.",
    '2:21': "\"I gave her space to repent.\" The judgment comes after a delay that was deliberate.",
    '2:22': "The bed she used for seduction becomes the bed of her affliction. The sentence keeps her own furniture.",
    '2:23': "\"I am he which searcheth the reins and hearts.\" The churches learn it by watching what happens to another.",
    '2:24': "\"I will put upon you none other burden.\" The faithful remnant is given no extra programme to carry.",
    '2:25': "Hold fast what you already have. Sometimes the entire command is not to let go.",
    '2:26': "Power over the nations is promised to people who have no power in their own town.",
    '2:27': "\"Even as I received of my Father.\" The rod of iron is delegated authority, not native right.",
    '2:28': "\"I will give him the morning star\" -- and the last chapter reveals the morning star to be himself.",

    # ---- Chapter 3 ----
    '3:1': "\"Thou hast a name that thou livest, and art dead.\" The reputation is the thing being contradicted.",
    '3:2': "Strengthen the things which remain. Even in a dead church something is still only ready to die.",
    '3:3': "\"Thou shalt not know what hour.\" The thief image is turned on the church, not on the world.",
    '3:4': "\"A few names even in Sardis.\" The number is small, and it is still counted out.",
    '3:5': "The promise is that he will not blot the name out. Assurance stated as something God refuses to do.",
    '3:7': "The key of David opens and shuts, and the shutting is claimed as his work as well.",
    '3:8': "\"Thou hast a little strength.\" The open door is set before weakness, not before achievement.",
    '3:9': "The opponents are brought to know \"that I have loved thee.\" The vindication is about love, not victory.",
    '3:10': "Kept the word of my patience, kept from the hour of temptation. The keeping runs in both directions.",
    '3:11': "\"That no man take thy crown.\" What is warned against is another's grasp, not one's own collapse.",
    '3:12': "A pillar that goes no more out, written on with three names. The unstable are promised permanence.",
    '3:14': "\"The Amen, the faithful and true witness\" -- he names himself as reliability to a church that has none.",
    '3:15': "\"I would thou wert cold or hot.\" Either extreme is preferred to the temperature they settled on.",
    '3:16': "Lukewarm water is spat out. What is described is physical disgust, not disappointment.",
    '3:17': "Rich by their own account and wretched by his. What is missing is not knowledge but self-knowledge.",
    '3:18': "Gold, raiment and eyesalve. He tells the self-sufficient to come and buy from him.",
    '3:19': "The rebuke is filed under love. The harshest letter claims affection for its target.",
    '3:20': "He stands outside his own church and knocks. The door in this picture opens from the inside.",
    '3:21': "To sit in his throne, \"even as I also overcame.\" The overcoming already happened, and it is the pattern.",

    # ---- Chapter 4 ----
    '4:1': "A door opened in heaven, and the word is \"Come up hither.\" The vantage point has to change first.",
    '4:2': "\"A throne was set in heaven, and one sat on the throne.\" The rest of the book is written from that fact.",
    '4:3': "He is described in stones and light and never by a face. The one on the throne is not pictured.",
    '4:4': "Twenty-four elders, seated and crowned. There are other thrones, and every one of them faces the same way.",
    '4:5': "Lightnings and thunderings proceed out of the throne. The centre of worship is not a calm place.",
    '4:6': "A sea of glass, still and passable. The water that drowns and divides in this book is frozen here.",
    '4:8': "\"Holy, holy, holy\" without rest, from creatures full of eyes. Seeing more produces more worship, not less.",
    '4:10': "The elders cast their crowns down. What was given to them as reward is handed back as tribute.",
    '4:11': "\"For thy pleasure they are and were created.\" Existence is traced to God's wanting it.",

    # ---- Chapter 5 ----
    '5:1': "A sealed book in the right hand of God. The future is written and closed, and nobody can read it.",
    '5:2': "The question is not who is able but who is worthy. Power is not the qualification being sought.",
    '5:3': "In heaven, on earth, under the earth. The search is exhaustive, and it comes back empty.",
    '5:4': "\"And I wept much.\" A sealed future with no one to open it is a thing worth crying over.",
    '5:5': "\"Weep not: behold, the Lion of the tribe of Juda hath prevailed.\" The announcement is of a conquest.",
    '5:6': "He was told of a Lion and saw a Lamb as it had been slain. The book's central substitution happens here.",
    '5:7': "He came and took the book. No struggle is described, because the worthiness was settled elsewhere.",
    '5:8': "The golden vials are the prayers of saints. What looked unanswered has been collected and kept.",
    '5:9': "\"Thou wast slain, and hast redeemed us.\" The worthiness is grounded in the dying, not in the strength.",
    '5:10': "Kings and priests, \"and we shall reign on the earth.\" The destination stays terrestrial.",
    '5:12': "\"Worthy is the Lamb that was slain.\" Seven things are given him, and the slaughter is the stated reason.",
    '5:13': "Every creature joins. The doxology widens until there is nothing left standing outside it.",
    '5:14': "The living creatures say Amen and the elders fall down. The answer to a hymn is posture.",

    # ---- Chapter 6 ----
    '6:1': "The Lamb opens the seals. Whatever is loosed in this chapter is loosed by the one who was slain.",
    '6:2': "A white horse, a bow, a crown, conquering. The rider is never identified, and the book leaves it so.",
    '6:4': "Peace is taken from the earth and men kill one another. The great sword is given, not seized.",
    '6:5': "A black horse with a pair of balances. Famine arrives as a set of scales weighing what is left.",
    '6:6': "A day's wage for a day's wheat, and \"hurt not the oil and the wine.\" The luxuries are spared; bread is not.",
    '6:8': "Death rides and Hell follows after. The fourth rider is the only one named, and a fourth part is his limit.",
    '6:9': "The souls are under the altar, where the blood of the offering was poured. They are the sacrifice.",
    '6:10': "\"How long, O Lord?\" The martyrs ask for judgment, and scripture records the question without rebuke.",
    '6:11': "Rest a little season, until the number is filled. The answer to How long turns out to be Not yet.",
    '6:12': "Sun black as sackcloth, moon as blood. The fixed points overhead are the first things to go.",
    '6:14': "The heaven departs as a scroll rolled together. The sky is treated as a document being put away.",
    '6:15': "Kings and bondmen hide in the same rocks. The judgment flattens the social order before it touches anyone.",
    '6:16': "\"Hide us from the face of him that sitteth on the throne.\" They ask a mountain to do what no mountain can.",
    '6:17': "\"The wrath of the Lamb\" is a deliberately impossible phrase, and it is the thing they cannot face.",

    # ---- Chapter 7 ----
    '7:1': "Four angels hold the four winds. Before anything is loosed, restraint is shown to be already in place.",
    '7:2': "The seal of the living God arrives before the harm does. The marking comes first.",
    '7:3': "\"Hurt not... till we have sealed the servants of our God.\" The delay in the disaster is for their sake.",
    '7:4': "A hundred forty and four thousand, heard as a number out of a tribal roll. The disputes begin right here.",
    '7:9': "He heard a number and then saw a multitude no man could number. The count and the sight do not match.",
    '7:10': "Salvation is ascribed to God and the Lamb. Those who came through claim none of it as achievement.",
    '7:12': "The angels' doxology is a sevenfold Amen wrapped around God. They add nothing; they agree.",
    '7:13': "The elder asks the question John cannot answer, and then answers it himself.",
    '7:14': "Robes made white in blood. The image refuses to be tidy, and it is this book's picture of righteousness.",
    '7:15': "They serve day and night in his temple, and he dwells among them. Service and shelter are one thing.",
    '7:16': "No hunger, no thirst, no scorching sun. The promises are addressed to people who knew all three.",
    '7:17': "The Lamb becomes the shepherd, and God wipes the tears. Even in glory there are tears to be wiped.",

    # ---- Chapter 8 ----
    '8:1': "Silence in heaven for half an hour. After all that singing, the seventh seal opens onto nothing audible.",
    '8:3': "Much incense offered with the prayers of all saints. The prayers are what the censer is carrying.",
    '8:4': "The smoke of the prayers ascends before God out of the angel's hand. They arrive, and they are handled.",
    '8:5': "The censer that carried prayers up is filled with fire and thrown down. The answer returns as fire.",
    '8:7': "A third part, not all. The trumpets are limited from the first blast, and the limit is repeated each time.",
    '8:10': "A great star falls on the rivers and the fountains. What comes from above spoils what people drink.",
    '8:11': "The star is named Wormwood. Men die because the water was made bitter, not because it was taken away.",
    '8:13': "An angel cries woe three times through mid-heaven. The worst of the trumpets has not sounded yet.",

    # ---- Chapter 9 ----
    '9:1': "A star fallen from heaven is handed a key. Even the bottomless pit is opened by permission.",
    '9:4': "The locusts are forbidden the grass and sent after men without the seal. The mark decides their reach.",
    '9:5': "Not to kill, but to torment five months. The restriction is as unsettling as the permission.",
    '9:6': "\"Men shall seek death, and shall not find it.\" The one exit people count on is closed off.",
    '9:10': "Stings in the tails, and a term of five months. Even the torment is issued with a calendar.",
    '9:11': "Their king is named twice, Destroyer in both tongues. The thing has no other identity to give.",
    '9:12': "\"One woe is past.\" The book keeps count so the reader knows how much is still to come.",
    '9:13': "The voice comes from the horns of the golden altar -- the same altar that held the prayers.",
    '9:14': "Four angels bound at the Euphrates are loosed on command. They were held, and now they are not.",
    '9:15': "Prepared for an hour, a day, a month and a year. The moment was appointed before the army existed.",
    '9:20': "After all of it, \"repented not.\" The plagues produce no change of mind, and the text says so flatly.",
    '9:21': "Murders, sorceries, fornication, thefts. The list is ordinary crime, not exotic wickedness.",

    # ---- Chapter 10 ----
    '10:1': "Clothed with a cloud, a rainbow on his head. The mighty angel wears the throne's own insignia.",
    '10:2': "One foot on the sea and one on the land, and the little book is open. The claim is territorial.",
    '10:3': "Seven thunders utter their voices, and they are voices with something in them to say.",
    '10:4': "\"Seal up those things... and write them not.\" This revelation includes a deliberate withholding.",
    '10:6': "An oath sworn by the Creator that there should be time no longer. What ends is the delay.",
    '10:7': "The mystery of God is finished as he declared to the prophets. Not a new plan; an old one completed.",
    '10:9': "\"Take it, and eat it up.\" The word has to be swallowed before it can be spoken.",
    '10:10': "Sweet in the mouth and bitter in the belly. The same message does both, and in that order.",
    '10:11': "After the bitterness, he must prophesy again. The commission is renewed rather than withdrawn.",

    # ---- Chapter 11 ----
    '11:1': "Measuring here is an act of ownership. The temple is surveyed before it is threatened.",
    '11:2': "The outer court is left unmeasured and given to the Gentiles. Some ground is deliberately unprotected.",
    '11:3': "Two witnesses in sackcloth. The prophesying and the mourning clothes arrive together.",
    '11:4': "Olive trees and candlesticks. The image is Zechariah's, and it means supply and light, not force.",
    '11:5': "Fire proceeds out of their mouth. Their only weapon is again speech, and it kills.",
    '11:6': "Elijah's drought and Moses' plagues in two men. The old prophetic powers turn up together.",
    '11:7': "\"When they shall have finished their testimony\" -- the beast kills them only after the work is done.",
    '11:8': "The great city is called Sodom and Egypt, and it is where our Lord was crucified. The naming is deliberate.",
    '11:9': "Three and a half days of unburied bodies, watched by everyone. The humiliation is public and prolonged.",
    '11:10': "They send gifts to one another. The death of the witnesses is kept as a holiday.",
    '11:11': "The Spirit of life entered into them and they stood upon their feet. The reversal takes one sentence.",
    '11:12': "\"Come up hither\" -- the words John himself heard, now spoken to the dead, in front of their enemies.",
    '11:13': "The remnant were affrighted and gave glory to God. It is the one repentance in the whole sequence.",
    '11:15': "\"The kingdoms of this world are become the kingdoms of our Lord.\" Announced as already done.",
    '11:17': "The elders drop \"which is to come\" from the name. He has come, and the title no longer needs a future.",
    '11:18': "Wrath, reward and ruin in one breath -- and those destroyed are \"them which destroy the earth.\"",
    '11:19': "The ark of his testament is seen. The most hidden object in Israel's worship is now in open view.",

    # ---- Chapter 12 ----
    '12:1': "A woman clothed with the sun. Whatever else she is, she is drawn in the language of the whole sky.",
    '12:2': "She cried, travailing in birth, and pained to be delivered. The vision does not skip the labour.",
    '12:3': "The dragon wears seven crowns. Opposition in this book is always a parody of the real thing.",
    '12:4': "The dragon waits at the birth to devour the child. The attack is aimed at the moment of arrival.",
    '12:5': "The man child is caught up to God and to his throne. Between the birth and that, the text leaves a gap.",
    '12:6': "The woman flees to a place prepared of God. Wilderness and provision stand in the same clause.",
    '12:7': "War in heaven. The struggle on earth has a version above it the reader could not otherwise have seen.",
    '12:8': "\"Neither was their place found any more in heaven.\" He is not destroyed; he is evicted.",
    '12:9': "Dragon, old serpent, Devil, Satan -- four names for one, and his trade is deceiving the whole world.",
    '12:10': "The accuser is cast down, and that is what gets called salvation. The relief is judicial first.",
    '12:11': "Blood of the Lamb, word of their testimony, and not loving their lives. Victory counted as loss.",
    '12:12': "Heaven rejoices and earth gets the woe. His wrath is explained by his knowing his time is short.",
    '12:13': "Unable to reach the child, he turns on the mother. Frustrated malice looks for a reachable target.",
    '12:14': "Eagles' wings, and a place, and a time, times and half a time. Even the protection runs on a clock.",
    '12:15': "A flood out of the serpent's mouth. When he cannot devour, he drowns with words.",
    '12:16': "\"The earth helped the woman.\" Creation takes a side in this, and it is not the dragon's.",
    '12:17': "He goes to make war with the remnant of her seed -- which is to say, with whoever is reading.",

    # ---- Chapter 13 ----
    '13:1': "The beast rises with blasphemy written on its heads. Its claim to divinity is worn where it shows.",
    '13:2': "Leopard, bear and lion together, and the dragon gives it authority. The power is lent, not its own.",
    '13:3': "A deadly wound healed, and all the world wondered. The beast counterfeits a resurrection to win its following.",
    '13:4': "\"Who is like unto the beast?\" The question is lifted word for word out of the worship of God.",
    '13:5': "A mouth speaking great things, and forty-two months. Even the blasphemy is held on a lease.",
    '13:6': "The blasphemy is aimed at God's name, his tabernacle, and those in heaven. It attacks upward only.",
    '13:7': "\"To make war with the saints, and to overcome them.\" The book concedes that the saints lose this one.",
    '13:8': "\"The Lamb slain from the foundation of the world.\" The cross is not the emergency it appears to be.",
    '13:9': "The formula that ran through the seven letters returns, this time with no church attached.",
    '13:10': "Captivity for captivity, sword for sword. \"Here is the patience and the faith\" -- and no call to arms.",
    '13:11': "Two horns like a lamb and a dragon's voice. The second beast works by resemblance, not by terror.",
    '13:12': "The second beast's entire business is making people worship the first. It asks nothing for itself.",
    '13:13': "Fire from heaven in the sight of men. Elijah's sign, performed by the wrong side.",
    '13:14': "Deceived by the miracles. The wonders are real, and that is precisely how the deception works.",
    '13:15': "An image that speaks and kills. Worship is enforced by the very thing made to be worshipped.",
    '13:16': "Small and great, rich and poor, free and bond. The mark is the one thing handed to everybody.",
    '13:17': "No buying or selling without the mark. Persecution arrives here as an economic condition.",
    '13:18': "\"It is the number of a man.\" Whatever else it means, it is human, and it falls short of seven three times.",

    # ---- Chapter 14 ----
    '14:1': "The Lamb stands on Sion, and what is on their foreheads is his Father's name, not the beast's.",
    '14:3': "A song no one else could learn. Some things are known only from inside of being redeemed.",
    '14:4': "\"They follow the Lamb whithersoever he goeth.\" The description is of a direction, not an attainment.",
    '14:5': "No guile in their mouth, without fault before the throne. Said of people the world had just condemned.",
    '14:6': "The everlasting gospel is preached to every nation in the middle of the judgments, not instead of them.",
    '14:7': "The gospel's content here is fear God and worship the Creator. It starts where idolatry has to end.",
    '14:8': "\"Babylon is fallen, is fallen\" -- past tense, four chapters before the city is even described.",
    '14:9': "The third angel's warning is about worship, which is what the whole conflict has been about.",
    '14:10': "Wine \"without mixture\" -- the one thing in this book not diluted or held to a third part.",
    '14:11': "The smoke ascends for ever. The sentence is severe, and the book makes no attempt to soften it.",
    '14:12': "\"Here is the patience of the saints.\" Between two terrible announcements, the instruction is to endure.",
    '14:13': "\"Blessed are the dead which die in the Lord.\" Their works follow after; they do not go on ahead as credentials.",
    '14:14': "One like the Son of man on a cloud, crowned, holding a sickle. The harvest is his to take in.",
    '14:16': "\"And the earth was reaped.\" The grain harvest is reported without a word about destruction.",
    '14:20': "Blood to the horses' bridles for two hundred miles. The winepress is not made presentable for any reader.",

    # ---- Chapter 15 ----
    '15:1': "\"In them is filled up the wrath of God.\" These plagues are last because the wrath comes to an end.",
    '15:2': "The sea of glass is mingled with fire now, and those who refused the mark are standing on it.",
    '15:3': "The song of Moses and the song of the Lamb sung as one song. Exodus and Calvary share a tune.",
    '15:4': "\"All nations shall come and worship\" -- sung in the middle of a book about nations in revolt.",
    '15:7': "The wrath is handed over in vials by a living creature. Even this is administered, not spilled.",
    '15:8': "No man could enter the temple till the plagues were finished. There is an interval when access is shut.",

    # ---- Chapter 16 ----
    '16:1': "The order to pour comes out of the temple. The wrath is issued from the place of worship.",
    '16:2': "The first vial falls on those with the mark. The plagues are aimed rather than indiscriminate.",
    '16:5': "\"Thou art righteous... because thou hast judged thus.\" The angel of the waters defends the verdict.",
    '16:6': "Blood to drink for those who shed blood. The punishment is described as a matching of measures.",
    '16:7': "The altar itself answers Amen -- the same altar under which the martyrs asked how long.",
    '16:9': "Scorched, they blasphemed and repented not. Pain does not produce repentance; the book keeps saying it.",
    '16:10': "Darkness falls on the beast's own seat. The kingdom built around that throne is what goes dark.",
    '16:11': "They blasphemed because of their pains. The suffering is acknowledged and still resented at the source.",
    '16:12': "The river is dried up to prepare a way. Even the enemy's road is opened for him.",
    '16:13': "Three unclean spirits like frogs, out of three mouths. The counterfeit trinity works by talking.",
    '16:14': "Spirits of devils, working miracles, gathering kings. The armies are assembled by persuasion.",
    '16:15': "\"Behold, I come as a thief.\" A word to the reader dropped straight into the middle of a battle scene.",
    '16:16': "Armageddon is named and then nothing happens there. The place is given and the battle deferred.",
    '16:17': "\"It is done.\" Two words out of the throne, and the sequence of vials is over.",
    '16:19': "\"Great Babylon came in remembrance before God.\" What looked forgotten was being remembered all along.",
    '16:21': "Hail of a talent weight, and men blasphemed. The last human response recorded here is cursing.",

    # ---- Chapter 17 ----
    '17:1': "The judgment of the whore is shown by an angel with a vial. The same hand pours and explains.",
    '17:2': "Kings commit fornication with her and the inhabitants are made drunk. Her power works by consent.",
    '17:3': "The woman sits on the beast. She is carried by the power she appears to be commanding.",
    '17:4': "Purple, scarlet, gold and a golden cup. Everything about her is expensive, and the cup is full of filth.",
    '17:5': "The name is written on her forehead, where the seal and the mark go. Everyone in this book is labelled.",
    '17:6': "Drunken with the blood of saints -- and John \"wondered with great admiration.\" Even he was impressed.",
    '17:7': "The angel rebukes the wonder before he explains the mystery. Being dazzled was the first problem.",
    '17:8': "\"Was, and is not, and yet is\" -- a mockery of the name of him which is, and was, and is to come.",
    '17:9': "\"Here is the mind which hath wisdom.\" The text announces a riddle and then leaves it a riddle.",
    '17:10': "Five fallen, one is, one not yet come. The count is given without names, and it has never been settled.",
    '17:12': "Ten kings receiving power for one hour. The alliance has real authority and almost no time.",
    '17:13': "\"These have one mind.\" Unanimity is offered as the mark of the coalition, not as a virtue.",
    '17:14': "\"The Lamb shall overcome them.\" The war is reported before it is fought, and the outcome is not in doubt.",
    '17:15': "The waters she sits on are peoples and nations. Her seat is popular support.",
    '17:16': "The beast's own horns turn on the woman. The system she rode destroys her without outside help.",
    '17:17': "\"God hath put in their hearts to fulfil his will.\" Their agreement against him is serving him.",
    '17:18': "The woman turns out to be a city. The great enemy of this book is a government and a market.",

    # ---- Chapter 18 ----
    '18:1': "The earth was lightened with his glory. The announcement of ruin arrives carrying light.",
    '18:2': "\"Babylon the great is fallen\" -- and what is left is a cage of unclean birds. The glory leaves a waste.",
    '18:3': "Kings, nations and merchants. Politics, culture and trade are all named in the same sentence.",
    '18:4': "\"Come out of her, my people.\" The call assumes God's people are inside and comfortable.",
    '18:5': "Her sins reached unto heaven and God remembered. It is the accumulation that finally registers.",
    '18:6': "\"In the cup which she hath filled fill to her double.\" The judgment uses the vessel she supplied.",
    '18:7': "\"I sit a queen, and am no widow.\" The boast is security, and the security is what dates her.",
    '18:8': "\"In one day\" -- the speed of the collapse is the detail the chapter keeps returning to.",
    '18:9': "The kings lament from a safe distance. Nobody who profited from her comes any nearer.",
    '18:10': "\"Standing afar off for the fear of her torment.\" The grief is real and the self-preservation is stronger.",
    '18:11': "The merchants weep because no man buys their merchandise. The tears are over unsold stock.",
    '18:13': "The cargo list ends with \"slaves, and souls of men.\" The last item is the whole indictment.",
    '18:14': "\"Thou shalt find them no more at all.\" The verse turns and speaks to the city about what she wanted.",
    '18:17': "\"In one hour so great riches is come to nought.\" What took centuries to build is priced by the hour.",
    '18:18': "\"What city is like unto this great city!\" The question asked of the beast, now asked of a marketplace.",
    '18:19': "Dust on their heads, and the lament is that she made them rich. They are mourning their own losses.",
    '18:20': "Heaven is told to rejoice over the smoke the kings are weeping at. Both reactions go in the record.",
    '18:21': "A millstone cast into the sea. The sign was chosen because a millstone does not come back up.",
    '18:22': "No harpers, no craftsmen, no millstone. What the chapter misses is ordinary work and ordinary music.",
    '18:23': "No candle, no voice of the bridegroom. The judgment is measured in weddings that will not happen.",
    '18:24': "\"In her was found the blood of prophets, and of saints.\" Underneath the trade and the music, this.",

    # ---- Chapter 19 ----
    '19:1': "The first Alleluia in the book comes after a city burns. Praise is provoked by a judgment.",
    '19:2': "\"True and righteous are his judgments.\" What heaven approves is the verdict, not the suffering.",
    '19:3': "\"And her smoke rose up for ever and ever.\" The Alleluia is repeated over that sentence.",
    '19:4': "The elders and the living creatures say Amen, and it is the last thing they are recorded saying.",
    '19:5': "\"Both small and great.\" The summons to praise recognises no distinction the world would make.",
    '19:6': "\"The Lord God omnipotent reigneth\" -- present tense, and the loudest sound in the book.",
    '19:7': "\"His wife hath made herself ready.\" The readiness is credited to her, and the next verse explains it.",
    '19:8': "The linen was granted to her, and the linen is the righteousness of saints. Given, and hers.",
    '19:9': "\"Blessed are they which are called unto the marriage supper.\" The guests are invited, not qualified.",
    '19:10': "The angel refuses worship and redirects it. \"The testimony of Jesus is the spirit of prophecy.\"",
    '19:11': "Faithful and True, and \"in righteousness he doth judge and make war.\" The war is a judicial act.",
    '19:12': "A name that no man knew but he himself. Even in this final unveiling something is held back.",
    '19:13': "The vesture is dipped in blood before any battle is fought. The blood on it is his own.",
    '19:15': "The sword is out of his mouth again. He rides out armed with nothing but speech.",
    '19:16': "KING OF KINGS written where anyone can read it. The title is worn rather than announced.",
    '19:17': "Birds are called to a supper. The chapter sets it directly opposite the marriage supper of the Lamb.",
    '19:19': "The armies gather to make war, and the gathering is the only part that gets described.",
    '19:20': "The beast and the false prophet are taken. No battle is narrated; the arrest is the entire event.",
    '19:21': "The remnant are slain by the sword out of his mouth. The word does all the killing there is.",

    # ---- Chapter 20 ----
    '20:1': "An angel with a key and a chain. The binding is done by an errand, not by a war.",
    '20:2': "The dragon is bound a thousand years, and the number is given without any explanation attached.",
    '20:3': "The stated purpose is \"that he should deceive the nations no more.\" Deception is what his power is.",
    '20:4': "Thrones, and on them the ones who were beheaded. Those who lost their heads are given the judgment seat.",
    '20:5': "\"This is the first resurrection\" -- a phrase that has divided readers ever since, and it is not expanded.",
    '20:6': "Blessed, holy, priests, reigning -- and \"the second death hath no power\" on them. The promise is a negative.",
    '20:7': "Satan is loosed when the thousand years expire. The release is as deliberate as the binding was.",
    '20:8': "He goes out to deceive, and the nations come. The same method still works after a thousand years.",
    '20:9': "Fire came down and devoured them. For the second time, the last battle ends before it starts.",
    '20:10': "The deceiver is cast where the beast and the false prophet already are. He is judged for the deceiving.",
    '20:11': "Earth and heaven flee from the face on the throne, and no place is found for them.",
    '20:12': "The books were opened, and another book. Works are read out, and a second register settles the matter.",
    '20:13': "Sea, death and hell give up their dead. No one is excused from appearing on the grounds of being lost.",
    '20:14': "Death itself is cast into the lake of fire. The last thing to die is dying.",
    '20:15': "Not found written in the book of life. The criterion stated at the very end is a name in a register.",

    # ---- Chapter 21 ----
    '21:1': "\"No more sea\" -- the element that carried the beast and kept John from his churches is simply gone.",
    '21:2': "The city comes down out of heaven. It is not built up from below, and it arrives dressed as a bride.",
    '21:3': "\"The tabernacle of God is with men.\" The whole history of tent and temple ends in one sentence.",
    '21:4': "He wipes the tears away himself. The comfort is not the absence of grief but somebody's hand.",
    '21:5': "\"Behold, I make all things new\" -- not all new things. What exists is renewed rather than replaced.",
    '21:6': "The water of life is given freely to whoever is athirst. The only qualification named is wanting it.",
    '21:7': "\"He shall be my son.\" After all the promises to overcomers, the last one is a relationship.",
    '21:8': "The list begins with the fearful and ends with liars. Cowardice heads the catalogue.",
    '21:9': "The angel who showed him the whore now shows him the bride. Same guide, opposite city.",
    '21:10': "Carried to a great high mountain to watch a city descending. The vantage is high and it still comes down.",
    '21:11': "Her light is the glory of God. The city does not shine on its own account.",
    '21:12': "Twelve gates named for the tribes, with an angel at each. Named for Israel, guarded, and not shut.",
    '21:14': "Twelve foundations bearing the apostles' names. The city rests on men who ran away once.",
    '21:16': "The city is a cube, the shape of the holy of holies. The whole place is the room only one man could enter.",
    '21:18': "Gold like clear glass -- the most opaque metal described as transparent. Nothing there conceals anything.",
    '21:21': "Each gate one pearl, and the street pure gold. What men hoard is used here for paving.",
    '21:22': "\"I saw no temple therein.\" The one building the whole Bible works toward is the thing that is missing.",
    '21:23': "No need of sun or moon. The lights that measured time are made unnecessary, not destroyed.",
    '21:24': "The nations walk in its light and kings bring their glory in. Something of human history is carried through.",
    '21:25': "The gates are never shut, because there is no night. Security has stopped being a consideration.",
    '21:27': "Nothing that defiles comes in -- and the gate is a book of life, not a standard of conduct.",

    # ---- Chapter 22 ----
    '22:1': "The river proceeds out of the throne. What the city drinks comes from where God sits.",
    '22:2': "The tree of life bears every month, and the leaves heal the nations. Eden comes back as a public street.",
    '22:3': "\"There shall be no more curse.\" Genesis 3 is revoked by name in the last chapter of the book.",
    '22:4': "\"They shall see his face.\" What Moses was refused is handed over in five words.",
    '22:5': "They shall reign for ever. The servants of one verse are the kings two verses later.",
    '22:6': "\"These sayings are faithful and true.\" The book keeps certifying itself, because it is hard to believe.",
    '22:7': "The blessing is pronounced on keeping the sayings, not on decoding them.",
    '22:8': "John falls down to worship the angel a second time. Even he does not learn it the first time.",
    '22:9': "\"I am thy fellowservant... worship God.\" The angel's entire answer is to redirect.",
    '22:10': "\"Seal not the sayings\" -- the opposite of what Daniel was told, because the time is now at hand.",
    '22:11': "Let the unjust be unjust still. It sounds like resignation and is actually about the hour being late.",
    '22:12': "\"My reward is with me.\" He brings it rather than finding it. Nothing is collected on arrival.",
    '22:14': "Right to the tree of life and entry through the gates. The blessing is stated as access.",
    '22:15': "\"Without are dogs\" -- the exclusion is recorded two verses before the widest invitation in the book.",
    '22:16': "Root and offspring of David at once: his ancestor's descendant and his descendant's source.",
    '22:17': "The Spirit and the bride say Come, and so may anyone who hears. The invitation spreads by being used.",
    '22:18': "A warning against adding, attached to a book people have never stopped adding to.",
    '22:19': "Taking away costs a part in the city. The threat is the exact mirror of the promise.",
    '22:20': "\"Surely I come quickly\" and \"Even so, come.\" The last exchange in the Bible is the church answering.",
    '22:21': "After dragons and plagues and a lake of fire, the last word of the book is grace.",
}
