#!/usr/bin/env python3
"""Written one-line takeaways for Romans.

Each states what the verse turns on. Verses carrying no standalone point —
bare connectives, greeting lists, the lead-in half of a quotation — are left
out deliberately; the drawer hides the card rather than showing filler.
"""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Servant, called, separated: Paul's three credentials are all things done to him, none of them chosen.",
    '1:2': "The gospel is not news of a change of mind in God. It was promised long before Paul preached it.",
    '1:3': "\"Made of the seed of David\" — the gospel's subject has a genealogy, not merely a doctrine.",
    '1:4': "The resurrection did not make him Son of God. It declared him so, with power, where all could see.",
    '1:5': "Grace and apostleship arrive in the same breath. The commission is part of the gift, not payment for it.",
    '1:7': "\"Called to be saints\" describes the Roman Christians before it asks anything of them.",
    '1:8': "He thanks God for their faith rather than congratulating them on it.",
    '1:9': "Prayer no one else witnessed still gets a witness: Paul calls God to testify to it.",
    '1:10': "Even the travel plans are held loosely — \"if by any means... by the will of God.\"",
    '1:11': "He wants to give them something, and the stated aim is their stability, not his standing.",
    '1:12': "He corrects himself mid-sentence: the apostle expects to be comforted by them as well.",
    '1:13': "\"But was let hitherto\" — years of blocked intention, reported without being explained away.",
    '1:14': "\"I am debtor\" — receiving the gospel put him in debt to people he had never met.",
    '1:15': "He is as ready to preach in the capital as anywhere else. The gospel does not adjust for an address.",
    '1:16': "\"Not ashamed\" concedes there was something to be ashamed of. The power belongs to God, not to the message's respectability.",
    '1:17': "The righteousness revealed is God's own, and it runs from faith to faith — never faith topped up by something else.",
    '1:18': "Wrath is revealed in the same tense as righteousness. Both are present, not merely coming.",
    '1:19': "What can be known of God is not hidden. The trouble lies further along than information.",
    '1:20': "Creation leaves no one uninformed, which is why the verdict is \"without excuse\" rather than untaught.",
    '1:21': "The first sin named is not cruelty but ingratitude, and the darkening follows it rather than causing it.",
    '1:22': "Not ignorance mistaken for knowledge, but a claim to wisdom that hollowed itself out.",
    '1:23': "Idolatry is a downward trade — glory for an image — and the image keeps shrinking down the list.",
    '1:24': "\"God gave them up\" — the judgment is not a thunderbolt but being handed over to what was already wanted.",
    '1:25': "The lie is not denying God but worshipping one level too low, at the creature rather than the Creator.",
    '1:26': "The second \"gave them up\" repeats the shape of the first: the desire itself becomes the sentence.",
    '1:27': "The recompence is received \"in themselves\" — consequence lodged in the doer, not imposed from outside.",
    '1:28': "They would not retain God in their knowledge and were given a mind that could not.",
    '1:29': "Covetousness, envy and whispering stand in the same sentence as murder, with no ranking offered.",
    '1:30': "\"Disobedient to parents\" sits beside \"haters of God.\" The domestic sins are not a lesser category.",
    '1:31': "The catalogue ends with things absent — understanding, affection, mercy — not only things done.",
    '1:32': "Approving the wrong is named last and worst: the applause outlives the act.",

    # ---- Chapter 2 ----
    '2:1': "The reader who was agreeing with chapter one is caught by the first word of chapter two.",
    '2:2': "God's judgment runs \"according to truth,\" which is precisely what makes it unsafe for the judge.",
    '2:3': "Seeing another's sin clearly has never once counted as a defence.",
    '2:4': "God's patience is not evidence of his indifference. It is the thing meant to bring a man round.",
    '2:5': "A hard heart is saving something up. Paul names the account: wrath.",
    '2:6': "Judgment according to deeds is stated plainly here and never withdrawn. It is the standard no one meets.",
    '2:7': "The offer is genuine and its terms are exact — patient continuance, not occasional effort.",
    '2:8': "Disobedience is described as obedience, to unrighteousness. Nobody is unattached.",
    '2:9': "\"To the Jew first\" governs trouble as well as privilege. Priority cuts in both directions.",
    '2:11': "\"No respect of persons\" is bad news for anyone quietly counting on being the exception.",
    '2:12': "Having less light alters the measure of the judgment, not its outcome.",
    '2:13': "Doers, not hearers — the law's own standard, quoted here before chapter three shows no one reaches it.",
    '2:14': "Gentiles who never read the law still behave as though something were written. The law is wider than its text.",
    '2:15': "Conscience is described as a courtroom already in session, with the accusing and excusing under way.",
    '2:16': "Judgment reaches the secrets, which is where everyone keeps what the public record misses.",
    '2:17': "\"Restest in the law\" — the law has become somewhere to lie down rather than a demand to be met.",
    '2:18': "Knowing God's will and approving what is excellent are real advantages, and Paul grants them before turning them.",
    '2:19': "The flattering self-portrait is allowed to run several clauses before it is punctured.",
    '2:21': "The indictment is delivered entirely as questions, which leaves the reader to return the verdict.",
    '2:22': "Abhorring idols and robbing temples can live in one man without either habit noticing the other.",
    '2:23': "Boasting in the law while breaking it does not embarrass the boaster first. It dishonours God.",
    '2:24': "The cost of religious inconsistency is measured in what outsiders conclude about God.",
    '2:25': "A sign kept without the thing it signifies does not stay neutral. It reverses.",
    '2:26': "Reckoning works in both directions: the outsider can be counted in.",
    '2:27': "The man without the badge ends up judging the man with it.",
    '2:28': "The outward mark is not called worthless, only insufficient to settle anything.",
    '2:29': "Circumcision of the heart cannot be self-administered, and its praise comes from the only one who can see it.",

    # ---- Chapter 3 ----
    '3:1': "Paul states the obvious objection to his own argument rather than steering around it.",
    '3:2': "The advantage is real and it is custodial. They were trusted with words, not granted immunity.",
    '3:3': "God's faithfulness is not a variable that moves with ours.",
    '3:4': "\"Let God be true, but every man a liar\" — the only arrangement under which anything at all can be trusted.",
    '3:5': "He flags the argument as human speech before making it, so that it cannot be mistaken for gospel.",
    '3:6': "The reply is short: take away God's right to judge and nothing is left standing.",
    '3:7': "If my lie serves God's glory, I have done him a service. Paul knows the argument and refuses it.",
    '3:8': "Being misrepresented is not new. He reports the slander and does not soften the verdict on it.",
    '3:9': "\"All under sin\" — not each guilty in his own fashion, but everyone under one power.",
    '3:10': "The chain of quotations opens with a flat denial, and \"no, not one\" forecloses the exception each reader hopes to be.",
    '3:11': "Seeking after God is listed among what is missing, not among what survives in us.",
    '3:12': "\"Together become unprofitable\" — the universality is the point, not the degree.",
    '3:13': "The indictment works down the body and starts at the mouth, where sin is most easily excused.",
    '3:15': "The feet are swift. Nothing here is sluggish or reluctant about it.",
    '3:17': "\"The way of peace have they not known\" — not refused, not forgotten: never known.",
    '3:18': "The catena ends at the root. Not the deeds, but no fear of God anywhere in view.",
    '3:19': "The law's first effect here is silence, not improvement. Every mouth stopped.",
    '3:20': "The law's office is diagnostic. It shows what is wrong and has no power to mend it.",
    '3:21': "\"But now\" turns the whole letter — righteousness apart from law, and the law itself standing as witness to it.",
    '3:22': "Faith levels the ground. Not that all are alike, but that there is no difference in how any are received.",
    '3:23': "The most quoted verse in the letter is a subordinate clause inside a sentence about being justified freely.",
    '3:24': "\"Freely\" means without cause in us. The cost was real and it was paid elsewhere.",
    '3:25': "Propitiation is what God sets forth, not what is offered up to him from our side.",
    '3:26': "The difficulty was never how God could forgive, but how he could forgive and stay just. Both are answered at once.",
    '3:27': "Boasting is not discouraged here. It is excluded — there is no longer a category for it.",
    '3:28': "\"Without the deeds of the law\" is not a lowered standard. It is a different basis altogether.",
    '3:29': "One God has a consequence: there cannot be two ways in.",
    '3:30': "Same God, same faith, two groups. The change of preposition is not a change of method.",
    '3:31': "Faith does not abolish the law. It finally lets the law be law instead of a ladder.",

    # ---- Chapter 4 ----
    '4:1': "The test case is the one man everyone already agreed was righteous.",
    '4:2': "Paul concedes that works would earn a boast — and says the boast would not survive God's presence.",
    '4:3': "\"Counted\" is a bookkeeping word. Righteousness was credited to Abraham, not produced by him.",
    '4:4': "Wages are owed, not given. Once the language of earning starts, grace has already left the room.",
    '4:5': "\"Him that justifieth the ungodly\" — the only qualification named is not working.",
    '4:6': "David is called as a second witness, and the phrase Paul wants from him is \"without works.\"",
    '4:7': "Blessedness is defined by what is not held against a man rather than by what is found in him.",
    '4:8': "Two reckonings in three verses: righteousness credited, sin not charged. Both are God's arithmetic.",
    '4:10': "Abraham was reckoned righteous before the sign existed. The order cannot be run backwards.",
    '4:11': "Circumcision is a seal on something already given — a receipt, never the purchase.",
    '4:12': "Descent from Abraham is traced by the steps of his faith rather than by blood.",
    '4:13': "The promise was larger than Canaan and older than the law that came to interpret it.",
    '4:14': "If the law-keepers are the heirs, faith is emptied out. Paul will not let the two share the weight.",
    '4:15': "\"The law worketh wrath\" — left to itself it produces not obedience but transgression made visible.",
    '4:16': "Faith is the means because grace is the aim, and certainty is what comes of both.",
    '4:17': "Abraham's God is described by two acts, and both are creation out of nothing.",
    '4:18': "\"Against hope believed in hope\" — faith is not optimism about the available evidence.",
    '4:19': "He looked straight at the dead facts and did not let them speak last. Faith is not blindness.",
    '4:20': "Giving glory to God is named as the content of strong faith, not as its reward.",
    '4:21': "Faith rests on the promiser's ability, never on the believer's confidence in his own.",
    '4:22': "The conclusion repeats the same verb: imputed. Nothing in the accounting has changed.",
    '4:24': "Faith now has the same shape it had then — trust in a God who raises the dead.",
    '4:25': "Delivered for our offences, raised for our justification: the acquittal is already a matter of public record.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "Peace with God is stated as an accomplished fact, not a feeling to be worked up or verified.",
    '5:2': "\"This grace wherein we stand\" — grace is the ground under the feet, not a mood that comes and goes.",
    '5:3': "Glorying in tribulation is not enjoyment of it. The reason given is knowledge of what it produces.",
    '5:4': "The chain runs through experience, which cannot be had in advance and cannot be hurried.",
    '5:5': "Hope does not disappoint because its basis is outside the one hoping — love poured in by the Spirit.",
    '5:6': "\"Without strength\" and \"ungodly\" are the terms of the transaction. Christ did not wait for improvement.",
    '5:7': "Paul measures human love at its very best and finds it falls short of dying for an enemy.",
    '5:8': "\"While we were yet sinners\" fixes the timing. The love was commended before anything in us answered it.",
    '5:9': "The argument runs from the harder thing to the easier: if he died for enemies, he will not lose friends.",
    '5:10': "Reconciliation was worked by his death; the keeping of it is credited to his life. Both ends are his.",
    '5:11': "The gift finally described is God himself — joy in God, not merely relief at the verdict.",
    '5:12': "Sin came in by one man and death spread to all. The problem is inherited, not merely imitated.",
    '5:13': "Sin existed before the law existed to name it; the law changed the record, not the reality.",
    '5:14': "Death reigned over those who had broken no explicit command, which is the proof that something deeper is wrong.",
    '5:15': "The parallel is deliberately uneven — \"much more\" — because grace is not the mere cancelling of the offence.",
    '5:16': "One offence brought condemnation; the free gift starts from many offences and still reaches justification.",
    '5:17': "Those in Adam do not reign; death does. Those in Christ are said to reign in life themselves.",
    '5:18': "Two men, two verdicts, and every human being is standing under one of them.",
    '5:19': "\"Made sinners\" and \"made righteous\" use the same verb. Both statuses are conferred, neither achieved.",
    '5:20': "The law came in to make the offence visible and larger — and grace outran it without effort.",
    '5:21': "Both sin and grace are said to reign. No one is ungoverned; the only question is which reign one is under.",

    # ---- Chapter 6 ----
    '6:1': "If grace abounds over sin, the obvious next question is whether sin is useful. Paul does not pretend it is never asked.",
    '6:2': "The answer is not that sinning is forbidden but that it is incongruous: the dead do not go on living there.",
    '6:3': "Baptism is described as being baptized into his death, not as a ceremony marking a decision.",
    '6:4': "Burial is the point of the image. Newness of life is on the far side of a grave, not an improvement on the old one.",
    '6:5': "The two halves are bound together: whoever is joined to his death is promised his resurrection as well.",
    '6:6': "\"Our old man is crucified with him\" — an execution already carried out, not a project to be undertaken.",
    '6:7': "Death ends sin's legal claim. A corpse cannot be charged.",
    '6:9': "Christ's death was final for him, which is why what happened in it is final for us.",
    '6:10': "He died unto sin once. The \"once\" is the whole comfort of the verse.",
    '6:11': "\"Reckon\" is the verb again: not make yourselves dead to sin, but count true what God has already done.",
    '6:12': "Sin is not told to leave the mortal body. It is told not to reign there — the fight assumes its presence.",
    '6:13': "The members are instruments either way. Neutrality is not on the list of options.",
    '6:14': "Sin's dominion is broken not by stricter law but by being placed under grace. The reason given is the surprising one.",
    '6:15': "The same question returns in a new form, which suggests the answer never settles easily.",
    '6:16': "Everyone obeys something. Freedom in this chapter means a change of master, not the absence of one.",
    '6:17': "The thanks go to God for their obedience — even their turning is credited to him rather than to their resolve.",
    '6:18': "Freedom from sin arrives as servitude to righteousness. Paul does not offer self-ownership.",
    '6:19': "He apologizes for the slavery image as too human, then uses it anyway because nothing plainer will do.",
    '6:20': "Service to sin came with a freedom of its own: free from righteousness, and it produced nothing worth keeping.",
    '6:21': "The argument from shame is simple. Whatever they now blush at was the fruit they were living for then.",
    '6:22': "Holiness is called fruit here, something that grows out of the new master rather than earning him.",
    '6:23': "Wages are earned and gifts are not; the sentence keeps the two words apart on purpose.",

    # ---- Chapter 7 ----
    '7:1': "The law's authority is real and it is bounded by death. That limit is the whole argument to come.",
    '7:2': "The illustration turns on a death, not on a release or a renegotiation of terms.",
    '7:4': "The believer is not merely freed from one marriage but given another — dead to the law in order to be joined to Christ.",
    '7:5': "The law did not restrain the motions of sin; it stirred them. Paul says this before defending the law.",
    '7:6': "Serving in newness of spirit rather than oldness of letter is a change of manner, not the end of service.",
    '7:7': "\"I had not known lust, except the law had said, Thou shalt not covet\" — the law's work is to make sin recognisable.",
    '7:8': "The commandment did not create the sin; it gave the sin an occasion and brought it to life.",
    '7:9': "\"I was alive without the law once\" — the comfortable self-assessment that the commandment came and killed.",
    '7:10': "A commandment ordained to life turned out to deal death, and the fault was not in the commandment.",
    '7:11': "Sin's method is deception, and its instrument is something holy. That is what makes it hard to see coming.",
    '7:12': "Having described what the law does to him, Paul insists it is holy, just and good. The law is not the villain.",
    '7:13': "The law's severest use is to make sin appear as sin — exceeding sinful, and therefore impossible to manage.",
    '7:14': "\"The law is spiritual: but I am carnal\" — the mismatch is not in the standard but in the one under it.",
    '7:15': "The divided will is described from inside: the man does not understand his own behaviour.",
    '7:16': "Even the failure testifies for the law. Hating what he does means he agrees with the verdict on it.",
    '7:17': "\"Sin that dwelleth in me\" — not an excuse but a diagnosis: sin as a resident, not a series of decisions.",
    '7:18': "Willing is present, performing is not. The gap between them is the whole of the chapter's misery.",
    '7:19': "The sentence circles back on itself because the experience does. There is no progress to report.",
    '7:20': "The doubling of the earlier verdict shows a man who has stopped expecting a different result.",
    '7:21': "He calls it a law — not an occasional lapse but a regularity he can predict about himself.",
    '7:22': "Delight in God's law and captivity to sin coexist in one man, and the chapter refuses to resolve this into one or the other.",
    '7:23': "The war is not between the believer and the world but between two laws inside the same body.",
    '7:24': "\"Who shall deliver me\" — the cry asks for a person, not a method, and that is why there is an answer.",
    '7:25': "The thanksgiving comes first and the divided state is restated after it. Both are true of the same man at once.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "\"No condemnation\" is stated as present and total. Not reduced, not suspended: none.",
    '8:2': "One law displaces another. Freedom here is not lawlessness but a change of jurisdiction.",
    '8:3': "The law's weakness was never in itself but in the material it had to work with, and God did what it could not.",
    '8:4': "The law's righteousness is fulfilled in us, not by us; the passive voice is doing the work in this sentence.",
    '8:5': "Minding is the tell. What a man's attention drifts toward says where he lives.",
    '8:6': "Two minds, two outcomes, stated without qualification. Peace is listed as life's companion, not its bonus.",
    '8:7': "\"Neither indeed can be\" — the carnal mind is not merely unwilling to submit but unable, which rules out self-repair.",
    '8:8': "The impossibility is total, and it is about persons, not performances.",
    '8:9': "The mark of belonging is the Spirit's indwelling, not the believer's intensity about it.",
    '8:10': "The body is still under sentence; the verse does not promise otherwise, and still calls the Spirit life.",
    '8:11': "The same power that raised Jesus is said to be aimed at mortal bodies — resurrection, not escape from the body.",
    '8:12': "We are debtors — but not to the flesh. Paul names the creditor we no longer owe.",
    '8:13': "Mortifying the deeds of the body is done \"through the Spirit.\" Even the killing is not self-generated.",
    '8:14': "Being led is the evidence of sonship, not a further stage beyond it.",
    '8:15': "\"Abba, Father\" is the cry of a child, not a slave. Fear is named as the spirit they did not receive.",
    '8:16': "Assurance is a joint testimony. Our own spirit is not left to persuade itself.",
    '8:17': "Heirship and suffering are placed in the same sentence, which means suffering is not evidence against it.",
    '8:18': "He does not deny the weight of present suffering. He weighs it against something and reports the result.",
    '8:19': "Creation is described as craning its neck, and what it waits for is the unveiling of God's children.",
    '8:20': "\"Not willingly\" — creation's futility was imposed on it, and imposed with hope attached.",
    '8:21': "The world is not written off. Its deliverance is tied to the liberty of the children of God.",
    '8:22': "\"Travaileth\" makes the pain productive rather than merely destructive, but it is still pain until now.",
    '8:23': "Having the firstfruits makes the groaning worse, not better. The Spirit sharpens the sense of what is missing.",
    '8:24': "Hope that can be seen has stopped being hope. Its invisibility is a feature of it.",
    '8:25': "Patience is defined here as what hope does with time.",
    '8:26': "Not knowing what to pray for is treated as the normal condition, and the Spirit prays underneath it.",
    '8:27': "The prayer that never found words is the one that is certainly according to God's will.",
    '8:28': "The promise is that all things work together for good, not that all things are good.",
    '8:29': "The good being worked toward is named: conformity to the image of his Son, which is not comfort.",
    '8:30': "The chain has no dropped link and the last verb is past tense: glorified, spoken of as already done.",
    '8:31': "\"If God be for us\" — the question is not whether anyone is against us but whether it can matter.",
    '8:32': "The argument runs from the hardest gift to all the rest. Anyone who gave the Son will not turn stingy now.",
    '8:33': "The answer to accusation is not a defence of the accused but the identity of the judge.",
    '8:34': "Four facts are stacked against condemnation, and the last one is that he is praying for us at this moment.",
    '8:35': "The list of separating candidates is made of real disasters, not imagined ones.",
    '8:36': "Paul quotes a psalm of slaughter into the middle of an assurance passage. The comfort is not a denial of the killing.",
    '8:37': "\"More than conquerors\" is said of people being killed all the day long, not of people spared.",
    '8:38': "The catalogue is exhaustive on purpose: death and life, present and future, nothing held in reserve.",
    '8:39': "The love is located \"in Christ Jesus our Lord\" — outside us, which is the only reason nothing in us can lose it.",

    # ---- Chapter 9 ----
    '9:1': "Three witnesses to his sincerity before he says one word of the sorrow. He expects to be doubted.",
    '9:2': "The doctrine of election opens with grief, not with satisfaction.",
    '9:3': "He would trade his own salvation for theirs. Whatever follows about God's choosing is not said coldly.",
    '9:4': "The privileges are listed in full and in the present tense. Paul does not diminish what Israel was given.",
    '9:5': "The line of the fathers ends in a doxology: the Christ who came of them is over all, God blessed for ever.",
    '9:6': "The problem is not a failed promise but a misread one. \"They are not all Israel, which are of Israel.\"",
    '9:7': "Descent from Abraham was never by itself the qualification, even in Abraham's own household.",
    '9:8': "Children of promise, not of flesh. Birth has never been the mechanism by which anyone is counted in.",
    '9:9': "The promise names a time and a son. Isaac existed because God said so, not because Abraham managed it.",
    '9:11': "\"Not yet born, neither having done any good or evil\" — the choosing is deliberately placed before any record exists.",
    '9:12': "The elder serving the younger overturns the one rule of succession everybody assumed was fixed.",
    '9:13': "The hardest sentence in the chapter is a quotation, and Paul does not soften it.",
    '9:14': "The charge of unrighteousness is raised by Paul himself. He knows the doctrine sounds like injustice.",
    '9:15': "Mercy is defined by the one who shows it. The moment it is owed, it has stopped being mercy.",
    '9:16': "Willing and running are both ruled out — the will is named among the things that do not decide this.",
    '9:17': "Even Pharaoh's resistance is said to serve a declared purpose. Nothing here is operating outside God's reach.",
    '9:18': "Mercy and hardening are stated in the same breath, with no explanation offered for either.",
    '9:19': "The objection is the reasonable one, and Paul quotes it before answering it.",
    '9:20': "The answer is not an argument but a question about standing: who is doing the replying.",
    '9:21': "The potter image grants the clay no vote and offers the reader no seat on the other side of the wheel.",
    '9:22': "\"Endured with much longsuffering\" — even the vessels of wrath are described as objects of divine patience.",
    '9:23': "The purpose named is to make known the riches of his glory. Mercy is what the whole argument is for.",
    '9:24': "The doctrine lands on \"even us\" — election is not an abstraction but the explanation of how Gentiles got here.",
    '9:25': "\"Not my people\" becomes \"my people\" by nothing but God's saying so.",
    '9:26': "The place of the rejection becomes the place of the naming. The location is not moved.",
    '9:27': "A remnant saved is both a promise and a reduction, and Paul lets both halves stand.",
    '9:28': "The work will be finished and cut short. God's judgments are not endlessly deferred.",
    '9:29': "Without a seed left, Israel would have been Sodom. The difference was never Israel's own doing.",
    '9:30': "Those not chasing righteousness caught it. Those pursuing it did not. Paul states the scandal flatly.",
    '9:31': "Israel's failure was not lack of effort. The effort was the problem.",
    '9:32': "\"Not by faith, but as it were by the works of the law\" — the stumblingstone is put there by God, and it is Christ.",
    '9:33': "The same stone that trips is the one to believe on, and believing on it is the end of being ashamed.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "After chapter nine's hard doctrine, the next thing Paul does is pray for the people it was about.",
    '10:2': "Zeal is granted them without irony, and it is not enough. Sincerity is not the missing ingredient.",
    '10:3': "Establishing one's own righteousness is described as a failure to submit. The self-made kind is disobedience, not effort.",
    '10:4': "\"Christ is the end of the law for righteousness\" — the finish line, not the abolition, and only for those who believe.",
    '10:5': "Moses states the law's terms honestly: do these things and live. Nobody has ever collected on that offer.",
    '10:6': "The righteousness of faith speaks against heroic religion. Nobody is asked to fetch Christ down from heaven.",
    '10:7': "Nor up from the deep. Both impossible errands are cancelled because the work is already finished.",
    '10:8': "\"The word is nigh thee\" — what faith needs has been brought within reach and put in the mouth.",
    '10:9': "Confession and belief, mouth and heart, and the content is a resurrection that happened outside us.",
    '10:10': "Faith is not private by design. It is given a mouth as well as a heart.",
    '10:12': "\"No difference\" is said twice in this letter, and both times it cuts a privilege away and opens a door.",
    '10:13': "\"Whosoever shall call\" leaves no one standing outside on a technicality.",
    '10:14': "The chain runs backwards from calling to preaching, which puts the burden on the sender rather than the hearer.",
    '10:15': "Feet are called beautiful — the least dignified part of the messenger, because of what he carries.",
    '10:16': "Preaching does not guarantee obedience, and Isaiah's complaint is quoted to say so.",
    '10:17': "Faith comes from outside: by hearing, and hearing by the word. It is not generated by looking inward.",
    '10:18': "The excuse of not having heard is examined and denied. The sound went out.",
    '10:19': "God's method with Israel includes jealousy — he uses the outsiders' welcome as an appeal.",
    '10:20': "\"I was found of them that sought me not\" — Paul calls Isaiah bold, because the verse credits God with all the initiative.",
    '10:21': "Hands stretched out all day long to a people answering back. Election does not cancel the pleading.",

    # ---- Chapter 11 ----
    '11:1': "The question is answered first with a person: Paul himself is the evidence that God has not finished with Israel.",
    '11:2': "Elijah is introduced as a man praying against his own people, which is the mistake being corrected.",
    '11:3': "\"I am left alone\" — the prophet's despair was sincere, well-informed and wrong.",
    '11:4': "Seven thousand were reserved by God, not recruited by Elijah, and he had no idea they existed.",
    '11:5': "A remnant \"according to the election of grace\" — smallness is not failure when the counting is God's.",
    '11:6': "Grace and works cannot be mixed without one of them ceasing to be itself. Paul says it twice to close the door.",
    '11:7': "Israel did not obtain what it sought; the election obtained it. Seeking was never the deciding factor.",
    '11:8': "A spirit of slumber is not sleepiness. It is judicial, and it is quoted from their own scriptures.",
    '11:9': "The table — the place of blessing and plenty — is what becomes the snare. Gifts can harden.",
    '11:11': "The fall is not the end of the story but the means of another mercy, and that mercy circles back.",
    '11:12': "\"How much more their fulness\" — Paul reasons from the good that came out of the loss to a greater good coming.",
    '11:13': "He magnifies his office to Gentiles precisely in order to reach Jews. The strategy is indirect and admitted.",
    '11:14': "\"Might save some of them\" — the apostle to the Gentiles is still hoping to provoke his own kin.",
    '11:15': "If their setting aside reconciled the world, their receiving is described as life from the dead.",
    '11:16': "Holiness runs from root to branch. The argument is about derivation, not about merit anywhere in the tree.",
    '11:17': "The wild branch partakes of a root it did not grow and could not have produced.",
    '11:18': "\"Thou bearest not the root, but the root thee\" — the grafted branch is carried, and it forgets this quickly.",
    '11:19': "The boast is given its most plausible form — they were removed for my sake — before it is dismantled.",
    '11:20': "\"Thou standest by faith. Be not highminded, but fear.\" Assurance and presumption are not the same thing.",
    '11:21': "If the natural branches were not spared, no grafted one has grounds for confidence in itself.",
    '11:22': "Goodness and severity are both attributes of the same God, and Paul refuses to let a reader choose one.",
    '11:23': "The broken branches are not discarded. God is named as able to graft them back in.",
    '11:24': "Grafting a wild branch into a good tree is the unnatural act; restoring the natural ones is the easier.",
    '11:25': "The warning against conceit is the stated reason for revealing the mystery at all.",
    '11:26': "The Deliverer comes out of Sion and turns away ungodliness; Israel's salvation is by the same means as anyone's.",
    '11:27': "The covenant is defined by what God does, not by what is promised back to him: \"when I shall take away their sins.\"",
    '11:28': "Enemies and beloved at once, from two different angles. Paul lets the two stand together unreconciled.",
    '11:29': "\"Without repentance\" — God does not change his mind about whom he has called.",
    '11:30': "Gentile mercy came through Jewish unbelief, which leaves no room for Gentile superiority.",
    '11:31': "The mercy travels both directions, and each group receives it by way of the other's failure.",
    '11:32': "All shut up in unbelief so that mercy could be shown to all. The imprisonment exists for the pardon.",
    '11:33': "The response to the doctrine of election is not a system but a shout. \"Past finding out\" is the conclusion.",
    '11:34': "Nobody has been God's counsellor, which is why nobody is in a position to audit his decisions.",
    '11:35': "Giving God something first would make grace a repayment. The question is rhetorical because the answer is nobody.",
    '11:36': "\"Of him, and through him, and to him\" — source, means and end all named, and none of them is us.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:1': "\"By the mercies of God\" — eleven chapters of gift come before the first real imperative.",
    '12:2': "The renewing is done to the mind, not by it, and proving God's will follows the renewal rather than producing it.",
    '12:3': "Sober thinking about oneself is possible because the measure is dealt out by God and not self-assessed.",
    '12:4': "Different offices in one body is stated as ordinary anatomy, not as a problem to be managed.",
    '12:5': "\"Members one of another\" goes further than belonging to Christ: they belong to each other as well.",
    '12:6': "Gifts differ according to grace given. Nobody chose his own and nobody earned it.",
    '12:8': "Manner is commanded alongside function — mercy with cheerfulness, giving with simplicity. How is part of what.",
    '12:9': "Love without dissimulation means love that is not performed, and the very next words are about hating something.",
    '12:10': "\"In honour preferring one another\" — the competition is inverted rather than abolished.",
    '12:11': "Diligence in business sits between fervency and serving the Lord. Ordinary work is placed inside worship.",
    '12:12': "Three verbs for three conditions, and the tribulation is assumed rather than prayed away.",
    '12:13': "Hospitality is not a temperament here but a practice to be pursued.",
    '12:14': "\"Bless, and curse not\" — the repetition closes the loophole of blessing publicly and cursing privately.",
    '12:15': "Weeping with the weeping is harder than helping them, and it is the one commanded here.",
    '12:16': "Condescending to men of low estate is named as the cure for being wise in one's own conceits.",
    '12:17': "Providing things honest \"in the sight of all men\" makes reputation a matter of the neighbour's confidence, not one's own.",
    '12:18': "\"If it be possible, as much as lieth in you\" — peace is commanded with an honest admission that it takes two.",
    '12:19': "Giving place to wrath is not passivity. It is handing the case to a court that will actually hear it.",
    '12:20': "Feeding the enemy is the concrete form of not avenging. The command is about bread, not feelings.",
    '12:21': "Evil is not merely resisted but overcome, and the only weapon named for it is good.",

    # ---- Chapter 13 ----
    '13:1': "The authority of rulers is derived, which both establishes them and puts a ceiling over them.",
    '13:2': "Resisting the ordinance is distinguished from disliking the ruler. Paul is speaking about the office.",
    '13:3': "The description assumes rulers who punish evil — the case Paul makes is about what government is for.",
    '13:4': "The magistrate is twice called God's minister, including when he bears the sword. The office is a calling, not a concession.",
    '13:5': "Subjection for conscience' sake rather than fear of punishment moves obedience out of mere calculation.",
    '13:6': "Tax collectors are described as attending continually on God's business. Paul is not being ironic.",
    '13:7': "Dues are itemised — tribute, custom, fear, honour — which makes vague goodwill no substitute for paying.",
    '13:8': "The one debt that is never discharged is love, and carrying it is said to fulfil the law.",
    '13:9': "The commandments are not abolished but gathered. Love is their summary, not their replacement.",
    '13:10': "\"Love worketh no ill\" — the test is negative and therefore checkable by the neighbour.",
    '13:11': "The argument for waking is the clock: salvation is nearer now than at the moment of first believing.",
    '13:12': "Casting off and putting on are both required. Nobody stands between the two garments.",
    '13:13': "The vices listed are the night's works, and strife and envy sit alongside drunkenness without apology.",
    '13:14': "\"Put ye on the Lord Jesus Christ\" — the flesh is starved of provision rather than fought head-on.",
})

TAKEAWAYS.update({
    # ---- Chapter 14 ----
    '14:1': "The weak are to be received, not debated into strength. Argument is ruled out before it begins.",
    '14:2': "Paul names who is weak and does not pretend both positions are equally informed — and still protects the weaker one.",
    '14:3': "Two temptations, one for each side: the free despise, the scrupulous judge. Both are answered by \"God hath received him.\"",
    '14:4': "\"Another man's servant\" — judging a fellow Christian means reaching into someone else's household.",
    '14:5': "On a genuinely open question, being fully persuaded in one's own mind is the standard, not conforming to the neighbour.",
    '14:6': "Both the man who keeps the day and the man who does not are described as giving thanks. The motive is the same.",
    '14:7': "\"None of us liveth to himself\" — privacy in these matters is not available, because the audience is the Lord.",
    '14:8': "Living and dying are both accounted for by the same three words: we are the Lord's.",
    '14:9': "Christ's lordship over the dead and the living was the purpose of the dying and rising, not a consequence of it.",
    '14:10': "The brother you are judging and you are standing in the same queue before the same seat.",
    '14:11': "Every knee bowing is quoted here to end an argument about diet. The scale of the correction is deliberate.",
    '14:12': "\"Of himself\" — the account to be given will not include the brother whose conduct you had catalogued.",
    '14:13': "Judging is not abolished but redirected: judge your own effect on a brother rather than his position.",
    '14:14': "Paul agrees with the strong on the facts and then sides with the weak on the conduct.",
    '14:15': "\"For whom Christ died\" is the measure of what is being risked over a meal.",
    '14:16': "A real liberty can be exercised in a way that gets it spoken of as evil. Being right is not the whole duty.",
    '14:17': "The kingdom is defined by what it is not, first: not meat and drink, which is exactly what the quarrel was about.",
    '14:18': "Serving Christ in these things is said to be approved of men too — the watching world notices how believers treat each other.",
    '14:19': "Peace and edification are things to be pursued, which assumes they do not happen by themselves.",
    '14:20': "\"All things indeed are pure\" is conceded in the same breath that limits their use. The purity was never in question.",
    '14:21': "The strong are asked to give up something lawful. That is the whole cost, and it is real.",
    '14:22': "\"Have it to thyself before God\" — a conviction can be true and still not need an audience.",
    '14:23': "\"Whatsoever is not of faith is sin\" — an act correct in itself is condemned when the doer has no confidence before God in it.",

    # ---- Chapter 15 ----
    '15:1': "The strong are given the obligation, not the privilege. Strength exists to carry someone.",
    '15:2': "Pleasing the neighbour is limited by two words — \"for his good\" — which rules out flattery.",
    '15:3': "The example given is not Christ's power but his refusal to please himself under insult.",
    '15:4': "The old scriptures were written with later readers in view, and the stated aim of reading them is hope.",
    '15:5': "Likemindedness is asked of God rather than organised, and it is according to Christ Jesus, not to agreement.",
    '15:6': "One mind and one mouth, and the purpose is not harmony for its own sake but the glory of God.",
    '15:7': "The standard for receiving one another is how Christ received us, which sets the bar at people who were not qualified.",
    '15:8': "Christ's ministry to the circumcision is described as God keeping his word to the fathers, not as favouritism.",
    '15:9': "Jews receive truth and Gentiles receive mercy, and both end in the same praise.",
    '15:12': "The root of Jesse is where Gentile hope is placed — grafted in, as chapter eleven said, and not a separate promise.",
    '15:13': "Joy and peace come \"in believing,\" and the abounding hope is credited to the Spirit's power rather than to temperament.",
    '15:14': "Before correcting them further he says what he actually thinks of them, and it is generous.",
    '15:15': "He accounts for his own boldness by the grace given him, not by his rank.",
    '15:16': "Paul uses priestly language for preaching: the Gentiles themselves are the offering he brings up.",
    '15:17': "Glorying is allowed only \"through Jesus Christ\" and only in the things pertaining to God.",
    '15:18': "He will speak only of what Christ wrought by him, which leaves his own contribution unreportable.",
    '15:19': "A finished work is claimed over a whole region, which tells you what Paul counted as fully preaching.",
    '15:20': "Not building on another man's foundation was a strategy, not a criticism of the other builders.",
    '15:21': "The text he works by is about people who had not heard, which is why he keeps moving outward.",
    '15:23': "\"No more place in these parts\" — he leaves a region not when it is Christian but when the gospel has been planted there.",
    '15:24': "He expects to be helped on his way by them, so the visit is not one-directional charity.",
    '15:25': "The apostle of justification by faith delays a mission trip to carry money to poor Christians.",
    '15:26': "The collection is described as something that pleased the givers, not as an assessment laid on them.",
    '15:27': "Gentiles owe a debt for spiritual things and pay it in carnal ones. Money is treated as the natural return for the gospel.",
    '15:29': "He is certain of the blessing he will bring and uncertain of nearly everything else about the journey.",
    '15:30': "\"Strive together with me in your prayers\" — prayer is described as labour undertaken alongside him.",
    '15:31': "The requests are specific and unheroic: deliverance from enemies, and that the gift would be accepted.",
    '15:32': "Even the hoped-for joy is put under \"the will of God,\" and the refreshment expected is mutual.",
    '15:33': "\"The God of peace\" is named at the end of a letter that has argued its way through a great deal of division.",
})

TAKEAWAYS.update({
    # ---- Chapter 16 ----
    '16:1': "The letter that defines justification was carried to Rome by a woman, and Paul names her first.",
    '16:2': "Phebe is to be assisted because she has assisted many, Paul included. The debt runs from the apostle to her.",
    '16:3': "Priscilla is named before Aquila, and both are called Paul's fellow workers rather than his supporters.",
    '16:4': "\"Laid down their own necks\" — a risk taken years earlier, still being repaid in thanks by whole churches.",
    '16:5': "A church meets in a house, and the first convert of a whole province is greeted by name like anyone else.",
    '16:6': "Mary is remembered for one thing: much labour. That was enough to get her into the letter.",
    '16:7': "Fellow prisoners, of note among the apostles, and in Christ before Paul was. He is not the senior figure here.",
    '16:12': "Three women are named as labourers in the Lord, and the work, not the relationship, is what is recorded.",
    '16:13': "\"His mother and mine\" — a woman who mothered Paul somewhere along the way, and he says so in passing.",
    '16:16': "The greeting is to be passed between them, which turns a list of names into something the whole room does.",
    '16:17': "Those who cause division are identified by their departure from the doctrine, not by their manner.",
    '16:18': "\"By good words and fair speeches\" — the danger is described as attractive, which is what makes the warning necessary.",
    '16:19': "Wise about good and simple about evil inverts the usual worldliness, which is expert in evil and naive about good.",
    '16:20': "\"The God of peace shall bruise Satan\" — the crushing is God's act, and it happens under their feet.",
    '16:22': "The scribe signs his own name in the middle of Paul's letter, and nobody edited it out.",
    '16:23': "A city treasurer and a man called simply \"a brother\" send greetings in the same sentence.",
    '16:25': "The power to establish is God's, and the means named is the gospel — the same one the letter has been preaching.",
    '16:26': "The mystery kept secret is now made known to all nations \"for the obedience of faith,\" which is where the letter began.",
    '16:27': "Sixteen chapters of argument end not in a conclusion but in glory given to God through Jesus Christ.",
})
