#!/usr/bin/env python3
"""Written one-line takeaways for 1 Thessalonians."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "No apostolic title is claimed and no problem is named. The address itself tells you what kind of letter this is.",
    '1:3': "Faith, love and hope are each given a hard noun: work, labour, patience. None of the three is left as a feeling.",
    '1:4': "Their election is something he can see, and what he sees is verse 3 — not a private certainty they reported.",
    '1:5': "\"Not in word only.\" The preaching came with power, and with preachers whose conduct they could check.",
    '1:6': "Affliction and joy arrived in the same package, and the joy is credited to the Holy Ghost rather than to temperament.",
    '1:7': "A church months old is already the pattern for older ones. Maturity and seniority are not the same thing.",
    '1:8': "\"We need not to speak any thing.\" Their reputation had done the work of his next missionary sermon.",
    '1:9': "Conversion is described as turning from idols to serve — a change of master, not merely of belief.",
    '1:10': "Waiting is listed as an activity alongside serving, and what is waited for is the one who already delivered them.",

    # ---- Chapter 2 ----
    '2:1': "He appeals to what they themselves saw. The defence of his ministry rests on their memory, not his claims.",
    '2:2': "Fresh from being shamefully treated at Philippi, he began again at Thessalonica. The beating did not change the practice.",
    '2:3': "Three charges answered before they are made: deceit, impurity, trickery — the standard suspicions of a travelling teacher.",
    '2:4': "Trying to please men and being tried by God are set as alternatives. A preacher cannot serve both audiences.",
    '2:5': "Flattery and a cloak of covetousness are named as the two ways money corrupts speech.",
    '2:6': "He had the right to be a burden and did not use it. A right waived is still a right.",
    '2:7': "\"As a nurse cherisheth her children\" — an apostle's chosen image for himself is a woman feeding infants.",
    '2:8': "The gospel and his own soul were handed over together. He could not give the message without giving himself.",
    '2:9': "Night and day at a trade so that no one would be charged for the preaching. Ordinary work paid for the ministry.",
    '2:10': "He calls both the congregation and God as witnesses to his conduct. Either could contradict him.",
    '2:11': "Having called himself a nurse, he now calls himself a father, and the fatherly part is exhorting each one by name.",
    '2:12': "The call came first, to kingdom and glory; walking worthy is the response to it, not the entrance fee.",
    '2:13': "They received it as the word of God, and it is that word — not their reception of it — that \"effectually worketh\" in them.",
    '2:14': "Suffering at the hands of their own countrymen is what made them like the churches in Judaea.",
    '2:15': "The sharpest words in the letter are aimed at his own people, and the charge is contrariness to all men.",
    '2:16': "Forbidding the Gentiles to hear is the sin that fills the cup. Blocking the message is treated as the climax.",
    '2:17': "\"In presence, not in heart.\" Absence is described as bereavement rather than as distance.",
    '2:18': "He names Satan as the one who stopped the trip, and still does not claim to know why.",
    '2:19': "The crown he expects to hold at Christ's coming is these people. Nothing else is listed.",

    # ---- Chapter 3 ----
    '3:1': "He gave up his only companion and stayed at Athens alone. The cost of sending Timothy was borne by Paul.",
    '3:2': "Timothy is sent not to inspect them but to strengthen and comfort them about the very thing they were suffering.",
    '3:3': "\"We are appointed thereunto.\" Affliction is not the sign that something went wrong with the plan.",
    '3:4': "He had told them in advance, so the suffering when it came was evidence he had been honest.",
    '3:5': "The fear is not that they would suffer but that the tempter would use the suffering.",
    '3:6': "Timothy's report is of faith and love and of their longing to see him — not of doctrinal soundness.",
    '3:7': "News of their faith comforted him in his own distress. Encouragement ran upward, from the young church to the apostle.",
    '3:8': "\"Now we live, if ye stand fast.\" His own well-being is frankly tied to how they are doing.",
    '3:10': "He prays to \"perfect that which is lacking in your faith\" — the church he has just praised is not finished.",
    '3:11': "The travel plans are handed back to God, right after Satan was said to have blocked them.",
    '3:12': "Love toward one another and toward all men are asked for in one breath, without ranking.",
    '3:13': "Hearts established unblameable is God's work here, not theirs, and it is aimed at a day, not at a standard.",

    # ---- Chapter 4 ----
    '4:1': "They are already walking as taught; the request is that they \"abound more and more\" in what they are doing well.",
    '4:3': "\"This is the will of God, even your sanctification\" — the will so many hunt for is stated plainly and is about conduct.",
    '4:4': "Possessing one's own vessel in honour treats the body as something to be governed, not merely restrained.",
    '4:5': "The contrast is with those \"which know not God.\" Sexual conduct is presented as a knowledge question.",
    '4:6': "Sexual sin is described as defrauding a brother. There is a second party with a claim, always.",
    '4:7': "The call was not to uncleanness. What God called them to is the standard he holds them to.",
    '4:8': "Rejecting the teaching is rejecting God, not the messenger — and the Spirit given to them is named as the reason.",
    '4:9': "He excuses himself from writing about brotherly love because God has already taught them it.",
    '4:10': "Even the thing they do well gets \"increase more and more.\" Nothing in this letter is treated as finished.",
    '4:11': "\"Study to be quiet, and to do your own business, and to work with your own hands\" — an ambition aimed downward.",
    '4:12': "Two reasons for honest work: how outsiders see the church, and not being dependent on anyone.",
    '4:13': "Christians are not told not to grieve, only not to grieve like those with no hope.",
    '4:14': "The argument runs from Jesus' resurrection to theirs. If the first happened, the second follows.",
    '4:15': "The anxiety answered is that the dead would miss the coming. The living get no head start.",
    '4:16': "Shout, archangel's voice, trump of God — nothing about this descent is quiet or private.",
    '4:17': "\"So shall we ever be with the Lord.\" The point of the passage is the company, not the transport.",
    '4:18': "The doctrine is given for a use: comforting each other. It was never meant as a timetable to argue over.",

    # ---- Chapter 5 ----
    '5:1': "On times and seasons he says they need nothing written. The question people most want answered is the one he drops.",
    '5:2': "A thief in the night is an image about unpredictability, not about stealth toward the church.",
    '5:3': "\"Peace and safety\" is the last thing said before the collapse. Confidence is named as the warning sign.",
    '5:4': "The day will come suddenly for everyone; it will only surprise those in the dark.",
    '5:5': "Children of light is stated as what they are, not as what they should become.",
    '5:6': "Watching and sobriety are the readiness asked for — not calculation, and not alarm.",
    '5:7': "Sleep and drunkenness belong to night. He is describing which world a life belongs to, not setting a curfew.",
    '5:8': "The armour here is faith, love and hope. The soldier is equipped with the things of chapter 1, verse 3.",
    '5:9': "\"God hath not appointed us to wrath.\" The end of the matter is an appointment already made, not an outcome in doubt.",
    '5:10': "Whether we wake or sleep — living or dead, the phrase covers both, and neither changes the outcome.",
    '5:11': "A second command to comfort one another, with \"even as also ye do\" attached. He asks for more of what exists.",
    '5:12': "Knowing those who labour among you is asked for before esteeming them. Recognition precedes respect.",
    '5:13': "They are esteemed \"for their work's sake,\" not for their personalities, and the sentence ends in peace among themselves.",
    '5:14': "Unruly, feebleminded, weak — each gets a different treatment. Uniform handling is not charity.",
    '5:15': "Repaying evil is forbidden not only inside the church but toward all men.",
    '5:16': "Three words, with no conditions attached and no circumstances excepted.",
    '5:17': "Prayer without ceasing describes a posture rather than an unbroken activity.",
    '5:18': "Thanks \"in every thing,\" not for every thing. The distinction is the difference between honesty and pretence.",
    '5:19': "The Spirit can be quenched, which means a congregation can put out what God has lit.",
    '5:20': "Prophecies were evidently being despised. The correction is to a church too suspicious, not too credulous.",
    '5:21': "Testing and holding fast are one instruction. Discernment exists in order to keep things, not to discard them.",
    '5:22': "The caution extends past what is evil to what looks like it. Appearance is treated as a real cost.",
    '5:23': "The sanctifying is asked of \"the very God of peace.\" The whole list of commands ends as a prayer.",
    '5:24': "\"Faithful is he that calleth you, who also will do it.\" The guarantee rests on the caller, not the called.",
    '5:27': "He puts the reading of the letter under oath, so that no one in the congregation is left out of it.",
}
