#!/usr/bin/env python3
"""Written one-line takeaways for 1 Timothy."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"By the commandment of God\" — the apostleship is an order received, and Christ is called our hope in the same breath.",
    '1:3': "Timothy's assignment at Ephesus is stated first as a restraint: stop certain men teaching.",
    '1:4': "Fables and genealogies \"minister questions\" — the test applied is whether the teaching builds anything.",
    '1:5': "The end of the commandment is love. Everything corrective in this letter is aimed at that, not at tidiness.",
    '1:6': "\"Vain jangling\" is what is left when men swerve from love; the noise is the symptom, not the disease.",
    '1:7': "They wanted to be teachers of the law and understood neither their words nor their assertions.",
    '1:8': "The law is good \"if a man use it lawfully\" — the fault lies in the handling, never in the law itself.",
    '1:9': "The law is not made for a righteous man. Its work is to expose and restrain, not to improve the already upright.",
    '1:10': "\"Menstealers\" sits in the middle of the list, which puts the slave trade under the same condemnation as perjury.",
    '1:11': "The measure of sound doctrine is the gospel, and Paul calls that gospel a trust he was handed.",
    '1:12': "He was counted faithful before he had proved faithful, and the enabling came with the appointment.",
    '1:13': "Blasphemer, persecutor, injurious — the résumé is given in full before the word mercy.",
    '1:14': "Grace is \"exceeding abundant,\" and the faith and love it brought are located in Christ, not in Paul.",
    '1:15': "\"Of whom I am chief.\" Present tense, decades in. His standing before God never came from a better estimate of himself.",
    '1:16': "He is the exhibit: if the longsuffering stretched to him, no later case can be argued as too hard.",
    '1:17': "The doxology breaks out mid-argument, right after the sentence about being chief of sinners.",
    '1:18': "The charge is tied to prophecies spoken over him. Timothy is to fight with something already said about him.",
    '1:19': "Faith and a good conscience travel together, and it is the conscience put away that wrecks the faith.",
    '1:20': "Two men named in a public letter, and the stated aim of the discipline is that they learn — not that they be finished with.",

    # ---- Chapter 2 ----
    '2:1': "\"First of all\" — prayer for all men is placed ahead of everything else the letter will order.",
    '2:2': "Prayer for rulers is asked for a modest end: a quiet life. Not revival, not deliverance, not victory.",
    '2:4': "God \"will have all men to be saved.\" The desire is stated without qualification before any doctrine of election is drawn.",
    '2:5': "One mediator, and he is named as \"the man Christ Jesus.\" The humanity is the qualification.",
    '2:6': "The ransom was self-given. No one collected it from him.",
    '2:7': "He interrupts himself to swear he is telling the truth about being sent to Gentiles — it was still contested.",
    '2:8': "Holy hands lifted \"without wrath and doubting\" — the obstacle to prayer named here is anger at other people.",
    '2:9': "Expensive dress is treated as a congregational problem, because it advertises rank inside a room meant to have none.",
    '2:10': "Good works are named as what actually adorns. The alternative to display is not plainness but usefulness.",
    '2:11': "\"Let the woman learn\" — the instruction assumes she is being taught, which was not assumed everywhere.",
    '2:12': "The restriction is stated as Paul's own ruling, and it joins teaching to authority rather than to speech as such.",
    '2:13': "The argument is grounded in the creation order rather than in local custom or capacity.",
    '2:14': "Adam was not deceived, which does not acquit him; it makes his sin the more deliberate of the two.",
    '2:15': "A hard verse. Whatever it settles, it rests her safety on faith, charity and holiness, not on childbearing alone.",

    # ---- Chapter 3 ----
    '3:1': "Wanting the office is not treated as ambition to be suspected. It is desiring \"a good work.\"",
    '3:2': "Almost everything listed is character, not ability; \"apt to teach\" is the single skill named.",
    '3:3': "Wine, violence, money, quarrelling. The disqualifications are the ordinary ones, not the exotic ones.",
    '3:4': "The household is the evidence, and what is looked for there is ruling well, not children who never fail.",
    '3:5': "The parenthesis makes the logic explicit: the church is a house, and the smaller house is the proving ground.",
    '3:6': "The risk in promoting a novice is named as pride, and the condemnation it invites is the devil's own.",
    '3:7': "A good report from outsiders is required. The opinion of people who do not share the faith still counts.",
    '3:8': "\"Not doubletongued\" — the deacon moves between households, where saying different things in different rooms is easy.",
    '3:9': "The mystery of the faith is held \"in a pure conscience.\" Doctrine is kept in a moral container, not a mental one.",
    '3:10': "Proving comes before office. The congregation is expected to have watched a man before it appoints him.",
    '3:11': "\"Not slanderers\" appears in the women's list where \"not doubletongued\" appeared in the men's. The same fault, named twice.",
    '3:12': "The same household test is applied to deacons. No one is exempted from it by holding the lesser office.",
    '3:13': "Serving well purchases \"great boldness in the faith\" — the reward described is confidence, not promotion.",
    '3:15': "The church is called the pillar and ground of the truth: it holds the truth up, it does not manufacture it.",
    '3:16': "A hymn quoted mid-letter, and the whole of it is about what happened to Christ, not about what godliness requires.",

    # ---- Chapter 4 ----
    '4:1': "The departures are predicted, which means their occurrence is not evidence that the faith has failed.",
    '4:2': "A conscience can be cauterised. The liars here have stopped feeling what they are doing.",
    '4:3': "The false teaching forbids marriage and food — it is ascetic, not licentious. Error can look like seriousness.",
    '4:4': "\"Nothing to be refused.\" The creation is good, and thanksgiving is what makes the use of it honest.",
    '4:5': "Sanctified by the word of God and prayer: grace at a meal is doing something, not decorating it.",
    '4:6': "A good minister is defined as one who reminds people of things they already know.",
    '4:7': "Godliness takes exercise, which is a word about training rather than about resolve.",
    '4:8': "Bodily exercise is not dismissed, only measured. Godliness has promise for both lives, which is the comparison being made.",
    '4:10': "God is called \"the Saviour of all men, specially of those that believe\" — a sentence that refuses to narrow too quickly.",
    '4:12': "The answer to being young is not authority but example, and the list is all conduct.",
    '4:13': "Reading, exhortation, doctrine — the public work of the ministry is described as attending to a text.",
    '4:14': "The gift can be neglected. Ordination did not make it self-maintaining.",
    '4:15': "\"That thy profiting may appear to all\" — a minister is expected to be visibly growing, not finished.",
    '4:16': "Doctrine and self are to be watched together, and Paul will not separate what a man teaches from what he is.",

    # ---- Chapter 5 ----
    '5:1': "An older man is not rebuked but entreated as a father. The manner of correction is regulated, not the correcting.",
    '5:3': "\"Widows that are widows indeed\" — the church's obligation is defined before it is commanded, so that it can be met.",
    '5:4': "Care for a widowed mother is put on her own family first, and that care is called piety and requital.",
    '5:5': "The widow with nothing is described by what she does with it: she trusts God and prays night and day.",
    '5:6': "\"Dead while she liveth.\" A life of pleasure is not called wicked here but vacant.",
    '5:8': "Failing to provide for one's own is called worse than unbelief. Ordinary household duty is treated as doctrine.",
    '5:9': "There was an actual list with actual criteria. Charity here is organised, not improvised.",
    '5:10': "The qualifications are all services rendered: children raised, strangers lodged, feet washed, afflicted relieved.",
    '5:11': "The younger widows are kept off the roll for a practical reason: a lifelong commitment made too early will break.",
    '5:13': "Idleness produces house-to-house talk. The remedy Paul reaches for is work, not a rule against gossip.",
    '5:14': "\"Give none occasion to the adversary.\" The concern is what a watching city will be able to say.",
    '5:15': "\"Some are already turned aside.\" The instruction is written after the damage, not before it.",
    '5:16': "Families relieving their own frees the church to relieve those with no one. Limits exist so that help reaches further.",
    '5:17': "Double honour for elders who rule well — and the context of wages in the next verse says the honour includes pay.",
    '5:18': "A line from Deuteronomy and a saying of Jesus are quoted together as \"the scripture.\"",
    '5:19': "An elder is protected from single-witness accusation, which protects the office from being destroyed by rumour.",
    '5:20': "The elder who does sin is rebuked publicly. The same verses that shield the office refuse to hide it.",
    '5:21': "The charge against partiality is sworn before God and the elect angels — a striking weight for a matter of fairness.",
    '5:22': "\"Lay hands suddenly on no man.\" Hasty ordination is said to make the ordainer complicit in what follows.",
    '5:23': "A prescription for a stomach, dropped into a letter about church order. Timothy's health mattered to Paul.",
    '5:24': "Some sins arrive at judgment ahead of the man, some trail behind him. Either way the assessment is not left to us.",
    '5:25': "Good works that are hidden \"cannot be hid\" forever. The same delay that covers sin also covers goodness.",

    # ---- Chapter 6 ----
    '6:1': "The reason given to slaves is the reputation of God's name, not their own advantage.",
    '6:2': "A believing master is not a reason to serve less. Brotherhood is treated as a claim, not as leverage.",
    '6:3': "Sound teaching is measured against \"the words of our Lord Jesus Christ\" and against godliness, together.",
    '6:4': "\"Doting about questions and strifes of words.\" He diagnoses a love of controversy as a sickness, and names pride as its root.",
    '6:5': "\"Supposing that gain is godliness\" — the false teachers had discovered religion pays, which is why money follows.",
    '6:6': "The phrase is turned around: godliness with contentment is the gain. The word they misused is taken back.",
    '6:7': "Nothing in, nothing out. The argument against greed is not moral but arithmetical.",
    '6:8': "Food and covering. The floor for contentment is set remarkably low and stated without apology.",
    '6:9': "The danger is attached to \"they that will be rich\" — the wanting, not the having.",
    '6:10': "\"The love of money is the root of all evil\" — of evil, not of money, and the wound described is self-inflicted.",
    '6:11': "\"Flee these things\" is followed by something to run toward. Avoidance alone is not the instruction.",
    '6:12': "Laying hold on eternal life, having been called to it. The fight is to keep what was given, not to win it.",
    '6:13': "Christ's confession before Pilate is the model: a good profession is one made where it costs something.",
    '6:14': "The commandment is to be kept \"until the appearing\" — the charge has an end date, and it is not retirement.",
    '6:15': "\"King of kings, and Lord of lords\" is said in a letter written under an emperor who claimed similar titles.",
    '6:16': "God alone has immortality; every other life is on loan. And no man has seen him, nor can.",
    '6:17': "The rich are not told to stop being rich but to stop trusting what is uncertain — and God is said to give things to enjoy.",
    '6:18': "\"Ready to distribute, willing to communicate\" — the wealth is redirected rather than renounced.",
    '6:19': "Generosity is described as laying a foundation for the future, which turns giving into the safer investment.",
    '6:20': "\"Keep that which is committed to thy trust.\" The last word is custody, not innovation.",
}
