#!/usr/bin/env python3
"""Written one-line takeaways for 2 Timothy."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"The promise of life\" — an apostle awaiting execution defines his commission by what is promised, not by what is ending.",
    '1:2': "\"My dearly beloved son.\" The last letter opens by naming the relationship rather than the office.",
    '1:3': "He thanks a God he has served \"from my forefathers.\" There is no break claimed between the old worship and the new.",
    '1:4': "Timothy's tears are remembered, and Paul says seeing him again would fill his joy. The need is admitted.",
    '1:5': "The faith is traced through a grandmother and a mother. Timothy received it from women, at home.",
    '1:6': "The gift needs stirring up, like a fire banked low. It was given once and can go quiet.",
    '1:7': "Fear is named as a spirit not given — which means its presence is not evidence of failure to try harder.",
    '1:8': "\"Nor of me his prisoner.\" Paul knows association with him is now a liability and asks Timothy to accept it.",
    '1:9': "Saved and called \"not according to our works, but according to his own purpose and grace\" — given before the world began.",
    '1:10': "Death is not survived but abolished, and life is brought to light by a gospel rather than discovered by inquiry.",
    '1:11': "Preacher, apostle, teacher — three words for the one job, and each of them got him into this cell.",
    '1:12': "\"I know whom I have believed.\" Not what. His confidence rests on a person's competence to keep what was handed over.",
    '1:13': "\"The form of sound words\" — there is a shape to the teaching, and Timothy's task is to hold it, not improve it.",
    '1:14': "The deposit is kept \"by the Holy Ghost.\" Even guarding the truth is not left to the guard's own strength.",
    '1:15': "\"All they which are in Asia be turned away from me.\" The field he planted has emptied, and he writes it down plainly.",
    '1:16': "Onesiphorus \"was not ashamed of my chain\" — in a letter where shame is the recurring word, one man's name stands against it.",
    '1:17': "He searched Rome until he found the prisoner. Loyalty here is a matter of legwork, not sentiment.",
    '1:18': "Paul can only pray for the man who helped him. There is no repaying it from a cell.",

    # ---- Chapter 2 ----
    '2:1': "Strength is commanded, and the place it is found is named: grace, not resolve.",
    '2:2': "Four generations in one sentence — Paul, Timothy, faithful men, others. The chain is the plan for the church's survival.",
    '2:3': "Hardness is what a soldier endures, not what he complains of. The image sets expectations rather than raising morale.",
    '2:4': "Entanglement, not ordinary life, is the problem; the soldier's freedom is for the sake of pleasing the one who enlisted him.",
    '2:5': "The athlete who breaks the rules is not crowned, however well he ran. Zeal does not excuse method.",
    '2:6': "The farmer eats first from his own crop. Ministry is expected to feed the minister.",
    '2:7': "Consider, and the Lord give understanding. Hard thinking and granted light stand side by side, not as rivals.",
    '2:8': "The whole gospel is compressed to two facts: descended from David, raised from the dead.",
    '2:9': "\"The word of God is not bound.\" The chain on Paul's wrist stops the man and not the message.",
    '2:10': "He endures \"for the elect's sakes\" — election does not make his suffering unnecessary, it gives it a purpose.",
    '2:11': "Dying with him is spoken of as already done, and the living with him follows from it.",
    '2:12': "Enduring and denying are set opposite each other, and the consequence of denial is stated without softening.",
    '2:13': "\"If we believe not, yet he abideth faithful.\" His faithfulness is grounded in his own nature, not in our response.",
    '2:14': "Word-fights are judged by their effect on listeners: no profit, and the hearers are subverted.",
    '2:15': "\"Rightly dividing the word of truth\" — the workman's shame or approval turns on how he handles the text.",
    '2:16': "Empty talk is said to \"increase unto more ungodliness.\" It does not stay harmless where it started.",
    '2:17': "The image is gangrene: error spreads through a body rather than sitting where it is placed.",
    '2:18': "Their error was a doctrine of over-realised hope — the resurrection already past — and it overthrew faith.",
    '2:19': "Two seals on one foundation: God knows his own, and those who name him leave iniquity. Assurance and holiness together.",
    '2:20': "In a great house some vessels are common. He is explaining why the church contains what it contains.",
    '2:21': "The purging is from \"these\" — from the corrupting company just described, not from ordinary usefulness.",
    '2:22': "Fleeing youthful lusts is paired with pursuing peace among those who call on the Lord. The escape runs through company.",
    '2:23': "The reason for avoiding foolish questions is not that they are beneath him but that they breed fights.",
    '2:24': "\"The servant of the Lord must not strive.\" Where the truth is at stake, the manner is still regulated.",
    '2:25': "Repentance is something God may give, which is why opponents are met with meekness rather than pressure.",
    '2:26': "Those who oppose are described as captives, taken at another's will. The enemy is not the person arguing.",

    # ---- Chapter 3 ----
    '3:1': "\"Perilous times shall come.\" The warning is a forecast, not a diagnosis of one bad generation.",
    '3:2': "The list starts at self-love and moves outward. Everything after it is a consequence of the first item.",
    '3:3': "\"Without natural affection\" — the collapse reaches the family, where affection was supposed to be instinctive.",
    '3:4': "\"Lovers of pleasures more than lovers of God\" — the fault is not that they love nothing but that the ranking is wrong.",
    '3:5': "A form of godliness with the power denied. The whole catalogue describes people inside the religion, not outside it.",
    '3:6': "They \"creep into houses\" and target the burdened. Predatory teaching looks for people already carrying something.",
    '3:7': "\"Ever learning, and never able to come to the knowledge of the truth.\" Appetite for study is not the same as arriving.",
    '3:8': "Jannes and Jambres resisted Moses with imitations, and Paul says that is what this resistance is — counterfeit, not argument.",
    '3:9': "\"They shall proceed no further.\" Folly eventually exposes itself; Paul does not assume the church must unmask it.",
    '3:10': "Doctrine heads the list and manner of life comes second. Timothy had watched both, at close range.",
    '3:11': "Three towns named where Paul was nearly killed — and \"out of them all the Lord delivered me\" is said by a man about to die.",
    '3:12': "Persecution is promised to \"all that will live godly,\" which removes it from the category of exceptional misfortune.",
    '3:13': "\"Deceiving, and being deceived.\" The deceivers are not standing outside their own lie.",
    '3:14': "Continuing rests partly on knowing \"of whom thou hast learned them.\" Trust in teachers is treated as a legitimate support.",
    '3:15': "The scriptures make wise unto salvation \"through faith which is in Christ Jesus\" — they point, they do not substitute.",
    '3:16': "\"All scripture\" — given by God, and its listed uses are mostly uncomfortable: reproof, correction, instruction.",
    '3:17': "The aim of the furnishing is good works, not accumulated knowledge. Scripture equips a man for a job.",

    # ---- Chapter 4 ----
    '4:1': "The charge is laid \"before God\" and before the judge of the living and the dead. Preaching is placed under that court.",
    '4:2': "\"In season, out of season\" — the word is not held back for receptive moments, and longsuffering is attached to the rebuking.",
    '4:3': "\"Itching ears\" — the hearers assemble the teachers they want. Bad preaching is described as a demand before it is a supply.",
    '4:4': "Turning from truth and turning to fables is one motion. Nothing is left empty.",
    '4:5': "Four imperatives for a man losing his mentor: watch, endure, do the work, make full proof of the ministry.",
    '4:6': "\"Ready to be offered.\" He describes his execution in the language of a drink offering poured out.",
    '4:7': "Fought, finished, kept — three verbs in the past tense. Nothing in the summary is about what he achieved for himself.",
    '4:8': "The crown is \"laid up,\" given by a righteous judge, and explicitly not reserved for apostles: all who love his appearing.",
    '4:10': "\"Demas hath forsaken me, having loved this present world.\" A co-worker's name is recorded with the reason attached.",
    '4:11': "\"Only Luke is with me.\" And the man he once refused to travel with, Mark, is now called profitable.",
    '4:13': "A cloak, books, and especially the parchments. A man three verses from describing his death still wants something to read.",
    '4:14': "Alexander's harm is named, and the repayment is handed to the Lord rather than arranged by Paul.",
    '4:16': "\"All men forsook me: I pray God that it may not be laid to their charge.\" The abandonment is forgiven in the same sentence.",
    '4:17': "Deserted by everyone, he says the Lord stood with him — and the purpose given is that the Gentiles might hear.",
    '4:18': "The deliverance he now expects is not from death but through it, into the heavenly kingdom.",
    '4:20': "Trophimus is left behind sick. The apostle whose handkerchiefs once healed does not heal his own companion.",
    '4:22': "The last line moves from \"thy spirit\" to \"you\" — the private letter was always meant to be heard by a church.",
}
