#!/usr/bin/env python3
"""Written takeaways for Amos."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "A herdman of Tekoa, dated two years before the earthquake. The prophecy is pinned to a tremor everyone would remember.",
    '1:2': "The LORD roars from Zion and the shepherds' pastures wither. A herdman hears judgement in the vocabulary of his own trade.",
    '1:3': "\"For three transgressions, and for four\" — the formula means the count has run past bearing. Damascus threshed Gilead with iron.",
    '1:4': "Fire into the house of Hazael. What burns is the dynasty that ordered the cruelty, not only the soldiers who did it.",
    '1:5': "Syria goes into captivity unto Kir — the very place Amos later says God brought them from. The journey is simply undone.",
    '1:6': "Gaza's charge is trafficking: carrying off a whole population to sell on to Edom. Nothing is said about what they believed.",
    '1:8': "Ashdod, Ashkelon, Ekron named one by one. The sentence is itemised so that no city can hear it as someone else's.",
    '1:9': "Tyre did what Gaza did and \"remembered not the brotherly covenant.\" A treaty broken is weighed alongside the slave trade.",
    '1:11': "Edom kept his wrath for ever. What is charged is not the outburst but the refusal ever to set the anger down.",
    '1:12': "Fire on Teman and Bozrah — the strongholds that made a permanent grudge feel affordable.",
    '1:13': "Ammon ripped up the women with child \"that they might enlarge their border.\" Atrocity is charged here as a land policy.",
    '1:14': "Shouting in the day of battle, a tempest in the whirlwind. The nation that annexed by terror is answered with noise.",
    '1:15': "The king goes into captivity with his princes. Those who ordered the expansion travel out together with it.",

    # ---- Chapter 2 ----
    '2:1': "Moab's crime is against a corpse, and the corpse is Edom's king. God prosecutes an outrage no Israelite had any stake in.",
    '2:2': "Moab dies with tumult, shouting and trumpet. A nation that treated the dead with contempt is buried loudly.",
    '2:4': "Judah's charge is not atrocity but despising the law of the LORD. Where more has been given, the indictment changes shape.",
    '2:5': "Fire upon Judah, devouring the palaces of Jerusalem. The formula used on the pagans is turned on the city of the temple.",
    '2:6': "The eighth round lands on the audience that approved the other seven. \"The poor for a pair of shoes\" — a man had a price.",
    '2:7': "Panting after the dust of the earth on the head of the poor. The greed described is appetite for the last thing he has.",
    '2:8': "They lie down on garments taken in pledge, beside the altar. The worship is furnished by the law-breaking it should have named.",
    '2:9': "The Amorite was cut down root and branch before them. What Israel inherited was given, which is why it can be taken.",
    '2:10': "Egypt, forty years, the land — the whole history recited as a list of things done for them, not by them.",
    '2:11': "Prophets and Nazarites are counted among the gifts. God lists the people he raised up as blessings, not as burdens.",
    '2:12': "They gave the Nazarites wine and told the prophets to stop. The gifts were not refused but corrupted and then silenced.",
    '2:13': "\"I am pressed under you, as a cart is pressed that is full of sheaves.\" God describes himself as loaded past bearing.",
    '2:14': "Swift, strong and mighty all fail in one verse. Judgement is pictured as every advantage giving way at the same moment.",
    '2:16': "The courageous flee away naked. The oracle ends on bravery with nothing left to wear.",

    # ---- Chapter 3 ----
    '3:1': "\"The whole family which I brought up from the land of Egypt.\" The word against them is addressed by way of their rescue.",
    '3:2': "\"You only have I known... therefore I will punish you.\" Election is stated as the ground of judgement, not of exemption.",
    '3:3': "Can two walk together, except they be agreed? The argument opens where everybody already agrees, and then closes.",
    '3:4': "A lion does not roar without prey. Each image insists that effects have causes, and so this disaster has one.",
    '3:6': "\"Shall there be evil in a city, and the LORD hath not done it?\" Amos refuses to let calamity be assigned to nobody.",
    '3:7': "God does nothing without telling the prophets. Prophecy is disclosure beforehand rather than commentary afterwards.",
    '3:8': "\"The lion hath roared, who will not fear?\" Prophesying is described as involuntary, the way flinching is.",
    '3:9': "Ashdod and Egypt are summoned to the hills to watch. Israel's oppression is exhibited to pagans as the scandal it is.",
    '3:10': "\"They know not to do right\" — the capacity has gone, not only the will. Violence is stored in the palaces like treasure.",
    '3:11': "The palaces that housed the plunder are the palaces that get spoiled. The judgement follows the goods home.",
    '3:12': "Two legs and a piece of an ear — the shepherd's proof that the sheep died. That is what will be left of Samaria.",
    '3:14': "The horns of the altar fall, the place a fugitive grabbed for asylum. The last refuge is the thing cut off.",
    '3:15': "Winter house, summer house, houses of ivory. The indictment is itemised in real estate.",

    # ---- Chapter 4 ----
    '4:1': "\"Ye kine of Bashan\" — comfortable women addressed as well-fed cattle, and their drink order stands as the charge.",
    '4:2': "Taken away with hooks. The cattle image is carried through to the abattoir without any softening.",
    '4:4': "\"Come to Bethel, and transgress.\" The call to worship is issued in the liturgy's own cadence as a call to sin.",
    '4:5': "\"For this liketh you, O ye children of Israel.\" The offerings are exposed as things done because they are enjoyed.",
    '4:6': "Cleanness of teeth is famine, put as a grim joke. \"Yet have ye not returned unto me\" — the refrain starts here.",
    '4:7': "Rain on one city and not the next, three months from harvest. The selectiveness is the signal; random weather says nothing.",
    '4:8': "They wandered city to city for water and were not satisfied. The thirst was meant to be read, and they only drank.",
    '4:9': "Blasting, mildew, palmerworm on the gardens and vines. Each warning comes closer to home, and each one fails.",
    '4:10': "Pestilence after the manner of Egypt. The plagues once sent against their oppressors are now sent against them.",
    '4:11': "\"As a firebrand plucked out of the burning.\" Survival itself was the mercy, and it was read as a lucky escape.",
    '4:12': "\"Prepare to meet thy God, O Israel.\" After five unheeded warnings what remains is the meeting itself.",
    '4:13': "Mountains, wind, morning, darkness — and \"declareth unto man what is his thought.\" The God to be met knows the inside too.",

    # ---- Chapter 5 ----
    '5:1': "He announces it as a lamentation. The funeral song is sung over a nation that is still on its feet.",
    '5:2': "\"The virgin of Israel is fallen; she shall no more rise.\" The dirge is in the past tense before the fall has happened.",
    '5:3': "A thousand leaves a hundred; a hundred leaves ten. The loss is given as arithmetic, which is worse than adjectives.",
    '5:4': "\"Seek ye me, and ye shall live.\" In the middle of a funeral there is an offer, and the offer is a person.",
    '5:5': "Seek not Bethel, nor Gilgal, nor Beersheba. The shrines where they went looking are named as the wrong places to look.",
    '5:6': "Seeking the LORD and surviving the fire are one act. Life is not the wage of the seeking but its content.",
    '5:7': "Turning judgment to wormwood. The courts are still sitting, and what they hand down is bitter.",
    '5:8': "The seven stars and Orion, the shadow of death turned into morning. The God they are told to seek moves the sky.",
    '5:9': "He strengthens the spoiled against the strong. The one power that reliably reverses stands on the side with none.",
    '5:10': "\"They hate him that rebuketh in the gate.\" The man who says it out loud in public is the one they cannot forgive.",
    '5:11': "Hewn stone houses and pleasant vineyards, paid for in wheat taken off the poor. They will neither live nor drink in them.",
    '5:12': "Afflicting the just, taking a bribe, turning aside the poor in the gate. Every sin in the list is committed in a courtroom.",
    '5:13': "\"The prudent shall keep silence in that time.\" Amos observes the sensible silence without once joining it.",
    '5:14': "\"As ye have spoken\" — they were already claiming God was with them. He states the condition that claim would require.",
    '5:15': "\"It may be that the LORD God of hosts will be gracious.\" Reform is urged without being made a lever on God.",
    '5:17': "\"I will pass through thee.\" The Passover word is used, and this time Israel is on the wrong side of the doorpost.",
    '5:18': "They wanted the day of the LORD, assuming it would fall on somebody else. He tells them it is darkness and not light.",
    '5:19': "Lion, then bear, then a serpent inside the safety of the house. There is no version of that day in which running helps.",
    '5:21': "\"I hate, I despise your feast days.\" The offence is not that worship has stopped but that it is flourishing.",
    '5:22': "Burnt offerings, meat offerings, the fat peace offerings — everything the law commands, and none of it accepted.",
    '5:23': "The songs are called noise. Music offered to God is described as a thing he would like switched off.",
    '5:24': "\"Let judgment run down as waters\" — not a trickle released when convenient, but a stream nobody can shut.",
    '5:25': "The forty wilderness years are recalled as a time of few sacrifices, and God raises no complaint about it.",
    '5:26': "Moloch and Chiun carried along with the offerings. The idolatry travelled beside the worship instead of replacing it.",
    '5:27': "\"Captivity beyond Damascus.\" The direction is named and Assyria is not, so the threat stays a horizon rather than a headline.",

    # ---- Chapter 6 ----
    '6:1': "\"Woe to them that are at ease in Zion.\" The charge is against comfort, and it names Jerusalem alongside Samaria.",
    '6:2': "Go and look at Calneh, Hamath, Gath. He sends them on a tour of cities that also considered themselves secure.",
    '6:3': "Putting far away the evil day while drawing the seat of violence near. Denial and cruelty are named as one motion.",
    '6:4': "Beds of ivory, lambs out of the flock, calves out of the stall. The luxury is described precisely, item by item.",
    '6:6': "\"But they are not grieved for the affliction of Joseph.\" The whole catalogue turns on the one thing they did not feel.",
    '6:7': "Those who stretched themselves go captive with the first. Privilege keeps its place at the front of the line either way.",
    '6:8': "\"I abhor the excellency of Jacob.\" What God says he hates is the very thing they were proudest of.",
    '6:9': "Ten men in one house, and all ten die. The number is given so the scale can be understood household by household.",
    '6:10': "\"Hold thy tongue: for we may not make mention of the name of the LORD.\" The terror ends with people afraid to say it.",
    '6:12': "Horses do not run on rock and no one plows the sea. Perverted justice is set down as against nature, not merely against law.",
    '6:13': "\"Have we not taken to us horns by our own strength?\" They rejoice in a thing of nought and call it an achievement.",
    '6:14': "A nation raised up against them from Hemath to the river. The answer to self-made strength is somebody else's army.",

    # ---- Chapter 7 ----
    '7:1': "Grasshoppers formed after the king's mowings, on the second growth. The crown was fed first; the timing is the cruelty.",
    '7:2': "\"By whom shall Jacob arise? for he is small.\" Amos pleads Israel's weakness, having no merit to plead.",
    '7:3': "\"The LORD repented for this.\" The prophet's intercession is recorded as actually altering what happens.",
    '7:4': "Fire that devours the great deep. The second vision escalates from the crop to the foundations of the world.",
    '7:5': "The same prayer again, a word shorter. He asks only for a stop, not for a pardon, and is heard a second time.",
    '7:7': "A plumbline held against a wall that was built by a plumbline. The measure used is the one the wall itself claimed.",
    '7:8': "\"I will not again pass by them any more.\" After two reprieves, this is the vision that does not get argued down.",
    '7:9': "Sanctuaries and the house of Jeroboam fall in the same breath. Shrine and throne are treated as a single structure.",
    '7:10': "Amaziah reports him to the king for conspiracy. A priest's first move against a prophet is to make it a security matter.",
    '7:11': "He quotes Amos accurately enough, leaving out everything that made it a warning rather than a threat.",
    '7:12': "\"Go, flee thee away into the land of Judah, and there eat bread.\" Amaziah assumes the man prophesies for a living.",
    '7:13': "\"It is the king's chapel, and it is the king's court.\" The sanctuary is defended as royal property, which is the problem.",
    '7:14': "\"I was no prophet, neither was I a prophet's son.\" No guild and no salary, and that is precisely his answer.",
    '7:15': "\"The LORD took me as I followed the flock.\" The call came to a working man at work, and it is his only credential.",
    '7:17': "The sentence on Amaziah is domestic and exact: his wife, his children, his land. Silencing the word costs him his own house.",

    # ---- Chapter 8 ----
    '8:2': "Summer fruit and the end. The vision turns on a pun, and ripeness here means ready for judgement, not for harvest.",
    '8:3': "Temple songs become howlings, and the bodies are cast out in silence. Both the worship and the speech stop.",
    '8:4': "\"Ye that swallow up the needy.\" The verb makes the poor into food rather than into neighbours.",
    '8:5': "They keep the sabbath and resent it, waiting for the holy day to end so trade can restart. The observance is intact and hollow.",
    '8:6': "Buying the poor for silver and selling them the sweepings of the wheat. They cheat at both ends of the same trade.",
    '8:7': "\"I will never forget any of their works\" — sworn by the excellency of Jacob, the very pride that made the works possible.",
    '8:8': "The land trembles and heaves like the Nile. Creation is described as unable to hold still underneath this.",
    '8:9': "The sun going down at noon. The judgement is timed to arrive at the hour when everything looked brightest.",
    '8:10': "\"As the mourning of an only son.\" The grief chosen for the comparison is the one with no consolation in it.",
    '8:11': "A famine of hearing the words of the LORD. The worst deprivation threatened is of the thing they ignored while it was free.",
    '8:12': "They run from sea to sea seeking the word and do not find it. The search becomes real exactly when it is too late.",
    '8:13': "The fair virgins and the young men faint. The strongest go down first when the thirst is for something bread cannot fix.",
    '8:14': "Swearing by the sin of Samaria, by Dan, by the manner of Beersheba. They had gods enough, and not one that answered.",

    # ---- Chapter 9 ----
    '9:1': "The LORD stands upon the altar and orders the sanctuary struck. Judgement begins at the place built for mercy.",
    '9:2': "Digging into hell or climbing to heaven changes nothing. The hiding places are named at their most extreme to close them.",
    '9:3': "The top of Carmel and the bottom of the sea, with a serpent already waiting there. Every refuge turns out to be staffed.",
    '9:4': "Even captivity is no shelter. Going into exile does not put a man outside the reach of the sentence.",
    '9:7': "\"Are ye not as children of the Ethiopians unto me?\" He claims to have brought the Philistines and Syrians up as well.",
    '9:8': "\"Saving that I will not utterly destroy the house of Jacob.\" The sentence on the kingdom carries its own exception inside it.",
    '9:9': "Sifted among the nations, and not the least grain falls. The scattering is described as sorting, with nothing lost in it.",
    '9:10': "Those who die are the ones who said the evil would not overtake them. The confidence is itself what gets judged.",
    '9:11': "\"The tabernacle of David that is fallen\" — a hut, not a palace. Restoration begins with the ruin plainly admitted.",
    '9:12': "\"The heathen, which are called by my name\" — James reads this verse at Jerusalem as the warrant for Gentiles in the church.",
    '9:13': "The plowman overtakes the reaper. Sowing and harvest run into each other, so the ground never stops giving.",
    '9:14': "They build the waste cities and drink their own wine. The curse of chapter five is undone clause by clause.",
    '9:15': "\"They shall no more be pulled up out of their land.\" The book that opened with a roar closes with a planting.",
}
