#!/usr/bin/env python3
"""Written one-line takeaways for 1 Chronicles 1-29."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens with one word: Adam. Israel's genealogy is a claim staked on the whole human race.",
    '1:4': "Noah, Shem, Ham, and Japheth — the line to David walks straight over a drowned world without a word.",
    '1:10': "\"He began to be mighty upon the earth.\" The first man singled out for power, and not for good.",
    '1:12': "\"Of whom came the Philistines\" — Israel's oldest enemy is filed in the same family tree as Israel.",
    '1:19': "Peleg is named for a division. Even the naming of a child carries the memory of a world coming apart.",
    '1:27': "\"Abram; the same is Abraham.\" The renaming that reordered history is dropped in as a settled fact.",
    '1:28': "Isaac and Ishmael in one breath. The son outside the promise is listed before the line narrows.",
    '1:34': "\"Esau and Israel\" — the chronicler will not write Jacob's old name even beside his brother's.",
    '1:43': "Edom had kings while Israel had none. The record states it plainly and declines to explain it.",
    '1:51': "\"Hadad died also.\" Eight kings of Edom, each dying in turn, and not one of them founding a house.",
    # ---- Chapter 2 ----
    '2:1': "Twelve names, Reuben first and nobody left out. All Israel is counted before Judah is singled out.",
    '2:3': "\"Was evil in the sight of the LORD; and he slew him.\" A genealogy stops mid-name to record a verdict.",
    '2:4': "The line to David runs through Tamar, and the chronicler leaves that shame standing in the record.",
    '2:7': "\"Achar, the troubler of Israel\" — one man's theft is still in his name generations after the stones fell.",
    '2:11': "Boaz appears with no mention of Ruth. Chronicles keeps the line and leaves the love story to another book.",
    '2:15': "\"David the seventh.\" The youngest is reached at last, and the whole chapter has been walking toward him.",
    '2:16': "Joab and Abishai are entered as their mother's sons. In Chronicles as in Samuel, Zeruiah's name carries them.",
    '2:17': "Amasa's father is an Ishmeelite. The man Joab murdered has foreign blood recorded without comment.",
    '2:20': "Bezaleel, who built the tabernacle, is set in Judah's line. The craftsman is remembered beside the kings.",
    '2:34': "\"Sheshan had no sons, but daughters.\" A line about to die out, and the record names the trouble first.",
    '2:35': "The house is carried on by an Egyptian slave given a daughter. The line survives through an irregularity.",
    '2:55': "Families of scribes are entered in a warrior's genealogy. Writing other men down was itself a calling.",
    # ---- Chapter 3 ----
    '3:1': "Amnon heads the list. Chronicles records these sons without a word of what the first two did to this house.",
    '3:4': "Seven years and six months in Hebron, thirty-three in Jerusalem. The reign is measured before it is told.",
    '3:5': "Solomon is listed as Bathshua's fourth son. Chronicles names the mother and says nothing of Uriah.",
    '3:9': "\"And Tamar their sister.\" One daughter named among the sons, and this book never tells what became of her.",
    '3:10': "The kings of Judah run past as a list of sons. A whole second book will be spent on what this line did.",
    '3:17': "The list keeps counting straight through the captivity, as though the line had never been cut off.",
    '3:19': "Zerubbabel arrives in a genealogy, not a throne room. David's house continues as a family, not a kingdom.",
    '3:24': "The line runs past the exile to men nobody remembers. A promise is kept in obscurity as well as in glory.",
    # ---- Chapter 4 ----
    '4:9': "A mother names her son for her own pain, and the record calls him the most honourable of his brothers.",
    '4:10': "Jabez asks for blessing, land, God's hand and keeping from harm — and the verse ends by saying he got it.",
    '4:14': "A whole valley is named for its craftsmen. Ordinary trades are given their place in the tribal record.",
    '4:18': "Mered married Pharaoh's daughter, and she is entered in Judah's genealogy with no apology attached.",
    '4:22': "\"And these are ancient things.\" The chronicler admits he is copying records older than anyone's memory.",
    '4:23': "Potters who lived among plants and hedges get into scripture because the work they did was the king's.",
    '4:27': "Simeon did not multiply like Judah. The record notes a tribe quietly shrinking and offers no reason.",
    '4:40': "\"Wide, and quiet, and peaceable\" — the land is called good in the same breath as the men who take it.",
    '4:41': "Hezekiah's reign is dated into a genealogy. These lists stay tethered to real kings and real years.",
    '4:43': "The Amalekites Saul was told to destroy are finished off by Simeonites in a footnote, centuries late.",
    # ---- Chapter 5 ----
    '5:1': "The firstborn loses the birthright over one act, and the genealogy is reckoned so that everyone knows why.",
    '5:2': "Judah gets the ruler and Joseph the birthright. The blessing is split, and neither half was earned.",
    '5:6': "A prince of Reuben ends his entry as a captive. The exile is already inside the genealogy.",
    '5:18': "Forty-four thousand skilful men, counted and armed — and the next verses credit the victory elsewhere.",
    '5:20': "\"They cried to God in the battle.\" The prayer came in the middle of the fighting, not safely before it.",
    '5:22': "\"The war was of God.\" And the men who won it hold the land only \"until the captivity.\"",
    '5:25': "The tribes that trusted God in one battle went after the gods of the nations he had destroyed for them.",
    '5:26': "God stirs up an Assyrian king. The empire that carries Israel off is described as an instrument.",
}

TAKEAWAYS.update({
    # ---- Chapter 6 ----
    '6:3': "Aaron is named before Moses, and Miriam with them. The priestly line is what this book is counting.",
    '6:10': "A note is slipped in to say which Azariah served in Solomon's temple. The list is anxious to be exact.",
    '6:15': "The priestly line ends this stretch in Babylon. Even the sons of Aaron were carried away.",
    '6:28': "Samuel's sons are listed with no word about the bribes that made Israel demand a king instead.",
    '6:31': "Song is an office, appointed by David, and it begins only once the ark has somewhere to rest.",
    '6:32': "The singers served a tent for years before there was a house. Faithful work outlasts its building.",
    '6:33': "Heman is introduced not as prophet or prince but as a singer. That is the whole title the record gives.",
    '6:39': "\"His brother Asaph, who stood on his right hand.\" The psalm headings belong to a man with an assigned place.",
    '6:44': "Merari's sons stood on the left. Even praise was organised, and every man knew where he was to stand.",
    '6:48': "The Levites were given \"all manner of service\" — the unglamorous half of the work, and still called service.",
    '6:49': "Only Aaron's sons make atonement, and the reason given is simply that Moses commanded it so.",
    '6:54': "\"For theirs was the lot.\" The tribe with no land of its own receives its towns by God's throw.",
    '6:56': "The city's fields go to Caleb. The priests hold the town while someone else works the ground around it.",
    '6:57': "Hebron is a priest's city and a city of refuge at once. Shelter for the manslayer was kept near the altar.",
    '6:60': "Anathoth is handed to the priests here. Centuries on it will be Jeremiah's town, and the town that hates him.",
    '6:67': "Shechem the city of refuge sits among the Levites' towns. Asylum was priestly duty, not civic goodwill.",
    # ---- Chapter 7 ----
    '7:2': "Even a count of fighting men is dated to David's reign. The genealogy keeps circling back to one king.",
    '7:15': "\"Zelophehad had daughters\" — the case that changed Israel's inheritance law is recalled in four words.",
    '7:21': "Two sons killed in a cattle raid. The genealogy stops for one family's disaster and then moves on.",
    '7:22': "\"Ephraim their father mourned many days.\" The list makes room for a man who could not stop grieving.",
    '7:23': "He names the next child for the trouble rather than the comfort. Beriah carries that year forever.",
    '7:24': "A daughter builds three towns, and the record says so in a parenthesis in the middle of the men.",
    '7:27': "Joshua turns up as the last name on a line — the conqueror reduced to a son of Nun in a list.",
    '7:40': "Asher, the least storied tribe, is credited with twenty-six thousand men fit to go to war.",
    # ---- Chapter 8 ----
    '8:8': "A man sends his wives away and then begets children in Moab. The line runs on through a broken house.",
    '8:12': "Ono and Lod are founded by a man buried in a name list. Towns outlast the people who built them.",
    '8:13': "Benjamites drive out the men of Gath. The tribe nearly wiped out in Judges is still taking ground.",
    '8:28': "\"These dwelt in Jerusalem.\" The chronicler is quietly establishing who belongs in the city that matters.",
    '8:33': "Saul's house is entered in Benjamin's list with no comment at all — no throne, no rejection, just names.",
    '8:34': "Meribbaal is the lame man David sought out. Chronicles gives his old name and moves on to his son.",
    '8:40': "The last of Saul's tribe are archers with many sons. The house that lost the crown did not die out.",
    # ---- Chapter 9 ----
    '9:1': "\"For their transgression.\" Nine chapters of names are finally explained by the word that ends them.",
    '9:2': "The roll of those who came back opens with Nethinims beside the priests. Temple servants count as Israel.",
    '9:3': "Ephraim and Manasseh are living in Jerusalem. The chronicler will not write the north out of the people.",
    '9:13': "\"Very able men for the work of the service.\" Competence is named as a qualification for temple work.",
    '9:17': "The porters have their names taken down. Doorkeeping is treated here as an office worth a genealogy.",
    '9:19': "Korah's descendants keep the gate their ancestor was swallowed for despising. The line was not cut off.",
    '9:20': "\"And the LORD was with him.\" Phinehas is remembered for God's presence rather than for the spear.",
    '9:22': "Two hundred and twelve doorkeepers, ordained by David and Samuel. Even the doors were a prophet's business.",
    '9:27': "They slept around the house because opening it every morning was their charge and nobody else's.",
    '9:28': "The vessels were counted in and counted out. Holy things were handled with an inventory.",
    '9:32': "Somebody had to bake the shewbread every sabbath. Worship runs on work that nobody watches.",
    '9:33': "The singers were freed from other duties and employed day and night. Praise was a full-time post.",
    '9:39': "Saul's line is set down a second time, immediately before his death. The book records the house, then buries it.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "Chronicles opens its story with a defeat. The first thing that happens in this book is Israel running.",
    '10:2': "Jonathan dies in half a verse. The friendship 1 Samuel built over chapters gets no farewell here.",
    '10:4': "\"Lest these uncircumcised come and abuse me.\" Saul's last concern is his dignity, not his people.",
    '10:5': "The armourbearer who would not kill his king kills himself. Loyalty followed Saul all the way down.",
    '10:6': "\"And all his house died together.\" The dynasty is closed in one clause and never reopened.",
    '10:7': "The towns empty and the Philistines move in. A king's failure is paid for by people who were not on the hill.",
    '10:9': "Saul's head is carried round as news for idols. The dead king is turned into a Philistine sermon.",
    '10:10': "His armour goes into the house of their gods. Israel's defeat is filed as evidence that Dagon won.",
    '10:12': "Men of Jabesh march all night for a body they owed a debt to. Gratitude outlives the man who earned it.",
    '10:13': "The verdict is doubled: he kept not the word of the LORD, and he went asking a familiar spirit instead.",
    '10:14': "\"And enquired not of the LORD.\" The charge Chronicles ends on is not what Saul did but what he never asked.",
    # ---- Chapter 11 ----
    '11:1': "\"We are thy bone and thy flesh.\" Chronicles skips seven years of civil war and has all Israel arrive at once.",
    '11:2': "They quote God's own word back to David. The people are ratifying a choice made long before they made it.",
    '11:3': "A covenant before the LORD, then the anointing. Even a popular king is made king by an older promise.",
    '11:4': "Jerusalem is introduced by its pagan name, Jebus, and by the people who were still living in it.",
    '11:5': "\"Thou shalt not come hither.\" The city that would house the temple began by telling David to keep out.",
    '11:6': "David turns the assault into a competition, and Joab wins a command that will trouble the whole reign.",
    '11:8': "David builds and Joab repairs. The city is joint work of a king and the man he could never control.",
    '11:9': "\"For the LORD of hosts was with him.\" The greatness is reported and at once assigned to its cause.",
    '11:10': "The mighty men \"strengthened themselves with him.\" The throne was carried by men whose names are kept.",
    '11:11': "Three hundred slain at one time. A man is measured here by what he did, never by what he was called.",
    '11:13': "The ground was a barley field. Men died holding a patch of crop, and the record thinks it worth naming.",
    '11:14': "They stood in the field, \"and the LORD saved them.\" The courage and the deliverance are one event.",
    '11:15': "Three captains go down into a cave to find their king. David's best men found him hiding, not reigning.",
    '11:17': "\"Oh that one would give me drink.\" A longing said aloud by a powerful man costs other men everything.",
    '11:18': "They break through an army for a cup of water, and David pours it on the ground rather than drink it.",
    '11:19': "\"Shall I drink the blood of these men?\" He treats their risk as too holy to swallow for his own comfort.",
    '11:20': "Abishai's three hundred earn him a name but not a place among the first three. The ranks are kept exact.",
    '11:21': "Honoured above two, short of three. Chronicles is unembarrassed about telling a man where he stands.",
    '11:22': "A lion, in a pit, on a snowy day. The detail proves nothing and the record keeps it anyway.",
    '11:23': "He walks at a spear with a staff, and kills the Egyptian with the Egyptian's own weapon.",
    '11:25': "Benaiah is set over the guard. Proven courage is given a post, not merely a paragraph of praise.",
    '11:26': "Asahel heads the list though Abner killed him years before. The roll honours the dead alongside the living.",
    '11:31': "Ithai of Gibeah was a Benjamite. A man from Saul's own town stands armed in David's bodyguard.",
    '11:39': "Zelek the Ammonite is on the roll. David's guard included men from the nations Israel kept fighting.",
    '11:41': "\"Uriah the Hittite.\" The name is set down plainly among the heroes, and the rest is left unsaid.",
    '11:46': "Ithmah the Moabite is counted a mighty man of Israel. Ruth's people are still in David's household.",
    # ---- Chapter 12 ----
    '12:1': "Men came to David while he was a fugitive. The kingdom was being built before there was anything to join.",
    '12:2': "Ambidextrous archers out of Benjamin — Saul's own kin, arming themselves for David while Saul still reigned.",
    '12:8': "\"Faces like the faces of lions,\" swift as roes on the mountains. The chronicler plainly enjoys these men.",
    '12:14': "The least of them commanded a hundred and the greatest a thousand. The scale is given so nobody misreads it.",
    '12:15': "They crossed Jordan at full flood. The river that parted for Joshua is simply swum by these men.",
    '12:17': "David will not assume good faith. He names both possibilities aloud and hands the judging over to God.",
    '12:18': "\"Thine are we, David\" — the pledge comes by the Spirit, and it arrives as peace said three times over.",
    '12:19': "Manasseh's men defected while David was marching with the Philistines against Israel. The timing is left raw.",
    '12:21': "They helped against the rovers. Men who joined at an awkward hour proved useful in an ordinary fight.",
    '12:22': "\"Day by day there came to David.\" The army grew by arrivals until it looked like the host of God.",
    '12:23': "A troop count is headed \"according to the word of the LORD.\" Numbers are read here as a promise keeping.",
    '12:28': "Zadok arrives as a young man with twenty-two captains. Solomon's high priest begins as a soldier.",
    '12:29': "Benjamin sends only three thousand, because most of the tribe was still keeping watch for Saul's house.",
    '12:30': "Ephraim sends twenty thousand famous men. The tribe that will later split the kingdom is here making it.",
    '12:31': "Manasseh's eighteen thousand were \"expressed by name.\" Nobody came to this inside an anonymous crowd.",
    '12:32': "Issachar sent two hundred men who understood the times. Discernment is counted among the weapons.",
    '12:33': "\"They were not of double heart.\" Of fifty thousand soldiers, the quality singled out is undividedness.",
    '12:38': "A perfect heart in the soldiers and one heart in the rest. The unity is reported as a gift, not a policy.",
    '12:39': "Three days of eating and drinking. The coronation is a feast supplied by brothers, not levied on them.",
    '12:40': "Bread, figs, raisins, wine and oil carried in on asses and camels — \"for there was joy in Israel.\"",
    # ---- Chapter 13 ----
    '13:1': "David consults every captain and leader. The one party this chapter proves he did not consult is God.",
    '13:2': "\"If it seem good unto you, and that it be of the LORD\" — the order of those two clauses is the problem.",
    '13:3': "\"We enquired not at it in the days of Saul.\" The reform is right, and the method will still be wrong.",
    '13:7': "A new cart: the best equipment money could buy, and the one thing the law never allowed for the ark.",
    '13:8': "All Israel playing before God with everything they had. Sincerity at full volume is not obedience.",
    '13:9': "The oxen stumbled and a man put out his hand. The disaster starts with an instinct anyone would have had.",
    '13:10': "Uzza dies for steadying what God said must not be touched. Good intentions are not a category here.",
    '13:11': "David's first reaction is displeasure. He is angry with God before he is willing to be taught by him.",
    '13:12': "\"How shall I bring the ark of God home to me?\" The music stops and the question is a genuine one.",
    '13:13': "The ark is parked with a foreigner. What David dared not keep, Obededom the Gittite simply housed.",
    '13:14': "Three months, and the house is blessed. The ark that killed Uzza enriches the man who just had it there.",
    # ---- Chapter 14 ----
    '14:1': "A foreign king builds David's house. The kingdom's first comfort arrives as a gift from outside Israel.",
    '14:2': "David perceives God confirmed him, and the reason given is \"because of his people,\" not because of him.",
    '14:3': "More wives at Jerusalem, reported without a word of comment. Chronicles lets the fact sit there.",
    '14:8': "The Philistines come looking the moment he is anointed. The anointing is what made him worth attacking.",
    '14:9': "The valley of Rephaim, twice in one chapter. The same ground has to be fought over a second time.",
    '14:10': "David asks two questions — shall I go, and wilt thou deliver — and waits for an answer to both.",
    '14:11': "\"God hath broken in upon mine enemies by mine hand.\" The hand is David's and the breaking is God's.",
    '14:12': "The captured idols are burned. What the Philistines did with Saul's armour, David refuses to do with theirs.",
    '14:13': "The enemy comes back to the same valley. One victory settles nothing, and David does not assume it has.",
    '14:14': "The second time the answer is different: go not up. Yesterday's guidance is not today's instruction.",
    '14:15': "\"God is gone forth before thee.\" The signal to advance is the sound of someone already fighting ahead.",
    '14:16': "\"David therefore did as God commanded him.\" The entire account of the victory is in that one sentence.",
    '14:17': "The fame spreads and the fear is the LORD's doing. Reputation is handed to David rather than built.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:1': "David prepares a place before he moves anything. The second attempt begins with homework, not a parade.",
    '15:2': "\"None ought to carry the ark of God but the Levites.\" The lesson of Uzza is stated as a rule, not a mood.",
    '15:3': "All Israel is gathered again to do the same thing over. Chronicles lets the second attempt be as public as the first.",
    '15:11': "Zadok and Abiathar are both called, two priests of rival houses. David takes no shortcut through the clergy.",
    '15:12': "\"Sanctify yourselves.\" The men who will handle holy things are prepared before the ark is even lifted.",
    '15:13': "\"We sought him not after the due order.\" David names the failure as his own, and as a matter of procedure.",
    '15:14': "The priests sanctified themselves. The correction was not more enthusiasm but more obedience.",
    '15:15': "On their shoulders, with the staves, as Moses commanded. The right way had been written down all along.",
    '15:16': "Singers are appointed alongside bearers. The music is arranged with the same care as the carrying.",
    '15:17': "Heman, Asaph and Ethan — three names that will head psalms for centuries — are appointed by a committee.",
    '15:22': "Chenaniah instructed about the song \"because he was skilful.\" Skill is the qualification actually named.",
    '15:24': "Obededom, who sheltered the ark for three months, is given a door to keep beside it.",
    '15:25': "David goes with joy this time. Fear taught him the order; it did not take the gladness away from him.",
    '15:26': "\"When God helped the Levites that bare the ark\" — even carrying it correctly is credited to God's help.",
    '15:27': "David puts on a linen ephod. The king dresses like a Levite on the day the ark comes into the city.",
    '15:28': "Shouting, cornets, trumpets, cymbals and harps. The noise is the same as before; the method is not.",
    '15:29': "Michal despises him from a window. Chronicles keeps her contempt and drops the argument that followed it.",
    # ---- Chapter 16 ----
    '16:1': "The ark comes to rest in a tent, not a temple. David's greatest achievement is still only curtains.",
    '16:2': "He blesses the people in the LORD's name. The king acts as their priest without claiming the altar.",
    '16:3': "Bread, meat and wine to every man and woman in Israel. The worship ends with everybody fed.",
    '16:4': "Levites are appointed to record, thank and praise. Remembering is entered as an official duty.",
    '16:7': "The psalm is put into Asaph's hand. Chronicles tells you who first sang what you now read in the Psalter.",
    '16:8': "Thanks, prayer, and telling others. The three verbs assume worship was never meant to stay indoors.",
    '16:9': "\"Talk ye of all his wondrous works.\" Praise is licensed to be ordinary conversation, not only song.",
    '16:10': "The glorying is in his name, and the rejoicing belongs to those still seeking rather than those arrived.",
    '16:11': "\"Seek his face continually.\" Seeking is not a stage to be got through but the shape of the whole life.",
    '16:12': "Remembering is commanded because forgetting is the default. Israel's besetting sin was always amnesia.",
    '16:13': "\"His chosen ones\" — the hearers are addressed by what God did to them, not by what they achieved.",
    '16:15': "The covenant was commanded to a thousand generations. God's memory is what the song celebrates.",
    '16:16': "Abraham and Isaac are named, anchoring a festival in a promise older than the nation holding it.",
    '16:18': "The land is spoken of as given while they were still few and homeless. The promise ran ahead of the deed.",
    '16:19': "\"When ye were but few, even a few, and strangers in it.\" The weakness is remembered, not edited out.",
    '16:21': "God reproved kings for their sakes — back when they had no power at all to protect themselves.",
    '16:22': "\"Touch not mine anointed\" was said over wandering herdsmen who held no office whatever.",
    '16:23': "\"All the earth\" is summoned. Israel's own thanksgiving turns outward before it is half finished.",
    '16:24': "Declaring his glory among the heathen is set down as a duty. Mission is built into the psalm itself.",
    '16:25': "He is to be feared above all gods — a comparison allowed here and demolished in the very next line.",
    '16:26': "\"All the gods of the people are idols: but the LORD made the heavens.\" Maker and made is the whole case.",
    '16:27': "Strength and gladness in one place. The psalm will not make God's presence either grim or feeble.",
    '16:29': "\"The glory due unto his name\" — worship is described as paying what is owed, not doing God a favour.",
    '16:30': "The world is stable because God is feared, and not the other way round.",
    '16:31': "\"The LORD reigneth\" is what the nations are to be told. It is announced as fact, not offered for debate.",
    '16:32': "Sea and fields are called in to help. The praise is wider than the congregation actually singing it.",
    '16:33': "The trees sing because he comes to judge. Creation hears the judgement as good news.",
    '16:34': "\"His mercy endureth for ever\" — the line Israel sang in every crisis, set down here on a good day.",
    '16:35': "Even at the festival they pray to be gathered and delivered. The celebration knows it is not the end.",
    '16:36': "The people answer Amen. The psalm is handed to them, and their answer is what makes it worship.",
    '16:37': "Asaph is left before the ark \"as every day's work required.\" The feast ends and the routine starts.",
    '16:39': "Zadok is left at Gibeon, where the tabernacle still stood. Worship ran in two places for a generation.",
    '16:40': "Morning and evening, according to all that is written. The extraordinary day gives way to the appointed one.",
    '16:41': "Men were chosen and named to say that his mercy endures for ever. Somebody had that as an occupation.",
    '16:43': "Everyone goes home, and David goes to bless his own house. The public act finishes in a private one.",
    # ---- Chapter 17 ----
    '17:1': "Cedar for him and curtains for God. The best impulses in this book begin with somebody noticing a mismatch.",
    '17:2': "Nathan approves on the spot. A prophet's immediate agreement turns out to be only his own opinion.",
    '17:4': "\"Thou shalt not build me an house.\" The refusal comes first, and the reason never once blames David.",
    '17:5': "God says he has been content in tents. He has not been waiting for better accommodation.",
    '17:6': "\"Why have ye not built me an house of cedars?\" — a question God says he never asked anyone.",
    '17:7': "\"I took thee from the sheepcote.\" Before the promise is made, David is reminded where he was found.",
    '17:8': "The name David has was made for him. Even the reputation is listed among the things given.",
    '17:9': "The promise is for the people first: a place, planted, unmoved. David's house is not yet the subject.",
    '17:10': "David offered to build God a house; God replies that he will build David one. The direction is reversed.",
    '17:11': "The promise runs past David's death. It is deliberately framed for a man who will not live to see it.",
    '17:12': "The son builds the house and the throne is established for ever. The building was never the main clause.",
    '17:13': "\"As I took it from him that was before thee.\" Saul is the measure of what this promise rules out.",
    '17:14': "\"Mine house and my kingdom.\" Chronicles quietly makes the throne God's own rather than David's.",
    '17:16': "\"Who am I?\" The right answer to an unconditional promise is not gratitude for services rendered.",
    '17:17': "\"This was a small thing in thine eyes.\" David measures the generosity by how easily God gives it.",
    '17:18': "\"Thou knowest thy servant.\" He stops adding anything, because God already holds the full account.",
    '17:19': "\"According to thine own heart\" — the cause is located in God rather than in David's suitability.",
    '17:20': "\"There is none like thee,\" and the evidence offered is what they heard, not what they worked out.",
    '17:21': "Israel's uniqueness lies in the God who went to redeem it, and the glory of it is his name, not theirs.",
    '17:22': "\"Thou, LORD, becamest their God.\" The covenant is described as something God did to himself.",
    '17:23': "David prays for what God has already sworn. Promise does not end prayer; it is what makes prayer possible.",
    '17:24': "The reason for asking is that God's name be magnified. The dynasty is wanted for the giver's sake.",
    '17:25': "\"Therefore thy servant hath found in his heart to pray.\" The word came first and produced the praying.",
    '17:27': "\"Thou blessest, and it shall be blessed.\" The prayer ends resting on the blessing rather than on the request.",
    # ---- Chapter 18 ----
    '18:1': "Gath falls at last. The city David once hid in feigning madness is taken out of Philistine hands.",
    '18:2': "Moab becomes tributary. Chronicles reports the conquest and leaves out what 2 Samuel says he did there.",
    '18:3': "David pushes his border to the Euphrates — the frontier promised to Abraham and never before held.",
    '18:4': "He hamstrings the chariot horses and keeps a hundred. Israel's king declines to become a chariot power.",
    '18:6': "\"The LORD preserved David whithersoever he went.\" The conquests are summed up as preservation.",
    '18:7': "The gold shields come to Jerusalem. Rehoboam will hand them over to Egypt within two generations.",
    '18:8': "The brass from these towns became the temple's sea and pillars. David's wars supplied Solomon's worship.",
    '18:10': "A rival king sends congratulations and gold, because David beat the enemy he could not beat himself.",
    '18:11': "All of it is dedicated to the LORD. The plunder is never counted as the king's private wealth.",
    '18:12': "Abishai is credited with the eighteen thousand Edomites. Chronicles hands the victory to the general.",
    '18:13': "The same sentence twice in one chapter: the LORD preserved him. The repetition is the chronicler's argument.",
    '18:14': "\"Judgment and justice among all his people.\" An empire is summarised by how it treated its own.",
    '18:17': "The cabinet list ends with David's sons \"chief about the king.\" Government and family were one thing.",
    # ---- Chapter 19 ----
    '19:2': "David repays a foreign king's old kindness. A pagan's decency is allowed to stand as a debt worth honouring.",
    '19:3': "Advisers read a condolence visit as espionage. Suspicion is the cheapest counsel a young king can get.",
    '19:4': "Shaved beards and cut garments. The insult is carefully designed to humiliate rather than to injure.",
    '19:5': "\"Tarry at Jericho until your beards be grown.\" David covers his men's shame before he answers the offence.",
    '19:6': "A thousand talents of silver to hire an army. The cost of not apologising is worked out and paid anyway.",
    '19:7': "Thirty-two thousand chariots. Ammon buys a war rather than admit it mishandled a funeral visit.",
    '19:10': "Attacked before and behind, Joab divides his army instead of choosing which direction to panic in.",
    '19:11': "He hands half the army to his brother. The whole plan rests on trusting the man standing next to him.",
    '19:12': "\"If the Syrians be too strong for me, then thou shalt help me.\" The plan openly allows for failure.",
    '19:13': "\"Let the LORD do that which is good in his sight.\" Courage and resignation held in a single sentence.",
    '19:14': "The Syrians simply fled. All the arrangement ends in an enemy breaking before a blow is described.",
    '19:15': "Ammon runs the moment its hired help runs. Bought allies fail exactly when the fighting turns.",
    '19:16': "The Syrians regroup and send beyond the river. A defeat that is not accepted becomes a larger war.",
    '19:18': "Forty thousand footmen and the captain of the host. The bill for one insult is finally counted in bodies.",
    '19:19': "They made peace and would not help Ammon again. Alliances end where their usefulness ends.",
})
