#!/usr/bin/env python3
"""Written one-line takeaways for 2 Chronicles 1-36."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Chronicles opens with the kingdom already settled and God named as the cause. The purge that cleared it is left out.",
    '1:3': "The new reign begins at the oldest thing Israel owns, the tent Moses made in the wilderness.",
    '1:4': "Ark in Jerusalem, tabernacle at Gibeon. Israel's worship is split between two addresses, and the temple will end the split.",
    '1:6': "A thousand burnt offerings before a single request is made. The asking comes after the giving here.",
    '1:7': "God moves first. The offer is made before Solomon has framed a prayer, and it is left wide open.",
    '1:8': "Solomon begins with what God did for his father rather than with what he now needs.",
    '1:9': "He asks God to keep a promise God made. That is the one kind of request which presumes nothing.",
    '1:10': "The request is for competence in the work he was given, not for release from it.",
    '1:11': "God lists what was not asked for. The prayer is commended chiefly for its omissions.",
    '1:12': "The riches arrive as an extra nobody requested, which is how they keep their character as gift.",
    '1:14': "Fourteen hundred chariots stand in the same chapter as the gift of wisdom, and the writer flags no tension.",
    '1:15': "Silver as common as stones. Chronicles reports the abundance as blessing and leaves Deuteronomy's warning unquoted.",
    '1:16': "The horses come up out of Egypt, the one market the law told a king of Israel never to send to.",
    '1:17': "Solomon is arming Syria and the Hittites at a markup. The wisdom given for judging a people is earning on the side.",
    # ---- Chapter 2 ----
    '2:1': "Two houses are determined in one breath, the LORD's and his own, and the pairing will run through the rest of the book.",
    '2:2': "Seventy thousand bearers and eighty thousand hewers. The glory of the house rests on conscripted backs.",
    '2:3': "The letter opens by invoking David. Solomon trades on a relationship his father built before he asks for anything.",
    '2:4': "The house is defined by what will happen in it daily, not by what it will look like.",
    '2:5': "The building is great because God is. Architecture is being used here as an argument about who is worshipped.",
    '2:6': "The builder says plainly that the house cannot hold its occupant. He builds it anyway, to sacrifice in.",
    '2:7': "Skill in gold and dye and graving is requisitioned for God's house, which makes a trade into a calling.",
    '2:8': "Solomon concedes that Tyre's men cut timber better than his own. The temple is built with borrowed competence.",
    '2:10': "Foreign woodcutters are paid out of Judah's harvest. The work of the house feeds men who do not worship in it.",
    '2:11': "A Gentile king reads Israel's politics theologically: you have this throne because the LORD loves this people.",
    '2:12': "Huram of Tyre blesses the God who made heaven and earth. The Chronicler lets an outsider say the largest thing here.",
    '2:14': "A Danite mother and a Tyrian father. The man who beautifies the house belongs fully to neither nation.",
    '2:16': "Cedar floated down the coast to Joppa. Whole economies are rearranged around one building in the hills.",
    '2:17': "The levy falls on the strangers in the land. The writer counts them exactly and does not comment.",
    # ---- Chapter 3 ----
    '3:1': "Moriah, and Ornan's threshingfloor. The temple stands where a father was stopped and a plague was stopped.",
    '3:2': "Building starts in the fourth year. Three years of a secured kingdom passed before the house was begun.",
    '3:3': "\"Wherein Solomon was instructed\" — the plan was handed to him. Nothing in this house is his own idea.",
    '3:5': "Palm trees and chains carved into the walls. The house is decorated as a garden, which is where God last walked with men.",
    '3:7': "Gold on the beams, posts, walls and doors, and cherubims graved everywhere. No surface is left ordinary.",
    '3:8': "Six hundred talents of gold on a room no one enters but once a year. The cost is heaviest where it is least seen.",
    '3:9': "Even the nails are weighed in gold. The record notices what a visitor never would.",
    '3:10': "The only images allowed in the house are the ones God specified, and they face the place where mercy is given.",
    '3:13': "\"They stood on their feet, and their faces were inward.\" The guardians of the gate now attend rather than bar.",
    '3:14': "A curtain is woven to keep the room shut. Matthew will report what finally happened to it.",
    '3:17': "Two pillars named He Establishes and In Him Is Strength. The entrance is a sentence about who holds the house up.",
    # ---- Chapter 4 ----
    '4:1': "The brasen altar has the same footprint as the most holy place. Sacrifice is built to the measure of the mercy seat.",
    '4:2': "A sea of standing water in a desert courtyard, kept for washing. Approach assumes that everyone arrives dirty.",
    '4:4': "Twelve oxen facing out to the four winds carry the water. The tribes are bearing up what cleanses them.",
    '4:5': "The rim of a washbasin is worked like a lily. Beauty is spent on the plumbing.",
    '4:6': "The offerings are washed in the lavers and the priests in the sea. Both the gift and the giver need cleaning.",
    '4:7': "One lampstand in the wilderness has become ten. What was carried is now installed.",
    '4:9': "A court for the priests and a great court for everyone else. Access is real and it is graded.",
    '4:11': "\"And Huram finished the work.\" A Tyrian craftsman's name is written into the account of the LORD's house.",
    '4:17': "The holy vessels were cast in clay pits down by the Jordan. Sacred things were made in the mud.",
    '4:18': "The brass could not be weighed. The one measurement the record gives up on is the one of sheer quantity.",
    '4:19': "The golden altar and the shewbread tables — incense and bread, prayer and provision, standing side by side.",
    '4:20': "Lamps that burn before the oracle at all hours. Light is kept up in a room nobody is watching.",
    '4:22': "Snuffers and spoons of pure gold. The smallest tools in the house are made of the most costly thing in it.",
    # ---- Chapter 5 ----
    '5:1': "David's dedicated silver and gold go into the treasury untouched. The son does not spend what the father set apart.",
    '5:2': "The ark is fetched from a tent a few hundred yards away. The whole nation is assembled for the shortest journey in the book.",
    '5:4': "This time the Levites carry it. Uzza's death taught a lesson the record does not need to repeat.",
    '5:6': "Sacrifices past counting. A day that costs this much is the Chronicler's way of saying what it meant.",
    '5:7': "The ark comes to rest under the wings. After the wilderness and Philistia and Obededom's house, it stops moving.",
    '5:9': "The staves are left in and their ends still show. The gear for travelling is kept visible in the place of rest.",
    '5:10': "Nothing in the ark but the two tables. At the centre of the house is the law that accuses whoever comes near.",
    '5:11': "Every priest present is sanctified and the courses are suspended. For one day nobody is off duty.",
    '5:12': "White linen, cymbals, psalteries, a hundred and twenty trumpets. Chronicles never lets the singers out of its sight.",
    '5:13': "\"To make one sound\" — and the cloud comes when the praise is unified, not when it is loud.",
    '5:14': "The priests cannot do their jobs. God's arrival stops the ministry that was arranged to receive him.",
    # ---- Chapter 6 ----
    '6:1': "Solomon's first word about the new house is that God said he would dwell in the dark.",
    '6:2': "A house built for ever, by a king who will be told within a chapter that it can be cast out of God's sight.",
    '6:3': "He blesses the congregation before he prays. The people are addressed before God is.",
    '6:4': "Spoken with his mouth, fulfilled with his hands. The praise is for a promise that was kept, not for a building.",
    '6:5': "For four hundred years God chose no city and no king. The arrangement Solomon inherits is late, not original.",
    '6:6': "A city and a man, both chosen. The place and the dynasty rest on the same free decision.",
    '6:7': "David wanted to build it. The desire is recorded because God took notice of a desire he refused.",
    '6:8': "\"Thou didst well in that it was in thine heart.\" God commends the intention while declining the work.",
    '6:9': "The man who plans is not always the man who builds, and being told no is not being told you were wrong.",
    '6:11': "What the house finally holds is a covenant document. The centre of the building is a promise in writing.",
    '6:13': "The king kneels on a platform where the whole nation can see him do it.",
    '6:14': "God is unlike any other, and the thing named as unlike is that he keeps covenant.",
    '6:16': "The promise is unconditional to David and conditional to his sons, and the history to come lives in that tension.",
    '6:18': "\"Will God in very deed dwell with men on the earth?\" The question stands unanswered until an incarnation answers it.",
    '6:20': "He asks for eyes open on a place, because God attached his name to it and not because stone attracts him.",
    '6:21': "Seven petitions follow, and this one sets the pattern: when you hear, forgive.",
    '6:22': "Where evidence runs out, an oath at the altar is all a court has left. Solomon asks God to be the last witness.",
    '6:23': "Justifying the righteous and requiting the wicked are one act of judgement, not two moods in God.",
    '6:24': "Defeat is read as discipline rather than accident, and the way back is confession rather than a better army.",
    '6:25': "The prayer for a beaten nation asks first for forgiveness and only then for the land back.",
    '6:26': "Drought is named as a shut heaven. The weather is treated as speech from God rather than as bad luck.",
    '6:27': "Forgiveness comes first and the rain after, and in between God teaches them the good way.",
    '6:28': "Blight, locusts, siege, sickness. The list is deliberately unsorted, because trouble does not arrive in categories.",
    '6:29': "\"Every one shall know his own sore.\" The national prayer makes room for the man who can only name his own trouble.",
    '6:30': "God alone knows the hearts, which is why he alone can render to every man and be just about it.",
    '6:32': "The stranger is prayed for by name at the dedication. The house was never meant to be only Israel's.",
    '6:33': "Solomon asks God to answer the foreigner in everything, so that the nations learn what kind of God this is.",
    '6:34': "Even the army at war prays toward a house, not toward its own strength.",
    '6:36': "\"For there is no man which sinneth not.\" The exile is treated as certain because the sin is.",
    '6:37': "\"We have sinned, we have done amiss, and have dealt wickedly.\" The words of a confession are supplied in advance.",
    '6:38': "Return is possible from the far country. Distance from the temple is not distance from God's hearing.",
    '6:41': "The ark is called the ark of thy strength, and the priests are asked to be clothed with salvation they did not make.",
    '6:42': "The prayer ends not on Solomon's record but on God's mercies to David. He pleads another man's covenant.",
    # ---- Chapter 7 ----
    '7:1': "Fire falls on the offering the moment the praying stops. God answers the prayer by consuming the sacrifice.",
    '7:2': "The priests are shut out of their own temple on its opening day.",
    '7:3': "The people's response to fire and glory is a sentence about mercy enduring for ever.",
    '7:5': "Twenty-two thousand oxen and a hundred and twenty thousand sheep. The dedication is measured in slaughter.",
    '7:7': "The altar was too small for the day. Solomon consecrates the courtyard floor to take the overflow.",
    '7:8': "Seven days, and the congregation stretches from Hamath to the brook of Egypt. This is the widest Israel ever stands together.",
    '7:10': "They go home glad, and the gladness is credited to what God did for David and Solomon rather than to the festival.",
    '7:12': "God answers by night, quietly, after the public fire. The word matters more than the spectacle.",
    '7:13': "God claims the drought and the locusts as his own doing before he offers any remedy for them.",
    '7:14': "The promise is made to a covenant people at their own temple about their own land, not to any nation that borrows it.",
    '7:15': "Solomon asked for open eyes and attentive ears at this place, and is told in the same words that he has them.",
    '7:16': "God's name, eyes and heart are put in the house. The presence promised is personal, not architectural.",
    '7:17': "The house is secured for ever in one verse and the king's own future made conditional in the next.",
    '7:18': "The covenant with David is restated to Solomon as the ground of his throne, not as a reward for the building.",
    '7:19': "\"But if ye turn away\" — the warning is given at the dedication, not saved for the decline.",
    '7:20': "The house God has just sanctified can be cast out of his sight. Consecration is not immunity.",
    '7:21': "A ruin that makes passers-by ask questions. God warns that his own house may end as an argument against Israel.",
    '7:22': "The answer supplied to that question is not that God failed them but that they forsook him.",
}

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "Twenty years of the greatest building project in Israel's history are dispatched in half a sentence.",
    '8:2': "In Kings Solomon hands cities to Huram and Huram despises them. Here he receives them and settles Israelites in them.",
    '8:4': "Store cities in the wilderness. Wealth this size has to be kept somewhere, and keeping it becomes its own work.",
    '8:5': "Walls, gates and bars, built in the middle of a reign famous for peace. Peace is expensive to maintain.",
    '8:6': "\"All that Solomon desired to build\" — the record has stopped distinguishing between what was needed and what was wanted.",
    '8:8': "The nations Israel failed to drive out are now the labour force. An old disobedience has been turned into a revenue stream.",
    '8:9': "No Israelite is made a bondservant. The northern tribes will remember this arrangement differently.",
    '8:11': "Solomon will not house his Egyptian wife where the ark has been. He is scrupulous about the place and not about the marriage.",
    '8:12': "The king offers on the altar he built, at the porch he built. Everything here is his, and he still stands as a worshipper.",
    '8:13': "The calendar is not Solomon's invention. He keeps a rhythm Moses set, in a house he designed.",
    '8:14': "David is called \"the man of God\" for arranging the singers and porters. Chronicles honours him most for the rota.",
    '8:15': "\"They departed not from the commandment.\" The high point of the reign is described as nothing having drifted.",
    '8:16': "The house is declared perfected, and within two chapters the kingdom that built it is torn in half.",
    '8:18': "Four hundred and fifty talents of gold, fetched by Tyrian sailors. Solomon's wealth arrives through other men's seamanship.",
    # ---- Chapter 9 ----
    '9:1': "She comes to test him, not to admire him, and she brings the caravan anyway.",
    '9:2': "\"There was nothing hid from Solomon.\" The wisdom asked for in chapter one is being spent on a foreigner's questions.",
    '9:4': "The stairway up to the house of the LORD is on her list with the food and the uniforms. What undid her was the whole scale.",
    '9:5': "She grants that the rumour was true, which people rarely do.",
    '9:6': "\"I believed not their words, until I came.\" Reports of this kind are not believed until they cost a journey.",
    '9:7': "She envies the servants, not the king. Nearness to wisdom looks better to her than possessing it.",
    '9:8': "A pagan queen states the Chronicler's whole doctrine of kingship: the throne is the LORD's, and the king sits on it for him.",
    '9:9': "The gold she gives is named after the spices, and the spices are what nobody could match.",
    '9:11': "Rare imported timber becomes stairs to the temple and harps for the singers. The luxury is put to liturgical use.",
    '9:12': "He gives her more than she brought. The exchange ends with the wise man out of pocket and content.",
    '9:13': "Six hundred and sixty-six talents of gold in a year, recorded without comment. Revelation will remember the number.",
    '9:15': "Two hundred golden shields, hung up for display. Shishak will carry every one of them off in chapter twelve.",
    '9:17': "A throne of ivory overlaid with gold, for a man who was given wisdom to judge from it.",
    '9:18': "Six steps up and lions on every one. The approach to the king's judgement seat is built to intimidate.",
    '9:20': "Silver was not accounted of. Prosperity has reached the point where an ordinary treasure has become worthless.",
    '9:21': "Apes and peacocks, three years at sea. A fleet is running for curiosities as well as for gold.",
    '9:22': "Riches are named before wisdom now. In chapter one the order was the other way round.",
    '9:23': "The kings come to hear what God put in Solomon's heart. Even at its most dazzling the wisdom is on loan.",
    '9:24': "\"A rate year by year.\" Tribute has become routine, and routine is how the heart stops noticing.",
    '9:25': "Four thousand stalls. Deuteronomy told the king not to multiply horses, and the record simply counts them.",
    '9:26': "The borders reach what was promised to Abraham. This is as much of the land as Israel ever actually holds.",
    '9:29': "Three prophets wrote the reign up, and one of them is remembered for prophesying against it.",
    '9:30': "Forty years, the same as David and Saul. The full span is given and no decline is described.",
    '9:31': "Chronicles buries Solomon with no foreign wives, no idols and no adversaries. The book has chosen what it will carry.",
    # ---- Chapter 10 ----
    '10:1': "The heir has to travel north to be made king. The throne is not simply inherited; it has to be granted.",
    '10:2': "The man Solomon tried to kill comes back from Egypt the moment the old king is dead.",
    '10:4': "The complaint is about Solomon's yoke. The glory of chapter nine is being priced from underneath.",
    '10:6': "He asks the men who watched his father govern. The right people are consulted first, which makes what follows worse.",
    '10:7': "The old men's advice is that kindness now buys loyalty for ever. It is shrewd politics and it is also simply true.",
    '10:8': "\"He forsook the counsel\" and went to the men he grew up with. Advice that flatters is easier to hear.",
    '10:9': "He puts the same question twice until it comes back in the shape he wanted.",
    '10:10': "The boast is about the size of his little finger. A kingdom is lost over a line written to sound impressive.",
    '10:11': "Whips to scorpions. The young men's plan for a restless people is to make the grievance worse on purpose.",
    '10:13': "\"The king answered them roughly.\" The tone did as much damage as the policy.",
    '10:14': "He says the young men's words in his own mouth, which makes the folly his and not theirs.",
    '10:15': "\"For the cause was of God.\" Rehoboam's stupidity is entirely his own, and it serves a word spoken by Ahijah.",
    '10:16': "\"What portion have we in David?\" The covenant with David is dismissed as a Judahite family matter.",
    '10:18': "He sends the taxman to negotiate and the taxman is stoned. The king did not understand what he was facing.",
    '10:19': "\"Unto this day.\" The split the Chronicler's readers live inside began with one badly chosen sentence.",
    # ---- Chapter 11 ----
    '11:1': "A hundred and eighty thousand men raised to recover by force what was lost by talking.",
    '11:4': "\"For this thing is done of me\" — and they obeyed. The one command Rehoboam kept was the one to stand down.",
    '11:5': "Having lost ten tribes, he fortifies what is left. The building programme is an admission of the borders.",
    '11:6': "Bethlehem heads the list of fortress towns. The town of David's birth is now a garrison on a shrunken frontier.",
    '11:10': "Fifteen fenced cities, and Shishak takes them all in the next chapter. Stone walls hold nothing up by themselves.",
    '11:11': "Captains, victual, oil and wine. A siege is planned for in advance by men who expect to be besieged.",
    '11:12': "\"Having Judah and Benjamin on his side\" — two tribes, and the writer counts that as strength.",
    '11:13': "The priests and Levites come south. The division of the kingdom is also a migration of the ministry.",
    '11:14': "The Levites walk away from their land and their houses. Fidelity to an office cost them everything they owned.",
    '11:15': "Jeroboam appoints his own priests for calves and devils. A state that wants loyalty will always make its own clergy.",
    '11:16': "Ordinary people follow the Levites south. Where worship goes, those who want God go after it.",
    '11:17': "\"Three years.\" The Chronicler dates the faithfulness precisely, because he knows exactly when it stopped.",
    '11:20': "Absalom's granddaughter becomes the favourite wife. The rebellion against David has married back into the house.",
    '11:21': "Eighteen wives and threescore concubines, and one of them loved above the rest. The arithmetic guarantees a grievance.",
    '11:22': "He names the son of the favourite wife as heir, which is how David's house got into trouble in the first place.",
    '11:23': "\"He dealt wisely\" and \"he desired many wives\" stand in the same verse, and the writer lets them sit there.",
    # ---- Chapter 12 ----
    '12:1': "Strength came first and apostasy came after. Security, not hardship, is what undoes Rehoboam.",
    '12:2': "The invasion is dated and then explained. Chronicles never lets an army be merely an army.",
    '12:4': "Every fenced city of chapter eleven falls, and Shishak stands at Jerusalem. The defences bought nothing.",
    '12:5': "\"Ye have forsaken me, and therefore have I also left you.\" The abandonment is described as reciprocal and in that order.",
    '12:6': "\"The LORD is righteous.\" The confession takes God's side against themselves and asks for nothing.",
    '12:7': "\"Some deliverance.\" God relents without cancelling the lesson. Mercy here is real and partial.",
    '12:8': "They will serve Shishak so that they can compare masters. Serving God is learned by trying the alternative.",
    '12:9': "\"He took all.\" Everything Solomon accumulated leaves Jerusalem in one campaign, five years after his death.",
    '12:10': "Brass shields where the gold ones hung. The replacement is the honest picture of the kingdom now.",
    '12:11': "The guard still carries them out with ceremony. The ritual continues exactly as before around an object worth a fraction.",
    '12:12': "This is why Chronicles tells the story: a king humbled himself, and wrath turned. Kings leaves that out.",
    '12:13': "His mother was an Ammonitess, named without comment in the middle of a verse about the chosen city.",
    '12:14': "\"He prepared not his heart to seek the LORD.\" The evil is diagnosed as a heart never set, not as a crime committed.",
    # ---- Chapter 13 ----
    '13:3': "Four hundred thousand against eight hundred thousand. The numbers are given so that the outcome cannot be credited to Judah.",
    '13:4': "He stands on a hill in enemy territory and preaches a sermon at an army. The battle opens with theology.",
    '13:5': "A covenant of salt — a grant meant to keep, like salted meat. Abijah stakes everything on God's promise to David.",
    '13:7': "Abijah calls his father young and tenderhearted. Chapter ten said he was forty-one and answered roughly.",
    '13:8': "\"Ye think to withstand the kingdom of the LORD\" — and you have brought golden calves with you to do it.",
    '13:9': "Anyone with a bullock and seven rams can be a priest in the north. Ordination has been put up for sale.",
    '13:10': "\"But as for us, the LORD is our God.\" His whole case rests on who is ministering, not on who is stronger.",
    '13:11': "Morning and evening sacrifice, shewbread, lamps. The argument for Judah is a list of things done every ordinary day.",
    '13:12': "\"God himself is with us for our captain.\" He warns the other side off rather than threatening them.",
    '13:13': "While Abijah preaches about God fighting for Judah, Jeroboam quietly gets behind him.",
    '13:14': "Surrounded, they cry out and the priests blow the trumpets. The response to the trap is liturgical.",
    '13:15': "The men shout and God smites. The shout is all Judah contributes to the verse.",
    '13:17': "Five hundred thousand chosen men of Israel dead. A victory over one's own brothers is counted at full price.",
    '13:18': "\"Because they relied upon the LORD.\" Chronicles states its verdict on every battle in a single clause.",
    '13:19': "Bethel is taken from Jeroboam — the shrine town with a golden calf in it changes hands.",
    '13:20': "Jeroboam never recovers, and the record says outright who struck him.",
    '13:21': "The man who preached that sermon took fourteen wives. Chronicles reports both and reconciles neither.",
})

TAKEAWAYS.update({
    # ---- Chapter 14 ----
    '14:1': "\"The land was quiet ten years.\" Chronicles measures a reign in years of rest as much as in battles.",
    '14:2': "\"Good and right in the eyes of the LORD\" — the formula that grades every reign here, and the eyes are not Judah's.",
    '14:3': "The reform arrives as a demolition list: altars, high places, images, groves. It begins as removal.",
    '14:4': "A king can command Judah to seek the LORD. Whether a heart follows a royal order is the open question.",
    '14:6': "The rest was given before the building began. Asa fortifies out of peace rather than to obtain it.",
    '14:7': "\"While the land is yet before us.\" He builds in the quiet years for a war nobody has declared yet.",
    '14:9': "A thousand thousand men and three hundred chariots. The odds are stated so the prayer coming has weight.",
    '14:11': "\"Let not man prevail against thee.\" Asa makes the battle God's quarrel instead of his own.",
    '14:12': "\"So the LORD smote the Ethiopians.\" The verb of the victory belongs to God; Judah only pursues.",
    '14:13': "\"Destroyed before the LORD\" — and Judah goes home rich. The spoil is a footnote to who fought.",
    '14:14': "\"The fear of the LORD came upon them.\" Towns round about learn from a battle they never entered.",
    # ---- Chapter 15 ----
    '15:2': "\"If ye seek him, he will be found of you.\" The book's whole theology, and it arrives as a condition.",
    '15:3': "\"Without a teaching priest, and without law.\" The famine named here is a famine of instruction.",
    '15:4': "The turning happened in trouble, and it was enough. Trouble is where this book keeps locating repentance.",
    '15:5': "\"No peace to him that went out, nor to him that came in.\" Collapse described at the scale of a day's errands.",
    '15:6': "\"God did vex them with all adversity.\" The anarchy is not merely reported; an agent is named for it.",
    '15:7': "\"Let not your hands be weak: for your work shall be rewarded.\" The prophet ends on encouragement.",
    '15:8': "He heard the word and \"took courage.\" This reform belongs to a king who needed telling to keep going.",
    '15:9': "Northerners come south because they saw God was with Asa. Reform pulled people across a hostile border.",
    '15:11': "Seven hundred oxen out of the spoil. What the Ethiopian campaign won is handed straight back in sacrifice.",
    '15:12': "The covenant is to seek, not to have found. The verb Chronicles cares about is one still in progress.",
    '15:13': "Death for the man or woman who would not seek God. This zeal is recorded without softening or praise.",
    '15:15': "\"They had sworn with all their heart, and he was found of them.\" The rest comes after the oath.",
    '15:16': "He deposes his own mother and burns her idol at the brook. The reform reached the palace last of all.",
    '15:17': "High places left standing, \"nevertheless the heart of Asa was perfect.\" The verdict is on a heart, not a record.",
    '15:18': "Dedicated silver and gold carried into the house of God. For now the treasure is moving inward.",
    # ---- Chapter 16 ----
    '16:1': "Baasha builds a town to seal the road, \"that he might let none go out or come in.\" A wall used as a chokehold.",
    '16:2': "Treasure comes back out of the house of the LORD. A frightened king spends what a grateful one deposited.",
    '16:3': "\"There is a league between me and thee\" — Asa pays Syria to break its word and trusts the man who breaks it.",
    '16:4': "The bribe worked. Chronicles lets the policy succeed and still calls it the failure of the reign.",
    '16:6': "He carts off the stones Baasha quarried and builds with them. A tidy ending, and a prophet is on his way.",
    '16:7': "\"Because thou hast relied on the king of Syria\" — the rebuke lands on a success, not on a defeat.",
    '16:8': "The Ethiopians are produced as evidence. He had already been shown what relying on God could do.",
    '16:9': "\"The eyes of the LORD run to and fro\" is said to a king being told he has done foolishly. It is a rebuke.",
    '16:10': "The seer goes to a prison house and the people are oppressed. A man who cannot take correction injures others.",
    '16:12': "\"He sought not to the LORD, but to the physicians.\" The fault is not the doctors but the seeking done nowhere else.",
    '16:14': "Spices, apothecaries and a very great burning. Asa is buried lavishly by people his rage had oppressed.",
})

TAKEAWAYS.update({
    # ---- Chapter 17 ----
    '17:1': "The reign opens by strengthening himself against Israel. Brothers are the border that has to be watched.",
    '17:2': "Garrisons in the cities of Ephraim. Judah is holding northern towns, and the division is now a frontier.",
    '17:3': "\"The first ways of his father David.\" The writer is careful which part of David is held up as the pattern.",
    '17:5': "Establishment came first and the riches after. Chronicles never lets the order of those two be reversed.",
    '17:6': "\"His heart was lifted up in the ways of the LORD.\" The same phrase damns Uzziah later; direction decides it.",
    '17:7': "He spends the third year of his reign sending princes out to teach. A king's first project is a curriculum.",
    '17:9': "\"They taught in Judah, and had the book of the law of the LORD with them.\" The text travelled to the villages.",
    '17:10': "The nations keep the peace out of fear of the LORD. Judah's safety is credited to a reputation, not an army.",
    '17:11': "Philistines and Arabians arrive with tribute. The neighbours who used to raid Judah are paying it instead.",
    '17:12': "Castles and cities of store. Jehoshaphat teaches the law and builds the walls in the same reign.",
    '17:16': "Amasiah \"willingly offered himself unto the LORD\" — one man in the muster roll given a reason as well as a number.",
    '17:19': "Over a million men waiting on the king, and in the next chapter he fights as another king's junior partner.",
    # ---- Chapter 18 ----
    '18:1': "\"Riches and honour in abundance, and joined affinity with Ahab.\" The marriage is placed beside the wealth on purpose.",
    '18:2': "Sheep and oxen in abundance, and then the request. Hospitality is being used as leverage and it works.",
    '18:3': "\"I am as thou art, and my people as thy people.\" He commits Judah before a single question has been asked.",
    '18:4': "\"Enquire, I pray thee, at the word of the LORD.\" He asks God's mind after promising the army.",
    '18:5': "Four hundred prophets and no dissent. Unanimity purchased from men on the payroll proves nothing.",
    '18:6': "\"Is there not here a prophet of the LORD besides?\" He can tell the difference, which makes verse three worse.",
    '18:7': "\"I hate him; for he never prophesied good unto me.\" Ahab's test of a prophet is whether the news pleases him.",
    '18:9': "Two thrones, royal robes, a void place at the gate. The consultation is staged as theatre before it begins.",
    '18:10': "Horns of iron and \"Thus saith the LORD.\" A prop is supplied because the words alone would not convince.",
    '18:12': "\"Let thy word therefore be like one of theirs.\" The pressure to conform arrives as friendly advice.",
    '18:13': "\"Even what my God saith, that will I speak.\" The freedom of the prophet is the narrowness of his brief.",
    '18:14': "\"Go ye up, and prosper.\" He gives the king the answer he wanted, in a tone nobody in the room mistakes.",
    '18:15': "The king demands the truth he has spent the day arranging not to hear.",
    '18:16': "\"Sheep that have no shepherd.\" The verdict pities Israel and quietly removes their king from the picture.",
    '18:18': "The scene shifts to a throne room where the real deliberation has already happened.",
    '18:21': "A lying spirit is permitted, not commanded by deceit. Ahab's chosen prophets are handed over to what they wanted.",
    '18:22': "Micaiah tells Ahab the prophets are lying before he goes. After this the king cannot claim he was deceived.",
    '18:23': "The answer to the vision is a blow on the cheek. Argument fails, so the hand is used instead.",
    '18:24': "\"When thou shalt go into an inner chamber to hide thyself.\" The reply is dated rather than defended.",
    '18:26': "Bread and water of affliction \"until I return in peace.\" The sentence assumes the outcome under dispute.",
    '18:27': "\"If thou certainly return in peace, then hath not the LORD spoken by me.\" He stakes his office on one event.",
    '18:28': "Both kings heard the vision, and both of them went up anyway. Judah's good king is in the chariot too.",
    '18:29': "\"I will disguise myself; but put thou on thy robes.\" Ahab arranges for his ally to be the visible target.",
    '18:30': "The Syrians have orders to kill one man. Ahab's disguise leaves only Jehoshaphat looking like a king.",
    '18:31': "\"Jehoshaphat cried out, and the LORD helped him.\" Chronicles adds the cry that 1 Kings does not record.",
    '18:33': "\"A certain man drew a bow at a venture.\" The random arrow finds the joint the word had already named.",
    '18:34': "Propped upright in his chariot till sundown. The disguise held, the appearance held, and he died anyway.",
    # ---- Chapter 19 ----
    '19:2': "\"Shouldest thou help the ungodly?\" The alliance itself is the charge, whatever the campaign achieved.",
    '19:3': "\"Nevertheless there are good things found in thee.\" The rebuke is exact enough to say what was not wrong.",
    '19:4': "After the rebuke he goes out through the people himself, from Beersheba to Ephraim. Repentance took the form of a circuit.",
    '19:5': "Judges set city by city. The reform is administrative, and it outlasts anything won at Ramothgilead.",
    '19:6': "\"Ye judge not for man, but for the LORD, who is with you in the judgment.\" The bench is told whose work it is doing.",
    '19:7': "No iniquity, no respect of persons, no taking of gifts. The judges are to imitate a character, not obey a rule.",
    '19:10': "Judges are to warn as well as decide, so that wrath does not come. The court has a pastoral duty attached.",
    '19:11': "Matters of the LORD go to the priest, the king's matters to the ruler. Two jurisdictions, named and kept apart.",
})

TAKEAWAYS.update({
    # ---- Chapter 20 ----
    '20:1': "Moab and Ammon come against the king who has just finished reorganising the courts. Reform buys no immunity.",
    '20:2': "The news arrives when the enemy is already at Engedi. Nobody had time to prepare anything but a prayer.",
    '20:3': "\"Jehoshaphat feared, and set himself to seek the LORD.\" The fear is not denied; it is given a direction.",
    '20:4': "The whole of Judah comes in from the cities to ask help. The emergency measure is an assembly, not a muster.",
    '20:6': "The prayer is built of questions whose answers he already knows. Prayer here is remembering out loud.",
    '20:7': "\"Abraham thy friend.\" The claim on the land is a claim on a promise, not on possession or arms.",
    '20:9': "\"We stand before this house.\" He is quoting Solomon's dedication prayer back to God and asking for the terms.",
    '20:10': "The nations now invading are the ones Israel was forbidden to invade. Restraint kept then is used against Judah now.",
    '20:11': "\"Behold, I say, how they reward us.\" He argues from God's ownership of the land rather than Judah's rights in it.",
    '20:12': "\"Neither know we what to do: but our eyes are upon thee.\" Ignorance is admitted as part of the petition.",
    '20:13': "Little ones, wives and children standing in the court. The whole population is present at the decision.",
    '20:14': "The word comes through a Levite of the sons of Asaph. A man from the choir is the prophet in this crisis.",
    '20:15': "\"The battle is not yours, but God's\" — said to a king with an army, about one particular invasion at his border.",
    '20:16': "The answer includes a route and a map reference. Judah is told exactly where to be standing tomorrow.",
    '20:17': "\"Stand ye still, and see the salvation of the LORD.\" They still have to march out and watch it happen.",
    '20:18': "King and people on the ground before a battle that has not been fought. The thanksgiving comes first.",
    '20:20': "\"Believe in the LORD your God... believe his prophets.\" Trusting God here means trusting the man who spoke.",
    '20:21': "Singers appointed to go out ahead of the army. The front rank carries no weapons and praises God's mercy.",
    '20:22': "\"When they began to sing... the LORD set ambushments.\" The timing is reported without being explained.",
    '20:23': "The coalition destroys itself. The armies Judah feared do to each other what Judah could not have done.",
    '20:24': "From the watch tower they look for an army and find dead bodies. The victory was over before the arrival.",
    '20:25': "Three days to collect the spoil, more than they could carry. A fast proclaimed in fear ends in this.",
    '20:26': "They stop to bless God and the valley keeps the name. A place is renamed after what was said there.",
    '20:28': "Psalteries and harps back to the house of the LORD. The campaign ends where it started, in the temple.",
    '20:32': "\"He walked in the way of Asa his father, and departed not from it\" — a compliment that chapter sixteen complicates.",
    '20:33': "The high places stand because \"the people had not prepared their hearts.\" This failure is laid on the nation.",
    '20:35': "He joins himself to Ahaziah, \"who did very wickedly.\" The man rebuked for helping the ungodly does it again.",
    '20:37': "\"The LORD hath broken thy works.\" The ships never sail, and the partnership is undone before it earns anything.",
    # ---- Chapter 21 ----
    '21:2': "The writer calls Jehoshaphat king of Israel. Judah's king holds the name the northern kingdom took.",
    '21:3': "Gifts and fenced cities to the younger sons, the kingdom to the eldest. A careful father plants a grievance.",
    '21:4': "He strengthens himself by killing his brothers. The first act of the reign is to remove the alternatives.",
    '21:6': "\"He had the daughter of Ahab to wife.\" The alliance made in chapter eighteen is now sitting on the throne.",
    '21:7': "\"The LORD would not destroy the house of David.\" The promise holds up a king who deserves nothing from it.",
    '21:8': "Edom revolts. Chronicles reports the loss of empire as a symptom rather than as a policy failure.",
    '21:10': "\"Because he had forsaken the LORD God of his fathers.\" The revolt of two provinces is given a theological cause.",
    '21:11': "He does not merely permit the high places; he compels Judah to them. Apostasy here is a royal programme.",
    '21:12': "Elijah appears in Chronicles once, and by letter. The prophet of the north writes south to a son-in-law of Ahab.",
    '21:13': "\"Thy brethren of thy father's house, which were better than thyself.\" The murdered brothers are ranked above him.",
    '21:15': "The sentence is a disease of the bowels, spelled out in full. Chronicles does not spare the reader the details.",
    '21:16': "\"The LORD stirred up against Jehoram the spirit of the Philistines.\" The raiders are described as an instrument.",
    '21:17': "Wives and sons carried off, one boy left. The dynasty is reduced to a single life, and the promise with it.",
    '21:19': "\"His people made no burning for him.\" Asa got spices and a great fire; this king gets nothing.",
    '21:20': "\"Departed without being desired.\" Eight years on the throne and not one person sorry he is gone.",
    # ---- Chapter 22 ----
    '22:1': "The youngest is crowned because raiders killed his brothers. Succession by massacre, twice in two chapters.",
    '22:2': "His mother is named a daughter of Omri. David's house is now being advised out of Samaria.",
    '22:3': "\"His mother was his counsellor to do wickedly.\" The influence is named plainly and placed inside the family.",
    '22:7': "\"The destruction of Ahaziah was of God by coming to Joram.\" The visit he chose is the judgement he received.",
    '22:8': "Jehu's purge of Ahab's house catches the princes of Judah. Marrying into that house meant sharing its end.",
    '22:9': "He is given a grave for his grandfather's sake: \"the son of Jehoshaphat, who sought the LORD with all his heart.\"",
    '22:10': "Athaliah destroys the seed royal to keep power. The threat to David's line now comes from inside the palace.",
    '22:11': "A priest's wife steals a baby out of a slaughter. The covenant survives in a bedchamber, hidden by a woman.",
    '22:12': "Six years hidden in the house of God while Athaliah reigned. The temple is where the promise is kept alive.",
})

TAKEAWAYS.update({
    # ---- Chapter 23 ----
    '23:1': "Seven years of waiting, and then a priest takes five captains into covenant. The rescue is organised, not sudden.",
    '23:2': "The Levites are gathered out of every city. The network that carries the coup is the one that carries the worship.",
    '23:3': "\"As the LORD hath said of the sons of David.\" The rising is justified out of a promise, not out of grievance.",
    '23:6': "Even now the rule holds: only priests go in, \"for they are holy.\" Urgency does not suspend the order.",
    '23:7': "Levites with weapons in their hands around a boy king. The ministry stands guard over the covenant itself.",
    '23:8': "\"Jehoiada dismissed not the courses.\" He doubles his force by keeping both sabbath shifts on duty at once.",
    '23:9': "The weapons are David's own, stored in the house of God. The arsenal of the coup is a century of relics.",
    '23:11': "Crown and testimony together. A king of Judah is handed a book at the same moment he is handed a throne.",
    '23:13': "\"Treason, Treason\" — cried by the woman who took the throne by killing the family that owned it.",
    '23:14': "\"Slay her not in the house of the LORD.\" The execution is moved outside so the place is not defiled.",
    '23:16': "The covenant is that they \"should be the LORD's people.\" A reign begins by naming whose the nation is.",
    '23:17': "Baal's house comes down the same day. Removing the queen was not treated as finishing the work.",
    '23:18': "Offices set \"as it was ordained by David,\" with rejoicing and singing. Restoration means the rota starts again.",
    '23:19': "Porters set at the gates against anything unclean. An early act of the new order is to guard a threshold.",
    '23:20': "The king is brought down from the temple to the palace. Chronicles walks him out of the house that hid him.",
    '23:21': "\"The city was quiet.\" Six years of terror end, and the writer notes the quiet rather than the triumph.",
    # ---- Chapter 24 ----
    '24:2': "\"All the days of Jehoiada the priest.\" The qualifier is the whole chapter, and it is set down in advance.",
    '24:4': "\"Joash was minded to repair the house of the LORD.\" The reign's best idea is the upkeep of an old building.",
    '24:5': "\"See that ye hasten the matter. Howbeit the Levites hastened it not.\" The clergy stall the building fund.",
    '24:6': "The king has to ask the priest why the collection Moses commanded is not being collected.",
    '24:7': "Athaliah's sons had broken up the house and spent its dedicated things on Baalim. There is real damage to undo.",
    '24:8': "A chest set outside at the gate. Giving is made public, voluntary and easy, and the money starts arriving.",
    '24:10': "Princes and people cast in \"until they had made an end.\" What the officials would not do the crowd did gladly.",
    '24:12': "Masons, carpenters, workers in iron and brass. The holy house is mended by ordinary trades drawing wages.",
    '24:14': "The surplus becomes vessels, and offerings continue \"all the days of Jehoiada.\" That clause is a countdown.",
    '24:16': "A priest buried among the kings \"because he had done good in Israel.\" Honour paid for service, not for rank.",
    '24:17': "The princes bow, and the king hearkens. He was steady while an old man stood beside him, and no longer.",
    '24:18': "They abandon the house they have just finished repairing. A restored building guarantees nothing about a heart.",
    '24:19': "\"Yet he sent prophets to them... but they would not give ear.\" The wrath keeps sending warnings first.",
    '24:20': "Jehoiada's own son stands above the people and tells them why nothing prospers. The message is his inheritance.",
    '24:21': "Stoned in the temple court at the king's command. Jesus names this murder as the last blood charged to Israel.",
    '24:22': "The boy Jehoiada hid now kills Jehoiada's son. \"He remembered not the kindness\" is the mildest possible phrasing.",
    '24:23': "Syria destroys the princes of the people — the same princes whose flattery turned the king. The blow is aimed.",
    '24:24': "A small company routs a very great host. Chapter fourteen ran the other way, and the reason given is the same.",
    '24:25': "Killed on his sickbed by his own servants \"for the blood of the sons of Jehoiada.\" The dying man's plea is answered.",
    '24:26': "The assassins' mothers are named, an Ammonitess and a Moabitess. Foreigners avenge a murdered priest of Judah.",
    # ---- Chapter 25 ----
    '25:2': "\"Right in the sight of the LORD, but not with a perfect heart.\" The formula is granted and then withdrawn.",
    '25:3': "He waits until the kingdom is established before executing his father's assassins. Justice timed for safety.",
    '25:4': "He spares their children because the book of Moses forbids it. A king consults the law before taking revenge.",
    '25:5': "Three hundred thousand men. Jehoshaphat mustered over a million, and the shrinkage is left without comment.",
    '25:6': "A hundred talents buys a hundred thousand northern soldiers. The gap in the muster is filled with money.",
    '25:7': "\"The LORD is not with Israel.\" The hired troops are refused on grounds unrelated to their fitness to fight.",
    '25:8': "\"God hath power to help, and to cast down.\" Both verbs belong to one hand, and the king is left to choose.",
    '25:9': "\"But what shall we do for the hundred talents?\" The money already spent is the last argument against obeying.",
    '25:10': "The dismissed men go home in great anger. Obedience has just made Amaziah a hundred thousand enemies.",
    '25:12': "Ten thousand prisoners thrown off a cliff. Chronicles records the atrocity of a king it has just called obedient.",
    '25:13': "The rejected mercenaries sack Judah's own towns. The cost of listening to the prophet arrives on time.",
    '25:14': "He comes home from beating Edom and sets up Edom's gods. The winner adopts the religion of the losers.",
    '25:15': "\"Gods, which could not deliver their own people out of thine hand.\" The absurdity is the entire argument.",
    '25:16': "\"Art thou made of the king's counsel? forbear.\" The prophet is silenced by a reminder of his job description.",
    '25:17': "\"Come, let us see one another in the face.\" A challenge to war dressed up as a proposal to meet.",
    '25:18': "A thistle writes to a cedar, and a wild beast treads the thistle down. The insult is delivered as a fable.",
    '25:19': "\"Thine heart lifteth thee up to boast: abide now at home.\" Sound advice, and it arrives from an enemy.",
    '25:20': "\"For it came of God, that he might deliver them.\" The deafness is reported as the means of the judgement.",
    '25:21': "The battle falls at Bethshemesh, \"which belongeth to Judah.\" The war he picked is fought on his own ground.",
    '25:23': "Four hundred cubits of wall pulled down. Jerusalem is left open by a king who went looking for a fight.",
    '25:24': "Gold, vessels and hostages carried off to Samaria. The house of God funds a royal humiliation once again.",
    '25:27': "\"After the time that Amaziah did turn away\" the plotting began. The conspiracy is dated from the apostasy.",
})

TAKEAWAYS.update({
    # ---- Chapter 26 ----
    '26:1': "A sixteen-year-old is taken by the people after his father was murdered. The throne is filled quickly to keep it.",
    '26:4': "\"According to all that his father Amaziah did\" — which chapter twenty-five showed ending in idols and defeat.",
    '26:5': "\"As long as he sought the LORD, God made him to prosper.\" The clause holds the whole reign in one condition.",
    '26:6': "Philistine walls come down and Judahite towns go up among them. The frontier is pushed out for the first time in reigns.",
    '26:8': "\"He strengthened himself exceedingly\" — and the phrase is put down without praise, because of what follows.",
    '26:10': "Wells, cattle, husbandmen, vine dressers. \"He loved husbandry\" is set in the record as a mark in his favour.",
    '26:14': "Shields, spears, helmets, habergeons, bows and slings. A king who equips his men himself is an unusual sight here.",
    '26:15': "\"Marvellously helped, till he was strong.\" The sentence names both the gift and the point where it turned.",
    '26:16': "\"When he was strong, his heart was lifted up to his destruction.\" Success, not suffering, is what ruins this king.",
    '26:17': "Fourscore priests follow him in, described as valiant men. Resisting a king in his own temple took courage.",
    '26:18': "\"It appertaineth not unto thee.\" The office is not withheld out of spite; it was never granted to a king.",
    '26:19': "Censer in hand, angry at being corrected, and the leprosy rises in his forehead beside the incense altar.",
    '26:20': "They thrust him out and he hurries out himself. The man who forced his way in cannot leave quickly enough.",
    '26:21': "\"Cut off from the house of the LORD\" — the one place he insisted on entering is now closed to him for life.",
    '26:22': "Isaiah wrote the rest of these acts, and his own vision is dated from the year this king died.",
    '26:23': "Fifty-two years of reign, and the epitaph the burial party gives is \"He is a leper.\"",
    # ---- Chapter 27 ----
    '27:2': "\"He entered not into the temple of the LORD.\" One son learned the exact lesson of his father's leprosy.",
    '27:3': "He builds the high gate of the house of the LORD. The king who stayed out of the temple worked on it instead.",
    '27:5': "Ammon pays silver, wheat and barley for three years running. The tribute is itemised down to the grain.",
    '27:6': "\"Because he prepared his ways before the LORD.\" Might is stated as a result and never as an achievement.",
    '27:8': "The regnal formula is repeated word for word a few verses later. A quiet reign leaves little else to record.",
    '27:9': "Sixteen faithful years, and then Ahaz. Chronicles never lets a good reign be a guarantee of the next one.",
    # ---- Chapter 28 ----
    '28:1': "\"Not that which was right... like David his father.\" David remains the measure even for the kings who fail it.",
    '28:3': "He burnt his children in the fire. Judah is now doing what the nations were driven out of the land for doing.",
    '28:5': "Syria takes captives and Israel strikes him. The judgement arrives through the neighbours on both sides.",
    '28:6': "A hundred and twenty thousand valiant men in one day, \"because they had forsaken the LORD God of their fathers.\"",
    '28:7': "The king's son, the governor of the house and the man next to the king, all killed. The court itself is emptied.",
    '28:8': "Two hundred thousand of \"their brethren\" carried off to Samaria. The captives and the captors are one people.",
    '28:9': "\"Ye have slain them in a rage that reacheth up unto heaven.\" Being God's instrument did not licence the fury.",
    '28:10': "\"Are there not with you, even with you, sins against the LORD?\" The victors are asked to look at themselves.",
    '28:11': "\"Deliver the captives again.\" The prophet does not ask for repentance in general but for these people, released.",
    '28:12': "Four men of Ephraim are named for standing in front of their own returning army. Chronicles keeps their names.",
    '28:13': "\"Ye intend to add more to our sins.\" They refuse the slaves on the grounds of a guilt they already admit.",
    '28:14': "The armed men set the captives and the spoil down in front of the congregation and walk away from both.",
    '28:15': "Clothed, shod, fed, anointed, the feeble carried on asses to Jericho. Jesus tells this story again on a Samaritan road.",
    '28:16': "Ahaz sends to Assyria for help while northerners are nursing his people home. He asks the wrong nation.",
    '28:18': "The Philistines take the low-country towns \"and they dwelt there.\" The losses are not raids but settlements.",
    '28:19': "\"He made Judah naked.\" The defeats are traced to a king who stripped his own people of their defence.",
    '28:20': "\"Distressed him, but strengthened him not.\" The great power he paid for treats Judah as another province.",
    '28:21': "He empties the house of the LORD to buy Assyrian help, \"but he helped him not.\" The purchase failed outright.",
    '28:22': "\"In the time of his distress did he trespass yet more.\" Trouble drove this king further out, not back.",
    '28:23': "He sacrifices to the gods of Damascus because they beat him. Strength is mistaken for a reason to worship.",
    '28:24': "The vessels cut in pieces and the doors shut. A king of Judah closes the temple, and the next chapter opens it.",
    '28:27': "Buried in Jerusalem but kept out of the royal sepulchres. Even the grave records a verdict on the reign.",
})
