#!/usr/bin/env python3
"""Written takeaways for Daniel."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens by dating itself to a king of Judah who is about to lose everything he is named for.",
    '1:2': "\"The Lord gave Jehoiakim into his hand.\" Babylon's victory is reported as a handing over, not a defeat God suffered.",
    '1:3': "The king's seed and the princes are the ones conscripted. Exile arrives first as a career opening.",
    '1:4': "\"No blemish\" is sacrificial language. Babylon selects its servants the way Israel selected its offerings.",
    '1:5': "Three years of the king's food and the king's wine. Assimilation is fed rather than forced.",
    '1:7': "Every new name swaps the God of Israel out for a god of Babylon, and the book goes on using them.",
    '1:8': "He takes the learning, the tongue and the new name, and draws his line at the table.",
    '1:9': "The favour Daniel would need had already been given before he opened his mouth to ask.",
    '1:10': "The official's objection is not theology. It is his own head, and he says so plainly.",
    '1:12': "Ten days of pulse and water. He asks for a trial rather than an exemption, and makes it easy to grant.",
    '1:13': "\"As thou seest, deal with thy servants.\" He stakes the case on evidence and leaves the verdict with his keeper.",
    '1:15': "The result shows in the face after ten days, and the text mentions no miracle at all.",
    '1:16': "No decree changes anything. The steward simply stops bringing the portion, and the arrangement holds.",
    '1:17': "God gives them the Chaldean learning they were conscripted to acquire. The captor's curriculum is his gift.",
    '1:19': "They win the king's own examination in the very schooling they had refused to be defiled by.",
    '1:20': "Ten times better than the magicians, in a court where wisdom was the only currency that bought safety.",
    '1:21': "Daniel outlasts the empire that took him, and is still standing when the exile's end arrives.",
}

TAKEAWAYS.update({
    # ---- Chapter 2 ----
    '2:1': "The most powerful man alive cannot command his own sleep, and the book begins its argument there.",
    '2:4': "\"O king, live for ever\" is automatic flattery, and it is the last confident thing these men say.",
    '2:5': "He demands the dream itself, precisely so that the interpretation cannot be invented to fit.",
    '2:8': "\"Ye would gain the time.\" He reads them correctly: delay is the only instrument they actually own.",
    '2:9': "The king describes the trade's real method aloud — lying words held until the situation changes.",
    '2:10': "The experts confess the limit of their entire profession, and the confession happens to be true.",
    '2:11': "\"The gods, whose dwelling is not with flesh.\" They state the problem the rest of the book answers.",
    '2:12': "The failure of a few experts is charged to every expert in the city. Tyranny does not sort.",
    '2:14': "He answers an executioner with counsel and wisdom. No panic, no protest, and no speech.",
    '2:15': "One question, put to the right man, buys him the whole story that the decree left out.",
    '2:16': "Daniel asks the king for the very thing the king had just refused the Chaldeans — time.",
    '2:17': "The first use he makes of the delay is to go home and tell three other men what is coming.",
    '2:18': "They ask for mercies, not for cleverness. The secret is treated as something begged, never extracted.",
    '2:19': "The answer arrives the same way the problem did, as a vision in the night.",
    '2:20': "Wisdom and might are his. Daniel blesses the giver before he makes any use of the gift.",
    '2:21': "\"He removeth kings, and setteth up kings\" — sung quietly in the house of a king who removes people.",
    '2:22': "He knows what is in the darkness, and the light dwells with him. Nothing is hidden on that side.",
    '2:23': "He thanks the God of his fathers, using the family name in a city that had renamed him.",
    '2:24': "His first act with the revelation is to save the pagan experts who could not obtain it.",
    '2:25': "\"I have found a man.\" Arioch presents himself as the discoverer of what he merely carried.",
    '2:27': "Daniel opens by agreeing with the men he is rescuing: this cannot be done by anyone here.",
    '2:28': "\"But there is a God in heaven that revealeth secrets.\" The answer to human limit is not a better expert.",
    '2:29': "The dream grew out of the king's own night thoughts about the future, and God met him inside them.",
    '2:30': "He disclaims the credit before anyone offers it. The gift does not make him the exception.",
    '2:31': "The king's picture of history was one enormous man, and the sight of it frightened him.",
    '2:33': "The whole weight of the figure comes down on feet that are half baked clay.",
    '2:34': "\"Cut out without hands\" — the one thing in the vision that no one manufactured.",
    '2:35': "The metals blow away as chaff and the stone becomes a mountain. Only what nobody made grows.",
    '2:36': "\"We will tell the interpretation.\" He keeps the three men who prayed with him inside the answer.",
    '2:37': "The title king of kings is granted, and in the same breath traced to someone above him.",
    '2:38': "\"Thou art this head of gold.\" Being the best part of the statue is still being part of what falls.",
    '2:40': "Iron breaks everything it touches. In this dream that is a description and not a compliment.",
    '2:43': "Marriages and alliances are tried, and iron still will not hold clay together.",
    '2:44': "The lasting kingdom is set up in the days of these kings, not after the last of them has gone.",
    '2:45': "\"The dream is certain, and the interpretation thereof sure.\" The vision closes by vouching for itself.",
    '2:46': "The king falls down before the interpreter. He has heard the message and mistaken the messenger.",
    '2:47': "He adds Daniel's God to the top of his list of gods. Confession is not yet conversion.",
    '2:48': "The reward for \"not for any wisdom that I have\" is rule over every wise man in Babylon.",
    '2:49': "He spends his promotion on the three who prayed with him, and keeps the gate for himself.",
})

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "The head of gold builds himself a statue of gold all the way down. The dream's limit is what he refuses.",
    '3:3': "The whole administration is assembled and made to stand in front of it. Worship here is an office duty.",
    '3:4': "\"O people, nations, and languages.\" The reach of the command is a large part of the point of it.",
    '3:5': "An orchestra rather than an argument. The signal to bow is a sound, and thought is not invited.",
    '3:6': "The alternative to worship is announced in the same breath as the invitation to it.",
    '3:7': "All the people fell down. The text lets the unanimity stand a while before reporting the exception.",
    '3:8': "The accusers are the guild Daniel had saved from the king's decree one chapter earlier.",
    '3:12': "The charge is dressed as a personal slight to the king, which is how informers get a hearing.",
    '3:13': "The man who worshipped Daniel's God in chapter two is enraged by three men who take it seriously.",
    '3:15': "\"Who is that God that shall deliver you out of my hands?\" The rest of the chapter is the answer.",
    '3:16': "\"We are not careful to answer thee in this matter.\" They decline to argue a question already settled.",
    '3:17': "They confess both that God is able and that he will deliver, and neither is theirs to guarantee.",
    '3:18': "\"But if not\" — the faith here is not resting on the rescue arriving, and says so before the fire.",
    '3:19': "Seven times hotter alters nothing about the outcome and everything about the state of the king.",
    '3:21': "The coats, hosen and hats are itemised now because the fire will be asked about them afterward.",
    '3:22': "The flame kills the men who carried them. It was hot enough; that was never in question.",
    '3:23': "They fall in bound. The last thing reported of the three is that they were tied.",
    '3:24': "He has to ask his own counsellors to confirm the arithmetic of the sentence he gave.",
    '3:25': "Four, and loose. The only thing the fire consumed was the rope the king put on them.",
    '3:26': "The king walks to the furnace mouth himself and calls them out by a title he has just granted their God.",
    '3:27': "The officials are made to inspect them. The deliverance goes into the record with witnesses attached.",
    '3:28': "He blesses God for men who defied him, and names what he is praising: they yielded their bodies.",
    '3:29': "His new reverence takes the only shape he knows, another decree threatening houses and limbs.",
    '3:30': "It ends in promotion, not escape. They go back to the same posts under the same king.",
})

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:1': "The chapter is a royal circular. A pagan king publishes his own humiliation over his own seal.",
    '4:2': "\"Wrought toward me.\" He files what was done to him under wonders done for him.",
    '4:3': "A man whose kingdom stopped for seven times is the one calling another kingdom everlasting.",
    '4:4': "At rest and flourishing. The dream finds him at the point where nothing needed to change.",
    '4:5': "He is afraid of the dream before he knows what it says. Some warnings land ahead of their content.",
    '4:7': "The magicians fail the same king in the same way a second time, and he calls them in anyway.",
    '4:8': "He still names Daniel for his own god and still says gods, plural. The furnace altered his vocabulary very little.",
    '4:10': "A tree at the centre of the earth. The dream hands him the position he already believed he held.",
    '4:11': "A height that reaches heaven is the dream's warning and the king's ambition in the same image.",
    '4:12': "The tree feeds and shelters everything under it. This greatness is genuinely useful before it is felled.",
    '4:14': "The sentence is cried aloud in the dream before anything happens. Judgment here is announced first.",
    '4:15': "\"Nevertheless leave the stump.\" The mercy sits in the clause the sentence did not require.",
    '4:16': "The punishment is to be given the heart he had been ruling by all along.",
    '4:17': "The stated purpose is public instruction, and it includes that heaven gives power to the basest of men.",
    '4:19': "Daniel sits an hour and wishes the dream were about somebody else. He takes no pleasure in it.",
    '4:22': "\"It is thou, O king.\" He says it to a man who had recently heated a furnace over less.",
    '4:24': "What the watchers cried is now called the decree of the most High. That court speaks with one voice.",
    '4:25': "The sentence runs till thou know. Its end is knowledge, and the grass is the means.",
    '4:26': "The kingdom is held for him rather than taken, kept in trust until he learns who lends it.",
    '4:27': "Daniel adds counsel to the interpretation, and offers mercy to the poor to a tyrant as a live option.",
    '4:28': "\"All this came upon the king.\" One flat sentence carries the whole distance from warning to ruin.",
    '4:29': "Twelve months of nothing happening, and the warning had evidently worn off by the end of them.",
    '4:30': "\"Great Babylon, that I have built by the might of my power.\" Three possessives inside one sentence.",
    '4:31': "The word was still in his mouth. The boast is not permitted to reach its own full stop.",
    '4:33': "The head of gold ends in a field, with the hair and the claws of the thing he had become.",
    '4:34': "Understanding returns when the eyes go up. The looking comes first and the mind follows it.",
    '4:35': "\"None can stay his hand, or say unto him, What doest thou?\" The restored king states it without complaint.",
    '4:36': "He receives the kingdom back with majesty added. The humbling turned out not to be the end of him.",
    '4:37': "His last recorded words are about the abasing of pride, and he is the exhibit he is citing.",
})

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "A thousand lords and a king drinking in front of them. Everything in this chapter is done in public.",
    '5:2': "The vessels his father only stored away, the son drinks from. Each generation finds a new use for what it inherits.",
    '5:4': "The metals of Nebuchadnezzar's statue are recited again, this time as a list of gods being toasted.",
    '5:5': "Fingers, and no arm attached. The king sees only the part of the hand that does the writing.",
    '5:6': "The knees deliver the verdict before anybody has managed to read the writing.",
    '5:7': "He offers third place in the kingdom, which is the most a man who is himself second can give.",
    '5:8': "The wise men of Babylon cannot read the writing on a Babylonian wall.",
    '5:10': "The queen walks into a feast she was not attending, and is the one person present who remembers anything.",
    '5:11': "\"Thy father, the king, I say, thy father.\" She repeats it until it lands, because the lesson was available.",
    '5:12': "Daniel had been in the kingdom the whole time — remembered by a woman, forgotten by the court.",
    '5:13': "The king introduces him by his captivity, the one fact about Daniel that has never changed.",
    '5:17': "\"Let thy gifts be to thyself.\" He refuses the fee and reads the writing anyway.",
    '5:18': "Before a word of the writing is read, Daniel makes him sit through his own father's story.",
    '5:19': "Absolute power is described exactly and then sourced: the majesty was given him by someone.",
    '5:20': "\"When his heart was lifted up.\" The fall is dated to the pride, not to any political cause.",
    '5:21': "The grass and the dew are recited to a son who had been treating them as a family anecdote.",
    '5:22': "The charge is not ignorance. He knew all this, and the knowing is what convicts him.",
    '5:23': "The gods he praised cannot see or hear; the God whose cups he drinks from holds his breath.",
    '5:25': "Four words nobody in Babylon could read, and they turn out to be weights and measures.",
    '5:26': "Numbered, and finished. The counting had been running quietly through every course of the feast.",
    '5:27': "\"Weighed in the balances, and art found wanting.\" The verdict is a shortfall rather than a charge sheet.",
    '5:28': "The kingdom is not abolished but handed over, and the successors are already named.",
    '5:29': "He pays out the reward for his own death sentence, and keeps the ceremony exactly to the letter.",
    '5:30': "\"In that night.\" Between the chain of gold and the end there is no interval at all.",
    '5:31': "The empire changes hands in one line, with the new king's age attached, like a clerk's note.",
})

TAKEAWAYS.update({
    # ---- Chapter 6 ----
    '6:2': "Daniel's post is an audit: the king should have no damage. He is trusted with the money.",
    '6:3': "A foreign captive is about to be set over native princes, and that is the engine of the whole chapter.",
    '6:4': "They audit the auditor and find nothing. His ordinary work survives hostile inspection.",
    '6:5': "The only way to make him a criminal is to make the law of his God illegal.",
    '6:7': "Thirty days is a small vanity, short enough to look harmless to the man asked to sign it.",
    '6:8': "They flatter him into a law he cannot repeal. Irrevocability is sold to a king as dignity.",
    '6:10': "\"As he did aforetime.\" He changes nothing at all, and that is the entire act of defiance.",
    '6:11': "They assemble to catch him and find precisely what they already knew they would find.",
    '6:12': "They make the king affirm his own decree before they name the man it is going to kill.",
    '6:13': "They call him a captive rather than a president. His foreignness is the charge, dressed as legality.",
    '6:14': "The king spends the day labouring to escape a law he made. He is caught by his own signature.",
    '6:15': "They return to quote his statute back at him. The trap holds the king as tightly as it holds Daniel.",
    '6:16': "The pagan king preaches deliverance at the den's mouth, and nobody else in the chapter says it.",
    '6:17': "Sealed with the king's own signet, so that nobody can rescue Daniel — the king included.",
    '6:18': "The man outside the den keeps the vigil, fasting, and his sleep goes from him.",
    '6:20': "\"Is thy God able to deliver thee?\" Chapter three's taunt, asked now by a king hoping for yes.",
    '6:21': "Daniel answers from the pit with the ordinary court greeting, entirely unchanged.",
    '6:22': "The mouths were shut, not the lions removed. The deliverance happens inside the den.",
    '6:23': "The reason is given outright, and it is not his innocence: because he believed in his God.",
    '6:24': "The lions were never tame, and the accusers demonstrate it on the way to the bottom.",
    '6:26': "A Persian decree confesses a kingdom that shall not be destroyed — Daniel's own visions in a king's words.",
    '6:28': "The book keeps ending its chapters the same way: the empire changes and Daniel is still there.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:1': "Daniel dreams now instead of interpreting, and the first thing he does with it is write it down.",
    '7:2': "Four winds striving on the great sea. The beasts come up out of chaos rather than out of nowhere.",
    '7:4': "The first beast is given a man's heart, which in chapter four was a mercy rather than a promotion.",
    '7:5': "A bear with ribs still between its teeth, told to devour more. Appetite is the entire description.",
    '7:6': "\"Dominion was given to it.\" Even the beasts hold their power on loan from somewhere else.",
    '7:7': "The fourth beast is likened to no animal at all. There was nothing available to compare it to.",
    '7:8': "The small horn is the dangerous one, and what makes it dangerous is a mouth speaking great things.",
    '7:9': "The vision cuts from beasts to a courtroom. The answer to the horn is a session, not an army.",
    '7:10': "The books were opened. Judgment here proceeds on a record rather than on a show of strength.",
    '7:11': "The beast is destroyed because of the voice of the great words. The court convicts on speech.",
    '7:12': "The other beasts lose their dominion and keep their lives. Not every ending here is an execution.",
    '7:13': "One like the Son of man comes with the clouds and is brought near. He arrives from the human side.",
    '7:14': "Dominion is given to him as it was given to the beasts — and this is the one grant never taken back.",
    '7:15': "The man who read other men's dreams without flinching is undone by the one he has himself.",
    '7:17': "The beasts are four kings out of the earth. The text supplies its own key, and keeps it short.",
    '7:18': "The kingdom passes to the saints of the most High. They receive it; they are never said to take it.",
    '7:19': "He asks about the fourth beast and lets the first three go. The weight of the vision is at its end.",
    '7:21': "The horn prevails against the saints. The vision does not pretend they win the intervening battles.",
    '7:22': "\"Until the Ancient of days came.\" The whole comfort of the chapter rides on one word of time.",
    '7:24': "The horns are counted out as kings. Daniel's symbols are explained inside Daniel before anyone else tries.",
    '7:25': "\"Wear out the saints\" — attrition rather than massacre, and a term is set on it before it starts.",
    '7:27': "The greatness under the whole heaven is handed to a people who are never described as seizing anything.",
    '7:28': "He is left shaken, holding a vision he cannot use, and keeps the matter in his heart.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "A second vision inside the same reign. The book stacks them up before the kingdom actually falls.",
    '8:3': "The higher horn came up last. The junior partner ends on top, and the vision takes note of it.",
    '8:4': "\"None that could deliver out of his hand\" — Nebuchadnezzar's own boast, now made by an animal.",
    '8:5': "A goat that does not touch the ground. Speed is nearly the whole character of this kingdom.",
    '8:7': "The ram nobody could deliver from is trampled, and nobody delivers the ram either.",
    '8:8': "The great horn breaks when he was strong. That is the one hour power never plans for.",
    '8:9': "Another little horn, and this one grows toward the pleasant land where the sanctuary stands.",
    '8:10': "It reaches at the host of heaven. Ambition in this book climbs upward before it turns cruel.",
    '8:11': "What is taken away is the daily sacrifice. The attack falls on the ordinary service, not on a doctrine.",
    '8:12': "\"It practised, and prospered.\" The vision concedes the success plainly before it names the limit.",
    '8:13': "\"How long?\" is the only question the holy ones ask, and it is the question of the persecuted.",
    '8:14': "A number is given, and it ends in the sanctuary being cleansed rather than in an enemy destroyed.",
    '8:16': "A voice has to order Gabriel to explain. Even the interpreting angel is under instruction here.",
    '8:17': "He is called son of man while lying on his face. The title and the posture arrive together.",
    '8:19': "The indignation has a last end and the end has an appointment. Neither is left open.",
    '8:20': "The kingdoms are named outright. Daniel's symbols are not left for later readers to assign.",
    '8:21': "Grecia and its first king are named well ahead of them, and the text does it without ceremony.",
    '8:23': "He rises when the transgressors are come to the full. Tyrants arrive into a room already prepared.",
    '8:24': "\"Mighty, but not by his own power.\" Even this king's strength is on loan from somewhere.",
    '8:25': "\"Broken without hand\" — the stone's phrase from chapter two, used again on the same kind of end.",
    '8:26': "Seal it up, because it is for many days. Some answers are not given for the use of the man who gets them.",
    '8:27': "He is sick for days, then rises and does the king's business. The vision does not excuse the day's work.",
})

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:2': "The greatest vision in the book begins with a man reading Jeremiah and counting years.",
    '9:3': "Finding the promise nearly due, he prays for it rather than waiting quietly for the calendar.",
    '9:4': "The great and dreadful God and the keeper of covenant and mercy are addressed in a single breath.",
    '9:5': "\"We have sinned.\" The one man in six chapters with no charge against him puts himself inside it.",
    '9:6': "The sin named first is not idolatry but not listening. The prophets were sent and were heard out.",
    '9:7': "Righteousness to God, confusion of faces to us. The confession divides the two without negotiating.",
    '9:9': "Mercies and forgivenesses are listed as belonging to God, like righteousness. They are his property.",
    '9:11': "The exile is read as the written covenant working exactly as written, not as God failing to keep it.",
    '9:12': "The worst thing that ever happened to Jerusalem is described as God confirming his words.",
    '9:13': "The evil came and still nobody prayed. Suffering by itself does not manufacture repentance.",
    '9:14': "He calls the LORD righteous in all his works, with the ruins of the city as the works in question.",
    '9:15': "He reaches for the exodus as precedent and follows it straight back into confession.",
    '9:16': "He asks for the city on the ground that it is God's city and his holy mountain.",
    '9:17': "\"For the Lord's sake.\" The petition is staked on God's own interest, not on the petitioner's record.",
    '9:18': "\"Not for our righteousnesses, but for thy great mercies.\" The blameless man refuses to plead his file.",
    '9:19': "Hear, forgive, hearken and do. The sentences shorten to single words as the prayer runs out of argument.",
    '9:21': "The answer lands at the hour of an evening oblation that has not been offered in Jerusalem for years.",
    '9:22': "The reply to a prayer about sin is skill and understanding. He asked for mercy and is handed a calendar.",
    '9:23': "The commandment went out at the beginning of the supplication, and the reason given is that he is beloved.",
    '9:24': "Six things are determined, and every one of them is done to sin rather than to Israel's enemies.",
    '9:25': "The street and the wall go up in troublous times. Restoration is promised, and ease is not.",
    '9:26': "\"Cut off, but not for himself.\" Four words that the New Testament spends itself unfolding.",
    '9:27': "A covenant confirmed with many, and the sacrifice stopped mid-week. Jeremiah's seventy years open into this.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "\"The thing was true, but the time appointed was long.\" The book states its own difficulty outright.",
    '10:2': "Three full weeks of mourning, with no reason given. The grief arrives before the vision explains it.",
    '10:3': "The man who once refused the king's meat refuses it again, this time as mourning rather than as a line.",
    '10:5': "Linen and a girdle of gold — a priest's dress, worn by the figure standing beside the river.",
    '10:6': "Nearly every phrase here is taken up again by John to describe the one walking among the lampstands.",
    '10:7': "The men with him feel the terror without seeing the cause, and run from something they cannot see.",
    '10:8': "The vision leaves him with no strength at all. Meeting God's messenger is nowhere reported as encouraging.",
    '10:10': "A hand raises him only as far as his knees and palms. The recovery is made in stages.",
    '10:11': "He is told he is greatly beloved, and he stands up trembling. Both are true in the same moment.",
    '10:12': "His words were heard on the first day. The three weeks of silence were not three weeks of delay.",
    '10:13': "The delay was a battle. The reader is told only because Daniel could never have guessed it.",
    '10:14': "The messenger comes to explain, and says plainly that the vision is for days a long way off.",
    '10:16': "His lips have to be touched before he can speak, and the first thing he says is that it hurts.",
    '10:18': "He is touched a second time and strengthened again. The help is repeated without any reproach.",
    '10:19': "\"Be strong, yea, be strong.\" The strength comes in the saying of it and not out of the man.",
    '10:20': "The messenger goes back to a fight that is not finished. The errand was an interval in a war.",
    '10:21': "There is a scripture of truth already written, and the next chapter is read aloud out of it.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "The angel's previous posting was propping up a Median king. Heaven's help had reached a pagan throne.",
    '11:2': "Riches rather than armies are what stir up the realm of Grecia. Wealth starts the war.",
    '11:3': "\"Shall do according to his will\" — the verdict this chapter hands to conqueror after conqueror.",
    '11:4': "The kingdom is divided to the four winds and not to his posterity. He cannot bequeath what he seized.",
    '11:6': "A marriage arranged to hold two kingdoms together, and every person involved in it is disposed of.",
    '11:7': "Her own family produces the avenger. The alliance failed and the blood tie did not.",
    '11:8': "Captured gods carried off to Egypt with the silver and the princes, itemised as part of the inventory.",
    '11:10': "The sons take up the quarrel. Nothing in this chapter ends with the generation that began it.",
    '11:11': "Anger raises a great multitude and the multitude is handed to the other side. Rage makes a poor general.",
    '11:12': "He wins and is not strengthened by it. A victory that lifts up the heart shows as a loss here.",
    '11:14': "Men of Daniel's own people try to force the vision along by force of arms, and fall doing it.",
    '11:15': "Siege mounts and fenced cities, and not even chosen troops can find the strength to withstand.",
    '11:17': "A daughter is spent as a weapon and declines to work as one. She shall not stand on his side.",
    '11:19': "He turns home to his own fort, stumbles, and is not found. The great ones here go out quietly.",
    '11:20': "A raiser of taxes on the throne, destroyed within days, neither in anger nor in battle.",
    '11:21': "They will not give him the honour of the kingdom, so he obtains it by flatteries, which cost less.",
    '11:22': "Swept away with the rest is the prince of the covenant. The violence reaches the sanctuary's own men.",
    '11:23': "He grows strong on a small people by way of a league he never intended to keep.",
    '11:24': "He buys loyalty by scattering plunder, which his fathers never did. Generosity is used here as a weapon.",
    '11:26': "The men who eat the portion of his meat destroy him. The betrayal comes from inside the household.",
    '11:27': "Two kings lying to each other across one table, and neither of them governs the appointed time.",
    '11:28': "He goes home rich and turns his heart against the holy covenant. Plunder settles nothing in him.",
    '11:30': "Checked by ships abroad, he takes it out on the covenant, and finds collaborators already waiting.",
    '11:31': "The daily sacrifice taken away and the abomination set up — the phrase Jesus hands back to his disciples.",
    '11:32': "Flatteries corrupt more of them than force does, and the ones who know their God are the ones who hold.",
    '11:33': "The teachers instruct many and are killed for it. Understanding turns out to be no sort of protection.",
    '11:34': "A little help arrives, and with it people who attach themselves for reasons that will not last.",
    '11:35': "The fall of the wise is given a purpose — to purge and make white — rather than left as a defeat.",
    '11:36': "He prospers only till the indignation is accomplished. The blasphemy runs on a term already fixed.",
    '11:37': "He honours nothing inherited and nothing human. Self-magnifying ends by leaving a man no attachments.",
    '11:38': "The one god he will pay for is the god of forces. He funds his own armoury and calls it worship.",
    '11:39': "The land is divided for gain. Even the strange god he acknowledges is worked as a property scheme.",
    '11:41': "Edom, Moab and Ammon escape out of his hand. Israel's old enemies are passed over by this particular flood.",
    '11:44': "A rumour unsettles the man no army could, and he answers the tidings with a massacre.",
    '11:45': "He pitches his palace on the glorious holy mountain and dies there, with none to help him.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:1': "Deliverance runs by a book with names written in it, and it comes in the worst trouble rather than instead of it.",
    '12:2': "The plainest resurrection sentence in the Old Testament, and it wakes people in both directions.",
    '12:3': "The ones who shine are the teachers. The glory here is promised for what they said to other people.",
    '12:4': "He is told to seal the words. The book closes by admitting it is not finished being understood.",
    '12:6': "At the close of the book the question comes round again, put now to the man clothed in linen himself.",
    '12:7': "He lifts both hands to swear it. An oath is offered because the answer is a number nobody can verify.",
    '12:8': "\"I heard, but I understood not.\" The prophet is left standing outside his own prophecy.",
    '12:9': "The answer to his question is a dismissal. He is sent on his way without the explanation.",
    '12:10': "Understanding is sorted by purifying, not by cleverness. The wicked do wickedly and see nothing.",
    '12:12': "\"Blessed is he that waiteth\" — and the day he waits to is later than the one just named.",
    '12:13': "He is promised rest and a place at the end, and for the interval nothing but going his way.",
})
