#!/usr/bin/env python3
"""Written takeaways for Exodus 23-40."""

TAKEAWAYS = {
    # ---- Chapter 23 ----
    '23:1': "False witness begins with what you are willing to repeat. The rumour is named before the courtroom is.",
    '23:2': "\"Thou shalt not follow a multitude to do evil.\" Numbers are treated as a pressure, never as a defence.",
    '23:3': "Even the poor man gets no thumb on the scale. Justice is not pity with the verdict already decided.",
    '23:4': "The enemy's stray ox goes back to him. The law commands the act and waits for the feeling to catch up.",
    '23:5': "Help is commanded exactly where you \"wouldest forbear\" to give it. The reluctance is assumed and overruled.",
    '23:6': "Having barred favouritism toward the poor, the law turns at once to the far commoner sin of ruling against him.",
    '23:7': "\"I will not justify the wicked.\" Israel's courts are told to imitate a judge who will not acquit the guilty.",
    '23:8': "The gift blinds the wise. The law assumes a bribe works, which is why it forbids taking one at all.",
    '23:9': "\"Ye know the heart of a stranger.\" Their own years in Egypt are made the ground of their kindness.",
    '23:10': "Six years of sowing are granted before the seventh is asked back. The command presumes a harvest first.",
    '23:11': "The fallow year is for the poor and the wild beasts to eat. Rest is legislated as redistribution.",
    '23:12': "The sabbath is argued here for the ox, the slave's son and the stranger — the ones with no power to claim it.",
    '23:13': "Even the names of other gods are to go unspoken. Idolatry is treated as something that starts in the mouth.",
    '23:15': "The feast is dated by the exodus, and none appear empty. Worship remembers a rescue and brings something.",
    '23:16': "Harvest and ingathering: the festivals are pinned to the farming year, so faith keeps time with work.",
    '23:17': "Three times a year every male leaves home and land undefended and goes up. Obedience here costs security.",
    '23:19': "The firstfruits go to God before the owner knows whether the rest of the crop will be enough.",
    '23:20': "An Angel to keep them in the way and bring them to a place already prepared. The destination precedes the journey.",
    '23:21': "\"My name is in him.\" This messenger is not a stand-in for God's presence but the form of it.",
    '23:22': "The covenant is put in personal terms: God undertakes to hold Israel's enemies as his own.",
    '23:24': "Refusing their gods is not enough; the images come down. A tolerated idol becomes an inherited one.",
    '23:25': "Bread, water, health. The blessing promised for serving the LORD is entirely ordinary and entirely material.",
    '23:27': "\"I will send my fear before thee.\" The first weapon named in the conquest is not Israel's sword.",
    '23:29': "The land is not cleared in one year, lest it go wild. God's slowness here is protection, not reluctance.",
    '23:30': "\"By little and little I will drive them out.\" Possession is paced to what Israel can actually hold.",
    '23:32': "No treaty with them or their gods. Israel may not make peace with what would make it comfortable.",
    '23:33': "The reason given for removal is not their blood but the snare: \"lest they make thee sin against me.\"",

    # ---- Chapter 24 ----
    '24:1': "Seventy elders are summoned up the mountain and told to worship afar off. Access is granted and bounded at once.",
    '24:2': "\"Moses alone shall come near.\" A mediator is defined by where he is permitted to stand.",
    '24:3': "\"All the words which the LORD hath said will we do.\" The promise is unanimous, sincere, and already doomed.",
    '24:4': "Moses writes the words down. The covenant becomes a text before it can become a memory.",
    '24:5': "Young men do the sacrificing. There is no priesthood yet; the blood comes before the institution.",
    '24:6': "Half the blood on the altar, half held back for the people. The covenant marks both parties to it.",
    '24:7': "The book is read aloud and they consent a second time, now having actually heard the terms.",
    '24:8': "\"Behold the blood of the covenant.\" These are the words Jesus will take up over a cup.",
    '24:10': "\"They saw the God of Israel\" — and the verse describes the pavement under his feet. Even here it looks down.",
    '24:11': "He laid not his hand on them: they saw God, and ate and drank. A meal, not a funeral.",
    '24:12': "The tables are written by God and given so Moses can teach them. Revelation is meant to be passed on.",
    '24:13': "Joshua goes up as far as he is allowed. The next leader is being formed in the margins of this story.",
    '24:14': "Aaron and Hur are left holding the camp. The disaster of chapter 32 has just been staffed.",
    '24:16': "Six days in the cloud before the voice comes on the seventh. Even Moses is made to wait inside the glory.",
    '24:17': "From below, the same glory looked like devouring fire. The presence is welcome and terrifying at once.",
    '24:18': "Forty days and forty nights. The length of the delay the people will not manage to sit through.",

    # ---- Chapter 25 ----
    '25:2': "The offering is taken only from those who give willingly. God's dwelling is funded by consent, not by levy.",
    '25:3': "Gold, silver and brass — the plunder carried out of Egypt comes back as the raw material of worship.",
    '25:5': "The outermost covering is badgers' skin. What holds the glory is wrapped on the outside in something plain.",
    '25:6': "Oil, spices and incense are on the list: part of the offering exists to be burned up and gone.",
    '25:7': "Stones for the ephod and the breastplate are budgeted before a priest has been named to wear them.",
    '25:8': "\"That I may dwell among them.\" The purpose is stated before a single measurement is given.",
    '25:9': "Nothing here is invented. The tabernacle is made after a pattern shown, not designed by the devout.",
    '25:11': "Overlaid with gold within and without — including the inside, where no eye would ever check.",
    '25:14': "The ark is built to be carried by poles. The holiest object is never meant to be handled directly.",
    '25:15': "The staves are never taken out. A settled people keep the ark permanently ready to move.",
    '25:16': "What goes inside the golden box is the testimony — the law that stands against the people who carry it.",
    '25:17': "The mercy seat is given a length and a breadth and no height. It is a lid, and it is the meeting place.",
    '25:18': "Cherubim over the mercy seat: the guardians who barred Eden now stand above the place where blood is put.",
    '25:20': "Their faces look toward the mercy seat. Even the angels' attention is fixed on the place of atonement.",
    '25:22': "\"There I will meet with thee\" — from above the mercy seat, over the ark. God speaks from the lid, not the tablets.",
    '25:30': "Shewbread before him always. The sign is not a sacrifice offered but a table kept set.",
    '25:31': "The lampstand is described in the words for a plant — shaft, branches, blossoms. Gold made to look alive.",
    '25:36': "\"One beaten work of pure gold.\" Nothing about the light is assembled out of parts.",
    '25:37': "Seven lamps, and the only light in the holy place is the light God himself specified.",
    '25:38': "Even the tongs and the snuffdishes are pure gold. Nothing near the light is allowed to be ordinary.",
    '25:39': "A talent of gold for the lampstand alone. The text names the cost without apologising for it.",
    '25:40': "\"After their pattern, which was shewed thee in the mount.\" Hebrews will read this tent as a copy of something.",
}

TAKEAWAYS.update({
    # ---- Chapter 26 ----
    '26:1': "Cherubim are woven into the innermost curtains. The guardians of Eden are overhead as well as over the ark.",
    '26:2': "\"Every one of the curtains shall have one measure.\" Nothing in the sanctuary is left to improvisation.",
    '26:6': "Fifty gold clasps, \"and it shall be one tabernacle.\" Many separate pieces are joined so the result can be called one.",
    '26:7': "Goats' hair goes over the embroidered linen. The beauty is put underneath, where only priests will ever see it.",
    '26:11': "Brass clasps here where the inner curtains had gold. The further out from the ark, the plainer the metal.",
    '26:12': "A half curtain is left over to hang down the back. The covering is cut generous enough to have remainder.",
    '26:14': "Rams' skins and badgers' skins on top. From outside, the dwelling place of God looks like a weathered tent.",
    '26:15': "The frame is desert acacia, standing up. God's house is built from what the wilderness actually grows.",
    '26:19': "Every board stands in sockets of silver. The whole weight of the structure rests on its footings, not its gold.",
    '26:28': "One bar runs the whole length inside the boards, holding the side together where nobody can see it.",
    '26:31': "Cherubim on the veil as well. The same figures that guard the mercy seat are woven into the barrier before it.",
    '26:33': "\"The vail shall divide.\" Even the house built so God could dwell among them has a wall inside it.",
    '26:35': "Table on the north, lampstand on the south. Bread and light stand facing each other across the room.",
    '26:36': "The way into the tent is a hanging, not a door. There is an entrance, and it is only cloth.",

    # ---- Chapter 27 ----
    '27:1': "The altar is larger than the ark and stands first in the court. Sacrifice is what you meet before anything else.",
    '27:2': "The horns are of one piece with the altar. These are the horns a frightened man will later grab and hold.",
    '27:3': "Pans, shovels, basons, fleshhooks. The furniture of worship is a butcher's kit; approaching God is bloody work.",
    '27:7': "The altar travels too. Israel's place of sacrifice moves with the camp instead of anchoring it to a site.",
    '27:8': "\"Hollow with boards.\" The altar is a shell, not a block of stone. Its weight was never what made it holy.",
    '27:9': "The court is walled with linen. The boundary around holiness is something a man could cut through and does not.",
    '27:16': "The gate is twenty cubits of blue, purple and scarlet in a wall of plain white. The way in is coloured to be found.",
    '27:18': "Five cubits high — the hangings stand over a man's head. The court does not only mark the line, it blocks the view.",
    '27:19': "Even the tent pins are specified, and they are brass. The smallest fittings are not beneath God's instruction.",
    '27:20': "The lamp burns always because the people keep bringing oil. Continual worship runs on somebody's daily errand.",
    '27:21': "Aaron tends the light from evening to morning. The holy place is kept lit through the hours nobody is watching.",

    # ---- Chapter 28 ----
    '28:1': "Aaron is named priest before he has done anything to deserve it — and Nadab and Abihu are named with him.",
    '28:2': "\"For glory and for beauty.\" The vestments are given an aesthetic reason and no practical one.",
    '28:3': "The wise hearted are said to be filled with the spirit of wisdom to sew. Craft is treated as a gift of God.",
    '28:4': "Six garments are listed. The priest is dressed head to foot; nothing of him shows when he serves.",
    '28:9': "The tribes' names are cut into stone. The people are made permanent in what the priest wears.",
    '28:10': "The names are ordered by birth. No tribe earns its place on the stone, and none is promoted up the list.",
    '28:11': "Engraved like a signet — the craft used to cut a king's seal is spent on a list of ordinary family names.",
    '28:12': "Aaron bears their names on his shoulders, where a man carries what is heavy.",
    '28:17': "Four rows of different stones. The twelve tribes are not represented by twelve of the same thing.",
    '28:21': "\"Every one with his name.\" Nobody is carried into the holy place merely as part of a total.",
    '28:28': "A lace of blue binds the breastplate to the ephod \"that it be not loosed.\" The names must not come away from the priest.",
    '28:29': "The same names move from his shoulders to his heart. He carries the people and he is meant to love them.",
    '28:30': "Urim and Thummim over his heart. He bears their judgment and the means of God's answer in the same place.",
    '28:32': "The robe is bound at the neck \"that it be not rent.\" The high priest at Jesus' trial will tear his own.",
    '28:33': "Bells and pomegranates alternate on the hem: fruit and sound, so the priest is heard as well as seen.",
    '28:35': "\"That he die not.\" The bells are a lifeline — those outside listen to know he is still alive in there.",
    '28:36': "HOLINESS TO THE LORD on a gold plate. The one sentence worn on a man's body is about God, not about him.",
    '28:38': "Aaron bears the iniquity of the holy things. Even Israel's gifts need atoning for before they can be received.",
    '28:40': "The sons get the same phrase, glory and beauty, in plainer cloth. Rank changes the vestment, not the reason for it.",
    '28:41': "Anointed, consecrated, sanctified — three verbs, and Aaron is the object of all of them. A priest is made.",
    '28:42': "Linen breeches to cover their nakedness. The shame that began in Eden is quietly provided for under the robes.",
    '28:43': "\"That they bear not iniquity, and die.\" The clothing is a condition of survival, not an ornament.",
})

TAKEAWAYS.update({
    # ---- Chapter 29 ----
    '29:1': "Hallowing a priest begins with a bullock and two rams. Ordination here is not a ceremony of words.",
    '29:4': "Aaron is washed before he is dressed. The first thing done to a priest is done to him, not by him.",
    '29:5': "Another man puts the garments on him. No priest in Israel robes himself.",
    '29:6': "The holy crown goes on over the mitre. Israel has a crowned head long before it has a king.",
    '29:7': "The oil is poured on his head, not dabbed. Anointing is deliberate excess, and Messiah is a word for it.",
    '29:9': "The office is made a perpetual statute for one family. Priesthood in Israel is inherited, not volunteered for.",
    '29:10': "Hands are laid on the bullock's head. The animal is tied to the men before anything happens to it.",
    '29:11': "The killing is done at the door, in the open. Nothing about the cost of atonement is hidden from the camp.",
    '29:12': "A little blood on the horns with a finger; the rest simply poured out at the base. Most of it is spilled.",
    '29:13': "The fat and the inward parts go up in smoke — the portions a man would most want. The best of it is burned.",
    '29:14': "The sin offering is burned outside the camp. Hebrews will point at this to say where Jesus suffered.",
    '29:18': "The whole ram goes up. A burnt offering is the one sacrifice with no portion kept back for anybody.",
    '29:20': "Blood on the right ear, thumb and toe: what he hears, what he does and where he walks are all marked.",
    '29:21': "Blood and oil are sprinkled on the garments too. The clothes are consecrated along with the man in them.",
    '29:24': "The offering is placed in their own hands and waved. They hold their consecration out toward God themselves.",
    '29:26': "The breast is Moses' portion. He is acting as priest in order to make priests, and then he steps out of it.",
    '29:28': "The priests live off the people's peace offerings. The ministry is funded by the worship it serves.",
    '29:29': "The holy garments pass to the sons. The office outlives the man; what he wore is handed on.",
    '29:30': "Seven days in the vestments before he serves alone. Nobody enters the holy place on his first morning.",
    '29:32': "They eat at the door of the tabernacle — inside the sanctuary's reach, still short of its rooms.",
    '29:33': "\"They shall eat those things wherewith the atonement was made.\" The sacrifice is not only watched; it is eaten.",
    '29:34': "Nothing keeps till morning. Holy things are not stored up against a future need.",
    '29:36': "Even the altar has to be atoned for, daily. Nothing Israel builds is clean merely by being built for God.",
    '29:37': "\"Whatsoever toucheth the altar shall be holy.\" Here holiness spreads outward rather than being defended.",
    '29:38': "Two lambs a day, continually. The extraordinary week gives way to a routine that will never end.",
    '29:42': "\"Where I will meet you.\" God locates himself at the spot where the daily lamb is burning.",
    '29:43': "The tabernacle is sanctified by his glory, not by the quality of its construction.",
    '29:44': "\"I will sanctify\" — tent, altar and priests alike. The holiness of all of it is God's doing, not theirs.",
    '29:45': "\"I will dwell among the children of Israel, and will be their God.\" Six chapters of blueprint were for this.",
    '29:46': "They came out of Egypt so that he might dwell among them. The rescue is said to have had this as its purpose.",

    # ---- Chapter 30 ----
    '30:1': "An altar for incense as well as one for blood. Worship includes what merely rises and feeds nobody.",
    '30:6': "The incense altar stands just outside the veil — as near the mercy seat as anything gets without going in.",
    '30:7': "Incense is burned while the lamps are trimmed. Prayer and light are tended in the same morning motion.",
    '30:8': "A perpetual incense. Something is always going up from Israel toward God, whatever kind of day it was.",
    '30:9': "No strange incense, no sacrifice, no drink offering here. Even genuine worship is refused in the wrong place.",
    '30:10': "Once a year blood touches the golden altar. The place of prayer is cleansed by the same means as the place of slaughter.",
    '30:12': "A ransom for the soul whenever they are counted. Numbering the people is treated as dangerous in itself.",
    '30:15': "\"The rich shall not give more, and the poor shall not give less.\" Souls are not priced according to income.",
    '30:16': "The ransom money becomes the tabernacle's funding. The silver under those boards was paid for men's lives.",
    '30:18': "A laver between altar and tent. Having offered the blood, the priest still cannot go in unwashed.",
    '30:20': "\"That they die not.\" This washing is not hygiene. Nearness without cleansing is fatal, even for a priest.",
    '30:23': "The anointing oil is a weighed recipe of costly spices. Nothing about consecration is left to be improvised.",
    '30:25': "\"After the art of the apothecary.\" God's service is carried out with a tradesman's skill, not a miracle.",
    '30:26': "The oil goes on the furniture before it goes on the priest. The place is consecrated ahead of the man.",
    '30:28': "Even the laver and the ash-pans are anointed. The unglamorous equipment is made holy with the rest.",
    '30:32': "The oil may not be poured on ordinary flesh or copied. Holiness is not a scent a man may wear for himself.",
    '30:33': "The penalty for copying it is being cut off from the people, not a fine. Imitation of the holy is treated as apostasy.",
    '30:34': "Four spices of like weight. Nothing in the mixture dominates, and none of it is optional.",
    '30:38': "Making the perfume \"to smell thereto\" is the offence named. The sin is turning what is holy into a pleasure.",

    # ---- Chapter 31 ----
    '31:2': "\"I have called by name Bezaleel.\" The man who builds the sanctuary is chosen as personally as the priest who serves in it.",
    '31:3': "Filled with the spirit of God — and what the filling produces is workmanship. The gift here is a trade.",
    '31:4': "\"To devise cunning works.\" Within a pattern he did not set, the craftsman still invents. Skill is not copying.",
    '31:6': "Aholiab is given as a partner, and wisdom is put in all the wise hearted. Nobody builds this alone.",
    '31:11': "\"According to all that I have commanded thee shall they do.\" Gifted men are still bound to the pattern.",
    '31:13': "The sabbath is a sign \"that I am the LORD that doth sanctify you.\" Rest testifies that the holiness is his work.",
    '31:14': "The sabbath law lands directly after the building orders. Even work for God's house does not override his rest.",
    '31:16': "A perpetual covenant, kept by stopping. The sign of belonging to God is the one thing you do by not doing.",
    '31:17': "God \"rested, and was refreshed.\" The word used of the Creator here is startlingly human.",
    '31:18': "Written with the finger of God. After all these instructions, the tables are the one thing no craftsman made.",
})

TAKEAWAYS.update({
    # ---- Chapter 32 ----
    '32:1': "\"Moses delayed.\" The whole collapse begins with a wait that ran longer than the people had budgeted for.",
    '32:2': "Aaron asks for the gold in their wives' and children's ears. The idol is paid for out of the household.",
    '32:3': "They break off the earrings without a murmur. The giving here is every bit as willing as the giving in chapter 25.",
    '32:4': "\"These be thy gods, which brought thee up out of Egypt.\" They do not want a different god; they want this one visible.",
    '32:5': "Aaron builds an altar to the calf and announces \"a feast to the LORD.\" The name is kept and the thing is swapped.",
    '32:6': "They sat down to eat and rose up to play. Paul will quote this line at a church that thought it was standing.",
    '32:7': "\"Thy people, which thou broughtest out of Egypt.\" God hands them back to Moses in the wording itself.",
    '32:8': "\"Turned aside quickly.\" It has been about six weeks since they said they would do everything he said.",
    '32:10': "\"Let me alone\" — said to a man who could not have stopped him. The words invite the pleading they forbid.",
    '32:11': "Moses gives the wording straight back: they are thy people, brought out by thy hand. He pleads God's stake, not Israel's merit.",
    '32:12': "His second argument is what Egypt would say. Nothing in this prayer is about how sorry the people are.",
    '32:13': "The last argument is the oath God swore by himself. Moses stakes everything on a promise that had no conditions in it.",
    '32:14': "\"The LORD repented of the evil.\" Scripture states it flatly and offers no apology for the language.",
    '32:15': "He walks down carrying the law toward a camp that has already broken it.",
    '32:16': "The work of God and the writing of God. What Moses is about to smash was not something a craftsman could replace.",
    '32:17': "Joshua hears a noise of war. From outside, idolatry and a battle sound much the same.",
    '32:19': "He breaks the tables in sight of the camp. The covenant document is destroyed in front of the party that broke it.",
    '32:20': "The calf is burnt, ground, scattered on water and drunk. They are made to swallow the thing they made.",
    '32:22': "\"Thou knowest the people.\" Aaron blames the congregation while standing beside the altar he built for them.",
    '32:24': "\"There came out this calf.\" The one detail Aaron omits is the graving tool that was in his own hand.",
    '32:25': "The people are naked \"unto their shame among their enemies.\" The idolatry has already cost them their name outside.",
    '32:26': "\"Who is on the LORD's side?\" The question assumes there is no neutral ground left anywhere in that camp.",
    '32:28': "About three thousand fell that day. The number is recorded plainly, with nothing offered to soften it.",
    '32:29': "Consecration is described as costing them their own sons and brothers. The word is used of a terrible day.",
    '32:30': "\"Peradventure I shall make an atonement.\" Even Moses goes up not knowing whether it can be done.",
    '32:31': "He names the sin to God without minimising it. Intercession starts by agreeing about what happened.",
    '32:32': "\"Blot me, I pray thee, out of thy book.\" The sentence breaks off unfinished, and he offers to be lost in their place.",
    '32:33': "God refuses the exchange. The offer was the right instinct, and Moses is not the man who can make it.",
    '32:34': "The Angel still goes before them and the reckoning is deferred, not cancelled. Forgiveness here is not amnesia.",
    '32:35': "The chapter's last word puts the calf back on Aaron. A leader is not absolved by the crowd's enthusiasm.",

    # ---- Chapter 33 ----
    '33:3': "The land is granted and the presence withdrawn — and the reason given is mercy: \"lest I consume thee in the way.\"",
    '33:4': "\"No man did put on him his ornaments.\" The mourning is measured by what people stopped wearing.",
    '33:5': "\"That I may know what to do unto thee.\" God leaves the outcome open and makes them live in the suspense.",
    '33:6': "They strip off at Horeb the jewellery that became a calf. The repentance is specific to the thing they did.",
    '33:7': "The tent is pitched outside the camp, and anyone who sought the LORD had to walk out of the camp to find him.",
    '33:9': "The pillar comes down once Moses is inside. God meets the mediator where the whole camp can see it happen.",
    '33:11': "\"As a man speaketh unto his friend\" — and nine verses later, no man may see his face and live. Both are true.",
    '33:12': "Moses presses the gap: God says he knows him by name and has not said who is being sent with him.",
    '33:13': "\"Shew me now thy way, that I may know thee.\" He asks for God himself rather than for directions.",
    '33:14': "\"My presence shall go with thee, and I will give thee rest.\" The answer to the request is a person, not a plan.",
    '33:15': "Moses would rather stay in the desert with God than walk into the promised land without him.",
    '33:16': "The only mark of a people in favour with God is that he goes with them. Nothing else would show it.",
    '33:17': "It is granted on the ground of Moses' standing, not Israel's. A nation is carried by one man's favour.",
    '33:18': "Having been given everything he asked for, Moses asks for more. \"I beseech thee, shew me thy glory.\"",
    '33:19': "Asked for glory, God answers with goodness and a name — and with mercy that answers to nothing but itself.",
    '33:20': "\"There shall no man see me, and live.\" The limit is not God's unwillingness but what a man can survive.",
    '33:21': "\"There is a place by me.\" Before any of the hiding, God says there is room beside him for a man to stand.",
    '33:22': "Hidden in the rock and covered by God's own hand. Moses is sheltered from God by God.",
    '33:23': "He is shown the back parts only. Even Moses is given the aftermath of the glory rather than the face of it.",

    # ---- Chapter 34 ----
    '34:1': "\"Hew thee two tables.\" The second set costs Moses labour the first did not, and God still does the writing.",
    '34:2': "\"Present thyself there to me.\" After the calf, Moses is summoned again rather than merely permitted.",
    '34:3': "Not a man, not even a grazing animal, on the mountain. After the calf the boundaries are drawn tighter than before.",
    '34:4': "He rises early and carries blank stone up a mountain on nothing but the promise that it will be written on.",
    '34:5': "The LORD descends and proclaims his own name. The glory Moses asked to see arrives as a self-description.",
    '34:6': "\"Merciful and gracious, longsuffering, and abundant in goodness and truth.\" God's account of himself opens with mercy.",
    '34:7': "Forgiving iniquity, and by no means clearing the guilty. Both halves stand in one breath, and neither is softened.",
    '34:8': "Moses made haste and bowed his head. The fitting answer to hearing that name is to get lower.",
    '34:9': "He turns the charge into the argument: come with us because we are stiffnecked. Need, not merit, is the plea.",
    '34:10': "God makes the covenant again on his own initiative. This time Israel is not asked to promise anything first.",
    '34:12': "The snare would be \"in the midst of thee.\" What threatens Israel in Canaan is domestic, not military.",
    '34:14': "\"The LORD, whose name is Jealous.\" God names himself by something we would call a fault in anyone else.",
    '34:15': "The slide begins with an invitation to dinner. Idolatry arrives as hospitality before it arrives as belief.",
    '34:16': "Idolatry is described as adultery, and the door into it is the marriage of the next generation.",
    '34:17': "\"Thou shalt make thee no molten gods.\" Five words, and everyone in earshot knows exactly what they refer to.",
    '34:19': "All that opens the womb is his. God's claim on the firstborn comes before any parent's claim on them.",
    '34:20': "The unclean firstling is redeemed by a lamb or its neck is broken. Redemption is offered and refusing it costs.",
    '34:21': "Rest is commanded \"in earing time and in harvest\" — at exactly the seasons when stopping is most expensive.",
    '34:24': "No one will covet their land while the men are away. The command to leave home comes with a promise about home.",
    '34:27': "\"After the tenor of these words.\" The covenant is with a people who will have the terms in writing.",
    '34:28': "Forty days again, without bread or water. The second stay on the mountain matches the first exactly.",
    '34:29': "\"Moses wist not that the skin of his face shone.\" The glory a man carries is the one thing he cannot see.",
    '34:30': "They were afraid to come nigh him. Even reflected, the glory frightens them as the mountain did.",
    '34:31': "Moses calls them back. The shining man goes after the people who have just backed away from him.",
    '34:32': "He hands on the commandment. What he went up for was always what he would bring back down.",
    '34:33': "The veil goes on after he has finished speaking, not before. Paul will read that order very closely.",
    '34:34': "The veil comes off when he goes in to the LORD. Uncovered before God, covered before men.",
    '34:35': "The veil goes back on each time. The shining is not permanent, and the covering has to be repeated.",
})

TAKEAWAYS.update({
    # ---- Chapter 35 ----
    '35:1': "Moses gathers the whole congregation — the same crowd that once gathered to Aaron, now assembled to be told what to do.",
    '35:2': "The sabbath is put first, before one word about building. Rest is not the reward waiting on the far side of the work.",
    '35:3': "\"Kindle no fire.\" The one concrete prohibition named strikes straight at the metalworker in the week he starts.",
    '35:5': "\"Whosoever is of a willing heart.\" After the calf, the offering is still asked for rather than demanded.",
    '35:10': "\"Every wise hearted among you shall come.\" The skilled are invited as a class; nobody is conscripted by name.",
    '35:20': "They departed from the presence of Moses — and the next verse has them coming back carrying things.",
    '35:21': "\"Every one whose heart stirred him up.\" The text keeps tracing the giving back to an inward movement, not a quota.",
    '35:22': "Bracelets, earrings and rings of gold. The same kind of jewellery that was broken off to make the calf.",
    '35:23': "\"Every man, with whom was found.\" People bring what they happen to have, not what they wish they had.",
    '35:25': "The women spin with their own hands and bring what they spun. The labour itself is brought as the offering.",
    '35:26': "Goats' hair, the coarsest stuff in the tent, is spun by women whose hearts stirred them \"in wisdom.\"",
    '35:27': "The rulers bring the onyx stones. They come late in the list and give the one thing only they could have given.",
    '35:30': "Moses names Bezaleel to the people. The congregation is told whose hands are on their offering and who called him.",
    '35:34': "\"He hath put in his heart that he may teach.\" The gift includes handing it on; a craftsman is made a trainer.",
    '35:35': "Engraver, embroiderer, weaver. Every trade in the camp is put under the one word wisdom.",

    # ---- Chapter 36 ----
    '36:2': "\"Every one whose heart stirred him up to come unto the work.\" Willingness stands beside skill as a qualification.",
    '36:3': "\"They brought yet unto him free offerings every morning.\" The generosity did not stop after the first surge of it.",
    '36:5': "\"The people bring much more than enough.\" It is a complaint no building project has ever expected to make.",
    '36:6': "A proclamation goes through the camp to make the giving stop. Moses has to restrain Israel from being generous.",
    '36:7': "\"Sufficient... and too much.\" The record closes the ledger and admits the surplus instead of quietly absorbing it.",
    '36:8': "The ten curtains are credited to every wise hearted man among them. The great work is written down as a plural.",

    # ---- Chapter 37 ----
    '37:1': "\"Bezaleel made the ark.\" The maker is named for this one object and then disappears behind \"he made\" for the rest.",
    '37:7': "The cherubim are beaten out of one piece with the mercy seat. The guardians and the lid cannot be taken apart.",
    '37:16': "Dishes, spoons, bowls and covers, all of pure gold — the tableware of a table at which nobody eats.",
    '37:29': "The last thing made is a perfume. A chapter of hammered gold ends at an apothecary's bench.",

    # ---- Chapter 38 ----
    '38:8': "The laver is cast from the looking glasses of the women who assembled at the door. They gave up the glass they saw themselves in.",
    '38:21': "\"This is the sum of the tabernacle, as it was counted.\" The accounts are published and signed off by a named man.",
    '38:22': "The record credits Bezaleel with doing all that the LORD commanded — obedience, not artistry, is what gets written down.",
    '38:23': "Aholiab is remembered in Scripture as an engraver and an embroiderer. The trade is the thing worth recording.",
    '38:24': "Twenty-nine talents of gold and more. The cost is totalled out loud rather than left as an impression.",
    '38:26': "A bekah a man, from six hundred and three thousand five hundred and fifty men. The whole nation is in that silver.",
    '38:27': "A talent a socket, a hundred sockets from a hundred talents. The arithmetic comes out exactly even.",

    # ---- Chapter 39 ----
    '39:1': "\"As the LORD commanded Moses.\" The refrain starts here and will be repeated until nobody can miss the point.",
    '39:3': "The gold is beaten into plates and cut into wires to be woven in. Metal is made thread so that it can be worn.",
    '39:9': "The breastplate is made double — a pouch. It is built to hold something inside as well as to display what is on it.",
    '39:32': "\"Thus was all the work finished... so did they.\" The sentence says it twice, as though the fact needed underlining.",
    '39:33': "They bring the whole thing to Moses rather than erecting it themselves. Finished work is handed over for inspection.",
    '39:42': "\"So the children of Israel made all the work.\" The people who made the calf are the people who made this.",
    '39:43': "Moses looked on all the work and blessed them. Inspection ending in blessing is the shape of Genesis 1.",

    # ---- Chapter 40 ----
    '40:2': "\"On the first day of the first month.\" The dwelling goes up on New Year's Day; the year opens with God's house.",
    '40:3': "The ark goes in first and is covered at once. The centre of the sanctuary is the part nobody is allowed to look at.",
    '40:4': "\"Set in order the things that are to be set in order.\" Bread and light are arranged by hand before any glory arrives.",
    '40:9': "Anointed, hallowed, \"and it shall be holy.\" A verdict is spoken over the objects; the workmanship did not earn it.",
    '40:16': "\"Thus did Moses: according to all that the LORD commanded him, so did he.\" A whole life summed up in one sentence.",
    '40:17': "Exactly a year after Egypt. It took twelve months to get from slavery to God living in the middle of the camp.",
    '40:18': "Moses fastens the sockets and sets up the boards himself. The man who spoke with God does the lifting.",
    '40:20': "The testimony goes into the ark, and the mercy seat goes on top of it. The law is put in and then covered over.",
    '40:23': "He sets the bread in order before the LORD. The first meal laid out in the new house is not for anybody in the camp.",
    '40:25': "He lighted the lamps before the LORD. A man strikes the first light in the tent, and it is lit for God to see by.",
    '40:27': "He burnt sweet incense on it. Before a single prayer has been offered there, the tent already smells of prayer.",
    '40:29': "The burnt offering is made at the door before the glory comes down. Sacrifice goes first; the presence follows.",
    '40:31': "Moses and Aaron wash their hands and feet at the laver. The men who built it still cannot walk in as they are.",
    '40:33': "The court goes up last, and \"so Moses finished the work.\" The labour of sixteen chapters closes in five words.",
    '40:34': "The cloud covered it and the glory filled it. Everything since chapter 25 has been arranging for this moment.",
    '40:35': "Moses cannot go in. The man who built the tent is shut out of it by the very presence it was built for.",
    '40:36': "They travel when the cloud lifts. Israel's timetable is set by God's movement rather than by their own readiness.",
    '40:37': "\"They journeyed not till the day that it was taken up.\" Staying put is obedience as much as marching is.",
    '40:38': "Cloud by day, fire by night, in sight of all Israel. The book ends with God plainly present and still on the move.",
})

TAKEAWAYS.update({
    # ---- Additions ----
    '23:14': "Three feasts a year. The working calendar is broken open at fixed points and nobody chooses when.",
    '23:26': "\"The number of thy days I will fulfil.\" The promise is a full life, not necessarily a long one.",
    '23:28': "Hornets go before them. Part of the conquest is done by means Israel could never take the credit for.",
    '23:31': "The bounds are described before one town has been taken. God draws the map before the marching starts.",
    '25:4': "Blue, purple, scarlet, fine linen — and goats' hair. Royal dye and coarse hair go on the same list.",
    '26:5': "Fifty loops facing fifty loops, \"that the loops may take hold one of another.\" The pieces are made to grip each other.",
    '26:24': "The corners are coupled beneath and above, into one ring. The weakest points get fastened twice.",
    '28:15': "It is called the breastplate of judgment. What the priest carries over his heart is a legal word, not a sentiment.",
    '29:2': "Unleavened bread goes into the basket alongside the animals. A priest is made at a meal as well as at an altar.",
    '29:17': "The ram is cut up and its inwards washed before burning. Even what will be smoke is made clean first.",
    '29:39': "A lamb in the morning and a lamb at evening. Both ends of every day are marked by a death.",
    '30:13': "The text stops to say a shekel is twenty gerahs. The price is defined so that nobody can quietly shave it.",
    '30:19': "Hands and feet: what a priest does with them and where he has walked are the two things washed.",
    '31:5': "Stone, timber and metal alike. The gift covers the whole trade, not only the part of it that touches holy things.",
    '32:9': "\"Stiffnecked\" is a word for an ox that will not turn with the yoke. It governs the next two chapters.",
    '34:11': "\"Behold, I drive out before thee.\" The command to observe arrives wrapped in what God undertakes to do first.",
})
