#!/usr/bin/env python3
"""Written one-line takeaways for Ezekiel 27-48."""

TAKEAWAYS = {
    # ---- Chapter 27 ----
    '27:2': "The oracle against the enemy city is ordered as a funeral song, not as a cheer.",
    '27:3': "\"I am of perfect beauty.\" Tyre's own sentence about herself is quoted back as the charge.",
    '27:4': "Her builders perfected her beauty. What she boasts of was other men's workmanship.",
    '27:5': "Fir from Senir, cedar from Lebanon: not one plank of the ship grew in Tyre.",
    '27:6': "Oars of Bashan oak, benches inlaid with ivory. Even the rowing bench had to be furniture.",
    '27:7': "Embroidered Egyptian linen for a sail. Where canvas would do, she flew a banner.",
    '27:8': "Zidon and Arvad pull the oars; Tyre supplies the pilots. She steers and hires the muscle.",
    '27:9': "The old men of Gebal caulk her seams. Someone else is paid to keep the water out.",
    '27:10': "Hired shields hung on the walls \"set forth thy comeliness\" — even defence was decoration.",
    '27:12': "Silver, iron, tin, lead from Tarshish. The song of praise turns into a shipping ledger.",
    '27:13': "\"They traded the persons of men\" — slaves entered between the metals and the brass vessels.",
    '27:15': "Ivory and ebony brought \"for a present.\" Tribute is written into the books as a gift.",
    '27:17': "Judah and Israel appear in the roll as one supplier of wheat and honey among many.",
    '27:21': "The princes of Kedar deal in lambs and goats. Desert royalty shows up here as a vendor.",
    '27:24': "The inventory runs down to chests bound with cords: the eye of a clerk, not of a poet.",
    '27:25': "\"The ships of Tarshish did sing of thee.\" The height of the song is the last line before the wind.",
    '27:26': "Her own rowers brought her out into the great waters where the east wind could break her.",
    '27:27': "Cargo, crew, caulkers and soldiers go down in a single sentence on the day of her ruin.",
    '27:28': "The cry of the drowning pilots reaches the mainland before any account of what happened does.",
    '27:29': "Every man who handled an oar comes down and stands on land, with nothing left to sail.",
    '27:30': "The mourners casting dust on their heads are her customers.",
    '27:31': "The grief is real, with shaved heads and sackcloth, and it is still grief over a market.",
    '27:32': "\"What city is like Tyrus?\" The lament keeps her boast alive, in the past tense.",
    '27:33': "She did enrich the kings of the earth. The good she did is admitted inside the judgement.",
    '27:35': "The kings are troubled in the face. Watching a trading power sink, they are afraid for themselves.",
    '27:36': "Her partners hiss at her. A lifetime of commerce bought no one willing to mourn her long.",
    # ---- Chapter 28 ----
    '28:2': "\"Yet thou art a man, and not God.\" The whole oracle is one correction of a category.",
    '28:3': "\"Wiser than Daniel\" is not sarcasm. The wisdom is real, and that is what made it dangerous.",
    '28:4': "Wisdom that reliably produces gold is still wisdom. It just cannot tell a man what he is.",
    '28:5': "Traffic increased the riches, and the riches lifted the heart. Prosperity works on a man slowly.",
    '28:7': "Strangers draw swords \"against the beauty of thy wisdom\" — the one argument it cannot answer.",
    '28:8': "The merchant prince dies the death of drowned sailors, in the sea his fleets made him rich on.",
    '28:9': "\"Wilt thou yet say before him that slayeth thee, I am God?\" The claim is tested where it counts.",
    '28:10': "The warrant for the sentence is not the strength of Babylon but the words \"I have spoken it.\"",
    '28:12': "The lament praises him fully — sealing the sum, perfect in beauty — before it accuses him.",
    '28:13': "Eden, and every precious stone for a covering. The language has climbed past any Phoenician king.",
    '28:14': "\"I have set thee so.\" The covering cherub's station was assigned to him, never seized.",
    '28:15': "\"Till iniquity was found in thee.\" The fall is dated exactly and never once explained.",
    '28:16': "The merchandise itself filled him with violence. The trade is named as the road into the sin.",
    '28:17': "Beauty lifted the heart and brightness corrupted the wisdom: the gifts did the damage.",
    '28:18': "The fire that consumes him is brought forth from his own midst. Nothing had to be imported.",
    '28:19': "Those who knew him are left astonished rather than grieving. Terror is the last thing he is.",
    '28:21': "Zidon gets four verses where Tyre got two chapters, and the sentence is no lighter for it.",
    '28:22': "\"I will be glorified in the midst of thee.\" Judgement on a city is God making himself known in it.",
    '28:24': "The point of the whole roll of nations: Israel's neighbours stop being briers in her side.",
    '28:25': "God is sanctified in Israel \"in the sight of the heathen.\" The nations watch him keep his word.",
    '28:26': "Houses built, vineyards planted, no one to fear. The promise is the most ordinary life imaginable.",
    # ---- Chapter 29 ----
    '29:3': "\"My river is mine own, and I have made it for myself\" — the lie told about every given thing.",
    '29:4': "Hooks in the jaws. The dragon of the Nile is landed like a fish by a man on the bank.",
    '29:5': "He is thrown out into the wilderness: the water creature left to die where there is no water.",
    '29:6': "Egypt's offence is named as being leaned on — \"a staff of reed to the house of Israel.\"",
    '29:7': "The reed broke and tore the hand that held it. A false support does more harm than none at all.",
    '29:9': "The land is laid waste over a sentence its king spoke. Words are treated here as deeds.",
    '29:10': "From the tower of Syene to the border of Ethiopia: the sentence is measured end to end.",
    '29:11': "Forty years with no foot of man or beast, the same span Israel spent crossing a wilderness.",
    '29:13': "\"Yet\" — after forty years God gathers Egypt again. Even the enemy gets a term rather than an end.",
    '29:14': "Egypt comes home, and comes home \"a base kingdom.\" Restoration need not mean restored greatness.",
    '29:15': "Kept smallest of the kingdoms so that no one will be tempted to lean on her a second time.",
    '29:16': "The real target is Israel's habit: Egypt will no longer be the confidence she runs to.",
    '29:17': "The latest dated word in the book reopens an oracle Ezekiel had already delivered years before.",
    '29:18': "Every head bald and every shoulder peeled from carrying siege works, and no wages at the end.",
    '29:19': "Egypt is handed over as back pay. God settles a pagan king's account out of another pagan's land.",
    '29:20': "\"They wrought for me.\" Nebuchadrezzar served God through a campaign he thought was his own.",
    '29:21': "The horn buds and the prophet's mouth is opened. Judgement on Egypt arrives as news for exiles.",
    # ---- Chapter 30 ----
    '30:2': "\"Howl ye, Woe worth the day!\" The prophet is told to make the sound, not merely report it.",
    '30:3': "The day of the LORD is called \"the time of the heathen.\" It was never a day for Israel only.",
    '30:4': "The sword falls in Egypt and the pain is felt in Ethiopia. Allies bleed for each other's defeats.",
    '30:5': "The mingled peoples fall with her. A coalition built on Egypt shares whatever Egypt gets.",
    '30:6': "\"They also that uphold Egypt shall fall.\" Propping up the doomed is a way of joining them.",
    '30:8': "Fire set and helpers destroyed, and the result named as knowing who the LORD is.",
    '30:9': "Messengers sent by ship to frighten \"the careless Ethiopians.\" The carelessness is the target.",
    '30:11': "\"The terrible of the nations\" are brought in. Hired brutality is still brutality on commission.",
    '30:12': "\"I will make the rivers dry.\" Egypt is the Nile, and the Nile is simply turned off.",
    '30:13': "The idols cease and the prince of the land ceases in one breath: gods and government fall together.",
    '30:14': "Pathros, Zoan, No — the judgement is named city by city so none can count itself the exception.",
    '30:15': "Fury poured on Sin, \"the strength of Egypt.\" The fortress she trusted is struck first.",
    '30:17': "The young men fall by the sword and the rest go captive. Conscripts pay before policy does.",
    '30:18': "At Tehaphnehes the day is darkened and the yoke broken. What she imposed is what is lifted.",
    '30:21': "\"I have broken the arm of Pharaoh\" — already done, and the splint is expressly refused.",
    '30:22': "Both arms are broken, the strong one and the one still mending. The second blow lands on the wound.",
    '30:24': "God puts his own sword into Babylon's hand. The conqueror is armed rather than merely permitted.",
    '30:25': "Egypt learns who the LORD is by watching another empire's arms get stronger than her own.",
    '30:26': "Scattered and dispersed, said twice over. Exile is what Egypt had long been arranging for others.",
}

TAKEAWAYS.update({
    # ---- Chapter 31 ----
    '31:2': "\"Whom art thou like in thy greatness?\" The question is answered with a felled tree.",
    '31:3': "Egypt is shown Assyria: a cedar taller than she is, and already cut down.",
    '31:4': "\"The waters made him great.\" The height everyone admired was fed from somewhere else.",
    '31:6': "Birds nested and nations sheltered in his shade. Empire is described here as something useful.",
    '31:7': "The beauty is traced down to the root by the water, not up to the branches on display.",
    '31:8': "Not even the trees in the garden of God matched him. The comparison is stretched to its limit.",
    '31:9': "\"I have made him fair.\" The maker states his own hand in the glory before he removes it.",
    '31:10': "Height was never the offence. The heart lifted up in the height is what is charged.",
    '31:11': "The fall has an agent and a reason: delivered into a conqueror's hand, driven out for wickedness.",
    '31:12': "Everyone who lived in his shadow goes down out of it and leaves him lying where he fell.",
    '31:13': "The birds that nested in his boughs now settle on the wreck of them.",
    '31:14': "The felling has a purpose stated outright: that no other well-watered tree exalt itself.",
    '31:15': "The deep is covered and the floods restrained. Even the waters that raised him go into mourning.",
    '31:16': "The trees already in the pit are \"comforted\" when he arrives. Comfort taken in another's fall.",
    '31:17': "\"They that were his arm\" go down with him. Allies share the grave as well as the shade.",
    '31:18': "\"This is Pharaoh.\" The whole parable is held back from its subject until the last line.",
    # ---- Chapter 32 ----
    '32:2': "Called a lion and a whale, and what he actually does is churn the water and foul the rivers.",
    '32:3': "\"I will spread out my net over thee.\" The nations are the net; the hunter is someone else.",
    '32:4': "The sea creature is left in an open field and the beasts of the whole earth are filled with him.",
    '32:5': "Flesh on the mountains, valleys filled with his height. What made him great is what fills them.",
    '32:6': "The river he swam in is watered with his own blood. The Nile runs with the man who claimed it.",
    '32:7': "A king's death is written as the putting out of a light, with the sky covered over it.",
    '32:9': "Countries he never reached are unsettled by his fall. Bad news travels further than he did.",
    '32:10': "The kings tremble \"every man for his own life.\" Their horror at his ruin is about themselves.",
    '32:13': "No foot of man or beast left to trouble the water. The quiet is the quiet of an emptied land.",
    '32:14': "The rivers run like oil because there is nobody left to stir them.",
    '32:15': "\"Destitute of that whereof it was full\" — desolation defined as the absence of what was there.",
    '32:16': "The lament is composed to be sung by the neighbouring nations over Egypt's grave.",
    '32:18': "Ezekiel is told to cast Egypt down by wailing over her. The word is what performs the burial.",
    '32:19': "\"Whom dost thou pass in beauty? go down.\" The question of rank is answered with a direction.",
    '32:21': "The mighty already in the pit speak up to greet him. He is expected there.",
    '32:22': "Asshur is there with her graves about her. The last world power is already filed away below.",
    '32:23': "They \"caused terror in the land of the living\" — the whole record is put in the past tense.",
    '32:24': "Elam bears her shame down with her. What a nation was does not stay behind at the grave.",
    '32:25': "A bed is set for her in the midst of the slain. The pit is furnished like a room.",
    '32:27': "Swords laid under their heads and iniquities upon their bones: buried with honours and with guilt.",
    '32:29': "Edom's kings and princes lie with the uncircumcised. Rank does not survive the descent.",
    '32:30': "The princes of the north are \"ashamed of their might.\" The strength itself becomes the shame.",
    '32:31': "Pharaoh is comforted by the company down there. The only consolation left is that others came first.",
    '32:32': "\"I have caused my terror in the land of the living.\" God claims the fear the empires traded in.",
    # ---- Chapter 33 ----
    '33:2': "The watchman is chosen by the people from among themselves, and then charged from above.",
    '33:3': "The whole office is two acts: see the sword, blow the trumpet. Nothing is asked about results.",
    '33:4': "The man who hears the trumpet and ignores it carries his own blood. Hearing is not heeding.",
    '33:5': "\"He that taketh warning shall deliver his soul.\" A warning only saves the man who takes it.",
    '33:6': "The silent watchman did not send the sword, and the blood is required at his hand regardless.",
    '33:7': "He is to warn \"from me.\" A watchman with something of his own to say has left the post.",
    '33:8': "The word he is held to is the one he would least like to deliver.",
    '33:9': "The warner is clear whether or not the warned man turns. He is answerable for speech, not outcome.",
    '33:10': "\"How should we then live?\" Despair finally spoken honestly is the first thing God answers.",
    '33:11': "God swears by his own life that he takes no pleasure in the death of the wicked.",
    '33:12': "A stock of past righteousness is not a balance to be drawn down in the day of transgression.",
    '33:13': "The man undone here is the one who trusted his own righteousness. The trusting is the ruin.",
    '33:14': "A sentence of death is announced as something that may still be answered by turning.",
    '33:15': "Repentance is made concrete: restore the pledge, hand back what was robbed. Not a mood.",
    '33:16': "\"None of his sins... shall be mentioned unto him.\" Forgiveness described as a silence kept.",
    '33:17': "They say God's way is not equal, and the charge is handed straight back to them.",
    '33:20': "The complaint about fairness is answered by judging each man singly, and not by class.",
    '33:21': "\"The city is smitten.\" Three words carried by a fugitive, and the whole book turns on them.",
    '33:22': "The prophet's mouth was opened the evening before the messenger arrived, not after.",
    '33:24': "\"Abraham was one, and he inherited the land: but we are many.\" Arithmetic done on a promise.",
    '33:25': "Blood, idols, bloodshed — and then the question whether such men can hold a land at all.",
    '33:26': "Standing on the sword and taking a neighbour's wife: possession is contested on conduct, not numbers.",
    '33:27': "Wastes, open field, forts and caves. Every place a man might hide is named and accounted for.",
    '33:28': "Even the ruin is emptied further. There was still pomp left in a smitten land, and it goes.",
    '33:30': "They talk about the preacher in doorways and invite each other to come and hear him.",
    '33:31': "They sit as God's people and hear as God's people, and the heart is elsewhere the whole time.",
    '33:32': "\"A very lovely song\" — the hardest thing said about a preacher is that he is enjoyed.",
    '33:33': "They will know a prophet was among them only once it is too late for the knowledge to help.",
    # ---- Chapter 34 ----
    '34:2': "The first charge against the shepherds is not cruelty but that they fed themselves.",
    '34:3': "Fat, wool and meat: they drew every product the flock could yield and returned nothing.",
    '34:4': "Five things left undone are listed before the one thing done. Neglect precedes the cruelty.",
    '34:5': "The sheep scattered \"because there is no shepherd.\" Absence is counted here as an act.",
    '34:6': "\"None did search or seek after them.\" Care is measured by who went out looking.",
    '34:8': "\"My flock\" and \"my shepherds\" in one breath. Neither the sheep nor the office was ever theirs.",
    '34:10': "\"I will require my flock at their hand.\" Office is answerable, and the flock is the evidence.",
    '34:11': "\"Behold, I, even I, will both search my sheep.\" The remedy is not a better hireling but God.",
    '34:12': "He goes after them in the cloudy and dark day, which is precisely when they were lost.",
    '34:13': "The gathering from the countries is not the goal. Being fed at home is what it is for.",
    '34:14': "Good pasture, good fold, high mountains. The promise is unglamorous and exactly what sheep need.",
    '34:15': "\"I will cause them to lie down.\" Rest is done to sheep; they do not arrange it themselves.",
    '34:16': "God takes up one by one the verbs the shepherds neglected, and adds judgement on the fat.",
    '34:17': "After the shepherds, the flock. Bad leadership never made the sheep innocent of each other.",
    '34:18': "It was not enough to eat and drink; they fouled with their feet what they could not use.",
    '34:19': "The weak drink what the strong have muddied. Damage always lands downstream from strength.",
    '34:20': "The line of judgement runs between fat cattle and lean, inside the one flock.",
    '34:21': "Thrusting with shoulder and horn until the diseased were pushed out: the scattering had culprits.",
    '34:22': "God saves the flock by judging it. The rescue and the reckoning are one action.",
    '34:23': "\"I will set up one shepherd over them\" — one, and called David long after David was buried.",
    '34:24': "The LORD is their God and David is prince among them. The two titles are not in competition.",
    '34:25': "A covenant of peace reaching as far as sleeping in the woods without setting a watch.",
    '34:26': "\"Showers of blessing\" in their season. Blessing pictured as weather: regular, and never earned.",
    '34:27': "Safety is dated from the breaking of a yoke held by men who served themselves of the flock.",
    '34:28': "\"None shall make them afraid.\" The promise is the end of fear, not merely of enemies.",
    '34:29': "A plant of renown ends the hunger and the shame of the heathen in the same sentence.",
    '34:30': "The whole chapter aims at one knowledge: that God is with them and that they are his people.",
    '34:31': "\"Ye my flock... are men, and I am your God.\" The metaphor is set down in the closing line.",
})

TAKEAWAYS.update({
    # ---- Chapter 35 ----
    '35:2': "The face is set against a mountain. Edom is arraigned under the name of its own high ground.",
    '35:3': "\"Behold, O mount Seir, I am against thee.\" The sentence is passed before the reason is given.",
    '35:4': "Cities laid waste so that Edom will know the LORD. Knowledge is what the ruin is for.",
    '35:5': "\"A perpetual hatred\" — the charge is not one raid but a grudge kept alive for generations.",
    '35:6': "Blood pursues the man who did not hate blood. The sentence is made out of the sin itself.",
    '35:7': "Him that passeth out and him that returneth: the road is closed at both ends at once.",
    '35:8': "Hills, valleys and rivers filled with his own slain. The whole geography becomes a grave.",
    '35:10': "\"Whereas the LORD was there.\" Edom counted two empty countries and missed who held the deed.",
    '35:11': "The judgement is measured out by Edom's own anger and envy. The grudge sets the sentence.",
    '35:12': "Blasphemies spoken against mountains are counted as spoken against the God of the mountains.",
    '35:13': "\"I have heard them.\" Words multiplied against God were not lost in the open air.",
    '35:14': "Edom is made desolate at the hour the whole earth rejoices. The timing is the whole point.",
    '35:15': "She rejoiced over another's desolation and receives desolation. The measure comes back.",
    # ---- Chapter 36 ----
    '36:2': "\"Aha, even the ancient high places are ours\" — the enemy's gloating is quoted as evidence.",
    '36:3': "Taken up in the lips of talkers. Part of the injury is having become a subject of gossip.",
    '36:4': "Wastes and forsaken cities are summoned to hear a word. The rubble is addressed first.",
    '36:5': "The fire of jealousy is kindled less by Israel's loss than by the joy the heathen took in it.",
    '36:6': "The land has borne the shame of the heathen, and it is the shame that God answers.",
    '36:7': "God lifts up his hand in oath: the nations that shamed her will carry shame themselves.",
    '36:8': "Branches and fruit are promised to a people described only as \"at hand to come.\"",
    '36:9': "\"I am for you\" — and what that turns out to mean is being tilled and sown.",
    '36:10': "Men multiplied, cities inhabited, wastes builded. Rescue measured in ordinary occupancy.",
    '36:11': "\"Better unto you than at your beginnings.\" The promise overshoots the good old days.",
    '36:13': "\"Thou land devourest up men.\" The reproach against the land is repeated before it is lifted.",
    '36:17': "The exile is explained without euphemism: they defiled the land by their own way and doings.",
    '36:18': "Fury poured out for blood shed and for idols set up. The two charges stand side by side.",
    '36:19': "\"According to their way... I judged them.\" The scattering is called fitting, not excessive.",
    '36:20': "The exiles profaned God's name simply by being exiles: their state told a story about him.",
    '36:21': "\"I had pity for mine holy name.\" The pity named here is pity for the name.",
    '36:22': "\"I do not this for your sakes.\" The reason for the rescue is God's own name, stated flatly.",
    '36:23': "The heathen learn who God is when he sanctifies himself in the people who profaned him.",
    '36:24': "The gathering is announced after the motive, not before it. Mercy follows the reason given.",
    '36:25': "Clean water is sprinkled before any command is issued. The cleansing is done to them.",
    '36:26': "The stony heart is not softened but taken out, and a heart of flesh put in its place.",
    '36:27': "The Spirit is put within them so that they walk in the statutes. Obedience is an effect here.",
    '36:28': "Land, people, God: the covenant sentence is restated only after the heart is replaced.",
    '36:29': "Saved from uncleanness, and then corn called for. Pardon and harvest in one breath.",
    '36:30': "Fruit multiplied until famine leaves the heathen nothing further to say about them.",
    '36:31': "The self-loathing comes after the cleansing, not before. Repentance follows the gift.",
    '36:32': "\"Not for your sakes do I this.\" The motive is said a second time, and it is still not them.",
    '36:34': "The land is tilled in the sight of everyone who once walked past it lying desolate.",
    '36:35': "\"Like the garden of Eden\" is what the onlookers say, not what God had promised.",
    '36:36': "\"I the LORD have spoken it, and I will do it.\" The guarantee is the speaker, not the plan.",
    '36:37': "After all the unasked-for promises, God says he will yet be enquired of to do them.",
    '36:38': "Waste cities filled with flocks of men. The chapter closes on the noise of a feast day.",
    # ---- Chapter 37 ----
    '37:1': "He does not find the valley. He is carried out and set down in the middle of it.",
    '37:2': "Led round about first: made to see how many and how dry before he is asked anything.",
    '37:3': "\"Can these bones live?\" The answer he gives is not yes but \"O Lord GOD, thou knowest.\"",
    '37:4': "He is told to preach to bones — an audience with no capacity to hear him.",
    '37:6': "Sinews, flesh, skin, breath: the rebuilding is itemised in the order a body is assembled.",
    '37:7': "The noise and the shaking begin while he is still speaking, not after he finishes.",
    '37:8': "Bodies complete and still dead. Everything except breath can be supplied and nothing gained.",
    '37:9': "A second sermon, this one preached to the wind. The breath comes by command as the bones did.",
    '37:10': "The slain stand up as an army, which is what a valley of unburied bones once was.",
    '37:11': "\"Our hope is lost\" — the vision was built out of a sentence the exiles said about themselves.",
    '37:12': "The picture turns from a battlefield to graves, and God is the one who opens them.",
    '37:14': "\"I have spoken it, and performed it.\" The Spirit put in them is what makes the word a deed.",
    '37:16': "Two sticks with two names written on them: the divided kingdom held in one hand.",
    '37:17': "The sticks are joined before any explanation is offered. The sign comes before the sermon.",
    '37:18': "The people's question about what it means is written into the instructions beforehand.",
    '37:19': "\"They shall be one in mine hand.\" The joining happens in God's hand, not by negotiation.",
    '37:21': "The gathering from every side comes first; the settlement of the kingdom follows it.",
    '37:22': "One nation, one king, \"no more two\" — a division of centuries ended in a single clause.",
    '37:23': "The cleansing is promised for the very dwellingplaces in which they had sinned.",
    '37:24': "David is king and one shepherd, and the statutes are kept under him rather than before him.",
    '37:25': "\"For ever\" is said twice in one verse, once of the land and once of the prince.",
    '37:26': "A covenant of peace, and the sanctuary set in their midst: the temple vision is promised here.",
    '37:27': "\"I will be their God, and they shall be my people\" — the oldest sentence in the covenant.",
    '37:28': "The heathen learn that God sanctifies Israel by seeing where his sanctuary stands.",
})
