#!/usr/bin/env python3
"""Written one-line takeaways for Ezekiel 1-26."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The thirtieth year, a foreign canal, a camp of deportees — and there the heavens open.",
    '1:2': "The date is reckoned from a king's deportation. Exile has become the calendar.",
    '1:3': "A priest far from any altar. The word finds him in Chaldea, and the hand of the LORD is there too.",
    '1:4': "The vision comes out of the north, the direction the armies came from, as storm and cloud and fire.",
    '1:5': "Whatever else the four creatures are, what they most resemble is a man.",
    '1:6': "Four faces and four wings apiece: built to face every direction at once.",
    '1:7': "Straight feet, a calf's sole, burnished brass. He reports the detail and offers no meaning for it.",
    '1:8': "Under the wings, the hands of a man. The strangest thing in the vision keeps something recognisable.",
    '1:9': "\"They turned not when they went.\" Nothing in this procession hesitates or changes its mind.",
    '1:10': "Man, lion, ox, eagle — the wild and the tame, the ruler and the ruled, carried on one body.",
    '1:11': "Two wings reach toward the next creature and two cover the body. Even these keep themselves covered.",
    '1:12': "The spirit settles the direction; the creatures do not deliberate about it.",
    '1:13': "Fire moving up and down among them, lightning going out. The living things are lit from inside.",
    '1:14': "They ran and returned like a flash of lightning. The vision will not hold still to be drawn.",
    '1:15': "Only now the wheels, and they are on the earth — touching the ground the creatures never touch.",
    '1:16': "A wheel in the middle of a wheel: made to roll any direction without being turned first.",
    '1:18': "The rings are high and dreadful and full of eyes. What carries the throne is also watching.",
    '1:19': "Creatures rise and wheels rise with them. Nothing here moves on its own account.",
    '1:20': "\"The spirit of the living creature was in the wheels.\" The machinery turns out not to be machinery.",
    '1:22': "Above their heads a firmament like terrible crystal. There is still a floor above them.",
    '1:24': "Great waters, the voice of the Almighty, the noise of an army — and silence when they let their wings down.",
    '1:25': "The voice comes from above the firmament, and only once the wings are down and the noise has stopped.",
    '1:26': "Above the sapphire throne, the likeness as the appearance of a man. The glory at the centre looks human.",
    '1:27': "Amber and fire above the loins and below. The one enthroned is circled with words and never described.",
    '1:28': "Not the glory but the appearance of the likeness of it — and that much put Ezekiel on his face.",
    # ---- Chapter 2 ----
    '2:1': "\"Son of man, stand upon thy feet.\" The first word to a man flat on his face is to get up.",
    '2:2': "The spirit does the standing for him. He is set on his feet rather than helped to his feet.",
    '2:3': "He is sent to rebels, and the rebellion is dated: they and their fathers, even unto this very day.",
    '2:4': "Impudent and stiffhearted — and he is sent anyway, with nothing to say but Thus saith the Lord GOD.",
    '2:5': "Hear or forbear, they will know a prophet was among them. Success is no part of the commission.",
    '2:6': "Briers, thorns, scorpions, and three times over: be not afraid. The threat named is their looks and words.",
    '2:7': "He is to speak the words given him, not adjust them to what the room will take.",
    '2:8': "Before he preaches against rebellion he is warned off his own, and told to open his mouth and eat.",
    '2:9': "A hand appears holding a roll. The word arrives as an object before it arrives as a message.",
    '2:10': "Written within and without, with no margin left: lamentations, and mourning, and woe.",
    # ---- Chapter 3 ----
    '3:1': "Eat first, then speak. The message has to go through him before it goes through his mouth.",
    '3:2': "He opened his mouth and was fed. Even the eating is something done to him.",
    '3:3': "A scroll of lamentation tasted like honey. God's word is sweet to the one who takes it, whatever it says.",
    '3:5': "Not sent to foreigners. The hardest language he will have to deal with is his own.",
    '3:6': "Strangers would have listened. The comparison is made to shame Israel, not to excuse the prophet.",
    '3:7': "Their refusal of him is a refusal of God. That is said as comfort and as warning at once.",
    '3:8': "God hardens his face to match theirs. The armour issued is made of the same stuff as their resistance.",
    '3:9': "An adamant forehead, harder than flint, given and not developed. Toughness here is equipment.",
    '3:10': "Receive in the heart, hear with the ears. He is made a hearer before he is made a speaker.",
    '3:11': "He is sent to the captivity, his own fellow deportees — and warned they may not listen either.",
    '3:12': "\"Blessed be the glory of the LORD from his place.\" The vision withdraws leaving a blessing behind it.",
    '3:14': "Bitterness and heat of spirit, and the hand of the LORD strong upon him. Both are true at once.",
    '3:15': "\"I sat where they sat\" — seven days among them, astonished and silent, before any word of judgement.",
    '3:17': "Watchman: the office is to hear at God's mouth and warn. Results are not what he is hired for.",
    '3:18': "If the warning is not given, the wicked dies anyway — and his blood is required of the silent man.",
    '3:19': "A warning refused clears the watchman. He answers for speaking, never for the outcome.",
    '3:20': "The righteous man's record does not hold him up when he turns. It shall not be remembered.",
    '3:21': "The warned man lives because he was warned. The word is the means, not a formality observed.",
    '3:22': "\"The hand of the LORD was there upon me\" — the book's way of saying he is not acting on his own.",
    '3:23': "The same glory, now out on the plain. Seeing it twice does not make it easier to stand in front of.",
    '3:24': "Set on his feet and told at once to shut himself in his house. The commission begins in confinement.",
    '3:25': "They will bind him, and he will not resist. The prophet is made to share the captivity he preaches to.",
    '3:26': "God makes his tongue cleave to his mouth. A reprover is withdrawn from people who would not hear one.",
    '3:27': "He speaks only when God opens his mouth, and then nothing of his own gets in.",
    # ---- Chapter 4 ----
    '4:1': "The prophecy starts as a drawing in clay: a brick, a scratched city, and the name Jerusalem.",
    '4:2': "He builds the siege works in miniature. The sign is performed before the army has marched.",
    '4:3': "The iron pan stands as a wall between prophet and city, and the prophet is on the besieger's side of it.",
    '4:4': "Lying on his side, he carries the iniquity of Israel in his own body for as long as it takes.",
    '4:5': "Three hundred and ninety days, a day appointed for a year. The sentence is counted out in daylight.",
    '4:6': "Forty days more for Judah, on the other side. The two houses are weighed on separate scales.",
    '4:7': "Bared arm and fixed face: the posture of a man about to strike, held toward his own city.",
    '4:8': "Bound so that he cannot turn over. Even the prophet's discomfort is not left to his discretion.",
    '4:9': "Wheat, barley, beans, lentiles, millet and fitches in one pot — the scrapings of a town with nothing left.",
    '4:10': "Twenty shekels a day, eaten by weight. Rationing is the whole point of the recipe.",
    '4:11': "A sixth part of an hin of water, at set times. Under siege even thirst runs to a schedule.",
    '4:12': "Bread baked on human dung, in their sight. The sign is built to disgust the people watching it.",
    '4:13': "The book explains its own sign: this is what eating defiled bread among the Gentiles will be.",
    '4:14': "\"Ah Lord GOD!\" The priest who has kept the food laws all his life objects, and objects out loud.",
    '4:15': "The command is eased to cow's dung. The objection was heard and something was actually changed.",
    '4:16': "The staff of bread: bread is what a city leans on, and it is broken rather than merely reduced.",
    '4:17': "They will look at one another astonished. Famine is described here by the faces it makes.",
    # ---- Chapter 5 ----
    '5:1': "A priest forbidden to shave his head takes a razor to head and beard, then weighs out what comes off.",
    '5:2': "Burned, cut, scattered. The hair is the population and the thirds are what becomes of them.",
    '5:3': "A few hairs bound into his skirt. Out of a whole head, a remnant, kept deliberately and by hand.",
    '5:4': "Some even of the few go into the fire. The book will not let the remnant harden into a guarantee.",
    '5:5': "\"This is Jerusalem\" — set in the midst of the nations, which is why more was asked of her.",
    '5:6': "Placed among the nations to show them the law, she has outdone them at breaking it.",
    '5:7': "She has not even kept the standards of her neighbours. The comparison is meant to sting.",
    '5:8': "\"Behold, I, even I, am against thee.\" The adversary named in this siege is not Babylon.",
    '5:9': "A judgement with no precedent and no repetition. It is called unique in both directions.",
    '5:10': "Fathers eating sons and sons their fathers. The siege turns a household into what it lives on.",
    '5:11': "The reason given is the defiled sanctuary, and the sentence is that the eye will not spare.",
    '5:12': "The thirds are named at last: pestilence, sword, scattering — with a drawn sword following the scattered.",
    '5:13': "\"I will be comforted.\" Anger that has finished its work is spoken of as coming to rest.",
    '5:14': "The ruin is public by design: waste and reproach in the sight of everyone who passes by.",
    '5:15': "Reproach, taunt, instruction, astonishment. The nations are expected to learn from the wreckage.",
    '5:16': "Famine is called an arrow — something aimed and sent, not a failure of the weather.",
    '5:17': "Famine, beasts, pestilence, sword; and under them the signature, I the LORD have spoken it.",
    # ---- Chapter 6 ----
    '6:2': "The face is set toward the mountains because of what has been built on the high ground.",
    '6:3': "Mountains, hills, rivers and valleys are summoned to listen. The landscape is put in the dock.",
    '6:4': "The slain are thrown down in front of the idols they trusted, in the place where they trusted them.",
    '6:5': "Bones scattered around the altars. The shrine is defiled by its own worshippers' corpses.",
    '6:6': "Altars waste, idols broken, works abolished. The stated aim is the end of the whole apparatus.",
    '6:7': "\"Ye shall know that I am the LORD\" closes oracle after oracle here: knowing him is what all this is for.",
    '6:8': "\"Yet will I leave a remnant.\" The sentence is interrupted by a promise nobody asked for.",
    '6:9': "The survivors remember, and loathe themselves. Repentance arrives after the punishment, not before it.",
    '6:10': "The proof offered that he is the LORD is simply that what he threatened actually came.",
    '6:11': "Smite with thine hand, stamp with thy foot. The prophet must act the grief out, not only report it.",
    '6:12': "Far off, near, or shut up in the siege: the three positions are listed to show there is no third option.",
    '6:13': "Every high hill and green tree and thick oak they chose for worship becomes a place of the dead.",
    '6:14': "More desolate than the wilderness toward Diblath. Emptiness is the unit of measurement.",
}

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:2': "\"An end, the end is come.\" The word is repeated because there is nothing left to put after it.",
    '7:3': "Judged according to thy ways: the sentence is drawn off the record, not invented for effect.",
    '7:4': "Recompense is the word chosen. What comes back to them is their own abominations, set in their midst.",
    '7:5': "\"An evil, an only evil.\" Singular, unrepeatable, the kind of thing that happens to a nation once.",
    '7:6': "\"It watcheth for thee.\" The end is given a face and made to stare back.",
    '7:7': "Morning has come and brings no shout from the hills. Daybreak itself is the thing to dread.",
    '7:9': "\"I am the LORD that smiteth.\" The refrain about knowing him is handed a very hard verb.",
    '7:10': "The rod has blossomed, pride has budded. What grew up among them is what will be used on them.",
    '7:11': "\"Neither shall there be wailing for them.\" Not even mourning is left over at the end.",
    '7:12': "Let not the buyer rejoice nor the seller mourn. With wrath on everyone, a good bargain means nothing.",
    '7:13': "The seller never returns to what he sold. Jubilee, and ordinary economic hope with it, is cancelled.",
    '7:14': "The trumpet is blown and nobody goes to the battle. The alarm works; the nerve is gone.",
    '7:15': "Sword without, famine and pestilence within. Staying and leaving are given the same ending.",
    '7:16': "Survivors mourn on the mountains like doves, and each mourns his own iniquity rather than the city's.",
    '7:17': "Feeble hands, knees weak as water. The first thing terror is said to do is bodily.",
    '7:18': "Sackcloth, horror, shame, baldness — the whole dress of mourning, worn by people not yet dead.",
    '7:19': "Silver thrown into the streets. Money that can neither buy bread nor buy off wrath stops being money.",
    '7:20': "The ornament given them for majesty was filled with their images, so he set it far from them.",
    '7:21': "The holy things go to strangers for a prey, and it is God who is handing them over.",
    '7:22': "He turns his face away and the robbers walk into his secret place. The desecration is permitted.",
    '7:23': "\"Make a chain.\" A land full of bloody crimes is handed a picture of its sentence to look at.",
    '7:24': "The worst of the heathen will live in their houses. Judgement is not carried out by the respectable.",
    '7:25': "They shall seek peace, and there shall be none. Seeking is not the same thing as finding.",
    '7:26': "Rumour on rumour; and when they finally want a vision, the law has already perished from the priest.",
    '7:27': "King, prince and people of the land together. The collapse reaches every rank and stops at none.",
    # ---- Chapter 8 ----
    '8:1': "The elders are sitting in front of him waiting for a word when the hand of the Lord GOD falls.",
    '8:2': "The figure of fire and amber from the first vision returns with no introduction at all.",
    '8:3': "Taken by a lock of his hair to Jerusalem, and set down at the gate where the image of jealousy stands.",
    '8:4': "The glory of the God of Israel is there — in the same building as the idol, in the same frame.",
    '8:5': "He is told where to look. The tour of the temple is guided, not wandered through.",
    '8:6': "\"Turn thee yet again, and thou shalt see greater abominations.\" The chapter is built as a descent.",
    '8:7': "A hole in the wall. What he is brought to see is not on display and was never meant to be.",
    '8:8': "He has to dig it open himself. The witness uncovers the evidence with his own hands.",
    '8:10': "Creeping things and abominable beasts painted all round the wall — the whole menagerie, indoors.",
    '8:11': "Seventy elders with censers in the dark, and Jaazaniah among them, from the family that backed reform.",
    '8:12': "\"The LORD seeth us not.\" The chambers of imagery were built on the assumption of not being watched.",
    '8:14': "Women weeping for Tammuz at the north gate. The grief is genuine and it is spent on a dying god.",
    '8:16': "Backs to the temple, faces east, worshipping the sun — and standing between the porch and the altar.",
    '8:17': "Idolatry and a land filled with violence are named in one breath, as two halves of one offence.",
    '8:18': "\"Though they cry in mine ears with a loud voice, yet will I not hear.\" Prayer can be offered too late.",
    # ---- Chapter 9 ----
    '9:1': "The executioners are summoned with a loud cry, the way a crier calls a case into court.",
    '9:2': "Six men with slaughter weapons, and a seventh with a writer's inkhorn. The clerk arrives with the killers.",
    '9:3': "The glory lifts off the cherub to the threshold. The departure from the temple begins with one step.",
    '9:4': "The mark is set on those who sigh and cry over the abominations. Grief is the only evidence looked for.",
    '9:5': "The order to spare no one is given in the prophet's hearing. He is not sent out of the room for it.",
    '9:6': "\"Begin at my sanctuary\" — and they begin with the old men standing in front of the house.",
    '9:7': "Defile the house, fill the courts with the slain. God commands the desecration of his own temple.",
    '9:8': "Left alone among the bodies, Ezekiel falls down and argues. The book lets its prophet object out loud.",
    '9:9': "The answer quotes their creed back at them: the LORD hath forsaken the earth, the LORD seeth not.",
    '9:11': "\"I have done as thou hast commanded me.\" The marking is reported finished before the killing is.",
    # ---- Chapter 10 ----
    '10:1': "The sapphire throne appears over the cherubims again — this time standing inside the temple.",
    '10:2': "The man with the inkhorn is sent back for coals. The hand that marked the spared now scatters the fire.",
    '10:3': "The cherubims stand on the right of the house and the cloud fills the inner court.",
    '10:4': "The glory moves from cherub to threshold, and the house fills with cloud. The second stage of leaving.",
    '10:5': "The wings can be heard out in the outer court. Nobody in the building could have missed it.",
    '10:7': "A cherub hands the fire over. The burning of the city passes from the throne into a human hand.",
    '10:8': "The hands of a man under the wings, noted a second time, as if he cannot get past it.",
    '10:10': "A wheel in the middle of a wheel, described again in the same words. He is confirming an identification.",
    '10:12': "Now the whole body is full of eyes, not only the rings. The watching has spread through the vision.",
    '10:13': "\"O wheel.\" A voice cries out to the wheels themselves, and the cry is recorded without explanation.",
    '10:14': "The ox of the first vision is now called the face of a cherub. The list has quietly changed.",
    '10:15': "\"This is the living creature that I saw by the river of Chebar.\" He is matching it, not describing it.",
    '10:18': "The glory leaves the threshold and stands over the cherubims. It is getting ready to travel.",
    '10:19': "They move to the east gate and the glory goes above them. God leaves his house by the door.",
    '10:20': "Only now does he name them cherubims. It took two visions to work out what he had been looking at.",
    '10:22': "\"They went every one straight forward.\" Even the departure of the glory is not a hesitant motion.",
    # ---- Chapter 11 ----
    '11:1': "Twenty-five men at the east gate, and two of them named. This corruption has addresses and surnames.",
    '11:2': "Devising mischief and giving wicked counsel are one charge. The sin here is committed as policy.",
    '11:3': "\"This city is the caldron, and we be the flesh.\" Their slogan of safety says they are the good meat.",
    '11:4': "Prophesy, prophesy — the command doubled. Nothing else is sent against their confidence.",
    '11:5': "\"I know the things that come into your mind, every one of them.\" The slogan was said behind doors.",
    '11:6': "The streets are full of their slain. The men who feel safest here are the ones who filled it with bodies.",
    '11:7': "Their own image is turned round on them: the corpses are the flesh, and they will be taken out of the pot.",
    '11:8': "\"Ye have feared the sword; and I will bring a sword upon you.\" The dreaded thing is the thing sent.",
    '11:9': "Delivered into the hands of strangers. What is removed first is the wall they were counting on.",
    '11:10': "Judged at the border, not in the city. Even the place of sentencing is chosen to make a point.",
    '11:12': "They kept the manners of the heathen around them while claiming the protection of God's own city.",
    '11:13': "Pelatiah drops dead mid-sermon, and the prophet's first instinct is to plead for everyone else.",
    '11:15': "Jerusalem has written the exiles off: get you far from the LORD, the land is ours now.",
    '11:16': "\"A little sanctuary in the countries.\" God goes into exile with them, and the building is not the point.",
    '11:17': "The gathering is promised to the scattered, not to the people still holding the land and the deeds.",
    '11:18': "Those who come back are the ones who clear the idols out. Restoration includes the demolition work.",
    '11:19': "A stony heart taken out and a heart of flesh put in. The obedience required has first to be created.",
    '11:20': "The new heart is given so the old covenant sentence can finally stand: my people, and their God.",
    '11:21': "The promise is not a blanket. A heart still walking after its idols gets its own way on its own head.",
    '11:22': "The wings lift and the glory moves. Nothing in the building is able to hold it there.",
    '11:23': "The glory halts on the mountain east of the city and stands. The leaving is done slowly, by stages.",
    '11:24': "The vision lets him go and he is back in Chaldea. He saw Jerusalem without ever leaving the camp.",
    '11:25': "He told the captives everything he had been shown. The vision was never his private property.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:2': "Eyes that see not and ears that hear not — the audience is described before the sign is designed.",
    '12:3': "\"It may be they will consider.\" The sign act is performed on the chance, not the certainty.",
    '12:4': "Baggage out in daylight, the man himself out at dusk. The performance is staged in two acts.",
    '12:5': "Digging through the wall, not walking out the door. This is how you leave when the gate is watched.",
    '12:6': "He carries it with his face covered, so he cannot see the ground he is leaving.",
    '12:7': "\"And I did so as I was commanded.\" He dug the hole with his own hand and reports it without comment.",
    '12:9': "\"What doest thou?\" The question is the object of the exercise; the sign was built to be asked about.",
    '12:10': "\"This burden concerneth the prince in Jerusalem.\" The mime had a specific man in it all along.",
    '12:11': "\"I am your sign.\" The prophet's own body, not his sermon, is the message being delivered.",
    '12:12': "The prince will do exactly what Ezekiel did, down to the shoulder and the covered face.",
    '12:13': "Brought to Babylon, \"yet shall he not see it.\" A riddle the blinding of Zedekiah would solve.",
    '12:14': "The scattering starts with the help: everyone around him is blown away first.",
    '12:15': "The dispersion is not only the sentence but the schooling — they learn him in the countries.",
    '12:16': "A few are spared to declare their own abominations abroad. Survival here is testimony against themselves.",
    '12:18': "Bread with quaking, water with trembling. The prophet has to eat the siege before the city does.",
    '12:19': "The reason given for the desolation is violence, not ritual failure.",
    '12:20': "Inhabited cities laid waste — put that way for people who thought occupancy was the guarantee.",
    '12:22': "\"The days are prolonged, and every vision faileth.\" Delay had hardened into a settled doctrine.",
    '12:23': "The proverb itself is what gets abolished, before the city does.",
    '12:24': "Flattering divination is named as the twin of the vain vision: comfort and emptiness together.",
    '12:25': "\"In your days\" — the timetable is pulled back inside the lifetime of the people hearing it.",
    '12:27': "Shelved a second way: not denied, just moved out to times far off.",
    '12:28': "\"There shall none of my words be prolonged any more.\" The delay they relied on is withdrawn.",
    # ---- Chapter 13 ----
    '13:2': "Prophesying \"out of their own hearts\" — the charge is invention, which can be perfectly sincere.",
    '13:3': "\"And have seen nothing.\" The foolish prophet's problem is empty hands, not faulty eyes.",
    '13:4': "Foxes in the deserts: scavengers who work a ruin rather than prevent one.",
    '13:5': "Not gone up into the gaps. The prophet's job is described as wall repair, and they skipped it.",
    '13:6': "They made others hope. The injury is not the lie in the air but the confidence built on it.",
    '13:8': "\"I am against you.\" The sentence is a person standing opposite, stated before any penalty.",
    '13:9': "Struck off the register of the house of Israel — not martyred, just not counted.",
    '13:10': "\"Peace; and there was no peace\" — and the untempered morter daubed over somebody else's bad wall.",
    '13:11': "Shower, hailstones and stormy wind arrive as the inspection the daubing was meant to survive.",
    '13:12': "\"Where is the daubing wherewith ye have daubed it?\" The question waits until after the collapse.",
    '13:13': "The storm is claimed as God's own fury, which rules out calling the fall bad weather.",
    '13:14': "The foundation gets discovered. What the plaster hid was that there was nothing underneath.",
    '13:16': "Only now are they named: the prophets who see visions of peace for Jerusalem, and there is none.",
    '13:17': "The same charge is turned on the daughters of the people, in the same words, with no softening.",
    '13:18': "Pillows sewn to armholes and kerchiefs on every head — religion run as a trade in charms.",
    '13:19': "\"For handfuls of barley and for pieces of bread.\" The price of the whole business is named, and it is tiny.",
    '13:20': "God declares himself against the pillows. The props are destroyed along with the practitioners.",
    '13:22': "False comfort cuts both ways: it saddens the righteous and hands the wicked a reason not to turn.",
    '13:23': "The end of the trade is stated as deliverance for the people, not merely as silence for the frauds.",
    # ---- Chapter 14 ----
    '14:1': "The elders come and sit down in front of him. The exiles do consult the prophet; that is not the problem.",
    '14:3': "Idols set up in the heart. The question raised is whether such men should be answered at all.",
    '14:4': "Answered \"according to the multitude of his idols\" — paid out in the currency he brought in.",
    '14:5': "\"That I may take the house of Israel in their own heart.\" The trap is set where the idols already are.",
    '14:6': "Repent, and turn your faces away. The oracle of refusal has a door left open in it.",
    '14:7': "The stranger who sojourns is held to the identical terms as the native-born.",
    '14:8': "Made \"a sign and a proverb\" — the man himself becomes the illustration others quote.",
    '14:9': "\"I the LORD have deceived that prophet\" — and destroy him for it. The text leaves both halves standing.",
    '14:10': "Prophet and enquirer draw the same punishment. Being consulted is no shelter from the verdict.",
    '14:11': "The stated aim of all this severity is an end to straying, not the satisfaction of anger.",
    '14:13': "\"Break the staff of the bread\" — famine pictured as a walking stick snapped under a man.",
    '14:14': "Noah, Daniel and Job \"should deliver but their own souls.\" Borrowed righteousness is not on offer.",
    '14:16': "Not even sons and daughters. Merit does not run downhill inside a family.",
    '14:18': "The same verdict repeated with the sword, because it contradicts what everyone assumes about the righteous.",
    '14:19': "Pestilence described as fury poured out in blood. The plague is not left to nature.",
    '14:20': "Righteousness delivers a soul and stops there. Stated four times, since once would not be believed.",
    '14:21': "\"How much more\" — four judgments at once on Jerusalem. The argument is being scaled up, not repeated.",
    '14:22': "A remnant is left, and left to be looked at: \"ye shall see their way and their doings.\"",
    '14:23': "The comfort offered is the strangest in the book: watching the survivors will show it was not done without cause.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:2': "\"What is the vine tree more than any tree?\" The nation's favourite image for itself is priced as timber.",
    '15:3': "Not even a pin to hang a vessel on. The smallest imaginable use is the one ruled out.",
    '15:4': "The fire takes both ends and the middle. Nothing is left over to be salvaged for something.",
    '15:5': "Useless whole, more useless burnt. The argument runs downhill with no turn built into it.",
    '15:6': "The parable explains itself: vine wood is fuel, and so are the inhabitants of Jerusalem.",
    '15:7': "\"They shall go out from one fire, and another fire shall devour them.\" Escaping the first is not the end.",
    '15:8': "The whole parable rests on one flat word: they have committed a trespass.",
    # ---- Chapter 16 ----
    '16:2': "\"Cause Jerusalem to know her abominations.\" The commission is to inform, not to persuade.",
    '16:3': "Amorite father, Hittite mother. The ancestry the city is proudest of is denied at the root.",
    '16:4': "Navel uncut, unwashed, unsalted, unswaddled — every ordinary kindness to a newborn withheld.",
    '16:5': "\"Cast out in the open field.\" The picture is exposure, the standard fate of an unwanted infant.",
    '16:6': "\"When thou wast in thy blood, Live.\" Said twice, over a child nobody had troubled to clean.",
    '16:7': "The growth is credited to the word spoken over her, not to anything she managed.",
    '16:8': "Skirt spread, oath sworn, covenant entered — and then \"thou becamest mine.\" A rescue turns into a marriage.",
    '16:9': "The washing comes after the covenant, not as the condition of it.",
    '16:10': "Broidered work, badgers' skin, fine linen and silk — the tabernacle's materials, worn by a person.",
    '16:12': "A jewel, earrings and a beautiful crown. She is not merely clothed; she is made a queen.",
    '16:13': "Fine flour, honey and oil: she is fed on exactly what gets brought to the altar.",
    '16:14': "\"Perfect through my comeliness, which I had put upon thee.\" The beauty was always on loan.",
    '16:15': "\"Thou didst trust in thine own beauty.\" The chapter turns here, on a gift mistaken for an asset.",
    '16:16': "The clothes come off her back and onto the high places. The gifts furnish the betrayal.",
    '16:17': "The gold and silver he gave her are melted down into images of men.",
    '16:18': "\"Mine oil and mine incense\" set before them. He keeps naming whose the goods were.",
    '16:19': "The food that kept her alive is laid out as a sweet savour for somebody else.",
    '16:20': "\"Thy sons and thy daughters, whom thou hast borne unto me\" — and then handed over to be devoured.",
    '16:21': "\"Thou hast slain my children.\" The sacrifice is not called worship; it is called killing.",
    '16:22': "The root failure named is amnesia: she never remembered the field she was found in.",
    '16:24': "An eminent place in every street. The unfaithfulness is carried out as public building work.",
    '16:26': "Egypt is put in the same sentence as the high places. Foreign policy and adultery are one subject here.",
    '16:27': "Even the Philistines are ashamed of her way. The neighbours she courted are embarrassed by her.",
    '16:28': "Assyria next, \"because thou wast unsatiable.\" What is being described is an appetite, not a plan.",
    '16:29': "Chaldea added, and still not satisfied. The list of lovers is a chronology of treaties.",
    '16:30': "\"How weak is thine heart.\" All that furious activity is diagnosed as weakness, not strength.",
    '16:32': "\"But as a wife that committeth adultery.\" The charge is precise: not a trade, a betrayal.",
    '16:33': "She pays her lovers instead of being paid. The economics of the figure run backwards.",
    '16:34': "\"Therefore thou art contrary.\" Even the comparison breaks down; she is worse than the thing compared to.",
    '16:36': "The blood of her children stands in the indictment beside the idols, not in a separate count.",
    '16:37': "The lovers are gathered as the instrument of judgement. The allies become the court.",
    '16:38': "Judged \"as women that break wedlock and shed blood are judged.\" She is tried under the ordinary law.",
    '16:39': "Stripped back to naked and bare. The sentence is largely the withdrawal of the gifts.",
    '16:40': "Stones and swords, and a company brought up. The crowd is handed the execution.",
    '16:41': "\"I will cause thee to cease from playing the harlot.\" The end of the punishment is the end of the practice.",
    '16:42': "\"I will be quiet, and will be no more angry.\" The jealousy is spent, not merely suppressed.",
    '16:43': "The recompense is fastened again to the one thing she failed to do: remember her youth.",
    '16:44': "\"As is the mother, so is her daughter.\" The proverb is put into the mouths of the neighbours.",
    '16:45': "Mother and sisters all loathing husbands and children — a family defined by what it throws away.",
    '16:46': "Samaria the elder sister, Sodom the younger. Jerusalem is placed in that company by name.",
    '16:47': "\"As if that were a very little thing, thou wast corrupted more than they.\" The comparison is meant to sting.",
    '16:48': "Sodom is compared favourably to Jerusalem, and the comparison is made under oath.",
    '16:49': "Sodom's iniquity: pride, fulness of bread, idleness, and no hand held out to the poor.",
    '16:50': "\"I took them away as I saw good.\" The overthrow of Sodom is stated without any drama at all.",
    '16:51': "\"Hast justified thy sisters.\" Her conduct ended up serving as their defence.",
    '16:52': "The judge of her sisters is told to bear her own shame: they are more righteous than thou.",
    '16:53': "The restoration promised includes Sodom's captivity turned back. That is not a threat and not expected.",
    '16:54': "Even the restoring comes with shame carried, and with being a comfort to Sodom as part of the terms.",
    '16:55': "\"Return to your former estate\" — the whole disgraced family is brought back together, not Jerusalem alone.",
    '16:59': "The verdict is contractual: she despised the oath in breaking the covenant.",
    '16:60': "\"Nevertheless I will remember my covenant.\" The chapter's hinge is his memory, after her failure to remember.",
    '16:61': "\"But not by thy covenant.\" The everlasting covenant is explicitly not the one she signed and broke.",
    '16:62': "The covenant is established first, and the knowing of him follows out of it.",
    '16:63': "Shame arrives after he is pacified, not before. The silence at the end is over a debt already settled.",
})

TAKEAWAYS.update({
    # ---- Chapter 17 ----
    '17:2': "\"Put forth a riddle.\" He is told to be deliberately obscure to people who were not listening anyway.",
    '17:3': "A great eagle crops the highest branch of the cedar: Nebuchadnezzar and Jehoiachin, in bird and tree.",
    '17:4': "\"A land of traffick... a city of merchants.\" Babylon is pictured as a market, not a fortress.",
    '17:5': "Seed of the land planted by great waters. The vassal arrangement is described as good growing conditions.",
    '17:6': "\"A spreading vine of low stature.\" It flourishes exactly as long as it consents to stay small.",
    '17:7': "The second eagle appears and the vine bends its own roots toward him. Nobody transplanted it.",
    '17:9': "\"Shall it prosper?\" The uprooting will not even need great power or many people.",
    '17:10': "The east wind is enough. It withers in the furrows where it grew, with no army in sight.",
    '17:12': "\"Know ye not what these things mean?\" The riddle is unwrapped in plain prose two verses later.",
    '17:13': "A covenant made and an oath taken. The treaty with Babylon is the thing actually on trial here.",
    '17:14': "\"That the kingdom might be base.\" The terms were humiliating, and they were survivable.",
    '17:15': "Ambassadors to Egypt for horses. \"Shall he break the covenant, and be delivered?\"",
    '17:16': "He dies in Babylon, in the house of the king whose oath he despised. The venue is chosen to make the point.",
    '17:17': "Pharaoh's army will not come. The ally that was paid for does not turn up.",
    '17:18': "\"He had given his hand.\" The handshake, not the parchment, is treated as the binding act.",
    '17:19': "\"Mine oath... my covenant.\" A treaty sworn to a pagan king is claimed by God as his own.",
    '17:20': "The net and the snare again, as with the prince in chapter twelve. The same trap fits both escapes.",
    '17:21': "The fugitives fall and the rest are scattered. Breaking a word costs more than the word.",
    '17:22': "God crops a tender twig from the same cedar himself. What the eagle did, the right hand now redoes.",
    '17:23': "Fowl of every wing dwelling in its shadow. The imperial picture is handed over to Israel's mountain.",
    '17:24': "The high tree brought down, the dry tree made to flourish. The reversal is how the trees know who did it.",
    # ---- Chapter 18 ----
    '18:2': "\"The fathers have eaten sour grapes.\" A proverb that turns guilt into inheritance and excuses everybody.",
    '18:3': "The proverb is abolished rather than argued with clause by clause.",
    '18:4': "\"All souls are mine\" comes first; \"the soul that sinneth, it shall die\" follows from the ownership.",
    '18:5': "The just man is defined by a list of things actually done, not by a standing he claims.",
    '18:6': "The list opens with the high places and moves straight to the neighbour's wife. Both tables, one paragraph.",
    '18:7': "Restoring the pledge, bread to the hungry, a garment on the naked — righteousness measured at the pawnshop.",
    '18:8': "No usury, no increase, true judgment between man and man. Money is where this is settled.",
    '18:9': "\"He is just, he shall surely live.\" The verdict is given flatly, with nothing hedged around it.",
    '18:10': "A son who is a robber and a shedder of blood. His father's record buys him nothing whatever.",
    '18:12': "Oppressing the poor and withholding a pledge stand in the same list as lifting the eyes to idols.",
    '18:13': "\"His blood shall be upon him.\" The account is charged to the man who ran it up, and to nobody else.",
    '18:14': "The third son \"seeth all his father's sins... and considereth.\" The turn begins with an honest look backwards.",
    '18:16': "The same short list of duties comes round again. The test never gets more elaborate than bread and a garment.",
    '18:17': "\"He shall not die for the iniquity of his father\" — said of the son with the best excuse in the chapter.",
    '18:18': "And the father dies in his own iniquity. Two verdicts inside one household, kept separate.",
    '18:19': "\"Yet say ye, Why?\" The objection is quoted because inherited guilt was the popular position.",
    '18:20': "\"Neither shall the father bear the iniquity of the son.\" The rule cuts the way nobody wanted either.",
    '18:21': "The wicked man who turns shall surely live. His past is not allowed to work as a sentence.",
    '18:22': "\"They shall not be mentioned unto him.\" Not weighed, not offset against anything — not mentioned.",
    '18:23': "\"Have I any pleasure at all that the wicked should die?\" The judge puts his own reluctance on the record.",
    '18:24': "The righteous man who turns away loses his record too. This is the half of the symmetry nobody quotes.",
    '18:25': "\"The way of the LORD is not equal.\" The complaint is that mercy and jeopardy are both live at once.",
    '18:27': "\"He shall save his soul alive.\" Turning is the only thing asked for, and it is treated as sufficient.",
    '18:28': "\"Because he considereth.\" The hinge of the whole chapter is a man looking honestly at his own case.",
    '18:30': "Judged every one according to his ways — and the sentence ends by telling them to turn.",
    '18:31': "\"Make you a new heart.\" Commanded here what chapter eleven promised to give. Law and promise, same book.",
    '18:32': "\"Wherefore turn yourselves, and live ye.\" A chapter of strict accounting closes as an appeal.",
})

TAKEAWAYS.update({
    # ---- Chapter 19 ----
    '19:1': "A lamentation is ordered for princes who are not all of them dead yet.",
    '19:2': "\"What is thy mother? A lioness.\" The royal house is described as a den of predators.",
    '19:3': "The whelp \"learned to catch the prey; it devoured men.\" Kingship taught as hunting.",
    '19:4': "Taken in their pit and led with chains to Egypt. The lion ends up caught like an animal.",
    '19:5': "\"When she saw that she had waited, and her hope was lost\" — she raised another one exactly the same way.",
    '19:7': "The roaring empties the land. What this lion laid waste was his own country.",
    '19:8': "The nations spread their net over him. The hunter is brought down by a coordinated hunt.",
    '19:9': "Caged \"that his voice should no more be heard upon the mountains of Israel.\" Silence was the object.",
    '19:10': "Mid-poem the figure changes: the lioness becomes a vine. Ezekiel will not hold one image still.",
    '19:11': "\"Strong rods for the sceptres of them that bare rule.\" The dynasty is counted as usable timber.",
    '19:12': "Plucked up in fury, dried by the east wind, and then the fire. Three ways of ending the same house.",
    '19:14': "The fire came out of one of her own branches. \"This is a lamentation, and shall be for a lamentation.\"",
    # ---- Chapter 20 ----
    '20:1': "Dated to the day: the elders come to enquire of the LORD and sit down. The request is a formal one.",
    '20:3': "\"I will not be enquired of by you.\" The answer given to the question is a refusal to accept it.",
    '20:4': "\"Wilt thou judge them, wilt thou judge them?\" The prophet is deputised as prosecutor, twice over.",
    '20:5': "The history is started in Egypt, not at Sinai: \"I am the LORD your God\" was said there first.",
    '20:6': "The land had been \"espied\" for them — scouted in advance, before they were ever brought out.",
    '20:7': "The first command in the story is to throw away Egypt's idols, given before the rescue, not after it.",
    '20:8': "They refused while still in Egypt. In this telling the rebellion is older than the redemption.",
    '20:9': "\"I wrought for my name's sake.\" The exodus is credited to God's reputation, not to Israel's promise.",
    '20:11': "\"Which if a man do, he shall even live in them.\" The statutes are handed over as life, not as burden.",
    '20:12': "The sabbaths are given as a sign, and the sanctifying in the clause is his work, not their achievement.",
    '20:13': "The wilderness rebellion is summarised with the sabbath at the centre of the charge sheet.",
    '20:14': "The name holds the sentence back a second time. By now the pattern is doing the arguing.",
    '20:15': "The oath is sworn not to bring them in. The generation fails; the land itself is not withdrawn.",
    '20:16': "\"For their heart went after their idols.\" One cause is given behind every separate breach listed.",
    '20:17': "\"Nevertheless mine eye spared them.\" The survival of the nation is put down to a look, in one clause.",
    '20:18': "The children are warned off their fathers' statutes. Inherited religion is named as the hazard.",
    '20:20': "The sabbath is made the sign by which they were to know whose they were — a day doing the work of a creed.",
    '20:21': "The second generation does precisely what the first did. Nothing improved at the handover.",
    '20:22': "\"I withdrew mine hand.\" The restraint is reported as an act performed, not a mood that passed.",
    '20:23': "The scattering is sworn in the wilderness, generations before there was anyone left to scatter.",
    '20:25': "\"I gave them also statutes that were not good.\" The hardest line in the book: judgement as worse law.",
    '20:26': "The firstborn passed through the fire, and God says he polluted them in their own gifts. Not disowned.",
    '20:27': "Blasphemy is the word chosen for what they did once they were safely inside the land.",
    '20:28': "\"Every high hill, and all the thick trees.\" The first thing they noticed in the good land was where to sacrifice.",
    '20:29': "\"The name thereof is called Bamah unto this day.\" A rhetorical question that stuck as a place name.",
    '20:30': "The indictment turns on the living: are you polluted after the manner of your fathers?",
    '20:31': "The refusal to be enquired of comes round again, this time with the reason attached to it.",
    '20:32': "\"We will be as the heathen.\" The wish is quoted back to them before they have said it out loud.",
    '20:33': "\"With fury poured out, will I rule over you.\" The kingship itself is the threat being made.",
    '20:34': "The mighty hand and stretched out arm, exodus language, now describes the gathering out of exile.",
    '20:35': "\"There will I plead with you face to face.\" The wilderness is used again, this time as a courtroom.",
    '20:37': "\"Pass under the rod\" — the shepherd counting sheep — and the covenant described as a bond, not a favour.",
    '20:38': "Brought out of the countries and still not brought in. A deliverance can stop at the border.",
    '20:39': "\"Go ye, serve ye every one his idols.\" A bitter permission, with only the holy name put out of reach.",
    '20:40': "All of them serving on the mountain, and the offerings required again. Worship is restored, not abolished.",
    '20:41': "\"I will be sanctified in you before the heathen.\" The audience the restoration is staged for is the nations.",
    '20:43': "They loathe themselves after they are home. Repentance follows the rescue instead of buying it.",
    '20:44': "\"Not according to your wicked ways.\" The plainest statement in the book of why any of this happens.",
    '20:46': "Set thy face toward the south. Direction is part of the oracle, as if the word had to be aimed.",
    '20:47': "Green tree and dry tree burn together. The fire in this parable does not sort the wood first.",
    '20:48': "\"All flesh shall see that I the LORD have kindled it.\" The arsonist signs the fire.",
    '20:49': "\"Doth he not speak parables?\" The prophet complains that his riddles are all anyone hears.",
})

TAKEAWAYS.update({
    # ---- Chapter 21 ----
    '21:2': "\"Drop thy word toward the holy places.\" The sanctuary is named as the thing being aimed at.",
    '21:3': "The sword cuts off \"the righteous and the wicked.\" Chapter eighteen's careful accounting does not survive a siege.",
    '21:5': "\"It shall not return any more.\" The sword is drawn with no arrangement made for sheathing it.",
    '21:6': "He is to sigh in public, with the breaking of his loins. Grief is assigned to him as a duty.",
    '21:7': "\"Wherefore sighest thou?\" Once more the sign is built round a question he waits to be asked.",
    '21:9': "\"A sword, a sword is sharpened.\" The poem stammers, and the stammer is doing the work.",
    '21:10': "\"Should we then make mirth?\" A question dropped into the middle of the sword's own song.",
    '21:11': "Furbished \"that it may be handled\" — polished until a human hand can pick it up comfortably.",
    '21:12': "Smite upon thy thigh. The prophet's body is conscripted into the oracle again, this time as mourning.",
    '21:13': "\"What if the sword contemn even the rod?\" A trial in which the discipline itself might not hold.",
    '21:14': "The sword doubled a third time, and it enters the privy chambers. There is no room too private for it.",
    '21:15': "The point is set against all their gates — aimed precisely at the structures built for safety.",
    '21:17': "God claps his own hands and the fury rests. Even this anger has a stopping place written into it.",
    '21:19': "Two roads marked out and a signpost planted. The oracle is staged as a map exercise.",
    '21:20': "Rabbath and Jerusalem are both on the itinerary. Only one of them gets visited first.",
    '21:21': "Arrows, images and the liver. Babylon's king decides by divination, and nobody calls it a mistake.",
    '21:22': "The lot falls on Jerusalem, and the battering rams follow the omen. The siege begins as a liver reading.",
    '21:23': "The men who swore oaths dismiss it as false divination. What is remembered is not the omen but the iniquity.",
    '21:24': "\"Ye are come to remembrance.\" Being remembered is itself the sentence here.",
    '21:25': "\"Profane wicked prince of Israel, whose day is come.\" The king is addressed to his face, without a title.",
    '21:26': "\"Remove the diadem, and take off the crown: this shall not be the same.\" The office is not just emptied but changed.",
    '21:27': "\"Overturn, overturn, overturn... until he come whose right it is.\" A door is left open inside the threat.",
    '21:28': "The sword turns on the Ammonites, who had been enjoying the spectacle from the far side of the river.",
    '21:29': "\"Whose day is come, when their iniquity shall have an end\" — the very words just used of Judah's prince.",
    '21:30': "\"I will judge thee in the place where thou wast created.\" No exile for Ammon; the reckoning is at home.",
    '21:31': "Delivered to brutish men, \"skilful to destroy.\" The instrument is praised with a craftsman's word.",
    '21:32': "\"Thou shalt be no more remembered.\" The opposite of Judah's sentence, and much worse than it.",
    # ---- Chapter 22 ----
    '22:2': "\"Wilt thou judge the bloody city?\" The name he is given for Jerusalem is already the indictment.",
    '22:3': "She \"maketh idols against herself.\" The damage in this oracle is all self-inflicted.",
    '22:4': "\"Thou hast caused thy days to draw near.\" The city set its own date without noticing.",
    '22:6': "The princes shed blood \"to their power\" — an office measured by how much harm it can manage.",
    '22:7': "Father and mother, the stranger, the fatherless, the widow. The unprotected are listed by category.",
    '22:8': "One short verse about holy things and sabbaths, wedged between two long lists of violence.",
    '22:9': "Men that carry tales to shed blood. Perjury is filed here as a form of killing.",
    '22:10': "Leviticus read back to the city as a charge sheet, clause for clause.",
    '22:11': "\"And another... and another.\" The sins are distributed across the city, one household at a time.",
    '22:12': "Gifts, usury, extortion — and the list ends not with a crime but with \"hast forgotten me.\"",
    '22:13': "\"I have smitten mine hand.\" God claps at dishonest gain, and the gesture is contempt, not applause.",
    '22:14': "\"Can thine heart endure?\" A question with no penalty attached to it, which is what makes it one.",
    '22:15': "The scattering is called a cleaning: \"will consume thy filthiness out of thee.\"",
    '22:16': "\"Thou shalt take thine inheritance in thyself.\" What is left to inherit is the people, not the land.",
    '22:18': "Brass, tin, iron and lead: the nation assayed and found to be the part that gets skimmed off.",
    '22:19': "\"Therefore I will gather you into the midst of Jerusalem.\" The gathering home is the furnace.",
    '22:20': "The fire is blown in anger, and nowhere in this figure does refined silver come out of it.",
    '22:22': "The knowing arrives through the melting. Here the lesson has no gentler delivery available.",
    '22:24': "\"The land that is not cleansed, nor rained upon.\" Drought described as a washing withheld.",
    '22:25': "The prophets head the list: a conspiracy, a lion over its prey, and widows made by the dozen.",
    '22:26': "The priests \"put no difference between the holy and profane.\" Distinguishing was the whole job.",
    '22:27': "Princes like wolves, \"to get dishonest gain.\" Not cruelty for its own sake; cruelty as a trade.",
    '22:28': "The prophets plaster over the princes with untempered morter. The frauds are working as a system.",
    '22:29': "The people of the land are charged as well. The list runs top to bottom and exempts nobody.",
    '22:30': "\"I sought for a man... but I found none.\" One person in the gap would have been enough.",
    '22:31': "\"Their own way have I recompensed upon their heads.\" Nothing extra is added to what they built.",
})
