#!/usr/bin/env python3
"""Written takeaways for Genesis 1-27."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The Bible opens by assuming God and arguing for nothing. Everything else in it is downstream of this sentence.",
    '1:2': "Before a word is spoken the Spirit is already over the chaos. God does not arrive after the darkness.",
    '1:3': "God speaks and it is. Creation by word sets the pattern for every act of God that follows.",
    '1:4': "\"God saw the light, that it was good.\" The maker inspects his own work and pronounces the verdict himself.",
    '1:5': "Naming is an act of authority, and God names the day and the night before any man names anything.",
    '1:6': "Creation proceeds by separation. Making room is as much a work of God as filling it.",
    '1:7': "\"And it was so.\" Between God's word and the fact there is no distance at all.",
    '1:9': "The sea appears when the water is told where to stop. Limits are what make the world habitable.",
    '1:10': "Dry land and seas are both called good. Nothing in the finished world is merely tolerated.",
    '1:11': "Seed is put inside the thing made. God builds the future into creation rather than remaking it each morning.",
    '1:14': "Sun and moon are given a job: signs, seasons, days and years. Time is a creature with a purpose.",
    '1:16': "\"He made the stars also.\" The lights other nations worshipped are given half a clause and not even named.",
    '1:18': "The lights rule by appointment. Every authority in this book holds office from someone above it.",
    '1:20': "Life is commanded to swarm. Abundance, not bare sufficiency, is the shape of the blessing.",
    '1:21': "The great sea creatures that fill the myths of the neighbours are simply made here, and called good.",
    '1:22': "The first blessing in Scripture falls on fish and birds. Humanity is not the first thing God is generous to.",
    '1:25': "The creeping things are called good before any use for them has been mentioned.",
    '1:26': "\"Let us make man.\" God deliberates before this one, and the deliberation is inside himself.",
    '1:27': "The image is given to male and female alike, and to the whole race before any of it has done anything.",
    '1:28': "Dominion is handed over as a blessing, not seized as a right, and it is exercised under the one who gave it.",
    '1:29': "God feeds his creatures before he asks anything further of them. Provision precedes demand.",
    '1:30': "The beasts are fed from the same hand. God's care does not stop at the edge of what is useful to us.",
    '1:31': "\"Very good\" is said only of the whole. The superlative waits until everything is in place together.",

    # ---- Chapter 2 ----
    '2:1': "\"Finished.\" Creation is a completed work, not an ongoing experiment that might yet be corrected.",
    '2:2': "God rests though nothing has tired him. The rest exists for the sake of the day, not for his sake.",
    '2:3': "The first holy thing in Scripture is a day, not a place, a person or an object.",
    '2:4': "The covenant name LORD appears only now, joined to God. The maker of galaxies is the one who deals by name.",
    '2:5': "The account pauses to say what was missing: rain, and a man to work the ground. Both are about to be supplied.",
    '2:7': "Dust and breath. Man is neither pure matter nor pure spirit, and the dust is named first.",
    '2:8': "The garden was planted before the man was placed in it. He inherits a prepared world.",
    '2:9': "Both trees stand in the same garden. The prohibition is set inside abundance, not instead of it.",
    '2:10': "The river does not pool in Eden but runs out of it in four directions. The garden was never meant to be private.",
    '2:15': "Work is given before the fall, as a charge to tend and guard. Labour is not the curse; its bitterness is.",
    '2:16': "The permission comes first and it is enormous: every tree in the garden.",
    '2:17': "One tree is withheld, with the reason and the penalty stated plainly in advance. Nothing is sprung on him.",
    '2:18': "The first thing God calls \"not good\" is a man on his own, in a world otherwise pronounced good.",
    '2:19': "God brings the animals \"to see what he would call them.\" The delegation is real and its outcome stands.",
    '2:20': "The naming ends in a discovery of lack. Adam learns what he needs by looking at everything that is not it.",
    '2:21': "The man is asleep for the making of his wife. He contributes nothing to her but the loss of a rib.",
    '2:22': "God brings her to him. The first marriage happens because someone else did the giving.",
    '2:23': "The first recorded human words are poetry, and they are about another person rather than himself.",
    '2:24': "Leaving comes before cleaving. A new household outranks the one a man was raised in.",
    '2:25': "Naked and not ashamed. Shame is absent here, which is the measure of what the next chapter costs.",

    # ---- Chapter 3 ----
    '3:1': "The first question recorded in Scripture is a question about what God said.",
    '3:3': "\"Neither shall ye touch it\" was never said. A fence added to the command makes God sound harsher than he is.",
    '3:4': "\"Ye shall not surely die.\" The serpent does not offer a rival religion, only a flat denial of one sentence.",
    '3:5': "The bait is God's own prerogative, offered on terms that leave God out.",
    '3:6': "Good for food, pleasant to the eyes, desirable to make wise. Sin is described as attractive, because it is.",
    '3:7': "Their eyes are opened and the first thing they see is themselves. New knowledge, and it is unbearable.",
    '3:8': "They hide from God among the trees God made. There was never any material for a hiding place but his own gifts.",
    '3:9': "\"Where art thou?\" God asks a question he knows the answer to, and the first move after the fall is his.",
    '3:10': "Adam reports the fear and the nakedness and says nothing about the eating.",
    '3:11': "\"Who told thee that thou wast naked?\" The question goes after where the new knowledge came from.",
    '3:12': "The blame passes through the woman and stops at God: \"the woman whom thou gavest.\"",
    '3:13': "She hands it on to the serpent, and there the chain runs out. Someone has to say \"I did eat\" at last.",
    '3:14': "The serpent is sentenced without being questioned. God interrogates those he means to deal with.",
    '3:15': "A promise buried inside a curse: the woman's seed will take the wound and crush the head.",
    '3:16': "The sentence falls on the two things she was given, childbearing and her husband, and spoils both from within.",
    '3:17': "\"Because thou hast hearkened unto the voice of thy wife\" — his failure was listening to the wrong voice, not to her.",
    '3:18': "Thorns are not a new creation but the old ground turned difficult. The world still gives, grudgingly.",
    '3:19': "Bread by sweat until the dust takes him back. The sentence ends exactly where chapter two began.",
    '3:20': "Under a death sentence Adam names his wife for life. That is faith taking God at the word of verse fifteen.",
    '3:21': "God replaces the fig leaves with skins. The covering that works is one he provides, and something dies for it.",
    '3:22': "Barring the tree of life keeps them from immortality in a ruined state. The expulsion is mercy as well as judgement.",
    '3:23': "He is sent out to till the ground he came from. The work continues; only the garden is gone.",
    '3:24': "The sword keeps the way to the tree of life. The way is guarded, not destroyed, which leaves it something to be reopened.",
}
