#!/usr/bin/env python3
"""Written takeaways for Genesis 28-50."""

TAKEAWAYS = {
    # ---- Chapter 28 ----
    '28:1': "The blessing Jacob stole is now handed over deliberately, with a charge attached to it.",
    '28:2': "The heir is sent away from the land of promise to find a wife. The promise travels before it settles.",
    '28:3': "Isaac asks God Almighty to do for Jacob what Jacob has spent two chapters trying to secure by fraud.",
    '28:4': "\"The land wherein thou art a stranger.\" Inheritance is promised to men who live in it as foreigners.",
    '28:6': "Esau watches the blessing happen from outside it and draws his own conclusions.",
    '28:8': "Esau finally notices what pleases his father, years after it would have mattered.",
    '28:9': "He marries into Ishmael's line — a rejected son seeking out another rejected son's house.",
    '28:10': "Jacob leaves with nothing but the blessing. Everything he schemed for he is now running from.",
    '28:11': "A stone for a pillow and the sun gone down. God meets him at the lowest point of the journey.",
    '28:12': "The ladder runs from earth to heaven, and the traffic is God's messengers, not Jacob's climbing.",
    '28:13': "The LORD introduces himself as the God of Abraham and Isaac to a man who has just deceived Isaac.",
    '28:14': "The promise to Abraham is repeated to the deceiver intact, with nothing subtracted for his conduct.",
    '28:15': "\"I will not leave thee, until I have done that which I have spoken.\" The keeping is tied to God's word, not Jacob's.",
    '28:16': "\"Surely the LORD is in this place; and I knew it not.\" God was there before the dream disclosed him.",
    '28:17': "The house of God is a frightening thing to stumble into. Awe, not comfort, is the first reaction.",
    '28:18': "He marks the spot with the stone he had slept on. The pillow becomes a pillar.",
    '28:19': "Bethel, house of God — a name given to a place that had been nothing but a stopping point called Luz.",
    '28:20': "Jacob answers an unconditional promise with an \"if.\" He is still negotiating with a God who has already committed.",
    '28:21': "\"Then shall the LORD be my God.\" Faith here is still on terms, and God bears with it.",
    '28:22': "The tenth is promised out of what God gives. Jacob can only pledge back a share of a gift.",

    # ---- Chapter 29 ----
    '29:2': "A well, flocks, and a stone too heavy to move. The obstacle is introduced before the man who moves it.",
    '29:6': "The answer to a question about Laban's welfare is Rachel arriving. God's providence runs through small timing.",
    '29:7': "Jacob arrives a stranger and immediately tells the local shepherds their business.",
    '29:8': "\"We cannot, until all the flocks be gathered.\" Custom held the stone in place as surely as its weight did.",
    '29:9': "Rachel keeps sheep. The woman at the centre of this story is working when she enters it.",
    '29:10': "Jacob rolls away the stone alone, for Laban's flock. Strength shows up where love is involved.",
    '29:11': "He kisses her and weeps. The man who has been all calculation breaks open at a well.",
    '29:13': "Laban runs and embraces him, exactly as he once ran out to Abraham's servant and his camels.",
    '29:14': "\"Thou art my bone and my flesh\" — warm words from a man who will spend twenty years exploiting the relation.",
    '29:15': "Laban's kindness turns into a wage negotiation within a month.",
    '29:17': "The two sisters are introduced by how they look. Everything that follows is set in motion by that comparison.",
    '29:18': "Jacob offers seven years for a woman he has no money to marry. He pays in the only currency he has left.",
    '29:19': "Laban never says yes. He says it is better than the alternative, and Jacob hears a promise.",
    '29:20': "Seven years seemed but a few days for the love he had to her. Love changes the weight of time, not its length.",
    '29:22': "Laban makes a feast for the whole town, and the whole town keeps the secret.",
    '29:23': "The deceiver is deceived in the dark, by a substitution of the elder for the younger.",
    '29:25': "\"Wherefore then hast thou beguiled me?\" Jacob asks Esau's question and does not hear himself.",
    '29:26': "Laban's excuse is that the younger must not go before the firstborn — the exact thing Jacob did to Esau.",
    '29:27': "The fraud is renegotiated into seven more years of labour. Laban turns his own wrong into a fee.",
    '29:28': "Jacob accepts the terms. He has no leverage, which is a new condition for him.",
    '29:30': "He loved Rachel more than Leah. Scripture states the preference flatly and then shows what it costs everyone.",
    '29:31': "\"When the LORD saw that Leah was hated, he opened her womb.\" God attends to the unwanted one first.",
    '29:32': "Reuben, \"the LORD hath looked upon my affliction\" — and still Leah hopes a son will buy her husband's love.",
    '29:33': "Simeon: she names her second son for being heard, not for being loved. The ache has not moved.",
    '29:34': "Levi, \"joined\" — three sons in, she is still counting them as arguments for affection.",
    '29:35': "Judah: \"Now will I praise the LORD.\" She stops bargaining, and the son she names then is the one the Messiah comes from.",
}

TAKEAWAYS.update({
    # ---- Chapter 30 ----
    '30:1': "\"Give me children, or else I die.\" The loved wife envies the unloved one. Neither has what the other has.",
    '30:2': "\"Am I in God's stead?\" Jacob is right about the theology and cruel in the delivery.",
    '30:3': "Rachel reaches for Sarah's old remedy. The household repeats a solution that failed a generation ago.",
    '30:6': "Dan — \"God hath judged me.\" Rachel reads a maid's child as a verdict in her favour.",
    '30:8': "Naphtali: she names a son after the fight with her sister and counts herself the winner.",
    '30:9': "Leah answers Rachel's move with the same move. The rivalry now runs on other women's bodies.",
    '30:11': "Gad, \"a troop cometh.\" Leah is counting numbers where she once counted for love.",
    '30:13': "Asher: \"the daughters will call me blessed.\" The audience she wants has shifted from her husband to the neighbours.",
    '30:14': "Mandrakes, thought to bring fertility, are traded for a night with a husband neither woman can hold.",
    '30:15': "\"Is it a small matter that thou hast taken my husband?\" The old wound is still open, and Rachel bargains around it.",
    '30:16': "\"I have hired thee.\" Jacob who bought a wife with labour is now rented out for an afternoon's herbs.",
    '30:17': "God hearkened unto Leah. The child comes from God, not from the mandrakes that were bought for him.",
    '30:18': "Issachar, \"hire\" — Leah reads a gift as payment owed her for the maid she handed over.",
    '30:20': "Zebulun: \"now will my husband dwell with me.\" Six sons in, she is still hoping for what six sons cannot buy.",
    '30:21': "Dinah is named without a speech. The daughter arrives unexplained, and her story waits four chapters.",
    '30:22': "\"God remembered Rachel.\" Remembering in Scripture is not recall but God moving at last.",
    '30:23': "\"God hath taken away my reproach.\" Barrenness was carried as shame, and its removal is felt as acquittal.",
    '30:24': "Joseph means \"he shall add.\" Even at the answer, Rachel is already asking for the next thing.",
    '30:25': "The moment Joseph is born, Jacob wants to go home. The son he waited for makes the exile unbearable.",
    '30:26': "\"Thou knowest my service.\" Jacob asks for his own wives and children as if for wages.",
    '30:27': "Laban has learned by experience that he prospers through Jacob, and means to keep the source.",
    '30:29': "Jacob's defence is his work record. Twenty years of labour is what he has instead of an inheritance.",
    '30:30': "\"When shall I provide for mine own house also?\" A man may serve faithfully and still be owed a life of his own.",
    '30:31': "\"Thou shalt not give me any thing.\" Jacob asks for no wage and takes the odds instead.",
    '30:32': "He claims only the off-coloured animals — the ones a shepherd would not expect to be born.",
    '30:33': "\"So shall my righteousness answer for me.\" He sets terms that make theft on his part visible at a glance.",
    '30:35': "Laban strips out the marked animals the same day and puts three days between them. He agrees and cheats simultaneously.",
    '30:37': "The peeled rods are folk science. The narrator lets Jacob's method stand without endorsing it.",
    '30:39': "The flocks bore ringstraked cattle. What Jacob credits to rods, chapter 31 will credit to God.",
    '30:42': "Jacob breeds Laban's share to be feeble. The cheated man has learned to cheat with more patience.",
    '30:43': "\"The man increased exceedingly.\" Prosperity arrives without the text saying a word about his deserving it.",

    # ---- Chapter 31 ----
    '31:1': "Laban's sons see a fixed pot of wealth: whatever Jacob has must have been taken from them.",
    '31:2': "Jacob reads a face and knows the welcome is over. Household weather changes before it is announced.",
    '31:3': "God's command and Jacob's convenience point the same direction, but the command came with a promise attached.",
    '31:5': "He names both things at once: the changed face of his father-in-law and the constant presence of God.",
    '31:7': "\"Changed my wages ten times; but God suffered him not to hurt me.\" Protection looked like twenty years of being cheated.",
    '31:9': "Jacob credits the flocks to God. The rods and the breeding tricks vanish from his own account of it.",
    '31:11': "\"Here am I.\" The schemer answers a summons the way Abraham did.",
    '31:12': "\"I have seen all that Laban doeth unto thee.\" God's silence through those years was not absence.",
    '31:13': "\"I am the God of Bethel.\" The God of the vow Jacob made twenty years ago has not forgotten it.",
    '31:14': "Rachel and Leah agree for once, and the thing they agree on is that their father has no future for them.",
    '31:15': "\"He hath sold us.\" The daughters describe the bride-price as a sale and themselves as the goods.",
    '31:16': "\"Whatsoever God hath said unto thee, do.\" Their grievance ends in submission to a word, not to their own case.",
    '31:19': "Rachel steals her father's household gods while leaving him. She takes the old religion on the road.",
    '31:20': "\"Jacob stole away unawares.\" The verb the narrator uses for Rachel's theft is used again for Jacob's departure.",
    '31:23': "Seven days' pursuit. Laban's grievance is worth chasing across a week of country.",
    '31:24': "God muzzles Laban in a dream. The rescue happens before Jacob ever knows he was in danger.",
    '31:26': "Laban speaks as if his daughters were captives, having treated them as merchandise for twenty years.",
    '31:27': "He mourns the farewell party he never intended to throw.",
    '31:29': "\"It is in the power of my hand to do you hurt: but the God of your father spake unto me.\" Real power, already overruled.",
    '31:30': "The real grievance surfaces last: \"wherefore hast thou stolen my gods?\" Gods that can be stolen are not much.",
    '31:31': "\"Because I was afraid.\" Jacob's whole flight comes down to one honest sentence.",
    '31:32': "Jacob curses the thief without knowing he has sentenced his beloved wife.",
    '31:34': "Laban's gods end up sat on, under a woman on a camel saddle. The scene is written to make them ridiculous.",
    '31:35': "Rachel deceives her father with a plea of weakness. The family talent passes down the female line too.",
    '31:36': "Jacob's anger finally breaks out, and it is the anger of a man who knows this time he is in the right.",
    '31:38': "Twenty years of flocks that never miscarried, and not one ram eaten. He kept better than the law would later require.",
    '31:39': "He bore the loss of what predators took, though no shepherd was obliged to. Laban's terms were always heavier than custom.",
    '31:40': "Drought by day, frost by night, sleep gone. The patriarch's fortune was built out of exhaustion.",
    '31:41': "Fourteen years for two wives and six for cattle, with the wages changed ten times.",
    '31:42': "\"Surely thou hadst sent me away now empty.\" Jacob credits twenty years of gain to God, not to his own shrewdness.",
    '31:43': "\"All that thou seest is mine.\" Laban claims everything and can do nothing, which is the position of a man out of power.",
    '31:44': "The covenant is offered by the loser. Men who cannot win make treaties.",
    '31:46': "A heap of stones and a shared meal. The boundary is marked by eating together on it.",
    '31:47': "Two names in two languages for one heap. Even the memorial is divided between them.",
    '31:49': "Mizpah is a watchtower between two men who do not trust each other, not a blessing between friends.",
    '31:50': "\"No man is with us; see, God is witness.\" The protection Laban arranges for his daughters is the only one left.",
    '31:52': "The agreement is that neither will cross the line. Peace here is distance, formally observed.",
    '31:53': "Laban swears by the God of Abraham and of Nahor together; Jacob swears only by the fear of his father Isaac.",
    '31:55': "Laban kisses them, blesses them, and goes home. He leaves the story without ever losing his temper again.",
})

TAKEAWAYS.update({
    # ---- Chapter 32 ----
    '32:1': "Angels meet him going home as angels met him leaving. The road out and the road back are both guarded.",
    '32:2': "\"This is God's host.\" Jacob names the place for the army he cannot see, then spends the chapter afraid.",
    '32:4': "\"Thy servant Jacob... my lord Esau.\" The man who bought the birthright now returns it in the address line.",
    '32:5': "He lists his wealth to a brother he cheated, hoping property will read as an apology.",
    '32:6': "Four hundred men, and the messengers bring no word of what they are for. Fear fills the silence.",
    '32:7': "Jacob divides the camp to cut his losses. Prudence and terror look identical from outside.",
    '32:9': "The prayer begins by quoting God's own command back to him. Jacob prays the promise, not his merit.",
    '32:10': "\"I am not worthy of the least of all the mercies.\" The bargainer of chapter 28 has stopped bargaining.",
    '32:11': "\"For I fear him.\" The petition is plain, unadorned, and names the exact thing dreaded.",
    '32:12': "\"And thou saidst.\" The last word of the prayer is God's word. Faith holds God to what he said.",
    '32:13': "The prayer over, he sends a present anyway. Trust and contingency plans coexist in the same man.",
    '32:16': "Space between the droves so the gift arrives in waves. Jacob has calculated even his repentance.",
    '32:18': "The servants are drilled to say \"thy servant Jacob\" and \"my lord Esau\" before Esau can say anything.",
    '32:20': "\"I will appease him with the present.\" He is still trying to buy what only a brother can give.",
    '32:22': "He sends everyone he loves across the river and stays on the far side alone.",
    '32:24': "\"And Jacob was left alone; and there wrestled a man with him.\" The one he had to face was never Esau.",
    '32:25': "God does not overpower him; God touches him, and the fight is over. A word would have done all night.",
    '32:26': "\"I will not let thee go, except thou bless me.\" Crippled, he finally asks for the blessing instead of taking it.",
    '32:27': "\"What is thy name?\" He has to say Jacob — supplanter — out loud before he can be given another.",
    '32:28': "Israel: he has power with God because God gave it, and he leaves the contest limping.",
    '32:29': "God asks Jacob's name and will not give his own. The blessing comes without the mastery Jacob wanted.",
    '32:30': "\"I have seen God face to face, and my life is preserved.\" Survival, not triumph, is what astonishes him.",
    '32:31': "The sun rises on a man who limps. The blessing and the injury arrive in the same night and never separate.",
    '32:32': "Israel's descendants keep a food custom in memory of a hip. The nation remembers itself by its founder's wound.",

    # ---- Chapter 33 ----
    '33:1': "He sees the four hundred men and arranges his family by how much he can bear to lose.",
    '33:2': "Rachel and Joseph go last, where it is safest. The favouritism that will wreck the family is already visible.",
    '33:3': "Jacob goes in front and bows seven times — the homage of a vassal to a king.",
    '33:4': "Esau runs, embraces, and weeps. Twenty years of dread are answered by a man with no grievance left.",
    '33:5': "\"The children which God hath graciously given thy servant.\" Jacob credits God and not his own long scheming.",
    '33:8': "Esau has to ask what the droves are for. He had not come for payment.",
    '33:9': "\"I have enough, my brother.\" The man who sold his future for soup is the one who now needs nothing.",
    '33:10': "\"As though I had seen the face of God.\" The night at Peniel and the morning with Esau are the same mercy twice.",
    '33:11': "Jacob calls the gift \"my blessing\" and presses it on Esau. He is handing back the word he once stole.",
    '33:13': "\"If men should overdrive them one day, all the flock will die.\" A shepherd sets the pace by the weakest animal.",
    '33:14': "He promises to follow Esau to Seir and then goes the other way. The reconciliation is real and the trust is not.",
    '33:15': "He refuses an escort. Jacob wants the peace without the company.",
    '33:17': "He builds a house and cattle-pens at Succoth. The man promised a land starts putting down roots short of it.",
    '33:18': "He pitches his tent before the city of Shechem. Proximity to that city is about to cost him everything.",
    '33:19': "He buys the field he camps on. A stranger in the land purchases his first piece of it outright.",
    '33:20': "El-elohe-Israel, God the God of Israel. He builds an altar under the new name he was given at the river.",

    # ---- Chapter 34 ----
    '34:1': "Dinah goes out to see the daughters of the land. The narrative gives her one act and then acts are done to her.",
    '34:2': "\"He took her, and lay with her, and defiled her.\" Three verbs, no consent, and the prince of the country did it.",
    '34:3': "He loves her afterward and speaks kindly. Affection following violence does not undo it.",
    '34:4': "\"Get me this damsel to wife.\" He asks his father for her as for a thing to be procured.",
    '34:5': "Jacob holds his peace. The father who should speak first says nothing, and his silence hands the matter to his sons.",
    '34:7': "The sons are wroth at folly wrought in Israel. They are right about the outrage before they are wrong about the answer.",
    '34:9': "Hamor proposes intermarriage — exactly what Abraham and Isaac forbade their heirs.",
    '34:10': "\"Dwell and trade ye therein.\" The offer is assimilation dressed as hospitality.",
    '34:12': "\"Ask me never so much dowry.\" Shechem assumes any price will settle it, which is its own insult.",
    '34:13': "The sons answer deceitfully. The family trade in deception has passed to the next generation and turned lethal.",
    '34:14': "They use the covenant sign as the bait. The holiest thing they have is turned into a weapon.",
    '34:19': "Shechem does it at once, and the narrator calls him the most honourable of his house. Nobody in the chapter is simple.",
    '34:21': "Hamor sells the deal to his city as good relations. He never mentions what his son did.",
    '34:23': "\"Shall not their cattle and their substance be ours?\" The real argument is profit, made in a whisper.",
    '34:24': "A whole city is cut for the greed of its leaders, and not one of them knows what is coming.",
    '34:25': "On the third day, when they were sore. The timing was planned from the moment the terms were offered.",
    '34:26': "They kill the man who wronged her and every man who did not. Vengeance never stops where justice would.",
    '34:27': "The others come after the killing to loot. The outrage over Dinah ends as plunder.",
    '34:29': "Wives and little ones taken captive. The brothers avenge one woman by doing worse to many.",
    '34:30': "Jacob's objection is his reputation and his safety, not the slaughter. He never mentions Dinah.",
    '34:31': "\"Should he deal with our sister as with an harlot?\" The last word is a question no one in the chapter answers.",

    # ---- Chapter 35 ----
    '35:1': "Bethel again — God calls Jacob back to the place of the vow he made and has not yet paid.",
    '35:2': "\"Put away the strange gods that are among you.\" There were idols in the household of the patriarch all along.",
    '35:3': "\"Who answered me in the day of my distress.\" The vow is recalled as God's faithfulness rather than his own promise.",
    '35:4': "The gods are buried under an oak. Not smashed, not argued with — buried and left behind.",
    '35:5': "After Shechem, the terror of God keeps the cities off them. Protection arrives where they had earned a reckoning.",
    '35:7': "The altar is named for the God who appeared, not for the appearing. Jacob has learned where to put the emphasis.",
    '35:8': "A nurse's death is recorded and the oak is named Weeping. Scripture notices servants nobody else would.",
    '35:9': "God appears and blesses him again. The promise is renewed by repetition, because men need it more than once.",
    '35:10': "The new name is given a second time, in daylight, without a fight.",
    '35:11': "\"A nation and a company of nations... and kings shall come out of thy loins.\" The word given to Abraham widens again.",
    '35:12': "The land is promised to a man who owns one field in it and will die in Egypt.",
    '35:14': "He sets up a pillar again where he set one up fleeing. The same stone, a different man.",
    '35:16': "Rachel goes into hard labour on the road. The son she asked for at Joseph's birth comes at the price of her life.",
    '35:17': "\"Fear not; thou shalt have this son also.\" The midwife's comfort is true and not enough.",
    '35:18': "Benoni, son of my sorrow; Benjamin, son of the right hand. The father renames the grief without denying it.",
    '35:19': "Rachel is buried on the way to Ephrath, which is Bethlehem. The road is not finished being important.",
    '35:22': "Reuben violates his father's concubine, \"and Israel heard it.\" The silence costs Reuben his birthright in chapter 49.",
    '35:23': "The twelve are listed by mother. The rivalry of two sisters is printed permanently into the shape of the nation.",
    '35:27': "Jacob reaches his father alive. The flight of chapter 27 ends at the tent it started from.",
    '35:29': "Esau and Jacob bury Isaac together. Whatever else was not resolved, they stood at the same grave.",
})

TAKEAWAYS.update({
    # ---- Chapter 36: the generations of Esau (list) ----
    '36:1': "Esau gets a full chapter of descendants. The rejected line is recorded with care before the story leaves it.",
    '36:2': "Esau's wives are Canaanite, the one thing Isaac charged Jacob to avoid. The two brothers' houses diverge at the root.",
    '36:6': "Esau moves away \"from the face of his brother Jacob.\" The separation is his own decision, not an expulsion.",
    '36:7': "The land could not bear them both — the same reason Abraham and Lot parted. Wealth divides families as reliably as poverty.",
    '36:8': "Esau settles in mount Seir, outside the promise. He takes a country and leaves the covenant.",
    '36:12': "Timna bears Amalek. A concubine's son in a name list becomes Israel's bitterest enemy for centuries.",
    '36:20': "The Horites already inhabited the land. Edom's dukes are listed alongside the people they displaced.",
    '36:24': "\"That Anah that found the mules in the wilderness.\" One man in the roll is remembered for a single odd discovery.",
    '36:31': "Kings reigned in Edom before any reigned in Israel. Esau's line got to power first, and it came to nothing.",
    '36:39': "Hadar's wife and her mother and grandmother are named. The line ends by recording women no one else recalls.",
    '36:43': "The chapter closes on dukes \"in the land of their possession.\" Esau received a possession; Jacob received a promise.",

    # ---- Chapter 37 ----
    '37:1': "Jacob dwells where his father was a stranger. The inheritance is still a tenancy.",
    '37:2': "\"Joseph brought unto his father their evil report.\" The favourite is introduced informing on his brothers.",
    '37:3': "The coat is the father's favouritism made visible and wearable. Jacob learned nothing from his own mother's preference.",
    '37:4': "They could not speak peaceably unto him. Hatred begins with the end of ordinary conversation.",
    '37:5': "He tells them the dream. Whatever God gave him, the telling of it was his own idea.",
    '37:7': "Sheaves bowing to a sheaf — the dream is about harvest and grain, which is exactly how it will come true.",
    '37:8': "\"Shalt thou indeed reign over us?\" They state the dream's meaning correctly and hate him for it.",
    '37:9': "The second dream adds sun and moon. Now even the parents are bowing, and nobody in the family is safe from it.",
    '37:10': "Jacob rebukes him and keeps the saying. The father is offended and half-convinced at once.",
    '37:11': "Envy in the brothers, watchfulness in the father. The same dream divides the house two ways.",
    '37:13': "\"Here am I.\" Joseph answers as Abraham answered, and is sent into the worst day of his life.",
    '37:14': "Jacob sends the favourite to check on sons he evidently does not trust, and does not see the danger.",
    '37:15': "A nameless man finds him wandering and sets him on the road to Dothan. Providence uses passers-by.",
    '37:18': "They conspire before he is near enough to speak. The decision is made while he is still a shape on the horizon.",
    '37:19': "\"Behold, this dreamer cometh.\" They cannot even use his name.",
    '37:20': "\"We shall see what will become of his dreams.\" They intend to kill the dream and become the means of fulfilling it.",
    '37:21': "Reuben interposes. Even in this family, murder needed only one voice against it to be delayed.",
    '37:22': "Reuben's plan is a rescue he never announces. Courage that stays secret usually arrives too late.",
    '37:23': "The first thing they take is the coat. The hatred was always aimed at what the coat said.",
    '37:24': "\"The pit was empty, there was no water in it.\" The detail is there so you know he was meant to die slowly.",
    '37:25': "\"And they sat down to eat bread.\" Men who have just thrown their brother in a pit are hungry, and the text says so.",
    '37:26': "\"What profit is it if we slay our brother?\" Judah's objection is arithmetic, not conscience.",
    '37:27': "\"He is our brother and our flesh\" — said in the course of arranging his sale.",
    '37:28': "Twenty pieces of silver, the price of a slave. Brothers turn a boy into a transaction.",
    '37:29': "Reuben comes back to an empty pit and tears his clothes. He was the one who left.",
    '37:30': "\"The child is not; and I, whither shall I go?\" Even his grief is about his own position.",
    '37:31': "They kill a kid and dip the coat. Jacob deceived his father with a goat and goat's hair; his sons use a goat on him.",
    '37:32': "\"Know now whether it be thy son's coat.\" They never say Joseph is dead; they let their father say it for them.",
    '37:33': "Jacob supplies the story himself, exactly as they intended. A lie told in questions leaves no fingerprints.",
    '37:34': "He puts on sackcloth for a son who is alive. Twenty-two years of grief rest on a piece of stagecraft.",
    '37:35': "\"He refused to be comforted.\" The brothers must stand there offering comfort for a death they arranged.",
    '37:36': "Joseph is sold to the captain of the guard. The pit ends in the house of the man who keeps Pharaoh's prison.",

    # ---- Chapter 38 ----
    '38:1': "Judah goes down from his brethren and settles among Canaanites. The interruption to Joseph's story is a descent.",
    '38:2': "He takes a Canaanite wife without a word of consultation. The line the Messiah comes through starts here.",
    '38:6': "Tamar enters as a wife chosen for someone else, and ends up the one who carries the line.",
    '38:7': "\"Er was wicked in the sight of the LORD; and the LORD slew him.\" What the wickedness was is not said; that it was seen is.",
    '38:9': "Onan takes the pleasure and withholds the duty. His sin is using his brother's widow while refusing his brother's heir.",
    '38:11': "Judah sends Tamar home \"till Shelah be grown,\" intending nothing of the kind. He protects his son by stranding her.",
    '38:14': "She lays aside the widow's garments \"for she saw that Shelah was grown.\" Her deception answers his.",
    '38:15': "Judah goes to a woman by the roadside within a chapter of burying his wife.",
    '38:16': "\"He knew not that she was his daughter in law.\" The narrator lets the reader hold what Judah does not.",
    '38:18': "Signet, bracelets and staff — he hands over his identity as a pledge for a goat.",
    '38:23': "\"Lest we be shamed.\" Judah's only concern is that the search should stop before anyone hears of it.",
    '38:24': "\"Bring her forth, and let her be burnt.\" He sentences her for the thing he paid to do, and feels no contradiction.",
    '38:25': "\"Discern, I pray thee, whose are these.\" She uses the word his own brothers used when they brought him the coat.",
    '38:26': "\"She hath been more righteous than I.\" Judah convicts himself out loud, and that admission is the turn of his life.",
    '38:27': "Twins again, as with Esau and Jacob. The struggle over who comes first is written into this family.",
    '38:29': "Pharez breaks out ahead of the marked hand. The younger takes precedence once more, and David comes from him.",
})

TAKEAWAYS.update({
    # ---- Chapter 39 ----
    '39:1': "The chapter opens with Joseph bought and sold. Everything that follows happens to a man who owns nothing.",
    '39:2': "\"The LORD was with Joseph, and he was a prosperous man\" — said of a slave. Presence, not position, is the prosperity.",
    '39:3': "An Egyptian master can see that the LORD is with him. Faithful work is legible to people who share none of the faith.",
    '39:4': "Joseph serves well in a house he was trafficked into. He does not wait for a just situation to do good work.",
    '39:5': "The Egyptian's house is blessed for Joseph's sake. Abraham's promise keeps working through a slave in a foreign kitchen.",
    '39:6': "Potiphar knew nothing he had but the bread he ate. Trust that complete is also an exposure.",
    '39:7': "\"Lie with me.\" Two words, no seduction, no pretence — a command from someone who owns him.",
    '39:8': "His first reason is his master's trust. He weighs the temptation against what has been committed to his hand.",
    '39:9': "\"How then can I do this great wickedness, and sin against God?\" The party he fears wronging cannot punish him.",
    '39:10': "Day by day. The refusal had to be made again every morning, which is what makes it costly.",
    '39:11': "None of the men of the house were there. The chapter records the moment when nobody would ever have known.",
    '39:12': "He leaves the garment and runs. A second time a coat is taken off him and used to tell a lie.",
    '39:14': "\"He hath brought in an Hebrew unto us to mock us.\" She turns her husband's servants against a foreigner in one sentence.",
    '39:16': "She keeps the garment by her until her lord comes home. The evidence is arranged before the accusation.",
    '39:17': "\"The Hebrew servant, which thou hast brought unto us.\" She blames Potiphar in the act of accusing Joseph.",
    '39:19': "His wrath was kindled — and a captain of the guard who believed his wife would have executed a slave, not jailed him.",
    '39:20': "Doing right lands him in prison. Nothing in this chapter suggests integrity is rewarded on the spot.",
    '39:21': "\"But the LORD was with Joseph\" — the same sentence as in Potiphar's house, now said of a dungeon.",
    '39:22': "He is running an institution again, from the bottom of it. Competence exercised where it cannot be promoted.",
    '39:23': "The prosperity is credited to the LORD, not to Joseph's gifts. The narrator will not let his ability take the credit.",

    # ---- Chapter 40 ----
    '40:1': "Two palace officials offend Pharaoh, and the machinery that will free Joseph begins with somebody else's trouble.",
    '40:3': "They are put in the very prison where Joseph is bound. Nothing in this story is a coincidence for long.",
    '40:4': "Joseph is charged with them and serves them. The forgotten man is assigned to wait on the men who will forget him.",
    '40:6': "He looked upon them and saw they were sad. A prisoner with reason for his own despair notices someone else's face.",
    '40:7': "\"Wherefore look ye so sadly to day?\" The question that changes his life is simple attention to two strangers.",
    '40:8': "\"Do not interpretations belong to God?\" He disclaims the gift in the same breath as he offers to use it.",
    '40:11': "The butler dreams himself doing his old job. Restoration comes to him as ordinary work resumed.",
    '40:13': "Three days to restoration. Joseph gives the good news plainly, without dressing it up.",
    '40:14': "\"Think on me when it shall be well with thee.\" He asks for one thing: to be remembered.",
    '40:15': "\"I was stolen away... and here also have I done nothing.\" He states his innocence twice and never names his brothers.",
    '40:16': "The baker asks only after hearing a favourable answer. Hope makes people eager to be told.",
    '40:19': "Joseph tells a condemned man the truth to his face. The gift is not for flattering those who hold it.",
    '40:20': "Pharaoh's birthday: one head lifted up, one lifted off. The same phrase carries both fates.",
    '40:22': "\"As Joseph had interpreted to them.\" The word is verified by both outcomes, the grim one included.",
    '40:23': "\"Yet did not the chief butler remember Joseph, but forgat him.\" The chapter ends on the failure of the only favour he asked.",

    # ---- Chapter 41 ----
    '41:1': "Two full years. The delay is stated exactly, so you feel how long Joseph waited on a forgotten promise.",
    '41:2': "The dream begins with fat cattle out of the Nile — Egypt's wealth pictured in Egypt's own river.",
    '41:4': "The lean eat the fat and Pharaoh wakes. A ruler is disturbed by something he cannot control or explain.",
    '41:7': "\"And, behold, it was a dream.\" The relief of waking lasts one clause.",
    '41:8': "All the magicians and wise men of Egypt, and none of them can read it. Expertise runs out where God speaks.",
    '41:9': "\"I do remember my faults this day.\" The butler's conscience wakes up only when it serves him.",
    '41:12': "\"A young man, an Hebrew, servant to the captain of the guard.\" Three ways of saying he was nobody.",
    '41:14': "They bring him hastily out of the dungeon. Two years of nothing, and then everything within an hour.",
    '41:15': "Pharaoh credits Joseph with the power to interpret, which is precisely what Joseph will deny.",
    '41:16': "\"It is not in me: God shall give Pharaoh an answer of peace.\" His first sentence to the king gives the credit away.",
    '41:21': "\"It could not be known that they had eaten them.\" Pharaoh's own detail: abundance consumed leaves no trace.",
    '41:25': "\"God hath shewed Pharaoh what he is about to do.\" The dream is not a warning to be averted but a decision announced.",
    '41:28': "Joseph tells a god-king that another God is running the next fourteen years of his country.",
    '41:30': "\"All the plenty shall be forgotten.\" Good years do not carry anyone through bad ones by memory.",
    '41:32': "The doubling of the dream means the thing is established. Repetition in Scripture is often certainty, not emphasis.",
    '41:33': "Having interpreted, he offers advice nobody asked for. The gift includes knowing what to do on Monday.",
    '41:34': "A fifth part taken in the plenty. Foresight here is a tax and a granary, not a miracle.",
    '41:36': "\"That the land perish not through the famine.\" The plan's aim is stated as the survival of ordinary people.",
    '41:38': "\"A man in whom the Spirit of God is.\" A pagan king identifies what Joseph's own brothers could not stand.",
    '41:40': "From prison to second in the kingdom in a single conversation. Nothing Joseph did in the dungeon earned this.",
    '41:42': "The ring, the linen, the gold chain. A third garment, and this one nobody takes off him.",
    '41:43': "\"Bow the knee\" — the sheaves of the dream, now in Egyptian.",
    '41:45': "An Egyptian name and an Egyptian priest's daughter. Joseph is absorbed into the empire he governs.",
    '41:46': "Thirty years old. Thirteen years passed between the pit and the chariot.",
    '41:49': "He gathered corn as the sand of the sea, until he left numbering. Abundance is real, and it is temporary.",
    '41:51': "Manasseh, \"God hath made me forget all my toil, and all my father's house.\" He names a son after letting go of home.",
    '41:52': "Ephraim, fruitful \"in the land of my affliction.\" He does not pretend Egypt was anything but affliction.",
    '41:54': "The dearth came in all lands, \"but in all the land of Egypt there was bread.\" Seven years of listening bought that.",
    '41:55': "\"Go unto Joseph; what he saith to you, do.\" Pharaoh sends his starving people to a former slave.",
    '41:57': "All countries came to Egypt to buy. The famine is what finally brings Joseph's brothers to him.",
})

TAKEAWAYS.update({
    # ---- Chapter 42 ----
    '42:1': "\"Why do ye look one upon another?\" Ten guilty men freeze at the word Egypt, and their father cannot think why.",
    '42:2': "\"That we may live, and not die.\" Jacob's whole policy is survival, and it drives his sons to the man they sold.",
    '42:4': "Benjamin stays home. Jacob has simply transferred the favouritism to the next son of Rachel.",
    '42:6': "They bowed down themselves before him with their faces to the earth. The dream they tried to kill arrives on schedule.",
    '42:7': "He knew them and made himself strange. The roughness is a strategy, not a relapse.",
    '42:8': "\"Joseph knew his brethren, but they knew not him.\" Twenty years and an Egyptian office are a complete disguise.",
    '42:9': "He remembers the dreams at the moment they come true, and charges them with spying. Even fulfilment does not settle him.",
    '42:11': "\"We are true men.\" The claim is false in a way they cannot yet see, and Joseph is about to prove it to them.",
    '42:13': "\"One is not.\" They report their brother's absence to his face and call it a death.",
    '42:15': "The test is Benjamin. Joseph needs to know whether they will do to Rachel's other son what they did to him.",
    '42:16': "\"Whether there be any truth in you.\" The examination is of character, and they think it is of paperwork.",
    '42:17': "Three days in ward. He gives them a short taste of what he had for years.",
    '42:18': "\"This do, and live; for I fear God.\" The fear of God is why the terms are softened, not why they are harsh.",
    '42:20': "One brother held and the rest sent home — the mirror image of what they did at the pit.",
    '42:21': "\"We saw the anguish of his soul, when he besought us, and we would not hear.\" Twenty years later they remember him begging.",
    '42:22': "Reuben's I-told-you-so is the response of a man who was right and did nothing.",
    '42:23': "They confess in front of him through an interpreter, never guessing he understands every word.",
    '42:24': "He turns away to weep, then comes back and binds Simeon. Tenderness and the hard thing are done by the same man.",
    '42:25': "The money goes back into the sacks. He will not take payment from his brothers even while testing them.",
    '42:28': "\"What is this that God hath done unto us?\" Kindness terrifies them, because guilt reads every surprise as a trap.",
    '42:35': "Every man's money in his sack, and they were afraid. A second gift lands like a second accusation.",
    '42:36': "\"All these things are against me.\" Jacob's reading of his life is exactly wrong at the moment God is saving it.",
    '42:37': "Reuben offers his own two sons as forfeit. It is a grotesque pledge, and Jacob does not even answer it.",
    '42:38': "\"He is left alone.\" Jacob says this of Benjamin with ten other sons standing in front of him.",

    # ---- Chapter 43 ----
    '43:1': "\"And the famine was sore in the land.\" Four words that force everything the family refused to do.",
    '43:2': "\"Buy us a little food.\" Jacob asks for a small errand rather than face what the errand costs.",
    '43:3': "Judah repeats the condition plainly. Someone in this family has started telling the truth.",
    '43:6': "Jacob blames his sons for answering questions honestly. Grief has made him unfair.",
    '43:8': "\"That we may live, and not die... and also our little ones.\" Judah names the grandchildren his father is risking.",
    '43:9': "\"I will be surety for him.\" Judah puts himself in the place of the brother he once sold.",
    '43:10': "\"Except we had lingered, surely now we had returned this second time.\" Delay had a price and they all paid it.",
    '43:11': "Balm, spices and myrrh — the very goods the caravan carried that took Joseph to Egypt.",
    '43:12': "Double money, and the returned money carried back. Jacob will not let an oversight stand as a debt.",
    '43:14': "\"If I be bereaved of my children, I am bereaved.\" He surrenders the outcome without pretending to be at peace with it.",
    '43:16': "Joseph sees Benjamin and orders dinner. The test continues, but the host has already decided how it ends.",
    '43:18': "Invited to dinner, they assume arrest. A guilty conscience cannot tell hospitality from ambush.",
    '43:21': "They volunteer the story of the money before anyone accuses them. Honesty is breaking out under pressure.",
    '43:23': "\"Your God, and the God of your father, hath given you treasure in your sacks.\" An Egyptian steward preaches to them.",
    '43:26': "They bow to the earth again, with the present in their hands. The second dream is completing itself in slow motion.",
    '43:27': "His first question is about his father. Everything Joseph does in these chapters is aimed at that old man.",
    '43:29': "\"God be gracious unto thee, my son.\" He blesses his full brother and still cannot say who he is.",
    '43:30': "He hurries out to weep where they cannot see. The governor of Egypt keeps breaking down in private rooms.",
    '43:31': "\"He washed his face, and went out, and refrained himself.\" Composure resumed is not the same as feeling nothing.",
    '43:32': "Three separate tables. Joseph rules Egypt and still eats apart from Egyptians.",
    '43:33': "Seated in exact birth order by a stranger, and the men marvelled. He is telling them something and they cannot hear it.",
    '43:34': "Benjamin's portion is five times the others'. Joseph sets up the old provocation to see whether they resent it now.",

    # ---- Chapter 44 ----
    '44:1': "The money goes back a second time, and this time with something planted beside it.",
    '44:2': "The silver cup in Benjamin's sack. Joseph builds a situation in which they can abandon Rachel's son cheaply.",
    '44:4': "\"Wherefore have ye rewarded evil for good?\" The steward's line is the charge Joseph could have made about the pit.",
    '44:5': "Joseph lets his household believe he divines by a cup. The disguise runs deeper than the clothes.",
    '44:8': "\"We brought again unto thee out of the land of Canaan.\" Their defence is the honesty they showed about the money.",
    '44:9': "\"Let him die, and we also will be my lord's bondmen.\" Confident men offer terms they will regret.",
    '44:10': "The steward reduces the penalty to one man. That is the whole point: only one of them need be lost.",
    '44:12': "He searches from eldest to youngest, drawing it out. The cup is found exactly where the suspense requires.",
    '44:13': "They rent their clothes and all go back. Not one of them takes the exit that was offered.",
    '44:14': "Judah and his brethren fell before him on the ground. The bowing is now grief rather than protocol.",
    '44:16': "\"God hath found out the iniquity of thy servants.\" Innocent of the cup, guilty of everything else, and Judah knows it.",
    '44:17': "\"Get you up in peace unto your father.\" Joseph offers them the identical bargain they took at the pit.",
    '44:18': "Judah comes near to a man who could kill him and asks to speak. The longest speech in Genesis begins here.",
    '44:20': "\"His brother is dead, and he alone is left of his mother.\" Judah describes the favouritism without a trace of resentment.",
    '44:22': "\"If he should leave his father, his father would die.\" The argument is entirely about the old man's survival.",
    '44:27': "\"Ye know that my wife bare me two sons.\" Judah quotes Jacob calling Rachel the wife, in front of Leah's son.",
    '44:28': "\"Surely he is torn in pieces.\" Judah repeats the lie he helped tell, to the man it was told about.",
    '44:31': "He foresees his father dying of it and cannot bear to be the cause. This is the man who priced a brother at twenty pieces.",
    '44:32': "The surety he gave in chapter 43 is now called in, and he does not look for a way out of it.",
    '44:33': "\"Let thy servant abide instead of the lad.\" Judah offers to be enslaved so Rachel's son can go free.",
    '44:34': "\"How shall I go up to my father, and the lad be not with me?\" He is handed the old sin again and will not take it.",
})

TAKEAWAYS.update({
    # ---- Chapter 45 ----
    '45:1': "He clears the room of Egyptians. Whatever this reunion costs him, his brothers will not be shamed in public.",
    '45:2': "He wept aloud, and the house of Pharaoh heard. The dignity he has built is spent in one sound.",
    '45:3': "\"I am Joseph; doth my father yet live?\" The second question is what he has wanted to ask for twenty years.",
    '45:4': "\"I am Joseph your brother, whom ye sold into Egypt.\" He names the crime and the relation in the same sentence.",
    '45:5': "\"Be not grieved, nor angry with yourselves.\" The one they wronged is the one working to lift the weight off them.",
    '45:7': "\"To save your lives by a great deliverance.\" The rescue of the family and of the promise are the same act.",
    '45:8': "\"It was not you that sent me hither, but God.\" Their guilt is not denied; it is placed inside a larger intention.",
    '45:9': "\"Tarry not.\" The message to his father has no reproach in it and no ceremony, only urgency.",
    '45:10': "Goshen: near enough to be fed, separate enough to stay a people.",
    '45:11': "\"There will I nourish thee.\" The son sold for silver becomes the one who feeds them all.",
    '45:12': "\"It is my mouth that speaketh unto you.\" No interpreter now. He has been listening in Hebrew all along.",
    '45:14': "He falls on Benjamin's neck first. The brother who was never part of the crime gets the first embrace.",
    '45:15': "\"And after that his brethren talked with him.\" Conversation resumes only after the weeping and the kissing.",
    '45:16': "Pharaoh is pleased. Joseph's family is welcomed by the throne long before a later Pharaoh knows him not.",
    '45:18': "\"Ye shall eat the fat of the land.\" Egypt offers its best, and the offer is the beginning of four hundred years.",
    '45:20': "\"Regard not your stuff.\" They are told to leave their possessions behind because better is waiting.",
    '45:22': "Benjamin gets five changes of raiment. Joseph gives a favourite's portion to the brothers who once killed over one coat.",
    '45:23': "Ten asses laden with the good things of Egypt for his father. The gift is aimed at persuading an old man to move.",
    '45:24': "\"See that ye fall not out by the way.\" He knows exactly what they will start arguing about on the road.",
    '45:26': "\"Jacob's heart fainted, for he believed them not.\" Good news too large to hold is harder than bad news.",
    '45:27': "The wagons convince him where the words could not. Faith is often revived by something you can see.",
    '45:28': "\"It is enough.\" The man who said all things were against him needs only one fact to change his mind.",

    # ---- Chapter 46 ----
    '46:1': "He stops at Beersheba to sacrifice. Before leaving the land of promise he checks with the God who gave it.",
    '46:2': "\"Jacob, Jacob.\" The doubled name, and the old answer: Here am I.",
    '46:3': "\"Fear not to go down into Egypt; for I will there make of thee a great nation.\" The nation is formed outside the land.",
    '46:4': "\"I will go down with thee into Egypt; and I will also surely bring thee up again.\" The exodus is promised in advance.",
    '46:5': "They carry Jacob in Pharaoh's wagons. Egypt's transport takes the covenant family into Egypt.",
    '46:7': "Sons, daughters, grandchildren — the whole household moves. Nothing of Israel is left in Canaan but graves.",
    '46:10': "\"Shaul the son of a Canaanitish woman.\" The roll quietly records that the separation was never clean.",
    '46:12': "Er and Onan are listed and then noted as dead, and Pharez, Tamar's son, carries the line into Egypt.",
    '46:15': "Thirty and three souls of Leah, \"with his daughter Dinah.\" The unloved wife's household is the largest in the list.",
    '46:19': "\"The sons of Rachel Jacob's wife.\" Even in a census, Rachel alone gets that title.",
    '46:26': "Threescore and six out of his loins. The nation that will fill a land goes into Egypt small enough to count.",
    '46:27': "Seventy souls. The number is kept so the reader can measure what Exodus 1 has become.",
    '46:28': "Judah is sent ahead to lead the way. The brother who offered himself as a slave is now trusted first.",
    '46:29': "Joseph makes ready his own chariot and weeps on his father's neck a good while. Rank is set aside for a long embrace.",
    '46:30': "\"Now let me die, since I have seen thy face.\" Jacob's grief ends, and he is ready to go.",
    '46:32': "Joseph coaches them to say plainly that they are shepherds. He does not want them assimilated.",
    '46:34': "\"Every shepherd is an abomination unto the Egyptians.\" Their disgrace in Egyptian eyes is what keeps them a people.",

    # ---- Chapter 47 ----
    '47:2': "Five brothers only, chosen and presented. Joseph manages the audience as carefully as he managed the famine.",
    '47:3': "They answer as Joseph told them: shepherds, and their fathers before them. They do not upgrade the family trade.",
    '47:4': "\"For to sojourn in the land are we come.\" They ask to stay as temporary guests and remain four centuries.",
    '47:6': "Pharaoh gives them the best of the land and offers work. Israel enters Egypt as honoured guests.",
    '47:7': "Jacob blesses Pharaoh. An old shepherd blesses the most powerful man on earth, and the order is not accidental.",
    '47:9': "\"Few and evil have the days of the years of my life been.\" Jacob's own verdict on a hundred and thirty years.",
    '47:10': "He blesses Pharaoh again on the way out. The audience begins and ends with the weaker man giving.",
    '47:12': "Joseph nourished them \"according to their families.\" The provision is measured by need, not by favour.",
    '47:13': "\"There was no bread in all the land.\" The narrator will not let the family's comfort hide what everyone else faced.",
    '47:14': "All the money of two countries ends in Pharaoh's house. Joseph's success is also the state's enrichment.",
    '47:15': "\"Give us bread: for why should we die in thy presence?\" Hunger makes citizens beg from their own granaries.",
    '47:16': "\"Give your cattle.\" Step by step the people hand over everything they own to stay alive.",
    '47:18': "\"There is not ought left... but our bodies, and our lands.\" They say it themselves, which does not make it less grim.",
    '47:19': "\"Buy us and our land for bread.\" The Egyptians propose their own enslavement, and Joseph accepts.",
    '47:20': "All the land of Egypt becomes Pharaoh's. The saviour of the country is also the architect of its serfdom.",
    '47:22': "The priests keep their land because the state already fed them. Religion under a king is rarely taxed.",
    '47:23': "\"I have bought you this day and your land.\" The transaction is stated bluntly and seed is handed over anyway.",
    '47:24': "A fifth to Pharaoh, four parts your own. By ancient standards it is mild, and it is still a permanent claim.",
    '47:25': "\"Thou hast saved our lives... and we will be Pharaoh's servants.\" Gratitude and servitude arrive together.",
    '47:26': "The law stands \"unto this day.\" A famine measure becomes a permanent arrangement, as they generally do.",
    '47:27': "\"They had possessions therein, and grew, and multiplied exceedingly\" — while Egypt lost everything it had.",
    '47:28': "Seventeen years in Egypt: exactly as many as Joseph had with him before the pit.",
    '47:29': "\"Bury me not, I pray thee, in Egypt.\" Jacob will take the plenty and refuses to be buried in it.",
    '47:30': "The dying man's one concern is the burying place in Canaan. He is holding on to a promise about land.",
    '47:31': "\"Swear unto me.\" He will not leave it to affection; he wants it under oath.",

    # ---- Chapter 48 ----
    '48:1': "Joseph brings his half-Egyptian sons to the deathbed. He wants them counted in.",
    '48:2': "\"Israel strengthened himself, and sat upon the bed.\" The dying man gathers what is left for one more act.",
    '48:3': "He starts with Luz, where God met him running away. His last speech begins at the lowest point of his life.",
    '48:4': "The promise he repeats is land, given to a man who is about to be carried out of Egypt in a coffin.",
    '48:5': "\"Ephraim and Manasseh... are mine; as Reuben and Simeon.\" Two Egyptian-born boys are adopted into the twelve.",
    '48:7': "Rachel's death comes back to him at the end. Some griefs are carried whole for sixty years.",
    '48:8': "\"Who are these?\" His eyes are failing, exactly as Isaac's were at the blessing he stole.",
    '48:10': "He kissed them and embraced them. A blind old man blessing grandchildren he cannot see.",
    '48:11': "\"I had not thought to see thy face: and, lo, God hath shewed me also thy seed.\" God gives past what was asked.",
    '48:13': "Joseph arranges the boys carefully so the right hand falls on the firstborn. The order matters to him.",
    '48:14': "He crosses his hands \"wittingly.\" The reversal is deliberate, not the mistake of a blind man.",
    '48:15': "\"The God which fed me all my life long unto this day.\" Jacob sums up a hard life as being fed by God.",
    '48:16': "\"The Angel which redeemed me from all evil.\" The first man in Scripture to use redeemed of himself is a deceiver.",
    '48:17': "It displeased Joseph, and he tried to move his father's hand. The favoured son wants the customary order kept.",
    '48:18': "\"Not so, my father: for this is the firstborn.\" Joseph argues from custom to a man whose whole life contradicts it.",
    '48:19': "\"I know it, my son, I know it.\" Jacob knows what he is doing, and so does the God who has done it in every generation.",
    '48:20': "\"God make thee as Ephraim and as Manasseh\" becomes the standard blessing, and it names the younger first.",
    '48:21': "\"God shall be with you, and bring you again unto the land of your fathers.\" He dies pointing them out of Egypt.",
    '48:22': "The one portion given to Joseph is the shoulder of land his sons will bury him in.",
})

TAKEAWAYS.update({
    # ---- Chapter 49 ----
    '49:1': "\"That which shall befall you in the last days.\" The deathbed words reach past his sons to their tribes.",
    '49:2': "\"Hearken unto Israel your father.\" He speaks under the name God gave him, not the one he was born with.",
    '49:3': "Reuben is given every title of the firstborn first, so that the loss of it lands harder.",
    '49:4': "\"Unstable as water, thou shalt not excel.\" The night with Bilhah is named at last, thirty years after Jacob said nothing.",
    '49:5': "Simeon and Levi are paired by their weapons. Shechem has followed them to the deathbed.",
    '49:6': "\"O my soul, come not thou into their secret.\" Jacob refuses his sons' violence even while blessing them.",
    '49:7': "The anger is cursed, not the men. Scattering is the sentence, and Levi's scattering will become priesthood.",
    '49:8': "\"Thy father's children shall bow down before thee.\" The fourth son gets the supremacy three older brothers forfeited.",
    '49:9': "\"Judah is a lion's whelp.\" The image outlasts the tribe and the kingdom and turns up in Revelation.",
    '49:10': "\"The sceptre shall not depart from Judah... until Shiloh come.\" The promise narrows here from a family to a throne.",
    '49:11': "Vines used as hitching posts and wine as washing water. The abundance is so great it is squandered.",
    '49:13': "Zebulun gets a coastline. Some blessings are simply geography, and geography is destiny for a tribe.",
    '49:14': "\"A strong ass couching down between two burdens.\" Strength that settles for comfort is diagnosed in one image.",
    '49:15': "He saw that rest was good and bowed his shoulder to bear. The price of pleasant land is paid in tribute.",
    '49:17': "Dan bites the heel of a horse and unseats the rider. The small tribe wins by ambush, not by weight.",
    '49:18': "\"I have waited for thy salvation, O LORD.\" A dying man stops mid-prophecy to say what he has actually been doing.",
    '49:19': "Gad is overcome and overcomes at the last. The blessing includes the defeat, not just the recovery.",
    '49:20': "Asher's portion is fat bread and royal dainties. Prosperity is named without apology as a gift.",
    '49:21': "\"Naphtali is a hind let loose: he giveth goodly words.\" Freedom and speech are the whole of that tribe's blessing.",
    '49:22': "\"A fruitful bough by a well; whose branches run over the wall.\" Joseph's fruitfulness spills past its own boundary.",
    '49:23': "\"The archers have sorely grieved him, and shot at him, and hated him.\" His father finally names what was done to him.",
    '49:24': "His bow held \"by the hands of the mighty God of Jacob.\" The strength is on loan, and the text says so.",
    '49:26': "\"Him that was separate from his brethren.\" The separation that was a crime is spoken of as a consecration.",
    '49:27': "Benjamin the wolf — the gentle youngest of the story gets the most violent blessing in the chapter.",
    '49:28': "\"Every one according to his blessing he blessed them.\" Even the hard words are counted as blessing.",
    '49:29': "\"Bury me with my fathers.\" His last command is about a cave, because the cave is a claim on the land.",
    '49:30': "The field Abraham bought is named in full. The only ground the patriarchs owned is a grave.",
    '49:31': "\"And there I buried Leah.\" Jacob asks to be laid beside the wife he did not choose.",
    '49:33': "He gathered up his feet into the bed and yielded up the ghost. The scheming ends quietly, with his sons around him.",

    # ---- Chapter 50 ----
    '50:1': "Joseph falls on his father's face and weeps. The governor of Egypt is a son first for one more moment.",
    '50:2': "Israel is embalmed by Egyptian physicians. The body has to be preserved because the grave is in another country.",
    '50:3': "Egypt mourns him seventy days, nearly a Pharaoh's mourning, for a shepherd from Canaan.",
    '50:4': "Joseph asks Pharaoh's house to speak for him. Second in the kingdom, he still needs permission to bury his father.",
    '50:5': "\"My father made me swear.\" The oath is what he leans on, because an oath outranks his own preference.",
    '50:6': "\"Go up, and bury thy father, according as he made thee swear.\" Pharaoh honours a promise made to a foreign God's man.",
    '50:7': "The elders of Egypt go up with him. A state funeral procession escorts Israel back to the promised land.",
    '50:8': "The little ones and the flocks stay in Goshen. They are going to a burial, and they are coming back.",
    '50:10': "Seven days of mourning at Atad. The grief is given its full measure before the burying.",
    '50:11': "The Canaanites call the place Abel-mizraim, the mourning of the Egyptians. To the locals, Israel now looks Egyptian.",
    '50:13': "His sons carry him into Canaan themselves. What Egypt escorted, the family had to carry the last distance.",
    '50:14': "Joseph returned into Egypt. The whole company goes back, which is how the exile becomes permanent.",
    '50:15': "With the father dead, the brothers assume the kindness was for his sake. Guilt cannot believe a pardon.",
    '50:16': "They send a message rather than come. And the quoted command from Jacob appears nowhere in the record.",
    '50:17': "\"Forgive, I pray thee now, the trespass of thy brethren.\" Joseph weeps that they still think he is holding it.",
    '50:18': "\"Behold, we be thy servants.\" They offer themselves as slaves — the very thing they sold him into.",
    '50:19': "\"Fear not: for am I in the place of God?\" He refuses the role of judge that they are pressing on him.",
    '50:20': "\"Ye thought evil against me; but God meant it unto good.\" Both intentions were real; only one decided the outcome.",
    '50:21': "\"I will nourish you, and your little ones.\" The forgiveness is not a speech but an undertaking to feed them for life.",
    '50:23': "He lives to see great-grandchildren on his knees. The man robbed of his family is given three generations of it.",
    '50:24': "\"God will surely visit you, and bring you out of this land.\" Joseph dies in a palace and calls Egypt a place to leave.",
    '50:25': "\"Ye shall carry up my bones from hence.\" His coffin becomes a standing promise that the story is not finished.",
    '50:26': "Genesis ends with a coffin in Egypt. The book of beginnings closes on a grave that is waiting to be moved.",
})

TAKEAWAYS.update({
    # ---- Chapter 34 (continued) ----
    '34:8': "Hamor opens with his son's longing and never mentions the offence. Negotiation begins by editing the facts.",
    '34:16': "\"We will become one people.\" The brothers offer the one thing Abraham's family could not survive, and mean none of it.",
    '34:18': "The words pleased Hamor and Shechem. The trap works because it offers them what they already wanted.",
    '34:28': "Sheep, oxen and asses taken. The loot is itemised so the reader can weigh it against the sister.",

    # ---- Chapter 35 (continued) ----
    '35:13': "\"God went up from him in the place where he talked with him.\" The visit ends, and the place stays marked.",
    '35:20': "The pillar on Rachel's grave stands \"unto this day.\" Jacob's love outlives her by a monument on a roadside.",
    '35:26': "\"These are the sons of Jacob, which were born to him in Padanaram.\" Twenty years of trouble produced a nation.",
    '35:28': "A hundred and eighty years. Isaac outlives by decades the day he thought he was dying and gave the blessing away.",

    # ---- Chapter 38 (continued) ----
    '38:8': "\"Raise up seed to thy brother.\" The duty is to give a dead man a future at your own expense.",
    '38:10': "The LORD slew him also. Two sons dead, and Judah will draw the wrong conclusion about the cause.",
    '38:12': "Judah is comforted and goes up to his sheepshearers. Tamar is still waiting in her father's house.",
    '38:19': "She puts the widow's garments back on. The disguise was for one purpose and she resumes her real position.",
    '38:21': "\"There was no harlot in this place.\" The neighbours cannot find the woman because she was never one.",
    '38:28': "A scarlet thread marks the hand that came first. Even the midwife is trying to fix the birth order.",
    '38:30': "Zarah, marked and second. The one who seemed to have precedence loses it in the moment of being born.",

    # ---- Chapter 40 (continued) ----
    '40:5': "Both men dream in one night, each dream fitted to its own meaning. Nothing here is random.",
    '40:10': "Budding, blossom and ripe grapes in one vine. The dream compresses a season into a moment, as the reading will.",
    '40:17': "Birds eating out of the basket on his head. The baker is being consumed while he carries Pharaoh's food.",
    '40:21': "The butler gets his old life back exactly. Restoration, for most people, looks like ordinary duty resumed.",

    # ---- Chapter 41 (continued) ----
    '41:3': "The lean cattle come up out of the same river. Famine and plenty arrive from one source.",
    '41:6': "Blasted with the east wind — the desert wind. The threat to Egypt comes from the side away from the Nile.",
    '41:13': "\"As he interpreted to us, so it was.\" The butler's testimony is that the word proved true, hanging included.",
    '41:19': "\"Such as I never saw in all the land of Egypt for badness.\" Pharaoh adds his own horror to the retelling.",
    '41:24': "\"There was none that could declare it to me.\" A king surrounded by advisers is left with no one to ask.",
    '41:26': "\"The dream is one.\" Two pictures, one message; the doubling was never two separate futures.",
    '41:27': "Seven years of famine named out loud. The interpretation offers no escape clause and no condition.",
    '41:29': "Plenty is announced first. The years of ease are the resource, and almost nobody treats them that way.",
    '41:35': "\"Let them keep food in the cities.\" The plan is storage, distribution and administration — unglamorous and decisive.",
    '41:37': "The thing was good in the eyes of Pharaoh and all his servants. A slave's plan convinces a whole court.",
    '41:39': "\"Forasmuch as God hath shewed thee all this.\" Pharaoh promotes him on the strength of the God Joseph credited.",
    '41:41': "\"See, I have set thee over all the land of Egypt.\" Said to a man who walked in from a dungeon that morning.",
    '41:44': "\"Without thee shall no man lift up his hand or foot.\" Absolute authority handed to a foreigner and a former convict.",
    '41:47': "\"The earth brought forth by handfuls.\" The good years are extravagant, which is what makes them easy to waste.",
    '41:48': "Food stored in the city nearest the field that grew it. Even the logistics are thought through.",
    '41:53': "\"The seven years of plenteousness were ended.\" One sentence, and the whole margin for preparation closes.",
    '41:56': "He opened the storehouses and sold. The grain is not given away; Egypt buys back what Egypt grew.",

    # ---- Chapter 42 (continued) ----
    '42:3': "\"Joseph's ten brethren went down.\" The narrator counts them by the brother they are about to meet.",
    '42:10': "\"Nay, my lord, but to buy food are thy servants come.\" They call themselves his servants without hearing it.",
    '42:14': "He refuses their explanation flatly. The accusation is a lever, and he keeps the pressure on it.",
    '42:19': "One bound, nine sent home with food for their households. He will not starve their children to make his point.",
    '42:27': "The money is discovered at an inn, far from anyone they can ask. Mercy found in the wrong place feels like danger.",
    '42:30': "\"The man, who is the lord of the land, spake roughly to us.\" Their report to Jacob leaves out what they confessed.",
    '42:34': "\"Ye shall traffick in the land.\" They repeat the promise of trade, as if business were the issue.",

    # ---- Chapter 43 (continued) ----
    '43:5': "\"We will not go down.\" Judah states the limit of what obedience to his father can achieve.",
    '43:7': "\"The man asked us straitly of our state.\" They did not volunteer Benjamin; the questions found him.",
    '43:15': "They took the present, the money and Benjamin, and stood before Joseph. Everything he arranged is now in the room.",
    '43:24': "Water for their feet and provender for the asses. The men braced for arrest are given ordinary hospitality.",
    '43:28': "\"Thy servant our father is in good health.\" The one fact Joseph wanted is delivered in a formal courtesy.",

    # ---- Chapter 44 (continued) ----
    '44:7': "\"God forbid that thy servants should do according to this thing.\" They are indignant, and they have done far worse.",
    '44:11': "Every man takes down his own sack and opens it. Innocence is confident enough to be searched.",
    '44:15': "\"Wot ye not that such a man as I can certainly divine?\" He plays the Egyptian magician to the last minute.",
    '44:21': "\"That I may set mine eyes upon him.\" Judah repeats the demand without once calling it unreasonable.",
    '44:23': "\"Except your youngest brother come down with you, ye shall see my face no more.\" The condition drove everything since.",
    '44:26': "\"We may not see the man's face, except our youngest brother be with us.\" The family's life came to depend on Benjamin going.",
    '44:29': "\"Ye shall bring down my gray hairs with sorrow to the grave.\" Judah has memorised the sentence that would condemn him.",
    '44:30': "\"His life is bound up in the lad's life.\" Judah understands his father's love now instead of resenting it.",
})
