#!/usr/bin/env python3
"""Written one-line takeaways for Habakkuk 1-3."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "He calls it a burden he saw. What follows is less a message delivered than an argument conducted.",
    '1:2': "The book opens by accusing God of not listening. The complaint is inside scripture, not aimed at it.",
    '1:3': "He blames God for the sight itself. Being made to see what is wrong is its own kind of suffering.",
    '1:4': "The grievance is legal. The courts still sit, and what proceeds from them is wrong judgment.",
    '1:5': "The answer comes with a warning attached: you will not believe it. God concedes the reply is hard.",
    '1:6': "The answer to injustice is a worse nation, and God names himself as the one raising it up.",
    '1:8': "Leopard, wolf, eagle. The army is described entirely in predators, and none of them is slow.",
    '1:11': "The instrument credits its own god for the win. God works through a nation that will not admit it.",
    '1:12': "Mid-protest he grants a point: they are ordained for correction, which is not the same as the end.",
    '1:13': "The objection is comparative. Not that Judah is good, but that the nation sent against her is worse.",
    '1:14': "If men are fish with no ruler over them, nobody is governing. That is precisely what he fears.",
    '1:15': "The fisherman is glad of a full net. From inside the net the same event reads differently.",
    '1:16': "He sacrifices to his own tackle. An empire that keeps winning needs no god but its equipment.",
    '1:17': "The first round closes on a question mark. Nothing has been settled and he stops asking.",
    # ---- Chapter 2 ----
    '2:1': "He posts himself like a sentry and expects to be reproved. The argument is pressed without insolence.",
    '2:2': "Plain enough to be read at a run. The vision is given a form that will outlast the man who got it.",
    '2:3': "The appointed time is God's, not the waiting man's. Delay is not refusal, and it is still delay.",
    '2:4': "\"The just shall live by his faith\" — taken up three times in the New Testament, and Romans is built on it.",
    '2:5': "Appetite is the charge. What cannot be satisfied will keep eating long after it has stopped being hungry.",
    '2:6': "The taunt song is put in the mouths of the nations he looted. The sentence is sung by his victims.",
    '2:7': "The creditors wake up. A man living on other people's goods is himself a debt that comes due.",
    '2:8': "The sentence is the crime handed back, with the same word used for what he did and what is done to him.",
    '2:9': "He builds his nest high to be safe from what he has been doing. The precaution is a confession.",
    '2:10': "Cutting off many people is charged first as an injury done to his own house and his own soul.",
    '2:11': "The house gives evidence against the man who built it. Stolen material does not stay quiet.",
    '2:12': "Civic achievement is priced at what it cost other people. A city can be an atrocity with streets.",
    '2:13': "All that labour, and it goes into the fire. The futility is not an accident but of the LORD of hosts.",
    '2:14': "Between the woes, the sea. What finally fills the earth is knowledge of God, not the reach of an empire.",
    '2:15': "The woe falls on engineered humiliation — a man made drunk on purpose, and hospitality as the cover.",
    '2:16': "The one who poured is handed a cup. The measure he chose is the measure that comes back to him.",
    '2:18': "\"A teacher of lies\" — the maker instructs his own handiwork, and then believes what it tells him.",
    '2:19': "He tells the wood to wake up. The gold laid over the outside is why he expects an answer.",
    '2:20': "After two rounds of argument the instruction is silence. The temple's reply is not another argument.",
    # ---- Chapter 3 ----
    '3:1': "The argument ends as a piece of music. What he arrived at is set down for other people to sing.",
    '3:2': "He does not ask for the wrath to be cancelled, only that mercy be remembered inside it.",
    '3:3': "The prayer turns backwards, to Teman and Paran. What steadies him is old news rather than new.",
    '3:4': "\"There was the hiding of his power.\" Even the brightness is described as concealment.",
    '3:6': "The everlasting mountains scatter and the perpetual hills bow. One thing in the verse lasts.",
    '3:8': "He asks whether God was angry at the rivers. The implied answer is that water was never the target.",
    '3:9': "The bow comes out because of oaths sworn. God's weaponry is tied to something he promised.",
    '3:10': "The deep lifts up its hands. Creation is drawn as a crowd reacting, never as scenery.",
    '3:11': "Joshua's day recalled: the light of God's arrows was enough, so the sun could afford to stand still.",
    '3:13': "Salvation goes out with an anointed one, and it lands on the head of the house that did the harm.",
    '3:14': "The enemy's delight is described as devouring the poor secretly, where there would be no witness.",
    '3:16': "Rottenness in the bones, and then rest. The trembling is not cured; it is what he rests inside.",
    '3:17': "Figs, vines, olives, fields, flock, herd — the inventory fails item by item, leaving nothing to hope on.",
    '3:18': "\"Yet I will rejoice\" — said with the stalls empty. The decision is made while everything is failing.",
    '3:19': "Feet for walking high ground, not for standing still. And the whole thing is handed to the choir.",
}
