#!/usr/bin/env python3
"""Written takeaways for Isaiah 34-66."""

TAKEAWAYS = {
    # ---- Chapter 34 ----
    '34:1': "An oracle against one small neighbour opens by convening the whole earth to listen in.",
    '34:2': "\"He hath utterly destroyed them\" — the sentence is reported in the past tense before a blow has landed.",
    '34:3': "The horror named is not the dying but the lying unburied, which in this world is the deeper shame.",
    '34:4': "The sky is treated as something that wears out and is rolled up, like a scroll finished being read.",
    '34:5': "The sword is bathed in heaven before it comes down. Judgement is prepared above and only then aimed.",
    '34:6': "Slaughter is described in the vocabulary of the altar: Bozrah is not a battlefield here but a sacrifice.",
    '34:8': "\"The controversy of Zion\" — vengeance is framed as a lawsuit with a party that has to answer.",
    '34:9': "Pitch and brimstone are Sodom's materials, lent to Edom. The judgement is quoted from an older one.",
    '34:10': "Smoke going up for ever is not the fire's length but its finality: nothing will ever be rebuilt on that ground.",
    '34:11': "\"The line of confusion, and the stones of emptiness\" — Genesis 1's formless void, measured out deliberately.",
    '34:12': "The titles survive the people. Nobles are summoned to a kingdom where there is no longer anyone to rule.",
    '34:13': "The palaces are not flattened but occupied. Thorns and owls move into rooms still standing.",
    '34:14': "The only rest anywhere in this chapter is found by a screech owl.",
    '34:16': "\"Seek ye out of the book of the LORD, and read\" — the prophecy invites being checked against the record later.",
    '34:17': "Lot and measuring line are Joshua's words for settling the promised land. Here the allotment goes to wild beasts.",

    # ---- Chapter 35 ----
    '35:1': "The desert is the one doing the rejoicing. Gladness reaches the landscape before it reaches anybody in it.",
    '35:2': "The wilderness is given Lebanon's glory and Carmel's excellency. What it blooms with is borrowed, not native.",
    '35:3': "The command goes to the bystanders, not to the weak. Someone else is told to steady those failing knees.",
    '35:4': "\"He will come with vengeance\" and \"he will come and save you\" are one sentence about one arrival.",
    '35:5': "Opened eyes and unstopped ears are the proof Jesus sends back to John in prison when asked who he is.",
    '35:6': "Healed bodies and watered desert are listed as a single event, as though the two had the same cause.",
    '35:7': "The habitation of dragons from the chapter before becomes grass and reeds. The curse is reversed on its own address.",
    '35:8': "\"The wayfaring men, though fools, shall not err therein\" — the road is made plain enough that stupidity is no bar.",
    '35:9': "No lion is there. The danger is not fought off along the way; it is simply absent from it.",
    '35:10': "Sorrow and sighing flee. They are not borne patiently to the end but chased off the premises.",

    # ---- Chapter 36 ----
    '36:1': "The chapter opens with the fortified cities already taken. Judah's defence policy has failed before a word is said.",
    '36:2': "The conduit of the upper pool is where Isaiah once met Ahaz. Same spot, different king, same question about trust.",
    '36:4': "\"Thus saith the great king\" mimics the prophets' formula, and the question he asks is the book's own: what are you trusting?",
    '36:5': "He calls Judah's war talk vain words, and about the war talk he happens to be right.",
    '36:6': "Egypt as a broken reed that pierces the hand leaning on it is Isaiah's own verdict, now in an Assyrian mouth.",
    '36:7': "Hezekiah's reform is turned into evidence against him: the man who pulled down altars must have offended the God who owned them.",
    '36:8': "Two thousand horses offered as a taunt, because the insult is that Judah could not find riders for them.",
    '36:10': "\"Am I now come up without the LORD?\" Isaiah had already called Assyria the rod of God's anger; the boast is half true and wholly blind.",
    '36:11': "The officials do not dispute the argument, only the language. They know the wall is listening.",
    '36:12': "He refuses to speak privately, because his real audience was never the negotiators but the people who will starve.",
    '36:14': "The attack shifts from Judah's allies to Judah's king: not can he win, but can he be believed.",
    '36:15': "Having disposed of Egypt and of Hezekiah, he comes to the last thing left, which is the LORD.",
    '36:16': "Surrender is offered in Israel's own picture of peace — every man his vine and fig tree — to make it sound like coming home.",
    '36:17': "\"A land like your own land.\" Deportation is sold as relocation, and the lie is the word like.",
    '36:18': "The argument is empirical and its flaw is the category: he is reasoning about the LORD from a list of idols.",
    '36:20': "He files the LORD among the gods he has already beaten. That single misplacement is what the next chapter answers.",
    '36:21': "Silence is a policy here, not paralysis. The king had given orders that nothing be said back.",
    '36:22': "They answer him with nothing and tear their clothes only once they are out of his sight.",

    # ---- Chapter 37 ----
    '37:1': "The king's first move against an army is to go into a building and put on sackcloth.",
    '37:2': "The prophet is sent for after the crisis has arrived rather than before it, but he is sent for.",
    '37:3': "\"The children are come to the birth, and there is not strength to bring forth\" — failure at the last possible moment.",
    '37:4': "\"It may be the LORD thy God will hear.\" Hezekiah hopes tentatively, and calls him Isaiah's God rather than his own.",
    '37:6': "\"Be not afraid of the words.\" The weapon that has actually been deployed against Jerusalem so far is speech.",
    '37:7': "A blast, a rumour, and a murder at home. None of the promised deliverance requires Judah to raise a soldier.",
    '37:9': "The rumour arrives exactly as promised, and it looks like nothing more than ordinary foreign politics.",
    '37:10': "The letter no longer argues that Judah is weak. It argues that God is lying to them.",
    '37:11': "The case rests on a track record, which is the strongest argument available to a man reasoning without God.",
    '37:14': "He does not answer the letter. He spreads it open where someone else can read it.",
    '37:16': "The prayer grants Rabshakeh's whole comparison and denies its premise: there is only one God in the room.",
    '37:17': "\"Open thine eyes, O LORD, and see.\" He asks God to take the insult personally, because it was meant that way.",
    '37:18': "\"Of a truth\" — Hezekiah concedes the enemy's facts before asking for anything.",
    '37:19': "The gods Assyria burned were wood and stone already. Their defeat proves nothing about the God who made the wood.",
    '37:20': "The reason he gives for rescue is that the nations may learn something, not that Judah may be comfortable.",
    '37:21': "\"Whereas thou hast prayed to me\" — the answer is tied explicitly to the prayer, and said to be because of it.",
    '37:22': "The laughter is given to the besieged city. Zion mocks the army camped outside her wall.",
    '37:23': "\"Whom hast thou reproached?\" The question does not deny the insult; it re-files who received it.",
    '37:24': "The boast is quoted back to him, and in it conquest sounds like logging — tall cedars cut down for the pleasure of it.",
    '37:25': "Drying up rivers with the sole of his foot is a claim to have done at will what God did once at the sea.",
    '37:26': "The conqueror learns he has been carrying out a plan formed long before him and not by him.",
    '37:27': "The nations he flattened were grass on a housetop already, withered before he ever reached them.",
    '37:28': "\"I know thy abode, and thy going out.\" The God he listed among the beaten has been watching his daily movements.",
    '37:29': "Hook in the nose and bridle in the lips is how Assyria led its own prisoners home.",
    '37:30': "The sign offered is not a wonder but a farming calendar: two years of scavenging, then a normal sowing.",
    '37:31': "Root downward before fruit upward. The recovery begins underground, where nobody can see it working.",
    '37:32': "The remnant survives by \"the zeal of the LORD of hosts,\" which is to say by nothing Judah arranged.",
    '37:33': "Not an arrow, not a siege bank. The promise is that the attack will not even properly begin.",
    '37:35': "\"For mine own sake, and for my servant David's sake.\" Both stated reasons for sparing the city are outside the city.",
    '37:36': "The deliverance asks nothing of Judah at all. They rise in the morning and find it already done.",
    '37:38': "He is killed by his own sons while worshipping, and the god he was bowing to did not manage the one thing gods are for.",

    # ---- Chapter 38 ----
    '38:1': "\"Thou shalt die, and not live\" is a word from the LORD that the same chapter will revise.",
    '38:2': "Turning his face to the wall is a prayer so private it begins by shutting out the prophet standing there.",
    '38:3': "He pleads his own walk and his perfect heart. This is how a man prays when the covenant he knows ties life to obedience.",
    '38:5': "\"I have heard thy prayer, I have seen thy tears.\" The tears are counted separately, as though they said what the words could not.",
    '38:6': "The private reprieve turns out to carry the city with it. One man's fifteen years and Jerusalem's survival arrive together.",
    '38:8': "The sign is given in the one thing that never goes backward, which is why it works as a sign.",
    '38:9': "The psalm is written after the recovery. What the sickbed felt like is set down by a man no longer on it.",
    '38:10': "The complaint is not death but timing: he is being deprived of years he had already counted as his.",
    '38:11': "What he expects to lose first is seeing — seeing the LORD, and seeing other people. Both are losses of company.",
    '38:12': "A shepherd's tent struck at dawn, a weaver cutting the finished cloth off the loom. Life ends by being tidily packed away.",
    '38:14': "\"O LORD, I am oppressed; undertake for me.\" He asks God to stand surety for him against God's own hand.",
    '38:15': "\"He hath both spoken unto me, and himself hath done it.\" Rescue leaves him quieter, not louder: he will go softly for the rest of his years.",
    '38:16': "\"By these things men live.\" The illness itself is put on the list of what gave him life rather than took it.",
    '38:17': "\"Thou hast cast all my sins behind thy back\" — the recovery is described as forgiveness, because that is what he thought was wrong.",
    '38:18': "The argument is that God will lose a worshipper. Israel's hope beyond the grave is thin here, and the text lets the thinness stand.",
    '38:19': "\"The father to the children shall make known thy truth.\" What the added years are for is one more generation being told.",
    '38:21': "A poultice of figs sits in the same account as a reversed shadow. Ordinary medicine is not treated as a rival to the miracle.",
    '38:22': "The king who has just been given fifteen years still asks for the sign. Assurance does not arrive once and stay.",

    # ---- Chapter 39 ----
    '39:1': "The first friendly embassy in the book comes from Babylon, and it comes because Hezekiah was ill.",
    '39:2': "The man who spread a letter before the LORD now spreads his treasury before Babylon, and leaves nothing unshown.",
    '39:3': "Isaiah asks what they saw and where they came from. Hezekiah answers the easier question and calls Babylon far off.",
    '39:4': "\"All that is in mine house have they seen.\" He reports it without a trace of embarrassment, which is the problem.",
    '39:6': "The showing has become the inventory. What was displayed with pride is the list of what will be carried away.",
    '39:7': "The sentence reaches his sons, and the word eunuchs means the line itself is what gets cut.",
    '39:8': "\"There shall be peace and truth in my days.\" He calls the word good because the disaster is scheduled for someone else.",
}
