#!/usr/bin/env python3
"""Written takeaways for Isaiah 1-33."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The vision is dated by four kings. Prophecy arrives inside named politics, not above it.",
    '1:2': "Heaven and earth are called as witnesses, and the charge is not crime but children rebelling.",
    '1:3': "The ox and the ass know their owner. Israel is measured against livestock and comes off worse.",
    '1:4': "Four names for the people, all of them about descent: sin here is inherited and then chosen.",
    '1:5': "More beating has produced more revolt. Punishment by itself has not made them any better.",
    '1:6': "Wounds untended from sole to head. The diagnosis is total, and nobody has tried to dress it.",
    '1:7': "The ruin is put in the present tense, as something they can look at while being told why.",
    '1:8': "Zion is left like a watchman's hut after harvest, still standing and emptied of all around it.",
    '1:9': "Sodom was spared nothing. Judah survives only because a remnant was left, and left by the LORD.",
    '1:10': "Calling Jerusalem's rulers Sodom takes the comparison just made and hands it to them as a name.",
    '1:11': "God says he is full. The sacrifices were commanded by him, and he will not take them like this.",
    '1:12': "\"Who hath required this at your hand?\" Worship he appointed is disowned once it is emptied out.",
    '1:13': "Incense, new moon, sabbath, assembly — the whole calendar is called iniquity while injustice stands.",
    '1:14': "God calls his own feasts a burden he is weary of carrying. The tiredness is on his side of it.",
    '1:15': "The hands spread out in prayer are the same hands full of blood, which is why he will not look.",
    '1:16': "\"Cease to do evil\" comes first. Repentance begins by stopping, not by adding something better.",
    '1:17': "Learning to do well is spelled out entirely as attention to people with no one to defend them.",
    '1:18': "After the indictment, an invitation to reason. Scarlet is not argued away but changed outright.",
    '1:19': "Willing and obedient are paired. The obedience asked for begins in consent, not in compliance.",
    '1:20': "The alternative is stated flatly, and its warrant is the mouth that spoke it, not the odds.",
    '1:21': "\"How is the faithful city become an harlot!\" The grief is over what she used to be.",
    '1:22': "Silver to dross, wine watered. Decline shows up as dilution long before it shows as collapse.",
    '1:23': "Bribes and neglected widows in one breath: the gift taken is what the fatherless pays for.",
    '1:24': "God speaks of easing himself of his enemies, and the enemies in view are his own people.",
    '1:25': "The hand turned against her is a refiner's hand. This judgement is aimed at what is worth keeping.",
    '1:26': "Restoration is described as getting honest judges back, and as nothing more spectacular than that.",
    '1:27': "Zion is redeemed with judgment. The same justice that condemns her is what buys her back.",
    '1:28': "Mercy for the city and ruin for those who forsake the LORD are announced in one sentence.",
    '1:29': "The oaks and gardens were chosen. Shame comes from having wanted them, not just from losing them.",
    '1:30': "The idolater ends up resembling his idol: an oak losing its leaf, a garden with no water in it.",
    '1:31': "The strong man and his handiwork burn together. The maker goes up with the thing he made.",

    # ---- Chapter 2 ----
    '2:2': "The nations come up of their own accord. The mountain is exalted and the traffic runs inward.",
    '2:3': "They ask to be taught before they ask to be helped. Instruction is what the pilgrimage is for.",
    '2:4': "Weapons become farm tools because the arbiter is trusted. Disarmament follows judgement.",
    '2:5': "Isaiah turns the vision on his own house: walk now in the light the nations will come for later.",
    '2:6': "Judah is forsaken because she imported everything — divination, alliances, other people's children.",
    '2:7': "Silver, gold, horses, chariots, all without end. Plenty is listed here as a symptom, not a blessing.",
    '2:8': "They worship the work of their own fingers. Isaiah spells out the manufacture to make it absurd.",
    '2:9': "Mean man and great man both bow, and the levelling is toward the idol rather than toward God.",
    '2:10': "The command is to hide in the rock, and the fear on offer is not of armies but of God's glory.",
    '2:11': "The whole day's work is stated as one change of altitude: man brought down, the LORD alone up.",
    '2:12': "Pride is not one sin among many here. It is the thing the day of the LORD is set against.",
    '2:13': "Cedars and oaks come first because a tall tree is the readiest picture of what has to fall.",
    '2:15': "Tower and fenced wall: even what was built for safety is counted among the things that are too high.",
    '2:16': "Ships of Tarshish and pleasant pictures. Trade and art go down with the fortifications.",
    '2:17': "The refrain returns unchanged, which is how the chapter says nothing else will be left standing.",
    '2:18': "The idols get one short clause. What men spent their lives making is disposed of in five words.",
    '2:19': "They run to caves from glory itself. There is nowhere for the proud to be when God rises.",
    '2:20': "Idols of silver and gold thrown to moles and bats — the worshipper himself admits they are worthless.",
    '2:22': "\"Whose breath is in his nostrils\" — the reason to stop trusting men is how easily they stop breathing.",

    # ---- Chapter 3 ----
    '3:1': "Judgement begins by removing supports: bread, water, and then everyone who held things together.",
    '3:2': "The list is of competence — soldier, judge, prophet, elder. Losing the capable is itself the sentence.",
    '3:3': "Even craftsman and orator are counted as props. A society falls when its ordinary skills are taken.",
    '3:4': "Children as princes is not sentiment but chaos: rule handed to those who cannot carry it.",
    '3:5': "When leadership fails, oppression turns horizontal — neighbour on neighbour, young against old.",
    '3:6': "A man is made ruler because he still owns a coat. Office goes to whoever has anything left.",
    '3:7': "He swears he will not be a healer. In a real collapse nobody wants the job of fixing it.",
    '3:8': "The cause is named as tongue and doings against the LORD, not as bad luck or stronger neighbours.",
    '3:9': "They declare their sin and hide it not. Shamelessness is treated as evidence given in open court.",
    '3:10': "In the middle of a sentence on the nation, the righteous is told separately it shall be well with him.",
    '3:11': "The wicked gets the reward of his hands. The punishment is described as wages, not as invention.",
    '3:12': "\"They which lead thee cause thee to err.\" The guides are the ones who lost the road.",
    '3:13': "The LORD stands up to plead. He is prosecutor in a case against the people he covenanted with.",
    '3:14': "The charge against the elders is specific: the spoil of the poor is in their houses, and findable.",
    '3:15': "\"Grind the faces of the poor.\" God asks what they think they are doing, and still says my people.",
    '3:16': "The indictment moves to how the daughters of Zion walk. Display is read as the same disorder.",
    '3:17': "The punishment answers the offence exactly: what was crowned is struck, what was flaunted uncovered.",
    '3:18': "The finery is begun as an inventory of what will be taken, item by item, starting with the anklets.",
    '3:23': "The catalogue runs on and on, and its length is the point: this was the whole preoccupation.",
    '3:24': "Five reversals in a line — stink, rent, baldness, sackcloth, burning — each replacing its ornament.",
    '3:25': "Behind the lost finery is the real loss: the men are dead, and they were who paid for it.",
    '3:26': "The city ends the chapter sitting on the ground, which is where mourners sit.",

    # ---- Chapter 4 ----
    '4:1': "Seven women to one man measures the slaughter, and the reproach they want lifted is childlessness.",
    '4:2': "\"The branch of the LORD\" — after all the stripping, what is beautiful is something God grows.",
    '4:3': "Holiness belongs to the remnant by being written down, not by having survived on merit.",
    '4:4': "The washing is done by a spirit of judgment and burning. The cleansing is the judgement, not its reversal.",
    '4:5': "Cloud by day and fire by night return, and now over every dwelling, not only over the tabernacle.",
    '4:6': "The glory is also a roof. What terrified the proud in chapter two here keeps the rain off.",

    # ---- Chapter 5 ----
    '5:1': "A love song is the form chosen for an indictment, and the audience does not hear it coming.",
    '5:2': "Every possible care is listed — fence, stones, choice vine, tower, winepress — and then wild grapes.",
    '5:3': "The hearers are made judges of the case, which is how a parable gets a verdict out of the guilty.",
    '5:4': "\"What could have been done more?\" God puts his own labour up for review and asks for a ruling.",
    '5:5': "The judgement is simply taking the hedge away. He does not trample the vineyard; he stops guarding it.",
    '5:6': "No rain commanded to the clouds. The owner of the song turns out to be the one who runs the weather.",
    '5:7': "The pun lands at the end: he looked for judgment and got oppression, for righteousness and got a cry.",
    '5:8': "The first woe is on property — joining house to house until a man is left alone in the middle of the land.",
    '5:9': "The houses gained by absorbing neighbours will stand empty. The sentence is the ambition completed.",
    '5:10': "Ten acres for one bath. The yield collapses on the very land that was so carefully accumulated.",
    '5:11': "The woe falls on the schedule: early to the drink and late to leave it, a whole day given over.",
    '5:12': "Music and wine are not what is condemned. The charge is that they regard not the work of the LORD.",
    '5:13': "Captivity comes \"because they have no knowledge.\" Ignorance is treated as culpable, not as innocent.",
    '5:14': "Hell opens its mouth without measure, and what goes down is named as glory, multitude and pomp.",
    '5:15': "Mean man and mighty man are brought low together. The levelling does not respect the ranking.",
    '5:16': "God is sanctified in righteousness. His holiness is displayed by judging, not in spite of it.",
    '5:17': "Lambs graze among the ruins of the rich. The picture of what follows is deliberately modest.",
    '5:18': "Sin is hauled along on a cart rope, as though the sinner were doing the pulling. The effort is his.",
    '5:19': "They dare God to hurry. Mockery here takes the form of asking for the judgement to come sooner.",
    '5:20': "Calling evil good gets its own woe. Renaming a thing is treated as a separate offence from doing it.",
    '5:21': "Wise in their own eyes: the woe falls on self-assessment, the one court that always acquits.",
    '5:22': "The only strength they are credited with is a capacity for drink, listed as though it were valour.",
    '5:23': "The drinking woe ends at the bench — justice sold, and the righteous stripped of his standing for a fee.",
    '5:24': "The root rots because the law was cast away. The failure is traced below anything anyone could see.",
    '5:25': "\"His hand is stretched out still.\" The refrain means the blow already struck was not the last one.",
    '5:26': "God whistles for a distant empire the way a man whistles for bees. Assyria comes because he called.",
    '5:27': "The army never tires, never stumbles, never loosens a strap. Its discipline is the frightening part.",
    '5:28': "Hooves like flint and wheels like a whirlwind — a description of equipment that will not fail.",
    '5:29': "The lion roars, takes the prey, and none delivers it. The last clause is the one that matters.",
    '5:30': "The chapter closes in a darkness that reaches the sky: even the light in the heavens goes out.",

    # ---- Chapter 6 ----
    '6:1': "The year a king died is the year Isaiah saw the throne that had never once been vacant.",
    '6:2': "The seraphim cover their own faces. Creatures nearer to God than he is cannot look either.",
    '6:3': "Holy three times, then the whole earth full of his glory. The holiness is not confined to the temple.",
    '6:4': "The building shakes at a voice. What Isaiah hears is a sound the architecture cannot take.",
    '6:5': "He confesses not a deed but a mouth, and names his people's mouths in the same breath as his own.",
    '6:6': "The coal is taken from the altar — that is, from the place where a sacrifice has already been made.",
    '6:7': "The lips that confessed uncleanness are the lips that are touched. It is done to him, not by him.",
    '6:8': "The call comes only after the cleansing. He volunteers as a forgiven man, not as a qualified one.",
    '6:9': "The commission is to preach to people who will not hear, and he is told so before he starts.",
    '6:10': "The word hardens what it does not soften. Preaching itself is handed over as the instrument of judgement.",
    '6:11': "\"Lord, how long?\" The prophet's first response to his own commission is to ask when it ends.",
    '6:12': "The answer is emptiness: men removed far away, and a great forsaking left in the midst of the land.",
    '6:13': "A stump is not nothing. The holy seed is what is still there after the tenth has been burned again.",

    # ---- Chapter 7 ----
    '7:1': "Two small kings besiege Jerusalem and cannot prevail. The crisis is limited before the chapter begins.",
    '7:2': "The house of David shakes like trees in wind. The dynasty of the promise is as frightened as anyone.",
    '7:3': "Isaiah brings his son Shearjashub, whose name — a remnant shall return — is half the message already.",
    '7:4': "Syria and Ephraim are two smoking firebrands, already burnt down. Fear is answered by resizing it.",
    '7:6': "Their plan is to put a nobody on David's throne, which is what makes it a matter for God.",
    '7:7': "\"It shall not stand.\" The whole counter-plan is dismissed in a sentence, with no argument attached.",
    '7:8': "A date is set for Ephraim's end, which turns the feared coalition into something with an expiry.",
    '7:9': "\"If ye will not believe, surely ye shall not be established.\" Security is made to rest on faith.",
    '7:11': "Ahaz may ask a sign of any size he likes, from the depth to the height. The freedom is nearly reckless.",
    '7:12': "Refusing to ask is dressed as reverence. Isaiah treats it as the opposite: Ahaz has already decided.",
    '7:13': "Wearying men is one thing. The charge is that the house of David is now wearying God as well.",
    '7:14': "A sign is given to the king who refused one. Matthew reads Immanuel of Christ; here it is God with us in Ahaz's crisis.",
    '7:15': "Butter and honey is not luxury but what is left when the fields are gone. The child eats in a ruin.",
    '7:16': "The sign is timed by a child's growing. Before he can choose, the two kings will both be gone.",
    '7:17': "Relief from Syria and Ephraim is followed by Assyria. The rescuer Ahaz hired becomes the disaster.",
    '7:18': "God hisses for fly and bee. Egypt and Assyria come like insects at a signal, not as powers with plans.",
    '7:19': "They settle in every crevice of the land. The occupation is so thorough that it has no front line.",
    '7:20': "The hired razor is Assyria, hired by Ahaz himself, and it shaves the body from head to foot.",
    '7:21': "A man's whole herd is one cow and two sheep. Wealth is being counted again in single animals.",
    '7:22': "There is butter in plenty because there are so few people left alive to eat it.",
    '7:23': "A vineyard worth a thousand silverlings becomes briers. Cultivated ground goes back to scrub.",
    '7:24': "Men go there with bow and arrow. The farmland has become a place you only enter armed.",
    '7:25': "Hills once dug with the mattock are left for cattle to tread. Farming gives way to grazing.",

    # ---- Chapter 8 ----
    '8:1': "The prophecy is written large and in public beforehand, so that no one can revise it afterwards.",
    '8:2': "Faithful witnesses are named. Prophecy is given the kind of evidence a court would recognise.",
    '8:3': "The child's name is the message — speed the spoil. A family is made to carry the oracle around.",
    '8:4': "Damascus and Samaria will be plundered before a baby can talk. The timetable is deliberately short.",
    '8:6': "Shiloah's waters go softly. They refused the quiet stream and asked for a river instead.",
    '8:7': "The river they preferred is Assyria, and it comes over its banks. The chosen help becomes the flood.",
    '8:8': "The flood reaches to the neck and stops there, and the land it drowns is still called Immanuel's.",
    '8:9': "\"Ye shall be broken in pieces\" three times over. The nations may associate all they like.",
    '8:10': "Counsel comes to nought for one stated reason: God is with us. Immanuel is offered as the argument.",
    '8:11': "Isaiah is warned with a strong hand not to walk the way of his people. Here dissent is commanded.",
    '8:12': "The crowd's word for the crisis is confederacy, and the prophet is told not to catch their fear.",
    '8:13': "Fear is not removed but relocated. The cure for dread of Assyria is dread of the LORD himself.",
    '8:14': "The same God is sanctuary and stone of stumbling. What a man does with him decides which one he is.",
    '8:15': "Stumble, fall, broken, snared, taken. The verbs pile up on those who trip over the sanctuary.",
    '8:16': "When the nation will not hear, the word is sealed among disciples and kept for a later reading.",
    '8:17': "He waits for a God who is hiding his face, and counts the hiding as God's act rather than absence.",
    '8:18': "The prophet and his oddly named children are themselves the sign, before any of them says a word.",
    '8:19': "Consulting the dead on behalf of the living is simply stated, and the absurdity does the work.",
    '8:20': "\"To the law and to the testimony.\" The test of any spirit is whether it agrees with what God said.",
    '8:21': "Hunger drives them to curse their king and their God and then look up. Desperation is not yet faith.",
    '8:22': "They look to the earth and find only darkness. The chapter ends with nowhere left to look.",

    # ---- Chapter 9 ----
    '9:1': "Galilee of the nations, the first region overrun, is named as the first to have its gloom lifted.",
    '9:2': "The light is seen by people still walking in darkness. It arrives before the darkness is gone.",
    '9:3': "Joy is likened to harvest and to dividing spoil — the gladness of people handed what they did not make.",
    '9:4': "The yoke is broken as in the day of Midian, a victory won with almost no army at all.",
    '9:5': "Boots and bloodied coats become fuel for a fire. The gear of war is not stored away but burned.",
    '9:6': "A child carries the government, and the names run past anything a king could bear: the mighty God.",
    '9:7': "The endless kingdom rests on the zeal of the LORD, not on the competence of David's house.",
    '9:8': "A word is sent and it lights on Israel. What God says is described as something that lands.",
    '9:9': "\"In the pride and stoutness of heart\" is the heading over the boast the next verse records.",
    '9:10': "Bricks fall, so they will build in hewn stone. Disaster is read as a chance to upgrade, not to repent.",
    '9:11': "The enemies about to come against them are said to be set up by the LORD, not merely permitted.",
    '9:12': "Devoured before and behind, and still his hand is stretched out. The refrain's first appearance.",
    '9:13': "The people do not turn to him that smiteth them, which is the whole thing the smiting was for.",
    '9:14': "Head and tail cut off in one day. The judgement does not work down through the ranks in order.",
    '9:15': "The tail is explained as the prophet that teacheth lies. False comfort is the lowest thing named.",
    '9:16': "Leaders who cause error and the led who are destroyed: neither the misleading nor the misled is spared.",
    '9:17': "No mercy even on fatherless and widows — the very people chapter one told them to go and defend.",
    '9:18': "Wickedness burns as fire and takes the briers first. It consumes the thing it is growing in.",
    '9:19': "\"No man shall spare his brother.\" Society is the fuel here, and it is burning from the inside.",
    '9:20': "Eating the flesh of his own arm is the exact picture of a nation devouring itself and staying hungry.",
    '9:21': "Manasseh and Ephraim eat each other and then combine against Judah, and the refrain closes it again.",
}

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "The woe falls on legislation. This injustice is written down, prescribed, and perfectly legal.",
    '10:2': "Widows made prey and the fatherless robbed — by decree, which is what makes it worse than theft.",
    '10:3': "\"To whom will ye flee for help?\" The question assumes they have been relying on something.",
    '10:4': "Nothing left but to crouch among prisoners or fall among the slain, and the refrain sounds again.",
    '10:5': "Assyria is God's rod. The empire that thinks it picked its own wars is being held by a handle.",
    '10:6': "God gives the charge and calls the target a hypocritical nation. His own people, described honestly.",
    '10:7': "\"He meaneth not so.\" The instrument's intention differs from the hand's, and both are quite real.",
    '10:8': "Assyria's boast begins with rank: even my princes are kings. Pride starts by counting its staff.",
    '10:9': "Fallen cities recited as proof that no city holds. The boast argues from a genuine track record.",
    '10:10': "He files Jerusalem's God among the idols he has already collected. The mistake is a category error.",
    '10:11': "Samaria fell, so Jerusalem will fall. His logic is sound; his premise about her God is not.",
    '10:12': "God punishes the rod only after the work is done. The instrument is used first and judged after.",
    '10:13': "\"By the strength of my hand I have done it.\" The charge against Assyria is a sentence of self-credit.",
    '10:14': "Empires gathered like eggs from a nest, and nothing so much as peeped. Cruelty described as easy.",
    '10:15': "The axe cannot boast against the man who swings it. The whole oracle turns on one obvious question.",
    '10:16': "Leanness sent among the fat ones. The punishment begins in the very prosperity that fed the pride.",
    '10:17': "Israel's light becomes a fire. The same holiness that comforts his people burns their conqueror.",
    '10:18': "Soul and body, forest and field, consumed together, and Assyria's standard-bearer faints at the front.",
    '10:19': "So few trees left that a child could write the list. Ruin measured by how short the tally runs.",
    '10:20': "The remnant will stop leaning on the power that struck them. Judah's habit of buying protection ends.",
    '10:21': "\"The remnant shall return\" was Isaiah's son's name. Here it is spoken as promise, not as warning.",
    '10:22': "Sand of the sea, and only a remnant comes back. The promise to Abraham is narrowed, not cancelled.",
    '10:23': "The consumption is determined. Even the scale of the loss is fixed beforehand, not running wild.",
    '10:24': "Be not afraid of the Assyrian, said to people who will still be beaten. The fear goes, not the rod.",
    '10:25': "\"Yet a very little while.\" The comfort offered is not that it stops but that it will be short.",
    '10:26': "Midian at Oreb, and the rod over the sea. Deliverance is argued from history, not from present odds.",
    '10:27': "The yoke is destroyed because of the anointing. What breaks it is consecration rather than strength.",
    '10:28': "The invasion is traced town by town, and naming the familiar places is what makes it terrifying.",
    '10:29': "Ramah afraid, Gibeah fled. The advance is measured in the panic of places the hearers know well.",
    '10:30': "Even Anathoth, small and poor, is told to lift up its voice. Nowhere is too minor to be counted.",
    '10:32': "He shakes his hand at Jerusalem from Nob and gets no nearer. The threat stops at a gesture.",
    '10:33': "The forest picture turns on Assyria: now it is the high ones of stature who get lopped off.",
    '10:34': "Lebanon falls by a mighty one. The cedar that stood for empire is felled by somebody stronger.",

    # ---- Chapter 11 ----
    '11:1': "A rod out of the stem of Jesse. The tree was cut down first, and the king grows from a stump.",
    '11:2': "The Spirit rests on him rather than coming and going, and the last gift named is the fear of the LORD.",
    '11:3': "He judges neither by what he sees nor by what he hears. Every other court has only those two.",
    '11:4': "The poor and the meek get the righteous verdict, and the rod he strikes the earth with is his mouth.",
    '11:5': "Righteousness and faithfulness are his belt — the garment that holds everything else in place.",
    '11:6': "Predator and prey lie down and a child does the leading. Peace is pictured as appetite reversed.",
    '11:7': "The lion eats straw. It is not that the lion is restrained but that it now wants something else.",
    '11:8': "A baby's hand over a snake's hole is the boldest image the chapter has for danger simply undone.",
    '11:9': "The reason for the peace is knowledge of the LORD filling the earth, not better handling of beasts.",
    '11:10': "The Gentiles seek the root of Jesse. Paul quotes this line as warrant for a gospel beyond Israel.",
    '11:11': "A second time, and the list of countries is longer than the exodus. Restoration outgrows its model.",
    '11:12': "An ensign for the nations, and the ones gathered are the outcasts and the dispersed — the strays.",
    '11:13': "Ephraim and Judah stop envying each other. Reunion is described as the end of a family grudge.",
    '11:14': "Old enemies are subdued together. The restored people are not left as a defenceless remnant.",
    '11:15': "The sea and the river are split again. God repeats his old miracles instead of inventing new ones.",
    '11:16': "A highway home from Assyria, \"like as it was\" from Egypt. The second exodus is dated by the first.",

    # ---- Chapter 12 ----
    '12:1': "Praise begins by naming the anger as real and over. The comfort is not that God was never angry.",
    '12:2': "\"I will trust, and not be afraid.\" Trust is chosen against fear, and God himself is called the salvation.",
    '12:3': "Wells of salvation are drawn from, not admired. What has been given is meant to be used daily.",
    '12:4': "The response to rescue turns outward at once: declare his doings among the people.",
    '12:5': "The song is for excellent things done, and their being known in all the earth is part of the point.",
    '12:6': "The reason for shouting is who is in the midst of Zion, not anything Zion has managed to become.",

    # ---- Chapter 13 ----
    '13:1': "\"The burden of Babylon\" — Isaiah names an empire that is not yet the danger it is going to be.",
    '13:2': "A banner raised and a hand shaken. The muster is described before the army is ever identified.",
    '13:3': "God calls the invaders \"my sanctified ones.\" Pagan soldiers are set apart for his own purpose.",
    '13:4': "The noise of nations gathering is credited to the LORD of hosts mustering them. He is the officer.",
    '13:5': "They come from the end of heaven, and they are named as the weapons of his indignation.",
    '13:6': "The day of the LORD is at hand, and the destruction is traced to the Almighty, not to the Medes.",
    '13:7': "Every hand faint and every heart melting. The first casualty named is the will to resist at all.",
    '13:8': "Labour pains, amazement, faces like flame. The horror is described from inside the people it hits.",
    '13:9': "The day is called cruel and the text does not soften it. Its stated aim is to destroy the sinners.",
    '13:10': "Sun, moon and stars withhold their light. A political collapse is given the scale of the cosmos.",
    '13:11': "The charge is arrogancy and haughtiness, which is what this whole book keeps saying God is against.",
    '13:12': "A man more precious than gold because so few are left. Value here is only a measure of scarcity.",
    '13:13': "The earth is moved out of her place. What shakes is not Babylon's walls but the ground beneath them.",
    '13:14': "Her mercenaries and merchants run home. An empire dissolves back into the nations it was made of.",
    '13:15': "No distinction between the found and the joined. In a sack, association is enough to be killed for.",
    '13:16': "Children dashed, houses spoiled, wives ravished. Isaiah will not describe war in clean language.",
    '13:17': "The Medes cannot be bought off with silver. What makes them terrible is that they do not want loot.",
    '13:18': "No pity on the fruit of the womb. Their indifference to gold turns out to extend to everything.",
    '13:19': "\"The glory of kingdoms\" ends like Sodom. The finest city is measured against the byword for ruin.",
    '13:20': "Not even an Arab will pitch a tent there. Desolation is measured by the nomads who pass it by.",
    '13:21': "Owls and satyrs occupy the palaces. What fills the empty city is the opposite of civilisation.",
    '13:22': "\"Her days shall not be prolonged.\" The oracle puts a clock on a city that is still rising.",

    # ---- Chapter 14 ----
    '14:1': "Mercy on Jacob arrives with strangers joined to them. Restoration does not close the doors.",
    '14:2': "Captors become servants. The reversal is total, and the text states it without embarrassment.",
    '14:3': "Rest from sorrow and fear comes first. Only then is the taunt-song against Babylon allowed.",
    '14:4': "It is called a proverb, not a curse. Israel's response to the tyrant's fall is a piece of poetry.",
    '14:5': "The staff and the sceptre are broken by the LORD. The tyrant did not simply run out of luck.",
    '14:6': "He struck with a continual stroke, and now none hinders his pursuers. The pattern turns on him.",
    '14:7': "The whole earth is quiet, and the quiet is the first thing noticed. Tyranny had been very noisy.",
    '14:8': "Even the trees are glad, because nobody is coming up to cut them for his building projects.",
    '14:9': "Hell stirs its dead kings to stand and greet him. The welcome is the cruellest part of the fall.",
    '14:10': "\"Art thou become like unto us?\" The dead ask the only question that still matters to him.",
    '14:11': "His music comes down with him and worms are made his bedding. Splendour is answered with vermin.",
    '14:12': "\"How art thou fallen from heaven\" is sung over a king of Babylon, and later read of a fallen angel.",
    '14:13': "Five \"I will\" clauses drive the boast, and every one of them is about getting further up.",
    '14:14': "\"I will be like the most High\" is the last step of the climb, and the oldest temptation there is.",
    '14:15': "The ascent ends in the sides of the pit, and the whole direction reverses on a single word: yet.",
    '14:16': "They look narrowly at him and cannot match the body to the reputation. Terror shrinks on inspection.",
    '14:17': "The charge that closes the list is small and precise: he never opened the house of his prisoners.",
    '14:18': "Other kings lie in glory in their own houses. The comparison is set up only in order to deny it him.",
    '14:19': "Cast out like a trampled carcase. For a king, being left unburied is a sentence after the sentence.",
    '14:20': "Burial with his peers is refused him because he destroyed his own land and killed his own people.",
    '14:21': "The dynasty is ended so that it cannot rebuild. The judgement reaches forward to prevent a return.",
    '14:22': "Name, remnant, son and nephew all cut off. Babylon loses not only its power but its memory.",
    '14:23': "Swept with the besom of destruction. The empire is described as dirt being brushed off a floor.",
    '14:24': "The LORD swears by his own thought and purpose. The guarantee offered is simply that he decided it.",
    '14:25': "Assyria, the present danger, is broken in God's own land. The far oracle turns back to the near one.",
    '14:26': "One purpose over the whole earth. The oracles against the nations are not separate plans but one.",
    '14:27': "\"Who shall disannul it?\" Two questions with no answer, and that unanswerableness is the comfort.",
    '14:28': "The burden is dated to the year Ahaz died. A king's death is the occasion for a word to Philistia.",
    '14:29': "Philistia should not celebrate a broken rod. What comes out of the root is worse than what broke.",
    '14:30': "The poor feed safely while Philistia's root dies of famine. Two outcomes set flat against each other.",
    '14:31': "Smoke from the north is the invasion's signature, seen long before the army itself is in view.",
    '14:32': "The answer to foreign envoys is not a treaty but a fact: the LORD founded Zion, and the poor trust it.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:1': "\"In the night\" twice over: Moab's two chief cities fall while nobody is awake to watch it.",
    '15:2': "Moab goes up to its high places to weep, and the gods it weeps to are the ones that just failed.",
    '15:3': "Sackcloth on the roofs and in the streets. The grief is public; there is nowhere private left.",
    '15:4': "Even the armed soldiers cry out. When the army weeps, the defence has already been abandoned.",
    '15:5': "\"My heart shall cry out for Moab.\" The prophet grieves for a nation under his own oracle.",
    '15:6': "The waters of Nimrim dry and no green thing is left. The land itself joins in the mourning.",
    '15:7': "They carry their savings to the brook of willows. A refugee is defined by what he can lift.",
    '15:8': "The cry runs right round the border, which is how a small country measures a total disaster.",
    '15:9': "Blood in the water, and lions for whoever escapes. The oracle will not let the remnant off.",

    # ---- Chapter 16 ----
    '16:1': "Moab is told to send tribute lambs to Zion. The refuge offered is the people she looked down on.",
    '16:2': "A bird pushed out of the nest is the picture chosen for Moab's women at the river crossings.",
    '16:3': "\"Hide the outcasts\" — Moab is asked for exactly the shelter Moab will shortly need herself.",
    '16:4': "Shelter my outcasts, and the reason given is that the oppressor's time is already running out.",
    '16:5': "A throne established in mercy, in David's tent. Moab's hope is tied to Judah's king, not her own.",
    '16:6': "Moab's pride is why the offer will not be taken. Isaiah states it as a thing everybody knows.",
    '16:7': "Moab howls for Moab. The only mourner the nation has left at the end is itself.",
    '16:8': "The vine of Sibmah reached over the sea. The trade it fed is what the invading lords broke down.",
    '16:9': "\"I will water thee with my tears.\" God speaks of weeping over the nation he is judging.",
    '16:10': "The vintage shouting has ceased, and the one who stopped it says so in the first person.",
    '16:11': "His inward parts sound like a harp for Moab. The judge's grief is described as something physical.",
    '16:12': "Moab prays at its high place and does not prevail. Exhaustion in worship is not the same as faith.",
    '16:13': "This word was spoken long before. The oracle is old news being brought out and read again.",
    '16:14': "Now a clock is put on it — three years, counted exactly, the way a hired man counts his term.",

    # ---- Chapter 17 ----
    '17:1': "Damascus ceases to be a city. The oracle's first words take away the thing the name meant.",
    '17:2': "Flocks lie down where cities stood, and nothing frightens them. It is peace of the wrong kind.",
    '17:3': "Ephraim's fortress goes with Damascus. Partners in the alliance share the fate of the alliance.",
    '17:4': "\"The fatness of his flesh shall wax lean.\" Judgement on Jacob is a body losing its weight.",
    '17:5': "Harvest is the picture. The reaper's arm sweeps the ears, and what is gathered does not grow back.",
    '17:6': "Gleanings left in the top boughs. The remnant appears here as two or three olives simply missed.",
    '17:7': "A man looks to his Maker in that day. Attention comes back only once everything else is stripped.",
    '17:8': "He stops looking at what his own fingers made. Repentance is described as a change of gaze.",
    '17:9': "Strong cities are left like an abandoned branch. Fortification does not keep a city inhabited.",
    '17:10': "Forgetting the rock of thy strength is named as the root, and the strange slips are its fruit.",
    '17:11': "Made to grow overnight and reaped as a heap of grief. Quick religion yields a quick sorrow.",
    '17:12': "Nations rushing like the sea. The noise is real, and the oracle treats it as no more than noise.",
    '17:13': "God rebukes them and they blow off like chaff. The rebuke is a word, and a word is all it takes.",
    '17:14': "Trouble at evening and gone before morning. The whole reversal is dated by a single night.",

    # ---- Chapter 18 ----
    '18:1': "Woe to a land so far off it is known only by its rivers. The oracle reaches past the known world.",
    '18:2': "Ambassadors come in reed boats looking for allies, and what they are given is not a treaty.",
    '18:3': "The whole world is told to watch for the ensign. What happens here is meant to be a public signal.",
    '18:4': "God says he will take his rest and consider. The stillness is deliberate watching, not absence.",
    '18:5': "He prunes before harvest, cutting the sprigs as the grape forms. The timing is his to choose.",
    '18:6': "Birds summer on the bodies and beasts winter on them. The ruin is measured out in two seasons.",
    '18:7': "The nation described in verse two arrives here carrying a present. The far people come to Zion.",

    # ---- Chapter 19 ----
    '19:1': "The LORD rides a cloud into Egypt, and the idols are moved before any army has crossed a border.",
    '19:2': "Egypt is set against Egypt. This judgement arrives as civil war rather than as invasion.",
    '19:3': "Counsel destroyed, they turn to charmers and wizards. Failed wisdom drives a nation to magic.",
    '19:4': "A cruel lord is given them, and the giving is God's. Even bad government is handed over on purpose.",
    '19:5': "The Nile fails. For Egypt the river drying up is the end of every other institution as well.",
    '19:6': "Brooks of defence emptied. What had protected the country was water, and the water is going.",
    '19:7': "Everything sown by the brooks withers. The agriculture goes down with the river that fed it.",
    '19:8': "The fishermen mourn first, because they are the ones who notice the water before anybody else.",
    '19:9': "Flax workers and weavers confounded. The export trade fails alongside the food supply.",
    '19:10': "Even the men who built the ponds are broken in their purposes. Engineering cannot replace a river.",
    '19:11': "Pharaoh's counsellors claim descent from ancient kings, and Isaiah calls the claim brutish.",
    '19:12': "\"Where are thy wise men?\" They are asked to say what the LORD purposed, and they cannot.",
    '19:13': "The princes are deceived and have deceived. Being the stay of the tribes only makes it worse.",
    '19:14': "A perverse spirit mingled in by the LORD, and Egypt staggers like a drunk. The confusion is sent.",
    '19:15': "Head and tail, branch and rush, and no work for any of them. Nobody in Egypt can do anything.",
    '19:16': "Egypt is afraid at a shaken hand. No army is mentioned, because the gesture is enough by itself.",
    '19:17': "Judah, the small neighbour, becomes a terror to Egypt, and only because of what God determined.",
    '19:18': "Five Egyptian cities speaking the language of Canaan. Conversion is described as learning a tongue.",
    '19:19': "An altar to the LORD inside Egypt. What the law forbade elsewhere stands here as a sign of mercy.",
    '19:20': "Egypt cries out against her oppressors and is sent a saviour, in the very words used of Israel.",
    '19:21': "The Egyptians shall know the LORD. Knowing, not merely fearing, is where the oracle ends up.",
    '19:22': "He smites and heals in one line, and the order matters: the blow comes from the hand that cures.",
    '19:23': "A highway between Egypt and Assyria — the two empires that had ground Israel between them.",
    '19:24': "Israel is the third, not the first. The chosen nation takes its place in a company of three.",
    '19:25': "\"Blessed be Egypt my people.\" The covenant words are handed to the old oppressor without hedging.",
})

TAKEAWAYS.update({
    # ---- Chapter 20 ----
    '20:1': "The oracle is pinned to a dated campaign. Isaiah's sign-acts happen inside verifiable history.",
    '20:2': "Isaiah is told to strip and go barefoot. The prophet's own dignity is spent on the message.",
    '20:3': "Three years of it, called a sign and a wonder. The cost is measured in years, not in minutes.",
    '20:4': "Egyptians led away stripped, and the shame of it is named as the point rather than the cruelty.",
    '20:5': "Ethiopia was their expectation and Egypt their glory. Both words describe misplaced confidence.",
    '20:6': "\"How shall we escape?\" The question comes from people who had a plan and watched it taken away.",

    # ---- Chapter 21 ----
    '21:1': "\"The desert of the sea\" is a riddle for Babylon, and the oracle arrives like a storm off open country.",
    '21:2': "The treacherous are dealt with treacherously. The instrument God uses is no better than its target.",
    '21:3': "The vision doubles the prophet over with pain. Seeing what God will do is not a comfortable gift.",
    '21:4': "His night of pleasure is turned into fear. The oracle spoils an evening that was going perfectly well.",
    '21:5': "Feasting and then a sudden call to arms. One verse holds the banquet and the ambush together.",
    '21:6': "A watchman is set to declare what he sees. Prophecy is presented here as a job of plain reporting.",
    '21:7': "He listens diligently and long before anything appears at all. Most of the work is waiting.",
    '21:8': "He stands on the watchtower by day and keeps his ward whole nights. No one comes to relieve him.",
    '21:9': "\"Babylon is fallen, is fallen\" — said twice, and Revelation takes up the phrase unchanged.",
    '21:10': "He calls his people threshed corn, and claims only to have passed on what he heard, nothing added.",
    '21:11': "\"Watchman, what of the night?\" Edom asks the one question anyone awake in the dark actually asks.",
    '21:12': "Morning comes, and also night. The honest answer will not promise only the half that was wanted.",
    '21:13': "Caravan traders are told they will sleep in the forest. Even the merchants have nowhere to trade.",
    '21:14': "Tema carries water and bread out to the fleeing. A small mercy is recorded inside a judgement oracle.",
    '21:15': "They fled from the drawn sword and the bent bow. The detail is what flight actually looks like.",
    '21:16': "A hireling's year is the measure again — short, counted, and owed to somebody on an exact day.",
    '21:17': "Kedar's archers are diminished, and the warrant given is that the God of Israel said it of Arabs.",

    # ---- Chapter 22 ----
    '22:1': "\"The valley of vision\" is Jerusalem. The burden against the nations turns here on the city itself.",
    '22:2': "A joyous, noisy city whose dead were not killed in battle. They died of famine or in flight.",
    '22:3': "The rulers fled and were taken without a fight. Leadership collapsed before the walls did.",
    '22:4': "Isaiah refuses to be comforted. The prophet insists on grieving what he himself announced.",
    '22:5': "Trouble, treading down and perplexity, and all of it by the Lord GOD of hosts in his own city.",
    '22:6': "Elam and Kir carry the quiver and shield. The besiegers are named, and they are hired from far off.",
    '22:7': "Chariots in the choicest valleys and horsemen at the gate. The best land is where the army parks.",
    '22:8': "The covering taken off, they look to the armoury. The first reflex in a crisis is to count weapons.",
    '22:9': "They saw the breaches were many, and what they did next was see about the water supply.",
    '22:10': "Houses are pulled down to patch the wall. Emergency measures cost the people their homes.",
    '22:11': "Every sensible thing was done and one thing was left out: they never looked to him that made it.",
    '22:12': "God called for weeping, baldness and sackcloth. The mourning was not a mood but a summons.",
    '22:13': "\"Let us eat and drink; for to morrow we shall die.\" Their answer to a call to repent is a feast.",
    '22:14': "This iniquity shall not be purged till ye die. The heaviest sentence in the book falls on a party.",
    '22:15': "The oracle narrows to one civil servant by name. Prophecy is willing to be this specific.",
    '22:16': "Shebna is carving himself a tomb in the rock, and the question put to him is: whom hast thou here?",
    '22:17': "The man who built to be remembered will be carried off and covered. His monument outlasts nothing.",
    '22:18': "Tossed like a ball into a large country, and the chariots of his glory become his master's shame.",
    '22:19': "Driven from his station. The office he furnished so carefully was never his to hold on to.",
    '22:20': "Eliakim is called \"my servant,\" which is the title Shebna's rock-cut tomb was never going to buy.",
    '22:21': "Robe, girdle and government handed over, and the new man is to be a father, not an administrator.",
    '22:22': "The key on his shoulder, to open and shut — words the risen Christ takes for himself in Revelation.",
    '22:23': "A nail in a sure place. Security is a fastening someone else drove, not a position one holds.",
    '22:24': "Everything hangs on him, down to the smallest cups. Being depended on is described as a weight.",
    '22:25': "The sure nail is removed after all, and all that hung on it falls. Even the good appointment ends.",

    # ---- Chapter 23 ----
    '23:1': "Tyre's ships learn of her fall while still at sea, by way of Chittim. The fleet hears it last.",
    '23:2': "\"Be still\" is said to an island that lived on traffic. Judgement on a port arrives as silence.",
    '23:3': "Tyre's revenue was another country's harvest. A mart of nations grows nothing of its own.",
    '23:4': "The sea itself says it has borne no children. Zidon's fruitfulness is disowned by the water.",
    '23:5': "News of Tyre pains them as news of Egypt did. Markets feel a distant collapse as their own.",
    '23:6': "Flee to Tarshish, the furthest colony. Even a merchant's escape runs along his trade routes.",
    '23:7': "Her antiquity is offered as an argument, and then her own feet carry her off to live as a stranger.",
    '23:8': "Merchants are princes and traffickers honourable. Isaiah asks who could plan against an order like that.",
    '23:9': "The LORD purposed it, to stain the pride of all glory. The answer names the motive as well as the agent.",
    '23:10': "\"There is no more strength.\" The restraint is off, and the colony may wander where it likes.",
    '23:11': "A hand stretched out over the sea. The realm Tyre was mistress of is the one God reaches into.",
    '23:12': "Pass over to Chittim, and no rest there either. Exile is offered without the relief exile promises.",
    '23:13': "The Chaldeans were nobody till Assyria made them a people, and the same hand brought them to ruin.",
    '23:14': "The ships are told to howl for their strength, which was a harbour they can no longer come back to.",
    '23:15': "Seventy years, the days of one king. The oracle fixes an end to the judgement as well as a start.",
    '23:16': "The forgotten harlot is told to sing for custom. Commerce is shown begging to be noticed again.",
    '23:17': "After the seventy years she turns to her hire again. Restoration has not changed what she is.",
    '23:18': "Her merchandise becomes holiness to the LORD, not hoarded but eaten. Trade is redeemed by being spent.",
})

TAKEAWAYS.update({
    # ---- Chapter 24 ----
    '24:1': "The earth turned upside down and its people scattered. The scale jumps from nations to the world.",
    '24:2': "Priest and people, master and servant, lender and borrower. The judgement flattens every distinction.",
    '24:3': "The only reason offered for the emptying is that the LORD hath spoken this word.",
    '24:4': "Earth, world and the haughty all languish together. The proud fade at the same rate as the grass.",
    '24:5': "The charge is a broken everlasting covenant, which reaches back past Sinai to Noah and all mankind.",
    '24:6': "The curse devours and few men are left. What is loose in the world is called a curse, not a war.",
    '24:7': "The new wine mourns. A failed vintage stands for a whole world that has lost its gladness.",
    '24:8': "Tabret, harp and the noise of rejoicing all stop. The silence of instruments measures the loss.",
    '24:9': "They can still drink, and it is bitter. What is left of pleasure is worse than its absence.",
    '24:10': "\"The city of confusion\" is broken down and shut up. Every door closed is the opposite of a city.",
    '24:11': "Crying for wine in the streets, and all joy darkened. The lament is small and exactly observed.",
    '24:12': "Desolation is what is left in the city, and the gate, where all business was done, is smashed.",
    '24:13': "The olive tree is shaken again. Even in a worldwide judgement the language of gleaning survives.",
    '24:14': "In the middle of the ruin a song starts, and it comes from the sea — from outside the land.",
    '24:15': "Glorify the LORD in the fires. Praise is located inside the judgement, not after it has passed.",
    '24:16': "Songs from the ends of the earth, and the prophet answers \"my leanness.\" He cannot join in yet.",
    '24:17': "Fear, pit and snare — three words for a world in which there is nowhere safe to put a foot.",
    '24:18': "Out of the pit and into the snare. Escape from one trap is only arrival at the next one.",
    '24:19': "Broken, dissolved, moved exceedingly. Three verbs where one would do, because the subject is the earth.",
    '24:20': "The earth reels like a drunkard, and the reason given is the weight of its own transgression.",
    '24:21': "The high ones on high are punished along with the kings on earth. Both face the same court.",
    '24:22': "Shut in the pit, and after many days they shall be visited. The sentence is held open, not closed.",
    '24:23': "Sun and moon are ashamed rather than extinguished. They dim the way lamps do at daybreak.",

    # ---- Chapter 25 ----
    '25:1': "The praise is for counsels of old — what God decided long before the events that proved them.",
    '25:2': "A city made a heap is the thing being thanked for. Isaiah praises God for a demolition.",
    '25:3': "The strong people glorify him. Judgement on the terrible nations ends with them worshipping.",
    '25:4': "Strength to the poor, a shadow from the heat. The same storm is ruin to one man and refuge to another.",
    '25:5': "The noise of strangers is put down like heat under a cloud — quietly, and all at once.",
    '25:6': "A feast of fat things for all people, on the mountain where the judgement fell. The menu is generous.",
    '25:7': "The covering over all nations is destroyed. What is taken away is not only death but the not seeing.",
    '25:8': "\"He will swallow up death in victory\" — Paul takes this line as the shout at the resurrection.",
    '25:9': "\"We have waited for him.\" The saved say nothing about themselves except that they waited.",
    '25:10': "Moab is trodden like straw on a dunghill while the feast is spread. The two stand side by side.",
    '25:11': "He spreads his hands as a swimmer does, and his pride goes down with the skill he swims by.",
    '25:12': "Walls brought down to the dust. The fortress that made Moab confident is the last thing named.",

    # ---- Chapter 26 ----
    '26:1': "The strong city's walls are salvation itself, appointed by God. The masonry is not what is trusted.",
    '26:2': "The gates open to a nation that keeps truth. Entry turns on what is kept, not on who built them.",
    '26:3': "Perfect peace is kept, not achieved, and the mind stayed on God is described as trusting, not gripping.",
    '26:4': "Trust for ever, because the strength is everlasting. The length of the trust follows from its object.",
    '26:5': "The lofty city is brought to the dust. The hand that appoints walls pulls other walls down.",
    '26:6': "The feet that tread the ruin are the feet of the poor. The reversal is done by those with the least.",
    '26:7': "God weighs the path of the just. Even the road a righteous man walks is measured by somebody else.",
    '26:8': "Waiting is set \"in the way of thy judgments.\" The waiting happens while God is already at work.",
    '26:9': "Judgements in the earth teach righteousness, which is why the night-long desire is not sentimental.",
    '26:10': "Favour shown to the wicked does not produce righteousness. Kindness alone converts nobody.",
    '26:11': "They will not see the lifted hand until they do, and by then it is shame rather than repentance.",
    '26:12': "\"Thou also hast wrought all our works in us.\" Even the obedience is credited to the giver of peace.",
    '26:13': "Other lords have ruled them, and they will still name only this one. Loyalty outlasts the defeat.",
    '26:14': "The dead tyrants shall not rise, and their memory perishes — which is all they ever built for.",
    '26:15': "\"Thou hast increased the nation\" twice over, and the glory named is God's rather than the nation's.",
    '26:16': "They visited him in trouble and poured out prayer under chastening. The affliction produced the prayer.",
    '26:17': "A woman in labour is the picture, and it is chosen here for the pain rather than for the birth.",
    '26:18': "\"We have as it were brought forth wind.\" The honest verdict on their own effort is that nothing came.",
    '26:19': "After the wind, the dead live. Resurrection is stated flatly, and it answers the failure just confessed.",
    '26:20': "Hide for a little moment till the indignation passes. The shelter offered is temporary on purpose.",
    '26:21': "The earth discloses her blood. Murders the ground had covered over are made to surface again.",

    # ---- Chapter 27 ----
    '27:1': "Leviathan and the dragon are killed with a sword. The chaos monster is handled as one more rebel.",
    '27:2': "The vineyard song comes back, and this time it is sung to her instead of against her.",
    '27:3': "\"I will water it every moment.\" The owner who took the hedge away now keeps watch night and day.",
    '27:4': "\"Fury is not in me.\" The one who burned the vineyard says the anger was never the settled thing.",
    '27:5': "The briers are invited to take hold of his strength and make peace, and the offer is made twice.",
    '27:6': "Jacob takes root and fills the world with fruit. The vineyard was never planted for its own wine.",
    '27:7': "He did not strike Israel as he struck her strikers. The question implies a difference of measure.",
    '27:8': "He stays his rough wind in the day of the east wind. Even the severity is carefully rationed.",
    '27:9': "The aim of the purging is named: altar stones ground to chalk, and no grove left standing anywhere.",
    '27:10': "The defenced city is left to grazing calves, and even that ruin serves the stripping of the idols.",
    '27:11': "No mercy from him that made them. Putting it as the maker's refusal is the severest way to say it.",
    '27:12': "Gathered one by one, like olives beaten off a branch. The regathering is individual, not a crowd.",
    '27:13': "A great trumpet for those ready to perish. The ones called home are the ones who nearly did not last.",
})

TAKEAWAYS.update({
    # ---- Chapter 28 ----
    '28:1': "The crown is a wreath of flowers on a drunk man's head, and it is already going over.",
    '28:2': "God's mighty and strong one comes as a hailstorm with a hand. The instrument is not yet named.",
    '28:3': "The proud crown is trodden under feet. A garland on a head ends up under somebody's boot.",
    '28:4': "Like the first ripe fig, swallowed the moment it is seen. Early beauty is a reason for being eaten.",
    '28:5': "The LORD himself will be the crown for the residue. He replaces the ornament by being one.",
    '28:6': "Grace is given to the judge on the bench and the soldier at the gate. Ordinary posts, ordinary gifts.",
    '28:7': "Priest and prophet err through drink. The men who interpret the vision cannot walk in a line.",
    '28:8': "\"No place clean.\" The chapter's most damning line describes the tables, not the doctrine.",
    '28:9': "They mock the prophet for addressing them as though they were infants just off the breast.",
    '28:10': "\"Precept upon precept, line upon line\" is their parody of his preaching. Baby-talk, they call it.",
    '28:11': "Stammering lips and another tongue. Their mockery is answered by the foreign speech of invaders.",
    '28:12': "He had offered them rest and refreshing, and the sentence ends: yet they would not hear.",
    '28:13': "Their own mocking jingle is handed back to them as the word of the LORD, and it trips them.",
    '28:14': "The scornful men are the ones who rule. Contempt for the word is policy here, not private mood.",
    '28:15': "\"We have made a covenant with death.\" They believe a treaty will hold off what holds off for no one.",
    '28:16': "A tried stone laid in Zion, and he that believeth shall not make haste. Paul and Peter both build on it.",
    '28:17': "Judgment to the line and righteousness to the plummet. Measuring tools are what sweep the lies away.",
    '28:18': "The covenant with death is disannulled. God cancels the contract they were relying on for safety.",
    '28:19': "Morning by morning it passes over, and merely understanding the report is called a vexation.",
    '28:20': "A bed too short and a blanket too narrow. The exact feeling of a policy that does not quite cover.",
    '28:21': "Judgement is called his strange work. Wrath is real, and it is not what he most delights to do.",
    '28:22': "Mocking makes the bands stronger. Scorn is said to tighten the very thing it hoped to shake off.",
    '28:23': "The tone turns to a teacher's — give ear, and hear my speech. A parable is coming, not a threat.",
    '28:24': "The plowman does not plow for ever. Even a farmer knows breaking ground is not the whole job.",
    '28:25': "Each seed is given its own place in the field. The farmer's distinctions are the point of the parable.",
    '28:26': "The farmer's skill is credited to God teaching him. Ordinary competence is treated as instruction.",
    '28:27': "Cummin is beaten with a rod, not crushed under a cart. The threshing is matched to what is threshed.",
    '28:28': "Bread corn is bruised, but not endlessly. Even the hardest handling stops once it has done its work.",
    '28:29': "The farmer's discretion is a picture of God's. Judgement is measured out the way a harvest is.",

    # ---- Chapter 29 ----
    '29:1': "Ariel, the city where David dwelt, is greeted with a woe and told to go on keeping its feasts.",
    '29:2': "Besieged Ariel will be \"as Ariel\" — the altar hearth, which is the place where things are burnt.",
    '29:3': "God is the besieger. The forts raised against Jerusalem are raised by the one who founded her.",
    '29:4': "The proud city's voice becomes a whisper out of the dust, like a medium's ghost muttering.",
    '29:5': "\"At an instant suddenly\" — the besieging host turns to dust in the same breath that describes it.",
    '29:6': "Thunder, earthquake and devouring fire visit the enemy, and Zion is not asked to do anything.",
    '29:7': "The nations that fight against her turn out, in the end, to be a dream of a night vision.",
    '29:8': "The hungry man dreams he eats and wakes empty. Conquest of Zion is that kind of satisfaction.",
    '29:9': "Drunk, but not with wine. Their staggering has a cause that no tavern can be blamed for.",
    '29:10': "The spirit of deep sleep is poured out by the LORD. The blindness is a judgement, not an accident.",
    '29:11': "The learned man cannot read it because it is sealed. Scholarship is not what is missing here.",
    '29:12': "The unlearned cannot read it because he is unlearned. Between the two, nobody hears the word at all.",
    '29:13': "Lips near, heart far, fear taught by the precept of men. Jesus quotes the line against his own generation.",
    '29:14': "The marvellous work is that the wisdom of the wise perishes. God does not answer rote religion with a lecture.",
    '29:15': "\"Who seeth us?\" Secrecy is the practical atheism of people who are still keeping the feasts.",
    '29:16': "The clay tells the potter he had no understanding. The absurdity is left to do its own work.",
    '29:17': "Lebanon into a field and the field into a forest. The reversal is a rearranging, not a tidy restoration.",
    '29:18': "The deaf hear the words of the book that neither the learned nor the unlearned could read.",
    '29:19': "The meek increase their joy and the poor rejoice. The beneficiaries are named by what they lack.",
    '29:20': "The terrible one, the scorner and those that watch for iniquity are all cleared away together.",
    '29:21': "Making a man an offender for a word: the injustice named is nit-picking a witness in open court.",
    '29:22': "\"The LORD, who redeemed Abraham.\" The promise is guaranteed by how it began, not by how it is going.",
    '29:23': "His children are called the work of mine hands. The God who is sanctified made the ones who do it.",
    '29:24': "They that murmured shall learn doctrine. The complainers are not written off but taught.",

    # ---- Chapter 30 ----
    '30:1': "Counsel not of him and a covering not of his Spirit. Foreign policy is given the language of idolatry.",
    '30:2': "They go down to Egypt without asking at his mouth. The fault is in the order, not only the destination.",
    '30:3': "Pharaoh's strength becomes their shame. What was bought for security produces the humiliation.",
    '30:4': "Ambassadors already at Zoan and Hanes. The treaty is well advanced before the prophet says a word.",
    '30:5': "A people that could not profit them. The whole verse turns on what the alliance failed to deliver.",
    '30:6': "Treasure hauled through lion country on donkeys to buy help that cannot help. The cost is itemised.",
    '30:7': "\"Their strength is to sit still.\" The hardest counsel in the chapter is to do nothing whatever.",
    '30:8': "Write it in a book for the time to come. The oracle is filed as evidence for a later generation.",
    '30:9': "Children that will not hear the law. The rebellion is against listening before it is against obeying.",
    '30:10': "\"Prophesy deceits.\" They ask openly for lies, which is more candid than the usual arrangement.",
    '30:11': "They want the Holy One of Israel to cease from before them. Not a softer God — no God in the room.",
    '30:12': "Despising the word and trusting in oppression are the same act, stated twice in a single sentence.",
    '30:13': "A bulging wall that looks solid and goes all at once. The suddenness is what the image is for.",
    '30:14': "Not a sherd left big enough to carry a coal. What breaks leaves nothing even to be useful with.",
    '30:15': "\"In returning and rest shall ye be saved\" — and then four words undo it: and ye would not.",
    '30:16': "They chose horses, so they will flee on horses. The request is granted exactly and becomes the sentence.",
    '30:17': "A thousand flee at the rebuke of one, till a single flagpole is left. Defeat measured by what stands alone.",
    '30:18': "He waits in order to be gracious. The delay everyone reads as absence is described here as patience.",
    '30:19': "He answers at the voice of the cry. The hearing comes before the crying has even finished.",
    '30:20': "Bread of adversity given, and teachers no longer hidden in a corner. Both arrive in the same verse.",
    '30:21': "A word behind you, heard when you turn aside. Guidance comes at the point of wandering, not before.",
    '30:22': "Idols of silver thrown out like a filthy cloth, and by the same hands that overlaid them.",
    '30:23': "Rain, bread and large pastures. The blessing promised is agricultural and specific, not a mood.",
    '30:24': "Even the oxen get winnowed fodder. The abundance runs down as far as the working animals.",
    '30:25': "Rivers on every high hill, \"in the day of the great slaughter.\" The blessing is dated by a battle.",
    '30:26': "Sevenfold sunlight on the day he binds up the breach. The new light is there for the healing.",
    '30:27': "The name of the LORD comes from far, burning. A name is described as arriving like a fire.",
    '30:28': "A sieve of vanity and a bridle in the jaws. The nations are handled the way a man handles a horse.",
    '30:29': "A song as in the night of a holy feast. The fall of Assyria is set to festival music.",
    '30:30': "Voice, arm, fire and hail. The deliverance is described entirely as weather, with no army in it.",
    '30:31': "Assyria is beaten down by a voice. The rod that smote the nations breaks without a battle.",
    '30:32': "Tabrets and harps in every place the staff falls. The judgement comes with music playing.",
    '30:33': "Tophet is ordained of old and prepared for the king. The valley of child sacrifice is turned around.",
})
