#!/usr/bin/env python3
"""Written takeaways for Isaiah 34-66."""

TAKEAWAYS = {
    # ---- Chapter 34 ----
    '34:1': "An oracle against one small neighbour opens by convening the whole earth to listen in.",
    '34:2': "\"He hath utterly destroyed them\" — the sentence is reported in the past tense before a blow has landed.",
    '34:3': "The horror named is not the dying but the lying unburied, which in this world is the deeper shame.",
    '34:4': "The sky is treated as something that wears out and is rolled up, like a scroll finished being read.",
    '34:5': "The sword is bathed in heaven before it comes down. Judgement is prepared above and only then aimed.",
    '34:6': "Slaughter is described in the vocabulary of the altar: Bozrah is not a battlefield here but a sacrifice.",
    '34:8': "\"The controversy of Zion\" — vengeance is framed as a lawsuit with a party that has to answer.",
    '34:9': "Pitch and brimstone are Sodom's materials, lent to Edom. The judgement is quoted from an older one.",
    '34:10': "Smoke going up for ever is not the fire's length but its finality: nothing will ever be rebuilt on that ground.",
    '34:11': "\"The line of confusion, and the stones of emptiness\" — Genesis 1's formless void, measured out deliberately.",
    '34:12': "The titles survive the people. Nobles are summoned to a kingdom where there is no longer anyone to rule.",
    '34:13': "The palaces are not flattened but occupied. Thorns and owls move into rooms still standing.",
    '34:14': "The only rest anywhere in this chapter is found by a screech owl.",
    '34:16': "\"Seek ye out of the book of the LORD, and read\" — the prophecy invites being checked against the record later.",
    '34:17': "Lot and measuring line are Joshua's words for settling the promised land. Here the allotment goes to wild beasts.",

    # ---- Chapter 35 ----
    '35:1': "The desert is the one doing the rejoicing. Gladness reaches the landscape before it reaches anybody in it.",
    '35:2': "The wilderness is given Lebanon's glory and Carmel's excellency. What it blooms with is borrowed, not native.",
    '35:3': "The command goes to the bystanders, not to the weak. Someone else is told to steady those failing knees.",
    '35:4': "\"He will come with vengeance\" and \"he will come and save you\" are one sentence about one arrival.",
    '35:5': "Opened eyes and unstopped ears are the proof Jesus sends back to John in prison when asked who he is.",
    '35:6': "Healed bodies and watered desert are listed as a single event, as though the two had the same cause.",
    '35:7': "The habitation of dragons from the chapter before becomes grass and reeds. The curse is reversed on its own address.",
    '35:8': "\"The wayfaring men, though fools, shall not err therein\" — the road is made plain enough that stupidity is no bar.",
    '35:9': "No lion is there. The danger is not fought off along the way; it is simply absent from it.",
    '35:10': "Sorrow and sighing flee. They are not borne patiently to the end but chased off the premises.",

    # ---- Chapter 36 ----
    '36:1': "The chapter opens with the fortified cities already taken. Judah's defence policy has failed before a word is said.",
    '36:2': "The conduit of the upper pool is where Isaiah once met Ahaz. Same spot, different king, same question about trust.",
    '36:4': "\"Thus saith the great king\" mimics the prophets' formula, and the question he asks is the book's own: what are you trusting?",
    '36:5': "He calls Judah's war talk vain words, and about the war talk he happens to be right.",
    '36:6': "Egypt as a broken reed that pierces the hand leaning on it is Isaiah's own verdict, now in an Assyrian mouth.",
    '36:7': "Hezekiah's reform is turned into evidence against him: the man who pulled down altars must have offended the God who owned them.",
    '36:8': "Two thousand horses offered as a taunt, because the insult is that Judah could not find riders for them.",
    '36:10': "\"Am I now come up without the LORD?\" Isaiah had already called Assyria the rod of God's anger; the boast is half true and wholly blind.",
    '36:11': "The officials do not dispute the argument, only the language. They know the wall is listening.",
    '36:12': "He refuses to speak privately, because his real audience was never the negotiators but the people who will starve.",
    '36:14': "The attack shifts from Judah's allies to Judah's king: not can he win, but can he be believed.",
    '36:15': "Having disposed of Egypt and of Hezekiah, he comes to the last thing left, which is the LORD.",
    '36:16': "Surrender is offered in Israel's own picture of peace — every man his vine and fig tree — to make it sound like coming home.",
    '36:17': "\"A land like your own land.\" Deportation is sold as relocation, and the lie is the word like.",
    '36:18': "The argument is empirical and its flaw is the category: he is reasoning about the LORD from a list of idols.",
    '36:20': "He files the LORD among the gods he has already beaten. That single misplacement is what the next chapter answers.",
    '36:21': "Silence is a policy here, not paralysis. The king had given orders that nothing be said back.",
    '36:22': "They answer him with nothing and tear their clothes only once they are out of his sight.",

    # ---- Chapter 37 ----
    '37:1': "The king's first move against an army is to go into a building and put on sackcloth.",
    '37:2': "The prophet is sent for after the crisis has arrived rather than before it, but he is sent for.",
    '37:3': "\"The children are come to the birth, and there is not strength to bring forth\" — failure at the last possible moment.",
    '37:4': "\"It may be the LORD thy God will hear.\" Hezekiah hopes tentatively, and calls him Isaiah's God rather than his own.",
    '37:6': "\"Be not afraid of the words.\" The weapon that has actually been deployed against Jerusalem so far is speech.",
    '37:7': "A blast, a rumour, and a murder at home. None of the promised deliverance requires Judah to raise a soldier.",
    '37:9': "The rumour arrives exactly as promised, and it looks like nothing more than ordinary foreign politics.",
    '37:10': "The letter no longer argues that Judah is weak. It argues that God is lying to them.",
    '37:11': "The case rests on a track record, which is the strongest argument available to a man reasoning without God.",
    '37:14': "He does not answer the letter. He spreads it open where someone else can read it.",
    '37:16': "The prayer grants Rabshakeh's whole comparison and denies its premise: there is only one God in the room.",
    '37:17': "\"Open thine eyes, O LORD, and see.\" He asks God to take the insult personally, because it was meant that way.",
    '37:18': "\"Of a truth\" — Hezekiah concedes the enemy's facts before asking for anything.",
    '37:19': "The gods Assyria burned were wood and stone already. Their defeat proves nothing about the God who made the wood.",
    '37:20': "The reason he gives for rescue is that the nations may learn something, not that Judah may be comfortable.",
    '37:21': "\"Whereas thou hast prayed to me\" — the answer is tied explicitly to the prayer, and said to be because of it.",
    '37:22': "The laughter is given to the besieged city. Zion mocks the army camped outside her wall.",
    '37:23': "\"Whom hast thou reproached?\" The question does not deny the insult; it re-files who received it.",
    '37:24': "The boast is quoted back to him, and in it conquest sounds like logging — tall cedars cut down for the pleasure of it.",
    '37:25': "Drying up rivers with the sole of his foot is a claim to have done at will what God did once at the sea.",
    '37:26': "The conqueror learns he has been carrying out a plan formed long before him and not by him.",
    '37:27': "The nations he flattened were grass on a housetop already, withered before he ever reached them.",
    '37:28': "\"I know thy abode, and thy going out.\" The God he listed among the beaten has been watching his daily movements.",
    '37:29': "Hook in the nose and bridle in the lips is how Assyria led its own prisoners home.",
    '37:30': "The sign offered is not a wonder but a farming calendar: two years of scavenging, then a normal sowing.",
    '37:31': "Root downward before fruit upward. The recovery begins underground, where nobody can see it working.",
    '37:32': "The remnant survives by \"the zeal of the LORD of hosts,\" which is to say by nothing Judah arranged.",
    '37:33': "Not an arrow, not a siege bank. The promise is that the attack will not even properly begin.",
    '37:35': "\"For mine own sake, and for my servant David's sake.\" Both stated reasons for sparing the city are outside the city.",
    '37:36': "The deliverance asks nothing of Judah at all. They rise in the morning and find it already done.",
    '37:38': "He is killed by his own sons while worshipping, and the god he was bowing to did not manage the one thing gods are for.",

    # ---- Chapter 38 ----
    '38:1': "\"Thou shalt die, and not live\" is a word from the LORD that the same chapter will revise.",
    '38:2': "Turning his face to the wall is a prayer so private it begins by shutting out the prophet standing there.",
    '38:3': "He pleads his own walk and his perfect heart. This is how a man prays when the covenant he knows ties life to obedience.",
    '38:5': "\"I have heard thy prayer, I have seen thy tears.\" The tears are counted separately, as though they said what the words could not.",
    '38:6': "The private reprieve turns out to carry the city with it. One man's fifteen years and Jerusalem's survival arrive together.",
    '38:8': "The sign is given in the one thing that never goes backward, which is why it works as a sign.",
    '38:9': "The psalm is written after the recovery. What the sickbed felt like is set down by a man no longer on it.",
    '38:10': "The complaint is not death but timing: he is being deprived of years he had already counted as his.",
    '38:11': "What he expects to lose first is seeing — seeing the LORD, and seeing other people. Both are losses of company.",
    '38:12': "A shepherd's tent struck at dawn, a weaver cutting the finished cloth off the loom. Life ends by being tidily packed away.",
    '38:14': "\"O LORD, I am oppressed; undertake for me.\" He asks God to stand surety for him against God's own hand.",
    '38:15': "\"He hath both spoken unto me, and himself hath done it.\" Rescue leaves him quieter, not louder: he will go softly for the rest of his years.",
    '38:16': "\"By these things men live.\" The illness itself is put on the list of what gave him life rather than took it.",
    '38:17': "\"Thou hast cast all my sins behind thy back\" — the recovery is described as forgiveness, because that is what he thought was wrong.",
    '38:18': "The argument is that God will lose a worshipper. Israel's hope beyond the grave is thin here, and the text lets the thinness stand.",
    '38:19': "\"The father to the children shall make known thy truth.\" What the added years are for is one more generation being told.",
    '38:21': "A poultice of figs sits in the same account as a reversed shadow. Ordinary medicine is not treated as a rival to the miracle.",
    '38:22': "The king who has just been given fifteen years still asks for the sign. Assurance does not arrive once and stay.",

    # ---- Chapter 39 ----
    '39:1': "The first friendly embassy in the book comes from Babylon, and it comes because Hezekiah was ill.",
    '39:2': "The man who spread a letter before the LORD now spreads his treasury before Babylon, and leaves nothing unshown.",
    '39:3': "Isaiah asks what they saw and where they came from. Hezekiah answers the easier question and calls Babylon far off.",
    '39:4': "\"All that is in mine house have they seen.\" He reports it without a trace of embarrassment, which is the problem.",
    '39:6': "The showing has become the inventory. What was displayed with pride is the list of what will be carried away.",
    '39:7': "The sentence reaches his sons, and the word eunuchs means the line itself is what gets cut.",
    '39:8': "\"There shall be peace and truth in my days.\" He calls the word good because the disaster is scheduled for someone else.",
}

TAKEAWAYS.update({
    # ---- Chapter 40 ----
    '40:1': "After thirty-nine chapters of indictment the next word is not a verdict but an order given to somebody: comfort them.",
    '40:2': "\"Double for all her sins\" — the announcement is not of a lighter sentence but of one already over-served.",
    '40:3': "The road is built for God to come to them, not for them to walk out. All four gospels hand this voice to John.",
    '40:4': "The engineering is levelling. Whatever stands high comes down and whatever lies low comes up, for the sake of one straight road.",
    '40:5': "\"All flesh shall see it together.\" The only guarantee offered that this will happen is that a mouth has said so.",
    '40:6': "The herald has to ask what the message is, and the first thing he is handed to cry is that people are grass.",
    '40:7': "The grass withers because the breath of the LORD blows on it. The fading is not bad luck but weather he sends.",
    '40:8': "The contrast is not frailty against eternity in general. It is grass against a spoken word, and the word outlasts it.",
    '40:9': "The one ordered up the mountain to shout the good news is Zion herself. The city that received it becomes the messenger.",
    '40:10': "\"With strong hand\" — comfort in this chapter does not mean a mild God, and the arm that rules is mentioned first.",
    '40:11': "The arm that ruled in the verse before is the arm that gathers lambs, and the pace is set by the ewes with young.",
    '40:12': "The sea held in a palm, the mountains weighed on scales. Scale is established before anything is asked of the hearer.",
    '40:13': "No one has ever advised him. Paul ends his hardest argument about Israel by quoting exactly this.",
    '40:15': "The nations are a drop left in a bucket and dust on the pan — not opposed, simply too light to register.",
    '40:16': "All Lebanon's wood and all its beasts would not make one adequate offering. Creation cannot fund its own sacrifice.",
    '40:17': "\"Less than nothing\" is arithmetic that does not exist, reached for because nothing was not low enough.",
    '40:18': "The hinge of the whole argument against idols: not whether the image works, but whether any likeness could be taken at all.",
    '40:20': "Even poverty finds a way to have a god. The specification is a wood that will not rot and an image that will not fall over.",
    '40:21': "Four questions assuming they already know. Idolatry is treated here as a failure of memory, not of information.",
    '40:22': "He sits above a circle where people look like grasshoppers, and stretches the sky out as the tent he lives in.",
    '40:23': "Princes are reduced to the same nothing the idols were. The category does not change between gods and governments.",
    '40:24': "Rulers are not even given a growing season. The whirlwind takes them before the stock has put down root.",
    '40:25': "The question of verse 18 is asked again, this time in the first person, by the Holy One about himself.",
    '40:26': "He brings out the stars by number and calls them by name, and \"not one faileth\" — the roll call matters more than the count.",
    '40:27': "All that astronomy has been aimed at one small complaint: that God has not noticed what is happening to Jacob.",
    '40:28': "The answer to feeling overlooked is that God does not get tired — not the answer anyone would have written.",
    '40:29': "Power is given to the faint and strength to those with none. Having none is the qualification, not the obstacle.",
    '40:30': "Even the young men fall. The one group that should never run out is named as the ones who do.",
    '40:31': "The verb is wait. Mounting, running and walking follow it, in descending order of drama and ascending order of difficulty.",

    # ---- Chapter 41 ----
    '41:1': "The nations are summoned to court and told to renew their strength first. The other side is given time to prepare.",
    '41:2': "\"Who raised up the righteous man from the east?\" Cyrus goes unnamed for seven more chapters; the question makes the hearer answer it.",
    '41:4': "\"The first, and with the last\" — the claim is not to be strongest within history but to stand at both ends of it.",
    '41:6': "Alarm makes them kind to one another. Neighbours encouraging neighbours is not by itself evidence of being right.",
    '41:7': "Carpenter cheers goldsmith, hammer cheers anvil, and the industry's whole aim is a god that will not fall over.",
    '41:8': "Against that workshop stands a people who were chosen rather than made, and an ancestor God calls his friend.",
    '41:9': "\"I have chosen thee, and not cast thee away\" is said to people with every visible reason to conclude the opposite.",
    '41:10': "Each command not to fear is answered with a because, and the reason given is never anything about the situation.",
    '41:11': "Those incensed against Israel \"shall be as nothing\" — the same word just spent on the idols.",
    '41:13': "He holds the right hand while saying Fear not. The reassurance arrives as contact and not only as speech.",
    '41:14': "\"Thou worm Jacob.\" The insult is not softened before the promise; a redeemer is given to something despised.",
    '41:15': "The worm becomes a threshing sledge with teeth, beating mountains small. The reversal is deliberately absurd in scale.",
    '41:17': "The promise is attached to a condition, and the condition is being poor, needy and out of water.",
    '41:18': "Rivers opened in high places — water sent where water does not naturally run.",
    '41:19': "Seven kinds of tree planted in a desert. What is promised is an orchard, well past what survival would require.",
    '41:20': "The planting exists so that they \"see, and know, and consider, and understand\" whose hand it was.",
    '41:21': "\"Bring forth your strong reasons.\" The idols are invited to argue their case rather than simply condemned.",
    '41:22': "The test set is prediction, and it is checkable in both directions: explain the past, or name the future.",
    '41:23': "\"Do good, or do evil\" — the bar drops to doing anything whatever, so long as it can be observed.",
    '41:24': "The verdict falls on the worshipper as well: \"an abomination is he that chooseth you.\"",
    '41:25': "The unnamed conqueror is now from the north as well as the east, and he treads princes as a potter treads clay.",
    '41:26': "None sheweth, none declareth, none heareth. The silence charged against the gods is not partial but total.",
    '41:27': "The reply to the gods' silence is not an argument but a person: one sent to Jerusalem with good tidings.",
    '41:28': "\"I beheld, and there was no man.\" God reports looking for a counsellor among them and finding nobody.",
    '41:29': "Not weak gods but \"wind and confusion\" — the images are classed with weather and disorder, not with rivals.",

    # ---- Chapter 42 ----
    '42:1': "\"Mine elect, in whom my soul delighteth\" — the words spoken over Jesus at the Jordan. The servant's first listed task is justice for Gentiles.",
    '42:2': "He will not raise his voice in the street. Authority arrives without any of the noise that normally announces it.",
    '42:3': "A bruised reed and a smoking wick are the two things anyone would throw out. He is defined by what he refuses to discard.",
    '42:4': "The words used of the reed and the flax are turned on him: he will not be broken or quenched before the work is set in the earth.",
    '42:5': "The credentials come before the commission, and they are creation and breath. The sender made the lungs of the one he sends.",
    '42:6': "\"Give thee for a covenant of the people\" — a person handed over as the covenant itself, not as its negotiator.",
    '42:7': "The work is opening eyes and opening prisons. The judgement he brings the nations arrives as release rather than sentence.",
    '42:8': "The name and the glory are declared non-transferable, and it is the graven images that are caught reaching for them.",
    '42:9': "The former predictions came true, and that record is offered as the only ground for trusting the new ones.",
    '42:10': "Sailors and islands are told to sing a new song about something they have not yet been given the details of.",
    '42:13': "The God who would not shout in the street goes out as a man of war and roars. Gentleness is not the whole of him.",
    '42:14': "Divine silence is explained as restraint, and the end of it is compared to a woman in labour who can hold back no longer.",
    '42:15': "Dried pools here, opened rivers a chapter earlier. The same hand does both, and neither is the mood of the moment.",
    '42:16': "The mercy is the unfamiliar road, not a familiar one made safe: they are led by ways they never knew.",
    '42:18': "\"Hear, ye deaf; and look, ye blind.\" The address demands of its hearers precisely what they cannot do.",
    '42:19': "The title just given to the one who opens blind eyes is now given to the blind. Israel is the servant too.",
    '42:20': "\"Seeing many things, but thou observest not.\" The failure is not a shortage of evidence but of attention.",
    '42:21': "God magnifies the law and makes it honourable for his own righteousness' sake, quite apart from anyone keeping it.",
    '42:22': "\"None saith, Restore.\" Part of the disaster is that no one is even asking for the plunder back.",
    '42:23': "The prophet stops and asks whether anybody in the room is actually listening for what comes next.",
    '42:24': "The answer to who handed Jacob over is the LORD himself, and mid-sentence the accusation turns into we have sinned.",
    '42:25': "\"It burned him, yet he laid it not to heart.\" Judgement that teaches nothing is the worst outcome the chapter names.",
})

TAKEAWAYS.update({
    # ---- Chapter 43 ----
    '43:1': "\"I have called thee by thy name; thou art mine.\" The ground for not fearing is ownership, not improvement.",
    '43:2': "Through the waters, not around them. What is promised is company in the flood and never exemption from it.",
    '43:3': "An exchange rate is put on Israel — Egypt, Ethiopia, Seba — and the striking thing is that somebody else pays it.",
    '43:4': "The preciousness comes first and the love is named after it. Neither is offered as something Israel arranged.",
    '43:6': "North and south are addressed as captors under obligation: Give up, Keep not back. Exile is told to hand them over.",
    '43:7': "Created, formed, made — Genesis vocabulary spent on a people, and the stated purpose of their return is God's glory.",
    '43:8': "\"The blind people that have eyes.\" The witnesses God is about to call are described by their disabilities first.",
    '43:9': "The nations are invited to produce witnesses who could be justified. The trial turns on who has a record to show.",
    '43:10': "\"Ye are my witnesses.\" The blind and deaf people of verse 8 are the evidence he chooses to put in the box.",
    '43:11': "\"Beside me there is no saviour.\" Of all the titles in this book, that is the one never shared out.",
    '43:12': "\"When there was no strange god among you\" — the saving happened with no other candidate present to take the credit.",
    '43:13': "\"I will work, and who shall let it?\" Nothing he does can be reversed, which is comfort and threat in one clause.",
    '43:14': "An empire is brought down for the sake of a small displaced people. The ratio is stated without embarrassment.",
    '43:16': "The exodus is cited the way a man cites his own record — the one who made a way in the sea is speaking.",
    '43:18': "\"Remember ye not the former things.\" After two verses of remembering, they are told to stop. That is the hinge.",
    '43:19': "\"Now it shall spring forth; shall ye not know it?\" The new thing is already under way, and the danger is walking past it.",
    '43:20': "The jackals and owls praise him for the water. Creation's thanks are for the drink, not for the doctrine.",
    '43:21': "\"This people have I formed for myself.\" The whole rescue is given a purpose clause, and it is not their comfort.",
    '43:22': "\"Thou hast been weary of me.\" The charge is not first disobedience but boredom with God.",
    '43:23': "He lists the offerings they failed to bring and then says he never wore them out demanding any.",
    '43:24': "The reversal is complete: \"thou hast made me to serve with thy sins.\" In this transaction God is the one doing the labour.",
    '43:25': "\"For mine own sake.\" Nothing whatever in the sinner is offered as the reason the sins are blotted out.",
    '43:26': "\"Declare thou, that thou mayest be justified.\" He invites them to argue their own case, which is the invitation nobody takes.",
    '43:27': "\"Thy first father hath sinned.\" The trouble runs back past everyone currently alive to be blamed.",
    '43:28': "The sentence lands on the princes of the sanctuary. Judgement starts with the men who handled holy things.",

    # ---- Chapter 44 ----
    '44:1': "One word, Yet, stands between the curse that ended the last chapter and the servant addressed in this one.",
    '44:2': "\"Jesurun\" means the upright one. It is a fond name, and Scripture tends to use it when Israel is behaving worst.",
    '44:3': "Water on dry ground and Spirit on the offspring are described as a single pouring, from one hand at one time.",
    '44:5': "Outsiders take the name by their own hand. Belonging is entered into here by signature rather than by birth.",
    '44:6': "\"I am the first, and I am the last\" — the title Revelation hands, without apology, to Christ.",
    '44:7': "The challenge set to any rival is not to match his power but to match his announcements.",
    '44:8': "\"I know not any.\" God says he is unaware of a rival, which is a stranger and heavier denial than saying there is none.",
    '44:9': "The idol makers \"are their own witnesses.\" No outside testimony is needed, because they watched themselves do it.",
    '44:11': "\"The workmen, they are of men.\" The manufacturers are only human, and nothing human makes can rise above its maker.",
    '44:12': "The smith gets hungry and faint. The man runs out of strength before the god he is making is finished.",
    '44:13': "The image is cut \"according to the beauty of a man.\" The god ends up looking like the species that ordered it.",
    '44:14': "He plants the ash and the rain feeds it. The raw material of the idol was grown by the God it will replace.",
    '44:15': "One log: part warms him, part bakes his bread, part becomes a god. Where he draws the line is entirely arbitrary.",
    '44:17': "\"Deliver me; for thou art my god\" — addressed to the leftovers of the firewood, and said in earnest.",
    '44:18': "\"He hath shut their eyes.\" The blindness is not only self-inflicted, and Isaiah does not soften who closed them.",
    '44:19': "\"None considereth in his heart.\" One minute of reflection would end the whole business, and the minute is never taken.",
    '44:20': "\"Is there not a lie in my right hand?\" The question no idolater asks is printed here as the one that would free him.",
    '44:21': "\"Thou shalt not be forgotten of me\" — spoken to the people who have just been shown the satire and not excluded from it.",
    '44:22': "\"Return unto me; for I have redeemed thee.\" The redemption is the reason for returning, not the wage paid for it.",
    '44:23': "The heavens are told to sing for something described in the past tense, though it has not visibly happened yet.",
    '44:24': "\"That stretcheth forth the heavens alone.\" The word alone shuts out helpers as firmly as it shuts out rivals.",
    '44:25': "The diviners are not refuted but driven mad, and the wise men are turned backward rather than corrected.",
    '44:26': "\"Confirmeth the word of his servant.\" God stakes his own credit on whether his messengers turn out to be right.",
    '44:27': "\"Be dry\" — two words spoken to the deep, and the whole crossing of the sea is contained in them.",
    '44:28': "Cyrus is called \"my shepherd,\" David's title, handed to a pagan king who does not know whose shepherd he is.",

    # ---- Chapter 45 ----
    '45:1': "\"His anointed, to Cyrus.\" The word is messiah, and it is given to a foreign king who will never worship the LORD.",
    '45:2': "The brass gates are broken before the army arrives. Cyrus will march down a road already cleared for him.",
    '45:3': "The treasures of darkness are handed over so that Cyrus \"mayest know\" who called him. Plunder used as an introduction.",
    '45:4': "\"For Jacob my servant's sake\" — the conqueror's whole career is arranged around a people he has not heard of.",
    '45:6': "The point of the entire Cyrus operation is stated plainly: that east and west find out there is only one God.",
    '45:7': "\"I make peace, and create evil.\" Isaiah refuses to supply a second power on whom disaster could be blamed.",
    '45:8': "Righteousness comes down as rain and salvation grows up out of the ground. It arrives as weather, not as achievement.",
    '45:9': "\"Shall the clay say to him that fashioneth it, What makest thou?\" The objection is not answered but disqualified, and Paul reuses it.",
    '45:10': "The complaint against God is restaged as a child arraigning his parents for the fact of having been born.",
    '45:11': "\"Command ye me.\" Three verses after the potsherd is silenced, the same people are told to ask. Both stand.",
    '45:13': "\"Not for price nor reward.\" Cyrus will release the captives without being paid, which is not how empires behave.",
    '45:14': "The nations arrive in chains and say \"Surely God is in thee.\" What they submit to is the God, not the people.",
    '45:15': "\"Thou art a God that hidest thyself\" — said at the precise point in the book where his working is most visible.",
    '45:17': "The salvation is everlasting and the proof offered for it is negative: never being ashamed, world without end.",
    '45:18': "\"He created it not in vain, he formed it to be inhabited.\" The emptiness of chapter 34 is not what the earth is for.",
    '45:19': "\"I said not unto the seed of Jacob, Seek ye me in vain.\" God denies running a religion whose terms are kept hidden.",
    '45:20': "The idol is carried into the assembly on the shoulders of the people it is supposed to be rescuing.",
    '45:21': "\"A just God and a Saviour\" in one breath. Holding those two together is the labour the rest of the book performs.",
    '45:22': "\"Look unto me, and be ye saved.\" Looking is the whole prescribed action, and the offer is made to the ends of the earth.",
    '45:23': "The oath is sworn by God on himself, and Paul takes the bowing knee and the swearing tongue and puts them under Christ.",
    '45:24': "\"In the LORD have I righteousness and strength\" — both are located outside the man reporting that he has them.",
    '45:25': "Glorying is permitted at the end only because the justifying at the start of the sentence was not their work.",

    # ---- Chapter 46 ----
    '46:1': "Bel and Nebo have to be loaded onto carts. Babylon's gods leave the city as freight, and heavy freight at that.",
    '46:2': "\"They could not deliver the burden.\" The gods cannot rescue even the cargo which they themselves are.",
    '46:3': "The contrast is exact and cruel: those gods have to be carried, and this people has been carried since the womb.",
    '46:4': "\"Even to hoar hairs will I carry you.\" The carrying is promised for the years when a person weighs most and gives least.",
    '46:6': "Gold weighed out, a goldsmith hired. The god's cost is itemised in full before anyone falls down in front of it.",
    '46:7': "\"From his place shall he not remove.\" Standing where he was put is the one thing an idol does reliably.",
    '46:8': "\"Shew yourselves men.\" The summons to transgressors is to think, as though thinking were most of the repentance.",
    '46:10': "\"Declaring the end from the beginning.\" The evidence of deity offered here is not strength but foreknowledge that holds up.",
    '46:11': "The man who executes God's counsel is called a bird of prey and is never told what counsel he is executing.",
    '46:12': "The address is to the stouthearted, and being far from righteousness is named as their situation before it is named as their fault.",
    '46:13': "\"I bring near my righteousness.\" It is carried to the people who are far from it, which is the only way that distance ever closes.",
})

TAKEAWAYS.update({
    # ---- Chapter 47 ----
    '47:1': "\"There is no throne\" is said as a plain statement of fact rather than a threat. The queen is simply told where to sit.",
    '47:2': "The sentence on a queen is not execution but the millstone: household labour, with her skirts pulled up to cross the river.",
    '47:3': "\"I will not meet thee as a man.\" The one place in the oracle where God says the terms of the reckoning are not human ones.",
    '47:4': "A single line of confession interrupts the sentencing — \"our redeemer\" — as though the victims could not keep quiet through it.",
    '47:6': "God admits handing his own people over, and then charges Babylon with the part he never commissioned: no mercy, and the old worst used.",
    '47:7': "\"Thou didst not remember the latter end of it.\" The sin being named is assuming that the present arrangement is permanent.",
    '47:8': "\"I am, and none else beside me\" is Babylon quoting, word for word, what God has been saying about himself for six chapters.",
    '47:9': "Widowhood and childlessness in one day, and the sorceries she paid for all her life are listed as what failed to stop it.",
    '47:10': "\"Thou hast said, None seeth me.\" What made the wickedness feel safe was not getting away with it but not being watched.",
    '47:11': "Three disasters, each with a clause about not knowing. An empire's collapse is described chiefly as a surprise.",
    '47:13': "Astrologers, stargazers, monthly prognosticators — the professions are named and invited to do one useful thing between them.",
    '47:14': "The experts burn like stubble, and the fire that takes them is not even the kind you could warm your hands at.",
    '47:15': "The merchants scatter, each to his own quarter. Business relationships turn out to end at the edge of trouble.",

    # ---- Chapter 48 ----
    '48:1': "Everything in the liturgy is correct, and then the last clause undoes all of it: \"but not in truth, nor in righteousness.\"",
    '48:2': "They call themselves citizens of the holy city and lean on the God of Israel. Both claims are accurate and neither one is believed.",
    '48:3': "Announced long in advance and then done \"suddenly.\" The notice was theirs; the timing stayed his.",
    '48:4': "\"Thy neck is an iron sinew, and thy brow brass.\" The reason for all the advance warning is that he knew what they were like.",
    '48:5': "The prophecies exist to close one specific escape route: so that nobody could say the idol arranged it.",
    '48:7': "The new things are created now rather than long ago, purely so that no one can claim to have known about them already.",
    '48:8': "\"A transgressor from the womb.\" He says he expected the treachery from the beginning, and went ahead with them anyway.",
    '48:9': "\"For my name's sake will I defer mine anger.\" The stay of execution is about his reputation, and Isaiah does not dress that up.",
    '48:10': "Refined \"but not with silver\" — the furnace produced no precious residue. Affliction is not credited with making them valuable.",
    '48:11': "\"For mine own sake, even for mine own sake.\" The repetition is there because he expects to be disbelieved on this exact point.",
    '48:13': "Earth and heaven stand up together when he calls them, the way a company answers a name at muster.",
    '48:14': "\"The LORD hath loved him\" — the word is spent on Cyrus, who is a foreign instrument and is loved anyway.",
    '48:16': "\"And now the Lord GOD, and his Spirit, hath sent me.\" A sent one appears mid-sentence, unnamed, and is not explained.",
    '48:17': "God describes himself as the one who \"teacheth thee to profit\" — the instructor in what would actually have done them good.",
    '48:18': "\"O that thou hadst hearkened.\" Scripture gives God a sentence of regret, and leaves the peace that might have been unclaimed.",
    '48:19': "The cost of not listening is counted in sand and gravel: descendants who were never born to be counted at all.",
    '48:20': "The order to leave Babylon comes with singing attached and a message to carry. Escape is treated as an announcement.",
    '48:21': "The wilderness water is promised again for the road home. The return is written as a second exodus, deliberately.",
    '48:22': "\"There is no peace, saith the LORD, unto the wicked.\" One flat sentence dropped at the end of a chapter of promises.",

    # ---- Chapter 49 ----
    '49:1': "The servant speaks to the isles rather than to Israel, and dates his calling and his name from before he was born.",
    '49:2': "A sharp sword hidden in a hand, a polished arrow kept in a quiver. The weapon is described mostly by being put away.",
    '49:3': "The servant is given the nation's own name, Israel — and four verses later is sent to that nation.",
    '49:4': "\"I have laboured in vain.\" The servant's own verdict on his ministry is failure, and the text lets it stand unanswered.",
    '49:5': "\"Though Israel be not gathered\" — the mission may not succeed, and the servant is told he will be honoured regardless.",
    '49:6': "\"It is a light thing.\" Restoring Israel is called too small a job, and the brief widens to the end of the earth; Paul takes it as his commission.",
    '49:7': "Abhorred by the nation now, worshipped by princes later, with nothing in between offered to explain the turn.",
    '49:8': "\"In an acceptable time have I heard thee\" — the line Paul lifts to insist that the acceptable time is the present one.",
    '49:9': "\"Go forth\" to the prisoners, \"Shew yourselves\" to those in darkness. The release is issued as a word, not as a raid.",
    '49:10': "The journey home is described as grazing. They are fed and watered along the way rather than marched through it.",
    '49:13': "A very large choir is summoned, and the reason given is mercy on the afflicted. Heaven sings over a small consolation.",
    '49:14': "\"But Zion said, The LORD hath forsaken me.\" Thirteen verses of promise, and the reply on record is flat disbelief.",
    '49:15': "The impossible comparison is conceded — \"yea, they may forget\" — and God's memory is said to outlast even that failure.",
    '49:16': "\"Graven thee upon the palms of my hands.\" Engraving on a hand is not writing on it. It cuts, and it does not come off.",
    '49:18': "Zion is told to put her returning children on like a bride's jewellery. The population is the ornament.",
    '49:19': "The land will be too narrow. Overcrowding is promised to a place whose whole complaint has been that it is empty.",
    '49:20': "Children born after the bereavement complain there is no room. That complaint is the good news of the chapter.",
    '49:21': "\"Behold, I was left alone; these, where had they been?\" She cannot account for her own household.",
    '49:22': "The Gentiles carry Israel's children home in their arms. The nations are cast as the transport, not the obstacle.",
    '49:23': "The scene of kings bowing ends on a quieter promise: those who wait will not be ashamed. Waiting is what Zion was doing badly.",
    '49:24': "\"Shall the prey be taken from the mighty?\" The objection is quoted fairly — these are lawful captives, legally held.",
    '49:25': "The reply does not dispute the law but changes the parties: \"I will contend with him that contendeth with thee.\"",
    '49:26': "The oppressors are made to consume themselves, and the stated purpose of that horror is that all flesh should know who saves.",

    # ---- Chapter 50 ----
    '50:1': "\"Where is the bill of your mother's divorcement?\" No document is produced because none exists. They sold themselves.",
    '50:2': "\"When I came, was there no man?\" God arrives and finds the room empty. The absence in this marriage is on the other side.",
    '50:4': "\"The tongue of the learned\" is given for one stated purpose: a word in season to the weary. Training aimed at the tired.",
    '50:5': "The opened ear is described as obedience rather than as insight, and the servant's not turning back is where this song turns.",
    '50:6': "\"I gave my back to the smiters.\" The suffering is handed over. Nothing in the verse is described as having been taken from him.",
    '50:7': "\"I have set my face like a flint.\" The only hardness in the servant is endurance; none of it ever turns into retaliation.",
    '50:8': "\"Who will contend with me?\" A courtroom challenge issued by a man who has just described his own beating.",
    '50:9': "\"Who is he that shall condemn me?\" Paul asks the same question at the end of Romans 8 and answers it the same way.",
    '50:10': "The man who fears the LORD and obeys the servant is also the man walking in the dark with no light. Obedience does not guarantee visibility.",
    '50:11': "Those who kindle their own fire are told to walk in it. The self-made light is not taken away; it is simply where they lie down.",
})

TAKEAWAYS.update({
    # ---- Chapter 51 ----
    '51:1': "People who are following after righteousness are told to look first at the quarry they were cut out of.",
    '51:2': "\"I called him alone.\" The argument for a future multitude is that the nation once consisted of one childless couple.",
    '51:3': "What is promised to the waste places is not improvement but Eden, and the first thing heard in it is singing.",
    '51:4': "\"A law shall proceed from me\" and it is set for a light. The law appears here as something that lets people see.",
    '51:5': "\"My righteousness is near.\" Righteousness is the thing that travels, and the isles are waiting for an arm rather than a rule.",
    '51:6': "The heavens go like smoke and the earth wears out like a coat. The things everyone calls permanent are the ones listed as passing.",
    '51:7': "People with the law written in the heart are still told not to fear revilings. Inward certainty does not quiet the street.",
    '51:9': "\"Awake, awake... O arm of the LORD.\" The prophet turns and wakes God up, addressing the prayer to God's own strength.",
    '51:10': "Cutting Rahab and drying the sea are told as the same act. Creation's oldest victory and the exodus are cited as one precedent.",
    '51:12': "The reply to the demand that God wake up is that he has been comforting them all along, and the fear was of a man who dies.",
    '51:13': "Fear of the oppressor is traced back to forgetting the maker, and the chapter ends the fear with a question: where is his fury now?",
    '51:14': "The verse is written from inside the pit — the hurry is a prisoner's, to be loosed before the bread runs out.",
    '51:16': "Words put in the mouth and a hand held over the head, and the purpose given is planting heavens. Speech is handed a cosmic job.",
    '51:17': "The cup Jerusalem drank came \"at the hand of the LORD.\" He does not disown the disaster he is about to end.",
    '51:18': "\"There is none to guide her among all the sons.\" The children she raised are not there to take her arm.",
    '51:19': "\"By whom shall I comfort thee?\" God asks who is left to console her, and the question hangs unanswered for three verses.",
    '51:20': "Her sons lie at the street corners like a wild bull caught in a net — strength taken, and still thrashing.",
    '51:21': "\"Drunken, but not with wine.\" The staggering is real and its cause is not her own indulgence.",
    '51:22': "The cup is taken out of her hand by the one who put it there, and he is described in the same verse as pleading her cause.",
    '51:23': "The cup passes to those who told her to lie down so they could walk across her. The punishment matches the posture.",

    # ---- Chapter 52 ----
    '52:1': "\"Put on thy beautiful garments\" reverses the sentence passed on Babylon five chapters earlier, and is spoken to the city that was in the dust.",
    '52:2': "\"Loose thyself from the bands of thy neck.\" The captive is told to undo her own chains, which is either mockery or the shape grace takes.",
    '52:3': "\"Sold yourselves for nought; and ye shall be redeemed without money.\" No price came in, so no price goes out.",
    '52:4': "Egypt and Assyria are set side by side: one was a sojourn they chose, the other an oppression \"without cause.\"",
    '52:5': "The grievance God states is not their suffering but that his name is blasphemed every day on account of it.",
    '52:6': "\"Behold, it is I.\" The whole operation ends not in restored fortunes but in their knowing who has been speaking.",
    '52:7': "The beauty is assigned to the feet — not the voice, not the message, the feet. Paul makes it the text for preachers.",
    '52:8': "\"They shall see eye to eye.\" The watchmen sing because, for once, all of them are looking at the same thing.",
    '52:10': "\"Made bare his holy arm\" is the gesture of a man pushing back his sleeve to fight, and it is done where every nation can see.",
    '52:11': "\"Be ye clean, that bear the vessels of the LORD.\" Those carrying holy things are held to a standard the rest are not.",
    '52:12': "Unlike the first exodus, nobody runs. God goes in front and behind, which is why there is no need for haste.",
    '52:13': "The song about the sufferer opens with his exaltation. Before a word about the wounds, the outcome is already stated.",
    '52:14': "\"Astonied\" here is not admiration but revulsion. People looked at him and had to look away.",
    '52:15': "Sprinkle is a priest's word, used of blood and water. The man too marred to look at performs a purification on nations who never heard of him.",

    # ---- Chapter 53 ----
    '53:1': "The song opens by conceding that nobody believed it. John and Paul both quote this line to account for unbelief they were watching.",
    '53:2': "A root out of dry ground. Nothing in the conditions suggested growth, and nothing in his appearance invited a second look.",
    '53:3': "\"We hid as it were our faces from him.\" The rejection is not violence but avoidance: he was easier not to look at.",
    '53:4': "The misreading is precise. They saw a man struck by God, which was true, and concluded it was for his own sins, which was not.",
    '53:5': "Everything rests on the little words: for our transgressions, for our iniquities. The wounds are his and the reasons are ours.",
    '53:6': "Each sheep wandered in its own private direction, and every one of those private directions was laid on one man's back.",
    '53:7': "\"He opened not his mouth\" twice over. Silence is the only action the song attributes to him from beginning to end.",
    '53:8': "\"Who shall declare his generation?\" He is cut off with nobody to speak for him and nobody left behind to speak of him.",
    '53:9': "His innocence is given as the reason for the grave with the rich, not as a reason for being spared. No violence, no deceit, and buried anyway.",
    '53:10': "\"It pleased the LORD to bruise him.\" The hardest sentence in the chapter puts the Father's will behind the whole thing.",
    '53:11': "\"My righteous servant\" makes many righteous. The exchange the book has been circling since chapter 1 is finally stated as a transaction.",
    '53:12': "The reward is a soldier's share of spoil, and every reason given for it points downward: poured out, numbered with transgressors, praying for them.",
})

TAKEAWAYS.update({
    # ---- Chapter 54 ----
    '54:1': "A childless woman is told to sing about children. Paul hands her the whole argument for a Jerusalem that is free.",
    '54:2': "Lengthen the cords, strengthen the stakes. The tent is enlarged well before anybody arrives to fill it.",
    '54:4': "What is promised is forgetting — the shame of her youth and the reproach of widowhood both let go rather than argued away.",
    '54:5': "\"Thy Maker is thine husband.\" The one who made her is the one who married her, which no human marriage can imitate.",
    '54:6': "She is called back as a wife of youth \"when thou wast refused.\" The reconciliation does not pretend the refusal never happened.",
    '54:7': "\"For a small moment have I forsaken thee.\" God calls the exile brief, which nobody living through it could have called it.",
    '54:8': "A little wrath set against everlasting kindness. The comfort here is entirely a matter of proportion, and he states it as such.",
    '54:9': "The guarantee offered is Noah: the point is not the flood but that God has bound himself by oath before and kept it.",
    '54:10': "Mountains are the standard example of what cannot be moved, and they are named as the ones that go first.",
    '54:11': "\"Tossed with tempest, and not comforted.\" Her actual condition is said aloud before a single sapphire is mentioned.",
    '54:12': "Gates of carbuncle and borders of pleasant stones. The defences are built out of jewellery, which is no way to hold a wall.",
    '54:13': "\"All thy children shall be taught of the LORD\" — Jesus quotes it to explain why some come to him and others do not.",
    '54:14': "What puts her far from oppression is being established in righteousness. The distance is moral before it is military.",
    '54:15': "\"They shall surely gather together, but not by me.\" Attack is expected, and God explicitly declines responsibility for it.",
    '54:16': "The smith who forges the weapon and the waster who wields it were both made by the one promising to protect her from them.",
    '54:17': "\"Their righteousness is of me.\" The heritage of the servants ends on righteousness being issued rather than accumulated.",

    # ---- Chapter 55 ----
    '55:1': "\"He that hath no money; come ye, buy.\" The invitation goes to people who cannot pay and still uses the word buy.",
    '55:2': "\"Wherefore do ye spend money for that which is not bread?\" The question is put as household economics before it is put as religion.",
    '55:3': "\"The sure mercies of David\" — a covenant made with one king is thrown open to anyone within earshot who will listen.",
    '55:5': "Nations that never knew you will come running, and the reason given is the LORD, not anything attractive about you.",
    '55:6': "\"While he may be found.\" The urgency named is not the shortness of life but the season of God's nearness.",
    '55:7': "\"He will abundantly pardon.\" The adverb carries the verse, and what it is aimed at is the unrighteous man's thoughts.",
    '55:8': "The famous line is spoken about forgiveness. The thoughts said to be unlike ours are his readiness to pardon.",
    '55:9': "Heaven's height above earth is the measure offered, which is a way of saying the distance cannot be crossed from the lower end.",
    '55:10': "Rain is chosen as the picture for one feature only: it does not go back up the way it came down.",
    '55:11': "The word is described as an agent with an errand. Whether it prospers is its business, not the hearer's achievement.",
    '55:12': "Hills singing and trees clapping — creation is written as having been waiting for this, not merely decorating it.",
    '55:13': "The thorn of the curse is replaced by the fir, and what commemorates it is a growing tree rather than a monument.",

    # ---- Chapter 56 ----
    '56:1': "Do justice because salvation is near. The ethics are grounded in what is about to arrive rather than in what already has.",
    '56:3': "The eunuch's own words, \"I am a dry tree,\" are quoted first, so that the excluded hear their sentence before it is overturned.",
    '56:4': "Keeping, choosing, taking hold — the conditions set for eunuchs are all things a man without descendants can still do.",
    '56:5': "\"A name better than of sons and of daughters\" is offered to the one man who can never have either.",
    '56:6': "Foreigners join to serve and \"to love the name.\" Affection is listed among the qualifications, next to the work.",
    '56:7': "\"An house of prayer for all people\" — the line Jesus shouts in the temple, standing in the court reserved for these very foreigners.",
    '56:8': "\"Yet will I gather others to him.\" The regathering of Israel is stated, explicitly, not to be the last one.",
    '56:9': "The beasts are invited in to feed. The turn from an open house to an unguarded pasture happens in a single verse.",
    '56:10': "\"Dumb dogs, they cannot bark.\" The watchmen's failure is not corruption but sleep, which is harder to prosecute.",
    '56:11': "\"Every one for his gain, from his quarter.\" Shepherds minding their own patch is precisely what is called greed here.",
    '56:12': "\"To morrow shall be as this day, and much more abundant.\" The drunkard's real sin in this verse is a confident forecast.",
})

TAKEAWAYS.update({
    # ---- Chapter 57 ----
    '57:1': "A good man dies and nobody thinks about it. The verse reads that death as a rescue and notes that the rescue went unremarked.",
    '57:2': "The grave is called a bed and the peace is entered straight away, with no waiting-room in between.",
    '57:5': "Child sacrifice is set down flatly in the middle of a list of religious practices, as one more item among the green trees.",
    '57:6': "The smooth stones of the brook are called her \"portion\" — the word used for what the LORD is to the tribe that had no land.",
    '57:8': "A private token set behind the door, where the commandment had told them to write the words of God on the doorpost.",
    '57:9': "The perfumes and the long-range embassies are summed up as one movement: \"didst debase thyself even unto hell.\"",
    '57:10': "\"Yet saidst thou not, There is no hope.\" Exhaustion never quite produced the admission that would have ended the whole business.",
    '57:11': "God names his own long silence as the thing that taught them he could be ignored without cost.",
    '57:12': "\"I will declare thy righteousness... they shall not profit thee.\" Their good record is what he offers to publish, and it will not save them.",
    '57:13': "\"Let thy companies deliver thee.\" The gods she collected are handed the job, and the wind is enough to take them all.",
    '57:14': "\"Take up the stumblingblock out of the way of my people.\" The instruction to the road crew is to remove things, not to add them.",
    '57:15': "The high and lofty One gives two addresses, and the second one is a crushed man's spirit.",
    '57:16': "The limit set on God's anger is what a creature can survive, not what a creature deserves.",
    '57:17': "\"I hid me, and was wroth, and he went on frowardly.\" The punishment did not work, and the text says so without embarrassment.",
    '57:18': "\"I have seen his ways, and will heal him.\" After the failed punishment comes healing, with no repentance recorded in between.",
    '57:19': "\"I create the fruit of the lips.\" Even the answering praise is his work, and the peace is announced to the far off before the near.",
    '57:20': "A sea that cannot rest and keeps throwing up mud. Restlessness is described as a condition of the wicked, not a mood.",
    '57:21': "The refrain from chapter 48 returns with one word altered: \"saith my God.\" The prophet has put himself into the sentence.",

    # ---- Chapter 58 ----
    '58:1': "The prophet is told to be as loud as a trumpet, and what he is to be loud about is his own people's sins.",
    '58:2': "The indictment opens by conceding that their religion is daily, sincere and enjoyable. None of that is disputed.",
    '58:3': "\"Wherefore have we fasted, and thou seest not?\" The complaint is that a transaction went unhonoured, which is the confession in it.",
    '58:4': "\"Ye fast for strife and debate.\" The fasting made them irritable, and the irritability had to land on somebody.",
    '58:6': "The fast God chooses is a list of things done to other people's chains rather than to one's own stomach.",
    '58:7': "\"Hide not thyself from thine own flesh.\" The hardest item on the list of the poor turns out to be the relatives.",
    '58:8': "Righteousness in front and the glory of the LORD behind. The march is escorted at both ends, and neither escort is theirs.",
    '58:9': "\"Thou shalt cry, and he shall say, Here I am\" — God answering the way a servant answers a master, which inverts the arrangement entirely.",
    '58:10': "The light rises \"in obscurity.\" It is given inside the darkness rather than as a replacement for it.",
    '58:11': "\"A spring of water, whose waters fail not.\" The one who was fed does not stay a garden; he becomes a source.",
    '58:12': "\"The repairer of the breach.\" The reward for feeding the hungry is a builder's title and other people's ruins to work on.",
    '58:13': "The sabbath is fenced not by a rule about labour but by rules about pleasure, ways and words of one's own.",
    '58:14': "Delight comes first and the high places second. The sabbath's promise is an appetite before it is an elevation.",

    # ---- Chapter 59 ----
    '59:1': "The case is made by elimination first: it is not the arm and it is not the ear. Both are ruled out before the real cause is named.",
    '59:2': "The separation is described as something they built, and its effect is on God's face rather than on his ability.",
    '59:4': "\"None calleth for justice, nor any pleadeth for truth.\" The collapse is not losing the argument but nobody making it.",
    '59:5': "Cockatrice eggs and spiders' webs. Whatever this society produces is either poisonous to eat or useless to wear.",
    '59:7': "\"Their feet run to evil\" — Paul drops this line into Romans 3 as part of his proof that nobody is exempt.",
    '59:8': "\"The way of peace they know not.\" The ignorance is genuine, which makes the situation worse rather than more excusable.",
    '59:9': "\"Therefore\" — the accusation turns into confession mid-chapter, and the speakers have started saying we.",
    '59:10': "\"We stumble at noon day as in the night.\" The light is available and they have lost the use of it.",
    '59:11': "Bears roaring and doves mourning. Both noises of frustration, the loud and the low, put in one line.",
    '59:12': "\"As for our iniquities, we know them.\" The confession claims no ignorance, which is the most honest sentence in the chapter.",
    '59:14': "\"Truth is fallen in the street\" — truth pictured as a person knocked down in public while the traffic goes round.",
    '59:15': "\"He that departeth from evil maketh himself a prey.\" Goodness has become dangerous, which is the last stage before intervention.",
    '59:16': "\"He wondered that there was no intercessor.\" God is described as surprised, and the vacancy he finds is the one he fills himself.",
    '59:17': "Breastplate, helmet, cloak. The armour is God's own, and Paul later hands the same pieces to the church to wear.",
    '59:18': "Repayment is \"according to their deeds\" — measured by their own work, which is exactly what the first half of the chapter catalogued.",
    '59:19': "When the flood comes, the standard is lifted by the Spirit. The defenders are not asked to raise it themselves.",
    '59:20': "\"The Redeemer shall come to Zion\" — Paul quotes it at the end of Romans 11 with one word shifted: out of Zion.",
    '59:21': "The covenant guarantees words in the mouths of three generations. What is promised to survive is speech, not territory.",
})

TAKEAWAYS.update({
    # ---- Chapter 60 ----
    '60:1': "\"Arise, shine; for thy light is come.\" The command comes after the gift. She is told to shine with light she did not make.",
    '60:2': "Darkness over the earth and glory over one place. What draws the nations in the next verse is the contrast, not the brightness alone.",
    '60:4': "The daughters are \"nursed at thy side.\" The returning exiles arrive as small children who had to be carried the distance.",
    '60:5': "\"Thine heart shall fear, and be enlarged.\" Fear and enlargement happen in one motion, which is how news too big to hold arrives.",
    '60:6': "Gold and incense out of Sheba, and the camels carry praise as well as freight. Matthew's visitors turn up with two of the three.",
    '60:8': "\"Who are these that fly as a cloud?\" The prophet watches his own people coming home and does not recognise them.",
    '60:9': "The ships of Tarshish, elsewhere in this book a byword for trade and idols, are put to work carrying sons.",
    '60:10': "\"In my wrath I smote thee, but in my favour have I had mercy on thee.\" Both halves are kept, and neither is allowed to cancel the other.",
    '60:11': "Gates that never shut. For an ancient city that means either perfect security or total surrender, and here it means the first.",
    '60:12': "The nations that will not serve perish. The vision of welcome keeps a hard edge and does not apologise for it.",
    '60:13': "Lebanon's timber comes to beautify the sanctuary — the same forest Sennacherib bragged about cutting down for himself.",
    '60:14': "It is the sons of the afflicters who bow. The reparation is made by a generation that did not commit the offence.",
    '60:16': "\"Thou shalt suck the milk of the Gentiles.\" The nations are cast as wet nurse to a city that had been starving.",
    '60:17': "Gold for brass, silver for iron — and then the upgrading moves off metals entirely: the officers themselves become peace and righteousness.",
    '60:18': "\"Thou shalt call thy walls Salvation, and thy gates Praise.\" The defences are renamed after work they will never have to do.",
    '60:19': "The sun is made redundant rather than destroyed, and Revelation borrows the line for a city with no temple in it.",
    '60:20': "A sun that never sets is explained in the second half of the verse: the mourning has ended, so the dark is not needed.",
    '60:21': "\"The branch of my planting, the work of my hands.\" Even the people's righteousness is traced back to whose hands did the planting.",
    '60:22': "\"I the LORD will hasten it in his time.\" Haste and waiting are put in one clause, and the clock named is not theirs.",

    # ---- Chapter 61 ----
    '61:1': "Jesus reads this aloud in Nazareth and stops in the middle of the next verse. Every verb of the anointing here is a verb of speech.",
    '61:2': "The acceptable year and the day of vengeance stand in one sentence, and in Luke the scroll is closed before the second half is read.",
    '61:3': "Three exchanges, each handing back exactly what grief took: beauty, oil, a garment. What comes out of it is called trees.",
    '61:4': "The mourners of the previous verse are the builders of this one. Generations of ruin are handed to the newly comforted.",
    '61:5': "Strangers do the ploughing and the vinedressing — the exact reversal of every arrangement in which Israel supplied the labour.",
    '61:6': "\"Ye shall be named the Priests of the LORD.\" The office is given to the whole people, and Peter repeats it to scattered congregations.",
    '61:7': "The double measure of chapter 40 was punishment received. Here the same word is used for what comes back.",
    '61:8': "\"I hate robbery for burnt offering.\" What offends is not a shortage of sacrifice but stolen goods arriving on the altar.",
    '61:10': "\"He hath clothed me with the garments of salvation.\" The righteousness is worn, and the one wearing it did not cut the cloth.",
    '61:11': "Righteousness comes up like a crop in front of all the nations. It grows into view rather than being imposed on it.",

    # ---- Chapter 62 ----
    '62:1': "\"I will not hold my peace... I will not rest.\" The speaker binds himself to keep on at it until Zion is visibly bright.",
    '62:2': "\"A new name, which the mouth of the LORD shall name.\" The right to name her belongs to God, which is why this name will hold.",
    '62:3': "A crown held in the hand rather than worn on a head. The city is something God displays, not something he puts on.",
    '62:4': "Forsaken and Desolate are traded for Hephzibah and Beulah — my delight is in her, and married. The names carry the whole argument.",
    '62:5': "\"As the bridegroom rejoiceth over the bride, so shall thy God rejoice over thee.\" What is attributed to God is delight, not relief.",
    '62:6': "Watchmen who never keep silence. Their posting is not to scan for danger but to keep reminding God of his own promise.",
    '62:7': "\"Give him no rest.\" Persistence in prayer is commanded in terms that come very close to rudeness.",
    '62:8': "The oath is sworn on God's own right arm, and what it secures is modest: that they get to eat what they grew.",
    '62:10': "\"Gather out the stones.\" The last road-building order in the book is ordinary manual labour, given to whoever is standing there.",
    '62:11': "\"His reward is with him, and his work before him\" — the line from chapter 40 returns, now as the announcement itself arriving.",
    '62:12': "\"Sought out, A city not forsaken.\" The new name is a record of the fact that somebody came looking for her.",

    # ---- Chapter 63 ----
    '63:1': "A lone figure walks out of Edom in stained clothes and answers the challenge himself: \"mighty to save.\" The saving and the staining are one errand.",
    '63:2': "The question put to him is about laundry. The answer is a winepress full of people.",
    '63:3': "\"I have trodden the winepress alone; and of the people there was none with me.\" Nobody helped, and nobody will be credited.",
    '63:4': "Vengeance and redemption are dated to the same calendar: a day for one, a year for the other, and both already in his heart.",
    '63:5': "\"I wondered that there was none to uphold.\" The surprise of chapter 59 repeats, and again the vacancy is filled by his own arm.",
    '63:7': "After the winepress, a recital of mercies. The word lovingkindness appears twice in one verse, as though once would not carry it.",
    '63:8': "\"Children that will not lie\" — God's expectation is quoted, and every reader already knows how that turned out.",
    '63:9': "\"In all their affliction he was afflicted.\" God is described as suffering with them, not merely as concerned about them.",
    '63:10': "\"He was turned to be their enemy, and he fought against them.\" Scripture does not soften whose side God took.",
    '63:11': "\"Where is he that brought them up out of the sea?\" The remembering turns into a question, and the question is about absence.",
    '63:12': "The exodus is recalled as something God did to make himself an everlasting name, and that name is what the prayer leans on.",
    '63:14': "Cattle going down into a valley to lie still. The entry into the land is pictured as rest rather than conquest.",
    '63:15': "\"Are they restrained?\" The prayer asks outright whether God's mercies have been deliberately held back.",
    '63:16': "\"Though Abraham be ignorant of us.\" The appeal skips the ancestors, because the ancestors would not recognise these descendants.",
    '63:17': "\"Why hast thou made us to err from thy ways?\" The hardening is laid at God's door, and then he is asked to come back anyway.",
    '63:18': "The whole history of the land is summed up as a short tenancy: they possessed it \"but a little while.\"",
    '63:19': "The complaint at the end is about identity: they have become indistinguishable from people God never claimed.",
})

TAKEAWAYS.update({
    # ---- Chapter 64 ----
    '64:1': "\"Oh that thou wouldest rend the heavens.\" The prayer asks for the sky to be torn, and Mark uses that same verb at the Jordan.",
    '64:2': "Even the prayer for fire is given a reason outside itself: that the nations should learn the name.",
    '64:3': "The precedent cited is \"terrible things which we looked not for.\" What they ask God to repeat is his habit of surprising them.",
    '64:4': "Paul quotes this to the Corinthians about what God has prepared. The condition attached here is simply waiting for him.",
    '64:5': "The sentence breaks apart in the middle — \"behold, thou art wroth; for we have sinned\" — and the grammar fails exactly where the confession starts.",
    '64:6': "\"All our righteousnesses are as filthy rags.\" Not the sins. The best of the record is what is being valued here.",
    '64:7': "Prayerlessness is named as the symptom — nobody stirs himself to take hold — and God's hidden face is given as its cause.",
    '64:8': "The clay picks up the potter argument from chapter 45 and uses it, this time as a plea rather than a rebuke.",
    '64:9': "\"We are all thy people.\" With the righteousness already written off, belonging is the only ground of appeal left.",
    '64:11': "The burned house is remembered as \"where our fathers praised thee.\" What is mourned is the loss of somewhere to sing.",
    '64:12': "The prayer ends on a question about God's silence and gets no answer in the chapter. The book lets it stand open.",

    # ---- Chapter 65 ----
    '65:1': "\"I am found of them that sought me not.\" Paul turns it toward the Gentiles; in Isaiah it is already aimed at the people who did ask.",
    '65:2': "Hands spread out all day long. The posture is the pleading one, and it is held toward people walking the other way.",
    '65:4': "Sitting among the graves and eating swine. The religion described here reaches for the forbidden because the forbidden feels powerful.",
    '65:5': "\"I am holier than thou,\" said by a man who has been sleeping in a tomb. Scruple and filth turn out to share a house.",
    '65:6': "\"It is written before me.\" The record already exists; the recompense will not be invented on the day.",
    '65:7': "The fathers' account and the children's are settled together. Scripture does not tidy the family ledger into individual columns.",
    '65:8': "A whole cluster is spared because one grape in it is good, and that is given as the working logic of the remnant.",
    '65:10': "The valley of Achor, named for the trouble Achan brought, becomes a place where cattle lie down in the afternoon.",
    '65:11': "Gad and Meni — luck and destiny — are served a proper meal by people who could not find time for the holy mountain.",
    '65:12': "\"When I called, ye did not answer.\" The sentence is built as an exact reply to a failure to reply.",
    '65:13': "My servants eat and ye go hungry. The line being drawn runs through the middle of one people, not between nations.",
    '65:14': "Singing on one side and howling on the other, and both are happening in the same room at the same hour.",
    '65:15': "The old name is left behind as a swear word, and the servants are called by another. Identity is reissued rather than repaired.",
    '65:16': "The former troubles are said to be \"hid from mine eyes.\" It is God's forgetting, before anyone else's, that ends them.",
    '65:17': "\"I create new heavens and a new earth\" — and the startling clause is the next one: the former shall not come into mind.",
    '65:18': "The new creation is announced as a mood. What is created is Jerusalem \"a rejoicing\" and her people \"a joy.\"",
    '65:20': "A child dying at a hundred years old. The new world is still described in numbers that leave room for death in them.",
    '65:21': "Build and inhabit, plant and eat. What is promised is simply that nothing gets in between the work and the fruit of it.",
    '65:22': "\"As the days of a tree are the days of my people.\" A life is measured against an oak rather than against a generation.",
    '65:23': "\"They shall not labour in vain.\" The curse laid on work in Genesis 3 is addressed head on and lifted.",
    '65:24': "\"Before they call, I will answer.\" The reply is described as arriving ahead of the request that prompted it.",
    '65:25': "Wolf and lamb feed together, and the serpent still eats dust. One sentence from Eden is deliberately left standing.",

    # ---- Chapter 66 ----
    '66:1': "\"Where is the house that ye build unto me?\" The temple question is put by the one who cannot be housed; Stephen quotes it as he is killed.",
    '66:2': "Poor, contrite, and trembling at his word. Trembling is listed among the qualifications rather than among the problems.",
    '66:3': "Sacrifice offered wrongly is not neutral but equivalent to murder. The rite does not lose its power when the heart goes; it reverses.",
    '66:4': "\"I also will choose their delusions.\" The judgement consists in letting the choices they made stand as chosen.",
    '66:5': "The persecutors are brethren and they say \"Let the LORD be glorified\" while they do it. The pious phrase is quoted from their side.",
    '66:6': "The recompense comes as a voice out of the temple. Judgement issues from the building that was supposed to be the refuge.",
    '66:7': "A birth before the labour. The ordinary order of pain and delivery is simply skipped over.",
    '66:8': "\"Shall a nation be born at once?\" The question is put as an absurdity, and the answer given is yes.",
    '66:9': "\"Shall I bring to the birth, and not cause to bring forth?\" God argues from his own character as one who finishes what he started.",
    '66:10': "Those told to rejoice with her are the ones who mourned for her. Having grieved is the stated qualification for the party.",
    '66:12': "Peace like a river and the wealth of nations like a stream, and the scene ends with a child bounced on a knee.",
    '66:13': "\"As one whom his mother comforteth.\" The book that opened with a father's grievance closes its comfort in a mother's terms.",
    '66:14': "\"Your bones shall flourish like an herb.\" Growth is promised to the driest part of the body there is.",
    '66:15': "Fire and chariots and whirlwind, two verses after the mother. Isaiah will not let either picture stand alone.",
    '66:16': "\"Plead\" is a courtroom word, and here it is done by fire and sword. The argument and the sentence arrive together.",
    '66:17': "The catalogue of abominations ends with the mouse. After swine's flesh and secret gardens, the last item is almost comic.",
    '66:18': "\"They shall come, and see my glory.\" All nations are gathered, and the stated purpose of the gathering is sight, not trial.",
    '66:19': "Survivors of the judgement are sent out to nations that never heard. The missionaries are drawn from among the judged.",
    '66:20': "Foreigners carry Israel's scattered home as an offering. The people themselves are the thing brought to the altar.",
    '66:21': "\"I will also take of them for priests and for Levites.\" The priesthood is opened to those who were carried in from outside.",
    '66:22': "Israel's name is given the same tenure as the new heavens and the new earth: it remains because they do.",
    '66:23': "New moon and sabbath are still kept, and the congregation attending them is all flesh.",
    '66:24': "The book ends outside the wall, looking at corpses. Jesus takes the undying worm and the unquenched fire for his own word about Gehenna.",
})
