#!/usr/bin/env python3
"""Written one-line takeaways for Jeremiah 29-52."""

TAKEAWAYS = {
    # ---- Chapter 29 ----
    '29:1': "Prophecy arrives as post. The congregation that needs this word is a thousand miles from the prophet.",
    '29:2': "Carpenters and smiths are listed with the queen: Babylon deported the skilled, and took the nation's hands.",
    '29:3': "The letter travels in Zedekiah's own diplomatic bag, carrying a word against Zedekiah's whole policy.",
    '29:4': "\"Whom I have caused to be carried away.\" Before any advice, God claims the deportation as his act.",
    '29:5': "Build houses, plant gardens. The first command to exiles is to stop living out of a packed bag.",
    '29:6': "Marry, and marry off your grandchildren. The instruction assumes two generations will die in Babylon.",
    '29:7': "They are told to pray for the city that burned theirs. Their welfare is tied to their captor's.",
    '29:8': "\"Your dreams which ye cause to be dreamed\" — the comforting prophecy was commissioned by its hearers.",
    '29:9': "The test of a prophet is not sincerity but sending, and God says flatly that he did not send them.",
    '29:10': "Seventy years is a lifetime. The promise is real and nobody first hearing it will see it kept.",
    '29:11': "Thoughts of peace and an expected end — spoken to people just told to settle in for seventy years.",
    '29:12': "Prayer is promised as part of the restoration rather than as the lever that starts it.",
    '29:13': "Sought with the whole heart. Half a heart had looked for him in Jerusalem and not found him there either.",
    '29:14': "\"Whither I have driven you.\" The scattering and the gathering are credited to the same hand.",
    '29:15': "Their objection is quoted before it is answered: we have prophets of our own here in Babylon.",
    '29:16': "Those left in Jerusalem are worse off than the deported. Escaping the first wave was not survival.",
    '29:17': "Vile figs that cannot be eaten. The good figs, in the earlier vision, were the ones already carried off.",
    '29:19': "\"Rising up early and sending them.\" God is pictured as the one who got up first, and kept at it.",
    '29:21': "Ahab and Zedekiah are named. False prophecy is charged to persons, not to a climate of opinion.",
    '29:22': "Their names survive only inside a curse. Babylon burned them and the exiles kept the phrase.",
    '29:23': "Adultery and lying in God's name are charged together, and the witness is the one they lied about.",
    '29:25': "Shemaiah writes letters in his own name. The difference from Jeremiah's letter is whose name is on it.",
    '29:26': "Prison and the stocks are described as the normal office: religion's provision for a man who prophesies.",
    '29:27': "From Babylon, Shemaiah writes to Jerusalem instructing the priesthood to shut the prophet up.",
    '29:28': "He quotes Jeremiah's letter accurately, as though the quotation were its own refutation.",
    '29:29': "Zephaniah reads the letter out to Jeremiah's face instead of acting on it, and that is the whole reply.",
    '29:31': "\"He caused you to trust in a lie.\" The charge is not error but what the comfort did to the hearers.",
    '29:32': "He will not see the good God does. Living on a false hope costs a man the real one.",
    # ---- Chapter 30 ----
    '30:2': "Write it in a book. The promise is put in writing because the people who need it are not born yet.",
    '30:3': "Israel and Judah together — the restoration reaches the northern tribes lost a century earlier.",
    '30:5': "A voice of trembling, and not of peace. The book of consolation opens by granting that the fear is right.",
    '30:6': "Men holding themselves like women in labour. The picture of terror is chosen to humiliate.",
    '30:7': "\"The time of Jacob's trouble, but he shall be saved out of it.\" Not saved from the day, saved through it.",
    '30:8': "The yoke Jeremiah had worn on his own neck before them is the thing God promises to break.",
    '30:9': "Release from Babylon is not independence. They are freed in order to serve the LORD and David's king.",
    '30:10': "\"Fear thou not\" is addressed to a servant who is still standing in the land of his captivity.",
    '30:11': "A full end of the nations, a measured correction for Israel. The same blow means different things.",
    '30:12': "\"Thy bruise is incurable.\" God states the case as hopeless before he says he will heal it.",
    '30:13': "None to plead the cause and no medicines. Every human remedy is cleared off the table first.",
    '30:14': "The lovers are the alliances, and they forget her. Courted nations lose interest the moment you are poor.",
    '30:15': "She cries out over a wound whose cause has already been named to her, repeatedly, for forty years.",
    '30:16': "Those who devoured her are devoured. Being God's instrument never made Babylon innocent of using the sword.",
    '30:17': "He heals her because men called her Outcast. The taunt itself is what is quoted as the reason.",
    '30:18': "The city is built again upon her own heap — restoration on the rubble, not on a cleaner site.",
    '30:19': "Thanksgiving and the voice of merrymakers are named as the produce of the rebuilt town.",
    '30:20': "Their children as aforetime. What is promised is not a golden age but ordinary life resumed.",
    '30:21': "\"Who is this that engaged his heart to approach unto me?\" Nobody comes near on his own nerve.",
    '30:22': "\"Ye shall be my people, and I will be your God.\" The whole consolation is an expansion of this line.",
    '30:23': "The whirlwind returns in the middle of the comfort. Mercy for Jacob does not suspend judgement.",
    '30:24': "\"In the latter days ye shall consider it.\" Understanding is promised later than the event itself.",
    # ---- Chapter 31 ----
    '31:1': "All the families of Israel — twelve tribes, long since broken apart, reassembled in one clause.",
    '31:2': "Grace was found in the wilderness by people left of the sword, not in the settled land afterward.",
    '31:3': "\"I have loved thee with an everlasting love.\" The drawing is the evidence; the love is the cause.",
    '31:4': "\"Again I will build thee, and thou shalt be built.\" The passive follows the active, never the reverse.",
    '31:5': "Vines planted on the hills of Samaria. Planting for a harvest you expect to eat is the shape of hope.",
    '31:6': "Ephraim's watchmen call the pilgrimage to Zion. The old schism ends in a shout from the wrong side of it.",
    '31:7': "They are told to sing for the remnant of Israel, because a remnant is all the nation there will be.",
    '31:8': "The blind, the lame and the woman in labour are in the returning column, which moves at their pace.",
    '31:9': "They come weeping and are led by water in a straight way. Repentance and comfort arrive together.",
    '31:10': "\"He that scattered Israel will gather him.\" The nations are told, because it settles who runs history.",
    '31:11': "Ransomed from a hand stronger than his own — which is the admission that he could not buy himself out.",
    '31:12': "\"They shall not sorrow any more at all.\" The promise plainly overshoots the return from Babylon.",
    '31:13': "Mourning is turned into joy, not swapped for it. The same material is worked over into something else.",
    '31:14': "Priests satiated and people satisfied out of one supply, and the supply is called God's own goodness.",
    '31:15': "Rachel refuses to be comforted, and the text lets her refusal stand before it answers her.",
    '31:16': "\"Thy work shall be rewarded.\" The weeping itself is counted as labour, and labour is paid.",
    '31:17': "Hope is located in the end rather than in the present, which is precisely why it is called hope.",
    '31:18': "\"Turn thou me, and I shall be turned.\" Even repentance is asked for as a thing God has to give.",
    '31:19': "Shame comes after the turning, not before it. He is ashamed as a man already being received.",
    '31:20': "God speaks against Ephraim and remembers him in the same breath, and calls the remembering bowels.",
    '31:21': "Set up waymarks along the road out. They are told to mark the way into exile so they can find it back.",
    '31:22': "\"A woman shall compass a man.\" The new thing is announced and deliberately left unexplained.",
    '31:23': "The restoration is measured by a blessing people will say to each other again in ordinary talk.",
    '31:24': "Husbandmen and shepherds sharing one countryside. Peace is described as two trades not at odds.",
    '31:26': "\"My sleep was sweet unto me.\" The prophet who watched the city burn records one good night.",
    '31:27': "Sowing with the seed of man and of beast. Repopulation is put in the vocabulary of farming.",
    '31:28': "The watching that plucked up is the watching that builds. God's attention never lapsed or changed kind.",
    '31:29': "The sour-grape proverb is retired — the exiles' standing complaint that they are paying their fathers' bill.",
    '31:30': "Every one shall die for his own iniquity. The comfort in that sentence is that the account is yours.",
    '31:31': "A new covenant is promised, which concedes that the old one failed at exactly the point that mattered.",
    '31:32': "\"Although I was an husband unto them.\" The covenant was broken by one party, and it was not God.",
    '31:33': "The law is not lowered, only relocated: the same commands, written where the wanting happens.",
    '31:34': "\"They shall all know me\" rests on \"I will forgive\" — the pardon comes first and produces the knowledge.",
    '31:35': "Sun, moon and sea are brought in as collateral. God pledges the running of creation against his word.",
    '31:36': "Israel's survival is tied to the ordinances of the moon: as likely to lapse as tonight's tide.",
    '31:37': "Casting Israel off is made conditional on measuring heaven, which is a way of saying it will not happen.",
    '31:38': "The rebuilt city is laid out by named towers and gates. This promise comes with surveyors.",
    '31:40': "The valley of dead bodies and ashes is made holy. The dump and the graveyard end up inside the wall.",
}

TAKEAWAYS.update({
    # ---- Chapter 32 ----
    '32:1': "Dated to Zedekiah's tenth year, the year the siege closed. The date is half of what the chapter means.",
    '32:2': "The army is outside the wall and the prophet is inside the prison court. Both facts are given at once.",
    '32:3': "Zedekiah jailed him for the content of the message, and the charge sheet quotes it accurately.",
    '32:4': "\"His eyes shall behold his eyes.\" Zedekiah does meet Nebuchadnezzar, and is blinded immediately after.",
    '32:5': "\"Though ye fight with the Chaldeans, ye shall not prosper.\" The resistance is not brave, only futile.",
    '32:7': "The land deal is announced by prophecy before the cousin turns up at the gate to propose it.",
    '32:8': "\"Then I knew that this was the word of the LORD.\" The confirmation was an ordinary visit happening.",
    '32:9': "Seventeen shekels for a field in occupied country. The sum is recorded because it was actually paid.",
    '32:10': "Signed, sealed, witnessed, weighed out. The sign God asked for is conveyancing done properly.",
    '32:11': "Sealed copy and open copy both. The legal formalities are kept exactly while the city is falling.",
    '32:12': "The deed is handed over in front of the Jews sitting in the prison court. The witnesses are deliberate.",
    '32:14': "The deeds go into an earthen jar to keep many days. The filing arrangements are the prophecy.",
    '32:15': "\"Houses and fields and vineyards shall be possessed again.\" That sentence cost seventeen shekels to say.",
    '32:16': "He obeys first and prays afterward. The purchase was made before he understood what he had done.",
    '32:17': "\"There is nothing too hard for thee\" — said by a man working up to asking whether this was a mistake.",
    '32:18': "Mercy to thousands and iniquity repaid into the children's bosom, held together in one breath.",
    '32:19': "God's eyes are open upon all the ways of men, which is comfort and threat inside the same clause.",
    '32:21': "The prayer rehearses the exodus, because the man praying needs reminding that God has done this before.",
    '32:23': "\"They came in, and possessed it; but they obeyed not.\" The whole history as gift and refusal.",
    '32:24': "\"Behold, thou seest it.\" He finishes his history lesson by pointing at the siege mounds outside.",
    '32:25': "The real question is kept until last: you told me to buy a field in a city you are handing over.",
    '32:27': "\"Is there any thing too hard for me?\" God answers by quoting Jeremiah's own opening line back to him.",
    '32:28': "The first half of the answer is that the city falls exactly as feared. Comfort here is not a reprieve.",
    '32:29': "They burned incense on the roofs; the Chaldeans burn the roofs. The sentence reuses their own fire.",
    '32:30': "\"Only done evil before me from their youth.\" The indictment leaves no period to look back on fondly.",
    '32:31': "The city has provoked him from the day it was built. Not even David's Jerusalem is exempted.",
    '32:32': "Kings, princes, priests, prophets, people. The list is drawn so no class can blame another for it.",
    '32:33': "\"The back, and not the face.\" What is charged is the posture, not any argument they ever made.",
    '32:34': "The abominations were set inside the house called by his name, and that is what made it defilement.",
    '32:35': "\"Neither came it into my mind.\" Child sacrifice is disowned as something God never thought to ask for.",
    '32:36': "God repeats their own despairing sentence about the city word for word before he contradicts it.",
    '32:37': "Gathered out of the countries he drove them to. The same wrath, once spent, becomes the road home.",
    '32:39': "One heart and one way are given, and given \"for the good of them.\" Fearing God is described as a benefit.",
    '32:40': "The everlasting covenant is secured at both ends by God: he will not turn away, and neither will they.",
    '32:41': "\"With my whole heart and with my whole soul.\" God describes his own appetite for doing them good.",
    '32:42': "The good is guaranteed by the evil already delivered. He kept the threat, so he will keep the promise.",
    '32:43': "Fields bought in a land they themselves call desolate. One absurd purchase becomes the ordinary future.",
    '32:44': "Deeds, seals and witnesses again, all over the country. What one man did in prison becomes everyone's.",
    # ---- Chapter 33 ----
    '33:1': "The second word comes while he is still shut up. Nothing about his circumstances improved in between.",
    '33:2': "The one who made the thing is the one who can establish it, and the name is offered as the guarantee.",
    '33:3': "\"Call unto me, and I will answer thee\" — said to a prisoner, about things he could not reason his way to.",
    '33:4': "Houses were pulled down to plug the breach. The city dismantled itself to survive, and did not survive.",
    '33:5': "The sorties only fill the houses with dead men, and God names whose anger did the actual killing.",
    '33:6': "Health and cure, and with them peace and truth. Part of the healing is being told the truth again.",
    '33:7': "\"As at the first.\" What is promised is not an improvement on the old order but that order returned.",
    '33:8': "Cleanse and pardon: the stain lifted and the charge dropped. Neither one by itself would do.",
    '33:9': "The nations are moved to fear by God's goodness to Judah, not by his judgement on her.",
    '33:10': "He quotes their description of the desolation back at them, in full, before overturning it.",
    '33:11': "The bridegroom's voice and the mercy-endureth-for-ever psalm, promised to streets with no inhabitant.",
    '33:12': "Shepherds bedding flocks where nothing now lives. The picture of recovery is deliberately unremarkable.",
    '33:13': "Flocks passing again under the hand of him that counts them. Someone taking inventory is the sign of peace.",
    '33:14': "The promise is not new. What is promised here is the performing of an old one already on the books.",
    '33:15': "The Branch grows up unto David, and what he does with the office is judgment and righteousness.",
    '33:16': "The name given to the king in an earlier oracle is now worn by the city: The LORD our righteousness.",
    '33:17': "David shall never want a man on the throne — said as the last king of his line is about to be blinded.",
    '33:18': "Throne and priesthood are promised together, which is how the New Testament finds them joined in one man.",
    '33:20': "The covenant with day and night is offered as the test case: break the sunrise and you may break this.",
    '33:22': "Stars and sand were Abraham's promise. It is transferred here onto David's line and the Levites.",
    '33:24': "The people already say God has cast off both families. Despair is quoted here as a form of contempt.",
    '33:26': "The oath is anchored behind David in Abraham, Isaac and Jacob, where nothing recent can reach it.",
    # ---- Chapter 34 ----
    '34:1': "The word comes while every kingdom of Nebuchadnezzar's dominion is at the wall. The setting is the argument.",
    '34:2': "Jeremiah is sent to tell the king to his face that the city he is defending will be burnt.",
    '34:3': "\"Thine eyes shall behold the eyes of the king of Babylon.\" It is the personal detail that makes it unbearable.",
    '34:4': "\"Yet hear the word of the LORD.\" Even this sentence has a mercy clause, addressed to Zedekiah by name.",
    '34:5': "A proper funeral with burnt spices and a lament. That is the entire good news given to this king.",
    '34:7': "Lachish and Azekah are named as the last two fortified cities left. The defence is down to two names.",
    '34:8': "The covenant to free slaves is struck during a siege, which says something about when reform gets tried.",
    '34:9': "The ground of release is brotherhood. A Jew may not hold a Jew, whatever the law permitted with others.",
    '34:10': "\"Then they obeyed, and let them go.\" The obedience was genuine for as long as it lasted.",
    '34:11': "The Babylonians pulled back and the freed slaves were taken again. Repentance lifts with the pressure.",
    '34:13': "The release law is traced to the exodus: a people bought out of slavery may not manufacture more of it.",
    '34:14': "Every seventh year, and the fathers never once did it. The law being broken here was already dead letter.",
    '34:15': "God grants that they had done right. He does not pretend the good act never happened at all.",
    '34:16': "\"Ye turned and polluted my name.\" The reversal is worse than the neglect because a vow was spent on it.",
    '34:17': "They would not proclaim liberty, so liberty is proclaimed — to the sword, the pestilence and the famine.",
    '34:18': "They had cut a calf in two and walked between the halves, swearing to become that if they broke faith.",
    '34:19': "Princes, eunuchs, priests and people all passed between the parts. Every class signed the same oath.",
    '34:21': "The army \"which are gone up from you\" still holds the king's future. The relief was only a pause.",
    '34:22': "God says he will command the besiegers back. The withdrawal that emboldened the slaveholders was borrowed.",
    # ---- Chapter 35 ----
    '35:1': "The Rechabite scene is dated to Jehoiakim, years earlier. It sits here for contrast, not chronology.",
    '35:2': "He is told to set out wine and press it on men who do not drink. The sermon is staged as an experiment.",
    '35:4': "The test is arranged in the temple, beside the princes' chamber, where the right people will see it.",
    '35:5': "Full pots and a direct invitation. God arranges a temptation for the pleasure of having it refused.",
    '35:6': "\"Jonadab our father commanded us.\" The refusal rests on a dead man's word, not on conviction or taste.",
    '35:7': "No house, no seed, no vineyard. A whole manner of life held for two centuries on one man's instruction.",
    '35:8': "Wives, sons and daughters are all named as keeping it. That is why the rule outlived the man who made it.",
    '35:10': "\"We have dwelt in tents, and have obeyed.\" The report is flat, and claims no difficulty in the doing.",
    '35:11': "They are inside Jerusalem only because an army drove them in. Even the exception comes with its reason.",
    '35:13': "\"Will ye not receive instruction?\" The question is put to Judah after the Rechabites have answered it.",
    '35:14': "A man's command is kept for generations. God's, spoken early and repeatedly, is not kept for a season.",
    '35:15': "The prophets' whole message reduces to return and amend, with the land named as what was on offer.",
    '35:17': "The judgement is finally grounded on two failures of hearing: I have spoken, and I have called.",
    '35:18': "What is commended is obedience to a father rather than to God. God credits it to them anyway.",
    '35:19': "Jonadab is promised a man standing before God for ever — the promise elsewhere made to David and Levi.",
})

TAKEAWAYS.update({
    # ---- Chapter 36 ----
    '36:2': "All the words from the days of Josiah onto one roll. Twenty years of preaching becomes an object.",
    '36:3': "\"It may be that the house of Judah will hear.\" The sentence is written down in hope of being cancelled.",
    '36:4': "Jeremiah dictates and Baruch writes. The book exists because a second man was willing to hold the pen.",
    '36:5': "\"I am shut up; I cannot go into the house of the LORD.\" Barred from the temple, he sends his voice in.",
    '36:6': "The fast day is chosen for the reading: the one day the crowd has already come in expecting bad news.",
    '36:9': "The fast falls in the ninth month, a year after the roll was written. The reading waited for its day.",
    '36:10': "Baruch reads from a borrowed chamber in the higher court. The word gets its hearing by loan of office space.",
    '36:12': "Michaiah goes straight down to the princes. The report travels further than the reader had arranged.",
    '36:14': "They send for the roll rather than for the man. It is the document the government wants in its hands.",
    '36:15': "\"Sit down now, and read it in our ears.\" The princes give the prophecy the hearing the king will not.",
    '36:16': "They were afraid, and the fear produced only a promise to pass the matter upward to the king.",
    '36:17': "\"How didst thou write all these words at his mouth?\" They ask about method, which is a way of not answering.",
    '36:18': "\"I wrote them with ink in the book.\" The answer is entirely ordinary, and that is the claim being made.",
    '36:19': "The princes' practical help is advice to disappear. They know their own king better than they will say.",
    '36:21': "Jehudi reads the same words a second time, now to the king. Identical text, opposite reception.",
    '36:22': "The ninth month, and a fire on the hearth. The means of destroying the roll is already lit in the room.",
    '36:23': "Three or four leaves, then the penknife and the flame. He destroys it a column at a time as it is read.",
    '36:24': "Nobody rent his garments. Josiah tore his clothes over a scroll; his son sat still and kept warm.",
    '36:25': "Three princes ask him not to burn it. Their names are kept, and so is the fact that he would not hear.",
    '36:26': "Warrants go out for the scribe and the prophet, and the note is simply that the LORD hid them.",
    '36:28': "\"Take thee again another roll.\" The answer to the fire is dictation, begun over from the first word.",
    '36:29': "The king's own question is quoted back at him. He burned the answer rather than dispute the writing.",
    '36:30': "His body cast out to the heat and the frost. The man who sat by a warm hearth is promised the open weather.",
    '36:31': "\"But they hearkened not.\" The account closes on the failure of hearing rather than on the burning.",
    '36:32': "The second roll has many like words added. Burning the first one cost Jehoiakim the shorter version.",
    # ---- Chapter 37 ----
    '37:2': "Neither the king, nor his servants, nor the people of the land. The deafness is spread evenly by name.",
    '37:3': "\"Pray now unto the LORD our God for us.\" Prayer is requested from the man whose word they will not take.",
    '37:5': "Pharaoh's army marches and the siege lifts. For a few weeks the false prophets looked like the accurate ones.",
    '37:7': "The army come to help shall return to Egypt. The rescue is real, and it is going home.",
    '37:8': "\"And take it, and burn it with fire.\" The reprieve changes the date and changes nothing else.",
    '37:9': "\"Deceive not yourselves.\" The lie under indictment is the one the hearers are telling themselves.",
    '37:10': "Wounded men left in their tents would rise and burn the city. The outcome is not a matter of arithmetic.",
    '37:12': "With the siege lifted he leaves for Benjamin on property business. The prophet takes the gap like anyone else.",
    '37:13': "A captain at the gate reads the errand as desertion. The man who urged surrender is easy to suspect.",
    '37:14': "\"It is false; I fall not away.\" The denial is recorded, and alters nothing about what is done to him.",
    '37:15': "They beat him and jail him in a scribe's house made over into a prison. Even the building was repurposed.",
    '37:16': "The dungeon, the cabins, and many days. The length of it is stated with no complaint attached.",
    '37:17': "\"Is there any word from the LORD?\" Asked in secret, and answered with the word already given in public.",
    '37:18': "\"What have I offended?\" He argues his case on the merits, to a king who has charged him with nothing.",
    '37:19': "\"Where are now your prophets?\" The men who promised safety are not in prison, and are not in evidence.",
    '37:20': "He does not ask for release, only not to be sent back. He knows what that house does to a man.",
    '37:21': "A daily loaf from the bakers' street, until the city's bread ran out. The mercy lasts as long as the flour.",
    # ---- Chapter 38 ----
    '38:2': "\"He shall have his life for a prey.\" Surrender is offered as plunder: the only spoil left is breath.",
    '38:4': "The charge is weakening the hands of the men of war. Telling the truth is prosecuted as damage to morale.",
    '38:5': "\"The king is not he that can do any thing against you.\" Zedekiah gives him up by pleading helplessness.",
    '38:6': "No water in the cistern, but mire. He is lowered into a place that kills slowly and leaves no marks.",
    '38:7': "An Ethiopian eunuch of the palace is the one who hears and moves. Help comes from outside every circle.",
    '38:9': "\"These men have done evil.\" A foreigner says plainly at the gate what the princes of Judah would not.",
    '38:10': "Thirty men are detailed to lift one starving prisoner. The king acts decisively in the harmless direction.",
    '38:11': "He goes to the treasury and brings out old rotten rags. What saves the prophet's life is the palace's refuse.",
    '38:12': "\"Put now these old cast clouts under thine armholes.\" The kindness is in noticing that ropes cut.",
    '38:13': "They drew him up, and he stayed in the court of the prison. The rescue returns him to custody.",
    '38:14': "\"I will ask thee a thing; hide nothing from me.\" The king wants the word without being seen to want it.",
    '38:15': "Jeremiah states the terms first: you will not listen, and answering you has already cost me once.",
    '38:16': "He swears by the God who made the soul that he will not take this soul, and he swears it secretly.",
    '38:17': "Going out would save the city as well as the man. Surrender is offered as the way to keep both.",
    '38:18': "The alternative is put without a third branch. The choice offered Zedekiah has exactly two outcomes.",
    '38:19': "\"I am afraid of the Jews that are fallen to the Chaldeans.\" A king's fear of mockery decides a city.",
    '38:20': "\"Obey, I beseech thee.\" The prophet pleads with the king as though the outcome were still open.",
    '38:22': "The palace women will chant it: thy feet are sunk in the mire. The taunt borrows the pit he was let into.",
    '38:23': "\"Thou shalt cause this city to be burned.\" Babylon will light it and the act is charged to him.",
    '38:24': "The king's last request is secrecy. He bargains over the leak instead of over the decision.",
    '38:27': "Jeremiah repeats the cover story he was handed, and the matter was not perceived.",
    '38:28': "He was in the court of the prison when the city fell. The safest place in Jerusalem had been the jail.",
})
