#!/usr/bin/env python3
"""Written one-line takeaways for Jeremiah 1-28."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"The words of Jeremiah\" — a priest's son from a village outside the city, named before God is.",
    '1:2': "The word comes in Josiah's thirteenth year, five years before the book of the law was found.",
    '1:3': "The dates run to the carrying away captive. The ministry is measured against the exile it did not prevent.",
    '1:5': "Known, sanctified, ordained — all three before birth, and none of them anything he did.",
    '1:6': "\"I cannot speak: for I am a child.\" The prophet's first recorded word is a refusal.",
    '1:7': "The objection is not answered, only overruled. Where he goes and what he says are both assigned.",
    '1:8': "Fear of their faces is assumed rather than denied. What is promised against it is company.",
    '1:9': "The hand touches the mouth. The words he will be hated for are put there by someone else.",
    '1:10': "Four verbs for tearing down and two for building. The ratio is the shape of the next forty years.",
    '1:11': "God asks what he sees and the answer is a twig. Vision here begins with what is actually in front of him.",
    '1:12': "The almond branch and the hastening are near the same word in Hebrew. The pun is the whole message.",
    '1:13': "A pot boiling over, tilted from the north. The picture carries a compass bearing before it carries a threat.",
    '1:14': "North is not geography here. It is the road every invading army has to take into Judah.",
    '1:15': "Foreign kings set their thrones in the gateway — the place where Judah's own elders gave judgment.",
    '1:16': "Three charges: forsaken me, burned incense to others, worshipped the works of their own hands.",
    '1:17': "Being confounded before them is held out as the sharper danger, sharper than anything they can do.",
    '1:18': "Defenced city, iron pillar, brasen walls. The fortification promised is the man, not the town.",
    '1:19': "\"They shall fight against thee\" is inside the promise. Deliverance is not the same as being spared.",
    # ---- Chapter 2 ----
    '2:2': "The indictment opens with the honeymoon remembered: a bride who followed him into unsown country.",
    '2:3': "Firstfruits are holy and eating them is trespass. Israel's safety lay in belonging, not in strength.",
    '2:5': "\"What iniquity have your fathers found in me?\" God asks to be shown the fault that justified leaving.",
    '2:6': "The sin named is a question nobody asked — Where is the LORD? Apostasy begins as simple neglect.",
    '2:7': "The gift was a plentiful country and what they did with it was defile it. Ingratitude put as vandalism.",
    '2:8': "Priests, lawyers, pastors, prophets. Every office that existed to know him is listed as part of the failure.",
    '2:9': "\"I will yet plead with you.\" The lawsuit runs on into the grandchildren, and pleading is not destroying.",
    '2:10': "Send to Chittim and Kedar and ask. God submits his case to comparative religion and expects to win it.",
    '2:11': "The pagans at least keep their gods. Judah traded a real glory for one that does not even profit.",
    '2:12': "The heavens are told to be horrified. The exchange is unnatural enough that the sky should notice.",
    '2:13': "Two evils, not one: leaving the spring, and then the labour of cutting tanks that will not hold.",
    '2:14': "The questions expect no for an answer. Israel was not born a slave, so the plundering has to be explained.",
    '2:16': "Noph and Tahapanes are Egyptian towns. The ally they ran to is the one who broke their crown.",
    '2:17': "\"Hast thou not procured this unto thyself\" — the damage is traced to the moment the hand was let go.",
    '2:18': "Drinking the Nile or drinking the Euphrates. Both alliances are a thirst they had no need to have.",
    '2:19': "The punishment is the sin allowed to finish its sentence. Backsliding does its own correcting.",
    '2:20': "The yoke God broke was Egypt's. The freedom went straight up every high hill and under every green tree.",
    '2:21': "A noble vine of right seed turned into something strange. The gardener is not the one who changed.",
    '2:22': "Nitre and soap will not touch it. The stain does not lie on the surface where washing reaches.",
    '2:23': "\"I am not polluted\" is met by a pointed finger: see thy way in the valley. Denial dies on evidence.",
    '2:24': "A wild ass in her season needs no seeking; she finds them. The appetite is what is being described.",
    '2:25': "\"There is no hope\" is said by the sinner, not by God. Despair here is a way of refusing to stop.",
    '2:26': "Ashamed as a thief is ashamed — caught, not sorry. Kings, princes, priests and prophets in one line.",
    '2:27': "A block of wood for father, a stone for mother, and then in trouble a cry to the God they turned from.",
    '2:28': "\"According to the number of thy cities are thy gods.\" Many gods is described as a shortage, not a piety.",
    '2:29': "They are pleading against him. The accused has walked into court as the one bringing the charge.",
    '2:30': "Their own sword devoured their prophets. The correction was killed as soon as it arrived.",
    '2:31': "\"Have I been a wilderness unto Israel?\" They left as though he had failed them, and he asks how.",
    '2:32': "A bride does not forget her attire. Forgetting God turns out to be harder to explain than rebelling.",
    '2:33': "She has grown so practised at seeking lovers that the wicked pick up technique from watching her.",
    '2:34': "The blood of the poor is on her skirts — not turned up by secret search, but lying in plain sight.",
    '2:35': "\"I have not sinned\" is what brings the case to trial. The claim of innocence becomes the charge.",
    '2:36': "Egypt will shame her as Assyria did. Changing sides is the one thing she has been consistent about.",
    '2:37': "Hands on the head is a captive's posture. The confidences were rejected by God before they failed her.",
    # ---- Chapter 3 ----
    '3:1': "The law forbids taking back a wife who has gone to another. God quotes it, then says return anyway.",
    '3:2': "\"See where thou hast not been lien with\" — he asks her to find him one hilltop that is still clean.",
    '3:3': "Drought is read as an answer. A whore's forehead is the refusal to blush, and that is the real trouble.",
    '3:4': "The words are perfect — my father, the guide of my youth — and the doing goes on unchanged beneath them.",
    '3:5': "Asking whether the anger will last for ever while doing evil as hard as you can is not repentance.",
    '3:6': "Israel's case is opened in Josiah's reign, with reform under way and Judah in the room listening.",
    '3:7': "\"And I said after she had done all these things, Turn thou unto me.\" The hope is admitted, and it failed.",
    '3:8': "Israel was divorced and deported where Judah could watch it, and Judah drew no conclusion at all.",
    '3:9': "The lightness of the whoredom is what defiles. The sin was not even taken seriously by those doing it.",
    '3:10': "Josiah's reformation is called feigned. A turning can be real in law and unreal in the heart.",
    '3:11': "The northern kingdom, long destroyed, is the more justified of the two. Privilege raises the charge.",
    '3:12': "The reason given is \"I am merciful,\" and it is preached northward to a people already carried away.",
    '3:13': "\"Only acknowledge thine iniquity.\" What return requires is not restitution but the truth said aloud.",
    '3:14': "\"I am married unto you\" — said to the divorced. One of a city and two of a family is a small, honest number.",
    '3:15': "The promised gift is pastors who feed with knowledge. Restoration arrives as ordinary teaching.",
    '3:16': "The ark will not be missed or rebuilt. A sign is dropped once the thing it pointed at is present.",
    '3:17': "Jerusalem itself becomes the throne, and the nations come to a name rather than to a box.",
    '3:18': "Judah and Israel walk home together out of the north. The exile's road is the one the return uses.",
    '3:19': "God talks like a father working out how to keep a son in the will: how shall I put thee among the children?",
    '3:20': "The covenant is a marriage, so the breach is not disobedience but treachery.",
    '3:21': "Weeping is heard from the high places — the same hills where the whoring was done.",
    '3:22': "\"I will heal your backslidings.\" The disease and the cure are named with the one word.",
    '3:23': "\"In vain is salvation hoped for from the hills.\" The confession names exactly where they had been looking.",
    '3:24': "Shame ate the labour of the fathers: flocks, herds, sons, daughters. Baal cost more than he ever gave.",
    '3:25': "The confession lies down in the dust and claims nothing — we and our fathers, from our youth until now.",
    # ---- Chapter 4 ----
    '4:1': "\"Return unto me.\" Not to the temple and not to a policy. The destination named is a person.",
    '4:2': "An honest oath in Judah is what would draw the nations in. The mission hangs on the swearing being true.",
    '4:3': "Fallow ground has to be broken before seed goes in, or the sowing is only feeding the thorns.",
    '4:4': "Circumcision of the heart asks for the covenant sign in the place it was always aimed at.",
    '4:5': "The call is to run for the walled cities. It is an order to take shelter, not an order to fight.",
    '4:6': "The standard goes up toward Zion and the word given is retire. There is no line anyone is to hold.",
    '4:7': "The lion has left his thicket. The destroyer is drawn as an animal, not an empire, and he is already moving.",
    '4:8': "Sackcloth is commanded because the anger has not turned back. Mourning is the only sane thing left.",
    '4:9': "King, princes, priests and prophets all fail on the same day. No institution is left standing to explain it.",
    '4:10': "\"Thou hast greatly deceived this people.\" Jeremiah lays the false prophets' peace at God's own door.",
    '4:11': "A wind that neither fans nor cleanses. It is the desert wind, no use whatever to a man with grain.",
    '4:12': "The weather turns into a courtroom: \"now also will I give sentence against them.\"",
    '4:13': "\"Woe unto us! for we are spoiled.\" The prophet puts himself among the people the news is about.",
    '4:14': "\"Wash thine heart\" is still being said while the chariots are being described. The offer has not closed.",
    '4:15': "Dan is the northern border. The news comes in stages, and this is the stage that is still far off.",
    '4:16': "Besiegers are called watchers, and it is God publishing the summons against his own city.",
    '4:17': "Keepers of a field guard what belongs to them. The besiegers are posted like men with a right to be there.",
    '4:18': "\"This is thy wickedness, because it is bitter.\" The sin and the suffering are given the same name.",
    '4:19': "\"My bowels, my bowels!\" The man carrying the sentence cannot sit still underneath it.",
    '4:20': "Tents and curtains spoiled in a moment. National ruin is measured by one household coming down.",
    '4:21': "\"How long shall I see the standard?\" He asks the question the people should have been asking.",
    '4:22': "Wise to do evil and no knowledge for good. What is missing is not intelligence but direction.",
    '4:23': "\"Without form, and void\" — Genesis 1 running backwards. Judgement is described as creation undone.",
    '4:24': "Mountains trembling and hills moving lightly. The things chosen to shake are the ones that never move.",
    '4:25': "No man and no birds left. The fifth and sixth days are rolled back in a single sentence.",
    '4:26': "The cities are broken down at the presence of the LORD, which is not the same as at the army's.",
    '4:27': "\"Yet will I not make a full end.\" One clause inside the ruin keeps the story from stopping here.",
    '4:28': "\"I have spoken it, I have purposed it.\" The word that will not be taken back is this one.",
    '4:29': "The flight is from noise — horsemen and bowmen heard well before anyone has seen them.",
    '4:30': "Crimson, gold and paint on the face while the lovers come to kill her. The alliances end as murder.",
    '4:31': "The cry is a first labour, which is the one nobody has any way of being ready for.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "One just man found in the streets would buy a pardon for the city. The search is offered, and it fails.",
    '5:2': "They swear by the living LORD and the oath is false. The name is used most where it is trusted least.",
    '5:3': "Stricken and not grieved, faces harder than a rock. Suffering on its own has softened nobody here.",
    '5:4': "Jeremiah first excuses them as poor and untaught. He looks for a kinder explanation before he gives up.",
    '5:5': "He goes to the educated men and finds the yoke broken there too. Knowing the way was never the difficulty.",
    '5:6': "Lion, wolf and leopard waiting at the edge of ordinary life. Going out of the gate is all it takes.",
    '5:7': "\"When I had fed them to the full.\" The adultery is dated to the season of plenty, not of want.",
    '5:8': "Fed horses neighing after the neighbour's wife. The picture is coarse on purpose, and it is about appetite.",
    '5:9': "\"Shall I not visit for these things?\" The question is put to the reader and expects him to agree.",
    '5:10': "Destroy, but make not a full end. Even the order given to the invaders has a limit written into it.",
    '5:12': "\"It is not he.\" Unbelief in Judah is not denying God exists but denying he will ever do anything.",
    '5:13': "The prophets shall become wind. What they said would blow over turns out to be what blows them away.",
    '5:14': "Words made fire and the people made wood. The preacher does not kindle it; he only carries it about.",
    '5:15': "A nation whose language you do not know. Part of the terror is not understanding the men at your gate.",
    '5:16': "\"Their quiver is as an open sepulchre.\" The grave is pictured arriving before the arrow does.",
    '5:17': "The list is everything a household eats, and it ends at the fenced cities they had trusted instead.",
    '5:18': "The reprieve is said again in the middle of the devouring, as though it needed hearing twice.",
    '5:19': "The sentence answers the crime word for word: strange gods served at home, strangers served abroad.",
    '5:21': "Eyes that see not, ears that hear not. The organs work; what has failed is the willingness to use them.",
    '5:22': "Sand holds back the sea. God's argument for fear is that the weakest barrier obeys him and they will not.",
    '5:23': "A revolting and rebellious heart. The fault is located under the behaviour, in the thing that does the wanting.",
    '5:24': "They never said, Let us fear the LORD that giveth rain. The rain came anyway and taught them nothing.",
    '5:25': "\"Your sins have withholden good things from you.\" The loss is not arbitrary. They paid for it themselves.",
    '5:26': "Men who set traps for other men, and they are found among my people. The hunter here is a neighbour.",
    '5:27': "Houses full of deceit as a cage is full of birds — and that, it says plainly, is how they got rich.",
    '5:28': "Waxen fat and shining, with the fatherless case never heard. The prosperity and the neglect are one item.",
    '5:31': "\"My people love to have it so.\" False prophets need an audience, and the audience is the worse half.",
    # ---- Chapter 6 ----
    '6:1': "Jeremiah tells his own tribe to get out. Benjamin is his people and Anathoth stands in it.",
    '6:2': "Zion is drawn as a comely and delicate woman, one verse before the camps are pitched around her.",
    '6:3': "Shepherds pitching tents and feeding, each in his place. The siege is described as quiet grazing.",
    '6:4': "The enemy's own talk is quoted: impatient at noon, and willing enough to work after dark.",
    '6:6': "\"This is the city to be visited.\" The LORD of hosts is the one giving orders to cut the siege timber.",
    '6:7': "A well keeps its water fresh by always giving. She keeps her wickedness fresh in the same way.",
    '6:8': "\"Lest my soul depart from thee.\" The threat held over the city is not damage but God leaving it.",
    '6:9': "Glean her as a vine and turn the hand back over the branches. Thoroughness is the frightening word.",
    '6:10': "\"The word of the LORD is unto them a reproach.\" It is not disputed, only found tiresome, which is worse.",
    '6:11': "\"I am weary with holding in.\" The fury is the LORD's, and the prophet has been carrying it himself.",
    '6:12': "Houses, fields and wives turned over to others. Judgement reaches what they thought they owned outright.",
    '6:13': "Least to greatest, prophet to priest. The corruption is complete by rank and complete by office.",
    '6:14': "\"Peace, peace; when there is no peace.\" A wound healed slightly is a wound closed over the infection.",
    '6:15': "They could not blush. Shame is spoken of as a capacity that has been lost, not a choice being made.",
    '6:16': "Stand, see, ask, walk. Four invitations, answered in four words: We will not walk therein.",
    '6:17': "Watchmen were set and the trumpet blown. The refusal to listen is recorded as a second, separate answer.",
    '6:19': "\"The fruit of their thoughts.\" The evil coming on them grows from what they had already been thinking.",
    '6:20': "Incense from Sheba and sweet cane from far off. Expense has never yet made an offering acceptable.",
    '6:21': "Stumblingblocks laid by God himself, and fathers and sons go down over them together.",
    '6:22': "\"From the sides of the earth\" — the enemy comes from beyond anything in Judah's experience.",
    '6:23': "Cruel, without mercy, roaring like the sea. Nothing in the description suggests they could be bargained with.",
    '6:24': "They have only heard the report and their hands already fail. The rumour does the army's work early.",
    '6:25': "\"Fear is on every side\" — the phrase that will follow Jeremiah through the rest of the book.",
    '6:26': "Mourning as for an only son. The comparison is to the grief that has nothing left over afterwards.",
    '6:27': "The prophet is set as an assayer. His work is to test the metal, not to decide what it proves to be.",
    '6:28': "Brass and iron where silver was expected. The base metals are the ones that came through the fire.",
    '6:29': "The bellows burned, the founder melting in vain. The refining is admitted to have failed.",
    '6:30': "\"Reprobate silver\" is the assayer's word for metal that would not come clean. The verdict is God's.",
    # ---- Chapter 7 ----
    '7:2': "The sermon is preached standing in the temple gate, to people on their way in to worship.",
    '7:3': "\"Amend your ways\" comes before the promise of dwelling. The tenancy had terms nobody was reading.",
    '7:4': "\"The temple of the LORD\" three times over is quoted as a chant. Repetition is how a lie gets its authority.",
    '7:5': "The test of amendment is judgment executed between a man and his neighbour. Not worship — court.",
    '7:6': "Stranger, fatherless, widow, innocent blood. The covenant's terms are named as people with no defender.",
    '7:7': "\"For ever and ever\" hangs on an if. The permanence was never offered without the condition.",
    '7:8': "\"Lying words, that cannot profit.\" The charge against the slogan is that it does not work.",
    '7:9': "Five commandments broken inside one sentence, and then the man walks in through the gate to worship.",
    '7:10': "\"We are delivered to do all these abominations.\" The temple was being used as a licence.",
    '7:11': "\"Is this house become a den of robbers?\" A den is where thieves rest between jobs, not where they work.",
    '7:12': "Go and look at Shiloh. The ruined sanctuary is the argument, and anyone could walk up and check it.",
    '7:13': "\"Rising up early and speaking.\" God's patience is drawn as a man getting up before dawn, again and again.",
    '7:14': "The house they trust in will be handled exactly as the house they have stopped thinking about.",
    '7:15': "Ephraim is already gone. Judah is told her brothers are the precedent and not the exception.",
    '7:16': "\"Pray not thou for this people.\" He is forbidden the one thing he most wanted to do for them.",
    '7:18': "Children gathering wood, fathers kindling, women kneading. Idolatry here is a family baking together.",
    '7:19': "\"Do they not provoke themselves?\" The anger is real, and the damage lands on the ones causing it.",
    '7:20': "Man, beast, trees, fruit of the ground. The fury falls on a land that did none of it.",
    '7:21': "\"Eat flesh.\" Take the whole burnt offering home and make a meal of it; as worship it is worth nothing.",
    '7:22': "God says the word out of Egypt was not about sacrifices. The ritual was never the centre of it.",
    '7:23': "\"Obey my voice, and I will be your God.\" The whole arrangement, with no ceremony anywhere in it.",
    '7:24': "\"They went backward, and not forward.\" No one was ever offered the option of standing still.",
    '7:25': "Prophets sent daily since the day they came out of Egypt. The refusal is not this generation's invention.",
    '7:26': "\"They did worse than their fathers.\" The record does not show a nation gradually improving.",
    '7:27': "He is told in advance that no one will answer him, and told to go and speak in any case.",
    '7:28': "\"Truth is perished, and is cut off from their mouth.\" What has died is not belief but honesty.",
    '7:29': "Cut off the hair and take up a lamentation. Jerusalem is told to conduct her own funeral.",
    '7:30': "The abominations are set inside the house called by his name. The pollution is put where the name is.",
    '7:31': "\"Neither came it into my heart.\" God denies that the thought of child sacrifice ever occurred to him.",
    '7:32': "Tophet is renamed the valley of slaughter, and the burying is done in the place of the burning.",
    '7:33': "Carcases with nobody left to fray the birds away. The insult is that no one remains to do it.",
    '7:34': "The voice of the bridegroom and the bride stops. Judgement is heard as silence where weddings were.",
    # ---- Chapter 8 ----
    '8:1': "The bones of kings, princes, priests and prophets turned out of their graves. Even the dead are reached.",
    '8:2': "Spread out before the sun and stars they worshipped. The gods they served are made to watch and do nothing.",
    '8:3': "\"Death shall be chosen rather than life.\" The survivors are described as the ones worse off.",
    '8:4': "A man who falls gets up; a man who turns away comes back. Judah does neither, and that is the strange thing.",
    '8:5': "\"They hold fast deceit.\" The grip is theirs. Nothing holds them in place but their own hands.",
    '8:6': "No man said, What have I done? The horse rushing into battle does not stop to consider either.",
    '8:7': "Stork, turtle, crane and swallow keep their seasons. The migrating birds know their times; Judah does not.",
    '8:8': "\"The pen of the scribes is in vain.\" Owning the law and handling it professionally are not obeying it.",
    '8:9': "Rejecting the word leaves the wise men with nothing. Their wisdom went out of the door with it.",
    '8:10': "Wives and fields given away. Covetousness is punished by having the coveted thing handed to somebody else.",
    '8:11': "\"Peace, peace\" is quoted a second time because the preachers themselves kept repeating it.",
    '8:13': "No grapes, no figs, the leaf fading. What was given is taken back item by item, in the order it came.",
    '8:14': "The people's own voice: let us go into the cities and be silent. They admit the water of gall is deserved.",
    '8:15': "\"We looked for peace, but no good came.\" They had been promised it, and the disappointment stands unanswered.",
    '8:16': "Horses snorting heard from Dan, and the whole land shakes. The noise arrives long before the riders do.",
    '8:17': "Serpents that will not be charmed. The usual remedy is named precisely in order to be ruled out.",
    '8:18': "\"When I would comfort myself against sorrow, my heart is faint in me.\" He tried, and it did not work.",
    '8:19': "\"Is not the LORD in Zion?\" The cry takes his presence for granted, and is answered with a question.",
    '8:20': "\"The harvest is past, the summer is ended, and we are not saved.\" A season closed with nothing gathered.",
    '8:21': "\"For the hurt of the daughter of my people am I hurt.\" He does not stand outside the sentence he carries.",
    '8:22': "\"Is there no balm in Gilead?\" The medicine existed and was close by. That is what makes the question bitter.",
    # ---- Chapter 9 ----
    '9:1': "He wants a head of water so he can weep harder. The man announcing the ruin wishes he could mourn it more.",
    '9:2': "He also wants to be gone — a lodging in the desert, away from them. Both wishes stand side by side.",
    '9:3': "Tongues bent like bows. The weapon in this chapter is speech, and they have been trained in it.",
    '9:4': "Trust no brother. The society described has lost the thing that makes ordinary life workable.",
    '9:5': "\"They weary themselves to commit iniquity.\" Deceit has become labour, and it is tiring them out.",
    '9:6': "\"Through deceit they refuse to know me.\" Habitual lying ends by making God himself unrecognisable.",
    '9:7': "\"How shall I do for the daughter of my people?\" The melting is put as God finding no other way left.",
    '9:8': "Peace in the mouth and an ambush in the heart. The courtesy is part of the attack, not a break from it.",
    '9:10': "God takes up the weeping himself, over burnt pastures where there is no beast left to make a sound.",
    '9:11': "Jerusalem made heaps and a den of dragons. The city becomes a place where only wild things live.",
    '9:12': "Who is wise enough to explain this? The question is raised as though nobody had thought to ask it.",
    '9:13': "The answer is old and plain: they forsook the law set before them. There is no hidden reason to find.",
    '9:14': "\"Which their fathers taught them.\" Idolatry is handed down like a trade, with lessons and a master.",
    '9:15': "Wormwood and water of gall. What they are fed is bitter, and it is still God doing the feeding.",
    '9:16': "Scattered among nations neither they nor their fathers knew. Exile is being made a stranger everywhere.",
    '9:17': "Send for the mourning women. The grief is too large to be managed by a household on its own.",
    '9:19': "\"Our dwellings have cast us out.\" The houses are made the subject; the land itself does the expelling.",
    '9:20': "Teach your daughters wailing. The skill is passed on because it is going to be needed for years.",
    '9:21': "\"Death is come up into our windows.\" Not the gate — the window, where nobody thought to post a guard.",
    '9:22': "Bodies like the handful the reaper drops and leaves. The dead are described as what nobody gathers.",
    '9:23': "Wisdom, might and riches. The three things a man would boast of are named, and all three are refused.",
    '9:24': "What may be gloried in is knowing him, and he names himself by lovingkindness, judgment and righteousness.",
    '9:25': "Circumcised and uncircumcised punished together. The mark does not by itself put anyone on the safe side.",
    '9:26': "Judah is listed between Egypt and Edom, one more uncircumcised nation among the neighbours.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:2': "The heathen are themselves dismayed at the signs of heaven. Why borrow a religion that frightens its own?",
    '10:3': "The god's story starts with a man walking into a wood with an axe, and nothing later in the account undoes that.",
    '10:4': "\"That it move not.\" The god has to be nailed down, or it would fall over where it stands.",
    '10:5': "Upright as a palm and carried like furniture. They cannot even do harm, which is the sharper insult.",
    '10:6': "The satire breaks off into praise mid-argument. The mockery only works set beside something real.",
    '10:7': "\"O King of nations\" — the title claims the very kingdoms whose wise men were just being laughed at.",
    '10:8': "\"The stock is a doctrine of vanities.\" A block of wood is called a teaching; what it teaches is its own grain.",
    '10:9': "Tarshish silver, Uphaz gold, blue and purple from skilled hands. The bill is itemised to show what it bought.",
    '10:10': "\"The living God\" is set against gods that must be carried. The difference named is which one moves by itself.",
    '10:11': "The one verse of Jeremiah written in Aramaic — a line Judah could say back to her captors in their own language.",
    '10:12': "Power, wisdom, discretion. The three things claimed for the craftsman are handed back to their owner.",
    '10:13': "Wind brought out of his treasures. Weather is drawn as stored wealth being spent, not as a mood.",
    '10:14': "\"Every founder is confounded by the graven image.\" The maker is the first man his own product shames.",
    '10:16': "Israel does not own her God. She is the portion, the measured-out share of somebody else's inheritance.",
    '10:17': "\"Gather up thy wares.\" The order is the one given to a refugee, not to a citizen of a fortress.",
    '10:18': "\"I will sling out the inhabitants\" — thrown clear of the land the way a stone leaves a sling.",
    '10:19': "\"Truly this is a grief, and I must bear it.\" The city stops arguing and takes the wound as hers.",
    '10:20': "Cords broken and nobody left to set up the curtains. Ruin pictured as a tent that will not be pitched again.",
    '10:21': "The pastors did not seek the LORD, and it is the flock that ends up scattered for it.",
    '10:23': "\"The way of man is not in himself.\" Said by the man whose own road went nowhere he would have chosen.",
    '10:24': "\"Correct me, but with judgment.\" He asks not to be spared the correction but to survive it.",
    '10:25': "The prayer he was forbidden to make for Judah he makes against her enemies instead.",
    # ---- Chapter 11 ----
    '11:2': "He is sent out as herald of an old document. The news is that the covenant still has terms in it.",
    '11:3': "\"Cursed be the man that obeyeth not.\" The covenant's own curse is read back to the people who agreed to it.",
    '11:4': "Egypt is called an iron furnace, and what came out of the smelter was a people under orders.",
    '11:5': "\"So be it, O LORD.\" Jeremiah says amen to the curse, putting himself under it with everybody else.",
    '11:7': "\"Even unto this day.\" The protesting is one unbroken sentence running from Egypt to the morning he speaks.",
    '11:8': "\"The imagination of their evil heart\" is what they walked in. Self-will is named here as the rival god.",
    '11:9': "\"A conspiracy is found.\" Apostasy is charged as something agreed to, not something drifted into.",
    '11:10': "Turned back, not forward. The new thing they wanted was their grandfathers' religion.",
    '11:11': "\"I will not hearken.\" The door that had always stood open is announced shut before they knock on it.",
    '11:12': "They will go and cry to the gods they paid for. The verse lets them, and says nothing will come of it.",
    '11:13': "A god for every city and an altar for every street. Idolatry counted out by civic geography.",
    '11:14': "The ban on praying for them is repeated, and now his cry and their cry are refused in the same breath.",
    '11:15': "She is still called \"my beloved\" in the sentence asking what she thinks she is doing in the house.",
    '11:16': "\"A green olive tree\" was the name he gave her. The fire in the branches is kindled by the one who named her.",
    '11:17': "\"Which they have done against themselves.\" The provoking injured the provoker before it reached anyone else.",
    '11:18': "He had no idea he was being hunted until he was shown. A prophet is not naturally well informed.",
    '11:19': "\"Let us destroy the tree with the fruit thereof.\" The plan is to end the name, not merely the man.",
    '11:20': "He asks to watch the vengeance himself. The book keeps the request and does not tidy it up.",
    '11:21': "\"Prophesy not, that thou die not by our hand.\" The threat comes out of Anathoth, his own village.",
    '11:23': "\"No remnant of them.\" The vengeance he asked to see is measured out on the town he grew up in.",
    # ---- Chapter 12 ----
    '12:1': "He grants that God is righteous and then files the complaint anyway, and in that order.",
    '12:2': "\"Near in their mouth, and far from their reins.\" The distance between speech and kidneys is measured, not guessed.",
    '12:3': "He asks for them exactly what they had planned for him, and reaches for the same word, slaughter.",
    '12:4': "Beasts and birds consumed over something men said. The land pays for a sentence spoken on it.",
    '12:5': "The complaint is answered with a harder question. He is told this was the level ground.",
    '12:6': "Fair words out of his own father's house are named as the thing he must not believe.",
    '12:7': "God uses of himself the word he has been using against them: I have forsaken mine house.",
    '12:8': "\"Therefore have I hated it.\" The heritage roared at its own owner, and the reply is left standing.",
    '12:9': "A speckled bird the rest of the flock turns on. Being marked out is what drew the attack.",
    '12:10': "The vineyard is ruined by its own keepers. No invader is mentioned until the pastors have been.",
    '12:11': "The desolate land mourns to God because no man laid it to heart. Grief goes up for want of a witness.",
    '12:13': "Wheat sown and thorns reaped. The labour was real enough; only the harvest failed to arrive.",
    '12:14': "Judah is plucked up in the same motion as her evil neighbours, and out of the same ground.",
    '12:15': "Compassion after the plucking up is promised to the neighbours too, each man back to his own land.",
    '12:16': "The nations that taught Judah to swear by Baal may be built in her midst if they learn the other name.",
})

TAKEAWAYS.update({
    # ---- Chapter 13 ----
    '13:1': "A linen girdle, worn next to the skin and never to be washed. The errand begins with clothing, not a sermon.",
    '13:4': "The sign requires a journey to Euphrates — the river the army will come from — to bury a belt in a rock.",
    '13:6': "\"After many days.\" The sign needs time to work, and he has to make the journey a second time.",
    '13:7': "He digs up what he buried and it is ruined. Nothing was done to it except leaving it in the ground.",
    '13:9': "What is to be marred is named as the pride of Judah. The nation is not the object of the verb.",
    '13:10': "They are not punished into uselessness. They are declared good for nothing, which is the harder word.",
    '13:11': "The girdle was chosen because it is worn close. Being chosen is pictured as being held against the body.",
    '13:12': "He is handed a proverb they will answer with a shrug, and the shrug is part of what he was sent to provoke.",
    '13:13': "The wine in the saying turns out to be stupor, poured out for kings, priests and prophets alike.",
    '13:14': "Earthen jars knocked together. Not pity, not spare, not have mercy — three refusals set side by side.",
    '13:15': "\"Be not proud: for the LORD hath spoken.\" Pride is treated here as a failure to listen.",
    '13:16': "Give glory before the darkness comes. The offer has a window in it, and the window is the light still up.",
    '13:17': "He will weep in secret places over their pride. The messenger grieves the message he is carrying.",
    '13:18': "\"Humble yourselves, sit down.\" The crown is told to take a seat before it is taken off the head.",
    '13:19': "The cities of the south are shut first. The road out towards Egypt closes before the city itself does.",
    '13:20': "The king is asked where his beautiful flock is. He was lent it, and is being asked to produce it.",
    '13:21': "The allies she trained as captains become her masters. She gave the lessons herself.",
    '13:22': "\"Wherefore come these things upon me?\" The question is anticipated, and answered with exposure, not argument.",
    '13:23': "Habit is put on a level with skin and spots. Being accustomed to evil is described as something fixed.",
    '13:24': "Stubble on the wilderness wind. The material is chosen because nobody goes out afterwards to collect it.",
    '13:25': "\"The portion of thy measures from me.\" The lot is measured out, and he does not disown the measuring.",
    '13:27': "\"When shall it once be?\" The chapter ends on a question about timing, and leaves it open.",
    # ---- Chapter 14 ----
    '14:1': "\"Concerning the dearth.\" The word arrives about the weather, and the whole argument starts from a dry sky.",
    '14:2': "The gates are said to languish and the ground to be black. The city mourns before anyone in it speaks.",
    '14:3': "Nobles send their little ones to the pits, and the children come back with empty jars and covered heads.",
    '14:5': "The hind leaves her own calf in the field. The drought is measured by an animal's instinct giving out.",
    '14:7': "The plea is not innocence but reputation: do it for thy name's sake, because our name will not serve.",
    '14:8': "God is charged with acting like a traveller who turns aside to stay one night and is gone by morning.",
    '14:9': "\"As a mighty man that cannot save.\" The accusation is put as a question and is never withdrawn.",
    '14:10': "\"They have loved to wander.\" The straying was enjoyed, and that is what makes it theirs and not an accident.",
    '14:11': "The third prohibition, and the wording narrows: pray not for this people for their good.",
    '14:12': "Fasting, burnt offering and oblation are named one by one in order to be refused one by one.",
    '14:13': "He pleads their case by blaming the preachers: the prophets promised them assured peace in this place.",
    '14:14': "Not sent, not commanded, not spoken to. The visions are traced back to the prophets' own hearts.",
    '14:15': "The men who promised no sword and no famine are to be consumed by sword and famine.",
    '14:17': "He is commanded to weep night and day. The tears are part of the assignment, not his reaction to it.",
    '14:18': "Slain in the field, famine in the city. The picture is arranged so that there is no door out of it.",
    '14:19': "\"Hast thou utterly rejected Judah?\" The prayer puts into words the thing nobody wanted said aloud.",
    '14:20': "The confession is full and accurate, naming their own sin and their fathers', and it changes nothing.",
    '14:21': "They ask him to keep the covenant they broke, and appeal to his own honour as the reason.",
    '14:22': "Rain is made the test question. The gods they paid for cannot produce the one thing anybody wants.",
    # ---- Chapter 15 ----
    '15:1': "Moses and Samuel are named and ruled out. The refusal is not a comment on Jeremiah's standing.",
    '15:2': "A sorting rhyme with four exits — death, sword, famine, captivity — and no door marked escape.",
    '15:3': "Sword first, then dogs and birds and beasts. The appointed list carries on past the point of dying.",
    '15:4': "Manasseh is named as the cause, two generations after his funeral. The account was still open.",
    '15:5': "The last loss is the smallest: nobody will step off the road to ask her how she does.",
    '15:6': "\"I am weary with repenting.\" God speaks of his own relenting as something that has worn him out.",
    '15:7': "Winnowing done in the gates of the land, where the town's ordinary business was settled.",
    '15:8': "Widows above the sand of the sea, and the spoiler sent at noonday, when nobody is watching for him.",
    '15:9': "The mother of seven left with none, and her sun going down while it is still the middle of the day.",
    '15:10': "\"Woe is me, my mother, that thou hast borne me.\" He has lent to no one, and is cursed by everyone.",
    '15:11': "The answer does not promise rescue. It promises that the enemy will treat him well.",
    '15:12': "\"Shall iron break the northern iron and the steel?\" A question left standing with no explanation attached.",
    '15:15': "He asks God to be less patient, because the longsuffering is keeping his persecutors in good health.",
    '15:16': "\"Thy words were found, and I did eat them.\" The word went down like food, and the joy came with the name.",
    '15:17': "He sat alone, and credits the loneliness to God's hand rather than to anybody's cruelty.",
    '15:18': "He asks whether God has been a dry streambed to him. The book prints the question and leaves it there.",
    '15:19': "\"If thou return\" — the prophet is the one told to repent. His complaint is answered with a call.",
    '15:20': "He is made a brasen wall, not given one. The defence is something he is turned into.",
})
