#!/usr/bin/env python3
"""Written one-line takeaways for Job 1-22."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The narrator settles Job's innocence before anything happens, so every later charge against him is already false.",
    '1:3': "Greatest of all the men of the east. The wealth is stated plainly, and Satan will call it the reason for the piety.",
    '1:4': "The feasting is not criticised. The book gives Job a happy family before it takes one away.",
    '1:5': "Job offers sacrifices for sins he only suspects. His religion runs ahead of any evidence of guilt.",
    '1:6': "The reader is let into a council Job never hears about, and that ignorance is the shape of his whole ordeal.",
    '1:7': "Satan's answer says where he has been and nothing about why. The evasion is left standing.",
    '1:8': "God raises the subject first. Job is not caught up in a case he brought on himself.",
    '1:9': "\"Doth Job fear God for nought?\" The question is whether love of God can survive apart from what God pays.",
    '1:10': "The charge is that Job loves the hedge and not the one who set it, and it can only be tested by removal.",
    '1:11': "Satan asks God to strike. What follows is not God's hand withheld but God's permission given.",
    '1:12': "Even the destruction is bounded. Satan can move only inside a limit he did not set.",
    '1:13': "The blow falls on a feast day, in the middle of the life Job had been thanking God for.",
    '1:15': "Raiders, and then one survivor left to carry the news. The grief is delivered by design.",
    '1:16': "\"The fire of God is fallen from heaven.\" The second blow arrives already labelled as God's own doing.",
    '1:17': "The third messenger begins before the second has finished. The losses overlap so there is no room to absorb them.",
    '1:19': "The children die in the house of their feasting, at the very thing Job had been sanctifying them for.",
    '1:20': "He tears his robe and shaves his head, and then he worships. The mourning is not tidied up first.",
    '1:21': "\"The LORD gave, and the LORD hath taken away.\" Job names God as the agent and blesses him in one breath.",
    '1:22': "The verdict again: what Job said was grief, not sin. The book permits a man to talk like this.",
    # ---- Chapter 2 ----
    '2:1': "The council meets a second time. Whatever the first round proved, it did not close the matter.",
    '2:2': "The same question, the same answer. Nothing about the accuser has changed; everything about Job's life has.",
    '2:3': "\"Thou movedst me against him, to destroy him without cause.\" God accepts the phrase without cause and leaves it unexplained.",
    '2:4': "\"Skin for skin.\" The accusation narrows: strip a man down to his own body and the piety will go.",
    '2:6': "\"Save his life.\" The second limit is narrower than the first, and it is still a limit.",
    '2:7': "Sole of the foot to the crown. The affliction is total, and nothing in the text calls it deserved.",
    '2:8': "A potsherd and an ash heap. The greatest man of the east is left scraping himself with a broken pot.",
    '2:9': "His wife's counsel is not stupid; it follows from her theology. If God does this, let go of him.",
    '2:10': "Job refuses to divide God into the part that gives good and some other part that sends evil.",
    '2:11': "They came from their own places, by appointment, to mourn with him. Whatever they became, they showed up.",
    '2:12': "They could not recognise him. Before any argument, the friends' grief is real and loud.",
    '2:13': "Seven days without a word is the best thing they do. The trouble starts when they open their mouths.",
    # ---- Chapter 3 ----
    '3:1': "After seven days of silence Job speaks first, and what comes out is a curse on his own birth.",
    '3:3': "He curses the day, not God. That distinction is what holds the rest of the book open.",
    '3:4': "\"Let not God regard it\" — he asks God to unmake a day God had made and looked upon.",
    '3:5': "Darkness is asked for as a stain and as a tenant. Job wants the day occupied, not merely dimmed.",
    '3:6': "He asks that the night be struck from the calendar, so that no anniversary of him is left standing.",
    '3:7': "Solitary, with no joyful voice in it. The curse is aimed at the shout that greets a birth.",
    '3:8': "He summons whoever curses days to join him. Job's sorrow is looking for allies and is not fussy.",
    '3:9': "\"Let it look for light, but have none.\" What he asks for is hope disappointed, not simple dark.",
    '3:10': "The charge lands on the womb that opened. He does not curse God, and he spares nothing else.",
    '3:11': "\"Why died I not from the womb?\" The cursing turns into asking, and the asking is the harder thing.",
    '3:12': "Even the knees that caught him and the breasts that fed him are counted among the injuries.",
    '3:13': "What he wants is not oblivion but rest, which tells you plainly what he has not had.",
    '3:14': "Kings who built desolate places now lie in them. Death levels the monuments along with the men.",
    '3:16': "The stillborn is named as the better lot. The book lets a righteous man say that out loud.",
    '3:17': "\"There the wicked cease from troubling.\" The grave is praised for the one mercy it certainly gives.",
    '3:18': "The prisoners rest and no longer hear the oppressor. Job's comfort is that death at least stops things.",
    '3:19': "The servant is free from his master. Every hierarchy Job knows dissolves at the same depth.",
    '3:20': "\"Wherefore is light given to him that is in misery?\" The question is now aimed squarely at the giver.",
    '3:21': "Men who dig for death as for hidden treasure. The image grants that some suffering really does want to end.",
    '3:22': "Joy attached to finding a grave. Job knows how strange that sounds, and says it anyway.",
    '3:23': "The hedge Satan called protection Job now feels as a fence. It is the same word, said from inside.",
    '3:24': "Sighing arrives before food and roaring pours out like water. Pain has taken over the ordinary hours.",
    '3:25': "\"The thing which I greatly feared is come upon me.\" Prosperity had not made him easy; it made him watchful.",
    '3:26': "No safety, no rest, no quiet — and trouble came anyway. Job denies he was ever living carelessly.",
    # ---- Chapter 4 ----
    '4:2': "Eliphaz opens by apologising for speaking, and then speaks for two chapters.",
    '4:3': "The credit is genuine: Job has strengthened others. It is also the setup for the charge coming.",
    '4:4': "Words that upheld the falling are recalled, and are about to be used to measure the man who spoke them.",
    '4:5': "\"It is come upon thee, and thou faintest.\" The counsellor's first move is to note that Job is not coping.",
    '4:6': "Eliphaz points Job to his own uprightness for comfort — the very thing now under question.",
    '4:7': "\"Who ever perished, being innocent?\" The reader has watched the answer sit down in the ashes.",
    '4:8': "His evidence is what he has seen. The whole argument rests on one man's sample of the world.",
    '4:9': "Judgement is drawn as God's breath: effortless, and in Eliphaz's telling, always aimed correctly.",
    '4:10': "The lions are the strong wicked, broken in the teeth. A fine image, and it does not fit the man he is facing.",
    '4:11': "The whelps are scattered too. Even the children are folded in, days after Job buried his own.",
    '4:12': "Eliphaz claims a private revelation. From here his advice carries authority Job has no way to check.",
    '4:13': "The vision comes in deep sleep, at the hour when a mind is least able to test what it hears.",
    '4:15': "A spirit passes and the hair stands up. Eliphaz was persuaded by the sensation before the words came.",
    '4:16': "\"I could not discern the form thereof.\" He admits he never saw what spoke, and quotes it as settled.",
    '4:17': "\"Shall mortal man be more just than God?\" True in itself, and no answer at all to a man asking why.",
    '4:18': "If angels are charged with folly, no creature has standing anywhere. The argument proves too much to be of use.",
    '4:19': "Houses of clay, crushed before the moth. Human frailty is real; it is not the same thing as guilt.",
    '4:20': "Men perish unregarded between morning and evening. It is offered as comfort, and it is not comfort.",
    '4:21': "\"They die, even without wisdom.\" Eliphaz ends his revelation with a truth that leaves Job nowhere to stand.",
    # ---- Chapter 5 ----
    '5:1': "\"To which of the saints wilt thou turn?\" Eliphaz closes the appeal court before Job can reach it.",
    '5:2': "Wrath and envy kill the fool. The proverb is aimed at Job's grief, as though anger were the disease.",
    '5:3': "He watches a fool prosper and pronounces the ruin in advance. The theory tells him what he is seeing.",
    '5:4': "The children crushed in the gate. He describes Job's fresh loss as the standard fate of a wicked man's sons.",
    '5:6': "Trouble does not spring out of the ground — so, by his logic, it must have sprung out of the man.",
    '5:7': "\"Man is born unto trouble, as the sparks fly upward.\" A true observation, used here to close a question.",
    '5:8': "\"I would seek unto God\" — easy counsel from a chair, given to a man who has been praying throughout.",
    '5:9': "God's works are past finding out, says the man who is about to explain exactly what God is doing.",
    '5:11': "Setting the low on high is true of God. It is not yet true of Job, and that gap is the whole difficulty.",
    '5:12': "God frustrating the crafty is good news to everybody except the man being told he is one of them.",
    '5:13': "\"He taketh the wise in their own craftiness.\" Paul quotes this line; even a false comforter can say a true thing.",
    '5:14': "Groping at noon. His picture of judgement is loss of bearings rather than loss of goods.",
    '5:15': "God saves the poor from the mouth of the mighty — said by a man whose own words are doing the wounding.",
    '5:16': "\"Iniquity stoppeth her mouth.\" Eliphaz is certain that in the end the right people fall silent.",
    '5:17': "\"Happy is the man whom God correcteth.\" The truest line in the speech, and it still assumes a fault to correct.",
    '5:18': "He woundeth, and his hands make whole. Eliphaz has the shape of it right and the diagnosis wrong.",
    '5:19': "Six troubles, and in seven none shall touch thee. A guarantee issued without any authority to issue it.",
    '5:21': "Hidden from the scourge of the tongue: the one danger on his list that Job is suffering at their hands.",
    '5:22': "\"At destruction and famine thou shalt laugh.\" Said to a man sitting in the ashes of both.",
    '5:23': "Peace with the stones and the beasts of the field. What Eliphaz holds out is essentially Eden regained.",
    '5:24': "Thy tabernacle shall be in peace. Job's household is already gone, and the promise is made anyway.",
    '5:25': "Offspring as the grass of the earth, promised to a man who buried ten children in a single day.",
    '5:26': "A grave in full age, like a shock of corn in season — a good death, held out as the reward for confessing.",
    '5:27': "\"We have searched it, so it is.\" The speech ends in certainty, and the certainty is what God will judge.",
}

TAKEAWAYS.update({
    # ---- Chapter 6 ----
    '6:2': "He asks for his grief to be weighed. The plea is not for relief but for someone to take its measure.",
    '6:3': "Heavier than the sand of the sea, and so his words are swallowed up. He warns that his speech will be wild.",
    '6:4': "\"The arrows of the Almighty are within me.\" Job does not blame circumstance or an enemy; he names the archer.",
    '6:5': "The wild ass does not bray over good grass. Complaint is evidence that something is genuinely missing.",
    '6:6': "Unsavoury food without salt. What the friends serve up cannot be swallowed, however correct the recipe.",
    '6:7': "What he once refused to touch is now his daily meat. Suffering redefines what a man can stomach.",
    '6:8': "Having been given nothing he asked for, he asks for the one thing left: that God finish the work.",
    '6:9': "He asks God to kill him. It is still a prayer, and still addressed to the same God he is accusing.",
    '6:10': "The comfort he names is that he has not concealed God's words. Even wanting to die, he holds to that.",
    '6:11': "\"What is my strength, that I should hope?\" Endurance is being urged on a man with nothing left to endure with.",
    '6:12': "Stones and brass. He tells the friends what his body is actually made of before they prescribe patience.",
    '6:13': "He looks inward for resources and finds the cupboard bare. Wisdom itself is described as driven out.",
    '6:14': "Pity is owed to the afflicted by his friend, and withholding it is counted a failure of the fear of God.",
    '6:15': "\"My brethren have dealt deceitfully as a brook.\" The charge is not cruelty but absence when needed.",
    '6:16': "The stream looks fullest when it is frozen. Some comfort is most impressive exactly when it is useless.",
    '6:17': "They run high in the wet season and vanish in the heat. That is the whole indictment of these friends.",
    '6:18': "The caravans turn aside after the water and come to nothing. Bad comfort does not merely fail; it misleads.",
    '6:20': "\"They were confounded because they had hoped.\" The shame lies in having expected something at all.",
    '6:21': "\"For now ye are nothing.\" Job says they are frightened by what they see, and fear is what dried them up.",
    '6:22': "He points out that he asked them for no money and no rescue. He wanted presence, and that was withheld.",
    '6:24': "\"Teach me, and I will hold my tongue.\" He is willing to be shown the sin. Nobody will name one.",
    '6:25': "\"How forcible are right words!\" Job grants the power of true speech and denies that theirs has any.",
    '6:26': "They correct the words of a desperate man as though they were a position he had argued for.",
    '6:27': "The charge is that they would cast lots for an orphan. Argument at this pitch becomes a kind of violence.",
    '6:28': "\"Look upon me.\" He asks them to raise their eyes from their doctrine to his face.",
    '6:29': "He asks them to turn back, and stakes the request on his righteousness still being in the case.",
    '6:30': "Can a man taste the difference between right and wrong? Job insists his palate is not the thing that broke.",
    # ---- Chapter 7 ----
    '7:1': "Life is described as conscripted service, an appointed time rather than a possession.",
    '7:2': "The servant longing for the shadow. What Job wants is the end of the shift, not the wages.",
    '7:3': "Months of vanity are appointed to him. The passive is deliberate: somebody assigned them.",
    '7:4': "At night he waits for morning and by day for night. Suffering wrecks time before it wrecks the body.",
    '7:5': "Worms and broken skin. The book does not spare its reader the physical detail of the trial.",
    '7:6': "Swifter than a weaver's shuttle, and the thread runs out with nothing woven: spent without hope.",
    '7:7': "\"Remember that my life is wind.\" He argues from his own frailty, as though brevity might move God.",
    '7:8': "\"Thine eyes are upon me, and I am not.\" God will look and there will be nobody left to look at.",
    '7:9': "The grave gives nothing back. Job's hope has no resurrection in it yet, which is why this bites.",
    '7:10': "His own house will not know him. What he dreads is being forgotten in the place he belonged.",
    '7:11': "\"Therefore I will not refrain my mouth.\" He decides to speak bitterly, and Scripture records the decision.",
    '7:12': "\"Am I a sea, or a whale?\" He asks why he is guarded like a monster of chaos rather than a man.",
    '7:14': "Dreams and visions are laid to God's account. Where Eliphaz found revelation, Job finds terror.",
    '7:15': "He would sooner be strangled than go on. The book lets the words stand without rebuking them.",
    '7:16': "\"Let me alone\" is the reverse of every prayer for God's attention, and it is still a prayer.",
    '7:17': "\"What is man, that thou shouldest magnify him?\" The psalm's wonder is turned into a complaint of surveillance.",
    '7:18': "Visited every morning, tried every moment. God's constant attention is being felt as pursuit.",
    '7:19': "He asks for the space of swallowing his spittle. The request has shrunk to a second's relief.",
    '7:20': "\"I have sinned; what shall I do unto thee?\" Job never claims sinlessness, only that this is not the bill for it.",
    '7:21': "He asks for pardon and then says it will arrive too late. The plea and the despair are one sentence.",
    # ---- Chapter 8 ----
    '8:2': "Bildad opens with impatience: Job's words are wind. He answers the volume before the content.",
    '8:3': "\"Doth God pervert judgment?\" Unanswerable, and it does not touch anything Job actually said.",
    '8:4': "\"If thy children have sinned\" — he explains the deaths of ten young people as a settled account.",
    '8:5': "The counsel is to seek God early, as though Job's trouble were a matter of insufficient application.",
    '8:6': "\"If thou wert pure and upright\" — the condition already carries the verdict Bildad has reached.",
    '8:7': "A greatly increased latter end is promised. The epilogue grants it, and not for Bildad's reason.",
    '8:8': "His authority is the former age. Bildad does not claim to have thought about any of this himself.",
    '8:9': "\"We are but of yesterday, and know nothing.\" A humble line, used to close an argument rather than open one.",
    '8:10': "The fathers will teach, he says, and what they teach turns out to be precisely what Bildad thinks.",
    '8:11': "The rush cannot grow without mire. A sound observation about plants, offered as a law about men.",
    '8:12': "It withers while still green and uncut. Bildad has a category for sudden ruin, and Job is put in it.",
    '8:13': "\"The hypocrite's hope shall perish.\" The accusation is dropped in as though it were a general truth.",
    '8:14': "A spider's web for a trust. The picture is of a confidence that was never load-bearing.",
    '8:15': "He leans on his house and it does not stand. Bildad is describing the collapse Job has just lived through.",
    '8:16': "Green before the sun and spreading. Even the flourishing gets written into the story of the doomed.",
    '8:18': "\"I have not seen thee\" — the place itself disowns the man. Ruin is pictured as being unremembered.",
    '8:19': "Others grow up out of the same earth and nothing is missed. The replacement is what makes it bitter.",
    '8:20': "\"God will not cast away a perfect man.\" The narrator called Job perfect in verse one, and here he sits.",
    '8:21': "Laughter is promised as the fruit of a repentance Job has no sin to bring to it.",
    '8:22': "The speech ends consigning Job's enemies to shame, when Job's trouble came from no enemy he can name.",
    # ---- Chapter 9 ----
    '9:2': "\"How should man be just with God?\" Job asks the question the whole Bible answers, and gets nothing here.",
    '9:3': "Not one answer in a thousand. He is imagining a courtroom where the questions never run out.",
    '9:4': "Wise in heart and mighty in strength. The two together are what make God impossible to argue with.",
    '9:5': "Mountains removed before they know it. God's power is described as working without notice or consent.",
    '9:7': "He commands the sun and it does not rise. Job can imagine the created order simply withheld.",
    '9:8': "\"Treadeth upon the waves of the sea.\" What terrifies everyone else is a road under God's feet.",
    '9:9': "Arcturus, Orion, Pleiades. The stars men steer by are listed as things God happened to make.",
    '9:10': "Job repeats Eliphaz's own line about unsearchable works and draws the opposite conclusion from it.",
    '9:11': "\"He goeth by me, and I see him not.\" The complaint is not God's absence but his undetectable presence.",
    '9:12': "\"Who will say unto him, What doest thou?\" Job states the fact and plainly wishes it were otherwise.",
    '9:13': "If God does not withdraw his anger, even the proud helpers stoop. No ally is any use in this case.",
    '9:14': "\"How much less shall I answer him?\" He knows that choosing better words would not improve his position.",
    '9:15': "Righteous and still unable to answer, he would sue for mercy from the judge he is trying to oppose.",
    '9:16': "Even a granted hearing would not convince him it had happened. Despair distrusts its own relief.",
    '9:17': "\"Multiplieth my wounds without cause.\" Job says without cause — the very phrase God used in heaven.",
    '9:18': "Not even allowed to take a breath. What he protests is the relentlessness as much as the pain.",
    '9:19': "Strength and judgement both belong to the other side. There is no court and no appointed day.",
    '9:20': "\"If I justify myself, mine own mouth shall condemn me.\" Self-defence before God collapses as it speaks.",
    '9:21': "\"Though I were perfect, yet would I not know my soul.\" He no longer trusts his own reading of himself.",
    '9:22': "\"He destroyeth the perfect and the wicked.\" The sentence the friends cannot allow and the book will not delete.",
    '9:23': "He accuses God of laughing at the trial of the innocent. The charge is kept in Scripture, unretracted.",
    '9:24': "\"The earth is given into the hand of the wicked.\" Job looks at who runs things and cannot square it.",
    '9:25': "Days swifter than a runner, fleeing and seeing no good. Even the shortness of it brings no comfort.",
    '9:27': "He tries deciding to cheer up — the advice he has been given — and reports plainly that it failed.",
    '9:28': "\"I know that thou wilt not hold me innocent.\" The fear is not punishment but a verdict already fixed.",
    '9:30': "Snow water and hands scrubbed clean. No amount of self-cleansing alters a verdict already given.",
    '9:31': "Plunged in the ditch till his own clothes abhor him. He pictures God as the one doing the defiling.",
    '9:32': "\"He is not a man, as I am.\" The obstacle in one line: there is no common ground to meet on.",
    '9:33': "\"Neither is there any daysman betwixt us.\" Job names the missing mediator, and Christians know his name.",
    '9:34': "He asks only that the rod and the dread be lifted enough for him to speak. The fear itself silences him.",
    '9:35': "\"But it is not so with me.\" The chapter ends admitting that the conditions for a fair hearing do not exist.",
    # ---- Chapter 10 ----
    '10:1': "\"I will speak in the bitterness of my soul.\" He announces that what follows is bitter, and says it to God.",
    '10:2': "\"Shew me wherefore thou contendest with me.\" What Job wants is not release but the charge read out.",
    '10:3': "He asks whether God enjoys despising the work of his own hands. The question dares an answer.",
    '10:4': "\"Hast thou eyes of flesh?\" If God does not see as men do, he cannot be mistaking Job for a wicked man.",
    '10:5': "God has no deadline. Job cannot see why an eternal judge would need to hurry a man into the ground.",
    '10:6': "Searching after his sin. The picture is of an investigator determined to turn something up.",
    '10:7': "\"Thou knowest that I am not wicked.\" He appeals to God's knowledge against God's treatment of him.",
    '10:8': "The hands that made him are the hands undoing him. Job will not pretend they are different hands.",
    '10:9': "\"Thou hast made me as the clay.\" He argues from creation: the potter has a stake in the pot.",
    '10:10': "Milk and curd. The making of a body is put in kitchen terms, as something handled with care.",
    '10:11': "Skin, flesh, bones and sinews recited by a man sitting inside a body that is coming apart.",
    '10:12': "Life, favour, and a visitation that preserved his spirit. He grants the past kindness in full.",
    '10:13': "\"These things hast thou hid in thine heart.\" He suspects the kindness was concealing an intention.",
    '10:14': "If he sins he is marked and not acquitted. The fear is a God who keeps records and never closes them.",
    '10:15': "Wicked or righteous, he cannot lift his head. The categories the friends live by have stopped working.",
    '10:16': "Hunted like a lion and made a spectacle. Job reads his suffering as attention rather than neglect.",
    '10:17': "Fresh witnesses, renewed indignation, changes and war. The trouble is described as arriving in waves.",
    '10:18': "\"Wherefore then hast thou brought me forth out of the womb?\" The quarrel is with having been made at all.",
    '10:20': "He asks for a little comfort, and the way he asks for it is by asking God to leave him alone.",
    '10:22': "Darkness where even the light is as darkness. The chapter ends with no order left in the picture.",
    # ---- Chapter 11 ----
    '11:2': "Zophar treats the length of Job's speech as the fault. A man full of talk cannot be in the right.",
    '11:3': "He calls Job's grief lies and mockery. The third friend arrives with the accusation already made.",
    '11:4': "He quotes Job as claiming to be clean in God's eyes, which is not a claim Job has made.",
    '11:5': "\"Oh that God would speak.\" The wish is granted in chapter 38, and it goes against Zophar.",
    '11:6': "\"God exacteth of thee less than thine iniquity deserveth.\" The cruellest line in the book, said kindly.",
    '11:7': "\"Canst thou by searching find out God?\" A great question, asked by a man certain he has the answer.",
    '11:8': "Higher than heaven, deeper than hell. He preaches God's unsearchableness to prove a point about Job.",
    '11:10': "If God cuts off and shuts up, who can hinder him? The power is real; the application to Job is not.",
    '11:11': "\"He knoweth vain men.\" Zophar assumes God's knowledge will confirm Zophar's reading of the case.",
    '11:12': "A vain man and a wild ass's colt. The argument has arrived at insult dressed up as proverb.",
    '11:13': "Prepare the heart and stretch out the hands. The cure offered is repentance for an unnamed sin.",
    '11:14': "Put iniquity far away. Zophar cannot say which iniquity, and does not think he needs to.",
    '11:15': "\"Lift up thy face without spot.\" The clear conscience he describes is real, and not for sale at his price.",
    '11:16': "Misery remembered as waters that pass away — a genuine mercy, promised on a condition that does not apply.",
    '11:17': "An age clearer than the noonday. Zophar's language is loveliest exactly where his theology fails.",
    '11:18': "Secure, because there is hope. The security is made to rest on the sufferer's own dealings with God.",
    '11:19': "None to make him afraid, and many seeking his favour. Restoration is pitched partly as regained standing.",
    '11:20': "The speech closes on the wicked's hope failing, a last look at where Zophar thinks Job is standing.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:2': "\"Wisdom shall die with you.\" Job answers the counsel with sarcasm, and the book lets the sarcasm stand.",
    '12:3': "\"Who knoweth not such things as these?\" What the friends offer as insight he has known all along.",
    '12:4': "The upright man laughed to scorn. Part of what Job is suffering is the company sitting in front of him.",
    '12:5': "\"A lamp despised in the thought of him that is at ease.\" Contempt for the falling comes easily to the comfortable.",
    '12:6': "Robbers' tents prosper. Job keeps putting in front of the friends the one fact their theory cannot hold.",
    '12:7': "\"Ask now the beasts, and they shall teach thee.\" Their doctrine is so elementary the animals could recite it.",
    '12:8': "Earth and fish called as teachers. Job widens the classroom to show how little instruction he needs.",
    '12:9': "\"The hand of the LORD hath wrought this.\" He grants what everyone agrees on and denies the conclusion drawn from it.",
    '12:10': "Every living soul and every human breath in one hand. The scope is total, and here that is the problem.",
    '12:11': "\"Doth not the ear try words?\" Job claims the right to test what he is told rather than swallow it.",
    '12:12': "Wisdom with the ancient. He states the friends' assumption plainly, one verse before relocating it.",
    '12:13': "With God is wisdom and strength. The subject moves from old men's experience to somewhere harder to quote.",
    '12:14': "What God breaks down stays broken. Job describes power with no appeal from it, and he means his own house.",
    '12:15': "Withheld waters and overturned earth. One hand sends drought and flood, and neither is a verdict on anybody.",
    '12:16': "\"The deceived and the deceiver are his.\" Both sides of a fraud answer to God, which ruins any simple sorting.",
    '12:17': "Counsellors led away spoiled, judges made fools. Job aims the hymn squarely at the class his friends speak from.",
    '12:18': "Kings unbound, then girded again. Rank is fastened and loosed by someone outside the arrangement.",
    '12:20': "Speech taken from the trusty, understanding from the aged. The credentials the friends lean on are revocable.",
    '12:21': "Contempt poured upon princes. Job's God is not the guarantor of the settled order but its unsettling.",
    '12:22': "\"He discovereth deep things out of darkness.\" The one line in the hymn that could work in Job's favour.",
    '12:23': "Nations increased and destroyed by the same hand. History is not being read here as a record of deserving.",
    '12:24': "Leaders' hearts taken away, left wandering where there is no way. The wise are included among the lost.",
    '12:25': "Groping in the dark, staggering like drunken men. The chapter ends with wisdom itself put out like a light.",
    # ---- Chapter 13 ----
    '13:1': "\"Mine eye hath seen all this.\" Job sets what he has lived against what they have been taught.",
    '13:3': "\"I desire to reason with God.\" He would rather argue with God than be consoled by men.",
    '13:4': "\"Physicians of no value.\" They came to heal him, and he names the treatment as quackery.",
    '13:5': "He rates their silence above their theology, and says so to their faces.",
    '13:6': "Reasoning and pleadings. Job speaks like a man in court, not a patient waiting for a diagnosis.",
    '13:7': "\"Will ye speak wickedly for God?\" Defending God with falsehood is itself named as sin.",
    '13:8': "\"Will ye contend for God?\" Taking God's side in an argument is not the same as being on it.",
    '13:9': "He asks how their case would look if God searched them out. In 42:7 that is exactly what happens.",
    '13:10': "Secret partiality will be reproved. Flattering the judge is still the corruption of a court.",
    '13:11': "\"Shall not his excellency make you afraid?\" The man accused of irreverence is the one urging fear of God.",
    '13:12': "Remembrances of ashes, bodies of clay. Their proverbs are as mortal as the men reciting them.",
    '13:13': "\"Let come on me what will.\" He accepts the risk of speaking before knowing what speaking will cost.",
    '13:14': "Flesh in his teeth, life in his hand. Job knows that pressing his case may finish him.",
    '13:15': "\"Though he slay me, yet will I trust in him.\" The book's highest word of trust, spoken in the middle of a lawsuit.",
    '13:16': "\"He also shall be my salvation.\" His confidence is that no hypocrite would dare come this close.",
    '13:18': "\"I know that I shall be justified.\" He expects acquittal from the same God he says is hunting him.",
    '13:19': "If he holds his tongue he dies. Speaking is not defiance here but the last breath he has.",
    '13:20': "Two conditions before he can face God. A frightened man states what he needs in order to speak.",
    '13:21': "Hand withdrawn, dread lifted. What he asks for first is not healing but room enough to talk.",
    '13:22': "\"Then call thou, and I will answer.\" He offers God either part, and God eventually takes the first.",
    '13:23': "\"Make me to know my transgression.\" Job asks for the charge sheet the friends keep assuring him exists.",
    '13:24': "\"Holdest me for thine enemy?\" The hidden face wounds worse than the affliction that came with it.",
    '13:25': "A driven leaf, dry stubble. He asks why such force is aimed at something already this weightless.",
    '13:26': "Iniquities of his youth. He suspects God of reaching back for old material to justify present treatment.",
    '13:27': "Feet in the stocks, a print set on his heels. Being watched this closely is itself part of the punishment.",
    '13:28': "A rotten thing, a moth-eaten garment. The speech closes with a man describing himself as clothing coming apart.",
    # ---- Chapter 14 ----
    '14:1': "\"Of few days, and full of trouble.\" Job widens his own case until it describes everyone born.",
    '14:2': "A flower cut down, a shadow that does not continue. Brevity stated with no consoling turn at the end.",
    '14:3': "\"Dost thou open thine eyes upon such an one?\" The grievance is that God takes so short-lived a thing to court.",
    '14:4': "\"Who can bring a clean thing out of an unclean? not one.\" Job grants inherited uncleanness and still denies the charge.",
    '14:5': "Days determined, bounds appointed. The limit Job resents is also the limit Satan was held to.",
    '14:6': "Even a hired man is given the end of his day. Job asks only to be let alone long enough to finish.",
    '14:7': "\"There is hope of a tree.\" The chapter turns on a hope that cut timber has and a man does not.",
    '14:9': "\"Through the scent of water it will bud.\" A stump that looks dead needs only the smell of rain.",
    '14:10': "\"Man giveth up the ghost, and where is he?\" The question is left open, and the chapter cannot close it.",
    '14:12': "Not awake till the heavens be no more. Job states the limit in words that leave a crack in it.",
    '14:13': "Hidden in the grave till the wrath is past, then remembered. A resurrection wished for rather than claimed.",
    '14:14': "\"If a man die, shall he live again?\" Asked as a question, and answered only by his willingness to wait.",
    '14:15': "\"Thou wilt have a desire to the work of thine hands.\" He imagines God missing him, and it steadies him.",
    '14:16': "Steps numbered, sin watched. The attention that read as care one verse ago has turned into surveillance.",
    '14:17': "Transgression sealed up in a bag. Sin kept on file rather than dealt with is the fear underneath.",
    '14:18': "Mountains fall, rocks are removed. Job builds his despair out of the most solid things he can find.",
    '14:19': "\"Thou destroyest the hope of man.\" Water wears stone slowly, and he says hope is worn down the same way.",
    '14:20': "Countenance changed, then sent away. Death is pictured as dismissal by one with authority to dismiss.",
    '14:21': "Sons come to honour or are brought low and he knows nothing of it. The dead are shut out of their children's lives.",
    '14:22': "\"His flesh upon him shall have pain.\" The chapter ends on the one thing Job is sure outlasts him: his own hurt.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:2': "\"Fill his belly with the east wind.\" Eliphaz opens the second round by calling Job's grief hot air.",
    '15:3': "Unprofitable talk. The test applied to Job's words is whether they do good, not whether they are true.",
    '15:4': "Casting off fear, restraining prayer. The charge has hardened since chapter four into open accusation.",
    '15:5': "\"Thou choosest the tongue of the crafty.\" What a tortured man says is treated as evidence of cunning.",
    '15:6': "\"Thine own mouth condemneth thee, and not I.\" Eliphaz claims only to be reading back what Job supplied.",
    '15:7': "\"Art thou the first man that was born?\" Sarcasm about presumption, from a man about to claim the ancients.",
    '15:8': "\"Hast thou heard the secret of God?\" The reader has heard it, in chapter one, and it goes against Eliphaz.",
    '15:9': "\"What knowest thou, that we know not?\" The argument has become a contest over who is better informed.",
    '15:10': "Grayheaded men on their side. Age is produced as evidence, since the facts of the case are not.",
    '15:11': "\"Are the consolations of God small with thee?\" He identifies his own counsel with the comfort of God.",
    '15:12': "A heart carried away, winking eyes. Eliphaz reads Job's agitation as contempt rather than as pain.",
    '15:13': "\"Thou turnest thy spirit against God.\" The real charge now is not Job's past but Job's words.",
    '15:14': "\"What is man, that he should be clean?\" True of everyone, and no help at all in deciding this case.",
    '15:15': "Not even the heavens are clean in his sight. The bar is set so high that no man's innocence can be discussed.",
    '15:16': "Man drinking iniquity like water. A doctrine of universal corruption standing in for missing evidence.",
    '15:18': "\"Which wise men have told from their fathers.\" The authority produced is inherited teaching, not the facts.",
    '15:19': "The land theirs alone, no stranger passing among them. Unmixed tradition is offered as proof of soundness.",
    '15:20': "The wicked man in pain all his days. Eliphaz's system has no room for a villain who does well.",
    '15:21': "\"In prosperity the destroyer shall come upon him.\" Even the good years are read backwards as dread.",
    '15:22': "He does not believe he will come out of the darkness. Eliphaz describes Job's despair and files it under guilt.",
    '15:23': "Wandering abroad for bread. The destitution described is Job's now, and was not his when he was upright.",
    '15:24': "Anguish prevailing like a king ready for battle. Fine poetry doing the work of an unproven accusation.",
    '15:25': "\"He stretcheth out his hand against God.\" Here the general portrait stops pretending not to be about Job.",
    '15:26': "Charging with the thick bosses of his shield. Job's protest is being read as an assault on God.",
    '15:27': "Collops of fat on his flanks. Prosperity itself becomes evidence of the guilt that supposedly undoes it.",
    '15:28': "Desolate cities, houses ready to become heaps. The wicked are pictured living where judgement already fell.",
    '15:29': "\"He shall not be rich, neither shall his substance continue.\" Stated as a rule, with this book as the exception.",
    '15:31': "\"Vanity shall be his recompence.\" A sound proverb, aimed at a man who has trusted nothing of the kind.",
    '15:32': "Cut off before his time, the branch not green. The wicked die early; Job dies old and full of days in 42:17.",
    '15:33': "Unripe grapes shaken off, olive blossom cast. Dead children are worked into the portrait with Job's in view.",
    '15:34': "Congregations of hypocrites, tents of bribery. The speech has arrived at crimes it never specifies.",
    '15:35': "\"They conceive mischief, and bring forth vanity.\" Eliphaz closes by naming what he thinks Job is carrying.",
    # ---- Chapter 16 ----
    '16:2': "\"Miserable comforters are ye all.\" The verdict on the comforters, given by the man they came to comfort.",
    '16:3': "\"Shall vain words have an end?\" Job hands their complaint about endless speeches straight back.",
    '16:4': "\"I also could speak as ye do.\" Their wisdom is easy, and easiest for whoever is not the one suffering.",
    '16:5': "He says he would have strengthened them instead, which is a fair description of the job they were sent to do.",
    '16:6': "Speaking does not ease the grief and keeping quiet does not either. Both options have already failed.",
    '16:7': "\"Thou hast made desolate all my company.\" Mid-argument with men, he turns and addresses God.",
    '16:8': "Wrinkles and leanness rising up as witnesses. His wasted body is read by everyone as testimony against him.",
    '16:9': "\"He teareth me in his wrath, who hateth me.\" Job says God hates him, and the sentence is left in the book.",
    '16:10': "Gaping mouths, a struck cheek, a gathering crowd. Human contempt arrives on top of the affliction.",
    '16:11': "\"God hath delivered me to the ungodly.\" Job's picture of a handing over is nearer chapter one than he knows.",
    '16:12': "\"Set me up for his mark.\" He calls himself a target, which is what the accuser's challenge made him.",
    '16:13': "Archers round about, gall poured on the ground. The violence is described as aimed, not accidental.",
    '16:14': "\"He runneth upon me like a giant.\" Breach upon breach — what he protests is the pace, with no gap to recover.",
    '16:15': "Sackcloth sewed to his skin. Mourning has stopped being a rite he performs and become the state he lives in.",
    '16:16': "A face foul with weeping. Job is nowhere stoical in this book, and is nowhere faulted for that.",
    '16:17': "\"Not for any injustice in mine hands.\" He holds his innocence and his ruin together without resolving them.",
    '16:18': "\"O earth, cover not thou my blood.\" He asks that his death stand as a killing still waiting for justice.",
    '16:19': "\"My witness is in heaven.\" While calling God his attacker he looks to heaven for his defence.",
    '16:20': "Friends scorning, tears poured out to God. The only one left to weep to is the one he is accusing.",
    '16:21': "\"O that one might plead for a man with God.\" The longing is for an advocate on ordinary neighbourly terms.",
    '16:22': "A few years, then the way from which there is no return. He wants his hearing before the time runs out.",
    # ---- Chapter 17 ----
    '17:1': "\"The graves are ready for me.\" He speaks as a man whose burial is arranged and merely waiting.",
    '17:3': "He asks God to put up the surety for a case against God. There is no one else to strike hands with him.",
    '17:4': "He says God has hidden understanding from the friends, so their confident wisdom will not be honoured.",
    '17:5': "Flattery to friends costs a man's children. Job warns that saying the agreeable thing carries a price.",
    '17:6': "\"He hath made me also a byword of the people.\" The most honoured man in the east is now the local proverb.",
    '17:7': "Eyes dim with sorrow, limbs like a shadow. Grief is reported as physical wasting rather than as mood.",
    '17:8': "Upright men astonished at this. Job expects his case to scandalise anyone who looks at it honestly.",
    '17:9': "\"The righteous also shall hold on his way.\" A plain word of endurance, dropped into the middle of despair.",
    '17:10': "\"I cannot find one wise man among you.\" He invites another round while telling them what the last one proved.",
    '17:11': "Days past, purposes broken off. He is mourning his plans as well as his children and his cattle.",
    '17:12': "Night called day, light cut short by darkness. He accuses the friends of renaming his darkness for him.",
    '17:13': "\"I have made my bed in the darkness.\" Hope has narrowed to a hope about where he will be lying.",
    '17:14': "Corruption for a father, the worm for mother and sister. The family he has left is named in grave terms.",
    '17:15': "\"Where is now my hope?\" Asked and not answered, two chapters before he says he knows his redeemer lives.",
    '17:16': "Bars of the pit, rest together in the dust. The speech ends with his hope going down into the grave with him.",
})
