#!/usr/bin/env python3
"""Written one-line takeaways for Job 23-42."""

TAKEAWAYS = {
    # ---- Chapter 23 ----
    '23:2': "He says his groaning understates the blow. The complaint is smaller than the thing complained of.",
    '23:3': "What he wants is not relief but an address. The absence of God hurts worse than the sores.",
    '23:4': "He is not asking for pity. He wants a hearing, with his case set out and his arguments ready.",
    '23:5': "He wants to hear the answer as much as to make the speech. Silence is what he cannot bear.",
    '23:6': "He does not expect to be overpowered. He expects God to hand him the strength to plead.",
    '23:7': "The same God is judge and the one he hopes will acquit him. Job has nowhere else to appeal.",
    '23:8': "Forward and backward, and nothing. The search is methodical and still comes up empty.",
    '23:9': "\"He hideth himself.\" The absence is not an accident of Job's looking but something God is doing.",
    '23:10': "\"He knoweth the way that I take.\" Job cannot locate God; he is certain he himself is located.",
    '23:11': "The record he offers is not of great deeds but of not turning aside.",
    '23:12': "He valued God's words above his necessary food — and that is exactly the man now sitting in ashes.",
    '23:13': "That God cannot be turned is usually a comfort. Here it is the reason Job is afraid.",
    '23:14': "\"Many such things are with him.\" What frightens Job is not this blow but the store behind it.",
    '23:15': "He has spent the chapter asking to find God, and admits that finding him is what terrifies him.",
    '23:16': "Even the softening of his heart is credited to God. Job will not attribute his fear to himself.",
    '23:17': "His grievance is that he was left alive to see the dark, not that the dark came.",
    # ---- Chapter 24 ----
    '24:1': "The complaint is about the court calendar: God knows the times, and the assize never seems to be called.",
    '24:2': "Moving a boundary stone is theft that leaves no visible wound, which is why it works.",
    '24:3': "They take a pledge from people with nothing to spare. The cruelty is transacted legally.",
    '24:4': "The poor are pushed off the public road, and then hide — driven out and blamed for vanishing.",
    '24:5': "The destitute forage like desert animals, and the wilderness feeds their children better than the town does.",
    '24:6': "They work the wicked man's harvest. The fields they labour in are never their own.",
    '24:7': "Nakedness here is not immodesty but exposure. Men sleep in the cold because a coat was taken as security.",
    '24:8': "\"Embrace the rock for want of a shelter\" — the picture is of holding on to something that gives nothing back.",
    '24:9': "A child taken from the breast to settle a debt. Job names the cruelty nobody in the city calls a crime.",
    '24:10': "They carry the sheaf and go hungry. Proximity to grain is not access to it.",
    '24:11': "Pressing oil and treading wine while thirsty. The worker is kept from the very thing he makes.",
    '24:12': "\"Yet God layeth not folly to them.\" This is the scandal of the chapter, said flatly and left standing.",
    '24:13': "Their quarrel is with light itself. They do not merely break the rules; they prefer the dark.",
    '24:14': "The murderer keeps working hours, rising with the sun to kill the poor and turning thief at night.",
    '24:15': "\"No eye shall see me.\" Adultery is here a problem of arithmetic about witnesses.",
    '24:16': "The house was marked in daylight. The crime of the night was planned in the ordinary afternoon.",
    '24:17': "For men who work by night, morning is the terror. Exposure is the thing they fear, not judgement.",
    '24:18': "The curse pronounced on them is that they are light, swift, carried off — never settled anywhere.",
    '24:19': "Snow water vanishes in heat with nothing left behind. That, Job says, is what the grave does to sinners.",
    '24:20': "Even the womb forgets him, and the worm finds him sweet. Being unremembered is counted as the punishment.",
    '24:21': "He preys on the woman with no son to defend her. Vulnerability, not wealth, is what draws him.",
    '24:22': "The strong are not safe either. A man of this kind rises, and nobody's life is certain.",
    '24:23': "God's eyes are on their ways even while he leaves them in safety. Job grants the watching and not the acting.",
    '24:24': "The concession is real but small: they do fall — after a little while, and like every other man.",
    '24:25': "He ends by daring anyone to call him a liar. The friends have no answer and Bildad changes the subject.",
    # ---- Chapter 25 ----
    '25:1': "Bildad's last speech runs six verses. The friends have said everything they have and it was not enough.",
    '25:2': "The peace God makes in his high places is order imposed, not agreement reached.",
    '25:3': "His light rises on everyone, which Bildad means as threat rather than mercy.",
    '25:4': "\"How can man be justified with God?\" The book's central question, used here to close a conversation.",
    '25:5': "Compared to God the moon does not even shine. The scale is set so high that distinctions below vanish.",
    '25:6': "Calling man a worm ends the argument by ending the man. Job's particular case is dissolved into the species.",
    # ---- Chapter 26 ----
    '26:2': "\"How hast thou helped him that is without power?\" Job measures comfort by what it actually did.",
    '26:3': "Advice delivered to a man who cannot use it is not counsel but performance.",
    '26:4': "He asks whose spirit was speaking. The friends' words were borrowed and Job has noticed.",
    '26:5': "Even the dead under the waters are not out of God's jurisdiction.",
    '26:6': "The grave has no covering before God. There is no place to be hidden, which cuts both ways.",
    '26:7': "\"Hangeth the earth upon nothing.\" The world is held up by nothing visible at all.",
    '26:8': "Water is bound in cloud and the cloud does not tear. The restraint is the marvel, not the storm.",
    '26:9': "God spreads a cloud over his own throne. The hiding Job complained of is deliberate policy.",
    '26:10': "A boundary drawn on the water where light ends and dark begins. Even the sea is given an edge.",
    '26:11': "The pillars of heaven tremble at a rebuke. What shakes the world is God's voice, not his hand.",
    '26:12': "The sea and the proud are divided by the same power — creation and judgement described as one act.",
    '26:13': "The serpent is not God's rival here but God's handiwork. The chaos monster was made.",
    '26:14': "All this is the whisper. Job says the thunder of God's power has not yet been heard — and in chapter 38 it is.",
    # ---- Chapter 27 ----
    '27:2': "He swears by the life of the God he is accusing. Job's complaint never becomes unbelief.",
    '27:3': "The breath he uses to protest is the breath God is lending him, and he says so.",
    '27:4': "He will not buy relief with a false confession. Lying about himself would be the one real sin here.",
    '27:5': "\"God forbid that I should justify you.\" Agreeing with his comforters would be a lie about God as well.",
    '27:6': "His conscience is clear, and he refuses to let three confident men talk him out of it.",
    '27:7': "The worst fate Job can wish an enemy is to be counted among the wicked — the very charge laid on him.",
    '27:8': "The hypocrite may gain everything and still have nothing when his soul is required of him.",
    '27:9': "Job has been crying out unanswered for chapters, and still holds that God hears the honest man.",
    '27:10': "\"Will he delight himself in the Almighty?\" The test the accuser proposed in chapter 1, put by Job himself.",
    '27:11': "He offers to teach them the doctrine they came to teach him. The pupil has outgrown the tutors.",
    '27:12': "They have seen the world with their own eyes and go on describing one that does not exist.",
    '27:13': "Job now recites the friends' doctrine of the wicked man's portion — and it never once fits his own case.",
    '27:14': "Numerous children are the standard sign of blessing. Here they are numbered for the sword.",
    '27:15': "\"His widows shall not weep.\" The sharpest loss described is that nobody is sorry.",
    '27:16': "Silver heaped like dust and clothes stacked like clay — wealth measured by the shovelful.",
    '27:17': "He prepares it and someone else wears it. The wicked man's labour is unknowingly done for the just.",
    '27:18': "A moth's shell and a watchman's booth: both built to stand one season and then be abandoned.",
    '27:19': "He lies down rich and opens his eyes to nothing. The whole reversal happens overnight.",
    '27:20': "Terror arrives like flood water — not at a door to be barred, but from every side at once.",
    '27:21': "The east wind takes him out of his place, and a place is precisely what such a man thought he had.",
    '27:22': "\"He would fain flee out of his hand.\" The flight is described, not the escape.",
    '27:23': "The crowd claps him out. Public opinion follows the fall rather than seeing it coming.",
    # ---- Chapter 28 ----
    '28:1': "The poem begins with what men are good at: there is a vein for silver and they know how to find it.",
    '28:2': "Iron and copper are dug and smelted. Human competence is granted in full before it is measured.",
    '28:3': "\"He setteth an end to darkness.\" A man with a lamp pushes the dark back to the edge of the world.",
    '28:4': "Shafts sunk far from anywhere, and the miner swings in the dark where no foot has walked.",
    '28:5': "Bread grows on the surface while fire is turned up underneath. The same earth serves both ways.",
    '28:6': "Sapphire and gold dust lie in the rock, and men have learned exactly where to look for them.",
    '28:7': "No bird of prey has seen this path. The sharpest eye in creation has been outdone by a miner.",
    '28:8': "Not even the lion walks there. Man goes where the strongest animal does not.",
    '28:9': "He overturns mountains by the roots. The verse credits human power with something close to violence.",
    '28:10': "\"His eye seeth every precious thing.\" What can be seen and priced, man will find.",
    '28:11': "He dams the floods and brings hidden things to light — every hidden thing, it seems, but one.",
    '28:12': "\"But where shall wisdom be found?\" Eleven verses of competence, and the question stops all of it.",
    '28:13': "Man does not even know what wisdom would cost. He cannot begin to bid for it.",
    '28:14': "The deep and the sea are asked directly and both answer that it is not there.",
    '28:15': "Wisdom is not expensive. It is the sort of thing that cannot be bought at any figure.",
    '28:16': "Ophir gold, onyx, sapphire — the best that trade can reach, and the comparison still fails.",
    '28:17': "The list grows and the answer stays the same. Value that can be weighed is a different kind of value.",
    '28:18': "Coral and pearls are not even worth naming in the conversation. The scale is not a high one but another one.",
    '28:19': "The catalogue of treasure ends where it started: none of it buys the one thing worth having.",
    '28:20': "The question is asked a second time, word for word. The poem refuses to move on from it.",
    '28:21': "Hidden from every living eye, and from the birds that saw further than men. The search has run out of searchers.",
    '28:22': "Destruction and Death have only heard the rumour. Even the grave can report nothing but hearsay.",
    '28:23': "God knows the way to it, not merely the place. Wisdom is reached by a road only he has travelled.",
    '28:24': "He sees to the ends of the earth. Wisdom belongs to the one who can take in the whole at once.",
    '28:25': "Weighing the wind and measuring the waters — wisdom is what it took to build the world's proportions.",
    '28:26': "Rain and lightning run by decree. What looks like weather is a rule laid down.",
    '28:27': "He saw it, declared it, prepared it, searched it out. Even God is described as taking trouble over wisdom.",
    '28:28': "Man is not given the mine but the entrance: fear the LORD, depart from evil. That much is handed over plainly.",
}
