#!/usr/bin/env python3
"""Written one-line takeaways for Job 23-42."""

TAKEAWAYS = {
    # ---- Chapter 23 ----
    '23:2': "He says his groaning understates the blow. The complaint is smaller than the thing complained of.",
    '23:3': "What he wants is not relief but an address. The absence of God hurts worse than the sores.",
    '23:4': "He is not asking for pity. He wants a hearing, with his case set out and his arguments ready.",
    '23:5': "He wants to hear the answer as much as to make the speech. Silence is what he cannot bear.",
    '23:6': "He does not expect to be overpowered. He expects God to hand him the strength to plead.",
    '23:7': "The same God is judge and the one he hopes will acquit him. Job has nowhere else to appeal.",
    '23:8': "Forward and backward, and nothing. The search is methodical and still comes up empty.",
    '23:9': "\"He hideth himself.\" The absence is not an accident of Job's looking but something God is doing.",
    '23:10': "\"He knoweth the way that I take.\" Job cannot locate God; he is certain he himself is located.",
    '23:11': "The record he offers is not of great deeds but of not turning aside.",
    '23:12': "He valued God's words above his necessary food — and that is exactly the man now sitting in ashes.",
    '23:13': "That God cannot be turned is usually a comfort. Here it is the reason Job is afraid.",
    '23:14': "\"Many such things are with him.\" What frightens Job is not this blow but the store behind it.",
    '23:15': "He has spent the chapter asking to find God, and admits that finding him is what terrifies him.",
    '23:16': "Even the softening of his heart is credited to God. Job will not attribute his fear to himself.",
    '23:17': "His grievance is that he was left alive to see the dark, not that the dark came.",
    # ---- Chapter 24 ----
    '24:1': "The complaint is about the court calendar: God knows the times, and the assize never seems to be called.",
    '24:2': "Moving a boundary stone is theft that leaves no visible wound, which is why it works.",
    '24:3': "They take a pledge from people with nothing to spare. The cruelty is transacted legally.",
    '24:4': "The poor are pushed off the public road, and then hide — driven out and blamed for vanishing.",
    '24:5': "The destitute forage like desert animals, and the wilderness feeds their children better than the town does.",
    '24:6': "They work the wicked man's harvest. The fields they labour in are never their own.",
    '24:7': "Nakedness here is not immodesty but exposure. Men sleep in the cold because a coat was taken as security.",
    '24:8': "\"Embrace the rock for want of a shelter\" — the picture is of holding on to something that gives nothing back.",
    '24:9': "A child taken from the breast to settle a debt. Job names the cruelty nobody in the city calls a crime.",
    '24:10': "They carry the sheaf and go hungry. Proximity to grain is not access to it.",
    '24:11': "Pressing oil and treading wine while thirsty. The worker is kept from the very thing he makes.",
    '24:12': "\"Yet God layeth not folly to them.\" This is the scandal of the chapter, said flatly and left standing.",
    '24:13': "Their quarrel is with light itself. They do not merely break the rules; they prefer the dark.",
    '24:14': "The murderer keeps working hours, rising with the sun to kill the poor and turning thief at night.",
    '24:15': "\"No eye shall see me.\" Adultery is here a problem of arithmetic about witnesses.",
    '24:16': "The house was marked in daylight. The crime of the night was planned in the ordinary afternoon.",
    '24:17': "For men who work by night, morning is the terror. Exposure is the thing they fear, not judgement.",
    '24:18': "The curse pronounced on them is that they are light, swift, carried off — never settled anywhere.",
    '24:19': "Snow water vanishes in heat with nothing left behind. That, Job says, is what the grave does to sinners.",
    '24:20': "Even the womb forgets him, and the worm finds him sweet. Being unremembered is counted as the punishment.",
    '24:21': "He preys on the woman with no son to defend her. Vulnerability, not wealth, is what draws him.",
    '24:22': "The strong are not safe either. A man of this kind rises, and nobody's life is certain.",
    '24:23': "God's eyes are on their ways even while he leaves them in safety. Job grants the watching and not the acting.",
    '24:24': "The concession is real but small: they do fall — after a little while, and like every other man.",
    '24:25': "He ends by daring anyone to call him a liar. The friends have no answer and Bildad changes the subject.",
    # ---- Chapter 25 ----
    '25:1': "Bildad's last speech runs six verses. The friends have said everything they have and it was not enough.",
    '25:2': "The peace God makes in his high places is order imposed, not agreement reached.",
    '25:3': "His light rises on everyone, which Bildad means as threat rather than mercy.",
    '25:4': "\"How can man be justified with God?\" The book's central question, used here to close a conversation.",
    '25:5': "Compared to God the moon does not even shine. The scale is set so high that distinctions below vanish.",
    '25:6': "Calling man a worm ends the argument by ending the man. Job's particular case is dissolved into the species.",
    # ---- Chapter 26 ----
    '26:2': "\"How hast thou helped him that is without power?\" Job measures comfort by what it actually did.",
    '26:3': "Advice delivered to a man who cannot use it is not counsel but performance.",
    '26:4': "He asks whose spirit was speaking. The friends' words were borrowed and Job has noticed.",
    '26:5': "Even the dead under the waters are not out of God's jurisdiction.",
    '26:6': "The grave has no covering before God. There is no place to be hidden, which cuts both ways.",
    '26:7': "\"Hangeth the earth upon nothing.\" The world is held up by nothing visible at all.",
    '26:8': "Water is bound in cloud and the cloud does not tear. The restraint is the marvel, not the storm.",
    '26:9': "God spreads a cloud over his own throne. The hiding Job complained of is deliberate policy.",
    '26:10': "A boundary drawn on the water where light ends and dark begins. Even the sea is given an edge.",
    '26:11': "The pillars of heaven tremble at a rebuke. What shakes the world is God's voice, not his hand.",
    '26:12': "The sea and the proud are divided by the same power — creation and judgement described as one act.",
    '26:13': "The serpent is not God's rival here but God's handiwork. The chaos monster was made.",
    '26:14': "All this is the whisper. Job says the thunder of God's power has not yet been heard — and in chapter 38 it is.",
    # ---- Chapter 27 ----
    '27:2': "He swears by the life of the God he is accusing. Job's complaint never becomes unbelief.",
    '27:3': "The breath he uses to protest is the breath God is lending him, and he says so.",
    '27:4': "He will not buy relief with a false confession. Lying about himself would be the one real sin here.",
    '27:5': "\"God forbid that I should justify you.\" Agreeing with his comforters would be a lie about God as well.",
    '27:6': "His conscience is clear, and he refuses to let three confident men talk him out of it.",
    '27:7': "The worst fate Job can wish an enemy is to be counted among the wicked — the very charge laid on him.",
    '27:8': "The hypocrite may gain everything and still have nothing when his soul is required of him.",
    '27:9': "Job has been crying out unanswered for chapters, and still holds that God hears the honest man.",
    '27:10': "\"Will he delight himself in the Almighty?\" The test the accuser proposed in chapter 1, put by Job himself.",
    '27:11': "He offers to teach them the doctrine they came to teach him. The pupil has outgrown the tutors.",
    '27:12': "They have seen the world with their own eyes and go on describing one that does not exist.",
    '27:13': "Job now recites the friends' doctrine of the wicked man's portion — and it never once fits his own case.",
    '27:14': "Numerous children are the standard sign of blessing. Here they are numbered for the sword.",
    '27:15': "\"His widows shall not weep.\" The sharpest loss described is that nobody is sorry.",
    '27:16': "Silver heaped like dust and clothes stacked like clay — wealth measured by the shovelful.",
    '27:17': "He prepares it and someone else wears it. The wicked man's labour is unknowingly done for the just.",
    '27:18': "A moth's shell and a watchman's booth: both built to stand one season and then be abandoned.",
    '27:19': "He lies down rich and opens his eyes to nothing. The whole reversal happens overnight.",
    '27:20': "Terror arrives like flood water — not at a door to be barred, but from every side at once.",
    '27:21': "The east wind takes him out of his place, and a place is precisely what such a man thought he had.",
    '27:22': "\"He would fain flee out of his hand.\" The flight is described, not the escape.",
    '27:23': "The crowd claps him out. Public opinion follows the fall rather than seeing it coming.",
    # ---- Chapter 28 ----
    '28:1': "The poem begins with what men are good at: there is a vein for silver and they know how to find it.",
    '28:2': "Iron and copper are dug and smelted. Human competence is granted in full before it is measured.",
    '28:3': "\"He setteth an end to darkness.\" A man with a lamp pushes the dark back to the edge of the world.",
    '28:4': "Shafts sunk far from anywhere, and the miner swings in the dark where no foot has walked.",
    '28:5': "Bread grows on the surface while fire is turned up underneath. The same earth serves both ways.",
    '28:6': "Sapphire and gold dust lie in the rock, and men have learned exactly where to look for them.",
    '28:7': "No bird of prey has seen this path. The sharpest eye in creation has been outdone by a miner.",
    '28:8': "Not even the lion walks there. Man goes where the strongest animal does not.",
    '28:9': "He overturns mountains by the roots. The verse credits human power with something close to violence.",
    '28:10': "\"His eye seeth every precious thing.\" What can be seen and priced, man will find.",
    '28:11': "He dams the floods and brings hidden things to light — every hidden thing, it seems, but one.",
    '28:12': "\"But where shall wisdom be found?\" Eleven verses of competence, and the question stops all of it.",
    '28:13': "Man does not even know what wisdom would cost. He cannot begin to bid for it.",
    '28:14': "The deep and the sea are asked directly and both answer that it is not there.",
    '28:15': "Wisdom is not expensive. It is the sort of thing that cannot be bought at any figure.",
    '28:16': "Ophir gold, onyx, sapphire — the best that trade can reach, and the comparison still fails.",
    '28:17': "The list grows and the answer stays the same. Value that can be weighed is a different kind of value.",
    '28:18': "Coral and pearls are not even worth naming in the conversation. The scale is not a high one but another one.",
    '28:19': "The catalogue of treasure ends where it started: none of it buys the one thing worth having.",
    '28:20': "The question is asked a second time, word for word. The poem refuses to move on from it.",
    '28:21': "Hidden from every living eye, and from the birds that saw further than men. The search has run out of searchers.",
    '28:22': "Destruction and Death have only heard the rumour. Even the grave can report nothing but hearsay.",
    '28:23': "God knows the way to it, not merely the place. Wisdom is reached by a road only he has travelled.",
    '28:24': "He sees to the ends of the earth. Wisdom belongs to the one who can take in the whole at once.",
    '28:25': "Weighing the wind and measuring the waters — wisdom is what it took to build the world's proportions.",
    '28:26': "Rain and lightning run by decree. What looks like weather is a rule laid down.",
    '28:27': "He saw it, declared it, prepared it, searched it out. Even God is described as taking trouble over wisdom.",
    '28:28': "Man is not given the mine but the entrance: fear the LORD, depart from evil. That much is handed over plainly.",
}

TAKEAWAYS.update({
    # ---- Chapter 29 ----
    '29:2': "What he misses first is not the herds or the children but the months when God kept him.",
    '29:3': "He walked through darkness by a light he did not own. The candle was on his head, not in his hand.",
    '29:4': "\"The secret of God was upon my tabernacle\" — he remembers being let in on something, not merely blessed.",
    '29:5': "The Almighty is named before the children. Job's account of the good days puts them in that order.",
    '29:6': "Washing his feet in butter and oil from the rock — the exaggeration is how a man remembers plenty.",
    '29:7': "The gate was the courthouse. Job is remembering public standing, not private comfort.",
    '29:8': "The young hid and the old stood up. Deference ran in both directions when he came through.",
    '29:9': "Princes stopped mid-sentence. Job is describing a silence he has now lost entirely.",
    '29:10': "The tongue of a noble stuck to his palate. Job remembers being the one man nobody interrupted.",
    '29:11': "Ear and eye both testified. His reputation did not need arguing; it only needed witnessing.",
    '29:12': "\"Because I delivered the poor.\" The honour rested on people who could not repay a penny of it.",
    '29:13': "He made a widow's heart sing. That is the achievement he names when listing his standing.",
    '29:14': "He wore righteousness like a robe — and the man remembering it is sitting naked in ashes.",
    '29:15': "Eyes to the blind and feet to the lame: he did not pity such people, he stood in for them.",
    '29:16': "\"The cause which I knew not I searched out.\" He investigated the case of a stranger with no claim on him.",
    '29:17': "Breaking the jaws to get the prey out. Rescue here is violent, because the injustice was.",
    '29:18': "\"I shall die in my nest.\" Every decent man assumes a quiet ending, and the assumption is rarely examined.",
    '29:19': "Root at the water, dew on the branch all night. He thought he was planted where the supply never stopped.",
    '29:20': "Glory fresh and the bow renewed — the strange confidence of a man who expects tomorrow to resemble today.",
    '29:21': "Men waited on his counsel. He is describing exactly what the three friends no longer grant him.",
    '29:22': "His speech fell like rain and nobody added to it. Now three men talk over him for chapters.",
    '29:23': "They opened their mouths for his words as a dry field opens for the latter rain.",
    '29:24': "His smile was too good to be believed. Power is measured here by what a face could do to a room.",
    '29:25': "He sat as a king over an army, and ends the list with comforting mourners — the one office now needed and absent.",
    # ---- Chapter 30 ----
    '30:1': "\"But now.\" The whole chapter turns on those two words, and the mockers are the sons of men he pitied.",
    '30:2': "Their fathers were too spent to be useful. Job's scorn is real and the book records it without softening.",
    '30:3': "These are the destitute of chapter 24, and Job describes them now with contempt rather than compassion.",
    '30:4': "Mallow leaves and juniper roots. Men eating what is not food is the measure of their state.",
    '30:5': "Driven out with the shout used for a thief — the community's way of making a person disappear.",
    '30:6': "Caves and clefts for houses. They live where the landscape allows rather than where men build.",
    '30:7': "They bray among the bushes. The word is chosen to deny them human speech.",
    '30:8': "\"Viler than the earth\" — and these, Job says, are the ones now laughing. The shame is in the source.",
    '30:9': "He has become their song. Suffering does not only hurt; it gets set to music by strangers.",
    '30:10': "They spit in his face, which no one dared while the gate was his.",
    '30:11': "He traces their boldness back past them to God: the cord was loosed before the mockery started.",
    '30:12': "Young men crowd his right hand — the place where a defender was supposed to stand.",
    '30:13': "\"They have no helper.\" They need none. Kicking a man already down requires no assistance.",
    '30:14': "A wall breached and water pouring through the gap. The attack is not aimed; it is simply everywhere.",
    '30:15': "Welfare passes like a cloud. What is gone is not only comfort but the sense that he is someone.",
    '30:16': "\"My soul is poured out upon me.\" The self is described as spilled rather than merely sad.",
    '30:17': "The pain keeps night hours. Job's sleeplessness is given its own verse.",
    '30:18': "The disease fits him like a garment he cannot take off, tight at the throat.",
    '30:19': "\"Dust and ashes\" — the phrase he will use again in 42:6, here forced on him rather than chosen.",
    '30:20': "\"I cry unto thee, and thou dost not hear me.\" Scripture lets the charge stand unanswered for twelve chapters.",
    '30:21': "\"Thou art become cruel to me.\" The book preserves the sentence, and God never afterwards calls it wicked.",
    '30:22': "Lifted into the wind and dissolved. He is not crushed by God's weight but scattered by his letting go.",
    '30:23': "The grave is \"the house appointed for all living.\" Job's certainty about his end is not the same as hope.",
    '30:24': "The Hebrew is obscure, but the grievance is clear: a man in ruins cries out and no hand comes.",
    '30:25': "He wept for men in trouble, and can find nobody doing it for him. That asymmetry is the wound.",
    '30:26': "He waited for light and darkness came. The disappointment is worse for having been expectant.",
    '30:27': "Grief is reported as a physical churning that will not stop, not as a mood.",
    '30:28': "He stands up in the assembly and cries aloud. Public grief was not thought shameful here.",
    '30:29': "Brother to jackals and companion to owls — he now belongs with the creatures that live where men do not.",
    '30:30': "Blackened skin and burning bones. The friends' theology never had to look at this.",
    '30:31': "His own instrument has been retuned to the sound of weeping. Even his music changed sides.",
    # ---- Chapter 31 ----
    '31:1': "The covenant is with the eyes, before the act. Job polices the look rather than the deed.",
    '31:2': "He keeps his eyes because of what is due from God above, not because of who might be watching.",
    '31:3': "Job holds the friends' doctrine exactly — destruction for the wicked. He only denies it explains him.",
    '31:4': "\"He counteth all my steps.\" An oath like this one only makes sense before a God who already knows.",
    '31:5': "The charge answered is dishonesty in dealing — walking with falsehood, hurrying after a fraud.",
    '31:6': "He asks not to be excused but to be weighed. The request is for accurate scales.",
    '31:7': "Eyes leading the heart, and a stain on the hands: the greed that begins in looking and ends in taking.",
    '31:8': "If he is a thief, let his own crop be eaten by someone else. The curse matches the crime.",
    '31:9': "The charge is adultery, and he puts it as waiting at a neighbour's door rather than as passion.",
    '31:10': "The curse he calls down for adultery falls on his wife. Even his self-cursing shows whose world this is.",
    '31:11': "He grants that this one belongs in court. Job is not arguing that the law is too strict.",
    '31:12': "A fire that burns down to Abaddon and takes the harvest with it. Adultery is described as a fire nobody controls.",
    '31:13': "The charge is refusing a servant a hearing — not beating him, but dismissing his complaint unheard.",
    '31:14': "A master who will not hear his slave is asked what he will say when God stands up to question him.",
    '31:15': "One womb, one maker. Job grounds a servant's rights in creation, centuries before anyone had to.",
    '31:16': "The charge is not robbing the poor but withholding — letting the widow's eyes fail while waiting.",
    '31:17': "Eating alone is the sin here. A full table with nobody else at it counts as an offence.",
    '31:18': "He raised the fatherless as a father would. The parenthesis is an old man's aside, and it rings true.",
    '31:19': "The charge is seeing a man perish for want of clothing — the sin is in what he watched and let pass.",
    '31:20': "The witness called is the body of the poor man: did his loins bless me, was he warmed by my fleece?",
    '31:21': "The charge is using court influence against an orphan, because \"I saw my help in the gate.\"",
    '31:22': "If that hand was ever raised, let the arm come out of its socket. The curse lands on the offending limb.",
    '31:23': "What kept him honest was not conscience but dread of God. Job names the restraint that actually worked.",
    '31:24': "The sin is not having gold but saying to it, \"Thou art my confidence.\" Wealth becomes an object of faith.",
    '31:25': "The charge is gladness at the size of the pile, and at whose hand had gotten it.",
    '31:26': "Sun and moon worship needs no temple. It begins with beholding something bright for too long.",
    '31:27': "A hand kissed in secret, no altar and no witness. Job counts a private gesture as real idolatry.",
    '31:28': "He names this one as punishable by the judge too, because a secret kiss denies the God above.",
    '31:29': "The charge is rejoicing at an enemy's ruin, and Job denies even the satisfaction nobody would see.",
    '31:30': "He never let his mouth curse the man. The oath reaches all the way down to what he muttered.",
    '31:31': "The proof of his hospitality is that nobody in his household ever went unfed enough to complain of it.",
    '31:32': "The traveller never slept in the street. A door left open at night is the whole of the evidence.",
    '31:33': "\"If I covered my transgressions as Adam\" — concealment is itself an item on the list, with its inventor named.",
    '31:34': "The charge is cowardice: keeping quiet and staying indoors because the crowd would not like it.",
    '31:35': "He wants the indictment written down. Job's request is not for mercy but for a document.",
    '31:36': "He would wear the charge sheet as a crown. A man certain of his answer wants the accusation published.",
    '31:37': "He would give an account of every step and approach like a prince. This is the last thing he asks for.",
    '31:38': "Even the land is called as a witness, in case he took a field by force and the furrows remember.",
    '31:39': "The charge is eating a harvest without paying, and costing the owners their lives to get it.",
    '31:40': "\"The words of Job are ended.\" He has sworn himself clean and no voice from heaven has yet said anything.",
})

TAKEAWAYS.update({
    # ---- Chapter 32 ----
    '32:1': "The debate ends not with an answer but with three men giving up. They stop because Job will not yield.",
    '32:2': "A fourth speaker nobody has mentioned is suddenly named, with a pedigree, and what is named first is his anger.",
    '32:3': "He is angry at both sides: the friends condemned Job while finding nothing to say.",
    '32:4': "He held his tongue because they were older. The deference was real before the outburst.",
    '32:5': "It is their silence, not Job's argument, that finally sets him off.",
    '32:6': "\"I am young, and ye are very old.\" He opens by conceding the one thing that should disqualify him.",
    '32:7': "\"Days should speak\" — he states the rule he is about to break before breaking it.",
    '32:8': "His warrant is not his years but a spirit in man. Elihu claims his understanding is given, not accumulated.",
    '32:9': "Age and greatness do not guarantee judgement. Elihu makes room for himself by unseating a whole convention.",
    '32:10': "He asks only to be allowed an opinion. The claim is modest and the speech runs six chapters.",
    '32:11': "He listened to the whole debate. Whatever else he is, Elihu is the one man who has heard everybody out.",
    '32:12': "His charge is precise: nobody answered Job's words. They convicted him without meeting a single argument.",
    '32:13': "He warns them off congratulating themselves on wisdom. Only God, not men, can thrust Job down.",
    '32:14': "He will not recycle their speeches. Elihu insists his case is new, and asks to be judged on that.",
    '32:15': "The three are amazed and have nothing left. The narrator's voice cuts in for a moment inside the speech.",
    '32:16': "He waited while they stood still. The pause before Elihu speaks is given two whole verses.",
    '32:17': "\"I also will shew mine opinion.\" He repeats himself, and a man this eager to begin is worth watching.",
    '32:18': "He is full of words and says the spirit inside him leaves him no choice.",
    '32:19': "New wine with no vent. His own picture of himself is of pressure that must escape.",
    '32:20': "\"I will speak, that I may be refreshed.\" He says outright that the speech is partly for his own relief.",
    '32:21': "He promises to use no flattering titles, which is a promise to spare nobody in the circle.",
    '32:22': "He fears that flattery would get him killed by his Maker. The scruple is genuine whatever comes of it.",
    # ---- Chapter 33 ----
    '33:1': "Elihu calls Job by name. In thirty chapters of debate the three friends never once did.",
    '33:2': "A whole verse to announce that he has begun speaking. Elihu clears a great deal of throat.",
    '33:3': "He stakes his case on plain speech and an upright heart rather than on standing.",
    '33:4': "Made by the same breath, he claims no advantage of nature over the man he is answering.",
    '33:5': "He invites a reply. Elihu is the only speaker who asks Job to argue back.",
    '33:6': "Job asked for someone to stand between him and God. Elihu offers himself — clay, like Job, and not frightening.",
    '33:7': "Job's fear was of being overwhelmed by power before he could speak. Elihu promises not to do that to him.",
    '33:8': "He quotes Job before answering him, which is more than the other three managed.",
    '33:9': "The quotation is sharpened. Job claimed innocence of the charges, not that no iniquity was in him.",
    '33:10': "\"He counteth me for his enemy\" — Elihu has Job's complaint exactly right, whatever he does with it.",
    '33:11': "Feet in the stocks: Job's own image, repeated back as the grievance to be answered.",
    '33:12': "\"God is greater than man.\" Elihu's answer begins where Bildad's ended, but he will not stop there.",
    '33:13': "Job's error, Elihu says, is demanding an accounting. God is not obliged to explain his matters.",
    '33:14': "The turn in the book's argument: God does speak, more than once, and the man fails to notice.",
    '33:15': "Dreams and night visions are named as one of God's ways of speaking to an ordinary man.",
    '33:16': "\"Sealeth their instruction\" — the dream is not information but a warning stamped and delivered.",
    '33:17': "The aim of the warning is to stop a man in his tracks and take his pride off him.",
    '33:18': "Suffering is described as prevention, keeping a soul back from the pit rather than paying it out.",
    '33:19': "Pain on the bed is God's second language. Elihu makes affliction a message rather than a verdict.",
    '33:20': "The sick man cannot face food. Elihu describes the illness in detail before he interprets it.",
    '33:21': "Flesh gone and bones showing. Elihu has evidently looked at Job while the others talked.",
    '33:22': "The man reaches the edge of the grave, and this is where Elihu's account turns.",
    '33:23': "\"One among a thousand\" — a messenger, an interpreter. What the man needs at the edge is somebody to speak for him.",
    '33:24': "\"I have found a ransom.\" Deliverance comes because a price has been located, not because the man improved.",
    '33:25': "Flesh fresher than a child's. Elihu's God restores rather than merely spares.",
    '33:26': "The restored man sees God's face with joy, and righteousness is rendered to him rather than earned.",
    '33:27': "The confession Elihu puts in the man's mouth admits both the sin and that it never paid.",
    '33:28': "The outcome is not merely survival but light. The pit is escaped, not endured.",
    '33:29': "\"Oftentimes\" — Elihu insists this is God's ordinary practice, not a rare intervention.",
    '33:30': "Twice from the pit, into the light of the living. His whole case is that God is working to bring a man back.",
    '33:31': "\"Hold thy peace, and I will speak.\" He asked for a reply in verse 5 and now asks for silence.",
    '33:32': "\"I desire to justify thee.\" Whatever the three came to do, Elihu says he came wanting Job acquitted.",
    '33:33': "The offer ends as a lesson: be quiet and be taught. Wisdom is on his side of the conversation.",
})

TAKEAWAYS.update({
    # ---- Chapter 34 ----
    '34:2': "He turns from Job to the bystanders and argues the case before an audience instead of the man.",
    '34:3': "\"The ear trieth words, as the mouth tasteth meat.\" He asks to be tested, which few speakers here do.",
    '34:4': "He proposes that they settle it together, as a jury weighing evidence rather than as a man pronouncing.",
    '34:5': "The quotation is fair: Job did say God had taken away his judgement.",
    '34:6': "\"My wound is incurable without transgression\" — the grievance Elihu must answer is that the punishment has no crime.",
    '34:7': "\"Drinketh up scorning like water.\" The promise of no flattering titles is being kept in full.",
    '34:8': "The charge is company, not conduct: Job's words put him on the side of men he has never walked with.",
    '34:9': "Elihu has Job saying that delighting in God profits nothing — which is exactly the accuser's thesis in chapter 1.",
    '34:10': "The axiom Elihu will not surrender: God cannot do wrong. Everything else must be arranged around it.",
    '34:11': "Retribution restated as flat arithmetic. Here Elihu sounds like the three men he was angry with.",
    '34:12': "Justice is argued from God's nature rather than from the evidence Job has laid out.",
    '34:13': "Nobody appointed God over the earth, so there is no higher office to appeal his conduct to.",
    '34:14': "God has only to draw back his breath and stop. Sustaining is presented as an ongoing decision.",
    '34:15': "If he gathered his Spirit home, all flesh would end together. Existence itself is on loan.",
    '34:16': "\"If now thou hast understanding\" — the invitation and the insult arrive in the same breath.",
    '34:17': "Government presupposes justice, Elihu argues: one who hated right could not hold the world together.",
    '34:18': "You do not call a king wicked to his face. The argument runs upward from ordinary courtesy.",
    '34:19': "God takes no bribes and knows no ranks, because rich and poor alike are the work of his hands.",
    '34:20': "The mighty are removed without a hand being laid on them, at midnight, with no process anyone can see.",
    '34:21': "God's eyes are on every step. Elihu makes omniscience the guarantee that judgement is accurate.",
    '34:22': "There is no darkness deep enough to work in. What Job feels as surveillance, Elihu offers as fairness.",
    '34:23': "God needs no fixed court date, Elihu says — which is precisely the hearing Job has been asking for.",
    '34:24': "He breaks the mighty without inquiry and puts others in their place. Power changes hands without explanation.",
    '34:25': "He overturns them in the night. The judgement Job cannot see is said to be happening in the dark.",
    '34:26': "\"In the open sight of others\" — Elihu needs the punishment to be public or the doctrine cannot be checked.",
    '34:27': "The root offence is turning back and refusing to consider God's ways. Inattention, not atrocity.",
    '34:28': "\"He heareth the cry of the afflicted\" — flatly contradicting Job's charge in chapter 24 that God does not.",
    '34:29': "When God is quiet, no one can make trouble, and when he hides, no one can compel him to appear.",
    '34:30': "Even God's hiddenness is said to serve a purpose: keeping the godless man off the throne.",
    '34:31': "\"I have borne chastisement, I will not offend any more\" — the speech Elihu is waiting for Job to make.",
    '34:32': "\"That which I see not teach thou me.\" A prayer about unknown sin, which Job has refused to pray.",
    '34:33': "God will not settle accounts to Job's specification. Elihu is right, and it is not yet an answer.",
    '34:34': "He appeals again to the sensible men listening, as though a show of hands could close the matter.",
    '34:35': "\"Job hath spoken without knowledge.\" The voice from the whirlwind will use nearly the same words.",
    '34:36': "\"Tried unto the end\" — he asks that the suffering continue until Job breaks. This is the book's coldest sentence.",
    '34:37': "Clapping and multiplied words: the charge has moved from Job's theology to his manner.",
    # ---- Chapter 35 ----
    '35:2': "Job said his cause was just. Elihu has him claiming to be more righteous than God, which he never said.",
    '35:3': "The quoted question is the accuser's question from chapter 1 turned inside out: what is godliness worth?",
    '35:4': "He answers Job and the three together, having decided that all four are making the same mistake.",
    '35:5': "\"Behold the clouds which are higher than thou.\" The argument from height is about to become an argument from distance.",
    '35:6': "Your sin does not damage God. Elihu removes the personal injury Job has been assuming all along.",
    '35:7': "And your righteousness adds nothing to him. Nobody puts God in his debt by behaving well.",
    '35:8': "Sin and virtue land horizontally, on the man next to you. That is where the damage and the good actually go.",
    '35:9': "The oppressed cry out under the arm of the mighty. Elihu grants the suffering before he analyses the cry.",
    '35:10': "\"Who giveth songs in the night\" — the cry is a complaint about pain, not a search for God, and Elihu hears the difference.",
    '35:11': "Men are taught more than the beasts, and the capacity is given rather than developed.",
    '35:12': "They cry and get no answer, and the reason offered is the pride still in the crying.",
    '35:13': "An empty cry gets an empty answer. Elihu's God is not obliged by noise.",
    '35:14': "\"Therefore trust thou in him.\" The case is filed even when the judge cannot be seen; Job is told to wait.",
    '35:15': "Because the reckoning has not come, Elihu says, Job assumes there will be none.",
    '35:16': "The charge is not that Job lied but that he talked — many words, and no knowledge under them.",
    # ---- Chapter 36 ----
    '36:2': "\"On God's behalf.\" Elihu takes up a brief nobody assigned him, and the book lets him deliver it.",
    '36:3': "He will fetch his knowledge from far off and ascribe righteousness to his Maker — the conclusion is fixed in advance.",
    '36:4': "\"He that is perfect in knowledge is with thee\" — said of himself, in a phrase he will shortly use of God.",
    '36:5': "\"God is mighty, and despiseth not any.\" Power that does not look down on the small is the best thing Elihu says.",
    '36:6': "The same God who ends the wicked gives the poor their rights. Strength is aimed in a direction.",
    '36:7': "He does not take his eyes off the righteous, and can seat them with kings for good.",
    '36:8': "\"And if they be bound in fetters\" — the righteous suffer too. Elihu grants what the three would not.",
    '36:9': "Affliction is God showing a man what he has done, which assumes there is always something to show.",
    '36:10': "The ear is opened by discipline. Elihu's whole case is that pain is instruction rather than sentence.",
    '36:11': "Obedience is promised prosperity, and the old equation quietly reassembles itself.",
    '36:12': "To die without knowledge is the loss named — not the sword but never having understood.",
    '36:13': "\"They cry not when he bindeth them.\" The fatal thing is not the chain but the silence in it.",
    '36:14': "Their lives end young and among the temple prostitutes. Elihu's picture of the wasted man is concrete.",
    '36:15': "God opens ears in oppression. The affliction is the instrument, not the obstacle.",
    '36:16': "A broad place and a full table were on offer, Elihu says. He knows what God intended for Job.",
    '36:17': "The turn against Job is sudden: he is now said to have earned the wicked man's sentence.",
    '36:18': "He warns that no ransom will be large enough — having promised one in chapter 33.",
    '36:19': "Riches and force buy nothing here. Whatever Elihu gets wrong, he is not flattering a rich man.",
    '36:20': "Job longed for the night and for death. Elihu tells him not to want what he has been praying for.",
    '36:21': "The accusation lands: Job is said to have chosen rebellion in preference to suffering quietly.",
    '36:22': "\"Who teacheth like him?\" Elihu's God is above all a teacher, and this is his final theme.",
    '36:23': "Nobody assigned God his method, and nobody has standing to charge him with wrong.",
    '36:24': "Praise is put as a command: remember to magnify the work. Elihu prescribes what he wants Job to feel.",
    '36:25': "Every man sees God's work, and every man sees it from far off. The viewing is real and the distance is permanent.",
    '36:26': "\"God is great, and we know him not.\" Elihu concedes the ignorance he has spent five chapters not showing.",
    '36:27': "Rain is traced back to single drops drawn up. The wonder is in the mechanism, not the downpour.",
    '36:28': "The clouds distil on men abundantly. What falls on everybody is given as evidence of care.",
    '36:29': "Nobody understands how a cloud spreads. Elihu's questions begin to sound like the ones that follow.",
    '36:30': "Lightning spread out to the roots of the sea — light reaching where no man has been able to look.",
    '36:31': "The same weather judges nations and feeds them. Elihu will not let the two be separated.",
    '36:32': "He holds the lightning in his hands and tells it where to strike. Nothing in the storm is loose.",
    '36:33': "Even the cattle know the storm is coming. The warning is issued to creatures that cannot reason.",
    # ---- Chapter 37 ----
    '37:1': "\"My heart trembleth.\" The man explaining the storm admits he is frightened of it.",
    '37:2': "Thunder is treated as speech. Elihu is closer than he knows to what is about to happen.",
    '37:3': "The lightning is aimed to the ends of the earth. What looks random is described as directed.",
    '37:4': "\"He will not stay them when his voice is heard.\" God does not hold back the thunder to be polite.",
    '37:5': "Great things doeth he, which we cannot comprehend — the sentence Elihu keeps returning to.",
    '37:6': "\"He saith to the snow, Be thou on the earth.\" Weather arrives as a command, not a process.",
    '37:7': "Winter seals up the hand of every man. Work is stopped so that men are made to look at God's work instead.",
    '37:8': "The beasts go into their dens. The storm empties the world of everything that can take shelter.",
    '37:9': "The whirlwind comes out of the south — and in the next chapter one arrives.",
    '37:10': "Frost is made by the breath of God, and the wide water narrows into ice at a word.",
    '37:11': "The heavy cloud is worn out with carrying water. The sky is described as labouring.",
    '37:12': "The clouds turn about by his counsels. Nothing in the weather is idle or accidental.",
    '37:13': "Correction, or his land, or mercy. The same rain arrives for three different reasons, and you cannot tell which.",
    '37:14': "\"Stand still, and consider.\" The instruction is to stop arguing and look, which is nearly what God will ask.",
    '37:15': "Elihu begins asking Job what he knows. The questions are the right shape and the wrong voice.",
    '37:16': "\"The balancings of the clouds\" — a man who cannot weigh a cloud is being asked to audit providence.",
    '37:17': "He points at the warmth of Job's own clothes. You cannot account for your own comfort, let alone God's dealings.",
    '37:18': "The sky is hammered out like a bronze mirror, and Job was not there holding the other end.",
    '37:19': "\"We cannot order our speech by reason of darkness.\" Elihu admits at last that he does not know what to say.",
    '37:20': "A man who insisted on speaking now says a man who speaks would be swallowed up.",
    '37:21': "The light behind the cloud is unlookable at once the wind clears it. He is describing what is about to arrive.",
    '37:22': "Golden splendour out of the north, and terrible majesty with God. Elihu's last picture is of approach.",
    '37:23': "His final claim is that God cannot be found out and will not afflict. The whirlwind interrupts him.",
    '37:24': "Elihu ends with God caring nothing for the self-declared wise, which is an odd note for this speaker to end on.",
})

TAKEAWAYS.update({
    # ---- Chapter 38 ----
    '38:1': "\"The LORD answered Job.\" He asked for a hearing and is given one, and it is given to him and not to the friends.",
    '38:2': "Counsel is darkened by talk, not by silence. The charge is against explaining what you do not know.",
    '38:3': "Job asked to question God. God arrives ready to question him, and Job is told to stand up for it.",
    '38:4': "\"Where wast thou?\" The first question is not about Job's guilt but about his absence from the beginning.",
    '38:5': "Measures and a stretched line: the earth was laid out like a building site, and Job did not hold the tape.",
    '38:6': "Foundations and a corner stone. Whatever the world rests on, nobody consulted Job about the footings.",
    '38:7': "\"The morning stars sang together.\" The founding of the world was attended by joy, not by explanation.",
    '38:8': "The sea is a newborn shut behind doors — wild, and delivered out of a womb rather than defeated.",
    '38:9': "Cloud for a garment, thick darkness for a swaddlingband. The deep is dressed like an infant.",
    '38:10': "Bars, doors and a decreed place. The sea is not destroyed; it is given a limit and left strong inside it.",
    '38:11': "\"Hitherto shalt thou come, but no further.\" A boundary, not an abolition, is what God does with the proud waves.",
    '38:12': "Morning arrives daily on an order Job never gave, and the dayspring knows its place without him.",
    '38:13': "Daylight takes the earth by its edges and shakes the wicked out like crumbs out of a cloth.",
    '38:14': "Dawn presses the earth as a seal presses clay. Light does not merely show the landscape; it stamps it.",
    '38:15': "Their light is the dark, and morning takes it away. The high arm is broken by sunrise, not by argument.",
    '38:16': "The sea has springs at the bottom of it, and Job has never stood there. His knowledge stops at the shore.",
    '38:17': "The gates of death have not been opened to him. He has spent the book asking to go somewhere he has never seen.",
    '38:18': "\"Declare if thou knowest it all.\" The width of the earth is offered as the smallest thing he does not know.",
    '38:19': "Light is asked after as though it had an address: where does it live when it is not here?",
    '38:20': "Could he walk the darkness home? The paths to its house are on no map Job has ever held.",
    '38:21': "\"Because thou wast then born?\" The sarcasm is mild and total: Job is young, and the world is not.",
    '38:22': "Snow and hail are kept in treasuries — weather stored rather than made, held back until it is wanted.",
    '38:23': "The hail is stockpiled against the day of battle. The storeroom is an armoury, and the war is not Job's.",
    '38:24': "The light is parted somewhere and the east wind scatters from that place. The mechanism is hidden, not absent.",
    '38:25': "Someone cut a channel for the flood and a road for the lightning. Even the violence runs in a made path.",
    '38:26': "Rain falls where no man is. God waters ground that nobody will ever thank him for.",
    '38:27': "Waste land is satisfied and a bud comes up unwatched. Usefulness to men is not the measure of the care.",
    '38:28': "\"Hath the rain a father?\" The dew is begotten rather than manufactured, and Job cannot name the parent.",
    '38:29': "Ice comes out of a womb. The hardest and deadest thing in the year is spoken of as something born.",
    '38:31': "Job can neither tie up the Pleiades nor untie Orion, and the seasons arrive on time regardless.",
    '38:32': "Mazzaroth brought out in his season, Arcturus led with his sons. The stars are herded, and not by Job.",
    '38:33': "Heaven has ordinances, and someone rules the earth by them. Job knows neither the statute nor the enforcement.",
    '38:34': "Could he call up to the clouds and be answered with rain? Asking for weather is not commanding it.",
    '38:35': "\"Here we are.\" The lightning reports for duty to someone, and it has never reported to Job.",
    '38:36': "Wisdom is put into the inward parts. Even Job's ability to argue this case was handed to him.",
    '38:37': "Nobody can number the clouds or stop the bottles of heaven. Counting them is as far out of reach as controlling them.",
    '38:39': "Does Job hunt for the lion? Something feeds the predator, and it is not the man who is afraid of it.",
    '38:41': "The young ravens cry to God and are fed. Job's whole complaint was that crying goes unanswered.",
    # ---- Chapter 39 ----
    '39:1': "Nobody attends the wild goat's birth. The most private business of the mountains is watched by someone.",
    '39:3': "\"They cast out their sorrows.\" Birth pain in the wild is over in half a line, unattended and uncomforted.",
    '39:4': "The young grow strong, go out, and do not return. Wild creatures are given no continuing household.",
    '39:5': "The wild ass was sent out free. His usefulness to nobody is described as a gift rather than a defect.",
    '39:6': "The wilderness is called his house. Barren land is somebody's home address, and assigned on purpose.",
    '39:7': "He scorns the city and ignores the driver. God points out a creature that will not be put to work.",
    '39:8': "His pasture is a mountain range and he searches it for anything green. The freedom includes the hunger.",
    '39:9': "The wild ox will not stand at Job's manger. Strength that cannot be stabled is still worth making.",
    '39:10': "No harness will go on him. He will not plough, and the furrow was never the point of his existence.",
    '39:11': "Great strength is exactly what makes him useless to you: he cannot be trusted with your labour.",
    '39:13': "The ostrich is given wings and cannot fly. God introduces a creature whose design looks like a mistake.",
    '39:14': "She lays her eggs in the earth and leaves the dust to do the warming.",
    '39:15': "She forgets that a foot may crush them. The negligence is stated without excuse and without condemnation.",
    '39:16': "Hardened against her young as though they were not hers — and it is God saying this of his own creature.",
    '39:17': "\"God hath deprived her of wisdom.\" The foolishness is credited to the maker, in the maker's own speech.",
    '39:18': "The bird that cannot fly outruns the horse. The botched creature has one thing nothing else can do.",
    '39:19': "\"Hast thou clothed his neck with thunder?\" The horse's strength is spoken of as something put on him.",
    '39:20': "The snorting is terrible, and the one thing Job cannot do is make this animal afraid.",
    '39:21': "He rejoices in his strength and goes out to meet armed men. The horse enjoys what terrifies his rider.",
    '39:22': "\"He mocketh at fear.\" Something was made that does not turn back from the sword, and it is not a man.",
    '39:23': "The quiver rattles on his back and the spear glitters, and he hears all of it as music.",
    '39:24': "He swallows the ground in rage and cannot believe the trumpet has gone. He is too eager to wait for the signal.",
    '39:25': "\"Ha, ha\" among the trumpets. He smells the battle from far off and is glad it is coming.",
    '39:26': "The hawk turns south by no wisdom of Job's. Migration happens without human instruction.",
    '39:27': "The eagle goes up at a command, and builds high on a command, and neither of them is Job's.",
    '39:28': "She lives on a bare crag and it is called the strong place. Safety is where nothing else would stay.",
    '39:29': "From that height she sees the prey far off — the long view Job has been asking for all along.",
    '39:30': "\"Where the slain are, there is she.\" The speech ends in blood, and God does not apologise for the bird.",
    # ---- Chapter 40 ----
    '40:2': "\"Let him answer it.\" The trial narrows to one question: will the man who reproved God now instruct him?",
    '40:4': "\"I will lay mine hand upon my mouth.\" Job stops talking, and the thing he wanted explained is still unexplained.",
    '40:5': "Once, twice, and no further. He does not withdraw the complaint; he declines to make it again.",
    '40:7': "The challenge comes a second time. Silence was not what God was after; he wants Job on his feet and listening.",
    '40:8': "\"That thou mayest be righteous\" — the charge is that Job's defence needed God to be in the wrong.",
    '40:9': "An arm and a voice. The comparison offered is not moral but physical, and Job has already lost it.",
    '40:10': "Job is told to put on majesty and glory as though the robes were hanging on a hook waiting for him.",
    '40:11': "Run the world for a day: pour out your anger and bring down every proud man you can find.",
    '40:13': "Bury them and bind their faces. Dealing with the wicked properly means dealing with their deaths.",
    '40:14': "\"Then will I also confess\" — the single condition on which God will grant that a man saved himself.",
    '40:15': "\"Which I made with thee.\" Behemoth and Job came from the same hand, and the monster eats grass like an ox.",
    '40:16': "The strength is in the loins and the belly. God locates it exactly instead of praising it in general.",
    '40:17': "A tail moving like a cedar, sinews wrapped tight. The description is admiring and anatomical at once.",
    '40:18': "Bones like bars of iron. What was made out of dust is built with metal.",
    '40:19': "\"The chief of the ways of God\" — and even the chief of them stands within reach of his maker's sword.",
    '40:20': "The mountains bring him food and the other beasts play where he feeds. The monster is fed, not feared.",
    '40:21': "He lies under shady trees in the reeds. The chief of God's ways spends his afternoon resting in a marsh.",
    '40:23': "He drinks up a river and is not in a hurry. The confidence of the beast shows in its slowness.",
    '40:24': "\"His nose pierceth through snares.\" The trap is noticed and walked through; nothing catches him by accident.",
    # ---- Chapter 41 ----
    '41:1': "A hook and a cord. God asks whether Job would fish for leviathan, which is how tackle looks beside the animal.",
    '41:2': "A thorn through the jaw is how a caught beast is led home. This one is not going to be led anywhere.",
    '41:3': "Will he beg, and speak softly to you? The question is whether the creature can be made to plead.",
    '41:4': "A covenant with leviathan, a servant for ever. Some things will not be brought into any arrangement.",
    '41:5': "Play with him like a bird, tie him up for the girls. The picture of a pet is drawn so that it can collapse.",
    '41:6': "Will the traders carve him up and sell the pieces? Not everything large can be turned into a market.",
    '41:7': "Barbed irons and fish spears: the weapons named are the ones that work perfectly well on ordinary fish.",
    '41:8': "\"Lay thine hand upon him, remember the battle, do no more.\" One touch, and nobody tries a second time.",
    '41:9': "The hope of taking him fails at the sight of him. The plan dies before the fight has started.",
    '41:10': "\"Who then is able to stand before me?\" The only argument God draws from the beast is about himself.",
    '41:11': "Nobody has put God in credit. Everything under heaven is already his, so no creature can send him a bill.",
    '41:12': "God says he will not conceal the beast's parts or his comely proportion. The catalogue is offered as beauty.",
    '41:13': "Nobody gets under the outer garment of him, and no bridle was ever made for that double jaw.",
    '41:14': "\"The doors of his face\" — the mouth is a gate, and what stands inside it is terrible all the way round.",
    '41:15': "The scales are called his pride: armour that is also ornament, shut together like a sealed document.",
    '41:16': "So close that no air can come between them. The fit is measured by what cannot get through it.",
    '41:18': "His sneeze throws light, and his eyes are like the first grey edge of the morning.",
    '41:19': "Burning lamps out of the mouth and sparks leaping. The description crosses out of zoology here.",
    '41:21': "His breath sets coals alight. What comes out of him is not smoke but ignition.",
    '41:22': "\"Sorrow is turned into joy before him.\" The devastation in front of the creature is its own delight.",
    '41:23': "The flakes of his flesh are firm and will not move. Even the soft parts of him are not soft.",
    '41:24': "A heart as hard as the nether millstone — the stone chosen is the one that takes all the weight.",
    '41:25': "When he rises the mighty are afraid and purify themselves. Terror sends strong men straight to religion.",
    '41:26': "Sword, spear, dart and habergeon are listed together and dismissed together, as inventory.",
    '41:27': "Iron is straw to him and brass is rotten wood. What men trust in is graded as rubbish.",
    '41:29': "He laughs at the shaking of a spear. It is the threat display, not the weapon, that amuses him.",
    '41:30': "Sharp stones are his bedding, and he leaves a harrowed track behind him through the mire.",
    '41:31': "He boils the deep like a pot and stirs the sea to ointment. The water is altered by his passing through it.",
    '41:32': "His wake shines white behind him. You can see where the creature has been long after he is gone.",
    '41:33': "\"Made without fear\" — the one thing on earth with no equal was made that way on purpose.",
    '41:34': "King over all the children of pride. God finishes by naming a beast that outranks every proud man alive.",
    # ---- Chapter 42 ----
    '42:2': "\"I know that thou canst do every thing.\" Job's first word back is about God's reach, not about his own case.",
    '42:3': "He takes up God's charge and turns it on himself: he spoke about things he did not understand.",
    '42:4': "He quotes back the summons he was handed, and this time he is the one under examination.",
    '42:5': "\"Now mine eye seeth thee.\" What changed was not the argument but that he met the one he was arguing with.",
    '42:6': "He repents of the demand rather than of a hidden sin — and he is never told why any of it happened.",
    '42:7': "The verdict is that the three were wrong and Job was right. The man who complained spoke rightly of God.",
    '42:8': "The friends need bullocks and Job's prayer. The man they diagnosed is made the priest who covers them.",
    '42:9': "Eliphaz, Bildad and Zophar go and do it, and it is Job whom the LORD is said to accept.",
    '42:10': "The turn comes while Job is praying for the men who tormented him, before any of the goods arrive.",
    '42:11': "The family that stayed away through the ashes comes to dinner once it is over, bringing gifts.",
    '42:12': "Twice the flocks, counted out as exactly as they were counted in the first chapter.",
    '42:13': "Seven sons and three daughters, the same as before. The children are not doubled and the first ten are not replaced.",
    '42:14': "The daughters are named and the sons are not, which is the reverse of how such records usually run.",
    '42:15': "He gives his daughters an inheritance among their brothers, which nothing obliged him to do.",
    '42:16': "A hundred and forty years and four generations: a long life, with everything that happened still inside it.",
    '42:17': "\"Old and full of days.\" The book closes without ever telling Job about the wager in chapter one.",
})
