#!/usr/bin/env python3
"""Written takeaways for Joshua."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens with a death, and the successor is introduced only as the dead man's minister.",
    '1:2': "\"Moses my servant is dead; now therefore arise.\" God states the loss and moves straight to the living.",
    '1:3': "The land is given before a foot touches it. The treading claims what is already deeded.",
    '1:5': "\"As I was with Moses, so I will be with thee.\" The promise rests on the presence, not on the man.",
    '1:6': "Courage is commanded for dividing an inheritance, not only for taking it. The paperwork needs nerve too.",
    '1:7': "The courage asked for is courage to keep the law, which is the harder kind.",
    '1:8': "Meditating in the book day and night, not conquering, is what the LORD ties his prospering to.",
    '1:9': "\"Have not I commanded thee?\" The order not to fear arrives with its own grounds attached.",
    '1:11': "Three days to prepare victuals, then a flooded river. The miracle is scheduled around ordinary bread.",
    '1:13': "The eastern tribes are reminded they already have rest before they are asked to fight for someone else's.",
    '1:14': "Men who already possess their land cross over armed for brethren who do not.",
    '1:16': "\"All that thou commandest us we will do.\" The pledge is total, and the book will test it.",
    '1:17': "Their obedience is hung on the LORD being with Joshua, not on Joshua's record.",
    '1:18': "They promise death to any rebel and then tell their commander to be strong. The threat is meant as reassurance.",

    # ---- Chapter 2 ----
    '2:1': "Spies sent to look at Jericho lodge in a harlot's house. Israel's first foothold in Canaan is her roof.",
    '2:3': "The king asks for the men politely. Rahab is given every chance to comply and does not.",
    '2:4': "She hid them first and answered afterward. The decision was already made before she opened her mouth.",
    '2:5': "A lie told in detail, with a direction of pursuit supplied. Scripture reports it without comment.",
    '2:6': "Flax laid in order on the roof — she had cover to hand because she was in the middle of ordinary work.",
    '2:9': "\"I know that the LORD hath given you the land.\" A Canaanite says what Israel keeps needing to be told.",
    '2:10': "Forty years on, the Red Sea is still doing its work — in the enemy's memory.",
    '2:11': "She confesses God in heaven above and in earth beneath, which is more than the spies have managed to say.",
    '2:12': "She asks kindness on the ground of kindness shown, and binds them by the LORD's own name to give it.",
    '2:13': "Her first thought on her own rescue is her father, her mother, her brothers and sisters.",
    '2:14': "\"Our life for yours.\" Two Israelites make themselves liable for a Canaanite household.",
    '2:15': "Her house stood on the town wall. The most dangerous address in Jericho becomes the only safe one.",
    '2:16': "She plans their escape route. The spies take their orders from the woman they came to spy on.",
    '2:17': "The men start hedging the oath before they are clear of the window.",
    '2:18': "The scarlet line hangs where the rope hung. The mark of rescue is the means of it.",
    '2:19': "Inside the house or nowhere — a rule as flat as the blood on the doorposts in Egypt.",
    '2:21': "She binds the line in the window at once, though the army will not come for weeks.",
    '2:24': "The spies report back in Rahab's words. Their whole intelligence is a Canaanite's confession of faith.",

    # ---- Chapter 3 ----
    '3:3': "The people follow the ark, not the general. What goes first is the sign that God is there.",
    '3:4': "Two thousand cubits of clearance. Nearness to the holy stays regulated even on the day it saves you.",
    '3:5': "\"Sanctify yourselves: for to morrow the LORD will do wonders.\" The preparing is for them, not for him.",
    '3:6': "The priests carry the ark toward the water before anything has happened to the water.",
    '3:7': "God's stated aim is to magnify Joshua publicly, so that the people will trust the word he brings.",
    '3:8': "The priests' whole assignment is to stand still in the Jordan. Standing is the act of faith here.",
    '3:10': "The living God among them is proved by what he drives out, not by what the people feel.",
    '3:11': "\"The LORD of all the earth\" — the widest possible title, used just before he hands over one small strip of it.",
    '3:13': "The water stops when the soles rest in it. The priests must get wet before there is any dry ground.",
    '3:15': "Jordan overflowed all his banks in harvest. The crossing is set for the worst month of the year.",
    '3:16': "The water piled up far upstream at Adam. The miracle happened miles from anyone who saw the result.",
    '3:17': "The priests stand firm in the riverbed until every Israelite is over. Those who went first come out last.",

    # ---- Chapter 4 ----
    '4:3': "The memorial is quarried from the exact place the priests' feet stood. The stones are evidence, not decoration.",
    '4:5': "One stone per tribe, on a man's shoulder. Each tribe carries its own share of what it saw.",
    '4:6': "The monument is built for a question children have not asked yet.",
    '4:7': "The answer children get is the bare fact, said twice, with no moral hung on it.",
    '4:8': "The obedience is recorded as carefully as the command was, stone for stone.",
    '4:9': "A second twelve stones are set in the riverbed, where the water will cover them and nobody will see.",
    '4:10': "The priests stand in the river until every word is finished, while the people hasten past them.",
    '4:11': "The ark crosses last, in sight of them all. What held the river open leaves it only when they are safe.",
    '4:12': "The eastern tribes cross armed and in front, keeping the promise they made in chapter one.",
    '4:13': "Forty thousand go over \"before the LORD unto battle.\" The muster is described as a procession.",
    '4:14': "The magnifying promised three verses into the crossing arrives on the day, and the people fear Joshua as they feared Moses.",
    '4:18': "The river returns the moment the priests' feet touch dry land. The road was open only while the ark stood in it.",
    '4:19': "The tenth day of the first month — the day the Passover lamb was taken up, forty years earlier.",
    '4:20': "The stones are pitched at Gilgal, where they will live, not at the river where it happened.",
    '4:22': "\"Israel came over this Jordan on dry land.\" The telling is kept to what happened.",
    '4:23': "Jordan is set beside the Red Sea so that the new generation is handed their fathers' story as their own.",
    '4:24': "The purpose runs outward first — that all the earth might know — and only then inward to Israel's fear.",

    # ---- Chapter 5 ----
    '5:1': "The kings' hearts melt at the news, and Israel's next move is to disable every fighting man it has.",
    '5:2': "Sharp knives in enemy country on the eve of a war. The covenant sign goes before the campaign.",
    '5:6': "Forty years in the wilderness is stated as a consequence, not a misfortune. They obeyed not the voice.",
    '5:8': "A whole army lies up sore in the field, defenceless because it obeyed.",
    '5:9': "\"This day have I rolled away the reproach of Egypt.\" Gilgal is named for something taken off them.",
    '5:10': "They keep the passover in Canaan before holding one acre of it.",
    '5:11': "They eat the old corn of a land that is not yet theirs.",
    '5:12': "The manna ceases the day the land's food begins. The provision changes form; it does not stop.",
    '5:13': "\"Art thou for us, or for our adversaries?\" Joshua asks it as though God had a side in his war.",
    '5:14': "\"Nay; but as captain of the host of the LORD am I now come.\" The question of sides is answered by refusing it.",
    '5:15': "The dirt outside Jericho is holy for the same reason the bush was: because he is standing on it.",

    # ---- Chapter 6 ----
    '6:1': "Jericho is shut up tight, and the narrator says so before describing the method that makes walls beside the point.",
    '6:2': "\"I have given into thine hand Jericho.\" Past tense, spoken before one circuit has been walked.",
    '6:4': "Seven priests, seven trumpets, seven days, seven circuits. The battle plan is a liturgy.",
    '6:5': "The wall comes down at a shout, so that no man can point to the place where he breached it.",
    '6:9': "Armed men before, rearward behind, trumpets in the middle. The army's function in this siege is escort.",
    '6:10': "Six days of enforced silence. The hardest order given at Jericho is to say nothing.",
    '6:11': "Once round the city, then back to camp. A full day's obedience with nothing whatever to show for it.",
    '6:14': "Six identical days pass in one sentence, and the wall is exactly where it was.",
    '6:15': "On the seventh day they rise at dawn to do seven times over the thing that has accomplished nothing.",
    '6:16': "\"Shout; for the LORD hath given you the city.\" The shout answers a gift; it does not earn one.",
    '6:17': "The city is devoted to the LORD entire, and the single exception is the prostitute who hid the spies.",
    '6:18': "The ban binds Israel too. Take the devoted thing and the taker becomes devoted with it.",
    '6:19': "Silver and gold go to the treasury. What is destroyed and what is kept are both his, on his terms.",
    '6:20': "The wall falls flat rather than breached, so the army walks in from wherever each man was standing.",
    '6:21': "Man and woman, young and old, ox and sheep, at the edge of the sword. The ban's full reach, stated without qualification.",
    '6:22': "In the middle of the killing, two men are sent to keep a private oath sworn to an enemy.",
    '6:23': "Rahab's whole kindred is brought out and left outside the camp — rescued, and not yet counted in.",
    '6:24': "The city burns and the metal goes to the house of the LORD. The men who took it keep nothing.",
    '6:25': "\"She dwelleth in Israel even unto this day.\" The harlot outlasts the city and joins the people.",
    '6:26': "A curse is laid on whoever rebuilds Jericho, priced in his sons. It is paid in 1 Kings 16.",
    '6:27': "\"So the LORD was with Joshua\" — the promise of 1:5, now audible as far as the country's gossip runs.",

    # ---- Chapter 7 ----
    '7:1': "One man takes, and the verse says the children of Israel committed a trespass. Guilt is not kept private here.",
    '7:3': "\"Let not all the people go up.\" After Jericho the scouts talk like men who know how this is done.",
    '7:4': "Three thousand men flee from a small town. The defeat is out of all proportion to the enemy.",
    '7:5': "Thirty-six dead, and the hearts of the people melted and became as water — Rahab's words about Jericho, now about Israel.",
    '7:6': "Joshua lies before the ark until evening with dust on his head, not yet knowing what has gone wrong.",
    '7:7': "\"Would to God we had been content, and dwelt on the other side Jordan!\" The new leader talks like the old generation.",
    '7:9': "His closing argument is what will become of God's great name. It is Moses' argument, used again.",
    '7:10': "\"Wherefore liest thou thus upon thy face?\" Prayer is the wrong answer when there is a sin to be dealt with.",
    '7:11': "Sinned, transgressed, taken, stolen, dissembled, hidden. The charge is laid out clause by clause.",
    '7:12': "God will not go with them while the devoted thing is in the camp. The victories were never mechanical.",
    '7:14': "Tribe, family, household, man — the lot narrows slowly, and the slowness gives Achan all night to come forward.",
    '7:15': "The sentence is published before the guilty man is found.",
    '7:16': "The tribe taken is Judah, the tribe the promise runs through. No line is exempt from the inquiry.",
    '7:18': "Achan is taken last, having watched the net close in on him all morning and said nothing.",
    '7:19': "\"My son, give, I pray thee, glory to the LORD.\" Joshua calls him son while passing sentence on him.",
    '7:20': "The confession comes only when there is nothing left to hide. It is still a true confession.",
    '7:21': "\"I saw... I coveted... I took.\" The tenth commandment broken first, and then the eighth.",
    '7:22': "The goods are exactly where he said they were. Men ran to check a confession that was already complete.",
    '7:23': "The stolen things are laid out before the LORD, whose they had been from the moment they were taken.",
    '7:24': "Sons, daughters, oxen, tent, everything he had. The text gives the full scope of the sentence without softening it.",
    '7:25': "\"Why hast thou troubled us? the LORD shall trouble thee this day.\" The valley is named out of the verdict.",
    '7:26': "Another great heap of stones, this one over a grave. The book marks its disasters the way it marks its rescues.",

    # ---- Chapter 8 ----
    '8:1': "\"Fear not\" comes after the sin is dealt with, not instead of dealing with it.",
    '8:2': "The spoil of Ai may be taken. The ban was a particular command about Jericho, not a standing rule.",
    '8:5': "The plan turns the humiliation of chapter seven into the bait. The old defeat becomes the tactic.",
    '8:7': "The men seize the city and the LORD delivers it. The verse holds both clauses without embarrassment.",
    '8:9': "\"But Joshua lodged that night among the people.\" The commander sleeps in the camp, not behind it.",
    '8:13': "Joshua goes down into the valley by night and puts himself in the exposed half of his own trap.",
    '8:14': "The king of Ai rises early and sure of himself, and the narrator says plainly that he wist not.",
    '8:15': "The rout is a performance. The men running away have been ordered to run away.",
    '8:17': "Not a man was left, and they left the city open. Eagerness opened the gate that no siege could.",
    '8:18': "The outstretched spear is Moses' rod again, and it stays out until the thing is finished.",
    '8:19': "The ambush rises at the signal and takes the city in the time it takes to cross the ground.",
    '8:20': "The smoke behind them is the moment the men of Ai understand, and by then there is no way to run.",
    '8:22': "Caught between the ambush and the army, none remained or escaped. The trap is described without a word of pity.",
    '8:23': "The king is the one man taken alive, and only so that his death can be public.",
    '8:25': "Twelve thousand, men and women, in a day. The number is set down flat, like a figure in a ledger.",
    '8:26': "Joshua's hand is not drawn back until the ban is complete. Obedience here is measured by not stopping.",
    '8:27': "Even the spoil is taken \"according unto the word of the LORD.\" The profit is under orders like everything else.",
    '8:28': "Ai is made a heap for ever. The city taken by a trick is destroyed more thoroughly than the one taken by a miracle.",
    '8:29': "The body comes down at sunset, as Deuteronomy requires. The law governs Israel's treatment of its enemies too.",
    '8:30': "An altar on mount Ebal, built in the middle of a campaign, because Moses had said to build it.",
    '8:31': "Whole stones, no iron lifted on them. An altar is to carry no mark of the builder's skill.",
    '8:32': "The law is written out on stones in the land itself, where anyone at all can read it.",
    '8:33': "\"As well the stranger, as he that was born among them.\" The covenant assembly is not closed to outsiders.",
    '8:34': "Blessings and cursings, both read out in full. Neither half of the covenant is quietly left off.",
    '8:35': "Women, little ones and strangers hear every word. Nothing is reserved for the men or for the priests.",
}

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:2': "\"With one accord\" — Canaan's unity is manufactured by Israel's arrival, and it comes too late.",
    '9:3': "Gibeon hears exactly what the kings heard and draws the opposite conclusion from it.",
    '9:4': "Mouldy bread, cracked bottles, patched shoes. Survival here takes the form of a costume.",
    '9:6': "\"We be come from a far country.\" The lie is geographical, because distance is the only thing that can save them.",
    '9:7': "Israel's men put the right question at once — and then let it drop.",
    '9:8': "\"We are thy servants.\" They surrender before anyone has asked them for a fight.",
    '9:9': "They cite the name of the LORD as their reason for coming. The lie is wrapped around a true confession.",
    '9:10': "Their evidence stops at Sihon and Og and leaves out Jericho, which no near neighbour could have missed.",
    '9:12': "The dry bread is held up as proof. Israel is shown precisely what it wants to see.",
    '9:14': "\"And asked not counsel at the mouth of the LORD.\" The whole failure is in one clause.",
    '9:15': "The princes swear, and that is what makes it binding. A treaty made on false evidence is still a treaty.",
    '9:16': "Three days, and the truth is out. The deception only had to last as long as the oath took.",
    '9:18': "The congregation murmurs and the oath holds. An oath sworn on a lie is not thereby void.",
    '9:20': "Wrath is feared for breaking the oath, not for having sworn it. The name sworn by outranks the blunder.",
    '9:21': "Hewers of wood and drawers of water. They keep their lives at the price of permanent service.",
    '9:22': "Joshua's charge against them is the lie, not their being Canaanites.",
    '9:23': "The curse ties them to the house of God. Their servitude is at the sanctuary, not in anyone's field.",
    '9:24': "They say plainly that they were afraid for their lives. Fear of Israel's God is what produced the fraud.",
    '9:25': "\"We are in thine hand: as it seemeth good and right unto thee to do unto us, do.\" They stop defending themselves.",
    '9:26': "Joshua delivers them out of the hand of his own people. The oath now protects them from Israel.",
    '9:27': "They end up drawing water for the altar of the LORD. A lie in chapter nine becomes a place in the worship.",

    # ---- Chapter 10 ----
    '10:1': "Adonizedec hears about Ai and about Gibeon, and it is the defection, not the conquest, that moves him.",
    '10:2': "Gibeon was greater than Ai and its men were mighty. The city that surrendered could have fought.",
    '10:3': "Four letters go out to four kings. The alliance is built on a grievance rather than a plan.",
    '10:4': "The first battle Israel fights in the land is fought on behalf of Canaanites.",
    '10:5': "Five kings encamp against Gibeon. Making peace with Israel cost them more at once than resisting would have.",
    '10:6': "\"Slack not thy hand from thy servants.\" The treaty got by fraud is called in the moment it costs something.",
    '10:7': "Joshua goes up. He keeps the treaty he was tricked into, and the text records no argument about it.",
    '10:8': "\"Fear them not: for I have delivered them into thine hand.\" The verdict is given before the march.",
    '10:9': "He came upon them suddenly, going up from Gilgal all night. Promised victory does not excuse him the walking.",
    '10:10': "The LORD discomfited them; Israel chased them. The verse puts the two in that order deliberately.",
    '10:11': "More died by hailstones than by the sword. The army is told mid-victory how small its part was.",
    '10:12': "He speaks to the LORD, and then speaks to the sun in the hearing of Israel.",
    '10:13': "The book of Jasher is cited by name. Scripture quotes an outside source and leaves the seam showing.",
    '10:14': "\"The LORD hearkened unto the voice of a man.\" The wonder named is the listening, not the standing still.",
    '10:16': "The five kings end the longest day of the conquest hiding in a hole in the ground.",
    '10:18': "Stones on the cave mouth and guards set. The pursuit matters more than collecting the trophies.",
    '10:19': "\"Suffer them not to enter into their cities.\" The object is to keep the enemy in the open.",
    '10:20': "The remnant reached the fenced cities. The rout was not as total as the formula first sounds.",
    '10:21': "\"None moved his tongue against any of the children of Israel.\" After such a day, not one complaint.",
    '10:24': "Feet on the necks of kings — the old ritual of total victory, performed by the captains rather than the commander.",
    '10:25': "\"Be strong and of good courage.\" Joshua hands his captains the exact words God gave him in chapter one.",
    '10:26': "The kings hang on trees until evening, as the king of Ai did. The precedent set once is followed exactly.",
    '10:27': "They are buried in the cave they hid in, under the stones that trapped them.",
    '10:28': "Makkedah is dealt with \"as he did unto the king of Jericho.\" The first city becomes the measure for all the rest.",
    '10:30': "Libnah too the LORD delivered. Each town in the list is credited to him separately, not to momentum.",
    '10:32': "Lachish took two days. The only variation in the formula is a city that lasted one day longer.",
    '10:33': "A king who marched to help a doomed ally is destroyed alongside it.",
    '10:40': "The summary offers no mitigation and no regret. It files the killing under obedience and moves on.",
    '10:41': "From Kadeshbarnea to Gaza. The extent is measured out, so that nobody can read it as a raid.",
    '10:42': "All these kings at one time, \"because the LORD God of Israel fought for Israel.\" The credit is stated, not implied.",
    '10:43': "After every campaign they go back to Gilgal, to the twelve stones out of the river.",

    # ---- Chapter 11 ----
    '11:1': "Jabin gathers the north once the south has fallen. The news travels and produces the same reflex each time.",
    '11:4': "Sand upon the sea shore was the promise made to Abraham. Here the image is spent on the army against him.",
    '11:5': "The kings meet at the waters of Merom. Canaan's last chance is also its first real coalition.",
    '11:6': "The horses are to be hamstrung and the chariots burned. Israel may not keep the weapons it captures.",
    '11:7': "Joshua comes upon them suddenly. A promise for tomorrow does not make him careless tonight.",
    '11:9': "\"Joshua did unto them as the LORD bade him.\" The hard part of that order was destroying usable equipment.",
    '11:10': "Hazor was the head of all those kingdoms, and it is taken after the field army, not before.",
    '11:11': "Hazor alone is burnt. The city that organised the resistance is the one erased from the map.",
    '11:12': "The warrant cited is what Moses commanded. Joshua acts on the instruction of a man already dead.",
    '11:13': "The other cities are left standing. Israel will live in houses it did not build.",
    '11:14': "Cattle and spoil taken, every person killed. The verse sets the two side by side and adds nothing.",
    '11:15': "The LORD to Moses, Moses to Joshua, Joshua to the work. Obedience is traced back along a chain of words.",
    '11:18': "\"Joshua made war a long time.\" Chapters of brisk formula are here admitted to have taken years.",
    '11:19': "Not one city made peace except Gibeon. The only Canaanites who live are the ones who lied their way in.",
    '11:20': "Their hearts were hardened by the LORD so that they would come out and fight. The text offers no softening.",
    '11:21': "The Anakims, the giants whose size turned Israel back in Numbers, are cut off in a single sentence.",
    '11:22': "Some Anakims remained in Gaza, Gath and Ashdod. Goliath's home towns are listed in the exception clause.",
    '11:23': "\"And the land rested from war.\" The chapter of slaughter ends on the word rest.",

    # ---- Chapter 12 ----
    '12:1': "The conquest is filed as a list of kings rather than a narrative of battles.",
    '12:4': "Og is noted as of the remnant of the giants. Even a ledger pauses to say what size the thing was.",
    '12:6': "Moses' half of the conquest is entered first, and credited to him by name three times over.",
    '12:7': "Joshua's list is framed exactly like Moses'. The land is given for a possession, not held as spoil.",
    '12:9': "Jericho and Ai head the roll, in the order the book told them.",
    '12:24': "\"All the kings thirty and one.\" Thirty-one kingdoms reduced to one word apiece and a total.",
})

TAKEAWAYS.update({
    # ---- Chapter 13 ----
    '13:1': "\"Thou art old and stricken in years, and there remaineth yet very much land to be possessed.\" The work outlives the man.",
    '13:2': "The survey of what is not yet taken is written into the inheritance list along with everything else.",
    '13:6': "The driving out is God's; the dividing is Joshua's. He is told to allot ground other people are still living on.",
    '13:13': "Geshurites and Maachathites dwell among Israel to this day. The failure is entered in the deed book beside the success.",
    '13:14': "Levi receives no land. The offerings made by fire are their portion, which means they live on what Israel brings.",
    '13:22': "Balaam the soothsayer turns up among the slain, listed in passing four books after he was hired to curse them.",
    '13:33': "\"The LORD God of Israel was their inheritance.\" One tribe is handed the giver instead of the gift.",

    # ---- Chapter 14 ----
    '14:2': "The land goes by lot. No tribe can say afterwards that its portion was negotiated.",
    '14:4': "Levi gets cities to dwell in and suburbs for cattle — a place to live, not a share to hold.",
    '14:6': "Caleb opens by reminding Joshua of a promise made forty-five years ago, to the two of them alone.",
    '14:7': "\"I brought him word again as it was in mine heart.\" He reported what he saw, not what the camp wanted to hear.",
    '14:8': "The others made the heart of the people melt; he wholly followed the LORD. The chapter repeats that phrase three times.",
    '14:9': "Moses swore the oath, but the ground of it was Caleb's following. The grant tracks the faith, not the service record.",
    '14:10': "Forty-five years of wandering he had no part in causing, spent among the people who did.",
    '14:11': "Eighty-five years old and claiming the same strength for war. The old man is asking for work, not for rest.",
    '14:12': "\"Give me this mountain.\" He asks for the hill with the Anakims on it — the exact thing that frightened the other ten.",
    '14:13': "Joshua blesses him and gives him Hebron. The hardest ground goes to the one man who asked for it.",
    '14:14': "The deed records the reason: \"because that he wholly followed the LORD God of Israel.\"",
    '14:15': "Hebron was Kirjatharba, named for a giant. The land had rest from war, and a great man's city changed hands.",

    # ---- Chapter 15 ----
    '15:13': "Caleb's portion is written into Judah's boundary \"according to the commandment of the LORD to Joshua.\"",
    '15:14': "Sheshai, Ahiman and Talmai, named and driven out. The giants who turned a nation back are removed by one old man.",
    '15:15': "Debir was Kirjathsepher, the city of the book. Even the towns in this survey came with histories attached.",
    '15:16': "A daughter offered as the prize for taking a city. The custom is set down without approval and without apology.",
    '15:17': "Othniel takes it and takes her. Israel's first judge enters the record as a man who won a wife by siege.",
    '15:18': "She moves her husband to ask, and then gets down off her ass and asks herself.",
    '15:19': "\"Thou hast given me a south land; give me also springs of water.\" She asks for the thing that makes dry land worth owning.",
    '15:63': "Judah could not drive out the Jebusites. Jerusalem appears first in this book as an item of unfinished business.",

    # ---- Chapter 16 ----
    '16:4': "Joseph's portion comes as two tribes. Jacob's adoption of his grandsons is being paid out in acres here.",
    '16:10': "Gezer's Canaanites were put to tribute instead of driven out. Useful labour beat the command.",

    # ---- Chapter 17 ----
    '17:1': "Machir gets Gilead and Bashan \"because he was a man of war.\" Some portions in this list were earned in the field.",
    '17:3': "Zelophehad had no sons, but daughters — and all five names are written into the land record.",
    '17:4': "The daughters come and claim what the LORD commanded, and the inheritance is given them among their father's brethren.",
    '17:12': "They could not drive out the inhabitants, and \"the Canaanites would dwell in that land.\" The other side had a will too.",
    '17:13': "When Israel waxed strong they took tribute rather than obey. Profit turned out easier than the command.",
    '17:14': "\"Why hast thou given me but one lot?\" Joseph argues that being blessed entitles him to more.",
    '17:15': "Joshua answers a complaint about space by pointing at the forest and telling them to start cutting.",
    '17:16': "Chariots of iron. They finally name the real objection, which was never the size of the plot.",
    '17:17': "He grants their premise — a great people with great power — and refuses the conclusion they drew from it.",
    '17:18': "The promise is that they shall drive them out, iron chariots and all. The portion comes with the clearing attached.",

    # ---- Chapter 18 ----
    '18:1': "The tabernacle is set up at Shiloh and the land is called subdued. Worship gets a fixed address before the tribes do.",
    '18:2': "Seven tribes still without an inheritance, in a land already taken.",
    '18:3': "\"How long are ye slack to go to possess the land?\" The gift has been made and not collected.",
    '18:4': "Three men from each tribe to walk the country and write it down. The survey is done by the men who will live on it.",
    '18:6': "The lot is cast before the LORD, so that no tribe can blame a man for the portion it gets.",
    '18:7': "\"The priesthood of the LORD is their inheritance.\" Levi's want of land is named again as the thing it actually is.",
    '18:9': "They described it by cities in a book. The chapters that follow are that book.",
    '18:28': "Jerusalem is listed as one of Benjamin's fourteen cities, with nothing said about it at all.",

    # ---- Chapter 19 ----
    '19:1': "Simeon's lot falls inside Judah's. A tribe is settled with no border of its own.",
    '19:9': "Judah's part was too much for them, so Simeon is housed within it. The division corrects itself in the doing.",
    '19:47': "Dan's coast was too small, so Dan took a northern town by the sword and put its own name on it.",
    '19:49': "The last portion handed out is Joshua's. The man dividing the land takes his share after everyone else has theirs.",
    '19:50': "He asked for one city and then built it. The conqueror of Canaan ends as a builder in the hills of Ephraim.",
    '19:51': "The dividing ends at the door of the tabernacle before the LORD. The survey is closed as an act of worship.",

    # ---- Chapter 20 ----
    '20:2': "Cities of refuge, commanded through Moses and established only now. The provision had to wait for a land to put them in.",
    '20:3': "The refuge is for the man who killed unawares. The law separates accident from murder and builds towns around the difference.",
    '20:4': "He states his cause at the gate and the elders take him in. Sanctuary begins with a hearing, not a ritual.",
    '20:5': "The avenger is refused on the ground that the slayer hated him not beforetime. Intent decides the case.",
    '20:6': "He stays until the high priest dies, and then goes home free. One man's death ends another man's exile.",
    '20:9': "\"And for the stranger that sojourneth among them.\" The refuge is open to foreigners on identical terms.",

    # ---- Chapter 21 ----
    '21:2': "The Levites come and ask. Even the tribe promised no land has to claim what was promised.",
    '21:3': "The cities come out of the other tribes' inheritance. Every tribe gives up something so that Levi can live.",
    '21:4': "The priests' cities fall in Judah, Simeon and Benjamin — near the ground where the temple will one day stand.",
    '21:11': "Hebron is given to the priests. The city Caleb asked for becomes a Levitical town.",
    '21:12': "Caleb keeps the fields and the villages. The city is split from its farmland and both claims stand.",
    '21:41': "Forty-eight cities scattered through every tribe. The landless tribe is put everywhere rather than settled anywhere.",
    '21:43': "\"The LORD gave unto Israel all the land which he sware to give unto their fathers.\" The oath to Abraham is reported paid.",
    '21:44': "Rest round about, and not a man of their enemies standing. Rest, not conquest, is this book's measure of success.",
    '21:45': "The book closes its own account: the promise is marked paid in full, one chapter before Judges undoes it.",
})

TAKEAWAYS.update({
    # ---- Chapter 22 ----
    '22:2': "The discharge opens with a commendation. They kept what Moses commanded and what Joshua commanded, and he says so.",
    '22:3': "\"Ye have not left your brethren these many days.\" Years of somebody else's war, served out to the end.",
    '22:4': "They go home only once their brethren have rest. The bargain struck in chapter one is honoured to the letter.",
    '22:5': "Love, walk, keep, cleave, serve. Five verbs in the parting charge, and not one of them about fighting.",
    '22:8': "The spoil is to be divided with the brethren who stayed behind. Those who did not march still draw a share.",
    '22:10': "They build a great altar on the border, great to see to. Everything that follows hangs on that one word.",
    '22:11': "Israel hears of it at second hand, and what reaches them is a report rather than a question.",
    '22:12': "The whole congregation gathers to make war over an altar. Zeal for right worship nearly destroys the nation.",
    '22:13': "Before the army moves they send Phinehas. The war is postponed for the length of a conversation.",
    '22:14': "Ten princes, one from each house. The delegation is weighted so that no tribe can disown the result.",
    '22:16': "The charge is framed as rebellion before a single question has been asked.",
    '22:17': "\"Is the iniquity of Peor too little for us?\" They argue from a sin they still regard as unsettled.",
    '22:18': "The fear is corporate: one tribe rebels today, and tomorrow the wrath falls on everyone.",
    '22:19': "Come over and take land from us, they offer, rather than let this stand. The proposal costs the accusers something.",
    '22:20': "Achan is named. Israel has learned that one man's sin does not stay one man's business.",
    '22:22': "\"The LORD God of gods, the LORD God of gods, he knoweth.\" The oath is doubled because intention cannot be proved.",
    '22:23': "They invite the LORD himself to require it of them if the charge is true. It is the only evidence they have.",
    '22:24': "\"We have done it for fear of this thing.\" The altar was built out of anxiety about being written off.",
    '22:25': "They feared their children would be told they had no part in the LORD, because a river ran between.",
    '22:27': "The altar is a witness and not a place of sacrifice. Its whole use is to answer a question nobody has asked yet.",
    '22:28': "\"Behold the pattern of the altar of the LORD.\" A copy built so that no one could deny them a share in the original.",
    '22:29': "\"God forbid that we should rebel against the LORD.\" The accused close by stating the accusers' own principle.",
    '22:30': "\"It pleased them.\" The delegation came willing to be satisfied, which is what made the inquiry work.",
    '22:31': "\"This day we perceive that the LORD is among us.\" The near-war ends with the accusers confessing something.",
    '22:33': "They bless God instead of marching. A mobilised nation stands down in a single verse.",
    '22:34': "The altar is called Ed, witness. A monument to a misunderstanding, kept where both sides can see it.",

    # ---- Chapter 23 ----
    '23:1': "A long time after the rest was given, and Joshua is old. The last speeches come from a man with nothing left to win.",
    '23:3': "\"The LORD your God is he that hath fought for you.\" The campaign is credited away from the men who fought it.",
    '23:5': "The expelling is his and the possessing is theirs, and the order of the two does not reverse.",
    '23:6': "\"Be ye therefore very courageous to keep and to do all that is written.\" Chapter one's charge, now laid on everybody.",
    '23:7': "Not even the names of their gods are to be spoken. The risk is treated as a matter of habit, not of argument.",
    '23:10': "One man chasing a thousand is only arithmetic if God is the one fighting.",
    '23:11': "\"Take good heed therefore unto yourselves, that ye love the LORD your God.\" Love is spoken of as a thing needing guard duty.",
    '23:12': "The danger he names is not armies but marriages.",
    '23:13': "Snares, traps, scourges, thorns in the eyes. The nations left standing become the instrument of Israel's undoing.",
    '23:14': "\"Not one thing hath failed of all the good things.\" He says it twice in one verse, the way a dying man repeats himself.",
    '23:15': "The same faithfulness that brought the good will bring the evil. Promise and threat rest on one character.",
    '23:16': "A book that opened with a land given closes its first farewell on the possibility of losing it.",

    # ---- Chapter 24 ----
    '24:1': "Shechem, where Abraham first built an altar. The covenant is renewed on the oldest ground in the country.",
    '24:2': "The history starts with idolatry: \"your fathers... served other gods.\" Abraham's own family is not the exception.",
    '24:3': "\"I took your father Abraham.\" The line begins with something God does to a man who was not looking for him.",
    '24:7': "\"Your eyes have seen what I have done\" — said to a generation that mostly had not, and told to own it anyway.",
    '24:9': "Balak hired a curse against Israel while Israel was camped a valley away, knowing nothing about it.",
    '24:10': "\"I would not hearken unto Balaam; therefore he blessed you still.\" They were kept from a danger they never saw.",
    '24:12': "\"Not with thy sword, nor with thy bow.\" In the retelling the victory is taken out of their hands.",
    '24:13': "Land they did not labour for, cities they did not build, vineyards they did not plant. Everything they hold is second-hand.",
    '24:14': "The call to serve comes after thirteen verses of what God did. The command rests on the history, not the reverse.",
    '24:15': "\"Choose you this day whom ye will serve.\" The choice is put as real, and he states his own before they answer.",
    '24:16': "\"God forbid that we should forsake the LORD.\" The answer is immediate and confident, and it will not hold.",
    '24:17': "They rehearse the history back correctly. Getting the story right turns out not to be the same as keeping the covenant.",
    '24:19': "\"Ye cannot serve the LORD.\" He tells them the promise is beyond them, and does not withdraw the call.",
    '24:20': "The warning is that God may do them hurt \"after that he hath done you good.\" Past kindness guarantees nothing.",
    '24:21': "\"Nay; but we will serve the LORD.\" They insist, having just been told plainly that they cannot.",
    '24:22': "\"Ye are witnesses against yourselves.\" He makes them the prosecution in their own future case.",
    '24:23': "\"Put away the strange gods which are among you.\" The gods were in the camp while the vows were being taken.",
    '24:25': "A covenant, a statute and an ordinance. The oath is given legal shape rather than left as a mood.",
    '24:26': "The words go into the book and a stone goes up under the oak. Written and standing, in case memory fails.",
    '24:27': "\"It hath heard all the words.\" A stone is called witness because a stone cannot be talked round.",
    '24:28': "Every man departs to his inheritance. The covenant ends with people going back to ordinary work.",
    '24:29': "Joshua dies at a hundred and ten, called at last what the first verse called Moses: the servant of the LORD.",
    '24:30': "He is buried in the one city he asked for. The man who handed out a country kept a hill.",
    '24:31': "Israel served the LORD as long as the men who had seen it lived. The faith lasted one generation past the witnesses.",
    '24:32': "Joseph's bones reach the field Jacob bought. A promise sworn at the end of Genesis is closed out here.",
    '24:33': "The book ends with a third grave. Three men buried in the land, and the land is theirs.",
})
