#!/usr/bin/env python3
"""Written one-line takeaways for 2 Kings, chapters 1-25."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Moab waits for Ahab to die before rebelling. The empire held only as long as the strong man did.",
    '1:2': "A king of Israel falls through a lattice and sends past his own God to a Philistine shrine for a prognosis.",
    '1:3': "The charge is not that Baalzebub is weak but that Israel has a God and the king looked elsewhere.",
    '1:4': "He gets an answer to the question he asked, and it comes from the God he did not consult.",
    '1:8': "\"An hairy man, and girt with a girdle of leather\" — the king knows the prophet from the description alone.",
    '1:9': "\"Thou man of God... Come down.\" The title is granted and the summons treats him as a subject anyway.",
    '1:10': "Elijah stakes the title on the outcome: if the king's word ruled, nothing would happen. Fifty men die.",
    '1:11': "The second captain adds \"quickly.\" Fifty corpses on the hill have taught the palace nothing.",
    '1:13': "The third captain climbs the same hill on the same errand and kneels, and he is the one who lives.",
    '1:14': "He pleads from the two burnt companies rather than from his rank. Fear of God is his whole argument.",
    '1:15': "\"Be not afraid of him\" — the man who called fire down twice still needed telling before he walked into the palace.",
    '1:16': "Elijah delivers the sentence to the king's face, word for word as he gave it to the messengers.",
    '1:17': "\"According to the word of the LORD\" — the reign is summed up by the verdict he tried to get around.",
    '1:18': "The formula sends you to the royal annals for the acts. Scripture keeps only what the acts came to.",
    # ---- Chapter 2 ----
    '2:1': "The narrator gives away the ending before the journey starts, so the chapter is about how Elisha walks it.",
    '2:2': "\"I will not leave thee.\" The first refusal of three; Elisha will not be dismissed from his master's last day.",
    '2:3': "\"Hold ye your peace.\" He knows, and will not have the day discussed while it is still being walked.",
    '2:6': "Gilgal, Bethel, Jericho, Jordan. The last walk retraces the way Israel came into the land, in reverse.",
    '2:7': "Fifty men watch from a distance. The thing itself happens where only the one who would not leave can see.",
    '2:8': "The mantle parts the Jordan, and the prophet leaves the land by the door Israel first entered.",
    '2:9': "He asks for the eldest son's share — the inheritance of a successor, not a favour or a feeling.",
    '2:10': "\"Thou hast asked a hard thing.\" Elijah cannot grant it; he can only say where to look when it is given.",
    '2:11': "Chariot and horses part them, but it is the whirlwind that takes him. The fire is not the vehicle.",
    '2:12': "\"The chariot of Israel, and the horsemen thereof\" — the nation's real defence was one man with a word.",
    '2:14': "\"Where is the LORD God of Elijah?\" The waters part for the God who is asked after, not for the mantle.",
    '2:15': "The sons of the prophets recognise the succession by the same river crossed the same way.",
    '2:16': "Fifty men who watched it happen want to send out a search party for the body anyway.",
    '2:17': "\"They urged him till he was ashamed.\" He permits what he has already refused, and three days are wasted.",
    '2:19': "The site is pleasant and the water kills. Jericho is still living under the curse laid on it in Joshua.",
    '2:20': "A new cruse and salt. The cure is ordinary material, and nothing in it explains the result.",
    '2:21': "The prophet handles the salt; the LORD claims the verb. \"I have healed these waters.\"",
    '2:22': "\"Unto this day\" — the writer's own readers are still drinking out of that spring.",
    '2:23': "\"Go up, thou bald head\" — the taunt mocks the ascension itself, and it comes out of Bethel, the calf shrine.",
    '2:24': "Forty-two torn by bears is meant to appal. Contempt for the prophet was never a small thing in Israel.",
    # ---- Chapter 3 ----
    '3:1': "The regnal formula fixes each king by a date and a length, and weighs him by one sentence about worship.",
    '3:2': "\"But not like his father.\" He pulls down the Baal pillar and is judged evil anyway. Partial reform is still measured.",
    '3:3': "Jeroboam's calves outlast Ahab's Baal. The idolatry nobody calls idolatry is the one never removed.",
    '3:4': "A hundred thousand lambs in tribute. The rebellion behind this chapter is about taxation before anything else.",
    '3:7': "Jehoshaphat gives Ahab's son the same blank yes he gave Ahab, and it goes the same way it went then.",
    '3:9': "Seven days round through Edom and no water. The alliance ran out of supplies before it met an enemy.",
    '3:10': "The king's first instinct is to blame the LORD for a route he chose himself.",
    '3:11': "Elisha is identified as the man who poured water on Elijah's hands. A servant's job is his whole credential.",
    '3:13': "\"Get thee to the prophets of thy father\" — try the gods you trust when you are not thirsty.",
    '3:14': "The prophet answers for Jehoshaphat's sake. The king of Israel is carried by company he did not deserve.",
    '3:15': "The word does not come on demand. A minstrel plays first, and then the hand of the LORD comes.",
    '3:16': "Dig ditches. The order costs a night's work with nothing in the sky to justify it.",
    '3:17': "No wind, no rain, and water regardless. The gift arrives without the means that normally produce it.",
    '3:18': "\"A light thing\" — what three kings needed to survive is the smaller half of what God intends to give.",
    '3:19': "Felling trees and stopping wells is scorched earth, and Deuteronomy forbade it in Israel's own sieges.",
    '3:20': "The water comes at the hour of the morning offering. Even in a wilderness, Israel is keeping time by worship.",
    '3:22': "Sun on water looks like blood, and Moab reads a rescue as a slaughter.",
    '3:23': "\"Now therefore, Moab, to the spoil.\" An army ruined by running at what it took for easy plunder.",
    '3:24': "Moab comes for spoil and finds a camp that is armed, awake and not dead.",
    '3:26': "Seven hundred swords aimed at the king of Edom, the weakest link in the alliance. Desperation still picks its target.",
    '3:27': "A boy burned on the wall, and Israel goes home. The chapter ends with a won war abandoned and God silent.",
    # ---- Chapter 4 ----
    '4:1': "A prophet's widow is losing her sons to a creditor. Fearing the LORD exempted her household from nothing.",
    '4:2': "\"What hast thou in the house?\" The miracle begins from the little she has and calls it something.",
    '4:3': "\"Borrow not a few.\" The size of the supply is set by how many empty vessels she is willing to go and ask for.",
    '4:4': "Shut the door. The multiplying happens out of sight, with nobody present to be impressed by it.",
    '4:6': "\"There is not a vessel more. And the oil stayed.\" The limit was never the oil.",
    '4:7': "Pay the debt first, then live on the rest. The gift settles the obligation before it becomes an income.",
    '4:8': "A woman of means feeds the prophet again and again before she is ever asked for anything.",
    '4:9': "She works out who he is by watching him pass. Discernment here is a matter of attention over time.",
    '4:10': "Bed, table, stool, candlestick. Four pieces of furniture is what hospitality to a prophet actually looks like.",
    '4:12': "Elisha speaks to her through Gehazi while she stands in the room. That distance matters before the chapter ends.",
    '4:13': "Offered a word to the king, she answers that she dwells among her own people. The court has nothing she wants.",
    '4:14': "It is the servant, not the prophet, who notices the one thing she has not asked for.",
    '4:16': "\"Do not lie unto thine handmaid.\" A promise of a son is the one thing she cannot bear to hear twice.",
    '4:17': "The word lands exactly on the season named. The birth is dated to the promise, not to the mother.",
    '4:19': "\"My head, my head.\" The child given by a word dies of an ordinary complaint in a harvest field.",
    '4:20': "He sits on her knees until noon and then dies. The whole disaster takes half a morning.",
    '4:21': "She lays him on the prophet's bed and shuts the door. The body goes back to where the promise came from.",
    '4:23': "\"It shall be well.\" She will not discuss it with her husband, and does not tell him the boy is dead.",
    '4:26': "Three questions, and she answers all three with one word while her son lies dead upstairs.",
    '4:27': "\"The LORD hath hid it from me.\" The man of God is not told everything, and he says so plainly.",
    '4:28': "\"Did I desire a son of my lord?\" Her complaint is not that she lost him but that she was given him.",
    '4:29': "Speak to nobody on the road. The staff is sent ahead with all the urgency and none of the prophet.",
    '4:30': "She uses Elisha's own words to Elijah back on him, and refuses to be sent home with a servant.",
    '4:31': "\"The child is not awaked.\" The staff does nothing. Power does not travel in an object handed over.",
    '4:33': "He shuts the door and prays first. The stretching comes after, and the narrator puts the prayer first.",
    '4:34': "Mouth to mouth, eyes to eyes, hands to hands. The prophet covers the dead child with his own living body.",
    '4:35': "Seven sneezes and open eyes. The raising is reported as untidily and as physically as the death was.",
    '4:37': "She falls at his feet before she picks up her son. The thanks comes first, and the boy is still there.",
    '4:38': "Famine in the land, and the prophet's answer is a pot of stew for his students. Ministry is often catering.",
    '4:39': "A man shreds into the common pot what he does not recognise. Ignorance is enough to poison everybody.",
    '4:40': "\"There is death in the pot.\" The danger is named at the table by the men about to eat it.",
    '4:41': "Meal in the pot, salt in the spring, oil in the vessels. The cure keeps being something already in the kitchen.",
    '4:42': "Firstfruits are brought to the prophet, and he hands them straight on to the hungry instead of keeping them.",
    '4:43': "\"Should I set this before an hundred men?\" The servant does the arithmetic; the word overrides it.",
    '4:44': "\"And left thereof.\" The leftovers are the point, and a later hillside will hear this story told again.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "The LORD gave Syria its victories by this man's hand. Then the sentence turns: \"but he was a leper.\"",
    '5:2': "The good news of this chapter enters on the lips of a kidnapped girl who had every reason to say nothing.",
    '5:3': "She wants her master healed by the prophet of the country her captors raided. Nobody asks her why.",
    '5:5': "Ten talents of silver and ten changes of raiment. Syria assumes a cure is bought, and prices it generously.",
    '5:7': "The king reads a request for healing as a pretext for war. He can imagine a quarrel sooner than a prophet.",
    '5:8': "\"He shall know that there is a prophet in Israel.\" The purpose of the healing is stated before it happens.",
    '5:9': "Horses and chariots drawn up at a private door. The general brings his whole rank to a house that ignores it.",
    '5:10': "Elisha does not come out. A messenger, a river and a number — the cure needs nothing of the prophet's presence.",
    '5:11': "\"Behold, I thought.\" He had the ceremony scripted, and the offence is that God would not follow it.",
    '5:12': "Abana and Pharpar are better rivers, and he is right. Cleansing comes by the water appointed, not the water preferred.",
    '5:13': "His servants see that he would have done something hard. It is the smallness of the command he cannot bear.",
    '5:14': "Seven dips, and the flesh comes back like a child's. The man who wanted a great thing is handed a new infancy.",
    '5:15': "\"No God in all the earth, but in Israel.\" A Syrian officer states the first commandment better than Israel's king.",
    '5:16': "Elisha will take nothing. A cure that could be paid for would have been filed away as a purchase.",
    '5:17': "Two mules' burden of Israelite soil. His theology is crude and his loyalty is not, and Elisha does not correct it.",
    '5:18': "He asks pardon in advance for the bows he will still make in Rimmon's house, and names the thing exactly.",
    '5:19': "\"Go in peace.\" No conditions and no programme of reform, and the new believer goes back to a hard post.",
    '5:20': "\"My master hath spared Naaman this Syrian.\" Gehazi resents the grace before he helps himself to it.",
    '5:22': "He invents two young men in need. Fraud in ministry works best when it asks on somebody else's behalf.",
    '5:23': "\"Be content, take two talents.\" The Syrian is generous even toward the man cheating him.",
    '5:25': "\"Thy servant went no whither.\" He stands before a prophet and lies about a walk anyone could have watched.",
    '5:26': "\"Went not mine heart with thee?\" The oliveyards and vineyards named show Elisha knew the whole ambition.",
    '5:27': "The leprosy Naaman left in the Jordan settles on the man who wanted paying. The two change places.",
    # ---- Chapter 6 ----
    '6:1': "The prophetic school has outgrown its house. Growth in this book looks like needing a bigger room.",
    '6:3': "\"Go with thy servants.\" They want the master on the work site, not waiting for them back at the study.",
    '6:5': "\"Alas, master! for it was borrowed.\" A poor man's whole trouble is that the tool was not his to lose.",
    '6:6': "The power that blinds armies is spent on one borrowed axe head. Nothing is beneath the prophet's attention.",
    '6:7': "\"Take it up to thee.\" The iron swims, and the man still has to put out his own hand for it.",
    '6:9': "The war is decided in a bedchamber the prophet never entered. Israel's intelligence service is a praying man.",
    '6:10': "\"Not once nor twice.\" The king who will soon want Elisha's head owes him his life several times first.",
    '6:12': "The leak is not a traitor. Syria's councils of war are overheard by the God its king does not believe in.",
    '6:13': "Told where the prophet is, the king sends an army to fetch him. Power can think of only one method.",
    '6:15': "\"How shall we do?\" The servant's arithmetic is accurate. It is simply not the whole count.",
    '6:16': "Elisha does not deny the horses and chariots on the hill. He disputes the total.",
    '6:17': "The prayer is not for reinforcements but for opened eyes. The fire surrounded Dothan before anyone saw it.",
    '6:18': "Blindness, not slaughter. The prophet's one act against the army leaves every Syrian in it alive.",
    '6:19': "\"This is not the way, neither is this the city.\" He walks the army that came for him into the capital.",
    '6:21': "\"Shall I smite them? shall I smite them?\" He asks twice, which is how a man asks for the answer he wants.",
    '6:22': "Men you never took by sword or bow are not yours to kill. Mercy is argued here as a point of law.",
    '6:23': "Great provision, then sent home, and the raids stop. A dinner ended a war that battles had not.",
    '6:24': "\"After this\" Benhadad comes back with everything he has. The peace kindness bought did not outlast a chapter.",
    '6:25': "An ass's head for fourscore pieces of silver. Siege prices are the arithmetic of a city eating what it despises.",
    '6:27': "\"Whence shall I help thee?\" Sound theology offered as a reason for doing nothing at all.",
    '6:28': "Two mothers agreed to eat their sons in turn. Deuteronomy warned that a siege would end here.",
    '6:29': "The grievance brought to the king is not the cannibalism but the broken bargain. Horror has become procedure.",
    '6:30': "Sackcloth under the robes. He was mourning in private and hunting the prophet in public on the same day.",
    '6:31': "His answer to a famine his house brought on is an oath to have Elisha's head before nightfall.",
    '6:32': "\"This son of a murderer\" — Elisha knows the errand and the ancestry, and has the door held on the messenger.",
    '6:33': "\"What should I wait for the LORD any longer?\" He abandons the wait one verse before the answer comes.",
    # ---- Chapter 7 ----
    '7:1': "Flour at a shekel tomorrow, in a city eating dove's dung today. The word names both a date and a price.",
    '7:2': "\"If the LORD would make windows in heaven.\" Mockery of the promise gets a sentence attached to it.",
    '7:3': "\"Why sit we here until we die?\" Four men outside the gate reason their way to the only move left.",
    '7:4': "Every road ends in death but one, and that one is surrender to the enemy. Desperation clears the head.",
    '7:5': "They reach the camp at twilight and find nobody. The deliverance was finished before anyone went to look.",
    '7:6': "God routed an army with a noise. Nothing was spent, and Syria fled from a sound it supplied itself.",
    '7:7': "Tents, horses and asses left standing. Panic does not stop to carry off what it already owns.",
    '7:8': "Their first act is to eat, and their second is to hide silver. Men starving an hour ago begin hoarding.",
    '7:9': "\"This day is a day of good tidings, and we hold our peace.\" News this good cannot be kept without guilt.",
    '7:10': "The word gets into the city through the gate porter. Lepers shut outside the wall are the ones carrying it.",
    '7:12': "The king explains the empty camp as a trap. Unbelief can always supply a plausible account.",
    '7:13': "A servant proposes risking the last five horses. The man with no rank is the one willing to go and see.",
    '7:15': "The road to Jordan is strewn with discarded clothes. The evidence of the rout is litter.",
    '7:16': "The prices fall exactly as spoken. A word fixed the market rate a day before the market moved.",
    '7:17': "He sees it with his eyes and is trodden down in the gate. The plenty he denied is what kills him.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "The prophet moves her out of the country seven years ahead. Famine is announced as something the LORD called for.",
    '8:3': "She comes back to find her land held by others and must go to court for it. Obedience cost her the house.",
    '8:4': "The king is being entertained with stories of Elisha's wonders. The word has become an anecdote at court.",
    '8:5': "She walks in on the very sentence about her own son. Providence is allowed to look like coincidence.",
    '8:6': "The land and the lost harvests are both restored. The court she once wanted nothing from now pays her.",
    '8:7': "Benhadad, who sent an army to seize Elisha, now sends a servant to ask him a question.",
    '8:8': "A Syrian king enquires of the LORD, which is more than a king of Israel managed in chapter one.",
    '8:10': "\"Thou mayest certainly recover: howbeit... he shall surely die.\" The disease was never what would kill him.",
    '8:11': "The stare holds until Hazael is ashamed, and then the prophet weeps at what he is looking at.",
    '8:12': "Foreknowledge here is not power but grief. Elisha weeps over atrocities nobody has committed yet.",
    '8:13': "\"Is thy servant a dog?\" He is offended by the prediction and goes home to fulfil it before morning.",
    '8:14': "He reports half the sentence and keeps the rest. A true clause can be made to serve a murder.",
    '8:15': "A wet cloth over a sick man's face. An empire changes hands by a method nobody can afterwards prove.",
    '8:17': "Thirty-two years old, eight years reigning. A whole life is filed as two numbers and one verdict.",
    '8:18': "\"The daughter of Ahab was his wife.\" A marriage treaty imports Samaria's religion into Jerusalem.",
    '8:19': "Judah survives on a promise made to David, not on the merits of the man currently on his throne.",
    '8:20': "Edom revolts under the king who married Ahab's house. The territory starts going as soon as the loyalty does.",
    '8:22': "\"Unto this day\" — the writer's readers are still living with what this reign lost.",
    '8:24': "Slept with his fathers, buried in the city of David. The formula hands him a peaceful line he did not earn.",
    '8:26': "The queen mother is named Athaliah, of the house of Omri. She is introduced here because she will matter.",
    '8:27': "\"For he was the son in law of the house of Ahab.\" The evil is traced to a connection, not a conviction.",
    '8:29': "Ahaziah goes down to Jezreel to visit a wounded relative, and the courtesy call is what kills him.",
    # ---- Chapter 9 ----
    '9:1': "The anointing is delegated to a nameless student with a box of oil. Kingmaking is given to an errand.",
    '9:2': "Out of a room full of captains, one is to be singled out and taken aside. The choosing happens in private.",
    '9:3': "\"Open the door, and flee, and tarry not.\" He delivers the word and is not to stay and manage the result.",
    '9:5': "\"Unto which of all us?\" Every officer in the room assumes the errand might be for him.",
    '9:7': "The commission is judicial. The blood of the prophets is being required at the hand of Ahab's house.",
    '9:8': "The whole house, shut up and left. A dynasty is sentenced without exception, having made none itself.",
    '9:10': "Dogs, and no burial. Elijah's word over Jezebel is read out again years later as a standing order.",
    '9:11': "\"Wherefore came this mad fellow to thee?\" Soldiers have only one category available for a prophet.",
    '9:12': "\"It is false; tell us now.\" The coup begins with other men refusing to accept his modesty.",
    '9:13': "Garments thrown on the stairs and a trumpet. A throne is proclaimed with whatever is to hand.",
    '9:16': "He drives to Jezreel, where both kings happen to be. The purge is efficient because its targets gathered.",
    '9:17': "\"Is it peace?\" The question the watchman keeps sending out is the one Jehu will not answer.",
    '9:18': "\"What hast thou to do with peace?\" Each rider sent to enquire is absorbed into the column behind him.",
    '9:20': "He is known at a distance by the way he drives. A man's manner arrives ahead of his news.",
    '9:21': "Both kings ride out to meet him, and they meet in the portion of Naboth. The ground has not forgotten.",
    '9:22': "\"What peace, so long as the whoredoms of thy mother Jezebel?\" An assassin refuses peace on religious grounds.",
    '9:23': "\"There is treachery, O Ahaziah.\" He reads the politics of it instantly and the judgement not at all.",
    '9:24': "One arrow at full draw, between the arms. Ahab's dynasty ends in a chariot in a stolen vineyard.",
    '9:25': "Jehu remembers riding behind Ahab when the word was spoken. He has carried that sentence for years.",
    '9:26': "The blood of Naboth and of his sons is repaid on that exact plot. God's memory for a stolen garden is long.",
    '9:27': "Ahaziah dies at Megiddo for having gone visiting. Judah's king is collateral in Israel's purge.",
    '9:30': "Paint and a dressed head at the window. She meets the coup as a queen and not as a fugitive.",
    '9:31': "\"Had Zimri peace, who slew his master?\" Her last words are a threat wearing the dress of a history lesson.",
    '9:32': "\"Who is on my side? who?\" Two or three eunuchs look out, and her own household decides in a moment.",
    '9:33': "Her servants throw her down, he drives over her, and then he goes in to eat. The brutality is casual.",
    '9:34': "\"Bury her: for she is a king's daughter.\" Rank is remembered once the meal is finished.",
    '9:35': "Skull, feet and palms. What is left are the parts that wore the crown, walked, and gave the orders.",
    '9:36': "He quotes Elijah accurately. Being right about the prophecy does not make his own motives clean.",
    '9:37': "\"So that they shall not say, This is Jezebel.\" The sentence is not death but the erasure of a name.",
    # ---- Chapter 10 ----
    '10:1': "Seventy sons in Samaria. Ahab's house is less a family than an institution, and Jehu treats it as one.",
    '10:3': "\"Fight for your master's house.\" The letter dares them to resist, knowing exactly what they will do.",
    '10:4': "\"Two kings stood not before him: how then shall we stand?\" Fear does work no army had to do.",
    '10:5': "\"Do thou that which is good in thine eyes.\" The men who raised the princes trade them for their own posts.",
    '10:6': "The second letter asks for heads and names no crime. The guardians are made to do the killing themselves.",
    '10:7': "Seventy heads in baskets, sent by courier. The atrocity is administered rather than fought.",
    '10:8': "Two heaps at the gate until morning. The display is arranged so that the city sees it in daylight.",
    '10:9': "\"Ye be righteous... but who slew all these?\" He spreads the guilt over everybody to thin out his own.",
    '10:10': "He preaches Elijah's prophecy standing beside the heads. Sound doctrine can be quoted to cover tracks.",
    '10:11': "Great men, kinsfolk and priests. The purge widens past the sentence to anyone who might object to it.",
    '10:13': "Forty-two men of Judah on a family visit, asked who they are and killed for answering honestly.",
    '10:14': "\"Take them alive.\" They are captured before they are killed, which makes it execution, not battle.",
    '10:15': "\"Is thine heart right, as my heart is with thy heart?\" Loyalty is now measured by agreement with Jehu.",
    '10:16': "\"Come with me, and see my zeal for the LORD.\" Zeal that needs a witness has named its real object.",
    '10:17': "The killing is reported as fulfilment of the word to Elijah. God's purpose and Jehu's ambition run on one track.",
    '10:18': "\"Ahab served Baal a little; but Jehu shall serve him much.\" A lie told in the language of devotion.",
    '10:19': "Attendance is compulsory on pain of death, and nobody asks why a sacrifice needs a full register.",
    '10:21': "The house of Baal fills end to end. Israel's idolatry turns out to be both extensive and well organised.",
    '10:23': "The worshippers of the LORD are sorted out first so that only the intended die. The trap is careful.",
    '10:24': "Guards outside, and a life for a life if any escape. The worship inside is a formality above a cordon.",
    '10:25': "The killing begins the moment the offering ends. He waits for the liturgy to finish before the massacre.",
    '10:27': "The house of Baal is made a latrine. Contempt, not argument, is the method of this reformation.",
    '10:28': "\"Thus Jehu destroyed Baal out of Israel.\" The sentence is true, and the next verse opens with \"Howbeit.\"",
    '10:29': "The calves at Bethel and Dan stay. He tore down the religion Ahab brought and kept the one he inherited.",
    '10:30': "Four generations on the throne for executing what was right. God pays wages for obedience he has not called pure.",
    '10:31': "\"Took no heed to walk in the law.\" A man may carry out God's sentence and never keep his commandments.",
    '10:32': "\"The LORD began to cut Israel short.\" The shrinking of the kingdom is dated from the reforming reign.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "A grandmother kills her grandsons to hold a throne. David's line shrinks to whoever survives this verse.",
    '11:2': "One aunt steals one baby out of the killing and hides him with his nurse. The promise hangs on that.",
    '11:3': "Six years hidden in the house of the LORD while Athaliah reigns. The rightful king is a secret in the temple.",
    '11:4': "In the seventh year the priest shows them the child. The rising is sworn on oath in the temple first.",
    '11:8': "Weapons in every hand, the boy in the middle. A child king is guarded before he is ever crowned.",
    '11:10': "David's own spears and shields come out of the temple store. The armoury of the promise arms the promise.",
    '11:11': "The guard stands from one corner of the temple to the other. The crowning happens where the covenant is kept.",
    '11:12': "Crown and testimony together. A king of Judah receives the law that rules him at the moment he is made king.",
    '11:13': "She hears the noise and walks into the temple she has not troubled to enter in six years.",
    '11:14': "\"Treason, Treason.\" The usurper's last word is the charge she has most thoroughly earned herself.",
    '11:15': "Not in the house of the LORD. The priest keeps the temple clean of the blood and has her killed outside it.",
    '11:16': "She dies by the horse gate. The woman who reached the throne by slaughter leaves it through a stable entrance.",
    '11:17': "Covenant between the LORD and the people first, and then between king and people. The order settles everything.",
    '11:18': "The people tear down the Baal house themselves. The reform is not imposed on them; they had been waiting.",
    '11:20': "\"The city was in quiet.\" The chapter ends with the ordinary peace that a seven-year-old on a throne bought.",
    '11:21': "Seven years old. The whole weight of the promise to David now rests on a boy who remembers nothing else.",
    # ---- Chapter 12 ----
    '12:1': "Forty years in Jerusalem for the child out of the bedchamber. The rescued baby outlasts everyone who hid him.",
    '12:2': "\"All his days wherein Jehoiada the priest instructed him.\" The verdict is quietly limited to one man's lifetime.",
    '12:3': "The high places stay. Even Judah's good kings leave the popular religion roughly where they found it.",
    '12:5': "Each priest collects from his own acquaintance and repairs the house. The scheme trusts everyone and audits nobody.",
    '12:6': "Twenty-three years on, and the breaches are still there. Money given for a purpose finds other uses.",
    '12:7': "The king has to ask the priests why the temple is not repaired. What was needed was accounting, not more zeal.",
    '12:8': "The priests give up the money and the job together. The reform is accepted by handing the work back.",
    '12:9': "A chest with a hole bored in the lid, set beside the altar. The remedy is a box nobody can reach into.",
    '12:10': "Scribe and high priest count it together. Honesty is protected by two men rather than by trusting one.",
    '12:11': "The money passes straight to the carpenters and builders, through as few hands as it can be made to.",
    '12:13': "No silver bowls or trumpets until the walls were sound. The fabric of the house came before its furnishings.",
    '12:15': "No reckoning was asked of the workmen, \"for they dealt faithfully.\" Trust earned is cheaper than an audit.",
    '12:16': "The trespass money stayed the priests'. The reform did not seize what the law had already assigned them.",
    '12:17': "Hazael takes Gath and turns toward Jerusalem. The newly repaired temple is about to be emptied to buy him off.",
    '12:18': "Three generations of dedicated gifts are sent to a Syrian. What was given to God is spent on protection.",
    '12:20': "The king who was rescued as an infant from murder is murdered in the end by his own servants.",
    # ---- Chapter 13 ----
    '13:1': "Jehu's son gets seventeen years. The four generations God promised begin to be counted off in the record.",
    '13:2': "The formula returns: evil in the sight of the LORD, the sins of Jeroboam, he departed not therefrom.",
    '13:3': "The occupation is not an accident of politics. The anger of the LORD is named as the reason for it.",
    '13:4': "An idolatrous king prays and God hears, and the hearing is credited to God's sight of the oppression.",
    '13:5': "A saviour is given and not named. Israel is delivered without ever learning whose hand to thank.",
    '13:6': "Delivered, and the grove still stands in Samaria. Rescue alone changes nothing about what a nation loves.",
    '13:7': "Fifty horsemen and ten chariots left, threshed to dust. This is what being given into a hand looks like.",
    '13:11': "The son draws the father's verdict word for word. The monotony of the record is itself the indictment.",
    '13:14': "The king weeps over Elisha in the words Elisha used over Elijah. He knows the liturgy and not the God.",
    '13:15': "The dying prophet asks for bow and arrows. His last act of ministry is a lesson done with objects.",
    '13:16': "The prophet's hands go over the king's hands. The shot is the king's, and it is not only the king's.",
    '13:17': "Eastward, over the occupied land. An arrow out of a sickroom window is called the LORD's deliverance.",
    '13:18': "\"Smite upon the ground.\" He is given no number, and that omission is the whole of the test.",
    '13:19': "He struck three times and stopped. What looked like restraint turns out to measure how much he wanted.",
    '13:20': "Elisha dies and is buried, and the raiders come back with the spring. No prophet's death pauses the world.",
    '13:21': "A corpse dropped in haste touches Elisha's bones and stands up. His last miracle happens after he is dead.",
    '13:22': "Oppression \"all the days\" of a reign. Some generations are given no relief inside their own lifetime.",
    '13:23': "The patience rests on the covenant with Abraham, Isaac and Jacob, an older promise than any king's merit.",
    '13:25': "Three victories for three strokes on the ground. The recovery is exactly the size of the asking.",
    # ---- Chapter 14 ----
    '14:2': "Age, length of reign, mother's name. The formula files a man completely before it judges him at all.",
    '14:3': "\"Right in the sight of the LORD, yet not like David.\" The measure is always David, and always a shortfall.",
    '14:4': "The high places again. It is the one sentence the reforming kings of Judah keep failing to make untrue.",
    '14:5': "He waits until the kingdom is confirmed before avenging his father. Even his justice is timed for safety.",
    '14:6': "He spares the murderers' children and cites Moses for it. A king limits his revenge because the law does.",
    '14:7': "Ten thousand Edomites in the valley of salt, and a city renamed. The victory is what gives him his next idea.",
    '14:8': "\"Come, let us look one another in the face.\" A declaration of war phrased as an invitation to meet.",
    '14:9': "A thistle proposing marriage to a cedar, and a beast that treads the thistle down. The insult arrives as a fable.",
    '14:10': "\"Glory of this, and tarry at home.\" Sound advice about a swollen head, offered by an enemy.",
    '14:11': "\"But Amaziah would not hear.\" The entire disaster is contained in four words.",
    '14:12': "Judah is beaten and every man runs for his tent. The army that crushed Edom will not stand against Israel.",
    '14:13': "Four hundred cubits of Jerusalem's wall pulled down, and by a king of Israel rather than a foreigner.",
    '14:14': "Temple gold carried to Samaria, with hostages. The brother kingdoms plunder each other's sanctuary.",
    '14:19': "A conspiracy runs him down at Lachish. The reign that opened with executions is closed by one.",
    '14:21': "The people of Judah, not the court, make a sixteen-year-old king. Ordinary hands save the succession.",
    '14:22': "He built Elath and restored it. A reign's real achievement is a working port, recorded in one line.",
    '14:23': "Forty-one years, the longest reign in the north, given to a king the record dismisses in a sentence.",
    '14:24': "Prosperity, and the same verdict as always. The formula was never measuring success.",
    '14:25': "The borders are restored by the word of the LORD through Jonah. Mercy to the north came by a reluctant prophet.",
    '14:26': "\"Not any shut up, nor any left, nor any helper.\" God's stated reason for helping is that nobody else would.",
    '14:27': "He had not said he would blot out Israel's name, so he saves them by a king who had earned nothing.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:2': "Fifty-two years in Jerusalem, the longest reign given to Judah, and six verses hold all of it.",
    '15:5': "\"The LORD smote the king\" — a leper in a several house while his son governs the land in his name.",
    '15:8': "Six months. From here the northern throne changes hands faster than the record can judge its holders.",
    '15:10': "Smitten \"before the people.\" A king is murdered in public and nobody in the crowd puts a hand out.",
    '15:12': "\"And so it came to pass.\" Jehu's four generations end in a six-month reign, counted out to the last man.",
    '15:13': "A full month. The book gives him a verse and a half, and a month was all there was to give him.",
    '15:14': "Menahem comes down from Tirzah and kills the man who killed the king. Each throne is taken from its last taker.",
    '15:16': "A town would not open its gates, so the women with child were ripped up. This is the king Israel now has.",
    '15:18': "The sin is still dated to Jeroboam, generations dead. Israel's founding decision keeps on choosing for it.",
    '15:19': "A thousand talents of silver to Assyria to confirm the kingdom in his hand. Israel buys its own king's crown.",
    '15:20': "The mighty men of wealth are assessed fifty shekels a head. The men with most to lose pay the protection.",
    '15:23': "Two years for the one son in this chapter who inherits rather than seizes, and a captain ends them anyway.",
    '15:25': "Killed in the palace by his own captain, with fifty Gileadites behind him. The bodyguard is where the danger lives.",
    '15:27': "Twenty years to a man who murdered his way in. Stability and legitimacy prove to have little to do with each other.",
    '15:29': "Naphtali, Gilead and Galilee carried to Assyria. The exile of the north begins quietly, inside a list of towns.",
    '15:30': "Hoshea kills Pekah and reigns in his stead. The last king of Israel arrives exactly as most of the others did.",
    '15:35': "One gate built on the house of the LORD is the whole positive record of a sixteen-year reign.",
    '15:37': "\"The LORD began to send\" Rezin and Pekah. The invasion that shapes the next reign is credited to God, not to politics.",
    # ---- Chapter 16 ----
    '16:2': "The comparison with David is made and then denied him. Judah's kings are measured whether they pass or not.",
    '16:3': "He made his son pass through the fire. A son of David does the thing the nations were dispossessed for doing.",
    '16:4': "Under every green tree. What Judah's better kings merely tolerated, this one takes up himself.",
    '16:5': "Besieged and not overcome. He was already surviving when he decided he needed Assyria to save him.",
    '16:6': "Elath, built up two reigns before, is lost for good. What one king achieves another simply cannot hold.",
    '16:7': "\"I am thy servant and thy son.\" A son of David adopts himself into the house of the king of Assyria.",
    '16:8': "Temple silver and gold sent as a present. The house of the LORD funds the alliance that replaces trusting him.",
    '16:9': "Damascus taken, Rezin killed, precisely as requested. The answered request costs more than the threat would have.",
    '16:10': "He sees an altar in Damascus and sends the pattern home. Conquest is admired straight into the temple court.",
    '16:11': "Urijah builds it and has it standing before the king returns. Nobody in Jerusalem thinks to refuse.",
    '16:12': "The king approaches the altar and offers on it himself. Kingship has quietly swallowed the priesthood.",
    '16:14': "The brasen altar is not broken, only moved to the north side. Displacement rather than abolition is how this works.",
    '16:15': "The LORD's altar is kept \"for me to enquire by.\" The old worship is demoted to a private royal oracle.",
    '16:16': "\"Thus did Urijah the priest.\" His entire part in the story is obedience directed at the wrong authority.",
    '16:17': "The laver off its bases, the sea off its oxen. The temple is being taken apart for metal by its own king.",
    '16:18': "Even the sabbath covert is turned \"for the king of Assyria.\" The day of rest is rearranged to suit a foreign court.",
    '16:20': "Buried with his fathers, and Hezekiah his son reigned. One of Judah's worst kings fathers one of its best.",
    # ---- Chapter 17 ----
    '17:1': "Nine years to Hoshea, and the list of Israel's kings stops here. Nobody knew this was the last name on it.",
    '17:2': "\"But not as the kings of Israel that were before him.\" The end arrives under a king who was not the worst.",
    '17:3': "Servant, and presents. The kingdom lasts a little longer by paying for the privilege of existing.",
    '17:4': "He looked to Egypt and stopped paying. What finishes Israel is a diplomatic calculation, made by a careful man.",
    '17:5': "Three years of siege. Samaria's fall took long enough that everyone inside had time to think it over.",
    '17:6': "Carried to Halah, Habor and the cities of the Medes. Ten tribes end as an address in another man's empire.",
    '17:7': "\"For so it was\" — the narrative stops and an argument begins. The cause named is not Assyria but Israel.",
    '17:8': "They walked in the statutes of nations evicted for exactly those statutes. The precedent was in plain sight.",
    '17:9': "\"Did secretly those things that were not right.\" It began hidden and ended in a shrine in every city.",
    '17:12': "\"Whereof the LORD had said unto them, Ye shall not do this thing.\" Not ignorance. A prohibition they knew.",
    '17:13': "Every prophet and every seer with one word: turn. The fall came after the warning, never instead of it.",
    '17:14': "\"They would not hear, but hardened their necks.\" The hardening is their own act, not something done to them.",
    '17:15': "\"They followed vanity, and became vain.\" What a people worships is what a people turns into.",
    '17:16': "Two calves, a grove, the host of heaven, Baal. The list keeps growing because nothing false satisfies long.",
    '17:17': "They \"sold themselves to do evil.\" The transaction is described with the seller as the thing being sold.",
    '17:18': "\"None left but the tribe of Judah only.\" Said in passing, and it is the subject of the rest of the book.",
    '17:19': "\"Also Judah kept not the commandments.\" The indictment turns south before it has finished with the north.",
    '17:21': "The rending of the kingdom was God's act; making Israel sin was Jeroboam's. One verse holds them both.",
    '17:23': "\"As he had said by all his servants the prophets.\" The catastrophe is filed as a kept word, not a surprise.",
    '17:24': "Babylon, Cuthah, Ava, Hamath and Sepharvaim moved in. Emptying a land is only half of the empire's work.",
    '17:25': "Lions among the settlers. The God of the land was not carried off along with the people who lived on it.",
    '17:26': "\"They know not the manner of the God of the land.\" The diagnosis is accurate, and foreigners make it.",
    '17:27': "Assyria's remedy is to import a priest. An empire arranges religious instruction as a matter of public order.",
    '17:28': "The teacher sent is a priest of Bethel, schooled at the calf shrine. Israel exports the religion that ruined it.",
    '17:29': "Every nation made gods of its own and housed them in Israel's high places. The shrines outlived their builders.",
    '17:31': "The Sepharvites burnt their children. Israel's high places are handed on to worship worse than the last tenants'.",
    '17:32': "Priests made \"of the lowest of them.\" Where the office costs nothing, anybody at all will fill it.",
    '17:33': "\"They feared the LORD, and served their own gods.\" Added, not exchanged — the oldest way of losing him.",
    '17:34': "\"They fear not the LORD\" — of the same people the verse before called God-fearing. Both sentences are meant.",
    '17:35': "\"Ye shall not fear other gods.\" The covenant's first demand was exclusive, and exclusivity was never given.",
    '17:36': "The claim rests on the exodus. The God who brought them out is the God with a right to their worship.",
    '17:39': "Fear him \"and he shall deliver you.\" Rescue was attached to the one commandment they would not keep.",
    '17:40': "\"Howbeit they did not hearken.\" Instruction was given, received, and left precisely where it was found.",
    '17:41': "Children and children's children, \"unto this day.\" A divided heart is inherited as reliably as land is.",
})
