#!/usr/bin/env python3
"""Written one-line takeaways for 1 Kings, chapters 1-22."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The man who killed Goliath cannot keep warm under blankets. The book opens on a king's body failing.",
    '1:2': "The court's remedy for a dying king is a policy about his body. Nobody asks him whether he wants it.",
    '1:4': "\"But the king knew her not.\" The note is about David's strength, and the whole court can read it.",
    '1:5': "\"I will be king\" — Adonijah does not wait to be told. Chariots and fifty runners, exactly as Absalom did.",
    '1:6': "\"His father had not displeased him at any time.\" A son's revolt traced to a father who never once asked why.",
    '1:7': "Joab and Abiathar: the general and the priest. The coup is carried by David's oldest surviving allies.",
    '1:8': "The list of who refused is as exact as the list of who joined. This book keeps count of loyalties.",
    '1:9': "A feast is a coronation without the word — sacrifice, guests, a chosen place, everything but an anointing.",
    '1:10': "Solomon was not invited. In a succession, the man left off the guest list is the man being ruled out.",
    '1:11': "Nathan goes to Bathsheba, not to David. The prophet who once accused the king now works around him.",
    '1:12': "\"Save thine own life\" — Nathan is blunt that a losing claimant's mother does not outlive the winner.",
    '1:13': "Nathan supplies her words, and the oath she is to cite is one the reader has never heard David swear.",
    '1:14': "Two witnesses arriving separately, so that one prepared account will sound like independent confirmation.",
    '1:15': "The narrator shows us the room: a very old king, and another woman already standing at his side.",
    '1:16': "\"What wouldest thou?\" David has to be asked what is happening inside his own kingdom.",
    '1:18': "The charge against the king is not cruelty but inattention: the kingdom is changing hands unnoticed.",
    '1:19': "She recites the guest list and ends on the omission, because the omission is the whole argument.",
    '1:20': "\"The eyes of all Israel are upon thee\" — a nation waits on one failing man to say a single name.",
    '1:21': "\"Counted offenders\" puts it plainly: when Adonijah is secure, she and her son are the loose ends.",
    '1:24': "Nathan asks whether the king said it rather than accusing him, leaving David room to answer as he likes.",
    '1:25': "\"God save king Adonijah\" is already being shouted, which turns further delay into a decision.",
    '1:27': "The prophet's last question offers David one honourable exit: say the thing was never your doing.",
    '1:29': "He swears by the God \"that hath redeemed my soul out of all distress.\" David dates his faith from his worst years.",
    '1:30': "\"This day\" — a promise made long ago is executed only under the pressure of losing it.",
    '1:33': "The king's own mule carries Solomon. The succession is shown in public before it is argued anywhere.",
    '1:34': "Priest and prophet anoint together, and a trumpet makes it public. Adonijah's feast had neither.",
    '1:35': "\"I have appointed him to be ruler.\" David finally uses the verb that ends the argument.",
    '1:36': "Benaiah's \"Amen\" asks the LORD to say so too. A coronation cannot supply that consent for itself.",
    '1:39': "The oil comes out of the tabernacle. The kingship is handed over from the place of worship, not the palace.",
    '1:40': "\"The earth rent with the sound.\" The noise itself becomes the news, carrying down the valley to Enrogel.",
    '1:41': "Joab hears a trumpet before he hears a word, and knows at once that something has gone against them.",
    '1:42': "\"Thou art a valiant man, and bringest good tidings\" — he names the message before he has heard it.",
    '1:43': "One sentence ends the reign of a man whose guests had already drunk his health.",
    '1:46': "\"Solomon sitteth on the throne.\" Present tense: while they were still eating, the thing was done.",
    '1:47': "David bows on the bed. The last exercise of the king's strength is worship he cannot stand up to offer.",
    '1:48': "\"Mine eyes even seeing it\" — the dying man's thanks is that he lived long enough to watch it land.",
    '1:49': "The guests rise and scatter. A movement built on a feast lasts precisely as long as the feast.",
    '1:50': "The horns of the altar are where a man runs when he has no case left, only a claim on mercy.",
    '1:51': "Adonijah asks for a sworn oath, knowing that his own word is now worth nothing to anybody.",
    '1:52': "Not a pardon but a probation. Life is granted on a condition, and the condition will be watched.",
    '1:53': "\"Go to thine house.\" The mercy is genuine and it is temporary, as the next chapter will show.",
    # ---- Chapter 2 ----
    '2:2': "\"Shew thyself a man\" — the charge is courage, and the chapter will test what Solomon thinks that means.",
    '2:3': "David's counsel is the law of Moses, unedited. The throne is not exempt from the book every Israelite has.",
    '2:4': "Unconditional to David, conditional to his sons. The whole history of the kings runs along that seam.",
    '2:5': "\"The blood of war in peace\" — the charge against Joab is exact: he killed when killing was murder.",
    '2:6': "\"According to thy wisdom.\" The first use of Solomon's famous gift is as a word for settling old scores.",
    '2:7': "Between two death sentences sits a debt of bread from the flight from Absalom. David remembers both kinds.",
    '2:8': "He quotes his own oath to Shimei, and in the same breath shows how it may be kept and got around.",
    '2:9': "\"Hold him not guiltless\" — the dying king hands his son the blood he swore he would not shed himself.",
    '2:10': "The shepherd, the psalmist, the adulterer, the king: one clause, and a grave in a city named for him.",
    '2:11': "Forty years compressed into a line. The record dates this reign as it dates every other, and moves on.",
    '2:12': "\"Established greatly\" is written before the killings, so the reader must hold the two together.",
    '2:13': "\"Comest thou peaceably?\" Bathsheba asks it outright, and accepts a single word for an answer.",
    '2:15': "He states his grievance and concedes the theology in one breath: \"it was his from the LORD.\"",
    '2:17': "Asking for the old king's nurse is asking for a piece of the old king's household, and he knows it.",
    '2:19': "Solomon rises, bows, and seats his mother at his right hand — then refuses her. Honour is not power.",
    '2:22': "\"Ask for him the kingdom also.\" Solomon hears the petition as a claim on the throne, and names its backers.",
    '2:23': "Sworn by the LORD, so that an execution becomes a vow no second thought is now permitted to loosen.",
    '2:24': "He grounds the death sentence in God's establishing of him. Piety and self-interest arrive in one sentence.",
    '2:25': "Benaiah's name recurs at each of these deaths. A throne is secured by somebody willing to do the work.",
    '2:26': "Abiathar is spared for carrying the ark and sharing David's afflictions. Old loyalty buys exile, not pardon.",
    '2:27': "The narrator reads a political purge as the word against Eli's house landing, generations after it was spoken.",
    '2:28': "\"Though he turned not after Absalom\" — Joab's one loyal moment is recorded just as it fails to save him.",
    '2:29': "The order is to strike at the altar itself, a thing the law of asylum had never contemplated.",
    '2:30': "\"Nay; but I will die here.\" The man who murdered two soldiers in cold blood pleads sanctuary and stays put.",
    '2:31': "The reason given is to clear innocent blood from David's house. The debt David let run is settled by his son.",
    '2:32': "\"More righteous and better than he\" — the verdict on Joab's victims is God's, not the court's convenience.",
    '2:33': "Blood on one head for ever, peace on the other for ever. The chapter's arithmetic is exactly that blunt.",
    '2:34': "Buried in his own house in the wilderness. Israel's longest-serving general gets no tomb in the city.",
    '2:35': "Benaiah for Joab, Zadok for Abiathar. The purge resolves into two appointments, which was always its point.",
    '2:36': "Shimei is not killed but fenced: house arrest with a city for a cell, and the terms are his to keep.",
    '2:37': "The boundary is a brook and the penalty is published in advance. Nothing is left for him to plead later.",
    '2:38': "\"The saying is good.\" He accepts the terms freely, which is what makes the later verdict unanswerable.",
    '2:39': "Three years of obedience undone by two runaway slaves. The trap needed only something he wanted more.",
    '2:40': "He saddles the ass himself. A man steps over a published sentence of death to recover his property.",
    '2:42': "Solomon recites the oath and Shimei's own assent to it. The prosecution is built entirely of the defendant's words.",
    '2:44': "The curse at Bahurim is named at last. Shimei dies for the brook, and for what the brook gave occasion to.",
    '2:46': "\"The kingdom was established in the hand of Solomon\" — established by wisdom, and by four graves.",
}

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "The reign's first recorded act is a marriage alliance with Egypt, the house Israel was brought out of.",
    '3:2': "The narrator excuses the high places and dates the excuse: \"until those days.\" The allowance will not last.",
    '3:3': "\"Solomon loved the LORD... only he sacrificed in high places.\" This book's verdicts nearly always carry an only.",
    '3:4': "A thousand burnt offerings at Gibeon. Devotion on that scale is not yet the same thing as obedience.",
    '3:5': "\"Ask what I shall give thee.\" God offers a blank cheque, and what a man writes on it exposes him.",
    '3:6': "He begins not with his request but with what God has already done for his father. Mercy first, then asking.",
    '3:7': "\"I am but a little child\" — said by a grown man who has just executed four enemies to secure the throne.",
    '3:8': "The difficulty he names is the size of God's people, not the size of his own ambition.",
    '3:9': "An understanding heart to judge, not to rule. He asks for what a courtroom needs, not what a palace wants.",
    '3:10': "God is pleased by the asking itself. What we ask for tells him, and us, what we believe we lack.",
    '3:11': "Long life, riches, the death of enemies — God lists what Solomon could have said, and did not.",
    '3:12': "The gift overshoots the request. Not enough wisdom for the job, but wisdom unmatched before or since.",
    '3:13': "\"That which thou hast not asked\" arrives as well, and the riches and honour are what finally undo him.",
    '3:14': "The wisdom is given outright; the long life is conditional. Even the best gift comes with a walk attached.",
    '3:15': "\"Behold, it was a dream\" — and he goes straight to the ark in Jerusalem rather than back to Gibeon.",
    '3:16': "Two prostitutes get direct access to the king. The new wisdom is tested on people nobody else would hear.",
    '3:20': "The swap is alleged to have happened while she slept, which is exactly why she cannot prove any of it.",
    '3:21': "\"When I had considered it in the morning\" — she knew her own child by daylight, and not a moment sooner.",
    '3:24': "\"Bring me a sword.\" For one moment the wisdom of God looks like the worst ruling ever handed down.",
    '3:25': "Split it evenly, half to each. The chapter lets us see what perfect fairness would actually cost.",
    '3:26': "Love gives the child away rather than watch it die. The other would rather neither of them had him.",
    '3:27': "The test worked because only a mother would rather lose the case than win the corpse.",
    '3:28': "They feared the king because they saw the wisdom was God's. The awe runs past the judge to the giver.",
    # ---- Chapter 4 ----
    '4:1': "\"King over all Israel\" — one line of settled fact, with the whole cost of keeping it still to come.",
    '4:6': "Adoniram is listed calmly here as the man over the tribute. In chapter twelve Israel stones him for it.",
    '4:7': "Twelve officers, a month each. The country is reorganised around feeding one household all year.",
    '4:11': "Solomon marries his daughters to his own district officers. Family and administration are one instrument.",
    '4:19': "\"He was the only officer which was in the land.\" Even a roster notices where its own pattern breaks.",
    '4:20': "\"As the sand which is by the sea\" — Abraham's promise quoted to describe a people eating and making merry.",
    '4:21': "An empire from the river to Egypt, held by tribute rather than by garrisons. Bought peace is still peace.",
    '4:22': "The flour for one day is counted in measures a village would eat in a year. Glory keeps a grocery bill.",
    '4:23': "Thirty head of cattle a day, plus game. The king's table is the kingdom's showpiece and its standing charge.",
    '4:24': "\"He had peace on all sides round about him.\" The rest David fought for is what Solomon inherits to spend.",
    '4:25': "Every man under his vine and fig tree — a picture the prophets will still be reaching for centuries later.",
    '4:26': "Forty thousand stalls of horses, against a law that told Israel's king plainly not to multiply them.",
    '4:27': "\"They lacked nothing\" is said of the king's table. It is not said of the districts that supplied it.",
    '4:28': "Barley and straw brought by quota, every man according to his charge. Splendour is assessed on somebody.",
    '4:29': "Largeness of heart, given by God. This wisdom is a capacity for the whole world, not only for hard cases.",
    '4:30': "His wisdom is measured against Egypt and the east, the very nations Israel was warned not to imitate.",
    '4:31': "Named rivals, all surpassed, and his fame in all nations. The book is tracking the fame as closely as the wisdom.",
    '4:32': "Three thousand proverbs and a thousand and five songs, and almost every one of them is simply lost.",
    '4:33': "From the cedar of Lebanon to the hyssop in the wall. The wise man's proper subject is the whole creation.",
    '4:34': "Kings of the earth come to listen. The nations gathering to hear is the high-water mark of this reign.",
    # ---- Chapter 5 ----
    '5:1': "Hiram sends first, for love of David. The great project begins in a friendship Solomon did not make.",
    '5:3': "David could not build, because of the wars. A calling can be limited by the very work God assigned.",
    '5:4': "\"Neither adversary nor evil occurrent\" — the temple goes up in the one long quiet Israel ever had.",
    '5:5': "He builds because the word said his son would, not because the idea was his. Obedience, not initiative.",
    '5:6': "Israel has the commission and Tyre has the craftsmen. The LORD's house needs foreign skill to be built at all.",
    '5:7': "A Phoenician king blesses the LORD for David's wise son. Outsiders keep noticing before Israel does.",
    '5:9': "Cedar floated down the coast in rafts and paid for in food. Worship gets built out of ordinary logistics.",
    '5:11': "Twenty thousand measures of wheat, year by year. The temple is paid for out of Israel's harvest.",
    '5:12': "The LORD gave the wisdom, and the treaty with Hiram is what that wisdom looked like in daily practice.",
    '5:13': "A levy of thirty thousand raised out of all Israel. Egypt had a word for this arrangement too.",
    '5:14': "A month in Lebanon and two at home. The rota is humane, and it is still forced labour under Adoniram.",
    '5:15': "Seventy thousand bearers and eighty thousand hewers in the hills. The house of prayer rests on those numbers.",
    '5:17': "Great stones, costly stones, hewed stones — the foundation no worshipper would ever see is made of the best.",
    '5:18': "Two kings' builders working side by side, preparing every stone and beam before a single wall goes up.",
})

TAKEAWAYS.update({
    # ---- Chapter 6 ----
    '6:1': "The temple is dated from the exodus, not from the king. The house is measured against the rescue that made a people.",
    '6:2': "Sixty cubits by twenty. For all the gold to come, the building itself is smaller than many a parish church.",
    '6:4': "Windows of narrow lights, wide within and narrow without. Whatever light is in there comes from outside.",
    '6:6': "The beams rest on ledges rather than being fastened into the walls. Nothing is driven into the holy house.",
    '6:7': "Neither hammer nor axe nor tool of iron heard in the house. Every rough cut was made somewhere out of hearing.",
    '6:9': "\"So he built the house, and finished it\" — said here and again five verses on, with a warning set between.",
    '6:12': "God interrupts the building to say the house is not the point: walk in my statutes, and then my word stands.",
    '6:13': "The promise is to dwell among the children of Israel. The people are the dwelling; the building only marks it.",
    '6:14': "The sentence resumes exactly where it broke off. Solomon heard the condition and went back to laying cedar.",
    '6:15': "Cedar over floor, walls and ceiling. The structure is lined until none of its own fabric is left in view.",
    '6:18': "\"There was no stone seen.\" The costliest building in Israel's history conceals what it is actually made of.",
    '6:19': "All of it is for one purpose: somewhere to set the ark. The house exists to hold a box with a covenant inside.",
    '6:20': "A perfect cube overlaid with gold. The most finished room in the kingdom is the one nobody may enter.",
    '6:21': "Chains of gold drawn across the entrance. The way in is closed at the same moment the work is completed.",
    '6:22': "Gold until the whole house is finished. Nothing here is held back, and nothing is done to a lesser standard.",
    '6:23': "Two cherubim of olive wood, ten cubits high. The guards who kept Eden's gate now stand over the ark.",
    '6:27': "Wingtip to wall and wing to wing, right across the room. The cherubim fill the space no worshipper may enter.",
    '6:29': "Cherubim, palm trees and open flowers on every wall, within and without. The room is carved to look like a garden.",
    '6:30': "Gold on the floor as well, where only feet would touch. Nothing here is graded by whether anyone would notice.",
    '6:32': "The doors carry the garden too, so that going in means passing back through what was lost at the beginning.",
    '6:36': "Three courses of stone to one of cedar around the inner court. Even the boundary is laid to a rule.",
    '6:38': "Seven years to build the house of the LORD — a figure worth holding on to as the next chapter starts counting.",
    # ---- Chapter 7 ----
    '7:1': "Thirteen years on his own house against seven on God's. The book sets the two numbers side by side and says nothing.",
    '7:2': "His hall of Lebanon runs a hundred cubits, near twice the temple's length. Proportion shows what a man ranks first.",
    '7:7': "A porch of judgment, cedar from wall to wall, where the king would hear cases. Justice is given its own room.",
    '7:8': "A separate house for Pharaoh's daughter. The Egyptian marriage has become architecture, permanent and on the plan.",
    '7:9': "Costly stones sawed within and without, even on faces nobody would ever stand in front of.",
    '7:10': "Foundation stones of eight and ten cubits. What holds a palace up is the part that will never be admired.",
    '7:12': "The great court is built to the same pattern as the LORD's. Palace and temple stand as one complex, by design.",
    '7:13': "Solomon sends to Tyre for Hiram. The man who casts the sacred vessels has to be fetched from outside Israel.",
    '7:14': "A widow's son of Naphtali, \"filled with wisdom, and understanding\" — the vocabulary of chapter three, applied to brass.",
    '7:15': "Two brass pillars eighteen cubits high, bearing no roof. Their entire purpose is to be seen and understood.",
    '7:21': "Jachin and Boaz: he establishes, in him is strength. The doorway is a sentence about God, not about the king.",
    '7:22': "Lily work on the top of the pillars. Even cast brass is made to flower.",
    '7:23': "A molten sea ten cubits across for washing. Approach to God starts with somebody getting clean first.",
    '7:25': "Twelve oxen facing out to the four quarters, hinder parts inward. The tribes carry the water and are not on display.",
    '7:26': "Two thousand baths of water, with a brim wrought like a cup. Tons of washing, in a vessel shaped for beauty.",
    '7:29': "Lions, oxen and cherubim on the panels. Even the wheeled washstands carry the creation on their sides.",
    '7:33': "The wheels are made like chariot wheels, naves and felloes and spokes. The craftsman built from what he knew.",
    '7:37': "\"One casting, one measure, and one size.\" Ten identical stands, because this worship is not improvised locally.",
    '7:38': "Ten lavers of forty baths each. The volume of water tells you the volume of blood the altar expected.",
    '7:39': "Five on the right, five on the left, the sea to the south. Everything is placed, and the placing is written down.",
    '7:40': "The list ends with lavers, shovels and basons. The holiest place in Israel is run with ordinary implements.",
    '7:45': "\"Bright brass\" — even the pots and shovels are polished. Nothing used before God is allowed to look neglected.",
    '7:46': "Cast in the clay ground of the Jordan plain. The temple's furnishings were made in a riverbed days away from it.",
    '7:47': "Left unweighed because they were too many. At the height of this reign the accounting simply gives up.",
    '7:48': "An altar of gold and a table with bread always on it. Inside the house, God is approached at a table that is set.",
    '7:49': "Ten candlesticks of pure gold, with flowers and lamps and tongs. The light has to be tended by hand, every day.",
    '7:50': "Even the hinges are gold. In rooms almost nobody enters, the parts nobody sees are made of the best material.",
    '7:51': "David's dedicated silver and gold go into the treasury at last. The father's offering reaches the house he never built.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "Elders, heads and chiefs are gathered first. The ark moves only with the whole people standing there to watch.",
    '8:2': "The seventh month, at the feast — Tabernacles, when Israel remembered living in tents. The timing is chosen.",
    '8:4': "The tabernacle comes up too. The tent that travelled for centuries is retired into the building that replaced it.",
    '8:6': "The ark goes in under the wings and stops moving. Everything since Sinai has been travelling toward this room.",
    '8:7': "The cherubim cover the ark and its staves. The wings of those who stay spread over the gear of those who moved.",
    '8:8': "The poles are drawn out so their ends show inside and not without. The ark keeps its travelling equipment on.",
    '8:9': "Nothing in the ark but two tables of stone. At the centre of all this gold lies the law that accuses.",
    '8:10': "The cloud fills the house the moment the priests step out. God's arrival is not timed to fit the liturgy.",
    '8:11': "The priests could not stand to minister. Glory's first effect in the new temple is that the service stops.",
    '8:12': "\"He would dwell in the thick darkness.\" Presence and concealment arrive together, in the same cloud.",
    '8:13': "\"A settled place for thee to abide in for ever\" — a sentence the rest of this book will quietly take apart.",
    '8:15': "\"Spake with his mouth... fulfilled it with his hand.\" His first word about the house is about God's reliability.",
    '8:16': "God chose no city until he had chosen a man. The place follows the person, not the other way about.",
    '8:17': "\"It was in the heart of David\" — the temple was another man's longing long before it was this king's project.",
    '8:18': "\"Thou didst well that it was in thine heart.\" The desire is commended and the permission is still withheld.",
    '8:19': "Not you, but your son. The refusal and the promise are one sentence, and David had to hear both at once.",
    '8:20': "Solomon can list the performance point by point. He is standing inside somebody else's promise, kept.",
    '8:21': "A house for the ark, and the ark for the covenant. Layer upon layer of container around a spoken word.",
    '8:22': "Hands spread toward heaven in front of the whole congregation. The king prays as one of the people, not over them.",
    '8:23': "God's incomparability is stated as covenant and mercy rather than power. What is unique is that he keeps his word.",
    '8:25': "He presses the promise to David and quotes its condition in the same breath. Solomon knows both halves by heart.",
    '8:27': "\"Will God indeed dwell on the earth?\" The builder says out loud that the building cannot hold what it is for.",
    '8:28': "\"Yet have thou respect.\" The impossibility is granted, and he asks anyway. That is the shape faith actually takes.",
    '8:29': "He asks only that God's eyes be open toward the place where his name is. Attention is requested, not residence.",
    '8:30': "\"And when thou hearest, forgive.\" Every petition in this long prayer bends toward that one verb.",
    '8:31': "The first case imagined is a quarrel between neighbours. The temple's opening use is ordinary justice.",
    '8:32': "Condemn the wicked, justify the righteous. God is asked to be the court that no human court manages to be.",
    '8:33': "Defeat is read as consequence rather than accident, and the road back is confession, not a better army.",
    '8:34': "Forgive, and bring them again. Restoration to the land follows the pardon; it never stands in for it.",
    '8:35': "Drought is named as discipline with a purpose, and the purpose is turning rather than suffering.",
    '8:36': "\"That thou teach them the good way\" — he asks for instruction before he gets round to asking for rain.",
    '8:37': "Famine, mildew, locust, siege, whatsoever plague. The prayer refuses to promise a life without disaster in it.",
    '8:38': "\"Every man the plague of his own heart.\" The worst trouble in the list is the one nobody else can see.",
    '8:39': "\"Thou only knowest the hearts.\" Because God alone sees, God alone can forgive without being deceived.",
    '8:41': "\"Concerning a stranger, that is not of thy people\" — the foreigner gets his own clause in Israel's great prayer.",
    '8:42': "The stranger comes because he has heard. Reports of what God has done are how outsiders learn there is anything to ask.",
    '8:43': "For Israel he asks forgiveness; for the stranger he asks God to do all that he calls for. The outsider is not rationed.",
    '8:44': "Even in war the prayer is aimed at a house rather than at the enemy. Battle is carried back to the place of mercy.",
    '8:46': "\"For there is no man that sinneth not.\" The prayer builds exile into its plan because it expects failure.",
    '8:47': "\"We have sinned, and have done perversely.\" Solomon writes the confession for a generation not yet born.",
    '8:48': "Praying toward a land they cannot see, from the country they were dragged to. Direction is what is left of hope.",
    '8:50': "He asks not for release but for compassion from the captors. Mercy is expected to arrive through the enemy's hands.",
    '8:51': "\"The furnace of iron\" — the argument for a rescue not yet needed is a rescue God has already performed.",
    '8:53': "The ground under the whole prayer is election: you separated them, and you said so by the hand of Moses.",
    '8:54': "The king had been kneeling. The record waits until he rises before it tells us he was ever on his knees.",
    '8:56': "\"There hath not failed one word of all his good promise.\" The verdict on God comes from a man who has counted.",
    '8:57': "\"Let him not leave us, nor forsake us\" — prayed on the best day this kingdom will ever have.",
    '8:58': "\"That he may incline our hearts.\" Obedience is asked for as a gift, not resolved upon as a policy.",
    '8:60': "The end of Israel's blessing is that all the earth should know. The nations were the point of the choosing.",
    '8:61': "\"As at this day\" — the hard charge is to go on being what you are on a day when everything is going well.",
    '8:63': "Twenty-two thousand oxen and a hundred and twenty thousand sheep. The dedication is measured out in slaughter.",
    '8:64': "The brazen altar was too small, so the court itself had to be hallowed. Even the provision could not keep pace.",
    '8:65': "Fourteen days, and a congregation reaching from Hamath to the river of Egypt. The kingdom at its widest extent.",
    '8:66': "They go home glad for the goodness done \"for David his servant.\" On Solomon's greatest day the credit goes back.",
})
