#!/usr/bin/env python3
"""Written one-line takeaways for 1 Kings, chapters 1-22."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The man who killed Goliath cannot keep warm under blankets. The book opens on a king's body failing.",
    '1:2': "The court's remedy for a dying king is a policy about his body. Nobody asks him whether he wants it.",
    '1:4': "\"But the king knew her not.\" The note is about David's strength, and the whole court can read it.",
    '1:5': "\"I will be king\" — Adonijah does not wait to be told. Chariots and fifty runners, exactly as Absalom did.",
    '1:6': "\"His father had not displeased him at any time.\" A son's revolt traced to a father who never once asked why.",
    '1:7': "Joab and Abiathar: the general and the priest. The coup is carried by David's oldest surviving allies.",
    '1:8': "The list of who refused is as exact as the list of who joined. This book keeps count of loyalties.",
    '1:9': "A feast is a coronation without the word — sacrifice, guests, a chosen place, everything but an anointing.",
    '1:10': "Solomon was not invited. In a succession, the man left off the guest list is the man being ruled out.",
    '1:11': "Nathan goes to Bathsheba, not to David. The prophet who once accused the king now works around him.",
    '1:12': "\"Save thine own life\" — Nathan is blunt that a losing claimant's mother does not outlive the winner.",
    '1:13': "Nathan supplies her words, and the oath she is to cite is one the reader has never heard David swear.",
    '1:14': "Two witnesses arriving separately, so that one prepared account will sound like independent confirmation.",
    '1:15': "The narrator shows us the room: a very old king, and another woman already standing at his side.",
    '1:16': "\"What wouldest thou?\" David has to be asked what is happening inside his own kingdom.",
    '1:18': "The charge against the king is not cruelty but inattention: the kingdom is changing hands unnoticed.",
    '1:19': "She recites the guest list and ends on the omission, because the omission is the whole argument.",
    '1:20': "\"The eyes of all Israel are upon thee\" — a nation waits on one failing man to say a single name.",
    '1:21': "\"Counted offenders\" puts it plainly: when Adonijah is secure, she and her son are the loose ends.",
    '1:24': "Nathan asks whether the king said it rather than accusing him, leaving David room to answer as he likes.",
    '1:25': "\"God save king Adonijah\" is already being shouted, which turns further delay into a decision.",
    '1:27': "The prophet's last question offers David one honourable exit: say the thing was never your doing.",
    '1:29': "He swears by the God \"that hath redeemed my soul out of all distress.\" David dates his faith from his worst years.",
    '1:30': "\"This day\" — a promise made long ago is executed only under the pressure of losing it.",
    '1:33': "The king's own mule carries Solomon. The succession is shown in public before it is argued anywhere.",
    '1:34': "Priest and prophet anoint together, and a trumpet makes it public. Adonijah's feast had neither.",
    '1:35': "\"I have appointed him to be ruler.\" David finally uses the verb that ends the argument.",
    '1:36': "Benaiah's \"Amen\" asks the LORD to say so too. A coronation cannot supply that consent for itself.",
    '1:39': "The oil comes out of the tabernacle. The kingship is handed over from the place of worship, not the palace.",
    '1:40': "\"The earth rent with the sound.\" The noise itself becomes the news, carrying down the valley to Enrogel.",
    '1:41': "Joab hears a trumpet before he hears a word, and knows at once that something has gone against them.",
    '1:42': "\"Thou art a valiant man, and bringest good tidings\" — he names the message before he has heard it.",
    '1:43': "One sentence ends the reign of a man whose guests had already drunk his health.",
    '1:46': "\"Solomon sitteth on the throne.\" Present tense: while they were still eating, the thing was done.",
    '1:47': "David bows on the bed. The last exercise of the king's strength is worship he cannot stand up to offer.",
    '1:48': "\"Mine eyes even seeing it\" — the dying man's thanks is that he lived long enough to watch it land.",
    '1:49': "The guests rise and scatter. A movement built on a feast lasts precisely as long as the feast.",
    '1:50': "The horns of the altar are where a man runs when he has no case left, only a claim on mercy.",
    '1:51': "Adonijah asks for a sworn oath, knowing that his own word is now worth nothing to anybody.",
    '1:52': "Not a pardon but a probation. Life is granted on a condition, and the condition will be watched.",
    '1:53': "\"Go to thine house.\" The mercy is genuine and it is temporary, as the next chapter will show.",
    # ---- Chapter 2 ----
    '2:2': "\"Shew thyself a man\" — the charge is courage, and the chapter will test what Solomon thinks that means.",
    '2:3': "David's counsel is the law of Moses, unedited. The throne is not exempt from the book every Israelite has.",
    '2:4': "Unconditional to David, conditional to his sons. The whole history of the kings runs along that seam.",
    '2:5': "\"The blood of war in peace\" — the charge against Joab is exact: he killed when killing was murder.",
    '2:6': "\"According to thy wisdom.\" The first use of Solomon's famous gift is as a word for settling old scores.",
    '2:7': "Between two death sentences sits a debt of bread from the flight from Absalom. David remembers both kinds.",
    '2:8': "He quotes his own oath to Shimei, and in the same breath shows how it may be kept and got around.",
    '2:9': "\"Hold him not guiltless\" — the dying king hands his son the blood he swore he would not shed himself.",
    '2:10': "The shepherd, the psalmist, the adulterer, the king: one clause, and a grave in a city named for him.",
    '2:11': "Forty years compressed into a line. The record dates this reign as it dates every other, and moves on.",
    '2:12': "\"Established greatly\" is written before the killings, so the reader must hold the two together.",
    '2:13': "\"Comest thou peaceably?\" Bathsheba asks it outright, and accepts a single word for an answer.",
    '2:15': "He states his grievance and concedes the theology in one breath: \"it was his from the LORD.\"",
    '2:17': "Asking for the old king's nurse is asking for a piece of the old king's household, and he knows it.",
    '2:19': "Solomon rises, bows, and seats his mother at his right hand — then refuses her. Honour is not power.",
    '2:22': "\"Ask for him the kingdom also.\" Solomon hears the petition as a claim on the throne, and names its backers.",
    '2:23': "Sworn by the LORD, so that an execution becomes a vow no second thought is now permitted to loosen.",
    '2:24': "He grounds the death sentence in God's establishing of him. Piety and self-interest arrive in one sentence.",
    '2:25': "Benaiah's name recurs at each of these deaths. A throne is secured by somebody willing to do the work.",
    '2:26': "Abiathar is spared for carrying the ark and sharing David's afflictions. Old loyalty buys exile, not pardon.",
    '2:27': "The narrator reads a political purge as the word against Eli's house landing, generations after it was spoken.",
    '2:28': "\"Though he turned not after Absalom\" — Joab's one loyal moment is recorded just as it fails to save him.",
    '2:29': "The order is to strike at the altar itself, a thing the law of asylum had never contemplated.",
    '2:30': "\"Nay; but I will die here.\" The man who murdered two soldiers in cold blood pleads sanctuary and stays put.",
    '2:31': "The reason given is to clear innocent blood from David's house. The debt David let run is settled by his son.",
    '2:32': "\"More righteous and better than he\" — the verdict on Joab's victims is God's, not the court's convenience.",
    '2:33': "Blood on one head for ever, peace on the other for ever. The chapter's arithmetic is exactly that blunt.",
    '2:34': "Buried in his own house in the wilderness. Israel's longest-serving general gets no tomb in the city.",
    '2:35': "Benaiah for Joab, Zadok for Abiathar. The purge resolves into two appointments, which was always its point.",
    '2:36': "Shimei is not killed but fenced: house arrest with a city for a cell, and the terms are his to keep.",
    '2:37': "The boundary is a brook and the penalty is published in advance. Nothing is left for him to plead later.",
    '2:38': "\"The saying is good.\" He accepts the terms freely, which is what makes the later verdict unanswerable.",
    '2:39': "Three years of obedience undone by two runaway slaves. The trap needed only something he wanted more.",
    '2:40': "He saddles the ass himself. A man steps over a published sentence of death to recover his property.",
    '2:42': "Solomon recites the oath and Shimei's own assent to it. The prosecution is built entirely of the defendant's words.",
    '2:44': "The curse at Bahurim is named at last. Shimei dies for the brook, and for what the brook gave occasion to.",
    '2:46': "\"The kingdom was established in the hand of Solomon\" — established by wisdom, and by four graves.",
}

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "The reign's first recorded act is a marriage alliance with Egypt, the house Israel was brought out of.",
    '3:2': "The narrator excuses the high places and dates the excuse: \"until those days.\" The allowance will not last.",
    '3:3': "\"Solomon loved the LORD... only he sacrificed in high places.\" This book's verdicts nearly always carry an only.",
    '3:4': "A thousand burnt offerings at Gibeon. Devotion on that scale is not yet the same thing as obedience.",
    '3:5': "\"Ask what I shall give thee.\" God offers a blank cheque, and what a man writes on it exposes him.",
    '3:6': "He begins not with his request but with what God has already done for his father. Mercy first, then asking.",
    '3:7': "\"I am but a little child\" — said by a grown man who has just executed four enemies to secure the throne.",
    '3:8': "The difficulty he names is the size of God's people, not the size of his own ambition.",
    '3:9': "An understanding heart to judge, not to rule. He asks for what a courtroom needs, not what a palace wants.",
    '3:10': "God is pleased by the asking itself. What we ask for tells him, and us, what we believe we lack.",
    '3:11': "Long life, riches, the death of enemies — God lists what Solomon could have said, and did not.",
    '3:12': "The gift overshoots the request. Not enough wisdom for the job, but wisdom unmatched before or since.",
    '3:13': "\"That which thou hast not asked\" arrives as well, and the riches and honour are what finally undo him.",
    '3:14': "The wisdom is given outright; the long life is conditional. Even the best gift comes with a walk attached.",
    '3:15': "\"Behold, it was a dream\" — and he goes straight to the ark in Jerusalem rather than back to Gibeon.",
    '3:16': "Two prostitutes get direct access to the king. The new wisdom is tested on people nobody else would hear.",
    '3:20': "The swap is alleged to have happened while she slept, which is exactly why she cannot prove any of it.",
    '3:21': "\"When I had considered it in the morning\" — she knew her own child by daylight, and not a moment sooner.",
    '3:24': "\"Bring me a sword.\" For one moment the wisdom of God looks like the worst ruling ever handed down.",
    '3:25': "Split it evenly, half to each. The chapter lets us see what perfect fairness would actually cost.",
    '3:26': "Love gives the child away rather than watch it die. The other would rather neither of them had him.",
    '3:27': "The test worked because only a mother would rather lose the case than win the corpse.",
    '3:28': "They feared the king because they saw the wisdom was God's. The awe runs past the judge to the giver.",
    # ---- Chapter 4 ----
    '4:1': "\"King over all Israel\" — one line of settled fact, with the whole cost of keeping it still to come.",
    '4:6': "Adoniram is listed calmly here as the man over the tribute. In chapter twelve Israel stones him for it.",
    '4:7': "Twelve officers, a month each. The country is reorganised around feeding one household all year.",
    '4:11': "Solomon marries his daughters to his own district officers. Family and administration are one instrument.",
    '4:19': "\"He was the only officer which was in the land.\" Even a roster notices where its own pattern breaks.",
    '4:20': "\"As the sand which is by the sea\" — Abraham's promise quoted to describe a people eating and making merry.",
    '4:21': "An empire from the river to Egypt, held by tribute rather than by garrisons. Bought peace is still peace.",
    '4:22': "The flour for one day is counted in measures a village would eat in a year. Glory keeps a grocery bill.",
    '4:23': "Thirty head of cattle a day, plus game. The king's table is the kingdom's showpiece and its standing charge.",
    '4:24': "\"He had peace on all sides round about him.\" The rest David fought for is what Solomon inherits to spend.",
    '4:25': "Every man under his vine and fig tree — a picture the prophets will still be reaching for centuries later.",
    '4:26': "Forty thousand stalls of horses, against a law that told Israel's king plainly not to multiply them.",
    '4:27': "\"They lacked nothing\" is said of the king's table. It is not said of the districts that supplied it.",
    '4:28': "Barley and straw brought by quota, every man according to his charge. Splendour is assessed on somebody.",
    '4:29': "Largeness of heart, given by God. This wisdom is a capacity for the whole world, not only for hard cases.",
    '4:30': "His wisdom is measured against Egypt and the east, the very nations Israel was warned not to imitate.",
    '4:31': "Named rivals, all surpassed, and his fame in all nations. The book is tracking the fame as closely as the wisdom.",
    '4:32': "Three thousand proverbs and a thousand and five songs, and almost every one of them is simply lost.",
    '4:33': "From the cedar of Lebanon to the hyssop in the wall. The wise man's proper subject is the whole creation.",
    '4:34': "Kings of the earth come to listen. The nations gathering to hear is the high-water mark of this reign.",
    # ---- Chapter 5 ----
    '5:1': "Hiram sends first, for love of David. The great project begins in a friendship Solomon did not make.",
    '5:3': "David could not build, because of the wars. A calling can be limited by the very work God assigned.",
    '5:4': "\"Neither adversary nor evil occurrent\" — the temple goes up in the one long quiet Israel ever had.",
    '5:5': "He builds because the word said his son would, not because the idea was his. Obedience, not initiative.",
    '5:6': "Israel has the commission and Tyre has the craftsmen. The LORD's house needs foreign skill to be built at all.",
    '5:7': "A Phoenician king blesses the LORD for David's wise son. Outsiders keep noticing before Israel does.",
    '5:9': "Cedar floated down the coast in rafts and paid for in food. Worship gets built out of ordinary logistics.",
    '5:11': "Twenty thousand measures of wheat, year by year. The temple is paid for out of Israel's harvest.",
    '5:12': "The LORD gave the wisdom, and the treaty with Hiram is what that wisdom looked like in daily practice.",
    '5:13': "A levy of thirty thousand raised out of all Israel. Egypt had a word for this arrangement too.",
    '5:14': "A month in Lebanon and two at home. The rota is humane, and it is still forced labour under Adoniram.",
    '5:15': "Seventy thousand bearers and eighty thousand hewers in the hills. The house of prayer rests on those numbers.",
    '5:17': "Great stones, costly stones, hewed stones — the foundation no worshipper would ever see is made of the best.",
    '5:18': "Two kings' builders working side by side, preparing every stone and beam before a single wall goes up.",
})
