#!/usr/bin/env python3
"""Written one-line takeaways for 1 Kings, chapters 1-22."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The man who killed Goliath cannot keep warm under blankets. The book opens on a king's body failing.",
    '1:2': "The court's remedy for a dying king is a policy about his body. Nobody asks him whether he wants it.",
    '1:4': "\"But the king knew her not.\" The note is about David's strength, and the whole court can read it.",
    '1:5': "\"I will be king\" — Adonijah does not wait to be told. Chariots and fifty runners, exactly as Absalom did.",
    '1:6': "\"His father had not displeased him at any time.\" A son's revolt traced to a father who never once asked why.",
    '1:7': "Joab and Abiathar: the general and the priest. The coup is carried by David's oldest surviving allies.",
    '1:8': "The list of who refused is as exact as the list of who joined. This book keeps count of loyalties.",
    '1:9': "A feast is a coronation without the word — sacrifice, guests, a chosen place, everything but an anointing.",
    '1:10': "Solomon was not invited. In a succession, the man left off the guest list is the man being ruled out.",
    '1:11': "Nathan goes to Bathsheba, not to David. The prophet who once accused the king now works around him.",
    '1:12': "\"Save thine own life\" — Nathan is blunt that a losing claimant's mother does not outlive the winner.",
    '1:13': "Nathan supplies her words, and the oath she is to cite is one the reader has never heard David swear.",
    '1:14': "Two witnesses arriving separately, so that one prepared account will sound like independent confirmation.",
    '1:15': "The narrator shows us the room: a very old king, and another woman already standing at his side.",
    '1:16': "\"What wouldest thou?\" David has to be asked what is happening inside his own kingdom.",
    '1:18': "The charge against the king is not cruelty but inattention: the kingdom is changing hands unnoticed.",
    '1:19': "She recites the guest list and ends on the omission, because the omission is the whole argument.",
    '1:20': "\"The eyes of all Israel are upon thee\" — a nation waits on one failing man to say a single name.",
    '1:21': "\"Counted offenders\" puts it plainly: when Adonijah is secure, she and her son are the loose ends.",
    '1:24': "Nathan asks whether the king said it rather than accusing him, leaving David room to answer as he likes.",
    '1:25': "\"God save king Adonijah\" is already being shouted, which turns further delay into a decision.",
    '1:27': "The prophet's last question offers David one honourable exit: say the thing was never your doing.",
    '1:29': "He swears by the God \"that hath redeemed my soul out of all distress.\" David dates his faith from his worst years.",
    '1:30': "\"This day\" — a promise made long ago is executed only under the pressure of losing it.",
    '1:33': "The king's own mule carries Solomon. The succession is shown in public before it is argued anywhere.",
    '1:34': "Priest and prophet anoint together, and a trumpet makes it public. Adonijah's feast had neither.",
    '1:35': "\"I have appointed him to be ruler.\" David finally uses the verb that ends the argument.",
    '1:36': "Benaiah's \"Amen\" asks the LORD to say so too. A coronation cannot supply that consent for itself.",
    '1:39': "The oil comes out of the tabernacle. The kingship is handed over from the place of worship, not the palace.",
    '1:40': "\"The earth rent with the sound.\" The noise itself becomes the news, carrying down the valley to Enrogel.",
    '1:41': "Joab hears a trumpet before he hears a word, and knows at once that something has gone against them.",
    '1:42': "\"Thou art a valiant man, and bringest good tidings\" — he names the message before he has heard it.",
    '1:43': "One sentence ends the reign of a man whose guests had already drunk his health.",
    '1:46': "\"Solomon sitteth on the throne.\" Present tense: while they were still eating, the thing was done.",
    '1:47': "David bows on the bed. The last exercise of the king's strength is worship he cannot stand up to offer.",
    '1:48': "\"Mine eyes even seeing it\" — the dying man's thanks is that he lived long enough to watch it land.",
    '1:49': "The guests rise and scatter. A movement built on a feast lasts precisely as long as the feast.",
    '1:50': "The horns of the altar are where a man runs when he has no case left, only a claim on mercy.",
    '1:51': "Adonijah asks for a sworn oath, knowing that his own word is now worth nothing to anybody.",
    '1:52': "Not a pardon but a probation. Life is granted on a condition, and the condition will be watched.",
    '1:53': "\"Go to thine house.\" The mercy is genuine and it is temporary, as the next chapter will show.",
    # ---- Chapter 2 ----
    '2:2': "\"Shew thyself a man\" — the charge is courage, and the chapter will test what Solomon thinks that means.",
    '2:3': "David's counsel is the law of Moses, unedited. The throne is not exempt from the book every Israelite has.",
    '2:4': "Unconditional to David, conditional to his sons. The whole history of the kings runs along that seam.",
    '2:5': "\"The blood of war in peace\" — the charge against Joab is exact: he killed when killing was murder.",
    '2:6': "\"According to thy wisdom.\" The first use of Solomon's famous gift is as a word for settling old scores.",
    '2:7': "Between two death sentences sits a debt of bread from the flight from Absalom. David remembers both kinds.",
    '2:8': "He quotes his own oath to Shimei, and in the same breath shows how it may be kept and got around.",
    '2:9': "\"Hold him not guiltless\" — the dying king hands his son the blood he swore he would not shed himself.",
    '2:10': "The shepherd, the psalmist, the adulterer, the king: one clause, and a grave in a city named for him.",
    '2:11': "Forty years compressed into a line. The record dates this reign as it dates every other, and moves on.",
    '2:12': "\"Established greatly\" is written before the killings, so the reader must hold the two together.",
    '2:13': "\"Comest thou peaceably?\" Bathsheba asks it outright, and accepts a single word for an answer.",
    '2:15': "He states his grievance and concedes the theology in one breath: \"it was his from the LORD.\"",
    '2:17': "Asking for the old king's nurse is asking for a piece of the old king's household, and he knows it.",
    '2:19': "Solomon rises, bows, and seats his mother at his right hand — then refuses her. Honour is not power.",
    '2:22': "\"Ask for him the kingdom also.\" Solomon hears the petition as a claim on the throne, and names its backers.",
    '2:23': "Sworn by the LORD, so that an execution becomes a vow no second thought is now permitted to loosen.",
    '2:24': "He grounds the death sentence in God's establishing of him. Piety and self-interest arrive in one sentence.",
    '2:25': "Benaiah's name recurs at each of these deaths. A throne is secured by somebody willing to do the work.",
    '2:26': "Abiathar is spared for carrying the ark and sharing David's afflictions. Old loyalty buys exile, not pardon.",
    '2:27': "The narrator reads a political purge as the word against Eli's house landing, generations after it was spoken.",
    '2:28': "\"Though he turned not after Absalom\" — Joab's one loyal moment is recorded just as it fails to save him.",
    '2:29': "The order is to strike at the altar itself, a thing the law of asylum had never contemplated.",
    '2:30': "\"Nay; but I will die here.\" The man who murdered two soldiers in cold blood pleads sanctuary and stays put.",
    '2:31': "The reason given is to clear innocent blood from David's house. The debt David let run is settled by his son.",
    '2:32': "\"More righteous and better than he\" — the verdict on Joab's victims is God's, not the court's convenience.",
    '2:33': "Blood on one head for ever, peace on the other for ever. The chapter's arithmetic is exactly that blunt.",
    '2:34': "Buried in his own house in the wilderness. Israel's longest-serving general gets no tomb in the city.",
    '2:35': "Benaiah for Joab, Zadok for Abiathar. The purge resolves into two appointments, which was always its point.",
    '2:36': "Shimei is not killed but fenced: house arrest with a city for a cell, and the terms are his to keep.",
    '2:37': "The boundary is a brook and the penalty is published in advance. Nothing is left for him to plead later.",
    '2:38': "\"The saying is good.\" He accepts the terms freely, which is what makes the later verdict unanswerable.",
    '2:39': "Three years of obedience undone by two runaway slaves. The trap needed only something he wanted more.",
    '2:40': "He saddles the ass himself. A man steps over a published sentence of death to recover his property.",
    '2:42': "Solomon recites the oath and Shimei's own assent to it. The prosecution is built entirely of the defendant's words.",
    '2:44': "The curse at Bahurim is named at last. Shimei dies for the brook, and for what the brook gave occasion to.",
    '2:46': "\"The kingdom was established in the hand of Solomon\" — established by wisdom, and by four graves.",
}

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "The reign's first recorded act is a marriage alliance with Egypt, the house Israel was brought out of.",
    '3:2': "The narrator excuses the high places and dates the excuse: \"until those days.\" The allowance will not last.",
    '3:3': "\"Solomon loved the LORD... only he sacrificed in high places.\" This book's verdicts nearly always carry an only.",
    '3:4': "A thousand burnt offerings at Gibeon. Devotion on that scale is not yet the same thing as obedience.",
    '3:5': "\"Ask what I shall give thee.\" God offers a blank cheque, and what a man writes on it exposes him.",
    '3:6': "He begins not with his request but with what God has already done for his father. Mercy first, then asking.",
    '3:7': "\"I am but a little child\" — said by a grown man who has just executed four enemies to secure the throne.",
    '3:8': "The difficulty he names is the size of God's people, not the size of his own ambition.",
    '3:9': "An understanding heart to judge, not to rule. He asks for what a courtroom needs, not what a palace wants.",
    '3:10': "God is pleased by the asking itself. What we ask for tells him, and us, what we believe we lack.",
    '3:11': "Long life, riches, the death of enemies — God lists what Solomon could have said, and did not.",
    '3:12': "The gift overshoots the request. Not enough wisdom for the job, but wisdom unmatched before or since.",
    '3:13': "\"That which thou hast not asked\" arrives as well, and the riches and honour are what finally undo him.",
    '3:14': "The wisdom is given outright; the long life is conditional. Even the best gift comes with a walk attached.",
    '3:15': "\"Behold, it was a dream\" — and he goes straight to the ark in Jerusalem rather than back to Gibeon.",
    '3:16': "Two prostitutes get direct access to the king. The new wisdom is tested on people nobody else would hear.",
    '3:20': "The swap is alleged to have happened while she slept, which is exactly why she cannot prove any of it.",
    '3:21': "\"When I had considered it in the morning\" — she knew her own child by daylight, and not a moment sooner.",
    '3:24': "\"Bring me a sword.\" For one moment the wisdom of God looks like the worst ruling ever handed down.",
    '3:25': "Split it evenly, half to each. The chapter lets us see what perfect fairness would actually cost.",
    '3:26': "Love gives the child away rather than watch it die. The other would rather neither of them had him.",
    '3:27': "The test worked because only a mother would rather lose the case than win the corpse.",
    '3:28': "They feared the king because they saw the wisdom was God's. The awe runs past the judge to the giver.",
    # ---- Chapter 4 ----
    '4:1': "\"King over all Israel\" — one line of settled fact, with the whole cost of keeping it still to come.",
    '4:6': "Adoniram is listed calmly here as the man over the tribute. In chapter twelve Israel stones him for it.",
    '4:7': "Twelve officers, a month each. The country is reorganised around feeding one household all year.",
    '4:11': "Solomon marries his daughters to his own district officers. Family and administration are one instrument.",
    '4:19': "\"He was the only officer which was in the land.\" Even a roster notices where its own pattern breaks.",
    '4:20': "\"As the sand which is by the sea\" — Abraham's promise quoted to describe a people eating and making merry.",
    '4:21': "An empire from the river to Egypt, held by tribute rather than by garrisons. Bought peace is still peace.",
    '4:22': "The flour for one day is counted in measures a village would eat in a year. Glory keeps a grocery bill.",
    '4:23': "Thirty head of cattle a day, plus game. The king's table is the kingdom's showpiece and its standing charge.",
    '4:24': "\"He had peace on all sides round about him.\" The rest David fought for is what Solomon inherits to spend.",
    '4:25': "Every man under his vine and fig tree — a picture the prophets will still be reaching for centuries later.",
    '4:26': "Forty thousand stalls of horses, against a law that told Israel's king plainly not to multiply them.",
    '4:27': "\"They lacked nothing\" is said of the king's table. It is not said of the districts that supplied it.",
    '4:28': "Barley and straw brought by quota, every man according to his charge. Splendour is assessed on somebody.",
    '4:29': "Largeness of heart, given by God. This wisdom is a capacity for the whole world, not only for hard cases.",
    '4:30': "His wisdom is measured against Egypt and the east, the very nations Israel was warned not to imitate.",
    '4:31': "Named rivals, all surpassed, and his fame in all nations. The book is tracking the fame as closely as the wisdom.",
    '4:32': "Three thousand proverbs and a thousand and five songs, and almost every one of them is simply lost.",
    '4:33': "From the cedar of Lebanon to the hyssop in the wall. The wise man's proper subject is the whole creation.",
    '4:34': "Kings of the earth come to listen. The nations gathering to hear is the high-water mark of this reign.",
    # ---- Chapter 5 ----
    '5:1': "Hiram sends first, for love of David. The great project begins in a friendship Solomon did not make.",
    '5:3': "David could not build, because of the wars. A calling can be limited by the very work God assigned.",
    '5:4': "\"Neither adversary nor evil occurrent\" — the temple goes up in the one long quiet Israel ever had.",
    '5:5': "He builds because the word said his son would, not because the idea was his. Obedience, not initiative.",
    '5:6': "Israel has the commission and Tyre has the craftsmen. The LORD's house needs foreign skill to be built at all.",
    '5:7': "A Phoenician king blesses the LORD for David's wise son. Outsiders keep noticing before Israel does.",
    '5:9': "Cedar floated down the coast in rafts and paid for in food. Worship gets built out of ordinary logistics.",
    '5:11': "Twenty thousand measures of wheat, year by year. The temple is paid for out of Israel's harvest.",
    '5:12': "The LORD gave the wisdom, and the treaty with Hiram is what that wisdom looked like in daily practice.",
    '5:13': "A levy of thirty thousand raised out of all Israel. Egypt had a word for this arrangement too.",
    '5:14': "A month in Lebanon and two at home. The rota is humane, and it is still forced labour under Adoniram.",
    '5:15': "Seventy thousand bearers and eighty thousand hewers in the hills. The house of prayer rests on those numbers.",
    '5:17': "Great stones, costly stones, hewed stones — the foundation no worshipper would ever see is made of the best.",
    '5:18': "Two kings' builders working side by side, preparing every stone and beam before a single wall goes up.",
})

TAKEAWAYS.update({
    # ---- Chapter 6 ----
    '6:1': "The temple is dated from the exodus, not from the king. The house is measured against the rescue that made a people.",
    '6:2': "Sixty cubits by twenty. For all the gold to come, the building itself is smaller than many a parish church.",
    '6:4': "Windows of narrow lights, wide within and narrow without. Whatever light is in there comes from outside.",
    '6:6': "The beams rest on ledges rather than being fastened into the walls. Nothing is driven into the holy house.",
    '6:7': "Neither hammer nor axe nor tool of iron heard in the house. Every rough cut was made somewhere out of hearing.",
    '6:9': "\"So he built the house, and finished it\" — said here and again five verses on, with a warning set between.",
    '6:12': "God interrupts the building to say the house is not the point: walk in my statutes, and then my word stands.",
    '6:13': "The promise is to dwell among the children of Israel. The people are the dwelling; the building only marks it.",
    '6:14': "The sentence resumes exactly where it broke off. Solomon heard the condition and went back to laying cedar.",
    '6:15': "Cedar over floor, walls and ceiling. The structure is lined until none of its own fabric is left in view.",
    '6:18': "\"There was no stone seen.\" The costliest building in Israel's history conceals what it is actually made of.",
    '6:19': "All of it is for one purpose: somewhere to set the ark. The house exists to hold a box with a covenant inside.",
    '6:20': "A perfect cube overlaid with gold. The most finished room in the kingdom is the one nobody may enter.",
    '6:21': "Chains of gold drawn across the entrance. The way in is closed at the same moment the work is completed.",
    '6:22': "Gold until the whole house is finished. Nothing here is held back, and nothing is done to a lesser standard.",
    '6:23': "Two cherubim of olive wood, ten cubits high. The guards who kept Eden's gate now stand over the ark.",
    '6:27': "Wingtip to wall and wing to wing, right across the room. The cherubim fill the space no worshipper may enter.",
    '6:29': "Cherubim, palm trees and open flowers on every wall, within and without. The room is carved to look like a garden.",
    '6:30': "Gold on the floor as well, where only feet would touch. Nothing here is graded by whether anyone would notice.",
    '6:32': "The doors carry the garden too, so that going in means passing back through what was lost at the beginning.",
    '6:36': "Three courses of stone to one of cedar around the inner court. Even the boundary is laid to a rule.",
    '6:38': "Seven years to build the house of the LORD — a figure worth holding on to as the next chapter starts counting.",
    # ---- Chapter 7 ----
    '7:1': "Thirteen years on his own house against seven on God's. The book sets the two numbers side by side and says nothing.",
    '7:2': "His hall of Lebanon runs a hundred cubits, near twice the temple's length. Proportion shows what a man ranks first.",
    '7:7': "A porch of judgment, cedar from wall to wall, where the king would hear cases. Justice is given its own room.",
    '7:8': "A separate house for Pharaoh's daughter. The Egyptian marriage has become architecture, permanent and on the plan.",
    '7:9': "Costly stones sawed within and without, even on faces nobody would ever stand in front of.",
    '7:10': "Foundation stones of eight and ten cubits. What holds a palace up is the part that will never be admired.",
    '7:12': "The great court is built to the same pattern as the LORD's. Palace and temple stand as one complex, by design.",
    '7:13': "Solomon sends to Tyre for Hiram. The man who casts the sacred vessels has to be fetched from outside Israel.",
    '7:14': "A widow's son of Naphtali, \"filled with wisdom, and understanding\" — the vocabulary of chapter three, applied to brass.",
    '7:15': "Two brass pillars eighteen cubits high, bearing no roof. Their entire purpose is to be seen and understood.",
    '7:21': "Jachin and Boaz: he establishes, in him is strength. The doorway is a sentence about God, not about the king.",
    '7:22': "Lily work on the top of the pillars. Even cast brass is made to flower.",
    '7:23': "A molten sea ten cubits across for washing. Approach to God starts with somebody getting clean first.",
    '7:25': "Twelve oxen facing out to the four quarters, hinder parts inward. The tribes carry the water and are not on display.",
    '7:26': "Two thousand baths of water, with a brim wrought like a cup. Tons of washing, in a vessel shaped for beauty.",
    '7:29': "Lions, oxen and cherubim on the panels. Even the wheeled washstands carry the creation on their sides.",
    '7:33': "The wheels are made like chariot wheels, naves and felloes and spokes. The craftsman built from what he knew.",
    '7:37': "\"One casting, one measure, and one size.\" Ten identical stands, because this worship is not improvised locally.",
    '7:38': "Ten lavers of forty baths each. The volume of water tells you the volume of blood the altar expected.",
    '7:39': "Five on the right, five on the left, the sea to the south. Everything is placed, and the placing is written down.",
    '7:40': "The list ends with lavers, shovels and basons. The holiest place in Israel is run with ordinary implements.",
    '7:45': "\"Bright brass\" — even the pots and shovels are polished. Nothing used before God is allowed to look neglected.",
    '7:46': "Cast in the clay ground of the Jordan plain. The temple's furnishings were made in a riverbed days away from it.",
    '7:47': "Left unweighed because they were too many. At the height of this reign the accounting simply gives up.",
    '7:48': "An altar of gold and a table with bread always on it. Inside the house, God is approached at a table that is set.",
    '7:49': "Ten candlesticks of pure gold, with flowers and lamps and tongs. The light has to be tended by hand, every day.",
    '7:50': "Even the hinges are gold. In rooms almost nobody enters, the parts nobody sees are made of the best material.",
    '7:51': "David's dedicated silver and gold go into the treasury at last. The father's offering reaches the house he never built.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "Elders, heads and chiefs are gathered first. The ark moves only with the whole people standing there to watch.",
    '8:2': "The seventh month, at the feast — Tabernacles, when Israel remembered living in tents. The timing is chosen.",
    '8:4': "The tabernacle comes up too. The tent that travelled for centuries is retired into the building that replaced it.",
    '8:6': "The ark goes in under the wings and stops moving. Everything since Sinai has been travelling toward this room.",
    '8:7': "The cherubim cover the ark and its staves. The wings of those who stay spread over the gear of those who moved.",
    '8:8': "The poles are drawn out so their ends show inside and not without. The ark keeps its travelling equipment on.",
    '8:9': "Nothing in the ark but two tables of stone. At the centre of all this gold lies the law that accuses.",
    '8:10': "The cloud fills the house the moment the priests step out. God's arrival is not timed to fit the liturgy.",
    '8:11': "The priests could not stand to minister. Glory's first effect in the new temple is that the service stops.",
    '8:12': "\"He would dwell in the thick darkness.\" Presence and concealment arrive together, in the same cloud.",
    '8:13': "\"A settled place for thee to abide in for ever\" — a sentence the rest of this book will quietly take apart.",
    '8:15': "\"Spake with his mouth... fulfilled it with his hand.\" His first word about the house is about God's reliability.",
    '8:16': "God chose no city until he had chosen a man. The place follows the person, not the other way about.",
    '8:17': "\"It was in the heart of David\" — the temple was another man's longing long before it was this king's project.",
    '8:18': "\"Thou didst well that it was in thine heart.\" The desire is commended and the permission is still withheld.",
    '8:19': "Not you, but your son. The refusal and the promise are one sentence, and David had to hear both at once.",
    '8:20': "Solomon can list the performance point by point. He is standing inside somebody else's promise, kept.",
    '8:21': "A house for the ark, and the ark for the covenant. Layer upon layer of container around a spoken word.",
    '8:22': "Hands spread toward heaven in front of the whole congregation. The king prays as one of the people, not over them.",
    '8:23': "God's incomparability is stated as covenant and mercy rather than power. What is unique is that he keeps his word.",
    '8:25': "He presses the promise to David and quotes its condition in the same breath. Solomon knows both halves by heart.",
    '8:27': "\"Will God indeed dwell on the earth?\" The builder says out loud that the building cannot hold what it is for.",
    '8:28': "\"Yet have thou respect.\" The impossibility is granted, and he asks anyway. That is the shape faith actually takes.",
    '8:29': "He asks only that God's eyes be open toward the place where his name is. Attention is requested, not residence.",
    '8:30': "\"And when thou hearest, forgive.\" Every petition in this long prayer bends toward that one verb.",
    '8:31': "The first case imagined is a quarrel between neighbours. The temple's opening use is ordinary justice.",
    '8:32': "Condemn the wicked, justify the righteous. God is asked to be the court that no human court manages to be.",
    '8:33': "Defeat is read as consequence rather than accident, and the road back is confession, not a better army.",
    '8:34': "Forgive, and bring them again. Restoration to the land follows the pardon; it never stands in for it.",
    '8:35': "Drought is named as discipline with a purpose, and the purpose is turning rather than suffering.",
    '8:36': "\"That thou teach them the good way\" — he asks for instruction before he gets round to asking for rain.",
    '8:37': "Famine, mildew, locust, siege, whatsoever plague. The prayer refuses to promise a life without disaster in it.",
    '8:38': "\"Every man the plague of his own heart.\" The worst trouble in the list is the one nobody else can see.",
    '8:39': "\"Thou only knowest the hearts.\" Because God alone sees, God alone can forgive without being deceived.",
    '8:41': "\"Concerning a stranger, that is not of thy people\" — the foreigner gets his own clause in Israel's great prayer.",
    '8:42': "The stranger comes because he has heard. Reports of what God has done are how outsiders learn there is anything to ask.",
    '8:43': "For Israel he asks forgiveness; for the stranger he asks God to do all that he calls for. The outsider is not rationed.",
    '8:44': "Even in war the prayer is aimed at a house rather than at the enemy. Battle is carried back to the place of mercy.",
    '8:46': "\"For there is no man that sinneth not.\" The prayer builds exile into its plan because it expects failure.",
    '8:47': "\"We have sinned, and have done perversely.\" Solomon writes the confession for a generation not yet born.",
    '8:48': "Praying toward a land they cannot see, from the country they were dragged to. Direction is what is left of hope.",
    '8:50': "He asks not for release but for compassion from the captors. Mercy is expected to arrive through the enemy's hands.",
    '8:51': "\"The furnace of iron\" — the argument for a rescue not yet needed is a rescue God has already performed.",
    '8:53': "The ground under the whole prayer is election: you separated them, and you said so by the hand of Moses.",
    '8:54': "The king had been kneeling. The record waits until he rises before it tells us he was ever on his knees.",
    '8:56': "\"There hath not failed one word of all his good promise.\" The verdict on God comes from a man who has counted.",
    '8:57': "\"Let him not leave us, nor forsake us\" — prayed on the best day this kingdom will ever have.",
    '8:58': "\"That he may incline our hearts.\" Obedience is asked for as a gift, not resolved upon as a policy.",
    '8:60': "The end of Israel's blessing is that all the earth should know. The nations were the point of the choosing.",
    '8:61': "\"As at this day\" — the hard charge is to go on being what you are on a day when everything is going well.",
    '8:63': "Twenty-two thousand oxen and a hundred and twenty thousand sheep. The dedication is measured out in slaughter.",
    '8:64': "The brazen altar was too small, so the court itself had to be hallowed. Even the provision could not keep pace.",
    '8:65': "Fourteen days, and a congregation reaching from Hamath to the river of Egypt. The kingdom at its widest extent.",
    '8:66': "They go home glad for the goodness done \"for David his servant.\" On Solomon's greatest day the credit goes back.",
})

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:2': "A second appearing, as at Gibeon. The dream that opened this reign is matched once the building is done.",
    '9:3': "\"Mine eyes and mine heart shall be there perpetually.\" God grants the attention Solomon asked for, and no more.",
    '9:4': "\"And if thou wilt walk before me\" — the answer to the great prayer arrives with a condition fastened on.",
    '9:5': "The throne for ever and the if stand in one sentence. Only the promise to David is spoken without terms.",
    '9:6': "\"But if ye shall at all turn\" — the warning is addressed to children not yet born as well as to the king.",
    '9:7': "The house just hallowed can be cast out of sight. Consecration is no insurance against demolition.",
    '9:8': "Passers-by will hiss at the ruin and ask why. The building's fame will one day be for having failed.",
    '9:9': "The answer to that question is written down centuries before anybody stands there to ask it.",
    '9:10': "Twenty years of building, summed up in half a verse. The labour of a generation gets one clause.",
    '9:11': "Twenty cities of Galilee handed over to Tyre. The temple was paid for partly in Israelite land.",
    '9:13': "The cities displeased him, so he named the district Cabul, good for nothing, and still called Solomon brother.",
    '9:15': "The levy is explained by the list of what it built. Forced labour is given a reason, never a defence.",
    '9:16': "Gezer arrives as a wedding present, burnt and emptied of its people. Solomon's city came out of Pharaoh's war.",
    '9:19': "Cities for chariots, cities for horsemen. The king Deuteronomy warned about is being built district by district.",
    '9:20': "The nations Israel never managed to drive out are still in the land, and now they have become useful.",
    '9:21': "\"A tribute of bondservice unto this day.\" What the conquest left undone turned into a labour supply.",
    '9:22': "No Israelite was made a bondman. The splendour of this reign rests on who may be worked and who may not.",
    '9:24': "Pharaoh's daughter is moved out of the city of David into a house of her own. Even this marriage needs managing.",
    '9:25': "Three times a year at the altar, and then the house is called finished. Worship has settled into a schedule.",
    '9:27': "Hiram lends shipmen \"that had knowledge of the sea.\" Israel's navy was sailed by foreigners who knew how.",
    '9:28': "Four hundred and twenty talents out of Ophir. The gold filling these chapters came in on somebody else's ships.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "She came at the fame of Solomon \"concerning the name of the LORD.\" What travelled abroad was news about God.",
    '10:2': "\"She communed with him of all that was in her heart.\" The hard questions turn out to be personal ones.",
    '10:3': "Nothing was hid from the king that he did not tell her. The wisdom is proved by being handed over.",
    '10:5': "\"There was no more spirit in her.\" What emptied her was not the gold but the order of the household.",
    '10:6': "\"It was a true report.\" A foreign queen certifies Israel's king, and the book lets her do the certifying.",
    '10:7': "\"The half was not told me.\" Rumour had undersold it, which is the rarest verdict a reputation ever gets.",
    '10:8': "\"Happy are these thy servants, which... hear thy wisdom.\" She envies the staff rather than the king.",
    '10:9': "She blesses the LORD and reads the throne as love for Israel, not as anything earned by the man on it.",
    '10:12': "Almug timber becomes pillars, and also harps and psalteries. Some of the imported wood went into music.",
    '10:13': "He gave her all her desire. The visit ends with the host outgiving the guest who came to test him.",
    '10:14': "Six hundred threescore and six talents in one year. The figure is recorded without a word of praise.",
    '10:17': "Shields of beaten gold, stored in a house of cedar. Armour made from the softest metal in the treasury.",
    '10:19': "Six steps up, and a lion at either hand. The seat of judgement was designed to be climbed toward.",
    '10:20': "\"There was not the like made in any kingdom.\" The throne's whole point is to be unlike anybody else's.",
    '10:21': "Silver \"was nothing accounted of\" — the reign grew rich enough that a precious metal stopped counting as one.",
    '10:22': "Gold, silver, ivory, apes and peacocks. By the end of the manifest the cargo has become mere curiosities.",
    '10:23': "Riches first, then wisdom. The book has begun naming them together, and in that order.",
    '10:24': "The wisdom is still called something God put in his heart, even here among the inventories.",
    '10:26': "A thousand four hundred chariots and twelve thousand horsemen. The discerning heart has been converted into cavalry.",
    '10:28': "Horses brought out of Egypt — the one country a king of Israel was told never to send to for them.",
    '10:29': "He resells chariots to the kings of the Hittites and of Syria. Israel has gone into the arms trade.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "\"But king Solomon loved many strange women.\" A single conjunction turns the whole reign around.",
    '11:2': "\"Solomon clave unto these in love.\" The verb is affection, not policy, and the warning was about the heart.",
    '11:3': "Seven hundred wives and three hundred concubines. At that volume the diplomacy has stopped being diplomacy.",
    '11:4': "\"When Solomon was old.\" The man who prayed chapter 8 did not fall young, or quickly, or all at once.",
    '11:5': "Ashtoreth and Milcom, named outright. The record refuses to leave this apostasy comfortably vague.",
    '11:6': "\"Went not fully after the LORD\" — the charge is not revolt but a heart no longer whole toward him.",
    '11:7': "High places for Chemosh and Molech on the hill facing Jerusalem. The man who built the temple built these too.",
    '11:8': "\"And likewise did he for all his strange wives.\" Love for one woman ends as a building programme for idols.",
    '11:9': "\"Which had appeared unto him twice.\" The anger is measured against how much this man had been shown.",
    '11:10': "He had been commanded about this very thing. The sin is not ignorance but a known instruction set aside.",
    '11:11': "\"I will surely rend the kingdom from thee.\" The tearing is announced as God's act before any rebel moves.",
    '11:12': "\"Not in thy days... for David thy father's sake.\" The reprieve is granted on somebody else's account.",
    '11:13': "One tribe kept back for David and for Jerusalem. The judgement is limited by a promise, not by a record.",
    '11:14': "\"The LORD stirred up an adversary.\" Trouble on the border is read as a sentence being carried out.",
    '11:15': "Hadad exists because Joab once killed every male in Edom. Old atrocities grow up and come looking.",
    '11:17': "Hadad escaped to Egypt \"being yet a little child.\" The threat to this kingdom got out as a refugee boy.",
    '11:21': "He waits until both David and Joab are dead before asking to go home. Grievance can be very patient.",
    '11:25': "\"He abhorred Israel.\" Syria's long enmity with Israel begins as a footnote to Solomon's decline.",
    '11:26': "Jeroboam was Solomon's own servant. The man who takes the kingdom was promoted from inside it.",
    '11:27': "The cause given is Millo and the breaches in the wall. The revolt starts as a grievance about labour.",
    '11:28': "Solomon saw he was industrious and put him over the house of Joseph. He advanced his own supplanter.",
    '11:29': "Ahijah meets him in the field, and the two of them are alone. The kingdom changes hands with no witnesses.",
    '11:30': "He tears a new garment into twelve pieces. Something not yet worn out is ruined to make the point.",
    '11:31': "Ten pieces handed over on the spot. The prophet performs the division before either kingdom exists.",
    '11:33': "The charge falls on \"they\" as much as on him. The king's private gods had become the nation's.",
    '11:36': "\"That David my servant may have a light alway.\" One tribe is spared so that a lamp will not go out.",
    '11:37': "\"Thou shalt reign according to all that thy soul desireth.\" Jeroboam is handed exactly what he wanted.",
    '11:38': "He is offered David's own terms, a sure house on condition of obedience. Jeroboam begins with every chance.",
    '11:39': "\"But not for ever.\" Even as the affliction of David's seed is announced, a limit is put on it.",
    '11:40': "Solomon tries to kill the man God has named. The wisest king's last recorded act is an assassination attempt.",
    '11:42': "Forty years, the same span as Saul and David. The number tells you nothing about how the reign ended.",
    '11:43': "He is buried in the city of David and his son reigns. The succession is quiet; the kingdom is already gone.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:1': "All Israel gathers at Shechem to make him king. The coronation is held on northern ground.",
    '12:4': "\"Make thou his heavy yoke lighter, and we will serve thee.\" The kingdom is offered for a tax cut.",
    '12:5': "Three days. He does the one prudent thing in the chapter and takes time before answering.",
    '12:6': "He asks the old men who stood before Solomon — the ones who watched the yoke being made.",
    '12:7': "\"If thou wilt be a servant unto this people\" — their whole counsel is that ruling means serving.",
    '12:8': "He turns to the young men grown up with him. Counsel chosen for its company rather than its judgement.",
    '12:10': "\"My little finger shall be thicker than my father's loins.\" Their advice is a boast about the body.",
    '12:11': "Whips, then scorpions. The plan is to answer a complaint about pain by promising a great deal more of it.",
    '12:13': "\"The king answered the people roughly.\" The tone did as much damage as the terms did.",
    '12:14': "He delivers the young men's speech word for word. The split comes of a king with no sentence of his own.",
    '12:15': "\"For the cause was from the LORD.\" A young man's folly and God's purpose are the same event.",
    '12:16': "\"What portion have we in David?\" Ten tribes disown a dynasty in one rhyming refusal.",
    '12:17': "Israelites living in Judah's cities stay under Rehoboam. The division runs through households too.",
    '12:18': "He sends the man in charge of the tribute, and they stone him. The king still cannot read the room.",
    '12:19': "\"Unto this day\" — written by somebody for whom the split is still the shape of the world.",
    '12:20': "He is made king by an assembly rather than by descent. The north begins as an elective throne.",
    '12:21': "A hundred and eighty thousand chosen men, raised against their brethren. The first instinct is civil war.",
    '12:24': "\"This thing is from me,\" and they obeyed. The one word Rehoboam kept was the one forbidding war.",
    '12:26': "\"Jeroboam said in his heart.\" The great sin of the north starts as a private calculation about security.",
    '12:27': "He fears that worship in Jerusalem will cost him his throne. Religion is reorganised to protect a king.",
    '12:28': "\"It is too much for you to go up to Jerusalem.\" Idolatry is sold as convenience, and it sells.",
    '12:29': "One in Bethel and one in Dan, at either end of the country. The calves are placed for coverage.",
    '12:30': "\"And this thing became a sin.\" Flatly said, and the phrase will follow every northern king to come.",
    '12:31': "Priests made \"of the lowest of the people.\" Invent a worship and you must invent a clergy for it.",
    '12:32': "A feast in the eighth month, like the one in Judah. A counterfeit calendar to match the counterfeit gods.",
    '12:33': "\"The month which he had devised of his own heart.\" The whole system is dated from a king's invention.",
})

TAKEAWAYS.update({
    # ---- Chapter 13 ----
    '13:1': "A man of God arrives from Judah while the king's hand is in the incense. The word interrupts the liturgy.",
    '13:2': "He cries against the altar rather than the king, and names Josiah three centuries before his birth.",
    '13:3': "The sign offered is the altar splitting. Confirmation is given in advance, and it is destructive.",
    '13:4': "He reaches out to seize a prophet and cannot draw the hand back. The gesture itself becomes the sentence.",
    '13:5': "The altar is rent and the ashes poured out as promised, while the king stands there unable to move.",
    '13:6': "The king asks for prayer and the hand is restored. Mercy arrives with no repentance attached to it.",
    '13:7': "\"Come home with me... and I will give thee a reward.\" The threat failed, so the king tries hospitality.",
    '13:8': "\"If thou wilt give me half thine house\" — the refusal is priced before the offer can be raised.",
    '13:9': "No bread, no water, no returning the same way. A very small command, and it turns out to be the whole test.",
    '13:10': "He went home another way. Obedience here looks like a detour that nobody would have noticed.",
    '13:11': "An old prophet hears the day's events secondhand from his sons, and goes out after the man who did them.",
    '13:14': "\"Art thou the man of God...? And he said, I am.\" He answers to the title, and the title undoes him.",
    '13:15': "\"Come home with me, and eat bread.\" The second invitation is the king's, out of a friendlier mouth.",
    '13:16': "He refuses again, in the same words. Resolve holds well enough the second time it is tested.",
    '13:18': "\"But he lied unto him.\" A newer revelation from a fellow prophet overturns a plain word already given.",
    '13:19': "He went back and ate. No argument is recorded; he simply preferred the second message to the first.",
    '13:20': "The word of the LORD arrives while they are still at table, and it arrives to the man who lied.",
    '13:21': "The sentence is spoken by the mouth that deceived him. God tells the truth through a false prophet.",
    '13:22': "His body will not reach his fathers' grave. The penalty lands on the burial, the last thing he had.",
    '13:24': "A lion meets him and kills him, and the ass simply stands there. Judgement, and then a strangely tidy scene.",
    '13:26': "The old prophet reads the verdict at once, and it is a verdict he helped to earn.",
    '13:28': "The lion had eaten nothing and torn nothing. This was a sentence carried out, not an animal feeding.",
    '13:30': "\"Alas, my brother!\" The man who lied to him mourns him, and the text lets both things stand.",
    '13:31': "He asks to be buried beside those bones. The deceiver wants to be found in that man's company.",
    '13:32': "He now believes the prophecy he had contradicted. Nothing convinces like watching a word come true.",
    '13:33': "\"Jeroboam returned not from his evil way.\" A split altar and a dead prophet changed nothing whatever.",
    '13:34': "\"This thing became sin unto the house of Jeroboam.\" The dynasty falls over the worship, not the politics.",
})

TAKEAWAYS.update({
    # ---- Chapter 14 ----
    '14:1': "The judgement on the house of Jeroboam begins with a sick child inside it.",
    '14:2': "He sends his wife in disguise to the prophet who made him king. He believes Ahijah and hides from him at once.",
    '14:3': "Ten loaves, cracknels and a cruse of honey. A peasant's gift, chosen to match the costume.",
    '14:4': "Ahijah could not see. The disguise was wasted on a blind man who had already been told who was coming.",
    '14:6': "\"Why feignest thou thyself to be another?\" The costume comes off at the door, before she has said a word.",
    '14:7': "\"Forasmuch as I exalted thee from among the people\" — the charge begins from the gift that came first.",
    '14:8': "He is measured against a David who \"followed me with all his heart.\" The standard is wholeness, not flawlessness.",
    '14:9': "\"Hast cast me behind thy back.\" Idolatry is described as putting someone out of sight rather than out of mind.",
    '14:10': "Swept away as a man takes away dung. The language is deliberately coarse; the dynasty is refuse to be carried out.",
    '14:11': "Dogs and fowls instead of a grave. The curse is aimed at the burial, which mattered more then than it does now.",
    '14:12': "\"When thy feet enter into the city, the child shall die.\" She is sent home to be the clock.",
    '14:13': "\"In him there is found some good thing.\" The child dies first because he is the only one worth mourning.",
    '14:14': "\"But what? even now.\" The prophet breaks off mid-sentence; the judgement is already on the road.",
    '14:15': "Israel shaken like a reed and rooted up beyond the river. Exile is named in the north's first generation.",
    '14:16': "\"Who did sin, and who made Israel to sin.\" The second clause is the one the book never lets him put down.",
    '14:17': "She reaches the threshold and the child dies there. The word had timed itself to her step.",
    '14:19': "\"Are they not written in the book of the chronicles\" — the record keeps what bears on the covenant and files the rest.",
    '14:21': "His mother was Naamah an Ammonitess. The queen mothers are named because their gods came into the house with them.",
    '14:22': "\"And Judah did evil.\" The south is not the good half; both accounts are kept, and both go wrong.",
    '14:23': "High places on every high hill and under every green tree. The phrase for a country whose religion has gone local.",
    '14:24': "Judah is now doing what the nations did whom God cast out. The dispossessed practices moved back in.",
    '14:25': "Shishak comes up in the fifth year. Solomon's empire lasted less than a decade past his funeral.",
    '14:26': "\"He even took away all,\" the golden shields included. Chapter 10's treasure is gone inside one generation.",
    '14:27': "Brasen shields made in their stead, carried out and carried back each time. The ceremony goes on with cheaper props.",
    '14:30': "War between Rehoboam and Jeroboam all their days. Neither man ever stopped paying for what happened at Shechem.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:1': "Abijam is dated by the eighteenth year of Jeroboam. From here each king is timed against his rival abroad.",
    '15:2': "Maachah the daughter of Abishalom. Absalom's line has come back into the house of David by marriage.",
    '15:3': "\"His heart was not perfect with the LORD\" — the measure for Judah's kings is David's heart, not their works.",
    '15:4': "\"Nevertheless for David's sake... a lamp in Jerusalem.\" The dynasty runs on a dead man's credit.",
    '15:5': "\"Save only in the matter of Uriah the Hittite.\" Even the commendation of David keeps the exception in writing.",
    '15:9': "Forty-one years, the longest reign yet in this book. Reform, unlike revolt, takes time to do.",
    '15:10': "The same Maachah is named as his mother. The grandmother held the office for two reigns running.",
    '15:11': "\"And Asa did that which was right.\" After four reigns the formula changes, and the change is the news.",
    '15:12': "He removes the idols his fathers made. Reform in Judah always begins by undoing the last generation's work.",
    '15:13': "He deposes his own mother over an idol. The reform reached the household before it reached the country.",
    '15:14': "\"The high places were not removed: nevertheless Asa's heart was perfect.\" A mixed record and a whole heart.",
    '15:15': "He brings in his father's dedications along with his own. Part of reform is paying somebody else's arrears.",
    '15:16': "War between Asa and Baasha all their days. The formula simply fills in with the next pair of names.",
    '15:17': "Baasha fortifies Ramah to seal the border. The two kingdoms now build walls against each other's travellers.",
    '15:18': "He empties the temple treasury to hire Syria. The good king buys safety with what was given to God.",
    '15:19': "\"Come and break thy league with Baasha.\" Asa's plan needs a foreign king to be treacherous first.",
    '15:20': "Benhadad hearkened, and Naphtali burned. The rescue works, and Israelites pay for it in Israelite towns.",
    '15:21': "Baasha leaves off building and goes home. A siege lifted by news arriving from somewhere else entirely.",
    '15:22': "\"None was exempted.\" Asa carts off Baasha's stones and timber and builds his own forts out of them.",
    '15:23': "\"Nevertheless in the time of his old age he was diseased in his feet.\" The one shadow the summary keeps.",
    '15:25': "Nadab gets two years. In the north a son rarely gets long, and he is the first to discover it.",
    '15:26': "\"He did evil... and walked in the way of his father.\" From here the formula repeats almost unaltered, reign after reign.",
    '15:27': "Baasha conspires against him at a siege. The northern throne changes hands in the field, not in a palace.",
    '15:29': "He left not any that breathed, and the text calls it Ahijah's word fulfilled. Butchery and prophecy in one sentence.",
    '15:30': "The reason given is not Nadab's crimes but his father's. Sin is inherited here the way an estate is.",
    '15:34': "Baasha wiped out Jeroboam's house and then walked in Jeroboam's way. The executioner takes up the crime.",
})

TAKEAWAYS.update({
    # ---- Chapter 16 ----
    '16:1': "The word comes to Jehu the son of Hanani. Every northern dynasty gets a prophet before it gets a successor.",
    '16:2': "\"I exalted thee out of the dust\" — Jeroboam's charge, word for word, because the same thing keeps happening.",
    '16:3': "\"Like the house of Jeroboam.\" The curse now has a precedent to be measured by, and that is its horror.",
    '16:6': "Baasha dies in his bed and is buried in his capital. The sentence falls on the house, not on the man.",
    '16:7': "The word came against him \"because he killed him.\" Baasha did what prophecy foretold and is charged with it anyway.",
    '16:9': "Zimri conspires while the king is drinking himself drunk. A throne in Israel needs very little occasion to change.",
    '16:10': "A regnal date is supplied for a murder. The chronicle records the killing itself as the accession.",
    '16:11': "He kills the whole house, kinsfolk and friends alike. Each new dynasty begins by earning the next curse.",
    '16:12': "This too is called the word fulfilled. Zimri is God's instrument for seven days and never learns it.",
    '16:13': "\"Their vanities\" — the gods are called nothings, and men are dying over them by the household.",
    '16:15': "Seven days. The shortest reign in the book still gets its regnal formula like all the others.",
    '16:16': "The army makes its own captain king in the camp. Israel's throne is now whatever the soldiers say it is.",
    '16:17': "Omri comes up from Gibbethon and besieges Tirzah. The army that named him walks him to the capital.",
    '16:18': "He burns the palace down over himself. The one thing he ever held he destroyed rather than hand over.",
    '16:19': "Even a seven-day usurper is charged with walking in Jeroboam's way. The verdict does not scale to the reign.",
    '16:21': "Half the people follow Tibni and half follow Omri. The seceding kingdom now secedes from itself.",
    '16:22': "\"So Tibni died, and Omri reigned.\" Four words for a civil war, and no account of how the loser died.",
    '16:24': "He buys a hill for two talents and names the city after the seller. Samaria begins as a property transaction.",
    '16:25': "\"Did worse than all that were before him\" — said of the one northern king that foreign records called great.",
    '16:28': "Omri, the name outsiders knew Israel by, is given six verses. This book is grading on another scale entirely.",
    '16:30': "Ahab takes the record for evil straight from his own father. In this family the superlative is hereditary.",
    '16:31': "\"As if it had been a light thing\" — the calves are now the baseline, and Jezebel and Baal are what he adds.",
    '16:32': "An altar for Baal in a house for Baal in Samaria. The new capital is given a rival temple from the start.",
    '16:33': "More provocation than all the kings before him. The comparison has finally run out of room to grow.",
    '16:34': "Hiel builds Jericho and buries two sons in it. Joshua's old curse comes due in the middle of a king list.",
})
