#!/usr/bin/env python3
"""Written one-line takeaways for Leviticus."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "God speaks out of the tent Israel has just finished building. Exodus ends with glory; Leviticus begins with a voice.",
    '1:2': "The instructions are addressed to \"any man of you,\" not to the priests. The system starts in a layman's hands.",
    '1:3': "\"Of his own voluntary will.\" A sacrifice regulated down to the species is still something a man chose to bring.",
    '1:4': "The hand on the head ties the man to the animal, and what happens to the animal is credited back to the man.",
    '1:5': "The worshipper kills it himself. Nobody in Israel is spared the sight of what his own sin costs.",
    '1:6': "He flays and cuts it up before the priest touches anything. The dirty half of the work is the offerer's.",
    '1:9': "The whole animal goes up, and God calls the smoke a sweet savour. Total loss is what is received as pleasure.",
    '1:10': "A sheep or a goat does what the bullock did. The offering is scaled to the herd a man actually keeps.",
    '1:14': "Turtledoves for a man with no flock. The law names a price the poorest can pay before anyone is turned away.",
    '1:15': "For the bird the priest does the killing. The offering too small to handle is handled for the man who brought it.",
    '1:16': "Even a pigeon has a part thrown out beside the altar. Little is asked, and what is asked is still to be clean.",
    '1:17': "\"He shall not divide it asunder.\" The smallest offering is opened but never reduced further.",
    # ---- Chapter 2 ----
    '2:1': "Flour, oil and frankincense: an offering with no death in it anywhere, and Leviticus counts it an offering.",
    '2:2': "A handful is burned as the memorial. God takes a token and reckons the whole gift as given.",
    '2:3': "What is left feeds Aaron's sons. The tribe with no fields eats from what the tribes with fields bring in.",
    '2:4': "Oven, pan or fryingpan. The law takes the grain offering as it comes out of whatever kitchen a man owns.",
    '2:6': "\"Thou shalt part it in pieces, and pour oil thereon.\" Even bread is broken before it is handed over.",
    '2:11': "Leaven and honey are both barred. Nothing that ferments and swells on its own is allowed on the fire.",
    '2:12': "Firstfruits are brought and not burned. A gift can be genuinely given without going up in smoke.",
    '2:13': "\"The salt of the covenant of thy God.\" What keeps meat from spoiling is made the sign of a bond that holds.",
    '2:14': "Green ears dried by fire: a man brings the first of the harvest before he knows what the harvest will come to.",
    '2:16': "All the frankincense burns, though only part of the corn does. The portion that is pure fragrance is God's entire.",
    # ---- Chapter 3 ----
    '3:1': "Male or female alike for a peace offering. Where the sacrifice ends in a shared meal, the requirements ease.",
    '3:2': "Killed at the door, blood thrown round the altar. Even the offering called peace is made over a carcass.",
    '3:3': "What goes up is the fat. Israel hands over the part any herdsman would have counted the reward of his year.",
    '3:5': "The peace offering burns on top of the burnt offering. Fellowship is laid on a fire atonement already lit.",
    '3:7': "A lamb is brought \"before the LORD\" in the same words as the bullock. The smaller beast buys no lesser standing.",
    '3:9': "\"The whole rump\" — the fat tail, the delicacy of the flock. The best cut is the one nobody at the meal eats.",
    '3:11': "\"It is the food of the offering made by fire unto the LORD.\" The altar is spoken of frankly as God's table.",
    '3:16': "\"All the fat is the LORD's.\" Not a portion of the fat; the richest part belongs to him as a category.",
    '3:17': "Fat and blood are barred in every dwelling, not only at the altar. What is learned at the tent binds the kitchen.",
    # ---- Chapter 4 ----
    '4:2': "Sin through ignorance still needs blood. Guilt here is a condition a man is in, not a thing he meant.",
    '4:3': "The anointed priest sins like the people he atones for, and his offering is the costliest of the four cases.",
    '4:6': "Blood sprinkled seven times before the vail. The nearer a man stood to God, the further in his sin must be answered.",
    '4:7': "The priest's blood goes inside, onto the golden altar. His sin has contaminated the room where he prays.",
    '4:11': "Skin, flesh, head, legs, inwards, dung. The list refuses to let the sin offering's carcass sound respectable.",
    '4:12': "The body is burned outside the camp where the ashes go. Hebrews will point here to say where Jesus suffered.",
    '4:13': "A whole congregation can sin and not notice. Corporate guilt does not wait on anyone realising it.",
    '4:15': "The elders lay hands for everybody. Representation is working in Israel long before doctrine is built on it.",
    '4:20': "\"And it shall be forgiven them.\" The clause the whole apparatus exists to reach is stated without ceremony.",
    '4:22': "\"The LORD his God\" is added only in the ruler's case. The man with power is reminded whose he is.",
    '4:23': "A goat where the priest brought a bullock. The nearer a man stands to the altar, the more his sin costs him.",
    '4:26': "The ruler's fat burns like a common man's peace offering. Office makes no difference once the knife is out.",
    '4:27': "The same machinery runs for an ordinary Israelite. No one's guilt is too small to be worth blood.",
    '4:28': "A female goat, the cheapest animal named. The scale is graded downward so that atonement stays reachable.",
    '4:31': "The fat of a sin offering is called a sweet savour. God is pleased by the thing that deals with sin.",
    '4:32': "A lamb may stand in for the goat. Even at the bottom of the scale the offerer is left a choice.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "A man who hears the adjuration and stays quiet bears the iniquity. Silence is listed among the sins needing blood.",
    '5:2': "Uncleanness contracted without noticing still counts. A man can be defiled by what he never knew he touched.",
    '5:4': "A rash oath binds, whether it promised good or evil. Words let go lightly are treated as debts that fall due.",
    '5:5': "\"He shall confess that he hath sinned in that thing.\" The animal does not save him from naming what he did.",
    '5:6': "The same offering is called both trespass and sin offering. The categories overlap where real cases do.",
    '5:7': "\"If he be not able to bring a lamb.\" The law itself anticipates the man who cannot afford what it has just asked.",
    '5:11': "Flour, with no oil and no frankincense. The poorest sin offering is stripped of everything that would smell pleasant.",
    '5:13': "A handful of flour earns the same sentence as a bullock: it shall be forgiven him. The verdict is not means-tested.",
    '5:15': "Trespass in holy things is priced in sanctuary shekels. Sacrilege is reckoned as a debt with a figure attached.",
    '5:16': "He repays the harm and adds a fifth. The sacrifice does not cancel the restitution; it comes on top of it.",
    '5:17': "\"Though he wist it not, yet is he guilty.\" Leviticus refuses to make ignorance the measure of innocence.",
    '5:19': "\"He hath certainly trespassed against the LORD.\" The charge is restated plainly after the remedy has been given.",
    # ---- Chapter 6 ----
    '6:2': "Lying to a neighbour about a deposit is a trespass against the LORD. God is named as the party injured.",
    '6:5': "Principal and a fifth are repaid \"in the day of his trespass offering.\" He squares with the man before the altar.",
    '6:7': "Forgiveness covers \"any thing of all that he hath done.\" Nothing is held back from the list for later.",
    '6:9': "The burnt offering burns all night with nobody watching. Worship continues through the hours the camp is asleep.",
    '6:10': "The priest puts on his linen to shovel ashes. The holy dress is worn for the least impressive job at the altar.",
    '6:11': "He changes clothes to carry the ashes out. What is worn inside the court does not go walking beyond the camp.",
    '6:13': "\"It shall never go out.\" Israel's one unbroken duty is feeding a fire, morning after morning, for ever.",
    '6:16': "The priests eat their portion in the court, not at home. Their wages are consumed inside the place they serve.",
    '6:17': "\"I have given it unto them for their portion.\" A priest's living is described as God's gift, not as his fee.",
    '6:18': "\"Every one that toucheth them shall be holy.\" Contact with the offering carries holiness outward, not defilement in.",
    '6:20': "Aaron has a daily offering of his own, morning and evening. The man who handles everyone's sacrifices brings one.",
    '6:23': "A priest's own meat offering is wholly burnt and never eaten. No man in Israel may live off his own atonement.",
    '6:26': "The priest who offers the sin offering eats it. Bearing another man's sin is also, in this law, how he is fed.",
    '6:28': "The pot it boiled in is broken. What has held the sin offering does not go back to ordinary kitchen use.",
    '6:30': "Where the blood went inside, the flesh is burnt and no one eats. The offering that reaches furthest in feeds nobody.",
    # ---- Chapter 7 ----
    '7:7': "\"There is one law for them.\" Sin and trespass are distinguished by name and handled with equal gravity.",
    '7:8': "The hide goes to the priest who offered it. Even a whole burnt offering leaves something behind for somebody to use.",
    '7:9': "Baked offerings belong to the priest who presented them. Work done at the altar is paid for from the altar.",
    '7:10': "The dry meat offerings are divided \"one as much as another.\" Part of the priests' income is deliberately levelled.",
    '7:12': "A peace offering may be simple thanksgiving. Not every approach to the altar is prompted by something gone wrong.",
    '7:13': "Leavened bread comes with the thanksgiving — the one place leaven is allowed, because this loaf is eaten, not burned.",
    '7:15': "Thanksgiving flesh must be eaten the same day. Gratitude is given a shelf life short enough to force a shared table.",
    '7:16': "A vow or freewill offering keeps a second day. What was promised in advance is given slightly more room.",
    '7:18': "On the third day it \"shall not be imputed unto him.\" A right sacrifice can be voided by how it is treated afterward.",
    '7:20': "An unclean man eating holy flesh is cut off. The meal that signifies peace is the thing that severs him.",
    '7:24': "Fat from an animal found dead may be put to other uses. The ban is on eating it, not on handling it at all.",
    '7:25': "Fat is barred because it is the portion men offer by fire. It is withheld not as unhealthy but as God's.",
    '7:26': "No blood of fowl or beast in any dwelling. The rule is laid down here; chapter 17 will stop and explain it.",
    '7:30': "\"His own hands shall bring the offerings.\" The priest does not carry it in for him; the man presents it himself.",
    '7:31': "The fat burns and the breast goes to Aaron. God's portion is taken first and the priest's is cut from the rest.",
    '7:32': "The right shoulder, the best joint, goes to the priest. Israel's meals are taxed in favour of the tribe with no land.",
    '7:34': "\"Have I taken... and have given them unto Aaron.\" God takes from the people in order to hand it to his servants.",
    '7:36': "A statute for ever, dated to the day of the anointing. The priests' support was settled before they had served a day.",
    '7:37': "Five offerings named in a single breath. The reader has been handed a whole vocabulary for approaching God.",
    '7:38': "\"In the wilderness of Sinai.\" A law assuming ovens, fields and flocks is given to people living out of tents.",
})
