#!/usr/bin/env python3
"""Written one-line takeaways for Leviticus."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "God speaks out of the tent Israel has just finished building. Exodus ends with glory; Leviticus begins with a voice.",
    '1:2': "The instructions are addressed to \"any man of you,\" not to the priests. The system starts in a layman's hands.",
    '1:3': "\"Of his own voluntary will.\" A sacrifice regulated down to the species is still something a man chose to bring.",
    '1:4': "The hand on the head ties the man to the animal, and what happens to the animal is credited back to the man.",
    '1:5': "The worshipper kills it himself. Nobody in Israel is spared the sight of what his own sin costs.",
    '1:6': "He flays and cuts it up before the priest touches anything. The dirty half of the work is the offerer's.",
    '1:9': "The whole animal goes up, and God calls the smoke a sweet savour. Total loss is what is received as pleasure.",
    '1:10': "A sheep or a goat does what the bullock did. The offering is scaled to the herd a man actually keeps.",
    '1:14': "Turtledoves for a man with no flock. The law names a price the poorest can pay before anyone is turned away.",
    '1:15': "For the bird the priest does the killing. The offering too small to handle is handled for the man who brought it.",
    '1:16': "Even a pigeon has a part thrown out beside the altar. Little is asked, and what is asked is still to be clean.",
    '1:17': "\"He shall not divide it asunder.\" The smallest offering is opened but never reduced further.",
    # ---- Chapter 2 ----
    '2:1': "Flour, oil and frankincense: an offering with no death in it anywhere, and Leviticus counts it an offering.",
    '2:2': "A handful is burned as the memorial. God takes a token and reckons the whole gift as given.",
    '2:3': "What is left feeds Aaron's sons. The tribe with no fields eats from what the tribes with fields bring in.",
    '2:4': "Oven, pan or fryingpan. The law takes the grain offering as it comes out of whatever kitchen a man owns.",
    '2:6': "\"Thou shalt part it in pieces, and pour oil thereon.\" Even bread is broken before it is handed over.",
    '2:11': "Leaven and honey are both barred. Nothing that ferments and swells on its own is allowed on the fire.",
    '2:12': "Firstfruits are brought and not burned. A gift can be genuinely given without going up in smoke.",
    '2:13': "\"The salt of the covenant of thy God.\" What keeps meat from spoiling is made the sign of a bond that holds.",
    '2:14': "Green ears dried by fire: a man brings the first of the harvest before he knows what the harvest will come to.",
    '2:16': "All the frankincense burns, though only part of the corn does. The portion that is pure fragrance is God's entire.",
    # ---- Chapter 3 ----
    '3:1': "Male or female alike for a peace offering. Where the sacrifice ends in a shared meal, the requirements ease.",
    '3:2': "Killed at the door, blood thrown round the altar. Even the offering called peace is made over a carcass.",
    '3:3': "What goes up is the fat. Israel hands over the part any herdsman would have counted the reward of his year.",
    '3:5': "The peace offering burns on top of the burnt offering. Fellowship is laid on a fire atonement already lit.",
    '3:7': "A lamb is brought \"before the LORD\" in the same words as the bullock. The smaller beast buys no lesser standing.",
    '3:9': "\"The whole rump\" — the fat tail, the delicacy of the flock. The best cut is the one nobody at the meal eats.",
    '3:11': "\"It is the food of the offering made by fire unto the LORD.\" The altar is spoken of frankly as God's table.",
    '3:16': "\"All the fat is the LORD's.\" Not a portion of the fat; the richest part belongs to him as a category.",
    '3:17': "Fat and blood are barred in every dwelling, not only at the altar. What is learned at the tent binds the kitchen.",
    # ---- Chapter 4 ----
    '4:2': "Sin through ignorance still needs blood. Guilt here is a condition a man is in, not a thing he meant.",
    '4:3': "The anointed priest sins like the people he atones for, and his offering is the costliest of the four cases.",
    '4:6': "Blood sprinkled seven times before the vail. The nearer a man stood to God, the further in his sin must be answered.",
    '4:7': "The priest's blood goes inside, onto the golden altar. His sin has contaminated the room where he prays.",
    '4:11': "Skin, flesh, head, legs, inwards, dung. The list refuses to let the sin offering's carcass sound respectable.",
    '4:12': "The body is burned outside the camp where the ashes go. Hebrews will point here to say where Jesus suffered.",
    '4:13': "A whole congregation can sin and not notice. Corporate guilt does not wait on anyone realising it.",
    '4:15': "The elders lay hands for everybody. Representation is working in Israel long before doctrine is built on it.",
    '4:20': "\"And it shall be forgiven them.\" The clause the whole apparatus exists to reach is stated without ceremony.",
    '4:22': "\"The LORD his God\" is added only in the ruler's case. The man with power is reminded whose he is.",
    '4:23': "A goat where the priest brought a bullock. The nearer a man stands to the altar, the more his sin costs him.",
    '4:26': "The ruler's fat burns like a common man's peace offering. Office makes no difference once the knife is out.",
    '4:27': "The same machinery runs for an ordinary Israelite. No one's guilt is too small to be worth blood.",
    '4:28': "A female goat, the cheapest animal named. The scale is graded downward so that atonement stays reachable.",
    '4:31': "The fat of a sin offering is called a sweet savour. God is pleased by the thing that deals with sin.",
    '4:32': "A lamb may stand in for the goat. Even at the bottom of the scale the offerer is left a choice.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:1': "A man who hears the adjuration and stays quiet bears the iniquity. Silence is listed among the sins needing blood.",
    '5:2': "Uncleanness contracted without noticing still counts. A man can be defiled by what he never knew he touched.",
    '5:4': "A rash oath binds, whether it promised good or evil. Words let go lightly are treated as debts that fall due.",
    '5:5': "\"He shall confess that he hath sinned in that thing.\" The animal does not save him from naming what he did.",
    '5:6': "The same offering is called both trespass and sin offering. The categories overlap where real cases do.",
    '5:7': "\"If he be not able to bring a lamb.\" The law itself anticipates the man who cannot afford what it has just asked.",
    '5:11': "Flour, with no oil and no frankincense. The poorest sin offering is stripped of everything that would smell pleasant.",
    '5:13': "A handful of flour earns the same sentence as a bullock: it shall be forgiven him. The verdict is not means-tested.",
    '5:15': "Trespass in holy things is priced in sanctuary shekels. Sacrilege is reckoned as a debt with a figure attached.",
    '5:16': "He repays the harm and adds a fifth. The sacrifice does not cancel the restitution; it comes on top of it.",
    '5:17': "\"Though he wist it not, yet is he guilty.\" Leviticus refuses to make ignorance the measure of innocence.",
    '5:19': "\"He hath certainly trespassed against the LORD.\" The charge is restated plainly after the remedy has been given.",
    # ---- Chapter 6 ----
    '6:2': "Lying to a neighbour about a deposit is a trespass against the LORD. God is named as the party injured.",
    '6:5': "Principal and a fifth are repaid \"in the day of his trespass offering.\" He squares with the man before the altar.",
    '6:7': "Forgiveness covers \"any thing of all that he hath done.\" Nothing is held back from the list for later.",
    '6:9': "The burnt offering burns all night with nobody watching. Worship continues through the hours the camp is asleep.",
    '6:10': "The priest puts on his linen to shovel ashes. The holy dress is worn for the least impressive job at the altar.",
    '6:11': "He changes clothes to carry the ashes out. What is worn inside the court does not go walking beyond the camp.",
    '6:13': "\"It shall never go out.\" Israel's one unbroken duty is feeding a fire, morning after morning, for ever.",
    '6:16': "The priests eat their portion in the court, not at home. Their wages are consumed inside the place they serve.",
    '6:17': "\"I have given it unto them for their portion.\" A priest's living is described as God's gift, not as his fee.",
    '6:18': "\"Every one that toucheth them shall be holy.\" Contact with the offering carries holiness outward, not defilement in.",
    '6:20': "Aaron has a daily offering of his own, morning and evening. The man who handles everyone's sacrifices brings one.",
    '6:23': "A priest's own meat offering is wholly burnt and never eaten. No man in Israel may live off his own atonement.",
    '6:26': "The priest who offers the sin offering eats it. Bearing another man's sin is also, in this law, how he is fed.",
    '6:28': "The pot it boiled in is broken. What has held the sin offering does not go back to ordinary kitchen use.",
    '6:30': "Where the blood went inside, the flesh is burnt and no one eats. The offering that reaches furthest in feeds nobody.",
    # ---- Chapter 7 ----
    '7:7': "\"There is one law for them.\" Sin and trespass are distinguished by name and handled with equal gravity.",
    '7:8': "The hide goes to the priest who offered it. Even a whole burnt offering leaves something behind for somebody to use.",
    '7:9': "Baked offerings belong to the priest who presented them. Work done at the altar is paid for from the altar.",
    '7:10': "The dry meat offerings are divided \"one as much as another.\" Part of the priests' income is deliberately levelled.",
    '7:12': "A peace offering may be simple thanksgiving. Not every approach to the altar is prompted by something gone wrong.",
    '7:13': "Leavened bread comes with the thanksgiving — the one place leaven is allowed, because this loaf is eaten, not burned.",
    '7:15': "Thanksgiving flesh must be eaten the same day. Gratitude is given a shelf life short enough to force a shared table.",
    '7:16': "A vow or freewill offering keeps a second day. What was promised in advance is given slightly more room.",
    '7:18': "On the third day it \"shall not be imputed unto him.\" A right sacrifice can be voided by how it is treated afterward.",
    '7:20': "An unclean man eating holy flesh is cut off. The meal that signifies peace is the thing that severs him.",
    '7:24': "Fat from an animal found dead may be put to other uses. The ban is on eating it, not on handling it at all.",
    '7:25': "Fat is barred because it is the portion men offer by fire. It is withheld not as unhealthy but as God's.",
    '7:26': "No blood of fowl or beast in any dwelling. The rule is laid down here; chapter 17 will stop and explain it.",
    '7:30': "\"His own hands shall bring the offerings.\" The priest does not carry it in for him; the man presents it himself.",
    '7:31': "The fat burns and the breast goes to Aaron. God's portion is taken first and the priest's is cut from the rest.",
    '7:32': "The right shoulder, the best joint, goes to the priest. Israel's meals are taxed in favour of the tribe with no land.",
    '7:34': "\"Have I taken... and have given them unto Aaron.\" God takes from the people in order to hand it to his servants.",
    '7:36': "A statute for ever, dated to the day of the anointing. The priests' support was settled before they had served a day.",
    '7:37': "Five offerings named in a single breath. The reader has been handed a whole vocabulary for approaching God.",
    '7:38': "\"In the wilderness of Sinai.\" A law assuming ovens, fields and flocks is given to people living out of tents.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:3': "The whole congregation is gathered to watch. Priests are not made privately; Israel sees who is set over it.",
    '8:5': "\"This is the thing which the LORD commanded to be done.\" Moses claims no authorship of the rite he conducts.",
    '8:6': "Aaron is washed before he is robed, and Moses does the washing. A priest's first act is to be acted upon.",
    '8:8': "Urim and Thummim are put into the breastplate. The means of getting God's answer is issued with the uniform.",
    '8:9': "The golden plate is called the holy crown. The first crowned head in Israel belongs to a priest, not a king.",
    '8:10': "The oil goes on the tent and its furniture first. The place is sanctified before the man who will serve in it.",
    '8:11': "The altar is sprinkled seven times before anything is offered on it. The instrument of cleansing is cleansed first.",
    '8:12': "Oil is poured over Aaron's head. Messiah begins as nothing grander than this: a man with oil running down him.",
    '8:13': "The sons receive coats and bonnets, not the ephod. The office is shared; its highest part of it is not.",
    '8:14': "Aaron lays hands on the sin offering. The man about to make atonement needs one made for himself first.",
    '8:15': "The blood is put on the altar to purify it. Even the furniture Israel built for God has to be reconciled.",
    '8:17': "The bullock burns outside the camp. Aaron does not eat his own sin offering; it is carried out and destroyed.",
    '8:23': "Blood on ear, thumb and toe. The consecration touches the extremities, as though outlining the whole man.",
    '8:27': "The portions are laid in their own hands and waved. They hold their consecration out before it is taken from them.",
    '8:29': "The breast falls to Moses this once. The man who ordains the priesthood never belongs to it himself.",
    '8:30': "Oil and altar blood together, on the men and on their clothes. Anointing alone did not finish the work.",
    '8:31': "They boil the flesh at the door and eat it. Ordination ends at a meal rather than with a charge.",
    '8:33': "Seven days inside the door without going out. The men who will stand between God and Israel are kept apart first.",
    '8:34': "\"So the LORD hath commanded to do, to make an atonement for you.\" The whole week is summed up as atonement.",
    '8:35': "\"That ye die not.\" Correctly ordained priests are told outright that this work is capable of killing them.",
    '8:36': "\"Aaron and his sons did all things which the LORD commanded.\" The chapter's verdict is exactly that, and no more.",
    # ---- Chapter 9 ----
    '9:1': "The eighth day, after seven of consecration. Israel's worship begins the morning after the week of preparation.",
    '9:2': "Aaron's first act as priest is a sin offering for himself — and a calf, of all animals, after what he made at Sinai.",
    '9:3': "The congregation brings animals of its own. The people are not spectators at the ordination of their priest.",
    '9:4': "\"For to day the LORD will appear unto you.\" The sacrifices are commanded as preparation for a visit.",
    '9:5': "\"All the congregation drew near, and stood before the LORD.\" Drawing near is what this whole book is arranging.",
    '9:6': "The glory appears when the thing commanded is done. God ties his showing up to obedience, not to fervour.",
    '9:7': "\"An atonement for thyself, and for the people\" — in that order. No priest carries others past where he stands.",
    '9:15': "The people's goat is offered \"as the first.\" Priest and congregation are dealt with by one procedure.",
    '9:17': "The meat offering is burnt \"beside the burnt sacrifice of the morning.\" The new day begins alongside the routine.",
    '9:22': "Aaron lifts his hand and blesses them before he comes down. The first thing a priest does after blood is bless.",
    '9:23': "They go in, come out, and bless — and then the glory appears. The people are spoken to before they are shown.",
    '9:24': "Fire comes out from the LORD and eats the offering. Israel did not light what made their sacrifice acceptable.",
    # ---- Chapter 10 ----
    '10:1': "\"Which he commanded them not.\" The offence is not a rule broken but worship invented and brought unasked.",
    '10:2': "The fire that devours them comes from the same place as the fire that had just accepted the offering.",
    '10:3': "\"And Aaron held his peace.\" The text hands the bereaved father no speech and does not fill the silence for him.",
    '10:4': "Cousins are called to carry the bodies. Even burying them is work handed to men outside the priesthood.",
    '10:5': "They are carried out in their coats. The garments that made them priests become what they are buried in.",
    '10:6': "Aaron is forbidden to mourn publicly, while all Israel is left to weep for his sons in his place.",
    '10:7': "\"The anointing oil of the LORD is upon you.\" A calling can hold a man at his post on the worst day of his life.",
    '10:9': "No wine in the tabernacle. The rule arrives the moment after two priests died doing something unauthorised.",
    '10:10': "Putting a difference between holy and unholy, clean and unclean, is named as the priest's actual work.",
    '10:11': "And to teach. The priest is not only a man at an altar but the one Israel learns the law from.",
    '10:12': "Moses turns straight back to the portions. The surviving sons are told to eat on the day of the funeral.",
    '10:14': "Daughters eat the wave breast in a clean place. The priestly portion feeds a whole household, women included.",
    '10:16': "Moses is angry that the goat was burnt instead of eaten. What he pursues is a question of who ate what.",
    '10:17': "\"God hath given it you to bear the iniquity of the congregation.\" Eating the offering was part of carrying sin.",
    '10:19': "\"Such things have befallen me.\" Aaron answers with his grief and asks whether God would have wanted that meal.",
    '10:20': "\"And when Moses heard that, he was content.\" A ruling bends for a man who has just buried two sons.",
})

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:2': "\"These are the beasts which ye shall eat.\" Israel's separateness is made visible three times a day, at table.",
    '11:3': "The test is hoof and cud together. Two conditions mean a man has to look twice before he decides.",
    '11:4': "The camel chews the cud and fails on the hoof. Half a qualification counts here as none at all.",
    '11:7': "The swine has the hoof right and the cud wrong. The animal that became the byword for uncleanness nearly passed.",
    '11:8': "Not eating, and not touching the carcase either. The line is drawn some distance short of the thing forbidden.",
    '11:9': "Fins and scales settle everything in the water. What is unclean is what does not keep to the form of its element.",
    '11:13': "The birds barred are the killers and the carrion eaters. Where the logic shows, the list is not arbitrary.",
    '11:21': "Locusts are permitted. Among the swarming things, the one a poor man could gather by hand is the exception.",
    '11:24': "\"Unclean until the even.\" Most defilement in this book expires at nightfall and costs nothing to remove.",
    '11:32': "A dead lizard falling into a pot makes the pot unclean. Uncleanness is treated as something that travels by touch.",
    '11:33': "The earthen vessel is broken rather than washed. What is porous cannot be scoured, so it is not kept.",
    '11:35': "Even the oven is broken down. A household's fittings are subject to a law about where a dead mouse fell.",
    '11:36': "A spring or a cistern stays clean. Water in quantity is not held to the rule that governs a cooking pot.",
    '11:37': "Dry seed stays clean and wet seed does not. The boundary runs through the ordinary physics of a farm.",
    '11:39': "A clean animal that dies of itself still defiles. It was never the species that made the meat fit to eat.",
    '11:43': "\"Ye shall not make yourselves abominable.\" The danger named is self-inflicted rather than caught from outside.",
    '11:44': "\"Ye shall be holy; for I am holy.\" The reason offered for the diet is not health but the character of the God behind it.",
    '11:45': "The God who brought them up out of Egypt is the one now saying be holy. The rescue comes first, and then the demand.",
    '11:47': "\"To make a difference.\" The whole chapter exists to train a people to see the distinctions God sees.",
    # ---- Chapter 12 ----
    '12:2': "Childbirth makes a woman unclean though nothing about it is sinful. Uncleanness and guilt are not the same thing.",
    '12:3': "Circumcision on the eighth day, set inside the mother's uncleanness. The covenant sign keeps its own calendar.",
    '12:4': "Thirty-three days barred from hallowed things. The law keeps a new mother at home rather than at worship.",
    '12:5': "Twice as long for a daughter, and no reason is given. Some of this law is left unexplained even to Israel.",
    '12:6': "A burnt offering and a sin offering after a birth. The most ordinary event in a household ends at the altar.",
    '12:8': "\"If she be not able to bring a lamb\" — two pigeons. This is what Mary brought, and Luke means it to be noticed.",
    # ---- Chapter 13 ----
    '13:2': "The suspected man is brought to a priest, not a physician. What is at stake is his standing in the camp.",
    '13:3': "The priest looks, and pronounces. The whole procedure turns on a word spoken over a man by somebody else.",
    '13:4': "Shut up seven days and looked at again. The law builds in delay instead of rushing to the worst reading.",
    '13:5': "Another seven days if nothing has changed. Priests are required to be slow before they put a man outside.",
    '13:6': "\"It is but a scab.\" The system is as ready to pronounce a man clean as it is to exclude him.",
    '13:11': "An old leprosy is not shut up for observation. Where the case is plain, the waiting period would be a pretence.",
    '13:13': "Covered head to foot, he is clean. The man wholly white comes back in; it is partial disease that keeps him out.",
    '13:14': "One patch of raw flesh makes him unclean again. What is still live and open is the thing the law will not have.",
    '13:16': "If the raw flesh turns white he comes back to the priest. No verdict here is treated as the last one.",
    '13:23': "A scar left by a boil is only a scar. The priest is trained to tell healed damage from disease still working.",
    '13:33': "He is shaved, but not over the sore. Even the examination is careful not to disturb what it is reading.",
    '13:37': "Black hair growing in the scall means it is healed. The sign that ends the quarantine is life coming back.",
    '13:39': "A freckled spot is clean. Most marks on most skin are nothing, and the law takes the trouble to say so.",
    '13:40': "\"Yet is he clean.\" A bald man is told plainly he is not diseased, in the middle of a chapter of warnings.",
    '13:45': "He must cry \"Unclean, unclean\" himself. The leper is made to announce his own exclusion wherever he walks.",
    '13:46': "\"He shall dwell alone; without the camp.\" The punishment is not pain but distance from where God dwells.",
    '13:47': "The same word covers mildew in a coat. Uncleanness attaches to a man's property as well as to his body.",
    '13:52': "The garment is burned. Property is given up to keep the spread out; nothing owned is too valuable to lose.",
    '13:54': "The cloth is washed and shut up again. Even a coat is given a second chance before it is written off.",
    '13:58': "Washed a second time, and clean. The last word on the infected garment is restoration rather than the fire.",
    '13:59': "\"To pronounce it clean, or to pronounce it unclean.\" Fifty-nine verses to teach one man to make one judgement.",
})

TAKEAWAYS.update({
    # ---- Chapter 14 ----
    '14:2': "\"The law of the leper in the day of his cleansing.\" The book that put him out has a chapter on his coming back.",
    '14:3': "The priest goes out of the camp to look at him. Somebody walks out to the excluded man before he can return.",
    '14:4': "Two birds, cedar wood, scarlet and hyssop. The cleansing is built out of the cheapest things a man could find.",
    '14:5': "One bird killed in an earthen vessel over running water. A death and living water are held in the same basin.",
    '14:7': "The second bird is dipped in the first one's blood and let go. The freed life carries the marks of the death.",
    '14:8': "He washes, shaves, comes into the camp, and still sleeps outside his tent a week. Return is granted by stages.",
    '14:9': "Head, beard, eyebrows, all of it. The man coming back is stripped of every hair he grew while he was outside.",
    '14:10': "Three lambs, flour and a log of oil on the eighth day. Coming back costs more than most offerings in this book.",
    '14:12': "A trespass offering, though no offence has been named. The road back into the camp runs through the altar.",
    '14:14': "Blood on ear, thumb and toe — the marks used to ordain Aaron. The restored leper is handled like a priest.",
    '14:17': "Oil goes on top of the blood in the same three places. Nothing is anointed here that was not first covered.",
    '14:18': "What is left in the priest's hand is poured on the man's head. The remainder goes to him, not back to store.",
    '14:20': "\"And he shall be clean.\" After eight days and three lambs, the verdict takes four words.",
    '14:21': "\"And if he be poor.\" The whole elaborate ceremony is rewritten for the man who cannot afford it.",
    '14:22': "\"Such as he is able to get\" — the phrase is repeated until it cannot be mistaken for a grudging allowance.",
    '14:31': "The poor man's two birds make the same atonement as the rich man's lambs. Cost and effect are uncoupled.",
    '14:32': "The statute is titled for the man \"whose hand is not able.\" A law named after poverty rather than disease.",
    '14:34': "\"I put the plague of leprosy in a house.\" God claims the trouble instead of leaving it to bad luck.",
    '14:35': "\"It seemeth to me there is as it were a plague.\" A householder's hesitant guess is enough to start the process.",
    '14:36': "The house is emptied before the priest looks in. Once he has ruled, everything still inside would go with it.",
    '14:40': "The infected stones are pulled out and dumped outside the city. The first remedy is surgery, not demolition.",
    '14:42': "New stones and new mortar. The house is repaired before anyone considers condemning it, and repair costs money.",
    '14:45': "If it breaks out again the house comes down. No man keeps his home at the price of the town around it.",
    '14:46': "Whoever goes in while it is shut up is unclean. A warning disregarded still has its effect on the one who ignored it.",
    '14:48': "\"Because the plague is healed.\" The word spoken over a restored man is spoken here over a wall.",
    '14:53': "The living bird is let go and atonement is made for a house. Even masonry is dealt with by blood in this book.",
    '14:57': "\"To teach when it is unclean, and when it is clean.\" All the detail is given a purpose, and it is instruction.",
    # ---- Chapter 15 ----
    '15:2': "A running issue, described without euphemism. The law does not find the body too embarrassing to legislate.",
    '15:4': "The bed and the seat are unclean. Defilement travels through furniture, which is why the rules reach indoors.",
    '15:5': "Wash, bathe, unclean until the even. The remedy for most of this chapter is water and the end of the day.",
    '15:8': "Even his spittle defiles. The rules follow contagion along every path a body actually uses.",
    '15:11': "\"And hath not rinsed his hands in water.\" Washed hands change what he passes on, and the law knows it.",
    '15:12': "Earthenware broken, wood rinsed. The law keeps distinguishing what can be made clean from what cannot.",
    '15:13': "Seven days are counted after the issue stops. Cleansing begins only once the thing is genuinely over.",
    '15:14': "Two pigeons on the eighth day. A private condition is still closed out at a public altar.",
    '15:16': "Ordinary sexual function makes a man unclean. Nothing here is called sin; it is called not fit to approach.",
    '15:18': "Both of them bathe. The rule falls on husband and wife alike, with no hint that either is at fault.",
    '15:19': "A woman is set apart seven days on the same terms a man is. The chapter is symmetrical about who is affected.",
    '15:24': "A man who lies with her carries her seven days of uncleanness. Defilement transfers rather than staying put.",
    '15:25': "A long issue counts as unbroken separation. This is the woman in the gospels, twelve years untouchable.",
    '15:28': "She numbers seven days and is clean. A condition with no end in sight is given a procedure that ends it.",
    '15:30': "Two birds, sin offering and burnt offering — exactly what the man brought. Her restoration is priced the same.",
    '15:31': "\"That they die not in their uncleanness, when they defile my tabernacle.\" All of it is about who is living in the camp.",
})

TAKEAWAYS.update({
    # ---- Chapter 16 ----
    '16:1': "The day of atonement is dated from the deaths of Aaron's sons. This law arrives out of a funeral.",
    '16:2': "\"That he come not at all times.\" Access is restricted not because God is absent but because he appears there.",
    '16:3': "Aaron does not come in empty-handed, and the first thing he brings is a sin offering for himself.",
    '16:4': "Plain linen, not the gold and the breastplate. On the day he goes furthest in, he dresses like a servant.",
    '16:5': "The two goats come from the congregation. The people supply what will carry what they cannot carry themselves.",
    '16:6': "He atones for himself and his house before he touches the people's offering. The mediator needs a mediator.",
    '16:7': "Both goats are presented alive before the LORD. Neither is picked out by the priest's estimate of it.",
    '16:8': "A lot decides which goat dies. The difference between the two lies in the lot that fell, not in the animals.",
    '16:9': "The lot marked for the LORD sends that goat to the knife. What falls to God in this ceremony is a death.",
    '16:10': "The scapegoat atones by being presented alive and sent away. Atonement has two halves and only one is a killing.",
    '16:11': "Twice the text says the bullock is \"for himself.\" Aaron's own guilt is not glossed over on Israel's great day.",
    '16:12': "Coals off the altar and incense beaten small. He carries fire from the place of blood into the place of God.",
    '16:13': "The incense cloud covers the mercy seat \"that he die not.\" Even the one man let in is let in behind smoke.",
    '16:14': "Blood on the mercy seat. The lid over the broken tables is the exact spot where the blood is put.",
    '16:15': "The people's goat is treated precisely as the priest's bullock was. Inside the vail no distinction is made.",
    '16:16': "Atonement is made for the holy place itself, which \"remaineth among them in the midst of their uncleanness.\"",
    '16:17': "Nobody else may be in the tent. The decisive act of Israel's year is done with no witness to it.",
    '16:18': "The altar is cleansed with the two bloods mixed together. Priest's sin and people's sin are handled at once.",
    '16:19': "Sprinkled seven times, cleansed and hallowed. Even the place where cleansing happens needs cleansing yearly.",
    '16:20': "\"When he hath made an end of reconciling\" — then the live goat. The sending away follows the blood, not replaces it.",
    '16:21': "Both hands on the head, and every sin confessed aloud. The guilt is named in full before it is carried off.",
    '16:22': "\"Unto a land not inhabited.\" The sin is not merely covered over but taken where it will never be found.",
    '16:23': "The linen garments are left behind in the tent. What he wore in there does not come out with him.",
    '16:24': "He washes and puts his own garments back on. The high priest goes back to being the man the camp knows.",
    '16:26': "The man who led the goat away has to wash. Handling what carried sin leaves something on the handler.",
    '16:27': "The bodies whose blood went furthest in are burned furthest out. Hebrews builds its argument on that geography.",
    '16:29': "The tenth day of the seventh month, and the stranger keeps it too. Israel's holiest day includes the outsider.",
    '16:30': "\"That ye may be clean from all your sins before the LORD.\" One day a year the whole account is declared settled.",
    '16:31': "A sabbath of rest on which they afflict their souls. The day of atonement is kept by stopping, not by doing more.",
    '16:32': "Whoever is anointed in his father's stead does this. The office makes the atonement, not the quality of the man.",
    '16:33': "Sanctuary, tent, altar, priests, people — five atonements in a verse. Nothing in Israel is exempt from needing one.",
    '16:34': "\"Once a year.\" It must all be done again next autumn, and that repetition is what Hebrews will argue from.",
    # ---- Chapter 17 ----
    '17:3': "The offence is killing an ox anywhere but the door. For a season Israel could not even butcher away from the tent.",
    '17:4': "\"Blood shall be imputed unto that man; he hath shed blood.\" Careless slaughter is described in the words for murder.",
    '17:5': "The reason is given plainly: sacrifices made in the open field are to be brought in. The law is pulling them back.",
    '17:6': "The priest sprinkles and burns. What a man would have done alone in a field is handed to somebody appointed.",
    '17:7': "\"After whom they have gone a whoring.\" The altars out in the fields were not harmless; they had other owners.",
    '17:8': "The stranger is bound by the same rule. Whoever lives in the camp lives under the camp's single altar.",
    '17:9': "The penalty is being cut off, not put to death. What the offender loses is the people he belonged to.",
    '17:10': "\"I will even set my face against that soul.\" On this one rule God says he will see to it personally.",
    '17:11': "\"I have given it to you upon the altar.\" The blood that atones is God's provision, not man's payment to him.",
    '17:12': "The prohibition is repeated for the stranger. The one thing this book stops to explain is not for insiders only.",
    '17:13': "Blood from hunting is poured out and covered with dust. Even a meal with no altar must own the life it took.",
    '17:14': "Three times in a single verse: the life is the blood. Leviticus repeats it because the rest of the book stands on it.",
    '17:15': "Eating what died of itself costs a wash and a day. The remedy stays small where the fault is small.",
    '17:16': "\"If he wash them not... he shall bear his iniquity.\" The lasting trouble is refusing the cleansing, not the stain.",
})

TAKEAWAYS.update({
    # ---- Chapter 18 ----
    '18:2': "Before one prohibition is given, the speaker names himself. The list rests on who he is, not on custom.",
    '18:3': "Egypt behind, Canaan ahead: Israel is told to resemble neither the place it left nor the place it is going.",
    '18:5': "\"Which if a man do, he shall live in them.\" Paul quotes this line to show the terms on which law offers life.",
    '18:6': "Near of kin are not available. Every clause that follows is this one principle worked out case by case.",
    '18:7': "Father and mother come first, in the house where a child has the least protection of anyone.",
    '18:8': "The father's wife is barred as the father's own body. Marriage, not blood, is what puts her out of reach.",
    '18:9': "A sister born at home or born abroad, named both ways. The loophole in an irregular birth is closed.",
    '18:12': "Father's sister and mother's sister alike. The ban runs through both parents, which local custom did not.",
    '18:14': "The aunt is protected because of the uncle. The wrong is described as done to the man who is not present.",
    '18:15': "The daughter in law. Genesis 38 had already told the story this clause is written against.",
    '18:16': "The brother's wife. John the Baptist lost his head for quoting this clause to Herod.",
    '18:17': "\"It is wickedness.\" The list stops to name the thing, having simply listed up to now.",
    '18:18': "Two sisters, and the reason given is \"to vex her.\" Jacob's household had already proved that cruelty.",
    '18:20': "Adultery appears as one item among the forbidden relations rather than as a category of its own.",
    '18:21': "A child burned to Molech is set in the middle of this list, and the charge is profaning God's name.",
    '18:22': "Man with man, stated without qualification and called abomination. Nothing in the clause softens it.",
    '18:23': "A man or a woman with a beast is called confusion: the objection is to the boundary, not the appetite.",
    '18:24': "The nations were cast out for these very things, which makes the list an account of why Canaan fell.",
    '18:25': "\"The land itself vomiteth out her inhabitants.\" The ground is described as sickened by what is done on it.",
    '18:28': "\"That the land spue not you out also.\" Israel is told plainly that it has no immunity from that reflex.",
    '18:30': "\"Abominable customs.\" What the neighbours did by habit is the pressure this whole chapter stands against.",
    # ---- Chapter 19 ----
    '19:2': "\"Ye shall be holy\" is said to the whole congregation, not to the priests. Holiness is not a clergy trade.",
    '19:3': "Mother before father, and the sabbath in the same breath. Household and sanctuary are one command here.",
    '19:4': "Molten gods are forbidden to people who had made one at the foot of this same mountain.",
    '19:5': "\"At your own will.\" The peace offering is the one sacrifice nobody is obliged to bring.",
    '19:6': "Eaten today or tomorrow, then burnt. A holy meal is not permitted to turn into leftovers.",
    '19:9': "The corners are left unreaped. The poor are fed by what the owner deliberately does not take.",
    '19:10': "Gleanings belong to the poor and the stranger by law. Ruth lives off this verse being kept.",
    '19:11': "Stealing, dealing falsely, lying: three ways of taking, and the last of them needs no hands.",
    '19:12': "A false oath pulls God's name into the lie, and the damage named is done to the name.",
    '19:13': "Wages are not held overnight. A hired man eats tonight on today's pay or he does not eat.",
    '19:14': "The deaf cannot hear the curse, the blind cannot see the stone. The only safeguard left is fearing God.",
    '19:15': "Judgment is bent by pitying the poor as surely as by flattering the mighty, and both are named.",
    '19:16': "Talebearing stands next to standing against a neighbour's blood. Words are treated as able to kill.",
    '19:17': "Hatred kept in the heart is answered by rebuke out loud. The alternative to confrontation is not peace.",
    '19:18': "\"Thou shalt love thy neighbour as thyself\" — the second great commandment, left in a list of field rules.",
    '19:19': "Mingled cattle, mingled seed, mingled cloth. Israel is taught holiness by keeping unlike things apart.",
    '19:20': "She is not put to death \"because she was not free.\" Her lack of freedom is read as lack of consent.",
    '19:22': "\"The sin which he hath done shall be forgiven him.\" The ram is brought; the forgiveness is pronounced.",
    '19:23': "Three years of fruit counted uncircumcised. Even an orchard is made to wait before it is reckoned clean.",
    '19:24': "The fourth year's whole crop goes to praise, before the man who planted the tree tastes any of it.",
    '19:26': "Divination is banned alongside eating with the blood. Both reach after life by a door not opened.",
    '19:27': "The rounded head and the marred beard were the neighbours' mourning cuts, not a matter of fashion.",
    '19:28': "Cuttings and printed marks for the dead: grief is not to be recorded on the body.",
    '19:29': "A father is told not to sell his daughter, and the consequence named is a whole land gone to whoredom.",
    '19:31': "Consulting familiar spirits defiles the one who asks. Saul went to Endor knowing this verse.",
    '19:32': "Rising before the grey head is made a matter of fearing God rather than of good manners.",
    '19:34': "\"Thou shalt love him as thyself; for ye were strangers.\" The command is argued from Israel's own memory.",
    '19:36': "Just weights sit beside loving the neighbour, because shorting a customer is that sin done at retail.",
    # ---- Chapter 20 ----
    '20:2': "Molech again, now with a sentence attached, and the congregation itself is made to do the stoning.",
    '20:3': "\"To defile my sanctuary, and to profane my holy name.\" A child burned elsewhere is an offence at the altar.",
    '20:4': "The law expects a village that will hide its eyes, and legislates for that in advance.",
    '20:8': "\"I am the LORD which sanctify you.\" The call to sanctify themselves is bracketed by his doing it.",
    '20:9': "Cursing a parent is capital. The household is treated as the floor the rest of the code stands on.",
    '20:10': "Both the adulterer and the adulteress die. The man is not handled as the woman's misfortune.",
    '20:11': "The father's wife: the offence is stated as done to the father, who may well be dead by then.",
    '20:13': "Both men bear the sentence, and the sentence is death. Chapter 18 forbade it; this chapter prices it.",
    '20:14': "Burning, and the stated reason is to clear wickedness out from among them, not to satisfy outrage.",
    '20:15': "The beast is killed as well, though nobody pretends it consented. The whole act is wiped off the ground.",
    '20:17': "Brother and sister are cut off rather than executed. The penalties in this chapter are graded.",
    '20:19': "\"They shall bear their iniquity.\" No court sentence is named, and the matter is left with God.",
    '20:20': "The penalty is dying childless, which answers an offence committed against somebody else's line.",
    '20:22': "Keeping the statutes is what lets the land keep them. Enforcement is framed as self-preservation.",
    '20:23': "\"I abhorred them.\" Disgust, not merely a verdict, is given as the reason Canaan lost the ground.",
    '20:25': "Clean and unclean at the table teach daily the distinction this chapter has been drawing about people.",
    '20:26': "\"That ye should be mine.\" Being severed from the nations is for belonging, not for superiority.",
    '20:27': "The chapter ends where it opened, with traffic in other powers, and with the same penalty.",
})

TAKEAWAYS.update({
    # ---- Chapter 21 ----
    '21:1': "A priest is not to be defiled for the dead. His work at the altar outranks the village funeral.",
    '21:2': "Mother, father, son, daughter, brother. Close grief is allowed for; the rule is not that he may not mourn.",
    '21:3': "The unmarried sister is named among his exceptions, since there is nobody else to bury her.",
    '21:5': "The mourning cuts every neighbour used are closed to priests. Their grief has to look different.",
    '21:6': "\"The bread of their God, they do offer: therefore they shall be holy.\" The reason is what their hands handle.",
    '21:7': "Whom a priest marries is part of his qualification. The office reaches into his house.",
    '21:8': "\"Thou shalt sanctify him.\" The congregation is made responsible for the priest's holiness, not only the priest.",
    '21:9': "The daughter's sin is said to profane her father. Office runs both directions through a family.",
    '21:10': "The high priest may not rend his clothes. Caiaphas rent his at the trial of Jesus, breaking this verse.",
    '21:11': "Not even for father or mother. The exception every other priest is granted is withdrawn from this one.",
    '21:12': "He may not leave the sanctuary. The anointing oil keeps him where it put him.",
    '21:14': "A virgin of his own people. The man who stands for Israel is bound even in whom he may marry.",
    '21:17': "A blemish bars a son of Aaron from offering. Fitness at the altar, not character, is what is measured.",
    '21:18': "Blind, lame, flat nose. The list is physical and unsentimental, and none of it is the man's own doing.",
    '21:22': "\"He shall eat the bread of his God.\" Barred from serving, he is never barred from eating; that is the mercy here.",
    '21:23': "The reason given for keeping him from the vail is God's sanctuaries, not any judgment on the man.",
    # ---- Chapter 22 ----
    '22:2': "Priests are told to keep clear of holy things at the wrong moment. Nearness is the hazard of their trade.",
    '22:3': "A priest who comes to holy things unclean is cut off from God's presence, not washed and restored by evening.",
    '22:4': "A leprous priest eats nothing holy until he is clean. The office does not exempt the body.",
    '22:7': "\"Because it is his food.\" The priest's holy portion is also his dinner; calling and livelihood are one thing.",
    '22:9': "\"Lest they bear sin for it, and die.\" The risk of the priesthood is stated plainly to the priests.",
    '22:10': "The holy portion feeds the priest's household and nobody else's. A guest is not fed from the altar.",
    '22:11': "A slave bought with his money eats it; a hired man does not. Belonging rather than wages decides.",
    '22:12': "A daughter who marries outside loses the portion. She leaves the household, and the food goes with it.",
    '22:13': "Widowed or divorced, she comes home and eats again. The door back into her father's house is not shut.",
    '22:14': "Eating holy food unwittingly still costs the fifth part added. Ignorance lowers the guilt, not the debt.",
    '22:18': "Vows and freewill offerings, and the stranger may bring them. The voluntary gift is open to the outsider.",
    '22:19': "\"At your own will a male without blemish.\" What is freely given is still not given carelessly.",
    '22:21': "A vow must be perfect. What was promised in trouble is paid in full once the trouble has passed.",
    '22:22': "Blind, broken, maimed: the list that barred a priest now bars an animal. The altar keeps one standard.",
    '22:23': "A defective beast may serve a freewill gift but never a vow. A promise is held to the higher bar.",
    '22:24': "Nothing mutilated is offered, and the practice is barred from the land itself, not merely from the altar.",
    '22:25': "A blemished gift from a foreign hand is refused too. The standard does not relax for an outside donor.",
    '22:27': "Seven days under the dam. A newborn is left with its mother before it can be given away.",
    '22:28': "The cow and her young are not killed in one day. Sacrifice is given a rule against wiping out a line.",
    '22:32': "\"I will be hallowed among the children of Israel.\" The name is not kept holy privately but in a people.",
    # ---- Chapter 23 ----
    '23:2': "\"Even these are my feasts.\" The calendar is claimed as his before a single date is named.",
    '23:3': "The sabbath heads the list of feasts. The weekly one is put ahead of every annual one.",
    '23:5': "Passover on the fourteenth at even. Israel's year is reckoned from the night it left Egypt.",
    '23:6': "Seven days of unleavened bread. The escape is remembered by eating the bread of people in a hurry.",
    '23:8': "\"Ye shall offer an offering made by fire... seven days.\" The week is not only abstaining but bringing.",
    '23:10': "The first sheaf comes in before the harvest does. The crop is God's before it is ever the farmer's.",
    '23:11': "\"On the morrow after the sabbath.\" The wave sheaf falls on the day Paul calls Christ the firstfruits.",
    '23:12': "A lamb goes up with the sheaf. Even thanks for grain is brought to the altar alongside a death.",
    '23:14': "No bread, no parched corn, no green ears until the offering is made. The first bite waits on the altar.",
    '23:15': "Fifty days are counted out from the sheaf. The interval is itself commanded, which is why Pentecost counts.",
    '23:17': "Two wave loaves \"baken with leaven\" — the one offering in the book where leaven is required rather than banned.",
    '23:19': "A sin offering is killed at the harvest feast. Thanksgiving is not allowed to pretend nothing is wrong.",
    '23:20': "The waved loaves become the priest's. The harvest festival feeds the men who were given no fields.",
    '23:22': "The gleaning law is set down in the middle of the feast calendar. Keeping the feast includes leaving the corners.",
    '23:24': "Trumpets on the first day of the seventh month. The month of atonement opens with a noise.",
    '23:27': "The day of atonement is the one feast kept by affliction rather than by eating.",
    '23:28': "No work at all that day, because the work being done is not theirs to do.",
    '23:29': "Whoever will not be afflicted is cut off. Refusing the fast counts as refusing the atonement.",
    '23:30': "\"The same soul will I destroy.\" Here God says he does the cutting off himself, without the congregation.",
    '23:32': "From even unto even, beginning the ninth day. The holiest day is measured so nobody can shorten it.",
    '23:34': "Tabernacles five days after the fast. Mourning and rejoicing are set in the same month of the year.",
    '23:36': "An eighth day added after the seven. That is the great day of the feast on which John has Jesus cry out.",
    '23:38': "\"Beside the sabbaths... beside your gifts.\" The fixed calendar never crowds out what anyone brings freely.",
    '23:40': "Palm branches, willows, and a command to rejoice. This is the feast where the joy itself is legislated.",
    '23:42': "Israel moves outdoors for a week, into the flimsiest shelter it can build.",
    '23:43': "\"That your generations may know.\" The booths are kept up for the sake of those who were never there.",
})

TAKEAWAYS.update({
    # ---- Chapter 24 ----
    '24:2': "The oil is brought by the people, so the lamp a priest tends burns on what the whole camp supplies.",
    '24:3': "\"From the evening unto the morning.\" The light is kept through the hours when nobody is there to see it.",
    '24:5': "Twelve cakes, one for each tribe, set out in a room only priests ever enter.",
    '24:7': "The frankincense is what burns; the loaves are eaten. Memorial and meal are divided between them.",
    '24:8': "Fresh bread every sabbath. An everlasting covenant is kept up by a weekly piece of baking.",
    '24:9': "The priests eat what came off God's table. David ate this bread, and Jesus used that against the Pharisees.",
    '24:10': "A half-Egyptian son and an Israelite fall out in the camp. The case begins as an ordinary quarrel.",
    '24:11': "His mother, Shelomith of the tribe of Dan, is named. The offender is not left an anonymous example.",
    '24:12': "He is held in ward while they wait for a word. Israel does not know the penalty and will not invent one.",
    '24:14': "Those who heard him lay hands on his head, the sacrificial gesture. The witnesses hand the guilt back.",
    '24:15': "\"Whosoever curseth his God shall bear his sin.\" The general statute is drawn out of one man's case.",
    '24:16': "The stranger falls under the same sentence. A foreign father buys the blasphemer no exemption.",
    '24:18': "A beast is paid for; a man cannot be. The gap between them is written into the penalties.",
    '24:20': "\"Eye for eye, tooth for tooth\" is a ceiling on revenge, not a licence: never more than the injury done.",
    '24:22': "\"One manner of law, as well for the stranger.\" The case that raised the question involved a half-foreigner.",
    '24:23': "The sentence is carried out and nothing is recorded about how the congregation felt doing it.",
    # ---- Chapter 25 ----
    '25:1': "\"In mount Sinai.\" The jubilee is legislated before Israel owns a foot of the land it governs.",
    '25:2': "\"Then shall the land keep a sabbath unto the LORD.\" The ground is given a commandment of its own.",
    '25:4': "A whole year with no sowing and no pruning. Stopping work takes more trust than doing it.",
    '25:5': "Volunteer growth is left standing. The fallow year is not a loophole for careful gleaning.",
    '25:6': "Owner, servant, hireling and stranger eat off the same unworked field for a year.",
    '25:7': "Cattle and wild beasts eat as well. In the seventh year nobody owns the increase at all.",
    '25:8': "Seven sevens counted to forty-nine. The jubilee is the sabbath scaled up until it reaches property.",
    '25:9': "The trumpet sounds on the day of atonement. Debts are released on the same day sins are.",
    '25:10': "\"Proclaim liberty throughout all the land.\" The year Isaiah announces and Jesus reads out at Nazareth.",
    '25:11': "A second fallow year follows the forty-ninth. The jubilee costs two harvests, not one.",
    '25:14': "\"Ye shall not oppress one another\" is dropped into the middle of instructions for an ordinary sale.",
    '25:15': "Land is bought by the years left before the jubilee. What changes hands is a lease, not the ground.",
    '25:16': "Price rises with many years and falls with few. The market is told exactly how to reckon it.",
    '25:17': "The only check on sharp arithmetic is fearing God, since this kind of dealing is hard to catch.",
    '25:19': "Safety, not merely produce, is promised to the people who let the ground rest.",
    '25:20': "\"What shall we eat the seventh year?\" The objection is written into the law before it is answered.",
    '25:21': "The blessing arrives in the sixth year, before the year of trust begins rather than during it.",
    '25:22': "Old store into the ninth year. The provision is spelled out at length because the fear was real.",
    '25:23': "\"The land shall not be sold for ever: for the land is mine.\" Every property rule here rests on that clause.",
    '25:24': "\"Ye shall grant a redemption for the land.\" A right of buy-back attaches to every sale by law.",
    '25:25': "\"If any of his kin come to redeem it.\" This is the kinsman-redeemer, the office Boaz fills for Ruth.",
    '25:27': "He counts the years and restores the overplus. Redemption is calculated and paid, not asked as a favour.",
    '25:28': "With nothing to pay, he still gets his land at the jubilee. Poverty delays recovery; it cannot cancel it.",
    '25:29': "A walled-city house may be redeemed for one year only. A town is not treated like a field.",
    '25:30': "The town house is sold outright, because no family's inheritance is bound up in its walls.",
    '25:32': "Levites may redeem at any time, having been given no tribal land to fall back on.",
    '25:34': "Levite pasture may never be sold. The tribe with no inheritance gets the tightest protection of all.",
    '25:35': "\"Thou shalt relieve him... though he be a stranger.\" Need, not membership, is what triggers the duty.",
    '25:36': "No interest from a brother in trouble, and the aim is stated: \"that thy brother may live with thee.\"",
    '25:39': "A man sold for debt is not to be held as a slave. The transaction is permitted; the status is not.",
    '25:40': "\"As an hired servant, and as a sojourner.\" The arrangement has an end date built into it from the start.",
    '25:41': "He goes out with his children. A debt is not allowed to outlive the man in his sons.",
    '25:42': "\"They are my servants.\" A man God already owns cannot be bought outright by anybody else.",
    '25:44': "Foreigners may be bought and kept. The chapter guards the brother and leaves the outsider unguarded.",
    '25:46': "Even while permitting perpetual bondage, the verse repeats the limit: no rigour over a brother.",
    '25:47': "A brother sold to a resident foreigner. The law follows him out of Israelite hands and keeps working.",
    '25:48': "\"He may be redeemed again.\" The right to be bought back survives the sale that lost him.",
    '25:49': "Uncle, cousin, any near kin, \"or if he be able, he may redeem himself.\" The list is used up before he is.",
    '25:53': "\"Shall not rule with rigour over him in thy sight.\" Israel is made a witness to how its poor are treated.",
    '25:54': "If nobody redeems him, the jubilee does. The year stands under every redemption that failed.",
    '25:55': "\"Unto me the children of Israel are servants.\" The chapter ends by naming who already owns them.",
})
