#!/usr/bin/env python3
"""Written one-line takeaways for Malachi 1-4."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Malachi means my messenger, which is also the word this book uses for the one it says is coming.",
    '1:2': "\"Wherein hast thou loved us?\" The first dispute answers a declaration of love by asking for evidence.",
    '1:3': "\"I hated Esau.\" Paul takes the line up in Romans 9, where it is about election and not temperament.",
    '1:4': "Edom intends to rebuild. The sentence is not that they cannot build but that what they build comes down.",
    '1:6': "A father and a master, with neither honour nor fear. The priests' reply is to ask when they despised him.",
    '1:7': "\"The table of the LORD is contemptible\" — not said in words, but said in what they were willing to bring.",
    '1:8': "\"Offer it now unto thy governor.\" The test is whether a Persian official would accept what God is handed.",
    '1:9': "The priests are told to pray for grace over a mess of their own making. Intercession does not void the charge.",
    '1:10': "\"Who would shut the doors for nought?\" Nothing in the temple is done unpaid, and God would rather it shut.",
    '1:11': "Great among the Gentiles while his own priests are bored. The pure offering is located outside the building.",
    '1:13': "\"Behold, what a weariness is it!\" The sin on record here is finding the service of God tedious.",
    '1:14': "The deceiver had a sound male in the flock. What is charged is choosing the second best on purpose.",
    # ---- Chapter 2 ----
    '2:2': "\"I will curse your blessings.\" The benediction is turned round in the mouths that pronounce it.",
    '2:3': "The dung of their own feasts spread on their faces. What was offered carelessly is handed straight back.",
    '2:5': "Levi's covenant was life and peace, given for the fear with which he feared. Reverence was the qualification.",
    '2:6': "\"The law of truth was in his mouth.\" A priest is measured by what people actually learned from him.",
    '2:7': "People come to the priest's mouth for the law, which means a silent priest is not a neutral one.",
    '2:8': "\"Ye have caused many to stumble at the law.\" Bad teaching is charged with everyone who tripped over it.",
    '2:9': "Made contemptible before all the people. The contempt shown at the altar came back as their reputation.",
    '2:10': "One father, one God, and treachery between brothers. The case for faithfulness begins at creation.",
    '2:11': "Marriage to the daughter of a strange god is called an abomination, and Judah is named as doing it.",
    '2:12': "Master and scholar cut off together. Teacher and pupil are treated as jointly liable for what was taught.",
    '2:13': "Tears covering the altar, and God not regarding the offering. The weeping is genuine and beside the point.",
    '2:14': "\"The wife of thy youth\" — she is called his companion, and God is named as witness to the contract.",
    '2:15': "\"And did not he make one?\" The argument runs back to Eden, and what it turns on is the children.",
    '2:16': "\"He hateth putting away.\" Divorce is described here as covering violence over with a garment.",
    '2:17': "\"Where is the God of judgment?\" They weary God with words about how God never does anything.",
    # ---- Chapter 3 ----
    '3:1': "The messenger who prepares the way is the verse the gospels hand to John the Baptist.",
    '3:2': "The coming they had been demanding is described as a refiner's fire and harsh soap, not as relief.",
    '3:3': "He sits down to refine, which takes heat and time. The priests are the metal being worked.",
    '3:5': "The list runs from sorcery to unpaid wages. Shorting a hireling is filed beside adultery and witchcraft.",
    '3:6': "\"I am the LORD, I change not.\" That they are not consumed is credited to his constancy, not to theirs.",
    '3:7': "\"Wherein shall we return?\" Asked by people who cannot see they left. The question is itself the diagnosis.",
    '3:8': "\"Will a man rob God?\" The theft is specified: not devotion in general but tithes and offerings.",
    '3:10': "\"Prove me now herewith.\" God invites the test, and what he names is overflow rather than enough.",
    '3:11': "The blessing promised is a rebuke to the devourer — not a larger harvest but an end to the losses.",
    '3:12': "The end of it is a reputation among the nations, which is not the same as private comfort.",
    '3:13': "\"What have we spoken so much against thee?\" They cannot recall saying it, which is how sour talk works.",
    '3:14': "\"It is vain to serve God.\" The grievance is about profit, and religion had been held as an investment.",
    '3:15': "The proud do look happy and the wicked do look secure. The observation is accurate; the conclusion is not.",
    '3:16': "They spoke often one to another, and a book was written. Ordinary conversation is what gets recorded.",
    '3:17': "\"As a man spareth his own son that serveth him.\" The jewels being made up are people, and they are kept.",
    '3:18': "The difference between the righteous and the wicked is named as something seen later, not now.",
    # ---- Chapter 4 ----
    '4:1': "Stubble with neither root nor branch. The fire is described as leaving nothing to grow back from.",
    '4:2': "\"The Sun of righteousness... with healing in his wings.\" The day that burns is the day that rises.",
    '4:4': "\"Remember ye the law of Moses.\" With prophecy about to fall silent they are pointed to what they have.",
    '4:5': "Elijah is promised before the day. The Old Testament stops here, still waiting for a man to arrive.",
    '4:6': "The last word of the Old Testament is curse, and what is set against it is fathers and children reconciled.",
}
