#!/usr/bin/env python3
"""Written takeaways for Micah."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Micah of Moresheth, a country town, sees a word concerning Samaria and Jerusalem. The verdict on the capitals comes from outside them.",
    '1:2': "The earth and all that is in it are called as witnesses. The quarrel is domestic and the courtroom is the whole world.",
    '1:3': "God comes forth out of his place and treads upon the high places. The hilltop shrines are where his feet land first.",
    '1:4': "Mountains melting like wax and valleys cleft open. What is most solid gives way first when he arrives.",
    '1:5': "\"What is the transgression of Jacob? is it not Samaria?\" The sin is identified with the capital cities by name.",
    '1:6': "Samaria's stones poured into the valley until the foundations show. The city is not damaged but returned to the field it stood on.",
    '1:7': "The images were bought with a harlot's hire and the money goes back to it. Nothing passing through the shrine was sanctified.",
    '1:8': "\"I will wail and howl, I will go stripped and naked.\" The prophet does not deliver this ruin from a safe distance.",
    '1:9': "\"Her wound is incurable; for it is come unto Judah.\" Samaria's disease has already arrived at Jerusalem's gate.",
    '1:10': "\"Declare ye it not at Gath\" — David's old lament is borrowed, because now it is Judah's shame that must be kept from the Philistines.",
    '1:12': "Maroth waited carefully for good, and evil came down from the LORD. The hope was pointed the right way and was wrong.",
    '1:13': "Lachish binds the chariot to the swift beast. The fortress town that imported Israel's sin with its horses is told to run.",
    '1:15': "The glory of Israel shall come to Adullam — the cave David hid in. The nation's honour ends where its first king was a fugitive.",
    '1:16': "Baldness enlarged for the delicate children already gone. The mourning rite is prescribed for a loss not yet suffered.",

    # ---- Chapter 2 ----
    '2:1': "They lie awake devising it and do it at first light, \"because it is in the power of their hand.\" Opportunity is the only rule left.",
    '2:2': "Fields coveted, then taken by violence. The tenth commandment is shown turning into the eighth overnight.",
    '2:3': "\"Against this family do I devise an evil.\" God answers their scheming with the very verb they had been using.",
    '2:4': "Their own words come back as a taunt song: \"turning away he hath divided our fields.\" The dividers get divided.",
    '2:6': "\"Prophesy ye not, say they to them that prophesy.\" What is wanted is preaching that leaves nobody ashamed.",
    '2:7': "\"Do not my words do good to him that walketh uprightly?\" The word is only harsh from one particular place to stand.",
    '2:8': "Robes pulled off men passing by securely, averse from war. The victims are specified as the peaceable ones.",
    '2:9': "Women turned out of pleasant houses, the children's glory taken for ever. Eviction is charged as the theft of a future.",
    '2:10': "\"This is not your rest.\" The land of promise is disqualified as a resting place by what has been done inside it.",
    '2:11': "A man promising wine and strong drink would be exactly the prophet they want. The preference is stated with contempt.",
    '2:12': "The God who has just threatened now assembles and gathers. Judgement and shepherding are spoken in the same voice.",
    '2:13': "\"The breaker is come up before them.\" A way out is forced open from the front, with the LORD on the head of them.",

    # ---- Chapter 3 ----
    '3:1': "\"Is it not for you to know judgment?\" The rulers are charged with knowing better, and that is the whole accusation.",
    '3:2': "Hating the good and loving the evil — then skin pulled off bone. The abstraction becomes butchery inside one verse.",
    '3:3': "Chopped in pieces as for the pot. Micah describes the governing of the poor as cannibalism and does not soften it.",
    '3:4': "\"He will not hear them.\" The men who would not listen to a cry find out what being unheard is like.",
    '3:5': "They cry Peace to whoever feeds them and declare war on whoever does not. The message tracks the money exactly.",
    '3:6': "Night instead of vision, the sun going down over the prophets. The punishment for false speech is silence.",
    '3:7': "\"They shall all cover their lips; for there is no answer of God.\" The professionals are left with nothing to say.",
    '3:8': "\"But truly I am full of power by the spirit of the LORD\" — and what the power is for is telling Jacob his sin.",
    '3:10': "\"They build up Zion with blood.\" The building programme is not covering the crime; it is the crime.",
    '3:11': "Judges for reward, priests for hire, prophets for money — and every one of them sure the LORD is among them.",
    '3:12': "\"Zion shall be plowed as a field\" — the verse Jeremiah's defenders quote a century later to save his life.",

    # ---- Chapter 4 ----
    '4:1': "The mountain of the LORD's house established above the hills. The same words stand in Isaiah, and neither prophet claims them.",
    '4:2': "\"He will teach us of his ways.\" The nations come for instruction, and they come without having been conquered.",
    '4:3': "Swords into plowshares. The disarming follows the judging; the peace holds because a judge is sitting, not because men tired of war.",
    '4:4': "Every man under his vine and fig tree with none to frighten him. Peace is pictured as a smallholding, not an empire.",
    '4:5': "\"We will walk in the name of the LORD our God for ever.\" The vision is future and the walking is decided now.",
    '4:7': "The halting and the cast-off are made the remnant and a strong nation. God builds the future out of the damaged part.",
    '4:8': "\"O tower of the flock\" — a shepherd's watchtower is told that the first dominion is coming back to it.",
    '4:9': "\"Is there no king in thee? is thy counsellor perished?\" The crying is real, and the question names what they were trusting.",
    '4:10': "Babylon is named, and named as the place of rescue. Deliverance lies on the far side of the exile, not instead of it.",
    '4:11': "The nations gather to see Zion defiled. The appetite described is for the spectacle as much as for the plunder.",
    '4:12': "\"They know not the thoughts of the LORD.\" The besiegers are being gathered like sheaves while they think they are besieging.",
    '4:13': "Their gain is consecrated to the Lord of the whole earth. Even the spoils of victory are not the victor's to keep.",

    # ---- Chapter 5 ----
    '5:1': "The judge of Israel smitten on the cheek with a rod. The chapter that promises a ruler opens with one being humiliated.",
    '5:2': "Bethlehem Ephratah, little among the thousands, and the ruler's goings forth from everlasting. Herod's scribes read him this verse.",
    '5:3': "\"Until the time that she which travaileth hath brought forth.\" The giving up has a stated end, and the end is a birth.",
    '5:4': "He shall stand and feed in the strength of the LORD. The promised ruler is described doing a shepherd's work, not a king's.",
    '5:5': "\"And this man shall be the peace.\" Peace is not what he arranges or delivers; it is what he is.",
    '5:6': "Seven shepherds and eight principal men raised against Assyria. Ordinary men are the means, and it is still his deliverance.",
    '5:7': "Dew and showers that tarry not for man. The remnant's usefulness among the nations does not wait on being wanted.",
    '5:8': "And a lion among the flocks. The same remnant is dew to one people and terror to another, in consecutive verses.",
    '5:9': "The hand lifted up upon the adversaries — and the verses that follow disarm Israel's own hand first.",
    '5:10': "Horses and chariots cut off. The nation's military strength is removed as a part of the blessing, not as a loss.",
    '5:12': "Witchcrafts and soothsayers cut off. What they consulted goes the same way as what they fought with.",
    '5:13': "\"Thou shalt no more worship the work of thine hands.\" The images go, and the hands that made them stop making.",
    '5:15': "Vengeance upon the heathen such as they have not heard. The chapter that promised the shepherd closes in fury.",

    # ---- Chapter 6 ----
    '6:2': "\"The LORD hath a controversy with his people.\" The mountains sit as jury in a case God brings against his own.",
    '6:3': "\"O my people, what have I done unto thee? testify against me.\" The plaintiff opens by inviting charges against himself.",
    '6:4': "Egypt, redemption, and Moses, Aaron and Miriam. The only evidence entered for the prosecution is his own kindness.",
    '6:5': "Balak and Balaam recalled as \"the righteousness of the LORD\" — a rescue Israel never knew was taking place.",
    '6:6': "\"Wherewith shall I come before the LORD?\" The answer assumes the difficulty is finding a large enough payment.",
    '6:7': "Thousands of rams, rivers of oil, then the firstborn. The bidding climbs until it reaches the one thing never asked for.",
    '6:8': "\"He hath shewed thee, O man, what is good.\" The famous answer is not a lower price but the end of pricing altogether.",
    '6:9': "\"Hear ye the rod, and who hath appointed it.\" The discipline is to be listened to, which means asking whose hand holds it.",
    '6:10': "The scant measure in the house of the wicked. Doing justly is tested at the point of sale, never in the abstract.",
    '6:12': "Rich men full of violence and tongues that are deceitful. Wealth and lying are reported as one condition, not two.",
    '6:13': "\"I will make thee sick in smiting thee.\" The judgement is described as an illness rather than a blow that ends.",
    '6:14': "Eating and not being satisfied. The curse is not scarcity but the failure of enough to feel like enough.",
    '6:15': "Sowing without reaping, treading olives without oil. Every step of the labour is left intact and only the result removed.",
    '6:16': "\"For the statutes of Omri are kept.\" Judah is convicted of keeping the northern kingdom's law in place of the LORD's.",

    # ---- Chapter 7 ----
    '7:1': "Gleaning after the vintage and finding no cluster. He is hungry for one good man and the field has been stripped.",
    '7:2': "\"They hunt every man his brother with a net.\" This is not lawlessness but a society organised to hunt inside itself.",
    '7:3': "Prince and judge ask, the great man names his desire, \"so they wrap it up.\" The corruption is done openly and tidily.",
    '7:4': "The best of them is as a brier. Even the top of the range is something that tears the hand reaching for it.",
    '7:5': "Trust not a friend, nor a guide, nor her that lieth in thy bosom. The collapse is measured by how near it reaches.",
    '7:6': "\"A man's enemies are the men of his own house\" — the line Jesus takes up for what following him will cost a family.",
    '7:7': "\"Therefore I will look unto the LORD.\" Therefore: the reason for waiting is that nothing else is left standing.",
    '7:8': "\"When I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.\" The confidence is spoken from the floor.",
    '7:9': "\"I will bear the indignation of the LORD, because I have sinned.\" He accepts the sentence and still expects his cause to be pleaded.",
    '7:10': "\"Where is the LORD thy God?\" The enemy's taunt is the question the whole deliverance is finally addressed to.",
    '7:13': "The land is desolate for the fruit of their doings. Even inside the promise the cause of the ruin is said again.",
    '7:14': "\"Feed thy people with thy rod.\" The rod that struck in the last chapter is now asked for as a shepherd's staff.",
    '7:15': "\"According to the days of thy coming out of the land of Egypt.\" The exodus sets the measure of what may still be expected.",
    '7:16': "The nations lay their hand upon their mouth. The talkers go quiet at last, and not because they were out-argued.",
    '7:18': "\"Who is a God like unto thee?\" The prophet's own name is that question, and pardon is what makes it unanswerable.",
    '7:19': "\"He will subdue our iniquities\" — not only forgiven but put down. Sin is treated as an enemy as well as a debt.",
    '7:20': "The truth performed to Jacob and the mercy to Abraham, sworn from the days of old. The last word is older than the sin.",
}
