#!/usr/bin/env python3
"""Written one-line takeaways for Nahum 1-3."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "A burden against the city Jonah was sent to a century earlier. The repentance there did not hold.",
    '1:2': "Vengeance is said three times in one verse. The word belongs to God and is never handed down to us.",
    '1:3': "Slow to anger is not the same as unwilling. The patience is real, and so is the end of it.",
    '1:4': "Bashan, Carmel, Lebanon — the three greenest names in the region are the first to go grey.",
    '1:6': "\"Who can stand before his indignation?\" The question is put to a city that assumed it could.",
    '1:7': "\"A strong hold in the day of trouble.\" One day, and it is fire to one man and shelter to another.",
    '1:8': "Darkness is given a verb here: it pursues. The enemy is not left in the dark but chased by it.",
    '1:9': "\"Affliction shall not rise up the second time.\" What is promised is not repeated blows but one that finishes.",
    '1:11': "The empire is indicted through one man who came out of it. Nations are charged by way of their counsellors.",
    '1:12': "The address turns mid-verse. To Judah the word is that the affliction has an end, and this is it.",
    '1:13': "Deliverance is described as somebody else's yoke being snapped, with Judah doing none of the snapping.",
    '1:14': "\"I will make thy grave; for thou art vile.\" The grave is dug by the one who was offended.",
    '1:15': "Beautiful feet on the mountains — here it is a siege lifted, and Paul later takes the line up for the gospel.",
    # ---- Chapter 2 ----
    '2:1': "Orders barked at a city already lost. Fortifying is set down as something to do while falling.",
    '2:2': "Nineveh's fall is filed under Jacob's restoration. Judgement on one nation is mercy read from the other side.",
    '2:3': "Red shields, scarlet men, torchlit chariots. The attack is described as a colour before it is a count.",
    '2:5': "He calls the roll of his best men, and they stumble on the way to the wall they are defending.",
    '2:6': "\"The gates of the rivers shall be opened.\" The city's own water is what dissolves its palace.",
    '2:7': "The mourning is given a sound: doves, and the beating of hands on the breast.",
    '2:8': "Nineveh was a pool that gathered the nations. Now it drains, and nobody turns back at the shout to stand.",
    '2:9': "The looters are invited in by the prophecy itself. What was gathered by plunder leaves the same way.",
    '2:10': "Three words for empty, then the body: melted heart, knocking knees, faces gone black.",
    '2:11': "Assyria carved lions on her palace walls. The oracle stands in the ruins and asks where the den went.",
    '2:13': "\"Behold, I am against thee\" — the book in four words. The messengers who carried the threats fall silent.",
    # ---- Chapter 3 ----
    '3:1': "The charge sheet is short: blood, lies, robbery, and prey that never stops arriving.",
    '3:2': "Nothing in this verse but noise. The attack is heard some time before anything can be seen.",
    '3:3': "The corpses are counted until counting gives out, and then the living stumble over them.",
    '3:4': "The charge is seduction as much as force. She sold nations, and there were buyers who came willingly.",
    '3:5': "The sentence is public stripping. An empire that exposed others is exposed before the same audience.",
    '3:7': "Nobody volunteers to mourn her. A power with no friends finds that out at its own funeral.",
    '3:8': "No fell, and Assyria is the one who felled it. The precedent held up to her is her own handiwork.",
    '3:9': "Her allies were reckoned infinite and she fell anyway. Numbers were never what was holding her up.",
    '3:10': "Children dashed in the streets, lots cast for the great men. Assyria is being shown her own methods.",
    '3:11': "\"Thou also shalt be drunken.\" The whole argument of the chapter rests on those two opening words.",
    '3:12': "Strongholds that drop into the eater's mouth at one shake. The defences are described as ripe.",
    '3:13': "An old taunt about soldiers, and underneath it a plain fact: the gates stand open and the bars burn.",
    '3:14': "Orders to tread mortar for walls that will not hold. The preparations are described as busywork.",
    '3:16': "Merchants past counting, and the picture chosen for them is the locust that strips a field and moves on.",
    '3:17': "Officials who camp in the hedge while it is cold and vanish when the sun comes up. Nobody knows where.",
    '3:18': "The king is addressed at last, and what he is told is that his people are scattered and no one is gathering.",
    '3:19': "The book ends in applause at a funeral, and the reason given is everyone the city had hurt.",
}
