#!/usr/bin/env python3
"""Written one-line takeaways for Nehemiah 1-13."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens as one man's own memoir, and he writes it from the palace at Shushan, not from Judah.",
    '1:2': "He asked after the remnant and after Jerusalem. The bad news reached him because he went looking for it.",
    '1:3': "Affliction and reproach come before the broken wall. The shame of it is the first item in the report.",
    '1:4': "He sat down and wept and mourned certain days before doing anything else. The rebuilding starts on the floor.",
    '1:5': "\"The great and terrible God, that keepeth covenant and mercy\" — both held in one breath, neither cancelling the other.",
    '1:6': "\"Both I and my father's house have sinned.\" The cupbearer in Shushan puts himself inside the guilt.",
    '1:7': "The sin is spelled out as commandments, statutes and judgments broken — the law named, not a vague regret.",
    '1:8': "He prays the threat back to God. The word about scattering is quoted as the ground for hope.",
    '1:9': "The gathering reaches to the uttermost part of heaven, and the only condition attached to it is turning.",
    '1:10': "His argument is what God has already spent: \"whom thou hast redeemed by thy great power.\"",
    '1:11': "\"For I was the king's cupbearer.\" The man he asks mercy from is the man he pours wine for.",
    # ---- Chapter 2 ----
    '2:1': "Four months between the prayer and the opening, and he had never let the king see him sad before.",
    '2:2': "\"Then I was very sore afraid.\" A downcast face in front of a Persian king was not a small risk.",
    '2:3': "He never says Jerusalem. He says the place of his fathers' sepulchres, which a king can be expected to respect.",
    '2:4': "Between the king's question and the answer to it there is a prayer nobody in the room heard.",
    '2:5': "The request, when it finally comes, is plain: send me to the city of my fathers, that I may build it.",
    '2:6': "Asked how long, he names a date. The project was costed before anyone invited him to propose it.",
    '2:7': "Faith that has thought about checkpoints. He asks for letters to the governors he will have to pass.",
    '2:8': "\"According to the good hand of my God upon me.\" A Persian grant of timber is credited elsewhere.",
    '2:9': "He had asked for letters. The king also sent captains and horsemen, which he never requested.",
    '2:10': "The opposition begins before a stone is laid, and its grievance is that someone sought Israel's welfare.",
    '2:11': "Three days in the city and still nothing said. He looks before he speaks.",
    '2:12': "\"Neither told I any man what my God had put in my heart to do.\" The plan stays private while he tests it.",
    '2:13': "He rides out past the dung port in the dark to see the worst of the ruin with his own eyes.",
    '2:14': "The rubble was too deep for the animal to pass. Part of the survey had to be made on foot.",
    '2:15': "He re-enters by the gate he left by. The whole inspection is arranged so that nobody notices it.",
    '2:16': "\"The rulers knew not whither I went.\" He earns the right to ask before he asks for anything.",
    '2:17': "He says \"we\" and \"us.\" The distress is his own before he proposes doing anything about it.",
    '2:18': "He reports God's good hand first and the king's permission second, and the order is not accidental.",
    '2:19': "The mockery arrives dressed as loyalty — \"will ye rebel against the king?\" — the one charge he has letters against.",
    '2:20': "He answers that God will prosper them, then tells the mockers they have no portion in the city at all.",
    # ---- Chapter 3 ----
    '3:1': "The high priest begins the work and sanctifies the gate. Masonry is handled here as holy business.",
    '3:5': "\"Their nobles put not their necks to the work of their LORD.\" The men who would not help are on the list too.",
    '3:8': "A goldsmith and an apothecary's son laying stone. The trades are wrong for the job and the names stay anyway.",
    '3:10': "Repairing the stretch over against his own house. Duty and self-interest run along the same wall.",
    '3:12': "A ruler of half Jerusalem, \"he and his daughters.\" The only builders in the chapter named as women.",
    '3:20': "Baruch the son of Zabbai \"earnestly repaired.\" One man in the whole roster is given an adverb.",
    '3:28': "The priests work above the horse gate, every one over against his house. The nearest stretch is the one they take.",
    '3:32': "The list closes where it opened, at the sheep gate. On paper the circuit of the wall is now unbroken.",
}

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:1': "Mockery is the first weapon reached for, and it arrives the moment the building becomes visible.",
    '4:2': "\"What do these feeble Jews?\" Four sneering questions, the last of them about reviving burnt stones.",
    '4:3': "Tobiah's joke is about the workmanship: a fox walking on it would bring the whole wall down.",
    '4:4': "The prayer asks God to turn the reproach back on the mockers. He prays what he is actually feeling.",
    '4:5': "\"Cover not their iniquity.\" He asks God not to forgive them, and the book leaves the request standing.",
    '4:6': "\"For the people had a mind to work.\" Half a wall is explained by willingness rather than by skill.",
    '4:7': "Progress is what escalates the threat. Mockery turns to conspiracy once the breaches begin to close.",
    '4:9': "\"We made our prayer unto our God, and set a watch.\" Prayer and sentries in the same sentence.",
    '4:10': "The discouragement comes from inside at the halfway mark, and it sounds entirely reasonable: too much rubbish.",
    '4:12': "The neighbours said it ten times. Fear repeated often enough by friends does the enemy's work for him.",
    '4:13': "He stations the people by families, so that a man guards the stretch where his own children stand.",
    '4:14': "\"Remember the LORD... and fight for your brethren.\" The remembering is not offered instead of the fighting.",
    '4:15': "God brought their counsel to nought, and the result was that every man went back to his own piece of wall.",
    '4:16': "From that day half the workforce is lost to guard duty. The wall now costs twice as much to finish.",
    '4:17': "One hand in the work and the other holding a weapon. Neither hand can be spared for the other.",
    '4:18': "The trumpeter stayed next to the governor, so that the signal could be given the moment it was needed.",
    '4:19': "\"The work is great and large, and we are separated.\" The danger of a long wall is the distance between friends.",
    '4:20': "\"Our God shall fight for us\" is said to men who have just been told where to run with their swords.",
    '4:21': "From the rising of the morning till the stars appeared. These are siege conditions, and self-imposed.",
    '4:23': "Nobody undressed except to wash. The memoir keeps the small indignity rather than the heroism.",
    # ---- Chapter 5 ----
    '5:1': "The great cry is not against Persia or against Sanballat. It is against their brethren the Jews.",
    '5:2': "Large families named as the reason for hunger. The complaint begins as arithmetic before it is injustice.",
    '5:3': "Lands, vineyards and houses mortgaged to buy corn. The dearth turned property into debt.",
    '5:4': "The tribute owed to a foreign king has to be borrowed, and the security is the family's land.",
    '5:5': "\"Our flesh is as the flesh of our brethren.\" Daughters already sold, and no power left to redeem them.",
    '5:6': "\"And I was very angry when I heard their cry.\" The anger is reported without any apology for it.",
    '5:7': "\"Then I consulted with myself.\" He thought it through privately and then said it in a great assembly.",
    '5:8': "\"Will ye even sell your brethren?\" They held their peace, and found nothing at all to answer.",
    '5:9': "The reason given for fearing God is that the heathen are watching how this people treats its own.",
    '5:10': "He names his own lending first, before asking anybody else to give theirs up.",
    '5:11': "\"Restore, I pray you, to them, even this day.\" Repentance here comes with a date attached.",
    '5:12': "The promise is put under oath before the priests. Goodwill was not trusted to last the week.",
    '5:13': "He shakes out his lap as a picture of the curse, and the whole congregation says Amen to it.",
    '5:14': "Twelve years as governor, and in all of them he never drew the governor's food allowance.",
    '5:15': "The former governors were chargeable to the people. \"But so did not I, because of the fear of God.\"",
    '5:16': "He bought no land during a crisis about land. The man settling the debts refused to profit by them.",
    '5:18': "An ox and six sheep a day at his own charge, \"because the bondage was heavy upon this people.\"",
    '5:19': "\"Think upon me, my God, for good.\" He sends the bill to God rather than to the people.",
    # ---- Chapter 6 ----
    '6:1': "\"There was no breach left therein\" — followed by a parenthesis admitting the doors were not yet hung.",
    '6:2': "An invitation to meet on neutral ground, and the narrator states the intention behind it outright.",
    '6:3': "\"I am doing a great work, so that I cannot come down.\" The refusal names no suspicion, only the work.",
    '6:4': "Four invitations and one answer, repeated word for word. He never improves on it or explains himself.",
    '6:5': "The fifth letter comes open in the servant's hand, so that everyone along the road can read it.",
    '6:6': "\"Gashmu saith it.\" A rumour is handed a name to carry, which is how it passes for established fact.",
    '6:8': "\"Thou feignest them out of thine own heart.\" A flat denial, with nothing conceded for the sake of quiet.",
    '6:9': "\"Now therefore, O God, strengthen my hands.\" The intimidation worked well enough to need praying about.",
    '6:10': "The advice to hide arrives from a prophet, inside the temple, and sounds like concern for his life.",
    '6:11': "\"Should such a man as I flee?\" He will not buy safety at the price of the place he holds.",
    '6:12': "He perceived that God had not sent him. The prophecy was tested by asking who was paying for it.",
    '6:13': "The plot's aim was not his death but his sin, and a story they could tell about him afterward.",
    '6:14': "Noadiah the prophetess is named among the hired voices, and named without any further comment.",
    '6:15': "Fifty and two days for the whole wall, and the number is dropped in almost as an aside.",
    '6:16': "The enemies were cast down in their own eyes, because they could see whose work it had been.",
    '6:17': "While the letters were flying at him, the nobles of Judah were exchanging their own with Tobiah.",
    '6:18': "The leak is explained by marriages. Tobiah was family to half the men Nehemiah had to work with.",
    '6:19': "They carried Tobiah's good deeds in and Nehemiah's words out. No wall defends against that.",
    # ---- Chapter 7 ----
    '7:1': "The doors are hung and the singers appointed in the same sentence. A gate needs both to make a city.",
    '7:2': "The qualification given for charge over Jerusalem is that he feared God above many.",
    '7:3': "The gates stay shut until the sun is hot, and each man watches the stretch in front of his own house.",
    '7:4': "A great wall around an empty city. The people were few and the houses were not built.",
    '7:5': "God put it in his heart to count people, and what he found was a register somebody else had kept.",
    '7:6': "A list of people who came back, defined by the name of the king who carried them away.",
    '7:7': "Twelve leaders head the list, and one of them is a different Nehemiah altogether.",
    '7:43': "Over four thousand priests in this list and seventy-four Levites. The unglamorous order mostly stayed away.",
    '7:46': "The Nethinims are counted household by household, temple servants written into the family record.",
    '7:61': "\"They could not shew their father's house.\" Some came home unable to prove that they belonged.",
    '7:63': "A priestly family took the name of the wife's house, and lost its own place in the register by it.",
    '7:64': "The register was searched, their names were not in it, and they were put from the priesthood as polluted.",
    '7:65': "Not a verdict but a suspension: no holy things until a priest with Urim and Thummim should stand up.",
    '7:66': "Forty-two thousand three hundred and threescore. The whole restored nation is the size of a town.",
    '7:67': "Seven thousand servants counted after the citizens, and two hundred and forty-five singers with them.",
    '7:70': "The giving is itemised down to fifty basons. Generosity is recorded as carefully as the census is.",
    '7:71': "The chief of the fathers gave by weight, and the weight is written where anyone could check it.",
    '7:72': "The rest of the people nearly matched the nobles' gold, out of very much less than the nobles had.",
    '7:73': "Everyone settled in his own city, and the seventh month came. The chapter ends by setting a date.",
})

TAKEAWAYS.update({
    # ---- Chapter 8 ----
    '8:1': "Nobody ordered the reading. The people gathered as one man and asked for the book themselves.",
    '8:2': "Men and women and all that could hear with understanding. The audience is defined by comprehension, not rank.",
    '8:3': "From the morning until midday, and the ears of all the people were attentive. Nobody walked away.",
    '8:4': "A pulpit of wood made for the purpose, and thirteen men standing with him. The reading was organised.",
    '8:5': "When the book was opened the people stood up. The standing is for the book, not for the man holding it.",
    '8:6': "Amen twice, hands lifted, then faces to the ground. The response is bodily before it is anything else.",
    '8:7': "Thirteen Levites named as the men who made the law understood. Teaching was distributed, not reserved.",
    '8:8': "\"Read distinctly, and gave the sense.\" Two verbs, and between them the whole business of preaching.",
    '8:9': "The law's first effect was weeping, and the leaders' first word was that this day is not for it.",
    '8:10': "\"The joy of the LORD is your strength\" — said next to \"send portions unto them for whom nothing is prepared.\"",
    '8:12': "The great mirth came \"because they had understood.\" Joy here runs downstream of comprehension.",
    '8:13': "The leaders came back the next day to study further. The feast did not put an end to the reading.",
    '8:14': "They found in the book a feast they had not been keeping. Reading the law turns up omissions.",
    '8:16': "Booths on the roofs, in the courts, in the streets. Obedience made the whole city look temporary.",
    '8:17': "Not done so since the days of Jeshua the son of Nun. Centuries of neglect stated without any excuse.",
    '8:18': "He read every day of the seven. The feast was kept by listening as much as by camping out.",
    # ---- Chapter 9 ----
    '9:1': "Sackcloth and earth two days after the great mirth. Joy and grief are not rival stages here.",
    '9:2': "They confessed their own sins and the iniquities of their fathers, and kept the two accounts together.",
    '9:3': "A fourth part of the day reading and a fourth part confessing. The repentance is measured out in hours.",
    '9:5': "\"Exalted above all blessing and praise.\" The praise admits at the outset that it falls short.",
    '9:6': "The confession starts at creation. Before a word is said about sin, God is named as the only one.",
    '9:7': "The history begins with a choosing and a call out of Ur, which nobody in Ur had asked for.",
    '9:8': "\"For thou art righteous\" — and the evidence offered for it is a promise about land that was kept.",
    '9:9': "God is credited with seeing the affliction and hearing the cry. That is where the exodus begins.",
    '9:10': "\"So didst thou get thee a name, as it is this day.\" The rescue was about God's reputation too.",
    '9:11': "Their persecutors went down \"as a stone into the mighty waters.\" One sea saved and drowned.",
    '9:13': "The law is called right, true and good by people who are about to confess they broke all of it.",
    '9:14': "Of all the commandments the sabbath is singled out as made known — a gift before it is a duty.",
    '9:15': "Bread from heaven, water from a rock, and a sworn land. He fed them on the way to what he promised.",
    '9:16': "\"But they and our fathers dealt proudly.\" The prayer turns, and the word our keeps them inside it.",
    '9:17': "They appointed a captain to go back to slavery, and the same sentence calls God ready to pardon.",
    '9:18': "The calf is named outright, with the words they said over it. Nothing is rounded off in this confession.",
    '9:19': "\"Yet thou in thy manifold mercies forsookest them not.\" The pillars kept going after the calf.",
    '9:20': "Instruction by God's good spirit is listed beside manna and water, as one more thing provided.",
    '9:21': "Forty years, and their clothes did not wear out. The wasted years are remembered as sustained ones.",
    '9:24': "The children went in where their fathers would not. The promise outlived the men who refused it.",
    '9:25': "They ate and were filled and became fat. The hazard in the story turns out to be the good land.",
    '9:26': "\"Cast thy law behind their backs\" — and the prophets sent to turn them back were the men they killed.",
    '9:27': "When they cried in their trouble they were heard, and the deliverers God sent are called saviours.",
    '9:28': "Rest, evil, oppression, crying, rescue. The prayer admits how many times the loop went round.",
    '9:29': "\"Which if a man do, he shall live in them.\" The law's own promise is quoted, and it accuses them.",
    '9:30': "Many years of forbearance, and the instrument of it was prophets nobody would give ear to.",
    '9:31': "\"Thou didst not utterly consume them.\" Mere survival is entered as evidence of mercy.",
    '9:32': "The one petition in the whole prayer is modest: let not all this trouble seem little before thee.",
    '9:33': "\"Thou hast done right, but we have done wickedly.\" The long history was assembled to reach that line.",
    '9:34': "Kings, princes, priests and fathers, all named as failing. No rank among them is left out of the charge.",
    '9:35': "They did not serve God in the fat land he gave them. Prosperity was the setting of the sin, not its cure.",
    '9:36': "\"Behold, we are servants this day\" — in the land given to their fathers, under another king's tax.",
    '9:37': "The increase goes to foreign kings, who have dominion over their bodies and their cattle at pleasure.",
    '9:38': "The answer to a prayer of unbroken failure is a written covenant, with seals put to it.",
})
