#!/usr/bin/env python3
"""Written one-line takeaways for Numbers 1-36."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens in a wilderness and never really leaves it. Sinai is behind them; the land is not yet ahead.",
    '1:2': "\"The number of their names.\" Even a head count is ordered to be taken name by name rather than in bulk.",
    '1:3': "From twenty years old and able to go to war. This is a muster roll, and almost none of these men will fight for the land.",
    '1:4': "A head from every tribe stands with Moses. The count is not one man's private arithmetic.",
    '1:16': "The princes are called renowned, and within a generation most of this list has died in the sand.",
    '1:18': "\"They declared their pedigrees.\" Belonging to Israel was something a man had to be able to show.",
    '1:27': "Judah comes out the largest tribe, and Jacob's blessing over the sceptre is quietly working itself out in a ledger.",
    '1:46': "Six hundred thousand and three thousand five hundred and fifty fighting men. Remember the figure; chapter 26 counts them again.",
    '1:47': "The Levites are left off the war roll. A tribe is exempted from the army because its work is at the tent.",
    '1:50': "Their charge is to carry, pitch and take down. The tribe nearest God is the one that does the lifting.",
    '1:51': "\"The stranger that cometh nigh shall be put to death.\" Nearness to God is treated as genuinely dangerous.",
    '1:53': "The Levites camp as a cordon \"that there be no wrath.\" The reason for the arrangement is stated outright.",
    '1:54': "\"So did they.\" The last flat note of obedience before the murmuring starts.",
    # ---- Chapter 2 ----
    '2:2': "Every man by his own standard and all of them facing one tent. Order and distance are arranged in the same sentence.",
    '2:3': "Judah pitches east, where the sun comes up, and Nahshon leads. Matthew's genealogy will pick up this name.",
    '2:9': "\"These shall first set forth.\" The marching order puts the tribe of the promise at the front of the column.",
    '2:14': "Gad's prince is Eliasaph son of Reuel here and son of Deuel in chapter one. The record keeps both spellings.",
    '2:17': "The tabernacle travels in the middle of the column. God is not out front as a mascot but housed among them.",
    '2:31': "Dan brings up the rear with the second largest host. The back of the march is guarded, not left to stragglers.",
    '2:32': "The same total is reached from the camps as from the tribes. The book is willing to show its working twice.",
    '2:33': "Levi is left out of the sum a second time. The tribe that serves the tent is counted on a different page.",
    '2:34': "They pitched and they set forward exactly as commanded. This is the last chapter where that is simply true.",
}

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "\"The generations of Aaron and Moses\" — and then only Aaron's sons are listed. The priestly line is the one being traced.",
    '3:2': "Nadab and Abihu head the list of Aaron's sons, named in their birth order before they are named among the dead.",
    '3:4': "Strange fire, no children, and the line passes to Eleazar. The priesthood's first casualties were the high priest's own sons.",
    '3:6': "Levi is brought near to serve Aaron. Even inside the tribe set apart, there are degrees of nearness.",
    '3:9': "The Levites are \"wholly given\" — Israel's gift to the priesthood before they are anything to themselves.",
    '3:12': "One tribe is taken in place of every firstborn son. Substitution is built into the shape of the camp.",
    '3:13': "God's claim on the firstborn dates from the night he spared them in Egypt. Redemption is what creates the ownership.",
    '3:15': "Levites are counted from a month old. Fighting men were counted from twenty; these belong to God before they can work.",
    '3:31': "Kohath carries the ark, the table, the lampstand and the altars. The honour and the danger are the same appointment.",
    '3:32': "Eleazar is made chief over the chiefs, and the man who will bury Aaron is already being placed.",
    '3:38': "Moses and Aaron camp at the door on the east side. The leaders are posted where the traffic is.",
    '3:39': "Twenty-two thousand Levites, against sixty thousand in Dan alone. The tribe that carries the tent is among the smallest.",
    '3:43': "Twenty-two thousand two hundred and seventy-three firstborn — two hundred and seventy-three more than there are Levites.",
    '3:47': "The surplus firstborn are redeemed at five shekels a head. Where the substitute runs out, a price is named instead.",
    # ---- Chapter 4 ----
    '4:3': "Thirty to fifty years old. The heavy service has a starting age and an end, and nobody is worked past it.",
    '4:5': "Aaron veils the ark before the carriers arrive. What they lift, they never see.",
    '4:6': "The ark alone is finished with blue on the outside. Under the badger skins, one object is marked differently.",
    '4:15': "\"They shall not touch any holy thing, lest they die.\" The privilege of carrying God's things is issued with a warning.",
    '4:16': "Eleazar's charge is oil, incense and oversight — the things that keep burning while everyone else is packing.",
    '4:19': "\"That they may live, and not die.\" The regulations are given as protection, not as obstacles to devotion.",
    '4:20': "Even a glance at the uncovered holy things is fatal. Curiosity is not treated as a small fault here.",
    '4:24': "Gershon's work is named plainly as burdens. Scripture does not pretend that service to God is weightless.",
    '4:32': "Pins and cords are reckoned by name to particular men. Nothing is so small that nobody is answerable for it.",
    '4:36': "Two thousand seven hundred and fifty Kohathites of working age out of eight thousand six hundred counted.",
    '4:49': "\"Every one according to his service, and according to his burden.\" The load is assigned man by man, not dumped on the tribe.",
})

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:2': "Leprosy, a discharge, a touched corpse. None of the three is a sin, and all three still put a man outside.",
    '5:3': "\"In the midst whereof I dwell.\" The camp's rules are strict for one reason, and it is a guest.",
    '5:4': "They put them out. The people who carried out the order were removing their own relatives.",
    '5:6': "Wronging a neighbour is charged here as \"a trespass against the LORD.\" There is no purely horizontal sin.",
    '5:7': "Confession and the principal and a fifth on top. Being forgiven is not treated as cancelling what is owed.",
    '5:8': "If the wronged man is dead with no kinsman, the debt is paid to God. It does not quietly lapse.",
    '5:10': "What a man gives the priest is the priest's. Ministers are kept by gifts rather than by charging for the holy.",
    '5:12': "The law of jealousy begins where the husband cannot know and will not stop suspecting.",
    '5:13': "\"Neither she be taken with the manner.\" The statute exists precisely where the evidence has run out.",
    '5:14': "The spirit of jealousy is described twice — once where she is guilty, once where she is not. Both cases get the same ordeal.",
    '5:15': "Barley meal, no oil, no frankincense. Everything pleasant is stripped off an offering that exists to expose.",
    '5:17': "Holy water, and dust off the tabernacle floor. The ordeal's ingredients are deliberately worth nothing.",
    '5:18': "She stands before the LORD with the offering in her hands and the priest holding the water. The case is out of her husband's hands.",
    '5:19': "The oath opens with \"be thou free\" — the priest states the innocent outcome first.",
    '5:21': "The curse is read out in full before she drinks. Nobody is condemned by terms they were not told.",
    '5:22': "\"Amen, amen.\" She is made to consent aloud to the verdict either way.",
    '5:23': "The written curses are blotted into the water she drinks. The words become the thing that enters her.",
    '5:27': "No judge rules and no witness testifies. The whole case is handed to God to decide or to drop.",
    '5:28': "The innocent woman goes home cleared and fruitful. The ordeal is built to acquit as readily as to convict.",
    '5:31': "\"The man shall be guiltless.\" The law's lopsidedness is stated flatly, and the text does not soften it.",
    # ---- Chapter 6 ----
    '6:2': "Man or woman, by their own vow. The nearest thing to priesthood open to an ordinary Israelite is voluntary.",
    '6:3': "Not only wine but vinegar, juice and raisins. The vow refuses the vine entirely rather than negotiating with it.",
    '6:4': "\"From the kernels even to the husk.\" Separation is defined so precisely that no one can argue the edges.",
    '6:5': "Uncut hair makes the vow public. A private devotion is given a form that everybody can see.",
    '6:6': "The Nazarite may go near no corpse. A layman's vow puts him under the high priest's own restriction.",
    '6:7': "He may not bury his own mother, \"because the consecration of his God is upon his head.\" The vow outranks the grave.",
    '6:9': "A man drops dead beside him and the vow is defiled. Some ruin arrives without anyone choosing it.",
    '6:11': "\"For that he sinned by the dead.\" Atonement is required even where no intention can be found.",
    '6:12': "The days already kept are lost and counted again from nothing. Past devotion buys no credit against a later failure.",
    '6:13': "The vow ends on a fixed day. Even Israel's most intense consecration was designed to be temporary.",
    '6:14': "A sin offering closes the perfect vow. A completed consecration still needs blood to end it.",
    '6:18': "The hair grown for God is cut off and burned under the peace offering. The proof of the vow goes into the fire.",
    '6:20': "\"After that the Nazarite may drink wine.\" The abstaining was a sign for a season, never a higher grade of holiness.",
    '6:21': "\"Beside that that his hand shall get.\" Above the required minimum, a man may give whatever he can.",
    '6:23': "The blessing is dictated. Aaron's sons hand over words they did not compose and cannot improve.",
    '6:24': "Bless and keep. God gives the good and then guards it, since gifts in this world do not hold themselves.",
    '6:25': "A shining face is the opposite of a turned back, and what it shines with is named: grace.",
    '6:26': "The countenance is lifted toward the people and the last word of the blessing is peace, handed over rather than achieved.",
    '6:27': "\"They shall put my name upon them, and I will bless them.\" The priest speaks; the blessing stays God's own act.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:1': "The chapter reaches back to the day the tabernacle went up. The narrative stops moving forward to record a gift.",
    '7:2': "The men who supervised the census are the first to give. Leadership here begins by opening its own hand.",
    '7:3': "Wagons and oxen. The gift for a travelling sanctuary is transport, not ornament.",
    '7:5': "\"To every man according to his service.\" What is given away is distributed by need, not split evenly.",
    '7:7': "Gershon carried curtains, so Gershon got two wagons. The lighter load draws the smaller allowance.",
    '7:8': "Merari hauled boards and sockets and received twice as many wagons. The heaviest work got the most help.",
    '7:9': "Kohath received no wagons at all, because the holiest things were carried on men's shoulders.",
    '7:10': "The altar is dedicated by gifts brought to it. Israel's first use of the altar is to give.",
    '7:11': "\"Each prince on his day.\" Twelve identical gifts are spread over twelve days so no tribe shares its moment.",
    '7:12': "Judah offers first, as Judah camps first and marches first. The order set in chapter two simply holds.",
    '7:13': "A hundred and thirty shekels of silver in one dish. The princes gave at a weight the text bothers to record.",
    '7:14': "A gold spoon of incense — ten shekels of metal holding something that will be burned away.",
    '7:16': "A sin offering is included in a gift of dedication. Even Israel's best day needs blood at the middle of it.",
    '7:17': "The peace offerings are the largest item, and peace offerings were eaten. The dedication ends in a meal.",
    '7:18': "The second day's inventory is written out in full rather than called the same as yesterday's.",
    '7:24': "A third time, item by item. The repetition is the honour: no tribe is folded into a summary.",
    '7:48': "Ephraim's day falls seventh, exactly where Ephraim's standard falls in the march. Nothing here is improvised.",
    '7:78': "The twelfth prince is given the same number of words as the first. Naphtali is not abbreviated for coming last.",
    '7:84': "Only now, after twelve days, does the text total it up. The summary existed all along and was withheld on purpose.",
    '7:86': "A hundred and twenty shekels of gold, all of it in spoons for incense. The costliest metal carries the most fleeting gift.",
    '7:87': "Twelve bullocks, twelve rams, twelve lambs, twelve goats. Every tribe brought the same, and no tribe brought more.",
    '7:88': "Twenty-four oxen and sixty each of rams, goats and lambs for peace offerings. The feast dwarfs everything burnt.",
    '7:89': "After eighty-eight verses of gifts, God speaks — from the mercy seat, between the cherubim, over the law.",
    # ---- Chapter 8 ----
    '8:2': "The lamps are set to shine over against the candlestick, so the light falls on what stands in front of it.",
    '8:3': "\"And Aaron did so.\" After what two of his sons did with fire, a plain note of obedience is worth recording.",
    '8:4': "Beaten work, after the pattern shewed. Nothing about the light in God's house was the craftsman's own idea.",
    '8:6': "\"Take the Levites and cleanse them.\" Being chosen by God did not leave them fit to come near him.",
    '8:7': "Sprinkled, shaved, washed. The cleansing is done on the body, in public, where anyone can see it happen.",
    '8:9': "The whole assembly is gathered to watch. A minister is set apart in front of the people he will serve.",
    '8:10': "Israel lays hands on the Levites the way a man lays hands on his sacrifice. The congregation is handing them over.",
    '8:11': "Aaron waves living men before the LORD as an offering. This tribe is what Israel puts on the altar.",
    '8:12': "The Levites lay their hands on bullocks in turn. The men who bear others' sin need atonement of their own.",
    '8:14': "\"The Levites shall be mine.\" Separation to God is described as God taking, never as the man volunteering.",
    '8:16': "Every household's eldest son walks free because a whole tribe stands in the place he would have filled.",
    '8:17': "The claim reaches beyond people to cattle. God's right over the firstborn was total before it was commuted.",
    '8:19': "The Levites are given \"that there be no plague\" when Israel comes near. Their office is a buffer as much as a service.",
    '8:21': "Aaron made atonement for them first. The men appointed to handle atonement did not begin by being clean.",
    '8:22': "\"And after that went the Levites in.\" Nobody in this book starts the work before the washing.",
    '8:24': "Twenty-five here, thirty in chapter four. The text leaves both ages standing, and the rabbis argued over it for centuries.",
    '8:25': "At fifty they cease. The one tribe with no land to retire to is still ordered to stop working.",
    '8:26': "The old Levites keep the charge but carry nothing. Age moves a man from labour to oversight, not out of the tent.",
})

TAKEAWAYS.update({
    # ---- Chapter 9 ----
    '9:1': "The first month of the second year — a month earlier than chapter one. The book is arranged by theme before chronology.",
    '9:3': "\"According to all the rites of it.\" A people living in tents keeps the feast in full rather than in outline.",
    '9:5': "They kept the passover at Sinai, and then kept none again until Joshua at Gilgal, forty years later.",
    '9:6': "Men made unclean by a corpse find themselves shut out of the one meal that marks them as Israel.",
    '9:7': "\"Wherefore are we kept back?\" They are pleading to be let into an obligation, not out of one.",
    '9:8': "\"Stand still, and I will hear what the LORD will command.\" Moses will not invent a ruling to be helpful.",
    '9:10': "A second date is created for the unclean and the far-off. The law is enlarged rather than waived.",
    '9:11': "Unleavened bread and bitter herbs a month late. The concession moves the day and changes nothing else.",
    '9:12': "\"Nor break any bone of it.\" John stands at the cross and reports that this rule was kept.",
    '9:13': "The man who could come and would not is cut off. The exception was made for the hindered, not the indifferent.",
    '9:14': "\"One ordinance, both for the stranger, and for him that was born in the land.\" The passover has no outer ring.",
    '9:15': "Cloud by day and fire by night, from the day the tent went up. The sign arrives with the dwelling.",
    '9:17': "They moved when the cloud moved. Israel's itinerary was followed, never planned.",
    '9:19': "When the cloud tarried long they stayed, and the text calls that keeping the charge of the LORD.",
    '9:21': "Sometimes the cloud lifted after a single night. They lived permanently ready to be moved on.",
    '9:22': "Two days, or a month, or a year. Guidance sometimes looks exactly like nothing happening.",
    # ---- Chapter 10 ----
    '10:2': "Two silver trumpets, beaten of one piece. A camp of six hundred thousand is governed by a sound.",
    '10:3': "Both trumpets call everyone to the door of the tent. The summons and the sanctuary are the same place.",
    '10:5': "An alarm moves the camp; a blast gathers it. The same instrument says different things, and the people had to know which.",
    '10:7': "The assembly is called without an alarm. Israel is taught to hear the difference between a meeting and a war.",
    '10:8': "The priests hold the trumpets, not the captains. The order to march comes from the altar's side of the camp.",
    '10:9': "\"Ye shall be remembered before the LORD.\" The battle signal is aimed upward before it is aimed at the enemy.",
    '10:10': "The same trumpets sound over feasts and new moons. Gladness gets the instrument that also sounds for war.",
    '10:11': "The cloud lifts on the twentieth day of the second month. Almost a year at the mountain ends in one sentence.",
    '10:12': "They leave Sinai for Paran. The mountain where the law was given is behind them now and never returned to.",
    '10:13': "The first march goes exactly as commanded. Three days later the complaining starts.",
    '10:14': "Judah's standard goes first, as chapter two arranged. The plan and the practice match for once.",
    '10:17': "The tent comes down and moves between the marching divisions, carried by men rather than drawn by beasts.",
    '10:21': "Kohath comes up later and finds the tabernacle already standing. The holy things never wait in the open.",
    '10:25': "Dan is the rereward, gathering the stragglers. Somebody has to march at the back of a nation.",
    '10:28': "\"Thus were the journeyings of the children of Israel.\" The order holds for exactly three days.",
    '10:29': "Moses invites his Midianite brother-in-law along on the strength of a promise made to somebody else.",
    '10:30': "\"I will not go.\" The refusal is left standing in the record, unanswered and unexplained.",
    '10:31': "\"Thou mayest be to us instead of eyes.\" A man led by a pillar of cloud still asks a desert guide to stay.",
    '10:32': "Whatever good God does to Israel, Moses promises to share out. The blessing is treated as spendable.",
    '10:33': "The ark goes ahead to seek a resting place. What normally sits behind the veil is out in front, looking for somewhere to stop.",
    '10:35': "\"Rise up, LORD.\" Israel's battle cry is addressed to God, and asks him to do the fighting.",
    '10:36': "\"Return, O LORD, unto the many thousands of Israel.\" The march ends by asking God to come and sit down among them.",
    # ---- Chapter 11 ----
    '11:1': "The complaint has no content — the text does not bother to report it. The fire falls at the edges, where it started.",
    '11:2': "Moses prays and the fire stops. The man they will spend the book resenting is the reason they survive it.",
    '11:3': "Taberah, the burning. Israel keeps naming its places after its own worst behaviour.",
    '11:4': "The craving starts with the mixt multitude and spreads inward. Israel catches the appetite of the people it brought along.",
    '11:5': "\"We did eat in Egypt freely.\" Slaves remember the fish as free and leave out what they paid for it.",
    '11:6': "\"Nothing at all, beside this manna.\" Bread from heaven, received daily, has become their word for nothing.",
    '11:8': "They ground it, beat it, baked it. Even bread from heaven had to be gathered and worked before it was a meal.",
    '11:9': "The manna came down with the dew, at night. The provision was already lying there before anyone woke to want it.",
    '11:10': "Every man weeping in his own tent door. The grievance is public, and each household performs it separately.",
    '11:11': "Moses answers the people's complaint with a complaint of his own, addressed upward in almost their words.",
    '11:12': "\"Have I conceived all this people?\" He is refusing a motherhood he never agreed to.",
    '11:13': "\"Whence should I have flesh?\" A leader is being asked for something only God can supply, and he knows it.",
    '11:14': "\"I am not able to bear all this people alone.\" The admission is not rebuked; it is answered.",
    '11:15': "\"Kill me, I pray thee.\" Scripture keeps the prayer of a good man asking to die, without comment or apology.",
    '11:16': "Seventy men Moses already knows. God's help comes as people who were standing there the whole time.",
    '11:17': "The Spirit on Moses is put on the seventy. Shared authority here is distributed, not invented from nothing.",
    '11:18': "\"Sanctify yourselves\" before the meat comes. Even a judgement is served with an order to prepare for it.",
    '11:20': "A month of flesh \"until it come out at your nostrils.\" The severest punishment in the chapter is getting what they asked for.",
    '11:21': "Moses does the arithmetic out loud — six hundred thousand men — and finds the promise impossible.",
    '11:22': "\"Shall all the fish of the sea be gathered?\" The man who saw the sea divided is now calculating the odds.",
    '11:23': "\"Is the LORD's hand waxed short?\" The question is put to the believer, not to the rabble.",
    '11:25': "The seventy prophesy once, and never again. The sign was given to settle the matter, not to found an order.",
    '11:26': "Eldad and Medad prophesy in the camp, having missed the meeting. The Spirit does not wait at the tent door.",
    '11:27': "A young man runs to report it. Irregular gifts are reported faster than useful ones.",
    '11:28': "\"My lord Moses, forbid them.\" Joshua's instinct is to protect an office that was never under threat.",
    '11:29': "\"Would God that all the LORD's people were prophets.\" Moses wants his own authority made unnecessary.",
    '11:31': "Quail two cubits deep for a day's journey around. The answer to their craving arrives in obscene abundance.",
    '11:32': "A day, a night and another day spent gathering. Nobody stopped to ask why God was being so generous.",
    '11:33': "\"While the flesh was yet between their teeth.\" The thing they wanted and the judgement arrive in the same mouthful.",
    '11:34': "Kibrothhattaavah, the graves of lust. The place is named for what the people buried there, and why.",
})

TAKEAWAYS.update({
    # ---- Chapter 12 ----
    '12:1': "The complaint is filed against his wife. The next verse shows what it was really about.",
    '12:2': "\"Hath he not spoken also by us?\" They were right about themselves and wrong about what it entitled them to.",
    '12:3': "A parenthesis on Moses' meekness, dropped in exactly where his self-defence would have gone.",
    '12:5': "God calls Aaron and Miriam out to the door. Moses is left standing there and says nothing in his own cause.",
    '12:7': "\"Faithful in all mine house.\" Hebrews will set this sentence beside a greater servant in the same house.",
    '12:8': "\"Wherefore then were ye not afraid?\" The offence is not against Moses' dignity but against God's choosing.",
    '12:9': "\"And he departed.\" The anger of God is expressed here as leaving, which is the worse of the two.",
    '12:10': "Miriam comes out leprous and Aaron does not. The priest who joined the attack is spared its consequence.",
    '12:11': "Aaron calls Moses \"my lord\" and asks him for help. The man they demoted is the only advocate in the tent.",
    '12:12': "Aaron pleads in the language of a stillbirth. He has seen at once what leprosy will do to his sister.",
    '12:13': "\"Heal her now, O God, I beseech thee.\" The shortest prayer in the book, prayed for the woman who attacked him.",
    '12:14': "The leprosy is healed and the shame is still served out. Forgiveness here does not cancel the seven days.",
    '12:15': "A nation of six hundred thousand waits a week for one woman. Nobody is left behind to catch up.",
    # ---- Chapter 13 ----
    '13:2': "\"The land of Canaan, which I give unto the children of Israel.\" The gift is settled before the survey begins.",
    '13:3': "Every man sent is a head of his tribe. The failure that follows is a failure of Israel's best men.",
    '13:6': "Caleb of Judah. His name appears here without comment, and by the end of the chapter it will need none.",
    '13:8': "Oshea the son of Nun, of Ephraim, listed among eleven men most of whom nobody remembers.",
    '13:16': "Moses renames him Jehoshua — the LORD saves. The man who will take them in is given the promise as a name.",
    '13:17': "They are sent to see the land, not to decide about it. The question of going was never on the agenda.",
    '13:18': "Strong or weak, few or many. Moses asks for military intelligence, which is exactly what he gets back.",
    '13:20': "\"Be ye of good courage, and bring of the fruit.\" The instruction anticipates that courage will be the difficulty.",
    '13:21': "They covered the whole land, from Zin to Hamath. Nobody could say afterwards that they had not looked.",
    '13:22': "Hebron, where Abraham had pitched and was buried. The spies walk through their own inheritance and see only Anakim.",
    '13:23': "One cluster of grapes carried between two men on a staff. The land's goodness came home on their shoulders.",
    '13:24': "The valley is named after the cluster, so the proof of the promise gave its name to the scene of the refusal.",
    '13:25': "Forty days of searching. The number will be charged back to them at a year apiece.",
    '13:26': "They report to the whole congregation, not to Moses alone. A briefing becomes a public meeting.",
    '13:27': "\"Surely it floweth with milk and honey; and this is the fruit of it.\" Every word of the promise is confirmed first.",
    '13:28': "\"Nevertheless.\" One word turns a confirmed promise into an argument against acting on it.",
    '13:29': "The list of nations is accurate, and accuracy is what makes the report so effective.",
    '13:30': "Caleb does not dispute the giants. He disputes the conclusion, and the arithmetic he is using includes God.",
    '13:31': "\"They are stronger than we.\" Perfectly true, and beside the point from beginning to end.",
    '13:32': "The land that flowed with milk and honey in verse 27 now eats its inhabitants. Fear rewrites the evidence it was given.",
    '13:33': "\"We were in our own sight as grasshoppers\" — and then they presume to report what they looked like to the giants.",
    # ---- Chapter 14 ----
    '14:1': "The congregation spends the night weeping over a land they have just been shown the fruit of.",
    '14:2': "\"Would God we had died in this wilderness.\" It is the one prayer in the chapter that God grants exactly.",
    '14:3': "They fear their wives and children will be a prey, and those are the only ones who will see the land.",
    '14:4': "\"Let us make a captain, and let us return into Egypt.\" The exodus is put to a vote and voted down.",
    '14:5': "Moses and Aaron fall on their faces. There is no argument left to make to a congregation in this state.",
    '14:6': "Joshua and Caleb rend their clothes. What they show first is grief rather than indignation.",
    '14:7': "The minority report disagrees about nothing they saw. It disagrees about who is going with them.",
    '14:8': "\"If the LORD delight in us.\" Their confidence rests on God's pleasure, not on their own estimate of the odds.",
    '14:9': "\"They are bread for us.\" Caleb keeps the giants exactly the size they were and changes who is eating whom.",
    '14:10': "The congregation reaches for stones and the glory appears. The interruption is what saves the two men's lives.",
    '14:11': "\"How long will it be ere they believe me, for all the signs?\" Miracles, it turns out, do not manufacture faith.",
    '14:12': "God offers Moses what was promised to Abraham. The offer tests the mediator as much as it threatens the people.",
    '14:13': "Moses argues from what Egypt will say. He pleads God's reputation because Israel's case is indefensible.",
    '14:16': "\"Because the LORD was not able.\" Moses repeats the slander aloud as his strongest argument for mercy.",
    '14:18': "Moses prays God's own self-description back to him. The safest prayer is one made of God's words.",
    '14:19': "\"As thou hast forgiven this people, from Egypt even until now.\" He pleads a long record of pardon as precedent.",
    '14:20': "\"I have pardoned according to thy word.\" The pardon is real, and the next verses still bury a generation.",
    '14:21': "In the middle of a national collapse God swears that the earth will be filled with his glory anyway.",
    '14:22': "\"These ten times.\" God has been keeping count of provocations the people had long stopped noticing.",
    '14:23': "The promise is not withdrawn; it is simply not for them. The land stays certain and the generation does not.",
    '14:24': "Caleb \"had another spirit with him.\" Even the courage that saved him is described as something he was given.",
    '14:28': "\"As ye have spoken in mine ears, so will I do to you.\" The sentence is their own wish, carried out.",
    '14:29': "The census that opened the book becomes the list of who will die here. Every name in chapter one is in this verse.",
    '14:30': "Two men out of six hundred thousand. The exceptions are exactly the two who said the land could be taken.",
    '14:31': "The children they used as their argument are the ones brought in. God takes the excuse and honours it.",
    '14:33': "The children wander forty years bearing what their parents did. Sin is rarely paid for by the sinner alone.",
    '14:34': "A year for every day of the search. The sentence is measured out in the currency of the sin itself.",
    '14:35': "\"I the LORD have said, I will surely do it.\" The same certainty that promised the land now closes it.",
    '14:37': "The ten die of plague. The report they carried home killed them before it killed anybody else.",
    '14:38': "\"Lived still.\" Two men outlive a whole generation because they believed a report nobody wanted.",
    '14:39': "\"The people mourned greatly.\" The next verse shows that mourning and repentance are not the same thing.",
    '14:40': "\"We be here, and will go up.\" Obedience offered a day late is only disobedience wearing better clothes.",
    '14:41': "\"It shall not prosper.\" Moses warns them off the very thing he had spent the day begging them to do.",
    '14:42': "\"Go not up, for the LORD is not among you.\" Presence, not courage, was always what made the difference.",
    '14:44': "They presumed to go up, and the ark stayed in the camp. They took the battle and left behind the reason to fight it.",
    '14:45': "At Hormah they lose the war they refused to fight with God. The giants were never the problem.",
})

TAKEAWAYS.update({
    # ---- Chapter 15 ----
    '15:2': "\"When ye be come into the land\" — said to a generation just told they will never see it.",
    '15:3': "Vow, freewill offering and feast stand side by side. Worship has room for the planned and the spontaneous.",
    '15:4': "Every animal offering comes with flour and oil. Nobody brings blood to the altar without bringing bread as well.",
    '15:11': "The grain and wine scale with the beast. A poor man's kid is not asked to carry a bullock's portion.",
    '15:13': "The manner is fixed so that no worshipper has to invent his own way of coming near.",
    '15:14': "The stranger who wants to offer is not turned away, and not given a lesser rite either.",
    '15:15': "\"As ye are, so shall the stranger be before the LORD.\" Israel's own standing is the measure of the outsider's welcome.",
    '15:19': "Not manna now but \"the bread of the land.\" Settled prosperity is given its own act of thanks.",
    '15:20': "A cake from the first of the dough. The offering is taken from the daily baking, before anyone has eaten.",
    '15:22': "\"If ye have erred.\" The law expects to be broken by people who were trying to keep it.",
    '15:24': "A whole congregation can sin without knowing. Corporate guilt is treated as real even where no one intended it.",
    '15:25': "\"And it shall be forgiven them; for it is ignorance.\" The remedy is named before anyone asks whether there is one.",
    '15:26': "The stranger is forgiven with them. He shares the pardon of a congregation he was never counted in.",
    '15:27': "One soul, one she goat. The individual is not swallowed up in the congregation's sacrifice.",
    '15:29': "Ignorance has the same price for the native and the sojourner. One law here means one remedy.",
    '15:30': "Presumption \"reproacheth the LORD,\" and no offering is prescribed for it. The gap is the point.",
    '15:31': "\"He hath despised the word of the LORD.\" The sin is not the act alone but the contempt inside it.",
    '15:32': "A man gathering sticks. The case that tests the sabbath is as small and domestic as it could possibly be.",
    '15:33': "They bring him to Moses rather than deal with him where they found him. Even the obvious case goes through the court.",
    '15:34': "\"It was not declared what should be done to him.\" They hold him rather than guess, and wait to be told.",
    '15:35': "The sentence is death, and it comes from God rather than from the offended community. Nobody improvised this.",
    '15:36': "Stoned without the camp for firewood. Set beside the man pardoned for ignorance, the difference is deliberate defiance.",
    '15:38': "A ribband of blue on the hem. God gives a people who forget everything a thing they cannot help seeing.",
    '15:39': "\"That ye may look upon it, and remember.\" The eyes that wander are given something to catch on first.",
    '15:40': "Remembering and doing sit in one clause. Holiness begins here as an act of memory.",
    '15:41': "\"I am the LORD your God\" twice in one verse, with the exodus between. The reason for the fringe is who tied it on.",
    # ---- Chapter 16 ----
    '16:1': "Korah is a Kohathite, from the clan that carried the holiest things. The rebellion starts closest to the centre.",
    '16:2': "Two hundred and fifty princes, \"famous in the congregation.\" This is not a mob but the establishment.",
    '16:3': "\"All the congregation are holy.\" Every word of it is true, and it is used to abolish the office God appointed.",
    '16:4': "Under attack Moses falls on his face again, out of the argument and onto the ground.",
    '16:5': "\"To morrow the LORD will shew who are his.\" Moses refuses to settle by debate what only God can settle.",
    '16:7': "The test is a censer each. Korah wanted the priesthood and is handed the priest's own risk.",
    '16:9': "\"Seemeth it but a small thing?\" The Levites already had nearness. Discontent had made a gift look like a slight.",
    '16:10': "\"And seek ye the priesthood also?\" Moses names the ambition that the language of equality was covering.",
    '16:11': "\"What is Aaron, that ye murmur against him?\" The quarrel with the office is a quarrel with the one who made it.",
    '16:12': "\"We will not come up.\" Dathan and Abiram will not even attend the hearing they demanded.",
    '16:13': "Egypt, where they were slaves, is now the land flowing with milk and honey. Memory has changed sides entirely.",
    '16:14': "\"Wilt thou put out the eyes of these men?\" They accuse Moses of the blindness they are choosing.",
    '16:15': "\"I have not taken one ass from them.\" The charge of profiteering stings a man who never took a fee.",
    '16:17': "Two hundred and fifty censers, each man his own. Nobody is dragged into this; every one carries his own fire.",
    '16:18': "Censers at the tabernacle door: for one moment the rebellion looks exactly like worship.",
    '16:19': "Korah brings the whole congregation to watch, and the glory appears instead of the verdict he expected.",
    '16:21': "\"That I may consume them in a moment.\" The two men under attack are the only reason the camp survives the hour.",
    '16:22': "\"Shall one man sin, and wilt thou be wroth with all the congregation?\" Moses pleads for the people who wanted him gone.",
    '16:25': "Moses walks to the tents of the men who would not come to him. The elders follow him there.",
    '16:26': "\"Touch nothing of theirs.\" Standing near the rebellion is treated as taking part in it.",
    '16:27': "Dathan and Abiram stand in their tent doors with their wives and little children. The text will not let us miss who is there.",
    '16:28': "\"I have not done them of mine own mind.\" Moses stakes his whole commission on what happens in the next minute.",
    '16:29': "\"If these men die the common death of all men, then the LORD hath not sent me.\" He offers a test that could destroy him.",
    '16:30': "\"If the LORD make a new thing.\" An ordinary judgement would have proved nothing, so Moses asks for an unrepeatable one.",
    '16:31': "\"As he had made an end of speaking.\" The ground waits for him to finish the sentence.",
    '16:32': "The earth opens her mouth. The one element that has never threatened them becomes the instrument.",
    '16:33': "\"Went down alive into the pit, and the earth closed upon them.\" The ground shuts as though nothing had happened.",
    '16:34': "Israel runs from the cry. The thing they feared was the punishment rather than the sin that earned it.",
    '16:35': "Fire from the LORD takes the two hundred and fifty. The censers they held did not make them priests.",
    '16:37': "The censers are hallowed even in the hands of rebels. What has been offered to God is not made common by the offerer.",
    '16:38': "\"Sinners against their own souls.\" The plates hammered from their censers are bolted to the altar as a public warning.",
    '16:39': "Eleazar, the son who will inherit the office, does the work of clearing away the men who wanted it.",
    '16:40': "A memorial in brass on the altar. Israel will see the answer to Korah's question every time they bring a sacrifice.",
    '16:41': "\"Ye have killed the people of the LORD.\" The morning after the earth closed, the same complaint starts again.",
    '16:42': "They gather against Moses and the cloud covers the tent. The pattern of yesterday begins repeating within a day.",
    '16:45': "The second sentence of destruction, and the second time these two answer it face down on the ground.",
    '16:46': "\"Take a censer, and run.\" The instrument of Korah's presumption becomes the instrument of the people's rescue.",
    '16:47': "Aaron runs into the middle of the plague. The high priest's place in an emergency is where the dying are.",
    '16:48': "\"He stood between the dead and the living.\" One man in the gap with incense is the whole office in a sentence.",
    '16:49': "Fourteen thousand seven hundred, counted apart from Korah's men. Sympathy cost more than the rebellion did.",
    # ---- Chapter 17 ----
    '17:2': "Twelve rods with twelve names. The question of who leads is to be answered by dead wood, not by a vote.",
    '17:4': "The rods are laid up before the testimony. The verdict is reached where no human hand can reach the evidence.",
    '17:5': "\"I will make to cease from me the murmurings.\" God treats the grumbling as aimed at himself, not at Moses.",
    '17:6': "Aaron's rod goes in among the others with nothing to distinguish it. The test is fair on its face.",
    '17:7': "Moses lays them up and leaves. The whole proceeding happens overnight, with no witnesses at all.",
    '17:8': "Buds, blossoms and ripe almonds on one dead stick in one night. The chosen office is marked by life, not by argument.",
    '17:9': "Every man takes back his own rod, still dry. They are made to carry home the proof in their hands.",
    '17:10': "The budded rod is kept \"for a token against the rebels.\" Israel's memory is not trusted to hold this on its own.",
    '17:12': "\"We die, we perish, we all perish.\" The people finally grasp the danger, and it leaves them with no hope in it.",
    '17:13': "\"Shall we be consumed with dying?\" The right terror still needs a mediator, which is what the next chapter gives.",
})

TAKEAWAYS.update({
    # ---- Chapter 18 ----
    '18:1': "\"Ye shall bear the iniquity of the sanctuary.\" The office Korah wanted is defined as liability, not privilege.",
    '18:2': "The Levites are \"joined\" to Aaron, which is what their name means. The pun is the job description.",
    '18:3': "A line the Levites may not cross, \"that neither they, nor ye also, die.\" The limit is protection, not insult.",
    '18:5': "\"That there be no wrath any more upon the children of Israel.\" The priesthood stands there as a firebreak.",
    '18:6': "The Levites are \"given as a gift\" — to Aaron, and by God. Nobody in this arrangement appointed himself.",
    '18:7': "\"A service of gift.\" The priesthood cannot be seized, only received, which was Korah's whole mistake.",
    '18:8': "Aaron is given charge of the offerings and also fed by them. Service and support arrive in the same sentence.",
    '18:9': "What the fire leaves is the priest's portion. He eats from the altar he tends, and eats it as holy.",
    '18:11': "Daughters eat of this as well as sons. The priest's whole clean household lives off the sanctuary.",
    '18:12': "\"All the best of the oil.\" God's share is specified as the best so that it cannot quietly become the remainder.",
    '18:14': "\"Every thing devoted in Israel shall be thine.\" What is given away irrevocably still has to land somewhere.",
    '18:15': "The firstling of a beast is offered and the firstborn son is bought back. The child is redeemed, not sacrificed.",
    '18:16': "Five shekels a head, at a month old. Every family in Israel paid a price to keep its own eldest.",
    '18:19': "\"A covenant of salt for ever.\" Salt keeps what would otherwise spoil, which is what the phrase is claiming.",
    '18:20': "\"I am thy part and thine inheritance.\" Aaron gets no acre, and the loss is stated as the gift.",
    '18:21': "The tithe is the Levites' inheritance — wages for work rather than charity for the landless.",
    '18:22': "Israel is kept back from the tent \"lest they bear sin, and die.\" Distance is a mercy here.",
    '18:23': "\"They shall bear their iniquity.\" The Levites absorb a risk that would otherwise fall on the whole nation.",
    '18:24': "The sentence ends where it began: no inheritance. The clause is repeated because it is hard to live with.",
    '18:26': "The Levites tithe their tithe. Those who live on gifts are not exempted from giving.",
    '18:31': "\"It is your reward for your service.\" Sacred work is treated as work, and paid.",
    '18:32': "Heave the best off first \"lest ye die.\" Skimming the holy things is the danger a salaried priesthood runs.",
    # ---- Chapter 19 ----
    '19:2': "A red heifer without blemish that never wore a yoke. Nothing already used for ordinary work will do here.",
    '19:3': "Slain outside the camp, in the priest's sight. Hebrews will notice where this one dies.",
    '19:4': "Blood sprinkled toward the tent seven times, though the body is burnt away from it. The direction still matters.",
    '19:7': "The priest who prepares the cleansing is himself unclean till evening. Making others clean costs him his own standing.",
    '19:9': "The ashes are stored up for later use. A single sacrifice is kept on hand for every death that will happen.",
    '19:11': "Touching a corpse makes a man unclean seven days. Death, not sin, is the contagion this chapter is built around.",
    '19:12': "Third day and seventh day, or not clean at all. Half the cure leaves a man exactly where he started.",
    '19:13': "A man who will not be cleansed \"defileth the tabernacle\" from a distance. Private neglect turns out to be public.",
    '19:14': "When a man dies in a tent, everyone who walks in is unclean. Grief and defilement arrive by the same door.",
    '19:16': "A bone, a grave, a body in a field. The law reaches the accidental contact nobody could have avoided.",
    '19:17': "Ashes and running water. The remedy mixes something dead and burnt with something living and moving.",
    '19:18': "A clean person does the sprinkling. Nobody in this rite cleanses himself.",
    '19:19': "The clean man ends the week washing himself. He takes on uncleanness by handling the cure for it.",
    '19:20': "Cut off, \"because he hath defiled the sanctuary.\" Refusing the water is what damns, not the corpse he touched.",
    '19:22': "Uncleanness spreads by touch and cleanness does not. The asymmetry is the argument the whole chapter makes.",
    # ---- Chapter 20 ----
    '20:1': "Miriam dies and is buried in half a verse. The sister who watched the basket on the Nile gets no eulogy.",
    '20:2': "No water, and the gathering against Moses is immediate. Thirty-eight years have changed the generation, not the habit.",
    '20:3': "\"Would God that we had died when our brethren died.\" The children have learned their parents' prayer by heart.",
    '20:4': "\"Why have ye brought up the congregation?\" Rescue is again described as abduction.",
    '20:5': "No seed, figs, vines or pomegranates. They name the very fruit the spies once carried home on a pole.",
    '20:6': "Moses and Aaron leave the assembly and fall down at the door. They take the complaint where it can be answered.",
    '20:8': "\"Speak ye unto the rock.\" Last time it was struck; this time the instruction is a word only.",
    '20:10': "\"Hear now, ye rebels; must we fetch you water?\" Two words go wrong at once: the insult, and the \"we\".",
    '20:11': "He smites the rock twice and the water comes abundantly anyway. Answered prayer is not the same as approval.",
    '20:12': "\"Because ye believed me not, to sanctify me.\" Forty years of service do not exempt the mediator from the law.",
    '20:13': "The place is named for Israel's striving, \"and he was sanctified in them.\" God gets his holiness either way.",
    '20:14': "\"Thus saith thy brother Israel.\" Edom is approached as kin, with Jacob and Esau still standing behind the word.",
    '20:16': "The whole exodus is compressed into one sentence for a foreign king. Israel's history is its only credential.",
    '20:18': "Edom answers with the sword. Kinship counts for nothing against a border.",
    '20:19': "They offer to pay for water — a people who had none an hour ago, bargaining in good faith.",
    '20:20': "\"Thou shalt not go through,\" backed by much people and a strong hand. The refusal is made expensive to test.",
    '20:21': "Israel turns away. The nation that just took Hormah declines a war it could probably have won.",
    '20:24': "Aaron is told he will die outside the land, and the reason given is Meribah. The rock cost both brothers everything.",
    '20:25': "Take Aaron and his son up the mountain. The man is to walk to his own deathbed and bring his successor.",
    '20:26': "The garments are moved from father to son. The office outlives the man wearing it, which is the comfort in this.",
    '20:27': "It is done \"in the sight of all the congregation.\" The succession is public so that nobody can dispute it.",
    '20:28': "Aaron dies on the top of the mount, and two men come down where three went up.",
    '20:29': "Thirty days of mourning for the man who made the golden calf and then carried incense into a plague.",
})

TAKEAWAYS.update({
    # ---- Chapter 21 ----
    '21:1': "Arad attacks \"by the way of the spies\" and takes prisoners. The old road is still the dangerous one.",
    '21:2': "Israel vows before it fights. The generation that once refused to go up now bargains for the chance.",
    '21:3': "Hormah, where the last generation was routed, is taken. The same place is lost and won by two sets of the same people.",
    '21:4': "\"The soul of the people was much discouraged because of the way.\" The detour, not the enemy, is what breaks them.",
    '21:5': "\"Our soul loatheth this light bread.\" Bread out of heaven has become the specific grievance.",
    '21:6': "Serpents in the sand. The punishment for despising the food is a death that comes up out of the ground they walk on.",
    '21:7': "\"We have sinned\" — the first clean confession in the book, and Moses prays for them without arguing.",
    '21:8': "The remedy is shaped like the plague. They are told to look at the very thing that is killing them.",
    '21:9': "Bitten men live by looking, not by doing. John 3 will hang the whole gospel on the grammar of this verse.",
    '21:13': "The Arnon is the border of Moab, so Israel is now camped on the edge of somebody's country.",
    '21:14': "\"The book of the wars of the LORD\" is quoted and then lost. Israel had records Scripture does not preserve.",
    '21:16': "Beer, the well God promised before they asked. Between two complaints, water arrives without a murmur.",
    '21:17': "\"Spring up, O well.\" The generation that sang at the Red Sea sings again, over a hole in the desert.",
    '21:18': "Princes and nobles dug it with their staves. The song credits the labour and the lawgiver's direction together.",
    '21:21': "Israel asks Sihon for passage in the same words it used on Edom. The policy did not change after the first refusal.",
    '21:22': "\"We will not drink of the waters of the well.\" A people with a grievance about water promise to touch none of his.",
    '21:23': "Sihon comes out to fight in the wilderness rather than wait behind walls. He picks the ground and loses on it.",
    '21:24': "The first land Israel keeps is land it never asked for. Sihon's refusal handed over what a request would not have.",
    '21:25': "Israel dwells in the Amorites' houses. After forty years in tents, the first roof is somebody else's.",
    '21:26': "Heshbon had been taken from Moab by Sihon. Israel inherits a conquest, which will complicate the claim later.",
    '21:27': "A Moabite victory song is quoted against the victors. The proverb-makers celebrated the city Israel now holds.",
    '21:28': "\"A fire gone out of Heshbon.\" The poem boasts of a strength that has just been broken in a single afternoon.",
    '21:29': "\"Woe to thee, Moab! thou art undone, O people of Chemosh.\" The god named here could not hold his own ground.",
    '21:31': "\"Thus Israel dwelt in the land of the Amorites.\" One flat sentence for the first thing they ever possessed.",
    '21:32': "Moses sends men to spy Jaazer, and this time the report is acted on without a meeting.",
    '21:33': "Og of Bashan comes out with all his people. The giants the spies feared are now simply the next battle.",
    '21:34': "\"Fear him not.\" The word is given before the fight, and it is the word the first generation would not take.",
    '21:35': "None left alive. The verse states without comment what the earlier refusal had judged impossible.",
    # ---- Chapter 22 ----
    '22:2': "Balak \"saw all that Israel had done to the Amorites.\" His fear is built on accurate information.",
    '22:3': "Moab is afraid \"because they were many.\" The nation that thought itself grasshoppers now frightens a kingdom.",
    '22:4': "\"As the ox licketh up the grass.\" Moab's picture of Israel is an animal that clears a field without malice.",
    '22:5': "Balak hires a prophet from the Euphrates. Every other weapon has been tried, so he sends for words.",
    '22:6': "\"He whom thou blessest is blessed.\" Balak believes in the power of the blessing and means to rent it.",
    '22:7': "\"The rewards of divination in their hand.\" The fee travels with the delegation, before any question is asked.",
    '22:8': "\"As the LORD shall speak unto me.\" A foreign seer uses the covenant name and expects an answer.",
    '22:9': "\"What men are these with thee?\" God asks a question he does not need answered, as he did in the garden.",
    '22:11': "Balaam repeats Balak's request to God almost word for word, including the part about cursing.",
    '22:12': "\"Thou shalt not curse the people: for they are blessed.\" The verdict rests on a fact, not on Israel's behaviour.",
    '22:13': "\"The LORD refuseth to give me leave.\" He reports the ban accurately and leaves out the reason for it.",
    '22:15': "Balak sends more honourable princes. When a refusal is treated as a price, the price simply goes up.",
    '22:16': "\"Let nothing hinder thee from coming.\" Balak is negotiating with the man rather than with the God who said no.",
    '22:17': "Promotion to very great honour. The bribe is aimed at standing rather than at silver, and it is better aimed.",
    '22:18': "\"His house full of silver and gold\" — Balaam names a sum, which is what a man does who is thinking about one.",
    '22:19': "\"Tarry ye also here this night.\" Asking again about a settled answer is how the second question gets asked.",
    '22:20': "\"Rise up, and go with them.\" Permission is granted to a man who wanted it, and it is not the same as approval.",
    '22:21': "He saddles his own ass and goes. The narrative dwells on his eagerness before it stops him in the road.",
    '22:22': "God's anger is kindled \"because he went\" — on the journey he had just been told he could make.",
    '22:23': "The ass sees the angel and the seer does not. The man hired for his sight is the blindest party on the road.",
    '22:25': "She crushes his foot against the wall, and he beats her for the injury she took to save his life.",
    '22:26': "\"A narrow place, where was no way to turn.\" The angel keeps closing the road until obedience is the only option left.",
    '22:27': "Three refusals from a beast, three beatings from her owner. Neither of them will change course.",
    '22:28': "\"What have I done unto thee?\" The ass asks the only reasonable question in the chapter.",
    '22:29': "\"I would there were a sword in mine hand.\" There is one, drawn, a few feet away and pointed at him.",
    '22:30': "\"Was I ever wont to do so unto thee? And he said, Nay.\" He concedes the argument and still misses the point.",
    '22:31': "The LORD opens his eyes. Seeing, for the professional seer, turns out to be something done to him.",
    '22:32': "\"Thy way is perverse before me.\" The journey permitted in verse 20 is named here for what it is.",
    '22:33': "\"I had slain thee, and saved her alive.\" The animal he beat three times is the reason he is breathing.",
    '22:34': "\"I have sinned; for I knew not.\" The confession is real and its excuse arrives in the same breath.",
    '22:35': "\"Only the word that I shall speak unto thee.\" He is sent on with his mouth no longer his own property.",
    '22:37': "\"Am not I able indeed to promote thee to honour?\" Balak's second sentence is about money, as his first was.",
    '22:38': "\"Have I now any power at all to say any thing?\" The famous freelance announces he has no discretion left.",
    '22:41': "Balak takes him to the high places of Baal to see \"the utmost part of the people.\" The staging is arranged for a curse.",
    # ---- Chapter 23 ----
    '23:1': "Seven altars, seven oxen, seven rams. Balaam brings professional technique to a decision already made.",
    '23:3': "\"Peradventure the LORD will come to meet me.\" The hired seer cannot be sure of his own access.",
    '23:4': "\"I have prepared seven altars.\" Told to speak with God, he opens by listing what he has spent.",
    '23:5': "\"The LORD put a word in Balaam's mouth.\" The mechanism is stated plainly so nobody credits the ritual.",
    '23:7': "\"Come, curse me Jacob.\" Balaam quotes his commission aloud before failing to carry it out.",
    '23:8': "\"How shall I curse, whom God hath not cursed?\" A curse is not a spell but an echo, and there is nothing to echo.",
    '23:9': "\"The people shall dwell alone, and shall not be reckoned among the nations.\" Their separateness is the blessing.",
    '23:10': "\"Let me die the death of the righteous.\" He wants their ending and not their life, which is the whole man.",
    '23:11': "\"I took thee to curse mine enemies.\" Balak's complaint is that he did not get what he paid for.",
    '23:12': "\"Must I not take heed to speak that which the LORD hath put in my mouth?\" He hides behind a constraint he resents.",
    '23:13': "\"Thou shalt see but the utmost part of them.\" Balak thinks a smaller view might produce a smaller blessing.",
    '23:14': "Another hill, another seven altars. The procedure is repeated exactly, as though the problem were the venue.",
    '23:17': "\"What hath the LORD spoken?\" Balak asks for the word he has been dreading, standing beside his own burnt offering.",
    '23:18': "\"Rise up, Balak, and hear.\" The paid man tells the king to stand up and listen.",
    '23:19': "\"God is not a man, that he should lie.\" The one line of this chapter the whole Bible keeps quoting.",
    '23:20': "\"I cannot reverse it.\" The prophet's impotence is the people's security.",
    '23:21': "\"He hath not beheld iniquity in Jacob\" — said of the nation whose sins fill the preceding chapters.",
    '23:22': "The exodus is cited as the reason for the strength. Their power is a rescue, not a record.",
    '23:23': "\"There is no enchantment against Jacob.\" The trade Balaam practises is declared useless against these people.",
    '23:24': "The lion image comes from the mouth of the man hired to stop them. Moab's own prophet describes the invasion.",
    '23:25': "\"Neither curse them at all, nor bless them at all.\" Balak would now settle for silence and cannot get that either.",
    '23:26': "\"Told not I thee?\" Balaam is right about his own limits and keeps taking the journey anyway.",
    '23:27': "\"Peradventure it will please God that thou mayest curse me them from thence.\" A third hill, and the same hope.",
    '23:28': "Peor. The place where the curse fails is the place where Israel will later ruin itself without any help.",
    '23:29': "Seven altars a third time. Persistence in a method that has twice failed is its own kind of faith.",
})

TAKEAWAYS.update({
    # ---- Chapter 24 ----
    '24:1': "He stops seeking enchantments. Even Balaam eventually gives up trying to work the machinery against God.",
    '24:2': "He sees Israel camped by tribes and the Spirit comes on him. The order of the camp is what triggers the blessing.",
    '24:3': "\"The man whose eyes are open.\" He claims the title three verses after an ass had to see for him.",
    '24:5': "\"How goodly are thy tents, O Jacob.\" The tents of a complaining people look different from the outside.",
    '24:6': "Gardens, aloes, cedars by the waters. A desert camp is described entirely in the language of well-watered land.",
    '24:7': "\"His king shall be higher than Agag.\" A nation with no king yet is promised one, by a foreigner's mouth.",
    '24:8': "\"God brought him forth out of Egypt.\" Every oracle here roots Israel's strength in a rescue they did not perform.",
    '24:9': "\"Blessed is he that blesseth thee.\" Abraham's promise is quoted back over Israel by a man hired against them.",
    '24:10': "Balak smites his hands together. The gesture of a man who has paid three times for the opposite of what he wanted.",
    '24:11': "\"The LORD hath kept thee back from honour.\" Balak blames God for the fee, and is more right than he knows.",
    '24:13': "\"To do either good or bad of mine own mind.\" He insists on his integrity in the one area where he had none.",
    '24:14': "\"I will advertise thee what this people shall do to thy people.\" His parting gift to his employer is bad news.",
    '24:17': "\"A Star out of Jacob, and a Sceptre.\" The clearest messianic line in the book is spoken by a hired pagan seer.",
    '24:18': "Edom, which refused passage, is named as a possession. The border that turned Israel back will not hold.",
    '24:19': "\"Out of Jacob shall come he that shall have dominion.\" The oracle moves from a nation to a single coming man.",
    '24:20': "\"Amalek was the first of the nations\" and will perish for ever. Being first proves nothing about lasting.",
    '24:21': "\"Thou puttest thy nest in a rock.\" The Kenite's security is described admiringly and then withdrawn.",
    '24:22': "Asshur is named centuries before Assyria matters. The oracle looks past Moab's problem entirely.",
    '24:23': "\"Alas, who shall live when God doeth this!\" The seer's last word is not triumph but dread.",
    '24:25': "\"Balaam rose up, and went and returned to his place.\" He goes home unpaid, and chapter 31 records where he ends.",
    # ---- Chapter 25 ----
    '25:1': "What Balak could not buy, Shittim supplies for nothing. Moab wins by invitation where it failed by curse.",
    '25:2': "They eat of the sacrifices and then bow down. The idolatry arrives at a meal, in that order.",
    '25:3': "\"Israel joined himself unto Baalpeor.\" The verb is the one used for covenant. This is not a lapse but an alliance.",
    '25:4': "The heads of the people are to be hanged. Leadership is held responsible for what the nation did under it.",
    '25:6': "He brings her past a congregation weeping at the tabernacle door. The insolence is aimed at the mourners.",
    '25:7': "Phinehas is a priest, and he leaves the assembly with a javelin. Nothing in his training covered this.",
    '25:8': "\"So the plague was stayed.\" The act that looks like murder is recorded as the thing that stopped the dying.",
    '25:9': "Twenty-four thousand dead at Peor. The seduction cost more lives than any battle in the book.",
    '25:11': "\"Zealous for my sake.\" God reads the spear as jealousy on his behalf rather than private rage.",
    '25:12': "\"My covenant of peace\" given for an act of violence. The phrase is deliberately uncomfortable.",
    '25:13': "\"Made an atonement\" — a priest's word for what he did with a javelin rather than with blood at the altar.",
    '25:14': "The man is named only now: Zimri, a prince of Simeon. Rank is recorded so no one thinks this was a nobody.",
    '25:15': "Cozbi is a chief's daughter in Midian. What looked like lust was, on her side, something closer to diplomacy.",
    '25:18': "\"They vex you with their wiles.\" Midian's counsel is treated as an act of war, which is what 31 will answer.",
    # ---- Chapter 26 ----
    '26:2': "A second muster of men able to go to war. The list that once recorded who would die is now an order of battle.",
    '26:4': "\"As the LORD commanded Moses\" — the same command as at Sinai, given to a different set of men entirely.",
    '26:9': "\"This is that Dathan and Abiram.\" Their family keeps its place in the register with the crime attached.",
    '26:10': "\"And they became a sign.\" The judgement is filed in the census as a permanent note, not a forgotten incident.",
    '26:11': "\"Notwithstanding the children of Korah died not.\" A whole line of temple singers descends from this one clause.",
    '26:14': "Simeon comes in at twenty-two thousand, down by more than half. Zimri's tribe paid for Peor in the count.",
    '26:19': "\"Er and Onan died in the land of Canaan.\" Two names from Genesis are kept in a list of families that continued.",
    '26:22': "Judah at seventy-six thousand five hundred, the largest tribe. The sceptre is promised where the numbers are.",
    '26:33': "\"Zelophehad had no sons, but daughters.\" Five names appear in a list of heirs where the law expects none.",
    '26:51': "Six hundred and one thousand seven hundred and thirty — almost exactly Sinai's figure. Forty years cost nothing net.",
    '26:53': "The census exists to divide the land. Being counted is now the same thing as being given an inheritance.",
    '26:54': "\"To many thou shalt give the more.\" The allotment is proportioned to need rather than divided into equal shares.",
    '26:55': "\"Notwithstanding the land shall be divided by lot.\" Size is calculated and location is left to God.",
    '26:59': "Jochebed named, with Aaron, Moses and Miriam as her three children. The book's leaders get one genealogical line.",
    '26:61': "\"Nadab and Abihu died, when they offered strange fire.\" Aaron's lost sons are recorded in the family register.",
    '26:62': "The Levites are counted separately because they inherit nothing. Their exclusion from the land is their entry here.",
    '26:64': "\"There was not a man of them whom Moses and Aaron the priest numbered.\" One sentence buries an entire generation.",
    '26:65': "\"Save Caleb and Joshua.\" The two men who believed the report are the two names carried across from the first list.",
})

TAKEAWAYS.update({
    # ---- Chapter 27 ----
    '27:1': "Five sisters with no brother walk into the assembly. They are the only people in Numbers who ask for land and get it.",
    '27:2': "They stand before Moses, Eleazar, the princes and the whole congregation. Nothing about this petition is done quietly.",
    '27:3': "\"He was not in the company of Korah; but died in his own sin.\" They distinguish their father's guilt carefully.",
    '27:4': "\"Why should the name of our father be done away?\" The plea is for a dead man's memory, not for their own comfort.",
    '27:5': "\"Moses brought their cause before the LORD.\" The lawgiver treats a gap in the law as a question, not an answer.",
    '27:7': "\"The daughters of Zelophehad speak right.\" God sides with the petitioners against the settled practice.",
    '27:8': "A case becomes a statute. Five women asking for their father's field changes inheritance law for the whole nation.",
    '27:11': "\"A statute of judgment.\" The chain runs son, daughter, brothers, uncles, next kinsman — nobody's name is to be lost.",
    '27:12': "\"Get thee up into this mount, and see the land.\" Moses is granted the sight and refused the entry.",
    '27:13': "\"Thou also shalt be gathered unto thy people, as Aaron thy brother.\" The brothers are told in the same terms.",
    '27:14': "The reason is Meribah again, named for the third time. God does not soften the charge when he announces the sentence.",
    '27:16': "Told he is about to die, Moses' first request is for a successor rather than for a reprieve.",
    '27:17': "\"As sheep which have no shepherd.\" The phrase Jesus will use of a crowd begins as Moses' fear for this one.",
    '27:18': "\"A man in whom is the spirit.\" The qualification named is not experience or descent but something given.",
    '27:20': "\"Put some of thine honour upon him.\" Some, not all. Joshua leads without being a second Moses.",
    '27:21': "Joshua must ask counsel through the priest. The new leader is given authority and a check on it in one verse.",
    '27:22': "Moses does it publicly, in front of the man who will replace him and the people who will follow him.",
    '27:23': "He lays his hands on Joshua. The succession is enacted by a touch, and the New Testament keeps the gesture.",
    # ---- Chapter 28 ----
    '28:2': "\"My offering, and my bread.\" God speaks of the sacrifices as his own portion, claimed rather than requested.",
    '28:3': "Two lambs a day, every day, for ever. The centre of Israel's worship is repetition rather than occasion.",
    '28:4': "One in the morning, one at evening. The day is bracketed by sacrifice at both ends.",
    '28:6': "\"Ordained in mount Sinai.\" A new generation is told the daily offering is not new, whatever else has changed.",
    '28:7': "Strong wine poured out in the holy place. What a man would drink is spilled on the ground instead.",
    '28:9': "The sabbath doubles the lambs. Rest from work does not mean rest from offering.",
    '28:10': "\"Beside the continual burnt offering.\" The feast is added to the daily rite, never substituted for it.",
    '28:11': "The month opens with bullocks, a ram and seven lambs. Israel's calendar is marked out by what it costs.",
    '28:15': "A sin offering every new month. The law assumes twelve fresh reckonings a year with no particular sin in view.",
    '28:16': "\"In the fourteenth day of the first month is the passover.\" Their year begins from the night they were let go.",
    '28:17': "Seven days of unleavened bread. The haste of the escape is rehearsed slowly, a week at a time.",
    '28:18': "\"Ye shall do no manner of servile work.\" The word for slave labour is the one chosen for a feast about leaving Egypt.",
    '28:19': "\"Without blemish\" attaches to every animal on the list. What is brought for God is not what could not be sold.",
    '28:22': "One goat for a sin offering at the passover feast. Even the deliverance festival admits something needs atoning.",
    '28:23': "The festival sacrifice happens after the ordinary morning one. Nothing special begins until the daily thing is done.",
    '28:26': "Firstfruits, \"after your weeks be out.\" A harvest feast dated by counting, which is what makes Pentecost a date.",
    # ---- Chapter 29 ----
    '29:1': "The seventh month opens with trumpets and no explanation. Israel is called to attention before it is told why.",
    '29:7': "\"Ye shall afflict your souls.\" The only day in the calendar whose observance is described as going without.",
    '29:11': "\"Beside the sin offering of atonement.\" Even on the day of atonement another sin offering is required alongside.",
    '29:12': "A seven-day feast in the seventh month, kept in booths by a people who have just stopped living in tents.",
    '29:13': "Thirteen bullocks on the first day. The most expensive week of the year is also the most joyful.",
    '29:17': "Twelve on the second day. The count starts going down, and the descent is the only thing that changes.",
    '29:20': "Eleven on the third. Seven days of bullocks falling by one make seventy, which is the number of the nations.",
    '29:32': "Seven bullocks on the seventh day, where the week began at thirteen. The feast winds down rather than peaking.",
    '29:35': "\"On the eighth day ye shall have a solemn assembly.\" An extra day added after the week is complete.",
    '29:36': "One bullock on the eighth day, after seventy. The year's largest feast ends with the smallest offering in it.",
    '29:39': "\"Beside your vows, and your freewill offerings.\" The fixed calendar is a floor, not a ceiling.",
    '29:40': "\"Moses told the children of Israel according to all that the LORD commanded.\" Two chapters of detail, passed on entire.",
})
