#!/usr/bin/env python3
"""Written one-line takeaways for Numbers 1-36."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The book opens in a wilderness and never really leaves it. Sinai is behind them; the land is not yet ahead.",
    '1:2': "\"The number of their names.\" Even a head count is ordered to be taken name by name rather than in bulk.",
    '1:3': "From twenty years old and able to go to war. This is a muster roll, and almost none of these men will fight for the land.",
    '1:4': "A head from every tribe stands with Moses. The count is not one man's private arithmetic.",
    '1:16': "The princes are called renowned, and within a generation most of this list has died in the sand.",
    '1:18': "\"They declared their pedigrees.\" Belonging to Israel was something a man had to be able to show.",
    '1:27': "Judah comes out the largest tribe, and Jacob's blessing over the sceptre is quietly working itself out in a ledger.",
    '1:46': "Six hundred thousand and three thousand five hundred and fifty fighting men. Remember the figure; chapter 26 counts them again.",
    '1:47': "The Levites are left off the war roll. A tribe is exempted from the army because its work is at the tent.",
    '1:50': "Their charge is to carry, pitch and take down. The tribe nearest God is the one that does the lifting.",
    '1:51': "\"The stranger that cometh nigh shall be put to death.\" Nearness to God is treated as genuinely dangerous.",
    '1:53': "The Levites camp as a cordon \"that there be no wrath.\" The reason for the arrangement is stated outright.",
    '1:54': "\"So did they.\" The last flat note of obedience before the murmuring starts.",
    # ---- Chapter 2 ----
    '2:2': "Every man by his own standard and all of them facing one tent. Order and distance are arranged in the same sentence.",
    '2:3': "Judah pitches east, where the sun comes up, and Nahshon leads. Matthew's genealogy will pick up this name.",
    '2:9': "\"These shall first set forth.\" The marching order puts the tribe of the promise at the front of the column.",
    '2:14': "Gad's prince is Eliasaph son of Reuel here and son of Deuel in chapter one. The record keeps both spellings.",
    '2:17': "The tabernacle travels in the middle of the column. God is not out front as a mascot but housed among them.",
    '2:31': "Dan brings up the rear with the second largest host. The back of the march is guarded, not left to stragglers.",
    '2:32': "The same total is reached from the camps as from the tribes. The book is willing to show its working twice.",
    '2:33': "Levi is left out of the sum a second time. The tribe that serves the tent is counted on a different page.",
    '2:34': "They pitched and they set forward exactly as commanded. This is the last chapter where that is simply true.",
}

TAKEAWAYS.update({
    # ---- Chapter 3 ----
    '3:1': "\"The generations of Aaron and Moses\" — and then only Aaron's sons are listed. The priestly line is the one being traced.",
    '3:2': "Nadab and Abihu head the list of Aaron's sons, named in their birth order before they are named among the dead.",
    '3:4': "Strange fire, no children, and the line passes to Eleazar. The priesthood's first casualties were the high priest's own sons.",
    '3:6': "Levi is brought near to serve Aaron. Even inside the tribe set apart, there are degrees of nearness.",
    '3:9': "The Levites are \"wholly given\" — Israel's gift to the priesthood before they are anything to themselves.",
    '3:12': "One tribe is taken in place of every firstborn son. Substitution is built into the shape of the camp.",
    '3:13': "God's claim on the firstborn dates from the night he spared them in Egypt. Redemption is what creates the ownership.",
    '3:15': "Levites are counted from a month old. Fighting men were counted from twenty; these belong to God before they can work.",
    '3:31': "Kohath carries the ark, the table, the lampstand and the altars. The honour and the danger are the same appointment.",
    '3:32': "Eleazar is made chief over the chiefs, and the man who will bury Aaron is already being placed.",
    '3:38': "Moses and Aaron camp at the door on the east side. The leaders are posted where the traffic is.",
    '3:39': "Twenty-two thousand Levites, against sixty thousand in Dan alone. The tribe that carries the tent is among the smallest.",
    '3:43': "Twenty-two thousand two hundred and seventy-three firstborn — two hundred and seventy-three more than there are Levites.",
    '3:47': "The surplus firstborn are redeemed at five shekels a head. Where the substitute runs out, a price is named instead.",
    # ---- Chapter 4 ----
    '4:3': "Thirty to fifty years old. The heavy service has a starting age and an end, and nobody is worked past it.",
    '4:5': "Aaron veils the ark before the carriers arrive. What they lift, they never see.",
    '4:6': "The ark alone is finished with blue on the outside. Under the badger skins, one object is marked differently.",
    '4:15': "\"They shall not touch any holy thing, lest they die.\" The privilege of carrying God's things is issued with a warning.",
    '4:16': "Eleazar's charge is oil, incense and oversight — the things that keep burning while everyone else is packing.",
    '4:19': "\"That they may live, and not die.\" The regulations are given as protection, not as obstacles to devotion.",
    '4:20': "Even a glance at the uncovered holy things is fatal. Curiosity is not treated as a small fault here.",
    '4:24': "Gershon's work is named plainly as burdens. Scripture does not pretend that service to God is weightless.",
    '4:32': "Pins and cords are reckoned by name to particular men. Nothing is so small that nobody is answerable for it.",
    '4:36': "Two thousand seven hundred and fifty Kohathites of working age out of eight thousand six hundred counted.",
    '4:49': "\"Every one according to his service, and according to his burden.\" The load is assigned man by man, not dumped on the tribe.",
})

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:2': "Leprosy, a discharge, a touched corpse. None of the three is a sin, and all three still put a man outside.",
    '5:3': "\"In the midst whereof I dwell.\" The camp's rules are strict for one reason, and it is a guest.",
    '5:4': "They put them out. The people who carried out the order were removing their own relatives.",
    '5:6': "Wronging a neighbour is charged here as \"a trespass against the LORD.\" There is no purely horizontal sin.",
    '5:7': "Confession and the principal and a fifth on top. Being forgiven is not treated as cancelling what is owed.",
    '5:8': "If the wronged man is dead with no kinsman, the debt is paid to God. It does not quietly lapse.",
    '5:10': "What a man gives the priest is the priest's. Ministers are kept by gifts rather than by charging for the holy.",
    '5:12': "The law of jealousy begins where the husband cannot know and will not stop suspecting.",
    '5:13': "\"Neither she be taken with the manner.\" The statute exists precisely where the evidence has run out.",
    '5:14': "The spirit of jealousy is described twice — once where she is guilty, once where she is not. Both cases get the same ordeal.",
    '5:15': "Barley meal, no oil, no frankincense. Everything pleasant is stripped off an offering that exists to expose.",
    '5:17': "Holy water, and dust off the tabernacle floor. The ordeal's ingredients are deliberately worth nothing.",
    '5:18': "She stands before the LORD with the offering in her hands and the priest holding the water. The case is out of her husband's hands.",
    '5:19': "The oath opens with \"be thou free\" — the priest states the innocent outcome first.",
    '5:21': "The curse is read out in full before she drinks. Nobody is condemned by terms they were not told.",
    '5:22': "\"Amen, amen.\" She is made to consent aloud to the verdict either way.",
    '5:23': "The written curses are blotted into the water she drinks. The words become the thing that enters her.",
    '5:27': "No judge rules and no witness testifies. The whole case is handed to God to decide or to drop.",
    '5:28': "The innocent woman goes home cleared and fruitful. The ordeal is built to acquit as readily as to convict.",
    '5:31': "\"The man shall be guiltless.\" The law's lopsidedness is stated flatly, and the text does not soften it.",
    # ---- Chapter 6 ----
    '6:2': "Man or woman, by their own vow. The nearest thing to priesthood open to an ordinary Israelite is voluntary.",
    '6:3': "Not only wine but vinegar, juice and raisins. The vow refuses the vine entirely rather than negotiating with it.",
    '6:4': "\"From the kernels even to the husk.\" Separation is defined so precisely that no one can argue the edges.",
    '6:5': "Uncut hair makes the vow public. A private devotion is given a form that everybody can see.",
    '6:6': "The Nazarite may go near no corpse. A layman's vow puts him under the high priest's own restriction.",
    '6:7': "He may not bury his own mother, \"because the consecration of his God is upon his head.\" The vow outranks the grave.",
    '6:9': "A man drops dead beside him and the vow is defiled. Some ruin arrives without anyone choosing it.",
    '6:11': "\"For that he sinned by the dead.\" Atonement is required even where no intention can be found.",
    '6:12': "The days already kept are lost and counted again from nothing. Past devotion buys no credit against a later failure.",
    '6:13': "The vow ends on a fixed day. Even Israel's most intense consecration was designed to be temporary.",
    '6:14': "A sin offering closes the perfect vow. A completed consecration still needs blood to end it.",
    '6:18': "The hair grown for God is cut off and burned under the peace offering. The proof of the vow goes into the fire.",
    '6:20': "\"After that the Nazarite may drink wine.\" The abstaining was a sign for a season, never a higher grade of holiness.",
    '6:21': "\"Beside that that his hand shall get.\" Above the required minimum, a man may give whatever he can.",
    '6:23': "The blessing is dictated. Aaron's sons hand over words they did not compose and cannot improve.",
    '6:24': "Bless and keep. God gives the good and then guards it, since gifts in this world do not hold themselves.",
    '6:25': "A shining face is the opposite of a turned back, and what it shines with is named: grace.",
    '6:26': "The countenance is lifted toward the people and the last word of the blessing is peace, handed over rather than achieved.",
    '6:27': "\"They shall put my name upon them, and I will bless them.\" The priest speaks; the blessing stays God's own act.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:1': "The chapter reaches back to the day the tabernacle went up. The narrative stops moving forward to record a gift.",
    '7:2': "The men who supervised the census are the first to give. Leadership here begins by opening its own hand.",
    '7:3': "Wagons and oxen. The gift for a travelling sanctuary is transport, not ornament.",
    '7:5': "\"To every man according to his service.\" What is given away is distributed by need, not split evenly.",
    '7:7': "Gershon carried curtains, so Gershon got two wagons. The lighter load draws the smaller allowance.",
    '7:8': "Merari hauled boards and sockets and received twice as many wagons. The heaviest work got the most help.",
    '7:9': "Kohath received no wagons at all, because the holiest things were carried on men's shoulders.",
    '7:10': "The altar is dedicated by gifts brought to it. Israel's first use of the altar is to give.",
    '7:11': "\"Each prince on his day.\" Twelve identical gifts are spread over twelve days so no tribe shares its moment.",
    '7:12': "Judah offers first, as Judah camps first and marches first. The order set in chapter two simply holds.",
    '7:13': "A hundred and thirty shekels of silver in one dish. The princes gave at a weight the text bothers to record.",
    '7:14': "A gold spoon of incense — ten shekels of metal holding something that will be burned away.",
    '7:16': "A sin offering is included in a gift of dedication. Even Israel's best day needs blood at the middle of it.",
    '7:17': "The peace offerings are the largest item, and peace offerings were eaten. The dedication ends in a meal.",
    '7:18': "The second day's inventory is written out in full rather than called the same as yesterday's.",
    '7:24': "A third time, item by item. The repetition is the honour: no tribe is folded into a summary.",
    '7:48': "Ephraim's day falls seventh, exactly where Ephraim's standard falls in the march. Nothing here is improvised.",
    '7:78': "The twelfth prince is given the same number of words as the first. Naphtali is not abbreviated for coming last.",
    '7:84': "Only now, after twelve days, does the text total it up. The summary existed all along and was withheld on purpose.",
    '7:86': "A hundred and twenty shekels of gold, all of it in spoons for incense. The costliest metal carries the most fleeting gift.",
    '7:87': "Twelve bullocks, twelve rams, twelve lambs, twelve goats. Every tribe brought the same, and no tribe brought more.",
    '7:88': "Twenty-four oxen and sixty each of rams, goats and lambs for peace offerings. The feast dwarfs everything burnt.",
    '7:89': "After eighty-eight verses of gifts, God speaks — from the mercy seat, between the cherubim, over the law.",
    # ---- Chapter 8 ----
    '8:2': "The lamps are set to shine over against the candlestick, so the light falls on what stands in front of it.",
    '8:3': "\"And Aaron did so.\" After what two of his sons did with fire, a plain note of obedience is worth recording.",
    '8:4': "Beaten work, after the pattern shewed. Nothing about the light in God's house was the craftsman's own idea.",
    '8:6': "\"Take the Levites and cleanse them.\" Being chosen by God did not leave them fit to come near him.",
    '8:7': "Sprinkled, shaved, washed. The cleansing is done on the body, in public, where anyone can see it happen.",
    '8:9': "The whole assembly is gathered to watch. A minister is set apart in front of the people he will serve.",
    '8:10': "Israel lays hands on the Levites the way a man lays hands on his sacrifice. The congregation is handing them over.",
    '8:11': "Aaron waves living men before the LORD as an offering. This tribe is what Israel puts on the altar.",
    '8:12': "The Levites lay their hands on bullocks in turn. The men who bear others' sin need atonement of their own.",
    '8:14': "\"The Levites shall be mine.\" Separation to God is described as God taking, never as the man volunteering.",
    '8:16': "Every household's eldest son walks free because a whole tribe stands in the place he would have filled.",
    '8:17': "The claim reaches beyond people to cattle. God's right over the firstborn was total before it was commuted.",
    '8:19': "The Levites are given \"that there be no plague\" when Israel comes near. Their office is a buffer as much as a service.",
    '8:21': "Aaron made atonement for them first. The men appointed to handle atonement did not begin by being clean.",
    '8:22': "\"And after that went the Levites in.\" Nobody in this book starts the work before the washing.",
    '8:24': "Twenty-five here, thirty in chapter four. The text leaves both ages standing, and the rabbis argued over it for centuries.",
    '8:25': "At fifty they cease. The one tribe with no land to retire to is still ordered to stop working.",
    '8:26': "The old Levites keep the charge but carry nothing. Age moves a man from labour to oversight, not out of the tent.",
})
