#!/usr/bin/env python3
"""Written takeaways for Proverbs 1-16."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "The sayings come with a name and a throne attached. This is not anonymous folk wisdom but a king's collection.",
    '1:2': "The book states its purpose before it begins, which is a way of admitting that proverbs can be misused.",
    '1:3': "Wisdom is unpacked as justice, judgment and equity — how a man deals with others, not how clever he is alone.",
    '1:4': "\"Subtilty to the simple.\" The shrewdness that makes a con man is here handed to the naive as a defence.",
    '1:5': "The wise man is the one still listening. Wisdom is measured by appetite for more of it, never by arrival.",
    '1:6': "\"Dark sayings.\" The book expects to be worked at; a proverb understood too quickly has not been understood.",
    '1:7': "Fear of the LORD is called the beginning, not a later stage — and fools are marked by contempt, not ignorance.",
    '1:8': "The mother's teaching is called law, set beside the father's. Both voices carry authority in this house.",
    '1:9': "Parental instruction is described as jewellery rather than a leash — something worn, and visible on you.",
    '1:10': "Everything turns on the one word \"consent.\" Being enticed is not the sin; agreeing is.",
    '1:11': "\"For the innocent without cause.\" The gang has no grievance to settle. Appetite is the whole motive.",
    '1:12': "They borrow the grave's own language to describe themselves, and hear nothing wrong in it.",
    '1:13': "The recruiting pitch is prosperity. Sin rarely argues morality; it presents a business plan.",
    '1:14': "\"Let us all have one purse.\" What is really being offered is belonging, with the money as the pretext.",
    '1:15': "The counsel is not to out-argue them but to keep the foot off the road. Distance does what debate will not.",
    '1:16': "Their feet \"make haste.\" Evil here is not drifted into; it is hurried toward.",
    '1:17': "A bird will not fly into a net it has watched being spread. The comparison is not flattering to the men.",
    '1:18': "The ambush they set is described as laid for themselves. The trap does not know who laid it.",
    '1:19': "Greed \"taketh away the life of the owners thereof\" — the gain ends up owning the man who chased it.",
    '1:20': "Wisdom does her crying in the street. She is not hidden in a school, and nobody can plead they never heard.",
    '1:22': "\"Love simplicity.\" The naive is not neutral or merely uninformed; he is attached to being that way.",
    '1:23': "The spirit is poured out on those who turn at reproof. The gift follows the correction, not the merit.",
    '1:24': "The charge is refusal, not ignorance. A hand was stretched out and no one looked at it.",
    '1:26': "Wisdom laughs at the calamity. Scripture lets her say it, and does not soften it into sorrow.",
    '1:27': "Desolation and whirlwind: the ruin arrives as weather does, all at once and open to no negotiation.",
    '1:28': "They seek early and do not find. The text allows for a lateness that earnestness cannot undo.",
    '1:29': "\"Did not choose the fear of the LORD.\" Fear of God is presented here as something elected or declined.",
    '1:31': "The sentence is to be fed on their own way. Judgement here is getting exactly what was wanted.",
    '1:32': "What destroys the fool is his prosperity. The hazard named is success, not hardship.",
    '1:33': "Safety is described modestly — dwelling quietly, free from dread. Not triumph; the absence of a nagging fear.",

    # ---- Chapter 2 ----
    '2:1': "The chapter is one long sentence hanging on \"if.\" Nothing is promised until the conditions have been laid out.",
    '2:2': "Inclining the ear and applying the heart: attention described as posture before it is described as thought.",
    '2:3': "Crying and lifting up the voice. Wisdom is not absorbed by proximity; it is asked for out loud.",
    '2:4': "Seeking her as for hid treasure assumes she is buried. The digging is expected, and so is the payoff.",
    '2:5': "Every condition was about seeking wisdom, and what is found is the knowledge of God. The search ends elsewhere than it began.",
    '2:6': "After all that searching, \"the LORD giveth wisdom.\" The digging turns up what was being handed out.",
    '2:7': "\"Layeth up\" — the wisdom is stored in advance for the righteous, a reserve rather than a wage paid on completion.",
    '2:8': "God keeps the paths, not only the travellers. The road itself is under guard.",
    '2:9': "Understanding arrives as righteousness and equity. In this book insight that changes no dealings is not insight.",
    '2:10': "Wisdom has to be \"pleasant unto thy soul\" to do its work. Agreement is not enough; it must be enjoyed.",
    '2:11': "Discretion preserves from the inside. The protection is a formed judgement, not a fence built around the man.",
    '2:12': "The first thing the evil man is identified by is his talk. Froward speech precedes froward deeds.",
    '2:13': "They \"leave the paths of uprightness.\" The crooked once walked straight; this is desertion, not native darkness.",
    '2:14': "The worst word in the sentence is \"rejoice.\" Evil has stopped being done and started being enjoyed.",
    '2:16': "Her weapon is named as flattery. The danger is the same as the evil man's: words that go down easily.",
    '2:17': "She forsook \"the guide of her youth\" and forgot a covenant of God. The betrayal is vertical before it is domestic.",
    '2:18': "Her house \"inclineth unto death\" — the floor is tilted. Nothing has to be decided for the slide to continue.",
    '2:19': "\"None that go unto her return again.\" The proverb states it absolutely and offers no exception to lean on.",
    '2:20': "The point of all that deliverance is positive: to walk with good men. Rescue is for company, not for solitude.",
    '2:21': "Dwelling in the land is covenant language. Wisdom is tied to Israel's inheritance, not to private success.",
    '2:22': "\"Rooted out\" — the image is agricultural. The wicked are not evicted from the land; they are pulled out of it.",

    # ---- Chapter 3 ----
    '3:1': "The commandments are kept by the heart, not stored in the memory. Retention here is a matter of affection.",
    '3:2': "The promise attached to the teaching is length of days and peace — plainly this life, plainly this world.",
    '3:3': "Mercy and truth, the pair used of God's own covenant loyalty, are bound on outwardly and written in inwardly.",
    '3:4': "Favour with God and with man together. The verse refuses to treat the two audiences as rivals.",
    '3:5': "The command is not to stop thinking but to stop leaning. Your understanding may be used; it may not be rested on.",
    '3:6': "\"He shall direct thy paths.\" The guidance is an act of God's, not a set of directions handed over in advance.",
    '3:7': "The opposite of fearing the LORD turns out to be being wise in your own eyes. Self-assessment is the rival religion.",
    '3:8': "Health to the navel and marrow to the bones. Wisdom's effect is described bodily, not spiritually.",
    '3:9': "Firstfruits. What honours God is not the amount but the order — what comes off the top before anything is kept.",
    '3:10': "Barns and bursting presses: a rule of how the world generally runs, not a lever the giver gets to pull.",
    '3:11': "Two ways to mishandle correction are named — despising it, and simply growing tired of it.",
    '3:12': "Chastening is offered as evidence of sonship rather than of anger. Hebrews takes this verse up exactly so.",
    '3:13': "\"Findeth\" and \"getteth\" stand side by side: wisdom is both stumbled on and worked for, and the book won't choose.",
    '3:14': "Wisdom is priced against silver on the market's own terms. The comparison meets the merchant where he lives.",
    '3:15': "\"All the things thou canst desire\" — the comparison is made to exhaust the list rather than top it.",
    '3:16': "Long life is in her right hand and riches in her left. Even in a verse about wealth, the days come first.",
    '3:17': "Pleasantness and peace. The wisdom being urged is nowhere described as grim, and its rewards are not deferred.",
    '3:18': "A tree of life. The tree barred at Eden's gate is here held out to anyone who will lay hold of her.",
    '3:19': "The wisdom that orders a life is the wisdom that founded the earth. It is the grain of things, not a personal knack.",
    '3:21': "\"Let not them depart from thine eyes.\" Wisdom is held by continuing to look at it, not by having once learned it.",
    '3:22': "Before it is an ornament, it is \"life unto thy soul.\" The advice is spoken of as something that animates.",
    '3:24': "Sleep is offered as the proof. What a man trusts shows most clearly in how he lies down.",
    '3:25': "The fear to be unafraid of is named as sudden. Warning is exactly what this kind of trouble does not give.",
    '3:26': "The confidence is placed in the LORD himself, not in the wisdom the chapter has just spent ten verses praising.",
    '3:27': "The good is called owed. Withholding it is not tight-fistedness but keeping back what already belongs to another.",
    '3:28': "The sin named is the delay, and what convicts is the clause \"when thou hast it by thee.\"",
    '3:29': "\"Seeing he dwelleth securely by thee.\" It is his trust in you that makes the scheming a betrayal.",
    '3:30': "Striving \"without cause\" is forbidden, which quietly concedes that there is sometimes cause.",
    '3:31': "The warning against envying the oppressor assumes that violent men often do look enviable.",
    '3:32': "Set against abomination is not reward but intimacy: \"his secret is with the righteous.\"",
    '3:33': "Curse and blessing land on houses. Consequence in this book runs through households, not just individuals.",
    '3:34': "Grace to the lowly, scorn to the scorner. Both James and Peter reach for this line when describing God's basic bent.",
    '3:35': "Shame is called the fool's promotion. He is not demoted into it; he rises, and that is the joke.",
}

TAKEAWAYS.update({
    # ---- Chapter 4 ----
    '4:1': "\"Ye children\" — the address widens from the one son. What a father says to one he says to the house.",
    '4:2': "He calls his own words doctrine and law. A parent's teaching is given the weight of torah, not of opinion.",
    '4:3': "Before he was a teacher he was somebody's tender and only beloved. The authority comes from having been taught.",
    '4:4': "David's charge to Solomon is quoted inside Solomon's charge to his son. Wisdom arrives third-hand and loses nothing.",
    '4:5': "\"Get wisdom\" — the verb is the merchant's. Wisdom is spoken of as something acquired, not as something dawning.",
    '4:6': "Forsaking and loving are the two options offered. Wisdom is treated as a person to be kept faith with.",
    '4:7': "\"With all thy getting get understanding.\" The price named is not a sum but everything else a man is acquiring.",
    '4:8': "You exalt her and she promotes you. The honour comes back, but only to the man who gave it first.",
    '4:9': "A crown is something she delivers, never something seized. Even wisdom's dignity arrives as a gift.",
    '4:11': "\"I have led thee in right paths.\" The teaching was not lecture but company along a road already walked.",
    '4:12': "The benefit shows up when running, not standing. Wisdom proves itself at speed, under pressure.",
    '4:13': "\"Take fast hold... let her not go.\" The grip has to be maintained, because the reason given is \"she is thy life.\"",
    '4:14': "The prohibition is about entering. Nothing has been done yet on that path, and that is the moment to refuse.",
    '4:15': "Avoid, pass not by, turn, pass away — four verbs for one act. The piling up is the argument.",
    '4:16': "They cannot sleep until harm is done. Mischief has stopped being chosen and become a nightly appetite.",
    '4:17': "Bread of wickedness and wine of violence: not what these men do but what they are living on.",
    '4:18': "The just path shines \"more and more.\" It is not described as bright at the start, only as brightening.",
    '4:19': "\"They know not at what they stumble.\" The worst of darkness is not the falling but never learning the cause.",
    '4:22': "The words are life \"to those that find them.\" The medicine is real, and it still has to be gone looking for.",
    '4:23': "Guard the spring, not the stream. Behaviour is treated as downstream of something that needs watching first.",
    '4:24': "A froward mouth is spoken of as a thing to be put away from you, as though speech were luggage a man carries.",
    '4:25': "The discipline is applied to the eyes. What a man permits himself to look at is treated as the decisive thing.",
    '4:26': "\"Ponder the path of thy feet.\" The call is to think about the route, not merely to be careful with the next step.",
    '4:27': "Neither to the right nor the left — Deuteronomy's phrase. Wisdom is not a balance between extremes but a road.",

    # ---- Chapter 5 ----
    '5:2': "The defence against seduction is placed in the son's own lips. What he says will decide what he does.",
    '5:3': "Honeycomb and oil. The warning opens by conceding the sweetness, because pretending otherwise persuades nobody.",
    '5:4': "Wormwood and a sword, and both are at \"her end.\" Nothing bitter is tasted on the way in.",
    '5:5': "Her feet are already going down. The man is not being tempted to stop somewhere; he is joining a descent.",
    '5:6': "\"Her ways are moveable, that thou canst not know them.\" There is no path here to ponder, and that is the danger.",
    '5:8': "Not nigh the door. The command is about where a man's feet go, which is cheaper than testing his willpower.",
    '5:9': "Honour and years, given to others. The cost is counted in reputation and time rather than in guilt.",
    '5:10': "The labour of a life ends up furnishing a stranger's house. Adultery is described as a transfer of property.",
    '5:11': "The mourning comes \"at the last,\" when the body is already spent. Regret arrives too late to be useful.",
    '5:12': "His lament is not about the woman. He traces it back to the moment he decided he did not need correction.",
    '5:13': "\"My teachers... them that instructed me.\" He had them. It was never a shortage of information.",
    '5:14': "\"In the midst of the congregation.\" The ruin happened while he was sitting among God's people every week.",
    '5:15': "Your own cistern. Faithfulness is pictured as drinking what is already yours, not as heroic self-denial.",
    '5:16': "Water scattered in the streets is water wasted. The image is of a precious thing poured where nobody owns it.",
    '5:17': "\"Only thine own.\" Exclusivity is named here as the blessing rather than as the restriction.",
    '5:18': "The alternative to adultery is not restraint but rejoicing. The remedy offered is a better pleasure.",
    '5:19': "\"Be thou ravished always with her love.\" Scripture is entirely unembarrassed about desire inside a marriage.",
    '5:20': "\"And why wilt thou?\" After all the warnings, the last appeal is to make the man explain himself.",
    '5:21': "The LORD ponders all his goings. Secrecy was the whole appeal of the thing, and it turns out not to exist.",
    '5:22': "The cords are his own sins. Nobody had to come and tie him; the habit did the binding.",
    '5:23': "He dies \"without instruction\" though he had teachers. To refuse instruction and to lack it come out the same.",

    # ---- Chapter 6 ----
    '6:1': "The danger is a handshake given for somebody else. The debt is real though the spending was not yours.",
    '6:2': "\"The words of thy mouth\" twice in one line. The snare was not sprung on him; he spoke it into existence.",
    '6:3': "\"Humble thyself.\" The escape costs pride, and the book counts that a cheap price for getting free.",
    '6:4': "No sleep until it is undone. A liability that most men would live with is treated as an emergency.",
    '6:5': "Roe and bird. He is told to see himself as prey, which is not how a man who signs a bond sees himself.",
    '6:6': "The sluggard is sent to be taught by an insect. The humiliation is part of the lesson.",
    '6:7': "No guide, overseer or ruler. What the ant lacks is exactly what the sluggard is waiting for.",
    '6:8': "Summer and harvest. She works to the season rather than to her mood, and that is the whole difference.",
    '6:9': "\"How long?\" The sluggard's fault is not an act but a duration, which is why nobody can name the day he fell.",
    '6:10': "A little, a little, a little. Ruin is spelled out in instalments small enough that none of them alarms anyone.",
    '6:11': "Poverty comes like a traveller and then like an armed man: on a schedule, and then taking what it wants.",
    '6:12': "He \"walketh with a froward mouth.\" The crooked speech is not an incident but his manner of moving through a room.",
    '6:13': "Eyes, feet, fingers. He says everything by signal, so there is nothing anyone can hold him to afterwards.",
    '6:14': "The signalling is traced back to the heart, and the product named is discord. He is manufacturing division.",
    '6:15': "\"Suddenly... suddenly... without remedy.\" The man who never spoke plainly gets a collapse with no warning either.",
    '6:16': "Six, yea seven. The old numerical formula exists to tell you the last item on the list is the one it was built for.",
    '6:17': "The list starts with a look. Pride is on the face before it ever reaches the tongue or the hands.",
    '6:18': "Heart and feet together — the thing devised inside and the speed with which the body carries it out.",
    '6:19': "Sowing discord among brethren is the seventh and the climax, set in company with murder and perjury.",
    '6:22': "Leads when walking, keeps when sleeping, talks when waking. The commandment is described as a companion, not a code.",
    '6:23': "Lamp and light. The law's work here is to show a man where he is standing, which is not the same as driving him.",
    '6:24': "All that light is aimed at one practical thing: surviving a flattering tongue.",
    '6:25': "\"In thine heart\" and \"with her eyelids.\" The transaction is complete before anybody has touched anybody.",
    '6:26': "A piece of bread against the precious life. Two prices are named, one absurdly small and one total.",
    '6:27': "The question assumes its answer. Every man who has done it believed he would be the exception.",
    '6:28': "The second question repeats the first, because men go on arguing with the first.",
    '6:29': "\"Shall not be innocent.\" That is a verdict, not a consequence. The guilt attaches at the touch.",
    '6:30': "The book concedes that a hungry thief is not despised. It is willing to weigh circumstances before it judges.",
    '6:31': "Even the pitied thief restores sevenfold. Theft is ruinous and it is payable; a price exists.",
    '6:32': "Against the thief who can repay, the adulterer is set as a man who \"destroyeth his own soul.\" No restitution is offered.",
    '6:33': "The wound heals. \"His reproach shall not be wiped away\" — what lasts is not the injury but the record of it.",
    '6:34': "Jealousy is called rage, not grievance. The husband is not described as a legal process to be managed.",
    '6:35': "No ransom, no gift. In a book that prices everything, this is the one door money does not open.",
})

TAKEAWAYS.update({
    # ---- Chapter 7 ----
    '7:2': "\"As the apple of thine eye\" — guarded the way a man guards his eyesight, by reflex rather than by decision.",
    '7:3': "Bound on the fingers, where a working man keeps seeing them. The law is put where the hands can be watched.",
    '7:4': "Call wisdom sister. Against a seductress the counter offered is kinship — a woman a man cannot think of that way.",
    '7:6': "The father teaches by telling what he watched from a window. The warning comes as a case, not as a rule.",
    '7:7': "\"Among the simple ones.\" He was not singular. The young man in this story is the ordinary one in the crowd.",
    '7:8': "He takes the route that passes her corner. Nothing has happened yet and everything has been settled.",
    '7:9': "Twilight, evening, black night — the hour is given three times, which is how long he stayed out there.",
    '7:10': "The attire is obvious, the heart is subtil. What he can see about her is not the part that catches him.",
    '7:11': "Loud, stubborn, never at home. She is described by restlessness before she is described by immorality.",
    '7:12': "\"Lieth in wait at every corner.\" He thought he was wandering. He was being hunted.",
    '7:13': "The impudent face is part of the method. There is no shame to be got past, so nothing slows the thing down.",
    '7:14': "She opens with religion — offerings made, vows paid. Piety is the first tool she reaches for.",
    '7:15': "\"I have found thee.\" She makes him feel chosen, which is the flattery under all the other flattery.",
    '7:16': "Tapestry and fine linen of Egypt. The pitch is imported luxury, a world he could not otherwise enter.",
    '7:17': "Myrrh, aloes and cinnamon — the spices of worship and of burial, sprinkled on a bed.",
    '7:18': "\"Until the morning.\" The offer states its own expiry out loud, and he does not hear it.",
    '7:19': "The husband enters the story only as an absence, and only because she needs him for the argument.",
    '7:20': "\"The day appointed.\" She has consulted the calendar. Nothing about this evening was impulsive.",
    '7:21': "\"With the flattering of her lips she forced him.\" The verse calls persuasion force and does not soften it.",
    '7:22': "An ox to the slaughter goes quietly. What is missing from the description is any struggle at all.",
    '7:23': "\"Knoweth not that it is for his life.\" Ignorance kills him here, not defiance.",
    '7:25': "The heart declines first. By the time the feet go astray the decision is old news.",
    '7:26': "\"Many strong men have been slain by her.\" The casualty list is made of capable people, which is the warning.",
    '7:27': "Her house is called a way rather than a place. Nobody intends to arrive where it goes.",

    # ---- Chapter 8 ----
    '8:1': "\"Doth not wisdom cry?\" Set against the whisper on the dark corner, the question is unanswerable.",
    '8:2': "She stands where the paths meet. Wisdom takes up her position at the point where a choice is actually made.",
    '8:3': "The gates and the city entrance — the most public ground there is, and the exact opposite of the last chapter.",
    '8:4': "\"Unto you, O men.\" The address stops being a father's to a son and becomes an offer to everybody.",
    '8:5': "She calls fools to become understanding. The address assumes a man is not stuck with what he currently is.",
    '8:6': "She warrants her content before delivering it — excellent things, right things. Wisdom expects to be assessed.",
    '8:7': "Not only does she speak truth; wickedness is \"an abomination to my lips.\" She claims a distaste, not just a policy.",
    '8:8': "\"Nothing froward or perverse in them\" — the exact opposite of the man in chapter six who spoke with his fingers.",
    '8:9': "Plain \"to him that understandeth.\" The clarity depends on the hearer, which is an uncomfortable thing to be told.",
    '8:10': "Instruction and silver are set as alternatives, not as a ranking. The verse assumes you cannot chase both.",
    '8:12': "She keeps company with prudence and with witty inventions. Practical ingenuity is counted in, not looked down on.",
    '8:13': "The fear of the LORD is given content: it is hating evil. And the first evil listed is pride.",
    '8:14': "\"I have strength.\" Wisdom claims power here, not merely good advice to be taken or left.",
    '8:15': "\"By me kings reign.\" A ruler's legitimacy is tied to something he does not control, which is a claim on him.",
    '8:16': "The judges of the earth, not just of Israel. The claim is made over governments that never heard of her.",
    '8:17': "\"Those that seek me early shall find me\" — the same word that in chapter one came too late to help anybody.",
    '8:18': "\"Durable\" is the working word. And righteousness is listed among the riches rather than against them.",
    '8:19': "Fruit and revenue in one breath. She speaks the language of the field and of the counting-house at once.",
    '8:20': "She leads in the way of righteousness. The profit and the path are not two things to be balanced.",
    '8:21': "The treasures are filled for \"those that love me.\" Wisdom is inherited by affection, not extracted by technique.",
    '8:22': "\"The LORD possessed me in the beginning of his way.\" The church fought a century over whether that word means made.",
    '8:23': "\"From everlasting... or ever the earth was.\" Wisdom's credential is offered as sheer antiquity.",
    '8:24': "\"I was brought forth\" — the language is birth rather than manufacture, and the poem keeps choosing it.",
    '8:25': "Before the mountains were settled. The oldest, most permanent things a man can point at are junior to her.",
    '8:26': "\"The highest part of the dust of the world.\" After the heavens and the deeps, the poem stoops to name dirt.",
    '8:27': "\"When he set a compass upon the face of the depth\" — creation as draughtsmanship, and she watched it drawn.",
    '8:29': "The sea is given a decree it cannot pass. Even the least governable thing in the world is under a word.",
    '8:30': "\"Daily his delight, rejoicing always.\" The making of the world is described as play, not as labour.",
    '8:31': "After the depths and the heavens, her delights land on the sons of men. The cosmic poem ends up at people.",
    '8:32': "After all that height, the ask is small: keep her ways. Nothing exotic is required of the people addressed.",
    '8:33': "\"Refuse it not.\" The one thing forbidden is stated as a refusal, which is the only move a hearer really has.",
    '8:34': "Watching daily at the gates, waiting at the posts. The posture is a servant's, or a suitor's — outside the door.",
    '8:35': "Life is what is found, and favour is what is obtained. Neither verb is one a man does to earn something.",
    '8:36': "\"All they that hate me love death.\" Indifference to wisdom is not neutrality; it is named as an affair.",

    # ---- Chapter 9 ----
    '9:1': "Wisdom builds and hews before she invites. Her house exists; Folly, later in the chapter, only sits in a doorway.",
    '9:2': "Beasts killed, wine mingled, table furnished. Everything was ready before a single guest was asked.",
    '9:3': "Maidens sent out and a cry from the highest places. The invitation is delegated and it is loud.",
    '9:4': "The invitation is addressed to the simple. The least qualified people in the city are the ones named.",
    '9:5': "\"Come, eat of my bread.\" Wisdom is not transmitted as information here but taken as a meal.",
    '9:6': "\"Forsake the foolish, and live.\" What has to be left is company, which is harder than leaving habits.",
    '9:7': "The man who corrects a scorner gets hurt for it. The book says so plainly instead of commending the attempt.",
    '9:8': "How a man takes a rebuke is offered as the whole diagnostic. Nothing else in the chapter sorts people so fast.",
    '9:9': "Instruction multiplies what is already there. Teaching is described as compounding, which explains the gap.",
    '9:10': "The book's opening line returns with wisdom in place of knowledge, and adds \"the knowledge of the holy.\"",
    '9:11': "Wisdom herself makes the promise of long life. It is not a reward arranged by a third party.",
    '9:12': "\"Thou alone shalt bear it.\" Neither the profit nor the loss can be transferred to anyone else.",
    '9:13': "Clamorous, simple, knowing nothing. Folly is loud in exact proportion to how little she has to say.",
    '9:14': "She sits at her door in the same high places. Folly counterfeits wisdom's address without having built anything.",
    '9:15': "She calls to people \"who go right on their ways.\" Her targets are chosen from among those already headed somewhere.",
    '9:16': "Her invitation is word for word wisdom's. Listening to the wording will not tell anyone which door he is at.",
    '9:17': "She does not deny that the waters are stolen. She sells the theft itself as the flavour.",
    '9:18': "The dead are already in the room. Nobody mentioned them, and the guest is not told who else accepted.",
})

TAKEAWAYS.update({
    # ---- Chapter 10 ----
    '10:1': "Gladness to a father, heaviness to a mother. The same son is felt differently in the two halves of the house.",
    '10:2': "Not that the treasures are not real — only that they \"profit nothing\" at the one point where profit is wanted.",
    '10:3': "The promise is that the righteous will not famish. It is a floor under a man, not a ceiling raised over him.",
    '10:4': "Poverty is traced to a hand. This book's usual case is not fate or injustice but what a man did all week.",
    '10:5': "The fault is timing. He is not called lazy for sleeping but for sleeping in harvest, the one month it costs.",
    '10:6': "Blessings worn on the head, violence stopping the mouth. Each man ends up wearing what he has dealt in.",
    '10:7': "Reputation keeps moving after death — one name blessed, the other rotting. Neither is finished when the man is.",
    '10:8': "Receiving commandments is set against prating. The fool's problem is not that he disagrees but that he is talking.",
    '10:9': "\"He that perverteth his ways shall be known.\" The crooked man's exposure is treated as a matter of time.",
    '10:10': "The wink does its harm without a word anyone can quote back at him.",
    '10:11': "\"A well of life\" — a righteous man's speech is described as a public utility that others come and draw from.",
    '10:12': "\"Love covereth all sins\" — Peter quotes it. Covering here is not hiding the wrong but declining to publish it.",
    '10:13': "The rod is for a back, not a mind. What cannot be got in through words is not therefore left untaught.",
    '10:14': "The wise lay knowledge up against a day. The fool's mouth spends the whole store the moment he has it.",
    '10:15': "Stated flatly and without moral comment: money really does protect. Proverbs is honest about that before it is critical.",
    '10:16': "The wicked man's fruit \"tendeth to sin.\" His gain does not sit still; it compounds into more of what ruined him.",
    '10:17': "The man who keeps instruction is himself \"in the way\" — he becomes a road that other people can walk on.",
    '10:18': "Hidden hatred and open slander are both called folly. Keeping it in does not make the quieter man the better one.",
    '10:19': "Simple arithmetic: more words, more sin. Restraint is offered as a technique, not as a temperament.",
    '10:20': "The tongue is priced as silver and the heart as worthless. Speech is being valued by what stands behind it.",
    '10:21': "The righteous feed many while fools die of what they lack. One mouth is a supply, the other a hunger.",
    '10:22': "The weight is on the second clause. What marks God's giving is not the size of it but the absence of the usual price.",
    '10:23': "\"As sport.\" The fool is not driven into mischief by need or pressure. He is entertained by it.",
    '10:24': "Each man is granted his inner life — the wicked his dread, the righteous his desire. Both get what they carried.",
    '10:25': "The whirlwind does not sort anybody. What differs between the two men is only what they are founded on.",
    '10:26': "Vinegar and smoke. The sluggard is described from the employer's side, as an irritation rather than a tragedy.",
    '10:27': "Fear of the LORD is given a plain measurable effect, and the shortening of the wicked is the same sum reversed.",
    '10:28': "The wicked had expectations too. That is the sting of the verse — not that he hoped for nothing.",
    '10:29': "One and the same \"way of the LORD\" is strength to the upright and destruction to the rest. The road does not change.",
    '10:31': "\"The froward tongue shall be cut out.\" The judgement is aimed at the organ that did the work.",
    '10:32': "Knowing \"what is acceptable\" is a sense of fit, not only of right. The righteous man is being credited with tact.",

    # ---- Chapter 11 ----
    '11:1': "A merchant's scale is made the object of God's delight or disgust. Worship and weights in the same sentence.",
    '11:2': "\"When pride cometh, then cometh shame.\" No interval is allowed between them; they travel as one arrival.",
    '11:3': "Integrity is said to guide. Honesty is treated as an instrument for finding the way, not merely as a fence.",
    '11:4': "Riches are not called worthless, only useless on one particular day. The verse names the day.",
    '11:5': "\"The wicked shall fall by his own wickedness.\" No executioner is needed; the thing is self-administering.",
    '11:6': "\"Taken in their own naughtiness\" — the language of a trap, sprung on the men who built it.",
    '11:7': "What dies with him is his expectation. The thing he was living toward turns out to have been perishable.",
    '11:8': "\"The wicked cometh in his stead.\" A substitution is stated and never explained, and the book leaves it there.",
    '11:9': "The hypocrite works by mouth and the just is delivered by knowledge. Against talk, the defence is knowing things.",
    '11:10': "A whole city's mood is said to rise and fall with who is prospering in it. Righteousness is treated as public weather.",
    '11:11': "A city is exalted by blessing and overthrown \"by the mouth\" — a town can be lost through what is said in it.",
    '11:12': "Set against despising a neighbour is not praising him but holding your peace. Silence is what love does here.",
    '11:13': "Faithfulness is defined by what a man does not repeat. It is measured in the conversations that never happen.",
    '11:14': "The book that praises the wise man also distrusts one man's judgement, and says so without embarrassment.",
    '11:15': "\"He that hateth suretiship is sure.\" A settled aversion is recommended in place of judging each case on merit.",
    '11:16': "Honour is retained by grace and riches by strength. Two different currencies, and the verse declines to rank them.",
    '11:17': "Mercy and cruelty are both described as landing first on the man himself, before they reach anyone else.",
    '11:18': "\"A deceitful work.\" The wicked man's wages are not merely lost; they lie to him while he is earning them.",
    '11:19': "He pursues evil and what he overtakes is his own death. The chase is real; the quarry is not what he thought.",
    '11:20': "Abomination and delight are set on hearts, not on deeds. God is described as reacting to a shape, not a tally.",
    '11:21': "\"Though hand join in hand.\" Numbers are specifically ruled out as a defence; conspiracy changes nothing.",
    '11:22': "The gold is still gold. Beauty is not denied in this insult — it is placed where it cannot do anything but glint.",
    '11:23': "The righteous desires and the wicked expects, and wrath is what arrives. It is the expecting that makes it bitter.",
    '11:24': "Scattering increases and hoarding impoverishes. And \"more than is meet\" concedes that some withholding is right.",
    '11:25': "\"He that watereth shall be watered.\" The return comes back in the same currency it went out in.",
    '11:26': "Withholding corn earns a public curse. The grain market is treated as a moral arena, not a private calculation.",
    '11:27': "The seeking is what procures. A man looking for good finds favour as a by-product of the looking.",
    '11:28': "Trusting riches against flourishing as a branch. A branch is green precisely because it holds nothing up itself.",
    '11:29': "\"Inherit the wind.\" A man who wrecks his own household ends up owning something he cannot put his hands on.",
    '11:30': "\"He that winneth souls is wise.\" Wisdom is finally measured by its effect on other people, not by its possession.",
    '11:31': "The argument runs from the righteous being recompensed here on earth, not around it. Peter uses the verse that way.",

    # ---- Chapter 12 ----
    '12:1': "Hating reproof is called brutish — the word for an animal. Refusing correction is placed below reasoning, not against it.",
    '12:2': "Condemnation falls on \"wicked devices\" — on the plans, which is earlier than most men expect to be judged.",
    '12:3': "The wicked is established and the righteous is rooted. One is built up from outside, the other holds from below.",
    '12:4': "A crown is worn where everyone sees it; rottenness works in the bones. The two harms run on different timescales.",
    '12:5': "The comparison is made at the level of thoughts. Righteousness is traced back behind the words to the counsel.",
    '12:6': "Words that \"lie in wait for blood\" and a mouth that delivers. Both murder and rescue are done here by talking.",
    '12:7': "\"Overthrown, and are not.\" The wicked do not decline gradually; what is contrasted is a house that stays standing.",
    '12:8': "Commendation eventually tracks wisdom. Reputation is not reliable quickly, but the verse says it settles honestly.",
    '12:9': "Better despised with a servant than honoured with no bread. Keeping up appearances is priced here in food.",
    '12:10': "How a man treats his animals is made a moral index. And the wicked are cruel at the exact point they mean to be kind.",
    '12:11': "The alternative to tilling your land is not rest but company — \"vain persons.\" Idleness comes with people attached.",
    '12:12': "He desires the net. What the wicked envies is not the plunder but the apparatus that other men use to take it.",
    '12:13': "The just \"come out of trouble\" rather than avoid it. Deliverance here is an exit, not an exemption.",
    '12:14': "The fruit of the mouth is set beside the work of the hands, as though talk were a trade a man is paid for.",
    '12:15': "\"Right in his own eyes.\" The fool is not defined by being wrong but by being satisfied with his own verdict.",
    '12:16': "The fault named is speed — his wrath is \"presently known.\" The anger itself is not what separates him from the prudent.",
    '12:17': "Telling the truth is called shewing forth righteousness. Testimony is treated as an act of justice, not of candour.",
    '12:18': "Piercings of a sword against a tongue that heals. Both are precise instruments; the difference is what they are for.",
    '12:19': "The trouble with a lie is its duration. The verse concedes it works, and dates it at a moment.",
    '12:20': "Joy is attached to the counsellors of peace. Peacemaking is paid, and the payment is described as internal.",
    '12:21': "\"There shall no evil happen to the just.\" It is stated bare, with no qualification, and the book lets it stand.",
    '12:22': "Truth is something a man deals in, like goods. It is an action here before it is a property of a sentence.",
    '12:23': "The prudent conceals what he knows. Knowing when not to display knowledge is counted as part of having it.",
    '12:24': "Diligence ends in ruling and slackness in tribute. Ordinary work is what quietly decides who gives the orders.",
    '12:25': "The cure for a stooping heart is a good word — somebody else's sentence, which the man cannot supply himself.",
    '12:26': "\"The way of the wicked seduceth them.\" They are described as taken in by their own road rather than as choosing it.",
    '12:27': "He does not even cook what he caught. Laziness is shown wasting the one thing that came to the man for free.",
    '12:28': "\"In the pathway thereof there is no death.\" The boldest line in the chapter, and the only one that outruns this life.",
})

TAKEAWAYS.update({
    # ---- Chapter 13 ----
    '13:1': "The wise son hears instruction; the scorner does not even hear rebuke. Raising the volume reaches him no better.",
    '13:2': "What a man says is a crop he has to eat. The transgressor's own harvest is described as violence.",
    '13:3': "Keeping the mouth and keeping the life are the same verb. Guarding one is stated as guarding the other.",
    '13:4': "The sluggard desires. Appetite is not the difference between him and the diligent man, and the verse says so first.",
    '13:5': "The righteous hates lying, and the wicked becomes loathsome. One is a choice, the other is what a man ends up smelling of.",
    '13:6': "Righteousness keeps a man \"in the way\" — it guards someone already walking rather than fetching him from elsewhere.",
    '13:7': "Both frauds get named: the man performing wealth and the man performing poverty. Neither is left as the honest one.",
    '13:8': "Riches ransom a life, but nobody bothers threatening a man with nothing. Poverty's one advantage, stated coldly.",
    '13:9': "One light rejoices and one lamp is put out. Neither man's light is his own doing; only one of them keeps burning.",
    '13:10': "\"Only by pride.\" One cause is named for every quarrel there is, which leaves nothing to blame on the other party.",
    '13:11': "Wealth is sorted by how it arrived, not by how much of it there is. Vanity shrinks and labour compounds.",
    '13:12': "Hope deferred is described as an illness. The book grants that waiting does real damage rather than building character.",
    '13:13': "\"He that feareth the commandment.\" Fear here is directed at a word, which the verse treats as an attainable posture.",
    '13:14': "A fountain keeps giving. And its stated purpose is evasive: to get a man away from snares he would otherwise walk into.",
    '13:15': "\"The way of transgressors is hard.\" Not punished — hard. The road itself is rough, before anyone judges anything.",
    '13:16': "The fool \"layeth open\" his folly. He is not caught out; display is his method, and he thinks it is candour.",
    '13:17': "A messenger's faithfulness is health to the man who sent him. Whoever delegates is exposed to another man's character.",
    '13:18': "Refusing instruction costs poverty and shame together. The price is charged to the purse as well as to the face.",
    '13:19': "The halves do not match, and that is the point: fools will not hand back what they want, even for the sweetness offered.",
    '13:20': "Wisdom passes by proximity. A man is shaped by his company without anybody in it intending to teach him.",
    '13:21': "\"Evil pursueth sinners.\" It hunts them. They are not standing still waiting for consequences to catch up.",
    '13:22': "The sinner's wealth is \"laid up for the just.\" He has been working as a custodian and was never told.",
    '13:23': "The poor man's field produces plenty. What destroys is want of judgment — a failure in the court, not in the furrow.",
    '13:24': "The rod and love are identified with each other, and \"betimes\" makes promptness part of the loving.",
    '13:25': "The difference is not the size of the meal but where a man stops. One eats to satisfying; the other's belly still wants.",

    # ---- Chapter 14 ----
    '14:1': "She plucks it down \"with her hands.\" The house is not lost through neglect; the demolition takes effort.",
    '14:2': "Walking uprightly is simply called fearing the LORD. The inward thing is read straight off the outward one.",
    '14:3': "\"A rod of pride\" in his own mouth. What beats the fool is the stick he has been carrying between his teeth.",
    '14:4': "A clean stable means an empty one. Mess is named as the cost of anything that actually produces.",
    '14:5': "The second half is a tautology on purpose: character decides testimony, which is why an oath settles nothing.",
    '14:6': "The scorner does seek wisdom and does not find it. Seeking is not enough when the posture is wrong.",
    '14:7': "The counsel is to leave. No argument is offered, no correction attempted — just get out of the room.",
    '14:8': "The prudent man's wisdom is to understand \"his way\" — his own. Set against it is deceit, which starts with the self.",
    '14:9': "Fools mock at sin. Comedy is the defence, because a joke about a thing need never be answered.",
    '14:10': "\"A stranger doth not intermeddle with his joy.\" The loneliness of the inner life is stated, and no remedy follows.",
    '14:11': "The wicked have a house and the upright a tent, and it is the permanent structure that comes down.",
    '14:12': "\"Seemeth right.\" The danger is not a road that looks wrong but one that passes every test a man knows to run.",
    '14:13': "Laughter with sorrow inside it. The book allows that cheerfulness is sometimes the surface of something else.",
    '14:14': "Both men are filled from themselves. The backslider is not punished with something foreign; he gets his own contents.",
    '14:15': "\"The simple believeth every word.\" Credulity, not ignorance, is what the book keeps meaning by simplicity.",
    '14:16': "The wise man is the one who is afraid, and the fool is the confident one. The usual valuation is reversed.",
    '14:17': "Quick temper is called foolish and scheming is called hated. One makes a man ridiculous, the other makes him despised.",
    '14:18': "Folly is inherited rather than committed here — received like an estate nobody chose to be left.",
    '14:19': "The bowing happens \"at the gates of the righteous.\" The reversal is placed on the good man's own doorstep.",
    '14:20': "Hated even by his own neighbour. The verse reports how poverty is actually treated before anyone says it is wrong.",
    '14:21': "The correction to the previous line arrives immediately: despising a neighbour is not sociology but sin.",
    '14:22': "Both parties devise. The difference is not that one plans and the other drifts, but what the planning is for.",
    '14:23': "\"In all labour there is profit.\" The thing set against work is not rest but talk about work.",
    '14:24': "The wise man's riches are called a crown; the fool has nothing to show but more of what he already was.",
    '14:25': "\"A true witness delivereth souls.\" Lives turn on what is said in court, which makes testimony a rescue operation.",
    '14:26': "The fear belongs to one man and the refuge extends to his children. Something is being sheltered forward a generation.",
    '14:27': "The phrase used of the wise man's teaching is here given to the fear of the LORD. The fountain has moved upstream.",
    '14:28': "A king's honour is counted in people. Greatness is measured by how many are there, not by what was conquered.",
    '14:29': "Slowness to anger is called great understanding. Patience is filed under intelligence rather than under temperament.",
    '14:30': "Envy is described as a disease working in the bones — not a feeling about someone else but damage to the envier.",
    '14:31': "The insult passes through the poor man and lands on his Maker, who is also the oppressor's. Both were made.",
    '14:32': "\"The righteous hath hope in his death.\" Hope is located at the one point where the book's usual promises run out.",
    '14:33': "Wisdom rests quietly in the wise; in fools it \"is made known.\" You can hear which man has less of it.",
    '14:34': "The book steps up from the household to the nation, and keeps the same measure for both.",
    '14:35': "A king's favour follows usefulness. Royal service is described without any sentiment about loyalty.",
})
