#!/usr/bin/env python3
"""Written takeaways for Psalms 1-56."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Walking, standing, sitting — the drift into wickedness is gradual, and it ends with you settled there.",
    '1:2': "Delight comes before meditation. The law is not a task he completes but a thing he cannot leave alone.",
    '1:3': "The tree is planted, not self-grown, and its fruit comes in its season rather than on demand.",
    '1:4': "Chaff has no root and no weight. The wicked are not described as strong and wrong, but as insubstantial.",
    '1:5': "The word is \"stand.\" The question at the judgment is not whether they appear but whether they can remain.",
    '1:6': "The two ways differ because the LORD knows one of them. Being known is what makes the way survive.",

    # ---- Chapter 2 ----
    '2:1': "The rage is real and the plan is empty. Scripture grants the fury and denies it any substance.",
    '2:2': "The nations' quarrel with the anointed king is named as a quarrel with the LORD himself.",
    '2:3': "God's rule is felt as rope. What the psalm calls government, the rebels call bondage.",
    '2:4': "Heaven's response to a coup is laughter. The threat is not met with alarm because it is not one.",
    '2:5': "The laughter is not the end of it. Derision gives way to speech, and the speech is wrath.",
    '2:6': "\"Yet have I set my king.\" One word overturns all the plotting: the appointment is already made.",
    '2:7': "\"Thou art my Son\" is a decree, not an observation. The king's status rests on what God has said of him.",
    '2:8': "The nations are given, not conquered. Even the Son's inheritance comes by asking the Father.",
    '2:9': "A potter's vessel does not survive being struck. The picture is of resistance that cannot be repaired.",
    '2:10': "The judges of the earth are told to be instructed. Wisdom for rulers begins in being taught, not consulted.",
    '2:11': "Fear and rejoicing are commanded in one breath. Neither one cancels the other in God's presence.",
    '2:12': "The psalm of raging kings ends by blessing everyone who takes refuge — including, by implication, them.",

    # ---- Chapter 3 ----
    '3:1': "The prayer opens by counting enemies out loud. David tells God the number before he asks for anything.",
    '3:2': "The cruelest taunt is theological: they do not say he will lose, they say God will not help him.",
    '3:3': "\"The lifter up of mine head\" — God is not only defence but the restorer of a face bowed in shame.",
    '3:4': "He cried with his voice and was heard from the holy hill, though he was far from it and in flight.",
    '3:5': "The evidence that God sustained him is simply that he slept and woke. Ordinary rest is counted as rescue.",
    '3:6': "Ten thousands round about, and the fear is gone. The numbers did not change; the reckoning did.",
    '3:7': "The enemies are already struck in the past tense inside a prayer still asking for help.",
    '3:8': "\"Salvation belongeth unto the LORD.\" It is his property, which is why it can be given away.",

    # ---- Chapter 4 ----
    '4:1': "\"Thou hast enlarged me when I was in distress\" — the room was made inside the trouble, not after it.",
    '4:2': "The complaint is not that they hurt him but that they love vanity. He grieves their choice, not only his loss.",
    '4:3': "The setting apart is God's act and the ground of the confidence that he hears at all.",
    '4:4': "Anger is not forbidden; it is sent to bed to think. Stillness is prescribed as the cure for sinning in it.",
    '4:5': "Sacrifice and trust are joined. Offering without reliance is the thing the prophets would later call empty.",
    '4:6': "\"Who will shew us any good?\" is the age's real question, and the answer asked for is a face, not a harvest.",
    '4:7': "Gladness given directly outweighs gladness that arrives with corn and wine. The comparison is deliberate.",
    '4:8': "Peace and sleep are named as the proof. Safety is measured by whether a man can stop keeping watch.",

    # ---- Chapter 5 ----
    '5:1': "He asks God to consider his meditation — the part of prayer that never became words.",
    '5:2': "He addresses God as King before making any request, which settles who is petitioning whom.",
    '5:3': "\"In the morning\" twice, and then \"will look up.\" Prayer is directed and then watched for an answer.",
    '5:4': "God's hatred of evil is stated as incompatibility, not temper. Wickedness cannot lodge where he is.",
    '5:5': "\"Thou hatest all workers of iniquity.\" The psalm refuses the comfortable split between sin and sinner.",
    '5:6': "Lying speech and bloodshed are listed together, as though words were already the first violence.",
    '5:7': "\"But as for me\" — entry into the house is by the multitude of God's mercy, not by belonging to a better class.",
    '5:8': "He asks for a straight path \"because of mine enemies.\" Being watched by opponents is a reason to walk carefully.",
    '5:9': "Throat, tongue, inward part — the anatomy of deceit runs from the heart outward, and flattery is its polished end.",
    '5:10': "The curse asked for is that their own counsels bring them down. Judgement here is being handed one's own plan.",
    '5:11': "The joy of the protected is loud and permanent, and its reason is given as God's defending, not their courage.",
    '5:12': "Favour surrounds like a shield — not held in front but closed all the way around.",

    # ---- Chapter 6 ----
    '6:1': "He does not ask to escape correction, only that it not come in anger. The request is about the spirit of it.",
    '6:2': "\"I am weak\" is offered as the reason for mercy. Weakness is the argument, not the obstacle.",
    '6:3': "\"How long?\" The sentence breaks off unfinished, which is exactly what long suffering does to speech.",
    '6:4': "\"For thy mercies' sake\" — he gives God a reason to save him, and it is nothing about himself.",
    '6:5': "The plea is that God would lose a worshipper. Grief argues by whatever it can reach.",
    '6:6': "Tears are described in flood language. The psalter lets a man exaggerate his sorrow out loud before God.",
    '6:7': "Grief is said to age the eye. The body keeps the account of what the heart has carried.",
    '6:8': "The turn comes mid-psalm with no change in circumstances reported — only \"the LORD hath heard.\"",
    '6:9': "He says it twice, heard and received, as though certainty needed repeating to be believed.",
    '6:10': "The enemies are wished the same vexation he has just described in himself.",

    # ---- Chapter 7 ----
    '7:1': "Trust is stated first and the request second. The refuge is claimed before the rescue arrives.",
    '7:2': "The danger is put as a lion tearing with no one to deliver — a picture of being entirely alone with it.",
    '7:3': "He opens his own case to examination rather than assuming his innocence is obvious.",
    '7:4': "The defence offered is that he spared a man who had no claim on his mercy.",
    '7:5': "He invites the worst if he is guilty. An oath like this is how a man with nothing to hide talks.",
    '7:6': "\"Awake for me\" — the prayer accuses God of sleeping, and the psalter keeps the accusation in.",
    '7:7': "He asks for vindication with the congregation watching, for their sake as much as his own.",
    '7:8': "\"Judge me according to my righteousness\" is a plea about one dispute, not a claim to be sinless before God.",
    '7:9': "God tries hearts and reins — the case is settled at a depth no human court can reach.",
    '7:10': "Defence is located in God and aimed at the upright in heart, not the strong in arm.",
    '7:11': "Anger every day, at the same time as the righteous are judged. God's displeasure is steady, not episodic.",
    '7:12': "\"If he turn not\" — the whetted sword waits on repentance. The weapon is drawn and still conditional.",
    '7:13': "The instruments of death are described as prepared, aimed and held. Judgement is not improvised.",
    '7:14': "Mischief is conceived and carried like a pregnancy. Evil takes time and nurture before it is born.",
    '7:15': "The pit was dug carefully by the man who fell into it.",
    '7:16': "Violence returns on the head that devised it. The psalm treats this as a law, not a wish.",
    '7:17': "The psalm that began in terror ends in praise of God's righteousness — the very thing it appealed to.",

    # ---- Chapter 8 ----
    '8:1': "The name is excellent in all the earth while the glory is set above the heavens. Both reach further than Israel.",
    '8:2': "Strength is ordained out of infant mouths. God silences his enemies with what looks least like power.",
    '8:3': "\"The work of thy fingers\" — the heavens are handiwork, not rivals, and the word chosen makes them small.",
    '8:4': "The question is asked from under a night sky, where man's size is the obvious fact and God's attention is not.",
    '8:5': "Lower than the angels and crowned at the same time. Humanity's rank is a gift, not a measurement.",
    '8:6': "Dominion is given over what God made. Every authority man holds is held on loan from the owner.",
    '8:8': "The list reaches the fish and the paths of the seas — the parts of creation man could least control.",
    '8:9': "The psalm closes exactly where it opened. Everything between has been argument for that one sentence.",

    # ---- Chapter 9 ----
    '9:1': "Whole-hearted praise is paired with showing forth the works. Gratitude here has an audience.",
    '9:2': "Gladness is directed at God himself, not at the outcome. \"I will be glad in thee\" is the whole clause.",
    '9:3': "The enemies fall at his presence rather than at David's counterattack.",
    '9:4': "The throne is described as a place where cases get heard. God's kingship is first of all a judgeship.",
    '9:5': "Blotting out the name is the ancient shape of final judgement — not only defeat but erasure.",
    '9:6': "The taunt is turned back: the destroyer's own cities are the ones with no memorial left.",
    '9:7': "\"But the LORD shall endure for ever\" — the contrast is not strength against strength but permanence against ruin.",
    '9:8': "World-wide judgement in righteousness is offered as good news, because impartiality is what the oppressed lack.",
    '9:9': "Refuge is named twice in one verse, and both times it is for people who have no other.",
    '9:10': "Trust follows from knowing the name. Confidence rests on character already disclosed, not on nerve.",
    '9:11': "Praise inside Zion and declaration among the peoples belong together. Worship was never meant to stay indoors.",
    '9:12': "The God who investigates bloodshed is the same one who does not forget the cry of the humble.",
    '9:13': "\"The gates of death\" — he is already at the threshold and describes God as the one lifting him back from it.",
    '9:14': "He asks for rescue in order to have somewhere to tell about it.",
    '9:15': "Their own net takes their own foot. The trap was well made; that was the problem.",
    '9:16': "God is made known by what he does, not by explanation. Judgement is one of the ways he is recognised.",
    '9:17': "The nations that forget God are set beside the wicked, as though forgetting were itself the wickedness.",
    '9:18': "\"Not alway\" and \"not for ever\" — the psalm concedes the delay while denying it the last word.",
    '9:19': "\"Let not man prevail\" is the whole fear underneath the psalm, said plainly at last.",
    '9:20': "The judgement asked for is that the nations learn they are men. Knowing your own creaturehood is the mercy here.",

    # ---- Chapter 10 ----
    '10:1': "The complaint is not that God is absent but that he is standing off and watching. Distance is worse than absence.",
    '10:2': "The prayer asks that the schemer be taken in his own device, before asking for the poor to be rescued.",
    '10:3': "He boasts of his appetite and praises greed in others. Wickedness here is not hidden but celebrated.",
    '10:4': "\"God is not in all his thoughts.\" Pride's real work is not denial of God but successful inattention to him.",
    '10:5': "God's judgments are \"far above out of his sight\" — not disbelieved, just too high up to be a factor.",
    '10:6': "\"I shall not be moved\" is a word of faith in the psalms, spoken here by a man with no God in it.",
    '10:7': "Cursing, deceit and fraud in the mouth, mischief kept under the tongue — the store is bigger than the speech.",
    '10:8': "Ambush in villages and secret places. The cruelty is patient and it chooses people nobody will miss.",
    '10:9': "The lion image lands on a man hunting the poor. Predation is being described in an ordinary street.",
    '10:10': "He crouches and humbles himself as a tactic. Even meekness can be worn as a weapon.",
    '10:11': "He credits God with his own indifference: hidden face, short memory, nothing seen.",
    '10:12': "\"Lift up thine hand\" — the prayer asks God to do the very thing the wicked said he never would.",
    '10:13': "The question is why God allows the contempt, not why he allows the violence.",
    '10:14': "\"Thou hast seen it.\" The whole answer to the psalm's opening complaint is one clause: God has been looking.",
    '10:15': "\"Till thou find none\" — the request is not for punishment but for the wickedness to be finished off entirely.",
    '10:16': "Kingship for ever is set against nations that perished. The throne outlasts everyone who ignored it.",
    '10:17': "God prepares the heart that then prays to him. Even the desire he answers was his own work first.",
    '10:18': "\"The man of the earth\" — dust is reminded of its material at the end of a psalm about the untouchable.",
}

TAKEAWAYS.update({
    # ---- Chapter 11 ----
    '11:1': "The advice to flee is refused not because the danger is small but because trust was already placed.",
    '11:2': "The arrow is on the string and aimed \"privily.\" The threat is real, prepared, and hidden.",
    '11:3': "The question is left standing without an answer, because the psalm's reply is about who is on the throne instead.",
    '11:4': "Heaven's throne is not a place of retreat but of inspection: his eyes behold and his eyelids try.",
    '11:5': "The righteous are tried too. Testing is not the mark of God's displeasure; hatred of violence is.",
    '11:6': "\"The portion of their cup\" — judgement is served as a measured share, not a loss of temper.",
    '11:7': "God loves righteousness because he is righteous. The upright are looked at by a face, not a rule.",

    # ---- Chapter 12 ----
    '12:1': "The cry is not about enemies but about scarcity — the godly are simply running out.",
    '12:2': "\"A double heart\" is the diagnosis: the lips flatter because the heart is already two things.",
    '12:3': "Judgement falls on speech itself. The tongue is treated as an organ that can be answerable.",
    '12:4': "\"Our lips are our own\" — the boast of free speech is quoted here as the language of rebellion.",
    '12:5': "God's stated reason for arising is the sighing of the needy. The trigger is a sound, not a strategy.",
    '12:6': "Against lips full of vanity, God's words are set as silver refined seven times. Purity is the contrast.",
    '12:7': "The preserving is from \"this generation\" — not out of the world but through the company that is in it.",
    '12:8': "Wickedness spreads in public when vile men are honoured. Exaltation of the worst licenses everyone else.",

    # ---- Chapter 13 ----
    '13:1': "\"How long... for ever?\" He asks God to set a limit on a silence he fears has no end.",
    '13:2': "Taking counsel in his own soul is listed as part of the suffering. Self-advice becomes its own weariness.",
    '13:3': "\"Lighten mine eyes\" — the request is for the light to come back into a face, which is how life is measured here.",
    '13:4': "The reason offered is the enemy's boast. He fears God's reputation going down with his own.",
    '13:5': "\"But I have trusted in thy mercy.\" The turn rests on mercy, which nothing in his circumstances has confirmed.",
    '13:6': "The past tense arrives at the end: God \"hath dealt bountifully\" with a man still waiting.",

    # ---- Chapter 14 ----
    '14:1': "The denial is said in the heart, not argued. Atheism here is a preference before it is a conclusion.",
    '14:2': "God looks down to see if there is anyone who understands. The search is real and it is his.",
    '14:3': "\"No, not one.\" The verdict is total, and Paul will quote it to close every mouth.",
    '14:4': "They devour God's people as casually as eating bread, and the missing thing is that they never call on him.",
    '14:5': "\"There were they in great fear\" — the confident are the ones who panic, because God is with the other side.",
    '14:6': "The poor man's counsel is mocked precisely because his refuge is invisible.",
    '14:7': "The psalm of universal corruption ends asking for salvation to come out of Zion, from outside the human material.",

    # ---- Chapter 15 ----
    '15:1': "The question is about staying, not visiting. Who can live where God lives is the harder form of the question.",
    '15:2': "Truth is spoken \"in his heart\" — the standard reaches inside, where no witness can verify it.",
    '15:3': "Two of the three marks are about what is not said. Restraint of the tongue counts as righteousness.",
    '15:4': "Swearing to his own hurt and not changing: integrity is measured by what a promise costs when it turns bad.",
    '15:5': "The answer to who may dwell with God turns out to be about money and courts, not about ritual.",

    # ---- Chapter 16 ----
    '16:1': "Preservation is asked for on the ground of trust already given, as though trust were the only claim he had.",
    '16:2': "\"My goodness extendeth not to thee.\" Nothing he does adds anything to God, which frees his goodness for others.",
    '16:3': "His delight lands on the saints in the earth. Love for God comes out as pleasure in ordinary believers.",
    '16:4': "He will not even speak the other gods' names. Refusal of idolatry reaches into vocabulary.",
    '16:5': "Inheritance language from the land allotment is applied to God himself. The LORD is the plot of ground.",
    '16:6': "\"The lines are fallen unto me in pleasant places\" — contentment is described as a surveyor's report.",
    '16:7': "God gives the counsel, and the man's own reins instruct him at night. Guidance arrives from outside and within.",
    '16:8': "Setting the LORD before him is his act; being at his right hand is God's. The stability follows the second.",
    '16:9': "Heart, glory and flesh all rest. The hope is bodily, not a consolation for the soul only.",
    '16:10': "\"Thou wilt not suffer thine Holy One to see corruption\" — a line Peter and Paul will say outran David's own grave.",
    '16:11': "Fulness of joy is located in a presence, not a place or a condition.",

    # ---- Chapter 17 ----
    '17:1': "\"That goeth not out of feigned lips\" — he stakes the prayer on its honesty before he states its content.",
    '17:2': "He asks for the sentence to come from God's presence, preferring heaven's court to any hearing on earth.",
    '17:3': "He claims God visited him in the night and found nothing — the hours when a man is least able to perform.",
    '17:4': "What kept him off the destroyer's paths was the word of God's lips, not his own resolve.",
    '17:5': "Having just claimed uprightness, he immediately asks to be held up. The integrity is not self-supporting.",
    '17:6': "\"For thou wilt hear me\" — the reason he calls is that he is already sure of the answer.",
    '17:7': "Lovingkindness is asked for as something marvellous. Mercy is treated as a wonder, not a routine.",
    '17:8': "The apple of the eye and the shadow of wings: the most guarded thing in a body, and a bird over its young.",
    '17:9': "\"Compass me about\" — the enemies are not ahead of him but all around, which is what makes wings the right image.",
    '17:10': "\"Inclosed in their own fat\" — prosperity itself becomes the shell that keeps them from feeling anything.",
    '17:11': "Their eyes are bowed to the earth, watching the ground for a footprint. The hunt is patient and close.",
    '17:12': "The lion is called greedy. The malice is not need but appetite.",
    '17:13': "\"The wicked, which is thy sword\" — the enemy is named as an instrument in God's hand even while being resisted.",
    '17:14': "Their portion is in this life and God himself filled it. Prosperity is granted, and it is all they get.",
    '17:15': "Against a belly full now, he sets a face seen later. Satisfaction is deferred to waking in God's likeness.",

    # ---- Chapter 18 ----
    '18:1': "\"I will love thee\" — the only place in the psalter where a man says this to God in so many words.",
    '18:2': "Rock, fortress, deliverer, buckler, horn, high tower: no one image carries it, so he piles them up.",
    '18:3': "Praise comes first and salvation follows in the sentence. He calls on a God already known to be worth calling.",
    '18:4': "Death is described as water closing in — not an event ahead but a flood already around him.",
    '18:5': "\"The snares of death prevented me\" — they got there first. He was trapped before he knew he was hunted.",
    '18:6': "One cry from a cornered man reaches into the temple and into God's ears. That is the hinge of the psalm.",
    '18:7': "The answer to the cry is an earthquake. God's rescue of one man is described as cosmic disturbance.",
    '18:8': "Smoke and fire from nostrils and mouth: the poem borrows the language of a raging animal for God's anger.",
    '18:9': "\"He bowed the heavens also, and came down.\" Rescue requires descent, not a message sent down.",
    '18:10': "He rides a cherub and flies on the wind. Even the storm is transport, not the deity itself.",
    '18:11': "God makes darkness his secret place. The nearer he comes, the less he can be looked at.",
    '18:12': "The brightness burns off the very clouds he was hiding in. Concealment does not survive his approach.",
    '18:13': "Thunder is called his voice. The sky is not accompanying the rescue; it is the rescue speaking.",
    '18:14': "Lightning is treated as archery. The scattering is aimed, not weather.",
    '18:15': "The sea floor and the world's foundations are laid bare by a breath. Creation is undressed to save one man.",
    '18:16': "\"He sent from above, he took me, he drew me out.\" Three verbs, all his; the drowning man does nothing.",
    '18:17': "\"For they were too strong for me.\" The reason God had to act is admitted without embarrassment.",
    '18:18': "They came on the day of calamity, when he was already down. Enemies keep good time.",
    '18:19': "\"Because he delighted in me\" — the reason given for deliverance is God's pleasure, not the rescued man's worth.",
    '18:20': "Righteousness rewarded, immediately after deliverance was credited to delight. The psalm holds both without apology.",
    '18:21': "Keeping God's ways is defined negatively: he did not wickedly depart. Faithfulness as staying put.",
    '18:22': "The judgments were \"before me\" — kept in sight rather than kept in memory.",
    '18:23': "\"I kept myself from mine iniquity\" — he names a particular sin that is his own, not sin in general.",
    '18:24': "\"In his eyesight\" is added the second time. The verdict that counts is rendered where God is looking.",
    '18:25': "God meets the merciful as merciful. The character a man brings is the character he encounters.",
    '18:26': "\"With the froward thou wilt shew thyself froward.\" Crookedness finds God hard to deal with, and is told why.",
    '18:27': "Saving the afflicted and lowering high looks are one action described twice.",
    '18:28': "\"Thou wilt light my candle\" — after all the lightning, the gift asked for is a small domestic flame.",
    '18:29': "Running a troop and leaping a wall, both \"by thee.\" The credit goes to God for what his own legs did.",
    '18:30': "\"The word of the LORD is tried\" — proved by use, like metal, which is why it can be leaned on.",
    '18:31': "The rhetorical question assumes the answer. Other gods are not refuted here, only dismissed.",
    '18:32': "God girds him with strength and makes his way perfect. Both the power and the path are supplied.",
    '18:33': "Hinds' feet are for staying upright on ground that gives way, not for speed.",
    '18:34': "Even the soldier's trained skill is traced back to teaching he received rather than talent he had.",
    '18:35': "\"Thy gentleness hath made me great.\" The one thing named as the making of him is the softest word in the psalm.",
    '18:36': "The enlarged step is the opposite of the snares of verse five. Room to walk is itself deliverance.",
    '18:37': "The pursuit does not stop halfway. Where God gives victory, David does not leave the work unfinished.",
    '18:38': "The language is unsparing. The psalter does not clean up what winning a war actually looked like.",
    '18:39': "The subduing is God's; the fighting is his. The psalm refuses to separate them.",
    '18:40': "\"Thou hast given me the necks of mine enemies\" — even the moment of triumph is described as a gift received.",
    '18:41': "They cried to the LORD and were not answered. Prayer in extremity is not automatically heard.",
    '18:42': "Dust before wind, dirt in the streets: the enemies end as the two most worthless things underfoot.",
    '18:43': "A people he never knew will serve him. The king's rule reaches past the borders of his acquaintance.",
    '18:44': "Submission at the mere report of him. Reputation does work that armies would have had to do.",
    '18:46': "\"The LORD liveth\" — the whole thanksgiving rests on the bare fact that God is not a dead idol.",
    '18:47': "Vengeance is assigned to God even in a psalm where the king did the killing.",
    '18:48': "\"The violent man\" in the singular closes the list. Behind all the armies there was one person he feared.",
    '18:49': "He gives thanks \"among the heathen.\" Paul will read that line as the Gentiles being brought in.",
    '18:50': "The promise runs past David to his seed for ever, which is more than any one king's life can hold.",

    # ---- Chapter 19 ----
    '19:1': "The heavens declare glory without saying anything a man could quote. Creation testifies and never argues.",
    '19:2': "Day and night hand the message to each other. The witness has no gaps in it.",
    '19:3': "No language is needed, so no one is excluded by not knowing the words.",
    '19:4': "\"Through all the earth\" — the reach of this preaching is what Paul will say leaves the nations without excuse.",
    '19:5': "The sun is a bridegroom and a runner: eager, not merely regular. The order of nature is described as joy.",
    '19:6': "\"Nothing hid from the heat thereof\" — the sun's reach is the picture of an exposure nothing escapes.",
    '19:7': "The law converts the soul. It is not described as a burden to carry but as something that does work on a man.",
    '19:8': "Right statutes rejoice the heart. Gladness is claimed for commandment, which is not how law is usually felt.",
    '19:9': "\"The fear of the LORD is clean\" — the reverence itself is called pure, and it is the one thing here that lasts.",
    '19:10': "Gold and honey: worth and sweetness. The psalm insists the law is desirable, not only correct.",
    '19:11': "Warned by them, and rewarded in keeping them — the reward is in the keeping, not paid afterward.",
    '19:12': "\"Who can understand his errors?\" The psalm about a perfect law turns and asks about faults he cannot even see.",
    '19:13': "Presumptuous sins are feared for their dominion. The danger named is not the act but the mastery.",
    '19:14': "Words and meditation are offered for acceptance, which is what a sacrifice is offered for.",

    # ---- Chapter 20 ----
    '20:1': "The people pray for the king before the battle. The whole psalm is intercession, not self-defence.",
    '20:2': "Help is asked from the sanctuary, not the armoury. Where strength is expected to come from is the point.",
    '20:3': "Remembering the offerings is asked for as a ground of favour, but God is the one who must accept them.",
    '20:4': "\"According to thine own heart\" — the prayer is bold enough to ask God to grant what the king wants.",
    '20:5': "Banners are set up in the name of God rather than in the name of the king who will fight under them.",
    '20:6': "\"Now know I\" — one man's certainty breaks into the congregation's prayer before anything has happened.",
    '20:7': "Chariots and horses are not denied their power; they are simply set against a name and found lighter.",
    '20:8': "The outcome is reported in the past tense before the battle. Faith speaks of the result as finished.",
    '20:9': "The last line asks the king to hear them, after a whole psalm asking God to hear him.",

    # ---- Chapter 21 ----
    '21:1': "The king's joy is in God's strength rather than in his own victory.",
    '21:2': "\"Hast not withholden the request of his lips\" — the granting is named twice, as if it were hard to believe once.",
    '21:3': "\"Thou preventest him\" — God arrives with blessing before it is asked for. The crown is placed, not seized.",
    '21:4': "He asked for life and was given length of days for ever, which is more than the request could hold.",
    '21:5': "Honour and majesty are \"laid upon him\" like a garment. Even the king's dignity is issued to him.",
    '21:6': "Gladness comes from God's countenance. The face, not the gifts, is what makes him most blessed.",
    '21:7': "Between all the blessings, the one thing said about the king himself is that he trusts.",
    '21:8': "\"Thine hand shall find out\" — no enemy is lost in the crowd. Judgement is described as locating people.",
})

TAKEAWAYS.update({
    '21:9': "The oven image puts the fire inside them. Wrath is not only what falls on the wicked but what they become.",
    '21:10': "Judgement reaches the seed as well. The psalm assumes a man's evil does not stop at his own lifetime.",
    '21:11': "\"Which they are not able to perform.\" The plot is real and simply beyond their strength.",
    '21:12': "Arrows aimed at the face turn men around. The rout is caused by being looked at.",
    '21:13': "The psalm asks God to be exalted in his own strength, not in the king's, and stops there.",

    # ---- Chapter 22 ----
    '22:1': "\"My God, my God\" — the forsaking is protested by a man who still has no other name to call on.",
    '22:2': "Unanswered by day and by night, and still not silent. Persistence here is not evidence that prayer is working.",
    '22:3': "\"But thou art holy.\" He will not explain the silence by finding a fault in God.",
    '22:4': "He recites the fathers' deliverance as fact, which sharpens rather than soothes the present silence.",
    '22:5': "They cried and were not confounded — the exact thing not happening to him, said out loud.",
    '22:6': "\"I am a worm, and no man.\" Contempt has done its work: he no longer counts himself among people.",
    '22:7': "The shot-out lip and the shaken head are recorded gestures, and the gospels will see them again at a cross.",
    '22:8': "The mockers use his own theology against him: if God delights in you, let him prove it.",
    '22:9': "The argument turns to infancy. If God brought him out of the womb, he has been responsible for him from the start.",
    '22:10': "\"Cast upon thee from the womb\" — dependence was never chosen; it was his condition before he could speak.",
    '22:11': "\"For there is none to help\" is given as the reason God should come near. Having no one else is the qualification.",
    '22:12': "Bulls of Bashan: the enemies are drawn as well-fed livestock, heavy and stupid and pressing in.",
    '22:13': "The mouth is open before the bite. What he describes is the moment of anticipation, not the injury.",
    '22:14': "Poured out, disjointed, melted — he reports the collapse of his body from the inside.",
    '22:15': "\"Thou hast brought me into the dust of death.\" The hand he blames for it is God's.",
    '22:16': "Pierced hands and feet, written centuries before crucifixion was a Roman word.",
    '22:17': "He can count his own bones while others stare. Exposure and emaciation are named in one line.",
    '22:18': "Garments divided and lots cast — the soldiers at Golgotha will do this without knowing they are quoting.",
    '22:19': "After the whole catalogue of horror, the one request is nearness. \"Be not thou far from me.\"",
    '22:20': "\"My darling\" is his own soul — the thing he loves most and cannot protect.",
    '22:21': "The tense breaks mid-verse: still pleading, and then \"thou hast heard me.\" The answer arrives inside the sentence.",
    '22:22': "The first thing done with the rescue is to tell his brethren. Deliverance becomes declaration.",
    '22:23': "He calls the whole congregation into a praise that began as one man's abandonment.",
    '22:24': "\"He hath not despised the affliction of the afflicted\" — the verdict on the silence, delivered after it ended.",
    '22:25': "Vows made in the dark are paid in public. The debt of a crisis prayer is settled where people can see.",
    '22:26': "The meek eat and are satisfied. The psalm's outcome is a meal, and the hungry are the guests.",
    '22:27': "The ends of the world \"remember\" — as though the nations were recalling something they had lost.",
    '22:28': "The kingdom belongs to the LORD, which is why one man's rescue can end with the nations turning.",
    '22:29': "\"None can keep alive his own soul.\" The fat and the dying are levelled by the same inability.",
    '22:30': "A seed not yet born is counted as a generation already belonging to him.",
    '22:31': "\"He hath done this\" — the psalm ends on a finished work reported to people who were not there.",

    # ---- Chapter 23 ----
    '23:1': "Because the LORD shepherds him, wanting stops. The second clause is a consequence, not a separate boast.",
    '23:2': "\"He maketh me to lie down.\" Sheep do not rest until they are made to; rest is administered.",
    '23:3': "The leading is for God's name's sake. Even guidance into righteousness is about his reputation, not the sheep's merit.",
    '23:4': "In the valley the pronoun changes from \"he\" to \"thou.\" Danger turns description into address.",
    '23:5': "The table is set in front of the enemies, not after they are gone. Provision does not wait for safety.",
    '23:6': "Goodness and mercy \"follow\" — they come up behind, covering the road he has already walked.",

    # ---- Chapter 24 ----
    '24:1': "Ownership is total and includes the inhabitants. Nobody in the world is outside the claim.",
    '24:2': "Founded upon the seas: the world is settled on what is least stable, and holds because he holds it.",
    '24:3': "The question is asked at the gate of the hill God owns. Everything is his, and still not everyone may come up.",
    '24:4': "Clean hands and a pure heart together — the outward act and the inward aim are both named, and neither alone.",
    '24:5': "Righteousness is received from the God of his salvation. The qualified man still has it given to him.",
    '24:6': "The generation that qualifies is defined as the one that seeks his face. Wanting him is the description.",
    '24:7': "The doors are called everlasting and still told to lift up. Nothing ancient is too settled to make room for him.",
    '24:8': "The answer names him mighty in battle. The King entering the city is described as a soldier coming home.",
    '24:10': "\"The LORD of hosts, he is the King of glory.\" The second answer drops the battle and gives only the name.",

    # ---- Chapter 25 ----
    '25:1': "Lifting up the soul is the whole act. Before any request, the self is handed over.",
    '25:2': "Shame, not defeat, is what he fears. To trust and be let down publicly is the worse outcome.",
    '25:3': "He widens his own prayer to cover everyone who waits. Personal need becomes intercession mid-sentence.",
    '25:4': "In the middle of trouble the request is for instruction. He assumes he may be going the wrong way.",
    '25:5': "\"On thee do I wait all the day\" — waiting is offered as the posture in which teaching is received.",
    '25:6': "He asks God to remember mercies that are \"ever of old.\" The appeal is to God's long habit.",
    '25:7': "Remember not the sins, remember thou me. The same verb is asked to work in two directions at once.",
    '25:8': "Because God is good, he teaches sinners. Goodness expresses itself as instruction of the wrong people.",
    '25:9': "Guidance is promised to the meek, which makes teachability the qualification rather than intelligence.",
    '25:10': "All God's paths are mercy and truth. Not some merciful and some true — every one of them both.",
    '25:11': "\"Pardon mine iniquity; for it is great.\" The size of the sin is used as an argument for forgiving it.",
    '25:12': "The man who fears God is taught the way he shall choose — instruction comes before the choosing, not after.",
    '25:13': "Ease of soul and an inheriting seed. The blessing reaches both inward quiet and outward continuance.",
    '25:14': "\"The secret of the LORD\" — intimacy, not information, is what the covenant opens up to those who fear him.",
    '25:15': "Eyes fixed upward while the feet are in a net. Looking away from the trap is how he expects to leave it.",
    '25:16': "\"I am desolate and afflicted\" — he describes himself as alone in a psalm addressed to someone.",
    '25:17': "The troubles are \"enlarged\" — grief takes up more room than it did, and he says so.",
    '25:18': "Affliction and sin are laid before God in the same breath, as though relief and pardon were one request.",
    '25:19': "Their hatred is called cruel. He names the quality of it, not just the number of them.",
    '25:20': "Trust is given as the reason he should not be ashamed. He has staked his standing on God's response.",
    '25:21': "Integrity is asked to preserve him, and then the ground shifts to waiting. Even his uprightness is not his security.",
    '25:22': "The acrostic ends outside itself, praying for the whole nation after twenty-one verses about one man.",

    # ---- Chapter 26 ----
    '26:1': "He asks to be judged, which is what only a man with a specific accusation against him would want.",
    '26:2': "Examine, prove, try — three words for the same request. He invites the deepest possible inspection.",
    '26:3': "The integrity he claims is traced to lovingkindness kept before his eyes. He walked well by looking at something.",
    '26:4': "Righteousness is described by whose company he has refused. Where a man sits is counted as a moral act.",
    '26:5': "Hating the congregation of evildoers is set opposite loving the house of God in the same psalm.",
    '26:6': "Washing the hands is done in order to go round the altar. The cleansing is for approach, not for display.",
    '26:7': "The purpose of access is thanksgiving out loud. He comes to the altar in order to tell about God.",
    '26:8': "\"The place where thine honour dwelleth\" — he loves the house for who is in it, not for the architecture.",
    '26:9': "The fear is of being counted with the bloody men, not of what they might do to him.",
    '26:10': "Bribes in the right hand — the hand for oaths and greeting is the one that is full.",
    '26:11': "\"Redeem me, and be merciful unto me\" closes a psalm of protested innocence. Even integrity asks for mercy.",
    '26:12': "\"An even place\" after all the sliding and trying: level ground is the answer to the psalm's opening fear.",

    # ---- Chapter 27 ----
    '27:1': "Light, salvation and strength are stacked up, and each one is answered by a question nobody replies to.",
    '27:2': "They came to eat his flesh and stumbled before reaching him. The collapse needed no counter-attack.",
    '27:3': "\"In this will I be confident\" — the confidence has a location, and it is not in the odds.",
    '27:4': "One thing desired, out of a life full of urgent needs, and it is to look at God.",
    '27:5': "Hiding in the pavilion and being set on a rock: concealment and exposure both count as safety here.",
    '27:6': "The head lifted above enemies leads not to revenge but to singing in the tabernacle.",
    '27:7': "After all the confidence, he is back to asking to be heard. Assurance does not make him stop pleading.",
    '27:8': "The invitation came first and his heart echoed it back. Seeking God is an answer, not an initiative.",
    '27:9': "\"Thou hast been my help\" is set in the middle of asking not to be abandoned. Memory is used as leverage.",
    '27:10': "Father and mother are named as the last people who could forsake him, and God is put after them.",
    '27:11': "\"A plain path, because of mine enemies\" — he asks for clarity precisely because he is being watched for a stumble.",
    '27:12': "False witnesses \"breathe out cruelty.\" The lie and the malice are described as one exhalation.",
    '27:13': "\"I had fainted, unless I had believed\" — he says plainly what belief was for. It kept him upright.",
    '27:14': "Waiting is commanded twice with courage between. The strengthening happens during the wait, not after it.",

    # ---- Chapter 28 ----
    '28:1': "Silence from God, not disaster, is what would put him among the dead. Being unanswered is the pit.",
    '28:2': "Hands lifted toward the oracle. The body turns to face the place where God has spoken.",
    '28:3': "\"Speak peace to their neighbours, but mischief is in their hearts\" — he asks not to share the fate of the two-faced.",
    '28:4': "The prayer is that their work be handed back to them. Judgement is requested as accuracy, not excess.",
    '28:5': "The named cause is inattention: they do not regard what God does. Not seeing his works is treated as guilt.",
    '28:6': "The whole psalm turns on \"he hath heard.\" One clause converts petition into blessing.",
    '28:7': "Strength, shield, trust, help, joy, song — he traces the whole chain and puts trust in the middle of it.",
    '28:8': "The pronoun changes to \"their.\" His own answered prayer is read as evidence for the people's safety.",
    '28:9': "The psalm ends asking God to feed and carry them, which is shepherd's work, not a king's.",

    # ---- Chapter 29 ----
    '29:1': "\"O ye mighty\" — the ones told to give glory are the powerful, who have the most trouble giving it.",
    '29:2': "Worship is to be offered in the beauty of holiness. Holiness is treated as something lovely, not only severe.",
    '29:3': "The thunder over the waters is called a voice. The storm is not God; it is God speaking.",
    '29:5': "Cedars of Lebanon were the strongest timber known. The voice breaks what men built their palaces from.",
    '29:6': "Mountains skip like calves. The solid things of the world are made to behave like young animals.",
    '29:7': "\"Divideth the flames of fire\" — lightning is described as the voice splitting, not as a separate force.",
    '29:8': "The wilderness of Kadesh, empty of people, shakes too. The storm's audience is not the point of it.",
    '29:9': "The same voice that shatters cedars starts a birth. Terror and life-giving come from one source.",
    '29:10': "He sits upon the flood — enthroned on the very chaos the storm has been stirring.",
    '29:11': "After eleven verses of overwhelming noise, what he gives his people is peace.",

    # ---- Chapter 30 ----
    '30:1': "\"Thou hast lifted me up\" — the word is for drawing a bucket from a well, and that is where he had been.",
    '30:2': "The cry and the healing are set side by side with nothing in between. The report leaves out the waiting.",
    '30:3': "Kept alive rather than raised after dying. The rescue was from the edge, and he knows how close it was.",
    '30:4': "The saints are told to give thanks at the remembrance of God's holiness, not of their own relief.",
    '30:5': "A moment of anger against a lifetime of favour, a night of weeping against a morning. The proportions are the point.",
    '30:6': "\"In my prosperity I said, I shall never be moved.\" Comfort taught him a confidence he had not earned.",
    '30:7': "The mountain stood by God's favour, and the trouble came when the face was hidden, not when the mountain fell.",
    '30:8': "He does not pretend the crying stopped when the trouble started. The psalm keeps the record of his panic.",
    '30:9': "The argument offered is that dust cannot praise. He bargains with God about the loss of a worshipper.",
    '30:10': "The plea narrows to two words: hear, and have mercy. Elaborate argument collapses into request.",
    '30:11': "Sackcloth taken off and gladness girded on. The change of clothing is how the change of state is reported.",
    '30:12': "The rescue's purpose is a voice that will not be silent. He was kept alive in order to say so.",
})

TAKEAWAYS.update({
    # ---- Chapter 31 ----
    '31:1': "Deliverance is asked for \"in thy righteousness\" — God's own rightness is the ground of the rescue.",
    '31:2': "\"Deliver me speedily.\" The prayer is allowed to be impatient about timing without being impatient about God.",
    '31:3': "Because God is his fortress, he asks to be led. Security does not remove the need for direction.",
    '31:4': "The net was laid \"privily.\" What he most needs pulling out of is the trap he could not see.",
    '31:5': "\"Into thine hand I commit my spirit\" — the words Christ will die saying, spoken here by a man asking to live.",
    '31:6': "Lying vanities and the LORD are the only two options offered. There is no neutral place in this verse.",
    '31:7': "\"Thou hast known my soul in adversities\" — being known in the trouble is counted as the mercy itself.",
    '31:8': "Not shut up, but set at large. The deliverance is described spatially: room instead of confinement.",
    '31:9': "Grief consumes the eye, the soul and the belly. He reports it as a bodily illness, because it is one.",
    '31:10': "\"My strength faileth because of mine iniquity.\" He names his own sin as part of what is wearing him out.",
    '31:11': "\"Especially among my neighbours\" — the nearest people are the ones whose contempt cuts deepest.",
    '31:12': "A broken vessel is not mourned, only discarded. He describes himself as something nobody would keep.",
    '31:13': "\"Fear was on every side\" — the phrase Jeremiah will make his own. Slander creates a climate, not just an injury.",
    '31:14': "\"But I trusted in thee\" arrives with no change in the facts. The turn is a decision, not a development.",
    '31:15': "\"My times are in thy hand\" — not just the outcome but the timetable belongs to someone else.",
    '31:16': "The blessing of Aaron is turned into a personal request. He wants the priestly words said over him.",
    '31:17': "Shame is treated as a limited commodity. He asks that it fall on the liars rather than the trusting.",
    '31:18': "The proud and contemptuous speech is what he asks to be silenced, not the people themselves.",
    '31:19': "Goodness is \"laid up\" and also \"wrought before the sons of men\" — stored in reserve and shown in public.",
    '31:20': "Hidden from the strife of tongues. The shelter offered is specifically against words.",
    '31:21': "\"In a strong city\" — the kindness came with walls, which is a very concrete form of marvellous.",
    '31:22': "\"I said in my haste\" — he records his own panicked verdict and then reports that it was wrong.",
    '31:23': "The saints are commanded to love God, which is the one duty the whole psalm has been demonstrating.",
    '31:24': "Hope is where the courage comes from, and the strengthening is promised to the heart, not the circumstances.",

    # ---- Chapter 32 ----
    '32:1': "Forgiven and covered — two pictures, one for the debt lifted off and one for the stain hidden.",
    '32:2': "Not imputing iniquity is the verdict Paul will build justification on: a man reckoned clear by decision.",
    '32:3': "Silence about sin did not preserve him; it aged his bones. Concealment is described as a physical cost.",
    '32:4': "\"Thy hand was heavy upon me\" — the misery of unconfessed sin is credited to God, not to conscience alone.",
    '32:5': "The confession is reported and the forgiveness arrives in the same sentence, before he has finished resolving to speak.",
    '32:6': "\"In a time when thou mayest be found\" — the psalm assumes an opening that is not permanently open.",
    '32:7': "\"Songs of deliverance\" surround him where the floods were. The encircling water is replaced by encircling music.",
    '32:8': "Guidance \"with mine eye\" is the closest kind — a look between people near enough to read each other.",
    '32:9': "The alternative to being guided by a glance is bit and bridle. Stubbornness does not avoid control; it coarsens it.",
    '32:10': "Sorrows surround the wicked and mercy surrounds the trusting. The same encircling, opposite contents.",
    '32:11': "A psalm about confessed sin ends in shouting. The gladness commanded belongs to the forgiven, not the innocent.",

    # ---- Chapter 33 ----
    '33:1': "Praise is called \"comely\" — fitting, like the right clothes. It suits the upright rather than obliging them.",
    '33:2': "Instruments are named specifically. Worship here has equipment and expects craft.",
    '33:3': "\"A new song\" and \"play skilfully\" — freshness and competence are both asked for, not one instead of the other.",
    '33:4': "God's word being right and his works being true are one claim. He does what he says.",
    '33:5': "\"The earth is full of the goodness of the LORD\" is set right after his love of judgment. Both fill the same world.",
    '33:6': "The heavens came by a word and a breath. Creation cost him nothing but speech.",
    '33:7': "The sea is stacked like a heap and stored like grain. What terrifies sailors is filed away in his storehouse.",
    '33:9': "\"He spake, and it was done.\" The gap between command and fact is the size of nothing.",
    '33:10': "The nations' plans are not opposed but emptied. God does not out-argue the heathen; he makes their counsel nothing.",
    '33:11': "Against human plans that fail, his counsel stands for ever, and it is called the thoughts of his heart.",
    '33:12': "The nation is blessed for whose God he is, and then described as the people he chose. The blessing runs backwards to election.",
    '33:13': "He looks from heaven at all men, not only at his own people.",
    '33:14': "The looking is done from his dwelling place. Distance does not reduce the detail.",
    '33:15': "He fashions hearts and then considers works. The maker of the motive is the one assessing the act.",
    '33:16': "No king is saved by the size of his army. The psalm names the one thing kings actually rely on and denies it.",
    '33:17': "\"An horse is a vain thing for safety\" — the best military technology of the age, dismissed in a line.",
    '33:18': "The eye that surveys all men rests on those who fear him. The same looking is providence and care at once.",
    '33:19': "Kept alive in famine, not kept out of it. The promise is preservation through the scarcity.",
    '33:20': "Waiting is put in the same breath as help and shield. The waiting is not the absence of protection.",
    '33:21': "Joy is traced to trust in the name — to what they know him to be, not to what has happened.",
    '33:22': "Mercy is asked for \"according as we hope\" — the measure requested is their own expectation.",

    # ---- Chapter 34 ----
    '34:1': "\"At all times\" is written by a man who had just escaped by pretending to be insane.",
    '34:2': "Boasting is allowed when its subject is God, and the people who are glad to hear it are the humble.",
    '34:3': "Magnifying is invited as a joint act. Praise is treated as something too large for one voice.",
    '34:4': "Delivered from his fears, which is not the same as delivered from the danger.",
    '34:5': "Looking produced light in their faces. What a man attends to shows on him.",
    '34:6': "\"This poor man cried\" — he puts himself in the third person, as an example rather than a hero.",
    '34:7': "One angel encamps, which is army language for a single messenger. The guard is not measured by number.",
    '34:8': "\"Taste and see\" — the invitation is to experiment, not to accept a report.",
    '34:9': "Fearing God and lacking nothing are joined, which redefines what counts as want.",
    '34:10': "Young lions, the most capable hunters, go hungry while seekers do not. Competence is not provision.",
    '34:11': "The fear of the LORD is something taught to children, which means it is learned rather than felt.",
    '34:12': "The question is framed as an offer anyone would want. Wisdom begins by asking what you actually desire.",
    '34:13': "The first instruction for a long good life is about the tongue, before anything else is mentioned.",
    '34:14': "Peace is to be pursued, as though it were running away and had to be chased down.",
    '34:15': "Eyes on them and ears open to them. God's attention is described as watching and listening at once.",
    '34:16': "The face is \"against\" the evildoers. Opposition, not absence, is what judgement looks like here.",
    '34:17': "The cry comes first and the hearing follows. The righteous are not spared the trouble that makes them cry.",
    '34:18': "Nearness is promised specifically to the broken. Brokenness draws God rather than disqualifying.",
    '34:19': "\"Many are the afflictions of the righteous\" — the psalm concedes the whole difficulty before promising anything.",
    '34:20': "\"Not one of them is broken\" — John will point to this line at a cross where the legs were left alone.",
    '34:21': "Evil is said to slay the wicked. The punishment is not brought in from outside; it is what they were doing.",
    '34:22': "Redemption of the servants' souls is the last word, and it is God's act, not their record.",

    # ---- Chapter 35 ----
    '35:1': "He asks God to both plead his case and fight for him — advocate and soldier in one request.",
    '35:2': "God is asked to pick up armour. The image is startling enough that the psalm does not soften it.",
    '35:3': "\"Say unto my soul, I am thy salvation.\" With the spear already drawn, what he wants most is to be told.",
    '35:4': "Confusion and shame are asked for rather than death. He wants the plot broken, not the plotters destroyed.",
    '35:5': "Chaff blown off the threshing floor, with an angel behind it — the wind of judgement is given a person.",
    '35:6': "Dark and slippery: the pursuit he asks for uses their own footing against them.",
    '35:7': "\"Without cause\" twice in one verse. The motiveless quality of the malice is what he cannot get past.",
    '35:8': "The net catches the man who hid it, and the destruction arrives \"at unawares\" — the surprise he was planning.",
    '35:9': "The joy anticipated is in the LORD and his salvation, not in the enemies' fall he has just described.",
    '35:10': "\"All my bones shall say\" — he wants praise out of the part of him that has been aching.",
    '35:11': "They charged him with things he knew nothing about. The lie was not even about something he had done.",
    '35:12': "Evil for good is the wound. It is not the attack but the exchange rate that he protests.",
    '35:13': "He fasted and wore sackcloth for the men now hunting him, before he knew what they were.",
    '35:14': "\"As one that mourneth for his mother\" — he sets the grief at its deepest to say how far the betrayal reaches.",
    '35:15': "They gathered while he was down, and \"I knew it not.\" The tearing was organised behind his back.",
    '35:16': "Mockery at feasts with gnashing teeth. Their entertainment and their hatred were the same evening.",
    '35:17': "\"How long wilt thou look on?\" The complaint is that God is a spectator, which assumes he is present.",
    '35:18': "Thanks promised in the great congregation. Private rescue is to be repaid with public testimony.",
    '35:19': "A wink of the eye is all they would need. He asks that so small a triumph not be allowed them.",
    '35:20': "\"Them that are quiet in the land\" — the victims are described as people who were not looking for a fight.",
    '35:21': "\"Aha, aha, our eye hath seen it.\" They claim to have witnessed what the false witnesses invented.",
    '35:22': "\"This thou hast seen\" answers their boast of seeing. The one real witness is asked to stop being silent.",
    '35:23': "God is told to wake up to a case, as though the delay were inattention rather than purpose.",
    '35:24': "Judgement is asked for according to God's righteousness, not the psalmist's, after all his protest of innocence.",
    '35:25': "\"We have swallowed him up\" is the sentence he cannot bear them to say. The fear is of their satisfaction.",
    '35:26': "Shame and dishonour are described as clothing — something they would be seen in, not merely feel.",
    '35:27': "The people who wanted his vindication are given a line to sing, and it is about God, not about him.",
    '35:28': "The psalm of violent petition ends with a tongue occupied all day in praise of righteousness.",

    # ---- Chapter 36 ----
    '36:1': "Transgression is described as speaking. Sin makes an argument inside a man before it shows in his conduct.",
    '36:2': "\"He flattereth himself in his own eyes\" — self-deception is the mechanism, and it lasts only until the iniquity is found out.",
    '36:3': "\"He hath left off to be wise, and to do good.\" The wickedness is a stopping, not only a starting.",
    '36:4': "He plans it in bed. The most private and restful hour is where the mischief is designed.",
    '36:5': "The psalm breaks off from the wicked mid-thought and measures mercy by the height of the sky.",
    '36:6': "Righteousness like mountains and judgments like the deep: one you can see, one you cannot fathom.",
    '36:7': "The shadow of his wings is where the children of men go, and the reason given is that his kindness is excellent.",
    '36:8': "Fatness and a river of pleasures — the language is of feasting, and God's house is where it is served.",
    '36:9': "\"In thy light shall we see light.\" Seeing anything truly requires standing in his.",
    '36:10': "Even lovingkindness is asked to be continued. Nothing already given is treated as automatically ongoing.",
    '36:11': "The foot of pride and the hand of the wicked: he fears being trodden on and being moved from his place.",
    '36:12': "\"There are the workers of iniquity fallen\" — spoken as though pointing at something already on the ground.",
})

TAKEAWAYS.update({
    # ---- Chapter 37 ----
    '37:1': "The first command of this psalm is not to act but to stop fretting. Envy of the wicked is treated as the danger.",
    '37:2': "Grass, not stone. The reason not to envy them is what they are made of, not what they have done.",
    '37:3': "\"Trust in the LORD, and do good\" — the trusting does not replace the doing, and the doing is quite ordinary.",
    '37:4': "Delight in God is put before the desires are granted, which quietly changes what the desires will be.",
    '37:5': "Committing the way and trusting are one act; the bringing to pass is left entirely to him.",
    '37:6': "Vindication is promised as light at noon — public, undeniable, and not arranged by the man himself.",
    '37:7': "Rest and patience are commanded precisely about the man whose wicked schemes are succeeding.",
    '37:8': "Anger is said to lead to evil. The psalm treats indignation at injustice as a road that can end badly.",
    '37:9': "Those who wait inherit. In this psalm inheritance is the reward of not grabbing.",
    '37:10': "\"Thou shalt diligently consider his place, and it shall not be\" — you will look carefully and find nothing there.",
    '37:11': "The meek inherit the earth and get peace with it. Jesus will quote the line without softening the claim.",
    '37:12': "Gnashing teeth at the just: the hostility is personal and physical, not merely a difference of principle.",
    '37:13': "God laughs \"for he seeth that his day is coming.\" The laughter is knowledge of a date, not contempt.",
    '37:14': "The sword is drawn against the poor and needy. Violence in this psalm always runs downhill.",
    '37:15': "The weapon turns inward. The sword enters the heart that drew it.",
    '37:16': "A little with righteousness is called better outright. The comparison is not consoling but evaluative.",
    '37:17': "Broken arms against an upholding hand. Strength and support are set opposite each other, not strength and strength.",
    '37:18': "\"The LORD knoweth the days of the upright\" — their obscure and difficult days are counted by someone.",
    '37:19': "Satisfied in famine, not exempted from it. The promise sits inside the evil time.",
    '37:20': "The fat of lambs burned on an altar: the wicked end as smoke, consumed in the very act of being offered up.",
    '37:21': "Borrowing without repaying and giving without being asked. Character is read off a ledger.",
    '37:22': "Blessing and cursing decide who keeps the land. The inheritance follows God's verdict, not the market.",
    '37:23': "The steps are ordered and God delights in the way. Providence here is pleasure, not only management.",
    '37:24': "\"Though he fall\" — the psalm assumes the good man will fall, and promises only that he is held while he does.",
    '37:25': "An old man's testimony, offered as observation rather than doctrine. He reports what he has and has not seen.",
    '37:26': "Mercy and lending are named as the habit of the man who was never forsaken. Generosity is how provision moves on.",
    '37:27': "Doing good is tied to dwelling for evermore. The ethics and the inheritance are one sentence.",
    '37:28': "\"The LORD loveth judgment\" is given as the reason he does not abandon his saints. Justice is why they are safe.",
    '37:30': "The righteous man's mouth produces wisdom. What he has been fed on comes back out.",
    '37:31': "\"The law of his God is in his heart\" — that, and not his own carefulness, is why his steps hold.",
    '37:32': "The wicked watches, which means the righteous man is being studied for a weakness.",
    '37:33': "God will not condemn him \"when he is judged.\" Human courts may go the other way, and often do.",
    '37:34': "Waiting and keeping his way together. Patience in this psalm is never idleness.",
    '37:35': "The green bay tree is native, rooted and flourishing in its own soil. That is what made it look permanent.",
    '37:36': "\"I sought him, but he could not be found.\" The disappearance is total and the psalmist went looking.",
    '37:37': "\"Mark the perfect man\" — the instruction is to watch how a life ends, not how it looks at its height.",
    '37:38': "\"The end of the wicked shall be cut off\" — not only the man but the future he was building toward.",
    '37:39': "After forty verses of moral contrast, salvation is finally said to be \"of the LORD.\"",
    '37:40': "\"Because they trust in him\" is the last clause of the psalm, and the only reason given for the rescue.",

    # ---- Chapter 38 ----
    '38:1': "He accepts the rebuke and asks only that wrath be taken out of it. Correction is not what he is resisting.",
    '38:2': "God's arrows, God's hand. He does not blame his enemies for this suffering.",
    '38:3': "Anger and sin are named as the two causes in one verse, and the effect is in his flesh and bones.",
    '38:4': "Iniquities \"gone over mine head\" — drowning language used for guilt rather than for enemies.",
    '38:5': "\"Because of my foolishness\" — he traces the rot in his wounds back to his own stupidity, not to misfortune.",
    '38:6': "Bowed down and mourning all day. The posture of grief has become his ordinary carriage.",
    '38:7': "The psalter includes a man describing a loathsome disease in his loins without euphemism.",
    '38:8': "The roaring comes from disquiet of heart, not from the pain. The inner trouble is louder than the illness.",
    '38:9': "\"All my desire is before thee\" — he stops describing and admits God already has the whole account.",
    '38:10': "The light of the eyes going out is how the psalms say a man is finished.",
    '38:11': "Friends and kinsmen stand off from the sore. Illness costs him the people, not only the strength.",
    '38:12': "While his friends withdraw, his enemies come closer. Weakness sorts the people around a man quickly.",
    '38:13': "He answers slander with silence, deaf and dumb by choice rather than by inability.",
    '38:14': "\"In whose mouth are no reproofs\" — he has given up defending himself, which is not the same as agreeing.",
    '38:15': "The silence is explained: he is not answering them because he is waiting on God to answer.",
    '38:16': "His concern about their triumph is bound up with his own slipping foot, which he expects.",
    '38:17': "\"My sorrow is continually before me\" — nothing in the day is free of it.",
    '38:18': "The confession comes late and plainly, after all the physical detail. The disease was never the real subject.",
    '38:19': "His enemies are \"lively\" while he is failing. The unfairness of the contrast is stated without comment.",
    '38:20': "They oppose him \"because I follow the thing that good is.\" The goodness is the provocation.",
    '38:21': "After every symptom is catalogued, the request is not healing but presence.",
    '38:22': "\"O Lord my salvation\" — the last word of the psalm names God as the thing he has been asking for.",

    # ---- Chapter 39 ----
    '39:1': "The silence is a policy, adopted specifically so the wicked will not hear him complain.",
    '39:2': "He held his peace \"even from good,\" and the sorrow got worse. Suppression made the wound deeper.",
    '39:3': "The fire burned while he mused, and the speech that followed was forced out rather than chosen.",
    '39:4': "What finally breaks the silence is not a complaint about enemies but a request to know how short life is.",
    '39:5': "A handbreadth is measured on a man's own body. The span of a life is given in the smallest human unit.",
    '39:6': "\"He heapeth up riches, and knoweth not who shall gather them\" — the labour is real and the beneficiary unknown.",
    '39:7': "\"What wait I for?\" He asks himself the question and finds no answer but God.",
    '39:8': "In the middle of a meditation on frailty he asks for deliverance from transgressions. Mortality has made sin urgent.",
    '39:9': "\"Because thou didst it\" — the silence returns, but now on the ground that God is behind the affliction.",
    '39:10': "Having accepted God's hand in it, he immediately asks for the hand to be lifted. The psalm holds both.",
    '39:11': "Beauty consumed like a moth-eaten garment. Correction works quietly, and what it eats does not grow back.",
    '39:12': "\"A stranger with thee\" — he claims the status of a resident alien in God's own land, as his fathers were.",
    '39:13': "The psalm ends asking God to look away. It is the bleakest request in the psalter and it is not withdrawn.",

    # ---- Chapter 40 ----
    '40:1': "The patience is reported after the rescue. It did not feel like patience while it was waiting.",
    '40:2': "Miry clay gives no footing, which is why the rock and the established goings are named separately.",
    '40:3': "The new song is put in his mouth by God, and the effect is on bystanders who never shared the pit.",
    '40:4': "The blessed man is described by what he does not respect, as much as by what he trusts.",
    '40:5': "He sets out to number God's works and gives up inside the sentence.",
    '40:6': "\"Mine ears hast thou opened\" — what God wanted instead of sacrifice was a hearer, not a better offering.",
    '40:7': "\"Lo, I come\" — the answer to a God who does not want sacrifice is a person offering himself instead.",
    '40:8': "Delight and the law within the heart. Obedience is described as appetite before it is described as duty.",
    '40:9': "\"I have not refrained my lips, O LORD, thou knowest.\" He calls God as witness to his own preaching.",
    '40:10': "Righteousness, faithfulness, salvation, lovingkindness, truth — all of them declared rather than kept private.",
    '40:11': "Having told everyone about God's mercy, he asks not to be denied it himself.",
    '40:12': "Evils outside and iniquities inside, and the iniquities are the ones that stop him looking up.",
    '40:13': "After the long thanksgiving, the psalm turns and begs. Past rescue does not settle present need.",
    '40:15': "\"Aha, aha\" is all they say, and he asks for desolation as its reward. The taunt is treated as the offence.",
    '40:16': "The seekers are told to rejoice \"in thee\" — not in the psalmist's vindication.",
    '40:17': "\"I am poor and needy; yet the Lord thinketh upon me.\" The whole psalm balances on that \"yet.\"",

    # ---- Chapter 41 ----
    '41:1': "The blessing is promised to the man who considers the poor — who thinks about them, not merely relieves them.",
    '41:2': "Preservation is set against being handed over to the enemies' will. Deliverance is described as custody.",
    '41:3': "\"Thou wilt make all his bed in his sickness\" — God is pictured doing the work of a nurse.",
    '41:4': "\"Heal my soul; for I have sinned\" — the disease he asks to be cured of is the guilt, not the fever.",
    '41:5': "They want his name to perish as well as his life. Erasure, not just death, is the wish.",
    '41:6': "The visitor speaks kindly at the bedside and carries the news out as gossip.",
    '41:7': "Whispering together — the conspiracy is conducted at the volume of concern.",
    '41:8': "\"Now that he lieth he shall rise up no more.\" They have read his illness as a verdict from God.",
    '41:9': "The friend who ate his bread lifted the heel. Jesus will quote this at a table, about a man still sitting there.",
    '41:10': "\"That I may requite them\" — the prayer is honest about wanting to settle the account himself.",
    '41:11': "Favour is inferred from a negative: the enemy has not triumphed. Assurance is read off what has not happened.",
    '41:12': "\"Settest me before thy face for ever\" — the sick man's hope is a permanent place in God's sight.",
    '41:13': "The doxology closing Book One is addressed to the God of Israel, not to the God of David's rescue only.",
})

TAKEAWAYS.update({
    # ---- Chapter 42 ----
    '42:1': "The hart pants because the brooks are dry. The image is of thirst, not of devotion.",
    '42:2': "\"The living God\" — he thirsts for a person, and what he wants is to appear before him, not to feel better.",
    '42:3': "\"Where is thy God?\" is asked daily, and the tears become the only thing he takes in.",
    '42:4': "What hurts is the memory of good days. He is undone by remembering worship, not by remembering sin.",
    '42:5': "He interrogates his own soul, which means part of him is still able to ask the question.",
    '42:6': "He remembers God from the far country by name of hill and river. Exile is given an address.",
    '42:7': "\"All thy waves and thy billows\" — the flood that is drowning him is God's own.",
    '42:8': "Lovingkindness by day and a song by night, both spoken of in the future while the darkness is present.",
    '42:9': "He calls God his rock in the same sentence as asking why he has been forgotten.",
    '42:10': "The taunt is felt \"as with a sword in my bones.\" A question about God cuts deeper than the enemies' blades.",
    '42:11': "The refrain returns with \"the health of my countenance\" added. The face that was wet with tears is what God mends.",

    # ---- Chapter 43 ----
    '43:1': "He asks God to be his advocate against a whole nation, and then names one deceitful man.",
    '43:2': "\"Thou art the God of my strength: why dost thou cast me off?\" Both halves are said without embarrassment.",
    '43:3': "Light and truth are asked for as guides, personified and sent out ahead of him.",
    '43:4': "\"God my exceeding joy\" — the altar is wanted for the person at it, not for the ritual.",
    '43:5': "The refrain closes the psalm rather than interrupting it. Nothing has changed except where the hope is put.",

    # ---- Chapter 44 ----
    '44:1': "The nation's history reaches them by ear, from fathers who told it. Faith here is inherited testimony.",
    '44:2': "Driving out and planting are one motion. The land was cleared in order that Israel could be put in it.",
    '44:3': "Sword and arm are explicitly denied. The conquest is credited to a face that favoured them.",
    '44:4': "\"Command deliverances\" — the King is asked to issue rescue as an order, the way a king would.",
    '44:5': "Pushing and treading are their verbs, but done \"through thee.\" The agency is shared and the power is not.",
    '44:6': "\"I will not trust in my bow\" — said in the singular by a soldier who still has one.",
    '44:7': "The past-tense saving is set down carefully, because everything after this verse will contradict it.",
    '44:8': "Boasting all the day long in God — and then the psalm's next word is \"But.\"",
    '44:9': "\"Goest not forth with our armies.\" The defeat is described as God's absence from the field, not as bad tactics.",
    '44:10': "Their enemies plunder them \"for themselves.\" The spoil is not even taken for any cause.",
    '44:11': "Sheep appointed for meat. Israel is described as livestock God has designated for slaughter.",
    '44:12': "\"Thou sellest thy people for nought\" — the accusation is not cruelty but a sale at no profit.",
    '44:13': "The shame is social. They are a reproach to the neighbours, among people who have to keep living near them.",
    '44:14': "A byword among the heathen. Their defeat has become a saying other nations use.",
    '44:15': "Confusion is \"continually before me\" and shame has covered his face. Humiliation has become a permanent state.",
    '44:16': "What he cannot bear is not the enemy's sword but the enemy's blasphemy.",
    '44:17': "\"Yet have we not forgotten thee.\" The psalm makes the one claim that removes every easy explanation.",
    '44:18': "Heart and steps both named. They insist the loyalty was inward and outward alike.",
    '44:19': "Broken \"in the place of dragons\" and covered with death's shadow — and still the covenant was kept.",
    '44:20': "The test is offered in the form they would recognise: hands stretched out to a strange god.",
    '44:21': "\"He knoweth the secrets of the heart\" is invoked as their defence, not as a threat to them.",
    '44:22': "\"For thy sake are we killed all the day long\" — Paul will quote it of the church, unchanged.",
    '44:23': "\"Awake, why sleepest thou?\" Scripture keeps a prayer that accuses God of negligence.",
    '44:24': "Hiding the face and forgetting affliction: the two things God is elsewhere praised for never doing.",
    '44:25': "Bellies cleaving to the earth. The nation is described as lying face down in the dirt.",
    '44:26': "The psalm ends with no answer and no confession, only \"for thy mercies' sake.\" Mercy is the last ground left.",

    # ---- Chapter 45 ----
    '45:1': "The poet names his own craft: a heart brimming over and a tongue working like a practised pen.",
    '45:2': "\"Grace is poured into thy lips\" — the king's beauty is located in how he speaks.",
    '45:3': "Sword, glory and majesty are girded on together, as though the splendour were part of the armament.",
    '45:4': "He rides \"because of truth and meekness and righteousness.\" Meekness is listed among the causes of a war.",
    '45:6': "\"Thy throne, O God, is for ever\" — a king is addressed as God, and Hebrews will take the line at its word.",
    '45:7': "Anointing with the oil of gladness follows loving righteousness. The joy is a consequence of the character.",
    '45:8': "Myrrh, aloes and cassia out of ivory palaces. The scene is deliberately sensory, and the psalter keeps it.",
    '45:9': "The queen stands at the right hand in gold of Ophir — the place of honour described by where she is standing.",
    '45:10': "\"Forget also thine own people\" — the bride is told that the marriage costs her the house she came from.",
    '45:11': "Desire and worship in one verse. The king is husband and lord, and the psalm does not separate them.",
    '45:12': "Tyre comes with a gift. The nations arrive at this wedding as petitioners.",
    '45:13': "\"All glorious within\" before the clothing is mentioned. The order of the description is the point.",
    '45:14': "Her companions come with her. Nobody enters this palace alone.",
    '45:16': "Children in place of fathers. The dynasty looks forward rather than back for its honour.",
    '45:17': "The poet promises to make the name remembered, and the psalm itself is how he does it.",

    # ---- Chapter 46 ----
    '46:1': "\"A very present help\" — the point is not that God is strong but that he is at hand when it happens.",
    '46:2': "Fear is refused on the terms of the worst imaginable case: the earth itself giving way.",
    '46:3': "Roaring waters and shaking mountains. The ancient picture of chaos is granted its full noise and then dismissed.",
    '46:4': "Against the roaring sea, a quiet river of streams. The city's water does not rage.",
    '46:5': "\"God is in the midst of her\" — the security is a location, and the help comes early rather than late.",
})

TAKEAWAYS.update({
    '46:6': "The kingdoms rage and he speaks once. Nations move armies; God moves his voice and the earth melts.",
    '46:7': "\"The God of Jacob\" — the name recalls a man who deserved nothing, which is the comfort in it.",
    '46:8': "\"Behold... what desolations he hath made.\" The invitation is to look at ruins and call them God's work.",
    '46:9': "Peace comes by breaking the weapons, not by persuading the armies.",
    '46:10': "\"Be still\" is addressed to the raging nations as much as to the frightened. It is an order to stop.",
    '46:11': "The refrain returns unchanged after the judgement scene. What was true in the earthquake is true after it.",

    # ---- Chapter 47 ----
    '47:1': "\"All ye people\" — the clapping is demanded of the nations, not only of Israel.",
    '47:2': "He is called terrible and great King in one breath. The awe and the rule are the same fact.",
    '47:3': "Subjugation of the nations is sung as good news by the people it favours. The psalm does not hide whose side it is on.",
    '47:4': "\"He shall choose our inheritance for us\" — even what they receive is not theirs to select.",
    '47:5': "\"God is gone up with a shout\" — the ark going up the hill is described as God ascending his throne.",
    '47:6': "\"Sing praises\" four times in one verse. The repetition is the meaning; there is nothing else to say.",
    '47:7': "\"Sing ye praises with understanding.\" Enthusiasm is not enough; the psalm asks for comprehension too.",
    '47:8': "He reigns over the heathen from a throne described by its holiness, not its power.",
    '47:9': "The princes gather as \"the people of the God of Abraham\" — the promise to one man has swallowed the nations.",

    # ---- Chapter 48 ----
    '48:1': "God is great, and he is greatly praised in a particular city. The universal claim has a postcode.",
    '48:2': "\"The joy of the whole earth\" is said of a small hill in a minor kingdom.",
    '48:3': "God is \"known in her palaces for a refuge\" — the city's reputation is not its walls but its resident.",
    '48:4': "\"The kings were assembled, they passed by together.\" The whole invasion is told in eight words.",
    '48:5': "They saw, marvelled, were troubled, hurried away. Nothing is said of a battle because there was not one.",
    '48:6': "Labour pains for an army: the psalm gives the conquerors the one pain they could never share.",
    '48:7': "The ships of Tarshish were the largest afloat. An east wind is all that is named against them.",
    '48:8': "\"As we have heard, so have we seen.\" The inherited story and their own eyes have finally matched.",
    '48:9': "In the temple they think about lovingkindness. What the building is for is remembering.",
    '48:10': "Praise reaches as far as the name does. The limit of God's fame is the limit of his worship.",
    '48:11': "Judah's daughters are told to be glad \"because of thy judgments\" — the verdicts are what they celebrate.",
    '48:12': "Walk round, count the towers. Faith is asked to take a physical inventory.",
    '48:13': "The point of counting the bulwarks is to have something to tell the next generation.",
    '48:14': "After all the walls and towers, what is promised is a guide. The city was never the security.",

    # ---- Chapter 49 ----
    '49:1': "The psalm addresses the inhabitants of the world, not the congregation. This is wisdom offered to everyone.",
    '49:2': "Low and high, rich and poor \"together\" — the audience is mixed on purpose, since the subject levels them.",
    '49:4': "He calls his teaching a dark saying and puts it to the harp. Hard truth is set to music to be carried.",
    '49:5': "The question is why he should fear when his own past sins surround him — not when enemies do.",
    '49:6': "The rich are described by what they trust, not by what they own.",
    '49:7': "\"None of them can by any means redeem his brother.\" The one purchase money cannot make is the important one.",
    '49:8': "The redemption of a soul is called precious and then said to cease for ever. It is priced out of human reach.",
    '49:9': "The thing wealth cannot buy is named plainly: not seeing corruption.",
    '49:10': "Wise men and fools die alike and leave their wealth to others. The observation is available to anyone watching.",
    '49:11': "They name their lands after themselves — the nearest thing to permanence a man can arrange.",
    '49:12': "\"Man being in honour abideth not.\" Honour is exactly the thing that does not survive.",
    '49:13': "Their posterity approve the sayings. The folly is inherited along with the estate.",
    '49:14': "\"Death shall feed on them\" — the shepherd of the grave leads them, and the image is deliberately grotesque.",
    '49:15': "\"But God will redeem my soul\" — the one thing no man could buy for his brother, God does for him.",
    '49:16': "\"Be not thou afraid when one is made rich.\" The instruction assumes another's wealth is frightening.",
    '49:17': "He carries nothing away and his glory does not follow him down. Both halves describe the same empty hands.",
    '49:18': "Men praise you when you do well to yourself. The psalm notes exactly whose approval self-interest buys.",
    '49:19': "\"They shall never see light\" — the fathers' generation is described as a place, and it is dark.",
    '49:20': "The refrain returns with \"understandeth not\" added. What makes a man like the beasts is not dying but not seeing it.",

    # ---- Chapter 50 ----
    '50:1': "God summons the whole earth from sunrise to sunset, and the case he will try is against his own people.",
    '50:2': "\"The perfection of beauty\" is where the fire comes from. The judgement issues out of the sanctuary.",
    '50:3': "\"Shall not keep silence.\" Everything wrong in this psalm has been going on under a silence about to end.",
    '50:4': "Heaven and earth are called as witnesses, which is the form of a covenant lawsuit.",
    '50:5': "The defendants are his saints, gathered by their own covenant made by sacrifice.",
    '50:6': "\"God is judge himself\" — no one else will hear this case, and no one else could.",
    '50:7': "\"I am God, even thy God\" — the relationship is stated before the charge, as the ground of the charge.",
    '50:8': "The sacrifices are not the problem. God clears the ritual before he indicts the worshippers.",
    '50:9': "\"I will take no bullock out of thy house.\" The offering was never something God needed to receive.",
    '50:10': "Cattle on a thousand hills already belong to him, which makes the gift a return, not a supply.",
    '50:11': "He knows the birds of the mountains — the creatures nobody offers and nobody counts.",
    '50:12': "\"If I were hungry, I would not tell thee.\" The sarcasm exposes what the worshippers thought they were doing.",
    '50:13': "The question is left unanswered, because the idea of God eating meat is the point being ridiculed.",
    '50:14': "What is asked instead is thanksgiving and kept vows — things that cannot be delegated to an animal.",
    '50:15': "Calling on him in trouble is listed as worship. Needing God is a way of honouring him.",
    '50:16': "The wicked man's offence is reciting the covenant. The indictment is against the mouth, not the hands.",
    '50:17': "Hating instruction and casting the words behind him — he keeps the text and discards the authority.",
    '50:18': "Consenting with the thief is counted the same as stealing. Approval is named as participation.",
    '50:19': "The mouth that recited the statutes is the mouth that frames deceit.",
    '50:20': "\"Thine own mother's son\" — the slander is aimed at the person with the strongest claim on his loyalty.",
    '50:21': "\"Thou thoughtest that I was altogether such an one as thyself.\" God's patience was read as agreement.",
    '50:22': "The warning is addressed to those who forget God, which is milder than denying him and ends the same way.",
    '50:23': "Praise and an ordered life are put together as the offering that was wanted all along.",

    # ---- Chapter 51 ----
    '51:1': "Mercy is asked for according to God's lovingkindness — no other measure would be survivable.",
    '51:2': "Wash and cleanse: he asks for the removal of a stain, which means he expects to be handled, not excused.",
    '51:3': "\"My sin is ever before me\" — the confession is not new information but a relief from carrying it silently.",
    '51:4': "\"Against thee, thee only\" — not that Uriah was unharmed, but that the offence runs first to God.",
    '51:5': "He traces the sin past the act to his origin. The adultery was a symptom of something older than he is.",
    '51:6': "\"Truth in the inward parts\" is what God desires, and it is exactly what he has not had.",
    '51:7': "Hyssop belonged to the leper's cleansing. He asks to be treated as the unclean man he now knows he is.",
    '51:8': "\"The bones which thou hast broken\" — he credits God with the damage and asks him to make them rejoice.",
    '51:9': "Hiding the face was the complaint of other psalms. Here he asks for it, because of what would be seen.",
    '51:10': "\"Create\" is the verb of Genesis. Nothing less than a making from nothing will serve for a heart.",
    '51:11': "The fear is not punishment but being put out of God's presence. Saul is close enough to remember.",
    '51:12': "He asks for the joy of salvation to be restored, not the salvation. What he lost was the gladness of it.",
    '51:13': "The forgiven man's usefulness is to transgressors. Pardon qualifies him for the work.",
    '51:14': "\"Deliver me from bloodguiltiness\" — the name of what he did is finally said, and it is murder.",
    '51:15': "Even the opening of his lips must be given. He cannot begin the praise he has just promised.",
    '51:16': "\"Else would I give it.\" He would gladly pay in sacrifice, and that is precisely what is not wanted.",
    '51:17': "The broken spirit is called a sacrifice, which makes the one thing he has to offer the one thing accepted.",
    '51:18': "Personal pardon turns outward to the city's walls. His sin was never only his own business.",
    '51:19': "The burnt offerings come back at the end — acceptable once the heart behind them has been remade.",

    # ---- Chapter 52 ----
    '52:1': "\"O mighty man\" is said with contempt. Against his boasting is set the one thing that actually endures.",
    '52:2': "A razor is a grooming tool. The tongue's danger is that it is precise and kept close to the skin.",
    '52:3': "Loving evil more than good: the charge is about preference, not weakness.",
    '52:4': "\"All devouring words\" — speech is described as eating, and the appetite is what he is accused of.",
    '52:5': "Plucked out of his dwelling and rooted out of the land: the man who destroyed by speech is removed bodily.",
    '52:6': "The righteous see, fear, and then laugh. The fear comes first, and it is not for the fallen man.",
    '52:7': "\"Strengthened himself in his wickedness\" — he was getting stronger, and that was the shape of his ruin.",
    '52:8': "A green olive tree lives a long time in one place. Against the uprooted man, the picture is of staying.",
    '52:9': "\"Because thou hast done it\" — the praise is for an act not yet visible, and he says he will wait for it.",

    # ---- Chapter 53 ----
    '53:1': "\"Abominable iniquity\" replaces the works of the earlier version. The second telling names it harder.",
    '53:2': "The search is repeated in the psalter because the result has not changed between the two hearings.",
    '53:3': "\"Every one of them is gone back.\" The word is of turning away, not merely of never having come.",
    '53:4': "They devour God's people and never pray. The two are put side by side as one description.",
    '53:5': "\"Where no fear was\" — the terror that seized them had no external cause. God scattered them with nothing.",
    '53:6': "The same longing closes both versions: salvation must come out of Zion, because it will not come from within.",

    # ---- Chapter 54 ----
    '54:1': "Saved by the name and judged by the strength. He asks for rescue and a verdict in the same breath.",
    '54:2': "\"The words of my mouth\" — the prayer draws attention to itself as spoken, by a man in hiding.",
    '54:3': "\"They have not set God before them.\" The betrayers' real fault is an absence, not an act.",
    '54:4': "\"Behold, God is mine helper\" — the turn comes at the psalm's midpoint, on nothing but assertion.",
    '54:5': "\"Cut them off in thy truth\" — even the destruction asked for is to be an act of God's faithfulness.",
    '54:6': "The freewill offering is promised while the danger is present. Thanks is pledged before delivery.",
    '54:7': "The psalm ends in the past tense. A man still hunted reports the rescue as finished.",

    # ---- Chapter 55 ----
    '55:1': "\"Hide not thyself\" — the fear is not that God cannot help but that he will withdraw from the request.",
    '55:2': "\"I mourn in my complaint, and make a noise.\" The psalm admits the prayer is not composed.",
    '55:3': "They cast iniquity upon him — the accusation is that they are transferring their own guilt onto him.",
    '55:4': "\"The terrors of death are fallen upon me.\" Not death, but the dread of it, is what has landed.",
    '55:5': "Fearfulness, trembling, horror — three words for the same state, piled up because one would not do.",
    '55:6': "\"Oh that I had wings like a dove\" — the most honest wish in the psalter, and it is escape, not victory.",
    '55:7': "The wilderness, elsewhere a place of danger, is here the thing he longs for. Anywhere is better than this.",
    '55:8': "The storm he wants to escape is a human one. The weather in this psalm is other people.",
    '55:9': "\"Divide their tongues\" — he asks for Babel, for the conspiracy to lose the ability to understand itself.",
    '55:10': "Mischief patrols the walls that were built to keep it out.",
    '55:11': "Deceit and guile \"depart not from her streets.\" The corruption has become residential.",
    '55:12': "\"Then I could have borne it.\" He measures the wound by the fact that an enemy's version would have healed.",
    '55:13': "\"A man mine equal, my guide, and mine acquaintance\" — the betrayer is identified by closeness, never by name.",
    '55:14': "They walked to the house of God together. The friendship was religious, which is why the break is total.",
    '55:15': "The curse is immediate and unqualified. The psalter does not edit out what betrayal makes a man want.",
    '55:16': "\"As for me, I will call upon God\" — the only action he takes in the whole psalm is to pray.",
    '55:17': "Evening, morning and noon. The discipline is stated as a schedule, and grief is what fills it.",
    '55:18': "\"There were many with me\" — he was outnumbered by enemies and not, it turns out, alone.",
    '55:19': "\"Because they have no changes, therefore they fear not God.\" An untroubled life is diagnosed as a danger.",
    '55:20': "The breach of covenant is the charge. It was a promise, not just a friendship, that he broke.",
    '55:21': "Butter, oil, and drawn swords. The smoothness is not the opposite of the violence but its delivery.",
    '55:22': "\"Cast thy burden upon the LORD\" — the only line in the psalm addressed to someone other than God.",
    '55:23': "\"But I will trust in thee.\" After the curse on the bloody men, the psalm's last word is about himself.",

    # ---- Chapter 56 ----
    '56:1': "\"Man would swallow me up\" — the enemy is named as man, which already limits him.",
    '56:2': "\"They be many\" is said to the most High. The count is offered to the one it cannot impress.",
    '56:3': "\"What time I am afraid, I will trust in thee.\" Fear is not denied; it is given a scheduled response.",
    '56:4': "He praises God's word while still in danger, then says flesh can do nothing to him. The order matters.",
    '56:5': "They wrest his words daily. The attack is on what he says, twisted into something he did not mean.",
    '56:6': "Gathering, hiding, marking steps: the surveillance is described more carefully than the violence.",
    '56:7': "\"Shall they escape by iniquity?\" He asks whether wickedness can be its own way out, and expects no.",
    '56:8': "Wanderings counted, tears bottled, both written in a book. God is described as keeping records of small griefs.",
    '56:9': "\"This I know; for God is for me.\" The whole psalm rests on a preposition.",
    '56:10': "The line is repeated with the divine name changed. He praises the word under both titles, as if testing it.",
    '56:11': "The refrain returns with \"man\" in place of \"flesh.\" Named either way, the threat is still only human.",
    '56:12': "\"Thy vows are upon me\" — the promises he made under pressure are treated as a weight he is glad to carry.",
    '56:13': "Delivered from death, he asks next to be kept from falling. Survival was not the whole of what he wanted.",
})
