#!/usr/bin/env python3
"""Written takeaways for Psalms 57-104."""

TAKEAWAYS = {
    # ---- Chapter 57 ----
    '57:1': "\"Until these calamities be overpast\" — the refuge is not an end to the trouble but a place to wait it out.",
    '57:2': "He cries to \"God that performeth all things for me\" — the appeal is made to one already finishing the business.",
    '57:3': "Mercy and truth are sent out like a rescue party. God's attributes arrive as the deliverance itself.",
    '57:4': "He lies among lions whose weapons are teeth and tongue. The danger he names is speech.",
    '57:5': "In the middle of asking to be saved he asks instead that God be exalted. The prayer forgets itself.",
    '57:6': "The pit worked exactly as designed. It simply caught the wrong men.",
    '57:7': "\"My heart is fixed\" — said twice, and nothing outside him has changed yet.",
    '57:8': "He gives orders to his own soul and to his instruments, and sets the hour himself.",
    '57:9': "A rescue in a cave gets reported among the nations. Private mercy is not meant to stay private.",
    '57:10': "Mercy reaching to the heavens is the answer to the lions of verse 4 — a larger measurement than the threat.",
    '57:11': "The refrain returns unaltered. What he asked for in terror he asks for again in confidence.",

    # ---- Chapter 58 ----
    '58:1': "The question is put to judges, and its form already contains the verdict.",
    '58:2': "\"Ye weigh the violence of your hands\" — injustice is measured out with the same care justice would take.",
    '58:3': "The psalm traces the lie further back than any particular lie. The problem predates the biography.",
    '58:4': "Poison and a deaf adder in one breath: the venom and the refusal to hear belong together.",
    '58:5': "The adder stops her own ear. Unreachableness here is a choice, not a defect.",
    '58:6': "\"Break their teeth\" — the prayer aims at the weapon rather than at the man holding it.",
    '58:7': "He asks that they melt away like spilled water — not that they suffer, but that they cease.",
    '58:8': "A snail and a stillbirth. Even the curse is for disappearance rather than for pain.",
    '58:9': "Judgement arrives before the cooking fire has caught. It does not wait for the ordinary day to finish.",
    '58:10': "\"He shall wash his feet in the blood of the wicked.\" The Psalter does not soften what vindication looks like.",
    '58:11': "The point of the whole savage prayer is a conclusion men draw: there is a God that judgeth in the earth.",

    # ---- Chapter 59 ----
    '59:1': "Deliver and defend — the two verbs ask for rescue out and for cover where he stands.",
    '59:2': "\"Bloody men\" — he will not use a gentler word for what they intend.",
    '59:3': "\"Not for my transgression, nor for my sin\" — he claims innocence of this charge, which is not innocence in general.",
    '59:4': "He tells God to wake up and look. Prayer in the Psalter is allowed to sound like that.",
    '59:5': "He asks God to show no mercy, and the request is left in the book without apology.",
    '59:6': "Dogs circling the city at nightfall. The menace is not a crisis but a routine.",
    '59:7': "\"Who, say they, doth hear?\" The assumption that nobody is listening is the root of everything else they do.",
    '59:8': "The answer to \"who doth hear\" is laughter from heaven.",
    '59:9': "Strength greater than his own is met by waiting rather than by counter-measures.",
    '59:10': "\"Shall prevent me\" — in this English, God goes ahead of him rather than blocking him.",
    '59:11': "\"Slay them not, lest my people forget.\" A living warning is judged more useful than a dead enemy.",
    '59:12': "Their own mouths supply the evidence. The sentence is built out of what they said.",
    '59:13': "The aim is not revenge but knowledge: that the ends of the earth learn who rules in Jacob.",
    '59:14': "The dogs come back at evening exactly as before. The threat is unchanged; the man singing is not.",
    '59:15': "They prowl for food and grumble when unfed. Stripped of menace, the enemy is merely hungry.",
    '59:16': "They come at evening; he has already booked the morning for singing.",
    '59:17': "Strength, defence, mercy — every title he gives God is a relation, not a description.",

    # ---- Chapter 60 ----
    '60:1': "Defeat is laid at God's door, not the enemy's. The complaint is addressed to the one held responsible.",
    '60:2': "He asks God to heal breaches that the same hand opened.",
    '60:3': "\"The wine of astonishment\" — the hard dealing is pictured as a cup God poured and made them drink.",
    '60:4': "A banner is given in the middle of a rout. Even scattered troops are given something to rally to.",
    '60:5': "The army that has just been cast off is still called \"thy beloved.\"",
    '60:6': "The psalm turns on a word already spoken. Nothing new is revealed; an old promise is remembered.",
    '60:7': "Gilead, Manasseh, Ephraim, Judah — the tribes are listed as God's property, not the king's.",
    '60:8': "Moab a washpot and Edom a place to throw a shoe. God's contempt for the great powers is domestic and casual.",
    '60:9': "The confidence of the oracle ends in a question. He still does not know who will get him into Edom.",
    '60:10': "He asks help from the very God he has just accused of abandoning the armies.",
    '60:11': "\"Vain is the help of man.\" The alternative is weighed openly and found worthless.",
    '60:12': "Valour is credited to God before the battle is fought, which settles who will be thanked after.",

    # ---- Chapter 61 ----
    '61:1': "Cry and prayer are named separately. The noise and the words are both being offered.",
    '61:2': "\"The rock that is higher than I\" — he asks to be led there, admitting he cannot climb it himself.",
    '61:3': "The ground of the request is past tense. What God has been is the argument for what he will be.",
    '61:4': "A tabernacle and a bird's wing in one sentence: the sanctuary and the nest are the same shelter.",
    '61:5': "The heritage is given to those that fear the name. The vows are heard, not purchased with.",
    '61:6': "The singer stops praying for himself and prays for the king's years.",
    '61:7': "Mercy and truth are asked to stand guard over the king. The throne is preserved by God's character, not its own.",
    '61:8': "The singing and the paying of vows are daily and joined. Praise here has an invoice attached.",

    # ---- Chapter 62 ----
    '62:1': "Salvation comes from him, not from the waiting. The posture is not the payment.",
    '62:2': "\"I shall not be greatly moved\" — the admission that he will be moved somewhat is left standing.",
    '62:3': "A bowing wall and a tottering fence — the men doing the pushing are the ones about to come down.",
    '62:4': "They bless with the mouth and curse inwardly. The gap between the two is the whole indictment.",
    '62:5': "He turns the opening line around and says it to his own soul. Faith has to be told things twice.",
    '62:6': "The refrain returns without \"greatly.\" Four verses of talking to himself removed the qualifier.",
    '62:7': "Glory is put in the same place as salvation. His reputation is relocated along with his safety.",
    '62:8': "\"Pour out your heart before him\" — what he has been doing alone is now handed to the crowd as instruction.",
    '62:9': "High degree and low degree both weigh less than nothing. The scale ranks no one above vanity.",
    '62:10': "The danger of increasing riches is not the money but where the heart settles while it happens.",
    '62:11': "\"God hath spoken once; twice have I heard this.\" One word from God, heard properly, counts double.",
    '62:12': "Power belongs to God and so does mercy, and the two are held in one sentence rather than traded off.",

    # ---- Chapter 63 ----
    '63:1': "The wilderness supplies the metaphor. He is thirsty in the ordinary way and says his soul is too.",
    '63:2': "What he saw in the sanctuary is what he now wants in the desert. Memory sets the appetite.",
    '63:3': "\"Thy lovingkindness is better than life\" — the thing everything else is measured against is itself outranked.",
    '63:4': "Blessing God is set for the whole span of his life, with no condition attached about how it goes.",
    '63:5': "Marrow and fatness — a banquet described by a man in a place with no water.",
    '63:6': "The sleepless hours are not endured but used. Night watches become the place of meditation.",
    '63:7': "Joy is grounded in help already given, not in help expected.",
    '63:8': "Following hard and being upheld sit in one sentence. The pursuit and the being carried are the same motion.",
    '63:9': "Those who hunt his life go downward. The psalm's geography is moral.",
    '63:10': "A portion for foxes — left unburied, which in that world was the worst thing that could be said.",
    '63:11': "The psalm ends not with the liars punished but with their mouths stopped. Silence is the sentence.",
}

TAKEAWAYS.update({
    # ---- Chapter 64 ----
    '64:1': "He asks to be preserved from fear of the enemy. The dread is treated as a separate danger from the man.",
    '64:2': "\"Secret counsel\" — he asks to be hidden from people whose whole method is hiding.",
    '64:3': "A whetted tongue and arrows of bitter words. The entire armoury in this psalm is speech.",
    '64:4': "They shoot in secret \"and fear not.\" What makes the ambush possible is the absence of any fear in them.",
    '64:5': "\"Who shall see them?\" They encourage each other first — a conspiracy needs company before it needs a plan.",
    '64:6': "\"The heart, is deep.\" The diligent searchers turn out to be unsearchable themselves.",
    '64:7': "God answers arrows with an arrow. The difference is not the weapon but how suddenly it lands.",
    '64:8': "Their own tongue falls on them. The sword of verse 3 was always pointed the wrong way.",
    '64:9': "Men fear, declare, and \"wisely consider.\" Judgement here produces understanding rather than mere terror.",
    '64:10': "The psalm ends with the upright glorying, not with the plotters ruined. The last word is not about them.",

    # ---- Chapter 65 ----
    '65:1': "\"Praise waiteth for thee\" — it is already there, queued in Sion, before anyone opens his mouth.",
    '65:2': "The title is \"thou that hearest prayer,\" and that alone is what brings all flesh in.",
    '65:3': "\"Iniquities prevail against me\" — he loses that contest openly, and the purging verb belongs to God.",
    '65:4': "Chosen and caused to approach. Both verbs are God's; the blessed man supplies neither.",
    '65:5': "\"Terrible things in righteousness\" — an answer to prayer can be frightening and still be the answer.",
    '65:6': "God is girded with power as a man belts on a garment, and the mountains hold because of it.",
    '65:7': "The roar of the sea and the tumult of the peoples are stilled by the same hand. Noise is noise.",
    '65:8': "Dawn and dusk are made to rejoice. The hinges of the day are given a voice of their own.",
    '65:9': "The rain is \"the river of God, which is full of water\" — supply out of his own store, not a cycle running itself.",
    '65:10': "Ridges, furrows, showers, springing — every verb a farmer would claim is given to God instead.",
    '65:11': "\"Thou crownest the year with thy goodness.\" The harvest is not wages for the year's work but its diadem.",
    '65:12': "Even the wilderness pastures catch the drip. Fertility reaches past the farmed land.",
    '65:13': "The fields shout and sing. The praise that waited in verse 1 is finally performed, and not by people.",

    # ---- Chapter 66 ----
    '66:1': "The summons goes to all lands. Israel's God is addressed as everyone's business from the first line.",
    '66:2': "\"Make his praise glorious\" — praise is something to be worked at, not merely felt.",
    '66:3': "He supplies the words as a script. Awe has to be learned and said before it is owned.",
    '66:4': "Enemies submitting and the earth singing are set down as one outcome, not two.",
    '66:5': "\"Come and see the works of God.\" The invitation is to look before it is to believe anything.",
    '66:6': "\"There did we rejoice in him.\" A generation centuries late says \"we\" about the Red Sea.",
    '66:7': "His eyes are on the nations. The reason the rebellious should not swell is that they are being watched.",
    '66:8': "Praise is to be audible. The command is not to feel gratitude but to let it be heard.",
    '66:9': "Keeping a soul alive and keeping a foot steady are listed beside the parting of a sea.",
    '66:10': "\"Tried us, as silver is tried.\" The image assumes there is silver in the ore worth the fire.",
    '66:11': "\"Thou broughtest us into the net.\" The trap is credited to God, not blamed on the enemy.",
    '66:12': "Men riding over their heads, then fire, then water, then \"a wealthy place.\" The route runs through all of it.",
    '66:13': "The vows are paid in the house with offerings. Gratitude here costs livestock.",
    '66:14': "The vows were made in trouble. Keeping them after the trouble lifted is the rarer thing.",
    '66:15': "Fatlings, rams, bullocks, goats — the list is deliberately more than anyone required of him.",
    '66:16': "After the nation's history, one man's: \"what he hath done for my soul.\"",
    '66:17': "The crying and the extolling come from the same mouth, and he does not rank them.",
    '66:18': "\"If I regard iniquity in my heart\" — the sin that closes God's ear is the one being kept, not the one committed.",
    '66:19': "His evidence that his heart was clear is simply that the prayer was heard.",
    '66:20': "Two things not turned away: his prayer and God's mercy. He blesses God for the pair as one gift.",

    # ---- Chapter 67 ----
    '67:1': "Aaron's blessing is prayed back to God, and then given a purpose it did not originally state.",
    '67:2': "The blessing is asked for so that the nations learn the way. It is requested as something to pass on.",
    '67:3': "The widening is in the second half: not the people, but all of them.",
    '67:4': "The nations are glad because God judges. Judgement is good news to anyone who has lived under bad judges.",
    '67:5': "The refrain comes back. The prayer for the nations is not said once and left behind.",
    '67:6': "The increase follows the praise. The earth's fruit is tied to the world's worship rather than to the weather.",
    '67:7': "The psalm ends abroad. Israel is blessed so that the ends of the earth will fear him.",

    # ---- Chapter 68 ----
    '68:1': "The psalm opens by quoting the words spoken when the ark set out. Worship begins as a marching order.",
    '68:2': "Smoke and melting wax — the wicked do not lose a battle here, they simply cannot stay present.",
    '68:3': "The presence that melts wax makes the righteous exceedingly glad. The same fire, two effects.",
    '68:4': "\"Him that rideth upon the heavens\" is a storm-god's title, taken off the idols and given to JAH.",
    '68:5': "The rider of the heavens is identified by what he is to orphans and widows.",
    '68:6': "The solitary housed, the prisoners freed, the rebellious left in a dry land. Three sentences, three destinies.",
    '68:8': "Sinai itself was moved. The mountain where the law was given could not hold still under the giver.",
    '68:9': "The rain came when the inheritance was weary. The timing is what the verse is about.",
    '68:10': "God's goodness is said to be prepared \"for the poor.\" The provision is aimed at the bottom of the camp.",
    '68:11': "\"The Lord gave the word\" and a great company published it. The news outruns the one who spoke it.",
    '68:12': "The women who stayed home divide the spoil. The plunder does not go to whoever swung the sword.",
    '68:13': "Soot from lying among the pots, and then dove's wings of silver and gold. The change is that extreme.",
    '68:14': "\"White as snow in Salmon\" — after the scattering of kings, an image of clean quiet rather than of triumph.",
    '68:15': "Bashan's great hill is named grandly, and the psalm is setting it up only to pass it over.",
    '68:16': "\"Why leap ye, ye high hills?\" God chose the smaller one, and the great mountains are left staring.",
    '68:17': "Twenty thousand chariots, and the word is \"as in Sinai.\" The mountain has moved into the sanctuary.",
    '68:18': "\"Received gifts for men; yea, for the rebellious also.\" Paul will read this as giving; either way the rebels are on the list.",
    '68:19': "\"Daily loadeth us with benefits\" — the verb is loading, as though goodness were freight.",
    '68:20': "\"The issues from death\" belong to God. Every way out of it is his to open or keep shut.",
    '68:21': "The wound falls on one who \"goeth on still\" in his trespasses. Persistence, not a single fault, is what is struck.",
    '68:22': "From Bashan and from the depths of the sea. Neither height nor drowning puts anyone out of reach.",
    '68:23': "Dogs lapping at blood. The triumph song is not edited to make the victory look clean.",
    '68:24': "The crowd is watching God's procession, not the army's. \"My God, my King, in the sanctuary.\"",
    '68:25': "Singers first, then instruments, then the timbrels. The order of the parade puts the music at the front.",
    '68:26': "\"From the fountain of Israel\" — the whole congregation is traced back to a single spring.",
    '68:27': "Little Benjamin leads and Judah's princes follow. The smallest tribe is given the front place.",
    '68:28': "\"Strengthen, O God, that which thou hast wrought for us.\" The prayer asks God to maintain his own work.",
    '68:29': "Kings bring presents because of a temple. It is the sanctuary, not the army, that draws the tribute.",
    '68:30': "\"Scatter thou the people that delight in war.\" A psalm full of battle ends asking for the end of those who enjoy it.",
    '68:31': "Egypt and Ethiopia arrive with their hands out. The old oppressor comes back as a worshipper.",
    '68:32': "The kingdoms of the earth are commanded to sing. The summons is addressed to governments.",
    '68:33': "\"He doth send out his voice, and that a mighty voice.\" The rider's weapon is speech.",
    '68:34': "\"Ascribe ye strength unto God.\" Nothing is added to him by it; the ascribing changes only the one who does it.",
    '68:35': "Terrible out of his holy places, and the giver of strength to his people. Both come from the same address.",
})

TAKEAWAYS.update({
    # ---- Chapter 69 ----
    '69:1': "\"The waters are come in unto my soul.\" The image is drowning, not discomfort.",
    '69:2': "Mire is worse than water. In deep waters he could at least swim; here there is nothing to push against.",
    '69:3': "\"Mine eyes fail while I wait.\" The waiting is doing its own damage, apart from the enemy.",
    '69:4': "\"I restored that which I took not away.\" He pays for a theft he did not commit, which is the psalm's whole shape.",
    '69:5': "In the middle of protesting his innocence he concedes real folly. The two admissions stand side by side.",
    '69:6': "His worst fear is not his own disgrace but that others who wait on God will be shamed by his example.",
    '69:7': "The reproach came \"for thy sake.\" The loyalty caused the trouble; it did not merely accompany it.",
    '69:8': "A stranger to his brethren, an alien to his mother's children. The isolation begins at home.",
    '69:9': "\"The zeal of thine house hath eaten me up\" — John quotes it of Christ in the temple. Zeal here consumes the man who has it.",
    '69:10': "He fasted and wept, and that itself became the charge against him. Piety supplied the mockery.",
    '69:11': "Sackcloth made him a proverb. Public grief turned into public entertainment.",
    '69:12': "The elders at the gate and the drunks in the street agree about him. Top and bottom of the town, one verdict.",
    '69:13': "\"In an acceptable time\" — he leaves the hour with God in the same breath as he begs for speed.",
    '69:14': "He hands the mire and the deep waters of verse 2 straight back to God as the terms of the request.",
    '69:15': "\"Let not the pit shut her mouth upon me.\" The grave is imagined as something closing, not a place to lie.",
    '69:16': "The appeal rests on God's lovingkindness being good, not on the petitioner's need being great.",
    '69:17': "\"Hide not thy face from thy servant.\" The absence he dreads is worse than the flood he is in.",
    '69:18': "Redemption is asked for as nearness: draw nigh, then redeem. Distance is the thing to be fixed.",
    '69:19': "God already knows the reproach and the shame. The telling is not information but relief.",
    '69:20': "\"I looked for some to take pity, but there was none.\" What broke his heart was the absence of comforters, not the enemies.",
    '69:21': "Gall and vinegar. The Gospels found this verse waiting for them at the cross.",
    '69:22': "The table, the one place a man is safe, is what he asks to become the trap.",
    '69:23': "Darkened eyes and shaking loins — he asks for them exactly what has already happened to him.",
    '69:24': "The wrath is asked to \"take hold,\" as a hand does. Judgement here is grip, not a stroke.",
    '69:25': "\"Let their habitation be desolate\" — Peter will read this line over the empty place of Judas.",
    '69:26': "They persecute a man God has already smitten. Adding to the grief of the wounded is the specific charge.",
    '69:27': "\"Let them not come into thy righteousness.\" He asks that they be shut out of the thing he himself lives by.",
    '69:28': "The book of the living is imagined as a register that can be edited. Names can come off a list.",
    '69:29': "The cursing stops and he is back to \"poor and sorrowful.\" The rage was never the same thing as confidence.",
    '69:30': "The song and the thanksgiving are promised before anything has been delivered.",
    '69:31': "A song pleases the LORD better than an ox with horns and hoofs. The cheapest offering outranks the expensive one.",
    '69:32': "The humble see one man rescued and their own hearts live. Deliverance is contagious across strangers.",
    '69:33': "\"His prisoners\" — the LORD is said to own the people in the cells, not merely to pity them.",
    '69:34': "The private drowning ends with heaven, earth and sea called in. The scale changes completely at the last.",
    '69:35': "One man's rescue ends in cities being built. Personal salvation is not the end of the sentence.",
    '69:36': "The inheritance goes to the seed of servants and to those who love the name. Both terms, not a bloodline alone.",

    # ---- Chapter 70 ----
    '70:1': "No preamble, no address, no ground given. The psalm begins where other psalms have got to by verse ten.",
    '70:2': "He asks that they be turned backward, not struck down. Stopping them would be enough.",
    '70:3': "\"Aha, aha.\" The mockery quoted is not an argument but a noise.",
    '70:4': "Mid-plea he breaks off to ask joy for everyone else who seeks God. The urgency does not make him narrow.",
    '70:5': "\"I am poor and needy.\" The only claim he presents is that he has nothing.",

    # ---- Chapter 71 ----
    '71:1': "Trust and the plea against confusion are one movement. To trust is already to have something at stake.",
    '71:2': "\"Deliver me in thy righteousness\" — God's rightness, not the petitioner's, is the ground of the rescue.",
    '71:3': "A habitation \"whereunto I may continually resort\" — refuge described as somewhere he can keep coming back to.",
    '71:4': "Cruelty is named separately from unrighteousness, as though it were its own category of danger.",
    '71:5': "\"My trust from my youth.\" The relationship is being measured in decades, which is the argument.",
    '71:6': "Held up from the womb. He traces the dependence back past anything he can remember choosing.",
    '71:7': "\"I am as a wonder unto many\" — being a spectacle and having a refuge are said in one breath.",
    '71:8': "A mouth filled all the day with praise is a mouth with no room left for the complaint.",
    '71:9': "The fear is precise: being discarded at the point where he stops being useful.",
    '71:10': "The enemies \"take counsel together.\" Old age brings not solitude but organised opposition.",
    '71:11': "\"God hath forsaken him.\" The attack rests on a theological claim, and that is what makes it bearable to them.",
    '71:12': "Against \"God hath forsaken him\" he does not argue. He asks God to come close and settle it.",
    '71:13': "He asks that they wear the reproach they meant for him. The clothing image is exact.",
    '71:14': "\"Yet praise thee more and more.\" The praise is on a rising curve while nothing outside him has improved.",
    '71:15': "\"I know not the numbers thereof.\" He will not estimate God's mercies, and says so rather than rounding.",
    '71:16': "\"Even of thine only.\" He undertakes to mention one righteousness and no other, his own included.",
    '71:17': "Taught from youth and declaring ever since. The learning and the telling are one continuous occupation.",
    '71:18': "The reason he wants more years is an unfinished report to a generation not yet born.",
    '71:19': "\"O God, who is like unto thee!\" The one exclamation in the psalm is not about his troubles.",
    '71:20': "The God who showed him the sore troubles is the same one who will bring him up. He does not split the two.",
    '71:21': "\"Increase my greatness.\" An unembarrassed request for honour, made without apology.",
    '71:22': "Psaltery and harp are tuned to \"thy truth.\" The music is set to a doctrine, not to a mood.",
    '71:23': "\"My soul, which thou hast redeemed\" — the reason the lips rejoice is stated as an accomplished fact.",
    '71:24': "The enemies are confounded in the past tense, at the end of a psalm that began with them still coming.",

    # ---- Chapter 72 ----
    '72:1': "The prayer for the king asks for God's judgments to be handed over, not for the king's own competence.",
    '72:2': "The poor are written into the job description. A reign is assessed by what happens at the bottom.",
    '72:3': "Mountains bring peace by righteousness. The landscape itself is said to settle when justice does.",
    '72:4': "Breaking the oppressor is listed as part of saving the needy, not as a separate item.",
    '72:5': "The reign is measured against the sun and moon. Nothing shorter is offered as a unit.",
    '72:6': "\"Rain upon the mown grass\" — kingship as weather, arriving on ground that has just been cut back.",
    '72:7': "The righteous flourish \"in his days.\" A ruler's character is treated as a climate other people live in.",
    '72:8': "Sea to sea, river to the ends of the earth. The borders named are the world's, not Israel's.",
    '72:9': "Enemies licking the dust — the one harsh picture in a psalm otherwise full of rain and corn.",
    '72:10': "Tarshish, Sheba and Seba: tribute named from the far edges of the map rather than the near neighbours.",
    '72:11': "All kings falling down. Christian reading has never been able to leave this verse with Solomon.",
    '72:12': "\"For\" — the reason all kings bow is that this one answers the man who has no helper.",
    '72:13': "Sparing the poor is put as a royal act. Restraint, not conquest, is the thing being praised.",
    '72:14': "\"Precious shall their blood be in his sight.\" What poor men's lives are worth to him is the whole measure of the reign.",
    '72:15': "The king who answers the needy is himself prayed for daily. The traffic runs both directions.",
    '72:16': "A handful of corn on a mountain top shakes like Lebanon. Abundance out of a scrap, in the worst ground available.",
    '72:17': "\"Men shall be blessed in him\" — the promise made to Abraham is quietly transferred to this king.",
    '72:18': "The doxology gives the credit to God, \"who only doeth wondrous things,\" directly after praising a king.",
    '72:19': "\"Let the whole earth be filled with his glory.\" The book closes asking for something no king could deliver.",
    '72:20': "\"The prayers of David the son of Jesse are ended.\" An editor's note, left in: a collection has a last page.",
})

TAKEAWAYS.update({
    # ---- Chapter 73 ----
    '73:1': "The conclusion is stated in the first line. The rest of the psalm is how he got back to it.",
    '73:2': "\"My feet were almost gone.\" He publishes the near-fall rather than the recovery.",
    '73:3': "He was envious of people he calls fools. Envy does not require respecting what you envy.",
    '73:4': "\"There are no bands in their death.\" Even their dying appeared to cost them nothing.",
    '73:5': "They are exempt from the troubles that everyone else treats as the price of being alive.",
    '73:6': "Pride worn as a chain and violence as a coat. The vices are being displayed, not hidden.",
    '73:7': "\"More than heart could wish\" — and still they want. Having everything has not ended the appetite.",
    '73:8': "\"They speak loftily.\" What galls him is not the money but the tone that comes with it.",
    '73:9': "Their mouth against heaven, their tongue across the earth. Blasphemy upward and slander sideways.",
    '73:10': "God's own people drift over to them, and what they get from it is a bitter cup wrung out.",
    '73:11': "\"How doth God know?\" Practical atheism stated as a question rather than held as a creed.",
    '73:12': "\"Behold, these are the ungodly, who prosper.\" He sets the fact down flat and leaves it unresolved.",
    '73:13': "\"I have cleansed my heart in vain.\" He books his own piety as a loss, and the wage-logic collapses with it.",
    '73:14': "Plagued all day, chastened every morning. The righteous man's account is a daily deficit.",
    '73:15': "He keeps the doubt to himself for the sake of God's children. Honesty is weighed against what it would do to others.",
    '73:16': "\"It was too painful for me.\" Thinking harder about it made it worse, not clearer.",
    '73:17': "\"Until I went into the sanctuary of God.\" What broke the deadlock was a place, not an argument.",
    '73:18': "The prosperity he envied turns out to be the slippery footing. The height was the danger.",
    '73:19': "\"As in a moment.\" What he resented for years is undone in less time than the resenting took.",
    '73:20': "A dream on waking. Their substance was in the sleep of the onlooker, never in themselves.",
    '73:21': "He goes back and names his own bitterness as the thing that was actually wrong.",
    '73:22': "\"I was as a beast before thee.\" He calls his envy stupidity rather than dressing it as a question.",
    '73:23': "\"Nevertheless I am continually with thee.\" He was being held by the hand throughout the stretch he spent as a beast.",
    '73:24': "Guidance now and reception afterward are one sentence. The counsel and the glory are the same handling.",
    '73:25': "\"Whom have I in heaven but thee?\" The envy is cured by a change of appetite, not by an explanation.",
    '73:26': "Flesh and heart are granted to be failing. The strength is put somewhere that is not himself.",
    '73:27': "Distance from God, not any particular crime, is what he names as the ruin.",
    '73:28': "\"It is good for me to draw near to God.\" The answer to the whole psalm is a clause about proximity.",

    # ---- Chapter 74 ----
    '74:1': "Anger smoking against \"the sheep of thy pasture.\" The relation and the wrath are set against each other.",
    '74:2': "The argument is God's own outlay: he purchased this congregation, and the purchase ought to be protected.",
    '74:3': "\"Lift up thy feet unto the perpetual desolations.\" He asks God to come and walk in the rubble himself.",
    '74:4': "The enemy roars where the congregation used to meet, and plants his standards as the new signs.",
    '74:5': "The wreckers are described as woodsmen at their trade. Demolition is pictured as honest labour.",
    '74:6': "Axes and hammers made the carved work and now break it. The tools are indifferent to which they do.",
    '74:7': "The sanctuary burned is called \"the dwelling place of thy name.\" What was attacked was the name.",
    '74:8': "Every meeting place in the land burned. The aim was not plunder but leaving them nowhere to gather.",
    '74:9': "\"Neither is there among us any that knoweth how long.\" Not knowing the length is named as the sharpest lack.",
    '74:10': "The complaint is made on God's behalf: it is his name being blasphemed, not the psalmist's.",
    '74:11': "\"Pluck it out of thy bosom.\" God is pictured with his hand inside his robe, and told to take it out.",
    '74:12': "\"For God is my King of old.\" The psalm turns at the point where memory is brought in as evidence.",
    '74:13': "Dragons' heads broken in the water. The language of creation myth is borrowed to tell the Exodus.",
    '74:14': "Leviathan is not merely killed but handed out as food. The monster becomes provision for wanderers.",
    '74:15': "He cleaves a fountain open and dries a river up. The same hand does both, which is the point.",
    '74:16': "The night belongs to him as much as the day. The dark hours are not enemy territory.",
    '74:17': "Borders and seasons alike are set. The framework everyone lives inside was drawn on purpose.",
    '74:18': "He asks God to remember, having just spent six verses remembering himself.",
    '74:19': "\"Thy turtledove\" — the nation is named as a small defenceless bird facing a multitude.",
    '74:20': "\"Have respect unto the covenant.\" The last appeal is to a document rather than to sympathy.",
    '74:21': "The aim of the request is that the poor have something to praise for. Vindication is asked as their occasion.",
    '74:22': "\"Plead thine own cause.\" He hands the case back, insisting the reputation at stake is not his.",
    '74:23': "The noise is still increasing when the psalm stops. Nothing has been answered.",

    # ---- Chapter 75 ----
    '75:1': "Thanks doubled, and the reason given is nearness: \"thy name is near.\" Proximity, not outcome.",
    '75:2': "God takes over the speaking. The judging waits for an hour he has already fixed.",
    '75:3': "The earth dissolves and he says he is holding the pillars. The calm of the sentence is the argument.",
    '75:4': "The warning is issued before the judgement, and it is against lifting the horn rather than against crime.",
    '75:5': "\"Speak not with a stiff neck.\" Arrogance is treated as a posture, legible in the body.",
    '75:6': "Three directions named and the fourth pointedly missing. Promotion does not come from any compass point.",
    '75:7': "\"He putteth down one, and setteth up another.\" Promotion here is a judicial act, not a reward.",
    '75:8': "The cup is drunk to the dregs. Nobody is handed a portion; they wring out what is left.",
    '75:9': "His response to the coming judgement is not relief but a promise to keep talking about it.",
    '75:10': "The same horns are cut off and exalted, by the same hand. Height is not the issue; who grants it is.",

    # ---- Chapter 76 ----
    '76:1': "\"In Judah is God known.\" He is known somewhere in particular, which is how anyone comes to know him.",
    '76:2': "Salem — the old name is used, the one that means peace, for the place the weapons are about to break.",
    '76:3': "Not only the arrows and shield but \"the battle\" itself is broken. The fighting is treated as a thing with a neck.",
    '76:4': "\"The mountains of prey\" are the raiders' strongholds, and they are simply outranked.",
    '76:5': "\"None of the men of might have found their hands.\" The strong wake unable to work their own arms.",
    '76:6': "A rebuke puts chariot and horse to sleep. No blow is described because none was needed.",
    '76:7': "The question is left hanging. Nobody is named who could stand, and no answer is offered.",
    '76:8': "The earth's response to judgement from heaven is silence. Fear here takes the form of stillness.",
    '76:9': "God arose \"to save all the meek of the earth.\" The judgement scene turns out to be a rescue.",
    '76:10': "\"The wrath of man shall praise thee.\" Hostility is conscripted, and whatever cannot be used is restrained.",
    '76:11': "Vow and pay, in that order, and the paying is the part that gets the command.",
    '76:12': "He cuts off the spirit of princes, not their armies. What is taken from them is nerve.",

    # ---- Chapter 77 ----
    '77:1': "The voice is mentioned twice. He wants it on record that he made an audible noise about this.",
    '77:2': "\"My soul refused to be comforted.\" The refusal is his own, and he reports it without excusing it.",
    '77:3': "\"I remembered God, and was troubled.\" Most piety will not admit that remembering God can make it worse.",
    '77:4': "God holds his eyes open and he cannot speak. The sleeplessness is attributed, not merely suffered.",
    '77:5': "He goes backwards in time looking for relief, since the present offers none.",
    '77:6': "The song he used to sing at night is now examined rather than sung.",
    '77:7': "\"Will the Lord cast off for ever?\" The question is asked aloud instead of being suppressed as improper.",
    '77:8': "What he fears has failed is the promise, not his feeling about it. The doubt is aimed at the right thing.",
    '77:9': "\"Hath God forgotten to be gracious?\" The dreadful possibility is that grace could slip God's mind.",
    '77:10': "\"This is my infirmity\" — he classes the doubt as weakness and then decides to remember anyway.",
    '77:11': "Remembering is stated as a resolution, not a mood that arrived. He is choosing where to look.",
    '77:12': "Meditating and talking of it together. The private recollection is made to come out of his mouth.",
    '77:13': "\"Thy way, O God, is in the sanctuary.\" The way out of the night is again a place rather than a reason.",
    '77:14': "The strength was \"declared among the people.\" The wonders were done in public, which is why he can appeal to them.",
    '77:15': "Jacob and Joseph named together — the whole family, including the branch that ended up in Egypt.",
    '77:16': "\"The waters saw thee.\" The sea is given eyes, and what it does with them is be afraid.",
    '77:17': "A full storm theophany, arriving in the middle of a psalm about lying awake.",
    '77:18': "Thunder and lightning at the Red Sea, where Exodus reports none. Memory has filled the night with weather.",
    '77:19': "\"Thy footsteps are not known.\" The path through the sea leaves nothing behind to follow.",
    '77:20': "The cosmic storm ends with two men and a flock. Deliverance arrives looking like a shepherd's job.",
})

TAKEAWAYS.update({
    # ---- Chapter 78 ----
    '78:1': "\"My law\" — a singer claims the teacher's place and asks for the attention owed to Moses.",
    '78:2': "\"I will open my mouth in a parable.\" Matthew found this line and gave it to Jesus. History told as a riddle.",
    '78:3': "Before any of the content, the chain is named: heard, known, and told to us by fathers.",
    '78:4': "\"We will not hide them from their children.\" The decision not to hide is the hinge the whole psalm turns on.",
    '78:5': "The testimony came with an instruction attached to it: make this known. Transmission was part of the gift.",
    '78:6': "Three generations inside one sentence. The command reaches children who have not been born yet.",
    '78:7': "Hope, memory and obedience are listed as one outcome, and the memory sits in the middle holding the other two.",
    '78:8': "The aim is that they not resemble their fathers. What gets handed down includes the record of failure.",
    '78:9': "Ephraim went out armed and turned back. Carrying the weapons is not the same as using them.",
    '78:10': "They \"refused to walk\" in the law. The verb is refusal, which requires knowing what was asked.",
    '78:11': "\"They forgat his works.\" Forgetting is named as the mechanism, not as an excuse.",
    '78:12': "The marvellous things were done in their fathers' sight. The forgetting happened to eyewitnesses' children.",
    '78:13': "The waters stood as a heap. The sea did not merely part; it was made to behave like a solid.",
    '78:14': "Cloud by day and fire by night. There was no hour they were left to find the way themselves.",
    '78:15': "Rocks cleft \"as out of the great depths.\" The driest place in the world yields ocean quantities.",
    '78:17': "\"They sinned yet more.\" The miracle increased the sin rather than settling it.",
    '78:18': "They asked \"meat for their lust.\" The request itself, not the refusal of it, is what tempted God.",
    '78:19': "\"Can God furnish a table in the wilderness?\" They ask for a set table, not for survival.",
    '78:20': "They concede the water and doubt the bread. Each miracle is granted and then discounted.",
    '78:21': "The complaint was addressed to nobody in particular, and the LORD heard it.",
    '78:22': "The verdict names unbelief, not ingratitude. What went wrong was a failure to trust his salvation.",
    '78:23': "Heaven is given doors, and they are opened. Provision comes out of a storehouse, not out of nowhere.",
    '78:24': "\"The corn of heaven.\" The manna is classed as grain, ordinary food with an extraordinary address.",
    '78:25': "\"Man did eat angels' food,\" and it changed nothing in him. Diet is not sanctification.",
    '78:26': "East wind and south wind are dispatched like servants. The weather is running an errand.",
    '78:27': "Flesh like dust and birds like sand. The quantities are absurd on purpose.",
    '78:28': "It fell in the middle of the camp, round about their tents. The delivery came to the door.",
    '78:29': "\"He gave them their own desire.\" The most frightening thing in the psalm is an answered prayer.",
    '78:30': "\"While their meat was yet in their mouths.\" The timing is the judgement.",
    '78:31': "The wrath took the fattest and the chosen men. It fell on the best of them, not on the obvious offenders.",
    '78:32': "\"For all this they sinned still.\" Neither the wonders nor the deaths changed anything.",
    '78:33': "The punishment is a life spent on nothing. Days consumed in vanity is a sentence without a scaffold.",
    '78:34': "\"When he slew them, then they sought him.\" The psalm names exactly what produced the revival.",
    '78:35': "They remembered he was their rock. The memory was accurate and came only under the knife.",
    '78:36': "\"They did flatter him with their mouth.\" Repentance conducted as a negotiation.",
    '78:37': "The heart is where the covenant was broken, long before any image was carved.",
    '78:38': "\"Did not stir up all his wrath.\" The restraint is measured, which means there was more he did not use.",
    '78:39': "\"He remembered that they were but flesh.\" God's memory of their frailty is given as the reason for mercy.",
    '78:40': "The verb is grieve. Provocation in the desert is described as something God felt, not merely judged.",
    '78:41': "They \"limited the Holy One of Israel.\" The sin is drawing a boundary around what he is able to do.",
    '78:42': "\"They remembered not his hand.\" Forgetting a hand is different from forgetting a fact.",
    '78:44': "The river that fed Egypt was made undrinkable. The plague struck the source of their confidence.",
    '78:45': "Flies and frogs. The great empire is broken by vermin rather than by an army.",
    '78:46': "The caterpiller took their increase and the locust their labour. A year of work eaten in a day.",
    '78:47': "Hail on the vines and frost on the sycomores. Cold weather deployed in Egypt.",
    '78:49': "Wrath itemised into four words and delivered by messengers. Even the anger is organised.",
    '78:50': "\"He made a way to his anger\" — as though a road had to be cleared before it could travel.",
    '78:51': "The firstborn are called \"the chief of their strength.\" A nation's future is what was taken.",
    '78:52': "One verb changes everything: his own people he \"made to go forth like sheep\" through the same night.",
    '78:53': "\"So that they feared not\" while the sea closed on the pursuers. The same water, two experiences.",
    '78:54': "The mountain is spoken of as purchased by his right hand. The land is described as bought, not seized.",
    '78:55': "The inheritance is divided \"by line\" — surveyed and pegged out. Gift arrives as administration.",
    '78:56': "Arrival in the land changed nothing. The provoking continues on the far side of the promise.",
    '78:57': "\"Like a deceitful bow\" — one that looks sound, draws properly, and sends the arrow somewhere else.",
    '78:58': "High places and graven images. The response named is jealousy, which is a word for love that has a claim.",
    '78:59': "\"Greatly abhorred Israel.\" The psalm does not look for a milder word for what God felt.",
    '78:60': "He forsook Shiloh, the tent he had placed among men. God vacated his own address.",
    '78:61': "The ark is called his strength and his glory, and it goes into enemy hands. He allowed his own capture.",
    '78:62': "\"Was wroth with his inheritance.\" The possession he bought is the one he struck.",
    '78:63': "Young men burned and maidens unmarried. What was cancelled was the next generation, not only this one.",
    '78:64': "\"Their widows made no lamentation.\" So many were dead that the mourning itself could not be staffed.",
    '78:65': "\"The LORD awaked as one out of sleep,\" shouting like a man who has been drinking. The boldest line in the Psalter.",
    '78:66': "He smote them in the hinder parts. The humiliation is chosen to be undignified, and it is permanent.",
    '78:67': "Joseph and Ephraim are passed over. The leading tribe learns that leading is not a tenure.",
    '78:68': "\"The mount Zion which he loved.\" The choice is explained by love and by nothing about the mountain.",
    '78:69': "The sanctuary is built like the earth he established for ever. Permanence is claimed for a building.",
    '78:70': "\"Took him from the sheepfolds.\" The king is fetched out of the work, not out of the court.",
    '78:71': "Following ewes great with young is named as the training. The apprenticeship was in caring for the vulnerable.",
    '78:72': "Integrity of heart and skilfulness of hands. The psalm ends insisting a shepherd needs both.",

    # ---- Chapter 79 ----
    '79:1': "Inheritance, temple, Jerusalem — everything violated is listed as God's property, not the nation's.",
    '79:2': "The corpses are \"thy servants\" and \"thy saints.\" The dead are identified by whose they were.",
    '79:3': "\"There was none to bury them.\" The scandal named is not the killing but what followed it.",
    '79:4': "The neighbours' scorn is listed alongside the massacre, as though shame were its own wound.",
    '79:5': "\"How long, LORD?\" They ask about the duration of the anger, having already granted that it is deserved.",
    '79:6': "The wrath is asked to go to nations \"that have not known thee.\" Ignorance is the ground of the request.",
    '79:7': "\"They have devoured Jacob.\" The case against them is stated in one blunt verb.",
    '79:8': "\"Remember not against us former iniquities.\" The guilt is conceded in the same breath as mercy is asked.",
    '79:9': "\"For thy name's sake\" — the ground of forgiveness offered is God's reputation, not their improvement.",
    '79:10': "\"Where is their God?\" The taunt is the thing they most want answered, ahead of their own relief.",
    '79:11': "\"Those that are appointed to die\" — men on a schedule, and the prayer is aimed at the calendar.",
    '79:12': "Sevenfold into the bosom. The reproach was aimed at God, so the repayment is asked in the same currency.",
    '79:13': "They end by naming what they are: sheep. The promise offered in return is only to keep talking about him.",

    # ---- Chapter 80 ----
    '80:1': "Shepherd of Israel and the one enthroned between the cherubims — the two titles are used in one address.",
    '80:2': "Ephraim, Benjamin and Manasseh — the tribes that marched behind the ark are the ones named.",
    '80:3': "\"Turn us again.\" The turning is asked of God rather than promised by them.",
    '80:4': "\"Angry against the prayer of thy people.\" What seems to provoke him is the praying itself.",
    '80:5': "Bread of tears and tears to drink, \"in great measure.\" Grief is served out as rations.",
    '80:6': "The neighbours quarrel over them and the enemies laugh. The humiliation here is entirely social.",
    '80:7': "The refrain returns with \"of hosts\" added. The title grows each time the request is refused.",
    '80:8': "\"Thou hast brought a vine out of Egypt.\" The nation is described as something transplanted, not native.",
    '80:9': "Room prepared and deep root before any fruit. The planting was thorough long before it was productive.",
    '80:10': "Boughs like the goodly cedars. A vine is being described in the vocabulary reserved for great trees.",
    '80:11': "From the sea to the river. The borders of an empire are drawn as the reach of one plant.",
    '80:12': "\"Why hast thou then broken down her hedges?\" The vinedresser is accused of pulling down his own fence.",
    '80:13': "A boar and a wild beast do the damage. The destroyers are animals, which cannot be reasoned with or blamed.",
    '80:14': "Look down, behold, visit. Three verbs, all asking only that God pay attention to what he planted.",
    '80:15': "\"The branch that thou madest strong for thyself.\" The vine was grown for his own use, not theirs.",
    '80:16': "Burned and cut down — and then they perish \"at the rebuke of thy countenance,\" not at the enemy's hand.",
    '80:17': "A vine was described; a man is asked for. \"The son of man whom thou madest strong for thyself.\"",
    '80:18': "\"Quicken us, and we will call.\" The life has to arrive first; the calling is what follows it.",
    '80:19': "The refrain a third time under the fullest title. Nothing in the request has changed but the name used.",

    # ---- Chapter 81 ----
    '81:1': "The command is to sing aloud. Volume is part of what is being asked for.",
    '81:2': "Timbrel, harp and psaltery are commandeered. The instruments are told where to be.",
    '81:3': "The trumpet at the new moon. The calendar itself is made to issue the summons.",
    '81:4': "\"This was a statute.\" The feast is law. Joy here is commanded, not waited for.",
    '81:5': "\"A language that I understood not.\" Egypt is remembered as incomprehensible noise around them.",
    '81:6': "The rescue is described by what the hands stopped carrying. Freedom measured in removed weight.",
    '81:7': "Answered in the secret place of thunder, proved at Meribah. He delivers and he tests, in one sentence.",
    '81:8': "\"If thou wilt hearken unto me.\" The festival sermon opens with a condition, not a promise.",
    '81:9': "The first commandment is read out at a feast, where no one expected to be examined.",
    '81:10': "\"Open thy mouth wide, and I will fill it.\" The only thing required of them is appetite.",
    '81:11': "\"Israel would none of me.\" What was refused was a person, not a set of rules.",
    '81:12': "\"I gave them up unto their own hearts' lust.\" The punishment is being allowed to have what you wanted.",
    '81:13': "\"Oh that my people had hearkened unto me.\" God is given a sentence of pure regret.",
    '81:14': "\"I should soon have subdued their enemies.\" The word is soon. The help that never came was close.",
    '81:15': "The haters would have submitted, and Israel's own time would have run on for ever.",
    '81:16': "Finest wheat and honey out of the rock — and all of it in a tense that never happened.",

    # ---- Chapter 82 ----
    '82:1': "God stands among the judges and judges them. The bench itself is in the dock.",
    '82:2': "\"Accept the persons of the wicked.\" Partiality, not bribery, is named as the court's specific sin.",
    '82:3': "The duty is stated positively. A judge is charged with defending, not merely with not harming.",
    '82:4': "\"Rid them out of the hand of the wicked.\" Justice is asked to be a rescue, not only a verdict.",
    '82:5': "Corrupt courts are described as the foundations of the earth going out of course. The damage is structural.",
    '82:6': "\"Ye are gods\" — Jesus takes this verse up in John 10, and it is addressed to men who are failing.",
    '82:7': "\"But ye shall die like men.\" The title granted in verse 6 exempts nobody from the common end.",
    '82:8': "The psalm ends by handing the whole bench over: \"thou shalt inherit all nations.\"",
})

TAKEAWAYS.update({
    # ---- Chapter 83 ----
    '83:1': "Three ways of asking for the same thing. What is unbearable is not the enemy but God's silence.",
    '83:2': "They are called \"thine enemies\" in the second line of the psalm. The quarrel is assigned before it is described.",
    '83:3': "\"Thy hidden ones\" — the people are spoken of as something God keeps out of sight and means to keep.",
    '83:4': "The stated aim is that the name be no more remembered. Erasure, not conquest, is what they want.",
    '83:5': "\"They are confederate against thee.\" A coalition aimed at a small nation is read as aimed at God.",
    '83:6': "Edom and the Ishmaelites head the list. The alliance against Israel begins with its own relatives.",
    '83:8': "Assur joins in as the junior partner, helping the children of Lot. The superpower has come to assist.",
    '83:9': "Midian, Sisera and Jabin are cited like case law. Old deliverances are produced as precedent.",
    '83:10': "\"They became as dung for the earth.\" Even in ruin the enemy is put to some use.",
    '83:11': "Four names of beaten chiefs, offered as a template. He asks for a repeat rather than for something new.",
    '83:12': "Their motive is quoted: to take the houses of God into possession. It is a property grab with a theology.",
    '83:13': "\"Make them like a wheel\" — the curse is restlessness, spinning with nothing to hold.",
    '83:14': "A fire loose in a wood. The image is not of a strike but of something that cannot be stopped once lit.",
    '83:15': "\"Make them afraid with thy storm.\" Fear itself is requested as the weapon.",
    '83:16': "The shame is asked for \"that they may seek thy name.\" The curse turns out to have a missionary purpose.",
    '83:17': "Two verses after asking that they seek him, he asks that they perish. The psalm does not resolve it.",
    '83:18': "The whole savage prayer ends wanting one thing known: that the name alone is JEHOVAH.",

    # ---- Chapter 84 ----
    '84:1': "The affection is for a building. \"How amiable are thy tabernacles\" is said about architecture.",
    '84:2': "Heart and flesh both cry out. The longing is not described as a purely inward thing.",
    '84:3': "A sparrow has what the singer has not: a permanent address at the altar. He envies a bird.",
    '84:4': "The blessedness of those who live there is that they never stop praising. That is offered as the reward.",
    '84:5': "\"In whose heart are the ways of them\" — the pilgrimage begins as a road map carried inwardly.",
    '84:6': "The valley of Baca becomes a well by being walked through. The dryness is not removed but used.",
    '84:7': "\"From strength to strength.\" The journey adds to them rather than spending what they set out with.",
    '84:8': "The hymn breaks off into a plain request. Even a psalm about longing has to stop and ask.",
    '84:9': "\"Look upon the face of thine anointed.\" The one petition in the psalm is made on the king's behalf.",
    '84:10': "A doorkeeper's post inside beats a dwelling anywhere else. The lowest job in the right house wins.",
    '84:11': "Sun and shield in one breath: the thing that gives light also stands between him and it.",
    '84:12': "The psalm ends on trusting rather than on arriving. He never says he reached the courts.",

    # ---- Chapter 85 ----
    '85:1': "The argument opens with what God has already done. Past favour is the ground for the request to come.",
    '85:2': "\"Thou hast covered all their sin.\" Forgiveness here is covering, which is not the same as overlooking.",
    '85:3': "God turned himself from his own anger. The ending of the wrath is credited to him, not to their repentance.",
    '85:4': "\"Turn us.\" Having said God turned himself, they ask to be turned in the same way.",
    '85:5': "\"Wilt thou be angry with us for ever?\" The question is asked by people who have just recited the pardon.",
    '85:6': "The stated purpose of reviving is that the people may rejoice in him. Revival is for the sake of the joy.",
    '85:7': "Mercy shown and salvation granted are asked in one line, as if the seeing and the getting were one act.",
    '85:8': "\"I will hear what God the LORD will speak.\" The psalm stops petitioning and waits.",
    '85:9': "Salvation's aim is \"that glory may dwell in our land.\" The rescue is so that God can move in.",
    '85:10': "Mercy and truth meeting, righteousness and peace kissing — four things that had every reason to be at odds.",
    '85:11': "Truth comes up out of the ground and righteousness looks down. They arrive from opposite directions.",
    '85:12': "The harvest follows the meeting in verse 10. The land's yield is tied to a reconciliation, not to weather.",
    '85:13': "Righteousness goes ahead of him and makes a road. It is the herald here, not the barrier.",

    # ---- Chapter 86 ----
    '86:1': "\"For I am poor and needy.\" The qualification he offers is that he has none.",
    '86:2': "\"For I am holy\" sits next to a plea for mercy without any embarrassment at the pairing.",
    '86:3': "Daily crying is offered as an argument. Persistence is presented as though it counted for something.",
    '86:4': "He lifts up his soul and asks God to make it glad. The lifting is his part; the gladness is not.",
    '86:5': "\"Ready to forgive\" — God is described as already poised for it, waiting on the asking.",
    '86:7': "\"For thou wilt answer me.\" The certainty is given as the reason for calling, not as its result.",
    '86:8': "Incomparability is argued from the works, not from theory. He compares records rather than definitions.",
    '86:9': "The claim on the nations rests on having made them. Creation is the title deed.",
    '86:10': "\"Thou art God alone.\" The sentence is short because there is nothing to qualify.",
    '86:11': "\"Unite my heart to fear thy name.\" He asks for the division inside himself to be repaired by God.",
    '86:12': "Praise with the whole heart — which is exactly what the previous verse asked to be made possible.",
    '86:13': "The deliverance from the lowest hell is in the past tense, stated before the present trouble is named.",
    '86:14': "\"Have not set thee before them.\" What makes violent men violent is traced to what is missing from view.",
    '86:15': "He quotes God's own self-description from Sinai back to him. The words were given to be used this way.",
    '86:16': "\"The son of thine handmaid\" — he claims a place in the household by birth, not by achievement.",
    '86:17': "He asks for something visible, and the reason given is what his enemies would see, not his own comfort.",

    # ---- Chapter 87 ----
    '87:1': "The foundation is his before anyone builds. The city is God's project, not a thing offered to him.",
    '87:2': "Zion's gates are loved more than all the dwellings of Jacob. A preference is stated inside the family.",
    '87:3': "The city is addressed directly, as a person. \"Glorious things are spoken of thee.\"",
    '87:4': "Rahab, Babylon, Philistia, Tyre, Ethiopia — the old enemies are issued birth certificates.",
    '87:5': "\"This and that man was born in her.\" Citizenship is granted by birth to people who were born elsewhere.",
    '87:6': "The LORD keeps the register himself. The census of Zion is not taken by the city.",
    '87:7': "\"All my springs are in thee.\" The singers say the source is in the city rather than in themselves.",

    # ---- Chapter 88 ----
    '88:1': "\"God of my salvation\" — the title is kept in the one psalm that never gets any.",
    '88:2': "He asks only that the prayer arrive. The request is for delivery, not yet for an answer.",
    '88:3': "The life draws nigh to the grave. He reports proximity, not arrival, which is worse.",
    '88:4': "Counted with those going down into the pit while still alive. The reckoning has already been made.",
    '88:5': "\"Free among the dead\" — a freedom that consists of being released from everything, God's hand included.",
    '88:6': "Lowest pit, darkness, deeps — and the verb is \"thou hast laid me.\" He knows whose hand put him there.",
    '88:7': "\"All thy waves.\" Nothing is said to have been held back, which is the most honest line in the psalm.",
    '88:8': "The friends are gone and God is named as the one who moved them. The loneliness is attributed.",
    '88:9': "Hands stretched out daily, and no answer is recorded anywhere in the psalm.",
    '88:10': "\"Shall the dead arise and praise thee?\" He argues that his death would cost God a worshipper.",
    '88:11': "Lovingkindness and faithfulness need somewhere to be declared. He says the grave is not it.",
    '88:12': "\"The land of forgetfulness.\" The dreadful thing about death here is that nothing there remembers.",
    '88:13': "\"In the morning shall my prayer prevent thee.\" He keeps the appointment though nothing has come of it.",
    '88:14': "\"Why hidest thou thy face from me?\" The question is put and the psalm never answers it.",
    '88:15': "\"From my youth up.\" This is not an episode he is passing through but the whole shape of his life.",
    '88:16': "The terrors themselves have cut him off. The wrath is not a blow but the thing doing the isolating.",
    '88:17': "Daily, like water, and \"together.\" The trouble is not one thing arriving but a circle closing.",
    '88:18': "\"Mine acquaintance into darkness.\" The psalm ends there, with no turn. The Psalter allows one prayer that does not lift.",
})

TAKEAWAYS.update({
    # ---- Chapter 89 ----
    '89:1': "The psalm that will end in accusation opens by promising to sing of mercy for ever.",
    '89:2': "Mercy is spoken of as masonry, built up; faithfulness is fixed in the sky, where no weather reaches it.",
    '89:3': "God is quoted swearing. The covenant enters the psalm as first-person speech rather than as history.",
    '89:4': "The promise covers a family line and a chair, two things that ordinarily outlast nobody.",
    '89:5': "The heavens praise the wonders and the congregation praises the faithfulness. Two choirs, two subjects.",
    '89:7': "The fear is located in the assembly of the saints. The people nearest him are the ones told to tremble.",
    '89:8': "What is finally found incomparable is not the strength but the faithfulness wrapped round about him.",
    '89:9': "The credential offered for the covenant is mastery of the sea, the least governable thing there is.",
    '89:10': "Rahab is Egypt, remembered as a corpse. The Exodus is entered as evidence in a covenant argument.",
    '89:11': "Ownership is established before anything is promised. He gives David what was already his to give.",
    '89:12': "Tabor and Hermon are named and told to rejoice. The landscape is conscripted as a witness.",
    '89:14': "Justice and judgment are the floor of the throne; mercy and truth walk ahead of it. Even the furniture is moral.",
    '89:15': "The joyful sound is something known, not merely heard. Blessedness here is being able to recognise it.",
    '89:16': "They are exalted in his righteousness, not in any of their own. The lifting is done on borrowed ground.",
    '89:17': "\"Thou art the glory of their strength.\" Even what strength they have is credited elsewhere.",
    '89:18': "The shield is the LORD's and the king is the LORD's. Israel owns neither thing it leans on.",
    '89:19': "The dynasty begins with a vision granted to somebody else. David hears of his own election second-hand.",
    '89:20': "\"I have found David my servant.\" The finding is God's verb and the oil is God's; nothing here is David's doing.",
    '89:22': "The promise is that no enemy shall exact upon him. It is protection from creditors, not from trouble.",
    '89:24': "Faithfulness and mercy, the two words the psalm will later accuse him of withdrawing, are pledged here by name.",
    '89:25': "A hand on the sea and on the rivers: the borders promised are the ones Israel never actually held.",
    '89:26': "God writes the king's reply in advance, down to the word father. The answer is scripted with the gift.",
    '89:27': "Firstborn is conferred rather than inherited. David was the eighth son and is made the first.",
    '89:28': "The covenant is put into God's own keeping, which is exactly what verse 39 will say went wrong.",
    '89:30': "The terms anticipate the children forsaking the law. Failure is written into the contract, not discovered later.",
    '89:32': "Rod and stripes are the penalty, and they are the whole penalty. Discipline is substituted for cancellation.",
    '89:33': "\"Nevertheless.\" The hinge of the covenant is a word that overrides everything just conceded.",
    '89:34': "What has gone out of his lips he will not alter. He binds his own freedom and says so.",
    '89:35': "He swears by his holiness because there is nothing higher to swear by. The oath's only security is himself.",
    '89:36': "The throne is measured against the sun, which no one has ever had to keep running.",
    '89:37': "The moon is appointed a faithful witness. The covenant is given a guarantor that hangs in the sky nightly.",
    '89:38': "\"But thou hast cast off.\" One word turns thirty-seven verses of promise into an indictment.",
    '89:39': "\"Thou hast made void the covenant.\" The psalm says plainly the thing verse 34 said could not occur.",
    '89:40': "The hedges come down by the same hand that promised to strengthen the arm inside them.",
    '89:41': "The anointed has become roadside plunder. Anyone passing helps himself, and the neighbours watch.",
    '89:42': "The adversary's right hand is the one exalted. The verb of blessing is turned round and aimed the other way.",
    '89:43': "The sword's edge is turned by God rather than by the enemy. Even the defeat is attributed upward.",
    '89:44': "The crown promised the permanence of the sun is described lying on the ground.",
    '89:45': "The days of his youth are shortened. The occupant of an everlasting throne is said to have aged early.",
    '89:46': "\"For ever\" was the covenant's word. Here it is used of the hiding instead.",
    '89:47': "The complaint widens past the king to every man: if life runs this short, why was it made at all.",
    '89:48': "The question whether any man escapes the grave is asked by someone holding a promise of an endless throne.",
    '89:49': "\"Where are thy former lovingkindnesses?\" The psalm's real question, and nothing in it answers.",
    '89:50': "The reproach is carried in the bosom, held against the chest rather than kept at arm's length.",
    '89:51': "The mockery follows the footsteps of the anointed. What is being taunted is the promise itself.",
    '89:52': "A doxology closing Book III is bolted onto a psalm that never recovered. The editors let both stand.",

    # ---- Chapter 90 ----
    '90:1': "Before a word about how short life is, God is called a dwelling place. The homeless generations had an address.",
    '90:2': "From everlasting to everlasting is said of him alone. The mountains, in this psalm, are latecomers.",
    '90:3': "\"Return, ye children of men.\" Dying is not an accident here but an instruction to go back.",
    '90:4': "A thousand years are yesterday to him, and yesterday is the day nothing can be done about any more.",
    '90:5': "Flood, sleep, grass: three pictures of the same brevity, and not one of them puts up a fight.",
    '90:7': "The shortness of life in this psalm is not biology. It is traced directly to anger.",
    '90:8': "Secret sins are set in the light of his countenance. They are not discovered so much as lit.",
    '90:9': "\"As a tale that is told.\" A life ends the way a story does, by having no more of it.",
    '90:10': "Seventy years, or eighty with strength, and the extra decade is labour and sorrow. The bonus is not called a kindness.",
    '90:11': "Nobody gauges the anger rightly, and the only measure offered for it is the fear.",
    '90:12': "The prayer is not for more days but for the arithmetic. Numbering is what makes the heart teachable.",
    '90:13': "\"Return, O LORD.\" The verb spoken over man in verse 3 is turned round and asked of God.",
    '90:14': "Mercy is asked for early, at the start of the day, so that the rest of it has something to stand on.",
    '90:15': "Gladness is requested in the same measure as the affliction. He wants the books balanced, not exceeded.",
    '90:16': "The work is to appear to the servants and the glory to their children. He does not ask to see both himself.",
    '90:17': "The psalm most honest about brevity ends asking that ordinary handwork be made to last. It asks twice.",

    # ---- Chapter 91 ----
    '91:1': "Secret place and shadow are both pictures of being unseen. That is where this psalm puts safety.",
    '91:2': "\"I will say of the LORD.\" The security starts with something the man says out loud.",
    '91:3': "The fowler's snare is malice and the pestilence is nobody's fault. Both are named in one breath.",
    '91:4': "Feathers and a buckler in one verse, and the thing called a shield is his truth.",
    '91:5': "The terror by night is listed before the arrow by day. What cannot be seen comes first.",
    '91:7': "A thousand fall alongside him. The promise is not that none die but that this one does not.",
    '91:8': "He sees the reward of the wicked with his own eyes. Being spared includes watching what he was spared.",
    '91:9': "Everything hangs on \"because.\" Making the most High a habitation is the condition, not the reward.",
    '91:11': "The angels are given charge. They are under orders here, not doing anybody a favour.",
    '91:12': "What the angels are posted against is a stone under the foot. The disaster guarded against is small.",
    '91:13': "Lion and adder: the danger that is obvious and the danger that is not, trodden by the same foot.",
    '91:14': "God speaks for the first time only at verse 14, and what he says turns on a love already set on him.",
    '91:15': "\"I will be with him in trouble.\" The rescue includes company inside it, not only an exit from it.",
    '91:16': "The last thing promised is not safety but sight: he is to be shewn the salvation.",
})

TAKEAWAYS.update({
    # ---- Chapter 92 ----
    '92:1': "Thanksgiving is called a good thing rather than a debt discharged. The case made is for fitness, not obligation.",
    '92:2': "Lovingkindness in the morning, faithfulness every night. The two halves of the day are given different attributes.",
    '92:3': "Ten strings, psaltery, harp. The gratitude is specified down to the instruments it is played on.",
    '92:4': "The gladness comes through his work. What produced it is outside the singer entirely.",
    '92:5': "Great works and deep thoughts in one line: what he does can be seen, what he means cannot.",
    '92:6': "The brutish man is not called wicked but ignorant. The failure being described is one of understanding.",
    '92:7': "The wicked spring up like grass, and the whole force of the comparison is in how grass finishes.",
    '92:8': "One short line sits in the middle of all the rise and fall, and the rest of the psalm leans on it.",
    '92:10': "Fresh oil and a lifted horn. He is re-anointed rather than merely rescued.",
    '92:11': "Eye and ear are both promised their desire. The psalm does not pretend this satisfaction is unwanted.",
    '92:12': "The righteous are compared to trees, which grow slowly and do it standing in one place.",
    '92:13': "Planted in the house of the LORD. The flourishing is credited to where they are, not to their vigour.",
    '92:14': "Fruit in old age. The productivity promised is at the point of life where none is expected.",
    '92:15': "The flourishing exists as evidence. It is there \"to shew that the LORD is upright.\"",

    # ---- Chapter 93 ----
    '93:1': "The world holds still because he is girded. Stability out there is traced to what he is wearing.",
    '93:2': "The throne is older than the world just called unmovable. Precedence, not only power, is being claimed.",
    '93:3': "The floods lift up their voice three times over. The threat is given its full say before anything answers it.",
    '93:4': "The answer to the noise of many waters is not more noise. It is height.",
    '93:5': "A psalm about floods ends on testimonies and holiness. The sea wall offered is his word and his house.",

    # ---- Chapter 94 ----
    '94:1': "Vengeance is said to belong to God, which is one way of saying it does not belong to the man praying.",
    '94:2': "\"Render a reward to the proud.\" What is asked for is payment rather than destruction.",
    '94:3': "The complaint is not that the wicked exist but that they have been triumphing this long.",
    '94:4': "What is named first is the talking. Hard words and boasting come before any account of what they do.",
    '94:5': "The people broken in pieces are called his heritage. The injury is described as damage to God's property.",
    '94:6': "Widow, stranger, fatherless. The three the law singled out for protection are the three singled out for murder.",
    '94:7': "They do not deny that God exists. They deny that he is paying attention.",
    '94:8': "The answer to practical atheism is addressed to fools, and its first word is Understand.",
    '94:9': "The argument runs from the organ back to its maker. Having planted the ear is treated as proof of hearing.",
    '94:11': "The thoughts God knows turn out to be vanity. Being thoroughly known is not flattering here.",
    '94:12': "Chastening and teaching sit in one line, and the man on the receiving end of both is called blessed.",
    '94:13': "The discipline is for rest, and it runs only until the pit is dug. Even its end is dated.",
    '94:14': "\"The LORD will not cast off his people.\" The flat sentence is what the how-long was waiting for.",
    '94:15': "Judgment is to return unto righteousness. The two had come apart, and the psalm expects them back together.",
    '94:16': "He asks who will stand up for him, and no one does. The next verse names God instead of a volunteer.",
    '94:17': "\"My soul had almost dwelt in silence.\" He measures the distance he came to it and calls it almost.",
    '94:18': "The mercy arrives at the words \"my foot slippeth,\" not after the fall.",
    '94:19': "The trouble named is the multitude of thoughts within. What meets it is comfort rather than rescue.",
    '94:20': "\"Which frameth mischief by a law.\" The psalm knows wickedness can be legislated and still be wickedness.",
    '94:21': "They gather together and condemn innocent blood. The injustice is collective and procedural, not a private crime.",
    '94:22': "After the whole complaint, the confession comes down to two nouns: defence and rock.",
    '94:23': "Their own iniquity is brought upon them. The punishment is the thing they had already made.",

    # ---- Chapter 95 ----
    '95:1': "A loud invitation addressed to a rock. The noise is directed at the least movable thing available.",
    '95:2': "Thanksgiving is how one comes before the presence. The order is given: gratitude first, then the room.",
    '95:3': "A great King above all gods. The other gods are not denied in this line, only ranked.",
    '95:4': "Deep places and the strength of the hills. The two extremes are named to take in everything between.",
    '95:5': "\"The sea is his, and he made it.\" The title is argued from having made the thing.",
    '95:6': "Worship, bow down, kneel: three verbs about the body, in a psalm that opened with a joyful noise.",
    '95:7': "The sentence breaks mid-verse, from the sheep of his hand straight into \"To day if ye will hear his voice.\"",
    '95:8': "\"Harden not your heart.\" The danger warned against is something done to oneself, not suffered.",
    '95:9': "They tempted him after they saw the work. The evidence had already been supplied and did not hold.",
    '95:10': "Forty years of grief, and the diagnosis is erring in the heart rather than failing in conduct.",
    '95:11': "The invitation psalm closes on an oath of exclusion. The rest being offered is one others were refused.",

    # ---- Chapter 96 ----
    '96:1': "The new song is required of all the earth. The choir is enlarged before the singing begins.",
    '96:2': "Salvation is to be shewn forth from day to day. The telling is daily rather than occasional.",
    '96:3': "The glory is declared among the heathen. The audience for the praise is the people who do not share it.",
    '96:4': "Praise and fear are set side by side. The greatness that draws the song is the same greatness that alarms.",
    '96:5': "The gods of the nations were made; the LORD made the heavens. The contrast is carried by one verb.",
    '96:6': "Strength and beauty are both in the sanctuary, and the verse does not treat them as rivals.",
    '96:8': "They bring an offering into his courts. The nations are handed a liturgy, not merely an opinion.",
    '96:9': "The beauty of holiness and fear before him, asked of the whole earth in the same breath.",
    '96:10': "The message for the heathen is that he reigns, and its consequence is that the judging will be righteous.",
    '96:11': "Heavens, earth and sea are told to rejoice. The joy is assigned to things with no ears.",
    '96:13': "The trees rejoice because he comes to judge. Judgement is the good news of this psalm, not its threat.",
})

TAKEAWAYS.update({
    # ---- Chapter 97 ----
    '97:1': "The gladness commanded reaches the isles, the furthest and least governed places on the map.",
    '97:2': "Clouds and darkness round about him, righteousness underneath the throne. What is hidden and what is settled share a verse.",
    '97:3': "The fire goes before him. The approach itself does the burning, before a word of sentence is spoken.",
    '97:4': "Lightning is treated as information. The earth saw, and what it did next was physical.",
    '97:5': "The hills melt like wax. The things people reach for as images of permanence are the ones running.",
    '97:6': "The heavens declare and the people see it. The announcement is published with nobody preaching it.",
    '97:7': "The idolaters are confounded and the gods themselves are told to worship. The rivals are conscripted, not abolished.",
    '97:8': "Zion is glad because of the judgments. What makes the earth tremble is what cheers the city.",
    '97:10': "Love of the LORD arrives with a duty attached, and the duty is to hate something.",
    '97:11': "Light is sown, not shone. The gladness is planted now and comes up at another time.",
    '97:12': "Thanks are given at the remembrance of his holiness, which is usually the attribute that frightens.",

    # ---- Chapter 98 ----
    '98:1': "The new song is owed to something already finished. The marvellous things come before the singing.",
    '98:2': "The righteousness is openly shewed in the sight of the heathen. It is published, not merely possessed.",
    '98:3': "Mercy remembered toward Israel is what the ends of the earth end up seeing. The particular becomes the exhibit.",
    '98:6': "Trumpets and cornet before the LORD, the King. These are coronation instruments, not temple ones.",
    '98:8': "The floods clap their hands. Water that threatens everywhere else in the Psalter is applauding here.",
    '98:9': "The judging is to be done with equity, an even hand. What is promised the world is fairness, not leniency.",

    # ---- Chapter 99 ----
    '99:1': "The same announcement that made the isles glad makes the people tremble. The reaction here is fear.",
    '99:2': "Great in Zion and high above all the people. He is placed in one town and over every town at once.",
    '99:3': "The name is called great and terrible in one line, and the reason offered for both is that it is holy.",
    '99:4': "\"The king's strength also loveth judgment.\" Power is credited with an affection, and it is for fairness.",
    '99:5': "Worship at his footstool. The worshipper is positioned at the lowest piece of the furniture.",
    '99:6': "Moses, Aaron, Samuel: three men remembered here not for what they did but for having been answered.",
    '99:7': "He spoke from the cloudy pillar and they kept the testimonies. The revelation produced obedience, not discussion.",
    '99:8': "Forgiveness and vengeance are said of the same people in one verse, and neither cancels the other.",
    '99:9': "Worship moves from the footstool to the holy hill. The place changes; the reason given for going does not.",

    # ---- Chapter 100 ----
    '100:1': "The noise is required of all the lands. The first thing this psalm does is widen the room.",
    '100:2': "Gladness is commanded as the manner of the service. The mood is part of the work, not an extra.",
    '100:3': "\"It is he that hath made us, and not we ourselves.\" What is commanded to be known is who did the making.",
    '100:4': "Gates and courts. Thanksgiving is given a doorway here, and praise is described as entry.",
    '100:5': "The ground for the whole earth's singing comes down to three words about him: good, merciful, true.",
})

TAKEAWAYS.update({
    # ---- Chapter 101 ----
    '101:1': "Mercy and judgment are sung together, and everything that follows in the psalm is judgment.",
    '101:2': "The vow to behave wisely is interrupted by \"O when wilt thou come unto me?\" The resolve stalls waiting.",
    '101:3': "\"I will set no wicked thing before mine eyes.\" The king's policy starts with what he looks at.",
    '101:4': "\"I will not know a wicked person.\" What is refused is acquaintance, which is a decision about the household.",
    '101:5': "The two things he will cut a man off for are slander and a high look. Neither is a crime anywhere else.",
    '101:6': "His eyes are on the faithful of the land, that they may dwell with him. Appointments are made on character.",
    '101:7': "Deceit and lying are barred from the house by name. The purge is domestic before it is national.",
    '101:8': "\"I will early destroy.\" The resolution ends by putting itself on a daily schedule.",

    # ---- Chapter 102 ----
    '102:1': "Two things are asked that are not the same: that God hear, and that the cry actually arrive.",
    '102:2': "\"Answer me speedily.\" The petition includes a deadline, which few prayers are honest enough to state.",
    '102:3': "Days like smoke, bones like a hearth. One image of vanishing and one of burning in a single line.",
    '102:4': "He forgets to eat his bread. The grief is measured by a small domestic failure rather than a large one.",
    '102:6': "Pelican and owl: two birds nobody keeps, chosen precisely for how unwanted they are.",
    '102:7': "A sparrow alone on the house top. The loneliness is set in a city, above the roofs of occupied houses.",
    '102:8': "The reproach is continual and organised. Men have gone so far as to swear oaths about him.",
    '102:9': "Ashes for bread and tears in the cup. Mourning has replaced the ordinary meal item for item.",
    '102:10': "\"Thou hast lifted me up, and cast me down.\" The height he was given is counted as part of the fall.",
    '102:11': "A declining shadow is at its longest just before it goes. The image is of lengthening, not shrinking.",
    '102:12': "\"But thou, O LORD, shalt endure for ever.\" The turn is a contrast with his own case, not yet a comfort.",
    '102:13': "The mercy expected for Zion is dated: the set time is come. The rescue is put on a calendar.",
    '102:14': "The servants take pleasure in her stones and favour the dust. Even the rubble is loved.",
    '102:15': "The heathen fear the name because of what is done for Zion. The rebuilding is a sermon to the nations.",
    '102:16': "\"He shall appear in his glory\" when he builds up Zion. The glory is to be seen in masonry.",
    '102:17': "The prayer of the destitute is regarded and not despised. The second verb answers a fear the first leaves standing.",
    '102:18': "It is written for a generation yet to be created. The record is made for readers who do not exist.",
    '102:19': "He looked down from the height of the sanctuary. The elevation is used for seeing, not for distance.",
    '102:20': "The point of the looking is to hear groaning and loose the condemned. Attention is described as an errand.",
    '102:22': "A sick man's prayer ends with kingdoms gathered to serve. The private case widens until nations are in it.",
    '102:23': "\"He weakened my strength in the way.\" The complaint resumes after the vision, and God is named as the cause.",
    '102:24': "He asks not to be taken in the midst of his days, and sets that against years that never end.",
    '102:25': "The earth was founded and the heavens are handwork. Both are given a date, which is the whole point.",
    '102:26': "\"As a vesture shalt thou change them.\" The sky is treated as clothing due for replacement.",
    '102:27': "\"Thou art the same, and thy years shall have no end.\" Hebrews takes this verse and addresses it to the Son.",
    '102:28': "A dying man's psalm ends on children continuing. The answer to his shortness is somebody else's future.",
})

TAKEAWAYS.update({
    # ---- Chapter 103 ----
    '103:1': "The command is addressed to his own soul. Praise begins as an instruction a man has to give himself.",
    '103:2': "\"Forget not all his benefits.\" The danger named is not ingratitude but amnesia.",
    '103:3': "Forgiveness is listed before healing. The order of the two is not an accident.",
    '103:4': "Redeemed from destruction and then crowned. The rescue does not stop when it reaches neutral.",
    '103:5': "Youth renewed like the eagle's. What is promised back is vigour, and the verse claims nothing about innocence.",
    '103:6': "Righteousness is executed for all that are oppressed. The judgement described is on somebody's side.",
    '103:7': "Moses was given the ways and Israel the acts. One man saw the method; the rest saw the results.",
    '103:8': "Slow to anger is a statement about pace. The anger is not denied, only its speed.",
    '103:9': "\"He will not always chide.\" The comfort offered is about duration, not about the fault being unreal.",
    '103:10': "The verse says what did not happen. Not being dealt with after our sins is the whole of the good news in it.",
    '103:11': "The mercy is measured against the height of the sky, and the height of the sky is only the comparison.",
    '103:12': "East from west is the one distance with no midpoint. North and south would have met at a pole.",
    '103:13': "A father's pity is the analogy, and it is offered to those that fear him rather than to those who earned it.",
    '103:14': "\"He remembereth that we are dust.\" The mercy rests on an accurate memory of the material.",
    '103:15': "The flower of the field is not a tragic image here. It sits between two verses about mercy.",
    '103:16': "The place thereof shall know it no more. What goes is not only the life but the space it occupied.",
    '103:17': "Everlasting to everlasting is said here of the mercy. Psalm 90 used that phrase of God himself.",
    '103:18': "A condition arrives at the last moment: to such as keep his covenant and remember to do it.",
    '103:19': "The throne is in the heavens and the kingdom rules over all. The domestic mercies just listed come from a government.",
    '103:20': "The angels are told to bless him, and in the same line they are doing his commandments. Praise sits next to obedience.",
    '103:22': "All his works in all places, and then back to \"O my soul.\" The psalm ends where it began, with one man.",

    # ---- Chapter 104 ----
    '104:1': "The words that opened the psalm about pardon open this one about creation, unchanged.",
    '104:2': "Light for a garment and the heavens for a curtain. Creation is described as the furnishing of a tent.",
    '104:3': "Clouds for a chariot and the wings of the wind for a road. The weather is the vehicle, not the obstacle.",
    '104:4': "Angels made spirits, ministers made flame. The servants are as elemental as the house they serve in.",
    '104:5': "The foundations are laid so that it should not be removed. Stability is stated as a decision taken.",
    '104:6': "The deep covered the earth like clothing, standing above the mountains. Water is remembered as the first state.",
    '104:7': "\"At thy rebuke they fled.\" The sea is driven back by a voice rather than by any barrier.",
    '104:8': "The waters go up and down to a place he founded for them. Even the runoff has been given an address.",
    '104:9': "A bound is set that they may not pass. The promise made after the flood is restated here as geography.",
    '104:10': "Springs are sent into the valleys. The water that had to be driven off is now being delivered.",
    '104:11': "The wild asses quench their thirst. The animals nobody owns are named among the beneficiaries.",
    '104:12': "The fowls have their habitation by the springs and sing there. The provision arrives with music attached.",
    '104:14': "Grass for the cattle, herb for the service of man. In the order of the provision the animals come first.",
    '104:15': "Wine to gladden, oil to shine, bread to strengthen. Only one of the three is strictly necessary.",
    '104:16': "The cedars of Lebanon are called the trees of the LORD, which he planted. Lebanon does not own them.",
    '104:17': "The catalogue slows down to say that the fir trees are the stork's house. One bird gets an address.",
    '104:18': "High hills for the wild goats and rocks for the conies. The useless ground turns out to be somebody's refuge.",
    '104:19': "The moon for seasons and a sun that knows its going down. The calendar is built into the sky itself.",
    '104:20': "\"Thou makest darkness, and it is night.\" Night is made on purpose, and something is meant to live in it.",
    '104:21': "The young lions seek their meat from God. The hunt is entered in this psalm as a kind of asking.",
    '104:23': "Man goes out to his labour until the evening, listed among the lions and the springs as one more shift.",
    '104:24': "\"In wisdom hast thou made them all.\" The variety is credited to wisdom rather than to mere abundance.",
    '104:25': "The great and wide sea, with things creeping innumerable. The psalm concedes that it cannot count them.",
    '104:26': "Leviathan was made to play there. The monster of every other passage appears here at its recreation.",
    '104:27': "\"These wait all upon thee.\" The whole catalogue is reduced to one posture, waiting for a meal.",
    '104:28': "\"Thou openest thine hand, they are filled with good.\" The distance between plenty and famine is a hand.",
    '104:29': "Hiding the face and taking the breath are one act told twice. Death here is a withdrawal, not a blow.",
    '104:30': "The spirit sent forth renews the face of the earth. Creation is not finished in this psalm but repeated.",
    '104:31': "\"The LORD shall rejoice in his works.\" The maker is said to enjoy the thing he made.",
    '104:32': "He looks and the earth trembles, touches and the hills smoke. The world he enjoys is also afraid of him.",
    '104:33': "The singing is promised for as long as he lives, which is the only limit named anywhere in the psalm.",
    '104:34': "\"My meditation of him shall be sweet.\" The thinking, and not only the singing, is offered as the worship.",
    '104:35': "A psalm of birds and lions ends asking that sinners be consumed. They are the one thing in it out of place.",
})
