#!/usr/bin/env python3
"""Written takeaways for Psalms 105-150."""

TAKEAWAYS = {
    # ---- Chapter 105 ----
    '105:1': "Thanksgiving is not kept indoors: the deeds are to be made known among people who have no part in them yet.",
    '105:2': "\"Talk ye of all his wondrous works.\" Singing and ordinary conversation are given the same subject matter.",
    '105:3': "Glorying is not forbidden, only relocated: the boast is moved off the self and onto his holy name.",
    '105:4': "\"Seek his face evermore.\" Having found him is not treated as the end of seeking him.",
    '105:5': "Remembering is commanded as work. Israel's faith is held together by a deliberate refusal to forget.",
    '105:6': "Seed of Abraham, children of Jacob — the congregation is told it belongs to the story about to be recited.",
    '105:7': "\"Our God\" and \"all the earth\" stand in one breath. The God of one people is not a local one.",
    '105:8': "The covenant holds because he remembered it, not because the thousand generations did.",
    '105:9': "Made with Abraham and sworn to Isaac: the promise is reissued to a son who did nothing to earn the reissue.",
    '105:10': "Confirmed to Jacob \"for a law\" — the promise hardens into something with the force of statute.",
    '105:11': "The land is called their inheritance before a foot of it is owned. The heir is named before the estate exists.",
    '105:12': "\"Very few, and strangers in it.\" The promise sat for generations with people who had no leverage at all.",
    '105:14': "\"He reproved kings for their sakes.\" The safety of the landless ran through the rebuke of the powerful.",
    '105:15': "\"Touch not mine anointed.\" Wandering herdsmen with no army are called anointed, and that is the whole defence.",
    '105:16': "\"He called for a famine.\" The hunger that drove Jacob's family to Egypt is described as God's own summons.",
    '105:17': "\"He sent a man before them, even Joseph, who was sold.\" The sending and the selling are one event read twice.",
    '105:18': "\"His feet they hurt with fetters: he was laid in iron.\" The psalm does not hurry past the prison years.",
    '105:19': "\"The word of the LORD tried him.\" The promise given to Joseph was also what tested him while it waited.",
    '105:20': "The king who held him is the one who looses him. Release comes through the hand that did the imprisoning.",
    '105:21': "A convict is made lord of the house. Egypt's second man is the Hebrew slave it had already condemned.",
    '105:23': "Jacob sojourned \"in the land of Ham\" — the rescue settles the family in the country that will enslave it.",
    '105:24': "The increase that alarmed Pharaoh is credited to God. Israel's growth under pressure was not an accident.",
    '105:25': "\"He turned their heart to hate his people.\" The psalm dares to put the persecution inside God's providence.",
    '105:26': "Moses his servant, Aaron his chosen. The deliverance arrives as two men rather than as an army.",
    '105:27': "The signs are worked in the land of Ham, on the ground where Egypt's own gods were supposed to be at home.",
    '105:28': "Darkness comes first, and the word that sent it met no resistance from the dark.",
    '105:29': "Water into blood: the river Egypt lived by is the first thing taken away from it.",
    '105:30': "Frogs reach \"the chambers of their kings.\" No room in Egypt was private enough to be spared.",
    '105:31': "\"He spake, and there came.\" The plagues arrive by a word, the same way the world they are unmaking did.",
    '105:32': "Hail instead of rain. The weather the fields depended on is what turns against them.",
    '105:33': "Vines and fig trees broken — the slow crops, the ones that take years to replace.",
    '105:34': "Locusts \"without number.\" The one plague the psalm refuses to count is the one nobody could.",
    '105:36': "\"The chief of all their strength.\" The firstborn are named as Egypt's power, and that is what is struck.",
    '105:37': "They leave with silver and gold and not one feeble person. Slaves walk out a paid and healthy nation.",
    '105:38': "\"Egypt was glad when they departed.\" The oppressor ends up relieved to lose what he would not release.",
    '105:39': "A cloud for covering and fire for light: one presence serves them differently by day and by night.",
    '105:40': "\"The people asked, and he brought quails.\" Here the wilderness grumbling is reported simply as a request answered.",
    '105:41': "The water from the rock runs \"like a river\" in dry places. The supply outlasts the moment of thirst.",
    '105:42': "The whole recital hangs on one clause: \"for he remembered his holy promise.\"",
    '105:43': "Joy and gladness, not relief, are the words chosen for a nation walking out of slavery.",
    '105:44': "They inherited \"the labour of the people.\" The gift arrives as somebody else's finished work.",
    '105:45': "The point of the land is obedience in it. The gift comes with a purpose attached and no price.",
}

TAKEAWAYS.update({
    # ---- Chapter 106 ----
    '106:1': "\"He is good\" comes before \"his mercy endureth for ever.\" The character is stated before the duration.",
    '106:2': "A psalm about to recite Israel's failures opens by admitting that praise outruns anyone's power to speak it.",
    '106:3': "Blessedness is tied to doing righteousness \"at all times\" — which the next forty verses show nobody did.",
    '106:4': "\"Remember me\" — the singer asks to be let into a favour shown to a people, not to be paid as an individual.",
    '106:5': "Thy chosen, thy nation, thine inheritance. Everything he wants to enjoy belongs to somebody else first.",
    '106:6': "\"We have sinned with our fathers.\" The confession refuses the distance that would make this generation spectators.",
    '106:7': "The failure at the Red sea is traced to not remembering. Forgetting is the root sin in this telling.",
    '106:8': "\"Nevertheless he saved them for his name's sake.\" The reason given for the rescue is nothing found in them.",
    '106:9': "The sea is rebuked as though it were a person. The obstacle is addressed rather than negotiated with.",
    '106:10': "Saved and redeemed \"from the hand\" — the psalm keeps naming a grip, because a grip is what slavery was.",
    '106:11': "\"There was not one of them left.\" The water that made a road made a grave in the same hour.",
    '106:12': "\"Then believed they his words.\" Faith that waits until the sea has parted has a short half-life.",
    '106:13': "\"They soon forgat.\" The interval between the song and the forgetting is this psalm's real subject.",
    '106:14': "Appetite in the desert is called tempting God. Wanting is treated here as a theological act.",
    '106:15': "\"He gave them their request; but sent leanness into their soul.\" A granted prayer can itself be the judgement.",
    '106:16': "Envy of Moses is listed among the sins against God. Resentment of a leader is not a merely social fault.",
    '106:17': "The earth itself opens. The judgement on Dathan comes up from under the camp rather than out of it.",
    '106:18': "The fire is reported with no account of how it started. Judgement is recorded here, not explained.",
    '106:19': "A calf made in Horeb — at the mountain itself, while the covenant was still being given.",
    '106:20': "\"They changed their glory into the similitude of an ox that eateth grass.\" Idolatry is described as a bad trade.",
    '106:21': "\"They forgat God their saviour.\" The title is spoken at exactly the moment it was being denied.",
    '106:23': "Moses \"stood before him in the breach\" — the mediator is pictured as a man filling a gap in a broken wall.",
    '106:24': "\"They despised the pleasant land.\" Unbelief showed itself as contempt for a gift, not as doubt about a doctrine.",
    '106:25': "Murmuring in tents is counted as not hearkening. Private complaint is heard as public disobedience.",
    '106:26': "The sentence matches the sin: they did not want the land, and they will not see it.",
    '106:27': "The wilderness judgement is carried forward into the exile. One verse reaches across centuries of the same refusal.",
    '106:28': "\"The sacrifices of the dead.\" Baalpeor is described as a meal shared with nothing living.",
    '106:29': "\"Their inventions\" — the psalm's word for idolatry is a word for creativity.",
    '106:30': "Phinehas stands up and the plague stops. One man's act is given the weight Moses' intercession had.",
    '106:31': "\"Counted unto him for righteousness\" — the phrase used of Abraham's believing is used here of Phinehas' zeal.",
    '106:32': "Moses fared ill \"for their sakes.\" The people's provocation cost the one man who had stood in the breach for them.",
    '106:33': "\"He spake unadvisedly with his lips.\" The whole charge against Moses comes down to one sentence said in anger.",
    '106:34': "The sin named here is an omission: they simply did not do what they were told about the nations.",
    '106:35': "\"Were mingled among the heathen, and learned their works.\" Nobody decided to apostatise; they picked it up.",
    '106:36': "The idols they served became a snare. What was taken up as worship closed on them as a trap.",
    '106:37': "Child sacrifice is where the drift ends. The psalm traces the line from mingling all the way to this.",
    '106:38': "\"The land was polluted with blood.\" The ground is said to carry the guilt of what was done on it.",
    '106:39': "\"Defiled with their own works.\" The uncleanness was self-inflicted, not caught from the neighbours.",
    '106:40': "\"He abhorred his own inheritance.\" The psalm will not soften what God felt toward what belonged to him.",
    '106:41': "Ruled by those who hated them: the judgement is the exodus running backwards.",
    '106:42': "Oppression returns, and this time no Pharaoh is needed to explain it.",
    '106:43': "\"Many times did he deliver them.\" The rescues are counted, and they outnumber the lessons learned from them.",
    '106:44': "\"Nevertheless he regarded their affliction, when he heard their cry.\" A cry is not repentance, and it was enough.",
    '106:45': "He remembered \"his covenant\" and acted by the multitude of his mercies. The measure is his word, not their record.",
    '106:46': "Even the captors are made to pity them. Mercy arrives through people who owe them nothing.",
    '106:47': "The psalm ends still in exile, still asking. The history lesson closes as a prayer not yet answered.",
    '106:48': "The congregation is told to say Amen. This whole record of failure is meant to be agreed with out loud.",
})

TAKEAWAYS.update({
    # ---- Chapter 107 ----
    '107:1': "The mercy thanked for is a covenant loyalty, which is why its length can be stated as a fact.",
    '107:2': "\"Let the redeemed of the LORD say so.\" Redemption is to be spoken by the redeemed, not reported about them.",
    '107:3': "Gathered from east, west, north and south: the congregation is collected out of scattering before it sings.",
    '107:4': "The first picture is not danger but aimlessness — wandering with no city to stop in.",
    '107:5': "Hunger and thirst are said to reach the soul. A body's lack is described as reaching the person.",
    '107:6': "\"Then they cried.\" The turn is not reform or sacrifice but noise made in trouble.",
    '107:7': "\"By the right way.\" The deliverance is not comfort where they were but a road that ends somewhere.",
    '107:8': "The refrain wishes rather than commands. \"Oh that men would\" concedes that mostly they do not.",
    '107:9': "The longing soul is satisfied and the hungry filled. The appetite is answered rather than rebuked.",
    '107:10': "Darkness, the shadow of death, affliction and iron. The second picture is prison, and it was earned.",
    '107:11': "The prisoners are told why they sit there. The psalm does not pretend the captives were innocent.",
    '107:12': "\"There was none to help.\" Being brought to the point of having nobody is itself described as God's work.",
    '107:13': "The guilty cry the same cry as the lost, and the answer comes back the same.",
    '107:14': "\"Brake their bands in sunder.\" The chains are not unlocked; they are broken.",
    '107:15': "The refrain returns unaltered after a stanza about rebels. The goodness praised is the same goodness.",
    '107:16': "Gates of brass, bars of iron — the psalm names the strongest thing it can think of and says it gave way.",
    '107:17': "\"Fools because of their transgression.\" Sin is diagnosed as stupidity before it is charged as guilt.",
    '107:18': "The sign given is loss of appetite. A man who will not eat is already at the gates of death.",
    '107:19': "This stanza cries in the present tense. The pattern is not being remembered; it is happening.",
    '107:20': "\"He sent his word, and healed them.\" The remedy is a word, sent, and that is the whole account of the cure.",
    '107:21': "Third refrain, third kind of trouble. The response asked for does not vary with the case.",
    '107:22': "Thanksgiving is given a form — sacrifice and telling. Gratitude here is something done, not only felt.",
    '107:23': "\"That do business in great waters.\" The fourth picture is ordinary work, not misadventure.",
    '107:24': "Those who go out on the sea \"see the works of the LORD.\" The dangerous place is also the place of sight.",
    '107:25': "The storm that nearly kills them is commanded. Weather is not outside the government of God here.",
    '107:26': "Up to heaven and down to the depths in one line: the psalm writes the motion of a ship into its grammar.",
    '107:27': "\"At their wit's end.\" Competent seamen are reduced to the condition of drunk men.",
    '107:28': "Professionals cry the same cry as the lost wanderers. Skill runs out at the same place ignorance does.",
    '107:29': "\"He maketh the storm a calm.\" What was raised by a word is stilled by one.",
    '107:30': "\"Glad because they be quiet.\" The relief comes at the silence, before the harbour is even reached.",
    '107:31': "The fourth refrain closes the four pictures. The psalm has been assembling a list of people who owe thanks.",
    '107:32': "The thanks is to be said among the people and before the elders. A private rescue is given a public setting.",
    '107:33': "The hand that made rivers makes wilderness. The reversal is shown running the wrong way first.",
    '107:34': "Fruitful land turned barren \"for the wickedness of them that dwell therein.\" Geography is read morally.",
    '107:35': "Wilderness into standing water: the sentence of two verses earlier is reversed word for word.",
    '107:36': "The hungry are settled where there was nothing and set to building. The gift includes the work.",
    '107:37': "Fields sown, vineyards planted. The rescue ends in ordinary agriculture and years of waiting for fruit.",
    '107:38': "Blessing is counted in people and cattle. The psalm is not embarrassed to measure it materially.",
    '107:39': "\"Again, they are minished and brought low.\" The psalm refuses to end the cycle at prosperity.",
    '107:40': "Princes wander where there is no way — put in the exact condition of the lost men in verse 4.",
    '107:41': "The poor are set on high and given families. The reversal is resettlement rather than revenge.",
    '107:42': "\"All iniquity shall stop her mouth.\" The argument ends not in defeat but in silence.",
    '107:43': "The last word goes to the wise: these things have to be observed before the lovingkindness is understood.",
})

TAKEAWAYS.update({
    # ---- Chapter 108 ----
    '108:1': "\"My heart is fixed\" comes before the singing. The settledness is claimed, and the praise follows from it.",
    '108:2': "He wakes the instruments and then himself. The mood is not waited for; it is summoned.",
    '108:3': "Praise offered \"among the nations\" — the audience for Israel's worship is deliberately outside Israel.",
    '108:4': "Mercy above the heavens, truth to the clouds. The two are always measured together in this psalm.",
    '108:5': "The prayer asks for God's exaltation first and for anything of his own only afterwards.",
    '108:6': "\"That thy beloved may be delivered.\" The glory wanted in the line before is wanted for somebody's sake.",
    '108:7': "\"God hath spoken in his holiness.\" All the confidence about the map rests on a word already given.",
    '108:8': "Gilead, Manasseh, Ephraim, Judah — the territories are counted as already his because they were promised.",
    '108:9': "Moab a washpot, Edom a place to throw a shoe. The contempt is deliberate and not softened.",
    '108:10': "\"Who will bring me into the strong city?\" The confident inventory stops at the one place still unconquered.",
    '108:11': "He names God as the one who cast them off and in the same breath asks him to march out with the army.",
    '108:12': "\"Vain is the help of man.\" Not weak, not insufficient — vain. The alternative is cancelled rather than ranked.",
    '108:13': "\"Through God we shall do valiantly.\" The courage is theirs to show and his to supply.",
})

TAKEAWAYS.update({
    # ---- Chapter 109 ----
    '109:1': "\"O God of my praise.\" He calls God by the title of his own song and then begs him not to stay silent.",
    '109:2': "The weapon complained of is a mouth. The whole assault described here is speech.",
    '109:3': "\"Without a cause.\" The hatred is not proportionate to anything done, because there was nothing to be proportionate to.",
    '109:4': "\"For my love they are my adversaries: but I give myself unto prayer.\" The answer to slander is not a reply.",
    '109:5': "Evil for good, hatred for love. The exchange rate is stated plainly before any curse is spoken.",
    '109:6': "A wicked judge and an accuser at his right hand: he asks that the man be given his own treatment back.",
    '109:7': "\"Let his prayer become sin.\" The hardest line in the psalm asks that even the man's religion be counted against him.",
    '109:8': "\"Let another take his office.\" Peter will read this line over the vacancy Judas left.",
    '109:9': "The curse reaches wife and children. The psalm does not pretend that hatred stops at the guilty man.",
    '109:10': "Begging children wandering from ruined homes. The wish is spelled out in detail rather than left general.",
    '109:11': "The extortioner is called in as the instrument. He asks that the man's own trade be turned against him.",
    '109:12': "\"Let there be none to extend mercy.\" What is asked for is the withdrawal of the one thing the psalmist himself lives on.",
    '109:13': "A blotted-out name was the worst loss Israel could imagine. The curse aims past the man at his future.",
    '109:14': "The father's iniquity remembered, the mother's sin not blotted out — the request runs backwards through a family.",
    '109:15': "The curses are set \"before the LORD continually\" and left there. He asks; he does not lift a hand.",
    '109:16': "The charge is finally named: he did not remember to shew mercy, and hunted men already broken in heart.",
    '109:17': "\"As he loved cursing, so let it come unto him.\" The punishment asked for is the man's own preference, delivered.",
    '109:18': "Cursing worn like a coat, then soaking in like water and oil. What was put on from outside works its way inward.",
    '109:19': "A garment and a girdle worn continually — he asks that the curse become clothing the man can never take off.",
    '109:20': "\"Let this be the reward... from the LORD.\" The whole terrible list is handed over rather than carried out.",
    '109:21': "\"But do thou for me... for thy name's sake.\" He asks for himself on entirely different ground than he asked against them.",
    '109:22': "\"I am poor and needy, and my heart is wounded within me.\" The hunter of the poor is answered by a poor man.",
    '109:23': "A shadow at evening, a locust shaken off. He describes himself as something already on its way out.",
    '109:24': "The fasting undertaken as prayer has left him unable to stand. Devotion is not described as making him stronger.",
    '109:25': "They shake their heads at him. The gospels record the same gesture in front of the cross.",
    '109:26': "\"According to thy mercy.\" The standard he wants applied to himself is not the one he asked for them.",
    '109:27': "The point of the rescue is what it will prove: \"that they may know that this is thy hand.\"",
    '109:28': "\"Let them curse, but bless thou.\" Two verdicts are passed on one man and only one of them holds.",
    '109:29': "Shame worn as a mantle answers cursing worn as a garment. The image is handed straight back.",
    '109:30': "Praise is promised \"among the multitude\" — in front of the same crowd that watched the shaming.",
    '109:31': "God stands at the right hand of the poor, which is the place the accuser was asked to take in verse 6.",
})

TAKEAWAYS.update({
    # ---- Chapter 110 ----
    '110:1': "\"The LORD said unto my Lord.\" David calls his own descendant Lord, which is the question Jesus put to the Pharisees.",
    '110:2': "\"Rule thou in the midst of thine enemies.\" The reign is exercised while the opposition stands, not after it falls.",
    '110:3': "The people are willing \"in the day of thy power.\" The volunteers are produced by the power, not recruited before it.",
    '110:4': "Sworn and not repented of: a priesthood older than Aaron's and owing nothing to descent. Hebrews is built on this line.",
    '110:5': "The one seated at the right hand is also the one standing at it. The psalm refuses to keep its picture tidy.",
    '110:6': "Judgement among the heathen, described without euphemism. This king is not only a priest.",
    '110:7': "\"He shall drink of the brook in the way.\" The conqueror stops at a stream like any tired man on a march.",
})

TAKEAWAYS.update({
    # ---- Chapter 111 ----
    '111:1': "Whole-hearted praise is located in the assembly. A private resolve is kept in public.",
    '111:2': "The works are \"sought out of all them that have pleasure therein.\" Delight is the condition of seeing anything.",
    '111:3': "His righteousness endures for ever is said of his work. What he does and what he is are not separable here.",
    '111:4': "\"He hath made his wonderful works to be remembered.\" The memorials were his idea, not Israel's good habit.",
    '111:5': "Food given and covenant remembered stand in one line. Daily provision is covenant keeping, not a separate kindness.",
    '111:6': "The power was shown for a purpose: to hand over an inheritance they could never have taken.",
    '111:7': "Works and commandments are called verity together. What he does and what he requires do not disagree.",
    '111:9': "\"He sent redemption unto his people\" — past tense and finished, before the name is called holy and reverend.",
    '111:10': "Wisdom begins in fear, and the good understanding belongs to those who do rather than those who know.",
})

TAKEAWAYS.update({
    # ---- Chapter 112 ----
    '112:1': "He \"delighteth greatly in his commandments.\" Fear of God and delight in his law are put in one clause.",
    '112:2': "The blessing is described as landing on a generation the blessed man will not live to see.",
    '112:3': "\"His righteousness endureth for ever\" was said of God one psalm ago; here it is said of the man who fears him.",
    '112:4': "\"There ariseth light in the darkness.\" The upright are not promised the absence of dark, only light inside it.",
    '112:5': "Lending, and guiding his affairs with discretion. Goodness here looks like money handled well.",
    '112:6': "Everlasting remembrance is promised to a man whose name no chronicle is going to carry.",
    '112:7': "\"He shall not be afraid of evil tidings.\" The bad news is expected; what is promised is a fixed heart when it lands.",
    '112:8': "His heart is \"established\" — the steadiness is something done to him rather than mustered by him.",
    '112:9': "\"He hath dispersed, he hath given to the poor.\" Paul quotes this verse to describe a generosity that lasts.",
    '112:10': "The wicked man's grief is at seeing someone else blessed. Envy is given the last word about him.",
})

TAKEAWAYS.update({
    # ---- Chapter 113 ----
    '113:1': "Servants are the ones told to praise. The call goes first to those with the least standing to make it.",
    '113:2': "\"From this time forth and for evermore.\" The praise is given a starting point and no ending one.",
    '113:3': "Sunrise to sunset. The praise is fixed to the daylight rather than to a temple or an hour of service.",
    '113:4': "High above the nations, glory above the heavens. The height is measured so the stooping can register.",
    '113:5': "\"Who is like unto the LORD our God?\" The question is asked about his height and answered by his descent.",
    '113:6': "He humbles himself even to look at heaven. The gap is such that noticing angels is condescension.",
    '113:7': "Out of the dust, off the dunghill. The lifting starts at the least dignified place the psalm can name.",
    '113:8': "\"That he may set him with princes.\" The beggar is not merely relieved but seated among the rulers.",
    '113:9': "The psalm's last picture of God's greatness is one barren woman with children in the house.",
})

TAKEAWAYS.update({
    # ---- Chapter 114 ----
    '114:1': "\"A people of strange language.\" What is remembered of Egypt here is the experience of not being understood.",
    '114:2': "Judah his sanctuary, Israel his dominion. The nation itself is named as the place where God lives.",
    '114:3': "The sea fled and Jordan turned back. Two miracles forty years apart are set side by side as one motion.",
    '114:4': "Mountains skipping like rams: the psalm has the landscape behaving like a startled flock.",
    '114:5': "The psalm turns and interrogates the sea directly, as though demanding an explanation from it.",
    '114:6': "The question is put again to the hills, and the answer is withheld one verse longer than is comfortable.",
    '114:7': "The answer is not an explanation but a command. The presence itself was the reason all along.",
    '114:8': "Rock into water, flint into a fountain. The hardest thing the psalm can name is what is made to give drink.",
})

TAKEAWAYS.update({
    # ---- Chapter 115 ----
    '115:1': "\"Not unto us, not unto us.\" The refusal of glory is said twice before the giving of it is said once.",
    '115:2': "The worry is the taunt \"Where is now their God?\" The reputation at stake is his rather than theirs.",
    '115:3': "\"He hath done whatsoever he hath pleased.\" The answer to the taunt is freedom, not a demonstration.",
    '115:4': "Silver and gold, \"the work of men's hands.\" The material is precious; the maker is the problem.",
    '115:5': "Mouths that do not speak, eyes that do not see. The mockery works by going through the organs one at a time.",
    '115:7': "Hands, feet, throat. The inventory ends with a body complete in every part and wholly inert.",
    '115:8': "\"They that make them are like unto them.\" A worshipper comes to resemble whatever he worships.",
    '115:9': "Israel is told to trust, and the ground given is not their record but his help and his shield.",
    '115:10': "The priests are given the same instruction as everyone else. The house of Aaron is not trusted to itself.",
    '115:11': "The third call reaches past Israel and past Aaron to anyone who fears him. The circle opens outward.",
    '115:12': "\"The LORD hath been mindful of us.\" What is expected is argued from what has already been received.",
    '115:13': "\"Both small and great.\" The blessing is explicitly denied a scale of importance.",
    '115:14': "The increase promised includes the children. Blessing is described as outliving the person blessed.",
    '115:15': "The blesser's credentials are the size of what he made. Heaven and earth stand behind the blessing.",
    '115:16': "Heaven kept, earth given away. Room for human work is made by God's own decision, not by his absence.",
    '115:17': "\"The dead praise not the LORD.\" The argument for wanting life is that praise needs a living voice.",
    '115:18': "\"But we will bless the LORD.\" Against the silence of the dead the congregation sets its own noise.",
})

TAKEAWAYS.update({
    # ---- Chapter 116 ----
    '116:1': "\"I love the LORD, because he hath heard my voice.\" The love is given a reason, and the reason is an answered prayer.",
    '116:2': "Because the ear was inclined once, he will call for a lifetime. A single answer settles a habit.",
    '116:3': "Sorrows of death, pains of hell. The trouble took hold of him; he is not described as having walked into it.",
    '116:4': "The prayer in the crisis is one line long. Under the pains of hell nobody composes.",
    '116:5': "Gracious, righteous, merciful. The righteousness stands between the two mercies rather than against them.",
    '116:6': "\"The LORD preserveth the simple.\" Not the shrewd and not the strong, but those with no defences to speak of.",
    '116:7': "\"Return unto thy rest, O my soul.\" He has to argue his own soul back to a place it already had.",
    '116:8': "Soul, eyes, feet. The deliverance is itemised all the way down to not stumbling.",
    '116:9': "\"In the land of the living.\" The walking before God that he wants is in this life, not past it.",
    '116:10': "\"I believed, therefore have I spoken\" — and what he spoke was that he was greatly afflicted. Faith said the trouble out loud.",
    '116:11': "\"I said in my haste, All men are liars.\" The psalm preserves the sentence he now knows he said too fast.",
    '116:12': "\"What shall I render?\" The question assumes a debt, and every answer that follows is a form of receiving more.",
    '116:13': "The repayment offered is to take a cup. Gratitude here is discharged by accepting, not by giving back.",
    '116:14': "Vows paid \"in the presence of all his people.\" A rescue nobody saw is settled where everybody can.",
    '116:15': "\"Precious in the sight of the LORD is the death of his saints.\" Their dying is costly to him, which is why this one did not happen.",
    '116:16': "\"I am thy servant\" twice over, and son of a servant. He claims the household before mentioning the loosed bonds.",
    '116:17': "The sacrifice named is thanksgiving, and it comes with calling on the name again. Gratitude here keeps asking.",
    '116:18': "The vow is repeated word for word. That is how vows work: said once, and then said again where it counts.",
    '116:19': "The courts of the house, the midst of Jerusalem. The thanksgiving is pinned to an address before the psalm ends.",
})

TAKEAWAYS.update({
    # ---- Chapter 117 ----
    '117:1': "The shortest psalm is addressed to the nations rather than to Israel. Paul quotes it to show the Gentiles were always intended.",
    '117:2': "The nations are told to praise God for a kindness shown \"toward us.\" They are called to rejoice at somebody else's mercy.",
})

TAKEAWAYS.update({
    # ---- Chapter 118 ----
    '118:1': "The refrain stands at the head of the psalm, and everything that follows is offered as evidence for it.",
    '118:2': "Israel is told to say it. The congregation's part is to repeat the sentence, not to improve on it.",
    '118:3': "The priests are given the same words as the nation. Office adds nothing to what there is to say.",
    '118:4': "\"Them that fear the LORD\" — the last group named has no lineage and no office, only the fear.",
    '118:5': "Distress answered with \"a large place.\" The relief is described as room rather than as escape.",
    '118:6': "\"What can man do unto me?\" — asked by a man who is about to describe being surrounded by nations.",
    '118:7': "God \"taketh my part with them that help me.\" The allies are counted, and he is counted among them first.",
    '118:8': "Better to trust the LORD than man. It is put as a comparison, which means the other option was real.",
    '118:9': "The same sentence again with princes in it. Improving the quality of the man does not change the verdict.",
    '118:10': "\"All nations compassed me about.\" The odds are stated at their worst before the name of the LORD is brought in.",
    '118:11': "\"They compassed me about; yea, they compassed me about.\" The repetition is the pressure, written as pressure.",
    '118:12': "Bees, and a fire of thorns. Fierce, and over quickly — two images for the same enemy in one line.",
    '118:13': "\"Thou hast thrust sore at me.\" He turns and speaks to his attacker, then changes the subject to who caught him.",
    '118:14': "Strength, song and salvation. The line is lifted out of the song Israel sang at the Red sea.",
    '118:15': "The rejoicing is heard in tents rather than in a palace. Salvation reaches the ordinary houses first.",
    '118:16': "The right hand exalted, the right hand doing valiantly. It is said twice because a crowd is meant to answer.",
    '118:17': "\"I shall not die, but live, and declare the works of the LORD.\" The reason for wanting life is having something to say.",
    '118:18': "\"Chastened me sore: but he hath not given me over unto death.\" The chastening is owned, and so is its limit.",
    '118:19': "\"Open to me the gates of righteousness.\" He asks to be let in rather than claiming a right of entry.",
    '118:20': "The gate belongs to the LORD, and the righteous are simply those found going through it.",
    '118:21': "\"Thou art become my salvation.\" Deliverance turns out to be a person rather than an event.",
    '118:22': "\"The stone which the builders refused.\" The experts' rejection is what marks out the cornerstone; Jesus applied it to himself.",
    '118:23': "\"It is marvellous in our eyes.\" The reversal is not explained. It is stared at.",
    '118:24': "\"This is the day which the LORD hath made\" — the day meant is the day the rejected stone was set at the corner.",
    '118:25': "\"Save now, I beseech thee\" is Hosanna. The crowd at the gates of Jerusalem was shouting this verse.",
    '118:26': "\"Blessed be he that cometh in the name of the LORD.\" A welcome for pilgrims, said one day over one man.",
    '118:27': "\"Bind the sacrifice with cords, even unto the horns of the altar.\" The praise ends with an animal tied down.",
    '118:28': "\"Thou art my God\" twice. The possessive is the whole confession, and saying it again is the emphasis.",
    '118:29': "The psalm ends on the line it began with, unaltered by everything that came between.",
})

TAKEAWAYS.update({
    # ---- Chapter 119: Aleph, Beth, Gimel, Daleth ----
    '119:1': "Blessedness is attached to the way walked rather than to the law known.",
    '119:2': "Keeping testimonies and seeking him with the whole heart are one activity. The law is treated as a road to a person.",
    '119:4': "\"Thou hast commanded us to keep thy precepts diligently.\" The standard is fixed before any of the pleading begins.",
    '119:5': "\"O that my ways were directed.\" The first thing he says about himself is a wish he cannot carry out.",
    '119:6': "Shame is escaped by respect unto \"all thy commandments.\" Partial keeping is precisely what leaves a man ashamed.",
    '119:8': "\"I will keep thy statutes: O forsake me not utterly.\" A resolution and a fear of abandonment in one breath.",
    '119:9': "How a young man cleanses his way: not by resolve but by taking heed to a word that came from outside him.",
    '119:10': "He has sought with his whole heart and still asks not to wander. Sincerity is not treated as a safeguard.",
    '119:11': "The word is hidden in the heart, not shelved. Sin is fought at the place where it is actually decided.",
    '119:12': "\"Blessed art thou, O LORD: teach me thy statutes.\" Praise and a request for instruction come out as one sentence.",
    '119:13': "\"With my lips have I declared.\" What was hidden in the heart two verses ago is now said out loud.",
    '119:14': "The testimonies are rejoiced in \"as much as in all riches\" — measured against wealth, not against other laws.",
    '119:17': "\"That I may live, and keep thy word.\" Life is asked for as the condition of obedience, not as its reward.",
    '119:18': "\"Open thou mine eyes.\" The wondrous things are already in the law; what needs fixing is the reader.",
    '119:19': "\"I am a stranger in the earth.\" A man with standing nowhere asks not to be kept from the one thing he has.",
    '119:20': "His soul breaks with longing, and what he longs for is judgments. The appetite is aimed at something austere.",
    '119:23': "Princes sit and speak against him; he sits and meditates. Two kinds of sitting in a single verse.",
    '119:24': "The testimonies are called \"my counsellors.\" The word he must obey is also the word he goes to for advice.",
    '119:25': "\"My soul cleaveth unto the dust\" — and what he asks for is not relief but quickening according to the word.",
    '119:26': "\"I have declared my ways, and thou heardest me.\" Confession comes first and the request to be taught after it.",
    '119:27': "Understanding is wanted so that he can talk of it. The learning is aimed at speech, not at private possession.",
    '119:28': "\"My soul melteth for heaviness.\" Strength is asked for according to the word, because that is where he has learned to look.",
    '119:29': "\"Grant me thy law graciously.\" The law itself is requested as a gift rather than taken up as a duty.",
    '119:32': "\"I will run the way of thy commandments, when thou shalt enlarge my heart.\" The pace waits on something done to him.",
})

TAKEAWAYS.update({
    # ---- Chapter 119: He, Vau, Zain, Cheth ----
    '119:33': "He asks to be taught the way and expects to keep it \"unto the end.\" The teaching is what makes persistence possible.",
    '119:34': "Understanding is asked for as the thing that produces obedience. He does not expect to keep what he cannot grasp.",
    '119:36': "\"Incline my heart unto thy testimonies, and not to covetousness.\" The rival is named outright, and it is money.",
    '119:37': "The prayer is about what the eyes rest on. Vanity is treated as something caught by looking at it.",
    '119:38': "\"Stablish thy word unto thy servant.\" He asks God to make good on what God has already said.",
    '119:39': "He admits the reproach he fears, and the reason he gives is not his innocence but that the judgments are good.",
    '119:41': "Mercies and salvation are asked \"according to thy word.\" He wants only what has already been promised.",
    '119:42': "His answer to the man who reproaches him is a word he trusts and did not compose.",
    '119:43': "\"Take not the word of truth utterly out of my mouth.\" He dreads being left with nothing true to say.",
    '119:45': "\"I will walk at liberty: for I seek thy precepts.\" The freedom is the result of the seeking, not its opposite.",
    '119:46': "Speaking of the testimonies \"before kings.\" What he says in private is what he expects to say at court.",
    '119:48': "\"My hands also will I lift up unto thy commandments.\" The gesture of worship is made toward the law itself.",
    '119:49': "\"Upon which thou hast caused me to hope.\" Even the hoping is traced back to God's doing rather than his own temper.",
    '119:50': "\"This is my comfort in my affliction.\" The word is not what removes the trouble but what he lives on inside it.",
    '119:51': "Derision from the proud did not move him. The pressure named here is contempt, not violence.",
    '119:53': "\"Horror hath taken hold upon me\" over other men's forsaking of the law. The distress is not about himself.",
    '119:54': "\"My songs in the house of my pilgrimage.\" Statutes set to music by a man who is not home yet.",
    '119:56': "\"This I had, because I kept thy precepts.\" A rare line where he names something obedience actually gained him.",
    '119:57': "\"Thou art my portion.\" The word for a Levite's inheritance is claimed by a man with no land at all.",
    '119:59': "\"I thought on my ways, and turned my feet.\" Thinking is reported as having changed the direction he walks.",
    '119:60': "\"I made haste, and delayed not.\" Speed is counted here as part of the obedience rather than a detail of it.",
    '119:62': "Thanksgiving at midnight. The hour chosen is the one with nobody awake to see it.",
    '119:63': "His company is chosen by what other men fear. Nothing else about them is mentioned.",
    '119:64': "\"The earth is full of thy mercy: teach me thy statutes.\" Out of the whole creation he asks for one lesson.",
})

TAKEAWAYS.update({
    # ---- Chapter 119: Teth, Jod, Caph, Lamed ----
    '119:65': "\"Thou hast dealt well with thy servant.\" The verdict on his life is given before the affliction is brought up.",
    '119:67': "\"Before I was afflicted I went astray.\" He credits the trouble with the correction without pretending he chose it.",
    '119:68': "\"Thou art good, and doest good.\" What God is and what God does are stated as one thing before the request follows.",
    '119:69': "A lie is forged against him and his answer is to keep the precepts. The slander is not returned in kind.",
    '119:70': "\"Their heart is as fat as grease.\" What he diagnoses in the proud is insensibility rather than hostility.",
    '119:71': "\"It is good for me that I have been afflicted.\" Said flatly, as a conclusion reached rather than a sentiment offered.",
    '119:72': "The law of his mouth set against thousands of gold and silver — a comparison made in a currency he does not have.",
    '119:73': "\"Thy hands have made me\" is the argument for \"give me understanding.\" The maker is asked to finish his own work.",
    '119:74': "His hoping is expected to gladden other people. One man's trust turns out to be public property.",
    '119:75': "\"Thou in faithfulness hast afflicted me.\" The trouble is not excused as an accident but credited to God's faithfulness.",
    '119:78': "They dealt perversely \"without a cause,\" and his whole response is to go on meditating. Nothing is planned against them.",
    '119:80': "A sound heart in the statutes is what keeps a man from shame, and the soundness is asked for, not claimed.",
    '119:81': "\"My soul fainteth for thy salvation: but I hope in thy word.\" Hope is stated as fact while the strength is gone.",
    '119:82': "\"When wilt thou comfort me?\" The waiting has lasted long enough to be complained of to the one waited for.",
    '119:83': "\"Like a bottle in the smoke\" — a wineskin shrivelled over the fire. He describes himself as dried out and past use.",
    '119:84': "\"How many are the days of thy servant?\" He points out that he has not got unlimited time to wait in.",
    '119:85': "The pits dug for him are called \"not after thy law.\" The offence he names first is against the law, not against him.",
    '119:86': "\"All thy commandments are faithful: they persecute me wrongfully.\" Two facts set side by side and left unreconciled.",
    '119:88': "Quickening is asked according to lovingkindness, and the reason given is so that he can go on keeping the testimony.",
    '119:89': "\"For ever, O LORD, thy word is settled in heaven.\" Its stability is located where his circumstances cannot reach it.",
    '119:90': "Faithfulness to all generations is proved by the ground underfoot. The earth is produced as evidence.",
    '119:91': "\"All are thy servants.\" Sun and season are described as obeying in the way he is still trying to.",
    '119:92': "\"I should then have perished in mine affliction.\" He says plainly that delight in the law is what kept him alive.",
    '119:93': "The precepts are never to be forgotten because \"with them thou hast quickened me.\" Gratitude is the reason, not discipline.",
    '119:94': "\"I am thine, save me.\" The plea rests on belonging; the seeking is only mentioned second.",
    '119:95': "The wicked wait for him and he considers the testimonies. Those two activities are the whole of his situation.",
    '119:96': "\"An end of all perfection: but thy commandment is exceeding broad.\" Everything else has a limit he has already reached.",
})

TAKEAWAYS.update({
    # ---- Chapter 119: Mem, Nun, Samech, Ain, Pe ----
    '119:97': "\"O how love I thy law!\" The one exclamation in a hundred and seventy-six verses, and it is about a rule.",
    '119:98': "Wiser than his enemies because the commandments \"are ever with me.\" The advantage claimed is company, not cleverness.",
    '119:100': "\"I understand more than the ancients, because I keep thy precepts.\" Doing is named as the source of the knowing.",
    '119:102': "\"I have not departed from thy judgments: for thou hast taught me.\" His constancy is credited to the teacher.",
    '119:103': "Sweeter than honey. The law is described by taste, which is a word for wanting rather than for approving.",
    '119:104': "Understanding produces hatred of every false way. Discernment does not stay neutral in this psalm.",
    '119:105': "A lamp for the feet and a light for the path: enough to see the next step, never the whole road.",
    '119:106': "\"I have sworn, and I will perform it.\" He binds himself by oath, which means he does not trust his intention alone.",
    '119:109': "\"My soul is continually in my hand\" — life carried loose in the palm, always about to be dropped.",
    '119:110': "A snare is laid and he does not err. The danger is described as another man's trap rather than his own weakness.",
    '119:111': "The testimonies are taken \"as an heritage for ever.\" A man with no land names the law as the estate he inherits.",
    '119:112': "\"I have inclined mine heart.\" Elsewhere he asks God to do this; here he reports having done it himself.",
    '119:114': "\"My hiding place and my shield\" — one word for where he runs and one for what goes with him when he cannot.",
    '119:115': "\"Depart from me, ye evildoers.\" Keeping the commandments is treated as requiring a change of company.",
    '119:116': "\"Let me not be ashamed of my hope.\" The fear named is not of dying but of having hoped for nothing.",
    '119:118': "Those who err are trodden down, \"for their deceit is falsehood.\" What ruins them is the lie they told themselves.",
    '119:119': "The wicked are put away like dross, and his response is to love the testimonies more. Judgement increases the affection.",
    '119:120': "\"My flesh trembleth for fear of thee.\" The man who delights in the law is frightened of its author.",
    '119:121': "A claim of innocence, immediately followed by a plea for help. Neither one is allowed to cancel the other.",
    '119:122': "\"Be surety for thy servant.\" He asks God to stand as guarantor, the way a man pledges himself for a debtor.",
    '119:125': "\"I am thy servant; give me understanding.\" The standing is claimed first and the understanding asked as a servant's due.",
    '119:126': "\"It is time for thee, LORD, to work.\" He tells God the hour has come, because men have made the law void.",
    '119:127': "\"Therefore I love thy commandments above gold.\" His love for them is the consequence of watching them broken.",
    '119:128': "All precepts concerning all things are right. The comprehensiveness is the claim, and it rules out choosing among them.",
    '119:129': "The testimonies are \"wonderful,\" and that, rather than duty, is the reason given for keeping them.",
    '119:130': "\"The entrance of thy words giveth light... unto the simple.\" This is the opposite of a knowledge for insiders.",
    '119:131': "\"I opened my mouth, and panted.\" The longing is described physically, like a man out of breath.",
    '119:133': "\"Let not any iniquity have dominion over me.\" Sin is spoken of as a ruler, and the prayer is about who governs.",
    '119:135': "The Aaronic blessing is asked for, and what he wants to get out of the shining face is instruction.",
    '119:136': "\"Rivers of waters run down mine eyes.\" The weeping is over other men's disobedience, not over his own trouble.",
})

TAKEAWAYS.update({
    # ---- Chapter 119: Tzaddi, Koph, Resh, Schin, Tau ----
    '119:137': "\"Righteous art thou.\" The verdict on God is entered before any verdict on his own case is requested.",
    '119:139': "\"My zeal hath consumed me.\" What his enemies forgot is what eats him, and the damage is all to himself.",
    '119:140': "\"Thy word is very pure: therefore thy servant loveth it.\" The love follows from what the word is, not what it gives him.",
    '119:141': "\"I am small and despised: yet do not I forget thy precepts.\" His standing has not changed, only what he holds on to.",
    '119:143': "\"Trouble and anguish have taken hold on me: yet thy commandments are my delights.\" Both are true, and neither is denied.",
    '119:144': "\"Give me understanding, and I shall live.\" Understanding is asked for as the thing survival depends on.",
    '119:145': "\"I cried with my whole heart.\" The wholeness claimed earlier for the seeking is now claimed for the shouting.",
    '119:147': "He is up before dawn and crying. Hoping in the word is what gets a man out of bed early.",
    '119:148': "His eyes are open ahead of the night watches. The watchmen are outlasted by a man lying awake meditating.",
    '119:150': "Those who follow mischief draw near, and they are \"far from thy law.\" Two distances are measured in one line.",
    '119:151': "\"Thou art near, O LORD.\" The answer to enemies drawing close is that somebody else is closer.",
    '119:152': "The testimonies were founded \"of old\" and for ever. He was not there at the start and will not see the end.",
    '119:153': "\"Consider mine affliction, and deliver me.\" He asks to be looked at before he asks to be helped.",
    '119:154': "\"Plead my cause.\" God is asked to act as advocate in a case the psalmist cannot argue himself.",
    '119:155': "Salvation is far from the wicked because they do not seek the statutes. The distance is of their own making.",
    '119:157': "Persecutors many; and the only thing he reports about himself is that he has not declined.",
    '119:159': "\"Consider how I love thy precepts\" — he offers his affection as evidence and then asks for lovingkindness anyway.",
    '119:160': "\"Thy word is true from the beginning.\" Its truth is dated to the start rather than established by what came after.",
    '119:161': "Princes persecute him and his heart stands in awe of the word. The fear he actually feels is not of them.",
    '119:162': "\"As one that findeth great spoil.\" The joy is a soldier's over plunder, not a scholar's over a text.",
    '119:164': "Seven times a day. The praise is counted, which means it is scheduled rather than waited for.",
    '119:165': "\"Nothing shall offend them\" — nothing makes them stumble. It is not a promise that nothing will upset them.",
    '119:166': "Hoping and doing are reported in one sentence, and neither is offered as a substitute for the other.",
    '119:168': "\"For all my ways are before thee.\" He keeps the precepts on the understanding that he is already being watched.",
    '119:169': "\"Let my cry come near before thee.\" Even the prayer has to be granted permission to approach.",
    '119:171': "The praise waits on the teaching. He will not offer worship built out of his own guesses.",
    '119:173': "\"For I have chosen thy precepts.\" The choosing is named as the ground of asking, not as a claim on being answered.",
    '119:174': "Longing for salvation and delighting in the law sit in one line. He has still not got the thing he wants most.",
    '119:175': "\"Let my soul live, and it shall praise thee.\" He argues for his life by naming what God would otherwise lose.",
    '119:176': "\"I have gone astray like a lost sheep.\" A hundred and seventy-six verses on loving the law end by asking to be searched for.",
})

TAKEAWAYS.update({
    # ---- Chapter 120 ----
    '120:1': "\"In my distress I cried unto the LORD, and he heard me.\" The answer is reported before the complaint is made.",
    '120:2': "What he asks to be delivered from is words. Lying lips are treated as a thing a soul needs rescuing from.",
    '120:3': "\"What shall be given unto thee... thou false tongue?\" He turns and addresses the tongue as if it were a person.",
    '120:4': "Sharp arrows and coals of juniper. The sentence passed on a tongue is fire, which is what it already was.",
    '120:5': "Mesech and Kedar lie at opposite ends of the known world. He names both to say he belongs in neither.",
    '120:6': "\"My soul hath long dwelt with him that hateth peace.\" The trouble is not a siege but an address.",
    '120:7': "\"I am for peace: but when I speak, they are for war.\" Even his peacemaking is heard as provocation.",

    # ---- Chapter 121 ----
    '121:1': "The hills are where help is looked for, not where it is found. The verse is a question the next one answers.",
    '121:2': "Help comes from the one who made heaven and earth, which is larger than the hills he had been scanning.",
    '121:3': "The psalm switches from I to thee here: someone else has taken up the song and is singing it back to him.",
    '121:4': "\"Shall neither slumber nor sleep.\" The single difference from every human watchman is offered as the whole comfort.",
    '121:5': "\"Thy shade upon thy right hand\" — the keeper stands where a man's shield hand is not.",
    '121:6': "Sun by day, moon by night. The danger is named for both halves of the clock so that nothing is left uncovered.",
    '121:7': "Preservation from all evil is narrowed in the same breath to the soul, which is the part that cannot be replaced.",
    '121:8': "Going out and coming in, from this time forth. The promise is cut to fit an ordinary day and then extended past a life.",

    # ---- Chapter 122 ----
    '122:1': "\"I was glad when they said unto me.\" The gladness is about the invitation, before a step of the journey is taken.",
    '122:2': "\"Our feet shall stand within thy gates.\" Arrival is reported by the feet, which is how travellers notice it.",
    '122:3': "\"Builded as a city that is compact together\" — joined stonework read as a picture of a joined people.",
    '122:4': "The tribes go up because of a testimony. The pilgrimage is obedience to a command, not an idea somebody had.",
    '122:5': "Thrones of judgment are set there too. The city of worship is also where a man's case finally gets heard.",
    '122:6': "\"Pray for the peace of Jerusalem\" is the one command in the psalm, and it asks for prayer rather than a visit.",
    '122:7': "Peace within the walls, prosperity within the palaces: the prayer covers the people who run the place.",
    '122:8': "\"For my brethren and companions' sakes.\" He wants the city's peace for the sake of whoever happens to be in it.",
    '122:9': "The last reason given is the house of God, so the good he seeks for the city is not the city's own.",

    # ---- Chapter 123 ----
    '123:1': "\"Unto thee lift I up mine eyes.\" The eyes go up to the heavens because every nearer direction has been tried.",
    '123:2': "Servants watch a hand, not a face. What is waited for is the small movement that signals a decision.",
    '123:3': "\"Have mercy upon us\" twice in one verse. Repetition is what a man falls back on when he has nothing else to say.",
    '123:4': "The scorn comes from \"those that are at ease.\" Contempt is named as a luxury of the comfortable.",

    # ---- Chapter 124 ----
    '124:1': "\"If it had not been the LORD who was on our side\" — the psalm is built on a sentence nobody is willing to finish.",
    '124:2': "Israel is told to say it aloud. The rescue has to be spoken in public or it will be remembered wrongly.",
    '124:3': "\"Swallowed us up quick\" — alive. The danger is described as being eaten whole rather than killed first.",
    '124:4': "The image switches from a mouth to a flood, and both are things that close over a man's head.",
    '124:6': "They were not saved from the teeth but from being handed over to them. The mercy is in what was withheld.",
    '124:7': "\"The snare is broken, and we are escaped.\" The bird did nothing; what changed was the trap.",
    '124:8': "The escape is filed under the maker of heaven and earth, which rules out calling it luck.",

    # ---- Chapter 125 ----
    '125:1': "Trust is not praised here as an effort but described by what it makes a man resemble: a mountain nobody moves.",
    '125:2': "The hills around Jerusalem are the picture, so the protection is the kind you were born inside and never chose.",
    '125:3': "The rod of the wicked is cut short \"lest the righteous put forth their hands unto iniquity.\" Oppression is limited to keep it from corrupting.",
    '125:4': "\"Do good, O LORD, unto those that be good.\" The prayer asks for nothing more than that the order hold.",
    '125:5': "Crooked ways lead a man out with the workers of iniquity, and the psalm still ends by pronouncing peace on Israel.",

    # ---- Chapter 126 ----
    '126:1': "\"We were like them that dream.\" The rescue was so complete it felt unreal to the people it happened to.",
    '126:2': "The heathen supplied the interpretation. Outsiders named what the LORD had done before Israel got round to it.",
    '126:3': "Israel repeats the heathen's sentence as its own and adds only that it is glad.",
    '126:4': "Having said the captivity was turned, they ask for it to be turned again. The return was partial, and they say so.",
    '126:5': "\"They that sow in tears shall reap in joy.\" The weeping is not the delay before the sowing; it is the sowing.",
    '126:6': "The seed is precious and it is buried anyway. Grief is pictured as a man spending what he cannot spare.",

    # ---- Chapter 127 ----
    '127:1': "Building and watching are not forbidden, only guaranteed. \"In vain\" is a verdict on the outcome, not on the work.",
    '127:2': "\"So he giveth his beloved sleep.\" Sleep is the proof that a man has stopped trying to be the one holding it together.",
    '127:3': "Heritage and reward are words for what is received. Children are put in the same class as land a man did not buy.",
    '127:4': "Arrows exist to be let go. A child is pictured as something aimed away from the hand that holds it.",
    '127:5': "\"They shall speak with the enemies in the gate.\" The blessing is that he will not have to stand alone in court.",
})

TAKEAWAYS.update({
    # ---- Chapter 128 ----
    '128:1': "The blessed man is defined twice in one line: he fears, and he walks. Neither half is offered without the other.",
    '128:2': "\"Thou shalt eat the labour of thine hands.\" The first blessing named is eating what you made, which is not always allowed.",
    '128:3': "A vine and olive plants. The household is pictured as a smallholding, and a family as something that takes years.",
    '128:4': "\"Behold, that thus shall the man be blessed.\" The blessing was so domestic that it needed pointing at.",
    '128:5': "The blessing comes out of Zion to a man in his own kitchen. The public place supplies the private one.",
    '128:6': "Grandchildren and peace upon Israel end the psalm together: a long life is only good inside a country at rest.",

    # ---- Chapter 129 ----
    '129:1': "\"From my youth.\" The affliction is dated to the beginning, so there is no earlier and better time to go back to.",
    '129:2': "The line repeats itself and then breaks: \"yet they have not prevailed.\" Survival is the only claim being made.",
    '129:3': "\"The plowers plowed upon my back.\" Flogging is described as farm work, done patiently and for a crop.",
    '129:4': "Righteousness is demonstrated by cutting a rope. The verdict on God is entered as an action, not an opinion.",
    '129:5': "What is asked on Zion's haters is confusion and retreat. The curse stops well short of destroying them.",
    '129:6': "Grass on a housetop withers before it grows. The wish is for an enemy who never gets started.",
    '129:7': "No handful for the mower, no armful for the binder. The failure is measured by what a harvester cannot pick up.",
    '129:8': "Passers-by withhold the ordinary blessing of the fields. Even the greeting between strangers is refused them.",

    # ---- Chapter 130 ----
    '130:1': "\"Out of the depths.\" Where he is praying from is stated before anything at all is asked for.",
    '130:2': "He asks for ears before he asks for hands. The first request is only to be listened to.",
    '130:3': "\"If thou, LORD, shouldest mark iniquities... who shall stand?\" A question that closes the case without waiting for a reply.",
    '130:4': "\"That thou mayest be feared.\" Forgiveness produces reverence. Being let off is not the same as being made casual.",
    '130:5': "The waiting is repeated and then given something to hold: \"in his word do I hope.\"",
    '130:6': "More than they that watch for the morning, said twice. Watchmen are certain the sun is coming; that is the comparison.",
    '130:7': "Israel is told to hope on exactly the ground he did, and the ground is mercy and plenteous redemption.",
    '130:8': "\"He shall redeem Israel from all his iniquities.\" The rescue the psalm ends on is from sin, not from enemies.",

    # ---- Chapter 131 ----
    '131:1': "A man states that his heart is not haughty, which is close to impossible to say without becoming it.",
    '131:2': "The comparison is not to an infant but to a weaned child: one that is with its mother and no longer demanding.",
    '131:3': "Three verses about one man's quiet end by telling the whole nation to hope.",

    # ---- Chapter 132 ----
    '132:1': "\"Remember David, and all his afflictions.\" God is asked to recall a man's trouble rather than his merit.",
    '132:3': "The oath opens with what he will not do, and it is go home. God's house is put ahead of his own.",
    '132:4': "No sleep, no slumber. He swears off the very thing another Song of Degrees calls a gift to the beloved.",
    '132:5': "\"Until I find out a place for the LORD.\" The vow has a stopping condition and it is not his own comfort.",
    '132:6': "\"We found it in the fields of the wood.\" The ark had to be located, because it had been left where it fell out of use.",
    '132:7': "\"We will worship at his footstool.\" The furthest into the room they expect to get is the floor by his feet.",
    '132:8': "God is asked to arise so that he can sit down, and the ark is what moves when he does.",
    '132:9': "The request made for the priests is about what they wear rather than what they do.",
    '132:10': "\"For thy servant David's sake.\" The plea rests on a dead king rather than on the living one making it.",
    '132:11': "David swore in verse three; here the LORD swears back, and only this oath is said to be one he will not turn from.",
    '132:12': "The everlasting throne is promised and then made conditional on the children. The psalm does not hide the clause.",
    '132:13': "\"The LORD hath chosen Zion.\" David went looking for a place; the answer is that the choosing was never his.",
    '132:14': "\"Here will I dwell; for I have desired it.\" Desire is given as the reason, which is to give no reason at all.",
    '132:15': "The first promise made to the chosen city is bread for its poor.",
    '132:16': "Verse nine asked for priests clothed with righteousness; they are clothed with salvation instead. The answer exceeds the request.",
    '132:17': "A horn budding and a lamp kept burning: two small things, both meaning the line has not gone out.",
    '132:18': "Enemies clothed with shame, the king's own crown flourishing. One verb dresses both, and only one is dressed well.",

    # ---- Chapter 133 ----
    '133:1': "Unity is praised for being pleasant, which is a lower and more honest claim than praising it for being right.",
    '133:2': "The oil is poured on one head and runs down to the hem. Unity is pictured as something given to a man and reaching everyone.",
    '133:3': "Dew off Hermon falling on Zion: water carried from a northern mountain to a dry southern one, which does not happen by itself.",

    # ---- Chapter 134 ----
    '134:1': "The servants addressed are the ones who \"by night stand in the house.\" The night shift is the congregation here.",
    '134:2': "Hands lifted in the sanctuary. Blessing God is given a posture before it is given any words.",
    '134:3': "The psalm turns the blessing round at the end: those told to bless are blessed back out of Zion.",
})

TAKEAWAYS.update({
    # ---- Chapter 135 ----
    '135:1': "The servants of the LORD are summoned first. The call to praise goes to the staff before it goes to the crowd.",
    '135:2': "Those that \"stand in the house\" are addressed. The praise is asked of people already on the premises.",
    '135:3': "Two reasons are given: he is good, and it is pleasant. The second is not embarrassed to be about the singer.",
    '135:4': "Jacob was chosen \"unto himself.\" Election is described as God acquiring something for his own keeping.",
    '135:5': "\"For I know that the LORD is great.\" One man's first-person knowledge, dropped into a congregation's psalm.",
    '135:6': "\"Whatsoever the LORD pleased, that did he.\" Pleasure and power are the same fact, in four regions of the world.",
    '135:7': "Vapours, lightnings and wind out of his treasuries. Weather is filed as stored goods that he spends.",
    '135:8': "The firstborn of Egypt, of man and beast. The praise does not step around what the rescue cost somebody else.",
    '135:9': "\"Into the midst of thee, O Egypt.\" The psalm breaks off and speaks to Egypt directly, as if it were listening.",
    '135:10': "Great nations and mighty kings are named as a class before any one of them is named as a man.",
    '135:12': "\"And gave their land for an heritage.\" What was taken by force is handed on in the language of inheritance.",
    '135:13': "Name and memorial endure through all generations. What lasts is not the land but the reputation attached to it.",
    '135:14': "\"He will judge his people, and he will repent himself concerning his servants.\" Judgement here ends in him relenting.",
    '135:15': "Idols are silver and gold, \"the work of men's hands.\" The expensive material is listed first and does not help.",
    '135:16': "Mouths that do not speak, eyes that do not see. The idol is mocked for what it has, not for what it lacks.",
    '135:17': "No breath in their mouths. Breath is the one thing the craftsman could not fit.",
    '135:18': "\"They that make them are like unto them.\" A man ends up as deaf as the thing he worships.",
    '135:19': "The house of Israel and the house of Aaron are called separately: the nation and its priests are addressed as two things.",
    '135:21': "The blessing returns to Zion, to a God who \"dwelleth at Jerusalem\" — near enough to be addressed by address.",

    # ---- Chapter 136 ----
    '136:1': "\"For he is good\" is the first reason given, and the twenty-five verses after it are worked examples.",
    '136:2': "\"God of gods.\" The thanksgiving begins by placing him over the competition rather than alone in an empty field.",
    '136:3': "\"Lord of lords\" is a political title where the last was a religious one. Both are ranks held over rivals.",
    '136:4': "\"To him who alone doeth great wonders.\" The word that carries the verse is alone; the wonders are shared with nobody.",
    '136:5': "The heavens were made \"by wisdom,\" which makes creation a piece of thinking rather than a burst of strength.",
    '136:6': "The earth is stretched out above the waters. Dry land is described as something held up over a flood.",
    '136:7': "Great lights are made and not named. The psalm follows Genesis in refusing to give the sun and moon their titles.",
    '136:8': "The sun rules the day, and the authority it holds is delegated rather than its own.",
    '136:9': "The moon and stars rule by night, which is to say that the dark is governed too.",
    '136:10': "The list runs out of creation and into the firstborn of Egypt without changing tone.",
    '136:11': "Israel is brought out \"from among them.\" The exodus is described as extraction rather than as victory.",
    '136:12': "A strong hand and a stretched out arm. The rescue is credited to the body language of a fighter.",
    '136:13': "The Red sea is \"divided into parts,\" which is a builder's verb used on water.",
    '136:14': "Israel passes through the midst of it. The way out runs through the thing that was going to drown them.",
    '136:15': "Pharaoh is overthrown in the same water Israel walked across. One sea does both jobs.",
    '136:16': "Leading them through the wilderness is counted among the wonders, though nothing visible happened for forty years.",
    '136:17': "\"To him which smote great kings.\" The list moves from Egypt to Canaan without pausing for breath.",
    '136:19': "Sihon is named, so the mercy that endures for ever is attached to one specific defeated man.",
    '136:21': "\"And gave their land for an heritage.\" A conquest is entered in the record under the word for a gift.",
    '136:23': "\"Who remembered us in our low estate.\" The psalm leaves history here and arrives at the people singing it.",
    '136:24': "Redemption from enemies is put in the past tense, in the same list as the Red sea.",
    '136:25': "\"Who giveth food to all flesh.\" The catalogue of Israel's rescues ends with a mercy that feeds everybody.",
    '136:26': "The closing title is \"God of heaven,\" the name used by exiles living under somebody else's king.",

    # ---- Chapter 137 ----
    '137:1': "\"There we sat down, yea, we wept.\" The weeping is given a place and a time, which is how grief gets remembered.",
    '137:2': "The harps are hung up, not broken. The instruments are kept back for a use nobody can yet imagine.",
    '137:3': "The captors want the songs of Zion for entertainment. Worship is demanded of them as mirth.",
    '137:4': "\"How shall we sing the LORD's song in a strange land?\" The refusal is a question about whether it would still be that song.",
    '137:5': "He curses his own right hand if he forgets. The punishment chosen is the loss of the skill they asked him to perform.",
    '137:6': "Jerusalem is set \"above my chief joy.\" Remembering is deliberately ranked higher than being happy.",
    '137:7': "Edom is remembered for words: \"Rase it, rase it.\" The neighbour is charged with the cheering, not the wrecking.",
    '137:8': "\"That rewardeth thee as thou hast served us.\" The wish asks for the same measure back and nothing beyond it.",
    '137:9': "The Psalter lets a prayer be this ugly rather than pretend the grief behind it was smaller than it was.",
})

TAKEAWAYS.update({
    # ---- Chapter 138 ----
    '138:1': "\"Before the gods will I sing praise unto thee.\" He praises in front of the rivals rather than out of their hearing.",
    '138:2': "\"Thou hast magnified thy word above all thy name.\" What God has said is ranked above his own reputation.",
    '138:3': "The answer came on the day he cried, and what arrived was strength in the soul rather than a change outside it.",
    '138:4': "Kings praise him \"when they hear the words of thy mouth.\" The conversion of rulers happens by hearing, like anyone else's.",
    '138:5': "\"They shall sing in the ways of the LORD.\" The kings end up walking the road, not standing back admiring it.",
    '138:6': "The high one has respect to the lowly and knows the proud afar off. Distance is all that pride is granted.",
    '138:7': "\"Though I walk in the midst of trouble.\" No exit is promised; the reviving happens inside the trouble.",
    '138:8': "\"Forsake not the works of thine own hands.\" He argues from God's investment rather than from his own worth.",

    # ---- Chapter 139 ----
    '139:1': "Searching takes effort; knowing does not. The psalm opens with both words and never says which came first.",
    '139:2': "Sitting down and getting up are the least remarkable things a body does, and those are what is said to be known.",
    '139:3': "\"Thou compassest my path\" — the verb is a farmer's, used of sifting grain. It is that sort of attention.",
    '139:4': "The word is known before the tongue arrives at it. No interval is left between thinking and being heard.",
    '139:5': "\"Beset me behind and before.\" The language is of a siege, and the hand laid on him could be arrest or blessing.",
    '139:6': "\"It is high, I cannot attain unto it.\" He stops, and the stopping is not treated anywhere as a failure.",
    '139:7': "The question is where he could flee to, which means the knowledge of verse one was first felt as a problem.",
    '139:8': "Heaven and hell are named as the two extremes, and the answer given for both is the same two words.",
    '139:9': "\"The wings of the morning\" — the speed of daybreak crossing the sea, and still not fast enough to outrun him.",
    '139:10': "At the far edge of the sea the hand that beset him leads him. The same presence has changed from pursuer to guide.",
    '139:11': "Darkness is the last hiding place he tries, and he tries it by saying so rather than by moving.",
    '139:12': "\"The darkness and the light are both alike to thee.\" What hides a man from other men does nothing at all here.",
    '139:13': "\"Thou hast possessed my reins.\" The knowing is traced back past memory to ownership, before he was anything to know.",
    '139:14': "\"Fearfully and wonderfully made.\" The praise is for the body, and the fear inside the word is not tidied away.",
    '139:15': "\"Curiously wrought in the lowest parts of the earth.\" The womb is described as a workshop underground.",
    '139:16': "All his days were written before any of them happened. The book is finished before the life begins.",
    '139:17': "The thoughts he was fleeing in verse seven are now called precious. Nothing has changed except where he stands.",
    '139:18': "\"When I awake, I am still with thee.\" He falls asleep counting, and the presence outlasts the counting.",
    '139:19': "The psalm turns without warning to bloody men. Being known by God and hating the wicked are set down side by side.",
    '139:20': "The charge against them is speech: they take the name in vain, and the name is what he has spent the psalm on.",
    '139:21': "\"Do not I hate them, O LORD, that hate thee?\" He offers his hatred as loyalty, and phrases it as a question.",
    '139:22': "\"Perfect hatred\" claims to be complete, two verses before he asks God to check whether anything in him is clean.",
    '139:23': "Having searched the world for somewhere to hide from the searching, he asks to be searched.",
    '139:24': "\"See if there be any wicked way in me.\" He will not certify his own heart, having just announced what is in it.",

    # ---- Chapter 140 ----
    '140:1': "The evil man and the violent man. What he needs deliverance from is a person, named twice in one line.",
    '140:2': "Mischief is imagined in the heart and then gathered for war. The sequence runs from a thought to an army.",
    '140:3': "Sharpened tongues and adders' poison. The weapon is speech again, and it is the kind that works slowly.",
    '140:4': "\"Who have purposed to overthrow my goings.\" What they are aiming at is his walking, the ordinary motion of a life.",
    '140:5': "Snare, cords, net and gins: four words for a trap, set by \"the proud,\" who would need none if they were strong.",
    '140:6': "\"I said unto the LORD, Thou art my God.\" In the middle of the traps he stops to state whose he is.",
    '140:7': "\"Thou hast covered my head in the day of battle.\" The one past mercy he names is a helmet.",
    '140:8': "He asks that the wicked not get what they want, \"lest they exalt themselves.\" Answered prayer is treated as dangerous.",
    '140:9': "The mischief of their own lips is asked to cover them, the way his own head was covered in battle.",
    '140:10': "Burning coals and deep pits, and the request attached is only that they not rise up again.",
    '140:11': "\"Evil shall hunt the violent man.\" Violence is described as turning round and tracking the man who sent it out.",
    '140:12': "\"I know that the LORD will maintain the cause of the afflicted.\" The certainty is about a class of people, not himself.",
    '140:13': "The psalm that opened with violent men closes with the upright dwelling in God's presence, which is the only safety offered.",
})

TAKEAWAYS.update({
    # ---- Chapter 141 ----
    '141:1': "\"Make haste unto me.\" Speed is asked for before anything else, which is what a man asks when time is short.",
    '141:2': "Prayer as incense, lifted hands as the evening sacrifice. A man far from the temple keeps its hours anyway.",
    '141:3': "\"Keep the door of my lips.\" With enemies all round him, the guard he asks for is over his own mouth.",
    '141:4': "The danger named is not their violence but their dainties. The pull he fears is toward joining them at dinner.",
    '141:5': "\"Let the righteous smite me; it shall be a kindness.\" A blow from a good man is preferred to a meal with a bad one.",
    '141:6': "His words will be heard sweet once the judges are overthrown. Some things cannot be said until power changes hands.",
    '141:7': "\"As when one cutteth and cleaveth wood upon the earth.\" The dead are described as split logs left where they fell.",
    '141:8': "\"But mine eyes are unto thee.\" The turn comes at the scattered bones, with nothing improved except where he is looking.",
    '141:9': "He asks to be kept from the snares rather than to have them cleared away.",
    '141:10': "\"Whilst that I withal escape.\" The escape he wants is a quiet one: he walks past while the nets close elsewhere.",

    # ---- Chapter 142 ----
    '142:1': "Voice is named twice in a single verse. Prayer that stays in the head is not what he is describing.",
    '142:2': "\"I poured out my complaint before him.\" The complaint is not tidied up before it is handed over.",
    '142:3': "\"When my spirit was overwhelmed within me, then thou knewest my path.\" Being known is the comfort when he cannot see the way.",
    '142:4': "\"No man cared for my soul.\" The worst line in the psalm is about absence rather than attack.",
    '142:5': "\"My refuge and my portion in the land of the living.\" A man hiding in a cave calls God the piece of ground allotted to him.",
    '142:6': "\"They are stronger than I\" is offered as a reason for help, not as an apology for needing it.",
    '142:7': "\"Bring my soul out of prison, that I may praise thy name.\" He gives God a use for his release.",

    # ---- Chapter 143 ----
    '143:1': "He asks to be answered in God's faithfulness and righteousness, then immediately asks not to be judged by them.",
    '143:2': "\"In thy sight shall no man living be justified.\" The verse Paul takes up: nobody at all comes through that court.",
    '143:3': "\"As those that have been long dead.\" He is not describing a threat of death but a life already conducted underground.",
    '143:4': "Spirit overwhelmed, heart desolate. The damage reported is interior, after the attack was described as coming from outside.",
    '143:5': "Remember, meditate, muse: three verbs for going back over old evidence when no new evidence is coming.",
    '143:6': "\"My soul thirsteth after thee, as a thirsty land.\" Dry ground does not beg; it simply cracks open where anyone can see.",
    '143:7': "\"Hide not thy face from me.\" What he dreads is not dying but going down without an answer.",
    '143:8': "Lovingkindness in the morning and the way he should walk are asked for together, as though they were one request.",
    '143:9': "\"I flee unto thee to hide me.\" Deliverance is requested by a man already running in that direction.",
    '143:10': "\"Teach me to do thy will; for thou art my God.\" The reason he gives for wanting instruction is whose he is.",
    '143:11': "\"For thy name's sake.\" He argues for his life from God's reputation, since verse two removed every other argument.",
    '143:12': "\"For I am thy servant.\" The psalm asks for enemies cut off on exactly the ground it asked for mercy.",

    # ---- Chapter 144 ----
    '144:1': "\"Which teacheth my hands to war.\" A soldier's skill is credited to God the way any other trade would be.",
    '144:2': "Seven names for God in one verse, and the last thing said is that he subdues a people under David.",
    '144:3': "\"LORD, what is man, that thou takest knowledge of him!\" The warrior king asks it straight after listing his own strength.",
    '144:4': "\"His days are as a shadow that passeth away.\" A shadow is not nothing; it is a shape with nothing inside it.",
    '144:5': "\"Bow thy heavens, O LORD, and come down.\" The request is for God to leave his own place and arrive here.",
    '144:6': "Lightning and arrows. The weather is asked for as artillery, with no apology for the mixture.",
    '144:7': "\"Rid me... out of great waters.\" The enemies are described as a flood before they are described as men.",
    '144:8': "A mouth that speaks vanity and a right hand of falsehood. A lying word and a lying handshake are charged as one offence.",
    '144:9': "The new song is promised in the middle of the prayer, before the rescue it would be about has happened.",
    '144:10': "\"It is he that giveth salvation unto kings.\" Verse one had his hands taught; here even a king is merely delivered.",
    '144:12': "Sons like grown plants, daughters like the corner stones of a palace. What he wants for the nation is the shape of its children.",
    '144:13': "Full garners and sheep by the thousand. The blessing asked for is ordinary surplus, listed like an inventory.",
    '144:14': "\"No complaining in our streets.\" The last item wanted is that people should have run out of things to complain about.",
    '144:15': "\"Happy is that people, whose God is the LORD.\" After a page of wanted goods, the happiness is quietly relocated.",
})

TAKEAWAYS.update({
    # ---- Chapter 145 ----
    '145:1': "\"I will extol thee, my God, O king.\" The man who is king in the psalm before gives the title away here.",
    '145:2': "Every day, and for ever and ever. The praise is promised at both scales in a single sentence.",
    '145:3': "\"His greatness is unsearchable.\" The psalm of praise opens by admitting that it cannot finish the job.",
    '145:4': "One generation praises to another. Praise is treated as something handed down rather than something felt.",
    '145:5': "What he undertakes is to speak. The verbs through this psalm are all about saying, never about feeling.",
    '145:6': "Men speak of his terrible acts; he speaks of his greatness. The crowd and the singer report different things.",
    '145:7': "\"They shall abundantly utter the memory of thy great goodness.\" The goodness is said aloud before it is explained.",
    '145:8': "Gracious, full of compassion, slow to anger: the words given at Sinai, quoted back to God as praise.",
    '145:9': "\"The LORD is good to all.\" The tender mercies are put over all his works, not over the covenant people alone.",
    '145:10': "The works praise him and the saints bless him. Two choirs, and only one of them chose to sing.",
    '145:11': "They speak of the glory of his kingdom. A political word is doing the work in the middle of a hymn.",
    '145:12': "The point of the saints talking is \"to make known to the sons of men.\" Praise here is aimed at outsiders.",
    '145:13': "\"Thy kingdom is an everlasting kingdom.\" The line that outlasts everything sits in the middle rather than at the end.",
    '145:14': "\"The LORD upholdeth all that fall.\" The unsearchable greatness of verse three is demonstrated by catching people.",
    '145:15': "\"The eyes of all wait upon thee.\" Every creature is put in the posture the Songs of Degrees gave to servants.",
    '145:16': "\"Thou openest thine hand.\" The feeding of everything alive is described as one gesture.",
    '145:17': "Righteous in all his ways and holy in all his works. The claim is made to cover what is not understood as well.",
    '145:18': "He is near to all that call, \"to all that call upon him in truth.\" The one qualification added is honesty.",
    '145:19': "The desire of them that fear him is fulfilled, which is not offered as a promise about desire in general.",
    '145:20': "Preserving and destroying are set in one line, and the psalm makes no attempt to blur the join.",
    '145:21': "One mouth begins the psalm and all flesh finishes it.",

    # ---- Chapter 146 ----
    '146:1': "\"Praise the LORD, O my soul.\" The command is issued to himself before anyone else is addressed.",
    '146:2': "Praise is promised for as long as he has \"any being,\" which quietly concedes that there is an end to it.",
    '146:3': "\"Put not your trust in princes.\" The warning is not that they are wicked but that they are no use.",
    '146:4': "\"In that very day his thoughts perish.\" A man's plans die on the same day he does, with nothing left running.",
    '146:5': "Happiness is moved from the prince to the God of Jacob, who is identified by a man dead a thousand years.",
    '146:6': "The maker of everything \"keepeth truth for ever.\" Creation is cited to prove that he does not change his mind.",
    '146:7': "Judgment for the oppressed, food for the hungry, prisoners loosed. The creator's record is read out as social work.",
    '146:8': "Eyes opened, the bowed down raised, the righteous loved. Three clauses, with the LORD as the subject of each.",
    '146:9': "Strangers, fatherless and widow: the three people with no family to protect them are the three he keeps.",
    '146:10': "\"The LORD shall reign for ever.\" This is the answer to the prince whose thoughts perished six verses earlier.",

    # ---- Chapter 147 ----
    '147:1': "Praise is called good, pleasant and comely: useful, enjoyable and fitting, in that order and without ranking them.",
    '147:2': "Building the city and gathering the outcasts are one work. The walls go up for the sake of the scattered.",
    '147:3': "\"He healeth the broken in heart, and bindeth up their wounds.\" A physician's verb is used on a feeling.",
    '147:4': "He counts the stars and calls them by name. The hands that bind up wounds are also taking an inventory of the sky.",
    '147:5': "\"His understanding is infinite.\" Set between the stars and the broken-hearted, the line is made to cover both.",
    '147:6': "Lifting the meek and casting down the wicked are one motion, reported in one line.",
    '147:7': "Thanksgiving and the harp. The praise commanded is to be made audible, and instruments are named for it.",
    '147:8': "Clouds, rain, grass. The chain is traced from the sky down to the grazing on a hillside.",
    '147:9': "\"The young ravens which cry.\" Provision reaches an unclean bird whose only contribution is noise.",
    '147:10': "He takes no pleasure in the horse or in the legs of a man, which are the two things an army counts.",
    '147:11': "What pleases him instead is fear and hope, neither of which can be measured by anybody watching.",
    '147:12': "Jerusalem and Zion are told to praise their own God, as if a city could be addressed like a person.",
    '147:13': "Strengthened gate bars and blessed children. The city is made safe so that what lives inside it can grow.",
    '147:14': "Peace in the borders and the finest of the wheat. Security is listed alongside good bread rather than victory.",
    '147:15': "\"His word runneth very swiftly.\" The commandment is pictured as a messenger already out on the road.",
    '147:16': "Snow like wool, hoarfrost like ashes. Winter is described in the language of the household.",
    '147:17': "\"Who can stand before his cold?\" The great question about power is asked here about the weather.",
    '147:18': "The same word that sent the ice melts it. A thaw is credited to a sentence rather than to a season.",
    '147:19': "The word that runs through the weather is also shown to Jacob, and there it arrives as statutes.",
    '147:20': "\"He hath not dealt so with any nation.\" The final boast is not about being loved but about having been told.",
})

TAKEAWAYS.update({
    # ---- Chapter 148 ----
    '148:1': "The praise starts in the heights, with whatever is already up there and needed no summoning.",
    '148:2': "Angels and hosts are commanded to praise, which settles the question of whether praise was a human invention.",
    '148:3': "Sun, moon and stars are told to praise. The gods of the neighbouring nations are put in the choir instead.",
    '148:4': "\"Ye waters that be above the heavens.\" Even the water nobody has ever seen is called into the summons.",
    '148:5': "\"For he commanded, and they were created.\" What is owed is traced to the fact that a word is what made them.",
    '148:6': "A decree \"which shall not pass\" holds them in place. For the stars, keeping their orbit is the praise.",
    '148:7': "The list moves down to earth and starts with dragons and the deeps. The frightening things are called first.",
    '148:8': "\"Stormy wind fulfilling his word.\" The weather that flattens a harvest is described as obedient.",
    '148:9': "Mountains and hills, fruit trees and cedars: what men planted and what men never touched, named together.",
    '148:10': "Beasts, cattle, creeping things, flying fowl. The roll call follows the order of the sixth day of Genesis.",
    '148:11': "Kings and judges turn up in the middle of the list, between the cattle and the children, with no extra rank.",
    '148:12': "Young men, maidens, old men, children. No age is excused and none is given precedence.",
    '148:13': "\"His name alone is excellent.\" Everything listed praises him, and none of it is given a share of the excellence.",
    '148:14': "After the whole creation has sung, the psalm ends on one nation \"near unto him.\" The universal narrows to the particular.",

    # ---- Chapter 149 ----
    '149:1': "The new song is asked for in the congregation of saints, so the newness is corporate rather than private.",
    '149:2': "\"Let Israel rejoice in him that made him.\" The maker in view is the maker of a nation, not of the world.",
    '149:3': "Dance, timbrel and harp. The praise is given a body and a beat before it is given any doctrine.",
    '149:4': "\"He will beautify the meek with salvation.\" What the meek are given to wear is the rescue itself.",
    '149:5': "\"Let them sing aloud upon their beds.\" The public praise is told to go on where nobody is watching.",
    '149:6': "High praises in the mouth and a two-edged sword in the hand. The psalm puts these in one verse without apology.",
    '149:7': "Vengeance upon the heathen is handed to the saints, which is not where the New Testament leaves it.",
    '149:8': "Kings bound with chains. The rulers summoned to praise in the psalm before are here the ones being tied up.",
    '149:9': "\"The judgment written.\" The saints carry out a sentence already passed; nothing is being decided by them.",

    # ---- Chapter 150 ----
    '150:1': "Sanctuary and firmament. The two places named are the temple and the sky, and one praise is asked to fill both.",
    '150:2': "Praise for what he did and praise according to what he is. Those are the only two reasons the psalm offers.",
    '150:3': "The instruments begin with the trumpet, which is a signal before it is music.",
    '150:4': "Timbrel and dance. The body is listed here among the instruments, between the drum and the strings.",
    '150:5': "Cymbals twice, loud and then higher sounding. The last instrument named is the one that cannot be talked over.",
    '150:6': "\"Every thing that hath breath.\" By the end of the Psalter the only qualification required is being alive.",
})
