#!/usr/bin/env python3
"""Written takeaways for 1 Samuel."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:2': "Two wives, one fruitful and one empty. The book opens on a household that already cannot hold together.",
    '1:3': "Hophni and Phinehas are named as priests of the LORD before we learn what they are. The office is real; the men are not.",
    '1:5': "\"He loved Hannah: but the LORD had shut up her womb.\" Being loved and being barren are stated in one breath.",
    '1:6': "The text says plainly that God closed the womb and that a rival used it as a weapon. Both are true at once.",
    '1:7': "Year by year, at the house of the LORD. The place of worship is where the provocation was worst.",
    '1:8': "\"Am not I better to thee than ten sons?\" A husband answers grief by asking to be enough for it.",
    '1:9': "Eli sits by the post of the temple. The priest is in position, and sees nothing until it is pointed out to him.",
    '1:10': "\"In bitterness of soul.\" Prayer here is not composure offered to God but the lack of it.",
    '1:11': "She asks for a son and gives him away in the same sentence. The vow undoes the point of the request.",
    '1:13': "She spake in her heart, and the priest read drunkenness. Silent prayer was strange enough to be mistaken for vice.",
    '1:14': "Eli's first word to the godliest woman in Shiloh is a rebuke for a sin she has not committed.",
    '1:15': "\"I have poured out my soul before the LORD.\" She corrects him without denying him the title \"my lord.\"",
    '1:16': "\"Out of the abundance of my complaint and grief have I spoken.\" Complaint is offered to God as worship, not against it.",
    '1:17': "Eli gives a blessing without knowing the petition. He does not withdraw his mistake; he simply blesses.",
    '1:18': "Her countenance was no more sad, and nothing had yet changed but the fact that the matter was out of her hands.",
    '1:19': "\"The LORD remembered her.\" To be remembered in Scripture is not to be recalled but to be acted for.",
    '1:20': "Samuel — asked of God. The name makes the child a standing reminder of where he came from.",
    '1:22': "She will not go up until the child is weaned, because after that visit she will not bring him home again.",
    '1:23': "\"Only the LORD establish his word.\" Elkanah defers to the vow his wife made without him.",
    '1:24': "Three bullocks and an ephah of flour for a toddler's handover. She pays the cost of the vow in full.",
    '1:26': "\"I am the woman that stood by thee here, praying.\" She reminds the priest of the day he got her wrong.",
    '1:27': "\"For this child I prayed.\" The answered prayer is what makes the surrender possible and what makes it hurt.",
    '1:28': "Lent to the LORD as long as he liveth — a loan with no return date. Giving back what was given is the whole transaction.",

    # ---- Chapter 2 ----
    '2:1': "\"Mine horn is exalted in the LORD.\" Her joy is placed in the giver, not in the son she has just handed over.",
    '2:2': "\"Neither is there any rock like our God.\" The song's foundation is God's uniqueness, not Hannah's vindication.",
    '2:3': "\"By him actions are weighed.\" Not counted or watched — weighed, which is a judgement, not a record.",
    '2:4': "Bows broken and stumblers girded. The reversal runs both directions, and neither party arranged it.",
    '2:5': "\"The barren hath born seven.\" Hannah has one son so far and sings as though the whole pattern were settled.",
    '2:6': "\"The LORD killeth, and maketh alive.\" The song refuses to hand the dark half of providence to anyone else.",
    '2:7': "Poverty and wealth are both listed as God's work. The song will not let prosperity stand as proof of favour.",
    '2:8': "The beggar is lifted from the dunghill to inherit the throne of glory. Mary will sing this same line in Luke.",
    '2:9': "\"By strength shall no man prevail.\" The one sentence that rules out every way Israel will try to save itself in this book.",
    '2:10': "A woman with no king sings of the LORD's anointed. The book's whole argument is already in her last line.",
    '2:11': "The child stays and the parents go home. The ministry of Samuel begins as an act of leaving him behind.",
    '2:12': "\"Sons of Belial; they knew not the LORD\" — said of men who handled the sacrifices daily.",
    '2:13': "\"The priests' custom\" — the abuse had settled into procedure, which is how it went unchallenged.",
    '2:14': "Whatever the fleshhook brought up, the priest took. Chance dressed up as entitlement.",
    '2:15': "They demand the meat before the fat is burnt, taking their share ahead of God's.",
    '2:16': "\"I will take it by force.\" When the worshipper objects on God's behalf, the priest threatens him.",
    '2:17': "\"Men abhorred the offering of the LORD.\" The clergy's greed drove people away from the sacrifice itself.",
    '2:18': "A child in a linen ephod, ministering beside men who are ruining the priesthood. Both pictures stand in one house.",
    '2:19': "A little coat, made larger each year. Hannah keeps mothering the son she gave away, in the only way left to her.",
    '2:20': "Eli asks God to repay the loan with more children — and the blessing that costs him nothing is granted.",
    '2:21': "Five more children for Hannah. What was surrendered is not returned but multiplied elsewhere.",
    '2:22': "Eli hears everything, including the women at the tabernacle door. Knowing is exactly what will condemn him.",
    '2:23': "\"Why do ye such things?\" He asks a question where he holds the authority to act.",
    '2:24': "\"Nay, my sons.\" A reprimand so mild it sounds like a request, aimed at men profaning the sanctuary.",
    '2:25': "\"If a man sin against the LORD, who shall intreat for him?\" Eli states the problem exactly and does nothing about it.",
    '2:26': "Samuel grew in favour with the LORD and with men — the sentence Luke will borrow for the boy Jesus.",
    '2:27': "The rebuke begins with what God gave: appearing in Egypt, choosing this house. Grace is recited before the charge.",
    '2:28': "The priesthood and its provisions were a gift. That is what makes the abuse of them theft rather than error.",
    '2:29': "\"Thou honourest thy sons above me.\" The father's fault is not the sons' sin but his preference of them.",
    '2:30': "\"Them that honour me I will honour.\" A standing promise to a priestly house is revoked, and God says plainly that he is revoking it.",
    '2:31': "\"There shall not be an old man in thine house.\" The sentence falls on the generations, not only on the guilty men.",
    '2:33': "The survivors are left to grieve. Judgement here includes being spared to watch.",
    '2:34': "Two deaths in one day are given as the sign. The proof of the prophecy will arrive too late to act on.",
    '2:35': "\"A faithful priest, that shall do according to that which is in mine heart.\" God's answer to a corrupt office is not to abolish it.",
    '2:36': "The heirs of the fat portions will beg for a morsel of bread. The punishment is shaped exactly like the sin.",

    # ---- Chapter 3 ----
    '3:1': "\"The word of the LORD was precious in those days\" — rare, not treasured. Scarcity is the point.",
    '3:2': "Eli's eyes wax dim. The physical detail keeps pace with what has happened to his discernment.",
    '3:3': "\"Ere the lamp of God went out.\" It had not gone out yet. God speaks at the last hour of the old order.",
    '3:4': "\"Here am I\" — the right answer, given to the wrong person, by a boy who does not yet know who is calling.",
    '3:5': "He runs to the man he can see. Learning to hear God begins with mistaking him for someone nearer.",
    '3:6': "The second call gets the same mistake. Repetition is how the boy is taught, and how the old priest is woken.",
    '3:7': "Samuel ministered faithfully in the temple and did not yet know the LORD. Service can run ahead of knowledge.",
    '3:8': "Eli perceives it on the third try. The man being judged is the one who teaches the boy to receive the judgement.",
    '3:9': "\"Speak, LORD; for thy servant heareth.\" Eli hands Samuel the words that will be used against Eli's own house.",
    '3:10': "The LORD came, and stood, and called. God repeats himself until the hearing is not in doubt.",
    '3:11': "\"Both the ears of every one that heareth it shall tingle.\" The first word to the new prophet is a word of judgement.",
    '3:12': "\"When I begin, I will also make an end.\" Delay has not meant reprieve.",
    '3:13': "\"His sons made themselves vile, and he restrained them not.\" The charge against Eli is the restraint he withheld.",
    '3:14': "The iniquity shall not be purged with sacrifice nor offering. The men who trafficked in sacrifice are told it cannot help them.",
    '3:15': "He opens the doors of the house as usual, and dreads the conversation. The duties continue while the news waits.",
    '3:16': "\"Samuel, my son.\" Eli asks with affection for the word that will destroy him.",
    '3:17': "He puts the boy under oath to withhold nothing. Eli insists on hearing it whole.",
    '3:18': "\"It is the LORD: let him do what seemeth him good.\" Submission at the end from a man who would not act at the beginning.",
    '3:19': "\"Did let none of his words fall to the ground.\" A prophet is authenticated by God's keeping of his words, not by his own force.",
    '3:20': "From Dan to Beersheba, all Israel knew. The recognition comes from the whole land, not from an institution.",
    '3:21': "The LORD revealed himself by the word. Vision returns to Shiloh in the form of speech.",

    # ---- Chapter 4 ----
    '4:2': "Four thousand dead, and the elders ask the right question in the next verse and reach the wrong answer.",
    '4:3': "\"Wherefore hath the LORD smitten us?\" They ask why God struck them, then propose to fetch the ark instead of repenting.",
    '4:4': "Hophni and Phinehas come with the ark. The two men under sentence of death carry the holy thing to the front.",
    '4:5': "A shout that made the earth ring. Confidence and covenant faithfulness are not the same thing.",
    '4:6': "The Philistines identify the shout correctly. The enemy understands what is in the camp better than Israel does.",
    '4:7': "\"God is come into the camp.\" The pagans take the ark more seriously than the men who sent for it.",
    '4:8': "They remember the plagues of Egypt. Israel's history is better known to its enemies than used by Israel.",
    '4:9': "\"Quit yourselves like men.\" Fear drives the Philistines to fight harder; it drove Israel to fetch a box.",
    '4:10': "Thirty thousand fall — seven times the loss of the battle fought without the ark.",
    '4:11': "The ark was taken. God allows his own throne to be captured rather than be used as a charm.",
    '4:12': "Rent clothes and earth on the head. The news arrives already interpreted.",
    '4:13': "Eli's heart trembled for the ark of God — not for his sons, and not for the army.",
    '4:15': "Ninety-eight, and blind. The judge of Israel receives the end of his house as a report he cannot see for himself.",
    '4:17': "Four disasters in one sentence, ordered from least to worst: rout, slaughter, his sons, the ark.",
    '4:18': "He falls at the mention of the ark. The one loss he could not survive was not the loss of his children.",
    '4:19': "Labour comes on at the news. The collapse of a nation arrives in one woman's body.",
    '4:20': "\"She answered not, neither did she regard it.\" A son is no comfort when the glory has gone.",
    '4:21': "Ichabod — a child named for a national loss, carrying the verdict of that day in his name for life.",
    '4:22': "She says it twice. The repetition is the point: the ark, not the family, is what she is mourning.",
}
