#!/usr/bin/env python3
"""Written takeaways for 1 Samuel."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:2': "Two wives, one fruitful and one empty. The book opens on a household that already cannot hold together.",
    '1:3': "Hophni and Phinehas are named as priests of the LORD before we learn what they are. The office is real; the men are not.",
    '1:5': "\"He loved Hannah: but the LORD had shut up her womb.\" Being loved and being barren are stated in one breath.",
    '1:6': "The text says plainly that God closed the womb and that a rival used it as a weapon. Both are true at once.",
    '1:7': "Year by year, at the house of the LORD. The place of worship is where the provocation was worst.",
    '1:8': "\"Am not I better to thee than ten sons?\" A husband answers grief by asking to be enough for it.",
    '1:9': "Eli sits by the post of the temple. The priest is in position, and sees nothing until it is pointed out to him.",
    '1:10': "\"In bitterness of soul.\" Prayer here is not composure offered to God but the lack of it.",
    '1:11': "She asks for a son and gives him away in the same sentence. The vow undoes the point of the request.",
    '1:13': "She spake in her heart, and the priest read drunkenness. Silent prayer was strange enough to be mistaken for vice.",
    '1:14': "Eli's first word to the godliest woman in Shiloh is a rebuke for a sin she has not committed.",
    '1:15': "\"I have poured out my soul before the LORD.\" She corrects him without denying him the title \"my lord.\"",
    '1:16': "\"Out of the abundance of my complaint and grief have I spoken.\" Complaint is offered to God as worship, not against it.",
    '1:17': "Eli gives a blessing without knowing the petition. He does not withdraw his mistake; he simply blesses.",
    '1:18': "Her countenance was no more sad, and nothing had yet changed but the fact that the matter was out of her hands.",
    '1:19': "\"The LORD remembered her.\" To be remembered in Scripture is not to be recalled but to be acted for.",
    '1:20': "Samuel — asked of God. The name makes the child a standing reminder of where he came from.",
    '1:22': "She will not go up until the child is weaned, because after that visit she will not bring him home again.",
    '1:23': "\"Only the LORD establish his word.\" Elkanah defers to the vow his wife made without him.",
    '1:24': "Three bullocks and an ephah of flour for a toddler's handover. She pays the cost of the vow in full.",
    '1:26': "\"I am the woman that stood by thee here, praying.\" She reminds the priest of the day he got her wrong.",
    '1:27': "\"For this child I prayed.\" The answered prayer is what makes the surrender possible and what makes it hurt.",
    '1:28': "Lent to the LORD as long as he liveth — a loan with no return date. Giving back what was given is the whole transaction.",

    # ---- Chapter 2 ----
    '2:1': "\"Mine horn is exalted in the LORD.\" Her joy is placed in the giver, not in the son she has just handed over.",
    '2:2': "\"Neither is there any rock like our God.\" The song's foundation is God's uniqueness, not Hannah's vindication.",
    '2:3': "\"By him actions are weighed.\" Not counted or watched — weighed, which is a judgement, not a record.",
    '2:4': "Bows broken and stumblers girded. The reversal runs both directions, and neither party arranged it.",
    '2:5': "\"The barren hath born seven.\" Hannah has one son so far and sings as though the whole pattern were settled.",
    '2:6': "\"The LORD killeth, and maketh alive.\" The song refuses to hand the dark half of providence to anyone else.",
    '2:7': "Poverty and wealth are both listed as God's work. The song will not let prosperity stand as proof of favour.",
    '2:8': "The beggar is lifted from the dunghill to inherit the throne of glory. Mary will sing this same line in Luke.",
    '2:9': "\"By strength shall no man prevail.\" The one sentence that rules out every way Israel will try to save itself in this book.",
    '2:10': "A woman with no king sings of the LORD's anointed. The book's whole argument is already in her last line.",
    '2:11': "The child stays and the parents go home. The ministry of Samuel begins as an act of leaving him behind.",
    '2:12': "\"Sons of Belial; they knew not the LORD\" — said of men who handled the sacrifices daily.",
    '2:13': "\"The priests' custom\" — the abuse had settled into procedure, which is how it went unchallenged.",
    '2:14': "Whatever the fleshhook brought up, the priest took. Chance dressed up as entitlement.",
    '2:15': "They demand the meat before the fat is burnt, taking their share ahead of God's.",
    '2:16': "\"I will take it by force.\" When the worshipper objects on God's behalf, the priest threatens him.",
    '2:17': "\"Men abhorred the offering of the LORD.\" The clergy's greed drove people away from the sacrifice itself.",
    '2:18': "A child in a linen ephod, ministering beside men who are ruining the priesthood. Both pictures stand in one house.",
    '2:19': "A little coat, made larger each year. Hannah keeps mothering the son she gave away, in the only way left to her.",
    '2:20': "Eli asks God to repay the loan with more children — and the blessing that costs him nothing is granted.",
    '2:21': "Five more children for Hannah. What was surrendered is not returned but multiplied elsewhere.",
    '2:22': "Eli hears everything, including the women at the tabernacle door. Knowing is exactly what will condemn him.",
    '2:23': "\"Why do ye such things?\" He asks a question where he holds the authority to act.",
    '2:24': "\"Nay, my sons.\" A reprimand so mild it sounds like a request, aimed at men profaning the sanctuary.",
    '2:25': "\"If a man sin against the LORD, who shall intreat for him?\" Eli states the problem exactly and does nothing about it.",
    '2:26': "Samuel grew in favour with the LORD and with men — the sentence Luke will borrow for the boy Jesus.",
    '2:27': "The rebuke begins with what God gave: appearing in Egypt, choosing this house. Grace is recited before the charge.",
    '2:28': "The priesthood and its provisions were a gift. That is what makes the abuse of them theft rather than error.",
    '2:29': "\"Thou honourest thy sons above me.\" The father's fault is not the sons' sin but his preference of them.",
    '2:30': "\"Them that honour me I will honour.\" A standing promise to a priestly house is revoked, and God says plainly that he is revoking it.",
    '2:31': "\"There shall not be an old man in thine house.\" The sentence falls on the generations, not only on the guilty men.",
    '2:33': "The survivors are left to grieve. Judgement here includes being spared to watch.",
    '2:34': "Two deaths in one day are given as the sign. The proof of the prophecy will arrive too late to act on.",
    '2:35': "\"A faithful priest, that shall do according to that which is in mine heart.\" God's answer to a corrupt office is not to abolish it.",
    '2:36': "The heirs of the fat portions will beg for a morsel of bread. The punishment is shaped exactly like the sin.",

    # ---- Chapter 3 ----
    '3:1': "\"The word of the LORD was precious in those days\" — rare, not treasured. Scarcity is the point.",
    '3:2': "Eli's eyes wax dim. The physical detail keeps pace with what has happened to his discernment.",
    '3:3': "\"Ere the lamp of God went out.\" It had not gone out yet. God speaks at the last hour of the old order.",
    '3:4': "\"Here am I\" — the right answer, given to the wrong person, by a boy who does not yet know who is calling.",
    '3:5': "He runs to the man he can see. Learning to hear God begins with mistaking him for someone nearer.",
    '3:6': "The second call gets the same mistake. Repetition is how the boy is taught, and how the old priest is woken.",
    '3:7': "Samuel ministered faithfully in the temple and did not yet know the LORD. Service can run ahead of knowledge.",
    '3:8': "Eli perceives it on the third try. The man being judged is the one who teaches the boy to receive the judgement.",
    '3:9': "\"Speak, LORD; for thy servant heareth.\" Eli hands Samuel the words that will be used against Eli's own house.",
    '3:10': "The LORD came, and stood, and called. God repeats himself until the hearing is not in doubt.",
    '3:11': "\"Both the ears of every one that heareth it shall tingle.\" The first word to the new prophet is a word of judgement.",
    '3:12': "\"When I begin, I will also make an end.\" Delay has not meant reprieve.",
    '3:13': "\"His sons made themselves vile, and he restrained them not.\" The charge against Eli is the restraint he withheld.",
    '3:14': "The iniquity shall not be purged with sacrifice nor offering. The men who trafficked in sacrifice are told it cannot help them.",
    '3:15': "He opens the doors of the house as usual, and dreads the conversation. The duties continue while the news waits.",
    '3:16': "\"Samuel, my son.\" Eli asks with affection for the word that will destroy him.",
    '3:17': "He puts the boy under oath to withhold nothing. Eli insists on hearing it whole.",
    '3:18': "\"It is the LORD: let him do what seemeth him good.\" Submission at the end from a man who would not act at the beginning.",
    '3:19': "\"Did let none of his words fall to the ground.\" A prophet is authenticated by God's keeping of his words, not by his own force.",
    '3:20': "From Dan to Beersheba, all Israel knew. The recognition comes from the whole land, not from an institution.",
    '3:21': "The LORD revealed himself by the word. Vision returns to Shiloh in the form of speech.",

    # ---- Chapter 4 ----
    '4:2': "Four thousand dead, and the elders ask the right question in the next verse and reach the wrong answer.",
    '4:3': "\"Wherefore hath the LORD smitten us?\" They ask why God struck them, then propose to fetch the ark instead of repenting.",
    '4:4': "Hophni and Phinehas come with the ark. The two men under sentence of death carry the holy thing to the front.",
    '4:5': "A shout that made the earth ring. Confidence and covenant faithfulness are not the same thing.",
    '4:6': "The Philistines identify the shout correctly. The enemy understands what is in the camp better than Israel does.",
    '4:7': "\"God is come into the camp.\" The pagans take the ark more seriously than the men who sent for it.",
    '4:8': "They remember the plagues of Egypt. Israel's history is better known to its enemies than used by Israel.",
    '4:9': "\"Quit yourselves like men.\" Fear drives the Philistines to fight harder; it drove Israel to fetch a box.",
    '4:10': "Thirty thousand fall — seven times the loss of the battle fought without the ark.",
    '4:11': "The ark was taken. God allows his own throne to be captured rather than be used as a charm.",
    '4:12': "Rent clothes and earth on the head. The news arrives already interpreted.",
    '4:13': "Eli's heart trembled for the ark of God — not for his sons, and not for the army.",
    '4:15': "Ninety-eight, and blind. The judge of Israel receives the end of his house as a report he cannot see for himself.",
    '4:17': "Four disasters in one sentence, ordered from least to worst: rout, slaughter, his sons, the ark.",
    '4:18': "He falls at the mention of the ark. The one loss he could not survive was not the loss of his children.",
    '4:19': "Labour comes on at the news. The collapse of a nation arrives in one woman's body.",
    '4:20': "\"She answered not, neither did she regard it.\" A son is no comfort when the glory has gone.",
    '4:21': "Ichabod — a child named for a national loss, carrying the verdict of that day in his name for life.",
    '4:22': "She says it twice. The repetition is the point: the ark, not the family, is what she is mourning.",
}

TAKEAWAYS.update({
    # ---- Chapter 5 ----
    '5:2': "The ark is set beside Dagon as a trophy. A captured god is supposed to join the winner's house.",
    '5:3': "Dagon is found face down before the ark, and they stand him up again. Devotion propping up its own object.",
    '5:4': "Head and hands broken off on the threshold. The second morning leaves nothing that can be set upright.",
    '5:5': "A custom about not treading on a threshold outlasts the god it commemorates. The shame became ritual.",
    '5:6': "\"The hand of the LORD was heavy upon them.\" The ark defends itself in exile without an army behind it.",
    '5:7': "\"His hand is sore upon us, and upon Dagon our god.\" They diagnose it correctly and still only move the problem.",
    '5:8': "The lords meet and decide to send the trouble to Gath. Policy by passing it to the next town.",
    '5:9': "Gath gets what Ashdod got. Relocating the holy thing does not change what it does.",
    '5:10': "Ekron cries out before the ark arrives. By now its reputation travels ahead of it.",
    '5:11': "\"Let it go again to his own place.\" The Philistines return the ark because they want relief, not because they repent.",
    '5:12': "\"The cry of the city went up to heaven.\" Pagan Ekron sends up the same cry Israel sent up in Egypt.",

    # ---- Chapter 6 ----
    '6:1': "Seven months. God is in no hurry to leave the country that captured him.",
    '6:2': "The Philistines consult their own priests about Israel's God, and get better advice than Israel's elders gave.",
    '6:3': "\"Send it not empty.\" Pagan diviners know that approaching this God requires a trespass offering.",
    '6:4': "Five golden tumours and five golden mice — an offering shaped like the punishment, admitting exactly what was suffered.",
    '6:5': "\"Give glory unto the God of Israel.\" The instruction is right; the \"peradventure\" shows they are guessing.",
    '6:6': "\"As the Egyptians and Pharaoh hardened their hearts.\" The Philistines preach Exodus to themselves.",
    '6:7': "New cart, unbroken cows, calves shut up at home — a test designed so that only God could make it come out right.",
    '6:9': "\"It was a chance that happened to us.\" They build in an escape clause, ready to call it coincidence.",
    '6:12': "The cows walk straight to Bethshemesh, lowing for their calves the whole way. Instinct overruled in plain view.",
    '6:13': "Men reaping wheat look up and see the ark coming home. The return arrives in the middle of ordinary work.",
    '6:14': "The cart becomes firewood and the cows become the offering. Everything the Philistines sent is consumed at once.",
    '6:15': "The Levites take it down. Even in a moment of joy the text notes who was allowed to handle it.",
    '6:16': "The five lords watch and go home the same day. They saw the whole thing and drew no conclusion from it.",
    '6:19': "Israelites die for looking into the ark that Philistines carried unharmed. Familiarity is the greater danger.",
    '6:20': "\"Who is able to stand before this holy LORD God?\" The question is right, and they ask it to get rid of him.",
    '6:21': "They send the ark on to the next town, exactly as the Philistines did. Israel's solution is the Philistines' solution.",

    # ---- Chapter 7 ----
    '7:1': "Kirjathjearim receives what Bethshemesh sent away, and sanctifies a man to keep it. Someone finally takes responsibility.",
    '7:2': "Twenty years, and all Israel lamented after the LORD. The longing runs ahead of the repentance by two decades.",
    '7:3': "\"If ye do return... then put away the strange gods.\" Returning is not a feeling; it is a removal.",
    '7:4': "They put away Baalim and Ashtaroth. The reform is dated by what was thrown out, not by what was felt.",
    '7:6': "Water poured out, fasting, and \"We have sinned against the LORD.\" Confession precedes deliverance and does not cause it.",
    '7:7': "The Philistines attack precisely when Israel gathers to repent. Turning to God is not a guarantee of quiet.",
    '7:8': "\"Cease not to cry unto the LORD our God for us.\" They ask for intercession, not for a commander.",
    '7:9': "A sucking lamb offered wholly, and the LORD heard him. The victory begins at an altar, not a muster.",
    '7:10': "God thunders while the sacrifice is still burning. Israel wins a battle it has not yet joined.",
    '7:12': "\"Hitherto hath the LORD helped us.\" Ebenezer names what is past and says nothing about what is promised.",
    '7:13': "The Philistines are subdued under a judge who kept no standing army. The book records this before Israel asks for a king.",
    '7:14': "Land is restored and there is peace with the Amorites — under exactly the arrangement Israel is about to reject.",
    '7:15': "Samuel judged Israel all the days of his life. The office he held was never taken from him, only outvoted.",
    '7:16': "A circuit of three towns, year by year. Government here is a man walking to where the people are.",
    '7:17': "He built an altar at home. The judge's house and the place of sacrifice are the same address.",

    # ---- Chapter 8 ----
    '8:1': "Samuel makes his sons judges. The man who grew up under Eli's failed sons appoints his own.",
    '8:3': "Lucre, bribes, perverted judgment. The complaint against them is that justice was for sale.",
    '8:5': "\"Make us a king to judge us like all the nations.\" The real grievance is true; the remedy asked for is the problem.",
    '8:6': "\"The thing displeased Samuel.\" His first move is not to argue with them but to pray.",
    '8:7': "\"They have not rejected thee, but they have rejected me.\" God consoles Samuel by naming a much larger injury.",
    '8:8': "This is treated as one more instalment of everything since Egypt, not as a new departure.",
    '8:9': "God grants the request and orders a warning. Being given what you asked for can itself be the judgement.",
    '8:11': "\"This will be the manner of the king.\" Not what he may do but what he will do — the warning is a forecast.",
    '8:12': "Sons conscripted to plough the king's ground and forge his weapons. The labour is taken first.",
    '8:13': "Daughters taken as cooks and bakers. The household is emptied into the palace.",
    '8:14': "\"The best of them\" — fields and vineyards taken and handed to courtiers. Loyalty is paid for out of other men's land.",
    '8:15': "A tenth of the harvest to his officers. The king will take the share that belonged to God.",
    '8:17': "\"Ye shall be his servants.\" Six times he says take, and this is where taking ends.",
    '8:18': "\"The LORD will not hear you in that day.\" They will cry out about a king they chose, and the choice will stand.",
    '8:19': "\"Nevertheless the people refused.\" They hear the whole list of costs and want the king anyway.",
    '8:20': "\"That we also may be like all the nations.\" Israel asks to stop being the exception it was made to be.",
    '8:21': "Samuel rehearses their words in God's ears rather than answering them himself.",
    '8:22': "\"Hearken unto their voice, and make them a king.\" God gives them the thing he has just called a rejection of himself.",
})
