#!/usr/bin/env python3
"""Written takeaways for Song of Solomon."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "\"The song of songs\" is a Hebrew superlative, like king of kings. The book claims to be the best of them.",
    '1:2': "The first voice in the book is hers, and her first want is his mouth. Nothing about it is prefaced or excused.",
    '1:3': "A name is not something you can smell, and she says his carries like poured oil. Reputation and body are not split here.",
    '1:4': "\"Draw me, we will run after thee.\" She wants to be taken, and the wanting is sung in the plural of a wedding crowd.",
    '1:5': "She names how she looks and refuses to let it count as a defect: dark as Kedar's tents, comely as Solomon's curtains.",
    '1:6': "Her colour came from field work her brothers forced on her. The vineyard she has not kept is herself.",
    '1:7': "She asks where to find him rather than waiting to be found, and her reason is that she will not wander among strangers.",
    '1:8': "The answer sends her along the tracks of the flock. Love here is found by ordinary means, not by a sign.",
    '1:9': "Comparing her to a mare among Pharaoh's chariots is not an insult. It is a remark about who stops and stares.",
    '1:10': "He praises what is already there before he offers her anything to add to it.",
    '1:12': "Her perfume reaches him across the table. She notices the effect she is having on him, and says so.",
    '1:13': "She says plainly where she wants him to lie all night. The book means this before it means anything else.",
    '1:14': "Engedi is a green place in the middle of a desert, and that is what she is calling him.",
    '1:15': "He says she is fair twice before adding anything else. Repetition is how this poetry insists.",
    '1:16': "She answers his praise with praise, and then names the bed, which turns out to be grass.",
    '1:17': "The house they are describing has no walls. The forest is the room, and neither of them mentions a roof.",

    # ---- Chapter 2 ----
    '2:1': "She calls herself a common flower of the plain, and he spends the next verse disagreeing with her.",
    '2:2': "He keeps her modest word for herself and changes only what is standing around her.",
    '2:3': "She answers in kind, then sits down in his shade and tastes his fruit. The appetite in the line is hers.",
    '2:4': "A banner is what an army is known by. She says what flies over her is not his rank but his love.",
    '2:5': "Lovesickness is treated as a real ailment needing raisins and apples, and nobody in the poem smiles at her for it.",
    '2:6': "The embrace is described from inside it, in the present tense, with no one else in the room.",
    '2:7': "Love has an hour of its own and cannot be hurried into it. The charge is not to force what has to be waited for.",
    '2:8': "She hears him before she sees him, and the whole landscape turns into something he is crossing to reach her.",
    '2:9': "He is at the window and not yet through the door. The poem is honest about how much of love is waiting.",
    '2:10': "His first recorded words to her are an invitation to leave with him, and he will say them again before he stops.",
    '2:11': "The argument for going is the weather. Nothing grander is offered, and nothing grander is needed.",
    '2:12': "Spring is counted off item by item, as though love had made a man notice the year for the first time.",
    '2:13': "Green figs and a vine in flower are his evidence, and then he repeats the invitation word for word.",
    '2:14': "He asks for her face and her voice, in that order, and calls both sweet. Hiding is what he is coaxing her out of.",
    '2:15': "The little foxes are the small things that ruin a vineyard in flower. What threatens love is rarely large.",
    '2:16': "The order is hers first — what she has before what has her. She will say it the other way round in chapter six.",
    '2:17': "She sends him off at daybreak and tells him how to run. The parting runs on a clock neither of them set.",

    # ---- Chapter 3 ----
    '3:1': "Wanting someone who is not there is given a whole scene, and the first thing reported is that she did not find him.",
    '3:2': "She goes out into the streets at night to look for him, and the refrain repeats: she sought him and found him not.",
    '3:3': "The watchmen find her before she finds him, and she does not wait for them to ask her business.",
    '3:4': "She takes hold and will not let go, and where she brings him is her mother's house — home, not away.",
    '3:5': "The same charge returns after the search. Even with him found, love is still not to be shaken awake.",
    '3:6': "The question comes from onlookers. A wedding procession is a public thing, and the crowd is part of the poem.",
    '3:7': "Sixty armed men around the litter. The guard is part of the splendour being described, and part of the unease.",
    '3:8': "\"Because of fear in the night\" is admitted in the middle of the pageantry. Even a royal wedding is guarded.",
    '3:10': "Silver, gold and purple are listed, and then \"paved with love\" — the one material that is not a material.",
    '3:11': "The crown named is not the royal one but the wedding crown his mother set on him, on the day of his gladness.",

    # ---- Chapter 4 ----
    '4:1': "He begins at her eyes and works downward, and the comparisons are pastoral because that is the world he sees her in.",
    '4:2': "Teeth like washed sheep, none of them missing. The praise is particular enough to be about her and not about beauty.",
    '4:3': "He praises her speech in the middle of praising her mouth, which keeps the compliment from being only about a face.",
    '4:4': "A tower hung with shields makes her bearing sound like something defended rather than something easily taken.",
    '4:5': "The praise reaches her body without hesitation and without euphemism, and the poem is not embarrassed by it.",
    '4:6': "He answers her daybreak line with one of his own, and the mountain he means to spend the night on is her.",
    '4:7': "\"No spot in thee\" is how love actually sees, and it is the sentence Paul reaches for about Christ and the church.",
    '4:8': "He calls her down from the lions' dens and the leopards' mountains — that is, from anywhere she is not safe.",
    '4:9': "\"My sister, my spouse.\" The language of kin is used for a wife, because marriage turns a stranger into family.",
    '4:10': "He hands her back her own comparison from the first chapter, word for word. Lovers quote each other.",
    '4:11': "Honey and milk under the tongue is how the promised land was described. He is telling her she is home.",
    '4:12': "Enclosed, shut, sealed. He praises her for not being available to everyone, and she is about to open the gate.",
    '4:13': "The garden is stocked with what grows slowly and costs a great deal. Nothing in this orchard is cheap or quick.",
    '4:15': "The sealed fountain becomes living water and streams off Lebanon — still hers, and now running.",
    '4:16': "She answers the enclosed garden by opening it and calling it his. The consent in this book is always hers to give.",

    # ---- Chapter 5 ----
    '5:1': "He says he has come in, and a third voice tells the friends to drink deep. This marriage is blessed, not hidden.",
    '5:2': "Half asleep, she hears him knocking with the night still in his hair. Love does not only arrive when convenient.",
    '5:3': "Her excuses are small and domestic, which is exactly how a door comes to be answered a moment too late.",
    '5:4': "His hand at the latch undoes her, and the response is reported in the body before any decision is made.",
    '5:5': "She reaches the door and finds myrrh on the handle: he was there, and she can measure the moment she missed.",
    '5:6': "She opens, and he is gone. The second search of the book begins with a door opened one moment too late.",
    '5:7': "The watchmen who once only questioned her now beat her and take her veil. Wanting him has turned dangerous.",
    '5:8': "Bruised and unveiled, the message she sends him is not a complaint but that she is sick with love for him.",
    '5:9': "The daughters ask the fair question — what makes him different from anyone else — and her answer runs seven verses.",
    '5:10': "She answers by describing him, which is the only argument love has ever been able to make.",
    '5:11': "She praises a man's body in the same frank detail he used for hers, and Scripture keeps her words on the page.",
    '5:12': "She gives him back the doves he gave her. The two voices in this book keep answering each other in kind.",
    '5:14': "Gold, beryl, ivory, sapphire. She describes him as something crafted, the way a statue is looked at.",
    '5:16': "After all the gold and the marble, the word she ends on is friend.",

    # ---- Chapter 6 ----
    '6:1': "Her praise works. The daughters who asked what he was are now offering to go and look with her.",
    '6:2': "She knew where he was. The answer suggests the losing was never as complete as the panic had made it feel.",
    '6:3': "The same words as chapter two with the order turned round: belonging to him now comes first.",
    '6:4': "He compares her to two cities and then to an army. Being overwhelmed is not the same thing as being charmed.",
    '6:5': "He asks her to look away because he cannot bear being looked at. That is the confession under all the praise.",
    '6:6': "He repeats lines he used in chapter four. Lovers say the same things twice, and the poem lets him.",
    '6:8': "The harem is counted up only in order to be set aside, and the counting does not flatter the man who assembled it.",
    '6:9': "Against all those numbers he says one, and the word he chooses for her is the one her mother would use.",
    '6:10': "Morning, moon, sun and army. The question others ask about her is answered with the largest things in the sky.",
    '6:11': "He goes down to see whether anything is in flower yet, which is what waiting for love looks like from outside.",
    '6:12': "The hardest line in the book to construe. What survives the translation is that desire moved faster than she did.",
    '6:13': "She is named for the first time here, and at once she asks why they are all standing about looking at her.",

    # ---- Chapter 7 ----
    '7:1': "This praise starts at her feet and climbs, the reverse of chapter four. Nothing about her is left unlooked at.",
    '7:2': "Wheat and wine are the harvest of the land, and he is using them to say that her body means plenty.",
    '7:4': "Fishpools and a watchtower sound odd as compliments until you notice he is praising depth and steadiness.",
    '7:5': "\"The king is held.\" A man with every power available to him describes himself as the one who has been caught.",
    '7:6': "The catalogue stops and turns into a single exclamation. Description gives out before delight does.",
    '7:7': "A palm is tall and hard to climb. He knows what he is saying about how far above him she stands.",
    '7:8': "He says out loud what he intends, and the poem records the intention instead of hiding it in metaphor.",
    '7:9': "He begins the sentence and she finishes it, turning his wine toward her beloved. She takes the line out of his mouth.",
    '7:10': "The third time she says this, ownership drops away and desire takes its place — and the word spoken over Eve is undone.",
    '7:11': "Now she is the one asking him to come away, in the words he used on her when the spring came.",
    '7:12': "She names the place and the hour herself. Nothing in this book happens to her without her having said so.",
    '7:13': "New fruits and old, laid up on purpose. Desire here has been prepared for, not merely fallen into.",

    # ---- Chapter 8 ----
    '8:1': "What she wants is to kiss him in the street unashamed — not less love, but love the town would leave alone.",
    '8:2': "Her mother's house comes up again. She keeps wanting to bring him back to the place she came from.",
    '8:3': "The embrace of chapter two returns, now in the mood of something wished for rather than something had.",
    '8:4': "The third charge, and the shortest. She has stopped explaining why love must not be woken before its time.",
    '8:5': "She comes up out of the wilderness leaning on him, and the apple tree sets them where love started.",
    '8:6': "Love is set against death and jealousy against the grave, the two things nobody escapes. The seal is asked for, not assumed.",
    '8:7': "Love cannot be drowned and cannot be bought, and the man who offers his whole house for it is laughed out of the room.",
    '8:8': "Her brothers speak, planning her future before she has one. The voice that drove her into the vineyards is back.",
    '8:9': "They will reward what they can defend and board up what they cannot. The brothers are deciding what she is.",
    '8:10': "She answers them herself: \"I am a wall.\" She had already decided, and the eyes she cared about were not theirs.",
    '8:11': "Solomon's vineyard is leased out and priced by the thousand. Everything in it is somebody's investment.",
    '8:12': "\"My vineyard, which is mine.\" The girl who could not keep her own vineyard has it now, and is not letting it out.",
    '8:13': "At the end what he asks for is her voice, the same thing he asked for at the lattice when the spring came.",
    '8:14': "The book ends with her calling him and not yet with him. Love that is answered is still love that waits.",
}
