#!/usr/bin/env python3
"""Written one-line takeaways for Zephaniah 1-3."""

TAKEAWAYS = {
    # ---- Chapter 1 ----
    '1:1': "Four generations, and a king: Josiah. The great reform was underway, and this is what the prophet saw anyway.",
    '1:3': "Man, beast, fowl, fish. Creation is taken apart in the order Genesis put it together.",
    '1:4': "The hand narrows from the whole land to Jerusalem, and what it reaches first is the priesthood.",
    '1:5': "The charge is not apostasy but mixture: they swear by the LORD and by Malcham in the same breath.",
    '1:6': "Two ways of being lost are named — turning back from God, and never having enquired after him at all.",
    '1:7': "The LORD prepares a sacrifice and bids his guests. Judah is not at the table; Judah is on it.",
    '1:8': "Princes, the king's sons, and men in foreign clothes. The day begins at the top and notices what people wear.",
    '1:9': "Leaping the threshold is a borrowed pagan habit, and the houses it serves are filled with violence.",
    '1:10': "Fish gate, second quarter, the hills. The noise of that day is mapped across a real city, street by street.",
    '1:11': "Maktesh is the market quarter. The ones cut off are named as the ones who handle the silver.",
    '1:12': "Searched out with candles: men settled on their lees, certain God will do neither good nor evil.",
    '1:13': "Build and not inhabit, plant and not drink. Deuteronomy's curse is quoted back to the comfortable.",
    '1:14': "\"It is near, and hasteth greatly.\" The one named as crying bitterly is the mighty man, who had most to lose.",
    '1:15': "The verse the Dies Irae is named from. Six pairs of words for one day, and not one of them is mercy.",
    '1:17': "Walking like blind men, blood poured out as dust. Both pictures are of something reckoned worthless.",
    '1:18': "Silver and gold buy no exemption, which is the first thing the wealthy would have tried.",
    # ---- Chapter 2 ----
    '2:1': "\"O nation not desired.\" The summons to gather is addressed to a people God says nobody wants.",
    '2:3': "\"It may be ye shall be hid.\" Shelter is held out as a possibility and never as a lever to pull.",
    '2:4': "Ashdod driven out at noon day. The work is done in daylight, without any need for the cover of dark.",
    '2:5': "The sea coast is addressed by the old name, Canaan. The sentence is that there be no inhabitant left.",
    '2:7': "The coast turns into pasture for Judah's remnant, who lie down in the evening in Ashkelon's houses.",
    '2:8': "What God says he has heard is talk. Neighbours' reproach against his people is treated as actionable.",
    '2:9': "Sodom and Gomorrah, nettles and saltpits. The comparison chosen is a place no one has lived in since.",
    '2:11': "He will famish the gods — starve them of offerings. Then men worship him each from his own place.",
    '2:12': "One line for Ethiopia, and it is a sword. The brevity does the work that a paragraph would have done.",
    '2:13': "Nineveh dry like a wilderness. A city built on a river is sentenced to thirst.",
    '2:14': "Cormorant and bittern in the window frames, cedar work laid open. Birds keep house where the empire sat.",
    '2:15': "\"I am, and there is none beside me\" — a city talking about itself the way God talks about himself.",
    # ---- Chapter 3 ----
    '3:1': "The oppressing city in this woe is Jerusalem, not Nineveh, and the switch is nowhere announced.",
    '3:2': "Four refusals in one line: not obeyed, not corrected, not trusting, not drawing near. None of them dramatic.",
    '3:3': "Princes as lions, judges as wolves that leave nothing till morning. Appetite is what makes them unfit.",
    '3:4': "Prophets light, priests doing violence to the law. Both offices meant to restrain the city are indicted.",
    '3:5': "Judgement brought to light every morning, as regular as sunrise, and still nobody in the city is ashamed.",
    '3:7': "\"Surely thou wilt fear me\" — God states the expectation plainly, and they rose early to spoil it.",
    '3:8': "Wait. It is the one instruction given while the fire is being described, and waiting is what faith does here.",
    '3:9': "A pure language handed back. Babel is undone so that the nations can call on one name with one consent.",
    '3:10': "Offerings come from beyond the rivers of Ethiopia, carried by the scattered. The dispersion becomes a road.",
    '3:11': "Shame is removed by removing the proud, not by talking down what was actually done.",
    '3:12': "What is left is afflicted and poor, and that is the remnant. Trust is what the weak have left to do.",
    '3:13': "The remnant's mark is a mouth with no lie in it, and the result is sleep that nothing disturbs.",
    '3:14': "The imperatives turn from howling to singing, and the text offers no transition between them.",
    '3:15': "The judgments are taken away and the King stands in the midst. The city's safety is a person, not a wall.",
    '3:16': "\"Let not thine hands be slack.\" Fear is answered with work to get on with rather than an explanation.",
    '3:17': "He will joy over thee with singing. The book of the day of wrath ends with the judge singing over them.",
    '3:18': "Those who grieved at missing the feasts are the ones gathered in. The reproach they carried is lifted off.",
    '3:19': "\"I will save her that halteth.\" The limping are picked out by name and handed fame where they had shame.",
}
