#!/usr/bin/env python3
"""Ephesians 4-6 commentary written for BibleScroll, from a Lutheran reading.

Continues ephesians_explain.py; see that module's docstring for the approach.
"""

NOTES = {
    # ---- Chapter 4: one body, and the walk that matches the calling ----
    '4:1': "<strong>Beseech you that ye walk worthy of the vocation wherewith ye are called</strong> (ἀξίως περιπατῆσαι τῆς κλήσεως)—The calling comes first and the walking follows. The whole second half of the letter rests on the first half.<br><br>\"Worthy\" does not mean earning the call but matching it, as a garment matches its wearer. Paul spends three chapters on what God has done before asking for anything. The order is itself the doctrine.",

    '4:2': "<strong>With all lowliness and meekness, with longsuffering, forbearing one another in love</strong> (ταπεινοφροσύνης καὶ πραΰτητος)—<em>Tapeinophrosynē</em> was no virtue in Greek ethics; low-mindedness counted as a defect. Christian usage turned the word over.<br><br>Every item is a cost paid toward somebody else, and <em>forbearing</em> assumes there will be something to bear. Paul does not imagine a church without friction, only one that absorbs it.",

    '4:3': "<strong>Endeavouring to keep the unity of the Spirit in the bond of peace</strong> (τηρεῖν τὴν ἑνότητα τοῦ πνεύματος)—The unity is <em>of the Spirit</em>: his work, already accomplished. We are told to keep it, never to create it.<br><br>The distinction matters. A unity we manufacture has to be held together by agreement and collapses when agreement fails. A unity the Spirit made is guarded rather than negotiated.",

    '4:4': "<strong>There is one body, and one Spirit, even as ye are called in one hope of your calling</strong>—Paul argues for unity not by urging effort but by listing facts; seven \"ones\" follow in three verses.<br><br>The logic is simply: be what you are. Division among Christians is not merely unfortunate, it is a contradiction of something already true — like a body debating whether it is one body.",

    '4:5': "<strong>One Lord, one faith, one baptism</strong> (εἷς κύριος, μία πίστις, ἓν βάπτισμα)—Baptism stands alongside the Lord himself and the faith as a ground of unity. Paul treats it not as a private testimony but as a public fact that binds.<br><br>That is worth pausing over. Baptism is named among the things God has done, not the things we have decided — which is why it can still be appealed to when feelings and agreements fail.",

    '4:6': "<strong>One God and Father of all, who is above all, and through all, and in you all</strong>—Three prepositions sketch a God over his people, at work through them, and present within them. Transcendence and nearness are not in competition.<br><br>The climax of the seven \"ones\" is not a doctrine about the church but about God. Unity rests finally on who he is, not on what the congregation manages to sustain.",

    '4:7': "<strong>But unto every one of us is given grace according to the measure of the gift of Christ</strong>—After the sevenfold \"one\" comes \"every one.\" Unity does not mean uniformity; the same Christ distributes differently.<br><br>Note that what is measured out is <em>grace</em>, not merit. Nobody's gift is a wage, so comparing gifts amounts to comparing presents — a strange thing to be either proud or ashamed of.",

    '4:8': "<strong>When he ascended up on high, he led captivity captive, and gave gifts unto men</strong>—Paul quotes Psalm 68, a victory procession: the conqueror returns with captives and distributes spoil.<br><br>But here the spoil is given to the people rather than taken from them. Christ's triumph enriches those he passes through instead of plundering them, which is the reverse of how conquest usually works.",

    '4:9': "<strong>Now that he ascended, what is it but that he also descended first into the lower parts of the earth?</strong>—Paul's argument is that the one who went up is the one who first came down. The ascent means nothing without the descent.<br><br>The order is fixed throughout Scripture and in Christian experience: down before up, cross before crown. Any spirituality offering glory without the lowering has left out the first half.",

    '4:10': "<strong>He that descended is the same also that ascended up far above all heavens, that he might fill all things</strong>—The stated purpose of the ascension is filling, not departing. Christ did not leave in order to be absent.<br><br>So the ascension is not the story of a friend who went away. It is how he came to be available everywhere at once, and why the church can speak of his presence in ordinary places.",

    '4:11': "<strong>And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers</strong>—The list is of people given, not offices invented. Ministers are Christ's gift to the church rather than its employees or its delegates.<br><br>That cuts both ways. A congregation cannot treat preaching as a service it purchases, and a preacher cannot treat the office as property. Both receive it from the same hand.",

    '4:12': "<strong>For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ</strong> (πρὸς τὸν καταρτισμὸν τῶν ἁγίων)—<em>Katartismos</em> is the word for setting a bone or mending a net: fitting something for its proper use.<br><br>The gifted men exist to equip the saints, and the saints do the work. A church where ministry means what the staff does has inverted the sentence.",

    '4:13': "<strong>Till we all come in the unity of the faith... unto the measure of the stature of the fulness of Christ</strong>—The standard of maturity is Christ himself, not the congregation's average nor the person you most admire.<br><br>And it is <em>we all</em>. Paul has no category for a mature Christian who has outgrown the others. The growing up described here happens together or it does not happen.",

    '4:14': "<strong>That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine</strong>—The images are of a small boat in weather. Immaturity here is not innocence but instability, and it makes people easy to exploit.<br><br>Paul names the danger as <em>the sleight of men</em>, deliberate deception. Sound teaching is presented not as an intellectual luxury but as protection for people who would otherwise be prey.",

    '4:15': "<strong>But speaking the truth in love, may grow up into him in all things, which is the head, even Christ</strong> (ἀληθεύοντες ἐν ἀγάπῃ)—The Greek is one verb: truthing in love. A single act, not two competing pressures to balance.<br><br>Truth without love wounds without healing; love without truth flatters without helping. Paul assumes a church where hard things are said, and said by people who evidently want your good.",

    '4:16': "<strong>From whom the whole body fitly joined together... maketh increase of the body unto the edifying of itself in love</strong>—Growth flows from the head but happens through the joints. Each part supplies something, and the body grows only as each one does.<br><br>Which means absence carries a cost that is easy to overlook. Nobody notices a single joint until the body cannot move properly.",

    '4:17': "<strong>That ye henceforth walk not as other Gentiles walk, in the vanity of their mind</strong> (ἐν ματαιότητι τοῦ νοὸς αὐτῶν)—<em>Mataiotēs</em> is emptiness, futility — the word Ecclesiastes lives in.<br><br>Paul locates the problem in the mind before the behaviour. A life goes wrong first at the level of what it believes worth having; conduct follows conviction rather than the reverse.",

    '4:18': "<strong>Having the understanding darkened, being alienated from the life of God through the ignorance that is in them</strong>—The ignorance is traced back to <em>the blindness of their heart</em>. It is a condition of the will, not a shortage of information.<br><br>That is why argument alone rarely converts anyone, and why the remedy Paul prayed for in chapter 1 was enlightened eyes. The darkness is not outside the person.",

    '4:19': "<strong>Who being past feeling have given themselves over unto lasciviousness</strong> (ἀπηλγηκότες)—The word describes a limb that has lost sensation. A conscience can be numbed by repetition until it stops reporting.<br><br>Paul's picture is not of people overwhelmed by sudden temptation but of people who stopped feeling and then <em>gave themselves over</em>. The numbness came first, and it came gradually.",

    '4:20': "<strong>But ye have not so learned Christ</strong> (ὑμεῖς δὲ οὐχ οὕτως ἐμάθετε τὸν Χριστόν)—The object of the verb is unusual: one does not normally learn a person. Paul does not say they learned about Christ, or learned from him.<br><br>Christ himself is the curriculum. Christianity is therefore not first a set of positions to hold but an acquaintance that reorders whoever has it.",

    '4:21': "<strong>If so be that ye have heard him, and have been taught by him, as the truth is in Jesus</strong>—Note \"heard <em>him</em>,\" not heard about him. Paul assumes Christ is the one speaking whenever the gospel is preached.<br><br>And truth is located in a person rather than in a system. Which is why faith can survive questions it cannot answer: it rests on someone, not on the completeness of an argument.",

    '4:22': "<strong>That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts</strong>—The old self is called <em>deceitful</em>. Its desires lie about what they will deliver, and that is how they keep their hold.<br><br>The image is of removing clothing — something worn, not something you are. For a Christian this putting off is a daily return to what baptism has already declared.",

    '4:23': "<strong>And be renewed in the spirit of your mind</strong> (ἀνανεοῦσθαι δὲ τῷ πνεύματι τοῦ νοὸς ὑμῶν)—The verb is present and passive: be being renewed. Continuous, and done to you rather than by you.<br><br>Between putting off and putting on stands this renewing of the mind. Behaviour change that skips it is management of symptoms, and it does not hold.",

    '4:24': "<strong>And that ye put on the new man, which after God is created in righteousness and true holiness</strong> (κτισθέντα)—The new self is <em>created</em>, not improved: God's making, in his likeness, put on rather than worked up.<br><br>That is the difference between renovation and resurrection. Paul is not asking for a better version of the old man. That one comes off and stays off.",

    '4:25': "<strong>Speak every man truth with his neighbour: for we are members one of another</strong>—The reason given for honesty is anatomical. Lying to a fellow Christian is a body deceiving itself, which is not cleverness but disease.<br><br>Paul's ethics keep grounding themselves in what is already true rather than in consequences. Tell the truth — not because it works out better, but because of what you now are.",

    '4:26': "<strong>Be ye angry, and sin not: let not the sun go down upon your wrath</strong> (ὀργίζεσθε καὶ μὴ ἁμαρτάνετε)—Anger itself is not forbidden; there are things a Christian ought to be angry about. What is forbidden is letting it settle in.<br><br>The sundown limit is practical rather than sentimental. Anger kept overnight starts to look like justice to the one keeping it, and by morning it has hardened into a position.",

    '4:27': "<strong>Neither give place to the devil</strong> (μηδὲ δίδοτε τόπον τῷ διαβόλῳ)—<em>Topos</em> is a place, a foothold, room to stand. That this sits immediately after the warning about nursed anger is not accidental.<br><br>Paul's concern is not dramatic evil but the ordinary opening — a grievance kept warm, a conversation avoided. Small doors left unclosed are how large trouble gets in.",

    '4:28': "<strong>Let him that stole steal no more: but rather let him labour... that he may have to give to him that needeth</strong>—The cure for theft is not merely stopping. It runs through honest work all the way to generosity.<br><br>Notice the destination. The former thief works not simply to support himself but <em>to give</em> — the exact reverse of the impulse that made him a thief in the first place.",

    '4:29': "<strong>Let no corrupt communication proceed out of your mouth... that it may minister grace unto the hearers</strong>—<em>Sapros</em>, corrupt, was used of rotten fruit. Speech either feeds people or spoils in their hands.<br><br>The standard set is high: words should <em>give grace</em>. Not merely avoid harm, not merely stay accurate, but leave the hearer better supplied than they were before.",

    '4:30': "<strong>And grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption</strong>—Both halves matter. The Spirit can be <em>grieved</em>, which means he is a person rather than a force, and our conduct touches him.<br><br>And the seal holds <em>unto the day of redemption</em>. Grieving is serious precisely because the relationship is secure — this is the grief of family, not a judge weighing whether to keep you.",

    '4:31': "<strong>Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice</strong> (πικρία)—The list opens with <em>bitterness</em>, the quietest item, and works outward to shouting and slander.<br><br>That order is diagnostic. Nobody begins with clamour. It begins as something small and interior that was never dealt with, and the noisy sins are the late symptoms.",

    '4:32': "<strong>And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you</strong> (χαριζόμενοι)—The verb for forgiving is built on <em>charis</em>, grace: to give freely, to let someone off.<br><br>The standard is not proportion or fairness but the forgiveness you received, which was neither. Christian forgiving always reasons downstream from the cross, never upstream from the offence.",
}

NOTES.update({
    # ---- Chapter 5: light, wisdom, and the household ----
    '5:1': "<strong>Be ye therefore followers of God, as dear children</strong> (μιμηταὶ τοῦ θεοῦ, <em>mimētai</em>)—\"Imitators.\" A staggering command, immediately made bearable by what follows: <em>as dear children</em>.<br><br>Children imitate a parent they already belong to; the copying does not earn the place. Take away \"dear children\" and this verse crushes. Left in, it describes the most natural thing in a family.",

    '5:2': "<strong>And walk in love, as Christ also hath loved us, and hath given himself for us</strong>—Love is defined here, not assumed. Paul does not appeal to what we already mean by the word; he points at a death.<br><br>The sacrificial language — <em>a sweetsmelling savour</em> — is drawn from Leviticus. What the altar pictured for centuries turns out to have been a portrait of him, and it is now the pattern for ordinary Christian behaviour.",

    '5:3': "<strong>But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints</strong>—The reason given is <em>as becometh saints</em>: this does not suit who you are. Paul argues from identity, not from consequences.<br><br>\"Not once named\" is severe, but it is a standard for the community's speech rather than a rule about vocabulary. What a group finds amusing is what it will eventually permit.",

    '5:4': "<strong>Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks</strong>—The replacement offered is unexpected. Not silence, not solemnity, but <em>thanksgiving</em>.<br><br>Coarse talk and gratitude come from opposite places: one treats God's gifts as a joke, the other as a gift. Paul's remedy for bad speech is therefore not restraint but a different relationship to what you have been given.",

    '5:5': "<strong>No whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God</strong>—Covetousness is flatly identified as idolatry. The greedy man is not merely undisciplined; he is worshipping.<br><br>Paul is describing settled direction, not the believer's daily failures. The warning is real, and it is aimed at anyone who has made peace with what he claims to renounce.",

    '5:6': "<strong>Let no man deceive you with vain words: for because of these things cometh the wrath of God</strong>—Somebody was evidently arguing that it did not matter. Paul calls the argument <em>vain words</em> — empty, unable to bear weight.<br><br>Sin usually arrives with a vocabulary attached, a way of renaming itself that makes it sound safe. Watching the language is often the first place resistance becomes possible.",

    '5:8': "<strong>For ye were sometimes darkness, but now are ye light in the Lord: walk as children of light</strong>—Paul does not say you were <em>in</em> darkness but that you <em>were</em> darkness, and are now light. The change is of substance, not of surroundings.<br><br>And the command follows the description, never the reverse. Walk as what you are. The imperative is a conclusion drawn from an indicative, which is the shape of nearly every command in this letter.",

    '5:9': "<strong>For the fruit of the Spirit is in all goodness and righteousness and truth</strong>—<em>Fruit</em>, not produce or output. Fruit grows from a living thing; it is never manufactured, and it appears in its season.<br><br>That single word rules out a great deal of anxious effort. The question is not whether you can generate goodness but whether you are connected to the one who grows it.",

    '5:11': "<strong>And have no fellowship with the unfruitful works of darkness, but rather reprove them</strong>—Darkness is called <em>unfruitful</em>: it yields nothing. Paul's charge against sin here is not only that it is forbidden but that it is barren.<br><br>And the response is not merely avoidance but <em>reproof</em> — bringing into the open. The verb belongs with verse 13: light does its work by exposing.",

    '5:12': "<strong>For it is a shame even to speak of those things which are done of them in secret</strong>—Paul, who has just said to expose such works, declines to detail them. Exposure does not require fascination.<br><br>The secrecy is itself evidence. What must be hidden to continue has already been judged by the one hiding it, which is why the question \"would I do this if I were seen?\" is rarely an unfair one.",

    '5:13': "<strong>But all things that are reproved are made manifest by the light</strong>—Light does not argue; it shows. Its work is not to shame but to make things visible, and what is visible can at last be dealt with.<br><br>This is how God's law functions before it condemns: it tells the truth about what is there. And the gospel that follows can only heal what has first been brought out into the open.",

    '5:14': "<strong>Awake thou that sleepest, and arise from the dead, and Christ shall give thee light</strong>—Paul quotes what appears to be an early Christian hymn, likely sung at baptisms. The command is addressed to the dead, who cannot obey it.<br><br>Which is the point. The word that orders the dead to rise is the word that raises them. A promise is attached — <em>Christ shall give thee light</em> — and the promise is what makes the command possible.",

    '5:15': "<strong>See then that ye walk circumspectly, not as fools, but as wise</strong> (ἀκριβῶς περιπατεῖτε)—<em>Akribōs</em> means accurately, carefully, with attention. Not anxiously, but not on autopilot either.<br><br>Wisdom in Scripture is practical before it is theoretical: it concerns how a life is actually conducted. A man may hold sound doctrine and still walk carelessly, and Paul treats that as folly.",

    '5:16': "<strong>Redeeming the time, because the days are evil</strong> (ἐξαγοραζόμενοι τὸν καιρόν)—The verb is commercial: buying up, as one buys out a market. Time is treated as something to be purchased back at cost.<br><br>The reason given is bracing — <em>because the days are evil</em>. Not because life is short and precious in a sentimental sense, but because the age is hostile and the opportunities in it are limited.",

    '5:17': "<strong>Wherefore be ye not unwise, but understanding what the will of the Lord is</strong>—Paul assumes God's will is knowable, and that not knowing it is culpable rather than unfortunate.<br><br>Note where he does not send them: to signs, impressions or a hidden decree. The will of the Lord in this letter is what God has revealed — which is usually less mysterious and more demanding than the will people go looking for.",

    '5:18': "<strong>And be not drunk with wine, wherein is excess; but be filled with the Spirit</strong>—The two are set against each other because both concern what governs a person. The question is never whether you are influenced, only by what.<br><br>The verb is passive and continuous: be being filled. Not a single crisis to be achieved and remembered, but a state to be lived in — and, like drunkenness, visible to everyone else before it is obvious to you.",

    '5:19': "<strong>Speaking to yourselves in psalms and hymns and spiritual songs</strong>—The first result of being filled with the Spirit is not private ecstasy but singing to one another. Paul makes congregational song a form of mutual teaching.<br><br>Which is why what a church sings matters as much as what it hears preached. A hymn lodges where a sermon often does not, and people generally believe what they have sung for years.",

    '5:20': "<strong>Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ</strong>—\"Always\" and \"all things\" leave no exemption, which is easier to read than to do.<br><br>Note the qualifier: <em>in the name of our Lord Jesus Christ</em>. Thanks is not offered to a vague providence for circumstances as such, but to the Father through the Son, whose cross is the guarantee that the circumstances are not hostile.",

    '5:21': "<strong>Submitting yourselves one to another in the fear of God</strong> (ὑποτασσόμενοι ἀλλήλοις)—This sentence heads everything that follows about households. Whatever is said next, it is said under <em>one to another</em>.<br><br>Mutual submission was not a Greco-Roman household value; those tables ran one direction only. Paul sets the whole domestic order inside something that qualifies every station in it.",

    '5:22': "<strong>Wives, submit yourselves unto your own husbands, as unto the Lord</strong>—The Greek supplies no verb here; it borrows from verse 21, so this is the first instance of the mutual submission just commanded.<br><br>The qualifier <em>as unto the Lord</em> both dignifies and bounds it. What is rendered is rendered to Christ, which means it can never be owed to a husband against Christ — a limit this verse is often quoted without.",

    '5:23': "<strong>For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body</strong>—The definition of headship is supplied immediately, and it is <em>saviour of the body</em>.<br><br>Christ's headship is exercised by rescuing at his own cost. Any use of this verse to license self-interest has ignored the clause that defines the term it depends on.",

    '5:24': "<strong>Therefore as the church is subject unto Christ, so let the wives be to their own husbands in every thing</strong>—The pattern is the church's response to a head who died for her. That is the relationship being copied.<br><br>Paul is not describing a contest of wills settled by rank. He is describing a response to love already proven, which is the only thing that makes such a sentence bearable.",

    '5:25': "<strong>Husbands, love your wives, even as Christ also loved the church, and gave himself for it</strong>—The husband's command is the longer and the heavier, and it is not to rule but to die.<br><br>Greco-Roman household codes told husbands to manage. Paul tells them to spend themselves. Whatever authority this passage grants, it is defined entirely by a self-giving that leaves nothing in reserve.",

    '5:26': "<strong>That he might sanctify and cleanse it with the washing of water by the word</strong> (τῷ λουτρῷ τοῦ ὕδατος ἐν ῥήματι)—Water joined to the word: the language is baptismal, and the early church read it that way without hesitation.<br><br>Note who acts. Christ sanctifies, Christ cleanses. The church is passive throughout the sentence — washed, not self-washing — which is exactly what a sacrament is for.",

    '5:27': "<strong>That he might present it to himself a glorious church, not having spot, or wrinkle</strong>—The beauty is entirely Christ's doing. He presents the church to himself, having made her presentable.<br><br>This is where a discouraged Christian should look when the church, or his own life, appears anything but glorious. The condition described is a promise about the outcome, not a report on current progress.",

    '5:28': "<strong>So ought men to love their wives as their own bodies. He that loveth his wife loveth himself</strong>—The measure is not an ideal but an instinct: the automatic, unreflective attention everyone gives to his own body.<br><br>Paul's realism is worth noting. He does not ask husbands to summon a feeling they lack, but to redirect a care they already exercise constantly without being told.",

    '5:29': "<strong>For no man ever yet hated his own flesh; but nourisheth and cherisheth it, even as the Lord the church</strong>—<em>Nourish</em> and <em>cherish</em> are words for feeding and warming, the care given to an infant.<br><br>That is how Christ is said to treat his church: not managing it at a distance but feeding and warming it. And where he does that in practice is the word and the table — the ordinary means, not extraordinary experiences.",

    '5:30': "<strong>For we are members of his body, of his flesh, and of his bones</strong>—The phrasing echoes Adam's words over Eve. Paul is reaching for the closest union Scripture knows, and finding it insufficient.<br><br>This is not metaphor decorating a legal transaction. Justification is God's verdict, but it is a verdict spoken over people joined to Christ — the union is what makes his righteousness genuinely theirs.",

    '5:31': "<strong>For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh</strong>—Paul quotes Genesis 2 at the climax of an argument about Christ and the church, not in a discussion of marriage advice.<br><br>Marriage is therefore not a human arrangement later borrowed as illustration. It was built at the beginning to mean something, and what it meant was this.",

    '5:32': "<strong>This is a great mystery: but I speak concerning Christ and the church</strong> (τὸ μυστήριον τοῦτο μέγα ἐστίν)—Paul says plainly what he has been doing. The subject under discussion was never only marriage.<br><br>Which gives every Christian marriage a public significance its participants did not invent, and gives the unmarried the thing marriage was pointing at. The sign matters; the reality it signs matters more.",

    '5:33': "<strong>Nevertheless let every one of you in particular so love his wife even as himself; and the wife see that she reverence her husband</strong>—After the cosmic mystery, Paul returns abruptly to <em>every one of you in particular</em>.<br><br>That is the letter's method throughout. The largest truths land in the smallest places — how a man speaks to his wife on a Tuesday. Doctrine that never reaches that far has not yet been believed.",
})

NOTES.update({
    # ---- Chapter 6: household, armour, and farewell ----
    '6:1': "<strong>Children, obey your parents in the Lord: for this is right</strong>—Paul addresses the children directly, which assumes they are present when the letter is read. They are treated as members of the congregation, not as its future.<br><br>The qualifier <em>in the Lord</em> both grounds the obedience and bounds it. What is done is done before Christ, which is why no parent's authority can require what Christ forbids.",

    '6:2': "<strong>Honour thy father and mother; which is the first commandment with promise</strong>—Paul quotes the Fourth Commandment and treats the Decalogue as still binding on Christians, in a letter that has spent three chapters denying that works save.<br><br>There is no contradiction. The law cannot justify, but it has not stopped describing what love looks like. And <em>honour</em> reaches further than obedience: it outlives childhood.",

    '6:3': "<strong>That it may be well with thee, and thou mayest live long on the earth</strong>—The promise attached is ordinary and earthly: things generally go better in a household ordered this way.<br><br>It is a proverb, not a contract, and Scripture elsewhere is honest that the godly sometimes die young. God attaches blessing to his commands without turning obedience into a transaction he can be held to.",

    '6:4': "<strong>And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord</strong>—The father, who held nearly unlimited legal power over his household in Roman law, is the one restrained.<br><br>\"Provoke not\" names a real danger: authority exercised in a way that exasperates rather than forms. A child can be correctly disciplined and still be driven to anger by the manner of it.",

    '6:5': "<strong>Servants, be obedient to them that are your masters according to the flesh... as unto Christ</strong>—Paul addresses slaves as moral agents who can be spoken to, which the household codes of his world did not do.<br><br>He does not bless the institution; he qualifies it out of existence at the root by making both parties answerable to one Master. \"According to the flesh\" quietly limits every earthly ownership to the surface of things.",

    '6:7': "<strong>With good will doing service, as to the Lord, and not to men</strong> (μετ' εὐνοίας δουλεύοντες)—<em>Eunoia</em> is goodwill, a willing disposition. Paul commands not only the action but the spirit it is done in.<br><br>That seems impossible until you notice the reframing. Work done <em>as to the Lord</em> has a different audience, and a changed audience changes the attitude more reliably than resolve does.",

    '6:8': "<strong>Knowing that whatsoever good thing any man doeth, the same shall he receive of the Lord, whether he be bond or free</strong>—Nothing good is lost, and the accounting does not consult social rank.<br><br>For a slave whose work was invisible and uncredited, this is not an abstraction. The one who finally reckons is not the master, and he has overlooked nothing that was done for him.",

    '6:9': "<strong>And, ye masters, do the same things unto them, forbearing threatening</strong>—\"The same things\": the same goodwill, the same service as to the Lord. The duty is reciprocal, which upends the whole convention.<br><br>And the ground is that <em>your Master also is in heaven; neither is there respect of persons with him</em>. The man who gives orders stands in the same position before God as the man who takes them.",

    '6:10': "<strong>Finally, my brethren, be strong in the Lord, and in the power of his might</strong> (ἐνδυναμοῦσθε ἐν κυρίῳ)—The verb is passive: be strengthened. Even the command to be strong is a command to receive rather than to summon.<br><br>Paul has just finished with wives, children and slaves — the people with least power in that world. The strength offered is not a temperament some possess, but the Lord's, available to all of them.",

    '6:11': "<strong>Put on the whole armour of God, that ye may be able to stand against the wiles of the devil</strong> (τὴν πανοπλίαν τοῦ θεοῦ)—<em>Panoplia</em> is the full kit. The armour is God's own, lent rather than manufactured.<br><br>And the enemy is described by <em>wiles</em>, schemes, rather than raw force. What is chiefly to be feared is not assault but deception — which is why most of the pieces that follow are forms of truth.",

    '6:12': "<strong>For we wrestle not against flesh and blood, but against principalities, against powers</strong>—The person opposite you is not the opponent. Paul does not say human conflicts are illusory, only that they are never the whole account.<br><br>This is a profound relief and a serious warning at once. It frees you from treating people as enemies, and it forbids the comfortable idea that with better arrangements there would be no fight.",

    '6:13': "<strong>Wherefore take unto you the whole armour of God... and having done all, to stand</strong>—The objective named three times is to <em>stand</em>. Not to advance, not to win — the victory is Christ's and already given.<br><br>That is a modest and achievable aim for a hard day. The Christian is not asked to defeat the powers, only to still be standing on the ground Christ took when the evil day has passed.",

    '6:14': "<strong>Having your loins girt about with truth, and having on the breastplate of righteousness</strong>—The imagery is Isaiah's, where the armour belongs to God himself. What the Lord wore to save his people, he now issues to them.<br><br>The breastplate covers the heart, and the righteousness covering it is Christ's, not ours. A conscience defending itself with its own record is fighting in armour that will not hold.",

    '6:15': "<strong>And your feet shod with the preparation of the gospel of peace</strong>—A soldier's footing decided whether he kept his place. What gives the Christian footing is the gospel — and specifically the gospel <em>of peace</em>.<br><br>Peace with God is not the reward for standing firm; it is the ground you are standing on. Which is why assurance is not a luxury for settled people but equipment for the fight.",

    '6:16': "<strong>Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked</strong>—The <em>thyreos</em> was the full-length door-shaped shield, soaked in water before battle so flaming arrows died on it.<br><br>Faith is defensive here. It does not achieve, it receives and extinguishes — and what it quenches are accusations and lies, which is where the enemy's real weaponry lies.",

    '6:17': "<strong>And take the helmet of salvation, and the sword of the Spirit, which is the word of God</strong> (τὸ ῥῆμα θεοῦ)—One offensive weapon in the whole kit, and it is a word.<br><br>Salvation is worn on the head, protecting the thinking; the word is carried in the hand. Note that the sword is <em>the Spirit's</em>. It is not our cleverness with texts but God's own speech, which is why it must be known to be used.",

    '6:18': "<strong>Praying always with all prayer and supplication in the Spirit... for all saints</strong>—The armour passage does not end in combat imagery but in prayer, and prayer for other people.<br><br>This is how the whole thing is actually worn. Not as a technique to be applied, but as a life lived in dependence — and dependence that keeps turning outward to the saints rather than inward on itself.",

    '6:19': "<strong>And for me, that utterance may be given unto me, that I may open my mouth boldly</strong>—Paul, who has just written three chapters of the profoundest theology in Scripture, asks to be given words.<br><br>He does not ask for release. He asks for boldness in the place he is. What he wants from their prayers is not a change in his circumstances but faithfulness inside them.",

    '6:20': "<strong>For which I am an ambassador in bonds</strong> (πρεσβεύω ἐν ἁλύσει)—The phrase is a deliberate contradiction. An ambassador's person was inviolable; this one is in a chain.<br><br>Paul holds the office and the chain at once, and treats neither as cancelling the other. A limitation is not a disqualification. The commission stands wherever the commissioned man happens to be standing.",

    '6:21': "<strong>Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things</strong>—After the powers and the armour, a name. Paul ends this letter the way he ends most of them: with people.<br><br>Tychicus carries the letter and the news. The grandest theology in the New Testament reached Ephesus in the hands of a man most readers would never meet, and would not otherwise have heard of.",

    '6:23': "<strong>Peace be to the brethren, and love with faith, from God the Father and the Lord Jesus Christ</strong>—Every item is said to come <em>from</em> God: peace, love, faith. None of the three is presented as something the reader generates.<br><br>That is the letter in miniature. What is commanded throughout chapters 4 to 6 is first given in chapters 1 to 3, and named again here on the way out the door.",

    '6:24': "<strong>Grace be with all them that love our Lord Jesus Christ in sincerity. Amen.</strong> (ἐν ἀφθαρσίᾳ)—The last word is <em>incorruptibility</em>: a love that does not decay. The letter closes reaching past the present age.<br><br>It opened with grace (1:2) and closes with grace, and everything between — election, redemption, the one new man, the household, the armour — stands inside that frame. Grace is not the introduction to the letter's subject. It is the subject.",
})
